### ISSUE TITLE
Feature Request: Ability to send to bech32 native segwit addresses

### ISSUE THREAD

**Issue by bitschmidty** [bitpay/copay#10007]
Ive seen github issues for adding bech32 to the contact/address book. And I saw some issues regarding "segwit support". I did not see an issue here specifically just for supporting bech32 sending support.

Some services, [like Gemini](https://medium.com/gemini/gemini-upgrades-wallet-with-full-support-of-segwit-5bb8e4bc851b), are already implementing native segwit receive addresses _by default_. Others like BRD wallet and [Bitcoin Core](https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.18.0.md#planned-changes) plan to have bech32 receive addresses as the default in the future. 

Being that bech32 is becoming more common and even more common as a default address, it will be harder for me as time goes on to use Copay. While full segwit support may be more involved, I think send support is a smaller effort and will ensure my ability to transact using Copay with everyone else in Bitcoin.

Optech (disclosure, I contribute to Optech) has a good [resource page](https://bitcoinops.org/en/bech32-sending-support/) just for bech32 send support. Please reach out to me directly if you have any questions about this.

**Comment by bitschmidty** [comment]
Looks like release https://github.com/bitpay/copay/releases/tag/v6.1.0 closes this out

**Comment by matiu** [comment]
done.
