### ISSUE TITLE
Cannot import wallet

### ISSUE THREAD

**Issue by jorge1891** [bitpay/copay#10043]
I create a wallet on iPhone app 2 years aprox. I save my 12 words phrase and now with a restart of the phone I try to recovery my wallet without success. I’m sure words are ok ..message is could not access the wallet at the server and I don’t remember any encryption password 
Can you help me with this ? 
![5F125FAD-005E-4515-88BA-27DE479B6F2A](https://user-images.githubusercontent.com/53370395/61993951-384ab780-b04a-11e9-8b2c-c2beb34c5c17.jpeg)

**Comment by matiu** [comment]
Hi. Which version of Bitpay wallet are you using to import? Can you try
5.9.4 or 5.9.5?

**Comment by jorge1891** [comment]
I'm using 5.9.5 and capture is from this version.
thanks for the help

**Comment by BGalliotti** [comment]
Hello @jorge1891 

Please try creating a wallet specifying the recovery phrase, for that follow [these](https://github.com/bitpay/copay/issues/9916#issue-464712495) steps.

Kind regards.

**Comment by Derick7** [comment]
good day mr/ mrs am Derick, am having a serious issue with my copay account, I can not recover my funds in my old copay wallet,I mistakenly save 11 Recovery phrase at of 12 Recovery phrase, so I can’t get access to my bitcoin, please help me am going insane.Am going crazy

**Comment by johnjames333** [comment]
@jorge1891 
we have developed our own hardware for fixing BITCOIN recovery phrase with superfast speed
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333

**Comment by walletrescue** [comment]
@jorge1891 
could you import your old wallet?
If you didn't import it successfully send me message in Gmail I will help you recover your wallet  : anywalletrecovery@gmail.com

**Comment by jorge1891** [comment]
> Hello @jorge1891
> 
> Please try creating a wallet specifying the recovery phrase, for that follow [these](https://github.com/bitpay/copay/issues/9916#issue-464712495) steps.
> 
> Kind regards.

I did this and recover my wallet thank you very much!!!
