### ISSUE TITLE
Error at Confirm BADREQUEST when trying to send funds.

### ISSUE THREAD

**Issue by Antonios-P** [bitpay/copay#10046]
I tried today to send funds to my exchange account, but the app said ```Error at confirm /n BADREQUEST: Invalid proposal signature```. If it helps, I am trying to send 1500 BTCZ.  Any help is appreciated.

**Comment by matiu** [comment]
We dont support btcz.

**Comment by Antonios-P** [comment]
Wait, the app stores BTCZ, but it can't send? It is called ```MyBitcoinZWallet```.

**Comment by matiu** [comment]
You are on the wrong repo. Maybe there is a copy of our app. But we only
support btc and bch for the moment.

**Comment by Antonios-P** [comment]
One last comment, I clicked on help and support, and it took me here.
