### ISSUE TITLE
Insufficient funds

### ISSUE THREAD

**Issue by ghoti2011** [bitpay/copay#10053]
I have 2 btc in my wallet, i sent 1148$ , money never arrived to the receiver, transaction is not show  in history and rest of balance is not show also, i have balance 116$ when i should have 19,800$

**Comment by BGalliotti** [comment]
Hello @ghoti2011 

Please [refresh](https://github.com/bitpay/copay/issues/9886) your wallet.

Kind regards.

**Comment by walletrescue** [comment]
@ghoti2011 
did you recover your lost bitcoins if you didn't let me know in my email i can help to recover it
 : anywalletrecovery@gmail.com
