### ISSUE TITLE
Why is the major system failure not reported on your Twitter?

### ISSUE THREAD

**Issue by brainscar** [bitpay/copay#10058]
I called the number on the back of my BitPay debit card.

They said there are all kinds of issues right now:

- Double transactions
- Missing transactions
- Unable to add funds
- Unable to use cards

But when I check your support Twitter there isn't a single mention of it.

My account is suddenly negative. Even though I have funds on it.

None of my pending transactions are processed and I can't use my card.

What's the ETA on fixing this anyway?

https://twitter.com/BitPaySupport

**Comment by BGalliotti** [comment]
Hello @brainscar 

Thank you for reaching out to us.

Please write to the BitPay Customer Success team: https://help.bitpay.com/requestHelp

BitPay representatives can address your inquiry there.

We appreciate your patience.

Kind regards.
