### ISSUE TITLE
Could not initialize the app: External Wallets are no longer supported

### ISSUE THREAD

**Issue by Brayd0n** [bitpay/copay#10062]
I get this error when trying to open the Copay app on Windows 10. I have tried uninstalling and reinstalling the app but the issue persists. I am using multisig wallets but other people with the same setup are not having this issue. See the attached error message. Please let me know how to proceed. 

![image](https://user-images.githubusercontent.com/53536749/62236017-6fdb9b80-b38b-11e9-90c9-cc2af1b8540a.png)

**Comment by In-Bitcoin-We-Trust** [comment]
same problem on iOS

**Comment by matiu** [comment]
Hi,

Did you have a Trezor/Ledger wallet on Copay on the past?

Given you have backup of your wallets, Can you try to completely delete the app (even the app's data), install again and reimport your wallets?

**Comment by Brayd0n** [comment]
Yes, an older wallet was a multisig trezor wallet. 

After uninstalling and removing the app data, the new install of the app is working. Thanks for your help.
