### ISSUE TITLE
How to import BCH wallet on mobile now? 

### ISSUE THREAD

**Issue by insiderq** [bitpay/copay#10075]
Just importing the seed phrase shows me only BTC wallet. How do i specify that i want to import BCH wallet?

**Comment by gabrielbazan7** [comment]
Try with this: Add Wallet -> Import Wallet -> Show advanced options -> Specify derivation path -> choose BCH for the coin and m/44'/0'/0' for the derivation path. And of course, write down the recovery phrase.
