### ISSUE TITLE
Verschlüsseltes Passwort/Password recovery

### ISSUE THREAD

**Issue by Silvia72** [bitpay/copay#10073]
Ich möchte einem Freund von der wallet aus Bitcoins senden und werde nach einem verschlüsselten Passwort gefragt, dass ich nie eingerichtet habe. Was kann ich tun? 
Android Version 5.2.2

**Comment by gabrielbazan7** [comment]
Do you have the 12 words backup?

**Comment by johnjames333** [comment]
@Silvia72 
we have developed our own hardware for cracking BITCOIN wallet PASSWORDS with superfast speed
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333

**Comment by walletrescue** [comment]
@Silvia72 
If you have recovery phrase you can restore your wallet and set new password. i f you don't have recovery phrase I can crack your password. send me email I can solve your problem : anywalletrecovery@gmail.com
