### ISSUE TITLE
Billetera copay se cuelga buscando fondos

### ISSUE THREAD

**Issue by Juampa79** [bitpay/copay#10083]
Hola. Perdí mi celular y al querés recuperar la billetera de bitcóin en copay hago los pasos tal cual dicen. Ingreso las 12 palabras en un billetera nueva y empieza a buscar fondos. Me aparecen todos los movimientos pero sigue con el reloj y dice buscando fondos hace dos días está así. Y no los puedo usar.
Ayuda por favor!!
Gracias

**Comment by gabrielbazan7** [comment]
Hola. Podés subir una captura de pantalla para entender mejor el problema?. Pienso yo, tenes una propuesta de pago pendiente ( alguna transaccion que nunca se pudo enviar o si es una billetera compartida una transaccion que nunca llegó a la cantidad de firmas necesarias ) que esta bloqueando los fondos, simplemente eliminala

**Comment by Juampa79** [comment]
![BIT](https://user-images.githubusercontent.com/53802161/62654757-e43baf00-b936-11e9-8171-df96ceceac7a.jpeg)

Esos fueron mis movimientos. Como se ve en la imagen el ultimo hace año y medio

**Comment by gabrielbazan7** [comment]
Te recomiendo actualizar la aplicación. Podes hacerlo y decirme si el error persiste ?

**Comment by Juampa79** [comment]
No me figura ninguna actualización para la app. Tengo la version v5.5.0

**Comment by gabrielbazan7** [comment]
Copay para android la podes encontrar aquí https://github.com/bitpay/copay/releases/tag/v6.0.0 al final donde dice "assets" -> copay-6.0.0.apk.

**Comment by gabrielbazan7** [comment]
Otra posibilidad que tenes es buscar BitPay wallet en el playstore e importar usando las palabras en esa app.

**Comment by Juampa79** [comment]
Gracias Gabriel!!! Solucionado con la wallet bitpay. Muchas gracias!!!
