### ISSUE TITLE
several transactions not received

### ISSUE THREAD

**Issue by andykimpe** [bitpay/copay#10097]
several transactions not received

on my wallet and very bigmontant more

Transaction Receipt

Net Amount

0.03930778 BTC

Date-time: 05 Jul 2019 16:50:11

Status:Confirmed
Hide Details

Transaction ID: eac803b21557e3ef01ec16c1e9cabcd7786358762b0e45cbc163d98cfe05da6c

Transaction Fees: 0.0000928 BTC

Transaction Size: 225 bytes

Fee rate: 41.2 satoshi per bytes

Input

bc1qwe07p0gnuhvjymp0xtrd4uughch9rwzqskuc7q

0.039613 BTC

Output

bc1q4s73pwzulnmf5z9lhpnp0c4a38lr87pjt3yaaj

0.00021242 BTC

12heNUtAEYbVTAorxXvNoMrcU2MD5jnzzL

0.03930778 BTC

Transaction Receipt

Net Amount

0.0382603 BTC

Date-time: 04 Jul 2019 08:58:31

Status:Confirmed
Hide Details

Transaction ID: 76b4534f0767947a8a7e78451f891cd26774c2c7b8e323b7c8eb6873931328d6

Transaction Fees: 0.000132 BTC

Transaction Size: 248 bytes

Fee rate: 53.2 satoshi per bytes

Input

3HQycg1ZoT9Gk4Da6u6n2FxECZMDDJXk8t

0.0405589 BTC

Output

1NA4mktro8pKJ4r9G3KTaEo4Q69DmHGHDs

0.0382603 BTC

bc1qg35s6fwr2q875xpfngyw70g2nsdtyvgkkl978g

0.0021666 BTC

Transaction Receipt

Date-time: 05 Aug 2019 22:04:47

Status:Confirmed

Transaction ID: 358483ecce9559a55d5ec3fbedb555ec6c612efa36e18c58c098637c4343154c

Transaction Fees: 0.0000606 BTC

Transaction Size: 226 bytes

Fee rate: 26.8 satoshi per bytes

Input

bc1q3ce3rv80f083vcdadnkgke9u0yw45lfgar9nk4

0.00399617 BTC

Output

15yMHTmYN9uhgaNJn7c92Lozckbuo9Yfbj

0.00380727 BTC

bc1q87gn6thc60rpt7q56hy3h9nfle4fgu8utypqav

0.0001283 BTC

Thanks for doing what's needed

I already update the address on bitpay

but its still not showing up

**Comment by matiu** [comment]
Hi,

Checking your wallet, I see all the transactions on your wallet's history:

  [Fri Jul 05 2019 11:50:11 GMT-0300] eac803b21557e3ef01ec16c1e9cabcd7786358762b0e45cbc163d98cfe05da6c <= received 0.03930778 btc (80.00 sat/b) (5258 confirmations)

  [Thu Jul 04 2019 03:58:31 GMT-0300] 76b4534f0767947a8a7e78451f891cd26774c2c7b8e323b7c8eb6873931328d6 <= received 0.03826030 btc (94.96 sat/b) (5482 confirmations)

  [Mon Aug 05 2019 17:04:47 GMT-0300] 358483ecce9559a55d5ec3fbedb555ec6c612efa36e18c58c098637c4343154c <= received 0.00380727 btc (52.24 sat/b) (467 confirmations)

Can you please provide your wallet Id to check the wallet match? Also, try to "delete transaction history cache" from the advance's wallet settings.

**Comment by matiu** [comment]
PS: Please also let us know which version of the app are you using.

**Comment by andykimpe** [comment]
and how did I do I see no one by emptying the cache all I have is to analize the address for the bottom is all?

bitpay for windows 10 version 6.01

installed using microsoft store

I have a withdrawal yesterday of 200 €

but I have never had 800 € otherwise I would have them withdraw immediately away sivous look well there is no withdrawal that corespond to this amount

**Comment by andykimpe** [comment]
ok i found it's in transaction history but even emptying the cache does not change anything

**Comment by andykimpe** [comment]
apartment the transactions appear well in the history but are not credier on the balance

**Comment by andykimpe** [comment]
the only two withdrawal transaction to be sent that I perform on the ego of August are the following

0.019752 BTC
206 €

transaction id

31625454f54cbda2ea0f2fc406dd1401eb83d14243c4e8850311977f69fbe236

0.002 BTC
20 €

transaction id

24b98cfcaedea1d8538505327e8f5d99df74f18e9317d01fdae7f61ef99725da

there is no withdrawal transaction

and so no other transaction send

and yet monsolde and 0 BTC

**Comment by andykimpe** [comment]
is still a transaction not received

as of yesterday

transaction id:
8dc21d0e29d019b5ee0e83929e4debdce467d0a7b1eeaaad65897d3c68992c57


wallet id

d38e05ec-82a9-4997-8afb-ad9097bf6b6b

**Comment by BGalliotti** [comment]
Hello @andykimpe 

The transaction is showing up in your wallet;

```
  [Fri Aug 09 2019 04:02:49 GMT-0300] 8dc21d0e29d019b5ee0e83929e4debdce467d0a7b1eeaaad65897d3c68992c57 <= received 0.00113747 btc (2.15 sat/b) (1832 confirmations)
```

Are you still having issues with it?

We look forward to hearing from you.
