### ISSUE TITLE
Can't add or pay recipient - recipient has red X

### ISSUE THREAD

**Issue by Handust** [bitpay/copay#10095]
I have tried multiple times to send payment for an invoice, but CoPay will not allow me to add the recipient. Not from the Send screen, and not in the Address Book. Address is correct (scanned directly from invoice). Can anyone help me resolve this?

Thanks.

**Comment by louisacalvo** [comment]
Is there any other possibility to gain back the account if we lose our back up phrase. I haven’t activate my copay for more then a year. And now I’m ask to verify all over again. Please advice

**Comment by BGalliotti** [comment]
Hello @Handust 

- What version of CoPay are you using?
- Is it a BitPay invoice?
- Is the address a Segwit one?


We look forward to hearing from you.
