### ISSUE TITLE
Error: Transaction not available at this time

### ISSUE THREAD

**Issue by labe971** [bitpay/copay#10110]
Just sent a payment from my bitpay wallet and it show transaction not available at this time. Payment was sent an hour ago

**Comment by BGalliotti** [comment]
Hello @labe971 

Are you still experiencing an issue?

If so
- **Please send us the BitPay/Copay Wallet ID and the transaction hash / ID or the link so we can further investigate and address your inquiry.**

- To get your Wallet ID, open your Copay/BitPay application, then go to `Settings` > [Your wallet] > `More Options` > `Wallet Information`. 
On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste it in your e-mail. 
You can do the same on your computer by clicking on the wallet ID.

- The transaction hash / ID is a alphanumeric chain like this: **d0a23876de7cf87574b5cda7557bcc8af5d84f3fd1e6f4c6063fd6b72b0e69ae**

**We look forward to hearing from you.**

**Comment by labe971** [comment]
hello, funds are recredited to my wallet. My balance is correct now, I dont know what happened but it is resolved now. Thank you for your answre
