### ISSUE TITLE
Copay wallet withdrawal/balance fail

### ISSUE THREAD

**Issue by onizhnikov** [bitpay/copay#10129]
Hello! 
I have Copay wallet ID
68e68cdb-825a-4bcf-b4f9-fc6ef454da00

After making a transaction 0,61btc my balance became less on 1,1223btc but transaction didn’t even go to blockchain. 

What is the reason? And why is it a mistake in balance display? It seams like one of the addresses on which was deposit is not displayed?   

https://www.blockchain.com/ru/btc/address/1G6dnt6GsHmdgpYABVzzPtYKkfSNgw2S42

This transaction is not in my balance but is in deposits. 
 
Check my deposit/withdrawal history, please! And correct balance, please!

**Comment by mshanx** [comment]
Did you resolve this issue?

**Comment by chuklov** [comment]
Yes, it was resolved by itself.

**Comment by BGalliotti** [comment]
Hello @mshanx @chuklov @onizhnikov 
Sometimes during funds confirmations, it takes a while for the balance to get properly updated.
If you are experiencing any anomaly with the wallet, please wait until the funds are confirmed and 
[refresh](https://github.com/bitpay/copay/issues/9886) your wallet.

Kind regards.
