### ISSUE TITLE
problem with an operation

### ISSUE THREAD

**Issue by Galibo86** [bitpay/copay#10135]
hi
I had made an operation yesterday morning from my copay wallet to a another own wallet
I recived an email sayng " a paymant has been sent"  from wallet-service@bitcore.io 

However I dont recive de trx in my new wallet.
the link in the email ; see it on the blockchain"  returns "trx not found"
Smt could help my to see where is the trx? 

![Blockchain](https://user-images.githubusercontent.com/54897609/64259050-b8442700-cefe-11e9-95e3-7a4b904fbf35.jpg)

**Comment by BGalliotti** [comment]
Hello @Galibo86 

Do you know the amount of the transaction (in BTC or USD)?
Keep in mind the email states that you have sent funds,  not received (unless you sent funds to another wallet of your own).

- **Please send us the Copay/BitPay Wallet ID so we can further investigate and address your inquiry.**

For the Copay/BitPay app 6.0 or later:

To get your Wallet ID:
- Open the Copay/BitPay application
- Tap **Preferences** (top right icon)
- Within **Wallets (Grouped by key)** Select the wallet
- Within **Wallets using this key** Select the wallet
- Tap **Information**

On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste it in your e-mail. 
You can do the same on your computer by clicking on the wallet ID.

For earlier versions of the app:

To get your Wallet ID:
- Open the Copay/BitPay application
- Select the wallet
- Tap **Preferences** (top right icon)
- Scroll down and within **Advanced** tap **Information**

On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste it in your e-mail. 
You can do the same on your computer by clicking on the wallet ID.

**We look forward to hearing from you.**
