### ISSUE TITLE
Balance dissappeared from wallet interface but shown in blockchain

### ISSUE THREAD

**Issue by mshanx** [bitpay/copay#10139]
Hello,
I have an isssue with my iOS Copay wallet, version 6.21
I had balance of 0.01723311 BTC on my wallet address: 1Mq1vFfPAUbWmhgMADQi2W75uN9PieMWsL 
I received it in February and never transferred.
Today I have received another transaction of 0.24499183 BTC to the wallet address: 1Bt3DzNqqJE3wxJVNY5TgVmZ1v7stuyw9q
Both addresses are on the same wallet.

I tried to make test transfer of 0.0001 BTC to the wallet address 1Mtj5yVfRDNos6QQhoJhtH7jCDAKmcLSqi

First it kind of made the transation, signed it and redirected back to the wallet interface but there was no transaction shown and balance hasn't changed.

I created one more transaction, it was pending for some time and then redirected me back to the wallet interface.
There was a change in the balance, it blocked the entire balance of both addresses and showed new transaction. It's said that transaction was prepared but was not finalized. There was a "cloud" icon with the text "Send"(but in russian - Отправить) and an option in the bottom of that page like cancel the transaction.

I cancelled it and it unblocked the balance on the wallet, however, it unblocked 0.244991 BTC
The balance of 0.01723311 BTC from the wallet address 1Mq1vFfPAUbWmhgMADQi2W75uN9PieMWsL just disappeared.

When I entered the Settings and chose the wallet with these addresses it showed me like only one address has balance, this one: 1Bt3DzNqqJE3wxJVNY5TgVmZ1v7stuyw9q

And the other address is empty.

I checked in the blockchain and it's sayin that those itcoins are still on the address 1Mq1vFfPAUbWmhgMADQi2W75uN9PieMWsL but they don't show up in my wallet.

I tried to clear the transaction history cache, it didn't help. Used this thread: https://github.com/bitpay/copay/issues/9886

I made an import of this wallet to Bitpay wallet but still only 0.244991 BTC on the wallet address: 1Bt3DzNqqJE3wxJVNY5TgVmZ1v7stuyw9q is shown.

I don't know what's happened but bitcoins weren't transferred according to blockchain records.

I have more bitcoin on other wallet addresses and I'm afraid I can lose all of them.

Can you take a look asap, please? I want to receive back that balance of 0.01723311 BTC and I want to be sure I can safely use my funds on all my wallets.
![photo_2019-09-04_20-43-28](https://user-images.githubusercontent.com/43844066/64278163-c91f8780-cf54-11e9-856e-47cd8638f9b7.jpg)

**Comment by mshanx** [comment]
@BGalliotti Please help me with the issue.

**Comment by BGalliotti** [comment]
Hello @mshanx 

Bitpay support is attending your inquiry.

We will close this ticket.

Kind regards.
