### ISSUE TITLE
Balance Locked Wallet is Not Locked But Cannot Send Money 

### ISSUE THREAD

**Issue by elizbrown** [bitpay/copay#10132]
I transferred funds yesterday on the iPhone app and it says the funds are locked. My wallet is not locked. I can’t access the funds.

**Comment by BGalliotti** [comment]
Hello @elizbrown 

- **Please send us the Copay/BitPay Wallet ID so we can further investigate and address your inquiry.**

For the BitPay app 6.0 or later:

To get your Wallet ID:
- Open the Copay/BitPay application
- Tap **Preferences** (top right icon)
- Within **Wallets (Grouped by key)** Select the wallet
- Within **Wallets using this key** Select the wallet
- Tap **Information**

On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste it in your e-mail. 
You can do the same on your computer by clicking on the wallet ID.

For earlier versions of the app:

To get your Wallet ID:
- Open the Copay/BitPay application
- Select the wallet
- Tap **Preferences** (top right icon)
- Scroll down and within **Advanced** tap **Information**

On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste it in your e-mail. 
You can do the same on your computer by clicking on the wallet ID.

**We look forward to hearing from you.**
