### ISSUE TITLE
Transaction not credited 

### ISSUE THREAD

**Issue by hdsecurity** [bitpay/copay#10142]
I have the Copay V6.0.0 apk

Someone sent me 0.0046055 btc but the transaction didn't show up neither does my balance after many confirmations....

Wallet address : 1JQgTyQ3eibxjUcmeRjFrF6Qdh6Y2jC1vx

Tx hash: bef4a632213404f9140e9657a60602e0d30219b1

Wallet ID: 8cf2f8ea-3a4f-4195-8440-3c5a45609f25

Pls fix it so my wallet can be credited

**Comment by matiu** [comment]
Hi, we had a small delay with our blockchain synchronization process. it should be ok now.

https://insight.bitcore.io/#/BTC/mainnet/address/1JQgTyQ3eibxjUcmeRjFrF6Qdh6Y2jC1vx

sorry for the inconvenience.
