### ISSUE TITLE
Transaction not credited

### ISSUE THREAD

**Issue by helpfixthis** [bitpay/copay#10144]
I purchased bitcoin about an hour and a half ago. I still have not received my bitcoin in my copay wallet.

Please fix this issue.

Here is the information:
wallet address: 1L5153Z1wkfxX5HyEiE98mX918jWkQ8Qs

hash: 039b3e4985598a616cf0121f2f622b637ec9a5b5

**Comment by matiu** [comment]
Hi, we had a small delay with our blockchain synchronization process. it should be ok now.


https://insight.bitcore.io/#/BTC/mainnet/tx/6f67a6ef4dea6bb00a5549fc620d34efdfe4d29419fe5615ddf447596ba010b9

sorry for the inconvenience.
