### ISSUE TITLE
Can't Recover Amazon Gift card from wallet

### ISSUE THREAD

**Issue by richneiswon** [bitpay/copay#10145]
I have lost my Amazon gift card in my copay wallet, what are the steps and version of the software I need for Android 8 or HP Play Chromebook? I think I have the wallet bacup phrase but commonly do not see the gift card there from over 15 years ago. I inquired about this before here.

**Comment by BGalliotti** [comment]
Hello @richneiswon,

The gift cards are no longer available on Copay, if you want to purchase gift cards you might want to download [BitPay](https://play.google.com/store/apps/details?id=com.bitpay.wallet) which is practically the same app except for a couple of features.

The Copay/BitPay apps are not available as Chrome Apps. 
On Chromebook devices, it may work, however, we have received reports of users about issues on that platform so we recommend Android/iOS/Desktop instead.

Kind regards.

**Comment by miapharo** [comment]
Again who are these request from.?

**Comment by miapharo** [comment]
I hope non are thought to be me.i have never requested or enjoyed any bit coin or any perks as of yet....Nothing seriously!

**Comment by BGalliotti** [comment]
Hello @miapharo 

If you have any inquiries related to Copay please create a new issue specifying what your problem is.

Kind regards.
