### ISSUE TITLE
Two transactions not visible in my wallet

### ISSUE THREAD

**Issue by timpieee** [bitpay/copay#10143]
I sent two transactions (two hours inbetween) to my BitPay wallet and even tough they have been confirmed a while ago I still can't see them in my wallet nor has my wallet been updated?

I didn't have this issue yesterday as I sent money to my BitPay wallet with no issue.

**Comment by matiu** [comment]
Hi, we had a small delay with our blockchain synchronization process. it should be ok now.


sorry for the inconvenience.
