### ISSUE TITLE
rest of the wallet balance is gone after sending a portion of btc

### ISSUE THREAD

**Issue by jan8888** [bitpay/copay#10141]
I need help admins.
Sent a portion of my btc now the rest of my balance isnt showing up

**Comment by BGalliotti** [comment]
Hello @jan8888 

Your issue is related to a temporary synchronization delay we were experiencing and should be fine now.

Kind regards.

**Comment by walletrescue** [comment]
@jan8888 
did you get back your missing balance
if not contact me I can restore it for you: anywalletrecovery@gmail.com
