### ISSUE TITLE
I don't receive my btc in my Copay wallet

### ISSUE THREAD

**Issue by mromano1894** [bitpay/copay#10163]
Me enviaron 0,0738 BTC a mi billetera, pero no me aparece el saldo ni la operación en Copay. Ya revise varias veces la dirección y esta correcta y la transacción aparece en el bloque y ya tiene 4 confirmaciones de momento.

Alguien sabe que hacer para que aparezca en mi wallet?

Gracias!

**Comment by mromano1894** [comment]
ENGLISH:

I have been sent to my wallet 0,0738 BTC, but I do not see the balance or the operation in the Copay app.

I have already checked the address several times and it is correct. And the transaction appears in the block also correctly and already has 4 confirmations at the moment.

The address is 144otnkJLB1ov3yrVJC13n6YpEJMCssTBK

Anyone know what to do to make it appear in my wallet?

Thank you!

**Comment by mrgilbbs** [comment]
I am experiencing same issue I made a transaction from my copay wallet .initially I had 5165usd on my wallet and I sent out 4120.89usd about an hour ago. I can’t find the transaction history and my balance is showing  5usd. The transaction history is not showing anywhere please I need a rapid response

This is my wallet address below please I need this to be sorted out 1ACLCamuCfmkzLHTVPcPbmQPxxDBaho3iF

**Comment by micahriggan** [comment]
We experienced an outage, is this issue still occurring?

**Comment by mromano1894** [comment]
Yes, my btc suddenly appeared in the wallet
