### ISSUE TITLE
Import Wallet option missing?

### ISSUE THREAD

**Issue by shaun-ba** [bitpay/copay#10165]
Where has this gone, nowhere in 6.3.3 can I see this option? 

Using Linux.

**Comment by mythril** [comment]
Same here, I was just about to create this post myself.

**Comment by gabrielbazan7** [comment]
Yes. Fixed here #10161. Workaround: Create a new wallet -> Settings -> switch on "Support wallets with different keys" -> go back to settings -> generate a new key -> import

Sorry about that

**Comment by shaun-ba** [comment]
@gabrielbazan7 Didn't help that on the same day there was a bug on Android that was fixed in 6.3.3 but Play Store didn't verify it for some days! Basically couldn't access any funds for 3-4 days.

**Comment by BGalliotti** [comment]
Hello @shaun-ba 

Are you still experiencing an issue?

We look forward to hearing from you.

**Comment by shaun-ba** [comment]
@BGalliotti I had used the workaround so not sure if it is fixed now for other users.

**Comment by BGalliotti** [comment]
Hello @shaun-ba 

Good, thanks, it is fixed :)

Kind regards.
