### ISSUE TITLE
Release artifacts of 6.3.0 are non existent

### ISSUE THREAD

**Issue by AeonLucid** [bitpay/copay#10160]
Version 6.2.3 has the "Fetching payment information" bug which apparently has been fixed since 6.3.0.
However it's impossible to find a download of 6.3.0.

BitPay advertising version 6.3.0:
- https://twitter.com/BitPay/status/1173699571547029505
- https://twitter.com/BitPay/status/1173277328694288384
- https://twitter.com/BitPay/status/1173699719438225409

Reviews having the same issue:
- https://play.google.com/store/apps/details?id=com.bitpay.wallet&hl=en_GB&reviewId=gp%3AAOqpTOGPLauBKdNk4oWQ9pdbNL0fp9lV-EITltkPSZfIod8sIbdV5Ck-c-3IWRFK2CklFfFlpu8HPFoDq8KT0A
- https://play.google.com/store/apps/details?id=com.bitpay.wallet&hl=en_GB&reviewId=gp%3AAOqpTOE0AKysUV2gUAK0I5RjlXXymamMDKyvOcQOlA8szF3y1Ffd3hVmuCWJwNN63p6z960tmWBkyck8aMrxRw

Latest version on play store: 6.2.3 (11 sept)
Latest version on ios appstore: 6.2.3 (11 sept)

**Comment by BGalliotti** [comment]
Hello @AeonLucid 

**A fixed version of the app has been already released (6.3.3) and it's pending approval on the Google Play Store, it should be available soon (likely later today).**

In the meantime, please try to use another device that does not use Android 9 (Computer, iPhone, iPad).

Kind regards.
