### ISSUE TITLE
Mnemonic not valid

### ISSUE THREAD

**Issue by Tony1424** [bitpay/copay#10173]
Hi support,
I'm using copay on November 2018 with iOS and now my iPhone have to reset to factory setting so I reinstall copay with the newest version 6.3.3 and try to use 12 phrase to recover my wallet but it keep show me error bwc.errorINVALID_BACKUP : invalid backup. 
I'm confirm that my 12 phrase is in correct order 
I use all lower case and no punctuation 
I didn't add password to my recovery phrase
I don't have QR code or text file backup
I separated each word with one space.
So please help me find the way to recover my wallet. 

Thank you

**Comment by BGalliotti** [comment]
Hello @Tony1424 

You must be entering some word wrongly.

Please also ensure that your words are all contained in the following list of possible words:
https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt
For other languages click [here](https://github.com/bitcoin/bips/blob/master/bip-0039). 


**Note for Spanish speakers**: **Spanish** words sometimes include acute, be sure to spell all the words correctly.

Kind regards.

**Comment by Tony1424** [comment]
Hello @BGalliotti 
I'm double check already all word correct. Still can't recover my wallet. 
do you have other solution?

**Comment by BGalliotti** [comment]
Hello @Tony1424 

On my experience every time this happens, the user is entering something wrong, I would encourage you to make sure that is not the case.

Make sure all the words and the phrase is correct [here](https://iancoleman.io/bip39/).

There is no other solution.

Kind regards.

**Comment by johnjames333** [comment]
@Tony1424 
we have developed our own hardware for fixing BITCOIN recovery phrase with superfast speed
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333

**Comment by walletrescue** [comment]
@Tony1424 
did you manage to import you mnemonics
if you didn't, send a message to me I can help you as I have solved many similar issues for my customers gmail : anywalletrecovery@gmail.com

**Comment by richardsuns** [comment]
@Tony1424 
did you recover your wallet?
I a powerful machine that looks for errors in recovery phrase and corrects the errors and restores the wallet.
it can correct up to 10 typos in phrase and can find up to 4 missing words from phrase
