### ISSUE TITLE
No puedo recuperar billetera

### ISSUE THREAD

**Issue by sergioch100** [bitpay/copay#10181]
Buenas noches, 

Quisiera saber como puedo recuperar mi billetera en la plataforma bitpay ya que el cifrado se me olvido, y tengo las 12 frases con la que di apertura a la cuenta pero no me deja restablecerla, hay alguna solucion 
muchas Gracias

**Comment by BGalliotti** [comment]
Hola @sergioch100 
Gracias por ponerse en contacto con nosotros.

Puede recuperar su billetera importando la misma con la frase de recuperación de doce palabras.


Por favor, háganos saber si tiene alguna pregunta adicional.
Saludos cordiales.

**Comment by sergioch100** [comment]
pero la frase no me funciona me sale error, y tengo pantallazos de las frases

**Comment by BGalliotti** [comment]
Hola @sergioch100 

- Cuál es el error que obtiene?
Puede que no esté relacionado con la frase.

Tiene que estar ingresando alguna palabra incorrectamente.
Recuerde que en Español si las palabras llevan acento, de escribirlas con acento.

Saludos cordiales.

**Comment by sergioch100** [comment]
gracias faltaban las tildes...
