### ISSUE TITLE
Wallet creating failed, key alrdy used by existing wallet

### ISSUE THREAD

**Issue by Riversen21** [bitpay/copay#10187]
Hi,

i got a new pc and wanted to install copay on the new one and start with my wallet....but when i use my phrase it says key has alrdy been used by an existing wallet. So i deleted Copay from my old PC and still same problem.

**Comment by BGalliotti** [comment]
Hello @Riversen21 

You might be trying to create a wallet that already exists. 
Please import the wallet instead.

Kind regards.

**Comment by Riversen21** [comment]
Ok done thank you....the import was there but no phrase option for last days....now its back
