### ISSUE TITLE
scanner in Copay AP not working 

### ISSUE THREAD

**Issue by KathyWStC** [bitpay/copay#10180]
Scanner in Copay AP not working, how can I get this working please.

**Comment by BGalliotti** [comment]
Hello @KathyWStC 

- What version of copay are you using?
- What are you scanning? (a regular QR code, a BitPay invoice, an exported wallet..)




Kind regards.

**Comment by Cristhian1325** [comment]
Hello

**Comment by Cristhian1325** [comment]
#10073
