### ISSUE TITLE
Trying to recover wallet from passphrase

### ISSUE THREAD

**Issue by metoro** [bitpay/copay#10195]
The new version of the CoPay wallet only has one restore option - 'Get Started' / Import

However, when specifying the 12-word recovery phrase from previous CoPay app installation, one is presented with the error "Could not access the wallet at the server"

The phone (iPhone 11) is online. The passphrase is correct. There is no password. Derivation path is the same. There is no reason for this error. 

Please address urgently.

**Comment by BGalliotti** [comment]
Hello @metoro 

- What version of the app are you using?
- Are you having any connectivity issues? 
- Are you residing in any cryptocurrency banned country?

**Comment by metoro** [comment]
Version: Latest / v6.3.3
Connectivity issues :  None
Banned country :   No  (Mexico)

**Comment by BGalliotti** [comment]
Hello @metoro 

Please try creating the wallet and specifying the recovery phrase (instead of importing)

Kind regards.

**Comment by metoro** [comment]
@BGalliotti there does not appear to be any route to do that (at least, not anymore) 

Get Started -> Create -> Set Password -> Wallet is created (new virgin wallet)

There is no option to specify a recovery phrase in this flow.

**Comment by BGalliotti** [comment]
Hello @metoro 

Thanks for your reply.

Please do the following:

1) As you have no wallets at all in the app (if you have a wallet skip this step), click **Get started** > Select the currency > Enter a name for the wallet > click **CREATE** 

2) Then click the gear icon (top-right corner), go to **Advanced** and enable the second toggle (support for multiple keys) and go back.

3) Now within **Keys** click **+ Generate new key** > **Import wallet** > enter the recovery phrase and click **IMPORT**

You can delete the first wallet you have created if you wish to, for that click the gear icon > within **Keys** click **group 1** > Click **Delete** > Click **Delete** and confirm.

Kind regards.

**Comment by metoro** [comment]
@BGalliotti Thanks, but I followed these steps, entered the recovery phrase, and just got the same error.

**Comment by metoro** [comment]
Also note - the flow for step #1 is not how you say. It goes:

click Get started > Select the currency > click CREATE (alternative is import existing) > Set password (I am not setting one)

i.e. there is no 'Enter name for wallet' step

**Comment by BGalliotti** [comment]
Hello @metoro 

I have mistaken the steps, just changed them, please check the previous post.
Kind regards.

**Comment by metoro** [comment]
Hi @BGalliotti 
I tried this (convoluted, isn't it?)... made a new wallet from a key generated from the seed phrase as per your steps. However, although the wallet was created, it does not show the balance.

**Comment by metoro** [comment]
Also of note, I tried scanning the QR from the Export wallet section of the CoPay s/w running on my other device, and the new wallet complains that a password must be given, but there is no password on the source wallet. Could these two problems be connected?

**Comment by BGalliotti** [comment]
Hello @metoro 

> I tried this (convoluted, isn't it?)... made a new wallet from a key generated from the seed phrase as per your steps. However, although the wallet was created, it does not show the balance.

Please post your wallet ID so we can check its funds, it may simply have no funds.

> Also of note, I tried scanning the QR from the Export wallet section of the CoPay s/w running on my other device, and the new wallet complains that a password must be given, but there is no password on the source wallet. Could these two problems be connected?

No. The **Export** differently to previous versions of the wallet, exports the private key in an encrypted format (not the recovery phrase) that is why it requires the user to enter a password. It is not an existing password, is the password that will be used to encrypt the wallet.


Kind regards.

**Comment by metoro** [comment]
@BGalliotti I'd rather not post the wallet ID here, but I can assure you the wallet has funds, which clearly show in the balance of the original device.

**Comment by BGalliotti** [comment]
Hello @metoro 

Please [refresh](https://github.com/bitpay/copay/issues/9886) all your wallets.

Kind regards.

**Comment by metoro** [comment]
No joy, @BGalliotti , I did both a cache clear and an address scan and the balance still reads 0.

**Comment by bknght0911** [comment]
I'm trying to put all coins in one wallet,  how do I do that

**Comment by muzafa-popo** [comment]
note
wait i want to create

**Comment by muzafa-popo** [comment]
hi,

i already create but panding to varify
below myblockchain address, if can user for tranfer.If not,need awaiting
after verify identity

**Comment by BGalliotti** [comment]
Hello @muzafa-popo 






Kind regards.

**Comment by Prospyyy** [comment]
Hi
same problem. 
The phrase does not work either in the wallet (old version) or in the recovery tool (https://bitpay.github.io/copay-recovery/)

**Comment by Prospyyy** [comment]
same problem. The phrase does not work either in the wallet (old version) or in the recovery tool (https://bitpay.github.io/copay-recovery/)

**Comment by BGalliotti** [comment]
Hello @Prospyyy 

Please refer to #10330 

Kind regards.

**Comment by couby1master** [comment]
🏴⚜🏴⚜

**Comment by johnjames333** [comment]
@metoro 
@Prospyyy 

we have developed our own hardware for fixing BITCOIN recovery phrase with superfast speed
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333

**Comment by Travis2022** [comment]
@Prospyyy
@muzafa-popo 
@metoro 

I can solve this issue, if you haven't still imported your wallet talk to me I can help recover it : : anywalletrecovery@gmail.com
