### ISSUE TITLE
Copay app won’t work

### ISSUE THREAD

**Issue by Teruah1** [bitpay/copay#10228]
Copay app lost my bitcoin and now wont open at all!!!  I need to get my bitcoin using pass phrase

**Comment by Schmadeke1** [comment]
I also lost my bitcoin   I tried to send money to via blockchain to 5Dimes.com. I tried to sent part of it and it all disappeared. My history shows bitcoin going in but no history of anything going out. It just now says I have no bitcoin in my wallet. This is crazy.

**Comment by BGalliotti** [comment]
Hello @Schmadeke1 

Thank you for reaching out to us.

Please write to the BitPay Customer Success team: https://help.bitpay.com/requestHelp

Our representatives can address your inquiry there.

We appreciate your patience.

Kind regards.

**Comment by walletrescue** [comment]
@Schmadeke1
 if this issue is still without I may recover your fund for you. just send me a message
gmail : anywalletrecovery@gmail.com
