### ISSUE TITLE
Cash out

### ISSUE THREAD

**Issue by Teruah1** [bitpay/copay#10229]
I want to cash out and have the money in my wallet sent to me

**Comment by BGalliotti** [comment]
Hello @Teruah1 

To cash your money out you can sell your Bitcoin through an exchange, like [Coinbase](www.coinbase.com).

The procedure looks pretty much like this:
(you need to have an exchange account and a bank account set up)

- Send the bitcoin to the exchange
- Sell the bitcoin in the exchange
- Send the funds to the bank account

Kind regards.
