### ISSUE TITLE
Still says receiving

### ISSUE THREAD

**Issue by helpfixthis** [bitpay/copay#10230]
I purchased bitcoin an hour ago. On the copay wallet, it still says receiving. I do not think its the mining system. Is something wrong with the app right now?

**Comment by BGalliotti** [comment]
Hello @helpfixthis 

Transactions take time to get confirmed.
If the transaction was confirmed in the blockchain and was not showing up in your wallet, 
please [refresh](https://github.com/bitpay/copay/issues/9886) your wallet.

Kind regards.
