### ISSUE TITLE
Missing parameter Email

### ISSUE THREAD

**Issue by Gubat111** [bitpay/copay#10255]
I wanted to redeem my BitCoin for Amazon money but it says that the parameter "email" is missing.
Where do I enter my information?

**Comment by BGalliotti** [comment]
Hello @Gubat111 

Please make sure your app is up to date, if you are using Copay, then it is not, to purchase gift cards please use [BitPay](https://play.google.com/store/apps/details?id=com.bitpay.wallet).

Kind regards.
