### ISSUE TITLE
Copay crashes (iPhone Xs Max)

### ISSUE THREAD

**Issue by realdistoast** [bitpay/copay#10267]
Hi.

My Copay is crashing upon opening the app. It first shows the Copay name and dark blue background, then it switches to a white background and then the app immediately crashes. 

I have wallets in my app, but I forgot the seed for one of them. I'd prefer not to delete the app and reinstall. I'm wondering if you can push an update and if my wallets are okay. I'm worried.

**Comment by realdistoast** [comment]
I also tried shutting off and then turning on my phone and that didn't fix the issue.

**Comment by BGalliotti** [comment]
Hello @realdistoast 

Does [this](https://www.ikream.com/2019/10/how-to-fix-apple-iphone-xr-apps-that-keep-freezing-closing-randomly-troubleshooting-guide-30254) apply to your problem?

It seems to be an iPhone problem, not an issue of our app, reason why we do not think an update should fix that.

Kind regards.
