### ISSUE TITLE
Copay wallet says "Error address has missmatched network type"

### ISSUE THREAD

**Issue by Elenjnjatrader** [bitpay/copay#10269]
Copay wallet says "Error address has missmatched network type"

I am not able to move my btc to another copay wallet or to another external wallet.

Your help would be greatly appreciated.

Thank you

Elninjatrader

**Comment by matiu** [comment]
Sorry for the problems you are having.

Can you tell us the version of the app you are using?

Also, could you please let us know when exactly the problem happens? 

thanks.

**Comment by Elenjnjatrader** [comment]
I put the seed into a mycelium wallet and then was able to move my btc out. It's actually a faster wallet than copay

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by mbunal** [comment]
i have same error too.
os: android 8.0.0
copay: v5.3.1 commit hash: #fbd2380

**Comment by mbunal** [comment]
i found copay 7.0.3 for android on sf. can i install copay from sf? can i trust it? is it safe to use?
https://sourceforge.net/projects/copay.mirror/files/v7.0.3/

**Comment by hoem1** [comment]
I have the same problem... copay version 3.9.1 android

**Comment by mbunal** [comment]
i found 7.0.3 on github.
https://github.com/bitpay/copay/releases/tag/v7.0.3
i think i can use it safely... and there is no such that problem too.

**Comment by Elpensad** [comment]
Same problem here since the 26th last week. version Version 3.15.2 (3.15.2) macosx. 

Please **admin/moderator** fix it, I would like to keep using this version of Copay and not have to be forced to upgrade. Thank you in advance!

**Comment by davidpenalosa** [comment]
Buenas tardes. También entre a hacer una transacción en mi billetera copay con cuentas internas de una a la otra y me salió errores dirección no coincide con el tipo de red, ahora me aparece balance total bloqueado y tampoco me deja mandar a otra billetera externa, tengo la versión 5.3.1 y Android 7.0 . Que hago esos fondos eran mis ahorros, nesecito disponer de ellos . Por favor me contestan. Gracias

**Comment by couby1master** [comment]
https://t.me/couby1master

**Comment by BGalliotti** [comment]
Hello @davidpenalosa @Elpensad 

The solution is to update the app. 
Some changes have affected old versions of the app, that issue may be solved in the future or not.
If you are using the BitPay wallet on your mobile device, please update the wallet application in the [App Store (iOS)](https://itunes.apple.com/us/app/bitpay-secure-bitcoin-wallet/id1149581638) or [Google Play Store (Android)](https://play.google.com/store/apps/details?id=com.bitpay.wallet).

If you are using the wallet on a Windows computer, you can download the most recent version of the BitPay wallet [here](https://www.microsoft.com/en-us/p/bitpay-for-windows/9nbr15sk4zjv?rtc=1&activetab=pivot:overviewtab).

If you are using the wallet on a Mac computer, you can download the most recent version of the BitPay wallet [here](https://itunes.apple.com/us/app/bitpay/id1440200291?ls=1&mt=12).

If you are using Linux, you can download the most recent version of the BitPay Wallet [here](https://snapcraft.io/bitpay).

Please note that the wallet in the older legacy (Windows/Mac OS/Linux) versions will have to first be [backed up](https://www.youtube.com/watch?v=U23E-dZEuYs) and then imported to the newest version of the BitPay App.

Kind regards.

**Comment by BGalliotti** [comment]
Hola @davidpenalosa 

> Buenas tardes. También entre a hacer una transacción en mi billetera copay con cuentas internas de una a la otra y me salió errores dirección no coincide con el tipo de red, ahora me aparece balance total bloqueado y tampoco me deja mandar a otra billetera externa, tengo la versión 5.3.1 y Android 7.0 . Que hago esos fondos eran mis ahorros, nesecito disponer de ellos . Por favor me contestan. Gracias

Sus fondos están seguros. 
Puede optar por:

- Actualizar la app
- Instalar la app en otro dispositivo e importar sus billeteras
- Instalar otra app e importar sus billeteras
- Recuperar los fondos con la Recovery Tool y moverlos a una billetera en otra app

Para importar las billeteras, es necesario contar con la frase de doce palabras.



Por favor, háganos saber si tiene alguna pregunta adicional.
Saludos cordiales.

**Comment by Elpensad** [comment]
Hi I ve been trying for some weeks to make some BHC transactions but an
error appears that didn't no long ago:
*500 - "min relay fee no met (code 66)"*

I tried with no success to change the miner fee, any suggestions and
assistance will be greatly appreciated.

Thanks in advance,
Saba

PS:I enclose an image
