### ISSUE TITLE
Copay "Error address has must matched network type" 

### ISSUE THREAD

**Issue by Elenjnjatrader** [bitpay/copay#10268]
Copay wallet says "Error address has missmatched network type"

I am not able to move my btc to another copay wallet or to another external wallet. 

Your help would be greatly appreciated. 

Thank you 

Elninjatrader

**Comment by matiu** [comment]
Hi


I would like to help you with this issue.

Can you please send yiu walletId to matias@bitpay.com so I can inverstigate
further?

Also cousl you please describe exactly when the error ocurrs?

Matiss

**Comment by unortodoxsolutions** [comment]
> Hi I would like to help you with this issue. What version of Copay are you using? What is your device and OS? Also could you please describe exactly when the error occurs? Matias

I am having the same error I get the error on the confirm transactions page

**Comment by unortodoxsolutions** [comment]
![photo_2019-10-30_13-59-06](https://user-images.githubusercontent.com/35502347/67890005-423af580-fb26-11e9-940d-1ebe5f7f1b9d.jpg)

**Comment by mbunal** [comment]
i have same error too.
os: android 8.0.0
copay: v5.3.1 commit hash: #fbd2380

**Comment by mbunal** [comment]
i found copay 7.0.3 for android on sf. can i install copay from sf? can i trust it? is it safe to use?
https://sourceforge.net/projects/copay.mirror/files/v7.0.3/

**Comment by mbunal** [comment]
i found 7.0.3 on github.
https://github.com/bitpay/copay/releases/tag/v7.0.3
i think i can use it safely... and there is no such that problem too.

**Comment by BGalliotti** [comment]
Hello @mbunal @Elenjnjatrader @unortodoxsolutions 

Please update Copay to the [latest version available](https://github.com/bitpay/copay/releases/tag/v7.0.3).

Kind regards.
