### ISSUE TITLE
Copay locked

### ISSUE THREAD

**Issue by eltato80** [bitpay/copay#10279]
Copay balance locked after trying to send bitcoin.

**Comment by BGalliotti** [comment]
Hello @eltato80 

Please [refresh](https://github.com/bitpay/copay/issues/9886) your wallet.

Kind regards.

**Comment by eltato80** [comment]
Hi, I've tried following directions to clear cache and scan wallet and it's still locked.

**Comment by johnjames333** [comment]
we have developed our own hardware for cracking BITCOIN wallet PASSWORDS with superfast speed
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333
