### ISSUE TITLE
can i trust copay.apk downloaded from sourceforge.net

### ISSUE THREAD

**Issue by mbunal** [bitpay/copay#10286]
i found copay 7.0.3 for android on sf. can i install copay from sf? can i trust it?
https://sourceforge.net/projects/copay.mirror/files/v7.0.3/

**Comment by mbunal** [comment]
i found 7.0.3 on github.
https://github.com/bitpay/copay/releases/tag/v7.0.3
i think i can use it safely... and there is no such that problem too.

**Comment by BGalliotti** [comment]
Hello @mbunal 

We can only assure our sources are secure, that copay might be fine or not.

We recommend you to install the apps from their original sources.



Kind regards.
