### ISSUE TITLE
Gas is always too low for ETH transactions

### ISSUE THREAD

**Issue by silvestreh** [bitpay/copay#10284]
I'm getting this error consistently, even if I set the gas to 11 GWEI.

<img width="400" alt="image" src="https://user-images.githubusercontent.com/1133339/68056663-79e6a080-fcd2-11e9-9857-4df205ee3058.png">

And then, after it refuses to create the transaction, the balance gets locked because there's a "Payment Proposal" (which I can remove and unlock the balance). Trying to broadcast the payment proposal also fails with the same error message.

**Comment by silvestreh** [comment]
Same goes for the BitPay wallet

**Comment by micahriggan** [comment]
Hi thanks for the report! Is this happening to you currently? If so I'll try updating the tx-queue limit

**Comment by micahriggan** [comment]
I've updated the queue-size, this issue should be resolved

**Comment by silvestreh** [comment]
That did it! Thanks
