### ISSUE TITLE
How do I find  my bitcoin address 

### ISSUE THREAD

**Issue by Bitcoin678** [bitpay/copay#10287]

**Comment by Bitcoin678** [comment]
I Need My Bitcoin or Else...

**Comment by BGalliotti** [comment]
Hello @Bitcoin678 

To see your Bitcoin address:
1. Click on the wallet you wish to receive funds into and select  **Receive** at the bottom.
2. Use the Bitcoin or Bitcoin Cash address displayed there to receive Bitcoin or Bitcoin Cash transactions. You can click on the QR Code/displayed address to copy it to the clipboard for pasting.

[Check out this video for reference on how to send/receive transactions from the Copay/BitPay wallet](https://www.youtube.com/watch?v=jctgoHSwPM0).

Kind regards.
