### ISSUE TITLE
unavailable funds 

### ISSUE THREAD

**Issue by wallothet** [bitpay/copay#10288]
I have a significant portion of my wallet unavailable to be used, however I deposited these funds back in August from another wallet. Why aren’t they available and when will they be? Are only a limited amount of funds available at a given time?

**Comment by matiu** [comment]
Hello,

 Can you please let us know what you mean by unavailable? What you exactly you see on the balance of your wallet? Are all the incoming transactions of your wallet confirmed?

**Comment by wallothet** [comment]
Hello, 

I apologize as the issue seems to have resolved itself (not entirely sure how but I’m happy either way). Thank you for your time.
