### ISSUE TITLE
Copay

### ISSUE THREAD

**Issue by tcross0621** [bitpay/copay#10282]
How do you get support for copay? Is there a support site ?

**Comment by BGalliotti** [comment]
Hello @tcross0621 

You can get support here, what do you need support with?

We look forward to hearing from you.
Kind regards.

**Comment by tcross0621** [comment]
Yes I sent money to an address that did not receive it. I’m trying to rectify it on their end but no luck so far. Is there a way to reverse the payment?

**Comment by BGalliotti** [comment]
Hello @tcross0621 

The payment cannot be reversed.

Cryptocurrency transactions are not [reversible](https://support.bitpay.com/hc/en-us/articles/115003028706-Can-I-reverse-a-transaction-from-my-BitPay-wallet-), there is nothing to do to recover funds already broadcast to the blockchain or roll-back the operation.
As a recommendation, next time please double check the destination address before sending the funds.

Kind regards.

**Comment by Schmadeke1** [comment]
I don’t understand, my Copay shows zero coins there but I put in $325 worth of bitcoin. I tried to send the money to five dimes.com it did not go to them, but it does not show where anything went my history shows a deposit not a withdrawal

**Comment by BGalliotti** [comment]
Hello @Schmadeke1 

Thank you for reaching out to us.

Please write to the BitPay Customer Success team: https://help.bitpay.com/requestHelp
providing the wallet ID.

Theur representatives can address your inquiry there.

We appreciate your patience.

Kind regards.
