### ISSUE TITLE
my copay ETH wallet lost and i can't add my ETHwallet

### ISSUE THREAD

**Issue by lswook7** [bitpay/copay#10299]
![2019-11-08](https://user-images.githubusercontent.com/57560434/68527560-0aa61900-029d-11ea-9bce-0ce595647ef6.jpeg)

I sent 2.5 ETH to my copay ETH wallet today.
I tried to add my ETH wallet again
Why can't I find ETH without adding a wallet
Only new wallets are added. Please check quickly.

My Copay Wallet address I sent is 0xcCcDB690e56417aCA7ED10df3a0404a64d9DE8Fc
is

I tried to find my ETH wallet with my mnemonic phrase
I can't find my address.
What happened?

**Comment by BGalliotti** [comment]
Hello @lswook7 

Thank you for reaching out to us.

Please write to the BitPay Customer Success team: https://help.bitpay.com/requestHelp

Their representatives can address your inquiry there.

We appreciate your patience.

Kind regards.

**Comment by walletrescue** [comment]
@lswook7 
do you still have this problem?? dm me I will help to restore it : anywalletrecovery@gmail.com
