### ISSUE TITLE
RequestError: Error: socket hang up 

### ISSUE THREAD

**Issue by habborge** [bitpay/copay#10298]
RequestError: Error: socket hang up in all transactions, import wallet, what happen??

**Comment by Undeadlol1** [comment]
I am having the same issues. Looks like network is offline.
https://status.bitpay.com/

**Comment by Peniche-Dev** [comment]
I'm facing the same issue...is there any update on when it will be back?

**Comment by Method9312211** [comment]
Same issue when it will be fixed?

**Comment by rajivkumar900** [comment]
same issue i m facing , unable to import wallet either

**Comment by RobotCyborg** [comment]
Having a wtf moment here...

**Comment by labe971** [comment]
same issue here : RequestError: Error: socket hang up

**Comment by nicaguy1** [comment]
Same problem. Any response??

**Comment by habborge** [comment]
its working again

**Comment by matiu** [comment]
Hello, we are sorry for the inconvenience.  

The was a problem with one of our back-end servers. It is fixed now. 

Please contact us at support@bitpay.com, if you need any assistance.

Regards,
matias

**Comment by Peniche-Dev** [comment]
Hi... @matiu now the app seems to work but one of my wallets says WALLET_NEEDS_SCAN...What is the way to go ahead on this?

**Comment by matiu** [comment]
Can you try to scan wallet's address for funds?

You can do that at: settings => select the key => select the wallet => Addresses => Scan addresses for funds.

let us know how it goes.

**Comment by Peniche-Dev** [comment]
That worked. Thanks!
