### ISSUE TITLE
My copay wallet shows zero

### ISSUE THREAD

**Issue by Schmadeke1** [bitpay/copay#10339]
I added about .0324 bitcoin to my wallet in August of 2019, it was there yesterday, I copied a blockchain from 5dimes.com to send them $200 dollars worth of bitcoin. After attempting the blockchain, nothing went to 5dimes.com, but yyen my wallet was at zero and there shows only a history of adding money to th e wallet nothing else. How can I of lost my bitcoin?

**Comment by matiu** [comment]
Hi, can you please share an address of your wallet, so we can investigate further?

**Comment by Schmadeke1** [comment]
How do I find the address of the wallet on copay?

**Comment by matiu** [comment]
go to the "receive" tab and you will see and address.

**Comment by Schmadeke1** [comment]
1GyigcERozxoQ2KxLSpJLdH5aRdFmK7D4P

**Comment by Schmadeke1** [comment]
Thankyou for your help

**Comment by maskoff102** [comment]
I put 90 dollars into the bitcoin machine and scanned my copay and everything went trhough but when i look at my copay wallet it shows zero balance on my wallet .

**Comment by BGalliotti** [comment]
Kind regards.

**Comment by johnjames333** [comment]
we have developed our own hardware for cracking BITCOIN wallet PASSWORDS with superfast speed
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333
