### ISSUE TITLE
6/3に送金したものが移動済となってる。

### ISSUE THREAD

**Issue by duschehitomi** [bitpay/copay#10347]
![F9F03120-5B5B-4433-B488-32E548CDB65C](https://user-images.githubusercontent.com/57902255/69104111-a2301680-0aaa-11ea-8300-9eaa6729b67c.jpeg)

移動済を戻してほしい

**Comment by BGalliotti** [comment]
Hello @duschehitomi 

You have moved your funds from your wallet to your wallet (the origin wallet is the same as the destination wallet, different addresses but same wallet).

**Wallet A > Wallet A**

There is no problem with the funds, there is nothing to recover or fix, the only expenditure here, are the network fees for the transaction.

Kind regards.
