### ISSUE TITLE
Bitcoin wallet went empty

### ISSUE THREAD

**Issue by Schmadeke1** [bitpay/copay#10340]
I added about .0324 bitcoin to my wallet in August of 2019, it was there yesterday, I copied a blockchain from 5dimes.com to send them $200 dollars worth of bitcoin. After attempting the blockchain, nothing went to 5dimes.com, but yyen my wallet was at zero and there shows only a history of adding money to th e wallet nothing else. How can I of lost my bitcoin?

**Comment by matiu** [comment]
dup: https://github.com/bitpay/copay/issues/10339

**Comment by soniaklick** [comment]
Well, i was in the same situation until i sorted professional help. These guys helped me recover my wallet private key [secrettruthhackers.imfast.io], what would i have done when my wallet had investors bitcoin in there? Thanks to the secrettruthhackers.

**Comment by walletrescue** [comment]
@Schmadeke1 
I have solved similar problem for my customer. 
get in touch with me I will return your lost btc : anywalletrecovery@gmail.com
