### ISSUE TITLE
BTC never received 

### ISSUE THREAD

**Issue by Welle7878** [bitpay/copay#10356]
I transferred a small amount of BTC to test the wallet but never received same. The address I sent to was 1Bkqio8MQUU6bmY3SyPHGX6Fi3t1UXa8tT which is not an address on either of my wallets in copay , this address was copy and pasted and is not even remotely the same . I suspects fowl play ?

**Comment by jordannick0** [comment]
Same Thing for me I Went to a Bitcoin machine at 9pm yesterday and haven’t received my bitcoin yet

**Comment by rjr333** [comment]
I had same issue so i restarted my phone and the BTC arrived.

**Comment by matiu** [comment]
@Welle7878 Please send us your walletId or any address from your wallet so we can check.

Not that addresses are regenerated everytime you receive a payment. Wallets can hay multiple addresses.

**Comment by maskoff102** [comment]
I put money into a bitcoin machine and scanned my wallet using copay and i look in my copay wallet and it doesn't show the bitcoin i have the receipt number to

**Comment by BGalliotti** [comment]
Hello @maskoff102 

We are going to close this thread. If you need further help, please open a new one and we will be happy to help you. :)

Kind regards.
