### ISSUE TITLE
Bitcoin lost 

### ISSUE THREAD

**Issue by InigoMontpiya** [bitpay/copay#10379]
Hi All,

Novice level here and I'm not sure how to fix the issue I have. I had copay setup on a mobile phone which tanked and I lost everything on it. 

When I got my new phone I setup copay but to my surprise when I entered my recovery phrase I do not get my bitcoin funds. I have my wallet address and can see the funds in there but the recovery phrase is only.goving me an empty wallet. 

Rather confused so any help appreciated.

Cheers

**Comment by matiu** [comment]
Can you please let us know the wallet ID of the wallet you access when you recover the funds, and the address where your funds are at?

**Comment by NEEDSCASH2017** [comment]
Thanks for your reply , this is order QKK4SLHW and this is bitcoin addresss
1HNbsqgmRn4x6hpe9SwExAcFCLrhnvt6Ny

**Comment by soniaklick** [comment]
> Hi All,
> 
> Novice level here and I'm not sure how to fix the issue I have. I had copay setup on a mobile phone which tanked and I lost everything on it.
> 
> When I got my new phone I setup copay but to my surprise when I entered my recovery phrase I do not get my bitcoin funds. I have my wallet address and can see the funds in there but the recovery phrase is only.goving me an empty wallet.
> 
> Rather confused so any help appreciated.
> 
> Cheers

Well, i was in the same situation until i sorted professional help. These guys helped me recover my wallet private key [secrettruthhackers.imfast.io], what would i have done when my wallet had investors bitcoin in there? Thanks to the secrettruthhackers.

**Comment by NEEDSCASH2017** [comment]
3FWeuhdJGunMZSSSJmur4VpNaRzhr7zgD9 this is the address where i sent bitcoins

**Comment by NEEDSCASH2017** [comment]
https://insight.bitpay.com/tx/08a223b954dbf726e7c30f513d22cb7a66af304dc7f527375bbe7ea692e99345
This is a copy of transaction on blockchain

**Comment by NEEDSCASH2017** [comment]
08a223b954dbf726e7c30f513d22cb7a66af304dc7f527375bbe7ea692e99345 this is
transaction id my name on copay Gettinabently

**Comment by soniaklick** [comment]
Have you contacted them? I'm sure they would help you recover your bitcoins like they did in my case.

**Comment by NEEDSCASH2017** [comment]
Yes but the email i got back they said once the bitcoins are sent they are
gone

**Comment by soniaklick** [comment]
secrettruthhackers@gmail.com..... They helped with a similar issue, they can't say that to you.

**Comment by NEEDSCASH2017** [comment]
08a223b954dbf726e7c30f513d22cb7a66af304dc7f527375bbe7ea692e99345
transaction id

**Comment by NEEDSCASH2017** [comment]
Summary
Size 3808 (bytes)
Fee Rate 0.00019284138655462185 BTC per kB
Received Time Dec 11, 2019 3:36:37 PM
Mined Time Dec 11, 2019 3:36:37 PM
Included in Block
0000000000000000001527d5db832fa492c437b31d9232c9912a772eac613bc3
<https://insight.bitpay.com/block/0000000000000000001527d5db832fa492c437b31d9232c9912a772eac613bc3>
Details
 08a223b954dbf726e7c30f513d22cb7a66af304dc7f527375bbe7ea692e99345
<https://insight.bitpay.com/tx/08a223b954dbf726e7c30f513d22cb7a66af304dc7f527375bbe7ea692e99345>
mined Dec 11, 2019 3:36:37 PM
2.06326092 BTC
38ENmTr2AD1avJrmmi9iM7PfS6nZVmuMKf
<https://insight.bitpay.com/address/38ENmTr2AD1avJrmmi9iM7PfS6nZVmuMKf>
0.00649096 BTC (S)
<https://insight.bitpay.com/address/1MCwDEAzJbnvvBv1AApEXPTCabuidgTnj2>
0.04247702 BTC (S)
1EsonLQJiZmD2SmQvXnPS4fa38Jg1b1yN3
<https://insight.bitpay.com/address/1EsonLQJiZmD2SmQvXnPS4fa38Jg1b1yN3>
0.13808911 BTC (S)
37DgVYSZdrAybskJuoGWho6TG4TsPXqWei
<https://insight.bitpay.com/address/37DgVYSZdrAybskJuoGWho6TG4TsPXqWei>
0.04130039 BTC (S)
36o8nxQHnoR7k7tzsKqmdM6aTCzFPFYCpm
<https://insight.bitpay.com/address/36o8nxQHnoR7k7tzsKqmdM6aTCzFPFYCpm>
0.14159008 BTC (S)
13qijMVW2JGTBYEQC6UBVxSS1BBMCCB87s
<https://insight.bitpay.com/address/13qijMVW2JGTBYEQC6UBVxSS1BBMCCB87s>
 Show more

**Comment by BGalliotti** [comment]
Hello @NEEDSCASH2017 

Cryptocurrency transactions are not [reversible](https://support.bitpay.com/hc/en-us/articles/115003028706-Can-I-reverse-a-transaction-from-my-BitPay-wallet-), there is nothing to do to recover funds already broadcast to the blockchain or roll-back the operation.
As a recommendation, next time please double check the destination address before sending the funds.

Kind regards.

**Comment by johnjames333** [comment]
we have developed our own hardware for cracking BITCOIN wallet PASSWORDS with superfast speed
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333

**Comment by walletrescue** [comment]
@InigoMontpiya 
@NEEDSCASH2017 
you can reach me if you still have this issue because I have solved similar problems before
: anywalletrecovery@gmail.com
