### ISSUE TITLE
Funds lost from wallet

### ISSUE THREAD

**Issue by mnjvs12345** [bitpay/copay#10373]
My wallet is 1F4WfZ6Rp4dnNnrLALZV8nFYrFEUi1C25q

I had around 0.2 BTC today.
Later I made one transfer 0.011 and my wallet says that I have got 0.008219 left.
What is that about?

I imported wallet to another app and there was everything ok with my funds. I made one more transfer from it.

Finally my copay wallet says I transfered 0.188605 to multiple recipients: 2 but it is total bullshit. What does it means and when you fix it?

**Comment by rjr333** [comment]
I had same issue, I restarted my phone and they appeared

**Comment by mnjvs12345** [comment]
Restarted many times on app and also on desktop version, still the same!

**Comment by rjr333** [comment]
Have you looked on the blockchain to see if it has been received in the wallet
Get Outlook for iOSFrom: mnjvs12345 <notifications@github.com>
Sent: Wednesday, November 27, 2019 13:52
To: bitpay/copay
Cc: rjr333; Comment
Subject: Re: [bitpay/copay] Funds lost from wallet (#10373) 

Restarted many times on app and also on desktop version, still the same!

**Comment by mnjvs12345** [comment]
Here is transaction ID 230f810c65be36d87da5f75fa5816c0d9466f7dad2ade3841d58e23f800133fb I cannot understand details

**Comment by rjr333** [comment]
I will check later when I’m home for you 
    	
    	

    	Get Outlook for iOS
    
  




On Wed, Nov 27, 2019 at 1:56 PM +0200, "mnjvs12345" <notifications@github.com> wrote:












Here is transaction ID 230f810c65be36d87da5f75fa5816c0d9466f7dad2ade3841d58e23f800133fb I cannot understand details

**Comment by rjr333** [comment]
This is the link to the transaction

 

So it shows its been received

 

https://www.blockchain.com/btc/tx/230f810c65be36d87da5f75fa5816c0d9466f7dad2ade3841d58e23f800133fb

**Comment by mnjvs12345** [comment]
Thank you for your time, but I don't understand what and where been received?
I transfered only 0.011 on 3A3f8d63fXDvxmeGNEfnPa2DcTn9jjk3Bp
And what is the 1577D1kNUB1KqwtbCyfZR2aWE1XqMdkCL9 0.17760526 transaction I don't know I didn't do it.


On imported wallet to other app everything is ok and 0.17760526 amount is available. But Copay shows wrong amount because of this transaction I have never done

**Comment by rjr333** [comment]
What is your wallet address then I can see the transaction to the wallet 
    	
    	

    	Get Outlook for iOS
    
  




On Thu, Nov 28, 2019 at 8:54 AM +0200, "mnjvs12345" <notifications@github.com> wrote:












Thank you for your time, but I don't understand what and where been received?

I transfered only 0.011 on 3A3f8d63fXDvxmeGNEfnPa2DcTn9jjk3Bp

And what is the 1577D1kNUB1KqwtbCyfZR2aWE1XqMdkCL9 0.17760526 transaction I don't know I didn't do it.


On imported wallet to other app everything is ok and 0.17760526 amount is available. But Copay shows wrong amount because of this transaction I have never done

**Comment by rjr333** [comment]
So if im correct you transferred 0.011 to your wallet

 

This shows the transaction  is received into the wallet.    https://www.blockchain.com/btc/address/3A3f8d63fXDvxmeGNEfnPa2DcTn9jjk3Bp

 

Maybe try to reload the app on your phone.

 

 

 

For the other amount… is this another wallet you hold ? im not sure   1577D1kNUB1KqwtbCyfZR2aWE1XqMdkCL9 0.17760526 transaction I don't know I didn't do it.

**Comment by mnjvs12345** [comment]
![Screen Shot 2019-11-28 at 16 35 41](https://user-images.githubusercontent.com/58221341/69814600-39a90e00-11fd-11ea-8a44-619d62eecc07.png)
I added screenshot. I transfered only 0.011. But this transaction shows that together with 0.011 that I transfered also 0.17760526 were gone some where to 1577D1kNUB1KqwtbCyfZR2aWE1XqMdkCL9. I don't understand this at all.

Here is my wallet address: 1F4WfZ6Rp4dnNnrLALZV8nFYrFEUi1C25q
Here is the address I made transfer 0.011 to: 3A3f8d63fXDvxmeGNEfnPa2DcTn9jjk3Bp
What is the wallet 1577D1kNUB1KqwtbCyfZR2aWE1XqMdkCL9 and why Copay shows that I sent 0.17760526 there I don't know at all and this is what I would like to understand. I didn't do it.

**Comment by mnjvs12345** [comment]
I tried to reload app, but the same picture on the phone or laptop version. Also imported wallet to Bitpay app and same situation there.

Now I do transactions from blockchain app where everything is right with my balance, but copay do not show the transactions any more from same wallet.

**Comment by matiu** [comment]
Hi @mnjvs12345 

Your wallet has multiple addresses. 
1577D1kNUB1KqwtbCyfZR2aWE1XqMdkCL9. and
1F4WfZ6Rp4dnNnrLALZV8nFYrFEUi1C25q belongs to the same wallet.

For same reason copay was not identifying that 1577D1kNUB1KqwtbCyfZR2aWE1XqMdkCL9 was ferom your wallet. When you send a TX, a new address is create and the remaining of the used funds are transfer to it (as the "change").

I have scanned your wallet, and the funds are udpated.

is it possible you are using the same wallet (seed) from an other software at the same time that copay?

**Comment by mnjvs12345** [comment]
Yes, I was forced to import wallet to another software to get my funds. Because situation that I am trying to tell, that funds that went to 1577D1kNUB1KqwtbCyfZR2aWE1XqMdkCL9 were not available in copay. I used new software to use my funds. Problem is why it took so long and in other software funds were available immediately but copay showed that they are gone for few days.
