### ISSUE TITLE
Can’t send eth, my funds are blocked!!

### ISSUE THREAD

**Issue by fidentiss** [bitpay/copay#10387]
every time I try to make a transfer in ETH, I can't do it, it keeps loading or shows some error, I tried to delete the app and reinstall it, install it in copay, I don't know what to do anymore, help

![4B93011B-71A1-46B1-ACFD-B5E9AEB498DE](https://user-images.githubusercontent.com/17974451/70047692-8478ac00-1596-11ea-89c5-67ab50c14b49.jpeg)
![C82D6C28-5786-4511-8ECB-08EB0D10AB13](https://user-images.githubusercontent.com/17974451/70047695-8478ac00-1596-11ea-8686-493eb24afc72.png)

**Comment by matiu** [comment]
Can you provide the walletId so we can check your wallet? thanks.

**Comment by johnjames333** [comment]
we have developed our own hardware for cracking BITCOIN wallet PASSWORDS with superfast speed
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333
