### ISSUE TITLE
Failing to add funds to a wallet

### ISSUE THREAD

**Issue by jonesjaynkala** [bitpay/copay#10386]
Hello there i had just recently downloaded the copay wallet and created an account.I have money in my bank account but i do not know how to transfer money from bank account into copay wallet since copay only uses links for transactions..please get back to me as soon as possible

**Comment by matiu** [comment]
You need to have Bitcoin or Bitcoin Cash or Ethereum to transfer to the wallet. You can exchange your fiat money to crypto on any exchange.
