### ISSUE TITLE
Can not send ethereum. Blocked?

### ISSUE THREAD

**Issue by onurmars** [bitpay/copay#10388]
Hello. My ID is 1b819e7b-5eb4-4466-a9f7-0d2d10284437

Please check i can not send any money

**Comment by onurmars** [comment]
![F6EC8FE0-44BE-477D-9244-28768ADDC2DA](https://user-images.githubusercontent.com/58470755/70049896-d1807080-15de-11ea-91c5-9d5b3c6e7e64.png)
![2682C223-4308-4B7F-BA2E-2AB27B55FDEA](https://user-images.githubusercontent.com/58470755/70049898-d1807080-15de-11ea-87df-573bf876ce4b.png)
![F377E0AA-45C6-45A4-96E9-6D93DEF74D4C](https://user-images.githubusercontent.com/58470755/70049899-d1807080-15de-11ea-9329-90c741e5cc21.png)

**Comment by matiu** [comment]
Hello, 

Thanks for the detailed report.

Can you try to delete the unsent transaction?. There should be a delete link on the bottom of the transaction view.

**Comment by onurmars** [comment]
Yes i deleted it and try to send several times but the same errors :(( can
you check it.  ( sorry of my english. )

3 Ara 2019 Sal, saat 20:33 tarihinde Matias Alejo Garcia <
notifications@github.com> şunu yazdı:

**Comment by onurmars** [comment]
Hello. I tryed on my PC and problem solved. Thank you

3 Ara 2019 Sal, saat 20:40 tarihinde Onur Turan <turan.onur@gmail.com> şunu
yazdı:

**Comment by Cristhian1325** [comment]
> Hello. My ID is 1b819e7b-5eb4-4466-a9f7-0d2d10284437
> 
> Please check i can not send any money

**Comment by FaDee1** [comment]
เปลี่ยนกระเป๋าใหม่ได้ไหมค่ะ

**Comment by timsuthee2535** [comment]
ผมต้องทำยังงัยครับ

ในวันที่ จ. 6 ม.ค. 2020 06:44 น. FaDee1 <notifications@github.com> เขียนว่า:

**Comment by BGalliotti** [comment]
Hello  @timsuthee2535 @FaDee1 

We are going to close this thread. If you need further help, please open a new one explaining the issue in detail and we will be happy to help you. :)

Please post your inquiry in English.

Kind regards.
