### ISSUE TITLE
Copay.

### ISSUE THREAD

**Issue by ProjectMike90** [bitpay/copay#10383]
Made a multi sig payment and the receipt did not deliver what I paid for and I would like my funds refunded to my copay account ASAP please.

**Comment by ProjectMike90** [comment]
The address that everything started from was 1QFkj7EGpZ67UXhCgkFxecdwYk9C9LQr6E.

**Comment by ProjectMike90** [comment]
14yUwGvwxbCtLWxozLWca7HV24HHDB8ZAm.  This is the address that I submitted my funds to, but as I stated, they unfortunately did not deliver what was required of them.  So, if you can please assist me in retrieving my funds please.

**Comment by matiu** [comment]
Hi, bitcoin transactions are not reversible, it is not possible for us (or anyone) to reverse the operation.
