### ISSUE TITLE
billetera copay problema

### ISSUE THREAD

**Issue by mauropicon** [bitpay/copay#10392]
hola buenos dias, alguien me puede ayudar? tengo btc en copay y no los puedo envia a ningun lado cuando los quiero enviar me dice : ERROR " la billetera que esta utilizando no coincide con la red y/o la moneda de la direccion proporcionada" , ya intente mandar a iq option y nada , tampoco a blockchain, a skrill , a ningun lado me deja enviar ....

**Comment by mauropicon** [comment]
mi wallet id es : 54c05c02-e3f6-4a88-a002-0ddb7b25bfa3

**Comment by mauropicon** [comment]
hello good morning, can anyone help me? I have btc in copay and I cannot send them anywhere when I want to send them to me: ERROR "the wallet you are using does not match the network and / or the currency of the address provided", I already tried to send to iq option and nothing , neither to blockchain, to skrill, nowhere let me send ...


My wallet id is: 54c05c02-e3f6-4a88-a002-0ddb7b25bfa3

**Comment by BGalliotti** [comment]
Hola @mauropicon 
Gracias por ponerse en contacto con nosotros.

Por favor actualice la app e intente nuevamente.
Algunos cambios que hicimos pueden haber afectado versiones anteriores de la app

Por favor, háganos saber si tiene alguna pregunta adicional.
Saludos cordiales.

**Comment by mauropicon** [comment]
Hola buenos dias, recien actualice la aplicación y volvi a intenter y sigue el mismo problema, no me deja enviar los btc a ninguna billetera , tampoco a iq option, y es un problema de copay, porque con otras billeteras si me deja enviar a iq option. Gracias espero su respuesta

**Comment by BGalliotti** [comment]
Hola
Gracias por ponerse en contacto con nosotros.

Qué version de la app está utilizando?

Para ver la version haga click en el icono del engranaje > **Acerca de BitPay** 

Esperamos su respuesta.
Saludos cordiales.

**Comment by mauropicon** [comment]
![90E41233-30B8-49E7-A420-BC4420D4BD6D](https://user-images.githubusercontent.com/58424721/70354215-cbdc9200-184d-11ea-9896-4d6d8196d1e3.png)


Version v8.0.5

**Comment by mauropicon** [comment]
Espero una respuesta 🙈. Gracias

**Comment by mauropicon** [comment]
Hola buenas tardes , aca estoy leyendo un poco y veo que mi billetera de copay y los bitcoins que compra hace mas de un año son en red testnet, como puedo hacer para venderlos a esos ya que estan en una red testnet, o me estafaron? Gracias

**Comment by BGalliotti** [comment]
Hola @mauropicon 
Lamentablemente parece haber sido víctima de una estafa.

Las monedas testnet carecen de valor por lo cual no puede venderlas o cambiarlas por monedas de valor real.

Desafortunadamente no hay nada que hacer al respecto

Por favor, háganos saber si tiene alguna pregunta adicional.
Saludos cordiales.

**Comment by mauropicon** [comment]
Muchas gracias por su respuesta, ahora te pregunto, conozco a la persona que me estafó, vive aca en resistencia chaco argentina , tengo todos sus datos, se donde vive tambien, hay alguna forma de denunciarlo para tratar de que me devuelva lo que me robó???

**Comment by BGalliotti** [comment]
Hola @mauropicon 

Le sugerimos realizar una denuncia privada como así también ante las autoridades locales.

Saludos cordiales.
