### ISSUE TITLE
About $1200 worth of bitcoin disappeared

### ISSUE THREAD

**Issue by rollyrules01** [bitpay/copay#10398]
I made a transfer of about $500, it went through, then I saw something like transfer no broadcasted and I saw options to cancel or broadcast which I cancelled and about $1200 automatically got deducted from my wallet. I’ve restarted the app more than 10 times and restarted my phone more than 5 times but funds hasn’t come back to it was sitting.
Could you guys look into this?
Thanks.

**Comment by BGalliotti** [comment]
Hello 2





Kind regards.

**Comment by walletrescue** [comment]
@rollyrules01 
I think I might be able to solve your issue
if your is still missing from your wallet pm me and I will try to return your fund you can reach me for help gmail : anywalletrecovery@gmail.com
