### ISSUE TITLE
Encryption code

### ISSUE THREAD

**Issue by tritri2999** [bitpay/copay#10409]
Using copay I never received any encryption code, but in order to send bitcoin I need one.
Where can I find mine?

**Comment by BGalliotti** [comment]
Hello @tritri2999 

The Encrypt password is something you set up.

If you do not remember it, the only way to recover the wallet is by importing it using the recovery phrase.

To know how to backup and restore the wallet please refer to [8532](https://github.com/bitpay/copay/issues/8532#issue-319277251)

In case you had any questions or concerns regarding the wallet backup/restore, please post it on that thread.
Kind regards.
