### ISSUE TITLE
Trouble with import 

### ISSUE THREAD

**Issue by nikisha2517** [bitpay/copay#10413]
Hi looking for help.  I am trying to import my wallet using a 12-word phrase.  But nothing happens.  On balance 0 $.  What to do?

**Comment by BGalliotti** [comment]
Hello,

Thank you for reaching out to us.

Please write to the BitPay Customer Success team: https://help.bitpay.com/requestHelp

Our representatives can address your inquiry there.

We appreciate your patience.

Kind regards.

**Comment by johnjames333** [comment]
we have developed our own hardware for cracking BITCOIN wallet PASSWORDS with superfast speed
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333

**Comment by walletrescue** [comment]
@nikisha2517 
I can solve your problem 
if your problem still lingers on your wallet let me know and recover it contact me for help gmail : anywalletrecovery@gmail.com
