### ISSUE TITLE
Consulta billetera btc

### ISSUE THREAD

**Issue by mauropicon** [bitpay/copay#10424]
Hola buenas tardes , aca estoy leyendo un poco y veo que mi billetera de copay y los bitcoins que compra hace mas de un año son en red testnet, como puedo hacer para venderlos a esos ya que estan en una red testnet, o me estafaron? Gracias

**Comment by BGalliotti** [comment]
Hola  @mauropicon 
Gracias por ponerse en contacto con nosotros.

Hemos respondido su ticket original.

Saludos cordiales.
