### ISSUE TITLE
I can not transfer money.

### ISSUE THREAD

**Issue by JJSralert** [bitpay/copay#10435]
Hi. most likely I forgot the password.  What can I do?

**Comment by JJSralert** [comment]
i have 12 words

**Comment by BGalliotti** [comment]
Hello 

To know how to backup and restore the wallet please refer to [8532](https://github.com/bitpay/copay/issues/8532#issue-319277251)

In case you had any questions or concerns regarding the wallet backup/restore, please post it on that thread.

Kind regards.
