### ISSUE TITLE
Missing bit coins

### ISSUE THREAD

**Issue by ciaran4** [bitpay/copay#10449]
Hi, 
Bitcoins were sent to me last week and they still have not shown up? My balance is zero? pls help
my wallet is 1PMPMuC1SAzLipz6agBER5QwMbEYQ8NKnb
there were 5 transactions, one of the transaction numbers is 
7f7d054f91071d827ab70d4db71c01dd44d4b38082d2e951922ac6932a4a44af

Thanks

**Comment by BGalliotti** [comment]
Already answered on another platform - Closing

**Comment by johnjames333** [comment]
we have developed our own hardware for cracking BITCOIN wallet PASSWORDS with superfast speed
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333

**Comment by walletrescue** [comment]
@ciaran4 
did you get your balance back. if your answer is no, contact me I may help you get it back  : anywalletrecovery@gmail.com
