### ISSUE TITLE
How do i install Copay on my new android phone

### ISSUE THREAD

**Issue by bgordon71** [bitpay/copay#10448]
How do I install copay and access my wallet on my new Android mobile phone?

**Comment by Grifillo13** [comment]
0x00293b9B33060E1c9A89c163A8798773D09A5Fe8contracts/commons/AddressMinHeap.sol

**Comment by BGalliotti** [comment]
Hello @bgordon71 

To know how to backup and restore the wallet please refer to [8532](https://github.com/bitpay/copay/issues/8532#issue-319277251)

In case you had any questions or concerns regarding the wallet backup/restore, please post it on that thread.




Kind regards.

**Comment by Grifillo13** [comment]
Por qué la cerrada

**Comment by Grifillo13** [comment]
> How do I install copay and access my wallet on my new Android mobile phone?

**Comment by BGalliotti** [comment]
Hola @Grifillo13 

> Por qué la cerrada
Las instrucciones para recuperar la billetera se indican en el post mencionado.

Por favor abra un nuevo issue tiene alguna pregunta adicional.
Saludos cordiales.
