### ISSUE TITLE
problem importing 12 word phrase into Bitpay 3 of 6 wallet

### ISSUE THREAD

**Issue by kirksu** [bitpay/copay#10459]
I am one of 6 signers on a copay 3 of 6 multisig wallet.  two of us still have our copay for windows wallets operational.  Three of the others have lost their copay wallets but not their phrases.  These phrases have  BTC and BHC.  When I enter any of the three phrases into my current version of the bitpay multisig wallet, with either BTC or BHC selected as derivation path, I get a message that says this in the title:
"WE COULDN'T FIND YOUR WALLET
There are no records of your wallet on our servers. xxxxxxxxxxxxxxx.  Go back or  Continue Anyway" These are bip44 phrases.  If I continue anyway i wind up with either an empty generic BTC or a BHC wallet being added to my Bitpay wallet.  
This happens on all three of the phrases we are trying to import.  We have the phrases correctly preserved and the spelling is correct when imported to the bitpay wallet.  Can some one help?

**Comment by kirksu** [comment]
Opps, I wrote BHC in my first post instead of BCH (bitcoincash)  sorry

**Comment by BGalliotti** [comment]
Hello @kirksu 

1) Please try importing the wallet on the latest version of the app
2) If the previous doesn't work, please try the recovery tool. For the recovery tool you will need 3 recovery phrases.

To know how to use the Recovery Tool please refer to #9540 

Kind regards.

**Comment by johnjames333** [comment]
we have developed our own hardware for cracking BITCOIN wallet PASSWORDS with superfast speed
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333
