### ISSUE TITLE
On Copay app says sent with confirmations but still unconfirmee

### ISSUE THREAD

**Issue by mrman811881** [bitpay/copay#10477]
Hi sent funds to a btc adress about 5 hours ago about 2 hours ago it says transaction confirmed on the app and says sent with 6+ confirmations 

Checked the blockchain and still unconfirmed?

When will the funds send

**Comment by BGalliotti** [comment]
- **Please send us the BitPay/Copay Wallet ID and the transaction hash / ID or the link so we can further investigate and address your inquiry.**

- To get your Wallet ID, open your Copay/BitPay application, then go to `Settings` > [Your wallet] > `More Options` > `Wallet Information`. 
On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste it in your e-mail. 
You can do the same on your computer by clicking on the wallet ID.

- The transaction hash / ID is a alphanumeric chain like this: **d0a23876de7cf87574b5cda7557bcc8af5d84f3fd1e6f4c6063fd6b72b0e69ae**

**We look forward to hearing from you.**
