### ISSUE TITLE
Copay took my money

### ISSUE THREAD

**Issue by Joshua1079** [bitpay/copay#10482]
I transferred money from Blockchain to copay and never was able to get my funds from copay. I feel abused. My money was stolen and I am unable to gain access.

**Comment by BGalliotti** [comment]
Hello @Joshua1079 

- **Please send us the BitPay/Copay Wallet ID and the transaction hash / ID or the link so we can further investigate and address your inquiry.**

- To get your Wallet ID, open your Copay/BitPay application, then go to `Settings` > [Your wallet] > `More Options` > `Wallet Information`. 
On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste it in your e-mail. 
You can do the same on your computer by clicking on the wallet ID.

- The transaction hash / ID is a alphanumeric chain like this: **d0a23876de7cf87574b5cda7557bcc8af5d84f3fd1e6f4c6063fd6b72b0e69ae**

**We look forward to hearing from you.**

**Comment by maksb199** [comment]
Hello!  I translated btc to an address that they no longer use.  Can I return the wrongly sent items?  help me please.

**Comment by BGalliotti** [comment]
Hello @maksb199 

Cryptocurrency transactions are not [reversible](https://support.bitpay.com/hc/en-us/articles/115003028706-Can-I-reverse-a-transaction-from-my-BitPay-wallet-), there is nothing to do to recover funds already broadcast to the blockchain or roll-back the operation.
As a recommendation, next time please double check the destination address before sending the funds.

If "they" still have access to the wallet, they are able to recover the funds.
You should talk to them to try to recover the funds.







Kind regards.
