### ISSUE TITLE
Lost password

### ISSUE THREAD

**Issue by clyde798er** [bitpay/copay#10517]
hi i lost my Bitcoin wallet Password to send bitcoins

**Comment by BGalliotti** [comment]
Hello 

Please refer to #8532 

Kind regards.

**Comment by johnjames333** [comment]
@clyde798er 
we have developed our own hardware for cracking BITCOIN wallet PASSWORDS with superfast speed
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333

**Comment by richardsuns** [comment]
@clyde798er 
if you have text backup and some idea about your password, it can be cracked
