### ISSUE TITLE
BCH lost 

### ISSUE THREAD

**Issue by Noah86** [bitpay/copay#10529]
Hace unos días miré mi wallet de Copay y vi que habían desaparecido tanto mis BTC como mis BCH. Probé a recuperarlos con las palabras de recuperacion y mis BTC volvieron, pero mis BCH desaparecieron. ¿Dónde están?

—

A few days ago I looked at my Copay wallet and saw that both my BTC and my BCH had disappeared. I tried to recover them with the words of recovery and my BTC returned, but my BCH disappeared. Where are they?

Thanks!

**Comment by BGalliotti** [comment]
Hola
Gracias por ponerse en contacto con nosotros.

Por favor dirijase a #9197 

Saludos cordiales.

**Comment by Noah86** [comment]
Sorry, but this isn’t my solution. I didn’t sent BCH to a BTC account, I HAD BCH in my wallet and they disappeared.

**Comment by BGalliotti** [comment]
Hola @Noah86 
Gracias por ponerse en contacto con nosotros.

Tus BCH no pueden desaparecer de manera instantánea de tu billetera.

Cada transacción saliente en su billetera debe estar firmada por las claves privadas de la billetera.
Esto significa que, para ser válida, se debe enviar una transacción desde su billetera utilizando tu dispositivo / dispositivos.

Hay dos posibilidades:

- Has enviado los fondos, tal vez accidentalmente.
- Alguien robó su billetera (frase de recuperación, clave privada) o tu dispositivo / dispositivos donde la billetera está instalada y ha enviado los fondos.

Lamentablemente, no hay nada que podamos hacer en este caso. Además, una transacción de criptomonedas no se puede revertir, por lo que no hay forma de recuperar los fondos.

Asegúrate de que tus dispositivos estén seguros y que tus billeteras estén protegidas con contraseña / huella digital si es necesario.

Por favor, déjanos saber si tienes alguna pregunta adicional.
Saludos cordiales.

**Comment by Noah86** [comment]
Pues...

   En principio fondos no he enviado (o intentado enviar) desde hace casi un año.
 
   Y con respecto al robo, es bastante-bastante improbable (huella digital, contraseña, nadie toca nunca mi móvil, etc.) pero además no tiene ningún sentido tampoco cuando los BTC sí se recuperaron con la clave. Pero los BCH siguen sin aparecer. 

   Tienen que estar en algún lugar, pero yo en mi saldo sigo viendo 0 BCH.

**Comment by Noah86** [comment]
Todavía continúo con el mismo problema, ¿dónde está el dinero que envíe y acumulé en la dirección de mi billetera? 

Gracias.

**Comment by BGalliotti** [comment]
Hola 

Vamos a cerrar este hilo. Si necesita más ayuda, abre un nuevo hilo que explique el problema en detalle y estaremos encantados de ayudarle. :)

@Noah86  Respecto de la billetera BCH por favor incluya el ID de la misma.

Saludos cordiales.
