### ISSUE TITLE
ERROR 500 "{}"

### ISSUE THREAD

**Issue by anfabian79** [bitpay/copay#10572]
Hola buenas tardes, estoy intentando hacer un retiro de ETHER a otra billetera pero en el proceso 
me da ERROR 500"{}"  Me pueden colaborar por favor.

**Comment by jordimen034** [comment]
Hola buenas tardes, estoy intentando hacer un retiro de ETHER a otra billetera pero en el proceso
me da ERROR 500"{}" Me pueden colaborar por favor.

**Comment by BGalliotti** [comment]
Hola
Gracias por ponerse en contacto con nosotros.

Por favor intente nuevamente, y déjenos saber si vuelve a tener el mismo problema.

Saludos cordiales.
