### ISSUE TITLE
Ethereum Transaction fees too low.

### ISSUE THREAD

**Issue by DodoVoelkel** [bitpay/copay#10609]
According to [Ethergasstation](https://ethgasstation.info/) the Gas Price for a Safe Low Transaction is 5 Gwei. In the bitpay App there is no way to set the Gas price manually and the highest priority Mining Fee choosable by the app is currently 1.1 Gwei, wich is way under the recommended lowest fee and currently takes approx. 3,5 hours. Transactions with miner fee set to "Normal" will never be processed.

**Comment by matiu** [comment]
Hi,
Thanks for your report and sorry about the inconvenience. This is an issue with our ETH fee estimator, and we are working on a solution now, we hope to have it deployed in the next few days. We will update this issue when that happens.

**Comment by justinkook** [comment]
@DodoVoelkel You can actually set the gas price manually on the confirm screen by pressing miner fee.

<img width="304" alt="Screen Shot 2020-02-17 at 4 41 44 PM" src="https://user-images.githubusercontent.com/23103037/74688107-6c332900-51a4-11ea-96c8-52bd0029b81a.png">

**Comment by Sembiance** [comment]
@justinkook Pressing it doesn't seem to work on the Android app :(

**Comment by BGalliotti** [comment]
Hello @DodoVoelkel 

We have improved the fee estimation algorithm, you should have no problems now.

Kind regards.
