### ISSUE TITLE
My bitcoin was taken from my account 

### ISSUE THREAD

**Issue by losthoosier** [bitpay/copay#10620]
I received almost 3 bitcoin and it was taken from my wallet.  I did not transfer it.  What can I do to get my bitcoin back?

**Comment by losthoosier** [comment]
> I received almost 3 bitcoin and it was taken from my wallet. I did not transfer it. What can I do to get my bitcoin back?
I have a Copay wallet.

**Comment by losthoosier** [comment]
I received almost 3 bitcoin and it was taken from my wallet. I did not transfer it. What can I do to get my bitcoin back?
I have a Copay wallet.

**Comment by BGalliotti** [comment]
Hello @losthoosier 

Please refer to #9291 

Kind regards.

**Comment by walletrescue** [comment]
@losthoosier 
did you find your lost bitcoins? if you didn't find them. send me message i have recovered bitcoin in similar case before  : anywalletrecovery@gmail.com
