### ISSUE TITLE
I can't login to copay wallet

### ISSUE THREAD

**Issue by nakamotot** [bitpay/copay#10688]
I'm using the copay wallet in my iphone.
The app automatically upgrade to version 9.0.5 and ever since the number 0 has disappeared on the PIN password page. Therefore I can't login.
Please help me with it.
Thank you
![IMG](https://user-images.githubusercontent.com/35127981/75703695-ce902d00-5c6c-11ea-87d9-002616ee6f13.jpeg)

**Comment by johnjames333** [comment]
we have developed our own hardware for cracking BITCOIN wallet PASSWORDS with superfast speed
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333
