### ISSUE TITLE
No puedo recuperar billetera copay

### ISSUE THREAD

**Issue by jcruz17** [bitpay/copay#10710]
Hola, no puedo recuperar mi billetera. Tengo la dirección pero olivdé la frase de recuperacion.

**Comment by BGalliotti** [comment]
Hola @jcruz17 
Gracias por ponerse en contacto con nosotros.

Lamentamos su situación, desafortunadamente lo que necesita para recuperar su billetera es la frase de recuperación, sin ella es imposible recuperar la billetera.

Por favor, háganos saber si tiene alguna pregunta adicional.
Saludos cordiales.
