### ISSUE TITLE
Lost all BTC and transaction records

### ISSUE THREAD

**Issue by pawinf** [bitpay/copay#10726]
I lost all my BTC in my wallet. All transactions records also disappear. Please help investigate. My wallet ID is

62f655c1-68db-49f2-8415-f437d69fdafb

**Comment by pawinf** [comment]
see my balance and latest transaction here

![23D83567-285E-40D4-A449-5C360E7987E7](https://user-images.githubusercontent.com/62349349/77128385-85b8e080-6a82-11ea-8a5d-09579f527258.jpeg)

**Comment by pawinf** [comment]
Anybody here can help me?

**Comment by BGalliotti** [comment]
Hello @pawinf 

I have answered in #10720 please refer to that thread.

I'm closing this thread.

Kind regards.

**Comment by johnjames333** [comment]
@pawinf
we have developed our own hardware for cracking BITCOIN wallet PASSWORDS with superfast speed
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333
