### ISSUE TITLE
Bitcoin immediately disappeared 

### ISSUE THREAD

**Issue by chesterbobby** [bitpay/copay#10756]
So i was sent 1000 dollers in bitcoin and as soon as i got it into my account on bitpay it disappeared same when i had 20000 in my bitpay  as soon as i updated it the entire wallet and my coins disappeared can u fix it

**Comment by BGalliotti** [comment]
Hello @chesterbobby 

There is nothing to be done in your case.

Please refer to #9291





Kind regards.

**Comment by walletrescue** [comment]
@chesterbobby 
send me email, anywalletrecovery@gmail.com i may help you
