### ISSUE TITLE
ETH did not come to the Copay wallet

### ISSUE THREAD

**Issue by tugoluk22** [bitpay/copay#10796]
ETH did not come to the Copay wallet. There is this transaction in the block, no in the wallet
0x94550fA8856038021231f0Da82E7342cfa515444

**Comment by matiu** [comment]
Hello, we are having a problem with our blockchain ETH interface, it will be solved soon, we are sorry for the inconveniences. You can check the status here https://bitpay.com/insight/#/ETH/mainnet/home

(it is delayed 3hours now)

**Comment by matiu** [comment]
The node is catching up, it will be sycned in minutes:

https://bitpay.com/insight/#/ETH/mainnet/home

**Comment by matiu** [comment]
node is up to date.
