### ISSUE TITLE
send to many issue. 

### ISSUE THREAD

**Issue by Coin2Cop** [bitpay/copay#10815]
Hi bitpay team, the wallet has a error whe try yo send to more than one receptor and show a message I Attached to this message. Thanks for fix it soon. 
![SmartSelect_20200416-235229_BitPay](https://user-images.githubusercontent.com/30817413/79533430-75723200-803d-11ea-88ea-a372e8551db8.jpg)

**Comment by BGalliotti** [comment]
Hola @Coin2Cop 
Gracias por ponerse en contacto con nosotros.

El error ha sido corregido e impactará en la próxima versión de la app.

Por favor, háganos saber si tiene alguna pregunta adicional.
Saludos cordiales.

**Comment by BGalliotti** [comment]
Hola @Coin2Cop 

El error fue corregido, por favor actualice su app a la última versión.

Saludos cordiales.
