### ISSUE TITLE
Copay removed my BTC? 

### ISSUE THREAD

**Issue by RvdM-SL** [bitpay/copay#10820]
Dear all,

I bought bitcoin June 2018 through litebit and placed it in my Copay wallet, iPhone 6s.

April 2020 I tried to sell my bitcoin.
An encrypted password was requested.
After many hours of trouble shooting and doing all the possibilities that lay within my capabilities (phrase, text, passwords, alternative apps) I finally braved myself to delete the key and restore it with my phrase on the same iPhone 6s.

The problem is that after importing my balance is gone.

How can I retrieve my balance? 

Many thanks

**Comment by johnjames333** [comment]
we have developed our own hardware for cracking BITCOIN wallet PASSWORDS with superfast speed
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333

**Comment by walletrescue** [comment]
@RvdM-SL 
did you find your password for wallet. if not contact me I may recover that : anywalletrecovery@gmail.com
