### ISSUE TITLE
Bitcoin Lost

### ISSUE THREAD

**Issue by adot092** [bitpay/copay#10836]
I had brought Bitcoin and send it to the address on Copay and by accident i refreshed the address. Do you think the bitcoin will still come ? or i lost it ?

**Comment by BGalliotti** [comment]
Hello @adot092 

To protect your privacy, the Copay/BitPay wallet generates new addresses automatically once you use a bitcoin address once. Wallet addresses do not expire – any payments sent to past addresses will continue to appear in your balance.

Please see this article for more information: [Why does my BitPay wallet's bitcoin address keep changing?](https://support.bitpay.com/hc/en-us/articles/115002989643-Why-does-my-BitPay-wallet-s-bitcoin-address-keep-changing-)

Kind regards.

**Comment by adot092** [comment]
yea but i haven’t received any funds

**Comment by adot092** [comment]
![BF3A791B-249F-4A64-B8E2-6373E1FB3D77](https://user-images.githubusercontent.com/64170181/80143312-9c1ef400-857a-11ea-9cd2-64cfa7529ea6.jpeg)

**Comment by adot092** [comment]
it has never appeared on my wallet

**Comment by kalahan2022** [comment]
@adot092 
we have developed our own hardware for cracking all versions of bitcoin wallet password with superfast speed
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @viladmir2022 or gmail : anywalletrecovery@gmail.com
