### ISSUE TITLE
Copay Error Sending BTC

### ISSUE THREAD

**Issue by FluffyPaw5** [bitpay/copay#10857]
I haven't used Copay in years, so now I logged in trying to send my BTC to another crypto website I'm using. However, just before the confirmation I get the "illegal state" error, preventing me from confirming the transaction. Doesn't matter whether I access Copay on my computer or on my phone. Always the same error. Tried deleting and reinstalling, same error. There's a significant amount of money in there I don't want to lose. How can I transfer it?

**Comment by FluffyPaw5** [comment]
Can anybody help me please?

**Comment by micahriggan** [comment]
Have you tried reimporting your 12 words? It could be that the app no longer can read the format that is saved on your device.

**Comment by FluffyPaw5** [comment]
What do you mean by reimporting? 
I've attached a screenshot of the error.
![IMG_4666](https://user-images.githubusercontent.com/64565273/80895656-f404db80-8c9b-11ea-936c-82d1d68e7346.PNG)

**Comment by FluffyPaw5** [comment]
So I downloaded Copay on my husband's Windows computer and it worked!! Seems like Apple products were the issue here.
