### ISSUE TITLE
BTC Wallet: Fees of 10-12%!! Too high

### ISSUE THREAD

**Issue by knipperkills** [bitpay/copay#10861]
Hi,
Since yesterday my btc sending fees have extremely increased and it’s only me in my wallet. From my wife’s phone and wallet the fees are still absolutely normal.
Please check the screenshot and advice.
Thank you
![CF09F064-9709-46BA-8231-0E3748B89E33](https://user-images.githubusercontent.com/64729034/80910904-64166e80-8d3b-11ea-90fc-4333da19b727.png)

**Comment by BGalliotti** [comment]
Hello @knipperkills 

Could you please tell us what versions have you currently installed on each of the devices?

We look forward to hearing from you.

Kind regards.

**Comment by knipperkills** [comment]
Hi 
I am using the most actual one from the Apple AppStore. Same with the mac version. I just now sent another transaction with 100$ roughly and paid 2,4$ fee. It’s not usable anymore

**Comment by matiu** [comment]
Hi @knipperkills 

We are sorry you are having problems with our wallet, the BTC fees are not controlled by our wallet, but by the offer and demand of the Bitcoin block size. You can check the current fees of the network at https://billfodl.com/pages/bitcoinfees and many other websites.

You can try to use Segwit enabled addresses or other currencies (like ETH or BCH) to operate with minor fees.
