### ISSUE TITLE
Can't export Bitcoin testnet wallet private key

### ISSUE THREAD

**Issue by mrsin** [bitpay/copay#10877]
Hi!

I need to export extended private key for Copay Bitcoin testnet wallet.

In prior Copay versions it was possible via wallet options.

In the recent Copay version key export is moved to settings, multiple wallets are grouped for single key and if you try to export a key you always got xpriv**** variant which is a main net key. AFAIK testnet keys start with tpriv*** prefix. Even if you only have testnet wallet and no mainnet wallets on this key you got mainnet key exported. I believe it is a bug.

I can export wallet to some JSON file but it is encrypted. Please advice on how to get private key from encrypted file or somehow get testnet wallet private key.

The testnet keys are needed for by blockchain classes training to work with Bitcoin programmatically.

**Comment by matiu** [comment]
Hi @mrsin 

Copay uses a single xpriv for multiple wallets. The key is exported as xpriv, but still is the key for all the wallets that are derived from it, including testnet wallets.

From the exported keys you can derive the testnet wallet's master key with a path like: m/44'/0'/1'/...

You can "transform" the xpriv to testnet format with bitcore-lib also:

```
key = new HDPrivateKey('xprivxxx');
keyObj = key.toObject();
keyObj.network = 'testnet';
testnetFormatedKey = new HDPrivateKey(keyObj);
```

**Comment by mrsin** [comment]
@matiu thank you for quick response!

I already managed to "transform" it with bitcoinjs library like this:

const TESTNET = bitcoin.networks.testnet;
const t =
bip32.fromBase58('xprvCopayExportedKey');
t.network = TESTNET; // trick to transform mainnet key pair to testnet
const derivedIndex = "m/44'/1'/0'/0/0";
const wifKey = t.derivePath(derivedIndex).toWIF();
const keyPair = bitcoin.ECPair.fromWIF(wifKey, TESTNET);
