### ISSUE TITLE
New iPhone - 12 word phrase doesn’t seem to be working

### ISSUE THREAD

**Issue by taimoriBR** [bitpay/copay#10882]
Hi,

I had to download the copay app again and tried to login to my wallet but cannot access it. I remember having funds inside this particular wallet and have my recovery phrase and my encryption password with me. Assistance would be appreciated.

I also retained the address from the last transaction: 
16UGppT6g1azCWyaESjv4fo8jAw26QQsyQ

I made this transaction in the end of 2018 I think. 
Many thanks,
taimoriBR

**Comment by matiu** [comment]
Hello,

How it is not working?  What error are you getting?

**Comment by taimoriBR** [comment]
Hi, thank you for your message. It turns out I miss wrote one of the recovery phrases (identity instead of identify)....
I was able to recover my wallet!
Thank you so much for the useful info thread!!!

**Comment by matiu** [comment]
Great, I am happy it worked.
