### ISSUE TITLE
Could not broadcast payment: 500 - "connect ECONNREFUSED 10.209.36.71:8332"

### ISSUE THREAD

**Issue by NateNate60** [bitpay/copay#10897]
I tried sending about 0.2 BCH to one of my other wallets and this error occurred.

STEPS TO REPRODUCE:
1. Try to send BCH to another wallet
2. Send any amount to any address
3. Click Send

Expected behaviour: Transaction posts and is ready to be added to a block and processed.
Actual behaviour: 

* A message pops up: Error 500 - There is a temporary problem, please try again later.
* The balance in the wallet is locked.
* The transaction is listed as "accepted, but not yet broadcasted".

Clicking the "broadcast transaction" button results in: 500 - "connect ECONNREFUSED 10.209.36.71:8332"

I am not using a VPN or proxy, and this happens across all my devices (Android phone, Windows 10 PC, Ubuntu 20.04 laptop). Attached below is a recording from my PC.

[ZIP file with recording of interaction](https://github.com/bitpay/copay/files/4641496/2020-05-17-17-59-21.zip)

**Comment by matiu** [comment]
thanks for the detailed report.

We were able to reproduce the error, we are investigating. 

We will update this ticket.

**Comment by matiu** [comment]
this should be fixed now. Sorry for the problems and thanks again for the detailed report.
