### ISSUE TITLE
Copay App on IOS Error Loading Keys

### ISSUE THREAD

**Issue by shatz17** [bitpay/copay#10974]
I just transfer btc to my copay wallet, tried to reopen the app but I can't is giving me an error Loading keys

keys.forEach is not a function. (In 'keys.forEach(k=>this.keys.push(this.Key.fromOBJ(k)));
'keys.forEach' is undefined.

That's all it says. The app is updated too. Please help

**Comment by matiu** [comment]
Hi, what you mean by "transfer the keys"?  Did You install the app and then import the backup phrase? If that is the case, can you try deleteing the app, and installing again and importing again? Thanks.

**Comment by shatz17** [comment]
thanks so much! 👍

**Comment by srisuk2519** [comment]
#10973

**Comment by shatz17** [comment]
thanks that worked!!
