### ISSUE TITLE
Issue on buying gift card in eur

### ISSUE THREAD

**Issue by HostFat** [bitpay/copay#10995]
I've just updated to the last android app v10.0.6, and it isn't anymore possible to buy "amazon.it" gift card (EUR) and virtual prepaid MasterCard (EUR).

Now it only show "Delta" and in USD currency.

It was possible before, so I guess that there is a bug somewhere.

**Comment by msalcala11** [comment]
Hey @HostFat, the gift card brands that are visible on the shop page are specific to the country associated with your IP address. Is it possible that you're not currently using an Italian IP address?

**Comment by HostFat** [comment]
No, but I can say that now it works again. Maybe there was an issue on the vendor.
