### ISSUE TITLE
Almost all funds stolen from Copay wallet on 1st July

### ISSUE THREAD

**Issue by mkmk47** [bitpay/copay#11016]
I had a balance of around 28.65 BTC. I last transacted from my wallet on 26/06/2020. Today when I opened my app, my funds were gone. There was transaction done on 1/07/2020. The transaction was done to multiple address. 1 with 28.63 BTC and other with a very small amount. My wallet was protected with a 4 digit PIN, also I had a transaction password on it. The seed could not be compromised, as I checked and it’s still where it is. I am using Copay app on iPhone. Kindly help.

**Comment by walletrescue** [comment]
@mkmk47 
if you couldn't solve your issue with missing bitcoins pm me i may help : anywalletrecovery@gmail.com
