### ISSUE TITLE
BTC did not reach wallet

### ISSUE THREAD

**Issue by avaladka** [bitpay/copay#11048]
![IMG_6732](https://user-images.githubusercontent.com/68906269/88664123-cca28c80-d099-11ea-817a-082f4720d84d.jpg)

My BTC transaction did not reach my wallet.  despite having a receipt of transaction from the atm machine i cannot find any record of said transaction on block explorer.  have removed and reinstalled app using seed words
transaction ID - 7c31207ca6
on iPhone Xr 
v10.0.10

thx

**Comment by matiu** [comment]
Do you have information about the bitcoin transaction? The vending machine should provide the address or txid so you can check it on a blockexplorer and see if it is on the blockchain. Check the TXID at: 

https://bitpay.com/insight/

**Comment by avaladka** [comment]
i do have it 7c31207ca6  have looked and comes up as - no transactions found

**Comment by matiu** [comment]
I am afraid that is not enough to help you at our end, or for you to check the TX on the blockchain/

**Comment by avaladka** [comment]
1METiZFyW25WGzxHBCb56MomrD4dXDWDh8 is the address but again nothing on 'insight'

**Comment by matiu** [comment]
If there is not transaction on the blockchain, You need to check with the vending machine.

**Comment by avaladka** [comment]
thx
