### ISSUE TITLE
Error querying the blockchain

### ISSUE THREAD

**Issue by Abwer** [bitpay/copay#11178]
I open my particl  copay wallet (android) and go to my BTC  its says:  Error querying the blockchain. I refresh but still an error.   
Last to receive  data 11 day ago. 
What's wrong with your app?
Pls Fix ASAP. 

![Screenshot_20201007_074743_io particl copay](https://user-images.githubusercontent.com/20970205/95296094-d9edab80-0880-11eb-8c0e-14c2a614d33b.jpg)
![Screenshot_20201007_073121](https://user-images.githubusercontent.com/20970205/95296097-db1ed880-0880-11eb-9f0e-b8041b6f8e8b.jpg)

**Comment by kiitospan** [comment]
I also same error in my apps.

**Comment by matiu** [comment]
hi. that project is a fork. it is not maintained here.
