### ISSUE TITLE
Copay v11.0.4 (ubuntu) , BTC showing but BCH not showing upon import

### ISSUE THREAD

**Issue by troowala** [bitpay/copay#11185]
Hello,

I restored a wallet  which held both BTC & BCH funds at the same address and was generated using the same private key.

BTC shows up fine , however BCH does not show up. The address is identical for both and the funds are showing on the blockchain explorer in that address but not in the wallet. 

Is there something i need to specify differently in the derivation path so that the address holding the BCH i.e. which is identical to the BTC address shows up in the wallet ?

Thanks

**Comment by troowala** [comment]
okay so had to do this, in case someone else is in the same boat and needs to recover BCH.

1. Go to Settings, Key1 (or whatever this maybe for you)
2. Click on the BTC Wallet
3. Click on Duplicate to BCH
4. Leave Screen and Go to Settings again and click on Key2 (this appears after the above step, even though its the same key)
5. Click on BCH Wallet
6. Click on Addresses
7. Scan Addresses for Funds
8. Funds show up.
9. Heave a sigh of relief and go spend that money.

**Comment by monzturreminem** [comment]
Out (Bch) in front Office it give Rhen kabels so the know white ti go Seve Bern doing slot of test and what you caughtbwas à golfen ticket out there on purpose for someone recieve and return positive resultat and to spend like your pants are on 🔥 

Eminem

**Comment by monzturreminem** [comment]
Label’s 

Eminem
