### ISSUE TITLE
Right amount not received 

### ISSUE THREAD

**Issue by kpalacios5** [bitpay/copay#11228]
I just put $450.00 into the bitcoin atm and the amount that it is showing I received is $91.69 Short. I know that there is a charge for it but how much is it and why is so much missing?

**Comment by matiu** [comment]
Hi. you neet to check with the ATM company. Bitpsy wallet is only showing that is on the blockchain.

**Comment by kpalacios5** [comment]
I transferred all of the funds from this wallet into another and I still haven’t received the money....why is that?

**Comment by matiu** [comment]
Can you share the transaction id?

**Comment by kpalacios5** [comment]
Transaction id is : ad3e7773f2cfb7357d428750c98797b14b73C7a111988077f3c7a2f47d587802

**Comment by matiu** [comment]
https://blockchair.com/bitcoin/transaction/ad3e7773f2cfb7357d428750c98797b14b73c7a111988077f3c7a2f47d587802

That transaction is on the blockchain and has 1000+ confirmation.

I saw you open multiple tickets. When you receive or send TX all you need to do is look for the TXID on any blockexplorer, and you can check if the TX is broadcasted and mined.

In this case, our wallet has sent the TX and it is already mined. You need to check with the recipient.
