### ISSUE TITLE
SCAM

### ISSUE THREAD

**Issue by kpalacios5** [bitpay/copay#11238]
DO NOT USE THIS APP. IT IS A SCAM! I was charged $92 after uploading money from a bitcoin atm and then after sending it to someone it WAS NEVER RECEIVED!!!! LIKE I SAID THIS IS A SCAM SITE!!! DO NOT USE IT!!!

**Comment by matiu** [comment]
As I mention before, Bitpay does not charge anything. You bought Bitcoin on a ATM and the charge is from the ATM vendor.
