### ISSUE TITLE
Missing funds

### ISSUE THREAD

**Issue by Ess2222** [bitpay/copay#11233]
Hi, 
I bought Bitcoins through Wyre-Buy Double Bay via Copay on 30th October, the money has been taken from my credit card but the Bitcoin is not yet showing up in my Copay balance and it has been 5 days. Please help - thanks

**Comment by matiu** [comment]
You need to contact Wyre-Buy and ask for a TXID, then check if that TXID is already on the blockchain. Copay will only show that is on the blockchain.
