### ISSUE TITLE
BitPay Gift Card issues

### ISSUE THREAD

**Issue by 4716MMBK** [bitpay/copay#11386]
I wanted to buy an Amazon gift card of a small amount to test the reliability of BitPay's service,
and encountered an issue.

I've been getting the message that says "could not claim code. Please contact BitPay support."
The outgoing payment is listed in Insight, maybe theres an error at copay's side?
So I tried looking for a solution on the support page, but couldnt find anything that solves
the problem im facing. I'm hoping that creating this post will solve the issue, if you need any information contact me.

4716.MMBK@protonmail.com

**Comment by Danilo-caio-da-silva-vieira** [comment]
you have the option when entering your own registration profile with your own name it will not be possible to use another person's name other than your own registration name ok

**Comment by 4716MMBK** [comment]
After 1 or 2 mails the issue was solved thank you for the support.
