### ISSUE TITLE
Mutisig HD Paper Wallet

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#1169]
1. add QR to #more -> show private key
2. add a `print` option
3. add QR reader to #create &  #join -> advanced priv key and  

@dskloet suggested:
A paper wallet could have the complete pub key ring, so, for example, in a 2-3 wallet, only 2 copayers will be needed to recover funds.

**Comment by matiu** [comment]
BWS already implements this feature, and can be accessed from BW https://github.com/bitpay/bitcore-wallet

**Comment by dskloet** [comment]
Don't you think it should be part of Copay, @matiu?
