### ISSUE TITLE
Use invoices instead of creating addresses

### ISSUE THREAD

**Issue by eordano** [bitpay/copay#1188]
A user should create an invoice instead of creating an address to receive money.

* An invoice contains:
  - name of the payer
  - what address is that user going to use
  - a note (why was this invoice created)
  - an amount in satoshis
  - amount in fiat at the time of invoice creation with the fiat currency created
    * something like {amount: 50, currency: 'USD'}
  - creation date
  - status
    * this status is updated with new transactions to the address

Two more views are needed: a view for a pending invoice and a paid invoice. See the screenshots for more information at the end of this issue.

The user can see a list of invoices created ordered by creation date.

An invoice detail screen shows transactions sent to this address. The date the invoice was paid is formated human readable, like "2 days ago".

A non-paid invoice should show a QR code and the address to pay.

![08-receive](https://cloud.githubusercontent.com/assets/42750/4047577/704133ea-2d3b-11e4-9d47-ef50abfd8763.jpg)
![09-invoice-pending](https://cloud.githubusercontent.com/assets/42750/4047578/70461608-2d3b-11e4-916c-643a0e520f8c.jpg)
![10-invoice-paid](https://cloud.githubusercontent.com/assets/42750/4047579/704a1eec-2d3b-11e4-83da-c3ff1dd94259.jpg)

**Comment by matiu** [comment]
Using automatic new address was chosen instead this approach.
