### ISSUE TITLE
Make wallet creation work asynchronously

### ISSUE THREAD

**Issue by maraoz** [bitpay/copay#1502]
I think it currently works, but the UI is confusing. To solve this issue, you should be able to do the following with no weird UI problems / confusing parts:

1. create new 2-of-3 wallet with copayer A
2. send wallet secret to copayer B and C
3. copayer A exits copay
4. copayer B joins wallet, and exits copay
5. copayer C joins wallet, and exits copay
6. all copayers open the wallet independently and create the backup
7. when they reopen the wallet, they should be able to use it normally

**Comment by matiu** [comment]
fixed at: https://github.com/bitpay/copay/pull/2502
