### ISSUE TITLE
Add ability to manually sign a message 

### ISSUE THREAD

**Issue by bluewookie** [bitpay/copay#1537]
The ability to sign a specified message using the wallet's key to prove that a message came unchanged from a wallet owner.

**Comment by fczuardi** [comment]
did this got implemented? I think he means the ability to sign any arbitrary sting, a feature like this: https://forum.bitcoin.com/beginners-help/guide-how-so-sign-a-message-with-blockchain-info-t436.html

**Comment by XBTdev** [comment]
+1 for this feature... but it should be under Advanced > Wallet information > then user will tap on the address he wants to sign a message with

**Comment by fczuardi** [comment]
@matiu can this be reopened?

**Comment by matiu** [comment]
sure, it is not a priority for us, but if someone wants to send a PR, will be happy to review it. I agree with the UX proposed by @XBTdev

**Comment by matiu** [comment]
Closing this one since it is not on the current roadmap. As said before, if someone wants to implemented it we can review it.

**Comment by rrous** [comment]
Pls, reopen ... it is necessary for https://www.bitstock.com/en
