### ISSUE TITLE
Error showing twice when trying to broadcast a txp

### ISSUE THREAD

**Issue by isocolsky** [bitpay/copay#1566]
![image](https://cloud.githubusercontent.com/assets/2073468/4598451/0d6fb182-50b9-11e4-9127-5e8268adb775.png)

To reproduce:
1) Create 1-2 wallet on local insight server
2) Shut down bitcoind instance
3) Create TXP

**Comment by matiu** [comment]
fixed at https://github.com/bitpay/copay/pull/2502
