### ISSUE TITLE
can't import old android wallet

### ISSUE THREAD

**Issue by maraoz** [bitpay/copay#1734]
I wasn't able to migrate my old Android wallet to new copay.
This is the error I get:
![screenshot from 2014-11-06 15 24 39](https://cloud.githubusercontent.com/assets/287189/4941565/589e9e1c-65e4-11e4-94db-5685c8a655ae.png)

And the header remains like this forever:
![screenshot from 2014-11-06 15 24 49](https://cloud.githubusercontent.com/assets/287189/4941575/6ed67fce-65e4-11e4-88b1-bbb3fb9bf1ba.png)

**Comment by matiu** [comment]
We not longer provide compatibility for <0.8. 

To retreive funds from <0.8, it is necessary to pull the source code and build copay for that version.
