### ISSUE TITLE
Support Firefox OS

### ISSUE THREAD

**Issue by gordonwritescode** [bitpay/copay#1820]
There only seems to be one bitcoin wallet available and it is lacking many of the great features offered by Copay.

I'd like to see Copay in the Firefox OS marketplace. This should be relatively easy. 

We should replace Copay's custom notifications with the W3C desktop notifications since this will tie into the FxOS native notification system as well.

**Comment by martindale** [comment]
+1 on this.

**Comment by matiu** [comment]
This is not on the current roadmap, and will require significant amount of work fiven that the set of plugins we use for cordova do not support firefoxOS.
