### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by DanyAlos** [bitpay/copay#1915]
Hi guys.
When trying to login after setting up a shared wallet I am sent directly to that wallet and cannot do nothing else. There is no HOME button or nothing. I got stuck there. Am I doing something wrong?
![captura de pantalla 2014-12-01 23 37 42](https://cloud.githubusercontent.com/assets/4530548/5257296/d37136ca-79b4-11e4-886d-08ca06943b01.png)

**Comment by matiu** [comment]
This is obsoleted by https://github.com/bitpay/copay/pull/2502 in which wallet creation works truly async.
