### ISSUE TITLE
keep PIN active longer - loses a partially composed spending proposal

### ISSUE THREAD

**Issue by tonygallippi** [bitpay/copay#2046]
when switching from Copay to another app, then back to Copay, I need to re-enter PIN.  We should put a timeout on this to keep the PIN session if I haven't been gone for more than X time.  1 minute?

Also, if I am composing a Send proposal, leave the app, re-enter PIN, my partially composed Send proposal is gone!

**Comment by matiu** [comment]
obsoleted by BWS.
https://github.com/bitpay/copay/pull/2502
