### ISSUE TITLE
Payment Protocol not working on Chrome Extension

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#2189]
again.
![copay_-_multisignature_wallet](https://cloud.githubusercontent.com/assets/98844/5476795/457ef62a-8604-11e4-953d-c25a26417eab.png)

Related: https://github.com/bitpay/copay/commit/cec0e2c4de8160797287599d2fac53c8b25c05be

**Comment by bitjson** [comment]
I think this can be closed since the platform is being deprecated anyways – #4909
