### ISSUE TITLE
Unable to import wallet

### ISSUE THREAD

**Issue by lquessenberry** [bitpay/copay#2193]
my friend Greg Darden and I share a wallet. The wallet was created and we both downloaded backups. He is unable to import his backup to his copay account. We have secret keys and the backup file and are unable to retrieve our coin

**Comment by isocolsky** [comment]
Hey guys, I'm closing this. Please let me know if this is still an ongoing issue.

**Comment by lquessenberry** [comment]
Hey I am sorry I got sidetracked. Let's see what we can do to release this coin.

**Comment by lquessenberry** [comment]
I'll get with you asap. I'm mobile at the moment

**Comment by felipelalli** [comment]
I have the  same issue. I made several tests in Chrome app and web app but all failed. Possible duplicated: #2230

**Comment by matiu** [comment]
closing this one, no feedback. please let us know if still relevant.

**Comment by lquessenberry** [comment]
Hey,

Sorry to open an old ticket, but I am trying to get the coins out of the
account and I am having a hard time doing so. My partner has become non
responsive, but I have his AES file that seems to be corrupt. I have
successfully imported the wallet and signed into it myself, but I can't
make any withdrawals without his signature. The problem is that in the past
he has been unable to import his wallet to do so. I do have the wallet and
his password. We're just trying to get the coin out of the wallet for now.

Thanks,

Lee Quessenberry
