### ISSUE TITLE
Improve profile reading from insight

### ISSUE THREAD

**Issue by isocolsky** [bitpay/copay#2204]
*Note: to check this behavior I had to simulate a corrupt wallet.*

If a profile "points" to a wallet that was not correctly saved, Copay will halt like this:

![image](https://cloud.githubusercontent.com/assets/2073468/5505468/fcadcb0c-876f-11e4-97fd-c8b4b2558b1d.png)

It should skip the corrupt wallet and continue opening the profile. Give feedback to the user about the corrupt wallet and let them take action (deleting if not yet complete or overwrite with backup)

**Comment by matiu** [comment]
obsoleted.
