### ISSUE TITLE
Wallet home screen provides no function

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#2223]
092 iOS maybe the wallet home screen should display the transaction history below the info already there.  I could then see and scroll the tx history from that screen - other wallet have the tx history as their home screen.

**Comment by KeyJockey** [comment]
LOL this is a really old issue report, I'm relatively NEW to Copay compared to you guys... but yeah regardless, I agree with this idea too

From a cleaner UI perspective, it'd be a gain to combine the current HOME screen design at the TOP with the fourth tab's "history" page, scrolling down past transactions at the bottom of the same tab on main/home screen.  

This would allow Copay to have only three tabs overall, or free up the current 4th tab for other future added functionality... here's a quick sim what it could look like: 

![3tabs](https://cloud.githubusercontent.com/assets/13903392/9571368/717482ba-4f6a-11e5-93bf-0fe87d1caf7b.png)

**Comment by matiu** [comment]
this is been considered in the next UX iteration. Thanks.
