### ISSUE TITLE
Deleting proposed transaction should be easier

### ISSUE THREAD

**Issue by mcelrath** [bitpay/copay#2227]
Deleting a proposed transaction is hidden in Settings->"Purge Pending Transaction Proposals".  This is rather hard to find.  Instead, allow transaction proposals to be deleted directly from a button on the "Home" screen.

**Comment by matiu** [comment]
fixed at https://github.com/bitpay/copay/releases/tag/v0.10.0

(creator can delete TX proposals with no extra signatures with a click.
