### ISSUE TITLE
Wallet backups cannot be imported

### ISSUE THREAD

**Issue by mcelrath** [bitpay/copay#2230]
When importing a backup using a logged in wallet, I get this error message: 
```Could not read wallet. Please check your password```

When using the "import" button at the bottom before logging in, I get the message: ```Unknown error```.

**Comment by felipelalli** [comment]
I have the same issue here. I made several tests and all failed even with fresh new wallets. The json generated in "backup" simply does not work to import a new wallet. The error occurs: "Unknown error"

**Comment by cmgustavo** [comment]
Did you make a backup from the profile or wallet? If you have a profile 's backup, try to import from home page. If you have a wallet ’s backup, try to import inside a created profile (add wallet -> import). Keep in mind if your backup is from a profile (local or remote), check the configuration to use LocalStorage or RemoteStorage (insight) before to import.

Please, let me know if you already did what I explained above.

**Comment by felipelalli** [comment]
Hi @cmgustavo I didn't know that were two kinds of backups. But I guess my backup is of a profile because the file call "<myname>.profile" - << check the configuration to use LocalStorage or RemoteStorage (insight) before to import. >> I did not understand this part. How can I do that? Thank you.

**Comment by thoatbk** [comment]
Go to the home screen where you login, the bottom right button says Settings. Go on there and change the Profile location to either Local storage or Insight; just try both, that error usually means you are importing a profile that was done on insight to local storage or vice versa.

**Comment by felipelalli** [comment]
:+1:  @thoatbk wow, that's it! Are you serious? Is there a issue to solve that? For me it is a bug, it is impossible to guess that. Thank you.

**Comment by thoatbk** [comment]
this should fix it when its done: https://github.com/bitpay/copay/issues/2354
