### ISSUE TITLE
Rejoin lost wallets

### ISSUE THREAD

**Issue by mcelrath** [bitpay/copay#2239]
I have a problem related to #2229 and #2230.  We created a 2-of-2 copay wallet, stored on the Insight server.  This was lost (See #2229) and after some time logging in the copay wallets did not appear.  This is very reproducible.  My guess is that it's a problem with Insight -- wallet backups pushed to the server are not updating the original, and only the first wallet backup is stored. The second of the two wallets was local (HTML5 storage) and continues to work.

So one of these two copayers cannot open the wallet.  It's necessary to rejoin this wallet to spend any funds in the wallet.  So the copayer with the open wallet needs to be able to send something to the other copayer so that he can "rejoin" the wallet.

I'm stuck in the situation now of hacking your BIP32 master keys, derived keys, and paths, to find the keys for the address in the wallet.  This could be very easily solved by a "rejoin wallet" functionality.

When I click "Join Shared Wallet" and enter the shared key, the wallet runs off into la-la land "connecting to insight sever" and never comes back.  On the other user's side I cannot "re-create" an existing wallet (since both parties must be "online" for this to work -- and it did work initially -- and the wallet already exists!).  If a wallet cannot be joined, for whatever reason, a specific error message needs to be issued, with specific instructions as to how to accomplish this.  Currently the wallet "hangs" when trying to join a wallet and the other party isn't online.

**Comment by matiu** [comment]
Hey, where you able to fix this? Note there there is an option on 'More -> advanced -> SCAN' to derive addresses automatically to look for funds.

**Comment by matiu** [comment]
closing this one, no response.

**Comment by mcelrath** [comment]
We did solve it, and it seems the bug was fixed sometime with 0.9.2.
