### ISSUE TITLE
Improve the "Import profile" using localstorage on mobile

### ISSUE THREAD

**Issue by cmgustavo** [bitpay/copay#2245]
* After to click on import, nothing happens. Should display a loading message.
* Importing a localStored profile with the configuration setted to cloudStorage, it gives an unknown error.
* After import, save all wallets automatically. If you don't close the app with "Close" button, your wallets won't be saved in localStorage.
* Simplify the content of backup. Perhaps deleting the history or notes. Avoid make big the backup file.

**Comment by matiu** [comment]
fixed at https://github.com/bitpay/copay/pull/2502
