### ISSUE TITLE
Trezor Support

### ISSUE THREAD

**Issue by martindale** [bitpay/copay#2251]
I'd like to use my Trezor to sign transactions through Copay.

**Comment by vermorel** [comment]
Would be very nice indeed.

**Comment by jaimenm** [comment]
+1

**Comment by lichtamberg** [comment]
Yeah, please integrate trezor!

**Comment by chrisrico** [comment]
I would also love this. Even if it required usage of trezord (Trezor Bridge) for ease of integration, that would be great. I'd even contribute to a Lighthouse project to prioritize this feature.

**Comment by matiu** [comment]
This one is coming soon! Stay tunned!

**Comment by nolim1t** [comment]
+1 for trezor support

**Comment by lichtamberg** [comment]
nice, thanks!!!

**Comment by jmaurice** [comment]
Now that 1.1 has been released, any update on the trezor integration? Thanks!

**Comment by koalalorenzo** [comment]
+1 I am looking for that too!

**Comment by lichtamberg** [comment]
+1!

**Comment by jmaurice** [comment]
Thanks, but it seems the Trezor support is Chrome only right now? Are you guys working on Android support, like how mycellium's Android app connects to trezor using a USB OTG cable? This would make copay the only mobile wallet with hw multisig support!
![20151212_140113](https://cloud.githubusercontent.com/assets/232186/11764305/60a0ad80-a0df-11e5-8739-f6cee37906bd.jpg)
