### ISSUE TITLE
Some devices stuck waiting for copayers

### ISSUE THREAD

**Issue by michelf** [bitpay/copay#2257]
Tried creating a 2-of-4 wallet to see how it'd work. First account created with the web app with Safari, the three other accounts with the Chrome app and two iOS devices (last three stored in localstorage). Went like this:

1. created wallet with the web app in Safari
2. scanned Safari's code with the camera on the first iOS device
3. scanned Safari's code with the camera on the second iOS device
4. scanned code shown on one of the iOS devices after joining (below the "share this secret with your copayers") with the Chrome app

This last step didn't work. The Chrome app complained about not being a valid code or something (sorry, I don't have the exact error message). Fine, so I copy-pasted the code from Safari to proceed and it seemed to work at first, but it got stuck in the "Waiting for copayers" state, with a single copayer shown below the QR code (other devices still had three copayers on display, waiting for the fourth, as before).

So to fix things I created another account in the Chrome app, went to join the wallet by copy-pasting the code from Safari to Chrome, and it worked!... oops, only partially. Now I have the Chrome app and Safari presenting me a working wallet, but the two iOS devices are stuck in the "Waiting for copayers" state.

Sorry for the convoluted process. Perhaps someone will have the patience to try it again and/or reduce the bug to something simpler.

**Comment by MrDunne** [comment]
https://github.com/bitpay/copay/issues/2243

Same issue

**Comment by matiu** [comment]
this should be fixed at https://github.com/bitpay/copay/releases/tag/v0.10.0
(new wallet creation protocol)
