### ISSUE TITLE
Windows Phone - Scroll requires flicks, won't respond to hold-down scroll

### ISSUE THREAD

**Issue by JawedAshraf** [bitpay/copay#2280]
Vertical scrolling (e.g. on Settings page in Advanced Options mode) appears to require the user  to perform "flicks" where the finger contacts, swipes and then lifts-off.

When user holds contact while attempting to scroll, without lifting-off, no scrolling occurs. Accidental scrolling may occur if the user is swiping at the time they lift their finger off the screen.

**Comment by matiu** [comment]
should be fixed on v0.10. Thanks for the report.
