### ISSUE TITLE
Wallet associated with account disapeared

### ISSUE THREAD

**Issue by lincolnerickson** [bitpay/copay#2285]
I signed up for copay using the web app on firefox 34.0.5.  The app made a wallet and gave me an address to send money to.  I chose to let insight manage the wallet.  I funded the wallet.  I logged into the same account on the app on my windows phone 8, 8.1 developer preview.  I was able to access the same account and wallet on the phone.  I saw a notification saying I needed to verify my e-mail.  I found the email and clicked on the link.  The link prompted me to login again but I just closed the tab as I was already logged in.

I went to my phone and 'locked' the phone to test my pin.  When I entered the pin, the phone app said I had no wallet associated with my account.  When I refreshed the app page on my computer it said the same thing.  I tried to click on the verification e-mail again but it gave this error "{"error":"Email already confirmed or credentials not found"}"

I still have access to the account and the password.  I know the address in the missing wallet I sent the bitcoins to.  I have no backup.  The wallet went missing within minutes and I hadn't got around to testing the backup feature.  I did not delete my profile or if I did it was not obvious I was doing so.

thanks for any help

**Comment by matiu** [comment]
Hi, I am sorry you are having problems with Copay. Given your problem I think it will be better for us to meet at chat. Can you join us at  https://gitter.im/bitpay/copay ? I am 'ematiu' there. I can be there tomorrow, just ping me.

**Comment by lincolnerickson** [comment]
Hello

I am available to talk.  i opened a chat on the link you gave me.

thanks

Lincoln Erickson
Rook's Comics and Games
2740 West Main ST
Bozeman, MT 59718
406-556-2153

**Comment by cmgustavo** [comment]
Fixed (#2324)
