### ISSUE TITLE
mobile apps -> should get language configuration from device settings.

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#2288]

**Comment by thoatbk** [comment]
To extend that further... as we use angular moment, we should also load and set the locales there

pseudocode: 
<script src="components/moment/locale/de.js"></script> //example for german

myapp.run(function(amMoment) {
    amMoment.changeLocale('de'); //example for german
});



Reason: No one here in europe uses weird am/pm stuff, we use 24 hours based system for example, in general the date and time sytems are so different in every region in the world, the day comes here before the month also (dd.mm.yyyy).
I guess its also the only way to translate strings like "xx hours ago" to other languages in the history tab of copay.


And last but not least, theres no way to translate the clipo images. So i guess it would be easiest to pack them into subfolders like 
en/clipo1.png 
... 
de/clipo1.png and load them depending on the language.

**Comment by matiu** [comment]
done.
