### ISSUE TITLE
What happens if your servers are compromised?

### ISSUE THREAD

**Issue by 5an1ty** [bitpay/copay#2291]
Our wallets are encrypted so that's ok but I noticed that when I take a backup of my profile I get a file named: email-profile.json. I hope all of our emails aren't stored in plaintext like that? A better option is to store the emails in a database and lookup their related profile file which is a JSON file with a randomly generated name.

**Comment by matiu** [comment]
Please see details of current Copay server needs at https://github.com/bitpay/copay/blob/master/README.md and https://github.com/bitpay/bitcore-wallet-service
