### ISSUE TITLE
What exactly can you do with a backed up profile?

### ISSUE THREAD

**Issue by 5an1ty** [bitpay/copay#2292]
Besides restoring your profile in copay? Is it possible to recover all wallets (including multi-sig) wallets in for example armory?

**Comment by thoatbk** [comment]
sure u can import the BIP32 master keys to Bitcoin core or whatever wallet supports it.

However electrum seeds would be a lot better and easier for this -> https://github.com/bitpay/copay/pull/2246

**Comment by 5an1ty** [comment]
But these don't get exported with your profile backup right? It would be interesting to have a button that gives you a backup file of every master key you have.

**Comment by matiu** [comment]
Yes, they are at the profile backup (encrypted)

You can see the extended master key at Settings (or more) -> advance ->

On Thu, Jan 8, 2015 at 11:59 AM, Ruben Callewaert <notifications@github.com>
wrote:

> But these don't get exported with your profile backup right? It would be
> interesting to have a button that gives you a backup file of every master
> key you have.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2292#issuecomment-69190254>.
>



-- 
BitPay.com

**Comment by 5an1ty** [comment]
So does that mean that I can import the profile backup file in bitcoind just like that?

**Comment by matiu** [comment]
no, backup formats are completely different. Copay is HD, multisig, it is
not possible to import it directly into bitcoind or armory.

On Thu, Jan 8, 2015 at 1:14 PM, Ruben Callewaert <notifications@github.com>
wrote:

> So does that mean that I can import the profile backup file in bitcoind
> just like that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2292#issuecomment-69202710>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by thoatbk** [comment]
well with mnemonic support in the pr mentioned above its easy to import to Electrum and whatever else supports mnemonics.

Its also way easier to backup a single master key if you just have to write down some words instead of a long ass hex key.

Is there a specific reason why that pr doesnt get merged in?

**Comment by matiu** [comment]
The HD derivation schema for Electrum is no the same for Copay (because
Copay is multisig). Importing the extended master key on Electron wont
work.

See https://github.com/bitcoin/bips/blob/master/bip-0045.mediawiki

On Thu, Jan 8, 2015 at 1:23 PM, thoatbk <notifications@github.com> wrote:

> well with mnemonic support in the pr mentioned above its easy to import to
> Electrum and whatever else supports mnemonics.
>
> Its also way easier to backup a single master key if you just have to
> write down some words instead of a long ass hex key.
>
> Is there a specific reason why that pr doesnt get merged in?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2292#issuecomment-69204085>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by 5an1ty** [comment]
I'm quite unfamiliar with HD wallets, multisig wallets, mnemonic keys, so my apologies for the stupid questions. Does bitcoind support mnemonic multisig wallets?

**Comment by thoatbk** [comment]
Ah damn, electrum 2.0 changed to BIP44, i somehow mixed that up with BIP45.

5an1ty, no you can´t bitcoin core has no support for mnemonics at all, and it seems that copay is the only wallet using bip45 atm, but i guess it should be possible for electrum to at least add support for importing 1 of 1 wallets of copay in the future.

**Comment by 5an1ty** [comment]
Sounds great, thanks for your patience with me both of you. I just wanted to make sure there is a backup plan if copay ever becomes unusable.

**Comment by matiu** [comment]
sure!

JFYI, there is a swipe tool that you can use, and you dont neet to use
copay and you can access your funds

https://github.com/bitpay/copay/blob/master/util/swipeWallet.js

On Thu, Jan 8, 2015 at 1:52 PM, Ruben Callewaert <notifications@github.com>
wrote:

> Sounds great, thanks for your patience with me both of you. I just wanted
> to make sure there is a backup plan if copay ever becomes unusable.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2292#issuecomment-69209154>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by diegoviola** [comment]
Is it possible to import my Copay backup file in Electrum? Please help, I'm a bitcoin noob.

**Comment by dabura667** [comment]
@diegoviola No it is not.

The only way you could import it into Electrum is if Electrum supported BIP45 multisig path derivation. Which it doesn't.

The next version of Copay (coming in a few days/weeks) will generate wallets with BIP44 path derivation for multisig and personal wallets, so if you have a multisig/personal wallet generated by Copay in the NEXT version, someone COULD make a plugin for Electrum to accept Copay backups.

However, (just reiterating for emphasis) this is impossible for any wallet generated with the current version of Copay or earlier.
