### ISSUE TITLE
WP: Profile Backup text cannot be selected or extracted from the  UI

### ISSUE THREAD

**Issue by drGarbinsky** [bitpay/copay#2299]
It is either not possible or very tricky / difficult to get the text out of the text box. The control type being used causes the keyboard to pop and obstruct the area of focus. 
Would be nice if a download to file or copy to clip board option was available.

platform: WP 8.1  Lumia 1520

**Comment by drGarbinsky** [comment]
It is possible to select the text for the individual wallet backup but it is also suboptimal.

**Comment by matiu** [comment]
thanks for the report, we will check that.

On Thu, Jan 8, 2015 at 10:17 PM, drGarbinsky <notifications@github.com>
wrote:

> It is possible to select the text for the individual wallet backup but it
> is also suboptimal.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2299#issuecomment-69279658>.
>



-- 
BitPay.com

**Comment by matiu** [comment]
outdated (passphrase backups are now offered)
