### ISSUE TITLE
Support multi-output transaction request

### ISSUE THREAD

**Issue by haight6716** [bitpay/copay#2300]
It appears the app does not support signed multi-output transaction requests.  This one is opened correctly by android bitcoin wallet, green address and bitcoin-qt:

    bitcoin:1NXXeQRyMFFFRfyUix2o7mk1vhvk2Nxp78?r=https%3A//www.syndicoin.co/signed.paymentrequest

aka

    https://www.syndicoin.co/signed.paymentrequest

When I open this link in copay, I receive "Error: Server sent a bad signature".

Edit: When scanning a similar transaction into the web-wallet via a QR code I receive: "Error: Illegal group end indicator for Message .PaymentRequest: 7 (not a group)"

Here's the QR code for that one:

http://i.imgur.com/GMmzENQ.png

**Comment by matiu** [comment]
dup: https://github.com/bitpay/copay/issues/170
