### ISSUE TITLE
My fund is locked because the proposal is not received.

### ISSUE THREAD

**Issue by autocoinage** [bitpay/copay#2302]
I have two accounts under info@autocoinage.com and ng.bernie@gmail.com 
I created a proposal under info@autocoinage.com
however, the proposal is never received at ng.bernie@gmail.com

Now the fund is locked and the proposal cannot be cancelled.
Please help and advise. Thanks.

**Comment by autocoinage** [comment]
![screen shot 2015-01-09 at 12 30 46 pm](https://cloud.githubusercontent.com/assets/10466619/5684117/7a5561b4-97fb-11e4-973f-1660591b012d.png)
![screen shot 2015-01-09 at 12 30 18 pm](https://cloud.githubusercontent.com/assets/10466619/5684116/7a5251d6-97fb-11e4-81c0-5f334c104541.png)

**Comment by autocoinage** [comment]
I cannot cancel nor resend the proposal at info@autocinage.com 
At ng.bernie@gmail.com it is not possible to view all the spending proposal  history & this request has never received.

**Comment by matiu** [comment]
You can go to "settings" => advanced => purge pending tx proposals.  You
need to do that in all copayers.

On Friday, January 9, 2015, autocoinage <notifications@github.com> wrote:

> I cannot cancel nor resend the proposal at info@autocinage.com
> <javascript:_e(%7B%7D,'cvml','info@autocinage.com');>
> At ng.bernie@gmail.com
> <javascript:_e(%7B%7D,'cvml','ng.bernie@gmail.com');> it is not possible
> to view all the spending proposal history & this request has never received.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2302#issuecomment-69368444>.
>


-- 
BitPay.com

**Comment by autocoinage** [comment]
THanks for the instruction.
