### ISSUE TITLE
Confirmation emails (sometimes?) not being sent

### ISSUE THREAD

**Issue by hkjn** [bitpay/copay#2303]
I've signed up for Copay using the web version some days ago, as well as downloaded and signed into the Android app earlier today. Both remind me that my email is not confirmed, I've clicked "resend" and gotten notifications that the email has been sent again, but I've never received any emails. (I've confirmed that they're not being marked as spam or anything like that.)

The email address I used was me@hkjn.me; you have my permission to check my account status to see if your systems believe that confirmation emails were sent out.

Let me know if I can provide any further information.

**Comment by matiu** [comment]
https://github.com/bitpay/copay/releases/tag/v0.10.0 does not use emails any more. Closing this one since it is obsoleted.
