### ISSUE TITLE
Windows Phone - Nokia 1020

### ISSUE THREAD

**Issue by SACarter** [bitpay/copay#2304]
When trying to send payment, program switching main camera lens, unable to focus on barcode and pickup details....

**Comment by nimchak** [comment]
same issue with Nokia Icon.

**Comment by eaxvac** [comment]
When you are in the camera page, you can't navigate back too unless a QR code is scanned.

Tested that on Lumia 1520, 1020

**Comment by matiu** [comment]
This is a known error of the QR plugin for Windows Phone. it is reported and fixed here:
https://github.com/phonegap/phonegap-plugin-barcodescanner/pull/3

we are waiting it to get merged. Closing it here.
