### ISSUE TITLE
Crash on ADDRESSBOOK message handling after sending a transaction (UPDATED)

### ISSUE THREAD

**Issue by mxmauro** [bitpay/copay#2308]
Hi,

After sending a payment, a copayer's instance generated an exception on BitCore's Address validation (Actually on VersionedData's constructor)

Examining the stacktrace and code I believe the problem is located on **js/models/Wallet.js** @ *line 661*

    if (key && !self.addressBook[key] && Address.validate(key)) {
 
should say:

    if (key && !self.addressBook[key] && Address.validate(value)) {

In our test, the *key* variable had a value of 1.

Regards,
Mauro.

**Comment by matiu** [comment]
Thanks for the detailed report. Is this preventing you to access the wallet?

**Comment by mxmauro** [comment]
Hi Matiu,

Yes. We are developing a service that interacts with Copay running on a local server and that's why we could reach there.

Kind regards.

**Comment by matiaspando** [comment]
Hi Mauro:
         Thanks for reporting an issue. Actually the line
if (key && !self.addressBook[key] && Address.validate(key)) {

is correct because the 'key' is the bitcoin address and the 'value' is an object with this structure
 {
    hidden: boolean,
    createdTs: timeStamp,
    copayerId: string,
    label: string,
  };

Check the method setAddressBook on line 2615

**Comment by mxmauro** [comment]
I'll will investigate further why the key had a value of "1".

Thank you.

**Comment by mxmauro** [comment]
Hi, the steps for reproduce the issue are the following:

1. Create a 2-2 multisig wallet in one account
2. Join the 2-2 wallet using another account.
3. Go to send money in the first account and add two addresses in the address book.
4. Log out from the secondary account and relogin. After the address book is updated, you will see in, for e.g., chrome's console ouput an error like this:

Uncaught TypeError: Cannot read property 'length' of undefined / vendors.js:30

While the browser fires an uncaught exception, if using copay under nodejs, the process exits with an error.

The received keys are "0" and "1", instead of valid bitcoin addresses. When key=0 the if in _onAddressBook resolves to false but when 1, the problem appears.

Best regards,
Mauro.

**Comment by matiaspando** [comment]
Thanks Mauro for reporting an issue, this PR will fix that.
