### ISSUE TITLE
Insufficient funds

### ISSUE THREAD

**Issue by thaxy** [bitpay/copay#2315]
Guys,

why isnt this working? I have over 100 confirmations on my address. I am really paranoid that my funds are gone. How can I fix this?

![wp_ss_20150116_0001](https://cloud.githubusercontent.com/assets/1968007/5777210/7081ef14-9d90-11e4-9f19-6221198ab673.jpg)

**Comment by bechi** [comment]
Thanks for your feedback. We already work on that.

**Comment by thaxy** [comment]
Cool, maybe I can help you with that?
I will attach my History. My first transaction was a test of ~14k bits.
I was able to send them to my other wallet. But after the 2nd charge of 2kk bits I cant send them.

![wp_ss_20150116_0003](https://cloud.githubusercontent.com/assets/1968007/5777451/c8e65b3e-9d92-11e4-9482-6e65f7bace9e.jpg)

**Comment by matiu** [comment]
Hey @thaxy  can you meet us online at https://gitter.im/bitpay/copay so we can see this one on more detail? thanks.

**Comment by matiu** [comment]
Closed it #gitter.
