### ISSUE TITLE
Can't Join Wallet

### ISSUE THREAD

**Issue by pipaman** [bitpay/copay#2320]
I'm trying to join a multi signature wallet. I create the new wallet but when I try to join the wallet from another account it keeps loading forever.
I'm using TESTNET.

**Comment by thoatbk** [comment]
Is it stuck on that grey loading screen with the rotating balls on it?
What device and os + browser (if used)?

**Comment by pipaman** [comment]
I'm using Windows. It's stucked on the 'Connecting to Insight Wallet Server'.
![copay-error](https://cloud.githubusercontent.com/assets/5437398/5803540/f5e764aa-9fdd-11e4-929d-956db2a0a3dc.png)

**Comment by thoatbk** [comment]
Thats the screen i meant,

And the other device you are trying to peer with? and what browser are you using?
Do you use the bitpay insight server?

**Comment by pipaman** [comment]
I tried with 2 windows from the UI. I've tried doing it by code on a Linux and a Windows. And also, 2 Linux by code.

**Comment by lukem512** [comment]
I am also experiencing this issue. It seems that the socket.io is timing out for some reason: ````http://insight.website.com/socket.io/?EIO=3&transport=polling&t=1428134777034-187&sid=tllclHrF6p9IvKn3AAAH````

**Comment by matiu** [comment]
wallet creation was completely rewritten at https://github.com/bitpay/copay/releases/tag/v0.10.0 to use Bitcore-Wallet-Service. Now, wallet creation is truly async and should be much more stable, please let us know if you have still problems.

**Comment by pipaman** [comment]
Great!
