### ISSUE TITLE
Unable to import backup from old Copay wallet

### ISSUE THREAD

**Issue by jaimenm** [bitpay/copay#2321]
I had a Copay wallet from several months ago which I made a backup of (.aes file) Now I'm trying to Import that file but I always get the "Bad password or corrupt profile file" message.
I have two questions:
1) What were the password constraints before October 24, 2014?
2) Is it the backup file from October 24, 2014 compatible with the current wallet version?

Thanks

**Comment by matiu** [comment]
Could you try checking out a version from that time (
https://github.com/bitpay/copay/releases/) and importing there?

On Mon, Jan 19, 2015 at 12:25 PM, jaimenm <notifications@github.com> wrote:

> I had a Copay wallet from several months ago which I made a backup of
> (.aes file) Now I'm trying to Import that file but I always get the "Bad
> password or corrupt profile file" message.
> I have two questions:
> 1) What were the password requirements before October 24, 2014?
> 2) Is it the backup file from October 24, 2014 compatible with the current
> wallet version?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2321>.
>



-- 
BitPay.com

**Comment by jaimenm** [comment]
I'll try and let you know, thanks

**Comment by matiu** [comment]
closing this one. please reopen if still active.
