### ISSUE TITLE
Windows Phone wallet disappeared

### ISSUE THREAD

**Issue by ttt777** [bitpay/copay#2325]
I made a Copay wallet with my Windows Phone. First I could see my wallet and I sent bitcoins there. Then I logged out and when I logged back in I had no wallet there. I think this is the same problem as #2285

**Comment by matiu** [comment]
Hey, can you join us at https://gitter.im/bitpay/copay so you can describe this further? 

thanks.

**Comment by matiu** [comment]
closed by gitter.

**Comment by cmgustavo** [comment]
Fixed since 0.9.5 (#2324)
