### ISSUE TITLE
Coinbase PaymentRequest bad signature

### ISSUE THREAD

**Issue by frolswe** [bitpay/copay#2329]
When I try to send Coinbase payments with Copay (Android),  verification of the BIP0070 PaymentRequest fails. Thus Copay prevents me from sending the payment without manually removing the payment request and sending directly to the address. See the attached image for the "Error: Server sent a bad signature." message.

I have tried both v0.9.5 and v0.9.4.
The Greenaddress wallet displays the same payment request as valid.

To reproduce this, try any Coinbase transaction, e.g. their demo donation button:
https://www.coinbase.com/docs/merchant_tools/payment_buttons

Thanks
/Fredrik

![signaturefailure](https://cloud.githubusercontent.com/assets/1169612/5826375/9f8c6e6e-a0f2-11e4-837f-6536f4fe8831.png)

**Comment by cmgustavo** [comment]
Hi @frolswe, 
Thanks for reporting. I can reproduce this error on mobile and desktop (using my local environment):

```
XMLHttpRequest cannot load https://www.coinbase.com/r/54cfd33b8912308d740000d4. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

copayBundle.js:8615 [warn] Error: Status: HTTP Request Error: This endpoint likely does not support cross-origin requests.
```

We will find a solution as soon as possible.

**Comment by thoatbk** [comment]
Thats a cors request error? Means they block cross domain usage, ie u can´t load their website from within the app or an external website.

The only sane fix would be for Coinbase to learn how to run a webserver imho ;)

**Comment by matiu** [comment]
It could be an error on Copay side, parsing the payment protocol. I
remember running into that error ('This endpoint likely does not support
cross-origin requests.') when the actual problem was paypro parsing and not
related to the server. we need to look further into this one.

On Mon, Feb 2, 2015 at 5:10 PM, thoatbk <notifications@github.com> wrote:

> Thats a cors request error? Means they block cross domain usage, ie u
> can´t load their website from within the app or an external website.
>
> The only sane fix would be for Coinbase to learn how to run a webserver
> imho ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2329#issuecomment-72528222>.
>



-- 
BitPay.com

**Comment by matiu** [comment]
I was not able to find payment protocol generating buttons at https://developers.coinbase.com/docs/merchants/payment-buttons.
(only: "pay this amount to this address" type of payment requests)

Please reopen if this is still relevant. thanks.
