### ISSUE TITLE
Can't Join Wallet and can't get proposal notifications

### ISSUE THREAD

**Issue by pipaman** [bitpay/copay#2330]
Hi,
I'm writing again because I didn't get any response. I'm using a multi-signature wallet on TEST NET.

I can't join a wallet from the second party. Also, I have some wallets which were joined before, and I can't get the transaction proposal notification on the other party.

Please, answer if you will fix it or if you won't do it.

Thanks on Advance.

**Comment by matiaspando** [comment]
Hi ,
      Yesterday we release version 0.9.5 which includes a fix for Windows Phone that was related with the problem that you mention. Please check the new version and let us know

**Comment by cmgustavo** [comment]
Sorry, we are having problems with insight-testnet, the messages are growing up too fast, so the service is currently offline. We are trying to solve this problem as soon as possible. This issue only affects TESTNET. So you can't join or receive any transaction proposals.

**Comment by pipaman** [comment]
Thank you for the information and fast response. Do you know when it is planned to be solved since I've been experiencing this issue from 1 week.

**Comment by cmgustavo** [comment]
insight-testnet is up and running.

Thanks!
