### ISSUE TITLE
Stuck transactions and funds

### ISSUE THREAD

**Issue by 21xhipster** [bitpay/copay#2331]
3 transactions stuck already:
![screen shot 2015-01-21 at 19 13 20](https://cloud.githubusercontent.com/assets/410789/5841149/4c2ac6d8-a1a3-11e4-9582-832beac7eedb.png)

One of which:
![screen shot 2015-01-21 at 19 26 39](https://cloud.githubusercontent.com/assets/410789/5841169/7e1cec66-a1a3-11e4-8f45-d7c82e7d0d09.png)

Please help to solve. Need to withdraw funds

**Comment by matiu** [comment]
You can erase pending transactions proposals and try again? In settings-> advanced -> purge

**Comment by cmgustavo** [comment]
Hi, this error seems to be a problem with the internet connection at the moment to send the transaction to the blockchain. We 'll add a button to re-send the transaction soon #2332.

Thinking little more about the problem, I can see you created the proposal 2 months ago (maybe you already spent the outputs). Anyway, you can try to "purge" the pending transaction proposals from all 5 users and create it again. This option is for advanced users (go to Settings -> Show advanced options -> purge) and should do all the users at the same time.

**Comment by thoatbk** [comment]
It may be wise to iterate through the stored tx proposals on every wallet login/after entering the pin and check them again?
And in case they are invalid now prompt the user to delete them or so.

**Comment by 21xhipster** [comment]
@thoatbk Thanks for notice about weird name - it wasn't setup up in cyrillic. Nonetheless - it is )
@matiu Thanks!. Didn't know about this function.. It help
@cmgustavo No. We didn't spend outputs yet

**Comment by 21xhipster** [comment]
Guys! Appreciation for your work :-) I've post small [bounty](https://www.bountysource.com/teams/bitpay) on Bountysource. Join!
