### ISSUE TITLE
Android app / receive money; ability to include amount

### ISSUE THREAD

**Issue by marvin8** [bitpay/copay#2333]
Hi Guys

Just trying our your CoPay android app and really loving the multi signature aspect of it.

There is one thing though that prevents me from making CoPay my everyday mobile wallet.
I am currently using mycelium wich allows me to enter an amount on the receive bitcoin to make it easier for other people to pay me in bitcoins. 

What makes this feature really powerful is the possibility of setting the preferred source for bitcoin exchange rates and enter the amount requested in the fiat currency I defined in the settings as well.

The above to features make it really easy to accept payments for products that are priced in (in my case AUD). E.g. if I sell something that has an agreed price of $12 AUD I am able to go to the receive screeen in mycelium, add an amount of $12 AUD, which is automatically converted to bitcoins using the exchange rate of my preferred currency conversion rate source. This is turn then displays a QR code that includes my bitcoin address and the amount in bitcoins corresponding to $12 AUD. The payer only needs to scan this QR code and hit send. 

I'd love if CoPay was able to do this as well. I would then be able to easily make CoPay my everyday wallet.

Any chance of this being implemented in the near future?

**Comment by cmgustavo** [comment]
Hi @marvin8, I 'm glad to hear you like Copay! I think we will implement this functionality as soon as possible, but we are discussing some details (#2342). I will let you know when we do it.

Thanks!

**Comment by fczuardi** [comment]
Documentation on how to build a bitcoin URL with an additional amount parameter can be found here: https://bitcoin.org/en/developer-guide#payment-protocol

The basic version of a fix/implementation to this issue could simply be the addition of an ```?amount=value``` parameter into the string of the QR image without worrying about using the payment protocol with a proper ```r``` parameter for now…

**Comment by matiu** [comment]
done.
