### ISSUE TITLE
Mobile: hide QR code on Receive

### ISSUE THREAD

**Issue by cmgustavo** [bitpay/copay#2342]
* Only show 2 buttons: 

1) Receive a payment (when click on it, generate new address and display the optional field to input an amount). Show generated QR code using BIP-21

2) Show all addresses (maybe a popup?)

**Comment by tonygallippi** [comment]
If I want to receive bitcoins from someone standing next to me, I need the QR code.

**Comment by cmgustavo** [comment]
I know. The idea is to avoid rendering the whole page if you are just browsing your wallet. After click in the button display the QR code or enable the option to input the amount to receive inside the QR code using BIP-21

**Comment by tonygallippi** [comment]
that's an extra click.  I think if I click the receive button, it's ok to render a QR code right away for a Quick Receive.  We shouldn't have extra clicks if we can avoid them.

**Comment by cmgustavo** [comment]
Agree, I don't like to do extra click, but I 'm just thinking in performance improvements for mobile (less elements, best performance at startup). Anyway it 's an idea, all feedback are welcome. We will not implement any issues labeled as "Idea".

**Comment by matiu** [comment]
resolved at https://github.com/bitpay/copay/issues/1503

**Comment by fczuardi** [comment]
the ability to input an amount as described in the original request is a really useful feature, I could use copay as a POS app without installing additional software, I guess the discussion will be handled back at  #2333 now since this one was closed as resolved (without implementing the suggestion)…
