### ISSUE TITLE
TEST NET not working

### ISSUE THREAD

**Issue by pipaman** [bitpay/copay#2348]
Hi,
I just want to know when are you going to solve TEST NET issues. 2 weeks have passed since it is broken.
Thanks on advance,
Pablo

**Comment by matiu** [comment]
Could you detail the problems you are having? I assume you are using insight testnet server, right? We are using normally now.

**Comment by pipaman** [comment]
It looks as it is fine now. I've tried earlier and it wasn't working but now I was able to join a wallet.
Thank you!
I'll report if I find something wrong.

**Comment by cmgustavo** [comment]
test-insight is currently working well. Days ago we had problem with memory consumption, so we disabled a plugin that handles messages between copayers. 

By the way, keep in mind that you can have your own insight server in your network.

**Comment by pipaman** [comment]
I see, I'll tell my customer this possibility and he'll decide! 
Thank you for your help!

(buenisimo que son de Argentina tambien)
