### ISSUE TITLE
Importing a profile only works if one is already present

### ISSUE THREAD

**Issue by YuriRamos2** [bitpay/copay#2353]
I tried importing a profile after uninstalling the copay extension for chrome and installing the new version, it didn't work, displaying the message "unknown error", I then tried to import the profile using the web version, both in chrome and in firefox. It didn't work. 
I then created a new profile in the chrome extension and tried again importing the old one. It worked with no issues.

I'm running Windows 8.1 x64 if it matters. This happened with firefox  35.0.1, chrome 40.0.2214.91 and extension v0.9.5. This profile is stored locally, I chose "on this device" when creating it.

**Comment by YuriRamos2** [comment]
Oh, I forgot to mention this profile is stored locally, I chose "on this device" when creating it.

**Comment by cmgustavo** [comment]
I think you were trying to import a local profile using the default configuration (remote store in the cloud). I mean, if you uninstall Copay and install it again, the default configuration uses insight storage (remote). 

So if you want to import your local profile, you need to change the configuration to use localStorage instead insightStorage

```
Settings -> 
     1-.In the cloud 
     2-.In this device
```

If you create the profile "ON THIS DEVICE", Copay will use local storage. Check if you see this message bellow the SIGN IN button: "* Using this device storage. Change to cloud storage on 'settings'." 

Well, I think this is the reason that you could import the profile after create a new local profile.

**Comment by YuriRamos2** [comment]
Oh thanks, I see. So instead of reporting an issue I'd like to make a suggestion, can't the app auto-detect the type of profile and change the settings accordingly?

**Comment by cmgustavo** [comment]
Good idea. I will close this issue and I will open this another #2354

Thank you!
