### ISSUE TITLE
PIN should just be requested on android lock

### ISSUE THREAD

**Issue by bitcoinuser** [bitpay/copay#2357]
PIN should just be requested on android lock

**Comment by matiaspando** [comment]
Hi:
Thanks for reporting this issue.

We had this problems on android version prior to 4.1.2.

The PR that solves this issue is https://github.com/bitpay/copay/pull/2346

**Comment by bitcoinuser** [comment]
I use Android 4.4.2 and the last version of Copay.

**Comment by cmgustavo** [comment]
I can't reproduce this issue. I have a tablet Samsung with Android 4.4.2 and works as expected. Which device are you using?

**Comment by thoatbk** [comment]
I think he means that the pin should only be requested when the lockscreen was active and not when you send an email, share an address or put the app into the background (ie it loses focus).

**Comment by bitcoinuser** [comment]
thoatbk,

Thanks for clarify.

**Comment by matiu** [comment]
this is not longer relevant on 0.10.x (no PIN)
