### ISSUE TITLE
BIP21 QR scanning not working in IOS 0.9.5

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#2369]
This QR:
![qr](https://cloud.githubusercontent.com/assets/98844/5967743/06e48f6c-a7ef-11e4-9e21-6e0047deecad.png)

throws Invalid value.

**Comment by cmgustavo** [comment]
I have the same issue. This PR should solve it (https://github.com/bitpay/copay/pull/2368).

**Comment by matiu** [comment]
I just realize this bug has nothing to do with QR... try to send:
`0.29133585` gives " Not valid"

**Comment by cmgustavo** [comment]
It works for me in BTC (8 decimals), but not in bits (2 decimals allowed)
