### ISSUE TITLE
No way to logout with the new pin form

### ISSUE THREAD

**Issue by thoatbk** [bitpay/copay#2370]
Theres no way to log out anymore with the new pin form - it´s missing the logout button ;)

**Comment by cmgustavo** [comment]
I know it needs more styling. It is in the bottom.

![img_0048](https://cloud.githubusercontent.com/assets/237435/5967942/fb598d12-a7f0-11e4-8026-c4e26c2f667b.png)

**Comment by thoatbk** [comment]
oh damn, i didnt see that -thanks.

maybe making it red is enough or a subtitle that says "logout".
