### ISSUE TITLE
In send form, error message"Insufficient funds" should warn the user if funds are locked

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#2373]

**Comment by thoatbk** [comment]
Theres another issue with that error message, its defined as:
```javascript
 if (msg.match('totalNeededAmount') || msg.match('unspent not set'))
msg = 'Insufficient funds'
```
However, i think you should split those errors into 2 different error messages like 

```javascript
      if (msg.match('unspent not set'))
        msg = 'Unspent outputs not set, it might also be that the amount you try to transfer is too small or only Dust inputs are left in your Wallet';

      if (msg.match('totalNeededAmount'))
        msg = 'Insufficient funds, keep in mind you have to pay a transaction fee.';
```

The unspent not sent can also be caused by having only dust in the wallet, i had like 100 * 0.0001 btc and couldnt send it out - it displayed only insuffienct funds but the real error was that all inputs were dust.

**Comment by matiu** [comment]
agree, and something like:

 if (msg.match('totalNeededAmount')

    if (lockedFunds)

        msg = 'Insufficient funds. Note that you have XX committed to
current spend proposals" ;

else
msg = 'Insufficient funds, keep in mind you have to pay a transaction fee.';



On Thu, Jan 29, 2015 at 10:14 PM, thoatbk <notifications@github.com> wrote:

> Theres another issue with that error message, its defined as:
>
>  if (msg.match('totalNeededAmount') || msg.match('unspent not set'))
> msg = 'Insufficient funds'
>
> However, i think you should split those errors into 2 different error
> messages like
>
>       if (msg.match('unspent not set'))
>         msg = 'Unspent outputs not set, it might also be that the amount you try to transfer is too small or only Dust inputs are left in your Wallet';
>
>       if (msg.match('totalNeededAmount'))
>         msg = 'Insufficient funds, keep in mind you have to pay a transaction fee.';
>
> The unspent not sent can also be caused by having only dust in the wallet,
> i had like 100 * 0.0001 btc and couldnt send it out - it displayed only
> insuffienct funds but the real error was that all inputs were dust.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2373#issuecomment-72137305>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by matiu** [comment]
done.
