### ISSUE TITLE
Suggestion for webversion of copay

### ISSUE THREAD

**Issue by bitcoinuser** [bitpay/copay#2374]
I think the home page of copay webversion should have an option to show and hide windows like the example of this video of my bank: (https://mega.co.nz/#!skpxhQhY!7N8tIgKDbxI0Dei9EHsAZyHB5ZwO3Vj8xqzYqTAQ1lE)
I would like to see charts, lighthouse crowdfunding projects, last transactions and other informations. (customized according to the user's tastes)

**Comment by gordonwritescode** [comment]
@matiu i did not mean to hastily close this, but when I read this last night, it just screamed malware. If this is not the case, I apologize.

**Comment by eordano** [comment]
According to other contributions by him, it doesn't seem the case :) Thanks a lot Gordon

https://github.com/bitpay/copay/issues/2357
https://github.com/bitpay/copay/issues/2355

**Comment by gordonwritescode** [comment]
my apologies @bitcoinuser - reopening

**Comment by bitcoinuser** [comment]
Thanks. Anyone watched the video? What do you think? good idea?

**Comment by matiu** [comment]
This seems to be out of scope for Copay. We are currently focusing on mobile dev, so this can of features should be provided as 3th party read-only clients to Bitcore-wallet-service.
