### ISSUE TITLE
Sidebar gravatar and translation for mobile issues

### ISSUE THREAD

**Issue by thoatbk** [bitpay/copay#2383]
on Android.

The gravatar picture doesn´t load, its always the standart pic (looks like a power off button).
However on the profile page it works fine, ie it shows my gravatar. 

I think its some kind of initilization problem, i also have a problem translating text in the sidebar, when i switch languages and dont close/start the app and then relogin to the profile after switching the language in the settings menu the sidebar is not completly translated.

"Add Wallet" and and "Lock" (sometimes) don´t get translated while the "view my profile" string is always translated correctly - when i reboot the app its all back to english or german, or whatever i switched to.

So, if we remove the translate directive and use the bracket annotation i.e. {{'Add wallet' | translate }}
it works fine, any idea how that is caused? It´s easily fixed using the bracket style, but i am not sure what issue this is caused by and if the issue itself shouldn´t be fixed, if there is one, else i would have done a PR.

And on the profile page maybe it makes sense to not open the link to the gravatar page in the external browser and instead use the internal app browser ->
<a class="photo-container profile" href ng-click="$root.openExternalLink('https://gravatar.com/')" ...

so the App doesn´t lock out; BUT that has some other drawback as the app doesnt have rights to upload picture from the mobile storage etc.

**Comment by cmgustavo** [comment]
Thank you for your detailed explanation @thoatbk! I will check the gravatar first and fix the external link.

Regarding the other issue, I am seeing that both (add wallet and lock) don't have the translation directives. Anyway, there is a thing to do if you want to translate string inside a javascript file: add the same string to "dummy-translations.html". This file is compiled in another javascript file (js/translations.js).

I 'm not sure what happening when change language without restart the app. I couldn't reproduce this issue. I will check it now.

Thanks!

**Comment by thoatbk** [comment]
Hi cmgustavo,
thats not the issue; 
I added translate directives in my local code and also added it to the dummy translations.

I think somehow it uses the default language from the config for the sidebar-mobile items that don´t get translated; if i dont restart the app.

**Comment by cmgustavo** [comment]
I think I know what 's happening. You said that "lock" and "Add wallet" are not translated. Well... I am seeing that this strings don't have the "translate" attribute:

```html
<span class="tu text-bold">Lock</span> <br>
```

We should add "translate":

```html
<span translate class="tu text-bold">Lock</span> <br>
```

This is the same if you use "{{'string'|translate}}. That 's all you need. 

But there is something I don't understand, when you save your settings, the app reload all variables and functions. So, why you need to restart the app to see the strings translated?

**Comment by thoatbk** [comment]
No :)

as i said i added those directives in my local code. I

so to make it short, this does not work: <span class="tu text-bold">Lock</span> <br>
but this works: {{'string'|translate}}.

"But there is something I don't understand, when you save your settings, the app reload all variables and functions. So, why you need to restart the app to see the strings translated?"

Thats the reason why i opened the Issue, because i don´t understand that either. The translations work absolutely fine everywhere else in the App.


And the directive and the annoted brackets are afaik not the same.

The translate directive will place a watcher on the passed variable. So the translation will only apply, when the passed value does actually change? 

The brackets use a filter instead of a directive and will be dirty checked and refreshed in every $digest, even if it's not necessary. 


And thats the reason why i thought it might be some kind of init problem as the filter bracket version works and the strings get translated whenever i open the sidebar "on-the-fly".

**Comment by cmgustavo** [comment]
I see, this seems more complex than what I thought :( We will have to review it more in detail.

**Comment by matiu** [comment]
Pictures were removed at https://github.com/bitpay/copay/releases/tag/v0.10.0
There are not plans to use them again, current UX design do not depend on them.
