### ISSUE TITLE
Some Samsung devices don´t provide a decimal point...

### ISSUE THREAD

**Issue by thoatbk** [bitpay/copay#2384]
... which makes it impossible to enter an amount with . or ,

No this is not a joke, if the numpad is used, for a lot of samsung phones it looks like this:
https://getsatisfaction.com/apperyio/topics/numeric-keyboard-on-galaxy-s5-missing-decimal-point-and-minus-sign
http://forums.androidcentral.com/samsung-galaxy-s4/307777-where-numeric-keypad.html#post_3013599

A friend of me tested copay on his galaxy S5 and he wasn´t able to send BTC, because he has no decimal point. There is simply nothing then the numbers from 0-9 on the pad.

Only solution so far was installing an alternative app like Swiftkey or flashing cynogenmod or whatever else rom...

I guess theres no easy fix, at least i can´t fine one. So using the js keyboard from the pin page and adding a . decimal point and maybe a comma for european users or whoever else uses comma should do it.

**Comment by matiu** [comment]
Thanks for the report.

Should we use a custom keyboard, like the upcoming PIN input?

On Mon, Feb 2, 2015 at 10:04 PM, thoatbk <notifications@github.com> wrote:

> ... which makes it impossible to enter an amount with . or ,
>
> No this is not a joke, if the numpad is used, for a lot of samsung phones
> it looks like this:
>
> https://getsatisfaction.com/apperyio/topics/numeric-keyboard-on-galaxy-s5-missing-decimal-point-and-minus-sign
>
> http://forums.androidcentral.com/samsung-galaxy-s4/307777-where-numeric-keypad.html#post_3013599
>
> A friend of me tested copay on his galaxy S5 and he wasn´t able to send
> BTC, because he has no decimal point. There is simply nothing then the
> numbers from 0-9 on the pad.
>
> Only solution so far was installing an alternative app like Swiftkey or
> flashing cynogenmod or whatever else rom...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2384>.
>



-- 
BitPay.com

**Comment by thoatbk** [comment]
definately - the same as on the pin page is ok, instead of the lock button a decimal point should work.

I am just not sure if a comma is also needed, people here in europe and other regions use a comma instead - maybe just add both signs on the same button?

**Comment by matiu** [comment]
Solving this in Copay would  require a significant amount of effort to implement it and maintain it.  For the moment we recommend installing a custom keyboard on the affected android device. More on this issue: https://github.com/bitpay/copay/issues/2838
