### ISSUE TITLE
trying to recover wallet with swipeWallet.js

### ISSUE THREAD

**Issue by algaris** [bitpay/copay#2400]
Hello! I have been trying to get this script (https://github.com/bitpay/copay/blob/master/util/swipeWallet.js) running since I found it, but it just keeps giving me a windows error before it can load.

**Comment by matiu** [comment]
Could you describe in detail the error you are getting? Thanks!



On Fri, Feb 6, 2015 at 2:40 AM, algaris <notifications@github.com> wrote:

> Hello! I have been trying to get this script (
> https://github.com/bitpay/copay/blob/master/util/swipeWallet.js) running
> since I found it, but it just keeps giving me a windows error before it can
> load.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2400>.
>



-- 
BitPay.com

**Comment by algaris** [comment]
Now, when trying to run the script, windows 7 pops up a dialog:
'Windows Script Host
There is no script engine for file extension ".js".'

before it was giving me:
'Windows Script Host
Line 1
Char 1
Error Invalid character
Code 800A03F6
Source Microsoft JScript compilation error'

**Comment by cmgustavo** [comment]
You have to run the script with NodeJS in the command prompt window.

**Comment by matiu** [comment]
please see:
http://blog.gvm-it.eu/post/20404719601/getting-started-with-node-js-on-windows

On Fri, Feb 6, 2015 at 3:26 PM, Gustavo Maximiliano Cortez <
notifications@github.com> wrote:

> You have to run the script with NodeJS in the command prompt window.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2400#issuecomment-73287122>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by algaris** [comment]
And this is node's output:
'C:\Users\Dexter\Documents\GitHub\copay\util>node swipeWallet.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'preconditions'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Dexter\Documents\GitHub\copay\js\models\Publ
icKeyRing.js:3:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)'

**Comment by cmgustavo** [comment]
Ok, It seems you don't have all modules installed. Run ```node install``` from 'C:\Users\Dexter\Documents\GitHub\copay\', then try again ```node utils\swipeWallet.js```.

Please, let us know if it works.

**Comment by algaris** [comment]
C:\Users\Dexter\Documents\GitHub\copay>node install

module.js:340
    throw err;
          ^
Error: Cannot find module 'C:\Users\Dexter\Documents\GitHub\copay\install'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

**Comment by cmgustavo** [comment]
Apologies,

```npm install```

**Comment by algaris** [comment]
Okay, today does not appear to be my day; thank you for taking the time with my noob self:

'C:\Users\Dexter\Documents\GitHub\copay>npm install
Error: ENOENT, stat 'C:\Users\Dexter\AppData\Roaming\npm'

**Comment by cmgustavo** [comment]
No problem. It also took me too much time to install Copay on Windows. It 's more easy on Unix platforms.

In this case you have to create the folder ```npm``` in the displayed path: ```C:\Users\Dexter\AppData\Roaming\```

**Comment by algaris** [comment]
*sighs*

'C:\Users\Dexter\Documents\GitHub\copay>npm install
npm ERR! git clone git://github.com/matiu/browser-request.git undefined
npm ERR! git clone git://github.com/matiu/browser-request.git undefined
npm ERR! git clone git://github.com/bitpay/bitcore.git undefined
npm ERR! git clone git://github.com/bitpay/bitcore.git undefined
npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\Dexter\Documents\GitHub\copay
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ENOGIT
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\Dexter\Documents\GitHub\copay\npm-debug.log
npm ERR! not ok code 0'

I think I shall just boot up the linux machine this evening when I get home...

**Comment by cmgustavo** [comment]
It seems that you are missing many packages like "Git for Windows" and maybe many other developer libraries.

Try https://www.cygwin.com/ (it is a terminal like on Linux)

**Comment by algaris** [comment]
I have git for windows installed, though I ran that on cmd. I have no realized that I should be doing it on the git shell, and am running it now. It seems to be running, but it is throwing up a bunch of errors. Unfortunately, I shall have to wait till after work to see the results, as I have to return from lunch. 

Thank you for your help so far, and I'll post which ever way it works.

**Comment by algaris** [comment]
Okay, nearly 24 hours later, a crash primer in the very things that made me get out of programming a decade ago, lots of reading/watching tutorials, and much consternation, I have gotten down to one error when attempting to install copay on windows...I think....

"Dexter@DEXTOWER ~/Documents/GitHub/copay (master)
$ npm install
npm WARN package.json querystring@0.2.0 querystring is also the name of a node c
ore module.
npm WARN excluding symbolic link examples\PayPro\bitcore.js -> ../../browser/bun
dle.js
npm WARN engine bitcore@0.1.41: wanted: {"node":">=0.10 <0.10.36"} (current: {"n
ode":"0.10.36","npm":"1.4.28"})
npm WARN excluding symbolic link examples\PayPro\bitcore.js -> ../../browser/bun
dle.js
\
> bignum@0.9.1 install c:\Users\Dexter\Documents\GitHub\copay\node_modules\bitco
re\node_modules\bignum
> node-gyp configure build


c:\Users\Dexter\Documents\GitHub\copay\node_modules\bitcore\node_modules\bignum>
node "c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modu
les\node-gyp\bin\node-gyp.js" configure build
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  bignum.cc
F:\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ exc
eption handler used, but unwind semantics are not enabled. Specify /EHsc [c:\Us
ers\Dexter\Documents\GitHub\copay\node_modules\bitcore\node_modules\bignum\buil
d\bignum.vcxproj]
..\bignum.cc(9): fatal error C1083: Cannot open include file: 'openssl/bn.h': N
o such file or directory [c:\Users\Dexter\Documents\GitHub\copay\node_modules\b
itcore\node_modules\bignum\build\bignum.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:
12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd c:\Users\Dexter\Documents\GitHub\copay\node_modules\bitcore\node_mo
dules\bignum
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
npm ERR! bignum@0.9.1 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bignum@0.9.1 install script.
npm ERR! This is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodej
s\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd c:\Users\Dexter\Documents\GitHub\copay
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0'

I think that either I am still missing this 'openssl/bn.h', or that, when attempting to conserve limited hard drive resources, my choosing not to install all of MS Visual Studio left out something important...maybe?

Even if this comes to me not being able to get this, I would like to say that I very much appreciate all the help I have received so far; as far as I am concerned, that alone will ensure my continued patronage.

This is, perhaps, the hardest I have worked for ~$500 (2.5BTC, what is in the account I am trying to get back to) in a long time

**Comment by algaris** [comment]
Okay, switched to linux, installed appropriate packages & libraries, including the one in this error:

'npm WARN excluding symbolic link examples/PayPro/bitcore.js -> ../../browser/bundle.js
npm WARN excluding symbolic link examples/PayPro/bitcore.js -> ../../browser/bundle.js
 
> bignum@0.9.1 install /home/algaris/copay/node_modules/bitcore/node_modules/bignum
> node-gyp configure build

gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.16.0-30-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "configure" "build"
cwd /home/algaris/copay/node_modules/bitcore/node_modules/bignum
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/home/algaris/copay/node_modules/bitcore/node_modules/protobufjs'
npm ERR! error rolling back  bitcore@0.1.41 { [Error: ENOTEMPTY, rmdir '/home/algaris/copay/node_modules/bitcore/node_modules/protobufjs']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/home/algaris/copay/node_modules/bitcore/node_modules/protobufjs' }
npm ERR! bignum@0.9.1 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bignum@0.9.1 install script.
npm ERR! This is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-30-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/algaris/copay
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! Error: ENOENT, lstat '/home/algaris/copay/node_modules/bitcore/node_modules/sjcl/jsdoc_toolkit-2.3.3-beta/app/run.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-30-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/algaris/copay
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! path /home/algaris/copay/node_modules/bitcore/node_modules/sjcl/jsdoc_toolkit-2.3.3-beta/app/run.js
npm ERR! fstream_path /home/algaris/copay/node_modules/bitcore/node_modules/sjcl/jsdoc_toolkit-2.3.3-beta/app/run.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! Error: ENOENT, lstat '/home/algaris/copay/node_modules/bitcore/node_modules/brfs/node_modules/falafel/node_modules/esprima/bin/esvalidate.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-30-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/algaris/copay
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! path /home/algaris/copay/node_modules/bitcore/node_modules/brfs/node_modules/falafel/node_modules/esprima/bin/esvalidate.js
npm ERR! fstream_path /home/algaris/copay/node_modules/bitcore/node_modules/brfs/node_modules/falafel/node_modules/esprima/bin/esvalidate.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! Error: ENOENT, chown '/home/algaris/copay/node_modules/bitcore/node_modules/socks5-client/node_modules/ipv6/node_modules/sprintf/test'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-30-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/algaris/copay
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! path /home/algaris/copay/node_modules/bitcore/node_modules/socks5-client/node_modules/ipv6/node_modules/sprintf/test
npm ERR! fstream_path /home/algaris/copay/node_modules/bitcore/node_modules/socks5-client/node_modules/ipv6/node_modules/sprintf/test/function-export.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call setupMadeDir
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack end (/usr/lib/nodejs/fstream/lib/writer.js:319:21)
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:336:20
npm ERR! fstream_stack next (/usr/lib/nodejs/fstream/lib/writer.js:366:20)
npm ERR! fstream_stack /usr/lib/nodejs/graceful-fs/polyfills.js:143:7
npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! Error: ENOENT, lstat '/home/algaris/copay/node_modules/bitcore/node_modules/socks5-client/node_modules/ipv6/node_modules/cliff/assets/inspect.png'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-30-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/algaris/copay
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! path /home/algaris/copay/node_modules/bitcore/node_modules/socks5-client/node_modules/ipv6/node_modules/cliff/assets/inspect.png
npm ERR! fstream_path /home/algaris/copay/node_modules/bitcore/node_modules/socks5-client/node_modules/ipv6/node_modules/cliff/assets/inspect.png
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! Error: ENOENT, lstat '/home/algaris/copay/node_modules/bitcore/node_modules/socks5-client/node_modules/ipv6/node_modules/cli/cli.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-30-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/algaris/copay
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! path /home/algaris/copay/node_modules/bitcore/node_modules/socks5-client/node_modules/ipv6/node_modules/cli/cli.js
npm ERR! fstream_path /home/algaris/copay/node_modules/bitcore/node_modules/socks5-client/node_modules/ipv6/node_modules/cli/cli.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
 
> phantomjs@1.9.15 install /home/algaris/copay/node_modules/karma-phantomjs-launcher/node_modules/phantomjs
> node install.js

npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/algaris/copay/npm-debug.log
npm ERR! not ok code 0'

I was fairly certain I have the latest version of node:
'algaris@DexTop:~/copay$ sudo apt-get install node
[sudo] password for algaris: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
node is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 107 not upgraded.'

What am I missing?

**Comment by cmgustavo** [comment]
It seems you have an old version of node: ```npm WARN This failure might be due to the use of legacy binary "node"```

Try update node: https://rtcamp.com/tutorials/nodejs/node-js-npm-install-ubuntu/

**Comment by algaris** [comment]
*pumps fist*

I have finally succeeded in installing copay! Now this:
'algaris@DexTop:~/copay$ sudo node utils\swipeWallet.js
algaris@DexTop:~/copay$ sudo node util\swipeWallet.js
algaris@DexTop:~/copay$ node util\swipeWallet.js
algaris@DexTop:~/copay$'

Nothing seems to happen when I run the script, which leads me to believe that I am using it wrong...

**Comment by cmgustavo** [comment]
Try with this sequence:

```
1- npm install
2- bower install 
3- grunt
4- npm start
5- Open chrome/firefox/whatever in http://localhost:3000
```

If everything is ok, you can import your profile o wallet. 

By the way, to use swipeWallet you need the Master Private Key. Do you have it?

**Comment by algaris** [comment]
I have the full backup, so I believe so.

**Comment by algaris** [comment]
copay is running, but nothing comes up in the browser.

**Comment by cmgustavo** [comment]
Well, if you have the full backup, why don't import it on http://copay.io/ ?

**Comment by algaris** [comment]
Because the password that I have for that wallet stopped working back in December, but at the time there was next to nothing in the account at the time. Due to a lack of forethought on my part, I not removed the address from all my various places, and when transferring loan money from BTCJam, it went to the problem wallet address.

**Comment by algaris** [comment]
I shall take the lack of response as a bad sign. *sighs* 

Thank you for all your help.

**Comment by cmgustavo** [comment]
If you have the backup file, it should be work with the import function.  I 'm more concerned that you can not import the wallet instead to do the swipe tool works.

Please, could you tell me how did you do to import the wallet (Is it a wallet or profile?). I will appreciate your help.

Thanks!

**Comment by algaris** [comment]
I am fairly certain that it is just the wallet backup, and the issue with just importing it is that my password doesn't seem to work. (I have done everything I can [copy directly from LastPass & the like] to verify that I am using the same password.)

Currently dealing with a massive bout of winter, so I will try to take a crack at it again this weekend.

**Comment by cmgustavo** [comment]
Just to be safe, are you trying to import from "https://copay.io/in/app/#!/importProfile" ? If you did, it 's not well. You should enter to your profile and -> "Add wallet" -> "Import".

**Comment by matiu** [comment]
closing this one. Please reopen if still active.
