### ISSUE TITLE
Random error with last signature. TX not broadcasting. TX Malleability. 

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#2406]
when adding the last signature in a TX proposal, I could happen the following:

- the TX get broadcasted to the bitcoin network.
- the wallet is not stored for any reason (network, for example).

The if the user reopen the wallet, the TX proposal will be there, and trying to sign it
will generate a different signature, therefore a different TXID. Broadcast will fail (since
inputs are allready spent) and checking the TXID on the blockchain will fail (since the
TXID differs from the original broadcasted TX).

It happen to me using 3G.

It will be fixed by bitcore 0.8 deterministic K.

**Comment by thoatbk** [comment]
I proposed checking the current locally stored txproposals on login of a user in another thread here, that would also prevent those situations i guess.

Is there something that speaks against that except the performance hit?

**Comment by cmgustavo** [comment]
I had the same issue. To reproduce the problem easily I followed this steps (2-2 wallet):

* Comment line before to send the transaction (It returns 404 error from insight). We verify that the tx was already sent, checking the existence on the blockchain.
```javascript
this.blockchain.broadcast(txHex, function(err, txid) {});
```
* Create transaction proposal.
* Sign the txp.
* Error
* Signout, uncomment the lines above.
* In both copayers you should see the transaction proposal. 
* Broadcast the transaction.
* Transaction was send to the blockchain and disappear from list of pending for the current copayer.
 * The other copayer has the transaction with all signatures but without the sentTs. As if it had never sent.

The only solution to remove this orphan transactions proposal is to purge them (from settings-> advanced-> purge).

**Comment by matiu** [comment]
fixed using the new bitcore (with deterministic-k signatures)
