### ISSUE TITLE
Copay with an altcoin, cant send coins to an address with a different prefix

### ISSUE THREAD

**Issue by chrisfranko** [bitpay/copay#2413]
Ive got everything pretty much up and working np except when trying to send to an address with a prefix that != bitcoins 1, example, I can receive coin at addresses that begin with 3 because both coins have the same script variable. However if I try to send coin to an address with the prefix F, (for frk of course) it says its not a valid address.

In bitcore I changed networks.js variables accordingly but i'm afraid its hardcoded somewhere else and im not sure where.

**Comment by chrisfranko** [comment]
figured it out.

The variables are also hardcoded in lib/bitcore.js

**Comment by iobond** [comment]
the new version has shift the a hardcode from  lib/bitcore.js to some where. anyone know about the location?

**Comment by matiu** [comment]
The new version uses Bitcore wallet service. I think you need to modify that in order to use Copay with an alt coin

**Comment by iobond** [comment]
Thanks your reply, I  have setup BWS, Insight-API with modified bitcore for one altcoin. and all works (receive funds, create wallets..., send funds start with "3" ) .  except that can't send with livenet address start with "A"  like the topic mentioned. and when I cut off BWS connection. the copay still doing validation for the address (Is it cached or some other way actually the validation store in locally?).
 any hint, how can I debug this to locate what's the error?  

or you might able to point me out, currently in Copay, which js file actually taking care the validation of the bitcoin address?  or  through which file and contact with BWS?
