### ISSUE TITLE
Allow Wallets to Be Renamed

### ISSUE THREAD

**Issue by martindale** [bitpay/copay#2415]
The default 'my wallet' can be an inconvenient name if the user has a different naming scheme or multiple wallets.  Wallets should be capable of being renamed.

**Comment by matiu** [comment]
dup: https://github.com/bitpay/copay/issues/2415

**Comment by martindale** [comment]
Can you link the issue where this is duplicated?  The above is just a link back to this issue.

**Comment by matiu** [comment]
https://github.com/bitpay/copay/issues/2418 sorry about that.

**Comment by martindale** [comment]
Hrm.  I don't think these are the same – #2415 is about changing the name of the wallet completely, while #2418 would be a client-side alias that overrides the real name of the wallet.  Maybe for simplicity's sake, we treat them as the same case, but I'd want both cases to be possible.

For example, if I'm a trusted third party in a transaction, imagine if the originator named the new wallet "Escrow", but I have three or four other "Escrow" wallets.  I'd want to "nickname" each of them (or provide annotations – just notes) without changing the name for all parties.

**Comment by matiu** [comment]
Got it.

I like the client side (i.e. local) annotations. Changing the global name
shouldn't be possible (or maybe only with quorum which is to complex).

On Tue, Apr 14, 2015 at 3:23 PM, Eric Martindale <notifications@github.com>
wrote:

> Hrm. I don't think these are the same – #2415
> <https://github.com/bitpay/copay/issues/2415> is about changing the name
> of the wallet completely, while #2418
> <https://github.com/bitpay/copay/issues/2418> would be a client-side
> alias that overrides the real name of the wallet. Maybe for simplicity's
> sake, we treat them as the same case, but I'd want both cases to be
> possible.
>
> For example, if I'm a trusted third party in a transaction, imagine if the
> originator named the new wallet "Escrow", but I have three or four other
> "Escrow" wallets. I'd want to "nickname" each of them (or provide
> annotations – just notes) without changing the name for all parties.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2415#issuecomment-93007444>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!
