### ISSUE TITLE
Chrome App: Download Backup Does Not Indicate Location

### ISSUE THREAD

**Issue by martindale** [bitpay/copay#2416]
When using the Chrome app, backing up one's profile does not provide any indication of where the backup is being saved.  I searched manually and found it (in `~/Downloads`), but some indicator (or even a selection) should be offered to the user.

**Comment by cmgustavo** [comment]
It 's not a Copay issue, it depends your Chrome configuration.

![settings](https://cloud.githubusercontent.com/assets/237435/6229960/8f1c22fa-b69a-11e4-969c-a76ffcac6caa.png)

**Comment by matiu** [comment]
done / outdated.
