### ISSUE TITLE
Android Intent Incorrectly Looks for Generic URI Handlers

### ISSUE THREAD

**Issue by martindale** [bitpay/copay#2419]
The Android intent launched when clicking "share address" on the "Receive" screen is incorrect; I would expect my applications Bitcoin wallets to be queried, like the Android Bitcoin Wallet by Andreas Schildbach.

**Comment by matiu** [comment]
Currently the share address in android allows the user to share the address by email / messegers, copy the address, etc which it seems to be the expected behaviour
