### ISSUE TITLE
Android app battery usage

### ISSUE THREAD

**Issue by dskloet** [bitpay/copay#2427]
I hadn't used the Copay app for a long time. Recently I opened it just for a few minutes to try something, and later when I looked at my battery usage I noticed that Copay had used 33% of my battery.
![screenshot_2015-02-23-00-13-30](https://cloud.githubusercontent.com/assets/6271274/6335413/af63f4b0-bb9b-11e4-897c-d5912196e198.png)

**Comment by matiu** [comment]
this should be fixed with the new BWS branch: (https://github.com/bitpay/copay/pull/2502)
