### ISSUE TITLE
Units on pending proposals are incorrect

### ISSUE THREAD

**Issue by ripper234** [bitpay/copay#2428]
To reproduce:

1. Someone else initiates a 0.02 bit tx.
2. It shows up as 0.02 bits:

![image](https://cloud.githubusercontent.com/assets/172282/6346740/24170e08-bc1b-11e4-8241-6a337fd32300.png)

3. Go to your settings for this wallet, and change your units from bits to BTC

**Expected**

The pending tx should show up as 0.00000002 BTC

**Actual**

The tx incorrectly is shown as 0.02 BTC

![image](https://cloud.githubusercontent.com/assets/172282/6346764/4352b54c-bc1b-11e4-908b-f613b394bea5.png)

**Comment by ripper234** [comment]
FYI, logging out and back in seems to resolve the issue.

**Comment by MeniRosenfeld** [comment]
This happens consistently from what I can tell. If there is a pending transaction, and you change the units, the nominal amount displayed for the transaction remains the same, but the units change, giving nonsensical results.

**Comment by cmgustavo** [comment]
It seems to be a problem with a global variable of AngularJS. If you logging out and back, the variables are reloaded. We will check it.

Thanks!

**Comment by cmgustavo** [comment]
This PR (#2429) should solve the problem.

Thanks for report.
