### ISSUE TITLE
Joining 2 of 2 wallet times out (web)

### ISSUE THREAD

**Issue by bitcoinbrisbane** [bitpay/copay#2430]
Via the browser, on a Mac + Safari and windows 7 + IE and FF.  Cannot join a multisig wallet with the key provided.

**Comment by cmgustavo** [comment]
Could you give us more details how did you do that? Remember that the creator of the wallet needs to be connected while the other copayers are trying to join.

**Comment by bitcoinbrisbane** [comment]
Thanks for the reply, yep that worked :)

**Comment by cmgustavo** [comment]
Thank you!
