### ISSUE TITLE
Can't broadcast transaction on mobile

### ISSUE THREAD

**Issue by mr-e-** [bitpay/copay#2432]
I tried copay for the first time and I set of a 2 of 2 wallet with the second key on my phone. I sent a transction from my pc and when I go to confirm it on my phone I am getting an error. It flashes very quickly, it look me a long time to take this screenshot but it keeps happening every time I click broadcast. 

http://i.imgur.com/74q6F07.png

Does this wallet rely on a centralized server that would leave me without access to my money if it goes down?

**Comment by mr-e-** [comment]
The intersting thing is the transction should have been for 300 bits yet it is showing in the screenshot that it is only 1 bit??

**Comment by matiu** [comment]
sorry this one was one unanswered.  Copay release on bitcore-wallet-service, as explained here: https://github.com/bitpay/copay#bitcore-wallet-service
