### ISSUE TITLE
Proposal Alert Bug

### ISSUE THREAD

**Issue by Anderson-Juhasc** [bitpay/copay#2433]
I refused the proposal as a test and now the proposal no longer appears to either side.

**Comment by cmgustavo** [comment]
Was it a 2-2 wallet? If your signature is the latest required to approve the transaction and you reject it, the proposals will disappear from all copayers.

**Comment by Anderson-Juhasc** [comment]
If I reject one proposal it doesn't mean I will reject any new proposals. And by the way, I may have rejected it by mistake and want a second opportunity to approve it.

How can I reverse?

**Comment by cmgustavo** [comment]
There is no way to reverse this operation. You have to create a new proposal.

**Comment by Anderson-Juhasc** [comment]
I'm creating, but does not appear the proposal to the other user accepts.

**Comment by Anderson-Juhasc** [comment]
Hi @cmgustavo ,

Well, my problem is that when I refused a proposal the system stopped showing new proposals to other users of the portfolio.

I have funds in the wallet but can not withdraw why not appear the proposal to the other user.

**Comment by matiu** [comment]
Hey, could you update this issue? Are you still having problems? Thanks.
