### ISSUE TITLE
CoinJoin-based Mixing

### ISSUE THREAD

**Issue by martindale** [bitpay/copay#2434]
This is a feature request from [several previous issues](https://github.com/bitpay/copay/issues/415#issuecomment-43672233), and more recently [from Reddit](https://www.reddit.com/r/Bitcoin/comments/2xkfih/is_electrum_the_best_multisig_wallet_that_doesnt/cp10vo9).

**Comment by matiu** [comment]
moved to https://github.com/bitpay/bitcore-wallet-service/issues/137
