### ISSUE TITLE
Can't understand what my wallet encrypted backup password is

### ISSUE THREAD

**Issue by mr-e-** [bitpay/copay#2435]
I created a new account on my phone and joined it to a 2 of 2 for testing purposes. I sent a backup of my wallet to my email address. At no point during this process was I asked to set a password yet when attempting to restore the backup it is asking me to enter a password. No idea how to restore my backup.

**Comment by matiu** [comment]
The backup password is the same are the profile password.

In the new BWS1 branch, the backup password is created only for the backup. (https://github.com/bitpay/copay/pull/2502)
