### ISSUE TITLE
inconsistent balance vs transaction history

### ISSUE THREAD

**Issue by maraoz** [bitpay/copay#2437]
![screenshot from 2015-03-02 12 36 00](https://cloud.githubusercontent.com/assets/287189/6443878/d7bac8b6-c0d8-11e4-962c-d651d2ce7305.png)

![screenshot from 2015-03-02 12 36 09](https://cloud.githubusercontent.com/assets/287189/6443879/dab54d48-c0d8-11e4-8d48-b7cc0f9ccee1.png)

Transaction history shows 2 transactions, balance only represents one of them. This has been this way for some minutes now, so it's not a sync problem

**Comment by matiu** [comment]
this should be fixed at https://github.com/bitpay/copay/issues/1503
