### ISSUE TITLE
when more accounts created in localstorage only last is accessible

### ISSUE THREAD

**Issue by sipak** [bitpay/copay#2449]
Tried with 3 accounts on Chrome (Centos 7). First two are not accessible, just showing "Accessing your profile..." forever

**Comment by lukem512** [comment]
I can also confirm this as an issue, tested on Chrome Version 39.0.2171.99 (64-bit) and Firefox 30 (Linux Mint 16)

**Comment by matiu** [comment]
I think this is not longer relevant in 0.10.x. Thanks for your report.
