### ISSUE TITLE
Local Insight server not working well

### ISSUE THREAD

**Issue by pipaman** [bitpay/copay#2451]
Hi,
I've deployed my own insight server and I have a random error. Sometimes it let me join a shared wallet and sometimes I get (insight server = https://192.168.0.194:3001):
XMLHttpRequest cannot load https://192.168.0.194:3001/socket.io/?EIO=2&transport=polling&t=1427475624228-120&sid=5rspstSF_nKGEryoAABU. Invalid HTTP status code 400

Any ideas?
Thanks on advanced,
Pablo

**Comment by matiu** [comment]
Closing this one. Copay does not use Insight directly, but thru BWS. Please report at `insight-api` repo.
