### ISSUE TITLE
Include Copay for Android in F-Droid

### ISSUE THREAD

**Issue by bookchin** [bitpay/copay#2465]
There are a many Android users, such as myself, that do not run GAPPS (Google Apps) on their device due to concerns relating to software licensing, privacy, and security. This means that Copay is not available to us (unless we build from source ourselves), since the Play Store is not available on our devices (by choice).

[F-Droid](https://f-droid.org/) is used in it's place, which is a catalogue of vetted FLOSS applications. I'd love to see Copay published there, so that myself and others can use Copay without having to build from source.
- https://f-droid.org/manual/fdroid.html
- https://f-droid.org/wiki/page/Inclusion_Policy
- https://gitlab.com/fdroid/fdroiddata

I'm happy to work on this if you guys do not have the time.

**Comment by braydonf** [comment]
+1

**Comment by martindale** [comment]
This would be awesome.  Huge +1 from me.  We should also publish the signed APK file to the website as part of the deploy process, so those not running any marketplace can also download and verify updates (so we should included a signed hash, too).

**Comment by ERamseth** [comment]
I would also like to be able to download and update Copay through F-Droid.

**Comment by martindale** [comment]
This is important to me, so I've [committed a $25 USD bounty](https://www.bountysource.com/issues/10274629-include-copay-for-android-in-f-droid) to make this happen.  While I wish they'd denominate the bounty in Bitcoin, that'll have to do for now.

**Comment by koalalorenzo** [comment]
+1

**Comment by cryptokarnal** [comment]
+1

Any news on this?

Coupled with the (apparent) lack of an official download for the apk, this makes it dangerous/very unconvenient for non-gapps users to use this awesome software!

**Comment by matiu** [comment]
https://github.com/bitpay/copay/releases

usually have the APK. (currently the last updated APK is v1.8.1)

ATM, there are no plans to include and maintain Copay in f-droid.

On Wed, Feb 3, 2016 at 11:30 AM, cryptokarnal <notifications@github.com>
wrote:

> +1
>
> Any news on this?
>
> Coupled with the (apparent) lack of an official download for the apk, this
> makes it dangerous/very unconvenient for non-gapps users to use this
> awesome software!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2465#issuecomment-179265924>.
>



-- 
BitPay.com

**Comment by matiu** [comment]
Adding a new channel for deploying Copay is not an option for us now due to time limitations. We will continue to provided the signed APK on github.

**Comment by martindale** [comment]
Please re-open this thread; Bitcoin users are much more likely to be privacy-conscious, and thus more likely to be using F-Droid.  It would follow that listing Copay in the F-Droid marketplace might gain the project more users, and since [submitting Copay can be automated](https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md#adding-a-new-app) it makes sense to re-open this issue and just get it done.

**Comment by hughdavenport** [comment]
Just noticed this, the community could just make their own repo for this. Instructions at https://f-droid.org/wiki/page/Setup_an_FDroid_App_Repo. I'm debating doing this for all open source apps that I use that refuse to go onto an open source market.

**Comment by juanjgit** [comment]
Yes, please, reopen this issue. There is not even an updated version of the APK at Github

**Comment by Stemby** [comment]
+1.

See also https://f-droid.org/forums/topic/copay-bitcoin-wallet/

**Comment by herbsmn** [comment]
Hello. 

I'm curious, do the CoPay devs support inclusion of CoPay in F-Droid, or not so much?

The Request For Packaging has already been filled out but it seems like F-Droid is unaware as to whether you will allow this into F-Droid or not. Please say yes.

https://gitlab.com/fdroid/rfp/issues/50

**Comment by IzzySoft** [comment]
@matiu 

> Adding a new channel for deploying Copay is not an option for us now due to time limitations. We will continue to provided the signed APK on github.

The last APK I see there is dated 8/2016 (v2.6.0). Since then, there have been 5+ releases, not a single of them having an `.apk` file attached. If you could continue attaching the file, I could adopt the app into [my F-Droid compatible repo](https://apt.izzysoft.de/fdroid/) until the official one picked it up (and even continue afterwards if you don't tell me to stop it). Please respond to this issue when done, so I know to pick up the file and have my updater running for future versions.

Still, I'd strongly encourage going for the official repo (as well; no contradiction keeping the app in both). I cannot compete with the trust and reputation it has (though I do my very best to keep the gap as small as possible). To get that rolling, as far as I can see all that's needed is your "saying yes", as @herbsmn already pointed out [and to](https://gitlab.com/fdroid/rfp/issues/50).

**Comment by martindale** [comment]
@matiu ping on this, I'd love to finally close this issue.  Copay is inaccessible to many of my clients as they do not use Google services.

**Comment by IzzySoft** [comment]
As the new tags now have their `.apk` attached again, you can find the app now [here in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.bitpay.copay) (available via the F-Droid app if you add my repo there).

**Comment by SirCmpwn** [comment]
Hey, installing this app from Google Play is a non-starter. For a company in the cryptocurrency space your disregard of this issue is alarming and turns me off of your service entirely. I want to store my bitcoins securely and this communicates to me that you don't understand mobile security.

**Comment by JDonadio** [comment]
We provide the APK for each release, so anyone can upload it on F-Droid.

**Comment by SirCmpwn** [comment]
We're asking *you* to maintain the F-Droid package.

**Comment by JDonadio** [comment]
We'll not maintain it, sorry.

**Comment by SirCmpwn** [comment]
Then what I said before holds true. Your approach to Android security is alarming and speaks poorly of your organization's ability to securely maintain their product.

**Comment by IzzySoft** [comment]
@SirCmpwn F-Droid packages are only maintained by F-Droid maintainers, not by the apps' own developers – though the maintainers might need their support (e.g. to provide specific flavors). So before you demand something, better check if you're not asking the impossible :wink:

**Comment by SirCmpwn** [comment]
F-Droid is not run in a vaccuum:

https://f-droid.org/en/contribute/

Volunteers can and do lots of the heavy lifting for getting new packages into the tree.

**Comment by IzzySoft** [comment]
OK, so someone [opened an RFP](https://gitlab.com/fdroid/rfp/issues/50) (request for packaging) at F-Droid – and we  would like to "fulfill" that request. But this is a Cordova app, so we can't build it unless the Android project is included in the repository. Would that be possible, @martindale?

**Comment by Forage** [comment]
With Copay being 'temporarily' unavailable in the Google Play store it would be great to have your blessing to include it in f-droid instead.
I was quite surprised to find out I've been missing out on updates all of a sudden. Having the app in f-droid would provide automatic updates again.
