### ISSUE TITLE
Passwords must match text messes up experience

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#2469]
The attached image shows that the "Passwords must match" text interfere's with long passwords.  I observed this caused confusion and multiple retries which could have easily led to loosing the user (user giving up).  Recommend some solution that doesn't steal real-estate from the input field.

![image1](https://cloud.githubusercontent.com/assets/1063765/6951634/aa736dbc-d88a-11e4-865d-a71d6c432dd6.PNG)

**Comment by matiu** [comment]
no longer relevant in 0.10.x
