### ISSUE TITLE
iPhone 4s: Copay iOS app unresponsive, crashes

### ISSUE THREAD

**Issue by jameswalpole** [bitpay/copay#2470]
Numerous bugs in the iOS app on my iPhone 4s device, mostly relating to app speed and responsiveness. Errors confined to this bitcoin wallet app, so not likely to simply be a hardware issue. 

1) App sidebar slow to respond or unresponsive to navigation, frequently taking several minutes and several reloads of the app in order to attempt to create or join a new wallet. 

2) In one test transaction, the app took 30 seconds to one minute to fetch payment data from an invoice. Other users did not experience this, so I do wonder if this is limited to the interaction of the Copay app and the 4s or to versions of iOS below 8.0.

![img_4932](https://cloud.githubusercontent.com/assets/9257396/6952104/9350d43c-d88d-11e4-9fd4-69c7aa1e8973.PNG)

3) App froze/crashed upon creating transaction.

![img_4934](https://cloud.githubusercontent.com/assets/9257396/6952106/98888c6a-d88d-11e4-8ae2-4a52aa510b1a.PNG)

**Comment by matiu** [comment]
should be fixed in 0.10.5. Please reopen if still fails.
