### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by Kirvx** [bitpay/copay#2471]
Hi :)

I'm going to translate Copay in French.

Is that ok if I open the es.po file (https://github.com/bitpay/copay/blob/master/po/es.po) to Poedit and translate all the things?

Thanks :)

**Comment by cmgustavo** [comment]
Hello @Kirvx! 

That’s OK! You have to Open a new file with Poedit selecting *New from POT/PO file* from `file` menu (select `es.po`), then enter a file name (and save it as `po/fr.po`) and translate. So simple!

Thanks a lot for your contribution!

**Comment by Kirvx** [comment]
Ok thanks :)
