### ISSUE TITLE
Balance not refreshing when wallet is not found on the server

### ISSUE THREAD

**Issue by isocolsky** [bitpay/copay#2492]
![image](https://cloud.githubusercontent.com/assets/2073468/7005578/9b100e52-dc4f-11e4-8dc0-2adcf111b8d5.png)
![image](https://cloud.githubusercontent.com/assets/2073468/7005589/b94d8e6c-dc4f-11e4-9cc7-d743455e5893.png)

**Comment by matiu** [comment]
not for .011
