### ISSUE TITLE
iOS specify features

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#2494]
- [ ] add option to require touchId authentication to send funds (per wallet, in preferences)
 (https://github.com/leecrossley/cordova-plugin-touchid or https://github.com/EddyVerbruggen/cordova-plugin-touchid)

**Comment by tonygallippi** [comment]
yes!

**Comment by BluSyn** [comment]
+1

This feature would give me more security confidence, and I would probably use Copay on mobile more. Currently I store more coins in Bread Wallet for iOS because of TouchID support.

**Comment by dabura667** [comment]
Yay +1

**Comment by cmgustavo** [comment]
closes #3289
