### ISSUE TITLE
Cannot build correctly on 0.9.9

### ISSUE THREAD

**Issue by deoxen0n2** [bitpay/copay#2503]
I downloaded version 0.9.9 and ran this:
```bash
bower install
npm install
grunt

npm start
```

Everything was fine. Buy when I browsed to `localhost:3000`, it complaint `Error: [$injector:modulerr] http://errors.angularjs.org/1.3.15/$injector/modulerr?...`.

I tried to fix this, and after changed the version of `ng-idle` to `0.3.5` instead of `*`, it worked.

**Comment by matiu** [comment]
thanks for sharing.

The build procedure should be OK on current 0.10
