### ISSUE TITLE
cannot build apk for Android

### ISSUE THREAD

**Issue by bushido** [bitpay/copay#2506]
ubuntu@ubuntu:~/Downloads/copay/cordova$ make android
make -C project plugins
make[1]: Entering directory `/home/ubuntu/Downloads/copay/cordova/project'
Intalling cordova plugins
cordova plugin add https://github.com/Initsogar/cordova-webintent.git
Fetching plugin "https://github.com/Initsogar/cordova-webintent.git" via git clone
cordova plugin add https://github.com/wildabeast/BarcodeScanner.git
Fetching plugin "https://github.com/wildabeast/BarcodeScanner.git" via git clone
cordova plugin add org.apache.cordova.splashscreen
Fetching plugin "org.apache.cordova.splashscreen" via plugin registry
cordova plugin add org.apache.cordova.statusbar
Fetching plugin "org.apache.cordova.statusbar" via plugin registry
cordova plugin add https://github.com/EddyVerbruggen/LaunchMyApp-PhoneGap-Plugin.git --variable URL_SCHEME=bitcoin
Fetching plugin "https://github.com/EddyVerbruggen/LaunchMyApp-PhoneGap-Plugin.git" via git clone
cordova plugin add org.apache.cordova.inappbrowser
Fetching plugin "org.apache.cordova.inappbrowser" via plugin registry
make[1]: Leaving directory `/home/ubuntu/Downloads/copay/cordova/project'
mkdir -p project/platforms/android/res/xml/
cp android/AndroidManifest.xml project/platforms/android/AndroidManifest.xml
cp android/project.properties project/platforms/android/project.properties
cp -R android/res/* project/platforms/android/res
make -C project android
make[1]: Entering directory `/home/ubuntu/Downloads/copay/cordova/project'
cordova platforms add android
Platform android already added.
make[1]: *** [android] Error 1
make[1]: Leaving directory `/home/ubuntu/Downloads/copay/cordova/project'
make: *** [android] Error 2

**Comment by cmgustavo** [comment]
Hi!
You have to do `make android-debug` onto `~/Downloads/copay/`, not copay/cordova.

Check to do `npm install` and `bower install` before `make android-debug`.

**Comment by bushido** [comment]
I have done that, and it's successful buid apk. But when I open on an Android phone, it doesn't show the UI page. It just seems to work, but suddenly close the program.

**Comment by matiu** [comment]
maybe @matiaspando  can help.

**Comment by matiaspando** [comment]
Hey bushido:  Try running  adb logcat  to check what is going on...you will see a lot of output but the lines that are useful contains  'CordovaLog: .....'

**Comment by cmgustavo** [comment]
I have the same problem when I do `make android-debug`. It opens the application on the simulator, but suddenly closes with the following error in the console log:

```
04-17 10:00:53.870: E/AndroidRuntime(1811): Process: com.bitpay.copay, PID: 1811
04-17 10:00:53.870: E/AndroidRuntime(1811): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.bitpay.copay/com.bitpay.copay.CordovaApp}: 
java.lang.ClassNotFoundException: Didn't find class "com.bitpay.copay.CordovaApp" on path: 
DexPathList[[zip file "/data/app/com.bitpay.copay-1.apk"],
nativeLibraryDirectories=[/data/app-lib/com.bitpay.copay-1, /system/lib]]
```
