### ISSUE TITLE
Question about the Web version

### ISSUE THREAD

**Issue by valuead** [bitpay/copay#2513]
Can someone tell me why v10 removed WEB
"Current Copay version is meant to be run on mobile devices OR desktop application, NOT browsers." 
Whats wrong?

**Comment by matiu** [comment]
Copay uses localstorage to store wallet's data. In a browser, extensions can access the localstorage, so it is not considerer secure.

If you grab Copay source code, and you know what you are doing, you can use Copay on a browser simply running `npm start` and point your browser to `localhost:3000`. But it is not recommended for the average user, and we will not be hosting a public web version.

**Comment by valuead** [comment]
So what is the best solution for the mass public wallet service in your opinion?
is there any desktop version, Win Mac 
what would be the suggestions for a service provider in my case?

**Comment by matiu** [comment]
For desktops we are now providing Chrome App and soon it will be replaced by native apps for the 3 major OS.
