### ISSUE TITLE
Cannot access profile

### ISSUE THREAD

**Issue by warpaul** [bitpay/copay#2522]
Profile was created by a colleague of mine. He gave me login credentials. I logged in via mobile app just fine. Then I added a PIN for added security. After I added a PIN I could not access the profile with email and password on web version, nor could I access via PIN on mobile app. My colleague cannot access profile either. The spinner just keeps spinning (see attached with console errors).
![screen shot 2015-04-15 at 3 10 25 pm](https://cloud.githubusercontent.com/assets/1200098/7167262/a9c15d8c-e381-11e4-9a27-9bbbc81a96b7.png)

**Comment by matiu** [comment]
Could you please try version 0.10 (import from Copay 0.9 Beta feature) and see if you can access your profile?
