### ISSUE TITLE
Input selection ties up unnecessary inputs.

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#2545]
I sent 500 bits into the wallet, immediately after, the other person sent in 300 bits.

I made a proposal for sending 400 bits which locked up all 800 bits... and when the transaction hit the blockchain, it used both 500 and 300 bit inputs.

This may be related to #2544 as it seems it is trying to use the "oldest coins first" which is standard coin selection... even though 500 bits would be older, since both were sent nearly the same time, it seems they recognized 300 bits as oldest.

Maybe coin selection should prioritize "not locking up inputs" by trying to use an input combination that is as close as possible to the required send amount without going under.

My transaction should have only used the 500 bit input and locked up 500 bits only. (in my opinion)

**Comment by dan-da** [comment]
Rather than a one-size fits all approach, perhaps there should be multiple coin-selection algorithms and advanced users could choose between them.  eg:

+ oldest first
+ best fit / smallest change amount
+ random / best privacy

**Comment by matiu** [comment]
Good idea @dan-da, I guess that would be the best approach, it is impossible to fit all criterias. 

Currently, Copay priorities confirmed (+6) inputs, then 1+ confirmation inputs, and the unconfirmed

**Comment by dabura667** [comment]
bump

Happened again today. It's a rarity that I have to worry about sending out multiple payments in rapid succession, but when it does happen, Copay make's it a chore...

Send to multiple people on the roadmap? (Another way of remedying the situation I faced)

**Comment by matiu** [comment]
The latest version of BWS implements a much enhaced input selection  (https://github.com/bitpay/bitcore-wallet-service/blob/master/lib/server.js#L1390) 
that should prevent locking more that it is necessary.

Check test cases (https://github.com/bitpay/bitcore-wallet-service/blob/master/test/integration/server.js#L3468)
to see details of how it behaves.

Also, we have fixed a small race condition if multiple TX proposals are created and broadcasted in short times.

Closing this one then. Please open a new issue with specific details in case a related problem occurs. thanks!
