### ISSUE TITLE
Do not tell user to backup after just importing a backup.

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#2547]
After importing the 1 of 1 backup from my Android Phone to my iPhone, I noticed it asks be to make a backup when I try to access the receive screen.

I just proved that I have a backup of this wallet... so it shouldn't ask me this imo.

**Comment by cmgustavo** [comment]
Agree. Imported wallets should not hide the QR code on receive section.

**Comment by matiu** [comment]
+1

On Sun, Apr 19, 2015 at 9:40 AM, Gustavo Maximiliano Cortez <
notifications@github.com> wrote:

> Agree. Imported wallets should not hide the QR code on receive section.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2547#issuecomment-94272554>.
>



-- 
BitPay.com
