### ISSUE TITLE
Same wallet gives different addresses. Need a way to verify.

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#2548]
This is what I did:

1. backup 1 of 1 Personal Wallet
2. restore backup to second device. (1 was Android, 2 is iPhone)
3. Notice that receive addresses are different.
4. Notice that name is same
5. Not sure if same wallet, bug, or what...
6. sent 500 bits to it.
7. both wallets show 500 bits and I am relieved.

at step 3 4 5 of this, I thought I was on the brink of discovering a huge bug until 7.

I think there needs to be a way to verify that this wallet is in fact the wallet you imported.

Maybe sha256(concat(all xpubs + this wallet's xprv)) and take the first 4 bytes as a fingerprint or something to show the user this wallet is really the wallet they think it is...

Maybe I'm reading too much into it and normal users won't even pick up on the receive addresses being different.

I think them being different is great, but imo there needs to be a way to verify...

**Comment by matiu** [comment]
Interesting idea. Yes, address are auto regenerated when they are used, and we decided to show them the least possible (to simplify UX).

There will be an option to 'show' your private key, in base58 or in bip39, so I guess that would be a solution, what you think?

**Comment by dabura667** [comment]
> Yes, address are auto regenerated when they are used

This was not used at all. The wallet had 0 transactions, but I had imported it to 2 separate devices (the same exact 1 of 1 wallet) and each one of the devices had a different address...

> There will be an option to 'show' your private key, in base58 or in bip39, so I guess that would be a solution, what you think?

I don't think it would be difficult to just hash the xpubs + xprv while decrypting the imported wallet and use that to make a fingerprint or maybe a graphicon (like github uses by default) that shows a shape based on the fingerprint. It would be a quick way to verify that this is the correct wallet.

However, if you had a "view xprv" then it would be a solution... but I still think people will freak out when they see different addresses on the same wallet even though the number of transactions are the same.

**Comment by matiu** [comment]
> This was not used at all. The wallet had 0 transactions, but I had imported it to 2 separate devices (the same exact 1 of 1 wallet) and each one of the devices had a different address...

Sorry, my mistake. When a wallet is imported it always generate a new address.


OK we will got to the view xpriv since that can be used  for others things also.

**Comment by dabura667** [comment]
Could you also view all participants xpub as well?
Maybe I'm just tinfoil hat, but when I import to a new device I always want to double check nothing has been tampered in transit... maybe I'm just paranoid.

**Comment by matiu** [comment]
for copayers, I guess you are looking for something like
https://github.com/bitpay/bitcore-wallet/blob/master/bin/wallet-confirm

What you mean by tampered in transit? The wallet backup (that contains the xpubs) is encrypted and signed by the password you entered when doing the backup, so no tampering possible there.

Also, bitcore-wallet-service client does check signatures on copayer's requests so if the server tried to tamper or create a message it will be detected.

**Comment by matiu** [comment]
in the current version of copay, settings -> advanced -> wallet info will show the wallet's pub keys.
