### ISSUE TITLE
Chrome App can not import copy-pasted json data

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#2549]
Android and iPhone generate copy-pasted data that you can e-mail... however, "oh yeah, you need to save it to a file as "xxx.aes.json" in order to import into Chrome" was not explained.

Chrome should allow importing of copy pasted json.

**Comment by matiu** [comment]
Given that now the 'normal'  import / export is using mnemonics and the blog export is only for special case, I think we can close this one.
