### ISSUE TITLE
Copy-paste import does not sanitize input

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#2550]
if someone mailed the backup to themselves along with the explanation paragraphs before and after, they will most likely copy the whole thing if on mobile. ("Select All" is much easier than selecting the entire json.)

It would be nice if the copy-paste import would search for a valid json inside.

currently the mail looks like this:

```
Here is the encrypted backup of the wallet Personal Wallet:

{"iv":"..."}

To import this backup, copy all text between {...}, including the symbols {}
```

So you could search the contents for the position of "{\"iv\":\"" for finding the beginning and "\"}" for the end. This way a user could just copy paste the whole mail and still be fine.

**Also** I think you should refrain from adding text after the json, as some larger wallets can have pretty big jsons... and people might not see it. (it explains how to import the json... so it should be at the top imo.)

**Comment by cmgustavo** [comment]
Hello @dabura667, 

I like your idea! I think we could implement this feature in the next release. Anyway if you want, you can make the changes and send your own  pull request. It would be awesome to see an active community of Copay users!

Thank you!

**Comment by dabura667** [comment]
Thanks for the consideration. I was going to do it myself, but I'm very busy for the next couple of days and decided to just quickly jot down all the issues I noticed rather than try to make PRs for all of them.

I look forward to Copay's future improvements.

**Comment by matiaspando** [comment]
Good idea!

**Comment by matiu** [comment]
this is fixed on current versions.
