### ISSUE TITLE
Master extended private key setting

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#2553]
0.10.3 - is not a user friendly setting name. I have no idea what this is for and suppose most users won't.

**Comment by matiu** [comment]
Where you see that setting? In "Advanced" at wallet creation?

On Sun, Apr 19, 2015 at 9:26 AM, Andy Phillipson <notifications@github.com>
wrote:

> 0.10.3 - is not a user friendly setting name. I have no idea what this is
> for and suppose most users won't.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2553>.
>



-- 
BitPay.com

**Comment by ajp8164** [comment]
Yes
