### ISSUE TITLE
Bechi's Send Screen prototype

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#2554]
0.10.3 - is a nicer ux than the standard one being used now.

**Comment by matiu** [comment]
The problem with that idea is that we cannot programmatically 'paste' from
clipboard on Cordova, so an address input is needed so the user can paste
(which is the most common scenario for entering an addresS).

On Sun, Apr 19, 2015 at 9:27 AM, Andy Phillipson <notifications@github.com>
wrote:

> 0.10.3 - is a nicer ux than the standard one being used now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2554>.
>



-- 
BitPay.com

**Comment by ajp8164** [comment]
Bummer.  Keep this design in mind - hopefully you'll be able to figure a way to do it.

**Comment by matiu** [comment]
yeap, we loved it to.

On Sun, Apr 19, 2015 at 9:50 AM, Andy Phillipson <notifications@github.com>
wrote:

> Bummer. Keep this design in mind - hopefully you'll be able to figure a
> way to do it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2554#issuecomment-94274028>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by matiu** [comment]
this is been fixed in the new send UX.
