### ISSUE TITLE
Storing Bitcore Wallet Service URL on a per-wallet basis.

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#2567]
Currently the only way to change the Bitcore Wallet Service is to do it from any one wallet... but this setting is changed for all wallets if you change for one. (So changing for ABC wallet will also change for XYZ wallet automatically.)

Should the Bitcore wallet service option be stored on a per-wallet basis (this seems intuitive as you can only access the option through wallet specific menu) rather than per-device basis (current behavior)?

I personally think yes.

I know not many people will touch it. But I am planning on using a private instance for a project and would like access from my Copay app without having to switch back and forth between servers when I switch to personal wallet and project wallet.

Also, It would be nice if you could specify a custom Bitcore Wallet Service URL when you create / join a wallet (via Advanced Options)

**Comment by matiu** [comment]
On Mon, Apr 20, 2015 at 2:31 PM, dabura667 <notifications@github.com> wrote:

> Is there a way to do this with current builds?
>
No, currently you need to change it afterways. Do decided to to it that
what to make it simpler.


> Also, currently the only way to change the Bitcore Wallet Service is to do
> it from any one wallet... but this setting is changed for all wallets if
> you change for one. (So changing for ABC wallet will also change for XYZ
> wallet automatically.)
>
Should the Bitcore wallet service option be stored on a per-wallet basis
> (this seems intuitive as you can only access the option through wallet
> specific menu) rather than per-device basis (current behavior)?
>
> I personally think yes.
>
> I know not many people will touch it. But I am planning on using a private
> instance for a project and would like access from my Copay app without
> having to switch back and forth between servers when I switch to personal
> wallet and project wallet.
>

Yes, it is a global setting. I dont think having multiples bws settings (ie
per wallet), will be a good idea, because it could confuse the user.



> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2567>.
>



-- 
BitPay.com

**Comment by dabura667** [comment]
In this case, having the bws setting in a global settings menu would be better. Not a wallet specific menu as it is now.

However, I think the current behavior would be confusing to the user either way, as the only people who will care about the setting will think it is per-wallet (being in a wallet specific menu) and the people who don't care about it will leave it as default and ignore it either way (with or without a fix).

Judging by your response I think the following would fix this:

1. Move bws setting to non-wallet-specific menu.

But I personally think:

1. Storing bws setting on per-wallet basis to match current expected behavior.

Would not change the ux drastically.

**Comment by dabura667** [comment]
Maybe moving this setting to the same menu as #2573 would be best.

In the wallet selection side-panel, there could be a global options menu in the lower left corner of the side-panel.

**Comment by tonygallippi** [comment]
It would be best if the BWS can be set by the wallet creator, and all copayers who join will inherit the BWS settings per-wallet.   The experience should be similar to setting up your phone with multiple POP3 email accounts, with a server setting per account.

**Comment by dabura667** [comment]
Tony

I fully agree.

This would mean the shared secret string for pairing would need to encode the bws url address as well.

So it might add a little complexity to pairing, but it is probably the best course of action.

**Comment by dabura667** [comment]
Slightly related:
https://github.com/bitpay/bitcore-wallet-service/issues/215

It would be nice to allow individual users who don't want to buy a certificate to still use SSL.

I would assume that "more people starting up their own instances" was one of the goals of separating copay into BWS + Copay, and having to buy a trusted SSL cert in order to do it with ssl is kind of a barrier to entry.

I could join my friends wallet which he runs on his own private BWS while at the same time (in the same app) using a bitpay-run wallet as well, with one-tap switch between wallets.

I am very excited about BWS + Copay. Very excited indeed.

**Comment by martindale** [comment]
I'm going to toss in a +1 for this as well; I'm running into an issue where I now need to switch between several different BWS servers (one personal, one BitPay), which is inconvenient on mobile.  When a user joins a wallet created by someone, the address of the "organizing service", or the BWS server, should be supplied as part of the secret data.

This also has seriously interesting implications if we can turn all the BWS nodes into a mesh network, using something like @gordonwritescode's Muttr project – only the "source" servers store the proposals, and only the intended recipients can retrieve the messages.  See also bitpay/bitcore-wallet-service#216.

**Comment by dabura667** [comment]
1. Allow the creator to set BWS server on creation.
2. encode the server info into the b58check secret.

ex. http://www.example.com/bws/api/ could be encoded by the following steps:
1. if the address ends in "/bws/api" we can automatically remove it and set a flag bit DEFAULT_PATH
2. remove the "http://" or "https://" and set a SSL_ON flag bit 1 for https.
3. take www.example.com and convert / compress and tag on the two flag bits from 1 and 2 somehow. (If you base58 encode the ASCII, you could use the MSB of the first two letters as all URL kosher letters have a 0 as their MSB anyways)
4. include it in secret data.

Note if the user places anything before or after the /bws/api/ then we must encode the full path of the URL as well.

This would make it so the joiners will not have to fiddle with the advanced settings and they can just connect to the necessary server.

**Comment by martindale** [comment]
That's a great proposal, @dabura667.  I really like that approach.

My only point of contention is allowing non-encrypted transport (HTTP) at all.  Node modules like `pem` allow for easy automatic creation of certificates, so perhaps we could just automatically create a certificate for every BWS instance.  If we can't achieve accurate authentication just yet (need to replace the PKI), we should at least offer encryption.  See also bitpay/bitcore-wallet-service#217.

**Comment by matiu** [comment]
done in 1.5.2
