### ISSUE TITLE
Create / refresh Firefox add-on

### ISSUE THREAD

**Issue by marvin8** [bitpay/copay#2577]
I have found Firefox to behave better on my low power ARM based embedded processor (Cubox-i) than Chrome.

If at all possible it would be great to have a Firefix add-on available for CoPay as well.

**Comment by matiu** [comment]
Firefox Extension support was suspended since Firefox add-ons do not run in sandbox (as Google Chrome Apps) so there is no way to prevent other extensions to access Copay's data.
