### ISSUE TITLE
Lost access to funds on update, can't import from 0.9

### ISSUE THREAD

**Issue by kyletorpey** [bitpay/copay#2585]
It appears that I've lost access to my funds. I followed the instructions to import a profile from beta v 0.9, but when I go to import using my username and password, it simply flashes "importing..." forever. I only stored my profile locally. This has happened on two separate devices that are used for a multi-sig wallet.

**Comment by matiu** [comment]
- Did you have you profile on the cloud or on the device?
- What devices are you using?
- Do you have backups of both devices?
- What version of Copay are you coming from?

thanks.

**Comment by kyletorpey** [comment]
1. Only on the device (locally)
2. Asus Desktop and ThinkPad Edge E545. Both running Ubuntu 14.04. There is also a third co-signer (Samsung Note II)
3. I have a backup of the desktop one. Trying to find the password.
4. Couldn't tell you. Chrome Apps auto-updated in the background.

Would there be any way to revert back to the old version of Copay? I see a 0.9.7 folder in the Chromium Extensions folder on my desktop.

**Comment by matiu** [comment]
Thanks for your responses

Before doing anything else you should do the following on both devices:
1. App the chrome app
2. Right click and inspect element
3. Go resources -> localstorage -> chrome-extension 
4 go should see some keys named "wallet::xxxx". Copy the keys and values to a text editor. 

Once you have successfully do this in both devices, you can use an old copay app version to recover funds. Please let me know how this precedure goes, and i can give
You further instructions

**Comment by kyletorpey** [comment]
I assume you meant open the chrome app instead of "app the chrome app." I did that, but right-clicking everywhere in the app does nothing.

**Comment by kyletorpey** [comment]
Trying to figure out how to inspect element. Could be due to me using Chromium instead of Chrome or something?

Side note: I seem to have the correct password for my backup. Copay gives me a different error when I type in the correct password than when I type in anything else. Going to try to import that into my smartphone.

**Comment by kyletorpey** [comment]
Importing my backup to my phone seemed to work. Was able to send the coins to another wallet. Thank you for the assistance.

**Comment by matiu** [comment]
good to hear. Thanks.
