### ISSUE TITLE
wallet delay receiving from Bittrex?

### ISSUE THREAD

**Issue by chemival** [bitpay/copay#2598]
Hi,

Just following your request to test out the new Blitz wallet. I sent 10 Blitz to my wallet address bFJ2pvaUAkohbePBgdYYHTQpTg9pZZv9hS from Bittrex @ 18.59 BST (20mins ago). I confirmed the transaction via email and this shows as completed in Bittrex but still no sign of it appearing in my wallet. Could just be a delay obv, but also no sign of anything unconfirmed in history?

Txn ID is cc55e5ea501df5dcc6e41a9ccb4df40376dd374ac7bbfe7099a297505b28142f

Please take a look.

Thanks

![bittrexblitz](https://cloud.githubusercontent.com/assets/12088693/7304170/67e725dc-e9ed-11e4-80d3-9aaa97153fca.jpg)

**Comment by matiu** [comment]
Your probably meant to send this bug report to other project. Copay does not support addresses starting with 'b'
