### ISSUE TITLE
Translation strings missing

### ISSUE THREAD

**Issue by Kirvx** [bitpay/copay#2631]
Hi :)

HOME,RECEIVE and HISTORY are missing from template.pot

**Comment by Kirvx** [comment]
"Personal Wallet" above the balance too.
And DELETE WALLET

**Comment by dabura667** [comment]
![screenshot_2015-04-26-06-12-10](https://cloud.githubusercontent.com/assets/6586275/7334860/70a490de-ebdb-11e4-87f0-3530bbca1ea9.png)
![screenshot_2015-04-26-06-12-04](https://cloud.githubusercontent.com/assets/6586275/7334862/7eb7e626-ebdb-11e4-8ebb-03b196c569ca.png)
![screenshot_2015-04-26-06-11-51](https://cloud.githubusercontent.com/assets/6586275/7334863/976fcb0c-ebdb-11e4-81b1-31162b240fd1.png)
![screenshot_2015-04-26-06-11-19](https://cloud.githubusercontent.com/assets/6586275/7334867/a40f2ccc-ebdb-11e4-859a-9b15f1df934d.png)
![screenshot_2015-04-26-06-10-47](https://cloud.githubusercontent.com/assets/6586275/7334870/b16cc7a8-ebdb-11e4-92ac-944c50bd7448.png)
![screenshot_2015-04-26-06-10-39](https://cloud.githubusercontent.com/assets/6586275/7334872/b8c4d73e-ebdb-11e4-86e3-9231ea3911a3.png)
![screenshot_2015-04-26-06-07-41](https://cloud.githubusercontent.com/assets/6586275/7334875/c123507c-ebdb-11e4-9cee-395cd26978f6.png)
![screenshot_2015-04-26-06-07-27](https://cloud.githubusercontent.com/assets/6586275/7334879/d1695b20-ebdb-11e4-9065-8b64bad0e704.png)
![screenshot_2015-04-26-06-07-06](https://cloud.githubusercontent.com/assets/6586275/7334881/d9ea00b0-ebdb-11e4-9c21-08d8427b30e2.png)

My bitcoin address
Sent
Received
Language
(日本人) → (日本語)
Wallet invitation
Paste invitation here
Master extended private key (this shows up somewhere else translated though)
If not given, a secure key will be generated
BIP32 master extended private key
If not given, a random key will be generated
BIP32 master extended private key
Import legacy wallet
Importing...
EMAIL
Email
USERNAME
Username


These are the terms I could find.

**Comment by dabura667** [comment]
Also, 2 of 3 etc "of" requires the number order to be reversed in Japanese so I tried using /  ... But it is difficult to understand.

I will return to English "of" for the time being once I get access to a computer.

Would it be possible to use variables to represent the numbers so I could switch order.

**Comment by dabura667** [comment]
![screenshot_2015-04-26-06-32-35](https://cloud.githubusercontent.com/assets/6586275/7334952/0f989f26-ebde-11e4-99f5-9866910e4c46.png)
Here's the delete wallet screen too

Need that string translatable

**Comment by matiu** [comment]
Thanks a lot for your detailed report!

We need to create a script that extract the translatable strings from the
Javascript code (currently we are only exposing HTML strings). That is why
there are still many strings to add. We don't want to do it by hand since
it will be too difficult to maintain. Probably in the next ~10days that
will be ready.

thanks

On Sat, Apr 25, 2015 at 6:33 PM, dabura667 <notifications@github.com> wrote:

> [image: screenshot_2015-04-26-06-32-35]
> <https://cloud.githubusercontent.com/assets/6586275/7334952/0f989f26-ebde-11e4-99f5-9866910e4c46.png>
> Here's the delete wallet screen too
>
> Need that string translatable
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2631#issuecomment-96282400>.
>



-- 
BitPay.com

**Comment by dabura667** [comment]
I believe crowdin has a library to automate translations replacing in source files...

I think that is how Electrum does it

```python
from i18n import _

some_text = _("Hey!")
```

Any text with _( ) around it is automatically replaced via automation

Maybe the Electrum team made it up themselves, but it seems like a good way to do it.

**Comment by dabura667** [comment]
If all strings in the source were surrounded by a _( ) it might be easier to run a script that searches through each source file and looks for _( ) and replaces.

```javascript
var _ = function(x){return x};

var some_result = some_function(x, y, _("Some text"))
```

**Comment by cmgustavo** [comment]
We are using `gettext` for this function. Maybe we could replace `gettext` by `_()` in a the near future
