### ISSUE TITLE
Invite other users via email to a shared wallet

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#2636]
Is it possible to create an html (alternative friendly) email with a button to to Ch to launch my wallet and give the code to the wallet? The landing view would ask me which wallet to apply it to or create a new one using the code.

**Comment by ajp8164** [comment]
0.10.4 iPhone

**Comment by gabrielbazan7** [comment]
On desktop you can copy the code and and in mobile you can share it. You think this is enough to close this ticket @ajp8164 ?

**Comment by ajp8164** [comment]
Yeah - it could be better integrated into BWS as the share point - idk, it's a hard thing..  go ahead and close..
