### ISSUE TITLE
Wallet view left/right slide is not standard animation

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#2637]
When the main (home) view slides right to reveal the wallet list the animation is not correct - the wallet list view (the view that is revealed) should not slide in and out - it should appear to be fixed/stationary underneath the main (home/send/receive/tx) view.

0.10.4 iPhone

**Comment by BitpopCoin** [comment]
Android is also not proper material design

**Comment by matiu** [comment]
fixed on Copay 2.0
