### ISSUE TITLE
Private Label

### ISSUE THREAD

**Issue by jodyrb** [bitpay/copay#2648]
This has just become my favorite wallet. Is there any easy way to clone this and create a "private label" version of the wallet/apps? Thank you.

**Comment by matiu** [comment]
Great to know!

There is no 'guide' to do so, but you are welcome to do it and please let us know the results!

**Comment by jodyrb** [comment]
Is there a reason why the backup can not be copied to the clipboard in the chrome app?

**Comment by cmgustavo** [comment]
Because the only way to copy to clipboard on desktop is to use an external flash plugin, that we consider it ’s insecure (https://github.com/zeroclipboard/zeroclipboard).

**Comment by jodyrb** [comment]
OK, great. I'm not asking because I doubt you... I want to support this format and I want to know why I support it. I want to be able to tell people why your product is superior to other options. That said, there is not an easy way to export from Chrome and import to Android. Would it be insecure to save it as a txt file?

**Comment by jodyrb** [comment]
OK, so... I am starting to make sense of this more now. Really, there is no need to transfer the wallet between devices if you create a shared wallet. For example, if I create a 1of2 wallet and put "Laptop" as one name and "Phone" as the other name... either one can sign. This is awesome!
