### ISSUE TITLE
Copay Wallet has diappeared

### ISSUE THREAD

**Issue by kharoof** [bitpay/copay#2657]
I have a windows phone (windows 8.1) and I had the Copy app installed. I am not sure what version it was but I installed it in the last few months. Today I tried to check my balance and I got a start screen as if it was the first time I opened Copay. I am guessing that the app must have updated to version 0.10. There is a link on this site that shows how to copay migration to v.10. I tried this but the app is saying my profile is not found.

How can I recover my old wallet and bitcoin balance?

**Comment by matiu** [comment]
Did you had your wallet  stored on the device or on the cloud?

What kind you backup you have?

**Comment by kharoof** [comment]
My wallet is stored on my device. When I set it up it did require me to set up a username and password which I had written down. When I noticed this morning that it has updated I tried to use the import facility to migrate from v0.9 (with import from cloud option turned off) and that is when I am getting the message saying my profile is not found. Would the update have overwritten my profile on my phone?

**Comment by matiu** [comment]
I am sorry your are having this problem.

The new version (0.10) uses different storage slots than 0.9, so no
overwrite is
possible.

Note that 'not found' means that either the username or the password is
wrong (the storage slot is determined by the to entries). Be sure to enter
them correctly.

Do you have any backups of your profile? In that case you can restore the
wallet in the legacy version as described at
https://github.com/bitpay/copay/releases/tag/v0.10.0



On Wed, Apr 29, 2015 at 8:46 AM, kharoof <notifications@github.com> wrote:

> My wallet is stored on my device. When I set it up it did require me to
> set up a username and password which I had written down. When I noticed
> this morning that it has updated I tried to use the import facility to
> migrate from v0.9 (with import from cloud option turned off) and that is
> when I am getting the message saying my profile is not found. Would the
> update have overwritten my profile on my phone?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2657#issuecomment-97399129>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by kharoof** [comment]
Thanks for the help. I got the wallet restored. As it happened I was typing the password incorrectly. As a suggestion it might be worth considering updating the error message for people like me or adding the clarification that not found can mean incorrect password. Thanks for the help.

**Comment by matiu** [comment]
Happy to hear that!

Thanks for the suggestion. I hope you enjoy the new version, it should work
much better on WP!


On Wed, Apr 29, 2015 at 10:12 AM, Ed <notifications@github.com> wrote:

> Thanks for the help. I got the wallet restored. As it happened I was
> typing the password incorrectly. As a suggestion it might be worth
> considering updating the error message for people like me or adding the
> clarification that not found can mean incorrect password. Thanks for the
> help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2657#issuecomment-97421625>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!
