### ISSUE TITLE
After upgrade from v0.9 to v0.10 failed to open profile/wallets

### ISSUE THREAD

**Issue by ihqtzup** [bitpay/copay#2665]
Platform: Android 5 and Sony Xperia Z3 compact
Software: Copay v0.9

1. Everything was working as expected.
2. Upgraded Copay Android v0.9 to v0.10.
3. Imported v0.9 profile from device succesfuly.
4. Everything was working as expected.
5. Rebooted phone.
6. Copay was unable to open profile or wallet (see screenshots).
7. Tried to install Copay to another Android phone and import wallet without success.
8. Unable to import v.0.9 backup with v0.10 with another Android phone
9. Unable to import v0.9 backup with https://copay.io/in/0.9 software.
10. At this moment I'm unable to access my profile and wallets at all

![screenshot_2015-04-28-12-38-09](https://cloud.githubusercontent.com/assets/1743396/7409074/00095f72-ef2c-11e4-939c-7a59a4e68920.png)
![screenshot_2015-04-28-12-38-00](https://cloud.githubusercontent.com/assets/1743396/7409075/000ddee4-ef2c-11e4-8bbf-ec0807c1e322.png)
![screenshot_2015-04-28-12-37-49](https://cloud.githubusercontent.com/assets/1743396/7409076/000e15da-ef2c-11e4-886b-57d5cd6f68b9.png)

**Comment by matiu** [comment]
Hello, 

I am sorry you are having this problems. Thanks for the detailed report. 

It will really help to check Copay's logs to  understand what is happening:

On your phone:
- please upgrade to 0.10.5. (Available now at the play store). 
- open copay and go to preferences > about copay > see session logs
- check if there is something wrong (errors are in red). 

Please let us know. 
  

An other way would be to use browser version of copay v0.10.5 to import your wallets from the cloud and access you funds. (Check the Chrome extension) at copay.io.

**Comment by ihqtzup** [comment]
How do I do that?

**Comment by matiu** [comment]
In 0.10.5 go to Preferences -> About Copay -> See Session logs. 

Thanks.

**Comment by ihqtzup** [comment]
Our team investigated the problem and we have found solutions. I had removed my SIM card to another phone (see pictures warning about no SIM card) and after reboot Copay stopped working. After I installed another SIM card (not the same I had before) Copay started normally with original profile and wallets.

My colleague thinks that Copay is throwing an exception which is not catched if there is no SIM card.

**Comment by matiu** [comment]
thanks for sharing this.

On Thu, May 7, 2015 at 11:10 AM, ihqtzup <notifications@github.com> wrote:

> Our team investigated the problem and we have found solutions. I had
> removed my SIM card to another phone (see pictures warning about no SIM
> card) and after reboot Copay stopped working. After I installed another SIM
> card (not the same I had before) Copay started normally with original
> profile and wallets.
>
> My colleague thinks that Copay is throwing an exception which is not
> catched if there is no SIM card.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2665#issuecomment-99881321>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by ihqtzup** [comment]
The same issue again. Removed sim card and started Copay. Error message and unable to start. I put the same SIM card back to the phone but Copay did not start. Tried also with another SIM card. Unable to get it working again.
![screenshot_20181008-130319](https://user-images.githubusercontent.com/1743396/46603565-148aa500-cafc-11e8-8832-b5152c6730ac.png)
