### ISSUE TITLE
Create Wallet Offline

### ISSUE THREAD

**Issue by jodyrb** [bitpay/copay#2667]
Can you please educate me about why an internet connection is required to create a new wallet? I'm not a developer, but it seems that it would be possible to use an old/offline device as a cold-storage wallet. Any other thoughts on this? Thank you.

**Comment by matiu** [comment]
Copays use Bitcore-wallet-service to connect to the blockchain and other copayers. It needs to be only to register the wallet at the service.

For cold storage usage you can use the air-gapped mode of Bitcore-Wallet https://github.com/bitpay/bitcore-wallet
