### ISSUE TITLE
Bower error

### ISSUE THREAD

**Issue by geopayme** [bitpay/copay#2678]
when I attempt to install I receive an error on this command

bower install

error -->
"/usr/bin/env: node:No such file or directory"

Are the instructions correct?

**Comment by matiu** [comment]
you need to install `node` (https://nodejs.org/) to run bower.

On Mon, May 4, 2015 at 8:35 AM, Adonis Valamontes <notifications@github.com>
wrote:

> when I attempt to install I receive an error on this command
>
> bower install
>
> error -->
> "/usr/bin/env: node:No such file or directory"
>
> Are the instructions correct?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2678>.
>



-- 
BitPay.com

**Comment by geopayme** [comment]
Ohhh you are right... I am on the wrong server... I need time off!

Thanks Matias

**Comment by matiu** [comment]
np :)
