### ISSUE TITLE
Balance Refresh

### ISSUE THREAD

**Issue by jodyrb** [bitpay/copay#2690]
How does the wallet balance refresh? Could there be a refresh button or, on the mobile apps, the ability to "pull down" to refresh? Thanks.

**Comment by matiu** [comment]
+1 on this!

Currently the balance is refreshed with a wallet tx is detected thru a
socket connection to bitcore-wallet-server or when the connection is
interrupted or restored, but a manual trigger would be also fine, IMO.

On Thu, May 7, 2015 at 10:33 AM, jodyrb <notifications@github.com> wrote:

> How does the wallet balance refresh? Could there be a refresh button or,
> on the mobile apps, the ability to "pull down" to refresh? Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2690>.
>



-- 
BitPay.com
