### ISSUE TITLE
The transaction could not be created: Bad signatures   when applying copay in altcoin

### ISSUE THREAD

**Issue by 9cat** [bitpay/copay#2693]
![image](https://cloud.githubusercontent.com/assets/1379110/7527050/acc7ce1a-f4cc-11e4-941a-3257019251f2.png)

when try to send the fund to the non-multisig address, it shows: The transaction could not be created: Bad signatures .

However, if I send to the multisig address, it works fine for this altcoin.

Any ideas how to solve this issue?

**Comment by matiu** [comment]
Be sure you have fork bitcore-wallet-client and -server for your alt coin and that test are passing with the modification. Other than that, there is not a lot of help we can do for your alt coin, better report this in the relevant fork.
