### ISSUE TITLE
Disappearing wallet

### ISSUE THREAD

**Issue by fonix232** [bitpay/copay#2697]
Some friends of mine and I began to use Copay as an easy multisig wallet option. We created the wallet, 4-of-4, and added some funds (one BTC). However, one of our signed in phones bugged out, and lost all the data, including the shared wallet private keys, etc. - the app simply restarted and it was completely empty.

This was about two minutes after creating the wallet, and thus, no backups were made of that specific private key. He is, however, not the wallet starter.

Is there a way to recover the funds from the wallet any way?

**Comment by dabura667** [comment]
> Is there a way to recover the funds from the wallet any way?

Nope, the keys were all on your devices. So unless you're just looking at it wrong or something... and your friend really lost his wallet, then the coins are lost.

For future reference:
1. Create wallet.
2. Backup wallet. (only have to make 1 backup for copay and it lasts forever)
3. Insert money.

**Comment by fonix232** [comment]
There is ONE backup but that was not made on the phone that we lost the keys at.
He closed the app, next time he started up it was gone. It is a multi-sig wallet, 4-of-4, and one of these keys are missing.

**Comment by matiu** [comment]
I am afraid there is no way to recover your funds, if the keys were definitely lost. 

Creating a m-n with `m = n` wallet means that **all** copayers are needed to move the funds, that is normally a very risky scenario since the unavailability of a single peer would lock the wallet.

**Comment by fonix232** [comment]
That is most unfortunate. We had a whole Bitcoin in there.
I will try to recover the data from his device (turns out he was using the Chrome extension, not his phone...), and see what we can do about that.

**Comment by fonix232** [comment]
Okay, I take it all back. It was an issue from Chrome itself - it forgot the user and tried to re-login, creating a secondary profile... It's working now and we got the BTC out.

**Comment by matiu** [comment]
Great to hear that. Thanks for letting us know.
