### ISSUE TITLE
Migration/Import from old cloud not possible

### ISSUE THREAD

**Issue by mariulab** [bitpay/copay#2702]
the old web version https://copay.io/in/0.9 is not working any more -> "404 Not Found"

Then, the server "https://insight.bitpay.com:443/api/email" is no longer working for importing old wallets from the cloud, can you please fix that, it says always "Profile not found".

**Comment by matiu** [comment]
Hi,

We are working to set the legacy cloud import server back again, sorry the
inconveniences. I will update this thread as soon as it is ready again.

On Mon, May 11, 2015 at 11:44 PM, mariulab <notifications@github.com> wrote:

> the old web version https://copay.io/in/0.9 is not working any more ->
> "404 Not Found"
>
> Then, the server "https://insight.bitpay.com:443/api/email" is no longer
> working for importing old wallets from the cloud, can you please fix that,
> it says always "Profile not found".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2702>.
>



-- 
BitPay.com

**Comment by Abd3lk4d3r** [comment]
I have the same issue please try to back up it as soon as possible .

**Comment by Abd3lk4d3r** [comment]
Please solve this problem i have my coins on Copay and I don't want to loose it .

**Comment by GitAleB** [comment]
Hi,
same for me, "Import from Copay BETA 0.9" results in a PNOTFOUND error.

**Comment by matiu** [comment]
Hi, just an update in this. We have migrated the to a new server the legacy import service, and we are testing it now. It will be online soon. Thanks for your patience.

**Comment by Abd3lk4d3r** [comment]
Thanks a lot for the hard work I really thank you and supporting you and will also ask all users to 
wait and understand the situation .

**Comment by matiu** [comment]
ok, it should be working now. We have temporary restored the old cloud storage in the public insight server.

Could you please test and let us know if you have any problems?

Thanks a lot and sorry for the inconveniences.

**Comment by Abd3lk4d3r** [comment]
Hi why this site not working https://copay.io/in/0.9 ?

**Comment by GitAleB** [comment]
Hi
thanks a lot. Migration did work, my wallet is restored. Great!

**Comment by matiu** [comment]
@GitAleB glad to hear that. Thanks for letting us know.

@Abd3lk4d3r we just installed https://copay.io/in/0.9. But please note that that should ONLY be used to import and migrate wallets, we are not supporting 0.9 anymore.

**Comment by JackScottie** [comment]
When I use the Chrome app to import an old wallet from the cloud, the first empty 1 of 1 wallet successfully imports, but not the multi-sig wallet that I need. I can see both wallets when I use the same login information but access it through https://copay.io/in/0.9.

![screen shot 2015-05-15 at 3 10 45 pm](https://cloud.githubusercontent.com/assets/4743575/7667716/4b03ca9a-fbc9-11e4-8f5f-a2b387fdf7a0.png)

I have backups of both my profile.json file and of my wallet json.aes file and the passwords that go with them, but they also fail to import into v 0.10.7.  I have also tried copying the backup as text and pasting it into the Android app and importing that way, but it also fails.

**Comment by vmatekole** [comment]
Hi, 

https://copay.io/in/0.9. - is down! I would like to retrieve my old wallet asap!

**Comment by matiu** [comment]
https://copay.io/in/0.9/#!/

working again. thanks for the report.
