### ISSUE TITLE
Easy transfer between (local) Copay wallets

### ISSUE THREAD

**Issue by fonix232** [bitpay/copay#2708]
I'd like to suggest a drop-down feature for transferring funds between wallets stored in the same Copay session.

**Comment by dabura667** [comment]
> drop-down feature

Can you be more specific?

**Comment by fonix232** [comment]
Sorry if it wasn't clear. On any "Send" page of any wallet, the "Address" field could have a drop-down list, containing the other wallets' addresses on the same instance/session. Say, I have a Personal wallet, a 2-of-3 wallet with my roommates to pay rent, and a 4-of-5 wallet with my friends to pay at the bar when we have a night out. I want to be able to e.g. transfer BTC form my Personal wallet to the 2-of-3 with a single click, and not by going to the target wallet, copying the receive address, then going back to the wallet I want to send the BTC from, and paste, etc. - a shortcut, if you prefer that.

Most online banking systems offer a similar feature if you have multiple accounts open.

**Comment by matiu** [comment]
Interesting idea. @bechi

**Comment by fczuardi** [comment]
was this implemented? or closed as wontfix?

**Comment by matiu** [comment]
it is implemented in v1.1.1

On Mon, Jul 13, 2015 at 10:26 AM, Fabricio C Zuardi <
notifications@github.com> wrote:

> was this implemented? or closed as wontfix?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2708#issuecomment-120925748>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!
