### ISSUE TITLE
Missing translation strings

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#2714]
![screenshot_2015-05-13-01-01-32](https://cloud.githubusercontent.com/assets/6586275/7606273/28526106-f90c-11e4-84a8-f17ebf31bf78.png)

![screenshot_2015-05-13-01-02-53](https://cloud.githubusercontent.com/assets/6586275/7606279/347e1830-f90c-11e4-93bd-aed1f5e60fdb.png)

me
Logs

me should definitely be translated.

**Comment by cmgustavo** [comment]
We have a lot of strings in logs system, and also it 's only for developer. So, I do not think that this is important for the end user (IMHO).

**Comment by dabura667** [comment]
Ah no

I mean the word "Logs" at the top of the screen only

Of course all logs should be in english, Japanese programmers are used to this

**Comment by cmgustavo** [comment]
Ah! :)

https://github.com/bitpay/copay/pull/2716
I already just sent my PR with these issues. Thanks!
