### ISSUE TITLE
Problem with Windows Phone Copay Application

### ISSUE THREAD

**Issue by utc66** [bitpay/copay#2729]
Hi,

I've got serious issues with my Windows Phone Copay app.
The app worked as it should since yesterday, but an hour ago it stopped working correctly.

It always returns the error "Wallet Server Error" - "Error at Wallet Service: Could not fetch transactions:[object Object]

and 

"Wallet Server Error" - "Error at Wallet Service: Could not fetch unspend outputs:[object Object]

As I saw in the settings of my wallet, the Bitcore Wallet Service is set as always: https://bws.bitpay.com/bws/api

And another problem was detected with the backup function: As I tried to create a backup with my own chosen password, everything worked so far correctly and it returned me an encrypted wallet backup. But if I try to import it on another Copay Wallet, no matter which device, it says "Password Incorrect"

I've got lots of Bitcoins in my wallet and want to access...

I really like your app and want it to get working again soon. Also I need to access to my coins...

Please fix this serious issues!

Best
utc

**Comment by eaxvac** [comment]
Same issue here on my Nokia Lumia 1520.
Looks temporary though, your private keys are same.

Sent from my Windows Phone
________________________________

**Comment by mikexine** [comment]
Me too, Windows Phone 8.1 with Lumia 925. I hope its temporary, during yesterday evening the wallet was working correctly!

**Comment by matiu** [comment]
Could you please try again? BWS public server was rebooted yesterday. I should be OK now.

**Comment by mikexine** [comment]
Now it's working! Great! Thank you.

**Comment by cmgustavo** [comment]
@utc66 , regarding importing a wallet, I checked it on my Lumia 630 and it 's working. I think the message is wrong, but the error is related that BWS was down. Please try again and let me know.

**Comment by matiu** [comment]
OK, glad to hear that. thanks for the update.

JFYI, it is possible to run your own bitcore-wallet-service (BWS) in
minutes (https://github.com/bitpay/bitcore-wallet-service) and just by
pointing Copay to that new server, your wallet can be recreated and
restored. (ie you dont need the original BWS server to operate / recover
your wallet).

On Fri, May 15, 2015 at 9:51 AM, Gustavo Maximiliano Cortez <
notifications@github.com> wrote:

> @utc66 <https://github.com/utc66> , regarding importing a wallet, I
> checked it on my Lumia 630 and it 's working. I think the message is wrong,
> but the error is related that BWS was down. Please try again and let me
> know.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2729#issuecomment-102390362>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!
