### ISSUE TITLE
Chrome extension, wallet won't show current balance

### ISSUE THREAD

**Issue by rustyn** [bitpay/copay#2730]
2-of-3 wallet not showing current balance for any users. Permanently states `Could not update Wallet Tap to retry` but does not resolve.

Attempted to import to new wallet, it works but does not find any balances, just scans forever. `Scanning Wallet funds...` with no resolution.

**Comment by rustyn** [comment]
Additional: when we attempt to set up a spend proposal for a small amount that we know we have in the wallet it gives the following error: "The transaction proposal could not be created: [object Object]"

**Comment by utc66** [comment]
Me too. But now I checked manually and it seems like they're currently experiencing seriously server problems (DDOS?)

http://bws.bitpay.com

-> Returns a Cloudflare error

**Comment by rustyn** [comment]
Good spot, I assumed it was just server issues. Let's keep this post updated to any changes with server accessibility.

**Comment by utc66** [comment]
Just received a response from Bitpay's support department:

Hello,

Thank you very much for reporting this issue. I appears there is currently an issue with the wallet server of Copay.

We are currently investigating and I will come back to you as soon as I have more information

Thank you for your patience

Best regards,

Charles Roland
BitPay, Inc.

**Comment by utc66** [comment]
Will update if anything new is happening

**Comment by matiu** [comment]
Could you please try again? BWS public server was rebooted yesterday. I should be OK now.

**Comment by rustyn** [comment]
http://bws.bitpay.com/ is still inaccessible

**Comment by rustyn** [comment]
Looks like it has just gone back up now, many thanks

**Comment by matiu** [comment]
OK, glad to hear that. thanks for the update.

JFYI, it is possible to run your own bitcore-wallet-service (BWS) in
minutes (https://github.com/bitpay/bitcore-wallet-service) and just by
pointing Copay to that new server, your wallet can be recreated and
restored. (ie you dont need the original BWS server to operate / recover
your wallet).

On Fri, May 15, 2015 at 9:43 AM, rustyn <notifications@github.com> wrote:

> Looks like it has just gone back up now, many thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2730#issuecomment-102388934>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!
