### ISSUE TITLE
Pending multi-sig wallet won't delete

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#2735]
I have a pending multi-sig wallet (2/3) that shows "waiting..." for the other two copayers.  If I cancel (request to delete the wallet) the operation it disappears from from copay and the left navigation list.  When I close the copay app and re-open the copay app the wallet I canceled shows up again (as though I never canceled).  I've tried multiple times to cancel the wallet but it keeps coming back.  Once item to note is that I created the pending wallet with v0.10.6 and since then I have upgraded to v0.10.7 (the pending wallet went through the upgrade).

**Comment by matiu** [comment]
Could not reproduce this one on Chrome App (current master). Need to try on iOS yet.

**Comment by ajp8164** [comment]
It's very reproducible in my iOS wallet.  I can't delete the pending wallet at all..

**Comment by matiu** [comment]
Thanks it was related to fileStorage (iOS / Android). Fixed byhttps://github.com/bitpay/copay/pull/2739
