### ISSUE TITLE
Wallet Blocks the ammount of 3 days old transaction?

### ISSUE THREAD

**Issue by gerardo15** [bitpay/copay#2737]
I just sent 1 dollar on my 4-4 copay wallet and still waiting for one of the copayers to aprove, but the wallet says that is blocking 27 dollars from a transaction recieved 3 days ago.

Is this normal?

**Comment by matiu** [comment]
Yes. Thats is normal. The amount blocked depends on the unspent outputs you own at the
Moment the tx is created.
