### ISSUE TITLE
Screen overflow

### ISSUE THREAD

**Issue by cmgustavo** [bitpay/copay#2742]
Steps:

1. Go to "Receive"
2. Tap on menu and select "Add wallet"
3. Close
4. Change to "Send" section

![copay_-_multisignature_wallet](https://cloud.githubusercontent.com/assets/237435/7683715/432f8234-fd57-11e4-970b-c4f37bb40a07.png)

**Comment by gerardo15** [comment]
I can confirm this too on Android App.
