### ISSUE TITLE
Web Page Not Available

### ISSUE THREAD

**Issue by jamiebtc** [bitpay/copay#2745]
I am no longer able to view transactions through Insight on my android phone (4.4os). Has this happened to other people or just me? 

Thanks

![copay](https://cloud.githubusercontent.com/assets/12503496/7691664/3007c9d4-fdb4-11e4-8d22-1f2491dce85c.jpg)

**Comment by matiu** [comment]
The domain of the public insight instance have change from live.insight.is to insight.bitpay.com ( a long time ago) and the URL redir is not working. We have update the link the current Copay master. Thanks for the report.
