### ISSUE TITLE
swipeWallet.js Requires config and version info not present

### ISSUE THREAD

**Issue by kenEldridge** [bitpay/copay#2746]
Problem: swipeWallet.js will fail with errors because I do not have config and version properties set.  Also, I have to change the path to copay itself.  

To reproduce:
1. Build copay per instructions in README.md
2. Run swipeWallet.js
3. The app stops working and throws an "Error: Cannot find module '../copay'" error.
4. After correcting the copay path the app stops working and throws an "Error: Cannot find module 
'../config'" error.
5. After correcting the copay path the app stops working and throws an "Error: Cannot find module '../config'" error.
> node util/swipeWallet.js -d &lt;destination&gt; -n 2 -k &lt;privateKey1&gt;,&lt;privateKey2&gt;
module.js:340
    throw err;
          ^
Error: Cannot find module '../copay'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/keneldridge/Documents/copay/util/swipeWallet.js:6:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

> node util/swipeWallet.js -d &lt;destination&gt; -n 2 -k &lt;privateKey1&gt;,&lt;privateKey2&gt;
App listening on port 3000
module.js:340
    throw err;
          ^
Error: Cannot find module '../config'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/keneldridge/Documents/copay/swipeWallet.js:8:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

Expected: Should sweep wallet without errors.  Obviously I'm just missing the config and version information.  However, I don't know what it should be or how to create the properties.  I do not see instruction on how to create them or what they should contain.  Any help will be appreciated, thank you.

Platform: OS X 10.10.2, Node.js v0.10.36

**Comment by matiu** [comment]
Sorry, swipeWallet is outdated, and it is not longer working. it should've
been removed when Copay 0.10.0 was released.

If you have the extended private keys, you can create a new wallet with the
same configuration (m-n) and using 'advanced' options at the wallet
creation and joining time enter your private keys. Then go to 'preferences
-> advanced -> scan for funds' and you should have access to the funds.
Alternatively you could use `bitcore-wallet`, the CLI wallet, compatible
with Copay.



On Tue, May 19, 2015 at 12:31 AM, kenEldridge <notifications@github.com>
wrote:

> Problem: swipeWallet.js will fail with errors because I do not have config
> and version properties set. Also, I have to change the path to copay
> itself.
>
> To reproduce:
> 1. Build copay per instructions in README.md
> 2. Run swipeWallet.js
> 3. The app stops working and throws an "Error: Cannot find module
> '../copay'" error.
> 4. After correcting the copay path the app stops working and throws an
> "Error: Cannot find module
> '../config'" error.
> 5. After correcting the copay path the app stops working and throws an
> "Error: Cannot find module '../config'" error.
>
> node util/swipeWallet.js -d <destination> -n 2 -k
> <privateKey1>,<privateKey2>
> module.js:340
> throw err;
> ^
> Error: Cannot find module '../copay'
> at Function.Module._resolveFilename (module.js:338:15)
> at Function.Module._load (module.js:280:25)
> at Module.require (module.js:364:17)
> at require (module.js:380:17)
> at Object. (/Users/keneldridge/Documents/copay/util/swipeWallet.js:6:13)
> at Module._compile (module.js:456:26)
> at Object.Module._extensions..js (module.js:474:10)
> at Module.load (module.js:356:32)
> at Function.Module._load (module.js:312:12)
>
> node util/swipeWallet.js -d <destination> -n 2 -k
> <privateKey1>,<privateKey2>
> App listening on port 3000
> module.js:340
> throw err;
> ^
> Error: Cannot find module '../config'
> at Function.Module._resolveFilename (module.js:338:15)
> at Function.Module._load (module.js:280:25)
> at Module.require (module.js:364:17)
> at require (module.js:380:17)
> at Object. (/Users/keneldridge/Documents/copay/swipeWallet.js:8:14)
> at Module._compile (module.js:456:26)
> at Object.Module._extensions..js (module.js:474:10)
> at Module.load (module.js:356:32)
> at Function.Module._load (module.js:312:12)
> at Function.Module.runMain (module.js:497:10)
>
> Expected: Should sweep wallet without errors. Obviously I'm just missing
> the config and version information. However, I don't know what it should be
> or how to create the properties. I do not see instruction on how to create
> them or what they should contain. Any help will be appreciated, thank you.
>
> Platform: OS X 10.10.2, Node.js v0.10.36
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2746>.
>



-- 
BitPay.com

**Comment by matiu** [comment]
Closed in favor of #2747 . Thanks for the report.

**Comment by kenEldridge** [comment]
Thanks for the quick response.  Can you answer a slightly unrelated question?  I just attempted to do as you said and create a v0.10 wallet using the extended keys.  Unfortunately, I didn't expect there to be any persistence.  I tested with two of the keys to see that it would work.  Then I closed copay without saving the wallets (very foolishly!).  Once we were ready to attempt with all three keys I found I could no longer use the two keys that were part of my earlier test.  

Is the persistence at the Bitcore-Wallet-Service level?  If I just run a local BWS instance will I be okay?  Or does the persistence extend beyond BWS to the Insight instance?  Thanks for your time!

**Comment by matiu** [comment]
yes, you can run your own BWS. Persistence is per server. (no
communications between BWSs).

On Tue, May 19, 2015 at 12:19 PM, kenEldridge <notifications@github.com>
wrote:

> Thanks for the quick response. Can you answer a slightly unrelated
> question? I just attempted to do as you said and create a v0.10 wallet
> using the extended keys. Unfortunately, I didn't expect there to be any
> persistence. I tested with two of the keys to see that it would work. Then
> I closed copay without saving the wallets (very foolishly!). Once we were
> ready to attempt with all three keys I found I could no longer use the two
> keys that were part of my earlier test.
>
> Is the persistence at the Bitcore-Wallet-Service level? If I just run a
> local BWS instance will I be okay? Or does the persistence extend beyond
> BWS to the Insight instance? Thanks for your time!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2746#issuecomment-103546652>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!
