### ISSUE TITLE
Certificate is empty on some payment requests

### ISSUE THREAD

**Issue by cmgustavo** [bitpay/copay#2748]
![img_0275](https://cloud.githubusercontent.com/assets/237435/7695611/59e9ec78-fdc8-11e4-9d6a-db8dc27159ba.jpg)

**Comment by matiu** [comment]
In testnet I get: (matiu.com.ar)
![copay_-_multisignature_wallet](https://cloud.githubusercontent.com/assets/98844/7703002/ad3ea552-fe0a-11e4-9c6a-70559d0e277e.png)

**Comment by cmgustavo** [comment]
I know (testnet is ok). I got it on 'livenet' with a real merchant
