### ISSUE TITLE
Copay logo out of alignment in side bar

### ISSUE THREAD

**Issue by isocolsky** [bitpay/copay#2763]
I'm testing on Moto G Android 5.0.2. Copay 0.10.7

![image](https://cloud.githubusercontent.com/assets/2073468/7749735/09b0c71a-ffa6-11e4-8403-ba32bfc5d54b.png)

**Comment by cmgustavo** [comment]
Could you try it again with the latest version of master?

**Comment by matiu** [comment]
fixed
