### ISSUE TITLE
Enable Firefox Addon / Chrome Extension

### ISSUE THREAD

**Issue by FoundationAwesome** [bitpay/copay#2768]
Hey team,

awesome product!

But why did you remove the FF addon? Was there also a Chrome extension? (How) is it possible to enable it again? What would be needed for? Would be willing to invest time into this... just lead me the way to go.

**Comment by FoundationAwesome** [comment]
Cool, I made the app work again as a Chrome extension! Was not too difficult. How about the FF addon?

**Comment by matiu** [comment]
Hi,

with 'make chrome' at the root dir, you get the chrome extension bundle.

FF add-on was removed since add-ons do not run in sandboxes, so private app
data is accesible by other addons, so I was insecure to run a bitcoin
wallet.



On Fri, May 22, 2015 at 9:52 PM, FoundationAwesome <notifications@github.com
> wrote:

> Cool, I made the app work again as a Chrome extension! Was not too
> difficult. How about the FF addon?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2768#issuecomment-104808525>.
>



-- 
BitPay.com

**Comment by FoundationAwesome** [comment]
Interesting. I thought I got the Chrome App and not the Chrome Extension after running the build script. I am pretty sure that Chrome extensions are safe (same like Chrome apps). Don't know about FF addons. Do you mean that other addons could read the localStorage of the Copay Addon and steal the privkey? I was not able to find a single FF wallet addon in the addon store of Mozilla. Maybe there is really a reason for this.

**Comment by FoundationAwesome** [comment]
Is there some background information about the security hole in FF? What exactly does make FF not secure? How is private data accessible? Any FF devs here who could confirm this? Could and should Mozilla 'bugfix' this?

**Comment by matiu** [comment]
please see hear. https://github.com/bitpay/copay/pull/2111

I dont think is a 'security hole'. Extensions are meant to cooperate with the browser, not to run isolated, as Chrome apps do.

**Comment by FoundationAwesome** [comment]
AFAIK Extensions in Chrome run isolated! Would be cool to see extension support again in Copay!

@matiu at #2111 there is no background information or anything what would explain the decision.
