### ISSUE TITLE
Correct time of transaction

### ISSUE THREAD

**Issue by FoundationAwesome** [bitpay/copay#2771]
As far as I understand it the Copay wallet shows (inside the history view) the time when a tx got mined and not when it appeared/got broadcasted. Additionally the wallet seems to break (white page, on testnet) when I open a not-mined tx inside the history view. Probably there should be a tx_appearance field inside Insight API, similar to blockchain.info API.

**Comment by isocolsky** [comment]
Some progress has been done on this, please see https://github.com/bitpay/insight-api/pull/339
