### ISSUE TITLE
"Could not update Wallet" error

### ISSUE THREAD

**Issue by eordano** [bitpay/copay#2775]
Using the Chrome App. It may be related to crafting transactions yesterday while Insight was down.

![screen shot 2015-05-28 at 12 25 21 pm](https://cloud.githubusercontent.com/assets/42750/7863792/b857df7c-0534-11e5-8d4e-ce971a79028a.png)

**Comment by matiu** [comment]
thanks, we are upgrading the (testnet) server. it will be up soon.

On Thu, May 28, 2015 at 12:26 PM, Esteban Ordano <notifications@github.com>
wrote:

> Using the Chrome App. It may be related to crafting transactions yesterday
> while Insight was down.
>
> [image: screen shot 2015-05-28 at 12 25 21 pm]
> <https://cloud.githubusercontent.com/assets/42750/7863792/b857df7c-0534-11e5-8d4e-ce971a79028a.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2775>.
>



-- 
BitPay.com

**Comment by matiu** [comment]
done! thanks for the report.
