### ISSUE TITLE
Wallet icon not updated when alias changed

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#2795]
When I change the wallet alias the icon on the wallet home screen doesn't get updated.  The side nav icon does get updated.  See example image.
![image](https://cloud.githubusercontent.com/assets/1063765/7894840/417a897e-0640-11e5-8561-3f92a1bc9104.jpg)

**Comment by ajp8164** [comment]
0.10.9 iOS.

**Comment by matiu** [comment]
Good catch! Thanks.
