### ISSUE TITLE
Little bug with alias (or not) + another on Chrome (but maybe only for me)

### ISSUE THREAD

**Issue by Kirvx** [bitpay/copay#2808]
- Create a wallet "Bob"
- Change the alias by "John"
- Go in Wallet Alias for changing the alias again and you will see "Alias for Bob" and not "for John".

And

![sans titre](https://cloud.githubusercontent.com/assets/6627786/7924323/85575b0a-08ba-11e5-90ad-d80a73141d20.png)

The logo doesn't appear, it is a problem I have already met in some other app, but I have not found the cause, if you have an idea 乁( ◔ ౪◔)ㄏ

**Comment by cmgustavo** [comment]
I see your point, but I think it 's not a bug. I mean, in your example "Bob" is the real name of your Wallet. So, if you create an *alias* for Bob (john, richard, or whatever), always you are going to change the alias for the real wallet called "Bob" (not for john, richard or whatever). 

Perhaps we could put both names like the previous screen: `Alias for John [Bob]`. What do you think?

Regarding the Copay logo, I think this is an issue on Windows systems.

**Comment by Kirvx** [comment]
> Perhaps we could put both names like the previous screen: Alias for John [Bob]. What do you think?

That's fine :)

**Comment by cmgustavo** [comment]
I have installed the chrome app in a Windows virtual machine from the store (v1.0.1) and it works (Copay logo on sidebar). It also happened in previous versions?

**Comment by Kirvx** [comment]
> It also happened in previous versions?

Yep

Well, if it's ok on a fresh install, it's me, don't know why but don't care 乁( ◔ ౪◔)ㄏ
Maybe a day with a Chrome update....
