### ISSUE TITLE
What is the English for this phrase?

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#2827]
I didn't find this on desktop... It looks like Google translate did it. It is very weird Japanese.

![screenshot_2015-06-04-02-55-54](https://cloud.githubusercontent.com/assets/6586275/7967524/86942c1c-0a65-11e5-9a0d-043a5205ced5.png)

**Comment by cmgustavo** [comment]
Which phrase?

**Comment by dabura667** [comment]
Bitpayから開いて...

**Comment by dabura667** [comment]
Open Bitpay, overlapping signatures are used by your terms a wallet with obtain bitcoins.

Is what it sounds like in Japanese as well :-P

**Comment by Kirvx** [comment]
"Secure bitcoin on your own terms with an open source, multisignature wallet from BitPay."
from https://github.com/bitpay/copay/blob/master/appstore_en
Google auto translate it for french too.

**Comment by dabura667** [comment]
Oh OK, then we can copy paste that line from the translation I already gave you

**Comment by cmgustavo** [comment]
In spanish, google translates that phrase to: "Asegure bitcoin en sus propios términos con una, carpeta multisignature abierto desde BitPay". Completely incoherent

**Comment by dabura667** [comment]
I guess it auto translates the first line if the store description is not in that stores language?

Is there any way to change that manually I wonder.
