### ISSUE TITLE
Bad pgp signature for linux64 binary

### ISSUE THREAD

**Issue by SmileyChris** [bitpay/copay#2833]
Was going to check out the latest release (1.0.1) and the signature is failing.
```
~> gpg --verify copay-linux64.zip.sig
gpg: assuming signed data in `copay-linux64.zip'
gpg: Signature made Thu 04 Jun 2015 05:25:15 NZST using DSA key ID 1112CFA1
gpg: BAD signature from "Copay (visit copay.io) <copay@bitpay.com>"
```

The 32 bit version verified correctly.

**Comment by matiu** [comment]
Thanks, will check asap.

**Comment by cmgustavo** [comment]
There was an error when uploading the zip file. It 's OK now. 
Thanks!

**Comment by SmileyChris** [comment]
Great, `Good signature from "Copay (visit copay.io) <copay@bitpay.com>"`

Thanks!
