### ISSUE TITLE
Add 'sweep paper wallet' feature

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#2834]
for wallets created, for example, in bitaddress.org

**Comment by isocolsky** [comment]
+1
Also support BIP38.
If the sweeping is done through a TX to send funds into a Copay address, the same strategy could be used to import 12 word phrases from BIP44 wallets.

**Comment by dabura667** [comment]
+1
BIP38 support +1

**Comment by zachdoty** [comment]
+1, and yes, BIP38 support please.

Option could be on receive page in small print at the bottom, or under settings menu.

**Comment by tab00** [comment]
I want to give away bitcoins via paper marketing material with QR code.

It has been possible with the core Bitcoin client, but I want it to be possible with the Copay app as it is more user-friendly for beginners.

Please make this feature available in the next release.
