### ISSUE TITLE
Is BWS down - can't fatch unspend outputs

### ISSUE THREAD

**Issue by offerm** [bitpay/copay#2837]
Please cehck. My wallet is not working and I urgently need it!

**Comment by AGConrad** [comment]
I'm running into this issue as well.

**Comment by matiu** [comment]
it should be OK now. thanks.

On Thu, Jun 4, 2015 at 2:10 AM, Andrew <notifications@github.com> wrote:

> I'm running into this issue as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2837#issuecomment-108726819>.
>



-- 
BitPay.com

**Comment by offerm** [comment]
Yes, OK now.
Should we expect this from time to time?
now that CoPay is out of beta, it would be best if you have high availability support for the backend components.If you must take them down, at least communicate and let us know when you expect them back.
Thanks
Offer

**Comment by matiu** [comment]
Agree. This should not happen.

we have setup a redundant cluster installation to handle BWS public install. We are working to stabilize to prevent this for happen.
