### ISSUE TITLE
Not able to type in a . under Amount due to phone number keyboard.

### ISSUE THREAD

**Issue by darkfur93** [bitpay/copay#2838]
The default number virtual keyboard for the LG Tribute does not include a ".".
Only the numbers 1,2,3,4,5,6,7,8,9,0,Back,Next as seen in this screenshot.
![screenshot_2015-06-03-22-29-46](https://cloud.githubusercontent.com/assets/1548625/7977479/47cf49f0-0a40-11e5-9b3b-21637c7e579e.png)

**Comment by dabura667** [comment]
Switch to bits for now. 1000000 bits is = 1 BTC

Hopefully they'll fix soon

**Comment by BitpopCoin** [comment]
Download Google keyboard

**Comment by matiu** [comment]
This is an issue with certain Android Devices in which numeric keyboard do not include '.' or ','. If it can be solved by downloading an additional software keyboard, as BitpopCoin suggested, I would be great. Could you confirm?

**Comment by darkfur93** [comment]
matiu, Switching keyboards like BitpopCoin suggested would solve the issue. But I see this temporary fix.
You might want to look into a virtual keyboard Integrated into the app itself.

**Comment by BitpopCoin** [comment]
I would consider this a bug with your phone as you can easily install Google keyboard which is standard and works, unless you can't, it wasn't always in the play store.

**Comment by tophensen** [comment]
I do experience the same bug on my Galaxy Tab3 (Android 4.4.2, Samsung Keyboard). Note that a decimal separator can be enabled also with this kind of input device, and indeed, copay should enable that key if I chose a unit other than bits.

**Comment by matiu** [comment]
>  Note that a decimal separator can be enabled also with this kind of input device,
> 
How?

**Comment by tophensen** [comment]
Problem is 'input type="number"' does not automatically
enable InputType.TYPE_NUMBER_FLAG_DECIMAL,
this site descibes a workaround:
http://www.codedisqus.com/0JygqqUqjP/input-typenumber-keyboard-has-dot-disabled-in-galaxy-tab.html

**Comment by matiu** [comment]
Thanks for sharing. That seems to be for Android native applications. Copay is Cordova/html5 based, no sure how could that be done. 

Html5 specs require float input for "number", so I guess that problem is an implementation problem on the device. can't you use an alternative keyboard as suggested?

**Comment by tophensen** [comment]
Sure, I can use a different keyboard or copy/paste or enter the amount in
bits. But considering the wide-spread use of Samsung phones, I guess a
workaround in copay (use input="text", and validate) or better in Cordova
would be much appreciated.
Here's an incomplete list of affected devices:
http://stackoverflow.com/questions/23205511/what-models-of-samsung-smartphones-have-missing-period-for-html5-input-type-num
Am 08.06.2015 01:01 schrieb "Matias Alejo Garcia" <notifications@github.com
>:

> Thanks for sharing. That seems to be for Android native applications.
> Copay is Cordova/html5 based, no sure how could that be done.
>
> Html5 specs require float input for "number", so I guess that problem is
> an implementation problem on the device. can't you use an alternative
> keyboard as suggested?
>

**Comment by BitpopCoin** [comment]
My note 4 has a button with multiple symbols including a period but i usually use swype. Using text is much slower for people who can use an alternate keyboard. It'll look pretty unprofessional.

**Comment by matiu** [comment]
dup: https://github.com/bitpay/copay/issues/2384
