### ISSUE TITLE
Import wallet from 0.9 fails

### ISSUE THREAD

**Issue by johannkaupen** [bitpay/copay#2839]
Hi guys,
I got a multi-sig-wallet with Copay end of 2014 and read that you guys are out of the beta.
This is a long-term thing (for my niece) so I thought I just download the app and log in again after long time.

Therefore I guess I've to "migrate"/import it to the new version from 0.9 and earlier.
Anyway, it says it can't find a profile for my email address (used the same email I got the account opening confirmation to back then).

In the iOS app it asks me for a username and password.
Isn't username also my email address?!

Any idea what I do wrong?
What other kind of information do you guys need?

**Comment by matiu** [comment]
Could you be sure that 'IMPORT FROM THE CLOUD" in  the 'Import legacy wallet' is on? When it is on, 'email' field will replace 'username'. In the screenshot you sent us it seems to be on the wrong position.

**Comment by johannkaupen** [comment]
Hi Matias,
I tried both. When import from the cloud is switched on, it starts to seem to work, indicated by a new screen and flashing Importing...But after a second or so it goes back to the screen before saying: PNOTFOUND: Profile not found.
Joachim



    _____________________________

**Comment by matiu** [comment]
Fixed thru email exchanges.

thanks
