### ISSUE TITLE
Someone sent to my regular address from the multisig address? 

### ISSUE THREAD

**Issue by BitpopCoin** [bitpay/copay#2842]
Are they related? Can I recover the underlying private key? 

Sent http://blockchain.info/tx/b1326bc92769b788da7314b115c08387187362da651a813f2831b879a5c9798e

Received https://blockchain.info/address/1B4qMi28z7m6uJ17owJzfGH2dBFSrPHTHF

Sent https://blockchain.info/tx/a19bd66690042a266ab177d5ebde3aa8f4a9cc7d9e6be582f8cdf26b8fb0a10e

Received https://blockchain.info/address/1D88Kc74c24GP9Xw78dG2TAV7rqtK3ToaW

Receives could be swapped.

**Comment by matiu** [comment]
Hey,

Could you explain this in more detail?

thanks

On Thu, Jun 4, 2015 at 11:54 AM, Bitpop <notifications@github.com> wrote:

> Are they related? Can I recover the underlying private key?
>
> Sent
> http://blockchain.info/tx/b1326bc92769b788da7314b115c08387187362da651a813f2831b879a5c9798e
>
> Received
>
> Sent
> https://blockchain.info/tx/a19bd66690042a266ab177d5ebde3aa8f4a9cc7d9e6be582f8cdf26b8fb0a10e
>
> Received
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2842>.
>



-- 
BitPay.com

**Comment by dabura667** [comment]
What?

**Comment by BitpopCoin** [comment]
They're supposed to send to my spending address (which is multisig) but they "replied" to a regular address. This isn't a copay bug, but I wanted help maybe recovering the underlying address of my multisig.

**Comment by dabura667** [comment]
"replied"?

Can you tell me what wallet they used?

So are you saying to me that they ignored the redeemscript and just regexed your pubkey and created a normal bitcoin address???

If there is a wallet software doing that, we MUST tell that developer...

if your friend did it on their own, you MUST tell your friend that they need to learn more about bitcoin before messing with the protocol directly like that.

**Comment by BitpopCoin** [comment]
Well they fixed the bug and will issue a refund. I don't know the wallet they used. I'm more curious if the address is random or they found the underlying public key which I should have the private key for.

**Comment by dabura667** [comment]
Tell them to stop "replying" to bitcoin addresses and ASK the customer for a "reply" address.

The idea that there is a "From:" address in bitcoin is False.

Would you mind telling me what company is doing this?

**Comment by BitpopCoin** [comment]
Look in the first link. Thanks.
