### ISSUE TITLE
Japanese font is slightly off-putting in desktop version

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#2852]
![fonts](https://cloud.githubusercontent.com/assets/6586275/7991073/7c46c12c-0b30-11e5-8b1b-aa442be0123c.png)

Left is Desktop client, Windows 64 bit.
Right is Chrome Extension

It's hard to tell when not native to Japanese... but the left font is kind of "cursive"-y.

You can tell by the first symbol on the Generate New Address Button.

Also the 2 symbols that make up Send on the bottom also are obviously different style.

Maybe it's because it is so small that the cursive-y style looks sloppy, pixelated, and hard to read.

Is there a file where I can specify a font, and what set of fonts would I be limited to?

**Comment by matiu** [comment]
Is this still valid?
