### ISSUE TITLE
Stop copying Bitcoin address prefixed with bitcoin:

### ISSUE THREAD

**Issue by BitpopCoin** [bitpay/copay#2854]
bitcoin:39id3SvmVQms5v1DpqnMuJ1j7UpB5us2Dy

**Comment by cmgustavo** [comment]
Why not? This is an standar: BIP-21 (https://en.bitcoin.it/wiki/BIP_0021)

**Comment by BitpopCoin** [comment]
That's a uri, no application accepts it via clipboard. Do you compose emails with email:bitpop@nsa.gov?

**Comment by dabura667** [comment]
> You don't compose emails with email:bitpop@nsa.gov

No you don't... but even if you did, it would be `mailto:` and not `email:`

jokes aside.

I +1 this. you should just copy the address only.

**Comment by matiu** [comment]
+1 for Copy

but I think it should stay on the QR, right?

On Fri, Jun 5, 2015 at 11:15 AM, dabura667 <notifications@github.com> wrote:

> You don't compose emails with email:bitpop@nsa.gov
>
> No you don't... but even if you did, it would be mailto: and not email:
>
> jokes aside.
>
> I +1 this. you should just copy the address only.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2854#issuecomment-109306266>.
>



-- 
BitPay.com

**Comment by BitpopCoin** [comment]
Yes qr should stay as uri

**Comment by tonygallippi** [comment]
copy should be only the address

a link (to launch a wallet) should have the bitcoin: prefix

QR code should have the bitcoin: prefix
