### ISSUE TITLE
Insert syntax to allow for translation of untranslated strings

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#2858]
1. "Personal Wallet" is the default name for the first wallet the app starts with. I want to translate it. (as well as the "me" which is the default name for yourself as a copayer, if possible.)
2. The words "Email" and "Username" in the import legacy wallet screen.

I think 1 is
https://github.com/bitpay/copay/blob/master/src/js/services/profileService.js#L168

And 2 is
https://github.com/bitpay/copay/blob/master/public/views/importLegacy.html#L33
(as well as Line 34 as the placeholder)

**Comment by Kirvx** [comment]
@cmgustavo  @matiu 

I want to translate it too :smile:

**Comment by matiu** [comment]
yes, this seems a good idea, any change to make that string available for
v0.1.2 @cmgustavo?

On Mon, Sep 14, 2015 at 4:11 PM, Kirvx <notifications@github.com> wrote:

> @cmgustavo <https://github.com/cmgustavo> @matiu
> <https://github.com/matiu>
>
> I want to translate it too [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2858#issuecomment-140179836>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by cmgustavo** [comment]
Will check
