### ISSUE TITLE
Error loading 'history' and only one 'receive' address shown

### ISSUE THREAD

**Issue by Darkster1** [bitpay/copay#2859]
After some upgrade I had to import from a legacy wallet (don't remember the version number 0.9.?) so I did import the local wallet and the balance shows correctly. In that wallet I had added a few addresses but after the upgrade none of the addresses is shown on the 'receive' tab.
The history tab shows "can't fetch transaction history, tap to retry" but I can tap endlessly but nothing.

The above happened on Windows Phone so I signed up for the iOS beta program, imported the backup there, on the receive tab on iOS I see a different wallet address then on Windows Phone but still not the addresses I had created.
The balance shows OK on iOS too.

Sending coins works fine aswell.

Any ideas on fixing this?

**Comment by matiu** [comment]
New Copay only show the latest address (while the other address are still monitored). New address are generated after they are used and in new devices. 

Regarding the history, could you check

 > advanced > about copay > session logs

After you have clicked refresh tx history, and see if there is something wrong?

**Comment by dabura667** [comment]
I thought the exact same thing re: different addresses on each device was not explained so was confused

dunno why there's no unique wallet ID number, or gravitar or something.

**Comment by Darkster1** [comment]
So it's not possible to see the addresses in use? So I can view the transactions in blockchain.info for example.

The log says:

Updating Status: {"verbose":false,"baseUrl":"https://bws.bitpay.com/bws/api","basePath":"/bws/api","baseHost":"https://bws.bitpay.com","payProHttp":null,"doNotVerifyPayPro":true,"transports":["polling"],"credential... null
TxHistory ERROR: {"code":"CONNERROR"}

the code CONNERROR comes back when tapping retry.

Creating a new wallet simply shows there are no transactions yet.

Now tried: iOS, Windows Phone and Windows 8 (desktop) all the same.
Tried the mobile versions on different networks including WiFi and 3G,4G cellular networks.

**Comment by matiu** [comment]
Given that you see your balance and you can send funds, I would suggest you
create a new wallet in Copay an move the funds there. This could be related
to the migration and it will be difficult to debug it without having access
to your device.

On Fri, Jun 5, 2015 at 4:15 PM, Darkster1 <notifications@github.com> wrote:

> So it's not possible to see the addresses in use? So I can view the
> transactions in blockchain.info for example.
>
> The log says:
>
> Updating Status: {"verbose":false,"baseUrl":"
> https://bws.bitpay.com/bws/api","basePath":"/bws/api","baseHost":"https://bws.bitpay.com","payProHttp":null,"doNotVerifyPayPro":true,"transports":["polling"],"credential...
> null
> TxHistory ERROR: {"code":"CONNERROR"}
>
> the code CONNERROR comes back when tapping retry.
>
> Creating a new wallet simply shows there are no transactions yet.
>
> Now tried: iOS, Windows Phone and Windows 8 (desktop) all the same.
> Tried the mobile versions on different networks including WiFi and 3G,4G
> cellular networks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2859#issuecomment-109408068>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by Darkster1** [comment]
Thought of that too, but I have small mining to one address (of course I can change that too) so it would be nice if it works again.

Could it have something to do with a timeout connecting to the wallet service that drops the connection when multiple address history is requested?
Would it somehow be possible to export the wallet so it can be imported in another wallet software like bitcoin-qt?

**Comment by Darkster1** [comment]
I just ran Fiddler to see what's going on.

The first request to 
https://bws.bitpay.com/bws/api/v1/txhistory/?limit=6&r=41194

Takes too long for Copay (probably), here are the statistics from Fiddler2:

ACTUAL PERFORMANCE
--------------
ClientConnected:	21:28:53.120
ClientBeginRequest:	21:36:37.860
GotRequestHeaders:	21:36:37.860
ClientDoneRequest:	21:36:37.861
Determine Gateway:	0ms
DNS Lookup: 		0ms
TCP/IP Connect:	27ms
HTTPS Handshake:	81ms
ServerConnected:	21:36:37.888
FiddlerBeginRequest:	21:36:37.969
ServerGotRequest:	21:36:37.969
ServerBeginResponse:	21:36:53.424
GotResponseHeaders:	21:36:53.424
ServerDoneResponse:	21:36:53.424
ClientBeginResponse:	21:36:53.424
ClientDoneResponse:	21:36:53.424

When the request is complete, Fiddler2 shows the transaction history in JSON format.

**Comment by matiu** [comment]
Oh, ic. Good catch. Insight  takes time for address with many transactions.

Probably we could mitigate this with a cache.

On Fri, Jun 5, 2015 at 4:40 PM, Darkster1 <notifications@github.com> wrote:

> I just ran Fiddler to see what's going on.
>
> The first request to
> https://bws.bitpay.com/bws/api/v1/txhistory/?limit=6&r=41194
>
> Takes too long for Copay (probably), here are the statistics from Fiddler2:
> ACTUAL PERFORMANCE
>
> ClientConnected: 21:28:53.120
> ClientBeginRequest: 21:36:37.860
> GotRequestHeaders: 21:36:37.860
> ClientDoneRequest: 21:36:37.861
> Determine Gateway: 0ms
> DNS Lookup: 0ms
> TCP/IP Connect: 27ms
> HTTPS Handshake: 81ms
> ServerConnected: 21:36:37.888
> FiddlerBeginRequest: 21:36:37.969
> ServerGotRequest: 21:36:37.969
> ServerBeginResponse: 21:36:53.424
> GotResponseHeaders: 21:36:53.424
> ServerDoneResponse: 21:36:53.424
> ClientBeginResponse: 21:36:53.424
> ClientDoneResponse: 21:36:53.424
>
> When the request is complete, Fiddler2 shows the transaction history in
> JSON format.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2859#issuecomment-109416589>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by Darkster1** [comment]
You're welcome. Just let me know if I can do some testing.

**Comment by matiu** [comment]
This should be resolved on current versions.
