### ISSUE TITLE
Watch Only Addresses

### ISSUE THREAD

**Issue by starvin** [bitpay/copay#2860]
Any plans to implement watch only addresses? I'd like to have offline wallets that I can monitor with copay.

**Comment by dabura667** [comment]
What do you mean watch-only addresses?

What do you plan on using them for (that must be done in Copay and nowhere else)?

What other apps support the features you are asking for, and why do you need the feature in Copay as well?

**Comment by starvin** [comment]
Importing a public key without a private key so that I can monitor the balance.

I plan on using them to monitor my cold storage wallets. This can be done in other places, but would be convenient to have in copay, so that I can view all my balances in one place.

I know blockchain.info and electrum have watch-only features.

**Comment by dabura667** [comment]
With Multi-sig?

I don't get where the "Copay" aspect comes into play.

Are you talking about making cold storage multi-sig or something?

**Comment by davidlatapie** [comment]
This is unrelated to multisig.
Multisig means that several persons (or devices) must agree for some bitcoins to be received.
Watch-only means that you just can't send bitcoins. It is used, for instance, to monitor your main wallet from a mobile phone, without fear of the phone being compromised. Sure a multisig could achieve a similar thing but in circumvoluted ways and with more human risks (like you leave one part at home and you lose it).

Mycelium does it. So far, Copay is my second favourite. Supporting watch-only wallet would help in making it closer to favourite.

**Comment by matiu** [comment]
it is possible to have 'export with out private keys' now. in 

`settings > advanced > export -> do not include private key`

importing that information into copay will create a wallet that cannot sign transactions and spend funds. It can see balance, create transaction proposals, create address, but not sign transactions.

Read-only addresses does not seem to be on out development path, 'no private key exports' and the upcoming more granular 'restrict access' (https://github.com/bitpay/copay/issues/3224) are the solutions we are planning to the use cases you mention.

**Comment by davidlatapie** [comment]
Indeed, I discovered this yesterday and I love it. I will publish an article about this later on. Plus, "no priv key" account can still initiate request for spending, which are then validated on a full account. I find it better than pure read only, especially with the comment entry, to remember why you wanted to spend money when you are back home.

I can't wait to see restricted access.

**Comment by matiu** [comment]
Thanks a lot for the response! Please let use know know the article when
you publish it!

Just for completion, there is a caveat with the upcoming `restricted
access`. While the 'no priv key' feature is warrant by the power of bitcoin
itself (ie: if Copay does not have the private key, there is simple no way
to sign), `restricted access` will be a server enforced limitation, pretty
much like an Access Control List on the Bitcore-Wallet-Service, so `no priv
key` will keep existing.





On Mon, Oct 5, 2015 at 3:24 AM, David <notifications@github.com> wrote:

> Indeed, I discovered this yesterday and I love it. I will publish an
> article about this later on. Plus, "no priv key" account can still initiate
> request for spending, which are then validated on a full account. I find it
> better than pure read only, especially with the comment entry, to remember
> why you wanted to spend money when you are back home.
>
> I can't wait to see restricted access.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2860#issuecomment-145441724>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by dan-da** [comment]
The no privkey feature is great and very useful.   It would be even better if the system facilitated the transfer of public key so that one can add readonly users to a wallet in similar fashion to adding signing copayers.  Is this functionality on the roadmap?

Access control and revokability via BWS sounds nice, but it is worrisome that it is server managed and disappears when switching servers, so I will probably stay away from that for now.
