### ISSUE TITLE
Suggestion: Add manual transaction proposal export/import feature.

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#2863]
1. If the number of signatures is insufficient, export in a json format with necessary info for the other members to sign.
2. If the number of signatures is sufficient, export in raw hex transaction for pushing to any pushtx website.
3. Allow for "import transaction proposal manually" feature in wallet menu "Advanced Features" section.

This feature is crucial for the Enhanced backups.

If we define "backup" as "restoring the ability you have to recover funds" then we must allow a way to use without relying on BWS, otherwise having a backup will do no good for any non-technical people.

Maybe when the signatures are done, you could have the app attempt to push to well known pushtx APIs and if fails move on to the next.

Related: #2722 #2866

**Comment by matiu** [comment]
Closed in favor of #3217
