### ISSUE TITLE
Request: Expose xPub

### ISSUE THREAD

**Issue by pooleja** [bitpay/copay#2865]
We are working on an application that allows users to upload videos/content and get paid in bitcoins.  To achieve this, we ask for the xPub of the user's wallet and then we generate "receive" addresses for the user, verify payments, etc.  Then payments go directly into the user's wallet without us ever needing to hold their coins.

We really like Copay and would like to promote it as the recommended wallet, but can't really do so until it is easy for the customer to export the xPub from one of their wallets and enter it into our system.  If this was available under the wallet preferences/info then it would close the gap.

**Comment by matiu** [comment]
Sure! Sounds like a good idea.

settings -> about this wallet

 -> my xpub
 -> copayeys xpub
 -> etc.

will do.


On Sat, Jun 6, 2015 at 9:28 AM, James <notifications@github.com> wrote:

> We are working on an application that allows users to upload
> videos/content and get paid in bitcoins. To achieve this, we ask for the
> xPub of the user's wallet and then we generate "receive" addresses for the
> user, verify payments, etc. Then payments go directly into the user's
> wallet without us ever needing to hold their coins.
>
> We really like Copay and would like to promote it as the recommended
> wallet, but can't really do so until it is easy for the customer to export
> the xPub from one of their wallets and enter it into our system. If this
> was available under the wallet preferences/info then it would close the
> gap.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2865>.
>



-- 
BitPay.com

**Comment by dabura667** [comment]
Re: @pooleja's idea... This seems dangerous:

What if the user doesn't understand what it is and they do this:

1. Your site asks them for an xpub.
2. They give you only their xpub and not ALL the xpubs.
3. You generate normal addresses (start with 1) for their xpub.
4. They complain "none of the bitcoins are in my copay wallet!!!" because they actually had a 2-of-3 so you needed 3 xpubs to generate their multi-sigs for them.

There is no way for your website to notice that, as the user is only telling you 1 xpub when they should tell you 3.

**Comment by dabura667** [comment]
As for the ability to export xpubs, I agree it should be possible... but there should be a warning to discourage people from doing it unless they know what they are doing.

**Comment by pooleja** [comment]
Yeah, I see that could definitely be a problem.  We would have to mitigate it with documentation or possibly even a verification step (like services do with ACH accounts by verifying they can receive a few cents and report how much was sent).

**Comment by matiu** [comment]
Good point dabura667.

Also the derivation path could be not detected by copay.

The 'normal' information exchange should be a wallet address, generated by
copay in 'receive'. Why you can put an address in your application, James?

On Sat, Jun 6, 2015 at 10:02 AM, James <notifications@github.com> wrote:

> Yeah, I see that could definitely be a problem. We would have to mitigate
> it with documentation or possibly even a verification step (like services
> do with ACH accounts by verifying they can receive a few cents and report
> how much was sent).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2865#issuecomment-109574319>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by matiu** [comment]
Maybe you want this:
https://medium.com/@ematiu/bitcoin-extended-addresses-5ac1b5e01b6c? We are
evaluating it.

On Sat, Jun 6, 2015 at 10:12 AM, Matias Alejo Garcia <ematiu@gmail.com>
wrote:

> Good point dabura667.
>
> Also the derivation path could be not detected by copay.
>
> The 'normal' information exchange should be a wallet address, generated by
> copay in 'receive'. Why you can put an address in your application, James?
>
> On Sat, Jun 6, 2015 at 10:02 AM, James <notifications@github.com> wrote:
>
>> Yeah, I see that could definitely be a problem. We would have to mitigate
>> it with documentation or possibly even a verification step (like services
>> do with ACH accounts by verifying they can receive a few cents and report
>> how much was sent).
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/bitpay/copay/issues/2865#issuecomment-109574319>.
>>
>
>
>
> --
> Matías Alejo Garcia
> @ematiu
> Roads? Where we're going, we don't need roads!
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by pooleja** [comment]
Yeah, maybe I do not understand how the multisig addresses are being generated.  Since the wallet supported importing a BIP32 key to create a wallet, I figured it would generate addresses similar to non-multisig wallets and use the scan/lookahead method for detecting payments.  If this is not the case, then it would probably require waiting until a feature that @matiu mentioned is supported.

**Comment by dabura667** [comment]
@pooleja https://github.com/bitcoin/bips/blob/master/bip-0045.mediawiki

This is how Copay works.

So if you got 3 xpubs from a user saying "I am using an x-of-3 wallet" then you would do the following:

Considering the xpub as N, we would derive `N/0/0/0` for all 3 xpubs, take the pubkey for those three.keys and sort them lexographically to create a redeemscript. RIPEMD160(SHA256(redeemscript)) gives you an address. Check the balance, if it has history, move on to N/0/0/1... etc.

Now, for a x-of-3 wallet, you could actually derive these addresses with N/1/0/0 and N/2/0/0 as well, and all of them would be valid addresses.

The only problem is that currently I don't think the wallet does any look ahead, and it only watches an address as soon as it is displayed on someone's Copay screen.

@matiu can answer any more specific questions about how gap limit works for BIP45 etc.


Your idea is not impossible, but it is very dangerous for the user... because if you tell them to put in all xpubs and they only put in 2 instead of 3 or 1 instead of 3, then you will generate a multisig address they can't get funds from possibly. (Not to mention my current wallets copayer "lost my data and didn't make a backup, oops" rate so far is depressing...)

Most of the hurdles with this wallet is about usability and user education.

**Comment by matiu** [comment]
Still, I dont completely understand why you need to generate addresses in
your application. Is it for privacy reasons?

On Sat, Jun 6, 2015 at 10:36 AM, dabura667 <notifications@github.com> wrote:

> @pooleja <https://github.com/pooleja>
> https://github.com/bitcoin/bips/blob/master/bip-0045.mediawiki
>
> This is how Copay works.
>
> So if you got 3 xpubs from a user saying "I am using an x-of-3 wallet"
> then you would do the following:
>
> Considering the xpub as N, we would derive N/0/0/0 for all 3 xpubs, take
> the pubkey for those three.keys and sort them lexographically to create a
> redeemscript. RIPEMD160(SHA256(redeemscript)) gives you an address. Check
> the balance, if it has history, move on to N/0/0/1... etc.
>
> Now, for a x-of-3 wallet, you could actually derive these addresses with
> N/1/0/0 and N/2/0/0 as well, and all of them would be valid addresses.
>
> The only problem is that currently I don't think the wallet does any look
> ahead, and it only watches an address as soon as it is displayed on
> someone's Copay screen.
>
> @matiu <https://github.com/matiu> can answer any more specific questions
> about how gap limit works for BIP45 etc.
>
> Your idea is not impossible, but it is very dangerous for the user...
> because if you tell them to put in all xpubs and they only put in 2 instead
> of 3 or 1 instead of 3, then you will generate a multisig address they
> can't get funds from possibly. (Not to mention my current wallets copayer
> "lost my data and didn't make a backup, oops" rate so far is depressing...)
>
> Most of the hurdles with this wallet is about usability and user education.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2865#issuecomment-109580338>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by pooleja** [comment]
@matiu See here: https://www.theprotocol.tv/bobby-lee-btc-china/  We are powering the paywall over the video.  When a user visits the page, we generate a payment address based on TheProtocol.tv's xPub on our servers that will send the payments directly to TheProtocol.tv's bitcoin wallet.  PopChest.com is powering it, but never actually is in control of the money.  Our problem is that we can't find a wallet that we can recommend to use that is A) Cross platform and B) Exposes an xPub the user can input into our site.

Yeah, I understand the problem with missing/combinations of multisig xPubs.  

If Copay doesn't support the lookahead feature to scan for incoming transactions for addresses itself has not generated, then this use case can't really be supported.  I see my incorrect assumptions about how the wallet works caused some confusion.  You can close this request from me, unless you think exposing the xPub for other use cases makes sense.

**Comment by matiu** [comment]
got it, thanks for the explanation.

Stay tuned for 'extended address support'. I think that would be a good solution for you use case.

**Comment by dan-da** [comment]
where can I learn more about the "extended address support" in copay?

**Comment by dabura667** [comment]
You can do it now by exporting your wallet, decrypting it, then copy pasting the xpubs.
