### ISSUE TITLE
Allow proposal creator to purge txp even after a reply

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#2867]
https://www.reddit.com/r/Bitcoin/comments/38sucy/funds_stuck_in_copay_2of3_wallet_need_help/

1. Created 2-of-3
2. deleted one of the wallets without backup on purpose (he said it was for "cold storage")
3. Created send proposal with one
4. Rejected send proposal with the other
5. The txp can no longer be purged by the creator, but it is waiting on a reply from a client that doesn't exist anymore.
6. No way to re-pair the wallet with the xprv (he has only the xprv in cold storage)

I understand that the user made tons of assumptions that don't make any sense, but the assumption that "the creator of the txp can rescind the txp whenever he wants" is an assumption I would make about any normal transaction in day-to-day life.

Why was it made this way? Obviously the person who made it will want to send it, so I don't see any way that giving the proposer the ability to take it back would make a bad situation.

We need to allow txp to be deleted by creator at any point in time.

**Comment by matiu** [comment]
Thanks for reporting.

Closing this one, in favor of:https://github.com/bitpay/copay/issues/2868
