### ISSUE TITLE
Implement BitID

### ISSUE THREAD

**Issue by Anders-Linden** [bitpay/copay#2874]
BitID is at the moment just a draft and experimental but an easy protocol for authentication with the behaviour of Bitcoin cryptography signing capability. This is a perfect way to securely validate an user for a service, instead of username and password or together with username and password (2FA).
Draft specification: https://github.com/bitid/bitid
For testing: http://bitid.bitcoin.blue/

Objectives: Implement an intuitive and user friendly support for BitID in copay.

**Comment by ianpurton** [comment]
+1 For this.

CarbonWallet supports the BitId protocol and it would be great to see some alternative implementations.

**Comment by zachdoty** [comment]
Multisig authentication is an interesting concept. 

This would enable new security best practices. 

Authentication requests could appear like payment proposals and require m/n approval. 

Just thinking out loud. But yeah, +1 for bitID

**Comment by matiu** [comment]
Is BitID still active / maintained?
