### ISSUE TITLE
Google Play / App Store (iOS) still are in English for Japanese region.

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#2888]
Whoever has write access to description for both stores, if you could please paste over the contents of [appstore_ja](https://raw.githubusercontent.com/bitpay/copay/master/appstore_ja) I would appreciate it.

**Comment by dabura667** [comment]
afaik you can change the description without releasing a new ipa / apk. Please correct me if I am wrong.

**Comment by matiu** [comment]
for iOS, a new CFBundle localization array need to be declared
(
http://apple.stackexchange.com/questions/166419/appstore-problem-with-language-of-ios-cordova-apps-always-english-and-german),
so it is not possible to update the current app listing until the new
version with the proper language list on the .plist file is upload.

On Fri, Jun 12, 2015 at 2:23 PM, dabura667 <notifications@github.com> wrote:

> afaik you can change the description without releasing a new ipa / apk.
> Please correct me if I am wrong.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2888#issuecomment-111565178>.
>



-- 
BitPay.com

**Comment by dabura667** [comment]
That is only for the "Languages: xxx" metadata on the appstore.

Adding a new language to display the appstore description is detailed here:

https://developer.apple.com/library/ios/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Chapters/DisplayInMoreLanguages.html

It even makes the distinction in the article:

> Important:  The language information you provide here **isn’t the same as the language information built into the app itself. The list of languages displayed in the store under Languages is set in the app build**.
> To have localized information describe your app in the store, you need to **provide it through iTunes Connect.**

**Comment by dabura667** [comment]
So your steps would be:
1. Log into iTunes Connect.
2. Click Description >> Version >> English
3. Choose new language from list: Japanese
4. Copy paste my translation
5. Save.
6. Within a few minutes Japanese appstore goers will see the Japanese description in the appstore. but the languages will still say "Supported languages: English" (This is the problem you are describing)

**Comment by dabura667** [comment]
https://developer.apple.com/library/ios/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Appendices/Properties.html#//apple_ref/doc/uid/TP40011225-CH26-SW3

Here under "Version Information" and "Description" it says "Unlocked" meaning it does not require approval from Apple to make changes to.

**Comment by matiu** [comment]
I am afraid no. There are no options to localized unless Your bundle declare other languages in the manifiest.

**Comment by dabura667** [comment]
I'm guessing preparations are moving forward for an update to Android and iPhone?

I am hoping localized appstore descriptions can be added. Thanks.

**Comment by matiu** [comment]
yes!

we already added them, thanks! They will be published with 1.1 is approved
on all app store markets.

On Sat, Jul 4, 2015 at 5:25 PM, dabura667 <notifications@github.com> wrote:

> I'm guessing preparations are moving forward for an update to Android and
> iPhone?
>
> I am hoping localized appstore descriptions can be added. Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2888#issuecomment-118550508>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!
