### ISSUE TITLE
Handle Bitcoin URIs on Windows Phone

### ISSUE THREAD

**Issue by BillStrait** [bitpay/copay#2892]
This seems like pretty basic stuff. When i do a bitpay checkout and I tap the button to pay copay should launch, or at least present as a valid handler.

**Comment by matiu** [comment]
This is implemented already. Do you have other `bitcoin:` handler installed?

**Comment by dabura667** [comment]
Can confirm it works on WP8. I just tapped the button for a Bitpay payment and Copay pops up.

If you have other apps using the bitcoin URI, then they might come up. I only have Copay.

**Comment by matiu** [comment]
Thanks. I have also tried it on WP8, (Lumia 810) with success.

On Tue, Jun 16, 2015 at 1:02 PM, dabura667 <notifications@github.com> wrote:

> Can confirm it works on WP8. I just tapped the button for a Bitpay payment
> and Copay pops up.
>
> If you have other apps using the bitcoin URI, then they might come up. I
> only have Copay.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2892#issuecomment-112480116>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by BillStrait** [comment]
I must have something configured incorrectly. Sorry about that.

**Comment by matiu** [comment]
thanks for the update.

On Tue, Jun 16, 2015 at 1:12 PM, BillStrait <notifications@github.com>
wrote:

> I must have something configured incorrectly. Sorry about that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2892#issuecomment-112482470>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by BillStrait** [comment]
Is there a better location to seek support? I just reinstalled Copay, I'm still being sent to the store to find an app that can handle bitcoin URIs. This is on a Lumia 830 running WP8.1.

**Comment by dabura667** [comment]
> Is there a better location to seek support?

Microsoft? Ask them why URI handler support is broken on Lumia 830.

**Comment by BillStrait** [comment]
Hmm, just had the only other WP user I know try it out on their device. It didn't work for them either. He's using WP 8.1 on a Lumia 930. We are both on Denim. I don't think I'll have a serious chance to take a look at it until tomorrow, but this isn't just me.

**Comment by cmgustavo** [comment]
It is strange, it isn't working on Lumia 630 (WP8.1). I will check it again. Thanks for report.

**Comment by cmgustavo** [comment]
@dabura667 , Do you have your self-compiled version of Copay for WP? 

I realized that the plugin that we are using to handle URI doesn't work on WP (It worked at some point): http://plugreg.com/plugin/EddyVerbruggen/LaunchMyApp-PhoneGap-Plugin

**Comment by Derrick-** [comment]
Handler not working on WP 8.1 under certain conditions.
Possibly because I had another bitcoin wallet previously registered. 
Other app uninstalled now, but I can see no way to add the handler for Copay. 

Hoping that it can check scheme registration at startup and prompt user, or put a scheme registration button in Global Settings?

**Comment by cmgustavo** [comment]
Confirmed: handler not working on WP8.1 (I think this happens since we updated the plugin). There is an issue in the latest release. See discussion here: https://github.com/EddyVerbruggen/Custom-URL-scheme/pull/136

Affected versions: Copay v1.6+ for Windows Phone 8.1

**Comment by sweetppro** [comment]
handler doesn't work on MacOS 10.11.5, Copay 2.0.1

**Comment by bitjson** [comment]
https://github.com/bitpay/copay/issues/4999
