### ISSUE TITLE
Join Wallet with xpub(s)

### ISSUE THREAD

**Issue by robjohnson189** [bitpay/copay#2894]
Add the ability to "join" with xpub(s) so they could be generated offline. This would then allow the other wallets to complete the join process while keeping some keys cold.

This join shouldn't create a wallet on the device completing it. This feature would really be there to  facilitate distribution of the offline xpub(s) and member information to the other wallet members.

**Comment by matiu** [comment]
This is supported by bitcore-wallet-service and impremented on the client:
bitcore-wallet:

See:
https://github.com/bitpay/bitcore-wallet#airgapped-operation

You can interoperate bitcore-wallet with Copay, so, you can create an
airgapped signed from bitcore-wallet for  you Copay wallet.

On Tue, Jun 16, 2015 at 11:41 PM, Rob Johnson <notifications@github.com>
wrote:

> Add the ability to "join" with xpub(s) so they could be generated offline.
> This would then allow the other wallets to complete the join process while
> keeping some keys cold.
>
> This join shouldn't create a wallet on the device completing it. This
> feature would really be there to facilitate distribution of the offline
> xpub(s) and member information to the other wallet members.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2894>.
>



-- 
BitPay.com

**Comment by robjohnson189** [comment]
Thanks, I'll have to try that out.

Do you think there is much need for a gui to help automate a airgapped join?

**Comment by matiu** [comment]
closed in favor of #3217
