### ISSUE TITLE
(BIP74) Send Wallet User Agent Header for Payment Protocol requests

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#2896]
Proposed BIP74 defines a standard to capture the wallet type for every transaction. This information will appear in the bitcoin payment protocol transaction per proposed BIP74.

Copay should implement this UA header ahead of the standard to begin collecting metrics on Copay and payment protocol.

See https://docs.google.com/document/d/101do-hxOE83TjnD-wGqxqveCmgXNORvJlGlNtqJIlbs/edit

Also see https://trello.com/c/xFs8dmIF/600-bip74-store-wallet-user-agent-header-for-payment-protocol-requests

**Comment by carnesen** [comment]
The linked documents are both private.

**Comment by matiu** [comment]
unluckily user-agent cannot be changed from AJAX request
http://stackoverflow.com/questions/1268673/set-a-request-header-in-javascript

Maybe you should modify the BIP to also accept alternate user-agent like:
x-requested-with:

xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest");

what you think?
