### ISSUE TITLE
Better Security: Signed tags/commits and other things

### ISSUE THREAD

**Issue by mika-mitzahlen** [bitpay/copay#2897]
* As many commits as possible should be signed with a PGP signature:

    * `git commit -S<keyid> ...`
    * or set `commit.gpgSign` appropriately.

    Failing that, *every* tag that is associated with a release (e.g., `v1.0.1`) should be signed with a PGP signature:

    * `git tag -s ...`
    * `git tag -u<keyid> ...`

    Currently, this appears not to be happening.

    It might also be prudent to be explicit about some of the dependencies, too, including not only run-time environments like `nw.js`, but also build-time dependencies like `grunt`. For instance, the source of `nw.js` is [hosted in a git repository](https://github.com/nwjs/nw.js/); when a release of `copay` is made, some officially verified version of `nw.js` can be listed by including in a file a commit hash from the `nw.js` repository, and then signing that file. Such a file should be committed to the `copay' repository, so that it is intimately linked with a release.

    In this way, a user has a very good starting point for determining that his `copay` wallet is indeed going to function as it should.

* Please provide copies of the relevant public keys in numerous locations, websites, and formats; it should be possible to collect them from not only a keyserver, but also mailing lists, files served from official servers, and even comments and wikis.

    *Come on, guys! Where's the pedantry?*

**Comment by matiu** [comment]
thanks. Just signed a pending PR with matias@bitpay.com

https://github.com/bitpay/copay/pull/2898

Key at keys.gnupg.net, also copy here:
```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1

mQINBFMnNIUBEADWqanjEZPzo7wfThSpcHOpBXnhb0bKMDXdr03PphC4v9n3juCv
Tab1bQ5DjEQFW/bQf+meEeHi2uVSWib0lcmE8QMXq2JHyPoGI0AUs6nNX9rtSszx
7lantVmKYEVyRlnn/T1GtFfn4utPSNQQIBqV3b6EY8r6lQBkV5QbGlPIKUxyv9GW
gd0I6XPVj48vxtSuqThTBKyL5gpjhjJ3o+ltANF1ydk0Dg47qoxCHutX7oDIuMpi
R353s7vPBm0rggjoesY2PBNZEpPkToILPpucb6PM0PaBPimNpKRz8RKtKutE+TJ/
qb3TqxtL4trt22akxqInDHt90/m6MQsvKMdrFmww9ZEEyq1vpk15PLClQfmpehKf
+8A/DG2t667sFbP9AfZ88VXa2AHFBfAZC6cm8SLIrWvFluXv82I24p5uTV3Dt+Mv
ASwUpNMpjHRzFdutmrFG93wzCGu5uf/CmLk7GrwKeOHJwkVMGsdrGZHFSVtac2Yy
i22iZ6d9hGKKyfu0S6X++5vil0vjMG/VMRBnZpw6NA1B0vyGaFHvEhd/HKmHTO1A
TSmC/n+5kL3Uj0zvbAHHjVlefjdLqYWuVeDQUaoyCSr8r3Po5FxoBGqplxjqrwdy
+HAfEFvAa8WGupndS0AyCAO3JaFzmbfTzgodgEHSs+ik2cwisSMu4PfyqQARAQAB
tDpNYXRpYXMgQWxlam8gR2FyY2lhIChtYXRpYXMgYXQgYml0cGF5KSA8bWF0aWFz
QGJpdHBheS5jb20+iQI3BBMBAgAiBQJTJzSFAhsDBgsJCAcDAgYVCAIJCgsEFgID
AQIeAQIXgAAKCRCe3m3k3lMfrECRD/d1Wsm/qtd+iukM+07vozRChGjJ6Lvnar2G
pQZWTFJ77gJZwgvLvip7LHguT/1XM1yFIvson3xRibFm/dC3ZBE9tzwAZaWjBj+G
oSkc+OypoSPAR9hVxqqi/YivSvhOHRrnBuLQZ3ZWQb2eQJHIM4Pq2WGPb+q9GJYD
qgkRLA5K1SXRlfEWVXn4HV4CFMh3+9TCLBNNJt0S3V4P7TDaZKYNHiwybaZcA1dN
TxaEX7Ngiy/ynK55itQM9LJPpVKH/ZXRHx+Bdju1UDWrJbZpfLnRG7433Y/UHVuI
mWHTbO9QMmAuAty9qDQyFfHqcX2B5sOFElqcUyf+eXUGYRmoso2s92afkYKkA3Ge
BXyPqbNRNvXHzypolgEk57slyypXE7HZP6cNxOFuk+jdoGQPTfeAV+IwN+jFfRj3
KMu1QYJjCsPQcTsEE+aMrwwnSQrPfl8FJmOuCl41qbE6Jbmq7QQObOj6pAlfSFhd
DGOk76IEKmTyvT5Y5kAYktAgRfSzUBRjGi5X4rP135R4i3BPzbVDFxznZkak3+U8
zs/hl04Ft0EZEz0X2C3ahd1h/vuWvT7OmTqF2KtpJPeCZukI/ToL0nmJesBSWprB
OTNf6Q6+gohuQl48uKN7/BpECX4VgBaHJeyn5Ib4Bo2fMXLaQd/+uAvNCMYW4Xjx
vMa1NmKFuQINBFMnNIUBEAC2NwVslezgby9//OtEcspWSqjtffp6vfkYoteAfoKR
MD4l/76J/i6nGoh9Edh3rMMwqLiCwyRURGWGJYfltXknGDl/An0v900BkCvEiNst
+WXZCmHfk4aCqiDMv/BVjUVlkx0cncCAPqzujwtaEDe1ehh6Z9w/RClPO2jxSYYz
RJyZkFPhSyneIQ/0cvDEp5ByJXpr3UYIBms6muC5KSldMRc27/ljQ6wHBMOH1DhW
vEdZeNQJJRudzncrf4724HK99dl/ZXuBkULSBNoxG0DX30n7ISTrODs3cpJ0Y9+x
xvzvWHW3mgBB0WpRTVAz1t+HLHliDB7doiADYeSYEC50NRl01gSpoLGf5RZ/Wln0
D/+wavZLXcY1XbFsKXCbu2se9T9Us50XRX0ibpeIW24zFZO1n8bTUn96alC9fsZt
yDldjXcFVg+FBBlXKFiPTB+IURrx010ximU8thLhtr2XMkMJMTJPGdr6SRFYxrGL
Vml4Z/oB4yl+26nZ4GtidT9OoBiyTU71AQegzf8mXcv6oHQv8AqwrJgqYPwwmeh2
Gj37qH4eXEM2WgET9a++K6Qm0QkimvPj74QRwN7sX/WJNTDzATR1+y38W0rJ2pis
OztmsljeCFYT72YsHMKuk4KqwtgR20rKQD3in2DOQyODAIHju3Izffqhrx7xb+cZ
cQARAQABiQIfBBgBAgAJBQJTJzSFAhsMAAoJEJ7ebeTeUx+s+esQAKy3dUS4bsQZ
wAn6yLDXshdQtKXzVkxt+K/k+59SXNpcor9BV1HjmN72A8conetmgJ6z7zPz2juo
qkWjFR135myGxIWRaWaupMk66qljtFy7+nizJyHqj+DmLmoPJtXMwI++d3jFpizP
97mvdqgLtRNii5LZch6oAMKB3UcJHZ4SD+Cp+HkoKuEnkffFtfXvcQnLSyn4kMiW
UePgfWDHN9bVx4nW3NMyQgGEK9MQYkA2pLYv+2UJEzu/nNcPqlcyhKUVuC0dMiU4
Wech4gAquGaVEagB/5q5GsZnHnfYxYgzxYnGBCRztdNj9Qx8OrSc9SosXNajsW0t
pdCKPJfLQWm/T7PND2VAoN5Ui9QjlZVatlGg3OIVPLMgw2XcHoffZhPPRz2rGv+9
C1KjL15FITxf8NAfXLy2VYJLa3Ot0GTLMSRvIOtFDGYD7gTldQb/KL1M1tFbjd/5
0459XZ1IIOpgv5jruPs58MQQk9NUq3ky1kCKVQ8/yVOomNSzHNKEBq4ev+YqpuJm
Tq6AUuOdgL2f2Yjb1RUU66e2qfP37x3Ths7gVg6GZ/gznCvO0u3W/CzcgvqjmPYG
l1TyGUP0ryBOqUyQExn7tIP+kAVkHUzmIt9ccTvuUs9pkYH2EkHgJEhWuMygQBjv
7ZmxY8p+f5H/Z7NwFC8TRjTnko9gFF6B
=6G6G
-----END PGP PUBLIC KEY BLOCK-----

```

**Comment by mika-mitzahlen** [comment]
Also, presumably, this is the public key used for verifying releases, [1112CFA1](https://pgp.mit.edu/pks/lookup?op=vindex&fingerprint=on&search=0x5CD600A61112CFA1):

    -----BEGIN PGP PUBLIC KEY BLOCK-----
    Version: SKS 1.1.5
    Comment: Hostname: pgp.mit.edu
    
    mQMuBFO8l6sRCAD+VYKPjZY7hMCKVC3KWCkcqvSXEfiqx8KIVSp4yKx1blpVHoBYfAj13Lls
    XkVMujjRVZZB8tVxl3282T/1T4VNLdHy+HvulWbAmZRAJzTw8xZYkb7L9iFFVvIHk2o31Gbq
    7PAvML2MKA556jd0/OjixDR8mLpdAee8la+09RHuWhOYtFJ4nyrVW0nVFApqj1R90eXMcvOj
    vSEdVHEmO341RiwayadfGRRwTqlYtsIx0k64+dpGyjA0CnJJLKVKPTzyn3bQEFhrCq41XfJf
    AFI928/YVb4Wmbd51wgDv01c2b/gyGXwNFW+Qxj9xIcVgK/EPMn2I5j4eBsnOZy9Gn9vAQDj
    SfX26Q6nU1x7ULPjGJ/SefPkYm2swp1Gxfmn78bXFwgA/Q7/QqqARHuUtO3ZP4FgmcxxYYK8
    M+/+ROKoUUPA7Hx3cG3eq86Q5Ok7ADGFTurjaOdZmuV42E54t1pKIYvAe3IJLXr06cx3Vb8L
    zLtalsQsYh2IebwRTu2wvQpsSJxBoVUzwmosNWiOuIemlTpujUFmP89Wad8MsnQSRBNoK0D7
    03ckYjVRJPD+qd788c9JGyTredk0gJzV2dqesMFT+EaLuNUuOktWC+jTGZ5xK9F7EXN0ZfIM
    fKDLFxvCL2a9cTCJIVirn1Ur6QHDsw5PBD/U7DDZDkk9Hzl1ep3qk7PVMn/xDzz3MxKRKKd+
    d7d7wZA9OE+iKoivcAPeC1yTxQgA8KEaCz2TuS1+M9A+8PzGebKJ1OazwCb+tIGWCXUeJlIh
    dRV7W/kre6e4fv0UOxDJHBrIoD1vIGtHguOGSMEnFuVJFDIH2HXXr5oxJkO86RMAig+EbglT
    BJbFEfdx8Ruwhw74JzetijGHYRG62u7n8o8iX6RbpTdzt/nq26fs3Ts0SLMHfP26ZVHJOjY6
    2dTCrw0q20RC4i9HWHJ0g694YBPYvhp2gYks93tigHbIqB1GhpBmBauuNvXRvNs493Rn40FI
    wNMtWZBcQSMch1aEm4j5njDTt4+a6c/v8W2px3u8nFacKBR5FV86WjHEg+HmNx72nvfE/PQW
    HEQixfyiObQpQ29wYXkgKHZpc2l0IGNvcGF5LmlvKSA8Y29wYXlAYml0cGF5LmNvbT6IegQT
    EQgAIgUCU7yXqwIbAwYLCQgHAwIGFQgCCQoLBBYCAwECHgECF4AACgkQXNYAphESz6FzCQEA
    wcLYPogeVLbG3ZL5Bi/Be7U4ctNgewfKEZSSmec3vBYBAIB2xXhiq5ZER1P033KFT8g5pgY2
    fMbk4YsO11Yj2B2m
    =tKra
    -----END PGP PUBLIC KEY BLOCK-----

Similarly, this would appear to be [Gustavo](https://github.com/cmgustavo)'s public key, [9F2EB1AF](https://pgp.mit.edu/pks/lookup?op=vindex&fingerprint=on&search=0x15EDAD8D9F2EB1AF):

    -----BEGIN PGP PUBLIC KEY BLOCK-----
    Version: SKS 1.1.5
    Comment: Hostname: pgp.mit.edu
    
    mQENBFME9A0BCAC6fqILywvBhyD7fWigD9CJKIUkgW02TlNJBFeoRdIlCp5dVJi4zxonusJC
    H7zGntRVsdxp4PirpfZ3uCeWn9A8tSWCp5Nw6kyEc1zxBHueJ9omuDfc1z/TmmD/RIg8p8KT
    D3YiGm6zHj/q3KGT6qqNohk271gjreB4kkbqMALFINedvGZDsoe/r/LeLTIEiIJefQzQePFg
    qLmSUYMAJqjD1vG7OL3qvjKd8r1jpapW38V6E1W9DH57ooVxbxIGxJF2xjRT5L9BbL3G80bv
    Z4TxzGCU/CkC4wMj53HJq9vWWLTBtHS5YQKQi6VY7sOW5UGVqxjrod9f5jnEOPplV1abABEB
    AAG0Jkd1c3Rhdm8gQ29ydGV6IDxjbWd1c3Rhdm84M0BnbWFpbC5jb20+iQE+BBMBAgAoBQJT
    BPQNAhsjBQkJZgGABgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRAV7a2Nny6xr4OnB/94
    PSoBSDw28TOwPV8S90AvRxB6tBtSkWPh3Ve9mVKdGdXhsmyXJOfAQKtVyi6DoUzZw3gHb2dn
    6dJoMb4PfFx/JZDNGYgME1xFkFVTuUQBnuYgFkdghNHNQWx0bDZxdRqP0Zjivb6MebiafnwC
    zjjo1DiVqqDA5wzZo0mpU7s2onhmLIRpffq0fff9EeSolJZpMQGodkb5fzm6AjTSjAiiNsHg
    y+67TynBvmV6MZ0B/Qr2EOzmzHTMg2rxJulK9OSkmucyibmovLgs5XyYOHntK2t/KnZ+0tRH
    i6c0qNvtNTNPChwYbi6AV1ppGcMuMPXMPdsB7XY2Yn42yVZzIraauQENBFME9A0BCADYjaHx
    jWmvKACXJzEbAPYzZSxQobSRLNEqgshwNANU1k0zzMW+dsFpqROUcpAQXd260EoyeEdcxjSf
    uKBa0SWvLSXsP+CCkYEWJc9/q81PwpjeV70jz5EfQCShzILEkjCMWj7ZtMZ8+oAe0OhySJPS
    wkxpBobqd0WUWUcr0VivYZ+eVfnc34QMlCa9s0/XSLyW0J+NAFb2aVO1EjuiEWd7k1JIm20Z
    2q8Bfm2mPEkJztHRqewxqC0ypoBY5TAbsu6Wmu6xeQwcDcpbUAG7va8veq8fM3woICZpwE6n
    uZhuZySpyMQeDEdKQy+TqXV8K/pdndDSgwl+7hPXv2vqpAarABEBAAGJASUEGAECAA8FAlME
    9A0CGwwFCQlmAYAACgkQFe2tjZ8usa+3Zwf/Z+9254tUXmLiFtkyWZXCvpM8jp/yy/O+K/hK
    LjHjxRFja0JPz5S0fZDNbwys6ZBml8lmBTmViTID5DNE+AOOG//Ok4/1VIxzHaZiflLyMprg
    +OpKk/2grwsjNgnfsPX/gbZWoHugaOjf8IWcbffokrNOgA+UNM63vPtdcvIijv9HpufvRL4y
    gw56QF1TH8pH6ocapZbs0UKNhjZq67+IQrwQb4LS/+6M8qm3AylR42JIDFdCcBS0AyzAJ6Rw
    6JCjUjOywF12nOCN5mYCOmYJYcOGCav7wbo+l5WTLWAKEfEmIk71ppivtVrRwLv6Ng8FK0dG
    Mw1q7x+9AuuAqPfTYw==
    =z6SG
    -----END PGP PUBLIC KEY BLOCK-----

**Comment by gabegattis** [comment]
+1 I have recently started signing all of my commits. It is very easy to do. Just add a "-S" when doing git commit.

Also +1 on specifying commit hashes for dependencies.

**Comment by matiu** [comment]
fixed.
