### ISSUE TITLE
Not Sync My Multisig Wallet on Chrome

### ISSUE THREAD

**Issue by goalkeeper112** [bitpay/copay#2912]
Hi! guys, i've a problem, i lost my linux partition in where i has my multisig wallet copay on chrome, they don't with my another paritition with linux and her google chrome, i haven't any backup and i can't rescue the partition, how i can rescue my public key, because the wallet is 4at4 and we can't send money

**Comment by matiu** [comment]
not sure I understand your problem.  

Are you telling you have a 4 of 4 wallet and you have lost one of the keys and you dont have a backup? If that is the case I am afraid there is way to access the funds.

**Comment by goalkeeper112** [comment]
The problem is simple, i lost my public key and the multisig wallet is 4 of 4, we can't send money, not exist way to rescue these key?

**Comment by matiu** [comment]
I guest you mean you lost your *private* key.  There is not way to recover you key, it only exist on your device and in the backups you made (in case you made some).
