### ISSUE TITLE
I have 2 wallets that seem to have corrupted

### ISSUE THREAD

**Issue by BitpopCoin** [bitpay/copay#2914]
They both keep changing balances from the correct balance to what seems a cached balanced. It happens on both android and windows. I can't send because it tries to use used inputs. Has the server been broken the last 12 hours?

**Comment by matiu** [comment]
Hi,

I am sorry you are having this problem. We wallet service was been working normally in last days.

On the backend, BWS uses a pull of Insight instances. It seems that in your case there are disagreements on the Insight server about your addresses' balances and UTXOs. I am not sure how this could happen, we would need to check insight DB.

Would you be able to contact us thought Gitter (https://gitter.im/bitpay/copay) so we can investigate this problem further (we will need to check the actual addresses' balances).

Alternatively, you can run your own BWS (https://github.com/bitpay/bitcore-wallet-service, which should be fairly simple to run) and point it to your own instance of Insight or  BitPay's public Insight instance ( insight.bitpay.com) or any other of the public insight instances around, so you can access the funds.

**Comment by matiu** [comment]
Closed via gitter. On of the backend insight server was delayed on the blockchain sync, so I was returning outdated balanced. It is fixed already and confirmed by @BitpopCoin . Thanks for the report.
