### ISSUE TITLE
Must be able to modify the transaction fee!

### ISSUE THREAD

**Issue by Sabbe** [bitpay/copay#2937]
I looked everywhere but didn't see an option to modify the transaction fee. With this day and age in Bitcoin, with blocks being full on occasion, with stress tests being done weekly, this feature is a MUST HAVE.

A wallet can become almost unusable without the ability to modify the tx fee. Please put this feature to TOP priority.

I'm using the Android version of Copay btw, in case there are platform differences.

**Comment by matiu** [comment]
This is already on master https://github.com/bitpay/copay/pull/2901
will be delivered to the app stores  soon.

**Comment by Sabbe** [comment]
Excellent news! You're doing great work. Keep it up.

Henry
