### ISSUE TITLE
Addons for Copay

### ISSUE THREAD

**Issue by troggy** [bitpay/copay#2949]
We want to make an addon to Copay, that will make it [color aware](http://coloredcoins.org/documentation/). Is there any addon/plugin support planned for implementation? I see PluginManager service which is not in use and delegates to non-existing code, hence my question.

**Comment by matiu** [comment]
Hi, thanks for your interest.

PluginManager is deprecated. It was meant only for storage alternatives. What kind of functions could be provided by the color integration?

**Comment by troggy** [comment]
Ideally, it should be possible to perform all the manipulations available for ColoredCoins assets. These are (this might not be a complete list):

1. Viewing available assets (initial version for this is already implemented in the [fork](https://github.com/troggy/copay/tree/color-aware))
2. Create new asset
3. Transfer asset
4. Displaying list of other asset holders (not sure it will be needed)

I guess, points 2 and 3 would require to hook into send coins functionality: actual unsigned transaction will be provided by ColoredCoins API, then Copay needs to sign it.
All the points will require to hook into UI.

**Comment by troggy** [comment]
On the second thought, all the functionality for color integration is not intersecting with main Copay functionality, so such an addon could be fully incorporated into a separate view (say, as a new "tab" in the bottom bar among "Home", "Send", "Receive" and "History"). And all the code behind this view could be fully separated, so no hooks into the core Copay signing code will be required.
