### ISSUE TITLE
Add fiat value to csv downloads

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#2961]
See https://github.com/bitpay/copay/pull/2954

**Comment by matiu** [comment]
wont fix.

**Comment by dan-da** [comment]
There's a workaround for anyone that needs this:
  https://mybitprices.info/faq.html#howdoiexportaddressesfromacopaywallet

Given your xpub key, the above tool can find all wallet addresses and then generate a transaction history including historic fiat prices and even gain/loss info.
