### ISSUE TITLE
Display problem for 'Send All'

### ISSUE THREAD

**Issue by Kirvx** [bitpay/copay#2963]
v1.1.0

![screenshot_2015-07-08-01-42-54](https://cloud.githubusercontent.com/assets/6627786/8559969/5ed8a70c-2513-11e5-93d5-2805b21e28dc.png)

**Comment by bechi** [comment]
@Kirvx  In which phone and OS it's happening?

**Comment by Kirvx** [comment]
@bechi Galaxy Nexus - 4.4.4 - Paranoid 4.6 BETA 6
