### ISSUE TITLE
3rd Party App Integration

### ISSUE THREAD

**Issue by DisruptorNation** [bitpay/copay#2966]
@bitjson
 
Making the user experience of enabling 3rd party apps is critical to the value of the Copay wallet. My suggestion for the UI design is below.

Sig3's recommendation for 3rd party app integration:

- Show a check box on the multi-sig wallet creation page that allows users to easily enable an app. For example, in Sig3's case it would say "Add Sig3 as a copayer (what is Sig3?)". We would provide the content for the "what is Sig3?" pop-up box or page.
- When a user has marked the box and clicked on "Create Wallet", Sig3 is automatically added as a copayer and represented as such on the shared secret page. 
- Once an app has been enabled, a button or icon is added to the dashboard signifying that the app was successfully added. The button or icon could link to a "3rd Party Apps" page where each app is described and could be added.
- Add a tab at the bottom of the dashboard page called "3rd Party Apps" so users can learn about the available apps and enable them. Same as above and similar to the plug-ins link/page for WordPress.

![screenshot-1](https://cloud.githubusercontent.com/assets/13156740/8583857/3967d7e2-258e-11e5-9790-b7e7c3c239e5.png)
![screenshot-3](https://cloud.githubusercontent.com/assets/13156740/8583860/3e105260-258e-11e5-90d7-0602c98ffc90.png)
![screenshot-4](https://cloud.githubusercontent.com/assets/13156740/8583863/417e14f0-258e-11e5-8e99-1022246679b4.png)

**Comment by troggy** [comment]
I've started some work on making Copay extendable. We need that for quite a different project ([Colored Coins](http://coloredcoins.org/)) and therefore don't hook into core Copay UI screens.
See:
https://github.com/bitpay/copay/issues/2949
https://github.com/bitpay/copay/pull/2968

**Comment by matiu** [comment]
Marking this as done thanks to @troggy's work + sig3.
