### ISSUE TITLE
Allow Screenshotting QR Codes for Chrome Extension

### ISSUE THREAD

**Issue by ghost** [bitpay/copay#2967]
Hey!

It would be great if copay had a feature on the chrome app where you can select a part of the webpage that has the qr code and analyze that.

Thanks.

**Comment by koalalorenzo** [comment]
I don't understand and I don't see a real use case for this. Do you want to take a screenshot of a QR code? I think that you can do that on your OS! On mac you can use cmd-shift-4 and select the area you need from your screen...

**Comment by nahtnam** [comment]
@koalalorenzo The reason i want this, is that sometimes sites show a qr code and so it would be really fast if I open copay on my computer and just select the QR code. Right now the desktop app uses your webcam, and who realistically holds a qrcode in front of their webcam?

**Comment by koalalorenzo** [comment]
I do use qrcode on my webcams with localbitcoins, when I have to pay somebody that is in my office after an exchange! Usually if you can see/read a qrcode on your screen you should be able also to copy-paste the address... or click on that using "bitcoin:" address for app links. I don't think that this is a issue/ important feature. :(

**Comment by nahtnam** [comment]
Sometimes sites dont have a bitcoin url provided and i would rather just have the option to select it.

This feature really couldnt hurt in any way...

**Comment by koalalorenzo** [comment]
They must provide the address anyway so you can copy and paste it: it's a non sense to make a screenshot of a qrcode in order to analyze it, when you can use copy-paste feature of your OS. :-1:

**Comment by nahtnam** [comment]
4 clicks, and 4 buttons + a password is what you need right now.

**Comment by matiu** [comment]
Agree that the copy and paste of the address on the screen seems to be simpler for the user and easier to maintain.
