### ISSUE TITLE
error storing wallet (unable to store data in insight)

### ISSUE THREAD

**Issue by sweetpotatoz** [bitpay/copay#2974]
cannot show all my balance correctly.
i have tried to scan my wallet address.
failed to send my bitcoin to other address.

it only able to show balance in one of my address.
i have send some bitcoin to my new address yesterday, even though shown in history but not added up in balance.  Tried to send out all bitcoin to my other wallet, but failed.

**Comment by dabura667** [comment]
Copay does not store wallet data with insight anymore.

If you have an old wallet, you must restore it using the new Copay.
