### ISSUE TITLE
Copay froze during signature creation for a spend proposal in a 2-of-3 wallet

### ISSUE THREAD

**Issue by jojkaart** [bitpay/copay#2976]
I was creating a new spend proposal and after I clicked send, it froze in the "signing transaction" phaze. I left it for 15 minutes but nothing else happened. The proposal itself somehow made it to BWS (bws.bitpay.com) despite this and one of the other participants signed it while I was waiting if my phone (android) would manage to get the signature done.

I tried signing it 2 more times, with a similar result. One of them was after rebooting my phone. Later I succesfully signed another send proposal to test if it the problem was limited to this specific transaction.

Eventually we got the transaction through by having the third participant sign the proposal.

I'd prefer to not reveal information about the wallet publicly, if possible. Is there some way to privately give a developer the txid in question?

**Comment by matiu** [comment]
Are you using v1.1.0? this was an known bug when using fee at 'emergency'
level. If you are using 1.1.0 Could you upgrade to 1.1.1? Thanks.

On Mon, Jul 13, 2015 at 9:54 AM, Joel Kaartinen <notifications@github.com>
wrote:

> I was creating a new spend proposal and after I clicked send, it froze in
> the "signing transaction" phaze. I left it for 15 minutes but nothing else
> happened. The proposal itself somehow made it to BWS (bws.bitpay.com)
> despite this and one of the other participants signed it while I was
> waiting if my phone (android) would manage to get the signature done.
>
> I tried signing it 2 more times, with a similar result. One of them was
> after rebooting my phone. Later I succesfully signed another send proposal
> to test if it the problem was limited to this specific transaction.
>
> Eventually we got the transaction through by having the third participant
> sign the proposal.
>
> I'd prefer to not reveal information about the wallet publicly, if
> possible. Is there some way to privately give a developer the txid in
> question?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2976>.
>



-- 
BitPay.com

**Comment by jojkaart** [comment]
Ah, yes, that's probably it. I'll reopen the issue in case it happens again with the new version.
