### ISSUE TITLE
Copay splash screen looks blurred in Android

### ISSUE THREAD

**Issue by sironitomas** [bitpay/copay#2979]
This is a small UI issue. [copayscreen.png](https://github.com/bitpay/copay/blob/master/cordova/android/res/drawable-port-xhdpi/copayscreen.png) needs to have a Full HD resolution in order to look sharp.

**Comment by bechi** [comment]
I can't reproduce this issue, but I will try to reproduce it and fix it

**Comment by sironitomas** [comment]
This is what I mean. From the same screenshot, I pasted the logo closer to the UX icons so you guys can see the problem. Hope this helps!

![screenshot_2015-08-25-11-50-05](https://cloud.githubusercontent.com/assets/813178/9471591/8281b7cc-4b27-11e5-8c6d-3cb73759bdae.png)

**Comment by bechi** [comment]
Oh I see. I will fix it right now

**Comment by sironitomas** [comment]
Also, please check that the background has some weird bands. They aren't very visible, but definitely there. I added contrast to make it easier to see them.
![screenshot_2015-08-25-11-50-05](https://cloud.githubusercontent.com/assets/813178/9476889/8d0c72e0-4b45-11e5-95df-68d4898b96db.png)
