### ISSUE TITLE
Double Notifications for 1 of N Wallets

### ISSUE THREAD

**Issue by bitjson** [bitpay/copay#2988]
When sending payments from a 1 of 2 wallet, the user gets two emails simultaneously:
- subject: `New payment proposal`, and
- subject: `Payment sent`

I think we need to adjust the logic to not send the `New payment proposal` message unless the required signers is greater than `1`.

**Comment by isocolsky** [comment]
A solution to this issue is not trivial. Consider the addition of non-signing copayers (introduced in this PR #2998). If a proposal is created by this user, there should be a `New payment proposal` email sent to the other copayers (and maybe to all of them?) as someone with signing capabilities need to step forward and accept it. We will continue discussing possible solutions. Thank you for reporting.

**Comment by dan-da** [comment]
Please consider making the email notifications optional.   Not everyone wants to associate an email address with their funds and have those notifications hopping around the internet.  At the very least PGP encryption should be offered.

For my company's banking website with a prepare/authorize workflow, the bank does not send me (authorizer) any notification.   Rather, the preparer notifies me via internal communications channel.  Or if I happen to login to the bank's website I see a notice that there are pending transactions awaiting approval.  That is a perfectly usable workflow that maintains privacy.

**Comment by matiu** [comment]
email is optional, and turned off by default.

On Thu, Jul 16, 2015 at 4:48 PM, dan-da <notifications@github.com> wrote:

> Please consider making the email notifications optional. Not everyone
> wants to associate an email address with their funds and have those
> notifications hopping around the internet. At the very least PGP encryption
> should be offered.
>
> For my company's banking website with a prepare/authorize workflow, the
> bank does not send me (authorizer) any notification. Rather, the preparer
> notifies me via internal communications channel. Or if I happen to login to
> the bank's website I see a notice that there are pending transactions
> awaiting approval. That is a perfectly usable workflow that maintains
> privacy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/2988#issuecomment-122068901>.
>



-- 
BitPay.com

**Comment by dan-da** [comment]
awesome.  I'm excited to try this out as soon as I can find time -- aiming for early next week.
