### ISSUE TITLE
[Idea] Window of confirmation for accepting, rejecting and deleting payement proposal.

### ISSUE THREAD

**Issue by Kirvx** [bitpay/copay#3014]
What do you think of that?

**Comment by dan-da** [comment]
just my $.02, fwiw.

A popup may be ok, eg upon login or when a payment proposal first arrives.

However, it should be possible to close the popup and deal with it later at one's convencience.  So the key thing is for there to be a notification link/button eg "XX pending payments awaiting your review" that always appears in the same location, so the user gets trained to look in that spot in case there are any.

**Comment by Kirvx** [comment]
Well I simply thought displaying a window like "Are you sure to %?" when the user click on "Accept" "Reject" and "Delete Payment Proposal" for the proposals ^^

**Comment by dan-da** [comment]
yeah, that's a different thing.  makes sense to me.

**Comment by Kirvx** [comment]
@matiu What do you think? :relaxed:

**Comment by matiu** [comment]
* In multisig, the user needs to open a tx proposal, and then check on accept / reject / delete. It is a 2 step process, so we thought that no confirmation was needed, we didn't wont to add friction to the process.
* In non-multisig, creating the transaction (filling the form) is a multistep process, so there is not risk of an accidental click.

That is why we decided not to add a confirmation popup. Users could add a passphrase for the priv key if they think you need an extra step (which of course is not the same you are proposing) .

**Comment by Kirvx** [comment]
OK :)
