### ISSUE TITLE
IDEA: Blind signatories

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#3015]
I have created an issue on BWS as well.

Similar to no-privkey backups, a blind signatory would only be able to obtain the following information
1. Can NOT see balance
2. Can NOT see addresses
3. Can NOT generate payment proposals
4. CAN sign payment proposals
5. Can NOT see the contents of the payment proposal they are signing

4 and 5 seem contradictory, but this can be achieved by generating the z value (tx hash for signing) and sending only the z value to the signer, which the signer returns only the ECDSA signature to BWS and BWS stores the signature.

This would be an interesting feature that allows for many new escrow cases.

The z value would have to be somehow verified out of band by a fellow copayer, this would require somehow showing the user a representation of the z value.

**Comment by matiu** [comment]
Intersting. Could you explain a little more the use case?

On Fri, Jul 17, 2015 at 11:47 PM, dabura667 <notifications@github.com>
wrote:

> I have created an issue on BWS as well.
>
> Similar to no-privkey backups, a blind signatory would only be able to
> obtain the following information
>
>    1. Can NOT see balance
>    2. Can NOT see addresses
>    3. Can NOT generate payment proposals
>    4. CAN sign payment proposals
>    5. Can NOT see the contents of the payment proposal they are signing
>
> 4 and 5 seem contradictory, but this can be achieved by generating the z
> value (tx has for signing) and sending only the z value to the signer,
> which the signer returns only the ECDSA signature to BWS and BWS stores the
> signature.
>
> This would be an interesting feature that allows for many new escrow cases.
>
> The z value would have to be somehow verified out of band by a fellow
> copayer, this would require somehow showing the user a representation of
> the z value.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3015>.
>



-- 
BitPay.com

**Comment by dabura667** [comment]
Imagine an escrow service that would hold a third key for companies.

The escrow, currently, would need to be entrusted with the ability to view all finances, but wouldn't it be nice if a third party could just agree "I will press sign only when it comes through Copay, and I will verify the hash with you over the phone to verify."

It seems a little weird, because it was not possible up until now. But I think this is a unique bitcoin use case.

**Comment by matiu** [comment]
Thanks a lot for the explanation.

JFYI, I think the air-gapped operation from bitcore-wallet (
https://github.com/bitpay/bitcore-wallet) could be modified to handle that
use case.

On Thu, Jul 23, 2015 at 7:22 AM, dabura667 <notifications@github.com> wrote:

> Imagine an escrow service that would hold a third key for companies.
>
> The escrow, currently, would need to be entrusted with the ability to view
> all finances, but wouldn't it be nice if a third party could just agree "I
> will press sign only when it comes through Copay, and I will verify the
> hash with you over the phone to verify."
>
> It seems a little weird, because it was not possible up until now. But I
> think this is a unique bitcoin use case.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3015#issuecomment-124049028>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by dabura667** [comment]
I still think this would be cool feature... but I guess Bitpay is ramping down on its open source development lately...

It's a shame...
