### ISSUE TITLE
Various Crowdin suggestions

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#3018]
1. All crowdin users should be able to translate any language freely. Adding the "join project" step in between and waiting for you to add them is unnecessary.
2. "Proofreaders" should be 1 or 2 people per language, where you are fairly certain that they are serious about translating the language. These roles can "approve" translations and override the voting system. (Any string without an "approved" candidate will build translations with the highest voted non-approved translation by default)
3. "Add Term" feature should be open to all users, and only restricted if someone starts abusing it. (I noticed I can add terms now, but I am also a proofreader, so I am not sure this is open to all.
4. "Download file" and "Upload file" option should be enabled for all users. Some people might have tools on their local computer that they would like to utilize, so having the ability to download the po file would be nice. This can only create suggestions, so it won't ruin the pot file or anything.
5. The "appstore_en" file should also be on the crowdin. However, I am not sure what format the file should be in. If you give me manager rights to the copay crowdin, I can test a few different formats and make a pull request to format all the other files as well.

Also, adding a script into the main repo to allow for frequent updates to translations on Copay ( #3012 ) would also be good.

**Comment by dabura667** [comment]
Here's an example of the best (in my opinion) setting for the project.

![example](https://cloud.githubusercontent.com/assets/6586275/8771013/605453c8-2ef6-11e5-9bdc-1a768b548d72.png)

**Comment by cmgustavo** [comment]
I agree with your suggestion for preferences. The initial configuration was a proof mode to learn more about the translation process with Crowdin. I see that you have experience using that, so I will add manager rights to you.

Regarding appstore_docs, I thought we could have an html file with `translate` attributes, then with grunt generate a .pot file and finally with (https://github.com/divampo/grunt-angular-gettext-generate-html) generate the html for each language. It 's just an idea, what do you think?

**Comment by dabura667** [comment]
I think that can work too. The only problem would be deciding how to split up the segments for translation.

Too big and it's a little unwieldly, too small and gettext will alphabetize the whole thing so you can not see the context (previous and proceeding segments)

txt files can be uploaded to crowdin directly. Maybe we should:
1. Change the file type to txt.
2. Separate the Appstore description and the "What's new" update info into two separate txt files.

One example of how the translation screen looks for txt files is the following.

https://crowdin.com/translate/telegram-with-getgems/4/en-es

This shows all strings in their context, but let's you edit the strings as individual sentences. It's kind of nice.

The problem with gettext is that it just shows the strings in alphabetical order, so the developer needs to decide where to separate the strings to maintain context.

**Comment by dabura667** [comment]
Another thing you might want to consider:

If you want to only pull in translations once templates.pot is 100% done, then we will have to check "Export only Approved translations" and make sure to approve all translations before exporting.

If you don't do this, there might be a situation where a partially translated po file is used and the user will see a mixture of their language and English. Electrum does this. It should be fine, but some people don't like to do this, so they wait til 100% and then approve everything. Then if anyone shows up to say "we want to change this string" appoint them as proofreader for that language and let them change the approvals, just tell them to make sure all strings have at least one approved at all times.

I don't know how your views on running the translations are, but I personally think the Electrum way of partially showing translation is ok. (The way it would be currently if you just automated and pulled all translations as is.)

**Comment by cmgustavo** [comment]
+1 to split the files in `description` and `changelog` or something for "What's new". I agree to use txt file to translate, it looks really easy for translator.

**Comment by cmgustavo** [comment]
I really don't know what is the best way to do that, but the Electrum way sound good for now.

**Comment by dabura667** [comment]
Maybe is there a way for angular to check if a language po file has all values? If so we could add an `"(Incomplete)"` after the language name in the language selection window.

**Comment by cmgustavo** [comment]
I 'm not sure. I think we could add `incomplete` manually.

**Comment by dabura667** [comment]
I just added store description and most recent update info as a txt file. I also copy pasted the current translations for each language (sentence by sentence) so that it will already be input to the Translation Memory.

I am currently working on the script for automation.
