### ISSUE TITLE
We urgently need red!

### ISSUE THREAD

**Issue by samapplebee** [bitpay/copay#3022]
Every wallet colour under the sun exists for users to select. Except red.

Copay needs red! Please... :)

**Comment by kaibakker** [comment]
I can give this a try, looks like https://github.com/bitpay/copay/blob/6cb4a4c34bc9d7c39d7f0a8ab5712ee5e6ef4a92/src/js/controllers/preferencesColor.js file is responsible for the possible color preferences. 
What kind of red would you like?

**Comment by samapplebee** [comment]
Thanks Kai!

A nice bold one, maybe like #DD4B39 ? (just colour picked from Gmail
'compose' button haha)

On 23 July 2015 at 11:29, Kai Bakker <notifications@github.com> wrote:

> I can give this a try, looks like
> https://github.com/bitpay/copay/blob/6cb4a4c34bc9d7c39d7f0a8ab5712ee5e6ef4a92/src/js/controllers/preferencesColor.js
> file is responsible for the possible color preferences.
> What kind of red would you like?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3022#issuecomment-124050962>.
>



-- 
Sam Applebee
Product owner - Satalia <http://www.satalia.com/>

Mobile: 0789 111 0401
LinkedIn <http://uk.linkedin.com/in/samapplebee> - Twitter
<http://twitter.com/Sam_Applebee>

**Comment by kaibakker** [comment]
To make things clear, I am not a bitpay developer, I just passed by and thought it would be a nice way to learn something. Here is the pull request:

https://github.com/bitpay/copay/pull/3028

**Comment by samapplebee** [comment]
Yeah I realise it's because you're awesome and not because you're getting
paid haha

Nice one Kai

On 23 July 2015 at 13:50, Kai Bakker <notifications@github.com> wrote:

> To make things clear, I am not a bitpay developer, I just passed by and
> thought it would be a nice way to learn something. Here is the pull request:
>
> #3028 <https://github.com/bitpay/copay/pull/3028>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3022#issuecomment-124084647>.
>



-- 
Sam Applebee
Product owner - Satalia <http://www.satalia.com/>

Mobile: 0789 111 0401
LinkedIn <http://uk.linkedin.com/in/samapplebee> - Twitter
<http://twitter.com/Sam_Applebee>

**Comment by matiu** [comment]
closed by https://github.com/bitpay/copay/pull/3028

thanks!
