### ISSUE TITLE
updates for OS X desktop app should be accessible from menu

### ISSUE THREAD

**Issue by ecv4btc** [bitpay/copay#3024]
It would be better a better user experience to be able to select "update" from the desktop app menu like other OSX applications.

**Comment by nilsws** [comment]
Or even better, there should be an automatic check for updates in the background and a popup that prompts users to install the latest version. Most users don't check out Github every month to see if there's a new version available.

**Comment by martindale** [comment]
+1 for the background check and notification method.

**Comment by KeyJockey** [comment]
This would be okay AS LONG as there remains an option NOT to update and stick to using an older version if desired.  

As I've noted (extensively) elsewhere, I personally prefer to stay with the 1.1.2 version for now, until my issue https://github.com/bitpay/copay/issues/3111 about miner fee control is improved. Seems like only on the Chrome/Win release is the updated version *forced.*

On my Macbook, in particular, I vastly prefer being able to manually update (or not) as needed.

**Comment by matiu** [comment]
Currently updates are shown on as notifications (on desktop apps) with a link, so user know there is an upgrade and can download it.
