### ISSUE TITLE
differentiate icons on OSX and Chrome so they are not identical

### ISSUE THREAD

**Issue by ecv4btc** [bitpay/copay#3025]
Chrome-launched Copay and OSX Copay icons look the same on my Dock. Would be better if there was some way, either under the version number on the Copay "menu" or on the icon, to differentiate the apps so I know which one I'm working with.

**Comment by XBTdev** [comment]
+1. Good suggestion.

I encountered the same usability issue. For now, you can tell them apart by "copay" vs "Copay". The osx app should be all lowercase.

![screenshot 2015-07-26 22 19 56](https://cloud.githubusercontent.com/assets/3032137/8899068/7b33c44c-33e4-11e5-9787-8dda3adeb155.png)
