### ISSUE TITLE
QR scan sound is terrifying

### ISSUE THREAD

**Issue by ecv4btc** [bitpay/copay#3026]
The sound Copay app makes when scanning a QR code scares me every time I hear it. Please replace with the BitPay "ding" or something pretty-sounding and pleasant.

**Comment by dabura667** [comment]
I've always had my phone on mute, but SERIOUSLY THAT IS TERRIFYING!

+1000

**Comment by matiu** [comment]
what platform?

On Wed, Jul 22, 2015 at 1:14 PM, dabura667 <notifications@github.com> wrote:

> I've always had my phone on mute, but SERIOUSLY THAT IS TERRIFYING!
>
> +1000
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3026#issuecomment-123775964>.
>



-- 
BitPay.com

**Comment by ecv4btc** [comment]
Android app
ᐧ

On Wed, Jul 22, 2015 at 12:17 PM, Matias Alejo Garcia <
notifications@github.com> wrote:

> what platform?
>
> On Wed, Jul 22, 2015 at 1:14 PM, dabura667 <notifications@github.com>
> wrote:
>
> > I've always had my phone on mute, but SERIOUSLY THAT IS TERRIFYING!
> >
> > +1000
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/bitpay/copay/issues/3026#issuecomment-123775964>.
> >
>
>
>
> --
> BitPay.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3026#issuecomment-123777304>.
>



-- 
Emily Vaughn
Marketing Manager
BitPay, Inc.
T: +1 228.669.7038

**Comment by dabura667** [comment]
And iOS as well.

**Comment by dabura667** [comment]
The volume is very very loud compared to other sounds on my phone.

Also the sound is very sharp and hurts the ears.

**Comment by cmgustavo** [comment]
With iPhone it isn't so annoying (I don't know if it the same sound). 

BTW, Cordova (the builder of Copay for mobile apps) puts this sound. We should see if it is possible to change (but I don't think so).

**Comment by dabura667** [comment]
other cordova apps don't emit this sound. (see Hive iOS and Ninki Wallet iOS)

**Comment by ecv4btc** [comment]
That's my experience as well, very loud and jarring. It makes me jump every time. Wasn't sure if it's the QR scanner/camera on my phone (Android/Samsung Galaxy S5) or the app.

**Comment by cmgustavo** [comment]
Great, so surely it 's configurable.

**Comment by dabura667** [comment]
I have an iPhone 6. Turned off mute switch, listened to heavy metal on Youtube on full volume. then switched to Copay... it went silent, I scanned a QR and I was startled.

I don't startle easily.

I never noticed because I always have my phone on mute so it never played for me before.

**Comment by wallclockbuilder** [comment]
Interesting. I'm using windows phone. Just tried it. No sound.

**Comment by matiu** [comment]
The sound you are all hearing is 'beep', right?

On Wed, Jul 22, 2015 at 6:42 PM, Mawueli Kofi Adzoe <
notifications@github.com> wrote:

> Interesting. I'm using windows phone. Just tried it. No sound.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3026#issuecomment-123875246>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by wallclockbuilder** [comment]
Nope. Just a vibration. All my sound settings: full volume. Expected some sound.

**Comment by ecv4btc** [comment]
Yes, a loud, harsh beep. If we can... the BitPay "ding" would be nice here

Emily Vaughn
Marketing Manager
228-669-7038
@bitsmash




This message was sent from my cell phone and may have been dictated via
voice-to-text. Please excuse typos.

**Comment by bitjson** [comment]
If anyone wants to submit a pull request for this, I can provide the sounds!

**Comment by matiu** [comment]
please provide an .ogg file and we can replace it (Android only)
