### ISSUE TITLE
Allow user to make transaction notes required

### ISSUE THREAD

**Issue by XBTdev** [bitpay/copay#3031]
I'm probably not the only person who looks through their transaction history later and says "Why didn't I add notes so I can figure out what these transactions are?"

The solution is simple; add a ON/OFF toggle under wallet settings "Require notes" so it won't let me send bitcoins without adding a description of the transaction.

This will keep the accountants happy :)

**Comment by isocolsky** [comment]
An alternative to this would be to allow users to annotate transactions directly from the history tab.

**Comment by dan-da** [comment]
I like this idea.  Either way is fine, so long as shared amongst the Copayers.

**Comment by vaikekana** [comment]
+1 require notes toggle is a great idea!

but equally, being able to edit existing historical transactions (like when you have received coins)

**Comment by matiu** [comment]
Done on Copay 2.0 (as the possibility to add comments to existing transaction) https://github.com/bitpay/copay/issues/3031#issuecomment-129094894)
