### ISSUE TITLE
Reusable Addresses / BIP 47

### ISSUE THREAD

**Issue by CredibleFriends** [bitpay/copay#3032]
Copay is quickly becoming the best all-around wallet. I would like to see privacy take a front-seat in development priority.

Are there any plans to implement [BIP47](https://github.com/OpenBitcoinPrivacyProject/bips/blob/master/bip-0047.mediawiki), or any other form of reusable addresses / stealth addresses ?

**Comment by matiu** [comment]
Thanks for you comments.

Yes, this is something that has been discussed many times. Still it was not decided which approach Copay will take. We put a lot of effort to prevent address re-usage but, in order to enhance the usability, some kind of reusable code is needed.

**Comment by bitalias** [comment]
Consider partnering with https://bitalias.github.io which will leverage BIP47. ;)

**Comment by XBTdev** [comment]
http://samouraiwallet.com/ has confirmed that they are nearly done with implementing BIP 47.

Also spoke with Ryan from onename and he suggested that they would support BIP 47 if the wallets supported it.

**Comment by luke-jr** [comment]
FWIW, I discourage implementing BIP 47 due to design flaws mentioned on the bitcoin-dev ML that were not addressed.

**Comment by bitjson** [comment]
@luke-jr any chance you have a link? I'd love to look into that.

**Comment by dan-da** [comment]
I'm guessing that Luke is referring to this thread regarding notification addresses.

http://thread.gmane.org/gmane.comp.bitcoin.devel/11008/focus=11022

**Comment by luke-jr** [comment]
Yes, it begins at https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2015-October/011592.html
