### ISSUE TITLE
Wallet self-destruct

### ISSUE THREAD

**Issue by XBTdev** [bitpay/copay#3033]
The people over at [ledgerwallet](http://support.ledgerwallet.com/knowledge_base/topics/what-happens-if-i-forget-my-pin-code) have designed their hardware wallet to self-destruct (factory defaults) after three incorrect pin attempts.

It would be interesting if copay wallets had a similar setting 'Delete after 3 failed attempts: on/off'.

Just opening up the topic for discussion. (You could also allow for a 'duress' passphrase which immediately deletes the accounts.)

**Comment by matiu** [comment]
Intersting idea :)

This would apply for wallets protected with passphrase, correct?

On Fri, Jul 24, 2015 at 6:34 AM, XBTdev <notifications@github.com> wrote:

> The people over at ledgerwallet
> <http://support.ledgerwallet.com/knowledge_base/topics/what-happens-if-i-forget-my-pin-code>
> have designed their hardware wallet to self-destruct after three incorrept
> pin attempts.
>
> It would be interesting if copay wallets had a similar setting 'Delete
> after 3 failed attempts: on/off'.
>
> Just opening up the topic for discussion.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3033>.
>



-- 
BitPay.com

**Comment by XBTdev** [comment]
Yes, this would apply to passphrase protected wallets. Or to a app-pin-code if that feature is added.

Honestly, I'd much prefer the Stealth Wallet #3030 feature... but I thought for the sake of discussion I'd see what people's thoughts were on wallet self-destruct.

**Comment by dan-da** [comment]
self destruct after 3 tries scares me.  Haven't you ever lost a password and then tried several variations until you get it right?

I definitely prefer the stealth wallet idea.

**Comment by tab00** [comment]
What if there was millions of dollars worth in the wallet? Someone tries to guess your PIN a few times, then you lose the entire wallet?

**Comment by matiu** [comment]
This seems to be to 'scary' for most used. Closing this one in favor of Stealth wallet idea.
