### ISSUE TITLE
Add credits for crowdin translators in app

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#3038]
Add a page somewhere in the app that thanks all the crowdin translators.

I was thinking maybe in the about Copay page add a link below session logs that says "Translators" and the page just lists out the crowdin usernames of everyone who helped.

Then just copy the entire list of translators / proofreaders in crowdin and paste them.

It might be a good way to say thank you. (I think a lot of people who translate the app will evangelize the app too, and saying "I helped translate it, see!" will make the translator more proud to show off the app, and make their friends more likely to try it out.

It will also instill a sense of "I am the xxx translator for Copay" sense of commnuity.

**Comment by dabura667** [comment]
Or maybe use the upper right corner (in the topbar) of the language setting page as a place for a link to such a page.

**Comment by koalalorenzo** [comment]
That's nice :-) :+1:

**Comment by matiu** [comment]
+1000 !
