### ISSUE TITLE
Transaction countervalue needs to be displayed without extra clicks

### ISSUE THREAD

**Issue by XBTdev** [bitpay/copay#3039]
When sending large amounts denominated in bits it can get confusing making sure I have the right number of digits. I tap on "bits" to display the usd amount, then I click back to 'bits' to enter the btc amount.

This is a cumbersome ux. *The countervalue amount should be displayed at all times.* **Tapping the countervalue can still toggle which amount input currency is primary/secondary.**

## Current UX

![screenshot 2015-07-26 21 04 16](https://cloud.githubusercontent.com/assets/3032137/8898601/743224ee-33db-11e5-90e4-df135d1a6255.png)

## Better UX

![screenshot 2015-07-26 21 04 16 copy](https://cloud.githubusercontent.com/assets/3032137/8898567/e9df8b38-33da-11e5-96df-ac22e8b6526c.png)

This small fix could prevent some fat finger mistakes.

**Comment by matiu** [comment]
hmm, we have it that way before, but we switch to the current design,
because it was cleaner

On Mon, Jul 27, 2015 at 1:14 AM, XBTdev <notifications@github.com> wrote:

> When sending large amounts denominated in bits it can get confusing making
> sure I have the right number of digits. I tap on "bits" to display the usd
> amount, then I click back to 'bits' to enter the btc amount.
>
> This is a cumbersome ux. *The countervalue amount should be displayed at
> all times.* *Tapping the countervalue can still toggle which amount input
> currency is primary/secondary.*
>
> [image: screenshot 2015-07-26 21 04 16 copy]
> <https://cloud.githubusercontent.com/assets/3032137/8898567/e9df8b38-33da-11e5-96df-ac22e8b6526c.png>
>
> This small fix could prevent some fat finger mistakes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3039>.
>



-- 
BitPay.com

**Comment by XBTdev** [comment]
You could make it very clean and still display countervalue. At the very least, it needs to be displayed on the password prompt screen as a confirmation.

Imaging trying to send 93232334 bits and sending 932323234 instead. The USD value is never displayed so you could easily make such a mistake.

What do you think of displaying the amount (in BTC & USD) on the confirmation modal?

**Comment by matiu** [comment]
The confirmation modal is already implemented on the current version. Thanks!
