### ISSUE TITLE
Confirm Deleting wallet message does not translate.

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#3041]
Here is an example of Spanish. This only occurs on cordova based apps (iOS or Android).

![2015-07-19 16 51 41](https://cloud.githubusercontent.com/assets/237435/8906547/ec2cb6a2-3445-11e5-8993-2d4edaf8ddec.png)

related to #3034 (failed attempt to fix)

**Comment by cmgustavo** [comment]
closes #3046
