### ISSUE TITLE
bip44 support

### ISSUE THREAD

**Issue by XBTdev** [bitpay/copay#3055]
It would be awesome if we could create bip44 sub-accounts for wallets. That's the whole point of HD.... one backup for all your wallets/accounts. Its great to have the option, to create an entirely new wallet or a sub-account for your wallet.

![new sub account](https://cloud.githubusercontent.com/assets/3032137/8998579/576b906e-36e4-11e5-9b86-db8f9def9bc8.png)
![menu](https://cloud.githubusercontent.com/assets/3032137/8998581/5ae67984-36e4-11e5-90ab-b11bd45d8f02.png)

**Comment by dabura667** [comment]
BIP44 is not compatible with multisig.

**Comment by matiu** [comment]
dup: https://github.com/bitpay/copay/issues/2244

**Comment by matiu** [comment]
PS: Thanks for the UX suggestion, definitely a good idea!
