### ISSUE TITLE
could not join wallet [object: Object]

### ISSUE THREAD

**Issue by dan-da** [bitpay/copay#3056]
I created a 2 of 3 wallet on testnet.

With the same running instance of CoPay on same device I attempted to join the the wallet.   ( I'm not sure if that is supported or not, but I don't see why it shouldn't be. )

The join action failed with error messsage:  could not join wallet [object: Object]

which clearly should not be a user-facing message.

**Comment by dan-da** [comment]
btw, this is with copay 1.1.2.

**Comment by matiu** [comment]
Yes. This is not supported. We need to fix the err 
Message.

**Comment by dan-da** [comment]
I'm kind of curious why it is not supported.

The wallets are separate logical entities  ( and I assume also technically separate ).

It certainly makes testing various scenarios easier.

I can also think of at least 1 use non-testing case where it is useful.

So why not allow it?

**Comment by matiu** [comment]
dup https://github.com/bitpay/copay/issues/2812
