### ISSUE TITLE
PIN implementation

### ISSUE THREAD

**Issue by miguelmorales85** [bitpay/copay#3061]
It would be perfect to implement PIN security in mobile versions. PIN could also be requested to confirm transfers.

**Comment by Kirvx** [comment]
+1

**Comment by cmgustavo** [comment]
You can enable `Encripted Private Key` from Preferences. Whenever you perform (or sign) a transaction, you 'll have to enter a PIN.

<img width="523" alt="copay_-_multisignature_wallet" src="https://cloud.githubusercontent.com/assets/237435/9283056/2c7c2174-42a7-11e5-8dbd-96435404d4dc.png">

Is it your idea?

**Comment by beatles1** [comment]
Would be good to have the option between the password in the current implementation and a PIN (or graphical code like android unlock patterns?). Should also be more clear what this does in the settings.

**Comment by miguelmorales85** [comment]
@cmgustavo I mean what @beatles1 mentioned. An unlock PIN or Pattern requested when I open the app in android.

**Comment by matiu** [comment]
This feature is now covered by:  Finger print scanning (ios/android) and Password for spend (encrypting the private key).

**Comment by adaojunior** [comment]
@matiu I think the issue here is that some one could potentially see your funds and or transactions. I still think a pin is needed.

**Comment by JDonadio** [comment]
@adaojunior there is 2 levels of security available, fingerprint and spending password. You can turn on both at same time. Also there is a new feature on home view, tapping and holding your balance will hide/show it, so in your home (and send tab) your balance will not be displayed.

![image](https://cloud.githubusercontent.com/assets/13851807/16154298/8ac7c442-3480-11e6-82e4-ef66f05ab816.png)
![image](https://cloud.githubusercontent.com/assets/13851807/16154307/98fa0200-3480-11e6-8212-8c467022f1b2.png)

**Comment by miguelmorales85** [comment]
I'd like a PIN request to open the app.

**Comment by adaojunior** [comment]
I'm with @miguelmorales85, I know you can hide funds, but this is very different of what we are asking for.

![7172725_orig](https://cloud.githubusercontent.com/assets/4921294/16274364/b57b0bf0-387b-11e6-9dd6-68969958cb17.jpg)

**Comment by bitjson** [comment]
https://github.com/bitpay/copay/issues/4555

**Comment by miguelmorales85** [comment]
@bitjson will they close #4555 like they closed this?
