### ISSUE TITLE
Decimal separator localization WP8

### ISSUE THREAD

**Issue by mareksip** [bitpay/copay#3062]
Using WP8 in Czech environment would give me comma decimal separator "," in WP Cordova numerical keyboard - which is correct. Nevertheless, after entering the amount, the applications parses for dot decimal separator "." which makes me unable to click Send button. Needless to say that it is impossible to write dot separator on the defautl numerical keyboard.

Currently it is possible to overcome with clicking Send all which would create the decimal separator with '.' and then adjust the amount.

**Comment by matiu** [comment]
Thanks for the report. We will fixed ASAP.
