### ISSUE TITLE
Total amount in "History" should display only the total of the own addresses

### ISSUE THREAD

**Issue by cmgustavo** [bitpay/copay#3063]
To get this, just send some bits to your Copay wallet that return a change.

![copay_-_multisignature_wallet](https://cloud.githubusercontent.com/assets/237435/9094799/43d2a88a-3b8a-11e5-9b3a-15e598170bb0.png)

**Comment by greggzigler** [comment]
see https://github.com/bitpay/copay/pull/3064

**Comment by cmgustavo** [comment]
fixes #3064
