### ISSUE TITLE
Download CSV file not working.

### ISSUE THREAD

**Issue by dan-da** [bitpay/copay#3066]
When I click "Download CSV File" in History, it shows the "Generating CSV file..." animation for approx 5 seconds and then it goes away.   I am given no indication that the file was actually downloaded or a prompt to save it.

So far I have gotten the same results on:

Windows 7, Copay v1.1.2 download  ( Chrome app )
Ubuntu 14.04, Copay 1.1.2 (latest git), running in FireFox.  ( browsing to localhost:3000 )

On windows I looked (unsuccessfully) in:
  + Downloads folder.
  + My Documents folder
  + chrome downloads.

On Firefox I looked  (unsuccessfully) in:
  + ~/Desktop  ( why my downloads usually go )
  + Firefox downloads history.

Since this issue is not already reported, I imagine I may be the only one seeing it. Maybe something special about my wallet?

Please let me know if there is any additional info I can provide or logs to check etc to help diagnose the issue.

**Comment by dan-da** [comment]
I just tried again now on windows and this time the file dialog popped up and I was able to save the CSV file.   I haven't even restarted CoPay since I filed the bug a couple days ago.

I wonder if it may have been due to an error querying the server, and it simply gave up without reporting anything to the user.  If so, that still seems a (minor) bug.

**Comment by matiu** [comment]
Thanks for the update. Were you testing a testnet wallet?

**Comment by dan-da** [comment]
No, the wallet I tried to download the CSV file for is on mainnet.

I do have testnet wallets, and I just now tried with one of those and it also downloads fine now.

I also just tried again on firefox/linux (mainnet wallet) with a freshly opened wallet (new browser window) and it still fails.  But I guess that isn't really a supported configuration at present, so not too surprised.

**Comment by cmgustavo** [comment]
Hi @dan-da , thank you for reporting and help us to improve Copay.

Regarding your issue on Firefox, you are right, we are not supporting Firefox. The function to download a file to your computer is very different in almost all browsers and platforms.

With Copay ChromeApp, you can download the CSV file. But if your browser is configured to download automatically to some folder, you will not see anything, but the file will be in the selected folder.

I think we could show a message or something to notify that the file was already generated and downloaded.
