### ISSUE TITLE
Need a way to export master public/private keys.

### ISSUE THREAD

**Issue by dan-da** [bitpay/copay#3072]
I do not see any UI for this, other than the backups, but those are encrypted with a password.

Users may have many possible reasons they need access to these keys directly.  One may wish to move funds into another wallet software.   Also, the master public key is useful for watch-only ( auditing ) wallet purposes.   

I would be satisfied with any UI or documented manual process that enables me to see these keys directly.

Hopefully the functionality exists and I have just missed it?

**Comment by dabura667** [comment]
I made a rough tool that decrypts copay backups.

https://bip32jp.github.io/english/copay_decrypt.html

This can be downloaded and used offline. (Just be sure to download the entire site and not just the HTML file.)

**Comment by dan-da** [comment]
Hey thanks for this.  I tried it out and it works.  That's sufficient for my personal immediate needs.

It seems to me that the logical and very simple thing in the wallet software would be to add a checkbox "Encrypt backup" (default = yes) in the Advanced Options when creating a backup.  With some sort of warning about security risks of this.

This way regular users will have encrypted backups by default, but advanced users can override if they need to.

**Comment by matiu** [comment]
you can also use: https://bitwiseshiftleft.github.io/sjcl/demo/
which decrypt the wallet and gives you a json, with `xPrivKey`
