### ISSUE TITLE
Transaction sent yesterday still says Unconfirmed in History.

### ISSUE THREAD

**Issue by dan-da** [bitpay/copay#3073]
The transaction was sent yesterday from a 2 of 3 wallet.

I go to history and then click on the transaction, it says "Unconfirmed".   I click on Home, then back to history and the transaction still says unconfirmed.

I then click "See it on the BlockChain" and insight.bitpay.com displays the transaction with 196 confirmations.   A clear discrepancy.

Copay has not been restarted since the transaction was sent.  Also, I have not exited the wallet.  So it appears that for whatever reason, the wallet is not being refreshed automatically.

I next choose another wallet, then go back to the first wallet and view the same transaction.   Now it shows 196 confirmations.

This is with Copay version 1.1.2.

**Comment by dabura667** [comment]
Wallets update balance in specific points. (Like you said, when switching wallets, or tapping balance etc.)

I have never had any misunderstanding with the UI as is.

**Comment by dan-da** [comment]
Hi thanks for your comment.   I didn't know about the tapping balance.

I am a new user of Copay, having only discovered it a month or so ago.    As such, I am looking at it with fresh eyes (for better or worse).

My experience with other bitcoin wallets that I run on PC or android has pretty much universally been that they listen to the network and update in near real time.   So that is kind of a baseline expectation I have for wallets.   I can understand if that is difficult to achieve technically, but in that case my reduced expectation would be that each screen would have a refresh icon or link and at least would attempt to auto refresh (poll) every 5 minutes or so.  Seeing zero confirmations after 24 hours is discomforting.

Despite testing the wallet on several occasions for a few weeks now, I had no idea that I could click the balance to initiate a refresh.   That feature has low discoverability.  So the only method I found to do a refresh is switching wallets.    You mention "etc" implying other methods, but I have no idea what those are either.  Admittedly, I haven't gone hunting for them.

So I don't think this is a bug per se, but is a rough edge that could be smoothed for a more polished experience.

**Comment by matiu** [comment]
fixed by https://github.com/bitpay/copay/pull/3083 (newBlock notification)
