### ISSUE TITLE
bug: pasting a bitcoin address in the amount field results in an amount to appear

### ISSUE THREAD

**Issue by maraoz** [bitpay/copay#3074]
Chrome app, Linux. Steps to reproduce:

1. Create a testnet wallet.
2. go to Send tab
3. copy 'mqpXkm4GYND47R2WTv1xxFH7vXz8mGjCvn' and paste it into the amount field

RESULT: The number 4472178 appears on the field
EXPECTED: validation error / blank field

I don't think this is desired, let me know if I misunderstood something

**Comment by matiu** [comment]
Thanks for the report, Manu!

 I was not able to reproduce it. Which very are you using?

On Mon, Aug 10, 2015 at 5:30 PM, Manuel Aráoz <notifications@github.com>
wrote:

> Chrome app, Linux. Steps to reproduce:
>
>    1. Create a testnet wallet.
>    2. go to Send tab
>    3. copy 'mqpXkm4GYND47R2WTv1xxFH7vXz8mGjCvn' and paste it into the
>    amount field
>
> RESULT: The number 4472178 appears on the field
> EXPECTED: validation error / blank field
>
> I don't think this is desired, let me know if I misunderstood something
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3074>.
>



-- 
BitPay.com

**Comment by maraoz** [comment]
version v1.1.2.
Just reproduced again with a new wallet, pasting 'mqpXkm4GYND47R2WTv1xxFH7vXz8mGjCvn' in the amount field of a testnet wallet.

**Comment by matiu** [comment]
thanks, it was fixed recently, that is why I was not able to reproduce it.
sorry.

It will be ok in v1.1.3.

On Tue, Aug 11, 2015 at 12:29 PM, Manuel Aráoz <notifications@github.com>
wrote:

> version v1.1.2.
> Just reproduced again with a new wallet, pasting
> 'mqpXkm4GYND47R2WTv1xxFH7vXz8mGjCvn' in the amount field of a testnet
> wallet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3074#issuecomment-129930466>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by maraoz** [comment]
thanks!
