### ISSUE TITLE
Wallet balance and history available only on first load of Android App

### ISSUE THREAD

**Issue by tab00** [bitpay/copay#3080]
When switching to a different wallet, the error message "Could not update Wallet" appears with a button "TAP TO RETRY". After pressing the button, an "Updating wallet" progress bar appears for some seconds, then it's almost always back to the same "Could not update Wallet" error. Repeated presses almost never actually leads to the balance appearing.

Switching to any other wallets results in the same error.

If I exit the app and run it from the beginning by pressing the icon in Android, the app loads and balance (of the last wallet that I wanted to access) always appears.

Then switching to any other wallets results in the same error.

It has been like this since the last update.

**Comment by dan-da** [comment]
I have seen this also.

**Comment by tab00** [comment]
It appears to have been fixed. Thank you for fixing it if so.
