### ISSUE TITLE
Layout issue on big screens

### ISSUE THREAD

**Issue by isocolsky** [bitpay/copay#3088]
![image](https://cloud.githubusercontent.com/assets/2073468/9252457/d91d0348-41ae-11e5-99bb-35b554645c89.png)

**Comment by matiu** [comment]
related: (in big screens)
![copay_-_multisignature_wallet_and_copay_-_multisignature_wallet](https://cloud.githubusercontent.com/assets/98844/9252507/0f10c188-41af-11e5-93e8-c3094a95dd4f.png)
