### ISSUE TITLE
Funds locked in "Payment accepted... But not broadcasted. Try to send manually". Can't cancel or broadcast.

### ISSUE THREAD

**Issue by vadim0** [bitpay/copay#3096]
Shared wallet. Payment proposal created and signed by all (2-of-2) participants.

Now funds are locked in "Payment accepted... But not broadcasted. Try to send manually" screen.

Can't cancel or broadcast. "Could not broadcast payment. Check you connection and try again" (sic!)
<img width="398" alt="2015-08-15 11 56 49" src="https://cloud.githubusercontent.com/assets/6342922/9288236/04bd3e72-4345-11e5-9fc6-a49f36470a62.png">

**Comment by vadim0** [comment]
"Could not broadcast payment. Check you connection and try again" (sic!)

**Comment by vadim0** [comment]
"Could not broadcast payment. Check you connection and try again" (sic!)

**Comment by matiu** [comment]
Payments cannot broadcasted with one of the following 2 reasons:
 - There is a network problem connecting the wallet service
 - There is a problem with the payment itself (for example its inputs have been already spent)

The upcoming version of Copay (1.1.3) differentiates these 2 states and will give a more accurate error message. 

What platform are you using? If you are sure network is fine, so there is a problem with the payment you can delete it and start over.  The creator of the payment can delete it at any time. The other participants can delete it after 24 hrs it was created.

**Comment by vadim0** [comment]
Platform: iOS 9 Public Beta 3
1) network connection perfect - WiFi
2) transaction is ok - multiple inputs (≈15-20 unspent)
No way to drop the transaction or broadcast it. And funds locked. There is no delete option after all copayers signed.

**Comment by matiu** [comment]
If broadcast fail (which mean that bitcoind rejected the transaction), the payment proposal can be deleted with the restriction mentioned above. I was able to reproduce the state you are in. Please see the following screenshot (be sure to be using the latest Copay version available at the app store, to see the delete option).

<img width="519" alt="copay_-_multisignature_wallet" src="https://cloud.githubusercontent.com/assets/98844/9288684/70429b86-4329-11e5-9aff-9bae216032b9.png">

**Comment by vadim0** [comment]
I use the latest 1.1.2 version. I use 2-of-2 shared wallet. When both signed, there is no such option like 'Delete payment'. Screenshot above.

**Comment by matiu** [comment]
in the screenshot it says '13 hours ago' +8h since you write. you need to wait 24 hours or ask the creator to delete the TX. ( I am assuming you are using the public BWS instance, with enforce this ruleS)

**Comment by vadim0** [comment]
Yes, BWS. I am the creator of transaction. And there is no delete option. Will wait for 24 hours. But I guess nothing will change. Funds stuck.

**Comment by matiu** [comment]
Thanks for the update. I will try to reproduce it in a 2-2
Wallet. Please let us know if the button appear after the 24h.  

The other signer is a native desktop app?

**Comment by vadim0** [comment]
Yes, native Mac OS X app + iOS app. I control both devices.
For both: more than 24 hours passed. Funds stuck. Still can't broadcast or drop. No deletion option appeared.

How to drop? Restore from backup didn't drop the transaction.
<img width="398" alt="2015-08-15 21 19 06" src="https://cloud.githubusercontent.com/assets/6342922/9290229/57e97612-4393-11e5-929a-f3bf6b90e788.png">
<img width="399" alt="2015-08-15 21 19 21" src="https://cloud.githubusercontent.com/assets/6342922/9290230/59c77e70-4393-11e5-8e71-8baae9a88846.png">

**Comment by matiu** [comment]
We are sorry you are having this problem. The tx proposal is at the bws, so restoring the backup does not delete the tx. 

I can try to reproduce it later today and fix it and send you an update. If you need the funds urgently you can run your own bws (it is very easy to setup) and point your Copay there an hit "recreate wallet".

**Comment by vadim0** [comment]
I was trying to launch own BWS, didn't finish, but when I still tried to point it to absent localhost BWS (although there was no sign it was started and so it could not sync) - after pointing to original BitPay BWS 'delete payment proposal' option suddenly appeared.

**Comment by vadim0** [comment]
No, the issue pops up again. Smaller amount was sent successfully after drop. However the rest is stuck again. Resyncing to BWS doesn't get back delete option.

**Comment by matiu** [comment]
Copay encrypts the backup with the Stanford  JS Cryto Library. To extract the private key you can use https://bitwiseshiftleft.github.io/sjcl/demo/ , copy the backup to 'ciphertext' and enter your password. The resulting JSON will  have a key named: xPrivKey, that is the extended private key of your wallet.

I will try to reproduce the error with a 2-2 wallet and get back to you.  Maybe we can meet  to chat at https://gitter.im/bitpay/copay so we can give you more personalized assistance, what you think?

**Comment by vadim0** [comment]
Thank you. Sure I can give you all needed info. I want to ensure Copay is the best one, so we need to clean it up.

**Comment by matiu** [comment]
Thanks a lot  for your support. I will ping you when i am at gitter (my user is ematiu)

**Comment by vadim0** [comment]
I finally transferred out in 3 instances. It took 4 days). I figured out the following:
Copay has difficulties is broadcasting transaction with more than 10 inputs.
Delete option appears after ≈27+ hours after creation of proposal.

**Comment by matiu** [comment]
Thanks a lot for the update. 

It is very valuable the information about the number of inputs. We will test it  for Bitpay internal use we normally broadcast txs from Copay with many inputs but there could be a bug anyways somethere. 

Thanks.
