### ISSUE TITLE
Wallet icon with extra padding

### ISSUE THREAD

**Issue by cmgustavo** [bitpay/copay#3101]
![copay_-_multisignature_wallet](https://cloud.githubusercontent.com/assets/237435/9332362/aa9c83f0-459a-11e5-9a18-b7d97e621651.png)

**Comment by sironitomas** [comment]
Does this happen on every device?

**Comment by cmgustavo** [comment]
No, in published version it is ok. This issue appears only in my dev environment.

Maybe this is due that I did an installation from scratch (foundation css was updated or something else).

**Comment by sironitomas** [comment]
I don't think it's OK in the published version. It happened in my device ever since I got the latest version from Google play.

**Comment by cmgustavo** [comment]
So, it 's a Chrome issue, because on iOS is fine. 
Anyway it is already fixed on #3105. We will release a patch soon.

Thanks for confirm this problem.

**Comment by cmgustavo** [comment]
closes #3105

**Comment by sironitomas** [comment]
Thank you too!
