### ISSUE TITLE
OneName Support

### ISSUE THREAD

**Issue by xbtdev** [bitpay/copay#3106]
Do you think OneName integration would be a good feature for CoPay? RushWallet supports it. The privacy implications of using one public bitcoin address aren't the best, but the usability is a big plus. Would love to hear feedback on this idea.

**Comment by sironitomas** [comment]
This would be a great addition!

**Comment by Nogreedy** [comment]
+1

**Comment by shea256** [comment]
+1 Happy to help with this!
