### ISSUE TITLE
Email backup should be an attachment, not inline text

### ISSUE THREAD

**Issue by XBTdev** [bitpay/copay#3107]
Doesn't an attachment make more sense for email backups?

* File extensions identify the file and could associate it with copay 
* No issues with whitespace, broken line returns, or other copy-paste mistakes
* Less confusing for non-technical users
* Would allow for restore instructions to be inline (in the email body)
* Easier to novice users to 'download to a usb drive'

Honestly, I'd much rather have a BIP39 backup option... but these are my thoughts on email backup options.

**Comment by tab00** [comment]
I agree. The backup file should also be importable into the Chrome app version of Copay.

I recently tried to import a wallet backup from Android Copay app (copied the text and pasted into a new text file) into the Chrome app version and it failed.

Are backups from the Android app version incompatible with the Chrome app version?

**Comment by matiu** [comment]
backups from all platforms use the same format. Be sure you are copying it
correctly and the password is ok.

On Thu, Aug 20, 2015 at 9:50 AM, tab00 <notifications@github.com> wrote:

> I agree. The backup file should also be importable into the Chrome app
> version of Copay.
>
> I recently tried to import a wallet backup from Android Copay app (copied
> the text and pasted into a new text file) into the Chrome app version and
> it failed.
>
> Are backups from the Android app version incompatible with the Chrome app
> version?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3107#issuecomment-132997126>.
>



-- 
BitPay.com
