### ISSUE TITLE
Need a way to export addresses used in transactions.

### ISSUE THREAD

**Issue by dan-da** [bitpay/copay#3109]
The CSV history does not presently include addresses, and the issue I opened for that functionality was closed without adding them.

As such, I am opening this issue to request an alternate method of obtaining the list of addresses that:

1) have ever been used in a transaction.
2) presently have unspent outputs.

I view (1) as most important and (2) as nice-to-have.

At present, I would be satisfied if clear documentation is provided for how the user may manually obtain (1) and hopefully also (2).

This is important for accounting (cost-basis) purposes.

Before closing, please have a look at these tools I've developed that make use of (1)
- https://github.com/dan-da/bitprices
- http://mybitprices.info

I would like to add documentation for how CoPay users may obtain (1) and (2).

thanks.

**Comment by dan-da** [comment]
just a note that this is also useful for libratax, which has a "Bulk Add Addresses" feature in addition to CSV transaction import.

**Comment by JDonadio** [comment]
Already done in https://github.com/bitpay/copay/pull/5070

Maybe we can add the ability to export. Thoughts?

**Comment by JDonadio** [comment]
In the current version we have this feature complete.
