### ISSUE TITLE
Rename "Encrypt Private Key" in settings

### ISSUE THREAD

**Issue by isocolsky** [bitpay/copay#3113]
To something like "Request password to spend funds" or something along those lines. The current setting name is hard to understand for non-technical users.

**Comment by matiu** [comment]
<img width="372" alt="copay_-_multisignature_wallet" src="https://cloud.githubusercontent.com/assets/98844/9409892/c9d53d06-47f3-11e5-8396-b76c1fa94de2.png">

done in the mnemonic branch.
