### ISSUE TITLE
Add confirmation popup after send

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#3116]
and show the actual, total, transaction fee.

@Kirvx we are finally moving forward with this, it will be optional (it can be disabled in settings), and it will show the total transaction fee, before signing.

**Comment by Kirvx** [comment]
Ok cool :)

**Comment by KeyJockey** [comment]
...AND -- hopefully, guys? -- a little better ability for advanced user control over the actual fee amount value number? 

i.e. my https://github.com/bitpay/copay/issues/3111 issue, which is still pending... out here... out in the "real world"... where actual USERS are **using** Copay and *need* things like this *fixed*... to actually USE this wallet **effectively** (and not just "play around" with cool new features like the Glidera buy/sell thing, that's not even available to a huge chunk of the market anyway yet, etc...) :stuck_out_tongue_winking_eye:
