### ISSUE TITLE
support non compatible paypro urls

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#3117]
like 
bitcoin:?r=https://merchant.com/pay.php?h%3D2a8628fc2fbe

described at 
https://github.com/bitcoin/bips/blob/master/bip-0072.mediawiki

**Comment by pieterpoorthuis** [comment]
Note that Copay does support the non-backwards compatible paypro URL when scanning a QR-code.

The bug however shows when clicking a non-backwards compatible bitcoin: URI. The OS redirects the request to Copay, and Copay shows 'Bitcoin URI is NOT valid!'

**Comment by pieterpoorthuis** [comment]
When scanning a non-backwards compatible QR-code, Copay shows in red-text in the background 'non valid bitcoin code', but Copay does process the request correctly. Tested on Android.

![image](https://cloud.githubusercontent.com/assets/13945200/9442275/5cbbacfc-4a7b-11e5-9588-3a0e23a9d318.png)
