### ISSUE TITLE
Show complete address list including current balance per address

### ISSUE THREAD

**Issue by isocolsky** [bitpay/copay#3122]
Related to #3119

Extra fields could include:
* creation date/time
* creator name
* address type (main, change)
* current balance
* used/unused flag

Addresses should be fully validated on the client side.

**Comment by drewwells** [comment]
Did this feature get removed? I don't see a way to find a list of all addresses in the CoPay app

**Comment by nycaleksey** [comment]
Has this feature been disabled? I no longer see an option to see all addresses associated with the wallet.
