### ISSUE TITLE
Open Bitcoin Privacy Project:  aim for a high score.

### ISSUE THREAD

**Issue by dan-da** [bitpay/copay#3123]
CoPay would do well to achieve a top rating from the Open Bitcoin Privacy Project next year and going forward.  At least, that is a worthy goal to aspire to, similar to the "acid" tests from the early days of browser CSS compatibility efforts.   It would certainly raise CoPay's star amongst those who care about financial privacy, as many bitcoiner's do.

The questionnaire for wallet developers is here:
https://github.com/OpenBitcoinPrivacyProject/wallet-ratings/blob/master/2015-1/questionnaire.md

The project's homepage is here:
http://www.openbitcoinprivacyproject.org/

I am opening this high-level issue to put the privacy project on the CoPay dev team's radar.   

A serious effort would require going through the questionnaire and rating criteria, answering the questions, and opening individual issues for any areas where CoPay presently falls short.

**Comment by dan-da** [comment]
So this has been marked lowprio.  :(  It will be interesting to see if copay is included in the next PrivacyProject report, and how it scores.

**Comment by XBTdev** [comment]
**I would also like to see privacy get more attention from copay.** Bad privacy has a lot of implications... because the blockchain lasts forever. At the moment, strong privacy in bitcoin is quite difficult. Hopefully, sidechains and payment channels will be a long-term solution.

**Comment by dan-da** [comment]
Version 2 of the report was released today.

Copay is included and ranks 14th out of 20 wallets tested with a score of 37 out of 100.

Clearly there is room for improvement with regards to privacy.

Report is at:  
http://www.openbitcoinprivacyproject.org/2016/02/announcing-the-2nd-edition-of-our-bitcoin-wallet-privacy-rating-report/

Reddit thread here:
https://www.reddit.com/r/Bitcoin/comments/48akum/open_bitcoin_privacy_project_report_2_is_out/

From the report:

Copay is a multi-signature wallet produced by the payment processing
company, BitPay. Their multi-signature technology allows multiple
users to have partial control over the same funds on different devices.
In the Google Play store description for the app, Bitpay stated it could
be used for cases such as “saving for vacations or joint purchases with
friends,” “tracking family spending and allowances,” and “managing
business, club, or organization funds and expenses.”
The primary privacy defense that Copay utilizes is their HD address
architecture, which helps to avoid address reuse. Because of the use
of P2SH-style multisignature addresses, the number of cosigners
involved in each transaction is recorded in the blockchain, and all
cosigners can track each other’s activity with respect to the shared
wallet.

Some privacy defenses missing from Copay but commonly present
in other wallet clients include BIP-62 compliance to avoid client
fingerprinting, avoiding the querying of balance information for
separate accounts in the same request, protecting physical access
to wallet data with a PIN, and allowing users to review their telemetry
data before it is submitted to the company.

Advanced users can download the Copay server source code from
GitHub and run their own personal Copay server, rather than using the
company’s, to better protect their network traffic privacy.

**Comment by martindale** [comment]
+1 for making this a significantly higher priority.  For a consumer wallet, privacy should certainly be a leading priority (and so too should convenience and experience).

**Comment by dabura667** [comment]
> avoiding the querying of separate accounts in the same request

This is a moot point, as BWS stores each wallet's xpub keys, and the insight and BWS instances are both owned by Bitpay, so there's no practical reason to use separate requests.

**Comment by matiu** [comment]
Closing this issue because it is too generic. 

There are multiple specific privacy features that were requested and implemented since this one was created. Please feel free to open specific tickets related to this one.
