### ISSUE TITLE
Show FULL Bitcoin Value/Balance, Some Places...

### ISSUE THREAD

**Issue by KeyJockey** [bitpay/copay#3125]
I realize Copay is truncating or "rounding" the bitcoin values in order to help make the user interface more simple and clean, and generally this is a good idea for anywhere it's just a "displayed value" such as Main screen in the big colored box that shows current wallet balance.

Keeping this to .0000 four or five decimal places given BTC's current exchange rate of the 4th digit equal to just a couple cents is fine... no problem with that :smile: 

However, in other places it *really* should be showing the WHOLE, exact bitcoin value... for example on the SEND page at the top, where Available Balance is displayed.

![donthidebalance](https://cloud.githubusercontent.com/assets/13903392/9562409/cd3537a2-4e39-11e5-8233-d94e2e137214.png)

This is a small font and there's plenty of room for 8 decimal places here: THIS page is where the user will be entering his *actual* next transaction amount, so THIS is where we need to know *exactly* how much bitcoin is available, precise down to the last single satoshi!

I think these values probably ought to be exact in the transaction history page too... and maybe in other places in the wallet as well: anywhere the number isn't just "displayed for a quick look" at it, but rather where it really ought to be *precise*.

P.S. I know we can click See It On The Blockchain to get actual full value of current address balance but that's really annoying to have to do: Copay should have this precise *full* value number at least in ONE place in the wallet itself.

**Comment by KeyJockey** [comment]
Glad to see this marked Next Release Now... 

![amountclipped](https://cloud.githubusercontent.com/assets/13903392/10074368/7b89ab36-629d-11e5-8947-86f35cdc9356.jpg)

**Comment by Giszmo** [comment]
I support the request to have the actual value visible at least in some place. Also would suggest that if at all, it should round down and never up.

**Comment by dabura667** [comment]
Someone sent me a utxo with no trailing zeroes at all, all the way down to the satoshi.

it is rather annoying to not be able to see it / spend it.

Seeing the in progress removed + lowprio added, I am assuming this problem is more hairy than it seems?

Anyone care to shed some light? @isocolsky @matiu ?

**Comment by Derek701** [comment]
Please fix.

**Comment by matiu** [comment]
Agree to implement this on the detailed transaction view, at least.

**Comment by tab00** [comment]
I was going to make a new issue for this, as I need to see full values up to 8 decimal places for accounting purposes.

The only way I could get the exact wallet balance was to export all transactions to a CSV file and then sum in a spreadsheet. This would be inconvenient to do regularly. Please show the full amount in the interface.
