### ISSUE TITLE
Send all bitcoins in "Send tab" should lock the "Advanced options - Fee policy"

### ISSUE THREAD

**Issue by cmgustavo** [bitpay/copay#3128]
* If click on "Send all", `Fee policy for this transaction` should be read-only.

**Comment by sironitomas** [comment]
Not really. I think the amount to send should be the total amount minus the fee selected.

**Comment by dabura667** [comment]
I think it should change the send amount if the user changes the fee policy after clicking send all.

**Comment by isocolsky** [comment]
Closed in favor of #3222
