### ISSUE TITLE
Single-Address, Fixed Wallet?

### ISSUE THREAD

**Issue by KeyJockey** [bitpay/copay#3130]
I suppose this suggestion won't be very popular here given that Copay is intended to be multi-sig and actively discourages address re-use... BUT would it really be out of the question to include an option for creating or (better) IMPORTING and using a single-address bitcoin wallet?

Correct me if I'm wrong but there ARE still some appropriate use cases for single-address bitcoin "accounts", aren't there?  

Charity donations that want to be fully transparent, for example, or some types of shared fund wallets, publishing a single bitcoin address (even a vanity address) that doesn't change, so people can directly see funds flowing in and out, etc.

IMHO it'd be nice in Copay if we could have a *separate* wallet using ONE such address feature, just for those use cases where it's appropriate... just so that Copay can still be the One Best Wallet for everyone.

**Comment by matiu** [comment]
this will be fixed eventually by implementing: https://github.com/bitpay/copay/issues/3032 or similar.
