### ISSUE TITLE
Copayer already voted

### ISSUE THREAD

**Issue by isocolsky** [bitpay/copay#3135]
The following happened in a shared 2-of-2 wallet:
1) Copayer 1 creates txp
2) Copayer 2 accepts
3) Copay reports network error, shows 'Accept' 'Reject' buttons again
4) Copayer 2 accepts
5) Copay complaints with message 'copayer already voted'.

Refreshing the app fixed the issue.

**Comment by cmgustavo** [comment]
Fixes #3137
