### ISSUE TITLE
Copay logo disappears on the ChromeApp with the new directive

### ISSUE THREAD

**Issue by cmgustavo** [bitpay/copay#3140]
@troggy Do you have the same issue with coloredCoins? It works on node-webkit apps.

**Comment by troggy** [comment]
Yes, it's weird. ColoredCoins logo is displayed using CSS background property and it works fine. But, yes, Copay logo disappears

**Comment by troggy** [comment]
Alright, that's known issue: http://stackoverflow.com/questions/22754393/in-a-chrome-app-using-angularjs-can-i-use-the-ngsrc-directive-directly-for-inte

**Comment by troggy** [comment]
Please take a look at possible fix: #3141
