### ISSUE TITLE
Incorrect time of proposal

### ISSUE THREAD

**Issue by isocolsky** [bitpay/copay#3144]
This proposal was created by another copayer in a shared wallet:

![image](https://cloud.githubusercontent.com/assets/2073468/9702045/cbdd694e-5422-11e5-80dc-ede702c3f6df.png)

**Comment by matiu** [comment]
Livenet?

**Comment by isocolsky** [comment]
Yes

**Comment by isocolsky** [comment]
I don't think it matters what network is this on as this is just a proposal
