### ISSUE TITLE
[Suggestion] Rename Copay to 'Copay - Bitcoin Wallet' in all app store.

### ISSUE THREAD

**Issue by Kirvx** [bitpay/copay#3166]
For more visibility, because:

Andreas Schildbach's wallet **'Bitcoin Wallet'**
Coinbase **'Bitcoin Wallet - Coinbase'**
Mycelium **'Mycelium Bitcoin Wallet'**
breadwallet **'breadwallet - bitcoin wallet'**
BlockChain **'Bitcoin Wallet'**
Airbitz **'Bitcoin Wallet - Airbitz'**
Xapo **'Bitcoin Wallet & Vault'**
Circle **'Circle for Bitcoin'**
GreenAddress **'GreenBits Bitcoin Wallet'**
Ninki **'Ninki: The Bitcoin Wallet'**
Blocktrail **'Bitcoin Wallet - by Blocktrail'**

I think it's important to add 'Bitcoin Wallet' in the name of the app in all store.

**Comment by dabura667** [comment]
+1 sounds good.

**Comment by matiu** [comment]
Good idea, will do.

On Sun, Sep 13, 2015 at 12:17 PM, dabura667 <notifications@github.com>
wrote:

> +1 sounds good.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3166#issuecomment-139886588>.
>



-- 
BitPay.com

**Comment by dabura667** [comment]
Maybe similar to breadwallet we should put Copay first.

"Copay - Bitcoin Wallet"

**Comment by Kirvx** [comment]
I agree.

**Comment by wallclockbuilder** [comment]
:+1:
