### ISSUE TITLE
Android blank white screen

### ISSUE THREAD

**Issue by XBTdev** [bitpay/copay#3173]
I recommended copay to a friend who installed the app and used it to store his bitcoins. That was a few months ago. Today he went to open the app to use his bitcoins and it shows a blank white screen after the splash screen (found a similar bug mentioned, #1519). He was running an old version, so we updated Copay to the latest version and tried again, same bug.

So running the latest version of copay we just see a white blank screen after the splash screen.

He has a backup, but we are unable to restore the backup because the password he remembers isn't accepted when we try to import the backup.

Any help?

**Comment by matiu** [comment]
If this a 1-1 wallet?

Could he try to decrypt the backup using:
https://bitwiseshiftleft.github.io/sjcl/demo/ ?
(he should enter the backup text at Cyphertext and the password)




On Tue, Sep 15, 2015 at 4:33 PM, XBTdev <notifications@github.com> wrote:

> I recommended copay to a friend who installed the app and used it to store
> his bitcoins. That was 6 months ago. Today he went to open the app to use
> his bitcoins and it shows a blank white screen after the splash screen
> (found a similar bug mentioned, #1519
> <https://github.com/bitpay/copay/issues/1519>). He was running an old
> version, so we updated Copay to the latest version and tried again, same
> bug.
>
> He has a backup, but we are unable to restore the backup because the
> password he remembers isn't accepted when we try to import the backup.
>
> Any help?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3173>.
>



-- 
BitPay.com

**Comment by XBTdev** [comment]
yes

**Comment by matiu** [comment]
The decryption worked?

On Tue, Sep 15, 2015 at 4:43 PM, XBTdev <notifications@github.com> wrote:

> yes
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3173#issuecomment-140516006>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by XBTdev** [comment]
No. It says the password he remembers for his backup is incorrect.

**Comment by matiu** [comment]
You mean than using https://bitwiseshiftleft.github.io/sjcl/demo/ is says the password is incorrect, right?

No, i wont work on the Copay. 6 months ago Copay was Beta and the storage format has changed in version 0.10 (https://github.com/bitpay/copay/releases/tag/v0.10.0,  ~ 5 month ago)

**Comment by XBTdev** [comment]
This is the backup json format: {"iv":"redacted","v":1,"iter":10000,"ks":128,"ts":64,"mode":"ccm","adata":"","cipher":"aes","salt":"redacted","ct":"redacted"}

I can privately send you the entire backup json if you would like.

But it looks like his backup was made after your new backup format (0.10), right?

**Comment by XBTdev** [comment]
By the way, he is currently running Android 4.4.2 on an LG Volt.

**Comment by matiu** [comment]
yes, it seems to be 0.10.

It would be difficult to debug a blank screen. The only way to move forward
that I can think of is you to build the Android App yourself, and run it in
the phone, to see the logs.

```
make android-debug
```
on the Copay repo root, with the phone connected.

On Tue, Sep 15, 2015 at 5:00 PM, XBTdev <notifications@github.com> wrote:

> This is the backup json format:
> {"iv":"redacted","v":1,"iter":10000,"ks":128,"ts":64,"mode":"ccm","adata":"","cipher":"aes","salt":"redacted","ct":"redacted"}
>
> I can privately send you the entire backup json if you would like.
>
> But it looks like his backup was made after your new backup format (0.10),
> right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3173#issuecomment-140519919>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by XBTdev** [comment]
There isn't any way to extract the wallet data file from the device with a file explorer? I know you use the device id to salt the local file, but I could access that. The wallet on the device is not encrypted with a password so it seems like the only way to access it.

**Comment by XBTdev** [comment]
Can I safely clear the app cache (not app storage) and try again?

Have rebooted the phone, and done force stop already.

**Comment by XBTdev** [comment]
Took a look at the code...

If I had an APK that would dump the results of storage.get('profile') and var getUUID to the screen or to a file.... then I could install this apk, run it, and the only thing encrypting the data would be the UUID which I have.

Thoughts?

**Comment by XBTdev** [comment]
I'm checking with a file explorer app and /sdcard/Android/data/com.bitpay.copay/files/ appears to be empty. Is this where I should see a data file?

**Comment by matiu** [comment]
Hi, any news on this?

We use file storage, you can check the locations here:

https://github.com/apache/cordova-plugin-file/blob/master/README.md

Please note that we use File storage since:

commit cf557fe0182cd90730f024df96d05a7ead9d7f2d

Date:   Sat Apr 25 14:42:17 2015 -0300

Before that, Copay used localStorage.




On Tue, Sep 15, 2015 at 6:19 PM, XBTdev <notifications@github.com> wrote:

> I'm checking with a file explorer app and
> /sdcard/Android/data/com.bitpay.copay/files/ appears to be empty. Is this
> where I should see a data file?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3173#issuecomment-140548043>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by matiu** [comment]
Closed, no response. Please reopen if still active.

**Comment by joshafest** [comment]
Is it necessary to debug copay apk at first time either on device or on avd?.
i did 'make android-debug' command and it created apk successfully, but failed to get avd or any device(because i did not installed it)
i extracted apk and run it on android....
it stuck at white screen....
also decompiling it has some files missing as compare to standard one.

any help?

**Comment by gabrielbazan7** [comment]
Try this: cordova /build.sh ANDROID --clear, before make android-debug command

**Comment by joshafest** [comment]
yes worked   ....some libs was missing ...
