### ISSUE TITLE
[Suggestions] Thoughts on BIP39

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#3176]
I think:
1. If we want to allow copying to clipboard (not secure) we should make it one-click tappable to copy. (also, this way we can prevent Japanese users from copying 2 space phrase and pasting into some other app)
2. If we want to disallow copying to clipboard, we should make the text not selectable.

I think 2 is better.
Also, I think we should warn the user if they try to screenshot the phrase.

Thoughts?

**Comment by Kirvx** [comment]
> I think 2 is better.
Also, I think we should warn the user if they try to screenshot the phrase.

I agree for both.

**Comment by dabura667** [comment]
> Also, I think we should warn the user if they try to screenshot the phrase.

Can cordova know when Android / iPhone / WP takes screenshot???

Maybe it is impossible... idk...

**Comment by MuhammedZakir** [comment]
A search gives:

iOS - http://stackoverflow.com/a/18158483
Android - http://stackoverflow.com/a/9822607 and http://stackoverflow.com/a/14951594

I don't know if it still works. Anyway, its worth checking.

**Comment by dabura667** [comment]
Merged. phrases on livenet are not copyable.
