### ISSUE TITLE
[Suggestion] Change to app update text.

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#3192]
- Support for backup phrases (BIP39)
- Support for BIP44
- Support for non-multisig addresses for personal wallets (1-of-1)
- Advanced wallet details
- Minor bug fixes

Let me know if there are others.
Once we update, let me know when we text lock so I can send out a message to all translators.

**Comment by isocolsky** [comment]
* Ledger support for multisig wallets

**Comment by cmgustavo** [comment]
Thanks!
