### ISSUE TITLE
[Critical] Depending on environment, pbkdf2 is being passed UTF-16 for non-ASCII characters (should be UTF-8)

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#3215]
https://github.com/bitpay/bitcore-mnemonic/pull/37#issuecomment-142169708

I have found the pbkdf2 used in bitcore-mnemonic salt handling deviates from other libraries in python etc. when the salt is multi-byte.

I will report upstream... but this means that if a person in Copay sets a "password" to protect their mnemonic, and that password contains non-ASCII characters, they will not be able to restore in Copay, and any phrase generated and protected in Copay will only be recoverable in Copay.

If we can't find a solution, we should prevent non-ASCII passphrase for mnemonics.

**Comment by dabura667** [comment]
hmmm... nevermind, it seems all these tests check out ok when manually inputting them into Copay. So I don't think there is a problem with Copay...

It's driving me nuts haha

**Comment by matiu** [comment]
Thanks for testing this issue and for the heads up!

**Comment by dabura667** [comment]
https://github.com/bitpay/bitcore-mnemonic/pull/38

Here's what I found:

1. in some environments, non-ASCII text is stored as UTF-16. This is why the hashes were not matching the other values.
2. If I manually convert the codePoints to UTF-8 then the tests all work fine.
3. Copay, for some reason, already is storing the data as UTF-8, but when I ran some of the tests through Copay manually, they still worked fine even when using my patch (linked above)

The reason I am opening this issue:

I am worried that the inconsistency I experienced might have caused some people to generate incorrect seeds due to UTF-16. (as I do not have a Windows Phone, etc. I have only been able to check Chrome browser, Android and iPhone.)

```javascript
var phrase = "あいこくしん　あいこくしん　あいこくしん　あいこくしん　あいこくしん　あいこくしん　あいこくしん　あいこくしん　あいこくしん　あいこくしん　あいこくしん　あおぞら";
// With no passphrase, "1HcTQkR243Qz4rGY3AvAh4EkPQUvz2Ju6P" should be m/44'/0'/0'/0/0 The first address.
```

**Comment by cmgustavo** [comment]
Hi @dabura667 , 

We did a test with your phrase on Windows Phone and everything works well. The first address is, indeed, `1HcTQkR243Qz4rGY3AvAh4EkPQUvz2Ju6P`.

Let us know if you want we test another thing. Thanks!

**Comment by dabura667** [comment]
Ok, I think that Copay for all platforms is fine (for what reason, I don't know why... maybe nodejs crypto module was updated and the environment you used to build the Official apps already accommodates for it.)

Travis CI was failing consistently on node v0.10.40 while I was trying to fix the issue.

@cmgustavo what version of node did you use to build the official releases?

**Comment by cmgustavo** [comment]
I have v0.10.35. But this is not necessary to build Copay. 

For example, to build Copay for Windows Phone, we do `grunt and a few cordova commands` and it uses "browserified" libraries. Anyway, I don't think that the problem has to see with nodejs.

**Comment by matiu** [comment]
Closing this one now. We will update bitcore-mnemonics ASAP.
