### ISSUE TITLE
AirGapped Operation

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#3217]

**Comment by thephez** [comment]
With the recent demise of Coinkite, I've been looking for a way to duplicate the functionality they provided. Specifically HD multisig using an offline generated key and a hardware wallet for 2 of the 3 signers.  I saw some references to doing this using the bitcore wallet and may investigate that further.  It would be really nice to have the functionality right within Copay though.  
Thanks for the great product.

**Comment by matiu** [comment]
This is now supported on bitcore-client. I wont be implemented also in Copay on the near feature.
