### ISSUE TITLE
Create an external tool random to mnemonics (eg: could receive random numbers from a dice)

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#3219]

**Comment by bigvacancy** [comment]
+1 for allowing a custom seed to generate the mnemonic. The input field, if it needs a limit at all, should be long enough to allow for various methods of entropy generation, such as dice, coin flipping, etc. I would think at least 256 characters (one bit per character).

**Comment by matiu** [comment]
Currently it is possible to enter the mnemonic. there are several tools on the internet to create random mnemonic already.
