### ISSUE TITLE
The wording on the backup page is kind of awkward with multisig

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#3225]
. Makes it seem like I only need the backup phrase for 2 -2 wallet. Perhaps it should say:
To restore this 2-2 shared wallet you will need:
Your wallet seed and access to the server that coordinated the initial wallet creation. You still need 2-2 keys to spend.
OR the wallet seeds of ALL copayers in the wallet.
Also at the bottom it says: "Once you have copy your wallet seed" should be "Once you have copied your wallet seed down"

**Comment by dskloet** [comment]
For 2-of-2 it's the same, right?
But I agree they should make it clear that for an m-of-n wallet with m<n, you need access to n public keys. Not just m.

**Comment by MuhammedZakir** [comment]
> > For 2-of-2 it's the same, right?
Yes!

> > But I agree they should make it clear that for an m-of-n wallet with m<n, you need access to n public keys. Not just m.
I don't understand! If you have m-of-n multisig address, where m<n, you only need to have access to m public keys, not n! If m=n, you need to have access to n public keys. Either you are mistaken or you wrote incorrectly!

**Comment by dskloet** [comment]
I'm not mistaken. That's the whole point. You only need m (<n) **private** keys, but you need all n (>m) **public** keys in order to spend!

**Comment by matiu** [comment]
To recover funds from a m-n wallet, in general, you need m extended private keys, an n extended public keys. Each wallet address is generated with n public keys, even for a 1-6 wallet, so you need the extended public keys to recover the funds (by scanning the blockchain).

BWS stored the extended public keys, so, to recover a multisig m-n wallet you can:
 1- completely recreate the wallet with the N  mnemonics (using a new BWS)
 2- OR if you have access to the BWS where the wallet was created, use N mnemonics to access it and transfer funds (so will be using the M extended public keys stored on the server).

I hope it helps.

See  https://github.com/bitpay/copay/blob/master/backupRecovery.md
for more details.

**Comment by dskloet** [comment]
It's clear, but I think you swapped N and M in (2).

**Comment by MuhammedZakir** [comment]
> I'm not mistaken. That's the whole point. You only need m (m) public keys in order to spend!

You said n public keys, not m! That's where the mistake is!

> {...} for an m-of-n wallet with m<n, you need access to n public keys. Not just

**Comment by dskloet** [comment]
@MuhammedZakir please read my comment again. The part you quoted was messed up by the HTML parser. You do need n public keys. That's not a mistake.

**Comment by matiu** [comment]
> It's clear, but I think you swapped N and M in (2).

Thanks, fixed :+1:
