### ISSUE TITLE
iPhone 6 @ iOS9 is bugging out wildly

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#3232]
1. Loading the app takes minimum 6 seconds.
2. Creating a new personal wallet takes 10 seconds, a glitched out screen with tons of objects from various screens flashes, and a wallet appears in my list.
3. Buttons sometimes don't react.
4. Updating balance never happens, just blank screen, until I switch wallets them come back.

All other bitcoin apps seem to work fine since updating, but Copay has been not usable.

**Comment by matiu** [comment]
Thanks for the report, we will check it.

**Comment by bitjson** [comment]
Thanks for reporting and all your contributions! I'm having trouble reproducing the issues on iOS 9.0.1 (13A404). Could you check what version of iOS you're on?

Also, would you mind reviewing your `Session log` from Copay for errors? In the preferences menu, `About Copay` > `Session log` should bring up a full log of activity in Copay. (The log can contain extremely sensitive info, so best to only post the red error messages here.)

**Comment by Kirvx** [comment]
Almost the same problems with iPod Touch 5G 9.0.1:
In red:
```
[$rootScope:infdig] 10 $digest() iterations reached. Aborting! Watchers fired in the last 5 iterations: [] http://errors.angularjs.org/1.3.18/$rootScope/infdig?p0=10&p1=%5B%5D
```

**Comment by dabura667** [comment]
@bitjson I had 9.0.0 and am currently upgrading to 9.0.1 right now and see if problems persist.

9.0.0 wasn't pushed out as a notification, as my wife never knew it existed, so I think the damage is small... but just FYI 9.0.0 was having these problems.

I will report back when I tried on 9.0.1

**Comment by dabura667** [comment]
I went ahead and took a video of my experience as well as some of the logs.

https://www.youtube.com/watch?v=DYa4vhEKdzY

I will now upgrade to 9.0.1 and try again.

**Comment by dabura667** [comment]
Here's 9.0.1

https://www.youtube.com/watch?v=_DYIvSZf7Os

Changes:
1. startup is normal
2. wallet creation is normal
3. HOWEVER, wallet deletion creates similar problems to wallet creation on 9.0.0 and then it returns to the wallet deletion screen of the next wallet in the list. (deleting あ sent me to "Personal Wallet"'s delete screen.

The only red text in the logs is same as @Kirvx 

```
[$rootScope:infdig] 10 $digest() iterations reached. Aborting! Watchers fired in the last 5 iterations: [] http://errors.angularjs.org/1.3.18/$rootScope/infdig?p0=10&p1=%5B%5D
```

**Comment by matiu** [comment]
Thanks a lot. I was checking the issue now. It seems there is a problem with IOS9 and Angular, and can be fixed with: https://gist.github.com/IgorMinar/863acd413e3925bf282c

Still, Copay 1.2.5 works OK on my iPhone 6+, IOS 9.0.1...

We will be submitting an app with the fix soon.

**Comment by matiu** [comment]
Fixed in master.
