### ISSUE TITLE
Delete doesn't really delete wallet

### ISSUE THREAD

**Issue by dskloet** [bitpay/copay#3236]
I wanted to create a 2-of-2 wallet from my own seed but accidentally created a 1-of-1 wallet. So I deleted the 1-of-1 wallet and tried to make the 2-of-2 wallet from the same seed.

But Copay told me:
"Error creating wallet: Wallet already registered"

I don't understand why I couldn't use the same seed for different wallets but in any case, if I delete a wallet it should be gone.

This was with testnet.

**Comment by dskloet** [comment]
This was with the Chrome app.

**Comment by matiu** [comment]
Currently 'delete wallet' means 'delete from the device'

Deleting the meta data from the server is not trivial:
 
  - For nonmultisig wallets, the use could have multiple instances of the wallet, in many devices. Deleting the wallet would delete his (encrypted) transaction metadata (notes), which could be undesirable.  In 1-1 wallets  or (1-of-N) maybe this could be fixed with a  checkbox at delete:
          [ ] ALSO DELETE WALLET FROM THE WALLET SERVICE
  what you thinkg?

 - For multisig wallets, it is more complex, since we should implement some kind of voting mechanism for deletion...
          [ ] ALSO VOTE TO DELETE WALLET FROM THE WALLET SERVICE
  and once the quorum of copayers have vote for deletion...BWS can delete it. Make sense?

**Comment by dskloet** [comment]
That makes sense. Currently it keeps a permanent record of the user which seems wrong and is a violation of least user surprise.

And why can't I use my seed to create a 2-of-2 wallet? Have I permanently ruined that possibility when I accidentally created the 1-of-1 wallet? Why can't I use the same seed for both wallets?

**Comment by matiu** [comment]
> That makes sense. Currently it keeps a permanent record of the user which seems wrong and is a violation of least user surprise.

thanks, I have added: https://github.com/bitpay/bitcore-wallet-service/issues/369



> And why can't I use my seed to create a 2-of-2 wallet? Have I permanently ruined that possibility when I accidentally created the 1-of-1 wallet? Why can't I use the same seed for both wallets?

The seeds are also use to derive a 'copayerId' and copayerId map 1-1 to wallet. This will probably change in the future when we support the field 'account' in BIP44, so with one seed you can have multiple accounts.

**Comment by dskloet** [comment]
I don't see why I shouldn't be able to use the same seed (and account) in different wallets. I might even do that using different BWS servers. Should that mean I can never use those wallets on the same server?

Maybe multiple wallets could be stored under the same copayerId and they could all be imported when that seed in entered?

**Comment by dabura667** [comment]
Would be interesting if all wallets in the app had the same backup phrase and just used the accounts index of BIP44 to differentiate.

**Comment by matiu** [comment]
yeap... thats the plan eventually :)

On Sat, Sep 26, 2015 at 9:37 AM, dabura667 <notifications@github.com> wrote:

> Would be interesting if all wallets in the app had the same backup phrase
> and just used the accounts index of BIP44 to differentiate.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3236#issuecomment-143433379>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by XBTdev** [comment]
>>Would be interesting if all wallets in the app had the same backup phrase and just used the accounts index of BIP44 to differentiate.

> yeap... thats the plan eventually :)

Wow! Awesome! That is great to hear. I introduced issue #3055 suggesting this.... this would be my number 1 most important feature request. If I want to create a sub-account for some unique purpose its annoying having to track a separate backup and go through the trouble of making multiple cold storage copies.

I do think it is important that you could still create completely separate accounts. But for most purposes, I'd create a sub-account.

![5ae67984-36e4-11e5-90ab-b11bd45d8f02](https://cloud.githubusercontent.com/assets/3032137/10879316/30086a88-8108-11e5-95ed-5f1205d7c0b4.png)
![576b906e-36e4-11e5-9b86-db8f9def9bc8](https://cloud.githubusercontent.com/assets/3032137/10879319/356b2038-8108-11e5-9bd4-a0b5a467920c.png)

**Comment by spazolas** [comment]
I'm fucking pissed at the terms used on Bitcoin, it's darn frustrating, I lost my wallet cos I couldn't send money because a sending password was requested, I was asked to delete it and retrieve it with the 12 crappy words but nothing happened. Why make life so hard on your clients all in the name of security and not considering easier means  to retrieve what's lost. I'll never use copay again.

**Comment by dabura667** [comment]
If you have your 12 words, you did not lose your wallet. You can restore your wallet if you just calm down.

Do you have your 12 word recovery phrase?

**Comment by Newmassage** [comment]
Ich sehe das genau wie spazolas

Ich habe dieses dingsda copay installiert um zu testen. Nach der Wiederherstellung sind meine kontakte weg und ich habe eine neue BTC adresse ist das normal? Währe dort Bitcoins drauf gewesen währen sie jetzt auch weg. Entweder ihr macht eine richtige anleitung mit Erläuterung nach einer neu Installation oder lasst es. Ja ich bin ein anfänger in sachen BTC. AN ALLE ANFÄNGER VORSICHT EURE BTC's WERDEN WEG SEIN Dieses Wiederherstellen geht nicht würde es gehen währen auch meine kontakte noch da

I have installed this dingsda copay to test it. After the recovery my contacts are gone and I have a new BTC address is that normal? If there had been bitcoins on it, they would now also be gone. Either you either make a proper guide with an explanation after a new installation or leave it. Yeah, I'm a beginner at BTC. ALL BEGINNERS WARNING YOUR BTC' S WILL BE WAY THIS RETURN WOULD NOT BE possible while my contacts are still there.
