### ISSUE TITLE
Wallet address is not deterministic

### ISSUE THREAD

**Issue by dskloet** [bitpay/copay#3237]
I'm trying to verify my understanding of BIP45 be reproducing the same receiving address that Copay generates. But I can't even get Copay to reproduce the same address as itself. Every time I uninstall the Chrome app and install it again, importing the same seeds, I get a different receiving address.

This is with a 2-of-2 wallet on testnet.

**Comment by MuhammedZakir** [comment]
You won't see same addresses, but if you have some coins in any address, case might be different. I haven't checked it myself though!

**Comment by dskloet** [comment]
I have not made or received any transactions with this wallet.
Why won't I see the same address?

**Comment by matiu** [comment]
Addresses are deterministic.

Copay uses BIP44 since version 1.2.0.  Check settings -> advanced -> wallet info to see the path of each address. (on the desktop app you can download a CSV).

What is probably happening in your case is that you are deleting the wallet from the device, but the wallet at BWS is still there. When you import it (in the device) the indexes are increased.

You can use http://bitpay.github.io/copay-recovery/ or http://bitcore.io/playground
to derive or check addresses yourself.

Closing this now, but please ask any question you have about this in this thread.

**Comment by dskloet** [comment]
If the index is increased without any transactions being made, that's a bug, right?
How can I reopen the bug?

**Comment by matiu** [comment]
it's a feature! :)

We decided that new installations (which normally translate to new devices
in which the same wallet is installed) create a new address, so you dont
see the same address in 2 different devices (thus, helps avoid address re
usage)...make sense?

On Sat, Sep 26, 2015 at 7:08 AM, dskloet <notifications@github.com> wrote:

> If the index is increased without any transactions being made, that's a
> bug, right?
> How can I reopen the bug?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3237#issuecomment-143416888>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by dskloet** [comment]
But if you do it too many times, you get a large gap and you won't find your funds during recovery.

What could I do to get deterministic results? I've tried deleting the wallet from the app instead of deleting the app, but even that doesn't work (issue #3236).

**Comment by matiu** [comment]
On Sat, Sep 26, 2015 at 7:36 AM, dskloet <notifications@github.com> wrote:

> But if you do it too many times, you get a large gap and you won't find
> your funds during recovery.
>

That is correct. You would have to do it 20 times tough.


> What could I do to get deterministic results? I've tried deleting the
> wallet from the app instead of deleting the app, but even that doesn't work
> (issue #3236 <https://github.com/bitpay/copay/issues/3236>)
>
You can check you wallet addresses in settings -> advanced -> wallet info.

Or you could run you own instance of BWS and the create a wallet there to
reset the index to 0.



> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3237#issuecomment-143418294>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by dskloet** [comment]
> You can check you wallet addresses in settings -> advanced -> wallet info

Thanks! I found the problem. Copay uses m/0/0 while I'm using m/45'/0/0/0. Does Copay not use BIP45?

**Comment by matiu** [comment]
On Sat, Sep 26, 2015 at 7:46 AM, dskloet <notifications@github.com> wrote:

> You can check you wallet addresses in settings -> advanced -> wallet info
>
> Thanks! I found the problem. Copay uses m/0/0 while I'm using m/45'/0/0/0.
> Does Copay not use BIP45?
>

Copay uses BIP44 from wallet created after version 1.2.0, What you mention
`m/0/0` it is actually: `m/44'/0'/0/0` from the master priv key.




> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3237#issuecomment-143418735>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by dskloet** [comment]
> Copay uses BIP44 from wallet created after version 1.2.0

BIP44 has coin type and account where BIP45 has cosigner index.
Are you no longer using cosigner index, or do you use the number 44 while still using the BIP45 format?

> What you mention `m/0/0` it is actually: `m/44'/0'/0/0` from the master priv key.

That's pretty misleading. I think it would be better to display the true path or at least not use the "m/" format to avoid confusion.

On https://github.com/bitpay/copay it still says:

> The backup also contains the key publicKeyRing that holds the extended public keys of the Copayers. Using a tool like Bitcore PlayGround, and following BIP45 it is possible to generate all wallet address. Note that addresses generated at BWS use the 'shared cosigner index' (2147483647) so Copay address indexes look like: m/45'/2147483647/0/x for main addresses and m/45'/2147483647/1/y for change addresses, where x and y are integers starting from 0.

Is that out of date?

**Comment by matiu** [comment]
On Sat, Sep 26, 2015 at 7:56 AM, dskloet <notifications@github.com> wrote:

> Copay uses BIP44 from wallet created after version 1.2.0
>
> BIP44 has coin type and account where BIP45 has cosigner index. Are you no
> longer using cosigner index, or do you use the number 44 while still using
> the BIP45 format?
>

44' with BIP44 format. We are not longer use BIP45 format, the
cosigner_index was proven not to be useful in most case (the original idea
was to create addresses "offline" (with no copayer syncronization) but that
was never used, and there are other way to achieve the same with BIP44.
Since BIP44 is wildly adopted, we decided it was better to switch, and be
compatible with other wallets (even considering I am one of the BIP45
coauthors ;-))


> What you mention m/0/0 it is actually: m/44'/0'/0/0 from the master priv
> key.
>
> That's pretty misleading. I think it would be better to display the true
> path or at least not use the "m/" format to avoid confusion.
>
Make sense. we will display the full path.

https://github.com/bitpay/copay/issues/3238


> On https://github.com/bitpay/copay it still says:
>
> The backup also contains the key publicKeyRing that holds the extended
> public keys of the Copayers. Using a tool like Bitcore PlayGround, and
> following BIP45 it is possible to generate all wallet address. Note that
> addresses generated at BWS use the 'shared cosigner index' (2147483647)
> so Copay address indexes look like: m/45'/2147483647/0/x for main
> addresses and m/45'/2147483647/1/y for change addresses, where x and y
> are integers starting from 0.
>
> Is that out of date?
>

Thanks, I just update it.


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3237#issuecomment-143419005>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by dskloet** [comment]
Thanks. Now I was able to produce the same address. As always I forgot to use 1' for testnet.
Just to be clear. It's m/44'/0'/0'/0/x (or m/44'/1'/0'/0/x for testnet). You missed one level earlier when you wrote:

> `m/0/0` it is actually: `m/44'/0'/0/0` from the master priv key.
