### ISSUE TITLE
Display full derivation path in advanced -> wallet Info.

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#3238]

**Comment by dskloet** [comment]
It would also be good to mention that the extended public keys are taken at m/44'/0'/0'.

**Comment by dskloet** [comment]
@isocolsky what do you think about showing the partial path that the xpub keys are based on?

**Comment by isocolsky** [comment]
I'm ok with showing this for the current copayer xpub. I'm not sure we can confidently show the derivation path for other copayers' xpubs. They could be using a different account (in the BIP44 sense) or a different path altoghether (not likely if using Copay).

**Comment by isocolsky** [comment]
Makes me wonder, have we gone too far by showing the full path in addresses? We only have confirmation that the addresses are created applying the relative path to the xpubs.

**Comment by dskloet** [comment]
maybe it should say something like xpub/0/1
It just shouldn't say m/0/1 because that's misleading.

**Comment by isocolsky** [comment]
I like that solution.
