### ISSUE TITLE
btc locked by pending transactions

### ISSUE THREAD

**Issue by ryanshaww** [bitpay/copay#3241]
please solve the issue , as i cant be able to use my funds

thanks

**Comment by dabura667** [comment]
> please solve the issue , as i cant be able to use my funds

This is not an issue. When someone proposes to spend funds, you are not allowed to use them.

Everyone should agree on what to do with the funds before trying to send them somewhere else.

After a day or two you can delete transaction proposals that aren't yours. And ones that are yours, you can delete them as long as no one else has approved them.

**Comment by ryanshaww** [comment]
i have funds in my wallet , confirmed transaction , it never happens before , its been 4 days now , wallet is stuck ????

**Comment by ryanshaww** [comment]
all i am doing is trying to spend my own funds and getting this message of btc locked ?

**Comment by matiu** [comment]
Could you describe he issue with more detail? Is this a personal or shared wallet? What you mean the wallet is stuck? Please also provide info about the platform you are using.

**Comment by ryanshaww** [comment]
personal wallet , when i try to send btc , it says payment proposal created and then the message pops up " btc locked by pending transactions" and nothing happens then , 4 days now , i can be able to use my funds as well ??? smh

**Comment by ryanshaww** [comment]
https://insight.bitpay.com/tx/6747a954c9e8ed4dcdde6feb92e14f9ecccdbfa8d40560fa743fe0cfe612a9eb

**Comment by dabura667** [comment]
If you have an Android, and you made your Personal Wallet recently (in the past few days) then you can use your "backup phrase" (12 word phrase that Copay generated for you) in another app like Mycelium to recover it.

**Comment by dabura667** [comment]
Actually, Mycelium is on iPhone as well. So iPhone too.

Have you tried deleting the proposal?

**Comment by ryanshaww** [comment]
i have it on my laptop , i have delete proposal ,  i am all stucked

**Comment by ryanshaww** [comment]
copay in installed on my laptop and btc locked by pending transactions thats all it says , copay developers or official help ??????/ please solve this , jeez its been 4 days

**Comment by matiu** [comment]
hey,

I would love to help you but you need to describe better the issue.

1- what platform are you using? What operating system are you using on your laptop?
2- what you mean by " i have delete proposal". Can you create a payment proposal?
3- Cant you send a screenshot of you wallet? please hide the sensitive information?
4- Please be use you are using the latest version available: v1.2.5. You can see that on the side menu.

**Comment by ryanshaww** [comment]
![nn](https://cloud.githubusercontent.com/assets/14861019/10124255/5ad01b46-6540-11e5-8eef-8e3976c039c5.JPG)
1- i am using windows 7 ,,,,,, 2 - it says payment proposal created and then i have to delete it , as it does nothing , ,,,,,,,,,,,,,,3- pics attached ,,,,,,,,,,,,,4 - my version is 1.2.5

**Comment by matiu** [comment]
thanks for the information.

The wallet say 'not private key' That wallet has no privileges to spend from it. I must have imported the wallet on that device. Did you made the export your self? When creating the export there is an option 'do not include the privake key' that generates a 'read-only' backup, as the one you have.

Do you have access to the device that has the wallet with the private key?

**Comment by ryanshaww** [comment]
i reinstall windows, i did make the backup and restore wallet with it , its just blocking btc now after i received the incoming latest transaction , before that i did use same wallet normally

**Comment by matiu** [comment]
I am sorry, but your backup is wrong. You must have used the option "do not
include te private key"  in the "advanced options" when creating the
 backup.

Without the private key, it is impossible to sign transactions, and
therefore no funds can be moved. That feature is only for creating
"read-only" access of the wallet.

Please, unless you have an other backup, do not send more funds to that
wallet.

On Sun, Sep 27, 2015 at 5:48 PM, ryanshaww <notifications@github.com> wrote:

> i reinstall windows, i did make the backup and restore wallet with it ,
> its just blocking btc now after i received the incoming latest transaction
> , before that i did use same wallet normally
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3241#issuecomment-143594243>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by ryanshaww** [comment]
how can i recover private key , how can i access those funds now

**Comment by ryanshaww** [comment]
there has to be something

**Comment by matiu** [comment]
I am afraid there is not way to recover the key, unless you have a full backup. Please reopen the issue if you are able to access a full backup or the original app.
