### ISSUE TITLE
Displaying mnemonic seed in 3 rows of 4 words

### ISSUE THREAD

**Issue by JackScottie** [bitpay/copay#3251]
I think it would make copying down the mnemonic easier if the words were always displayed in 3 rows of 4 words.

**Comment by dabura667** [comment]
Would have to make the font small to allow for 4 of the longest word.

Making it harder to read.

NACK

**Comment by matiu** [comment]
I prefer in 2 rows also. We though about it for a while. One main concern is that it has the appearance of a "phrase", not a table of words, so the user cannot misinterpret order of the words.
