### ISSUE TITLE
PayPro: "Payment to" field is empty

### ISSUE THREAD

**Issue by cmgustavo** [bitpay/copay#3254]
![copay_-_multisignature_wallet](https://cloud.githubusercontent.com/assets/237435/10164085/e7ca2b38-668d-11e5-95c4-dff3f4985f94.png)

![copay_-_multisignature_wallet](https://cloud.githubusercontent.com/assets/237435/10164095/00c88666-668e-11e5-835b-6d836cc43f24.png)

**Comment by matiu** [comment]
bitcoin:1yXe2AMpXUFeh1Y29qh9PF7uojybgDeTY?amount=0.01&r=https%3A%2F%2Fbitpay.com%2Fi%2F4e7RnvVxQwCsb3sQyDKpfS

works. It must be a problem with test.bitpay.com
