### ISSUE TITLE
App freeze/crash when using modal views

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#3273]
Observed on iOS9 (others not tested).  Two different scenarios:

A.
1. Launch Copay
2. Tap wallet settings icon
3. Minimize app
4. Restore app
5. Wait a few seconds; app minimizes by itself - when brough back to foreground it restarts at splash screen

B.
1. Launch Copay
2. Open Add wallet view
3. Minimize app
4. Restore app
5. App is unresponsive; must kill and restart

**Comment by cmgustavo** [comment]
Hi @ajp8164 , I couldn't reproduce the issue in my device (with iOS 9.0.2 and Copay 1.2.5). Are you using this same version?

**Comment by ajp8164** [comment]
iOS 9.0.1 and Copay 1.2.6.

**Comment by ajp8164** [comment]
Verified to be broken as described using iOS 9.0.2 and Copay 1.2.6.

**Comment by matiu** [comment]
I was not able to reproduce A nor B using Copay 1.2.6, iOS 9.0.2, iPhone 6+

But I after trying many times case B) opening Preferences led to the view,
but no options was working, ie
I could scroll the view, but taping on any of the options or in Close did
not work. Minimizing and Restoring
did not fix it, I had to kill the app. Unluckily I was not able to
reproduce it again later.

Andy, are you using the app store version?




On Sun, Oct 4, 2015 at 11:37 PM, Andy Phillipson <notifications@github.com>
wrote:

> Verified to be broken as described using iOS 9.0.2 and Copay 1.2.6.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3273#issuecomment-145413647>.
>



-- 
BitPay.com

**Comment by ajp8164** [comment]
Yes.  Using version for App Store.

--
Andy Phillipson, Director of Engineering Services
Does your website accept cash?
https://bitpay.com

**Comment by cmgustavo** [comment]
I finally could reproduce this issue in both cases (A and B). 

Thanks for report.
