### ISSUE TITLE
Blurry Copay Logo

### ISSUE THREAD

**Issue by sironitomas** [bitpay/copay#3277]
![screenshot_2015-10-05-14-32-12-01](https://cloud.githubusercontent.com/assets/813178/10288562/f2d0953a-6b6f-11e5-8503-0a937cf1fd62.jpeg)

It needs to be updated to a higher DPI version.

**Comment by sironitomas** [comment]
Will you guys update?

**Comment by bechi** [comment]
I will fix that @sironitomas thanks for your feedback :)

**Comment by bechi** [comment]
do you have Android ?, which version?. @sironitomas

**Comment by sironitomas** [comment]
Yes. Android 5.1.1, Full HD screen. BTW, the icon also looks blurry.
