### ISSUE TITLE
Layout issue : Backup with encrypted private key

### ISSUE THREAD

**Issue by gabrielbazan7** [bitpay/copay#3286]
maybe the error should be show in the modal. Also, when cancel is clicked, should return to the last page, and do not show that error
![screen shot 2015-10-07 at 12 52 42 pm 2](https://cloud.githubusercontent.com/assets/10999037/10343255/597a5166-6cf3-11e5-81c8-7cf937414838.png)

**Comment by bechi** [comment]
I agree with you @gabrielbazan7
