### ISSUE TITLE
Configuration of self-signed and approved certificates

### ISSUE THREAD

**Issue by braydonf** [bitpay/copay#3302]
**Use case:**
Someone has setup a locally running BWS and is connecting via https from Copay however hasn't gone through the process of having a certificate signed by a CA. 

**Enhancement:**
Ability to make individual certificate approvals in the BWS settings for Copay.

**Comment by dabura667** [comment]
https://github.com/bitpay/bitcore-wallet-service/issues/215

Related.

**Comment by kleetus** [comment]
Specifically, it would be good for the self-signed cert to be whitelisted in Copay. One this works, #215 might also be resolved.
