### ISSUE TITLE
Trans Malleability Double-Spend "History" Issue

### ISSUE THREAD

**Issue by KeyJockey** [bitpay/copay#3304]
Copay is apparently having some trouble with the recent Transaction Malleability attack stuff.

Today I'm seeing a false "double spend" item in HISTORY that isn't going away.  It *was* intermittently disappearing, yesterday... I think (unless I imagined it LOL) but it now seems STUCK in my history.

Also the TIME stamp on it is completely wrong -- indicating a few minutes ago forever even though it was over a DAY ago... see screen capture: 

![doublespendhistory](https://cloud.githubusercontent.com/assets/13903392/10411541/7bb084d0-6f37-11e5-8312-bef414619f7f.png)

...I'm fairly sure the malleated transaction was the one there for 10.0 bitcoins but not entirely sure, and can't check it now since the transaction ID is invalid now, been removed.

Wallet BALANCE total and operation otherwise SEEMS to be A-OK so far, (knock on wood) but having errors in history obviously could present a problem & needs to be corrected... maybe allow users to somehow manually select and *delete* particular history items?  OR is all this coming from the "permanent record" of the blockchain and un-alterable...?

**Comment by matiu** [comment]
Thanks a lot for the detailed report. We have spotted the issue yesterday
and working on a solution. It needs to be implemented mainly on the backend
blockexporer service (insight).


On Sat, Oct 10, 2015 at 11:19 AM, KeyJockey <notifications@github.com>
wrote:

> Copay is apparently having some trouble with the recent Transaction
> Malleability attack stuff.
>
> Today I'm seeing a false "double spend" item in HISTORY that isn't going
> away. It *was* intermittently disappearing, yesterday... I think (unless
> I imagined it LOL) but it now seems STUCK in my history.
>
> Also the TIME stamp on it is completely wrong -- indicating a few minutes
> ago forever even though it was over a DAY ago... see screen capture:
>
> [image: doublespendhistory]
> <https://cloud.githubusercontent.com/assets/13903392/10411541/7bb084d0-6f37-11e5-8312-bef414619f7f.png>
>
> ...I'm fairly sure the malleated transaction was the one there for 10.0
> bitcoins but not entirely sure, and can't check it now since the
> transaction ID is invalid now, been removed.
>
> Wallet BALANCE total and operation otherwise SEEMS to be A-OK so far,
> (knock on wood) but having errors in history obviously could present a
> problem & needs to be corrected... maybe allow users to somehow manually
> select and *delete* particular history items? OR is all this coming from
> the "permanent record" of the blockchain and un-alterable...?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3304>.
>



-- 
BitPay.com

**Comment by matiu** [comment]
closed in favor of: https://github.com/bitpay/bitcore-wallet-service/issues/451
