### ISSUE TITLE
Get base address derivation path from BWC

### ISSUE THREAD

**Issue by isocolsky** [bitpay/copay#3317]
Instead of getting it from `profileService.getUtils()`.

**Comment by Giszmo** [comment]
Is there a pull request with this issue? Just finding my way around here. I guess you refer to [this function](https://github.com/bitpay/copay/blob/0c30dde7274f6e78418ee419aa6c34af5eb7d84a/src/js/services/profileService.js#L12) wrapping the other not being necessary?
