### ISSUE TITLE
Idea to improve "Request a specific amount"

### ISSUE THREAD

**Issue by cmgustavo** [bitpay/copay#3327]
* Improve UX on receive section (display two tabs for QR simple and QR with a specific amount)
* Make the "alternative amount" as default option in the input field.

**Comment by bechi** [comment]
![receive](https://cloud.githubusercontent.com/assets/1882599/11221631/e57ae3ee-8d44-11e5-8162-d08f92303004.jpg)
Like this?

**Comment by matiu** [comment]
https://youtu.be/Ju7OECKzS2I?t=75

**Comment by matiu** [comment]
The tabs names are confusing. Also, we need to see how the 'specific amount' tab will look like.

**Comment by bechi** [comment]
![receive](https://cloud.githubusercontent.com/assets/1882599/11428918/a57b5f3c-944f-11e5-8ef9-d4211cf77243.png)

**Comment by XBTdev** [comment]
Just for comparison, here is the equivalent screen in Airbitz. 

![screenshot_20151126-190057](https://cloud.githubusercontent.com/assets/3032137/11433324/6e5c4cde-9470-11e5-8051-c890294afe1c.png)

**Comment by bechi** [comment]
![address](https://cloud.githubusercontent.com/assets/1882599/12234874/c75e5bf4-b84e-11e5-9f63-0a88f2f25f6e.jpg)
This is the last version about this issue.
