### ISSUE TITLE
BIP44 "support" on the non-multisig accounts is confusing the users

### ISSUE THREAD

**Issue by Giszmo** [bitpay/copay#3346]
Copay does support Non-Multisig accounts and claims to use BIP44 there. Maybe [that](https://github.com/bitpay/copay) can be worded a bit clearer because it results in confusion with users that expect copay to be compatible with BIP44 wallets one of which cases I had the pleasure to [investigate](https://www.reddit.com/r/Bitcoin/comments/3q3u23/issue_with_mycelium_hd_wallet/) yesterday and today.

The user created transactions in copay that could not be found by Mycelium due to long gaps in the internal chain `m/44'/0'/0'/1/*`. I tried out copay and found another incompatibility with BIP44, namely that copay allows to "generate" new addresses without warning him that this is not compatible with BIP44. I tried this with the testnet `mom mom mom mom mom mom mom mom mom mom mom mom` account and after some transactions these addresses were used:

      m/44'/1'/0'/1/0 is mp9oRVbZutxX89kpDgT5ZT85F7A1RSbHba
      m/44'/1'/0'/1/1 is msiVMoPeZr6cejGVuV5zTkaxbQLbRDNskb  <---- address re-use
      m/44'/1'/0'/0/2 is mmuYv1FFSpSQoDdcQyKv3ADvHyfL2umvJS
      m/44'/1'/0'/0/3 is n2ooxjPCQ19f56ivrCBq93DM6a71TA89bc
      m/44'/1'/0'/0/33 is mfeNKdUaJFJkwvL4NiR3QSwdTXj5heEuJo
      m/44'/1'/0'/0/34 is mryJaZzde2zwPPT6rKWdyH56rCVb32quQH

While the change addresses had no gaps, one of them was re-used. This wallet would not be recoverable by a BIP44 wallet due to the look-ahead of 20 being exceeded. But of course the user will blame the other wallet. Therefore I'd like to ask you to fix this or clearly state that copay can only import a BIP44 wallet, although I'm not sure it can, due to secondary accounts not being supported in copay.

**Comment by matiu** [comment]
Thanks a lot for the detailed review.

We are implementing a warning message, as BIP44 recommends, so when the user tries to manually create an address generating a gap bigger that 20, it will not be allowed (https://github.com/bitpay/bitcore-wallet-service/issues/388) . That will be shipped in the next Copay release (1.5).

Regarding the change address reuse, we will investigate issue with the seed you have provided, not sure how can that happen.

**Comment by Giszmo** [comment]
Thanks for looking into this.

My test might have produced the address re-use by using both copay and mycelium to move money on own account. How that other user skipped addresses, I don't know. His wallet is xpub6CJCuUYePjM92GfznaE63bxheHnKbhYV7eQJJEmDkk4b4Jbq2H9YiCKvVgLkx3pd6jmGipBJ3TY3WCYYUSsZWjDuBsYM285YoYu8eLzFfhu and my analysis gives me this pattern:

                                $ cat /tmp/parsed.txt | grep 'address_'
				address_23 (0.00082536 BTC - Output)
				address_23 - (Spent) 0.00082536 BTC
				address_12 (0.01418825 BTC - Output)
				address_12 - (Spent) 0.01418825 BTC
				address_11 (0.00086926 BTC - Output)
				address_11 - (Spent) 0.00086926 BTC
				address_10 (0.03723858 BTC - Output)
				address_10 - (Spent) 0.03723858 BTC
				address_9 (0.073 BTC - Output)
				address_9 - (Spent) 0.073 BTC
				address_8 (0.05734916 BTC - Output)
				address_8 - (Spent) 0.05734916 BTC
				address_7 (0.05869695 BTC - Output)
				address_7 - (Spent) 0.05869695 BTC
				address_6 (0.05946932 BTC - Output)
				address_6 - (Spent) 0.05946932 BTC
				address_5 (0.06 BTC - Output)
				address_5 - (Spent) 0.06 BTC
				address_4 (0.72639229 BTC - Output)
				address_4 - (Spent) 0.72639229 BTC
				address_3 (0.05563049 BTC - Output)
				address_3 - (Spent) 0.05563049 BTC
				address_2 (0.00288775 BTC - Output)
				address_2 - (Spent) 0.00288775 BTC
				address_1 (0.10996 BTC - Output)
				address_0 (0.30603405 BTC - Output)
				address_1 - (Spent) 0.10996 BTC
				address_0 - (Spent) 0.30603405 BTC
                                $ cat /tmp/parsed.txt | grep 'change_'
				change__25 (0.01322999 BTC - Output)
				change__25 - (Spent) 0.01322999 BTC
				change__43 (0.01333601 BTC - Output)
				change__42 (0.01424431 BTC - Output)
				change__43 - (Spent) 0.01333601 BTC
				change__41 (0.01780732 BTC - Output)
				change__42 - (Spent) 0.01424431 BTC
				change__24 (0.02868943 BTC - Output)
				change__41 - (Spent) 0.01780732 BTC
				change__23 (0.03612572 BTC - Output)
				change__24 - (Spent) 0.02868943 BTC
				change__23 - (Spent) 0.03612572 BTC
				change__22 (0.0374426 BTC - Output)
				change__21 (0.06376156 BTC - Output)
				change__22 - (Spent) 0.0374426 BTC
				change__20 (0.06488624 BTC - Output)
				change__21 - (Spent) 0.06376156 BTC
				change__18 (0.00006931 BTC - Output)
				change__19 (0.06889596 BTC - Output)
				change__20 - (Spent) 0.06488624 BTC
				change__19 - (Spent) 0.06889596 BTC
				change__18 - (Spent) 0.00006931 BTC
				change__17 (0.00202226 BTC - Output)
				change__16 (0.01499926 BTC - Output)
				change__17 - (Spent) 0.00202226 BTC
				change__15 (0.01871721 BTC - Output)
				change__16 - (Spent) 0.01499926 BTC
				change__14 (0.02232252 BTC - Output)
				change__15 - (Spent) 0.01871721 BTC
				change__14 - (Spent) 0.02232252 BTC
				change__13 (0.17597465 BTC - Output)
				change__11 (0.07280172 BTC - Output)
				change__12 (0.18295893 BTC - Output)
				change__13 - (Spent) 0.17597465 BTC
				change__10 (0.23878942 BTC - Output)
				change__12 - (Spent) 0.18295893 BTC
				change__9 (0.07576107 BTC - Output)
				change__11 - (Spent) 0.07280172 BTC
				change__8 (0.24454761 BTC - Output)
				change__10 - (Spent) 0.23878942 BTC
				change__7 (0.07626107 BTC - Output)
				change__9 - (Spent) 0.07576107 BTC
				change__6 (0.25984761 BTC - Output)
				change__8 - (Spent) 0.24454761 BTC
				change__5 (0.08796107 BTC - Output)
				change__7 - (Spent) 0.07626107 BTC
				change__4 (0.26395659 BTC - Output)
				change__6 - (Spent) 0.25984761 BTC
				change__3 (0.09606 BTC - Output)
				change__5 - (Spent) 0.08796107 BTC
				change__2 (0.30143405 BTC - Output)
				change__4 - (Spent) 0.26395659 BTC
				change__1 (0.10846 BTC - Output)
				change__3 - (Spent) 0.09606 BTC
				change__0 (0.30453405 BTC - Output)
				change__2 - (Spent) 0.30143405 BTC
				change__1 - (Spent) 0.10846 BTC
				change__0 - (Spent) 0.30453405 BTC

He claims to only have used Mycelium and copay. I reviewed all the relevant code in Mycelium and I think I can rule out that Mycelium can use anything but the `last internal address with activity + 1` for change.

**Comment by dabura667** [comment]
"We scan just the external chains, because internal chains receive only coins that come from the associated external chains." - from BIP44

Change address use should be sequential, and not reuse addresses in order to be BIP44 compliant.

**Comment by matiu** [comment]
This is mitigated on current master:
- Scanning a wallet do not left gaps (it uses to leave gap with less than 20 slots)
- Generate new address is limited when there are already 20 empty slots.
