### ISSUE TITLE
White Screen after new installation 

### ISSUE THREAD

**Issue by schnerchi** [bitpay/copay#3348]
This happens on ubuntu 15.10 64bit and Mac OSX 10.11.1 :

Install Copay
Start Copay
Agree to the license 
-> White Screen

Killing copay and restarting it seems to fix it.

**Comment by cmgustavo** [comment]
Hi @schnerchi, this issue was fixed in the latest version (1.4.3) (https://github.com/bitpay/copay/releases/tag/v1.4.3). There was a problem reloading app.

Thanks for report!
