### ISSUE TITLE
Could not send payment: [object Object]  Copay desktop app windows

### ISSUE THREAD

**Issue by pennyfx** [bitpay/copay#3357]
![image](https://cloud.githubusercontent.com/assets/224857/10803363/0f1b7f54-7d7f-11e5-97c1-3c1d49d84973.png)

What is this error for?

**Comment by matiu** [comment]
What version of copay are you using?

**Comment by pennyfx** [comment]
v1.2.5  #12c04f7

**Comment by pennyfx** [comment]
Updated to 1.4 and it worked fine.  thx

**Comment by matiu** [comment]
thanks for the update.

On Wed, Oct 28, 2015 at 7:51 PM, Arron Schaar <notifications@github.com>
wrote:

> Closed #3357 <https://github.com/bitpay/copay/issues/3357>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3357#event-448655983>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!
