### ISSUE TITLE
Blurry Icon on Android

### ISSUE THREAD

**Issue by sironitomas** [bitpay/copay#3374]
Title says it. For a full HD screen, this is what the icon looks like, compared to others:

![screenshot_2015-10-30-11-57-42](https://cloud.githubusercontent.com/assets/813178/10849164/1a0b7df8-7efe-11e5-8d87-710536a6401d.png)

**Comment by sironitomas** [comment]
@bechi can you review this? The icon on the Play Store looks much cleaner and sharper than the app icon.

Thanks

**Comment by bechi** [comment]
Yes I can, I will fix it. Thanks for report :)

**Comment by bechi** [comment]
@sironitomas  I already sent the pull request with this fix. Do you check it later?. Thanks!

**Comment by sironitomas** [comment]
I can check it if you provide me with an android build. I've had problems to compile it myself.
