### ISSUE TITLE
Add setting to choose bitcoin exchange rate source (from a list of exchanges)

### ISSUE THREAD

**Issue by KeyJockey** [bitpay/copay#3382]
I can't figure out exactly where Copay is getting its current fiat-price value for bitcoin - doesn't seem to exactly correspond with any of the main index prices (like preev.com, bitcoinaverage, winkdex etc).

This is a problem when trading BTC person-to-person as the dollar-value a customer is using isn't always exactly the same dollar value as entered in Copay's SEND box: it is very convenient having the choice of switching between dollar value and bitcoin amount, but it would be very helpful too if Copay had an option to allow user-choice from a list of specific bitcoin price indexes.

**Comment by XBTdev** [comment]
+1

**Comment by isocolsky** [comment]
+1

**Comment by Jacobbubble** [comment]
+1

**Comment by KeyJockey** [comment]
In the meantime, until this is done (?) can the devs here explain exactly how Copay currently is calculating dollar value from wallet bitcoin balance?  It'd be helpful just as a reference to which index or whatever the number is coming from...

**Comment by matiu** [comment]
Copay currently uses Bitpay's API for exchange rates:

https://bitpay.com/bitcoin-exchange-rates

The rates are refreshed every hour or so.

Note that the rats are only meant as gross reference. Using it precisely will require a different approach (for example storing the exact rate for each transaction).

**Comment by Jacobbubble** [comment]
@matiu Can we add the option to choose what exchange the fiat value is pulled from? I realize that some exchanges are fiat specific like USD/BTC, EUR/BTC, MXN/BTC, but if it was pulled from a user selected exchange then it could be more in line with what the user's expectations are.

**Comment by matiu** [comment]
Sure you can. Just make sure you use a exchange rate API that provides
historical data. PR are always welcomed.
