### ISSUE TITLE
Add a "reset to default url" option if I have specified a custom Wallet Service url

### ISSUE THREAD

**Issue by gabegattis** [bitpay/copay#3383]
I previously pointed my Copay at my own BWS instance that I set up on my own machine. Tonight, I wanted to change the url to point back at the public BitPay-operated BWS server. The problem was that I did not know what the url was. I had to search through the Copay source code to find the url. (https://bws.bitpay.com/bws/api)

There should be a way to make this easier. Either we can include a reminder in the interface of what the original url was, or we have a button that says "reset to default" or something like that.

**Comment by matiu** [comment]
Dev workaround:

Enter "prod" and the bws url will setup to the default bitpay bws server. 

Enter "dev" for localhost.

**Comment by cmgustavo** [comment]
closes #3384
