### ISSUE TITLE
Apk file for copay

### ISSUE THREAD

**Issue by chek2fire** [bitpay/copay#3389]
Can i have the apk file for copay? I have a blackberry phone and i like to install copay there. The Blackberry os has compatibility with android apk files. 
Thank you

**Comment by martindale** [comment]
Related: #2465

**Comment by chek2fire** [comment]
i have try to create the apk file in ubuntu linux and i get this error message

make: *** No rule to make target 'android'.  Stop.

is that so hard to give me a ready apk file? I dont want to download it from third party sources

**Comment by matiu** [comment]
this will be distributed on the upcoming release (1.5). To create from source, you need to run `make androd-prod`.

**Comment by chek2fire** [comment]
thx for the answer i will try to compile it but i am looking forward for your apk realeas

**Comment by matiu** [comment]
JFYI, 1.5.2 is distribution includes a builded APT.
