### ISSUE TITLE
Funds stuck in a 2-2 multisig wallet.

### ISSUE THREAD

**Issue by ghost** [bitpay/copay#3391]
Good afternoon,

I have a 2 out of 2 multisig wallet with my girlfriend, sadly she had to reset her phone ( and apps ) and she did not make a backup.

I can get her private key out of the wallets Json but I'm kinda puzzled how to make it happen that I can "import" her info into another wallet and get the funds back.

Do you have any tool for this? Or at least some information how to get it back at least.

With kind regards,

Lars Timmerman

**Comment by matiu** [comment]
Hello,

To understand better the problem, could you confirm you have the extended
private key of the 2nd copayer? (that will be something like
`xprivXXXXXXXXXXXX`, right?
Do you have the mnemonic of the 2nd copayer? Or the complete JSON?

If you have the mnemonic or the complete JSON you can try our official
recovery tool: https://bitpay.github.io/copay-recovery/

On Wed, Nov 4, 2015 at 10:09 AM, flatvoet <notifications@github.com> wrote:

> Good afternoon,
>
> I have a 2 out of 2 multisig wallet with my girlfriend, sadly she had to
> reset her phone ( and apps ) and she did not make a backup.
>
> I can get her private key out of the wallets Json but I'm kinda puzzled
> how to make it happen that I can "import" her info into another wallet and
> get the funds back.
>
> Do you have any tool for this? Or at least some information how to get it
> back at least.
>
> With kind regards,
>
> Lars Timmerman
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3391>.
>



-- 
BitPay.com

**Comment by chriswilmer** [comment]
How does the recovery tool know which account # to try?

**Comment by matiu** [comment]
Closing this one,no response.

Regarding your question @chriswilmer, the recovery tool for now only supports account #0.
