### ISSUE TITLE
Password issue

### ISSUE THREAD

**Issue by PHoltzendorff** [bitpay/copay#3394]
I hope someone can help me out:

I downloaded the Copay app on my iphone
- I sent bitcoin to this newly created wallet which was no problem
- I never set up a password or key, and I was not asked to do so
- Now I cannot send or spend the bitcoin, because the app asks me to enter the password.... BUT I NEVER CREATED ONE. So what shall I do?

Thanks a lot!

**Comment by matiu** [comment]
Could it be possible that you or someone have set up a password? It is the
first report we have regarding this issue.

Do you have a backup? You can check deleting the wallet, and then importing
the backup.

On Thu, Nov 5, 2015 at 4:40 AM, PHoltzendorff <notifications@github.com>
wrote:

> I hope someone can help me out:
>
> I downloaded the Copay app on my iphone
>
>    - I sent bitcoin to this newly created wallet which was no problem
>    - I never set up a password or key, and I was not asked to do so
>    - Now I cannot send or spend the bitcoin, because the app asks me to
>    enter the password.... BUT I NEVER CREATED ONE. So what shall I do?
>
> Thanks a lot!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3394>.
>



-- 
BitPay.com

**Comment by PHoltzendorff** [comment]
Matiu, Thanks for your note. It is almost impossible. I cannot remember that I set one up and I tried all passwords I ever used.

In addition, I just set up a second Copay wallet and again was not asked to add a password anymore. That means I can again send bitcoin to this new wallet, but could then not access or send these bitcoins from this wallet - because it would ask me for a password. 

I now emailed myself a backup as you suggested, but have still no idea how I could access my funds without this password...

Anyone has any idea what to do?

**Comment by matiu** [comment]
By backup, I mean the wallet mnemonic (ie the 12 words). If you have that,
you can delete the wallet, and import it again and access your coins.

On Thu, Nov 5, 2015 at 6:16 PM, PHoltzendorff <notifications@github.com>
wrote:

> Matiu, Thanks for your note. It is almost impossible. I cannot remember
> that I set one up and I tried all passwords I ever used.
>
> In addition, I just set up a second Copay wallet and again was not asked
> to add a password anymore. That means I can again send bitcoin to this new
> wallet, but could then not access or send these bitcoins from this wallet -
> because it would ask me for a password.
>
> I now emailed myself a backup as you suggested, but have still no idea how
> I could access my funds without this password...
>
> Anyone has any idea what to do?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3394#issuecomment-154195380>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by PHoltzendorff** [comment]
I do not have it. Never received it for the Copay wallets....

**Comment by PHoltzendorff** [comment]
Any update or help possible?

**Comment by matiu** [comment]
The password is used to encrypt the private key. Unless you know the password or you have the backup words of your wallets, I am afraid it is not possible to access the funds in it.

**Comment by PHoltzendorff** [comment]
Hmmm...but how can it be possible to set up the wallet without the password or mnemonic, send bitcoins to it, but then be asked for a password to withdraw or send bitcoins to another wallet?

I don't understand because I was never asked to set up a password. Maybe it would help if you tell me how I can get a mnemonic or a password set up in the first place.

Thank you very much!

**Comment by dabura667** [comment]
I had something similar happen to me a while back.

It turned out that my son had no clue what he was doing and he accidentally set gibberish for my password. Luckily, that app also had mnemonic phrases for backup, so I was fine.

> how can it be possible to set up the wallet without the password or mnemonic, send bitcoins to it

It's only possible if you skip the warning message that says in BIG RED LETTERS "You have not written down your mnemonic, please do so before sending bitcoin to this wallet"

This warning message is shown when you tap the "receive" tab for the first time.

If you do not remember seeing this tab, then the only thing I can think of is someone accessed your device, skipped the warning message, then added a password. (Maybe a small child who has no idea what they're doing etc)

**Comment by bechi** [comment]
Hey @PHoltzendorff just to ilustrate what @dabura667  is saying, here are screenshot for the initial Copay flow: 
![copay-flow](https://cloud.githubusercontent.com/assets/1882599/11015985/37386652-8552-11e5-98b8-eca25fbedf42.png)

Thanks and if you have some questions just tell me

**Comment by PHoltzendorff** [comment]
Thank you all very much!

However, this does not work as I must have skipped the initial backup before receiving the first funds.  When I now try to back up, no mnemonic code os shown or accessible. Instead it gives me the below message. If I then follow that instruction, all I can do is sending a backup to myself with an email etc. 

But there is nowhere a password or mnemonic code to be seen... Any ideas how I can get to the mnemonic code or a password when it was not set up prior to receiving the first funds?

**Comment by PHoltzendorff** [comment]
Thank you all very much!

However, this does not work as I must have skipped the initial backup before receiving the first funds.  When I now try to back up, no mnemonic code os shown or accessible. Instead it gives me the below message. If I then follow that instruction, all I can do is sending a backup to myself with an email etc.

But there is nowhere a password or mnemonic code to be seen... Any ideas how I can get to the mnemonic code or a password when it was not set up prior to receiving the first funds?

**Comment by matiu** [comment]
If the wallet is password protected and you have no backup, it is not possible to access the funds. Once a password is set, both the private key and the mnemonics are encrypted, so the only way to get around that is to have the backup taken  before the password is set.

**Comment by PHoltzendorff** [comment]
Thank you, Matiu. The key problem though is that I never set a password. And Copay app does not require you to set one to set up a wallet....

**Comment by PHoltzendorff** [comment]
Hello everyone, this has still not been resolved and I really hope someone can help.

I never set up a password for my Copay wallet and then sent bitcoins to this wallet.

Now I cannot access my own funds because I am being asked for a password (that I never set up).

How can I get to my funds?

Thank you very much for your help!

**Comment by matiu** [comment]
We have not detected any problem on the password implementation. Unless you provide 
a step-by-step procedure to reproduce the problem, we had to assume that someone 
has set up a password in the wallet. As explained before, without the password it is impossible
to recover access to the funds.

**Comment by dabura667** [comment]
> How can I get to my funds?

If you have a password on it, you can not access your funds.

> I am being asked for a password (that I never set up).

I think someone must have opened Copay and set a password for you. (maybe a baby who didn't know what they were doing, or a person who wants to spite you)

This is one reason why you SHOULD set a password: Because if you don't set a password, anyone with physical access to your device can set a password FOR YOU and not tell you what it is.

**Comment by dabura667** [comment]
@PHoltzendorff If you want to give us your encrypted backup, we can try to brute force guess your password... but if it was a baby randomly pressing keys it might be difficult. No promises.

**Comment by PHoltzendorff** [comment]
Great. To which email address shall I send this?

**Comment by dabura667** [comment]
matsuringo667 (at) gmail (dot) com

No guarantees. But also send me an address to return the funds if I find your password.

**Comment by PHoltzendorff** [comment]
Matias,

This has never been solved. How can I get help regarding this?

Thanks so much,
Philipp

**Comment by matiu** [comment]
Please see my previous comments.

**Comment by Plies10** [comment]
Hello 
Am having problems importing my copay wallet 
I have entered my 12 word phrase and still no luck 
Why is that?

**Comment by josepatino15** [comment]
What do you do if you have your phone stolen (the device used to create the account) and the 12 word password is lost?

**Comment by JDonadio** [comment]
You have 3 hackup format:

* 12 words (recovery phrase)
* File/Text (exported format)
* QR code (exported format)

If you have not any of these backups you will not be able to access to your funds.

It's **strongly** recommended have your backup/s safe to avoid this situations.
