### ISSUE TITLE
Problem with a transaction (unconfirmed, keeps updating time, not found in block explorer)

### ISSUE THREAD

**Issue by sapounas** [bitpay/copay#3396]
I made a transaction, my bits are gone from wallet and now the transaction is stuck in history saying UNCONFIRMED with updated time and date (a few seconds ago, or the time when i start my wallet application). The money did not reach the other end.

see a screen shot
![image1](https://cloud.githubusercontent.com/assets/4091971/10970415/24db2534-83d7-11e5-85c3-7393ca3e6641.jpg)

using windows 8.1

Thanks in advance

**Comment by matiu** [comment]
The "Unconfirmed" state is normal after you have sent a transaction, until
it gets mined. Could you check again now if the transaction is already
confirmed?

On Thu, Nov 5, 2015 at 11:06 AM, sapounas <notifications@github.com> wrote:

> I made a transaction, my bits are gone from wallet and now the transaction
> is stuck in history saying UNCONFIRMED with updated time and date (a few
> seconds ago, or the time when i start my wallet application). The money did
> not reach the other end.
>
> see a screen shot
> [image: image1]
> <https://cloud.githubusercontent.com/assets/4091971/10970415/24db2534-83d7-11e5-85c3-7393ca3e6641.jpg>
>
> using windows 8.1
>
> Thanks in advance
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3396>.
>



-- 
BitPay.com

**Comment by sapounas** [comment]
It is unconfirmed still.

The point is that every time that i open my wallet, the transaction time is the current system time
It is unconfirmed about 3-4 days now

how can i cancel it?

**Comment by sapounas** [comment]
All OK guys
thank you

All transactions are confirmed now. Many thanks for quick reply
