### ISSUE TITLE
Enhace this page design

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#3405]
![copay_-_multisignature_wallet](https://cloud.githubusercontent.com/assets/98844/11001545/6a85a136-8486-11e5-9038-116c738f3b21.png)

**Comment by bechi** [comment]
should be a progress bar, what do you think ?, can we make this?

**Comment by matiu** [comment]
we dont know the total amount of TXs...

**Comment by bechi** [comment]
Like this?
![sync-history](https://cloud.githubusercontent.com/assets/1882599/11222438/27ad5342-8d49-11e5-9617-a565e2744b8f.jpg)

**Comment by matiu** [comment]
looks good

On Tue, Nov 17, 2015 at 4:35 PM, Juan Ignacio Sosa Lopez <
notifications@github.com> wrote:

> Like this?
> [image: sync-history]
> <https://cloud.githubusercontent.com/assets/1882599/11222438/27ad5342-8d49-11e5-9617-a565e2744b8f.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3405#issuecomment-157481377>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by matiu** [comment]
done.
