### ISSUE TITLE
Error on Nexus 6P

### ISSUE THREAD

**Issue by rmflagg** [bitpay/copay#3410]
I went to open the Copay app on my Nexus 6P and got the following error: "Could not decrypt storage: device ID mismatch" and then the app closes.  
Any idea as to what is going on and how to correct it?

**Comment by matiu** [comment]
Did you previously used Copay on that device? Did you changed or restored the device storage from other device?

**Comment by rmflagg** [comment]
I exported the wallet from another device and then imported it to the Nexus 6P.  It was working fine yesterday and today I got the error.

**Comment by rmflagg** [comment]
Any ideas as to the problem?

**Comment by matiu** [comment]
How do you imported the wallet to the new device?

Could you try import it again?

On Mon, Nov 9, 2015 at 7:14 PM, rmflagg <notifications@github.com> wrote:

> Any ideas as to the problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3410#issuecomment-155216003>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by rmflagg** [comment]
I can't import it again, the app just exits after the error message.  Could someone out there point to a how-to to joining a wallet?

**Comment by matiu** [comment]
Could you uninstall the app and install it again and then import it? Also you can install the backup on a desktop so you can access your funds again. (See copay.io for downloads).

**Comment by matiu** [comment]
Closing this one, please reopen if still an issue.  

Note that encryption using DeviceID was disabled in 1.5.2.
