### ISSUE TITLE
No way to send all coins from a wallet, some suggestions to fix fee and tx options

### ISSUE THREAD

**Issue by SuperHenkie** [bitpay/copay#3412]
Encountered some with Copay on Mac OS X version (not sure if this is the same on other platforms as well).
Wallet says: Available balance: 168000 bits.
Trying to send all 168000 bits to another wallet. 

I open advanced options, set fee policy to Economy. Click send, nothing happens. 
- First problem: error message turned out to appear at the top of the screen **which is not visible from here!**
- Second problem: the error message was: "Could not send payment: Insufficient funds for fee." How am I going to know how much I can actually spend?
- Third problem: the various fee options are unclear, there's no way telling how much fee is actually applied for a transaction.

Four suggestions:

1. If an error occurs when sending a payment, scroll up to the top so that the error is actually visible (which is not always the case, e.g. if the advanced options area is opened)
2. Along with the fee options, instead of just "Priority", "Normal" and "Economy", also explicitly specify how much bits these fees are.
3. At the top of the screen, besides the total available balance, also list the **spendable** balance (being the total balance minus the tx fee required to spend it).
4. At the part where you specify the transaction amount, have a button like 'All' or 'Max' or something, in order to spend *all* funds from a wallet (taking the tx fee into account).

**Comment by matiu** [comment]
Thanks for the report.

We will check the error message problem. there is also an oustanding issue
for fixed fees.

There should be a 'send all' button (screenshot from OSX below). Be sure
your are using the latest version.


[image: Inline image 1]

On Sun, Nov 8, 2015 at 6:37 PM, SuperHenkie <notifications@github.com>
wrote:

> Encountered some with Copay on Mac OS X version (not sure if this is the
> same on other platforms as well).
> Wallet says: Available balance: 168000 bits.
> Trying to send all 168000 bits to another wallet.
>
> I open advanced options, set fee policy to Economy. Click send, nothing
> happens.
>
>    - First problem: error message turned out to appear at the top of the
>    screen *which is not visible from here!*
>    - Second problem: the error message was: "Could not send payment:
>    Insufficient funds for fee." How am I going to know how much I can actually
>    spend?
>    - Third problem: the various fee options are unclear, there's no way
>    telling how much fee is actually applied for a transaction.
>
> Four suggestions:
>
>    1. If an error occurs when sending a payment, scroll up to the top so
>    that the error is actually visible (which is not always the case, e.g. if
>    the advanced options area is opened)
>    2. Along with the fee options, instead of just "Priority", "Normal"
>    and "Economy", also explicitly specify how much bits these fees are.
>    3. At the top of the screen, besides the total available balance, also
>    list the *spendable* balance (being the total balance minus the tx fee
>    required to spend it).
>    4. At the part where you specify the transaction amount, have a button
>    like 'All' or 'Max' or something, in order to spend *all* funds from a
>    wallet (taking the tx fee into account).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3412>.
>



-- 
BitPay.com

**Comment by SuperHenkie** [comment]
You're right about the 'Send All', thanks! I think I looked around with an empty wallet first, and then tried receiving + sending some funds.

Anyway the Send All seems to work fine. Consider item no.4 fixed :) And this sortof takes away the need for no.3 as well. Hopefully my suggestions in no.1 and 2 are of any help in further improving Copay. 

Love your work!

**Comment by matiu** [comment]
thanks!

no.2 is at https://github.com/bitpay/copay/issues/3111

we will check no. 1 and update this ticket.

**Comment by matiu** [comment]
Closing this in favor of:
https://github.com/bitpay/copay/issues/3535
and #3111
