### ISSUE TITLE
Balance/Transactions Not "Sticking"...!

### ISSUE THREAD

**Issue by KeyJockey** [bitpay/copay#3420]
Hey guys, something bizarre's going on today with Copay.

Wallet BALANCE and *transactions* are not "sticking" for some reason.  Refreshing page sometimes works but sometimes doesn't seem to pick up *all* information and I'm getting like OLD "total balance" number.

Is this something being done, starting today, to try and mitigate the transaction malleability problem?  Maybe has to do with I'm using OLDER versions of Copay (but, honestly, I'm seeing in even in the Chrome version on my WinXP laptop which IS up to date as far as I know...)

This is really bizarre and seriously looks BAD for any new users who may encounter it: if the wallet balance doesn't stay absolutely *CORRECT* at ALL times, nobody will ever trust *anything* about Copay.

Let me know what else I can do to try and pin this down for you....

**Comment by frenchfaso** [comment]
Same issue here with Copay 1.4.3 OSX64

**Comment by matiu** [comment]
Thanks for the report. We have a similar issue yesterday. It is not releated to malleability, but to the fact that we run multiple servers on the backend and it is possible they were out of sync. 

 @frenchfaso @KeyJockey could you confirm that the problem persist now?

thanks.

**Comment by frenchfaso** [comment]
@matiu balance and history seem stable now, thanks.

**Comment by matiu** [comment]
thanks, I will close the issue, we are monitoring the problem now.

Please if you see the issue again, reopen this. Also please inform if the difference is between confirmed or unconfirmed balance.

**Comment by KeyJockey** [comment]
Just saw this update... gotta run in a minute but will come back and test again & report back ASAP
