### ISSUE TITLE
Won't broadcast

### ISSUE THREAD

**Issue by Qaezel** [bitpay/copay#3421]
I have a whole wallet system failing to broadcast. Even the mobile app won't broadcast after signing.

**Comment by matiu** [comment]
Could you confirm the issue is still happening?  Are you using a custom BWS or the public one?

**Comment by Qaezel** [comment]
I made many transactions today without an issue from a 1-2 wallet. With that wallet I can remove the tx should it get stuck. We stopped using the the 3-4 wallet. It's the public one.

**Comment by matiu** [comment]
Thanks for the update.

We had a compatibility issue in the last days with certain Copay client versions, but it now fixes in BWS. Please reopen if you have any new problem.
