### ISSUE TITLE
Copay FirefoxOS build

### ISSUE THREAD

**Issue by frenchfaso** [bitpay/copay#3423]
Copay mobile apps are based on Cordova, which supports FirefoxOS.
How hard would it be to make a FirefoxOS build?

**Comment by matiu** [comment]
you should check that the cordova plugins we are using support Firefox OS https://github.com/bitpay/copay/blob/master/cordova/build.sh#L84

**Comment by frenchfaso** [comment]
Thanks, sadly most plugins don't, it's a pity.
