### ISSUE TITLE
Money Sending Problem

### ISSUE THREAD

**Issue by solayagim** [bitpay/copay#3430]
Is there a problem on your system? Trying to send payment to my friend, the payment starting to sign but never broadcast. Using version 1.3.1 on windows home premium 64 bit. My internet connection is great.

**Comment by matiu** [comment]
what message do you get when you try to broadcast the payment?

**Comment by matiu** [comment]
I think this is related to https://github.com/bitpay/copay/issues/3430

if should be fix now. Please reopen if you still having problems.
