### ISSUE TITLE
Enhance Send Tab design

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#3441]

**Comment by KeyJockey** [comment]
LOL maybe my eyes are just getting bad but it seems to me that the "Available Balance:" text at the top of the SEND tab page ought to be a little larger, just to be able to better see how much you can Send.

Address-book icon and issues were addressed in another posting, I think...

Also isn't immediately very clear that the little SQUARE [ . ] icon/text at the upper-right corner is the method of activating the CAMERA for scanning QR codes: that icon may be improved by being something like a camera pic or a little QR or something like that?

Isn't obvious at first glance either that the user can switch between BTC and USD value by tapping the text in the Amount box: something could be added there to show this is a toggle value?

Anyone have anything else?  That's all the UI stuff for the SEND tab I can think of... :smile:

**Comment by bechi** [comment]
This is the mockups:
![slice 2](https://cloud.githubusercontent.com/assets/1882599/11248202/9e8f5d06-8dfe-11e5-9963-41f5c05da9f7.png)

And this is the invision proyect:
https://invis.io/U84XHV0PS

**Comment by KeyJockey** [comment]
Looks good... but I'm also *still* hoping to see (soon?) an 'advanced user' control for manual miner fee editing too... https://github.com/bitpay/copay/issues/3111 

If/When this is available, I think it'd be helpful to have access to it "on the fly" directly from the SEND tab, as well as having a 'default' setting for it in the overall Settings control.  

Maybe just keep an "advanced" button at the BOTTOM of the Send tab screen for setting stuff like miner fee (and maybe for selecting a specific change address too?)

**Comment by bechi** [comment]
I agree, I will do that :+1:

**Comment by matiu** [comment]
the backend is not ready to support that.

On Thu, Nov 19, 2015 at 11:48 AM, Juan Ignacio Sosa Lopez <
notifications@github.com> wrote:

> I agree, I will do that [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3441#issuecomment-158078046>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!
