### ISSUE TITLE
IDEA: show the backup words alternative in a QR, so it is easy to transfer a wallet from one mobile device to other.

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#3453]

**Comment by XBTdev** [comment]
+1

**Comment by dabura667** [comment]
hmmm......................

Definitely only generate QR code of seed if it is encrypted with a strong password...

Having a huge QR code for anyone (or security camera) to see with plaintext phrase encoded is dangerous...

+1 (with condition that it is required to be encrypted)

**Comment by matiu** [comment]
Closed in favor of https://github.com/bitpay/copay/issues/4320
