### ISSUE TITLE
Add wallet setting: callback url / webhook

### ISSUE THREAD

**Issue by xbtdev** [bitpay/copay#3458]
Wouldn't it be awesome if I could feed bitcoin transaction information from copay wallets into a webhook callback?

The app could store this URL on the BWS server and the server could perform the callback directly.

Would be awesome for third party integrations.... Slack, IFTTT, Zapier, etc.

**Comment by matiu** [comment]
Nice idea!

**Comment by BGalliotti** [comment]
Hello @xbtdev 
Thanks for reaching out to us.

There are no plans to prioritize this feature, while it could be nice for some usages. We are open to receive pull requests for this one.

Kind regards.
