### ISSUE TITLE
Wallet lost after update to Apple IOS 9.0

### ISSUE THREAD

**Issue by darkfrx** [bitpay/copay#3459]
After the update to the latest version of Apple Ios 9.x i lost by wallet.

In the past i had created a backup which i email to my personal mail account.
I tried to restore the text file that i received from an encrypted wallet backup that i did on July 18, with no luck at all.
I am sure of the password, as well as the backup file which is a text file with {text inside}.

Can you help me recover my wallet or its lost in space ?

Thanks anyway i hope for a positive answer.

**Comment by matiu** [comment]
Do you remember from when it was the version of Copay you had installed? Was it beta (before 1.0)?

Could you try to decrypt the backup at https://bitwiseshiftleft.github.io/sjcl/demo/
(please see https://github.com/bitpay/copay#copay-backups-and-recovery) ?

Finally is it a 1-1 wallet?

**Comment by darkfrx** [comment]
I think it was 0.9 or something i' am not sure.

What is the 1-1 wallet?

**Comment by matiu** [comment]
I mean if it was a personal wallet, or a multisignature wallet.

**Comment by darkfrx** [comment]
Sorry.
It was a personal wallet.

**Comment by matiu** [comment]
no problem. Could you try to decrypt the backup at

https://bitwiseshiftleft.github.io/sjcl/demo/ ?

(fill password and copy the backup at 'ciphertext')

On Fri, Nov 13, 2015 at 7:26 PM, darkfrx <notifications@github.com> wrote:

> Sorry.
> It was a personal wallet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3459#issuecomment-156576226>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by darkfrx** [comment]
with {..} on i get an error

**Comment by matiu** [comment]
what error?

On Fri, Nov 13, 2015 at 7:52 PM, darkfrx <notifications@github.com> wrote:

> with {..} on i get an error
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3459#issuecomment-156581536>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by darkfrx** [comment]
"Can't decrypt: CORRUPT: ccm: tag doesn't match"

**Comment by matiu** [comment]
I am afraid that means wrong password. Could you double check?

On Fri, Nov 13, 2015 at 7:55 PM, darkfrx <notifications@github.com> wrote:

> "Can't decrypt: CORRUPT: ccm: tag doesn't match"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3459#issuecomment-156582007>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by darkfrx** [comment]
And here comes the fun part.
I use an app on my iphone to save the passwords.
So i 've always copied the password and pasted in order to pay something using my wallet.

So the password has to be correct.
I don't know the backup file if is corrupted or not.

**Comment by matiu** [comment]
Note that the password of the backup is not necessary the same of the password for sending funds. You will still need that password to send funds, but the backup password is the one you entered when you created the backup and it is not needed for sending from from Copay.

**Comment by darkfrx** [comment]
dudE!!
You are a hero.
That's why i could' t decrypt it!

Thank you very much for your help!

**Comment by matiu** [comment]
Great to hear!

I recommend you migrate your coins to a new Copay wallet. Newer wallets can be backed up with 12 words, which are much easier to store securely (than a file).

**Comment by darkfrx** [comment]
Could you give me a guide, or write the steps required to do that?

**Comment by matiu** [comment]
Sure, just go to the side menu on the left -> Create Wallet.

Once you have the new wallet, go to receive, backup the wallet (write down the 12 words), and then transfer the funds from the old wallet to the new one.

If you are planning to store a significant amount of Bitcoin, consider to create a multisignature wallet, storing, for example, one key on your cel, and one key on your PC. To do that you need to go to Create Wallet and then select the 'shared wallet', and choose 2 required keys, 2 total keys.
