### ISSUE TITLE
Used receiving address shown after importing an existing wallet

### ISSUE THREAD

**Issue by sipak** [bitpay/copay#3460]
After importing existing account from Trezor via Create new wallet and going to Receive tab, there is receiving address 1 shown even if 10 first addresses are already used. I tried reloading history, restarting wallet, it didn't help. After generating new address, the first empty (11) is skipped and address 12 is shown.

**Comment by matiu** [comment]
Thanks for the report. We were able to reproduce it. It is related to a local address cache, we will fix it asap.

**Comment by matiu** [comment]
this should be fixed in >=1.7
