### ISSUE TITLE
Weird behaviour of send proposal in personal wallet

### ISSUE THREAD

**Issue by sipak** [bitpay/copay#3461]
In personal wallet, after interrupting singing process with Trezor, it is not possible to try again by clicking on Send again (coins are already locked) but the proposal in not shown automatically. It is not also shown in the wallet home until the app is restarted.

There are two way how to way how to discard it: Reject + Delete proposal. For personal wallet, there should be just one.

**Comment by matiu** [comment]
Fixed by https://waffle.io/bitpay/copay/cards/5647a56dd7d883030026c28f
