### ISSUE TITLE
Windows Phone 8.1 installation error

### ISSUE THREAD

**Issue by frenchfaso** [bitpay/copay#3462]
I wasn't able to install the latest update from the Windows Store a couple of days ago, also tried uninstall, reboot, reinstall but got this same error:
Error 8103012e
The phone is a Lumia 620 with Windows Phone 8.1 (8.10.14219.341)

**Comment by matiu** [comment]
This does not seems to be directly related to Copay, please check:

http://lumia520.blogspot.com.ar/2014/11/8103012e-error.html

http://answers.microsoft.com/en-us/mobiledevices/forum/mdlumia-mdapps/error-code-8103012e/326543ae-6e6b-4093-8f85-979d1f4f746a

http://answers.microsoft.com/en-us/mobiledevices/forum/mdlumia-mdapps/8103012ewhat-can-i-do/96d9d59d-e200-41b9-8f0e-420a52d9dcd7?auth=1

**Comment by cmgustavo** [comment]
Hi @frenchfaso , 

Please, try to install Copay in the internal memory (not SD). We thought that slow SD memories might fail with the DeviceId plugin.

Let us know how it goes.

**Comment by matiu** [comment]
@frenchfaso after reviewing the issue further,  in the latest version of Copay available on the WP store disabled the possibility of installing in SD card. We suppose you had it installed  on SD, and probably trying to upgrade generate this issue.

We will revert this change, so it is possible to install (and upgrade) on SD. We are updating the WP version now. Thanks for the report.

**Comment by frenchfaso** [comment]
@matiu @cmgustavo this was exactly the problem, changing default install location to internal memory solved it.
Thanks!
