### ISSUE TITLE
Server response could not be verified when creating address 

### ISSUE THREAD

**Issue by mmitech** [bitpay/copay#3467]
I am getting "Could not create address: Server response could not be verified" when I click on generate new address or when I go to receive.

I have both bws and copay installed localy.

**Comment by matiu** [comment]
What versions of  BWS and Copay are you using? Also check the database if
you have some old transaction proposal.

On Mon, Nov 16, 2015 at 6:53 AM, Mourad Ilyes Mlik <notifications@github.com
> wrote:

> I am getting "Could not create address: Server response could not be
> verified" when I click on generate new address or when I go to receive.
>
> I have both bws and copay installed localy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3467>.
>



-- 
BitPay.com

**Comment by mmitech** [comment]
I am using latest versions for both bws and copy.

**Comment by mmitech** [comment]
BTW, when I go to preference => advanced => wallet information I can see a valid generated addresses and when I send funds I can see the balance changing and I can see the transactions history, I can't however send transactions because I get address "not valid".

I am using this for an alt, I only changed networks.js in the bitcore-lib in bitcore-wallet-service...

**Comment by matiu** [comment]
You should check the output of 

https://github.com/bitpay/bitcore-wallet-client/blob/master/lib/verifier.js#L122
and
https://github.com/bitpay/bitcore-wallet-service/blob/master/lib/server.js#L1224

and check that they match.

Please note do not provide support to alt coins, so I am closing this ticket.

**Comment by mmitech** [comment]
I understand, thank you.
