### ISSUE TITLE
Fiat value in history tab

### ISSUE THREAD

**Issue by Chris869218** [bitpay/copay#3488]
I love Copay and it has become my main wallet. However, the one thing I miss about other wallets is having fiat values in the transaction history tab. Best would be an approximate value at time of past transaction, but the approximate current fiat value would work as well. I find myself constantly having to do mental math in the history tab to figure out how much I sent someone, or what a specific transaction was for. Any chance this could be included in the future? Thanks!

**Comment by matiu** [comment]
It was present at Copay v0.9 (using historic exchange rates!).

+1 for adding it back again.

On Thu, Nov 19, 2015 at 1:01 AM, Chris869218 <notifications@github.com>
wrote:

> I love Copay and it has become my main wallet. However, the one thing I
> miss about other wallets is having fiat values in the transaction history
> tab. Best would be an approximate value at time of past transaction, but
> the approximate current fiat value would work as well. I find myself
> constantly having to do mental math in the history tab to figure out how
> much I sent someone, or what a specific transaction was for. Any chance
> this could be included in the future? Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3488>.
>



-- 
BitPay.com

**Comment by XBTdev** [comment]
+1 for adding it back again

**Comment by caveman1973** [comment]
+1

Clicking on the transaction could change from actual fiat to past fiat exchange rate.

If only one option possible, the exchange at the transaction day would be better. Knowing I paid 0.5 btc for an 10usd gift card is depressing if I see a $200 next to it.

**Comment by matiu** [comment]
Related https://github.com/bitpay/copay/issues/2961

**Comment by isocolsky** [comment]
Reopening as the current solution is not great IMHO. It should default to the historic amount in fiat and clicking on it could show how much 1 BTC was worth on that date (I think this is the current behavior).
