### ISSUE TITLE
Question regarding receiving bitcoins to my wallet

### ISSUE THREAD

**Issue by treplr** [bitpay/copay#3518]
Hi,

I got a quick question. If I'm receiving bitcoins to my desktop/software wallet that I installet. Where are the bitcoins stored during the transaction? Like, if I'm offline with my computer, and I send bitcoins to my address, where will they be stored until i log on to the internet?

I'm new to bitcoins so this might be a basic question.

Thank you!

**Comment by matiu** [comment]
When someone send you bitcoin, he broadcast a valid transaction to the bitcoin network. That transaction is eventually mined and written on the blockchain. When you log to your Copay wallet and check your balance, you are just querying the blockchain for the balance of the address in your wallet (not "downloading" the bitcoins). So, been online or offline does not make a difference in where the 'bitcoins are'. The transaction that transfer the bitcoins to your is at the blockchain.

Hope this answer helps to clarifies it. :)

**Comment by dan-da** [comment]
and to add to @matiu's answer.  Physically, the blockchain database is stored in separate identical copies on computers all around the world distributed in peer to peer fashion.  Anyone who is running a bitcoind full node (or btcd, etc) has a copy.  So the worldwide bitcoin network acts as a virtual server that both you and your friend can connect to at different times.
