### ISSUE TITLE
Two bugs: Specifying seed disables Testnet and auto-deletes seed.

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#3520]
Reproduce:

1. Create new wallet personal wallet
2. Activate Testnet button
3. Select "specify seed" and notice Testnet button disappears.
4. Type in phrase never used on BWS before.
5. Wallet is created as mainnet wallet.
6. Wallet backup screen says that "this wallet has no seed"

Verified this bug on iPhone 1.5.1 and Android 1.5.2.

**Comment by dabura667** [comment]
Expected result:

1. Can specify seed for Testnet wallet.
2. Specified seed generated wallets retain their seed until the user explicitly deletes it.

**Comment by matiu** [comment]
> Can specify seed for Testnet wallet.

Since recovering a testnet wallet from seed is a very special use case, we moved to the derivation path:

Instead of using:
  m/44'/0'/0'

modify it to:
  m/44'/1'/0'

the `1` means testnet bitcoins, as specified in BIP44.

> Specified seed generated wallets retain their seed until the user explicitly deletes it.
We were not sure about this. Since the user already have a 'backup' of the wallet it seemed correct not to
store the mnemonics.

**Comment by dabura667** [comment]
> modify it to: m/44'/1'/0'

This is non-intuitive. I assumed the testnet value would be retained because I assumed the button disappearing was a bug.

I would assume that entering the above would generate a mainnet wallet using the testnet derivation path. If I would assume that it would automatically change, then I would need to assume that your wallet supports all altcoins by entering the coin path. No one will assume that.

You should add "Enter m/44'/1'/0' for Testnet" next to the title of derivation path box.

> Deleting seed automatically

This is also non-intuitive. It should have a notice saying "specified seed will not be saved in the wallet."

Every other wallet saves the seed no matter what, so someone could lose their phrase because of this. (Copying directly from another app then deeting the original app etc.)

**Comment by dabura667** [comment]
> Testnet with specified seed

Also, doing it with the current method locks Testnet wallets into m/44'/1'/... Paths.

tbh Testnet wallets will be more likely to want to enter weird paths... So I think the button is better imo.

> Testnet unlikely to recover from phrase

The only Testnet wallet before Copay for mobile is Mycelium, which only backs up using BIP39 phrase.

I was trying to move my testnet wallet from mycelium and was going to delete Mycelium Testnet, luckily I caught myself.

**Comment by matiu** [comment]
I spawned the ticket: 
 https://github.com/bitpay/copay/issues/3534
regarding keeping the mnemonic

thanks

**Comment by matiu** [comment]
#3534 is fixed in Copay 2.0.

Closing this one, and adding https://github.com/bitpay/copay/issues/4315 regarding the testnet switch
