### ISSUE TITLE
advanced setting: change gap limit

### ISSUE THREAD

**Issue by XBTdev** [bitpay/copay#3521]
I would like to be able to use a CoPay xpub with [BC.i's api receive v2](https://blockchain.info/api/api_receive). This will power a bitcoin web-app and it will generate a new deposit address for each user, potentially creating a few thousand addresses.

It would be great if there was an advanced option to change the gap limit.

Electrum has a similar advanced option:
>wallet.storage.put('gap_limit',1000)

**Comment by dabura667** [comment]
I would recommend Mycelium Gear over Blockchain.info. Blockchain.info's API is always down and not responding, so we moved all our services away from them a long time ago.

Just a forewarning, code whatever it is you're making under the assumption that your query to BC.i will timeout.

As for Copay gap limit, currently the gap limit just tells Copay to not generate addresses over the gap limit, however Copay will only actively scan addresses that BWS generated.

This issue would require a "full path rescan" function.

**Comment by matiu** [comment]
"full path rescan" is currently available at Settings > Advanced > Wallet info.

The GAP at BWS was bumped to 40.

In the copay-recovery-tool the gap is configurable.
