### ISSUE TITLE
Offline duplicate alerts

### ISSUE THREAD

**Issue by XBTdev** [bitpay/copay#3522]
* When you open copay without a network connection it displays a pop-up alert. When you click "OK" you're greeted with the same message a 2nd time.
* Maybe a red banner with refresh/retry icon or a toast notification would be better suited for network errors.
* Can we display the last known balance? Right now without a connection their is no way to see the last known balance. Maybe "Last known balance 1,000 bits. Network error. Unable to refresh. Tap to try again."

![screenshot 2015-11-24 at 3 03 29 pm](https://cloud.githubusercontent.com/assets/3032137/11383495/5e681e84-92bd-11e5-8408-181c7c4b136f.png)

![screenshot 2015-11-24 at 3 03 40 pm](https://cloud.githubusercontent.com/assets/3032137/11383494/5e679a22-92bd-11e5-9b7f-37bd9c79534d.png)

**Comment by matiu** [comment]
ACK, good catch.

Also, displaying last known balance make sense, specially know that we have
a TX history cache.

On Tue, Nov 24, 2015 at 8:16 PM, XBTdev <notifications@github.com> wrote:

>
>    - When you open copay without a network connection it displays a
>    pop-up alert. When you click "OK" you're greeted with the same message a
>    2nd time.
>    - Maybe a red banner with refresh/retry icon or a toast notification
>    would be better suited for network errors.
>    - Can we display the last known balance? Right now without a
>    connection their is no way to see the last known balance. Maybe "Last known
>    balance 1,000 bits. Network error. Unable to refresh. Tap to try again."
>
> [image: screenshot 2015-11-24 at 3 03 29 pm]
> <https://cloud.githubusercontent.com/assets/3032137/11383495/5e681e84-92bd-11e5-8408-181c7c4b136f.png>
>
> [image: screenshot 2015-11-24 at 3 03 40 pm]
> <https://cloud.githubusercontent.com/assets/3032137/11383494/5e679a22-92bd-11e5-9b7f-37bd9c79534d.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3522>.
>



-- 
BitPay.com

**Comment by dabura667** [comment]
Also ACK. Sometimes in bad reception areas I want to remember how much Bitcoin I have on me.

**Comment by matiu** [comment]
this one should be fixed already. thanks.
