### ISSUE TITLE
Importing an incomplete wallet from trezor does not show the invitation code.

### ISSUE THREAD

**Issue by schnerchi** [bitpay/copay#3526]
I found an issue with trezor and importing wallets. I can recreate the issue with the following steps : 

1. Create a 2 of 2 wallet with the first signer as a trezor hardware wallet.
2. Let not join the second signer but instead delete the wallet.
3. Choose Import Wallet->Hardware Wallet and Import the trezor xpub keys again.

After doing that, you should see the screen to join the imported wallet for the second signer... This does not happen.
 
Mac OS X 10.11.1
Chrome Version 46.0.2490.86 (64-bit) 
Copay 1.5.2

**Comment by matiu** [comment]
thanks for the detailed report.

After 3, what screen you see? The wallet home? (as the wallet was completed?)

**Comment by schnerchi** [comment]
No, it is not the wallet home. It is seams to be the screen with the QR Code and the string for the second signer, but no QR Code ist show und "it says" : "Loading.....". But even after a couple of minutes nothing happened.

**Comment by matiu** [comment]
Can you see invitation the code? (the string) Maybe it is just a problem
with the QR code.

On Thu, Nov 26, 2015 at 5:58 AM, schnerchi <notifications@github.com> wrote:

> No, it is not the wallet home. It is seams to be the screen with the QR
> Code and the string for the second signer, but no QR Code ist show und "it
> says" : "Loading.....". But even after a couple of minutes nothing happened.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3526#issuecomment-159851440>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by schnerchi** [comment]
No... it does not show the invitation code. I can make a screenshot when I am back home tomorrow if you like.

**Comment by matiu** [comment]
yes, please, that will be helpful.

**Comment by schnerchi** [comment]
![bildschirmfoto 2015-11-27 um 08 53 21](https://cloud.githubusercontent.com/assets/7231994/11436391/902f4130-94e4-11e5-8a3c-f2f7e6a2aa82.png)

**Comment by schnerchi** [comment]
this shows up after importing the keys from the trezor....

**Comment by matiu** [comment]
Thanks for the follow up. I think I find the problem here: The invitation code is not deterministic and if the wallet is deleted, it cannot be restored. Given this is a very special case, and the wallet was never completed, so it cannot have associated address or funds, I think the situation should be handle with a appropriate error message, OR,   deleting the wallet on BWS when the use 'cancels' BUT only if he is the creator of the wallet.


I will edit the title to better reflect problem.

**Comment by schnerchi** [comment]
Ok, that makes sense. I think the wallet should be deleted on the BWS. Right now it is not possible to create a new wallet with the same trezor. See screenshot.... This error appears after trying to create a new wallet with the same trezor.

![bildschirmfoto 2015-11-30 um 08 17 39](https://cloud.githubusercontent.com/assets/7231994/11465654/dd98d104-973a-11e5-947e-939474538af8.png)

**Comment by matiu** [comment]
We should probably enhance the message in case this happen, to inform the use the invitation code is not present.
