### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by AB8520** [bitpay/copay#3530]
Good morning, I have problems with my wallet copay, when removing a multifirm account gives me error Connection with the server and does not let me remove the bitcoin. if I could help please

**Comment by matiu** [comment]
Could you provide more information about the issue: Platform / Copay version / Screenshot of the error.

Also, I dont completely understand that is the problem. Are you trying to remove a wallet? When exactly the error occurs?

thanks!

**Comment by AB8520** [comment]
Good evening, when I want to withdraw bitcoin a multifirm portfolio, gives me error whether I'm the one who makes the order or the second person to authorize the withdrawal, the version is the penultimate who took not the full version, right now I have no phone at the hand

**Comment by matiu** [comment]
But, are your trying to remove the wallet from the device, as mentioned on the original issue? Could you include a screenshot?

**Comment by AB8520** [comment]
this afternoon will give the application update if I get the same mistake I will proceed to eliminate it and try again

**Comment by matiu** [comment]
thanks. please reopen if still valid.
