### ISSUE TITLE
"Copayer already in this wallet" after deleting wallet from 2-2 multisig and trying to rejoin

### ISSUE THREAD

**Issue by chriswilmer** [bitpay/copay#3531]
- I used a single trezor to create a 2-of-2 multisig wallet on two different instances of Copay (let's call them A and B). I used the trezor's account #1 on instance A and the trezor's account #2 on instance B.
- I intentionally deleted the wallet on instance B
- I tried rejoining the shared Copay walled on instance B with account #2 of the trezor, and I get the error message "Copayer already in this wallet"

I'm not sure how to rejoin the wallet. I will try uninstalling and reinstalling the Copay chrome app. I don't understand how the recovery tool (https://bitpay.github.io/copay-recovery/) would help in this case as it doesn't provide any input fields for account numbers.

**Comment by dabura667** [comment]
> I tried rejoining the shared Copay walled on instance B with account #2 of the trezor, and I get the error message "Copayer already in this wallet"

in Copay, you don't rejoin. Joining the wallet only happens once.

The only way to restore a deleted multisig wallet currently is to import the exported json format backup.

It sounds like you did not create an exported wallet file... so I'm sorry.

The recovery tool does not support Trezor. Only the Chrome app does.

**Comment by chriswilmer** [comment]
Is there a technical reason preventing the ability to "rejoin"? Or rather
"recreate" the identical previous wallet instead of needing to import it?

I didn't lose any funds doing this, I am intentionally testing the
robustness of Copay + Trezor + multisig. The fact that there is no way to
recreate the wallet if Copay gets suddenly uninstalled (or of that laptop
catches fire) soon after joining a trezor-based multisig wallet seems
problematic.

I don't think people carrying around hardware wallets should need to also
be carrying around a separate device with Copay installed or with a JSON
backup of their wallet. It should be possible to sit down at a fresh
install of Copay on a new computer and continue your business with a prior
multisig Copay wallet (obviously things like wallet names and aliases
wouldn't transfer this way).

On Thu, Nov 26, 2015 at 9:29 AM, dabura667 <notifications@github.com> wrote:

> I tried rejoining the shared Copay walled on instance B with account #2
> <https://github.com/bitpay/copay/issues/2> of the trezor, and I get the
> error message "Copayer already in this wallet"
>
> in Copay, you don't rejoin. Joining the wallet only happens once.
>
> The only way to restore a deleted multisig wallet currently is to import
> the exported json format backup.
>
> It sounds like you did not create an exported wallet file... so I'm sorry.
>
> The recovery tool does not support Trezor. Only the Chrome app does.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3531#issuecomment-159927616>.
>



-- 
Chris Wilmer, Ph.D.
Asst. Professor of Chemical & Petroleum Engineering
University of Pittsburgh

c.wilmer@gmail.com
847-859-9404 (cell/office/home)
www.wilmerlab.com <http://wilmerlab.com/>

**Comment by matiu** [comment]
On Thu, Nov 26, 2015 at 11:52 AM, chriswilmer <notifications@github.com>
wrote:

> Is there a technical reason preventing the ability to "rejoin"? Or rather
> "recreate" the identical previous wallet instead of needing to import it?
>
> I didn't lose any funds doing this, I am intentionally testing the
> robustness of Copay + Trezor + multisig. The fact that there is no way to
> recreate the wallet if Copay gets suddenly uninstalled (or of that laptop
> catches fire) soon after joining a trezor-based multisig wallet seems
> problematic.
>

It is totally possible to recreate a wallet if Copay is suddenly
uninstalled.





>
> I don't think people carrying around hardware wallets should need to also
> be carrying around a separate device with Copay installed or with a JSON
> backup of their wallet. It should be possible to sit down at a fresh
> install of Copay on a new computer and continue your business with a prior
> multisig Copay wallet (obviously things like wallet names and aliases
> wouldn't transfer this way).
>
>
Exactly. Recover ONLY with TREZOR was an objective of the integration.

To recover from TREZOR only you need:

1) In a single sig wallet: Only the trezor.

2) In a multi sig wallet: say a 2-3 wallet, the 3 of them TREZORs signers:

(probably, in order of most common cases)
  2.a: 2 trezors + access to the wallet server where the wallet was created.
  2.a: 2 trezors, a new BWS, an one COPAY app where the wallet was create
(an hit 'recreate' there)
  2.b: 2 trezors, a new BWS, and  1 copay export (so the xPubKey of the 3
signed is obtained)

**Comment by matiu** [comment]
Replaying your original post, in order to access the wallet again, you need
to go to "Import Wallet" in copay, an select Hardware Wallet -> Trezor ->
and the appropiate account. Be sure to select 'shared wallet' since the
space of account # of multisig wallet is different than singlesig wallets.

Sorry the confusion.  Please confirm if you can regain access to your
wallets.

On Thu, Nov 26, 2015 at 12:00 PM, Matias Alejo Garcia <matias@bitpay.com>
wrote:

>
>
> On Thu, Nov 26, 2015 at 11:52 AM, chriswilmer <notifications@github.com>
> wrote:
>
>> Is there a technical reason preventing the ability to "rejoin"? Or rather
>> "recreate" the identical previous wallet instead of needing to import it?
>>
>> I didn't lose any funds doing this, I am intentionally testing the
>> robustness of Copay + Trezor + multisig. The fact that there is no way to
>> recreate the wallet if Copay gets suddenly uninstalled (or of that laptop
>> catches fire) soon after joining a trezor-based multisig wallet seems
>> problematic.
>>
>
> It is totally possible to recreate a wallet if Copay is suddenly
> uninstalled.
>
>
>
>
>
>>
>> I don't think people carrying around hardware wallets should need to also
>> be carrying around a separate device with Copay installed or with a JSON
>> backup of their wallet. It should be possible to sit down at a fresh
>> install of Copay on a new computer and continue your business with a prior
>> multisig Copay wallet (obviously things like wallet names and aliases
>> wouldn't transfer this way).
>>
>>
> Exactly. Recover ONLY with TREZOR was an objective of the integration.
>
> To recover from TREZOR only you need:
>
> 1) In a single sig wallet: Only the trezor.
>
> 2) In a multi sig wallet: say a 2-3 wallet, the 3 of them TREZORs signers:
>
> (probably, in order of most common cases)
>   2.a: 2 trezors + access to the wallet server where the wallet was
> created.
>   2.a: 2 trezors, a new BWS, an one COPAY app where the wallet was create
> (an hit 'recreate' there)
>   2.b: 2 trezors, a new BWS, and  1 copay export (so the xPubKey of the 3
> signed is obtained)
>



-- 
BitPay.com

**Comment by chriswilmer** [comment]
"Exactly. Recover ONLY with TREZOR was an objective of the integration."

Super! Glad that we agree on this.

OK thanks, I'll give the import "hardware wallet" a try.

(is this the right place for these kind of discussions? I tried asking some
questions on BitPay Labs - Copay... but it seems github is more active)

On Thu, Nov 26, 2015 at 10:08 AM, Matias Alejo Garcia <
notifications@github.com> wrote:

> Closed #3531 <https://github.com/bitpay/copay/issues/3531>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3531#event-475672352>.
>



-- 
Chris Wilmer, Ph.D.
Asst. Professor of Chemical & Petroleum Engineering
University of Pittsburgh

c.wilmer@gmail.com
847-859-9404 (cell/office/home)
www.wilmerlab.com <http://wilmerlab.com/>

**Comment by chriswilmer** [comment]
Tried using the Import shared Trezor wallet... worked like a charm!

One confusing thing is that with the import feature... Copay somehow remembered my modified Wallet alias... how did it do that? Does it get it from the Copay server?
