### ISSUE TITLE
Can't add address to addressbook in a 2-2 shared Trezor Copay wallet

### ISSUE THREAD

**Issue by chriswilmer** [bitpay/copay#3536]
I won't list all of the steps I followed to create the wallet, but for this specific bug I did the following:

1. Go to send tab
2. Click on the address icon to pull up the address book 
3. Click on addressbook (to switch from my own wallets)
4. I enter in a new Bitcoin address (and see a green check mark appear)
5. I enter a label for the address
6. I click "save"
7. I am returned to the list of saved addresses (which is empty), and the address I just tried to save isn't there

**Comment by cmgustavo** [comment]
Hi, thanks for report.

I can't reproduce the issue. I followed the same steps, but finally the address is there.
What happen if you restart the app? Does The new entry appear in the list?

**Comment by matiu** [comment]
JIC, note that addressbook entries are not shared between copayers. It is a local feature only.

**Comment by chriswilmer** [comment]
@cmgustavo : Didn't appear when I restarted the app. In case it makes a difference, this is a wallet that I deleted and then reimported from a backup file. I am on a Windows 8.1 machine.

@matiu : Yes, to be clear, I was not expecting addresses to be shared between copayers... this is all one one machine/copay-instance.
