### ISSUE TITLE
Trezor : Wrong chrome extension title in trezor extention

### ISSUE THREAD

**Issue by schnerchi** [bitpay/copay#3543]
Trezor indicates an "Unknown Chrome Extension". Is this the normal behavior?

![bildschirmfoto 2015-11-27 um 08 52 17](https://cloud.githubusercontent.com/assets/7231994/11436421/d6af9100-94e4-11e5-9e52-1c68c5a9da94.png)

**Comment by matiu** [comment]
yes, that is expected. We will talk to TREZOR if there is any way to solve that. thanks.

**Comment by jpochyla** [comment]
fixed, thank you!
