### ISSUE TITLE
"Key already associated with an existing wallet"... why does this prevent creating a Trezor wallet?

### ISSUE THREAD

**Issue by chriswilmer** [bitpay/copay#3545]
Why can't a user create multiple identical wallets on different Copay instances using the same Trezor and account number? I'm confused about what is expected of users in this situation.

When I try using the import function I get the error message "Wallet not registered at the Wallet Service."

Something seems wrong...

[Note, I am not using shared wallets here. I am using two identical Trezors (they have different aliases but the same seed), and the same password and account number. When I try to use the second Trezor on a second instance of Copay, I am getting the above errors]

**Comment by chriswilmer** [comment]
OK, I think I figured it out.

Copay asks you to export public keys twice, but what it does the key it gets the first time is really mysterious (to the user at least). Each time it asks me to export the public key I have to enter my password, and so the first time I just type gibberish, and the second time I type my actual password.

I THINK that Copay is using that first public key to check if I am already registered on the B?? (I always forget the acronym) server. I tried making sure that that the passphrases matched on the first public key export on both Copay instances and then it let me import my wallet on the second instance.

**Comment by matiu** [comment]
> Why can't a user create multiple identical wallets on different Copay instances using the same Trezor and account number? I'm confused about what is expected of users in this situation.

For software wallets (the majority of Copay wallets), having 2+ keys on the same device does not make sense, so that is why there is a restriction.

> I THINK that Copay is using that first public key to check if I am already registered on the B?? (I always forget the acronym) server. I tried making sure that that the passphrases matched on the first public key export on both Copay instances and then it let me import my wallet on the second instance.

The first public key is used as entropy source for several keys in Copay (for example having a private key to encrypt configuration data an store it on BWS (like the wallet alias you mentioned on other thread))
