### ISSUE TITLE
Close call

### ISSUE THREAD

**Issue by XBTdev** [bitpay/copay#3549]
Nearly lost a VERY significant amount of bitcoin today because of my own hastiness AND because of VERY POOR UX in one copay screen.

I'd prefer to discuss the issue details privately. If I could chat with @matiu or @cmgustavo or @bechi that would be great. Any instant message app convenient for you guys? Slack/Skype/Telegram/etc?

Edit: a few hours later, and I'm still a bit shaken up by how close I came to losing a large amount of money. I will definitely be more careful in the future, but these UX issues absolutely need fixed.

**Comment by matiu** [comment]
thanks, followed up privately.
