### ISSUE TITLE
Signatures rejected by server

### ISSUE THREAD

**Issue by AB8520** [bitpay/copay#3551]
Good morning, I have problems with my wallet copay, when removing a multifirm account gives me error Connection with the server and does not let me remove the bitcoin. if I could help please
![img-20151129-wa0007](https://cloud.githubusercontent.com/assets/16025081/11491514/bb44af68-97b4-11e5-9c4d-aabaf72418fe.jpg)

**Comment by matiu** [comment]
Hola,

por favor fijate que todos los clientes  estén usando la última version
(1.5.2) de Copay. Borra la propuesta de pago actual y crea una nueva y
prueba firmar de vuelta.


Voy a modificar el título del ticket para reflejar mejor el problema.

On Tue, Dec 1, 2015 at 12:20 AM, AB8520 <notifications@github.com> wrote:

> Good morning, I have problems with my wallet copay, when removing a
> multifirm account gives me error Connection with the server and does not
> let me remove the bitcoin. if I could help please
> [image: img-20151129-wa0007]
> <https://cloud.githubusercontent.com/assets/16025081/11491514/bb44af68-97b4-11e5-9c4d-aabaf72418fe.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3551>.
>



-- 
BitPay.com

**Comment by AB8520** [comment]
Si tenemos la misma versión de copay, incluso cuando daba error de conexión
al servidor

**Comment by matiu** [comment]
No podemos reproducir el error. Hay algo particular en su wallet que pueda aportar más información?  

Si borras la propuesta y creas una nueva, funciona?

**Comment by AB8520** [comment]
No funciona, incluso la hemos realizado de ambas maneras tanto el equipo
que da error como el otro haciendo la propuesta y da error

**Comment by matiu** [comment]
Lamentablemente no podemos reproducir el error.

Algunas preguntas:
1- estas corriendo tu propio wallet service?
2- que plataforma usan todos los copayers?
3- cuando, aproximadamente, fue creada la wallet? de que version  de copay es?

podrías buscarnos en el chat de https://gitter.im/bitpay/copay para ver el problema en más detalle?

**Comment by AB8520** [comment]
1- No, estamos usando la plataforma copay netamente sin servicios
adicionales.
2- Android 4.4 y 4.2
3- Hace 2 meses aproximadamente, la version no te la sabria decir.


El 1 de diciembre de 2015, 9:49, Matias Alejo Garcia <
notifications@github.com> escribió:

> Lamentablemente no podemos reproducir el error.
>
> Algunas preguntas:
> 1- estas corriendo tu propio wallet service?
> 2- que plataforma usan todos los copayers?
> 3- cuando, aproximadamente, fue creada la wallet? de que version de copay
> es?
>
> podrías buscarnos en el chat de https://gitter.im/bitpay/copay para ver
> el problema en más detalle?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3551#issuecomment-160981494>.
>



-- 
________________________________________
                     Angel Briceño
                     Msn:Angelbriceno@gmail.com
                     Cel: 0412-5127955
