### ISSUE TITLE
UI freeze

### ISSUE THREAD

**Issue by monsterbitar** [bitpay/copay#3553]
After starting application, UI is responsive for a few seconds, then freezes. If I open the camera to scan during this time then after a successful scan it will show "requesting camera".

The animation for updating wallet completes successfully, but the icon-sync.svg icon keeps flashing/blinking indefinately.

Issue is with v1.5.2 on android 4.2.2, on two separate devices using identical hardware. (Philips W6610)

**Comment by matiu** [comment]
Does your wallet have a lot of transactions? Could you check the "history" tab?

**Comment by monsterbitar** [comment]
I opened the history tab during the first few seconds and can see it count up in transactions to 48, then freeze. I'm fairly sure there should be at least a couple of hundred transactions on that wallet.

**Comment by monsterbitar** [comment]
I upgraded the copay app through google play store today, but the issue remains.

**Comment by monsterbitar** [comment]
I can confirm that the issue is wallet specific. If I change wallets before it freezes to my family savings wallet, it correctly loads the 10-15 transactions in it and the UI does not freeze until I go back to the spendings wallet.

**Comment by matiu** [comment]
thanks for the follow up.


There must be one TX that is been incorrectly handled by the block explorer, or Copay. Because not TXs are preloaded and cached on the device, all TXs are requested.

In order to move forward we would need some information about the wallet. Do you think we can meet at https://gitter.im/bitpay/copay ? (my user name is @ematiu).

**Comment by monsterbitar** [comment]
I'm a bit busy atm, but can be there in an hour I think. I see the user matiu, but not ematiu there, assuming you misspelled as it's connected to github accounts and your name here is matiu.

**Comment by matiu** [comment]
Right, sorry about that `matiu` is the username.

no problem just ping me when you are around.

**Comment by hoangpnr** [comment]
Unfortunately, I do not understand what you send is ....?

2015-12-02 20:49 GMT+07:00 Matias Alejo Garcia <notifications@github.com>:

**Comment by monsterbitar** [comment]
After turning off my network connection, I get several more seconds before it freezes, but it still does. It might be that it has always frozen on all wallets, and that it is simply faster on the wallet where most of my transactions are.

**Comment by monsterbitar** [comment]
I can confirm that the freeze still happens in todays release.

**Comment by matiu** [comment]
Thanks for the update. We have tried to reproduce the error, but no luck. The history loaded ok.

After discovering this issue ( https://github.com/bitpay/copay/pull/3683 ) with Android 4.2, it think this is could be related with the platform. There seems to be some language differences  in Androids < 4.3. We will try to reproduce this one on 4.2 and get back to you.

I would be very helpful if you can install you wallet on other device (a desktop for example) and let us know if the history loads fine there.

**Comment by monsterbitar** [comment]
The history loads fine on the wallet install, I've used that as a means to transfer the funds over to a mycelium wallet for the time being, but would like to return to multisig and the much more userfriendely UI of copay compared to mycelium.

**Comment by monsterbitar** [comment]
Since I've encountered further issues with the latest release (1.6.2) I've written a new issue on that matter on: https://github.com/bitpay/copay/issues/3686

Since you are unable to reproduce the issue on your end, could we work towards finding clues/logs using my environment (phone & software) where it is currently easily reproducable?

**Comment by monsterbitar** [comment]
I should add that I after backing up and sending the funds elsewhere, I deleted all wallets, cleaned out the data and updated to 1.6.2 today hoping the stated fix in the changelog would be the solution. As such I now have different issues (and more of them), but they may still stem from the same underlying problem.

**Comment by matiu** [comment]
closed, followed at https://github.com/bitpay/copay/issues/3686
