### ISSUE TITLE
Implement 'Show on TREZOR' or 'eyeball button'

### ISSUE THREAD

**Issue by Chris869218** [bitpay/copay#3558]
The 'Show on TREZOR' feature that some TREZOR compatible wallets have implemented provides a lot of peace of mind. When preparing to transfer a large amount of bitcoin to a multisig wallet, it would be nice to display the receiving address on the TREZOR screen to confirm the receiving address is one controlled by a TREZOR signature and hasn't been swapped elsewhere with malware.

**Comment by matiu** [comment]
Depends on https://github.com/trezor/connect/issues/11

thanks.

**Comment by matiu** [comment]
Closing until https://github.com/trezor/connect/issues/11 is implemented.
