### ISSUE TITLE
Bitcoins gone..forever?

### ISSUE THREAD

**Issue by Uberlinu** [bitpay/copay#3563]
Hi!

I'm very new to bitcoin.. and today I made two of my first ever transactions... The other one made it through... The other seems to have gone into some sort of internet limbo.. Now the thing is that I don't know who to ask for help and what info to divulge to one who could help me... In the name of security.
So if I could get some author of Copay to tell me who to turn to, what to tell, and how the hell am I gonna get my money back...

-Uberlinu

**Comment by monsterbitar** [comment]
Disclaimer: I am not an author of copay.

If you choose to share information, you should be aware of the possible consequences, so I'll help list them to the best of my knowledge here:

If you share a public address from a HD wallet (the ones used in copay), you will give up information about transaction history, allowing others to see the transactions that is on the blockchain (the public ledger) relating to that public address, but not transactions done with other addresses generated from the same wallet.

If you share a private key or backup/recovery passphrase from a HD wallet, you will hand over complete control of all past, current and future funds associated with that wallet.

I would suggest that you go to a public blockchain explorer (https://blockchain.info/ for example) and make a search on the public addresses used in both the transactions, to get a look at them on the blockchain, if they are there.

If you can find the first transaction in a public blockexplorer, but not the other transaction, then please come back here and tell us how the transactions where made, and we might be able to help you locate the transaction.

**Comment by Uberlinu** [comment]
Thanks monsterbitar..

What I found out in Blockchain.info was that both of my transactions seem to show up there...
It looks like my first payment, the 10,00 USD, made from my address 1A5x7Y1RVHc6XPoRMgNbvdpCEC588N5Gdb
went to
1GzeC4hBhbdHvEgwq9EdSbQBk6BtS14e44
Where it should've gone... But there is also another address when I click on the transaction code (?)
482c275015a999bb388754836e56c733a0dd4b7c60766048165261f505354f65
And that other address is
1GU1od5tcXrfab2G6qBKfyawXU2LYSu4SJ
Right next to the target address... This was the transaction that failed... And this latter address shows up below..?!

The other payment, the 5,00 USD, left from the address
1GU1od5tcXrfab2G6qBKfyawXU2LYSu4SJ
(The one shown above.. Is it mine?! It shouldn't be.. ?) To the other target address
1HgSGua9rD8gnDY3TseAL8czFDmVKzyfd2
Which is the correct target address... But when I click on the transaction code
47cf53fe00cf9c28ee5805cce854e8a354bf5a983ab90b8973533780c64d594f
There's also another address
1FpMSCc32tJa2A7t4y5rt1eKCufrQiBF8R 
Well... This is latter payment was successful...
I don't mind if my address shows up.. these are the only transactions I've made so far, and I can always change my address... So you gurus tell me what the hell is going on.. I can't make heads or tails of this whole thing... I only know that I've lost 10,00 USD somewhere along the way... 
I've been struck dumb.. :(

**Comment by monsterbitar** [comment]
when you send a transaction in bitcoin, you always use your full inputs (think of these as bills), and all amounts that you don't want to send to the recipient will be sent to another address in your wallet as change. (this is why there is two outputs on the transaction, on to the target, one back to you as change).

These new addresses are generated by the wallet, you control them through the wallet and they are part of the backup/recovery passphrase.

It seems you have nothing to worry about here, it is all as it should be and in copay you should be able to chose the wallet, click on transaction/history and look at your transactions in a more userfriendly manner.

**Comment by matiu** [comment]
In general, everytime you send a TX there are 2 outputs, the external address, the one you are sending funds, and a change address, that is from your wallet. The excess funds are 'transfered back' to your change address. Note that your wallet can have multiple addresses. And everytime you send money, a new change address if generated.

Your wallet balance should reflect the balance of ALL the addresses of your wallet.
