### ISSUE TITLE
"Address limit reached"

### ISSUE THREAD

**Issue by netsmashers** [bitpay/copay#3582]
I got a strange error message when trying to send a payment from my iOS Copay. The payment was not sent, instead i received a message like this: "Could not generate new address, address limit reached". Maybe the app was not able to create a change address?

I was finally able to send payment from the Copay app on my Mac, but this seems to be a bug on the iOS app.

**Comment by isocolsky** [comment]
Hi. BIP44 dictates that the maximum number of consecutive addresses *without* any activity in a wallet should not be greater than 20. The error message you are getting means the app is trying to generate that 21th address. Earlier versions of Copay did not have that check in place, maybe that is why the OSX app did work for you? Did you retry sending from the iOS app after the incident?
