### ISSUE TITLE
Copay support for smaller mobile platforms.

### ISSUE THREAD

**Issue by ApostolosB** [bitpay/copay#3609]
Your email support told me to post here and even though i don't feel is the best place here goes:

Are there any plans to support/port copay for platforms like Sailfish OS or Ubuntu (both have a lot in common). Both don't have bitcoin wallet apps available and are used -at the moment- by technically competent users that are most likely to use bitcoin as a currency than the average joe user. 

Thanks in advance.

**Comment by matiu** [comment]
> Are there any plans to support/port copay for platforms like Sailfish OS or Ubuntu

no plans for now. Copay relies on multiple components (like cordova, and some cordova pluggins, that will need to support those OSs first). PRs are always welcomed.

**Comment by ApostolosB** [comment]
Thank you very much for the answer.
