### ISSUE TITLE
Sent Coin to old deposit address

### ISSUE THREAD

**Issue by interloper0** [bitpay/copay#3635]
Help, I sent bitcoin to an address I sent bitcoin to earlier today. It isnt showing up. If I click create new deposit address will it delete the old one? Please help.

**Comment by matiu** [comment]
New address are generated when you use then or when you manually generate a new one. Your wallet can have multiple address. You are still in control of old addresses.

You can see all the addresses at settings -> advanced -> wallet information

**Comment by interloper0** [comment]
hi, I tried searching all the old addresses and nothing came up. It's been over 12 hours and my coin hasnt shown up.

**Comment by matiu** [comment]
check in a block explorer (like insight.bitpay.com or https://www.blocktrail.com/BTC) the address. Check if the transaction is there and if it is confirmed.

**Comment by interloper0** [comment]
Hi, I tried that many times and It didnt find it at all.

**Comment by matiu** [comment]
If the transaction is not on the block exporers, it wont show on Copay. Check with the payor that the transaction was really sent.

**Comment by interloper0** [comment]
https://gyazo.com/a0f2e8036996ef00d1ae13d536c11967 

It was confirmed.

**Comment by interloper0** [comment]
so is my money gone?

**Comment by matiu** [comment]
You said it was confirmed.
