### ISSUE TITLE
Can't Send Coins Because Other Wallet Holder Is Gone

### ISSUE THREAD

**Issue by lquessenberry** [bitpay/copay#3637]

**Comment by matiu** [comment]
please provide more information.

**Comment by lquessenberry** [comment]
I just realized that I have had this open in the past under issue 2193. I
am trying to find all the information that I had before that is relevant to
this issue.

https://github.com/bitpay/copay/issues/2193

Thanks,

On Thu, Dec 10, 2015 at 9:25 AM Matias Alejo Garcia <
notifications@github.com> wrote:

> please provide more information.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3637#issuecomment-163657704>.
>
-- 
Lee Quessenberry
Co-Founder | Nifty & Swell Handmade Media
Co-Founder | Forge Arkansas
Co-Founder | Bluff City BBQ Supply
Fellowship Entrepreneur | Delta Regional Authority
Web Developer | E.C. Barton & Co.
Digital Marketing Director | Axanar Productions

Phone: 501-281-2231

Twitter: http://twitter.com/lquessenberry
LinkedIn: http://linkedin/in/lquessenberry
Facebook: http://facebook.com/lquessenberry
PayPal: https://www.paypal.me/lquessenberry
OneName.io: https://onename.io/lquessenberry

http://niftyandswell.com | http://leequessenberry.com
