### ISSUE TITLE
Copayer Gone, but coin is locked.

### ISSUE THREAD

**Issue by lquessenberry** [bitpay/copay#3641]
Issue 2193 was my original post. I have a backup AES file of the wallet of my copayer who has skipped town. I have a password that he sent to me a while back when we were having trouble with copay early on. When I try to import the wallet in the new Copay, I get a password error, but earlier in the year I got a corrupt file alert. I have about 1.25 locked up in bitcoins that I can't get out because I can't seem to get my copayer's wallet imported in order to okay the release.

**Comment by matiu** [comment]
> . When I try to import the wallet in the new Copay, I get a password error, but earlier in the year I got a corrupt file alert

older versions of Copay were not specific about the error. If you get password error now it just means that the password is wrong.

You can verify that independently  here: https://bitwiseshiftleft.github.io/sjcl/demo/ 

Enter the backup text in 'cipher text' and the password. If you get 'CCM mismatch" it means the password is wrong.

**Comment by lquessenberry** [comment]
Okay. I'll give it a shot. I've reached out to the other copayer again to
unlock the coin, but he's unresponsive. Are there other options I can
pursue?
On Thu, Dec 10, 2015 at 12:03 PM Matias Alejo Garcia <
notifications@github.com> wrote:

> Closed #3641 <https://github.com/bitpay/copay/issues/3641>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3641#event-488487021>.
>
-- 
Lee Quessenberry
Co-Founder | Nifty & Swell Handmade Media
Co-Founder | Forge Arkansas
Co-Founder | Bluff City BBQ Supply
Fellowship Entrepreneur | Delta Regional Authority
Web Developer | E.C. Barton & Co.
Digital Marketing Director | Axanar Productions

Phone: 501-281-2231

Twitter: http://twitter.com/lquessenberry
LinkedIn: http://linkedin/in/lquessenberry
Facebook: http://facebook.com/lquessenberry
PayPal: https://www.paypal.me/lquessenberry
OneName.io: https://onename.io/lquessenberry

http://niftyandswell.com | http://leequessenberry.com
