### ISSUE TITLE
Google Play and App Store Copay screenshots 

### ISSUE THREAD

**Issue by gabrielbazan7** [bitpay/copay#3651]
Need to be updated 

<img width="1062" alt="screen shot 2015-12-10 at 4 57 55 pm" src="https://cloud.githubusercontent.com/assets/10999037/11726835/5926b80a-9f5f-11e5-9827-673db309456e.png">
![screen shot 2015-12-10 at 4 53 31 pm 3](https://cloud.githubusercontent.com/assets/10999037/11726837/5c68a834-9f5f-11e5-9d5b-8b0c8421c4e8.png)

**Comment by caveman1973** [comment]
I don't have a 4.7 inch model so my screenshots won't look good. But here's the link for PSD vector mockups for the iPhone 6 (all colors):
http://www.pixeden.com/psd-mock-up-templates/iphone-6-psd-vector-mockup

**Comment by caveman1973** [comment]
Copay was updated and I think this ticket should be closed.

**Comment by gabrielbazan7** [comment]
Still the same screenshots in my google play.
