### ISSUE TITLE
OSX builds

### ISSUE THREAD

**Issue by frenchfaso** [bitpay/copay#3657]
When clicking the OSX download link on the website, it opens a page from which you can download source code but there are no binaries.

**Comment by cmgustavo** [comment]
Sorry, there was a problem with the link. It 's been fixed right now, please check again at: https://github.com/bitpay/copay/releases/latest

**Comment by matiu** [comment]
thanks, it should be fixed  now.

**Comment by frenchfaso** [comment]
Thanks!
