### ISSUE TITLE
image is mirrorred, when scanning

### ISSUE THREAD

**Issue by philhug** [bitpay/copay#3663]
Platform: Android 6.0

**Comment by dabura667** [comment]
What image?
Mirrored veritcally or horizontally?
Scanning what?
Where did you enter the scanning?

etc.

You need to give more information, otherwise someone will look at this and say "ok, well nothing is mirrored for us, so no problem"

**Comment by philhug** [comment]
phone is a Nexus 5X
image is mirrored both vertically und horizontally and makes capturing weird.

**Comment by matiu** [comment]
Related: http://www.xda-developers.com/why-images-in-some-camera-apps-are-upside-down-on-the-nexus-5x/

**Comment by matiu** [comment]
should be fixed with the new QR scanner

**Comment by cjr-roland** [comment]
Issue is still here on Nexus 5X,
