### ISSUE TITLE
Disable input locking for 1 of 1 wallets

### ISSUE THREAD

**Issue by XBTdev** [bitpay/copay#3665]
Currently inputs are 'locked' internally by copay when they are part of a payment proposal. This makes sense in most cases, because a competing spend could invalidate inputs thus requiring every copayer to re-sign the invalided transaction with new inputs. BUT... there may be some use-cases when it would be nice to disable input locking.

I was going to use Copay for employee payments. Using a 1-1 wallet, I was going to export a backup WITHOUT private keys and give this to someone responsible for creating payment proposals for each employee. For example; every Saturday they might review employee time-logs and create 15 payment proposals, one for each employee. I would review the TX proposals and approve them later.

In this case, the input locking is not needed at all, since this is a 1-1 wallet and I don't have to worry about other copayers invalidating a partially-signed tx. The input locking just prevents me from using copay in the above use-case without maintaining a minimum number of suitably sized UTXOs.

**So I propose that 1-1 wallets have non-blocking payment proposals.** This will greatly increase the useful options with watch-only users. Or... let the user disable this option completely under advanced settings.

This is similar to #3473, but I think my use case is different because input locking is truly unneeded for 1 of 1 wallets.

**Comment by matiu** [comment]
This would be the same as https://github.com/bitpay/copay/issues/3825

Thanks for the detailed case explanation. Linking the tickets.
