### ISSUE TITLE
using SIGHASH_ANYONECANPAY for flexible input handling with multiple competing proposals

### ISSUE THREAD

**Issue by XBTdev** [bitpay/copay#3666]
Lighthouse works by using SIGHASH_ALL | SIGHASH_ANYONECANPAY to allow transaction proposals where adding inputs later is allowed.

The outputs are signed, which prevents the amounts or destination addresses from being changed.

Copay could sign using all available inputs without locking inputs. If an input is spent, there will be additional inputs already signed that can be used instead.

Would this work? I'm just looking for advanced solutions to the input locking issue.

**Comment by dabura667** [comment]
Problem with that scheme is change and fees...

**Comment by matiu** [comment]
agree with @dabura667 

closed in favor of https://github.com/bitpay/copay/issues/3825
