### ISSUE TITLE
Copay: Wallet service - Unknown Error (desktop client 1.5.2, win x64)

### ISSUE THREAD

**Issue by xyz15** [bitpay/copay#3668]
Hi,
I am using Copay wallet for couple of weeks without any problem, but today I have got "Unknown error" - please see screenshot (using desktop client on win64). I can not access my wallet/btc. I have tried to restore via passphrase (seed) incl. my pass but no luck - client reports unknown error. The only luck I had was by using backup file (encrypted with pass), but then client reports that import was sucessful but immediately displays "unknown error" once again and addresses, balance and history are unavailable.

Please let me know, how I might repair this or if this is it and I lost btcs ?
Thank you in advance for your reply and any help.
Best regards
John

![copay_unknown error](https://cloud.githubusercontent.com/assets/12380253/11769384/1367ee52-a1de-11e5-87db-1b6d3bf66d7d.png)

**Comment by davidlatapie** [comment]
Same issue (but on Mac), it is a recurring error. It may come from the ISP, since I have no problem on my mobile, with another ISP.

**Comment by matiu** [comment]
it this still valid? (OP) can you import you wallet on other device so you
can access your funds?

On Thu, Jan 14, 2016 at 5:52 PM, David <notifications@github.com> wrote:

> Same issue (but on Mac), it is a recurring error. It may come from the
> ISP, since I have no problem on my mobile, with another ISP.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3668#issuecomment-171775870>.
>



-- 
BitPay.com
