### ISSUE TITLE
Suggestion: buttons should hide when the user scroll the activity window 

### ISSUE THREAD

**Issue by bitcoinuser** [bitpay/copay#3678]
I think the buttons Receive|Activity|Send, should hide when the user scroll the window. I think should work the same way twitter app.

**Comment by bechi** [comment]
I don't think so because these button are the main navigation for the app. Maybe other things could hide when the user scroll the window, but the navigation bar no.

**Comment by bitcoinuser** [comment]
Changed my mind. Closing it.
