### ISSUE TITLE
Suggestion: touch screen movement left and right should switch the windows

### ISSUE THREAD

**Issue by bitcoinuser** [bitpay/copay#3679]
1- Hi, I think the left menu (Where it's located profile|add wallet|Settings) should not open on screen movement. I think should only open when the user click on top left button or android phone button.
2- If the left menu is not opened with screen movement, the windows (Receive|Activity|Send) can be switched with user touch screen movement. I think it's the ideal.

Sorry for the english. Hope you understand.

**Comment by bitcoinuser** [comment]
Changed my mind. Closing it.

**Comment by bitcoinuser** [comment]
Reopened. I see https://www.yallet.com/ allows switch windows with touch screen movement and still allows open the left menu with touch screen movement too.

**Comment by matiu** [comment]
We save the swipe to open the side bar to show the wallets.  Most of the times the sidebar need to be open on the activity view, which is on the center of the tabs, so it will add complexity to only allow to open it from the tab on the left (receive)

**Comment by bitcoinuser** [comment]
Yallet wallet allows to open menu from the tab of center. 
Did you test yallet app? If not, please test it.

**Comment by bitcoinuser** [comment]
I mean sidebar instead of menu.
