### ISSUE TITLE
Question: Import keys from Coinbase Vault on Copay

### ISSUE THREAD

**Issue by bitcoinuser** [bitpay/copay#3680]
Hi, I created a vault 2of3 wallet on coinbase. Is it possible to import the 2 keys I have access and create another 2of3 wallet, but now with my 2 keys and 1 from copay? So I can have access of my bitcoins of coinbase vault.

**Comment by matiu** [comment]
No, idont think that will work. No sure what multisig schema Coinbase uses for vault, but it has never been tested in Copay.
