### ISSUE TITLE
iOS version stuck at step 1.

### ISSUE THREAD

**Issue by Transisto** [bitpay/copay#3685]
Most people won't understand that they have to scroll down to be able to click "agree with T&C"

Especially since scrolling scroll into the T&C instead of the whole page.

**Comment by Transisto** [comment]
also the backup phase one word in a row below "Continue" button.  (Scrolling needed)

**Comment by matiu** [comment]
Thanks for the report. what phone are you using?

**Comment by matiu** [comment]
Thanks for the report. We will check it on an iPhone 5 screen .
