### ISSUE TITLE
Something is wrong in android 4.2.2 or Philips W6610

### ISSUE THREAD

**Issue by monsterbitar** [bitpay/copay#3686]
Last update (1.5.2) added something that froze my user interface after a couple of seconds. This update (1.6.2) irratically fails at multiple tasks:

When making a new wallet, then cancel at invitation sharing, it then freezes when making new wallets.
When spending funds from one wallet, I've gotten authentication errors.
When backing up a new wallet (empty, clean) it claims it fails to verify (I triple-checked the words and order).
When importing a seed from mycelium (private wallet), it finds only a few of the transactions.
When scanning for more transactions on a wallet imported from mycelium it finds more transactions thatn mycelium does, then freezes the UI.

Is there a debug version somewhere I can get, or log files I can inspect?

**Comment by monsterbitar** [comment]
the freeze issue in 1.5.2 mentioned here is talked about in https://github.com/bitpay/copay/issues/3553

**Comment by matiu** [comment]
you can check the session log at settings -> about copay -> logs

**Comment by monsterbitar** [comment]
Can I reach that log from a file in the filesystem? Once the UI freeze I'd like to read the log after the fact, but since the UI is frozen I cannot get there.

The backup verification writes in the log: "Failed to verify backup: Private key mismatch".

This happens on both a single-key and 2-of-2 multisig wallet. Triple checked the words and orders in both cases.

**Comment by monsterbitar** [comment]
Complete logs from start of application to backup verification; wallet is a throw-away without funds:

Starting Copay v1.6.2 #e92a29f
Client: isCordova: true isChromeApp: null isNodeWebkit: undefined
Navigator: Mozilla/5.0 (Linux; U; Android 4.2.2; en-us; Philips W6610 Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
Using file storage: true
Setting default language: en
Got main dir: file:///data/data/com.bitpay.copay/files/
Read: {"version":"1.0.0","createdOn":1450264792802,"credentials":[{"network":"livenet","xPrivKey":"xprv9s21ZrQH143K4GyFB16M7mjg4kecneDicRRjofj38y9dQR3FZTUQaPWGRaFTx4PG6vbipP3d7Lr46somyRdYw7EFX31QyyqLimfYxzJKTdo","xPubKey":"xpub6CoRz2Pv3rCqNRPMJX9suQA2BmJyLpN9gVpFWpLWpC9MPMQMcQMRL36TVH7XvtCwVqbB5GpeGSaZEdy2ZezKpcB2VSRRtqH6KphdT4xX3cJ","requestPrivKey":"099bb38d82e9b7efab4f5df118d913892d47d96d32b865f9e72bc7555f48c3e9","requestPubKey":"03eed83f7581e1303921ef94af9740d72abea1af3641807a948f20227f012d7917","copayerId":"0440088643a8365a0f7017748d953923b5939702a6c76ff8a5f58670d371a15e","publicKeyRing":[{"xPubKey":"xpub6CoRz2Pv3rCqNRPMJX9suQA2BmJyLpN9gVpFWpLWpC9MPMQMcQMRL36TVH7XvtCwVqbB5GpeGSaZEdy2ZezKpcB2VSRRtqH6KphdT4xX3cJ","requestPubKey":"03eed83f7581e1303921ef94af9740d72abea1af3641807a948f2022 7f012d7917"}],"walletId":"6c76ad39-9f3d-4fcd-a08b-51452e921336","walletName":"Personal Wallet","m":1,"n":1,"walletPrivKey":"5c321fd790f93e01c85f5988e6ba19a8381f8af7161caa0613219d9629e0a2bb","personalEncry...
Profile is not encrypted
Profile read
Read: {"limits":{"totalCopayers":6,"mPlusN":100},"bws":{"url":"https://bws.bitpay.com/bws/api&quot;},"wallet":{"requiredCopayers":2,"totalCopayers":3,"spendUnconfirmed":true,"reconnectDelay":5000,"idleDurationMin":4,"settings":{"unitName":"bits","unitToSatoshi":100,"unitDecimals":2,"unitCode":"bit","alternativeName":"Swedish Krona","alternativeIsoCode":"SEK"}},"glidera":{"enabled":false,"testnet":false},"rates":{"url":"https://insight.bitpay.com:443/api/rates&quot;},"colorFor":{},"aliasFor":{},"bwsFor":{"953a1016-1669-470b-866a-bd5fb62bdb58":"https://bws.bitpay.com/bws/api","7e72ad72-0f9e-47ac-a453-e680b7306937":"https://bws.bitpay.com/bws/api&quot;}}
Preferences read: {"limits":{"totalCopayers":6,"mPlusN":100},"bws":{"url":"https://bws.bitpay.com/bws/api&quot;},"wallet":{"requiredCopayers":2,"totalCopayers":3,"spendUnconfirmed":true,"reconnectDelay":5000,"idleDurationMin":4,"settings":{"unitName":"bits","unitToSatoshi":100,"unitDecimals":2,"unitCode":"bit","alternativeName":"Swedish Krona","alternativeIsoCode":"SEK"}},"glidera":{"enabled":false,"testnet":false},"rates":{"url":"https://insight.bitpay.com:443/api/rates&quot;},"colorFor":{},"aliasFor":{},"bwsFor":{"953a1016-1669-470b-866a-bd5fb62bdb58":"https://bws.bitpay.com/bws/api","7e72ad72-0f9e-47ac-a453-e680b7306937":"https://bws.bitpay.com/bws/api&quot;}}
Preferences read
Read: 6c76ad39-9f3d-4fcd-a08b-51452e921336
Set focus: 6c76ad39-9f3d-4fcd-a08b-51452e921336
Read: {"version":"1.0.0","createdOn":1450264792802,"credentials":[{"network":"livenet","xPrivKey":"xprv9s21ZrQH143K4GyFB16M7mjg4kecneDicRRjofj38y9dQR3FZTUQaPWGRaFTx4PG6vbipP3d7Lr46somyRdYw7EFX31QyyqLimfYxzJKTdo","xPubKey":"xpub6CoRz2Pv3rCqNRPMJX9suQA2BmJyLpN9gVpFWpLWpC9MPMQMcQMRL36TVH7XvtCwVqbB5GpeGSaZEdy2ZezKpcB2VSRRtqH6KphdT4xX3cJ","requestPrivKey":"099bb38d82e9b7efab4f5df118d913892d47d96d32b865f9e72bc7555f48c3e9","requestPubKey":"03eed83f7581e1303921ef94af9740d72abea1af3641807a948f20227f012d7917","copayerId":"0440088643a8365a0f7017748d953923b5939702a6c76ff8a5f58670d371a15e","publicKeyRing":[{"xPubKey":"xpub6CoRz2Pv3rCqNRPMJX9suQA2BmJyLpN9gVpFWpLWpC9MPMQMcQMRL36TVH7XvtCwVqbB5GpeGSaZEdy2ZezKpcB2VSRRtqH6KphdT4xX3cJ","requestPubKey":"03eed83f7581e1303921ef94af9740d72abea1af3641807a948f2022 7f012d7917"}],"walletId":"6c76ad39-9f3d-4fcd-a08b-51452e921336","walletName":"Personal Wallet","m":1,"n":1,"walletPrivKey":"5c321fd790f93e01c85f5988e6ba19a8381f8af7161caa0613219d9629e0a2bb","personalEncry...
Profile is not encrypted
Read: {"version":"1.0.0","createdOn":1450264792802,"credentials":[{"network":"livenet","xPrivKey":"xprv9s21ZrQH143K4GyFB16M7mjg4kecneDicRRjofj38y9dQR3FZTUQaPWGRaFTx4PG6vbipP3d7Lr46somyRdYw7EFX31QyyqLimfYxzJKTdo","xPubKey":"xpub6CoRz2Pv3rCqNRPMJX9suQA2BmJyLpN9gVpFWpLWpC9MPMQMcQMRL36TVH7XvtCwVqbB5GpeGSaZEdy2ZezKpcB2VSRRtqH6KphdT4xX3cJ","requestPrivKey":"099bb38d82e9b7efab4f5df118d913892d47d96d32b865f9e72bc7555f48c3e9","requestPubKey":"03eed83f7581e1303921ef94af9740d72abea1af3641807a948f20227f012d7917","copayerId":"0440088643a8365a0f7017748d953923b5939702a6c76ff8a5f58670d371a15e","publicKeyRing":[{"xPubKey":"xpub6CoRz2Pv3rCqNRPMJX9suQA2BmJyLpN9gVpFWpLWpC9MPMQMcQMRL36TVH7XvtCwVqbB5GpeGSaZEdy2ZezKpcB2VSRRtqH6KphdT4xX3cJ","requestPubKey":"03eed83f7581e1303921ef94af9740d72abea1af3641807a948f2022 7f012d7917"}],"walletId":"6c76ad39-9f3d-4fcd-a08b-51452e921336","walletName":"Personal Wallet","m":1,"n":1,"walletPrivKey":"5c321fd790f93e01c85f5988e6ba19a8381f8af7161caa0613219d9629e0a2bb","personalEncry...
Profile is not encrypted
Profile loaded ... Starting UX.
Read: true
onGoingProcess openingWallet true
onGoingProcess openingWallet null
Wallet Opened
onGoingProcess updatingStatus true
Updating Status: Personal Wallet null
Updating Transaction History
Read: {"version":"1.0.0","createdOn":1450264792802,"credentials":[{"network":"livenet","xPrivKey":"xprv9s21ZrQH143K4GyFB16M7mjg4kecneDicRRjofj38y9dQR3FZTUQaPWGRaFTx4PG6vbipP3d7Lr46somyRdYw7EFX31QyyqLimfYxzJKTdo","xPubKey":"xpub6CoRz2Pv3rCqNRPMJX9suQA2BmJyLpN9gVpFWpLWpC9MPMQMcQMRL36TVH7XvtCwVqbB5GpeGSaZEdy2ZezKpcB2VSRRtqH6KphdT4xX3cJ","requestPrivKey":"099bb38d82e9b7efab4f5df118d913892d47d96d32b865f9e72bc7555f48c3e9","requestPubKey":"03eed83f7581e1303921ef94af9740d72abea1af3641807a948f20227f012d7917","copayerId":"0440088643a8365a0f7017748d953923b5939702a6c76ff8a5f58670d371a15e","publicKeyRing":[{"xPubKey":"xpub6CoRz2Pv3rCqNRPMJX9suQA2BmJyLpN9gVpFWpLWpC9MPMQMcQMRL36TVH7XvtCwVqbB5GpeGSaZEdy2ZezKpcB2VSRRtqH6KphdT4xX3cJ","requestPubKey":"03eed83f7581e1303921ef94af9740d72abea1af3641807a948f2022 7f012d7917"}],"walletId":"6c76ad39-9f3d-4fcd-a08b-51452e921336","walletName":"Personal Wallet","m":1,"n":1,"walletPrivKey":"5c321fd790f93e01c85f5988e6ba19a8381f8af7161caa0613219d9629e0a2bb","personalEncry...
Profile is not encrypted
Writing: profile {"version":"1.0.0","createdOn":1450264792802,"credentials":[{"network":"livenet","xPrivKey":"xprv9s21ZrQH143K4GyFB16M7mjg4kecneDicRRjofj38y9dQR3FZTUQaPWGRaFTx4PG6vbipP3d7Lr46somyRdYw7EFX31QyyqLimfYxzJKTdo","xPubKey":"xpub6CoRz2Pv3rCqNRPMJX9suQA2BmJyLpN9gVpFWpLWpC9MPMQMcQMRL36TVH7XvtCwVqbB5GpeGSaZEdy2ZezKpcB2VSRRtqH6KphdT4xX3cJ","requestPrivKey":"099bb38d82e9b7efab4f5df118d913892d47d96d32b865f9e72bc7555f48c3e9","requestPubKey":"03eed83f7581e1303921ef94af9740d72abea1af3641807a948f20227f012d7917","copayerId":"0440088643a8365a0f7017748d953923b5939702a6c76ff8a5f58670d371a15e","publicKeyRing":[{"xPubKey":"xpub6CoRz2Pv3rCqNRPMJX9suQA2BmJyLpN9gVpFWpLWpC9MPMQMcQMRL36TVH7XvtCwVqbB5GpeGSaZEdy2ZezKpcB2VSRRtqH6KphdT4xX3cJ","requestPubKey":"03eed83f7581e1303921ef94af9740d72abea1af3641807a948f2022 7f012d7917"}],"walletId":"6c76ad39-9f3d-4fcd-a08b-51452e921336","walletName":"Personal Wallet","m":1,"n":1,"walletPrivKey":"5c321fd790f93e01c85f5988e6ba19a8381f8af7161caa0613219d9629e0a2bb","personalEncry...
Read: 178vXbohFFKvUpMx1MhjqhrBRHsyoF3wsi
Read: []
Binding touchstart elements...
Syncing TXs. Got:0 Skip:6 EndingTxid: null Continue: undefined
Finish Sync: New Txs: 0
Tx History synced. Total Txs: 0
onGoingProcess scanning null
Status update. hash:0 Try:0
onGoingProcess updatingStatus null
Wallet Status: {"wallet":{"version":"1.0.0","createdOn":1450264918,"id":"6c76ad39-9f3d-4fcd-a08b-51452e921336","name":"Personal Wallet","m":1,"n":1,"status":"complete","copayers":[{"version":2,"createdOn":1450264919,"id":"0440088643a8365a0f7017748d953923b5939702a6c76ff8a5f58670d371a15e","name":"me","requestPubKeys":[{"key":"03eed83f7581e1303921ef94af9740d72abea1af3641807a948f20227f012d7917","signature":"30440220344e531ae133cc35b47545181bb7f95b32b1bbd69ba2dbfa89a5e37e518d10a602203416d6403b16eabe66d092030f987aa9fdf39ec11b0e97cc623b1b0078a335c0"}]}],"network":"livenet","derivationStrategy":"BIP44","addressType":"P2PKH","scanStatus":null},"pendingTxps":[],"preferences":{"version":"1.0.0","createdOn":1450264953,"walletId":"6c76ad39-9f3d-4fcd-a08b-51452e921336","copayerId":"0440088643a8365a0f7017748d9 53923b5939702a6c76ff8a5f58670d371a15e","email":null,"language":"en","unit":"bit"},"balance":{"totalAmount":0,"lockedAmount":0,"totalConfirmedAmount":0,"lockedConfirmedAmount":0,"availableAmount":0,"availabl...
Writing: txsHistory-6c76ad39-9f3d-4fcd-a08b-51452e921336 []
Read: 178vXbohFFKvUpMx1MhjqhrBRHsyoF3wsi
Failed to verify backup: Private key mismatch
Read: 178vXbohFFKvUpMx1MhjqhrBRHsyoF3wsi
Binding touchstart elements...

**Comment by monsterbitar** [comment]
When reading these logs, I notice alot of NULL and undefined. I don't know what expected behaviour is, but assume the those are normal.

**Comment by matiu** [comment]
Thanks a lot for your update.

We were not able to reproduce any errors you are mentioning:
 - We run Copay on Android simulator 4.2.2
 - and on a hardware Samsung S2 (android 4.1) device 

Copay worked without any problems (import / export / verify backup / sign / etc), although the interface was really slow on the S2.  

- We also import your addresses on a wallet, and check it on the device and on the simulator, and we were able to see the history. 
- Finally, we dont see any error on the logs you sent.

 Unluckily I dont see any other way to move forward to make Copay work on your device.

**Comment by monsterbitar** [comment]
I will reflash and test again from a clean device with no games or other software installed, see if that has any effect. I doubt we'll be able to find the issue even if that solves the problem, but at least it's one more thing tested and removed from the list of possible causes.

**Comment by monsterbitar** [comment]
I have now re-flashed the device from official firmware and re-installed copay. The app still freezes if I leave it for a few minutes, and the backup process still writes a system entry: "Failed to verify backup: Private key mismatch".

**Comment by monsterbitar** [comment]
Is the session log stored on the filesystem, or can I change something to make it store itself to the filesystem so I can try and diagnose the freeze issue?

**Comment by monsterbitar** [comment]
I found the apk files for previous releases and will downgrade and see if I can find the version that introduced the issues.

**Comment by monsterbitar** [comment]
The freeze issue is not present in 1.5.2, and importing the backed up private wallet from 1.6.3 worked in 1.5.2.

Will try 1.6.1 now.

**Comment by monsterbitar** [comment]
UI freeze is present in 1.6.1, but backup verification works.

**Comment by monsterbitar** [comment]
UI freeze is present in 1.6.2, but backup verification works.

**Comment by monsterbitar** [comment]
UI freeze is present in 1.6.3, but backup verification works.

**Comment by monsterbitar** [comment]
My initial testin (1.6.2) and my testing after a full reset of my device (1.6.3) both give different results compared to when installing from the signed apk's on the releases page. Will re-install via google play and check if the issue remains.

**Comment by monsterbitar** [comment]
Using v1.6.3 from google play can verify the backup, but freezes the UI.

**Comment by monsterbitar** [comment]
I will restore back to 1.5.2 and use that for a few days, to ensure that the freeze issue is not present even during longer periods and under stress.

**Comment by monsterbitar** [comment]
I've now run on 1.5.2 for a couple of days and it works as intended, I have no issues at all with that version. I don't know how to progress from here since I'm not familiar with the  build/distribution process, but I've narrowed down the issues to be related to the update after 1.5.2.

**Comment by monsterbitar** [comment]
@matiu I assume there's nothing we can do from here, so if you wish you can close this report as unresolved and I will then stick to 1.5.2 until I change hardware, which should happen in a year or two I think.

**Comment by matiu** [comment]
thanks for the update. Please if you have any other information about this share it here.

**Comment by monsterbitar** [comment]
Running latest version today I rarely see the lockup but the backup verification process is still broken. After selecting the words in the proper order it fails with "Failed to verify private key". Using the same words to import on the desktop version fails with "Could not import: Wallet not registered at Wallet Service" despite the wallet being created without issues on the phones.

I've checked that both the phones and desktop verstion list the same server url and same derivation path.

Updating the desktop version to the latest (1.9.4) and retrying to import gives another error: "Could not import: Not Authorized".

**Comment by monsterbitar** [comment]
Making a wallet from the phones and using the desktop version as a copayer creates fine as well, and the desktop version can backup and verify the backup properly but the phones fail to verify the backups.

**Comment by matiu** [comment]
thanks for the update.

**Comment by thephez** [comment]
@monsterbitar Were you trying to import a Testnet account from a seed when you got the "Could not import: Not Authorized" error?  I've encountered that issue and (in my case) am guessing it's trying to recreate a wallet on the main network since there's not an option to designate TestNet on the Import screen (unlike the Create screen).

**Comment by JDonadio** [comment]
@monsterbitar if you display the advanced options in import tab you can see the derivation path, please try to change it to " m/44'/1'/0' " to import a testnet wallet

**Comment by monsterbitar** [comment]
@thephez, @JDonadio:

Thanks for commenting, but I'm convinced this is not a testnet wallet for many reasons. For exampe, it works just fine to import the seed words into the desktop version as well as the mobile version of copay on a different phone model.

@matiu:
While we still have two W6610 phones in my household, the money has been moved over we are no longer relying on those phones to handle our funds and I believe there is no more that can be done to solve this issue at the moment. I feel safe knowing that even if the phone cannot verify the backups, I can verify and use them on the desktop or other phone versions and the phones can still spend (the part that multisig is there for) even though they refuse to show the QR's on the recieve tab.

This bug can be closed as wont-fix or similar, as I will soon no longer be able to provide more defails (not using the phones). One quick idea I'll drop here is a setting for allowing it to show the recieve tab and allowing it to remove the seed words even if the phone does not have the backup status set, as that would allow me to completely 100% work around the issue.

Thanks for all the attention, and keep doing the good work, I still use copay as my primary and only wallet - it has everything I need in a convenient package :)
