### ISSUE TITLE
Allow multiple copayers for a single shared wallet on the same machine

### ISSUE THREAD

**Issue by gabegattis** [bitpay/copay#3688]
As a developer, I need to be able to use/test multi-sig functionality on my machine. I want to create an m-of-n wallet and control all n private keys from the same copay instance on the same machine. Currently, this is not possible. If I try to join a wallet that I have already created in my copay instance, I get the error, "Cannot join the same wallet more that once". I also cannot run multiple copay instances at the same time on the same machine.

One or both of these limitations should be removed. From a high level, I do not see why there must be either of these limitations, though I would like to know if there is a particular technical challenge in fixing this.

**Comment by matiu** [comment]
As a workaround you can run Copay in different browsers or/and in browser's
private mode.

**Comment by vmatekole** [comment]
This also an issue for HW wallets e.g. creating multisig with two Ledger wallets...

**Comment by martindale** [comment]
Strong support for this case.  It feels like an arbitrary limitation.

**Comment by matiu** [comment]
Having multiple keys on the same device goes against the multisig core security features.

This could be allowed maybe on testnet or for hw wallets, but the effort to implement it on this case does not seems to be worthy. It is still possible to use the desktop version + the chrome version + other chorme app, etc.

**Comment by benma** [comment]
It would be great if one copay instance could act as multiple parties in case of HW wallets. After all, the keys on the HW wallet are not with the copay instance, so there is no security problem. It would make it much easier though to create a multisig account where you want copay itself to be one party, and HW wallets to be the other parties.

**Comment by dabura667** [comment]
@benma You can work around this by using different Chrome profiles.

1. Create three user profiles on Chrome
2. Open Copay on each (You can do this at the same time) you will have 3 Copay windows open with 3 different wallet data.
3. Create multisig on one and join with the other two.

You can speed up signing by creating a Chrome shortcut to a specific profile. I have 4 profiles each with a unique Chrome-esque icon. if I click them in order and open Copay from each of the windows, I can go multisig all I want with my HW wallets.
