### ISSUE TITLE
Regarding XPUBS

### ISSUE THREAD

**Issue by alejoacostaa** [bitpay/copay#3691]
Hello,
It would be cool and useful if Copay for IOS had the option to import XPUBs to be able to monitor the wallets balance and generate new addresses, just like the app Sentinel for android does. Just a suggestion as there is literally no current app for IOS that has such feature, so I thought it would be wise to suggest it.
Alejo.

**Comment by matiu** [comment]
While it is not allowed in the way you present it, it is possible to export a Copay wallet without the xPrivKey and then import it, so  you can see the wallet balance / TX and even propose TX, but you can't sign TXs.
