### ISSUE TITLE
Add watch only address

### ISSUE THREAD

**Issue by iraszl** [bitpay/copay#3695]
Add ability to import a public Bitcoin address to a new wallet.

Typical use case would be a reusable public cold wallet where funds arrive regularly for donation. The owner of the address would want to be able to follow the incoming funds and the final balance in his copay account, but he would not want the private key to be stored on the device to remove the possibility of a security breach.

bitWallet has such functionality to add a public key without adding a private key.

**Comment by notf0und** [comment]
This option is available on current version of Copay.
All you need to do is:
Open wallet preferences->Advanced->Export Wallet
And enable the "Don't include private keys" option
Later import this watching-only wallet and import on the another devices

**Comment by iraszl** [comment]
Thanks, but what if a user wants to import an existing watch only address created on another device?

**Comment by dabura667** [comment]
No. This is not possible currently.

Adding watch addresses encourages address reuse. So NACK.

But maybe adding an xpub to create a watch only address from scratch is a good idea.

Currently, the app can only create a watch-only wallet by first inserting the private key to generate the wallet first, then delete the private keys later.

It would be nice to create a new wallet from the wizard, specify an xpub and get a brand new wallet object on bitcore-wallet-service that is a watch-only wallet from the start without ever needing to enter the private keys on any online device.

**Comment by matiu** [comment]
Adding addresses to monitor (which are not part of the wallet HD tree) is not on the roadmap. The solution we propose for that is having a "read-only" copy of the wallet, as @dabura667 suggested.
