### ISSUE TITLE
Show payment requests in activity feed

### ISSUE THREAD

**Issue by XBTdev** [bitpay/copay#3696]
Should payment requests be displayed in the activity feed?  There could be an option to delete / cancel them. 

We could also let the user add notes or titles to the payment requests. 

For someone who makes multiple payment requests, this works greatly simplify the process of figuring out who paid. 

Email notifications could also be aware if they are payments from a payment request.

**Comment by matiu** [comment]
This is already implemented (payment request (from payment protocol) info is showed) and notes are supported on the upcoming 2.0 version.
