### ISSUE TITLE
iOS: Error message "Could not access storage" when app starts

### ISSUE THREAD

**Issue by reneoelke** [bitpay/copay#3697]
Some days ago everything was fine. But today the error message "Could not access storage" appears when the app starts (see screenshot). The I closed the app, restarted the phone and updated the app. But without success, the error message is the same. Now I can't use the app.

![datei 18 12 15 09 55 14](https://cloud.githubusercontent.com/assets/835041/11893070/ca608348-a56d-11e5-953c-3c26309ced50.png)

What can I do? Are all my wallets lost?

(Last week I tried to import the wallets into the desktop app with the wallet seed. But without success. Wallets were created but empty.)

**Comment by reneoelke** [comment]
@matiu or @cmgustavo Could someone of you confirm this error? And perhaps answer with a little help. Thanks.

**Comment by DrHayt** [comment]
I am fortunate that I back up frequently as I was hit by this several times in the 1.6.x series.  I do not appear to be affected by it anymore, but that could be happenstance.

**Comment by matiu** [comment]
Hey, sorry the delay in the response. Recovering from the seed should
Work without problems. Please
Let me know if the issue persist and we will be happy to help.

**Comment by reneoelke** [comment]
As i said, i wanted to create a seed backup. But precisely at this time the error occured. Since then i couldn't use the app anymore. So i decided to reinstall it. The wallets including their bitcoins where lost. Now everything is working fine, the error has not occured so far. I created new wallets incl. making a seed backup before i got coins in it.

**Comment by matiu** [comment]
ok, please let us know any other problem.
