### ISSUE TITLE
"Updating Wallet..." graphic obscures other buttons

### ISSUE THREAD

**Issue by gabegattis** [bitpay/copay#3699]
![screenshot from 2015-12-18 11 30 41](https://cloud.githubusercontent.com/assets/4419243/11901672/d16a0e54-a57a-11e5-89e0-0c08b170e878.png)

In this example, the "Updating Wallet..." graphic is blocking the "GENERATE NEW ADDRESS" button. I am unable to click that button until the graphic goes away.

I am using the v1.6.3 linux desktop app

**Comment by matiu** [comment]
fixed in current version.
