### ISSUE TITLE
UNCONFIRMED TRANSACTION for the past 3 hours.

### ISSUE THREAD

**Issue by justsum1uknow** [bitpay/copay#3702]
Basically, I received 27 dollars, received 90 cents, sent 27.90 dollars, the first two confirmed, the last one is the fucking slow kid stuck there.  
Will I ever get my money back or has it just fucking magically disappeared?
27 dollars: https://insight.bitpay.com/tx/7706424a62c3e3170e686f07b0c717bfa2443205236d0daf89aafe4d65d492e2

90 cents: https://insight.bitpay.com/tx/a2cc543f587d79bddc955bb5069e6c9b44c9f77b1555d50bcd18060f24014c37

27.90 dollars: https://insight.bitpay.com/tx/c2ba2b9a00cfa2510910460bb186767f867ecc3342ec32809dc565a4dde74ece

**Comment by XBTdev** [comment]
Looks like there is a very small "almost dust" output.

Yes, you will get your money back. Bitcoins can't 'disappear'... if the transaction doesn't confirm soon nodes will drop it from the mem pool and you can spend it again.

You can also try double-spending it with a higher fee.

Note to copay devs: maybe we should display a warning to user if a transaction has a very small output (under 1000 satoshi).

**Comment by justsum1uknow** [comment]
How do I double-spend it when I have 9 bits on my wallet?

**Comment by justsum1uknow** [comment]
On average, how long does it take to get the money back?

**Comment by bitcoinfees** [comment]
> maybe we should display a warning to user if a transaction has a very small output (under 1000 satoshi).

The ideal case would perhaps be to dynamically adjust the dust limit, based on the fee rate you are paying.

For example, if you consult Bitcoin Core's estimatefee and it returns say 0.0002 BTC / kB for a fast confirmation time, then you know the network's minrelaytxfee is < 0.0002.  The corresponding dust threshold would be 0.0001092, and this is more or less guaranteed to be network-safe.
