### ISSUE TITLE
Let us set up our own TXID fee!

### ISSUE THREAD

**Issue by YiumPotato** [bitpay/copay#3709]
My bitcoin transaction got stuck. Set the fee to be a minimum of 10k or else the miners wont even add them to a block.. 

https://blockchain.info/tx/143233488a085474dcab0ccad9b87e83acb2cfd86eeaecac45056e9f785a1765

It's been at "Very Soon" forever.

**Comment by dabura667** [comment]
Your transaction is paying over 0.00025 BTC per kB, which is waaaay more than enough to get you confirmed within 2 blocks or so. Most likely 1.

There is another reason why your transaction is not confirming.

https://insight.bitpay.com/tx/43405131d1c3dfdd12248be4ac648aa013bcd40e977812ddefa393995d4bbb51

This transaction is used in the transaction you linked, and it is not confirmed yet.

A child transaction CAN NOT confirm until ALL PARENT TRANSACTIONS ARE CONFIRMED.

The transaction I have linked here only has 0.000033 BTC per kB, which is extremely low.

**Comment by YiumPotato** [comment]
ok thank you! By the way, if that scenario happens, does the first transaction get to confirm normally? and then the other? Sorry!
