### ISSUE TITLE
Send all no longer works

### ISSUE THREAD

**Issue by BitpopCoin** [bitpay/copay#3710]
The latest version is leaving random change behind. I tried it twice now I got tiny change I can't use.

**Comment by BitpopCoin** [comment]
Android

**Comment by dabura667** [comment]
+1 Same here. I have 4 bits left after "Sending All" on my wallet.

**Comment by isocolsky** [comment]
I suspect this issue is related to having the "Use unconfirmed funds" set to OFF (i.e. only send confirmed funds) and trying to "Send all" while there are unconfirmed funds in the wallet. Does this sound like something you might be running into?

**Comment by BitpopCoin** [comment]
No mine is on. But it was unconfirmed. It was 1 btc clean input. The only input I had.

**Comment by isocolsky** [comment]
Was that 1 btc input confirmed on the same "session" (meaning, you didn't close/repoen Copay) in which you performed the send all?

**Comment by BitpopCoin** [comment]
Possibly it confirmed very quickly

**Comment by dabura667** [comment]
Mine was exactly 0.0002 BTC and had been confirmed for a long time before opening the app.
I had unconfirmed spend on, and fees were set to normal.
I was using my own BWS server.

**Comment by isocolsky** [comment]
Thank you for your valuable feedback. We were able to identify the issue and we are working on a fix. Will keep you posted.

**Comment by BitpopCoin** [comment]
Thank you

**Comment by matiu** [comment]
This is fixed in the upcoming version 1.7.x. Thanks!
