### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by xbtdev** [bitpay/copay#3713]
Copay has a unique server-assisted design that makes it idea for bitcoin subscriptions.

One of the limitations of a push-based payment system (bitcoin) is the relative inconvenience of subscription payments. But Copay, with a server-assisted model, could store a pre-signed tx on BWS that would be broadcasted by BWS at the scheduled time.

The user could always cancel a subscription from within copay to stop future payments. The inputs could be 'locked' within copay to avoid double-spending them by accident. If the user tried to spend those inputs the wallet could alert the user that they would need to cancel the subscription to make those inputs spendable.

**Comment by dabura667** [comment]
I'm not buying the UX you're explaining.
Personally I think it would be too complicated and a hassle.

**Comment by XBTdev** [comment]
> I'm not buying the UX you're explaining.

Do you think there is any feasible UX for implementing subscriptions in a wallet where keys are user-controlled? Coinbase accounts offers subscription features, but I don't currently know of any wallet that does.

I have about 10 clients who pay me monthly subscriptions with bitcoin... but they have to manually perform each payment and because of that its not nearly as convenient as using a pull payment system (Credit Cards).

**Comment by dabura667** [comment]
Why not just make a P2SH script that is like this:

```bash
OP_IF
    <TIME_A> // midnight the 1st of April etc.
    OP_CHECKLOCKTIMEVERIFY
    OP_DROP
    <PUBKEY_A> // pubkey owned by receiver of subscription money
    OP_CHECKSIG
OP_ELSE
    <PUBKEY_B> // pubkey owned by sender of subscription money
    OP_CHECKSIG
OP_ENDIF
```

Then you could have the wallet automatically send parts of change outputs to those P2SH scripts and the subscribee would just collect the money after a certain time, while the original owner of the bitcoin has the ability to remove them at any time if they wish.

However, this would be based on the assumption that your balance is always higher than one payment worth, and that you make at least one transaction per period of payment...

If this was hidden in the background from the user, by removing the utxo from your wallet after the date, and services would gather payments up asap, I think it would be doable, and pretty good UX...

However, those assumptions are very big assumptions, as well as the fact that the user, if they knew what they were doing, could reclaim the funds at any point even after the payment time has past...

But nothings perfect, I guess.

**Comment by matiu** [comment]
I think this is more a business use case than a wallet feature. If there is a need for it, sponsored by a business, we can implement it.
