### ISSUE TITLE
Bad signatures 

### ISSUE THREAD

**Issue by mmitech** [bitpay/copay#3719]
I am reopening this ticket since copay is gaining popularity and for the sake of visibility for developers (especially altcoin developers)

Original issue https://github.com/bitpay/copay/issues/3674
***Still trying to solve this.*** I think the Bad signature is caused because of the transaction timestamp, this is a PoW/PoS coin so it has a different header than Bitcoin.

I implemented these changes: https://github.com/bitpay/bitcore-lib/compare/master...mmitech:master
The same changes were implemented in bitcore and angular-bitcore-wallet-client, I am using copay version 1.4 (so bitcore-wallet-client is not needed here).

The same changes worked on [LEOcoin](https://github.com/Leocoin-project/LEOcoin)(also a yacoin fork) which is a PoW/PoS scrypt-jane hybrid coin but changing only the networks parameters for [Creditbit](https://github.com/creditbit/creditbit) doesn't seem to be enough!!

any insights on the issue and/or suggestions on how to solve the problem would be really appreciated.

**Comment by mmitech** [comment]
BTW, I got Bitcore and Insight-api to support  PoW and PoS at the same time, stake reward and transactions are working perfectly. check it here https://creditsight.creditbit.org

**Comment by dabura667** [comment]
You're not signing the extra timestamp you added... include the timestamp in the data to be signed.

**Comment by mmitech** [comment]
@dabura667  how and where do I include it exactly ?

**Comment by dabura667** [comment]
the transaction proposal.

And you also need to include it in the temporary tx it builds in the walletutils sign txp function.

You have the to and from Buffer alleys caught well, but unfortunately Copay signs a transaction that it builds from scratch without using serialized buffers, so it ducked your code completely.

I don't know how the timestamp is supposed to work, but I think your problem would be solved by the following:

1. Add timestamp initialization upon Transaction creation in bitcore-lib (just under the this.inputs = []; area)
2. Modify the transaction proposal object to hold a timestamp.
3. Modify the transaction sign and verify functions account for timestamp.

**Comment by mmitech** [comment]
Great, so:
1- this.timestamp = transaction.timestamp;
2- which file contains the proposal and where should I add the timestamp ?
3- which file contains the verify function and how I should add the timestamp ?


Here you can check how we got the timestamp https://github.com/creditbit/creditbitcore/blob/master/lib/Block.js#L89

I know that I might be slow/slowing you down, but JS is not my play ground, however this was a really fun learning experience for me, I still have allot to learn.

**Comment by dabura667** [comment]
1. Should be more like this.timestamp = Math.floor(new Date().getTine()/1000)

For 2 and 3, there are txp sign and txp to transaction functions in bitpay/bitcore-wallet-utils you will need to change, but other than that, I am not sure.

The issue is resolved: include your timestamp bytes into the transaction being signed, as well as keep the timestamp data in the transaction proposal so you can use it to reproduce the signatures for validation.

How you do that is an implementation detail directly related to your altcoin, so I think this should be an issue on your fork, not here.

Any other alts should be aware that adding or removing necessary data to or from the transaction (in comparison to bitcoin) is hairy and remember to also add/remove said information to/from the transaction proposal object as well.

**Comment by mmitech** [comment]
OK I will try to figure it out, meanwhile all suggestions are welcome (in case this one doesn't work), also feel free to PR https://github.com/creditbit?tab=repositories

**Comment by mmitech** [comment]
Issue solved, these are the changes needed in bitcore-lib and angular-bitcore-wallet-client https://github.com/bitpay/bitcore-lib/compare/master...mmitech:master

Otherwise I solved the problem by adding txntime and time to transaction in the rpcwallet.cpp (coin source code).
https://github.com/creditbit/creditbit/commit/2c316c99ad561b92b8904c39cfefda5f7d5b86ba
