### ISSUE TITLE
Identifying source of incoming payments

### ISSUE THREAD

**Issue by XBTdev** [bitpay/copay#3721]
I use copay for receiving payments from clients for recurring monthly, quarterly and yearly payments, some clients also pay at irregular intervals.

Currently, the I can't identify the source for these payments within a single copay wallet, so I have to create a separate wallet for each of them so that I can name the wallet "from $clientName", requiring me to backup those seeds for each separate wallet (not a convenient thing either, since my backup process requires creating multiple copies of the seed in a secure environment).

I'm pretty sure I'm not alone in experiencing the inconvenience of this usability issue. Suggested solutions including (1) allowing user to label addresses #1189 #2511 #1492  and #2499 and (2) allowing user to create sub-accounts without requiring a new seed and backup each time #3055 or (3) showing payment request activity in activity feed (labeling implied) #3696.

Are there any planned future changes that would make it more convenient to label an address so incoming payments could be distinguished from each other?

I imagine address labeling is the easiest solution to this problem. If I could label addresses from either the 'Receive' tab or from Advanced > Wallet Information that would be a complete solution to this usability issue.

**Comment by matiu** [comment]
While address labelling would be nice, we are working on Payment Code what should solve this issue in a better way. You will be able to label incoming txs from certain payment codes, without the need of reusing addresses.

**Comment by XBTdev** [comment]
Oh, that is great news!! Bip47 payment codes? Very happy to hear this is being worked on. Is there an eta?

**Comment by vaikekana** [comment]
+1

**Comment by dan-da** [comment]
Sounds good, but I imagine it will be quite some while until all wallets support payment codes.  Address labelling is something that can work for payments from any wallet software now.

**Comment by bitedgeco** [comment]
Coming from Electrum to Copay being able to label address is the only thing I miss.

+1

**Comment by martindale** [comment]
Can we have a simple address label feature to hold us over until we get BIP47 Payment Codes?

**Comment by matiu** [comment]
Copay 2.0 allows to add notes to all transactions, incoming and outgoing. This notes are encrypted and shared between copayers.

**Comment by bitedgeco** [comment]
Sounds great. what's the timeframe on Copay 2.0?

**Comment by matiu** [comment]
@bitedgeco Probably this week.
