### ISSUE TITLE
Transaction confirmation

### ISSUE THREAD

**Issue by Pratist** [bitpay/copay#3725]
I had performed a send transaction on my mobile app (Windows Phone 8.1). 3 hours have passed but the transaction is yet to be confirmed . Sorry for the inconvenience caused . Further information about the transaction can be found in the screenshot. Thanks for looking into the issue.
![wp_ss_20151230_0001](https://cloud.githubusercontent.com/assets/16491474/12053917/c1369070-af43-11e5-93d5-5a9749b3779f.jpg)

**Comment by dabura667** [comment]
fees look good.

The only thing I could think would be the change output.

Recently Bitcoin Core raised the MIN_RELAY_TX_FEE default from 10 bits to 50 bits.

This would raise the DUST_LIMIT from 5.46 bits to x5 that, or 27.3 bits.

So a large number of nodes that raised their MIN_RELAY_TX_FEE from 10 bits to 50 bits, but your change output would only be valid for any node with MIN_RELAY_TX_FEE of 15 bits or less.

@cmgustavo @matiu @isocolsky 

To calculate dust limit, it's `546 * (MIN_RELAY_TX_FEE / 1000)` (all units in satoshis) so 1000 / 1000 * 546 is what we had before, now we have (5000/1000)*546...

dust calculation is done on BWS, correct?

Note to self: this small block BS is a PITA for user experience...

**Comment by Pratist** [comment]
Thanks for replying fast. My transaction is the last one (0.001 BTC) . Even that amount falls under the dust ?
Anyway , thanks again . Hope that the tnx gets confirmed

**Comment by dabura667** [comment]
@Pratist It doesn't matter who it is sent to.

If ANY of the outputs in a given transaction fall under the dust limit, your entire transaction is viewed as dust and will have difficulty confirming.

**Comment by Pratist** [comment]
@dabura667 Thanks very much for taking the time to answer and clarifying my doubts . Extremely sorry for troubling you ... Have a Happy New Year !
