### ISSUE TITLE
xPrivKey shown in session log?

### ISSUE THREAD

**Issue by dan-da** [bitpay/copay#3726]
I'm not sure if it is a security issue or not, but I noticed that the session log (in v1.6.3) contains entries like:

---
Read:
{"version": ...
"credentials": 
{..., "xPrivKey": "tprv...", "xPubKey": "tpub..."
---

I'm not familiar with tprv and tpub....?

Should such log entries be visible without requiring a password or something?

**Comment by dabura667** [comment]
tprv is for testnet

**Comment by matiu** [comment]
Well, the log is only seen by the user, and if the xPrivKey is encrypted, it will be shown encrypted...but we will hide it anyways, thanks.
