### ISSUE TITLE
Balance locked and BTC not received 

### ISSUE THREAD

**Issue by gwaghamare40** [bitpay/copay#3727]
my account balance id locked also BTC not receiced

**Comment by dabura667** [comment]
Did you sign the proposal?

How many more signatures does it need?

**Comment by adler-rok** [comment]
после перевода на мой идентификатор - на балансе 0
идентификатор заблокирован! на blockchain показывает что транзакция совершена.
что делать&

**Comment by chinh7** [comment]
https://github.com/bitpay/bitcore-wallet-service/issues/428

**Comment by adler-rok** [comment]
баланс в бумажнике не отображается(

**Comment by RussianNeuroMancer** [comment]
https://bitpay.github.io/copay-recovery/ 

И снова переведите средства себе, должны будут отобразиться.

**Comment by matiu** [comment]
This was probably related to a temporary BWS update problem.
