### ISSUE TITLE
My wallet doesn't see processed transactions

### ISSUE THREAD

**Issue by vitalylvov** [bitpay/copay#3728]
Hello, I created 3 multisig transactions and they was successfully processed by Bitcoin blockchain:
- https://blockchain.info/tx/7086b3da805afb33e1b9164e6f938b539b761ccb05063689e49ab18131b819d2
- https://blockchain.info/tx/6fe44e3ca890ae3e445e5861afcb8ecc812418f9bc60f990451996099ded1b45
- https://blockchain.info/tx/784e2af6c4824b226b0ae7b1b4c4414ea4607e06112791d9e66baa200ddbdb60

But my Copay Wallet doesn't see that, and by this reason I can't create any other transactions.

What should I do now?

**Comment by 21xhipster** [comment]
As copayer I also see that transactions with money stuck and can do nothing about it

**Comment by matiu** [comment]
Could you try to clear the transaction history cache and try again? 

(settings -> advanched -> transaction history -> clear cache)

**Comment by vitalylvov** [comment]
@matiu Thanks for attention and quick response. Problem self-resolved
