### ISSUE TITLE
I Lost my Phone 

### ISSUE THREAD

**Issue by Hundoknows** [bitpay/copay#3730]
I lost my phone with about 53 us dollars worth of bit coin and im looking for a way to retrieve or link it my wallet on my PC

**Comment by dabura667** [comment]
Did you write down the backup phrase?

**Comment by KeyJockey** [comment]
Hmm, you said "link it my wallet on my PC" but if that wallet on PC is Copay, copied or backup/restored as the one on your lost phone, then it's already the SAME WALLET: your bitcoin should be accessible there, hopefully, if that's what's happened? 

If not, and the lost phone was a totally different Copay installation, well then yeah hopefully you saved the 12 word backup phrase somewhere other than on the lost phone???

**Comment by matiu** [comment]
please reopen if still valid.

Ad @dabura667 mentioned, with the backup phrase you can restore access to your coins from any other device.
