### ISSUE TITLE
Top Android Bar is not being showing with the same color of Copay.

### ISSUE THREAD

**Issue by bitcoinuser** [bitpay/copay#3732]
Hi, I use Android 5.0.2, Hardware LG G2 and the top Android bar doesn't appear with the same color of Copay app (The top bar is being showing in black color).  Other apps works ok.
See my Copay screenshot
![screenshot_2016-01-01-20-57-41](https://cloud.githubusercontent.com/assets/1178856/12072550/e3e8a4f4-b0ca-11e5-8669-99b66dbe82e2.png)

**Comment by cmgustavo** [comment]
Hi @bitcoinuser , 
The Cordova plugin (https://github.com/apache/cordova-plugin-statusbar) can't modify the status bar on same versions of Android. We 'll try to update the plugin or report if it continues with the issue.

Thanks.

**Comment by matiu** [comment]
fixed on current copay version and Android 6
