### ISSUE TITLE
Application Error copay "I can not send Bitcoin"

### ISSUE THREAD

**Issue by Oliwier2555** [bitpay/copay#3733]
Hello,
I bought BTC for ** ** PLN and I make them **, **!
Normally I filled in the application form:
1.Wpisałem account number BTC
2.The unit value
3. I sent.
Unfortunately, I waited and even transfer has not been sent!
There was an error such as a shared account!
And my account is per user!

**Comment by matiu** [comment]
please reopen if still active. No sure if this issue is related to Copay.

**Comment by Oliwier2555** [comment]
REOPEN

**Comment by matiu** [comment]
Could you describe better the issue?

**Comment by Oliwier2555** [comment]
Otherwise, I can not

**Comment by matiu** [comment]
Ok.
