### ISSUE TITLE
message signing with BTC adress?

### ISSUE THREAD

**Issue by abarents** [bitpay/copay#3734]
Is this possible with Copay? Did not find the option yet..

**Comment by dabura667** [comment]
No, it is not.

**Comment by abarents** [comment]
Thanks! Thats really a swift reply..

Regards, Antoon.

-----Original Message-----

**Comment by peanut-brittle** [comment]
Is there perhaps some kind of workaround for this? The idea I had is to export the address(es) into another wallet program that can do the signing function. I tried this but it seems other programs don't want to use the .aes.json file. Suggestions?

**Comment by XBTdev** [comment]
Yes, there are workarounds. You can use recovery tool to extract private keys from backup file, or from seed.

Just created an issue to suggest that coinb.in add this to their browser tool: https://github.com/OutCast3k/coinbin/issues/38

also check this repo https://github.com/bitpay/bitcore-message

**Comment by peanut-brittle** [comment]
XBTdev, thanks for your helpful input. What exactly is "recovery tool" and how does one use it to extract private keys from a backup file or seed?

**Comment by XBTdev** [comment]
This is the recovery tool: http://bitpay.github.io/copay-recovery/

You can input your seed (for newer backups), or the backup file and password (older backup format) and it will generate the private keys for you.

Then you can import them into Electrum or Core or some wallet that supports message signing.

**Comment by peanut-brittle** [comment]
Strange, it's telling me it can't decrypt the private key even I just went and reset the password for it in Copay. Using the .aes.json file generated from the "export wallet" option in Copay should work fine for this recovery tool, right?

**Comment by XBTdev** [comment]
Try exporting the wallet json again from Settings > Advanced > Export Wallet 

The backup tool will require two passwords. The export password, and the spending password. You'll need to enter both to decrypt your private keys.

Also, I would highly recommend moving all funds to a new copay wallet that uses the new backup format (a seed instead of json file).

**Comment by XBTdev** [comment]
Update: found this and it works well https://github.com/weex/bitcoin-signature-tool

**Comment by matiu** [comment]
thanks for sharing.

On Thu, Jan 14, 2016 at 1:46 AM, XBTdev <notifications@github.com> wrote:

> Update: found this and it works well
> https://github.com/weex/bitcoin-signature-tool
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3734#issuecomment-171528853>.
>



-- 
BitPay.com

**Comment by peanut-brittle** [comment]
I tried the recovery tool again with a new backup file and it worked this time (instead of saying it couldn't decrypt the private key like before). But all it did was give me the ability to transfer funds from the wallet to a new address. So it must be getting the private keys from the backup to be able to transfer funds, but it gives me no easy way of getting the private keys, so I'm not any closer to being able to sign a message.

**Comment by matiu** [comment]
What is the use case for this?

**Comment by abarents** [comment]
With this You could "sign" a message to prove you are the owner of a btc address. So the one paying has the assurance he is paying the right guy...

Quite usefull...

-----Original Message-----

**Comment by XBTdev** [comment]
> What is the use case for this?

I've had to use it twice to prove I was the account owner on an exchange before they would reset 2fa. Its also very useful if you want a legally binding digitally signed contract from someone holding bitcoins. Its quite useful I think... definitely worth adding under advanced > wallet info > $address > Sign message

**Comment by XBTdev** [comment]
FYI, this thread is the same as previously closed thread #1537

**Comment by dan-da** [comment]
> What is the use case for this?

srsly?

**Comment by dabura667** [comment]
> So the one paying has the assurance he is paying the right guy...

This is not a valid use case, if the goal is to protect from MITM attacks, bitcoin message signing along is not enough.

1. This would indicate that the people have reason to believe there is an active MITM attack going on.
2. Alice wants to be sure Bob's address is really Bob's.
3. Bob signs 1ABC with the private key and sends it to Alice.
4. Eve intercepts this, signs 1DEF with her private key and sends 1DEF with the signature along to Alice.
5. Alice sees 1DEF signing their message, believes it's Bob's and sends the money.
6. MITM attack successful.

**Comment by dabura667** [comment]
> You could "sign" a message to prove you are the owner of a btc address.

This use case is a sort of "receipt to prove that you are the sender of bitcoin." But imagine the following situation and tell me whether you think the outcome is acceptable for the person asking proof.

1. Bob wants proof of ownership of at least 100 BTC before giving a loan. (Assume Bob thinks "signing a message to prove you are the owner of a btc address" is enough proof)
2. Alice pays Eve, who owns 5000 BTC, in order to sign the message on Alice's behalf using Eve's address.
3. Bob sees the address signed having 5000 BTC and gives Alice the loan.

**Comment by dabura667** [comment]
However, some websites / services who are "the cool hip crypto crowd" ask for signatures from their customers. So I understand why it would be nice.

It is not secure though.

**Comment by dan-da** [comment]
To be complete, there should be both message signing and verification.

Descriptions:
https://www.reddit.com/r/Bitcoin/comments/18qy88/bitcoin_message_signing_and_verification/

https://multibit.org/en/help/v0.5/help_signAndVerifyMessage.html

Some use cases:
https://bitcointalk.org/index.php?topic=70911.msg813815#msg813815

**Comment by dabura667** [comment]
@dan-da You are more than welcome to write up a pull request.

That doesn't make the feature any more useful, nor does it make the feature more urgent on the Copay to-do list.

I would like to point out the link you gave of use cases are from a post in 2012, and the rest of the thread many users gave valid points against the use cases given. Of course, no one objected to the feature itself (it's harmless), but the use cases given there do not have any merit and overlook major security flaws which they are based on.

Again, I want to repeat that I am not against the feature. I just see no use for it that isn't extremely flawed.

**Comment by JohnTitor1006** [comment]
So there is no way at all to extract a private key with the recovery tool: ( http://bitpay.github.io/copay-recovery/ )?

I am not looking to recover funds, but like *@peanut-brittle*, I need to sign a transaction with bitcoin core to prove ownership of a trading account in order to reset 2FA.

**Comment by matiu** [comment]
It is possible, but not straith forward.

Here are some options.

1- Using the seed
  a. go to https://dcpos.github.io/bip39/
  b. enter the seed
  c. check the addresses and priv keys below

2- using the file backup (wallet's export)
  a. enter the backup text https://bitwiseshiftleft.github.io/sjcl/demo/ and the password to decrypt it.
  b. in the decrypted text look for `xPrivKey` value
  c. go to https://bitcore.io/playground/#/hdkeys and enter xPrivKey value in ' Root HD Private Key
' and then enter the desired path below to get the corresponding private key.

3- using the recovery tool (need programming skils)

 a. check out the repository (https://github.com/bitpay/copay-recovery)
 b. add `console.log(path + index , derivedPrivateKey) ` at lin https://github.com/bitpay/copay-recovery/blob/gh-pages/js/services.js#L193
 c. run the tool with your backup and check the logs.

**Comment by ankeshkothari** [comment]
Hi - can you elaborate more on:
b. add console.log(path + index , derivedPrivateKey) at lin https://github.com/bitpay/copay-recovery/blob/gh-pages/js/services.js#L193 ?

I downloaded the copay-recovery files from github. But don't see a services.js file in it...

**Comment by johanneswilm** [comment]
@matiu: In solution 2, what is my "desired path"?
