### ISSUE TITLE
Copay on "Silk" Browser?

### ISSUE THREAD

**Issue by KeyJockey** [bitpay/copay#3736]
I was helping a friend look for a bitcoin wallet that'd run on his Kindle Fire tablet the other day, but unfortunately without any luck... I was hoping Copay would work there as (apparently?) Silk is a Chrome-based browser: is there any (easy) way to get that to work?  Any interest by the devs here in making a port for this platform, seeing as how Copay's one of the best multi platform wallets already?

**Comment by dabura667** [comment]
afaik Kindle Fire can run android apps, you just need to download the apk file and install it directly.

Here's the latest:
https://github.com/bitpay/copay/releases/download/v1.6.3/android-release-signed-aligned.apk

If they download this and go in their tablet settings to "Enable unknown apps" (or something like that) then they can just install the apk directly.

I am pretty sure this works.

**Comment by dabura667** [comment]
If my method doesn't work, this more technical method seems to work without rooting the device:

http://www.gizmag.com/how-to-install-google-apps-kindle-fire-hd-hdx/30736/

**Comment by KeyJockey** [comment]
Okay thanks dabura... cool, I'll link him to this page and see if he can try it.  I don't have an Android phone myself so can't do it here *but* pretty sure he can manage, if it's possible.  I'll report back here with results/info ASAP.

Also seems to me that it might still be a good idea to package up a nice specific version of Copay for this platform too, if that's reasonable?  Just 'cuz as I said, our searching for a good bitcoin wallet for this platform in his app-store didn't readily turn up anything I could immediately recognize

**Comment by dabura667** [comment]
Related:
https://developer.amazon.com/public/support/submitting-your-app

Looks like you can submit your apps for free, but that would be an extra step for each release.

@matiu @cmgustavo what do you think?

**Comment by j32ravens** [comment]
Thanks dabura, I followed your first set of instructions and these worked perfectly. No glitches as far as I can tell.

**Comment by KeyJockey** [comment]
Hey @j32ravens  :smile_cat: good to see U here. 

Very cool that it worked, welcome to the Copay family :stuck_out_tongue_winking_eye:

**Comment by matiu** [comment]
Thanks a lot for sharing that @dabura667 ! I have a Kindle Fire myself, will try it :)

For the moment, adding a new platform is not in our plans, but we can re-evaluate it later.
