### ISSUE TITLE
Export the seed as Qrcode

### ISSUE THREAD

**Issue by bitcoinuser** [bitpay/copay#3738]
I would like to be able to export the seed as Qrcode. Maybe encrypted?

**Comment by dabura667** [comment]
Why? I can't think of a good use for this.

**Comment by bitcoinuser** [comment]
I would like to be able to spend bitcoins with cold storage from mycelium app, scanning the seed from a Qrcode, instead of type the seed.

**Comment by dabura667** [comment]
This is Copay, not mycelium.

**Comment by matiu** [comment]
closed in favor of https://github.com/bitpay/copay/issues/3224
