### ISSUE TITLE
Feature For "Archive" Old Wallets

### ISSUE THREAD

**Issue by KeyJockey** [bitpay/copay#3739]
Feature Idea: would be nice to be able to "archive" old/unused wallets directly inside the Copay app in order to keep their transaction history and used addresses, info, etc _but_ still get the wallet OFF the active wallet list, to keep that cleaner...

Maybe only allow this IF the wallet is actually _EMPTY_ and/or has not been used in some set amount of time...?

{Edit} UPDATE: Seems to me this would be most appropriately implemented where the current "Delete Wallet" functionality is, i.e. it's a pretty extreme and irreversible thing now to totally _delete_ a wallet, so perhaps it might be better to have a sub-system where the unused/unwanted wallet _must_ be ARCHIVED, at first, and where it will be available to un-archive later if needed.  THEN, only from the _archived_ state, the user may be allowed to really, finally, fully, and irreversibly DELETE a wallet.

Thoughts?

**Comment by Derrick-** [comment]
I agree. This just crossed my mind a couple days ago when deleting a wallet. Just saving the seed would be nice, just in case.

However, this may complicate the UI and be confusing. I would expect objections to this to be that the seed should already be saved offline somewhere.

**Comment by JDonadio** [comment]
No quorum.
