### ISSUE TITLE
About importing wallet

### ISSUE THREAD

**Issue by cbuhka** [bitpay/copay#3753]
Hello, I have wallet made in Armory software, but I'm totally disappointed in software. How can I import wallet to copay? Via Import wallet file/text backup password from armory doe not work.
I can retrieve next data:
Secret phrase (password - encription)
PrivBase58
PrivHexBE
PublicX
PublicY
If in Copay importing I input encryption pass i receive answer: Could not decrypt files, check your password.

**Comment by matiu** [comment]
Do you have the 12 (or 15 or 24) wallet seed words ?

If so, you can go to 'New Wallet -> Create -> Advanced -> Specify Seed' and
enter the words.

On Fri, Jan 8, 2016 at 11:56 AM, cbuhka <notifications@github.com> wrote:

> Hello, I have wallet made in Armory software, but I'm totally disappointed
> in software How can I import wallet to copay? Via Import wallet file/text
> backup password from armory doe not work
> I can retrieve next data:
> Secret phrase (password - encription)
> PrivBase58
> PrivHexBE
> PublicX
> PublicY
> If in Copay importing I input encryption pass i receive answer: Could not
> decrypt files, check your password
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3753>.
>



-- 
BitPay.com

**Comment by cbuhka** [comment]
I do not want to make new wallet, I want to import existing.

**Comment by matiu** [comment]
you need to use 'new wallet' for importing a seed in Copay.

On Fri, Jan 8, 2016 at 12:04 PM, cbuhka <notifications@github.com> wrote:

> I do not want to make new wallet, I want to import existing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3753#issuecomment-170025993>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by cbuhka** [comment]
http://funkyimg.com/i/26dY6.png
http://funkyimg.com/i/26dY7.png

**Comment by matiu** [comment]
that is only for Copay specify backups, you need tog go to 'new wallet'.

On Fri, Jan 8, 2016 at 12:19 PM, cbuhka <notifications@github.com> wrote:

> http://funkyimg.com/i/26dY6.png
> http://funkyimg.com/i/26dY7.png
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3753#issuecomment-170029426>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by cbuhka** [comment]
Thank you for help but I was unable to add Installing Electrum I added without any problems

**Comment by matiu** [comment]
Sorry, I dont understand what you mean. What error do you get? Could you send a screenshot (hide the seed words)

**Comment by dabura667** [comment]
Armory does not use BIP39, so there is no way to import into Copay unless you sweep the wallet using the paper wallet sweep function.

1. copy the PrivBase58 value (make sure you delete any empty spaces)
2. paste it into the paper wallet sweep area.
3. The bitcoins in your address will be sent to Copay.

However, this is not "importing" but rather "sweeping"

There is no way to import Armory wallet into Copay. And importing private keys individually into Electrum is a bad idea. (The creator of Electrum himself says it's a bad idea)

**Comment by cbuhka** [comment]
Now I have problems importing Electrum vallet.

**Comment by dabura667** [comment]
@cbuhka This is not the place for posting issues with Electrum.

Nothing in Electrum or Armory is compatible with Copay.

Please make a new Copay wallet and send your bitcoins to Copay.

If you keep messing around with your wallet, you might accidentally ruin it. Please stop.

**Comment by CopayZhujili** [comment]
Hello, good about copay wallet, please help me, my phone restored factory settings, and then use the 12-digit phrase import, was told that the need to import the password, but I have set up a 4-digit pin, so Use the four-digit pin input into the results of the emergence of this information "wrong number of recovery words: 1".

**Comment by dabura667** [comment]
You need to type in your 12 word phrase with spaces.

Is your phrase Chinese? Please add one space in between each symbol.

**Comment by CopayZhujili** [comment]
Thank you very much for your answer, after each Chinese secret language with spaces,
The error number changed from the original 1 
to 11 (error! Wrong number of recovery words: 11)

![default](https://user-images.githubusercontent.com/30965444/29250275-4f4aad8e-8016-11e7-9fba-5eb3dc4eac42.png)

**Comment by CopayZhujili** [comment]
dabura667 Thank you very much for your answer, has been successfully restored!
