### ISSUE TITLE
Any problem running multiple Chrome extension of Copay?

### ISSUE THREAD

**Issue by KeyJockey** [bitpay/copay#3759]
Hey Folks: 

I want to try running the Copay wallet CHROME extension on more than one instance of Google Chrome, on an old laptop I have -- planning to try it by using first the normal Chrome full installation *but* then also set up a completely different wallet on an instance of the alternative "Iron Browser" Chrome rebuild, running in its "portable app" version.

Since the Iron browser "portable" keeps its profile and cache etc all in its own folder I am assuming the two instances of the Copay extension will be adequately isolated, to hopefully not cause any problem for each other??  But just thought I'd check here first to be sure this is okay?

OR is something like this seriously "not recommended"...?  LOL

I don't want to trash my main Copay wallet instance doing this, but it still would be helpful to have a second "portable" install of the wallet running under the (very cool) Iron Browser portable setup.

Let me know what y'all think... thanks :smile_cat:

**Comment by matiu** [comment]
As long as the file are kept separately, there shouldn't be any problem,
but I didn't tried that.

On Mon, Jan 11, 2016 at 1:43 PM, KeyJockey <notifications@github.com> wrote:

> Hey Folks:
>
> I want to try running the Copay wallet CHROME extension on more than one
> instance of Google Chrome, on an old laptop I have -- planning to try it by
> using first the normal Chrome full installation *but* then also set up a
> completely different wallet on an instance of the alternative "Iron
> Browser" Chrome rebuild, running in its "portable app" version
>
> Since the Iron browser "portable" keeps its profile and cache etc all in
> its own folder I am assuming the two instances of the Copay extension will
> be adequately isolated, to hopefully not cause any problem for each other??
> But just thought I'd check here first to be sure this is okay?
>
> OR is something like this seriously "not recommended"? LOL
>
> I don't want to trash my main Copay wallet instance doing this, but it
> still would be helpful to have a second "portable" install of the wallet
> running under the (very cool) Iron Browser portable setup
>
> Let me know what y'all think thanks [image: :smile_cat:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3759>.
>



-- 
BitPay.com

**Comment by KeyJockey** [comment]
Thanks for reply @matiu -- I went ahead and installed it and "so far so good" : everything seems to be working okay, so far.

I'll report back here if/when anything goes wrong, but hopefully it won't :smile:

**Comment by matiu** [comment]
thanks for the update!

On Wed, Jan 13, 2016 at 11:40 AM, KeyJockey <notifications@github.com>
wrote:

> Thanks for reply @matiu <https://github.com/matiu> -- I went ahead and
> installed it and "so far so good" : everything seems to be working okay, so
> far.
>
> I'll report back here if/when anything goes wrong, but hopefully it won't [image:
> :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3759#issuecomment-171310988>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!
