### ISSUE TITLE
Transaction issue: coins withdrew, but unconfirmed, and never arrives

### ISSUE THREAD

**Issue by startjoinadmin** [bitpay/copay#3761]
Hi,

A team at Startjoin has made an Andriod app - StartWallet as port of copay and bitcore product. We have a couple of users who are struggling with unconfirmed transactions, whilst the coins are taken out of the account, they never arrive at the destination.

The team is looking into this but would like some advice from copay too, which StartWallet is based on:

![example-01](https://cloud.githubusercontent.com/assets/5268806/12289327/bd3f324e-b9d2-11e5-989a-d88cef11c532.png)
![example-02](https://cloud.githubusercontent.com/assets/5268806/12289326/bd3f1c28-b9d2-11e5-9e5b-1440e499b017.png)
![example-03](https://cloud.githubusercontent.com/assets/5268806/12289324/bd3c3850-b9d2-11e5-843c-a424e9d7c26b.png)
![example-04](https://cloud.githubusercontent.com/assets/5268806/12289329/bd3f8316-b9d2-11e5-876e-334b87530dfa.png)
![example-05](https://cloud.githubusercontent.com/assets/5268806/12289328/bd3f61ba-b9d2-11e5-8ba1-6cd73da9e35b.png)
![example-06](https://cloud.githubusercontent.com/assets/5268806/12289325/bd3d1b44-b9d2-11e5-8c5c-e1c55d0d5899.png)

**Comment by matiu** [comment]
Thanks for the information. We dont support alt-coins so I will close the ticket, you should probably link the fork so others can respond the issue in the fork's issue tracker.
