### ISSUE TITLE
Issue creating a shared wallet.

### ISSUE THREAD

**Issue by bitcoinuser** [bitpay/copay#3766]
Hi, 

I'm trying to create a shared wallet (2of2) with the seeds from my greenaddress.it wallet, but I'm unable. This message show: Error creating wallet: Key already associated with an existing wallet.

What is the reason to not allow?

Thanks

**Comment by matiu** [comment]
you cann't join the multiple times the same wallet on the same device. This restriction is there  because the idea of multisig is to have use it from different device to make hacking the wallet more difficult (the message has not to do with the fact the keys are from greenaddress).

**Comment by bitcoinuser** [comment]
But I'll use the seed on different devices. How copay knows the seed is already used?

**Comment by matiu** [comment]
Sorry, I think I have responder incorrectly the first time.

Different copayers need to have different seeds.  You cann't use the same seed in to different copayers.
