### ISSUE TITLE
Issue with copay android app v1.6.3

### ISSUE THREAD

**Issue by j-vern** [bitpay/copay#3768]
Hi,

I have a copay multi sig wallet. It's working well on desktop but on the Android version and I can see the transaction proposal but I cannot validate the transaction: every time I try there is an error message "failed to retrieve from server".

The keys are stored on your servers.

Any way to fix the issue?

**Comment by matiu** [comment]
Keys are never stored on servers. 'failed to retreive from server' does not sound a Copay message. What version are you using on Android?

**Comment by j-vern** [comment]
The exact error message is "Server response could not be verified". I use the app v1.6.3 as described in the issue. Now on windows desktop I have the same issue. The version used is the v1.8.1

**Comment by matiu** [comment]
Could you try using the same version on both platform? Please let us know
if that helps.

On Tue, Feb 2, 2016 at 4:54 AM, J Vern <notifications@github.com> wrote:

> The exact error message is "Server response could not be verified". I use
> the app v1.6.3 as described in the issue. Now on windows desktop I have the
> same issue. The version used is the v1.8.1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3768#issuecomment-178431796>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by j-vern** [comment]
I did. It does not help unfortunately.

*William PIQUARD*
Business Developer.

+852 9681 1930
william@gatecoin.com

[image: Inline image 1]
*Gatecoin Limited*
1804, Lucky Centre
165 Wanchai road
Hong Kong


*Gatecoin.com <https://www.gatecoin.com/>*
*@Gatecoin*
<http://t.sidekickopen36.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3LjyFqW2zWKb23N1L5nW7dKLV856dP1Cf1lt-ld02?t=https%3A%2F%2Ftwitter.com%2FGatecoin&si=5603526086754304&pi=27c529c0-0f7e-4060-c921-de8afc44ca71>

**Comment by matiu** [comment]
Did you delete all pending TX proposals, and created a new one with version
1.8.x?

On Tue, Feb 2, 2016 at 7:44 AM, J Vern <notifications@github.com> wrote:

> I did. It does not help unfortunately.
>
> *William PIQUARD*
> Business Developer.
>
> +852 9681 1930
> william@gatecoin.com
>
> [image: Inline image 1]
> *Gatecoin Limited*
> 1804, Lucky Centre
> 165 Wanchai road
> Hong Kong
>
>
> *Gatecoin.com <https://www.gatecoin.com/>*
> *@Gatecoin*
> <
> http://t.sidekickopen36.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3LjyFqW2zWKb23N1L5nW7dKLV856dP1Cf1lt-ld02?t=https%3A%2F%2Ftwitter.com%2FGatecoin&si=5603526086754304&pi=27c529c0-0f7e-4060-c921-de8afc44ca71
> >
>
> On Tue, Feb 2, 2016 at 6:33 PM, Matias Alejo Garcia <
> notifications@github.com> wrote:
>
> > Could you try using the same version on both platform? Please let us know
> > if that helps.
> >
> > On Tue, Feb 2, 2016 at 4:54 AM, J Vern <notifications@github.com> wrote:
> >
> > > The exact error message is "Server response could not be verified". I
> use
> > > the app v1.6.3 as described in the issue. Now on windows desktop I have
> > the
> > > same issue. The version used is the v1.8.1
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/bitpay/copay/issues/3768#issuecomment-178431796>.
> > >
> >
> >
> >
> > --
> > Matías Alejo Garcia
> > @ematiu
> > Roads? Where we're going, we don't need roads!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/bitpay/copay/issues/3768#issuecomment-178500828>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3768#issuecomment-178503570>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by j-vern** [comment]
I installed copay on a new device, there was no pending proposal and I can
create a proposal but I cannot sign proposals from the other people have a
signature the multi signature wallet we share.

*William PIQUARD*
Business Developer.

+852 9681 1930
william@gatecoin.com

[image: Inline image 1]
*Gatecoin Limited*
1804, Lucky Centre
165 Wanchai road
Hong Kong


*Gatecoin.com <https://www.gatecoin.com/>*
*@Gatecoin*
<http://t.sidekickopen36.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3LjyFqW2zWKb23N1L5nW7dKLV856dP1Cf1lt-ld02?t=https%3A%2F%2Ftwitter.com%2FGatecoin&si=5603526086754304&pi=ab10a82c-42fa-43c1-f355-f358a716dded>

**Comment by matiu** [comment]
So, just to be clear,

1. you can create a proposal and others can sign and you can access your
funds
2. BUT, you can't sign proposal created by others

is that correct?

On Tue, Feb 2, 2016 at 8:00 AM, J Vern <notifications@github.com> wrote:

> I installed copay on a new device, there was no pending proposal and I can
> create a proposal but I cannot sign proposals from the other people have a
> signature the multi signature wallet we share.
>
> *William PIQUARD*
> Business Developer.
>
> +852 9681 1930
> william@gatecoin.com
>
> [image: Inline image 1]
> *Gatecoin Limited*
> 1804, Lucky Centre
> 165 Wanchai road
> Hong Kong
>
>
> *Gatecoin.com <https://www.gatecoin.com/>*
> *@Gatecoin*
> <
> http://t.sidekickopen36.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3LjyFqW2zWKb23N1L5nW7dKLV856dP1Cf1lt-ld02?t=https%3A%2F%2Ftwitter.com%2FGatecoin&si=5603526086754304&pi=ab10a82c-42fa-43c1-f355-f358a716dded
> >
>
> On Tue, Feb 2, 2016 at 6:56 PM, Matias Alejo Garcia <
>
> notifications@github.com> wrote:
>
> > Did you delete all pending TX proposals, and created a new one with
> version
> > 1.8.x?
> >
> > On Tue, Feb 2, 2016 at 7:44 AM, J Vern <notifications@github.com> wrote:
> >
> > > I did. It does not help unfortunately.
> > >
> > > *William PIQUARD*
> > > Business Developer.
> > >
> > > +852 9681 1930
> > > william@gatecoin.com
> > >
> > > [image: Inline image 1]
> > > *Gatecoin Limited*
> > > 1804, Lucky Centre
> > > 165 Wanchai road
> > > Hong Kong
> > >
> > >
> > > *Gatecoin.com <https://www.gatecoin.com/>*
> > > *@Gatecoin*
> > > <
> > >
> >
> http://t.sidekickopen36.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3LjyFqW2zWKb23N1L5nW7dKLV856dP1Cf1lt-ld02?t=https%3A%2F%2Ftwitter.com%2FGatecoin&si=5603526086754304&pi=27c529c0-0f7e-4060-c921-de8afc44ca71
> > > >
> > >
> > > On Tue, Feb 2, 2016 at 6:33 PM, Matias Alejo Garcia <
> > > notifications@github.com> wrote:
> > >
> > > > Could you try using the same version on both platform? Please let us
> > know
> > > > if that helps.
> > > >
> > > > On Tue, Feb 2, 2016 at 4:54 AM, J Vern <notifications@github.com>
> > wrote:
> > > >
> > > > > The exact error message is "Server response could not be
> verified". I
> > > use
> > > > > the app v1.6.3 as described in the issue. Now on windows desktop I
> > have
> > > > the
> > > > > same issue. The version used is the v1.8.1
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> https://github.com/bitpay/copay/issues/3768#issuecomment-178431796
> > >.
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Matías Alejo Garcia
> > > > @ematiu
> > > > Roads? Where we're going, we don't need roads!
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/bitpay/copay/issues/3768#issuecomment-178500828
> >.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/bitpay/copay/issues/3768#issuecomment-178503570>.
> >
> > >
> >
> >
> >
> > --
> > Matías Alejo Garcia
> > @ematiu
> > Roads? Where we're going, we don't need roads!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/bitpay/copay/issues/3768#issuecomment-178507992>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3768#issuecomment-178509863>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by j-vern** [comment]
It is correct.

*William PIQUARD*
Business Developer.

+852 9681 1930
william@gatecoin.com

[image: Inline image 1]
*Gatecoin Limited*
1804, Lucky Centre
165 Wanchai road
Hong Kong


*Gatecoin.com <https://www.gatecoin.com/>*
*@Gatecoin*
<http://t.sidekickopen36.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3LjyFqW2zWKb23N1L5nW7dKLV856dP1Cf1lt-ld02?t=https%3A%2F%2Ftwitter.com%2FGatecoin&si=5603526086754304&pi=48d88ea8-cfd9-4932-97b1-1282508f8a46>

**Comment by matiu** [comment]
Could you check the version your others copayers have please?

If all have 1.8.x, I would suggest: first to move the funds to a new
multisig-wallet created on 1.8.x
and then we can check the problem in you wallet.

On Tue, Feb 2, 2016 at 8:05 AM, J Vern <notifications@github.com> wrote:

> It is correct.
>
> *William PIQUARD*
> Business Developer.
>
> +852 9681 1930
> william@gatecoin.com
>
> [image: Inline image 1]
> *Gatecoin Limited*
> 1804, Lucky Centre
> 165 Wanchai road
> Hong Kong
>
>
> *Gatecoin.com <https://www.gatecoin.com/>*
> *@Gatecoin*
> <
> http://t.sidekickopen36.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3LjyFqW2zWKb23N1L5nW7dKLV856dP1Cf1lt-ld02?t=https%3A%2F%2Ftwitter.com%2FGatecoin&si=5603526086754304&pi=48d88ea8-cfd9-4932-97b1-1282508f8a46
> >
>
> On Tue, Feb 2, 2016 at 7:04 PM, Matias Alejo Garcia <
>
> notifications@github.com> wrote:
>
> > So, just to be clear,
> >
> > 1. you can create a proposal and others can sign and you can access your
> > funds
> > 2. BUT, you can't sign proposal created by others
> >
> > is that correct?
> >
> > On Tue, Feb 2, 2016 at 8:00 AM, J Vern <notifications@github.com> wrote:
> >
> > > I installed copay on a new device, there was no pending proposal and I
> > can
> > > create a proposal but I cannot sign proposals from the other people
> have
> > a
> > > signature the multi signature wallet we share.
> > >
> > > *William PIQUARD*
> > > Business Developer.
> > >
> > > +852 9681 1930
> > > william@gatecoin.com
> > >
> > > [image: Inline image 1]
> > > *Gatecoin Limited*
> > > 1804, Lucky Centre
> > > 165 Wanchai road
> > > Hong Kong
> > >
> > >
> > > *Gatecoin.com <https://www.gatecoin.com/>*
> > > *@Gatecoin*
> > > <
> > >
> >
> http://t.sidekickopen36.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3LjyFqW2zWKb23N1L5nW7dKLV856dP1Cf1lt-ld02?t=https%3A%2F%2Ftwitter.com%2FGatecoin&si=5603526086754304&pi=ab10a82c-42fa-43c1-f355-f358a716dded
> >
> > > >
> > >
> > > On Tue, Feb 2, 2016 at 6:56 PM, Matias Alejo Garcia <
> > >
> > > notifications@github.com> wrote:
> > >
> > > > Did you delete all pending TX proposals, and created a new one with
> > > version
> > > > 1.8.x?
> > > >
> > > > On Tue, Feb 2, 2016 at 7:44 AM, J Vern <notifications@github.com>
> > wrote:
> > > >
> > > > > I did. It does not help unfortunately.
> > > > >
> > > > > *William PIQUARD*
> > > > > Business Developer.
> > > > >
> > > > > +852 9681 1930
> > > > > william@gatecoin.com
> > > > >
> > > > > [image: Inline image 1]
> > > > > *Gatecoin Limited*
> > > > > 1804, Lucky Centre
> > > > > 165 Wanchai road
> > > > > Hong Kong
> > > > >
> > > > >
> > > > > *Gatecoin.com <https://www.gatecoin.com/>*
> > > > > *@Gatecoin*
> > > > > <
> > > > >
> > > >
> > >
> >
> http://t.sidekickopen36.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3LjyFqW2zWKb23N1L5nW7dKLV856dP1Cf1lt-ld02?t=https%3A%2F%2Ftwitter.com%2FGatecoin&si=5603526086754304&pi=27c529c0-0f7e-4060-c921-de8afc44ca71
> > > > > >
> > > > >
> > > > > On Tue, Feb 2, 2016 at 6:33 PM, Matias Alejo Garcia <
> > > > > notifications@github.com> wrote:
> > > > >
> > > > > > Could you try using the same version on both platform? Please let
> > us
> > > > know
> > > > > > if that helps.
> > > > > >
> > > > > > On Tue, Feb 2, 2016 at 4:54 AM, J Vern <notifications@github.com
> >
> > > > wrote:
> > > > > >
> > > > > > > The exact error message is "Server response could not be
> > > verified". I
> > > > > use
> > > > > > > the app v1.6.3 as described in the issue. Now on windows
> desktop
> > I
> > > > have
> > > > > > the
> > > > > > > same issue. The version used is the v1.8.1
> > > > > > >
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > <
> > > https://github.com/bitpay/copay/issues/3768#issuecomment-178431796
> > > > >.
> > > > > > >
> > > > > >
> > > > > >
> > > > > >
> > > > > > --
> > > > > > Matías Alejo Garcia
> > > > > > @ematiu
> > > > > > Roads? Where we're going, we don't need roads!
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <
> > https://github.com/bitpay/copay/issues/3768#issuecomment-178500828
> > > >.
> > > > >
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> https://github.com/bitpay/copay/issues/3768#issuecomment-178503570
> > >.
> > > >
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Matías Alejo Garcia
> > > > @ematiu
> > > > Roads? Where we're going, we don't need roads!
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/bitpay/copay/issues/3768#issuecomment-178507992
> >.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/bitpay/copay/issues/3768#issuecomment-178509863>.
> >
> > >
> >
> >
> >
> > --
> > Matías Alejo Garcia
> > @ematiu
> > Roads? Where we're going, we don't need roads!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/bitpay/copay/issues/3768#issuecomment-178511455>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3768#issuecomment-178511859>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by j-vern** [comment]
Ok I ll check with them and get back to you if there is still an issue


*William PIQUARD*
Business Developer.

+852 9681 1930
william@gatecoin.com

[image: Inline image 1]
*Gatecoin Limited*
1804, Lucky Centre
165 Wanchai road
Hong Kong


*Gatecoin.com <https://www.gatecoin.com/>*
*@Gatecoin*
<http://t.sidekickopen36.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3LjyFqW2zWKb23N1L5nW7dKLV856dP1Cf1lt-ld02?t=https%3A%2F%2Ftwitter.com%2FGatecoin&si=5603526086754304&pi=e02824d6-1f92-4bba-dad2-f38c8ab18c1a>

**Comment by matiu** [comment]
thanks, sorry for the inconveniences you are having with Copay. Please let
us know.

On Tue, Feb 2, 2016 at 8:24 AM, J Vern <notifications@github.com> wrote:

> Ok I ll check with them and get back to you if there is still an issue
>
>
> *William PIQUARD*
> Business Developer.
>
> +852 9681 1930
> william@gatecoin.com
>
> [image: Inline image 1]
> *Gatecoin Limited*
> 1804, Lucky Centre
> 165 Wanchai road
> Hong Kong
>
>
> *Gatecoin.com <https://www.gatecoin.com/>*
> *@Gatecoin*
> <
> http://t.sidekickopen36.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3LjyFqW2zWKb23N1L5nW7dKLV856dP1Cf1lt-ld02?t=https%3A%2F%2Ftwitter.com%2FGatecoin&si=5603526086754304&pi=e02824d6-1f92-4bba-dad2-f38c8ab18c1a
> >
>
> On Tue, Feb 2, 2016 at 7:09 PM, Matias Alejo Garcia <
>
> notifications@github.com> wrote:
>
> > Could you check the version your others copayers have please?
> >
> > If all have 1.8.x, I would suggest: first to move the funds to a new
> > multisig-wallet created on 1.8.x
> > and then we can check the problem in you wallet.
> >
> > On Tue, Feb 2, 2016 at 8:05 AM, J Vern <notifications@github.com> wrote:
> >
> > > It is correct.
> > >
> > > *William PIQUARD*
> > > Business Developer.
> > >
> > > +852 9681 1930
> > > william@gatecoin.com
> > >
> > > [image: Inline image 1]
> > > *Gatecoin Limited*
> > > 1804, Lucky Centre
> > > 165 Wanchai road
> > > Hong Kong
> > >
> > >
> > > *Gatecoin.com <https://www.gatecoin.com/>*
> > > *@Gatecoin*
> > > <
> > >
> >
> http://t.sidekickopen36.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3LjyFqW2zWKb23N1L5nW7dKLV856dP1Cf1lt-ld02?t=https%3A%2F%2Ftwitter.com%2FGatecoin&si=5603526086754304&pi=48d88ea8-cfd9-4932-97b1-1282508f8a46
> >
> > > >
> > >
> > > On Tue, Feb 2, 2016 at 7:04 PM, Matias Alejo Garcia <
> > >
> > > notifications@github.com> wrote:
> > >
> > > > So, just to be clear,
> > > >
> > > > 1. you can create a proposal and others can sign and you can access
> > your
> > > > funds
> > > > 2. BUT, you can't sign proposal created by others
> > > >
> > > > is that correct?
> > > >
> > > > On Tue, Feb 2, 2016 at 8:00 AM, J Vern <notifications@github.com>
> > wrote:
> > > >
> > > > > I installed copay on a new device, there was no pending proposal
> and
> > I
> > > > can
> > > > > create a proposal but I cannot sign proposals from the other people
> > > have
> > > > a
> > > > > signature the multi signature wallet we share.
> > > > >
> > > > > *William PIQUARD*
> > > > > Business Developer.
> > > > >
> > > > > +852 9681 1930
> > > > > william@gatecoin.com
> > > > >
> > > > > [image: Inline image 1]
> > > > > *Gatecoin Limited*
> > > > > 1804, Lucky Centre
> > > > > 165 Wanchai road
> > > > > Hong Kong
> > > > >
> > > > >
> > > > > *Gatecoin.com <https://www.gatecoin.com/>*
> > > > > *@Gatecoin*
> > > > > <
> > > > >
> > > >
> > >
> >
> http://t.sidekickopen36.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3LjyFqW2zWKb23N1L5nW7dKLV856dP1Cf1lt-ld02?t=https%3A%2F%2Ftwitter.com%2FGatecoin&si=5603526086754304&pi=ab10a82c-42fa-43c1-f355-f358a716dded
> > > >
> > > > > >
> > > > >
> > > > > On Tue, Feb 2, 2016 at 6:56 PM, Matias Alejo Garcia <
> > > > >
> > > > > notifications@github.com> wrote:
> > > > >
> > > > > > Did you delete all pending TX proposals, and created a new one
> with
> > > > > version
> > > > > > 1.8.x?
> > > > > >
> > > > > > On Tue, Feb 2, 2016 at 7:44 AM, J Vern <notifications@github.com
> >
> > > > wrote:
> > > > > >
> > > > > > > I did. It does not help unfortunately.
> > > > > > >
> > > > > > > *William PIQUARD*
> > > > > > > Business Developer.
> > > > > > >
> > > > > > > +852 9681 1930
> > > > > > > william@gatecoin.com
> > > > > > >
> > > > > > > [image: Inline image 1]
> > > > > > > *Gatecoin Limited*
> > > > > > > 1804, Lucky Centre
> > > > > > > 165 Wanchai road
> > > > > > > Hong Kong
> > > > > > >
> > > > > > >
> > > > > > > *Gatecoin.com <https://www.gatecoin.com/>*
> > > > > > > *@Gatecoin*
> > > > > > > <
> > > > > > >
> > > > > >
> > > > >
> > > >
> > >
> >
> http://t.sidekickopen36.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3LjyFqW2zWKb23N1L5nW7dKLV856dP1Cf1lt-ld02?t=https%3A%2F%2Ftwitter.com%2FGatecoin&si=5603526086754304&pi=27c529c0-0f7e-4060-c921-de8afc44ca71
> > > > > > > >
> > > > > > >
> > > > > > > On Tue, Feb 2, 2016 at 6:33 PM, Matias Alejo Garcia <
> > > > > > > notifications@github.com> wrote:
> > > > > > >
> > > > > > > > Could you try using the same version on both platform? Please
> > let
> > > > us
> > > > > > know
> > > > > > > > if that helps.
> > > > > > > >
> > > > > > > > On Tue, Feb 2, 2016 at 4:54 AM, J Vern <
> > notifications@github.com
> > > >
> > > > > > wrote:
> > > > > > > >
> > > > > > > > > The exact error message is "Server response could not be
> > > > > verified". I
> > > > > > > use
> > > > > > > > > the app v1.6.3 as described in the issue. Now on windows
> > > desktop
> > > > I
> > > > > > have
> > > > > > > > the
> > > > > > > > > same issue. The version used is the v1.8.1
> > > > > > > > >
> > > > > > > > > —
> > > > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > > > <
> > > > > https://github.com/bitpay/copay/issues/3768#issuecomment-178431796
> > > > > > >.
> > > > > > > > >
> > > > > > > >
> > > > > > > >
> > > > > > > >
> > > > > > > > --
> > > > > > > > Matías Alejo Garcia
> > > > > > > > @ematiu
> > > > > > > > Roads? Where we're going, we don't need roads!
> > > > > > > >
> > > > > > > > —
> > > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > > <
> > > > https://github.com/bitpay/copay/issues/3768#issuecomment-178500828
> > > > > >.
> > > > > > >
> > > > > > > >
> > > > > > >
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > <
> > > https://github.com/bitpay/copay/issues/3768#issuecomment-178503570
> > > > >.
> > > > > >
> > > > > > >
> > > > > >
> > > > > >
> > > > > >
> > > > > > --
> > > > > > Matías Alejo Garcia
> > > > > > @ematiu
> > > > > > Roads? Where we're going, we don't need roads!
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <
> > https://github.com/bitpay/copay/issues/3768#issuecomment-178507992
> > > >.
> > > > >
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> https://github.com/bitpay/copay/issues/3768#issuecomment-178509863
> > >.
> > > >
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Matías Alejo Garcia
> > > > @ematiu
> > > > Roads? Where we're going, we don't need roads!
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/bitpay/copay/issues/3768#issuecomment-178511455
> >.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/bitpay/copay/issues/3768#issuecomment-178511859>.
> >
> > >
> >
> >
> >
> > --
> > Matías Alejo Garcia
> > @ematiu
> > Roads? Where we're going, we don't need roads!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/bitpay/copay/issues/3768#issuecomment-178513478>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3768#issuecomment-178518403>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!
