### ISSUE TITLE
Request specific amount QR code keyboard 

### ISSUE THREAD

**Issue by neocogent** [bitpay/copay#3772]
The numeric keyboard has no decimal point. 

So it's impossible to enter fractions of a BTC or cents if in USD mode. 

I am using Samsung phone on Android. Maybe in other cases it has a decimal point but definitely not for my situation.

**Comment by hrishikeshio** [comment]
Using moto g xt1033 android 5.1 I don't have any problems. My numeric keypad has decimal point.

**Comment by matiu** [comment]
see https://github.com/bitpay/copay/issues/2838

**Comment by neocogent** [comment]
Program uninstalled because forced to use bits for units on my device.
