### ISSUE TITLE
[tangential] /r/Copay subreddit

### ISSUE THREAD

**Issue by BashCo** [bitpay/copay#3773]
Hey, I'm the sole mod of [/r/Copay](https://www.reddit.com/r/Copay/) on reddit. The sub is quiet, but I would like to turn it over to some people involved with Copay's development. I'd like to add 2-3 mods before stepping down. I suggest replying here and PMing the [/r/Copay mod mail](https://www.reddit.com/message/compose?to=%2Fr%2FCopay) with some sort of verification. Thanks for all the work you do!

**Comment by matiu** [comment]
thanks! Will replay.
