### ISSUE TITLE
How to unlock locked balance?

### ISSUE THREAD

**Issue by gwaghamare40** [bitpay/copay#3775]
Balance is locked.
How to unlock locked balance?
![screenshot_1](https://cloud.githubusercontent.com/assets/16508477/12395751/796f15ba-be29-11e5-8e5f-7ad3c4ea1174.jpg)

**Comment by dabura667** [comment]
Send your unsent transaction.

**Comment by gwaghamare40** [comment]
I tried to sending but it can't send

On Tue, Jan 19, 2016 at 8:00 AM, Dabura667 <notifications@github.com> wrote:

> Send your unsent transaction.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3775#issuecomment-172714335>.
>



-- 
Regards,
*Ganesh H Waghamare*
*Ganesh Waghamare Photography*
6A, Vrundawan Colony,Karve naka , Goleshwar road, Goleshwar.
KARAD - 415 124 Dist.- Satara. (M.S.)
*Contact No.: *02164 - 226699/ Mob. - +919503386896,+918485844474
*Email - ID : *gwaghamare40@gmail.com

**Comment by matiu** [comment]
please provide better feedback (screenshots, error messages, etc.)

**Comment by gwaghamare40** [comment]
![dddd](https://cloud.githubusercontent.com/assets/16508477/12441625/077db5e6-bf6f-11e5-87b4-9aa0e043ca13.jpg)
Balance is locked.again. why is this happen?
How to unlock locked balance?

**Comment by matiu** [comment]
In a 1-1 (non-multisig) wallet, balance is locked only if the was a problem broadcasting the transaction. Could please try to broadcast again? (tap on the transaction under "unsent transactions"), and click on Broadcast.

**Comment by gwaghamare40** [comment]
I trying but it is not working 

-----Original Message-----

**Comment by matiu** [comment]
What error do you get?

**Comment by gwaghamare40** [comment]
I got this error

On Wed, Jan 20, 2016 at 5:10 PM, Matias Alejo Garcia <
notifications@github.com> wrote:

> What error do you get?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3775#issuecomment-173179541>.
>



-- 
Regards,
*Ganesh H Waghamare*
*Ganesh Waghamare Photography*
6A, Vrundawan Colony,Karve naka , Goleshwar road, Goleshwar.
KARAD - 415 124 Dist.- Satara. (M.S.)
*Contact No.: *02164 - 226699/ Mob. - +919503386896,+918485844474
*Email - ID : *gwaghamare40@gmail.com

**Comment by matiu** [comment]
what error?

**Comment by gwaghamare40** [comment]
![sssss](https://cloud.githubusercontent.com/assets/16508477/12447984/1e4b129e-bf99-11e5-9dfd-74105488384f.jpg)

**Comment by gwaghamare40** [comment]
Could not broadcast payment  Error querying the blickchain

-----Original Message-----

**Comment by matiu** [comment]
The input for that transaction (https://insight.bitpay.com/tx/06bae5fa1a1cef61c6f857cb1c1f1c80c64b1331d7a6777cf10e4b74bf58aae2) was already spent. That is the problem. You probably has installed the seed on other wallet and spend it already. The transaction cannot be broadcasted because of that.

**Comment by matiu** [comment]
we can remove the tx proposal in the DB, if you want. let us know.

**Comment by gwaghamare40** [comment]
How?

-----Original Message-----

**Comment by moscarossa** [comment]
Hi, i have the same problem, I made 2 transactions that i tried to pay more than one time but I received the error "address has mismatched network type" so i tried to delete the proposal pay but I still see my btc locked

**Comment by RusGamer** [comment]
i tryed to send money 2 times with no internet connection. and now 1 undesded transaction locked my balance! how to cancel ?
