### ISSUE TITLE
Copy and Paste Seed

### ISSUE THREAD

**Issue by mrabinovsky** [bitpay/copay#3777]
You should totally be allowed to copy and paste the seed. Why is this not a thing?

**Comment by matiu** [comment]
it is disabled for security (only enabled in testnet).

Ideally, you should copy the seed by hand, of typing it in a secure device.

**Comment by mrabinovsky** [comment]
That's not secure, if I copy it into an encrypted vault then there is no chance of a typo or a missread, it's faster, and a keylogger can't pick up on it, and no one can pick up a piece of a paper and get it off of that. That is secure. There should at least be an option to toggle that on and off.
