### ISSUE TITLE
Unrecieved bitcoins

### ISSUE THREAD

**Issue by billeborg** [bitpay/copay#3778]
Hey, i bought bitcoins to my copay adress: 
1GMLvZqkM9KNBLeG5TLxJSR2Qf4YLzP28J
Transaction ID is: https://blockchain.info/tx/df398cfd92f1eaadad38acd90021a645e011ea9bac26973017db7209f86af544

When i check it on blockchain, it says it has 33 confirmations, but i haven’t received any bitcoins in my wallet
Hope you will help me

**Comment by matiu** [comment]
Could you please check again and reopen the ticket if the problem persist? We are migrating our bitcoind instance. Thanks and sorry for the inconvenience.
