### ISSUE TITLE
Coins stuck in Locked Balance of Unsent Transaction

### ISSUE THREAD

**Issue by twisterswirl** [bitpay/copay#3779]
It says "Payment accepted, but not yet broadcasted"

If I try to broadcast it, I get this message: " Could not broadcast payment: Error querying the blockchain "

Using latest version of Copay wallet v1.7.1
On windows phone
1 of 1 wallet

Things I have tried, I deleted Copay, redownloaded it from the store, restored my wallet with the back up but the coins remain stuck. 

Are these coins lost? Or can I get them out?

**Comment by matiu** [comment]
Could you please check again and reopen the ticket if the problem persist? We are migrating our bitcoind instance. Thanks and sorry for the inconvenience.
