### ISSUE TITLE
Possibel double spend

### ISSUE THREAD

**Issue by billeborg** [bitpay/copay#3780]
My transactions says invalid, but the bitcoins are withdrawn from my account?
What do i do?

**Comment by matiu** [comment]
What you mean by invalid? Can you share a screenshot?

**Comment by blocklud** [comment]
I might have had a similar experience today.

Transaction in the "Activity" feed was displayed with a yellow "invalid" label and message reffering to "possible double spend". The transaction (with normal fee setting) took more than an hour and half to receive its first confirmation (unconfirmed transactions in the network were at the time above 10k).

From user experience perspective, a bit distressing was when the transaction disappeared from the "Activity" feed and the wallet balance printed 0 BTC. After the first confimration 90min later, wallet seems back to normal, printing both transaction and balance.

**Comment by matiu** [comment]
We later discover with was to a restart in one of our bitcoind instanced, so the mempool was resetted. All unconfirmed TX pointing to that bitoind become `invalid` until they were confirmed. Sorry about this problem.
