### ISSUE TITLE
Payment accepted but not yet broadcasted

### ISSUE THREAD

**Issue by phideas** [bitpay/copay#3781]
After recent network problems.
Payment accepted but not yet broadcasted.
After hit Broadcast payment:
"Could not broadcast payment: Error querying the blockchain"

Tried to send a new payment and it works!

The previous not broadcasted payment stuck in my wallet.
Is there a way to delete it?

**Comment by matiu** [comment]
deleting proposal of TX that cannot be broadcasted was fixed in #3782. You can wait until it is deployed or we can remove it manually if you want. You can contact my at matias @ bitpay .com
