### ISSUE TITLE
Altcoins

### ISSUE THREAD

**Issue by ih8ra1n** [bitpay/copay#3796]
Hi!

First of all, I'd like to say thank you for the great job you did. Copay is a wonderful service.

Secondly, I'd like to ask if it is possible to implement some other cryptocurrency support or replace Bitcoin with let us say Litecoin? Is it something that will demand full code remastering?

**Comment by matiu** [comment]
it will require significant amount of work in insight / bitcore-lib / bitcore-wallet-service / bitcore-wallet-client and Copay.
