### ISSUE TITLE
Possible double spend

### ISSUE THREAD

**Issue by samer** [bitpay/copay#3798]
![screen shot 2016-01-21 at 19 43 38](https://cloud.githubusercontent.com/assets/554078/12493017/6b2c4dae-c083-11e5-9f10-37913faaf19c.png)

I had around 0.08 BTC in my wallet and now it is showing as empty. Moreover, I sent a small amount of BTC to two friends with fresh Copay wallets. They're having the same problem.
Any hints as to what is going on? I tried importing my seed into the desktop client, and I'm having the same issue.

**Comment by matiu** [comment]
click in the transactions details and check the transactions on the block explorer (see it on the block chain) to see if it is valid.

**Comment by samer** [comment]
All three transactions show as unconfirmed.
This is weird because:
- the top two that say "3 minutes ago" were done at least a week ago.
- all three of them had plenty of confirmations

**Comment by matiu** [comment]
Can you check the txid on other block explorer? (Or share the ID)?

**Comment by samer** [comment]
I edited my previous post to include the TX IDs.
Checking them on Blockchain.info yields:
> Transaction rejected by our node. Reason: Transaction was previously accepted but has been pruned from our database.

**Comment by matiu** [comment]
So, it is probably a double spend. Try contacting the sender.

**Comment by samer** [comment]
Indeed, it was a double spend. I moved some BTC from a blockchain.info wallet to the Copay wallet around two months ago. I'm guessing the transaction was never confirmed. It sat there for a month, and then I was able to create a new transaction and spend the unconfirmed outputs as inputs using the copay wallet to send some BTC to two friends who are also using copay.

The UI did not indicate that anything was wrong, and did not warn me at any point that the transaction had not been confirmed, or that I was about to spend unconfirmed inputs.

**Comment by samer** [comment]
@matiu: not sure why this was closed. I think there's an uncommon, yet serious UX bug to be addressed here, as was pointed out by my last sentence:
> The UI did not indicate that anything was wrong, and did not warn me at any point that the transaction had not been confirmed, or that I was about to spend unconfirmed inputs.

This lead to a 2 month long illusion whereby 3 Copay users thought they actually owned a certain amount of Bitcoin, with the UI not contradicting this in any way.
