### ISSUE TITLE
Copay on Chrome doesn't popup the fee when sending bitcoins

### ISSUE THREAD

**Issue by bitcoinuser** [bitpay/copay#3807]
Hi, Copay on Google Chrome doesn't popup the fee when sending bitcoins. Android Copay show this information.

**Comment by matiu** [comment]
thanks for the report. Yes, that is a known issue due to Chrome Apps not supporting alert/confirm. It will be fixed one the Send Confirmation popup get merged (https://github.com/bitpay/copay/pull/3795)

**Comment by KeyJockey** [comment]
@matiu - I *seriously hope* that this upcoming *Send Confirmation* popup will _ALSO_ *finally* allow the fee to be "tweaked" to a preferred user-set amount, i.e. manually setting the miner fee...? 

Please please please tell me that's how you guys are *finally* gonna handle this long-standing BUG and my ONLY real complaint about Copay, to *finally* close my long-standing and most-commented issue,  https://github.com/bitpay/copay/issues/3111 i.e. "Manual Override Dynamic Fee" here...?
