### ISSUE TITLE
Can't send BTC from a Android multi-sig password protected wallet

### ISSUE THREAD

**Issue by JPUnix** [bitpay/copay#3810]
I generated a multi-sig transaction from the Chrome app on my laptop. My intention was to sign it with my Android device. My Android just updated to the latest version of Copay for Android. The multi-sig wallet is password protected. When I click the "Confirm" button on the Android the screen says "Signing Payment" in a little box and the place to enter the password is sent to a background screen and I'm not allowed to enter the password. The effect is that it stays on the "Signing Payment" box and I'm not allowed to obtain access to the password field to type in the password. I ultimately had to turn off the "Request Password" feature on the Android in order to complete the transaction.

**Comment by matiu** [comment]
thanks for the report. we will check that ASAP.

**Comment by JPUnix** [comment]
I've tested the new version and it works. Thanks.

**Comment by matiu** [comment]
thanks for the update.
