### ISSUE TITLE
The note field on send window should be visible

### ISSUE THREAD

**Issue by bitcoinuser** [bitpay/copay#3816]
Hi, see the video uploaded to understand the problem.

Thanks
[2016_01_23_19_01_35.mp4.zip](https://github.com/bitpay/copay/files/102029/2016_01_23_19_01_35.mp4.zip)

**Comment by bitcoinuser** [comment]
Suggestion: when android keyboard be active, hide the buttons request/activity/send

**Comment by matiu** [comment]
fixed in copay 2.0
