### ISSUE TITLE
How  to unlock locked balance in copay

### ISSUE THREAD

**Issue by gtfrk** [bitpay/copay#3820]
So i was sending 6 dollars to a friend via my copay app but i had not changed the value from bit to usd. this couldn't get sent and it ended up locking my entire funds. it shows up in the app as "unsent transactions" and when i click on, it says i should broadcast payment, but when i do, there is an error of "could not broadcast payment: error querying the blockchain" how do i solve this issue?

**Comment by matiu** [comment]
there should be a 'delete payment' also (check that you are using version >1.8). Once you delete it, you should have access to your funds again.

**Comment by gtfrk** [comment]
@matiu it has been resolved.. thank you
