### ISSUE TITLE
Cannot use Glidera on iOS

### ISSUE THREAD

**Issue by ovaltinedinosaur** [bitpay/copay#3821]
this is what happens on Bitpay 1.8.2 iOS, I don't have this issue on Mac OS X:

press hamburger menu button
press - buy & sell bitcoin
press - Connect to Glidera
login to Glidera
press allow - bitpay request access to your glidera account
I see a pop saying - Open in "Blockchain"?  (wants to open blockchain.info application) - options to press are Open / Cancel
If I click Open, blockchain.info opens and nothing happens
if I click Cancel it drops me back to the allow - bitty request access to your glidera account

**Comment by matiu** [comment]
You need to associate the 'bitcoin:' protocol handler to Copay. I think
that in IOS the last app
Assosiated is the one that installs last.

So you could:
Uninstall bc.i
Or
Uninstall copay and reinstall it again

Please let us know how it goes. And remember to backup your wallets before
uninstalling.

**Comment by ovaltinedinosaur** [comment]
I tried uninstalling copay and reinstalling it, didn't seem to help any other ideas? 

    On Wednesday, January 27, 2016 8:25 AM, Matias Alejo Garcia <notifications@github.com> wrote:
 

 Closed #3821.—

**Comment by matiu** [comment]
Could you uninstall blockchain info, just for testing?

On Wed, Jan 27, 2016 at 12:00 PM, ovaltinedinosaur <notifications@github.com
> wrote:

> I tried uninstalling copay and reinstalling it, didn't seem to help any
> other ideas?
>
> On Wednesday, January 27, 2016 8:25 AM, Matias Alejo Garcia <
> notifications@github.com> wrote:
>
>
> Closed #3821.—
>
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3821#issuecomment-175670327>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by ovaltinedinosaur** [comment]
I fixed it finally,
had to uninstall blockchain, then circle, then coinbase.   Then within copay I could associate with the glidera account.  I then reinstalled blockchain, circle and coinable and the association is still working which is great.  Just weird that I had to do that to get the glidera to connect/associate.
any ideas or is this a bug? 

    On Wednesday, January 27, 2016 10:15 AM, Matias Alejo Garcia <notifications@github.com> wrote:
 

 Could you uninstall blockchain info, just for testing?

On Wed, Jan 27, 2016 at 12:00 PM, ovaltinedinosaur <notifications@github.com
> wrote:

> I tried uninstalling copay and reinstalling it, didn't seem to help any
> other ideas?
>
> On Wednesday, January 27, 2016 8:25 AM, Matias Alejo Garcia <
> notifications@github.com> wrote:
>
>
> Closed #3821.—
>
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3821#issuecomment-175670327>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by matiu** [comment]
Thanks a lot for the update.

So, probably the default app for the handler is the *first* one installed.

The solution would be to have a special handler (something like
copayglidera:// ) for the glidera callback, but we were not able to
register multiple handler, in copay's multiplatform app yet.

thanks again and sorry for the inconvenience.



On Wed, Jan 27, 2016 at 12:30 PM, ovaltinedinosaur <notifications@github.com
> wrote:

> I fixed it finally,
> had to uninstall blockchain, then circle, then coinbase.   Then within
> copay I could associate with the glidera account.  I then reinstalled
> blockchain, circle and coinable and the association is still working which
> is great.  Just weird that I had to do that to get the glidera to
> connect/associate.
> any ideas or is this a bug?
>
> On Wednesday, January 27, 2016 10:15 AM, Matias Alejo Garcia <
> notifications@github.com> wrote:
>
>
> Could you uninstall blockchain info, just for testing?
>
> On Wed, Jan 27, 2016 at 12:00 PM, ovaltinedinosaur <
> notifications@github.com
> > wrote:
>
> > I tried uninstalling copay and reinstalling it, didn't seem to help any
> > other ideas?
> >
> > On Wednesday, January 27, 2016 8:25 AM, Matias Alejo Garcia <
> > notifications@github.com> wrote:
> >
> >
> > Closed #3821.—
> >
> > Reply to this email directly or view it on GitHub.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/bitpay/copay/issues/3821#issuecomment-175670327>.
> >
>
>
>
> --
> Matías Alejo Garcia
> @ematiu
> Roads? Where we're going, we don't need roads!
> —
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3821#issuecomment-175689907>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by ovaltinedinosaur** [comment]
Love your app keep up the great work! :)  

    On Wednesday, January 27, 2016 10:33 AM, Matias Alejo Garcia <notifications@github.com> wrote:
 

 Thanks a lot for the update.

So, probably the default app for the handler is the *first* one installed.

The solution would be to have a special handler (something like
copayglidera:// ) for the glidera callback, but we were not able to
register multiple handler, in copay's multiplatform app yet.

thanks again and sorry for the inconvenience.



On Wed, Jan 27, 2016 at 12:30 PM, ovaltinedinosaur <notifications@github.com
> wrote:

> I fixed it finally,
> had to uninstall blockchain, then circle, then coinbase. Then within
> copay I could associate with the glidera account. I then reinstalled
> blockchain, circle and coinable and the association is still working which
> is great. Just weird that I had to do that to get the glidera to
> connect/associate.
> any ideas or is this a bug?
>
> On Wednesday, January 27, 2016 10:15 AM, Matias Alejo Garcia <
> notifications@github.com> wrote:
>
>
> Could you uninstall blockchain info, just for testing?
>
> On Wed, Jan 27, 2016 at 12:00 PM, ovaltinedinosaur <
> notifications@github.com
> > wrote:
>
> > I tried uninstalling copay and reinstalling it, didn't seem to help any
> > other ideas?
> >
> > On Wednesday, January 27, 2016 8:25 AM, Matias Alejo Garcia <
> > notifications@github.com> wrote:
> >
> >
> > Closed #3821.—
> >
> > Reply to this email directly or view it on GitHub.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/bitpay/copay/issues/3821#issuecomment-175670327>.
> >
>
>
>
> --
> Matías Alejo Garcia
> @ematiu
> Roads? Where we're going, we don't need roads!
> —
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3821#issuecomment-175689907>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!
