### ISSUE TITLE
Copay wallet import issue.

### ISSUE THREAD

**Issue by JohnTitor1006** [bitpay/copay#3823]
I’ve lost everything on my phone, so I've had to reinstalled Copay.

I need help recovering access to a wallet. I had already backed up the wallet to a aes type file.
The string starts with these characters:

{"iv":"fCfAmhee0wgDmZwgpiTFAg==","v":1,"iter":10000,"ks":128,"ts":64,"mode":"ccm","adata":"","cipher":"aes","salt":"/QqC... ...etc.

Anyways, it looks like I can import the wallet just fine (see screenshot). But sending funds does not work well. When I try to send funds and a message, Copay returns the following error message: "The payment was created but cold not be completed. Please try again from home screen" 

If I got back to the homescreen, I see my Unsent Transaction, and Copay locks my balance.

Please see attached screenshots.

In case you’re wondering, the reason why I’m trying to recover a wallet worth 20 cents is for identity verification. The wallet is not worth anything to me once I am able to send the message. Ultimately, I would not mind sharing the backup file - I understand I can no longer use the wallet after that.

Can you help me?

Thanks.

<img width="317" alt="capture01" src="https://cloud.githubusercontent.com/assets/16910388/12602239/a309134c-c475-11e5-89bd-4faa93e0aa0e.PNG">
<img width="314" alt="capture02" src="https://cloud.githubusercontent.com/assets/16910388/12602240/a3167654-c475-11e5-98fa-8754d26ff325.PNG">

**Comment by matiu** [comment]
Cclick on the unsent transaction and a popup will appear, with a broadcast button.

**Comment by matiu** [comment]
If the solution above does not work, please reopen the ticket.

**Comment by JohnTitor1006** [comment]
The solution does not work. Can you suggest anything else?

**Comment by matiu** [comment]
you detail what happened when you try to broadcast the TX?
