### ISSUE TITLE
Allow TX proposals without fund locking

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#3825]
-   create a tx proposal that only specifies the outputs …the first signer then supplies the inputs (and the change output) …after the first signer signs, the UTXOs are locked

this would allow proposals to be created even when you have an empty wallet
- if you have, say 5 tx proposals created that way (with out signatures and without assigned inputs), it wont be possible to sign 5 at the same time, you will need to sign one, wait for others to sign, and the sign the 2nd
- in the UI, we will probably want some indicator of which proposals have already locked inputs …that might just be which ones already have at least one signature
- handle the case where someone tries to put the first signature on a proposal and fails because there aren’t enough unlocked UTXOs

There should be a confirmation popup "you are about to create a spend proposals without funds" and/or a checkbox "create the TX without locking the funds"

**Comment by gabegattis** [comment]
+1 on this one. I am having to handle special cases in my work where we try to create a transaction proposal, but can't because of the locked funds error. It sounds like this could help with that.
