### ISSUE TITLE
Suggestion: Show the share address button on top right

### ISSUE THREAD

**Issue by bitcoinuser** [bitpay/copay#3828]
Hi, 

I think the share address button on Copay is not located on a good position. The user need to scroll down to see the button.
I think the correct position of the button should be on top right, like many other android apps.

See the imahe of greenbits app as example:

![screenshot_2016-01-27-18-11-29](https://cloud.githubusercontent.com/assets/1178856/12626928/61899eca-c522-11e5-9bec-69e97a20af24.png)

Now Copay: Where is the button? Needs to scroll down.

![screenshot_2016-01-27-18-10-28](https://cloud.githubusercontent.com/assets/1178856/12626959/84bca464-c522-11e5-98c9-9e3cde3febe3.png)

**Comment by matiu** [comment]
moved to the first scroll. thanks.
