### ISSUE TITLE
Suggestion: change wallet settings button 

### ISSUE THREAD

**Issue by bitcoinuser** [bitpay/copay#3829]
Hi, I think the wallet settings button should not be on top right. (I think the top right button should open the global settings )
The wallet settings should be opened when the user clicks on the area (green line on screenshot posted here: 
![screenshot_2016-01-27-18-43-30](https://cloud.githubusercontent.com/assets/1178856/12627893/8c2e0738-c527-11e5-8558-d45786cee762.png)

**Comment by matiu** [comment]
hmm, I dont think users will understand that clicking that area will open the settings.
