### ISSUE TITLE
Design bug

### ISSUE THREAD

**Issue by bitcoinuser** [bitpay/copay#3831]
(I think the color should be blue on top, when the copay menu is opened) See the screenshot:
Obs: Device: Moto X Play (Android Marshmallow)

![screenshot_20160127-201049](https://cloud.githubusercontent.com/assets/1178856/12631215/5ee6798a-c537-11e5-9227-4928633500a3.png)

**Comment by cmgustavo** [comment]
Agree. Even it could be hide.

**Comment by bitcoinuser** [comment]
I think the menu could overlap the app, something like how Circle pay app works.

**Comment by matiu** [comment]
No sure this is a bug. We dont want to hide the status bar, for an app like Copay.

**Comment by bitjson** [comment]
Copay has a new design 🎉
