### ISSUE TITLE
add batches to app icin

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#3841]

**Comment by tanojaja** [comment]
We can try using the current plugin to send push notifications.

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushsetapplicationiconbadgenumbersuccesshandler-errorhandler-count---ios-only

**Comment by gabrielbazan7** [comment]
The badge number should be set only when is a pending proposal. It's true that counting incoming and outgoing transactions or new copayers is a little confuse.

**Comment by gabrielbazan7** [comment]
The Push Plugin do not support to add batches to app icon on Android, and also the version 1.2.3 do not support add batches at all.
