### ISSUE TITLE
Requesting to lock the wallet until fingerprint was entered

### ISSUE THREAD

**Issue by aviadoffer** [bitpay/copay#3842]
When you launch the app you can see your balance without any pass or fingerprint.
Most other wallets are locked until you enter pass or fingerprint.
Kindly consider adding it.

**Comment by matiu** [comment]
We trust on the device security for that. You can set up a password or fingerprint for spending bitcoins.

**Comment by matiu** [comment]
We trust on the device security for that. You can set up a password or fingerprint for spending bitcoins.
