### ISSUE TITLE
Unconfirmed transactions lose the original timestamp

### ISSUE THREAD

**Issue by aviadoffer** [bitpay/copay#3843]
Transaction X until confirmed keeps advancing the time.
So a person asked me to pay at 00:00 10btc and I did. It did not get confirmed until 01:00 and when I look at the app there is no way to prove actually submitted it at 00:00.
Every time you fresh the page and until it's confirmed the date will update as well.

Anyway we can keep the original submit date as well as the confirmed one ?
Thanks

**Comment by dabura667** [comment]
> there is no way to prove actually submitted it at 00:00

If data created by an app that you could have easily modified to say any time before the confirmation is enough basis of proof for your partner... why do you need bitcoin at all? Why not just make gentlemen's loans to each other in any denomination you want?

I agree it would be nice to show both "Copay timestamp" and "confirmation timestamp" please know that:

1. "Copay timestamp" can be modified with no proof that it was tampered with.
2. "confirmation timestamp" can only prove that a transaction was created BEFORE a certain point, but it can not prove AFTER a certain point. To do this you would need to include a headline of something you would not be able to know, like the US Times front page in your transaction... this would prove you signed the transaction AFTER a certain point.

**Comment by KeyJockey** [comment]
Can't you still get the original first submitted time for the transaction from the actual blockchain entry?

Even if it's not exactly the same inside Copay's log, that's still permanent and immutable, isn't it?

(That said, IF it's really different in Copay's record from what the permanent blockchain record timestamp says, I'd still think it's a bug to be fixed in Copay.  But at least this is a workaround for OP's original need anyway...)

**Comment by dabura667** [comment]
> Can't you still get the original first submitted time for the transaction from the actual blockchain entry?

There's no such thing.

**Comment by aviadoffer** [comment]
All I want is to prove I sent the transaction so we can continue the exchange of the goods.
Since it takes an hour to get all confirmation I didn't want to wait there.
I realize of course that it's not any real proof but between a coffee shop and client it should be enough.
Anyway, if the protocol doesn't support single transaction timestamp than we can't do it.
Thanks @dabura667  and @KeyJockey  for the inputs.

**Comment by dabura667** [comment]
> All I want is to prove I sent the transaction so we can continue the exchange of the goods.

The other party obviously has a wallet. Why don't they look at their wallet? Why do they need you to send a screenshot? lol

**Comment by aviadoffer** [comment]
The transaction doesn't show up on the other person wallet until a confirmation

**Comment by dabura667** [comment]
What wallet is that?

Tell them to look up the address on any of the tons of block explorer websites. All of these websites will show the user unconfirmed transactions.

**Comment by KeyJockey** [comment]
@dabura667 hmm yeah you learn something new every day I guess.  Wasn't aware there is no such thing actually... at least not in the "official" bitcoin spec, huh?  Hmm.

Anyway, FWIW it seems to me like other blockchain explorers like (ugh, yeah I know) blockchain.info manage to put in a timestamp for whenever a transaction is "first seen" on the network, even if it's not the official first confirmation time stamp. 

The OP here could accomplish what he says he needs by looking at his submitted transaction via these other block explorers even if that timestamp info there isn't available directly in his Copay wallet.

But, IMHO anyway, would be nice to have it somehow available IN COPAY as well.

**Comment by matiu** [comment]
The creation date is stored on BWS, but, as @dabura667 mentioned, it is not verificable by a 3rd party, therefore it is now shown on the tx details.
