### ISSUE TITLE
Main Tab's Scrollbar?

### ISSUE THREAD

**Issue by KeyJockey** [bitpay/copay#3846]
Just a minor cosmetic issue...?  Or, maybe not if this is really better (worse?) functionality for UI...?

Seems to me that *maybe* the main tab's scrollbar should only scroll the transaction information and leave the large colored-box area with the wallet balance at the TOP of the window in place?

LEFT side of screencap below is how it scrolls now, RIGHT side is what I'm proposing: what do y'all think?

![copay-scroll](https://cloud.githubusercontent.com/assets/13903392/12687329/30dd8f76-c69d-11e5-92ee-40d1395e9bd7.jpg)

**Comment by bitcoinuser** [comment]
No. I think the large colored-box area with the wallet balance, should hide, something like how coinbase or circle apps works.

**Comment by KeyJockey** [comment]
@bitcoinuser thanks for the reply: I assume by "hide" you mean leave the design alone, i.e. as it is NOW where the big colored box with wallet balance scrolls UP and OFF the screen?

Honestly I'm kind of 50-50 about this idea myself, not sure if it's better as-is where scrolling area to show more of the transactions as the user moves down the list -OR- keeping the top area with wallet balance visible at all times.  Former maybe is more "functional" but the LATTER just seems to... I don't know... kind of just LOOK better for some reason to me.

This is why I posted this: to ask people's opinion LOL.  So... kind of so far we have one FOR and one AGAINST?  Anyone else have any thought on this?

**Comment by matiu** [comment]
yes, I think it is better the balance to scroll up. That information is "static" and it wont probably change while you scroll down, so the idea to have it fixed on the screen using an important portion of the display does seems to be good in most cases.
