### ISSUE TITLE
Multisignature wallet using 2 Ledger HW

### ISSUE THREAD

**Issue by vmatekole** [bitpay/copay#3847]
Hi!

I recently bought 2 Ledger and a Trezor wallet with a plan to create a multisig wallet with the 3 as signers. I attempted to create a 2-2 wallet using my **Ledger wallets only**. However, it appears that the Copay wallet does not allow for 2 Ledger wallets to sign on the same computer. Is this correct?

**Comment by martindale** [comment]
@matiu can you provide some clarity here?  I'm very interested in this scenario as well.

**Comment by matiu** [comment]
See / Dup: https://github.com/bitpay/copay/issues/3688#issuecomment-199888483
