### ISSUE TITLE
Android Intent and Return Tx Hash

### ISSUE THREAD

**Issue by hifilij** [bitpay/copay#3849]
Hello,

I am posting this issue for Bitholla, a mobile app for Android that interfaces with mobile wallets.  After doing some testing with major wallet providers, we are coming across some different issues that affect the interoperability of our service with others.

To enable our services to work together, an intent should be called.  Here is some example code that should resolve this issue:

`// Include the transaction hash in the response
Intent result = new Intent();
result.putExtra(transaction_hash, _transaction.getHash().toString());
setResult(RESULT_OK, result);`

In addition, we would request that once a payment from the wallet has been completed, Copay should send back a success code including the transaction hash to Android apps interfacing with Copay.  We think that if this is done in general, it will benefit compatibility between all services.

If there are any further questions please let us know.  We can be reached at team@bitholla.io.  Thanks for taking the time to look into this.

Regards,

Paul Bugge

[copay bip 21.pdf](https://github.com/bitpay/copay/files/111256/copay.bip.21.pdf)

**Comment by matiu** [comment]
Thanks for getting in contact.

I dont think this will be a priority for us, please feel free to summit a PR in case you think it is needed.
