### ISSUE TITLE
Please disable cloudflare from https://bws.bitpay.com/

### ISSUE THREAD

**Issue by cryptokarnal** [bitpay/copay#3855]
In classic horrific cloudflare fashion, the app is broken from devices connecting through tor, and loading the wallet service url on a (torified) browser makes it obvious why:

One more step
Please complete the security check to access bws.bitpay.com

This renders the app useless when proxying over Tor, it won't ever get past the "I agree" in the beginning, and if the wallet creation is done outside of Tor, then re-enabling Tor proxying will always make the app hang at "Updating wallet...."

**Comment by matiu** [comment]
For the moment, removing cloudfare for the public BWS is not an option at the moment, but you can host your BWS (https://github.com/bitpay/bitcore-wallet-service), for enhanced privacy.

**Comment by dan-da** [comment]
I understand the motivations, no one likes a DOS attack, but still when I'm trying to access a site or service and I see that cloudflare warning, it lowers my opinion of the service.  ( and of course, of cloudflare. )

Perhaps bws could make an onion service available for tor users.
