### ISSUE TITLE
testnet option missing on chrome import wallet (present on android app)

### ISSUE THREAD

**Issue by tphyahoo** [bitpay/copay#3856]
on android:

  import wallet -> show advanced options
  has option for testnet

on chrome:
  missing this option

fix: testnet option needs to be included in chrome

**Comment by matiu** [comment]
In order to import testnet wallet you need to modify the 'coin type' path element in the derivation path.

Something like: 
m/44'/1'/0'

**Comment by nem25** [comment]
How do I find out what the coin type path is?

**Comment by matiu** [comment]
For testnet is 1. For mainnet 0.

If you are importing a single sig testnet wallet if is probably:

m/44'/1'/0'

**Comment by nem25** [comment]
I have a multisig 1 of 3 testnet wallet that I am trying to import

**Comment by matiu** [comment]
Try

m/48'/1'/0'

**Comment by nem25** [comment]
Awesome that worked! Thanks!

How can I figure this out in the future myself? Is there some documentation out there? Or is copay planning on adding this feature in the future?

**Comment by matiu** [comment]
PS: Sorry the delay, check BIP44 spec.
