### ISSUE TITLE
derivation path option missing on android create/import new wallet (present on chrome)

### ISSUE THREAD

**Issue by tphyahoo** [bitpay/copay#3857]
on chrome:

import/create wallet -> show advanced options
has option for derivation path

on android:
missing this option

fix: derivation path option needs to be included in android app for import and create wallet screens

**Comment by matiu** [comment]
Trhanks for the report. We will check it.

On Wed, Feb 3, 2016 at 11:43 PM, tphyahoo <notifications@github.com> wrote:

> on chrome:
>
> import wallet -> show advanced options
> has option for derivation path
>
> on android:
> missing this option
>
> fix: derivation path option needs to be included in android app
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3857>.
>



-- 
BitPay.com

**Comment by matiu** [comment]
it is shown on the current version, on Android.
