### ISSUE TITLE
Cancel button disappear in send tab

### ISSUE THREAD

**Issue by tanojaja** [bitpay/copay#3859]
![1](https://cloud.githubusercontent.com/assets/13851807/12821467/538fc72e-cb42-11e5-8a25-ecd7217fa98d.png)
![2](https://cloud.githubusercontent.com/assets/13851807/12821466/538e69c4-cb42-11e5-957d-8d2c55d0c837.png)
![3](https://cloud.githubusercontent.com/assets/13851807/12821468/5390480c-cb42-11e5-916e-d8889eb3fa3f.png)
![4](https://cloud.githubusercontent.com/assets/13851807/12821469/539a2b60-cb42-11e5-8e80-a76be33c3c73.png)

**Comment by cmgustavo** [comment]
Fixed on #3853. Thanks for report!

**Comment by tanojaja** [comment]
ACK
