### ISSUE TITLE
shared testnet wallet creation on chrome app results in livenet wallet (works on android)

### ISSUE THREAD

**Issue by tphyahoo** [bitpay/copay#3863]
when you try to create a shared testnet wallet on chrome app, the result is livenet wallet.

this does work on android however.

**Comment by matiu** [comment]
ACK

I was able to reproduce it. (only for shared wallets)

On Sat, Feb 6, 2016 at 2:08 AM, tphyahoo <notifications@github.com> wrote:

> when you try to create a shared testnet wallet on chrome app, the result
> is livenet wallet.
>
> this does work on android however.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3863>.
>



-- 
BitPay.com

**Comment by tphyahoo** [comment]
cool, chrome app auto updated and now works for me.

thanks.
