### ISSUE TITLE
Feature request - Copay/Android - Fingerprint authentication

### ISSUE THREAD

**Issue by cjr-roland** [bitpay/copay#3867]
Fingerprint authentication is now part of the standard Android API http://developer.android.com/about/versions/marshmallow/android-6.0.html#fingerprint-authentication

This would be a nice feature to add for the Android version of Copay in order to sign transactions. 
As far as I am aware, no wallet on the Playstore is using it.

**Comment by dotydevelopment** [comment]
+1

But does Cordova support this already?
