### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by XBTdev** [bitpay/copay#3875]
https://i.imgur.com/nv84fnJ.png

https://i.imgur.com/5oE73p6.png

Fetching plugin "hu.dpal.phonegap.plugins.spinnerdialog" via npm
Error: Failed to fetch plugin hu.dpal.phonegap.plugins.spinnerdialog via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Registry returned 404 for GET on https://registry.npmjs.org/hu.dpal.phonegap.plugins.spinnerdialog
* ERROR. Exiting...
make: *** [android-debug] Error 1

**Comment by cmgustavo** [comment]
It 's working for me. What version of `Cordova` are you using? Mine is 5.3.3

Thanks for report.

**Comment by XBTdev** [comment]
I'm running cordova 6.0.0

**Comment by XBTdev** [comment]
https://www.npmjs.com/package/hu.dpal.phonegap.plugins.spinnerdialog

**Comment by XBTdev** [comment]
Can I use this instead?

**Comment by XBTdev** [comment]
Downgraded cordova and build works.

Wish it worked with cordova 6.0.0 though

**Comment by matiu** [comment]
thanks for the update. For sure Cordova 6.0.0 will be supported in following versions.
