### ISSUE TITLE
Bug: Send to other copay wallet that backup is not completed

### ISSUE THREAD

**Issue by bitcoinuser** [bitpay/copay#3878]
Hi,
Reproducing:
1- You have a copay wallet (wallet 1) and then create another copay wallet (wallet 2).  
2- You select wallet 1 and go to send, then click on wallet icon. 
3- Now on my wallets tab, show the option to send bitcoins to wallet 2, even if wallet 2 has no backup  completed.

**Comment by tanojaja** [comment]
Remember this, a shared wallet still being a unique wallet. Multiple copayers are needed just to sign the transactions proposals. If you can send a paymet that's means you previously made a backup in order to receive any amount.

**Comment by bitcoinuser** [comment]
@tanojaja Didn't understand your post. Did you understand my bug report?

**Comment by cmgustavo** [comment]
Hi @bitcoinuser , I can see the issue, but I 'm not sure how is the best way to solve it. Do you think that we shouldn't show wallets without backups? Or just display a warning or something?

Thanks for report.

**Comment by bitcoinuser** [comment]
I can' generate addresses If I don't complete the bakup. So I think we shouldn't allow send to a wallet where the backup is not completed too. I think should show a message telling the user to complete the backup first.

**Comment by tanojaja** [comment]
My bad @bitcoinuser, I'm agree with showing a error/warning message. +1
