### ISSUE TITLE
Questions about how Copay backup works

### ISSUE THREAD

**Issue by bitcoinuser** [bitpay/copay#3879]
Hi, I think Copay backup confused.
1-  I created a wallet, encrypted the seed, then I deleted the seed from Copay. When I go to spend the bitcoins, will I need to insert the seed?

2- If I deleted the seed, why is possible to export the Wallet? I think shouldn't be possible, right? On Wallet Preferences/Advanced.

3- If I deleted the seed, why is possible to Request a password? On wallet preferences/Security Preferences.

**Comment by dabura667** [comment]
"Deleting the seed" only deletes the actual words themselves. It does not delete the extended private key, so deleting the words will only remove the words, but all your private keys will still be there.

If you want to create a "watch-only" wallet, you must EXPORT the wallet and check the "Export without private keys" then delete the wallet from your device... then IMPORT the wallet you just EXPORTED (which has no private keys) and you will have a wallet with 0 ability to send bitcoin, and can only create proposals that another device (with the private keys) must sign.

**Comment by matiu** [comment]
To add to @dabura667 reponse, note that the `seed` (12 mnemonic words) and the actual private key are different entities.  The private key can be derived from the seed, but NOT the other way around. 

The option to remove the `seed` is to prevent someone to see the (relatively easy to copy) mnemonics on Copay. But the private key is still there. And can be exported.

To create the wallet without the seed and without the private key, you need to export it *without the private key*, as @dabura667 explained.

Please let us know any doubt.

**Comment by bitcoinuser** [comment]
(The private key can be derived from the seed, but NOT the other way around.)

1- So if I delete the seed, how copay generates new addresses?
2- If I Export the wallet, then I delete the seed, then I create many new addresses, Will the file from export wallet be able to recover the bitcoins from all addresses I created after I deleted the seed?

I think Copay should explain better (inside copay app) the difference between export wallet, backup seed and request password.

Thanks.

**Comment by matiu** [comment]
> 1- So if I delete the seed, how copay generates new addresses?

It still has the private key stored ( when I say private key, I mean the Extended Master Private Key, in the BIP32 sense).

> 2- If I Export the wallet, then I delete the seed, then I create many new addresses. Will the file from export wallet be able to recover the bitcoins from all addresses I created after I deleted the seed?

Yes. Addresses are derived from the extended master private key.
