### ISSUE TITLE
Question: Read only addresses

### ISSUE THREAD

**Issue by wzrdtales** [bitpay/copay#3880]
Short question:

What are the plans to support read only addresses?
I am building a cold storage with https://github.com/bitpay/bitcore-wallet and it would be interesting to know if it will be possible to use copay to watch and also create unsigned transactions. Most of the time those will be created automatized anyway, but there are always some manual transactions.

Thank you

**Comment by XBTdev** [comment]
You can do an export of a wallet and check the checkbox to not include private keys. Then you can restore this export into copay and you'll have a wallet with no private keys. If you create a transaction proposal, other copay devices with this wallet will see the proposal and be able to sign it.

**Comment by wzrdtales** [comment]
This was actually kind of an answer, but not to my actualy question. I did not asked to create a read only from a co pay wallet, guess I will have to look and search for that piece of the source myself. Please don't just close tickets without actually verifying that the question was answered, this is a very rude behavior...

**Comment by matiu** [comment]
Sorry, we leave open tickets only when there are open issues to be resolved, in order to organize our work. 

If you are planning to make automated agents, please check https://github.com/bitpay/bitcore-wallet-client and  https://github.com/bitpay/bitcore-wallet-service (the backend and its client, used by Copay).

**Comment by wzrdtales** [comment]
@matiu That is still not a reason to close things without saying a word or anything and this is not resolved.

Thanks for your answer though. As already stated in my question, my question is not how to do it, or how I create a read only wallet from a copay wallet. I know about the wallet client I have actually linked the wrapper in the link description. It might be also my fault for being not clear enough, so next try:
What I ask for is the interoperability between copay and the wallet client. Are there plans to support in copay to just drop in the xpub instead of using the seed or import a file backup? Or is this nothing from interest and I will have to grab the source part from copay to create the file backup together with the bw-client?

**Comment by XBTdev** [comment]
This is related to #2894 - which is closed

There is also an open ticket for AirGapped operation #3217 - but this ticket was recently marked low priority

https://github.com/bitpay/bitcore-wallet#airgapped-operation

**Comment by wzrdtales** [comment]
Managed to get a file export from my cold wallet into copay, viewing works but currently it is also not possible to create a txproposal through copay.
