### ISSUE TITLE
How to integrate Java and CoPay

### ISSUE THREAD

**Issue by edeykholt** [bitpay/copay#3882]
I really like CoPay's user interaction model, but I'd rather not deploy javascript on my servers.
Is there a Java client that supports talking with CoPay? If I wanted to interface my Scala-based server with CoPay protocols (for creating multi-sig wallets, invitations, and spend proposals), how would you suggest I do it?

**Comment by dabura667** [comment]
No.

The best way to do it would be difficult if you have 0 experience with bitcoin development. It would entail:
1. Study up on how bitcore-lib works
2. Study up on how bitcoinj works (afaik, bitcoinj (java) is a ways behind bitcore-lib (node-js) as far as supporting the newest tech. I don't even think bitcoinj can generate multisig addresses without some hoop jumping)
3. Port bitcore-wallet-service to Java.
4. Port insight-api to Java (blockchain parser)

bitcore is a finely woven ecosystem based around nodejs... so depending on how much you want to dive into it, you'll need to do a lot of porting...

**Comment by edeykholt** [comment]
@dabura667, thank you.

**Comment by isocolsky** [comment]
As an alternative to what @dabura667 proposed. If you would like to interact with BitPay's Bitcore Wallet Service instance, all you need to do is reimplement [Bitcore Wallet Client](github.com/bitpay/bitcore-wallet-client) in java. This would still require experiencie with Bitcoin development though.
