### ISSUE TITLE
Could not broadcast payment: error query the blockchain

### ISSUE THREAD

**Issue by utxorob** [bitpay/copay#3886]
Can someone help me with this??? I have 5k just sitting in my wallet.

**Comment by utxorob** [comment]
It's been 3 hours...

**Comment by matiu** [comment]
Could you provide more details?

Is it a multisig wallet? What platform are you using? Can you delete the payment proposal and try again?

**Comment by utxorob** [comment]
Using iOS new version iPhone 6. Multisig. Both of us signed off on it. Won't let me cancel payment something about 24 hour wait. Customer waiting on this coin. And if price goes down ....

**Comment by matiu** [comment]
The other copayer (the creator) can delete the payment immediately. Could you try that?

**Comment by utxorob** [comment]
Will not let me delete it either... Wallet is fucked who created this?

**Comment by utxorob** [comment]
Can someone who works for copay fix this shit. It's 5k for shits sake

**Comment by matiu** [comment]
Could you show a screen shot when you try to delete the payment proposal from the creator of the payment proposal?

Please contact my in private at matias@bitpay.com to provide sensitive info. We can investigate further if you give us some wallet info.

**Comment by utxorob** [comment]
Sent email manually do it if ou have to

**Comment by matiu** [comment]
resolved offline.
