### ISSUE TITLE
internal notes

### ISSUE THREAD

**Issue by vaikekana** [bitpay/copay#3889]
hi copay!

its really important to be able to write internal notes, to remember what transactions where from/to who.

i know when making a transaction, its possible to add an optional note, which is great.  but if viewing historical transactions in "history", it would be perfect to be able to add a note later, on a historical transaction.  

currently, its impossible to add any notes in incoming funds either (only to add notes to outgoing funds at the time of making transaction). similarly, there needs to be a way to edit existing notes too

![copay_-_multisignature_wallet](https://cloud.githubusercontent.com/assets/417269/13155026/6ea19220-d684-11e5-959b-cf28a359e6ae.png)

also when viewing history, it would be very handy to have a running balance next to each transaction.

![copay_-_multisignature_wallet](https://cloud.githubusercontent.com/assets/417269/13155113/c7c3e5ba-d684-11e5-8387-f97297b4f19f.png)

thanks tim

**Comment by matiu** [comment]
Thanks for your ideas.

I really like the 'add note' in history!

**Comment by Jacobbubble** [comment]
+1 For running balance and notes on receive.

**Comment by bitcoinuser** [comment]
+ 1

**Comment by nvk** [comment]
👍

**Comment by gabegattis** [comment]
@matiu This might go well with the new tx history stuff I'm working on. It would be worth thinking about once I'm done with the main part of it.

**Comment by matiu** [comment]
done on Copay 2.0
