### ISSUE TITLE
Illegal State error after joining wallet 

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#3892]
I created a 2-of-2 testnet wallet on my pc and then joined the wallet with mobile.  After the wallet was joined I noticed that the amount and tx history did not update (the sync icon remained flashing).  I clicked on the amount to refresh and checked the console output (on pc).  The console has the error "Illegal state".  Wallet seems to be okay afterward. See screenshot attached.

![screen shot 2016-02-18 at 4 31 27 pm](https://cloud.githubusercontent.com/assets/1063765/13158918/2c706c36-d65d-11e5-9713-08220b074155.png)

Built from master (e867a6a0c7680b57d71fc9ddbd4343d28c934d82)

**Comment by cmgustavo** [comment]
Hi @ajp8164 , 
I think it is a known issue that was already fixed on BWC (https://github.com/bitpay/bitcore-wallet-client/pull/220). Just waiting for release a new version. 

Also, here the original issue: #3864 

Could you check please if it 's exactly the same problem? Thanks.

**Comment by ajp8164** [comment]
Yes. This appears to be the same issue as reported in #3864.

--
Andy Phillipson
Director of Engineering Services, BitPay, Inc.
844A CCA5 F277 30C0 E86F  9799 0CEE 502F 2484 0854
