### ISSUE TITLE
dollar conversion from real exchanges

### ISSUE THREAD

**Issue by lucaszanella** [bitpay/copay#3921]
Hi, the dollar conversion for BRL is innacurate, because exchanges won't trade at this value in my country, neither credit card will charge at that price, so I'd suggest, at least for BRL, to use the price from mercadobitcoin.com.br and foxbit.exchange, otherwise it has no point in using showing the price in another currency.

**Comment by KeyJockey** [comment]
Yes, my Issue/Suggestion to have user-configurable price index source would solve this too: https://github.com/bitpay/copay/issues/3382

**Comment by matiu** [comment]
Closing this one an leaving #3382
