### ISSUE TITLE
I am a complete beginner and I am unable to understand the source code. Can you please highlight where is the server side code? Is there any documentation for copay?

### ISSUE THREAD

**Issue by sadiakhalil123** [bitpay/copay#3925]

**Comment by afrikanhut** [comment]
How do I install this system to my server?

**Comment by dabura667** [comment]
https://bitcore.io/guides/wallet-service/

**Comment by gabegattis** [comment]
As @dabura667 mentioned, you can view the guide to running the server at https://bitcore.io/guides/wallet-service/

This will let you set up a Bitcore full node. The node will also run Insight-API and Bitcore-Wallet-Service as services. You can also add Insight-UI to get the Insight block explorer.
