### ISSUE TITLE
Tx history search suggestions

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#3929]
- When I click the search icon I should see all the tx history by default, as I type the history will filter down.
- Searching for an amount should disregard the comma in "2,500 bits"; typing "25" should reveal "2,5" and "25".
- Searching for a bitcoin transaction id should be case sensitive "Png" is different than "png".  I imagine that as the history gets bigger this will be needed.
- Rather than "playing" with the html of walletHome, the search function should be a separate modal.  This will reduce the complexity of walletHome to make it more maintainable and less likely to receive future bugs.

**Comment by JDonadio** [comment]
Pending https://github.com/bitpay/copay/issues/5159
