### ISSUE TITLE
Unconfirmed transactions

### ISSUE THREAD

**Issue by arruah** [bitpay/copay#3942]
I have two transactions which do not have confirmation of three days. I do not know what to do. Can you help me? I sent to the mobile wallet bitpay. 
https://redd.it/48hhy5
https://blockchain.info/ru/tx/5f93d69938d57309e9d03d442dc6b80f6fa28ed62cde9c29668ea8eb4042d180
https://blockchain.info/ru/tx/7cf14e9e0c8c05ef2b560907529f57e8bbee69bcdad6c41907fdddd6108b19b6

**Comment by Jacobbubble** [comment]
It seems both transactions have been confirmed. The fee rate is pretty typical too, it should have been confirmed within 6 blocks.
