### ISSUE TITLE
Support Hardware Wallets with Android version using OTG USB cable

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#3943]
https://github.com/trezor/trezor-android

Would be nice :-D

https://github.com/LedgerHQ/btchip-java-api

Could also work if it seems easier.

I'll leave this issue open to discuss what kind of technical hurdles are in the way of this.

Are there currently any issues preventing this, for instance, something with cordova?

**Comment by matiu** [comment]
ATM we are using the Trezor Connect API, that seems to be only available with Google Chrome.  I agree it would be nice to support Android w/Trezor! Let us check if that is something that could be possible to do from our current mobile software stack.

**Comment by mitzip** [comment]
Adding hardware wallet capability outside of chrome app would be amazing! NFC on andriod with Ledger Unplugged, unstoppable! Great work and thank you!

**Comment by evilsocket** [comment]
+1
