### ISSUE TITLE
bitWallet HD compatibility - m/i'/0/k

### ISSUE THREAD

**Issue by OliverCole** [bitpay/copay#3944]
bitWallet generates HD wallets with a variety of options (below). Are any of these compatible?

I tried entering m/i'/0/k into copay, and it said that was an invalid derivation path.

![img_6049](https://cloud.githubusercontent.com/assets/6171713/13475969/7acc2784-e0bd-11e5-9140-60cd41967623.PNG)

**Comment by martindale** [comment]
Are you importing an existing root key and attempting to re-scan?

**Comment by OliverCole** [comment]
No, I'm attempting to import with the mnemonic sentence/seed. If you're lacking something to do, bitWallet is free on the app store, you should be able to reproduce it.

**Comment by dabura667** [comment]
Copay doesn't know what i and k means. They aren't a part of the standard.

Pick an account index, (0 prolly)

You want m/0'

**Comment by OliverCole** [comment]
Same error as above - invalid derivation path.

**Comment by dabura667** [comment]
https://github.com/bitpay/copay/blob/master/src/js/services/derivationPathHelper.js

This is called in the create, join, and import methods and apparently it rejects any path that does not have either 44' or 48' as the first level and 0' or 1' for the second level. (1' will activate testnet mode)

bitWallet paths are not supported by Copay.

You should send all your bitcoins to Copay and generate a new wallet with Copay.

**Comment by OliverCole** [comment]
Yeah, I suspected as much. 

It would be nice to support other paths so users can migrate fee free from other apps... or in the situation where the old app is no longer available and they are using a paper backup of the seed/passphrase/path.

**Comment by dabura667** [comment]
> It would be nice to support other paths so users can migrate fee free from other apps...

That's what BIP44 is for. Copay follows BIP44. Tell bitWallet to support BIP44 as default and we won't have these sorts of problems.

1. If we have to keep a list of every path that every wallet has ever used ever, that's outrageous.
2. If we let the user pick random paths, then they are putting themselves at risk if they don't know what they're doing. (hint: many people who don't know what they're doing think they know what they're doing, and then they don't and they lose money)

Therefore, I think sticking with BIP44 is a good call.
