### ISSUE TITLE
Invalid due to double spend attempt

### ISSUE THREAD

**Issue by JohnMathers69** [bitpay/copay#3946]
I purchased 0.4 BTC from an ATM machine (March 2nd) and entered my copay wallet address. A while later it was in the activity log on the application. I then sent the bitcoins to another address not knowing that the first transaction was still unconfirmed. Now in my copay wallet, it says "This transaction has become invalid; possibly due to a double spend attempt." I don't know what a double spend is but I am sure I did not attempt it. I am very new to this and extremely confused and worried about where my money is. Please help me

**Comment by matiu** [comment]
Hi,

Could you share the transaction ID? You can see if when you open the TX details, and click on 'see if on the blockchain'

**Comment by JohnMathers69** [comment]
<img width="402" alt="screen shot 2016-03-03 at 3 20 01 pm" src="https://cloud.githubusercontent.com/assets/17627121/13513088/7e84392a-e153-11e5-950f-5fcf4451c8e8.png">

When i press see it on block chain, it says transaction not found (for both of them)

**Comment by matiu** [comment]
Given that that original incoming transaction was never confirmed, you
need to contact the ATM owner.  If you go
to Settings -> Advanced -> Wallet Information you can see your wallet
addresses. You can provide the address you used for the ATM for
reference.

**Comment by JohnMathers69** [comment]
Is there a possibility that I would be able to get my money?

**Comment by matiu** [comment]
The coins were never in your possession, so you should contact the ATM owner.
