### ISSUE TITLE
Bitcoin Network Fee Policy is a global setting

### ISSUE THREAD

**Issue by Jacobbubble** [bitpay/copay#3947]
I find myself often having to switch back to global settings in the middle of creating a transaction when I want to send a transaction with a different fee policy.

Mycelium has the fee policy setting on the transaction creation screen so that the setting can easily be toggled on a transaction basis.

**Comment by dabura667** [comment]
It used to be like that.

Was removed because it cluttered up the transaction screen too much.

**Comment by matiu** [comment]
yes, it was removed to clean the `send` screen. It seems to fit better most users needs.
