### ISSUE TITLE
Could not broadcast payment: error querying the blockchain

### ISSUE THREAD

**Issue by AcselUA** [bitpay/copay#3948]
Copay multisignature wallet on windows10
Can someone help me with this?

**Comment by matiu** [comment]
Could you check you network connectivity?

Is it possible that transaction you are trying to broadcast has its inputs already spent? (you can try deleting the payment and start again).

**Comment by AcselUA** [comment]
How can I check network connectivity?

I can delete transaction and make new one, but it show same error

**Comment by kangasbros** [comment]
Same error here. Would be happy to receive any assistance.

**Comment by kangasbros** [comment]
Or is there any way to receive the raw transaction? It appears like the transaction was signed etc properly, but for some reason we can't broadcast it :(

**Comment by matiu** [comment]
Are you getting "Error querying the blockchain"?

**Comment by kangasbros** [comment]
Yep. Could the reason be that the transaction has too many inputs? This wallet was working earlier properly, and everything worked as well for a smaller transaction earlier.

**Comment by kangasbros** [comment]
Also, is there a way to get out the raw transaction? That would help debugging the problem quite a lot.

**Comment by matiu** [comment]
Copay should handle TX with many inputs fine. It could be a problem that one of the inputs is not longer available.

 = Can you delete the payment proposal  and refresh the balance and try a smaller output JIC?
  = IIRC, the raw transaction is show at the logs. Check Global Settings > About Copay > Session Logs
(after it failed to broadcast).

If you prefer, let us know the WalletId (available on Settings > Advanced> Wallet Info) and we can check the TX on the DB. (if you prefer send it privately to me (matias@bitpay.com))

**Comment by kangasbros** [comment]
We have our own wallet-core server. Where should I look for the transaction?

**Comment by matiu** [comment]
Then is almost sure a problem related to the backend.

Be sure you bitcore node is alread synchronized with the blockchain.

Please if you still have the issue report it to https://github.com/bitpay/bitcore

**Comment by maximilliangeorge** [comment]
Having the same issue. In sync and all.
