### ISSUE TITLE
Windows Phone app stop function, 

### ISSUE THREAD

**Issue by alextheangel** [bitpay/copay#3949]
the windows phone app act abnormal on windows 10 mobile device, with the setting and menu botton not function, it worked before.

**Comment by matiu** [comment]
What device are you using? For the moment we are only supporting WP 8.x

**Comment by alextheangel** [comment]
Lumia 950 which only run on windows 10 , but it worked before until I need to reset my phone, and reinstall the app.

**Comment by matiu** [comment]
We have sent an update (1.9.3) to the WP store to try to fix this issue. Could you try it once it is published and report if it is working properly? Thanks a lot.

**Comment by eaxvac** [comment]
I've tested on the Nokia Lumia 1520, running W10M build 10.0.1056.107.
Yes it works now. Thank you :+1:

**Comment by matiu** [comment]
thanks!

**Comment by alextheangel** [comment]
THanks for the update, now it works fine now. and any plan for an Windows 10 UWP app ?
