### ISSUE TITLE
Windows Phone Not sending

### ISSUE THREAD

**Issue by bizichild** [bitpay/copay#3951]
Trying to send but the button wont function! none of them do after the initial click. Lumia 950

**Comment by matiu** [comment]
Thanks for the report. We will check it and let you know.

**Comment by bizichild** [comment]
what am I suppose to do until then?  I need access to my funds asap!  =(

**Comment by cmgustavo** [comment]
Are you using Windows Phone 8.1? Did you upgrade your phone to Windows 10?

**Comment by matiu** [comment]
you can import you wallet on other device. (like a laptop) see copay.io for
all the available platforms.

On Fri, Mar 4, 2016 at 5:14 PM, bizichild <notifications@github.com> wrote:

> what am I suppose to do until then? I need access to my funds asap! =(
>
> On Fri, Mar 4, 2016 at 2:11 PM, Matias Alejo Garcia <
> notifications@github.com> wrote:
>
> > Thanks for the report. We will check it and let you know.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/bitpay/copay/issues/3951#issuecomment-192445825>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3951#issuecomment-192446865>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by bizichild** [comment]
I'm using a Lumia 950, windows 10 the latest build. Sometime between
yesterday and today my copay app was automatically updated.  Now nothing
functions in the app! I cant get to settings, I cant send, oh but I can
receive!  I have my blockchain confirmations etc.... can I transfer it to
another wallet?

**Comment by matiu** [comment]
We do not support windows 10 yet.

Can you restore the backup on other device?

On Fri, Mar 4, 2016 at 5:32 PM, bizichild <notifications@github.com> wrote:

> I'm using a Lumia 950, windows 10 the latest build. Sometime between
> yesterday and today my copay app was automatically updated. Now nothing
> functions in the app! I cant get to settings, I cant send, oh but I can
> receive! I have my blockchain confirmations etc.... can I transfer it to
> another wallet?
>
> On Fri, Mar 4, 2016 at 2:15 PM, Matias Alejo Garcia <
> notifications@github.com> wrote:
>
> > you can import you wallet on other device. (like a laptop) see copay.io
> > for
> > all the available platforms.
> >
> > On Fri, Mar 4, 2016 at 5:14 PM, bizichild <notifications@github.com>
> > wrote:
> >
> > > what am I suppose to do until then? I need access to my funds asap! =(
> > >
> > > On Fri, Mar 4, 2016 at 2:11 PM, Matias Alejo Garcia <
> > > notifications@github.com> wrote:
> > >
> > > > Thanks for the report. We will check it and let you know.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/bitpay/copay/issues/3951#issuecomment-192445825
> >.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/bitpay/copay/issues/3951#issuecomment-192446865>.
> > >
> >
> >
> >
> > --
> > Matías Alejo Garcia
> > @ematiu
> > Roads? Where we're going, we don't need roads!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/bitpay/copay/issues/3951#issuecomment-192447413>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3951#issuecomment-192456283>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by bizichild** [comment]
I cant use the info from the blockchain? I literally just deposited bits to
my wallet... about an hour ago.  The back up I have is from the initial
setup, does that count?

**Comment by matiu** [comment]
yes, the backup does not change.

Just import it on  ther device and should work.

We will be releasing a patch for windows 10 very soon.

On Fri, Mar 4, 2016 at 5:38 PM, bizichild <notifications@github.com> wrote:

> I cant use the info from the blockchain? I literally just deposited bits to
> my wallet... about an hour ago. The back up I have is from the initial
> setup, does that count?
>
> On Fri, Mar 4, 2016 at 2:34 PM, Matias Alejo Garcia <
> notifications@github.com> wrote:
>
> > We do not support windows 10 yet.
> >
> > Can you restore the backup on other device?
> >
> >
> > On Fri, Mar 4, 2016 at 5:32 PM, bizichild <notifications@github.com>
> > wrote:
> >
> > > I'm using a Lumia 950, windows 10 the latest build. Sometime between
> > > yesterday and today my copay app was automatically updated. Now nothing
> > > functions in the app! I cant get to settings, I cant send, oh but I can
> > > receive! I have my blockchain confirmations etc.... can I transfer it
> to
> > > another wallet?
> > >
> > > On Fri, Mar 4, 2016 at 2:15 PM, Matias Alejo Garcia <
> > > notifications@github.com> wrote:
> > >
> > > > you can import you wallet on other device. (like a laptop) see
> > copay.io
> > > > for
> > > > all the available platforms.
> > > >
> > > > On Fri, Mar 4, 2016 at 5:14 PM, bizichild <notifications@github.com>
> > > > wrote:
> > > >
> > > > > what am I suppose to do until then? I need access to my funds asap!
> > =(
> > > > >
> > > > > On Fri, Mar 4, 2016 at 2:11 PM, Matias Alejo Garcia <
> > > > > notifications@github.com> wrote:
> > > > >
> > > > > > Thanks for the report. We will check it and let you know.
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <
> > https://github.com/bitpay/copay/issues/3951#issuecomment-192445825
> > > >.
> > > > >
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> https://github.com/bitpay/copay/issues/3951#issuecomment-192446865
> > >.
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Matías Alejo Garcia
> > > > @ematiu
> > > > Roads? Where we're going, we don't need roads!
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/bitpay/copay/issues/3951#issuecomment-192447413
> >.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/bitpay/copay/issues/3951#issuecomment-192456283>.
> >
> > >
> >
> >
> >
> > --
> > Matías Alejo Garcia
> > @ematiu
> > Roads? Where we're going, we don't need roads!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/bitpay/copay/issues/3951#issuecomment-192457596>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3951#issuecomment-192458843>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by matiu** [comment]
(probably will be fixed by https://github.com/bitpay/copay/pull/3952)

**Comment by bizichild** [comment]
how do I launch this update to my phone?

**Comment by bizichild** [comment]
I don't remember ever using a password for my backup... if I did, its always the same password... its not working.  Any ideas? is there a special format I have to follow?

**Comment by bizichild** [comment]
The bottom menu now works... Top Left and Top Right still doesn't work.... and most importantly the send button.

**Comment by matiu** [comment]
1.9.2 will be released to the windows phoen store soon. Please let us know
how it go.

On Fri, Mar 4, 2016 at 6:23 PM, bizichild <notifications@github.com> wrote:

> The bottom menu now works... Top Left and Top Right still doesn't work....
> and most importantly the send button.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3951#issuecomment-192470910>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by matiu** [comment]
Related to https://github.com/bitpay/copay/issues/3949#issuecomment-193220350

Should be fixed in 1.9.3  Please reopen if this is still an issue.
