### ISSUE TITLE
Auto-insert digit separators

### ISSUE THREAD

**Issue by Jacobbubble** [bitpay/copay#3954]
On the `send` screen, the `AMOUNT` field doesn't place separators between large amounts, hurting readability. 1000000 should be b1,000,000 (or b1.000.000 for Europe). Same goes for fiat values.

This should be auto-inserted, but currently "," aren't allowed and multiple "."'s aren't recognized as a valid amount.

Not sure if #3062 is somewhat related but it seems to be separate.

**Comment by JDonadio** [comment]
Pending a little format issue here https://github.com/bitpay/copay/issues/5162
