### ISSUE TITLE
Password on copay

### ISSUE THREAD

**Issue by utxorob** [bitpay/copay#3956]
Apparently I have a password on my copay how do I figure out what it is? There is no option for recovering it and I have 10k in the wallet

**Comment by utxorob** [comment]
Anyone have advice??

**Comment by matiu** [comment]
The password is to encrypt the priv key. I am afraid it is not possible to
recover it. Dont you have a backup?

**Comment by Jacobbubble** [comment]
Question @matiu does Copay hold the private key unencrypted client side? I.e. is this a soft security feature that can be circumnavigated, or is the only option to bruce force the encrypted private key?

**Comment by utxorob** [comment]
Um no what do you mean? It has never asked me for password. I have 10k on there it asked for my figure print and password 

Rob Gonzalez
956-648-2089

**Comment by utxorob** [comment]
Guys it asked for my finger print and that passes then it asks for my password. Which I have tried every password I know for 90 min. I can't figure it out. It's 10k guys. 

Rob Gonzalez
956-648-2089

**Comment by matiu** [comment]
No. The key is encrypted if the user set a password.

**Comment by utxorob** [comment]
You can't turn my password off?

Rob Gonzalez
956-648-2089

**Comment by utxorob** [comment]
What do I do?

**Comment by Jacobbubble** [comment]
@utxorob Do you have the 12 words backed up? When you first try to receive money, Copay will prompt you to back up those words.

If you don't remember your password AND you didn't backup the words, your only real option is to brute force it. That's not guaranteed to work though.

**Comment by utxorob** [comment]
I don't even remember setting a password...

**Comment by utxorob** [comment]
I never received any 12 words

**Comment by Jacobbubble** [comment]
@utxorob What happens when you go to the receive screen?

**Comment by utxorob** [comment]
Guys it was a pin...

**Comment by utxorob** [comment]
Wasn't even words ...

**Comment by utxorob** [comment]
Luckily I figured it could be a pin

**Comment by dabura667** [comment]
> Guys it was a pin...

So I'm guessing that means you figured out your password.

I know you're freaking out, but it's hard to understand exactly what's happening on your end if you don't write in coherent sentences.

**Comment by dabura667** [comment]
If you still can't find your password, here's a few questions:

1. What device are you using now? What device did you use to first generate your wallet?
2. When did you first create your wallet? (this is important)
3. Do you ever remember seeing a screen like the below? If you have your wallet's 12 words written down you can restore your wallet at any time.

![sfgsd](https://cloud.githubusercontent.com/assets/6586275/13543946/a547c0ac-e2b3-11e5-943b-d62633cb947d.PNG)

**Comment by utxorob** [comment]
The password was a series of numbers 

Rob Gonzalez
956-648-2089

**Comment by dabura667** [comment]
Just guessing...

Is it 2089?

**Comment by richardsuns** [comment]
@utxorob 
if done have the 12 phrase and you couldn't restore your wallet.
i can crack your password. this is the only option.
you can reach me at telgrm. my telgrm id is: @walletrecover
