### ISSUE TITLE
Show mining fee under "Details" of the "Transaction" screen for receiving money.

### ISSUE THREAD

**Issue by Jacobbubble** [bitpay/copay#3959]
Often I like to know what mining fee was used to send me money in order to estimate how long a transaction will take to confirm.

Currently, Copay shows the mining fee when a transaction is outgoing but not incoming. I have to click "SEE IT ON THE BLOCKCHAIN" every time in order to see the mining fee.

**Comment by isocolsky** [comment]
I like the idea of having a way to estimate how long it will take for a tx to confirm. I don't think showing the fee is the right approach though. Unless you also know the size of the tx and the status of the Bitcoin network, it is going to be really hard to estimate.
Maybe Copay could evaluate these parameters for you and assess the expected time/blocks for a  confirmation?

**Comment by Jacobbubble** [comment]
To get a very accurate estimation, sure. I want to know if they sent a mining fee of b10 of b1,000 though. That gives me a rough estimation.

Either way, transaction "details" already show the mining fee on a send. It's still useful to show it on a receive.

**Comment by JDonadio** [comment]
Fee is currently displayed in transaction details
