### ISSUE TITLE
Raspberry Pi support?

### ISSUE THREAD

**Issue by tapansino91** [bitpay/copay#3961]
Not sure if this has been asked before, but is Raspberry Pi support something that is being considered for a future release? Or is it something that's already possible, and maybe there's some instructions published on how to do a Raspberry Pi build? As it stands right now, Copay seems like it is in an excellent position to compete with Armory (and in fact surpasses Armory in several key areas, like supporting BIP 32 for example). The only thing that seems to be missing is the ability to set up something like an air-gapped Raspberry Pi for offline cold storage.

So is this being considered by chance?

**Comment by dabura667** [comment]
You can install on Raspberry Pi.

**Comment by matiu** [comment]
Also, check https://github.com/bitpay/bitcore-wallet  an other BWS client,  that supports air gapped operation (only CLI).

**Comment by Nogreedy** [comment]
@dabura667 How can I install Copay on my Raspberry Pi2/Raspbian ?
Is it Copay-linux.zip release to use for Raspberry?
Do I ned to install NW.js ?
Or do I need to clone the source (git clone) and install bower and grunt ...  ??
Thank you for your answer.

**Comment by tapansino91** [comment]
Bump. Can someone provide some answers to Nogreedy's questions? I've tried running the Copay linux executable directly on the Raspberry Pi 1B, but it doesn't seem to do much of anything. Do we have to do a full build on the Pi to get a working version?
