### ISSUE TITLE
UI design bug

### ISSUE THREAD

**Issue by bitcoinuser** [bitpay/copay#3963]
Hi, I installed Copay on Xiaomi MI4 and it has a blank line on top. See the screenshot:

![screenshot_2016-03-06-14-24-36_com bitpay copay](https://cloud.githubusercontent.com/assets/1178856/13555956/efbb5186-e3ac-11e5-8db0-640b40d16b52.png)

**Comment by matiu** [comment]
should be fixed in Copay 2.0
