### ISSUE TITLE
UI design problem

### ISSUE THREAD

**Issue by bitcoinuser** [bitpay/copay#3964]
Hi, I tried to send bitcoins to a wallet without backup and show this message: Destination wallet needs backup. 
Ok, I understand I need to do a backup before send bitcoins to this wallet. But, I see the Send button with a gray color that look like inactive. But for my surprise, the button is active. 
I think the way the button appear, most people think i'ts inactive, that clicking on it, nothing will happen. 
For active buttons, the color should be maybe more glossy? 

See the screenshot to see the problem:

![screenshot_2016-03-06-14-52-25](https://cloud.githubusercontent.com/assets/1178856/13556017/9891fb24-e3ae-11e5-9e33-552571abd6e9.png)

**Comment by matiu** [comment]
thanks, we will check it.
