### ISSUE TITLE
Email Notifications are duplicated per device with notification set

### ISSUE THREAD

**Issue by Jacobbubble** [bitpay/copay#3969]
This is ultimately a sync issue and possibly related to #3955.

Having "x" devices with the same email set for "Email Notifications" produces "x" emails per notification instead of 1 email per notification.

**Comment by matiu** [comment]
Is this a 1-1 wallet? Or a multisig wallet?

**Comment by matiu** [comment]
So, for 1-1 wallets, no more that one emails is sent per email address, no matter how many devices you have. For multisig wallets, it does make sensse to send multiple emails, you can disable notifications in one copayer to avoid this.
