### ISSUE TITLE
cannot 'select a wallet' when opening a bitcoin URI w/ address & amount on Android v1.9.2

### ISSUE THREAD

**Issue by aiouy** [bitpay/copay#3971]
I'm getting some lag and/or page freeze when I open a bitcoin URI w/ address & amount coming from another app. I cannot 'Select a wallet'. Tapping on one does nothing. Usually 20-30 seconds in, I am redirected to my wallet activity page without having sent transaction.

Running on Nexus 5 Android 6.0.1, Copay v1.9.2
Replicated on an LG G4, Android 6.0, Copay v1.9.2

**Comment by cmgustavo** [comment]
Hi @aiouy , sorry for the inconvenience. We can reproduce the issue and right now we are working on a fix.

Thanks for report.
