### ISSUE TITLE
Only TXPs type SIMPLE are supported in TREZOR

### ISSUE THREAD

**Issue by chrisrico** [bitpay/copay#3976]
We've been running on our own Bitcore server for a while, but today while doing an upgrade we switched to Bitpay's. We're all getting this error when attempting to send transactions on 1-of-3 Trezor backed wallet.

**Comment by chrisrico** [comment]
Here is the transaction proposal that Copay won't let me sign with my Trezor.

```
{ version: 3,
    createdOn: 1457547169,
    id: '...',
    walletId: '...',
    creatorId: '...',
    network: 'livenet',
    outputs: [ [Object] ],
    amount: 1000000,
    message: 'Test',
    payProUrl: null,
    changeAddress: 
     { version: '1.0.0',
       createdOn: 1457547169,
       address: '...',
       walletId: '...',
       isChange: true,
       path: 'm/1/205',
       publicKeys: [Object],
       network: 'livenet',
       type: 'P2SH',
       hasActivity: null,
       _id: '...' },
    inputs: [ [Object] ],
    walletM: 1,
    walletN: 3,
    requiredSignatures: 1,
    requiredRejections: 1,
    status: 'pending',
    txid: null,
    broadcastedOn: null,
    inputPaths: [ 'm/1/190' ],
    actions: [],
    outputOrder: [ 1, 0 ],
    fee: 16151,
    feePerKb: 48357,
    excludeUnconfirmedUtxos: false,
    addressType: 'P2SH',
    customData: null,
    proposalSignature: '...',
    proposalSignaturePubKey: null,
    proposalSignaturePubKeySig: null,
    derivationStrategy: 'BIP44',
    creatorName: 'Chris',
    deleteLockTime: 84899,
    encryptedMessage: '{"iv":"y4n2+jgNJEvbEEnWQxhlkw==","v":1,"iter":1,"ks":128,"ts":64,"mode":"ccm","adata":"","cipher":"aes","ct":"HjqppnhebjD23yfg"}',
    hasUnconfirmedInputs: false }
```

**Comment by gehlm** [comment]
I just set up a 2-4 multi-sig all with Trezor cosigners. Getting the same error. Using https://bws.bitpay.com/bws/api

**Comment by matiu** [comment]
Thanks for the report, we are checking it now, with Copay 1.9.3 and public BWS.

**Comment by gehlm** [comment]
Also, When creating a payment, I get an error, "The payment was created but could not be completed. Please try again from the home screen." Other "copayers" can see the payment request, and get the "Only TXPs type SIMPLE are supported in TREZOR" when they try to accept.

Also, the trezor was asked to export keys. Shouldn't the originator have to sign the original payment proposal?

http://imgur.com/a/jZJW4

**Comment by matiu** [comment]
Please check version 1.9.4 at Chrome Store.

**Comment by chrisrico** [comment]
I'm not seeing 1.9.4, but with 1.9.3 a number of notes from previous transactions say ```<ECANNOTDECRYPT>```.

Also, I'm getting this error message while trying to sign a proposal: ```Could not add message to imported wallet without shared encrypting key```.

**Comment by matiu** [comment]
Version 1.9.4 will be there soon.

**Comment by gehlm** [comment]
1.9.4 Seems to have fixed the issue.

**Comment by chrisrico** [comment]
Updated to version 1.9.4.

I deleted the app and then reinstalled it to clear all data (for this Chrome profile).

When I reimported my Trezor copayer, I'm still seeing ```<ECANNOTDECRYPT>``` in the last 10 or so transactions' notes (nothing before that). When I try to send a transaction with this wallet I still get ```Could not add message to imported wallet without shared encrypting key```. Should I create a separate issue for this?

Using my other profile with the copayer already set up, it seems to work.

**Comment by matiu** [comment]
@gehlm thanks for the update

@chrisrico When you recreate a wallet in a BWS, the metadata of the transactions (like the notes) are lost. See https://github.com/bitpay/copay#copay-backups-and-recovery

Also, if you are using a new BWS, and importing the wallet from the TREZOR alone (ie, not from a 'Export Wallet' file) the shared key used to encrypt messages (so BWS cannot access them) is not available (because is derived from the initial shared wallet invitation). So it is not possible to create TX with messages in that case.  The message field should be disabled in that case (I have spawn a new ticket for that one: https://github.com/bitpay/copay/issues/3984).  The case you are using (new BWS, and importing only from mnemonics or only from public key (Trezor in this case) in multisig wallets is the most difficult one, and should only be used to recover the funds and move them to a new wallet.  Please try to create a TX without notes, if the problem persist, let us know we will try to solve https://github.com/bitpay/copay/issues/3984 ASAP.

**Comment by chrisrico** [comment]
This is getting off topic but is it possible to import the shared key from another copayer's wallet (even if it requires some code)?

**Comment by matiu** [comment]
@chrisrico definitely yes. You need to call `addWalletPrivateKey` in the corresponding `credential` item in the profile.  (each credential is for a wallet).

**Comment by chrisrico** [comment]
Ok, turns out the reason the old transactions weren't showing memos is because they were done on our BWS server, not Bitpay's. Last question, then let's close this issue. Is there a way to update the memo field of a transaction (on the BWS server) after the fact?

**Comment by matiu** [comment]
No, that is not supported ATM.

On Wed, Mar 9, 2016 at 9:25 PM, Chris Rico <notifications@github.com> wrote:

> Ok, turns out the reason the old transactions weren't showing memos is
> because they were done on our BWS server, not Bitpay's. Last question, then
> let's close this issue. Is there a way to update the memo field of a
> transaction (on the BWS server) after the fact?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3976#issuecomment-194586450>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!
