### ISSUE TITLE
Image is mirrored when using the QR code scanner on some android phones

### ISSUE THREAD

**Issue by cjr-roland** [bitpay/copay#3978]
Follow up of https://github.com/bitpay/copay/issues/3663

This is a known issues on some recent android phones (tested on Nexus 5X, Copay version 1.9.2) which can easily be fixed http://www.xda-developers.com/why-images-in-some-camera-apps-are-upside-down-on-the-nexus-5x/

It has been fixed on some other bitcoin wallet (mycelium, Blockchain)

**Comment by freeAgent85** [comment]
This has been bugging me since I got a Nexus 5X and it still hasn't been fixed as of v1.12.14.  It's very disorienting when attempting to scan a QR code as things are.

**Comment by matiu** [comment]
We should consider migrating to https://github.com/phonegap/phonegap-plugin-barcodescanner/commits/master

instead of 
https://github.com/JrontEnd/phonegap-plugin-barcodescanner/commits/master

and check on a Nexus 5x device.
