### ISSUE TITLE
Import Shared Wallet - Trezor

### ISSUE THREAD

**Issue by gehlm** [bitpay/copay#3986]
edit: Same as https://github.com/bitpay/copay/issues/3945

v1.9.4

Tried to import from 2 of 3 shared wallet from Trezor and get "share this invitation with your copayers" with animated progress. Loading screen does not go away, no invitation shown, and no way to delete wallet.

http://imgur.com/D1qd6xc

Clicking back, then Settings: Language, Unit, Alternative Currency, Bitcoin Network Fee Policy, About Copay, displays same loading screen.

**Comment by matiu** [comment]
Was the wallet completed in the BWS you are using before you tried to
import?

**Comment by gehlm** [comment]
No idea. Its currently set to: https://bws.bitpay.com/bws/api. The wallet was created and invitations sent on 1/10/2016 using the default settings. 

Yesterday, I purposely removed copay from chrome and reinstalled v1.9.4. To my surprise, when copay was relaunched all wallets were gone, so I restored from backups. Both file/text backups and Trezor (from a wallet created last week) were restored with no issue.  Only the older Trezor wallet (from 1/10/2016) is experiencing an issue.

**Comment by matiu** [comment]
Thanks for the detailed information.

If the wallet was not completed, (ie no all the copayers had joined) it is
not possible to recover it from TREZOR alone, since the 'wallet invitation
code' (the secret information between copayers that is unknown to BWS) is
not available. It should be better explained in Copay (I had spawned the
issue https://github.com/bitpay/copay/issues/3987).  Incomplete wallet have
not addresses and cannot have coins on them.



On Thu, Mar 10, 2016 at 7:34 AM, gehlm <notifications@github.com> wrote:

> No idea. Its currently set to: https://bws.bitpay.com/bws/api. The wallet
> was created and invitations sent on 1/10/2016 using the default settings.
>
> Yesterday, I purposely removed copay from chrome and reinstalled v1.9.4.
> To my surprise, when copay was relaunched all wallets were gone, so I
> restored from backups. Both file/text backups and Trezor (from a wallet
> created last week) were restored with no issue. Only the older Trezor
> wallet (from 1/10/2016) is experiencing an issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3986#issuecomment-194783520>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by gehlm** [comment]
> Was the wallet completed in the BWS you are using before you tried to
> import?

Yes, one of the copayers was able to share the walletID. Can I use that to restore?

**Comment by matiu** [comment]
No sure what you mean. Please see mu previous answer. If the wallet was
incomplete, it is not possible to restore it.

**Comment by gehlm** [comment]
The wallet was fully set up and funds were sent to it. Then I removed the copay app from my machine before upgrading to copay v1.9.4. After upgrading the wallet was gone (data files were removed on uninstall). One of the cosigners still has their copy of the wallet and can see the correct balance and transactions. I cannot restore fully from the Trezor. It does restore the wallet name, however.

**Comment by matiu** [comment]
OK, thanks for the explanation.

Can we meet at https://gitter.im/bitpay/copay so we can better assist you? My user name is `ematiu`.

**Comment by isocolsky** [comment]
@matiu, @gehlm is this still an ongoing issue?

**Comment by gehlm** [comment]
Yes, still a problem. 

To recreate the problem, make a shared wallet ABC. Alice decides the wallet was a mistake and deletes it locally (no transactions were made with wallet ABC). Alice creates a new, shared wallet ADE and starts transacting with it. Alice's computer dies and she tries to restore her shared wallet ADE only to find that it restores wallet ABC.

Shared Wallet ABC (2 of 3)
Alice: Trezor #1
Bob: Random Seed
Carol: Random Seed

Shared Wallet ADE (2 of 3)
Alice: Trezor #1
Dave: Random Seed
Erin: Random Seed
