### ISSUE TITLE
Can't scroll down the share invitation window

### ISSUE THREAD

**Issue by bitcoinuser** [bitpay/copay#3989]
Hi, I started to create a shared wallet 2of2 on Copay.
So I wanted to delete it before the other copayer join it.
I tried to scroll down the share invitation window to delete it.

Result: For any reason, on my smartphone, Copay can't scroll down the window. My smartphone is a LG G2.

![screenshot_2016-03-10-12-19-41](https://cloud.githubusercontent.com/assets/1178856/13674204/622f2fec-e6bb-11e5-8e13-594ae516372e.png)

**Comment by JDonadio** [comment]
Thanks for report. I'm on it.

**Comment by bitcoinuser** [comment]
This was fixed on Copay 1.11.0. Thanks.
