### ISSUE TITLE
Unable to send funds to another addresses

### ISSUE THREAD

**Issue by umagon** [bitpay/copay#3991]
Hi, I have this problem... I am trying to send btc to another address, but I keep getting error messages and can't send at all.

First, I would receive something like "Transaction was created, but was not sent. Bad signatures".
When I did this, a message appeared in my home screen "Total Locked Balance: X.XX btc", and there was my transaction waiting to be sent.

Whenever I try to send the transaction, I get "Signatures rejected by server". I am getting same behaviour in Android.

Am I missing something?

**Comment by matiu** [comment]
Hi,

Do you have a singlesig or multisig wallet? Is the wallet old ? (ie created more that a year ago?)

Can you try delete the transaction proposal and start again?

**Comment by matiu** [comment]
PS: Do you have the backup (Mnemonic) ? If you need to send urgently, you can use Copay's recovery tool at: https://bitpay.github.io/copay-recovery/

**Comment by umagon** [comment]
I don't know whether I'm using a singlesig or multisig wallet. How can I find out? I have my wallet since december of 2015.

Deleting and creating again the transaction yields same results.

I downloaded 3 backups and deleted none of them. I'm in no hurry. I'd like to see it working, btw.

**Comment by umagon** [comment]
Bump?

**Comment by dabura667** [comment]
What version of Copay are you using?

If it's old, you could be generating high-S signatures. (I forgot when that fix went in effect on the network)

**Comment by matiu** [comment]
Can you try using the Copay recovery Tool to move funds to a new wallet?

http://bitpay.github.io/copay-recovery/

On Mon, Mar 14, 2016 at 9:01 PM, Dabura667 <notifications@github.com> wrote:

> What version of Copay are you using?
>
> If it's old, you could be generating high-S signatures. (I forgot when
> that fix went in effect on the network)
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/bitpay/copay/issues/3991#issuecomment-196576795
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by umagon** [comment]
I am now using the latest version, I updated a week ago.

I noticed that my wallet is singlesig. (found an indicator "(m-n)" which says 1-1)

I uploaded my backup to Copay recovery tool and input my password. It said I had 0 btc on it. What's going on...?

**Comment by umagon** [comment]
I would like to at least obtain my private key so I can move to another wallet. I couldn't even find that option.

**Comment by matiu** [comment]
Do you have the mnemonic for your wallet (the 12 back words)?

On Wed, Mar 16, 2016 at 5:20 PM, Brian Salamone <notifications@github.com>
wrote:

> I would like to at least obtain my private key so I can move to another
> wallet. I couldn't even find that option.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3991#issuecomment-197528995>
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by matiu** [comment]
You can import that mnemonic on any BIP44 wallet you check the balance.

On Thu, Mar 17, 2016 at 8:14 AM, Matias Alejo Garcia <ematiu@gmail.com>
wrote:

> Do you have the mnemonic for your wallet (the 12 back words)?
>
> On Wed, Mar 16, 2016 at 5:20 PM, Brian Salamone <notifications@github.com>
> wrote:
>
>> I would like to at least obtain my private key so I can move to another
>> wallet. I couldn't even find that option.
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/bitpay/copay/issues/3991#issuecomment-197528995>
>>
>
>
>
> --
> Matías Alejo Garcia
> @ematiu
> Roads? Where we're going, we don't need roads!
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by umagon** [comment]
I recently discovered that in the settings menu there is this option "Backup" at root level that I can't access. It says... "Wallet seed not available. You can still export it from Advanced > Export"

Seems like this "mnemonic" thing I need... Why can't I backup my wallet this way? Any ideas?

**Comment by matiu** [comment]
Your wallet is probably old (we didnt have mnemonics on the first versions)
or the mnemonics were deleted.

You can backup the wallet in Advanced > Export

**Comment by umagon** [comment]
But I don't know what to do with these backups. The recovery tool didn't help, it says I have 0 btc, and I can't import my backup to other wallets. Is there any other way to get my money out? Are there any other wallets that can import Copay's old backups?

**Comment by matiu** [comment]
Could you let us know one of the address of your wallet that has funds
On it? So we can investigate further?

**Comment by umagon** [comment]
374pTJCABDyFbWMTGXEYbzRmMSkfvwposL

**Comment by matiu** [comment]
OK, we were able to identify the wallet. it seems that the problem (with
the recovery tool) is that the address gap is set to 20, and it seems that
wallet as a bigger gap between addresses with activity. Let us work on a
fix, and we will get back to you.


On Mon, Mar 21, 2016 at 2:42 PM, Brian Salamone <notifications@github.com>
wrote:

> 374pTJCABDyFbWMTGXEYbzRmMSkfvwposL
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3991#issuecomment-199396930>
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by matiu** [comment]
OK, we have added a configurable address GAP to
https://bitpay.github.io/copay-recovery/

Could you try again, setting an address GAP of ~60?

thanks.

On Tue, Mar 22, 2016 at 10:14 AM, Matias Alejo Garcia <ematiu@gmail.com>
wrote:

> OK, we were able to identify the wallet. it seems that the problem (with
> the recovery tool) is that the address gap is set to 20, and it seems that
> wallet as a bigger gap between addresses with activity. Let us work on a
> fix, and we will get back to you.
>
>
> On Mon, Mar 21, 2016 at 2:42 PM, Brian Salamone <notifications@github.com>
> wrote:
>
>> 374pTJCABDyFbWMTGXEYbzRmMSkfvwposL
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/bitpay/copay/issues/3991#issuecomment-199396930>
>>
>
>
>
> --
> Matías Alejo Garcia
> @ematiu
> Roads? Where we're going, we don't need roads!
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by umagon** [comment]
Thank you for your efforts.

I tested the recovery with gaps of 60, 70 and 80 to no avail-- my balance appears as 0 btc in every case.

**Comment by matiu** [comment]
Could you please contact me at matias@bitpay.com so we can try to assist you privately?

thanks

**Comment by romancsandl** [comment]
@umagon could you resolve that issue? i seem to have the exact same problem

**Comment by umagon** [comment]
I contacted matiu privately and despite his efforts I never got this resolved. This is sad for me, I've been struggling with the fact I have no power over my BTC and I stopped getting response from matiu some months ago. I'm out of ideas.

**Comment by romancsandl** [comment]
this is quite interesting since this #4266 seems to be the same problem, which was also closed and then no response anymore...this is not cool

**Comment by dabura667** [comment]
@umagon if you want, I could continue investigating with you.

1. Download https://github.com/bip32JP/bip32JP.github.io/archive/master.zip
2. Unzip to a folder
3. open the html file in /english/copay_decrypt.html with your browser
4. Make sure your internet is working. (This will query the balances of all your addresses and show them to you)
5. Copy the JSON text of your wallet backup in the first entry (should look similar the text below)
```
{"iv":"resq3e0IOYEIlU7qNQKqDA==","v":1, ..... s7w0"}
```
6. Type 50 into the addresses box
7. Type in your backup's encryption password into the password box
8. Click decrypt button
9. It should show you a list of addresses, and which ones have a balance.
10. If you can't find the address, try a bigger number than 50, you will have to hit decrypt twice (there is a warning message) and wait longer (javascript is slow)

Then you will know the following:

1. Your address is definitely in your wallet
2. which index it is

Then all we have to do is create a transaction for sending your money to an address of your choosing.

Which should be easy to code up in a few hours.

But first, using the tool above, you can find if the address you are looking for is on your copay wallet.

Let me know if you get any errors.

the source is available here:
https://github.com/bip32JP/bip32JP.github.io/blob/master/english/copay_decrypt.html

**Comment by romancsandl** [comment]
@dabura667 i know that the coins are in the wallet and also which adress...the problem is still to get them out of there....when sending there are signatures wanted from the bws server...but there are no signatures sent within the process...so the issue looks to be on bws side not the client

**Comment by umagon** [comment]
@dabura667 I got no errors and I have the indexes. To this point I could get before, but transfering the funds to another wallet did never work.

**Comment by matiu** [comment]
Hi guys,

@dabura667 a little context for this error. 

We put a lot of effort to resolve it, but the xpriv key of the wallet simply does not match the xpub key in BWS and even the xpub key wallet export file. So the Bitcoin's on its addresses are not recoverable with that xpriv.

We investigated what could have cause it, and our best guest was that @umagon was using a custom, not official Android distribution. Because we were not able to reproduce this error by any means, and finally give up.

**Comment by umagon** [comment]
What could @romancsandl 's problem have in common with mine's? Maybe we can investigate further with this new lead.

**Comment by romancsandl** [comment]
at first i can tell you a difference...this phone was not rooted and did not have a custom version running

**Comment by matiu** [comment]
Roman I suggest you open a new ticket and explain in detail the problem.

On Jan 12, 2017 8:29 AM, "Roman Csandl" <notifications@github.com> wrote:

at first i can tell you a difference...this phone was not rooted and did
not have a custom version running

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/bitpay/copay/issues/3991#issuecomment-272140480>, or mute
the thread

**Comment by romancsandl** [comment]
#5407
already did that

**Comment by umagon** [comment]
I have read in another issue that someone got a bad signatures error working by installing an old version.

I have my wallet since August 2015, and Copay was at v1.1.2. I installed that version and when I wanted to use it, it said...
![image](https://user-images.githubusercontent.com/4467191/30145621-dad23c4a-9368-11e7-8820-e08b2b343da6.png)
Is there any way I can make this service work for this copay version? Maybe use other service provider?
