### ISSUE TITLE
Feedback: "destination wallet needs backup" message should appear in the previous window.

### ISSUE THREAD

**Issue by bitcoinuser** [bitpay/copay#3992]
Hi, I think the message "destination wallet needs backup": shouldn't appear in this window.

![screenshot_2016-03-11-14-21-17](https://cloud.githubusercontent.com/assets/1178856/13709879/f153c654-e794-11e5-909b-c86f924be8db.png)

Should appear in this previous windows:

![screenshot_2016-03-11-14-20-34](https://cloud.githubusercontent.com/assets/1178856/13709894/08c411f4-e795-11e5-9ed6-f4bef4bdc455.png)

**Comment by isocolsky** [comment]
It's a protection so people don't send coins to a wallet without first having a backup. Do you disagree with the feature or just with the way it is done in the UI?

**Comment by JDonadio** [comment]
if I remember correctly @bitcoinuser has been suggested this feature. I'll work with this idea, I agree with this.

**Comment by bitcoinuser** [comment]
@isocolsky I agree with the idea. I disagree with the UI. The message should appear in the previous window, and If no backup, the user couldn't click and go to the next window.

**Comment by bitcoinuser** [comment]
This was fixed on Copay 1.11.0. Thanks
