### ISSUE TITLE
bitcoin URI: "Open in Wallet" not working (in Desktop versions)

### ISSUE THREAD

**Issue by mrabinovsky** [bitpay/copay#3994]
I have copay 1.9.4 installed (and I have uninstalled it and reinstalled it) on a Windows 10 Pro x64 computer but whenever I click the "Open in Wallet" on a bitpay invoice, copay does nothing. If I do it under firefox I get an option to select which program to open the link with. There were none listed by default so I selected one from "Choose an application" and selected copay. It opens copay now but doesn't give me an option to make a payment. Edge and IE11 tell me I need a new application to open this kind of link, and the only option is to go to the app store to find one.

**Comment by bumi** [comment]
I was trying to debug this and to add the functionality that copay registers a bitcoin: protocol handler. 
There seem to be some protocol handlers for the cordova apps (though I have not checked if the plugins are there). I could not find any code for the desktop apps. 

Sadly I could not find any solution on how to do that with the used [NW.js](http://nwjs.io/).
[Electron](http://electron.atom.io/) seems to have better support for Desktop apps. Are there any plans to switch to electron? ...another issue I guess :)

**Comment by matiu** [comment]
Yes, Copay does not support protocol handlers on its desktop app. Related to https://github.com/nwjs/nw.js/issues/951
