### ISSUE TITLE
BTC DEPOSIT

### ISSUE THREAD

**Issue by iso1717** [bitpay/copay#3996]
Hi, I have a problem with an Deposit.. a few days ago they sent me 0.059 btc, and I still have not received anything ... this is the hash 71f6fdb3c0d5db618b8eb4c4178ce6fbb9441d96921bcf12eb433b9fff34b43b ... here is the link https://www.blocktrail.com/BTC/address/1LTBKfU6VpC3s6tCndRcgaU187eqjtsKZN/transactions ...

WALLET -  V 1.9.4

If you need anything else, please let me know  

Regards

**Comment by isocolsky** [comment]
Actually, the tx hash you are providing already has 260 confirmations. Also, looks like the 0.059 btc were already spent by this tx: https://insight.bitpay.com/tx/a76a90590846f76de7405bab3b9a0da9ea1cd7f978692df2ca72007c518a496d

**Comment by iso1717** [comment]
Hi, yes , but the BTC never reached my wallet

**Comment by iso1717** [comment]
Hi, yes , but the BTC never reached my wallet . ... I have the screenshot of my wallet, and there is nothing yet .

**Comment by iso1717** [comment]
and if you can see in the Summary, it says that  I have 0 btc, and its not true .. something strange is happening .

**Comment by matiu** [comment]
`1LTBKfU6VpC3s6tCndRcgaU187eqjtsKZN` is not an address managed by Copay.

**Comment by isocolsky** [comment]
Could you please go to your wallet -> Preferences -> Advanced -> Wallet Information and verify the address 1LTBKfU6VpC3s6tCndRcgaU187eqjtsKZN belongs to your wallet?

**Comment by iso1717** [comment]
Hola Matías,.

Tengo mucha pena,  yo tengo 5 wallet  de diferentes compañías,..  Pensé que
los había enviado a Copay pero me lo enviaron a otra wallet y me estoy
dando cuenta gracias a Tu mensaje.

Gracias por solucionar mi torpeza.

Saludos

**Comment by matiu** [comment]
No hay problemas. Saludos.
