### ISSUE TITLE
Unable to release payment from logged in account

### ISSUE THREAD

**Issue by SergeyDNazarov** [bitpay/copay#3998]
Hi Copay Team, thanks for all your hard work. 

There are two a quick problems I was hoping you could help me out with. 

Firstly, my account was sent a proposal and I can't seem to sign off on it because when I click Accept it says "Server response could not be verified", is there any way you can fix this on your end?

Secondly, I have about one Bitcoin in that same wallet and the send screen says I have an "available balance" of 0 bits and that all of it is "locked by pending payments", how do I transfer the bitcoin I do have already in the wallet to another address? This is a wallet I imported from before 0.9, but I am logged in to the correct wallet because I can see proposals from others.

Thanks,
Sergey

**Comment by dabura667** [comment]
You are using Linux version on Ubuntu / Kubuntu?

Please use the Chrome/Chromium add-on version and you can approve the proposal.

When a proposal is active, the funds referenced in the transaction data are locked and cannot be touched. This is normal.

**Comment by matiu** [comment]
Given that 0.9 is a very old version , i suggest you use the Copay Recovery
Tool and move the funds to a new Copay wallet.

**Comment by SergeyDNazarov** [comment]
Thanks for the prompt response, I do appreciate it. 

I tried the "Import Legacy Wallet" tool to pull from the cloud and it gave me a "Failed to import wallets" error even thought it did seem to recognize my account and started to pull in data. 

Is the Copay Recovery Tool something other than what I just used, if so, how do I get to it? 

I do have the .JSON and .AES backup files from these old versions if that is helpful.

**Comment by SergeyDNazarov** [comment]
Just an update; I tried the chrome extension and was able to setup the wallets using the same "Import Legacy Wallet" feature, but after it updated my wallets it still gives me the same error of ""Server response could not be verified".

**Comment by matiu** [comment]
https://github.com/bitpay/copay-recovery

**Comment by SergeyDNazarov** [comment]
The recovery tool didn't work so we canceled all the copay transactions and had my wallet send them in the standard app and then the other person sign-off, they weren't having server side issues so it worked. Just thought I would let you know in case it comes up again, thanks for your help.
