### ISSUE TITLE
Hi, ASAP

### ISSUE THREAD

**Issue by nolegalname** [bitpay/copay#4000]
Need your assistance want to send bitcoin but getting this message.
Could not send pyment Cannot create TX proposal during backoff time.

The payment was created but could not be signed. Please try again from home screen. Bad signatures.  
Running wallet on win 7.
[Doc15032016.pdf](https://github.com/bitpay/copay/files/174433/Doc15032016.pdf)

**Comment by cmgustavo** [comment]
Hi @nolegalname , I think that you 're using an old version. Could you upgrade Copay to v1.9.4 and try again? This is the latest installer for Windows: https://github.com/bitpay/copay/releases/download/v1.9.4/Copay-win.exe

**Comment by nolegalname** [comment]
It is same on new version geting this message:
COULD NOT SEND PAYMENT LOCKTIME IN EFFECT. Please waith to create a new spend proposal

**Comment by cmgustavo** [comment]
Can you see the list of `UNSENT TRANSACTIONS` in the `Activity` screen? Did you try to sign it manually?

Thanks

**Comment by nolegalname** [comment]
Yes, and cancel all transaction because is not sending coins from wallet

**Comment by nolegalname** [comment]
was try now and now is working

**Comment by nolegalname** [comment]
what was problem do not know,  first time get something like that on this wallet

**Comment by isocolsky** [comment]
There is a protection in place to avoid one copayer attacking other copayers by making funds impossible to withdraw. If a given nb of consecutive proposals are rejected by other copayers in the wallet, a lock time is applied and the offending copayer needs to wait 24hs before creating a new tx. This is most likely what was happening to you.

**Comment by isocolsky** [comment]
Glad to know it its working ok now :smile:
