### ISSUE TITLE
Total Locked Balance doesn't seem to match Payment Proposal

### ISSUE THREAD

**Issue by Jacobbubble** [bitpay/copay#4001]
![screenshot copay](https://cloud.githubusercontent.com/assets/6015223/13791307/ab68348c-eaa9-11e5-8c2d-f126b4b37fc0.png)
Total Locked Balance is ƀ1,998,621 for a payment proposal for ƀ240,958.

Why is the locked balance significantly higher than the proposal amount and far from the total balance?

**Comment by dan-da** [comment]
because it locks the inputs, which usually do not exactly match the output amounts.

It's as if you are spending a $20 on a $3 coffee.   The $20 gets locked until the purchase is finalized.

**Comment by isocolsky** [comment]
Yes, what @dan-da said is exactly true. There is an [improvement on the algorithm used to select inputs](https://github.com/bitpay/bitcore-wallet-service/pull/477) so as to minimize the amount locked by a spending proposal (although the problem can not be completely solved).

**Comment by dan-da** [comment]
This seems to be a common question.   Perhaps the locked funds message could be made more understandable for users by adding a "?" tooltip that goes into a bit more detail with eg the $20 for a $3 coffee analogy.

**Comment by Jacobbubble** [comment]
@dan-da At a minimum there should probably some sort of explanation.

If proposals were historically dependant, this problem could be fixed by basing proposals off of current proposals.

I understand it would be much more complicated to do this, but I think this would be the optimal behavior as you could have amounts correctly locked instead of entire inputs per.

**Comment by isocolsky** [comment]
There is no way to sign a tx using your private key unless all inputs have been specified. If proposals were based on other proposals, this would not make things faster/easier as you would need to sign them sequentially. There have been talks of decoupling proposal acceptance from tx creation so multiple proposals can be accepted before one or more physical txs exists and can be signed. This sounds like an improvement but it still requires several roundtrips to create actual txs.

**Comment by matiu** [comment]
Adding to the new FAQ.
