### ISSUE TITLE
Android N errors

### ISSUE THREAD

**Issue by XBTdev** [bitpay/copay#4003]
See errors when running on Android N.

Also note that on Nexus 5x the camera is inverted. This was also an issue with Android M. Lots of old camera apps actually have this issue with Nexus 5x phones.

![screenshot_20160316-035732](https://cloud.githubusercontent.com/assets/3032137/13811071/8e667a9c-eb30-11e5-814e-49c28f802a5e.png)

**Comment by XBTdev** [comment]
Android N includes namespace changes to prevent loading of non-public APIs. If you use the NDK, you should only be using public APIs from the Android platform. Using non-public APIs in the next official release of Android can cause your app to crash.
In order to alert you to use of non-public APIs, apps running on an Android N device generate an error in logcat output when an app calls a non-public API. This error is also displayed on the device screen as a message to help raise awareness of this situation. You should review your app code to remove use of non-public platform APIs and thoroughly test your apps using a preview device or emulator.
If your app depends on platform libraries, see the NDK documentation for typical fixes for replacing common private APIs with public API equivalents. You may also be linking to platform libraries without realizing it, especially if your app uses a library that is part of the platform (such as libpng), but is not part of the NDK. In that case, ensure that your APK contains all the .so files you intended to link against.
Caution: Some third-party libraries may link to non-public APIs. If your app uses these libraries, your app may crash when running on the next official release of Android.
Apps should not depend on or use native libraries that are not included in the NDK, because they may change, or be removed from one Android release to another. The switch from OpenSSL to BoringSSL is an example of such a change. Also, different devices may offer different levels of compatibility, because there are no compatibility requirements for platform libraries not included in the NDK. If you must access non-NDK libraries on older devices, make the loading dependent on the Android API level.

**Comment by matiu** [comment]
I think the library related problems will be fixed on Ionic/Cordova itself.

Regarding the Camera problem on nexus devices, it reported here: https://github.com/bitpay/copay/issues/3978
