### ISSUE TITLE
Decimal places not shown for unit "bits"

### ISSUE THREAD

**Issue by Jacobbubble** [bitpay/copay#4004]
Copay isn't showing me the exact amount of bits received or sent.

Example: 
Transaction: Received ƀ3,366,013.39
https://insight.bitpay.com/tx/14ef5e80c1bcc5e256e497e8b9a55cbeccd0d7d8e49f01ace623247737c7bf7b
Copay shows: 
![screenshot 2016-03-16 at 19 47 41](https://cloud.githubusercontent.com/assets/6015223/13834904/fd105844-ebaf-11e5-8ff8-094cc2f78f77.png)

This is true on a per-transaction basis and the total balance.

**Comment by matiu** [comment]
Related / Dup: https://github.com/bitpay/copay/issues/3125
