### ISSUE TITLE
Simple crypt and decrypt function in Copay

### ISSUE THREAD

**Issue by avibrazil** [bitpay/copay#4005]
Since every Bitcoin user gets a PKI for free, I'd like to suggest that next Copay versions may be able to simply encrypt and decrypt text. This is unrelated to Bitcoin transactions but may be useful for any user since all of us already have public and private keys.

I'd like to be able to use someone's public address to encrypt a message to be sent by e-mail or SMS. Or even use my public key to encrypt a message for myself.

**Comment by martindale** [comment]
Copay would make an ideal identity store, in addition to storing funds.  Encrypting and decrypting messages with stored keys would be the perfect example for an application around identity.

**Comment by avibrazil** [comment]
Later I learned that Bitcoin keys are not very good for encryption, they are better optimized for signing only. I don't know details about it or how elliptic curve encryption works. Its just an idea, let the specialists reply about it.

**Comment by matiu** [comment]
This seems to be out of the scope of current Copay objectives.
