### ISSUE TITLE
How to run on Raspberry Pi

### ISSUE THREAD

**Issue by tapansino91** [bitpay/copay#4006]
Hi,
This is a reopen of the thread in #3961, in which I asked if Copay has Raspberry Pi support. 

Continuing the thread, it sounds like it is possible to run Copay on a Raspberry Pi, but I can't seem to figure out how.

I downloaded the Linux binary for v1.9.4 and attempted to run it on my Pi (gen 1), but it fails with:
`./Copay: Exec format error. Binary file not executable.`

I'm guessing this is because this is compiled for x86 architecture, not ARM?

So going a different route, I then tried building from scratch. I downloaded node, ran through the local build process with bower, grunt, etc, and I think it all worked ok (first time doing this), because I was able to access the app in my browser afterward.

The only trouble is, I don't want to have to run this through my browser, what I want is to run the app natively (or whatever the correct term is). Basically, I don't want to have to launch the node process each time via terminal and _then_ have to sign in to my browser.

So my question is: how can I run Copay natively on the Raspberry Pi? Is there a different binary already built that I can download? Or is there something I can do to the build I have already done to package it up as a standalone application?

**Comment by cmgustavo** [comment]
Hi, I 'm glad to know that Copay can running in a Raspberry Pi with NodeJs, but I think that the binary won't work until node-webkit supports ARM. It only works on win/osx/linux, all of them for x86/x86_64. The good news is that they are planning to support it. Check it at https://github.com/nwjs/nw.js/issues/193 and https://github.com/nwjs/nw.js/issues/1151 

JFYI, there is a command line with grunt that generate the bundles for Linux/OSX: `grunt desktop`.

But if you only need to build the binaries for Linux(only 64), just do `grunt` with the follow params: 

```
grunt prod nodewebkit copy:linux compress:linux
```

The ZIP file will be created at: `./webkitbuilds/Copay-linux.zip`

Thanks for your concern.

**Comment by tapansino91** [comment]
Excellent, thank you very much for the information.

Just to clarify: if I run that `grunt desktop` on my Raspberry Pi right now today, it will fail, because I don't have nw installed, and nw doesn't support ARM yet. Is this correct? But, once nw releases an ARM build, I should be able to download/install it, and do the grunt build, and that might work, yes?

If this is all true, then I'll watch for the ARM build of nw and try after that, and this ticket can be closed.

**Comment by jalbam** [comment]
Hello,

I have just created a repository with the node-webkit binary port that runs on Raspbian, tested and working on Raspberry Pi 1 and Raspberry Pi 3 so it is ARMv6 and ARMv7 compatible.

Here you can check it: https://github.com/jalbam/nwjs_rpi
