### ISSUE TITLE
BIP73 URI in the bitcoin address field is not supported

### ISSUE THREAD

**Issue by cjr-roland** [bitpay/copay#4008]
On the latest 1.9.4 release, it is not possible to copy paste the BIP73 URI in the bitcoin address field to initiate a transaction with the Payment Protocol (still possible with BIP72 and 72b URI)
Issue can be reproduced on all platforms, see below a screenshot of the error.

![copay_issue](https://cloud.githubusercontent.com/assets/12460881/13880182/72658c06-ed1b-11e5-8eb1-d85cae8beb94.png)

Probably something wrong with the parsing

**Comment by matiu** [comment]
This can be tested on:

https://bitpay.com/demos

and copying the URL (something like: https://bitpay.com/invoice?id=Cag99SHcofsrmXiKVfboin)
to the 'send' field (it should work but it does not).

Copying this:
bitcoin:14j1sPxQujZ4oN8YJmXk6dELkzPtNtRsYn?amount=0.010000&r=https%3A%2F%2Fbitpay.com%2Fi%2FCag99SHcofsrmXiKVfboin
works.

**Comment by JDonadio** [comment]
Confirmed, this is an error from Bitpay.com end.

> curl -H 'Accept:application/bitcoin-paymentrequest'  https://bitpay.com/invoice?id=FGebVzmbTrMVbUXFLLiDaz

Should return a payment protocol but it doesn't, but return the complete HTML. It's already reported as well. Thanks @cjr-roland!

**Comment by braydonf** [comment]
This should work from Copay with the URL in the form `https://bitpay.com/i/Cag99SHcofsrmXiKVfboin`
