### ISSUE TITLE
BUG: QR code reading flip-flopped image on Nexus 5x

### ISSUE THREAD

**Issue by taw00** [bitpay/copay#4009]
Please read this. You are doing it wrong. :)
http://www.androidcentral.com/google-reveals-why-some-photos-taken-nexus-5x-are-upside-down

Summary: The spec says that the image chip can be in one of two ways. But almost all phones engineer it one particular way. App writers (such as you guys) assume that is The Way it is supposed to work. Alas, Nexus 5x -- a very popular smartphone -- has nicely uncovered all the apps that made this assumption and flip-flop the image.

It makes scanning QR codes challenging. Don't feel terrible. You are not the only app for which I am filing a very similar bug.

**Comment by XBTdev** [comment]
I mentioned the issue in #4003, but it's good to have a separate issue for this as that issue is focused on the Android N errors

**Comment by matiu** [comment]
dup: https://github.com/bitpay/copay/issues/3978
