### ISSUE TITLE
"Set Copay As Default Wallet" on iPhone?

### ISSUE THREAD

**Issue by KeyJockey** [bitpay/copay#4011]
Not sure if this is possible to do *in* the wallet code somehow, but there appears to be a problem on iPhone bitcoin wallets where only the most recently installed wallet is always determined to be the "default" wallet... as for example when clicking the Pay link for bitcoin on the FoldApp for Starbucks coffee.

On my phone, this opens another wallet that I don't use much rather than my favorite, Copay.  When this happens I have to manually close the other wallet, go back to Fold, copy the QR to clipboard, manually launch Copay, then paste the payment code in Copay's send tab.  Annoying.

The recommended "solution" for this problem from the FoldApp FAQ is to only keep ONE bitcoin wallet on the phone, but that's kind of not the best solution is it?  LOL

If Copay could implement some kind of feature for iPhone that would "Set Copay As Default Bitcoin Wallet App On This Phone" that would be very cool :)

**Comment by ajp8164** [comment]
This is a limitation of iOS.  There is nothing we can do with Copay that can fix this, as much as we'd like to.

--
Andy Phillipson
Director of Engineering Services, BitPay, Inc.
844A CCA5 F277 30C0 E86F  9799 0CEE 502F 2484 0854

**Comment by KeyJockey** [comment]
Ahh, bummer.  OK well thanks for replying anyway.

**Comment by martindale** [comment]
I suspect Apple will be forced to add this feature eventually, so I'm voicing a strong +1 from me for this once they do.  It's been terribly difficult to demonstrate to iPhone users a positive payment experience in general, let alone without this feature.

**Comment by dabura667** [comment]
> this opens another wallet that I don't use much rather than my favorite

Delete that app, then reinstall it.

The way URI registering happens on iOS is an app can register it, but if multiple apps register the same URI, it defaults to the oldest app on the device.

Delete all apps in the queue until Copay is the default, then reinstall all the other apps and it will stay Copay until you delete Copay (or some bug in iOS causes it to jump for some reason, I had this happen once when I updated an app).

I believe Copay does register the bitcoin URI, but there's just no way for the user, or the app, to make itself the actual app for that URI scheme.

**Comment by matiu** [comment]
> I believe Copay does register the bitcoin URI, but there's just no way for the user, or the app, to make itself the actual app for that URI scheme.

Right.
