### ISSUE TITLE
Bug freezes UI with waiting ms wallet and "About Copay" view

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#4013]
Recreate this issue doing the following:

1. Create a new shared wallet with entering only the wallet name and nickname (that's all I entered)
2. Ensure the "waiting wallet" is selected
3. Open sidebar and click "Settings"
4. Click "About Copay"

The view presented is "Global preferences" (which is incorrect) and the UI is frozen.  You have to close and reopen the app.  This bug is repeatable.

**Comment by gabrielbazan7** [comment]
#4068

**Comment by matiu** [comment]
fixes in Copay 2.0
