### ISSUE TITLE
blocked bitcoins

### ISSUE THREAD

**Issue by joepain** [bitpay/copay#4017]
i send bitcoins on my copay walled, wy they are blocked ?? i have no idea why. please help.

**Comment by matiu** [comment]
Could you share a screenshot?

**Comment by joepain** [comment]
![2016-03-22 23 44 29](https://cloud.githubusercontent.com/assets/16671089/13970482/46cf2d42-f089-11e5-85eb-b4e0c95dc7fe.png)

**Comment by joepain** [comment]
![2016-03-22 23 45 00](https://cloud.githubusercontent.com/assets/16671089/13970512/7a6e7932-f089-11e5-9ef0-1d9977ad0222.png)

**Comment by joepain** [comment]
Adresse 1M78tPyjK4rd9rW1BMoqySxGhD2C9VWtcj 
Copied!
Zusammenfassung bestätigt
Insgesamt empfangen
0.2472 BTC
Insgesamt gesendet
0 BTC
Schlussbilanz
0.2472 BTC
Anzahl Transaktionen
1
Transaktionen
 8bacf203d95912fbd0971d6f62d5405cf134438b56ce6a3688e0c2c729b61e2f 
Copied!
gefunden Mar 22, 2016 3:29:50 PM
9.03722818 BTC
3QyUSB4eRYePHcvpS6k6YDMBUDGXRSSMPc
0.2472 BTC (U)
1M78tPyjK4rd9rW1BMoqySxGhD2C9VWtcj
8.78952818 BTC (S)
3QyUSB4eRYePHcvpS6k6YDMBUDGXRSSMPc
GEBÜHR: 0.0005 BTC 49 BESTÄTIGUNGEN 9.03672818 BTC
[ Deutsch · English · Spanish · Japanese ]   [ verify message · broadcast transaction ]

**Comment by joepain** [comment]
Adresse 0.1236 BTC
Adresse 1HBNzj16aHq9wtoR74wtTWF29DJgJqjP38 
Copied!
Zusammenfassung bestätigt
Insgesamt empfangen
0.1236 BTC
Insgesamt gesendet
0 BTC
Schlussbilanz
0.1236 BTC
Anzahl Transaktionen
1
Transaktionen
 05b90ac32793b46482f6600cedb2981bc3e66d062d4df111f676e0e81a7abaf9 
Copied!
gefunden Mar 22, 2016 3:29:50 PM
9.16132818 BTC
3QyUSB4eRYePHcvpS6k6YDMBUDGXRSSMPc
0.1236 BTC (U)
1HBNzj16aHq9wtoR74wtTWF29DJgJqjP38
9.03722818 BTC (S)
3QyUSB4eRYePHcvpS6k6YDMBUDGXRSSMPc

**Comment by matiu** [comment]
Could you try deleting the payment and trying again?

**Comment by joepain** [comment]
yes for shure, tryed it 10 times.
i have a i phone 5. is it posiible that they block the bitcoins becouse its all appl aps, and i have a app where i have to pay for every month. and its running out today and i have not enough mony at i tunes to pay at the moment. when i buy money for i tunes and pay for this app that than they not longer block my bitcoins ??

**Comment by joepain** [comment]
i think its possible that apple apps work together and that is the reason wy they block my bitcoins, there stands its blockt about unpaid things.

**Comment by matiu** [comment]
> i have a i phone 5. is it posiible that they block the bitcoins becouse its all appl aps, and i have a app where i have to pay for every month. and its running out today and i have not enough mony at i tunes to pay at the moment. when i buy money for i tunes and pay for this app that than they not longer block my bitcoins ??

no, that is not possible.


Could  you try installing Copay on a different device (like a desktop computer), importing you wallet there and sending the funds from there?

Sorry for the inconveniences you are having.

**Comment by joepain** [comment]
yes, i also have it on laptop desktop, also dont work.

**Comment by joepain** [comment]
i dont know what for outstanding paymends they mean. what have i pay for ?

**Comment by matiu** [comment]
Could you please write me to matias@bitpay.com so we can follow up this issue in private?

thanks.

**Comment by matiu** [comment]
This was resolved offline, by installing a fix in BWS (https://github.com/bitpay/bitcore-wallet-service/pull/484).


Thanks for your patience.

**Comment by b51b51** [comment]
Hello matiu! i have the same problem and tried what you did. is it possible to fix it privatly? Kind regards
