### ISSUE TITLE
hardware wallet fail

### ISSUE THREAD

**Issue by nybe** [bitpay/copay#4019]
I've been using copay to manage my tremor and today I went to use it and got the following error (see attachment)
![screen shot 2016-03-22 at 6 03 09 pm](https://cloud.githubusercontent.com/assets/4483720/13973894/985fb412-f064-11e5-9f68-db2687ec909c.png)

PLEASE HELP

**Comment by nybe** [comment]
trezor not tremor

**Comment by matiu** [comment]
That error seems to be coming directly from TREZOR. Could you try unplug
and plug the device and try again?

On Tue, Mar 22, 2016 at 11:31 PM, nybe <notifications@github.com> wrote:

> trezor not tremor
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/4019#issuecomment-200136626>
>



-- 
BitPay.com

**Comment by nybe** [comment]
Nope. It seems copay needs an update to work again with trezor. It's failing to connect to my trezor whereas chrome connects fine. 

//Bob

**Comment by matiu** [comment]
Thanks for the update. Could you explain more " It's failing to connect to
my trezor"?   What message are you receiving? Thanks.

On Wed, Mar 23, 2016 at 10:47 AM, nybe <notifications@github.com> wrote:

> Nope. It seems copay needs an update to work again with trezor. It's
> failing to connect to my trezor whereas chrome connects fine.
>
> //Bob
>
> > On Mar 23, 2016, at 4:51 AM, Matias Alejo Garcia <
> notifications@github.com> wrote:
> >
> > That error seems to be coming directly from TREZOR. Could you try unplug
> > and plug the device and try again?
> >
> > On Tue, Mar 22, 2016 at 11:31 PM, nybe <notifications@github.com> wrote:
> >
> > > trezor not tremor
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/bitpay/copay/issues/4019#issuecomment-200136626>
> > >
> >
> >
> >
> > --
> > BitPay.com
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/4019#issuecomment-200350519>
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by nybe** [comment]
"Hardware Wallet Error: Wrong acquire input"



 

//Bob

**Comment by matiu** [comment]
Thanks. We just installed a minor patch at BWS in order to prevent creation
of proposals with very small change output. Would you mind to try one more
time?  thanks.

On Wed, Mar 23, 2016 at 11:02 AM, nybe <notifications@github.com> wrote:

> "Hardware Wallet Error: Wrong acquire input"
>
>
>
>
>
> //Bob
>
> > On Mar 23, 2016, at 6:50 AM, Matias Alejo Garcia <
> notifications@github.com> wrote:
> >
> > Thanks for the update. Could you explain more " It's failing to connect
> to
> > my trezor"? What message are you receiving? Thanks.
> >
> > On Wed, Mar 23, 2016 at 10:47 AM, nybe <notifications@github.com> wrote:
> >
> > > Nope. It seems copay needs an update to work again with trezor. It's
> > > failing to connect to my trezor whereas chrome connects fine.
> > >
> > > //Bob
> > >
> > > > On Mar 23, 2016, at 4:51 AM, Matias Alejo Garcia <
> > > notifications@github.com> wrote:
> > > >
> > > > That error seems to be coming directly from TREZOR. Could you try
> unplug
> > > > and plug the device and try again?
> > > >
> > > > On Tue, Mar 22, 2016 at 11:31 PM, nybe <notifications@github.com>
> wrote:
> > > >
> > > > > trezor not tremor
> > > > >
> > > > > —
> > > > > You are receiving this because you are subscribed to this thread.
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> https://github.com/bitpay/copay/issues/4019#issuecomment-200136626>
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > BitPay.com
> > > > —
> > > > You are receiving this because you authored the thread.
> > > > Reply to this email directly or view it on GitHub
> > > >
> > >
> > > —
> > > You are receiving this because you commented.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/bitpay/copay/issues/4019#issuecomment-200350519>
> > >
> >
> >
> >
> > --
> > Matías Alejo Garcia
> > @ematiu
> > Roads? Where we're going, we don't need roads!
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/4019#issuecomment-200357502>
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by matiu** [comment]
(We believe this could be related to https://github.com/bitpay/copay/issues/4017#issuecomment-200354868  with was fixed recently)

**Comment by nybe** [comment]
I got very nervous and removed all ones from tremor/copay and deleted all wallets. 

I have since wiped the tremor and am using it with chrome only.

I just now tried to setup a new copay/trezor wallet and this is what I get:

**Comment by matiu** [comment]
Sorry, the screenshot is not showing. Could you send it again?

Contact me at matias@bitpay.com if you prefer to follow up this one privately.

**Comment by nybe** [comment]
//Bob

**Comment by nybe** [comment]
What was the solution?

**Comment by matiu** [comment]
The code is here:
https://github.com/bitpay/bitcore-wallet-service/pull/484/files



thanks.

On Wed, Mar 23, 2016 at 1:01 PM, nybe <notifications@github.com> wrote:

> What was the solution?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/4019#issuecomment-200411731>
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by nybe** [comment]
so copay will work with trezor again?

**Comment by matiu** [comment]
Copay is working with Trezor in our tests. It seems there was a problem
that BWS was generating a TX will very small change output, that were not
handling correctly by Trezor. This only was happening in certain input /
output combinations.

Importing you Trezor wallet in Copay should be very simple, if you want to
give it a try.

thanks.


On Wed, Mar 23, 2016 at 3:15 PM, nybe <notifications@github.com> wrote:

> so copay will work with trezor again?
>
>
> On Mar 23, 2016, at 11:13 AM, Matias Alejo Garcia <
> notifications@github.com> wrote:
>
> > The code is here:
> > https://github.com/bitpay/bitcore-wallet-service/pull/484/files
> >
> >
> >
> > thanks.
> >
> > On Wed, Mar 23, 2016 at 1:01 PM, nybe <notifications@github.com> wrote:
> >
> > > What was the solution?
> > >
> > > —
> > > You are receiving this because you modified the open/close state.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/bitpay/copay/issues/4019#issuecomment-200411731>
> > >
> >
> >
> >
> > --
> > Matías Alejo Garcia
> > @ematiu
> > Roads? Where we're going, we don't need roads!
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> >
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/4019#issuecomment-200473606>
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by nybe** [comment]
ok I shall try again when I get home this evening and let you know… 

thanks

//Bob

**Comment by nybe** [comment]
Looks like I go it back up and running. 

Thanks for the help!

//Bob

**Comment by matiu** [comment]
Thanks a lot for the update. And sorry for the inconveniences.
