### ISSUE TITLE
Cannot select and copy seed text in Chrome app

### ISSUE THREAD

**Issue by Inversion-des** [bitpay/copay#4023]
It is on the backup step titled "Write your wallet seed"

**Comment by dabura667** [comment]
Why would you want to copy your seed?

**Comment by Inversion-des** [comment]
I do not trust a piece of paper, I prefer digital encrypted storage that can be backed up to the cloud. So I just need to copy-paste.

**Comment by matiu** [comment]
For security (in order to prevent malicious app to grab the seed) `copy` is disabled for wallet seeds. You will need to copy it by typing it, if you want to store it online.
