### ISSUE TITLE
Mobile Encrypted Backup Format (Copay 1.0.1)

### ISSUE THREAD

**Issue by lukem512** [bitpay/copay#4024]
Hello,

I'm trying to decrypt a backup from an old Copay wallet, made on a mobile device, and the issue I am having is that, whilst the decrypt works, the master private key is still encrypted (it's shown as "xPrivKeyEncrypted"). Can you advise me on what key would have been used to encrypt this and how I can go about decrypting it?

The format looks similar to that of the log itself (i.e. using SJCL): 

`"xPrivKeyEncrypted":"{\"iv\":\"vwO ... XoNagJA==\",\"v\":1,\"iter\":10000,\"ks\":128,\"ts\":64,\"mode\":\"ccm\",\"adata\":\"\",\"cipher\":\"aes\",\"salt\":\"N ... WxM=\",\"ct\":\"KA9OAV+jc6Flh9 ... zqlN007VoScmSxfQsF2+zUIC5d+IwJzn9Kj/heCq65odFdXg=\"}",`

Many thanks,
Luke

**Comment by matiu** [comment]
When `xPrivKeyEncrypted` is present, means  that the wallet as a 'password' set ("Request password" option in security settings in current versions).  In order to decrypt the xPrivKey, you need that password.
