### ISSUE TITLE
Ledger Unplugged on Copay?

### ISSUE THREAD

**Issue by RealSEnergy** [bitpay/copay#4026]
is there a way to sync Ledger Unplugged and Copay? when I go to "hardware" wallets when importing new I get "No hardware wallets supported on this device"

what should I do? I read somewhere that the support has been added like half a year ago

**Comment by matiu** [comment]
No, ATM we only support ledger thru the Ledger Chrome App, which (AFAIK) does not support Ledger Unplugged.
