### ISSUE TITLE
Private key and migrating CoPay to new device with iCloud

### ISSUE THREAD

**Issue by dissentertainer** [bitpay/copay#4030]
I have a user who got a new phone and migrated all of their app data to the new device using iCloud without backing up their wallet, but they are showing 0 bits on the new device. I assume this must be because the private key is stored somewhere else on the device and not in the app data or SIM card. I have had them move the SIM card back to the old device to try to get it to it's original state but there are 0 bits on the old device as well after doing that. Any idea where their bits disappeared to and if there is a way to get them back?

I realize that they should have backed up their wallet before migrating, but unfortunately they did not. From a user experience perspective it might be good to think through the sad paths that an average user might take and try to build in some foolproof automated backups. This isn't first time I've seen iCloud and phone migrations send data into a black hole.

**Comment by matiu** [comment]
Copay does not use iCloud to prevent the private key leaving the device. Previous versions of Copay used to use it, but we disabled it for security reasons. I am afraid that if the there are not backups, it is not possible to recover the wallet.

Regarding the UX: Copay forces the user to make the backup before showing the address of the wallet. Current versions even test the backup before showing the address.

**Comment by dissentertainer** [comment]
It's very easy for a user to just skip the backup step. I helped install CoPay about 50 times in a row at an event and the vast majority of people opted out of backing up and said they would do it later. I love the CoPay wallet but this seems like a big UX gap for an average user. I still don't completely understand how the private key could have been removed from the original device. Where was this data being stored if not on the device hard drive or in the application data on iCloud? What action of the user actually resulted in the private key being removed? Whatever that action is, it should probably have a huge warning flag associated with it. 

- Max

**Comment by matiu** [comment]
Thanks a lot for your comments.

> It's very easy for a user to just skip the backup step.
In order to prevent that, the current version of Copay forces the user to demonstrate that she have copied it. 

> . I still don't completely understand how the private key could have been removed from the original device

You mentioned that the user migrated to a new device. Since Copay does not use iCloud for security reasons, the migration of Copay's wallet need to be done manually.

> Where was this data being stored if not on the device hard drive or in the application data on iCloud? 
Locally in the device.


thanks.

**Comment by dissentertainer** [comment]
So the private key would still be on the original device if it wasn't wiped, correct? I had the user turn the original device back on and enable wifi but CoPay on that device still shows zero bits. They claim that they had not yet wiped the device, however they did have to redownload CoPay on that device  from iCloud for some reason. 

So my final question is: is there a way to reconnect a redownload CoPay wallet to a private key that is already on that device from when the wallet was originally installed? 

- Max

**Comment by matiu** [comment]
> So the private key would still be on the original device if it wasn't wiped, correct? 

Yes that is corret.


> I had the user turn the original device back on and enable wifi but CoPay on that device still shows zero bits. They claim that they had not yet wiped the device, however they did have to redownload CoPay on that device  from iCloud for some reason.

If Copay was uninstalled, its related data is erased. But if it was not uninstalled, the Private key should be there.

> So my final question is: is there a way to reconnect a redownload CoPay wallet to a private key that is already on that device from when the wallet was originally installed?

Copay use iOS's file system. As long as the file system was not deleted, and Copay not uninstalled, the priv key should be there.
