### ISSUE TITLE
Enhancement - ledger transfer from old wallet

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#4033]
I recently created a new wallet and transferred my balance from another copay wallet (old wallet).  The old wallet has a transaction history.  It would be nice to have the ability to import the transaction history from the old wallet into the new wallet (as read only and distinct from the new wallet history).  The new wallet should then (in the future) be able to propagate the full history to an even newer wallet.  This would allow me to maintain a long running ledger even if I move to a new wallet.

**Comment by martindale** [comment]
Would this use the "mailbox" feature of BWS to move the data?  This could set an interesting precedent for using BWS as a general-purpose messaging solution.

**Comment by bityogi** [comment]
> import the transaction history from the old wallet into the new wallet (**as read only **

Are transaction histories ever NOT read only?

**Comment by ajp8164** [comment]
The only difference between a messaging app and Copay is transaction history management/accounting and Ux (in a multisig env).  All messages are pay as you go and guaranteed secure/provable by the blockchain.  Cool idea Eric!

**Comment by JDonadio** [comment]
https://blog.bitpay.com/copay-chrome-end/
