### ISSUE TITLE
Enhancement - ability to archive/hide wallet without delete

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#4034]
Would be convenient to be able to hide a wallet (remove it from sidebar) with the ability to make it visible again in the future (via settings).  After I has moved from one wallet to another I'm left with empty wallets that I prefer to keep to reference the transaction history.

**Comment by martindale** [comment]
"Archive" is a great way to explain this.  Then have a separate list of "archived" wallets.  Most importantly, always be able to unarchive!

**Comment by KeyJockey** [comment]
@ajp8164 Heh, great minds think alike: I suggested exactly this already, back in January... https://github.com/bitpay/copay/issues/3739

**Comment by matiu** [comment]
dup: https://github.com/bitpay/copay/issues/3739
