### ISSUE TITLE
Design bug (activity)

### ISSUE THREAD

**Issue by bitcoinuser** [bitpay/copay#4037]
See the screenshot uploaded.

Smartphone: Motorola Moto X Play

![screenshot_20160329-214655](https://cloud.githubusercontent.com/assets/1178856/14145388/1063d80c-f66a-11e5-8709-54449876373b.png)

**Comment by martindale** [comment]
Can confirm this also happens on Google's flagship Nexus line, as well.  Nexus 6P here.

**Comment by matiu** [comment]
fixed on 2.0
