### ISSUE TITLE
Error at wallet service: Please upgrade copay to perform this action

### ISSUE THREAD

**Issue by ziggamon** [bitpay/copay#4039]
Tested out setting up a 2/3 multisig wallet. 
* Ledger via Chrome app
* Chrome browser window
* Mac app

Deposited some btc, tried sending it out -> This happened after first signature. 

Please advise.

**Comment by matiu** [comment]
What version of Copay are you using? (you can see the version on the left sidebar).

**Comment by matiu** [comment]
BTW, you should *NOT* use Chome browser windows for a real wallet, it is only meant for development.

**Comment by ziggamon** [comment]
Thanks for speedy response!

And thanks for advice abt Chrome window - I did not know that. RNG issues?

Running: 
* 1.9.5
* 1.8.2
* 1.6.3

Perhaps this is the problem :)

**Comment by ziggamon** [comment]
Upgraded the mac app one (the lowest version and transaction went out). 
PEBKAC, sorry for wasting your time, and thanks again for speedy reply.

**Comment by matiu** [comment]
no problem. thanks for the update.
