### ISSUE TITLE
Can't delete last wallet on mobile, UI freeze

### ISSUE THREAD

**Issue by gabrielbazan7** [bitpay/copay#4040]

**Comment by gabrielbazan7** [comment]
This could be related to : #4042

**Comment by bektar** [comment]
I'm having the same issue, except my UI doesn't freeze, it is just that nothing happens when i click "Accept" on the confirmation window. Tried on iPhone and iPad with copay 1.9.6 and iOS 9.3

**Comment by Willstar44** [comment]
Getting the same thing . Cant delete any wallet

**Comment by bektar** [comment]
My iPhone claims to have downloaded a new version of Copay, it is still version 1.9.6 though. Anyway, with this version i was able to delete a wallet.

**Comment by Willstar44** [comment]
Yea it working for me on iphone and ipad :)

**Comment by matiu** [comment]
@gabrielbazan7 Could you confirm is working for you?

**Comment by gabrielbazan7** [comment]
The problem still there. UI freeze when the last wallet of Copay is deleted. ( on mobile )
