### ISSUE TITLE
Remove v <= 0.9 wallet format support

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#4045]
See https://github.com/bitpay/bitcore-wallet-client/pull/225

**Comment by martindale** [comment]
Does this prevent older Copay users who might've used Cloud Sync from recovering their wallets in any way?

**Comment by matiu** [comment]
@martindale yes.  But Clould Sync has been disabled for a couple of months now.

**Comment by martindale** [comment]
I am aware of several non-trivial wallets with co-signers that have not migrated away from Cloud Sync as of yet, as they haven't even launched Copay in over a year.  What is the process that should be recommended to them for recovering their keys, if they are unable to access their personal backups?

**Comment by matiu** [comment]
There are only 2 options: their personal backups or the installed Copay
instance.

**Comment by matiu** [comment]
We decided not to move forward with this, since users may have old backups formats stored and may need to restore their wallets from them.

We will restore the Old Copay Backup functions in BWC also.
