### ISSUE TITLE
Copay.io: consider turning off CloudFlare IP blocker

### ISSUE THREAD

**Issue by Squaredude** [bitpay/copay#4049]
I'm using desktop program for Windows 7 64bit, though I don't think it's relevant. It affects the website and all apps that communicate with it.

I have the misfortune of having a terrible ISP (cannot change this), which forces me into one IP that is blocked in a list that CloudFlare uses. This means that I often have to complete a CAPTCHA to view some websites.

Because Copay.io apparently uses this service, the program is not working as it should. I gave it a try on my phone's connection, and the program works as it should.

**Comment by Derrick-** [comment]
I second this. I have been working on a firewall that allows bitcoin services through, and bitpay's use of cloudflare for the Copay insight API has significantly complicated the configuration.

**Comment by braydonf** [comment]
What about running an internal (inside firewall) wallet service? https://bitcore.io/guides/wallet-service

**Comment by Derrick-** [comment]
@braydonf It's for a public access point. As I understand it a custom wallet service needs to be configured on each wallet. If this was a setting that the Copay wallet could fetch from a DHCP server that'd work though :)

**Comment by Squaredude** [comment]
I am still having this issue. I'll have to move to another wallet software. :(

**Comment by martindale** [comment]
It's possible #3158 was caused by this as well.

**Comment by kinoshitajona** [comment]
@Squaredude @martindale If you would like to use my BWS you are welcome to.

Send me a DM on Twitter @kinoshitajona (I accept DMs from all users) I will tell you my url (I have https thanks to Lets Encrypt)

**Comment by Squaredude** [comment]
Thanks, but I've moved to Electrum, since it doesn't give me any issues.

**Comment by dabura667** [comment]
@Squaredude https://github.com/spesmilo/electrum is one of the first bitcoin projects I ever contributed to. You are in good hands.

**Comment by matiu** [comment]
Thanks for you feedback. 

Currently moving away from Cloudfare on our public BWS is not an option, due to our DDOS prevention policies.

As an alternative, you can host your own BWS (see https://bitcore.io/guides/wallet-service) and connect your Copay instances to it.
