### ISSUE TITLE
Optional: Payment proposal notification email could include the Note field

### ISSUE THREAD

**Issue by StartHash** [bitpay/copay#4058]
The current email notification includes the wallet name and the cosigner name. Would it be possible to also include the note?

Reference: https://bitcointalk.org/index.php?topic=1355366.0

**Comment by matiu** [comment]
Closed due to spam link

**Comment by StartHash** [comment]
Not a spam link, I am promoting Copay wallet as a means of decentralized worker hiring system. Maybe you should read it first.

**Comment by isocolsky** [comment]
I think your comment about email notifications is a valid one. I also appreciate the fact that you are using Copay and trying to make it better. I just don't think it is appropriate to promote one's personal business/activity on this medium. It contributed nothing to your request.

**Comment by StartHash** [comment]
I can just remove the links if that's an issue. 

I am fighting 2-3 people every day that point out the small snags in Copay as they suggest other means of arranging payments. It becomes irritating after a while and I really want to provide feedback from actual users that will NEVER forward that feedback to you.
