### ISSUE TITLE
Feature: Ability to propose A/B transactions using the same outputs

### ISSUE THREAD

**Issue by StartHash** [bitpay/copay#4059]
At the moment one dollar transaction request can block several Bitcoins in the shared wallet blocking any other proposals. There should be a setting that allows multiple blocking proposals to be entered and only able to be sent out when funds are available (I am aware of the fees issue, but you can't block whole bitcoins for a thousandth of a Bitcoin). This also creates a denial situation where a minority can create transactions as they expire and the majority can't easily create favorable proposals.

Voting systems or recurring payments would benefit greatly.

Reference: https://bitcointalk.org/index.php?topic=1355366.0

**Comment by matiu** [comment]
Related / Dup: https://github.com/bitpay/copay/issues/168
