### ISSUE TITLE
issue with copay app on windows phone

### ISSUE THREAD

**Issue by TLeonA** [bitpay/copay#4062]
Dear support/ community,
I´m currently experiencing problems with a bitcoin deposit I made on my windows phone copay wallet app.
If I try to send my funds to another wallet, I get an error message telling me:

" The payment was created but could not be signed. Please try again from home screen. Bad signatures"

Now I wanted to backup my wallet on my copay app (on my pc) but I can´t find out how to transfer the backup of my phone app to the copay app on my pc...
Can you help me out with this? I really don´t know what to do...
Kind regards, TLeonA

**Comment by matiu** [comment]
Hi,

Is this a 1-1 (personal) wallet?

Do you have the backup keys? (the 12 words)



On Fri, Apr 8, 2016 at 8:44 AM, TLeonA <notifications@github.com> wrote:

> Dear support/ community,
> I´m currently experiencing problems with a bitcoin deposit I made on my
> windows phone copay wallet app.
> If I try to send my funds to another wallet, I get an error message
> telling me:
>
> " The payment was created but could not be signed. Please try again from
> home screen. Bad signatures"
>
> Now I wanted to backup my wallet on my copay app (on my pc) but I can´t
> find out how to transfer the backup of my phone app to the copay app on my
> pc...
> Can you help me out with this? I really don´t know what to do...
> Kind regards, TLeonA
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/4062>
>



-- 
BitPay.com

**Comment by TLeonA** [comment]
Hi, 
No, it´s the 2nd one I created
I think I´ve got em, : 
"faculty attack million enemy thing word share use unaware rice stamp empty "
The only other thing I´ve got is the "encrypted backup code" of the wallet..
Thank you very much for the quick answer!

**Comment by matiu** [comment]
The words are the backup itself. Please do not share it in public. 

In order to prevent someone else to access you funds, I removed the words from your comment.

Can you try to import that words from other Copay installation to access your funds? Please note you need to put a "passphrase" besides the words in case you set up one at the moment created the wallet.

**Comment by TLeonA** [comment]
OK thanks!
If I enter the words under the option "import wallet" on my pc I get the message: Could not import. Not authorised.

**Comment by TLeonA** [comment]
do I have to choose a random passphrase?
forgot to do that...

**Comment by matiu** [comment]
No, the passphrase is the one you selected when you created the wallet.
Otherwise you will
get the error "Not authorised"

On Fri, Apr 8, 2016 at 9:23 AM, TLeonA <notifications@github.com> wrote:

> do I have to choose a random passphrase?
> forgot to do that...
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/4062#issuecomment-207410580>
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by TLeonA** [comment]
Ok you mean the passphrase of my phones wallet, right?
Is there any way to recover it? I tried it multiple times, even with other passwords, but it didn´t seem to match.. 
Do I have  to fear that I cant´t access my funds anymore now?;(

**Comment by matiu** [comment]
We tried

https://bitpay.github.io/copay-recovery/


with the words you sent previously and no passphrase you send before, but
it seems the wallet is empty.

There are only 5 active addresses, and the newest transaction is from ~20
days ago.




On Fri, Apr 8, 2016 at 9:34 AM, TLeonA <notifications@github.com> wrote:

> Ok you mean the passphrase of my phones wallet, right?
> Is there any way to recover it? I tried it multiple times, even with other
> passwords, but it didn´t seem to match..
> Do I have to fear that I cant´t access my funds anymore now?;(
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/4062#issuecomment-207413877>
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by matiu** [comment]
In the App, you currently see funds?


On Fri, Apr 8, 2016 at 9:45 AM, Matias Alejo Garcia <ematiu@gmail.com>
wrote:

> We tried
>
> https://bitpay.github.io/copay-recovery/
>
>
> with the words you sent previously and no passphrase you send before, but
> it seems the wallet is empty.
>
> There are only 5 active addresses, and the newest transaction is from ~20
> days ago.
>
>
>
>
> On Fri, Apr 8, 2016 at 9:34 AM, TLeonA <notifications@github.com> wrote:
>
>> Ok you mean the passphrase of my phones wallet, right?
>> Is there any way to recover it? I tried it multiple times, even with
>> other passwords, but it didn´t seem to match..
>> Do I have to fear that I cant´t access my funds anymore now?;(
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/bitpay/copay/issues/4062#issuecomment-207413877>
>>
>
>
>
> --
> Matías Alejo Garcia
> @ematiu
> Roads? Where we're going, we don't need roads!
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by TLeonA** [comment]
Yes for sure I do, I can also see them on the blockchain!

**Comment by TLeonA** [comment]
I really don´t get it:(

**Comment by matiu** [comment]
Can we chat at https://gitter.im/bitpay/copay now?

My user is `ematiu`

**Comment by TLeonA** [comment]
matiu or ematiu?

**Comment by matiu** [comment]
`matiu`, sorry.

Resolved offline.

**Comment by TLeonA** [comment]
Lightningfast, very friendly and helpful support, I couldn´t be happier.
Thank you a lot!
