### ISSUE TITLE
lost password 

### ISSUE THREAD

**Issue by utxorob** [bitpay/copay#4069]
I have forgotten my password on my iOS copay wallet. Now i have 13k stuck on there. What do I do?

**Comment by utxorob** [comment]
was a series of numbers.

**Comment by utxorob** [comment]
close this please

**Comment by JoeFerrucci** [comment]
Have a shared wallet with a few friends. We are trying to transfer money but one of the persons got a new phone and didn't backup their 12 word pass phrase. He can't get into wallet. Not sure how to invite him. How do we get our money out?

**Comment by gabrielbazan7** [comment]
Without the backup words is not possible to recover the wallet.

**Comment by richardsuns** [comment]
@utxorob 
you remembered your password? if not i have solution
