### ISSUE TITLE
Feature Request: BWC console 

### ISSUE THREAD

**Issue by gabegattis** [bitpay/copay#4072]
In Bitcoin-qt the debug window has a console where I can enter RPC commands. It would be convenient if Copay had a console where I could directly invoke [BWC Api methods](https://github.com/bitpay/bitcore-wallet-client#api-client).

For example, today I needed to generate a bunch of receiving addresses in my Copay wallet. I had to go to the "Receive" tab and click "Generate New Address" over and over again and manually copy/paste each one into a text file. In bitcoin-qt, I could just run ```getnewaddress``` several times and have all of my new addresses right there in the console window.

**Comment by braydonf** [comment]
Is the equivalent command with the CLI client https://github.com/bitpay/bitcore-wallet ?

**Comment by gabegattis** [comment]
https://github.com/bitpay/bitcore-wallet has most of the commands one would need. The commands have different names that the api methods in BWC though.

But yeah, something like bitcore-wallet for a console inside the Copay UI was the idea.

**Comment by matiu** [comment]
Closing this one (bitcore-wallet seems to be the solution).
