### ISSUE TITLE
can't change Wallet Alias on ios

### ISSUE THREAD

**Issue by ajlowndes** [bitpay/copay#4084]
can't change alias on ios - it give me the ability to type a new name, but the text goes grey when I hit "done". the "Save" button doesn't respond. If I click "back" the name has not been changed from "Personal Wallet".

**Comment by JDonadio** [comment]
I'm trying to reproduce this issue following step by step that you say, but it's working well for me. What version of Copay are you using? If you can add more info would be great.

**Comment by ajlowndes** [comment]
Eventually got it to work by typing my new wallet name, pressing "done" then hitting the iPhone power button to put the device to sleep. When I turned it back on and unlocked, the save button worked. Same "fix" for the other issue I posted

**Comment by ajlowndes** [comment]
As score the version... 1.9.6 as I just downloaded it

**Comment by gabrielbazan7** [comment]
It's working well for me also. This always happens to you when you try to change alias ? Or sometimes ?

**Comment by ajlowndes** [comment]
I'm a brand new user so not much experience.I installed Copay, clicked around for a bit, found a few bugs including this - tried to rename my 'Personal Wallet' a few times. As said before I had now gotten it to work but I'm not sure how to give more specific instructions to reproduce.
Something that might help - 2 days prior I had installed Copay, decided I didn't want it, deleted it. But I had written down the 12-word phrase. When I reinstalled it gave me a different phrase, and I was trying to figure out why (I'm new...). So now I have eventually managed to enter the old "original" phrase onto my ios app and my mac app*, managed to rename it on both machines and deleted the wallet the the installation created. 
*let me know if I shouldn't do that as I can't find any help files on the proper way to use multiple devices

**Comment by JDonadio** [comment]
I'm trying to reproduce it without luck... It's working for me.

Off topic: When you install Copay and accept the terms a wallet (Personal Wallet) is created. In this case you have a random seed (12 wods) because that wallet was created by default. If you keep that seed safe, you will be able to restore your wallet whenever you want from "wallet seed" tab. Note: each wallet in your Copay application have a different seed so if you have more than one, you have more than one wallet.

**Comment by matiu** [comment]
We try several ios devices, and cannot reproduce the error. Please recheck the issue and reopen of necessary.
