### ISSUE TITLE
Set up a Password "Cancel" button doesn't work

### ISSUE THREAD

**Issue by ajlowndes** [bitpay/copay#4085]
Go to Set up a password - decide not to (I'm a newbie, trying to figure out how to set up on ios and mac), find that the cancel button doesn't work.

Observed this behaviour in IOS and on the Mac application.

**Comment by JDonadio** [comment]
@ajlowndes can you try to update Copay in order to check if this issue has been solved?

**Comment by matiu** [comment]
fixed.thanks.
