### ISSUE TITLE
ios - imported a wallet, Scan fingerprint option won't stay on

### ISSUE THREAD

**Issue by ajlowndes** [bitpay/copay#4086]
Imported a wallet onto ios device, find that I cannot turn on the "scan fingerprint" option for that wallet. Tried turning it off for the default wallet created, then on for my imported one. still doesn't work. the slider stays on but when I click "Back" it turns off again.

**Comment by JDonadio** [comment]
I just sent a fix for this. Thanks for reporting!

**Comment by ajlowndes** [comment]
Np
