### ISSUE TITLE
Can't access my old Android wallet 

### ISSUE THREAD

**Issue by maraoz** [bitpay/copay#4094]
Haven't opened my Android wallet in a long time, and now I get:
![screenshot_2016-04-19-02-19-30](https://cloud.githubusercontent.com/assets/287189/14640141/7d968cb0-0616-11e6-96a2-a340c485b5f3.png)

I downloaded Copay on a new phone and I find no way to restore my account from the cloud backup I have, it automatically creates a new wallet. I couldn't find any way of logging in with my email as I did before, when I used Copay.

Any ideas?

**Comment by matiu** [comment]
Copay does not longer support cloud storage (since ~6 months ago).


You can import your old cloud storage using: Add Wallet -> Import -> File
Backup -> Import Copay v0.9.

Please note that this option will be removed shortlly.


On Tue, Apr 19, 2016 at 10:08 AM, Manuel Aráoz <notifications@github.com>
wrote:

> Haven't opened my Android wallet in a long time, and now I get:
> [image: screenshot_2016-04-19-02-19-30]
> <https://cloud.githubusercontent.com/assets/287189/14640141/7d968cb0-0616-11e6-96a2-a340c485b5f3.png>
>
> I downloaded Copay on a new phone and I find no way to restore my account
> from the cloud backup I have, it automatically creates a new wallet. I
> couldn't find any way of logging in with my email as I did before, when I
> used Copay.
>
> Any ideas?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/4094>
>



-- 
BitPay.com

**Comment by maraoz** [comment]
So there's no longer a cloud storage of my encrypted wallets? Even if I download and run an older version, I can't access that?

**Comment by matiu** [comment]
Right, no new wallets are stored on the cloud, and  access to the old ones will be removed soon.

**Comment by maraoz** [comment]
I could access my old wallet using your method, thanks Mati!

**Comment by matiu** [comment]
Great.Be sure to migrate to a new one, and store the mnemonic
