### ISSUE TITLE
Way to launch copay app ready to "receive" payment

### ISSUE THREAD

**Issue by tmmunro** [bitpay/copay#4095]
In my app I can use the following URI scheme to launch copay such that copay is ready to make a payment to the address I specify:
bitcoin:{address}

Is there a similar URI scheme I can use to launch the copay app without specifying a pay-to address? Specifically I would like the user to get (copy) a "receive" address from their wallet.

Thanks a lot.

**Comment by matiu** [comment]
Interesting.

At the moment, there is not such procedure, but I leave this open so we can
evaluate how to implement it.

On Tue, Apr 19, 2016 at 9:04 PM, tmmunro <notifications@github.com> wrote:

> In my app I can use the following URI scheme to launch copay such that
> copay is ready to make a payment to the address I specify:
> bitcoin:{address}
>
> Is there a similar URI scheme I can use to launch the copay app without
> specifying a pay-to address? Specifically I would like the user to get
> (copy) a "receive" address from their wallet.
>
> Thanks a lot.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/4095>
>



-- 
BitPay.com
