### ISSUE TITLE
[Proposal] Change "Seed" by "Recovery phrase", like breadwallet.

### ISSUE THREAD

**Issue by Kirvx** [bitpay/copay#4097]
I think the seed is a technical term which adds an interrogation for new users, and makes difficult the translation of it.

Also, a "recovery phrase" is 100% explicit.

Thoughts?

**Comment by isocolsky** [comment]
+1

**Comment by dabura667** [comment]
種？ lol

**Comment by matiu** [comment]
While seed is probably too technical, I would like the user to understand that those words *are* the secret. And are *not a credential* to access the secret stored remotely. 

I think an explanation in the form could be the best solution, but maybe I am overthinking this and "recovery phase"  is just fine.

**Comment by Kirvx** [comment]
#4109

In the page that asks to write down the recovery phrase, I added:

"This set of words (also called "seed") fully contains your bitcoins by reconstructing the private key without any contact with a distant server (as specified in the BIP39 Standard)."

**Comment by Kirvx** [comment]
Merged in https://github.com/bitpay/copay/pull/4201
