### ISSUE TITLE
Scanning crashes app after upgrade to 1.10.2

### ISSUE THREAD

**Issue by JulianTosh** [bitpay/copay#4098]
CoPay 1.10.2 hard crashes when I press any scan icon in any context.

Scanning worked fine under last release (1.9.7)

Nexus 6
Android 6.0.1
Kernel 3.10.40-gae8e7ad Build MMB29X

**Comment by JulianTosh** [comment]
Camera works well with other apps.

Workaround is to use zxing barcode scanner to get address into clipboard, then start tx in copay. address field populates with address from clipboard.

**Comment by Kirvx** [comment]
Same problem.
Z3 Compact.
Android 6.0.1

**Comment by JulianTosh** [comment]
this merge has resolved my issue. Thanks!
