### ISSUE TITLE
Wallet seed input random order

### ISSUE THREAD

**Issue by sir-lebowski** [bitpay/copay#4099]
Hi.

Please make wallet seed import prompt for and input 1 word at a time in random order. This will defeat keyboard loggers. Just my opinion, man.

Take it easy.

**Comment by isocolsky** [comment]
I don't think it will defeat keyboard loggers as the number of permutations of 12 words = 479001600 which is not big enough to be secure against brute force attacks.

**Comment by dabura667** [comment]
Like Trezor, if the user has 12 words, randomly tell the user "write down 'apple'" etc. intermittenly so that no matter what, they write down 24 words.
