### ISSUE TITLE
Multisig Recovery Question

### ISSUE THREAD

**Issue by blueknight02** [bitpay/copay#4104]
Hello,

I am currently using a multisig wallet with multiple devices. I have backed up the seeds for all of the devices. But I was wondering what the process would be to recover my wallet if one of the devices was lost. How would I connect a new device to my existing multisig setup? Am I safe by just backing up the seed, or should other info like the wallet id be saved as well?

Thank you for the help. Love this wallet so far!

**Comment by matiu** [comment]
Thanks!

Check https://github.com/bitpay/copay#copay-backups-and-recovery

Let us know any question.

**Comment by blueknight02** [comment]
Wow! Talk about a quick response. Thanks for this. Keep up the great work.
