### ISSUE TITLE
Inaccurate "not valid" amount

### ISSUE THREAD

**Issue by braydonf** [bitpay/copay#4107]
At commit: https://github.com/bitpay/copay/commit/4761b68fcdbd0de9155a8b0d3e26db33094ba83e (1.10.3)

![copay-amount-invalid](https://cloud.githubusercontent.com/assets/544777/14719539/c4550bf8-07ca-11e6-9619-d0678779c345.png)

This amount is valid, no?

**Comment by braydonf** [comment]
Some more details from https://github.com/bitpay/copay/blob/master/src/js/directives/directives.js#L103:
```
decimals 8
sep_index 1
str_value 019815140000000002
validAmount false
```

Looks like this may be related to: https://github.com/bitpay/copay/issues/4096

**Comment by braydonf** [comment]
Updated code with by running `grunt` to update `public/js/copay.js` and this issue has been fixed. Interesting that the amount was being displayed differently though.

**Comment by JDonadio** [comment]
Thank you @braydonf !
