### ISSUE TITLE
Restore Testnet backup seed

### ISSUE THREAD

**Issue by CowboyNick** [bitpay/copay#4127]
When attempting to restore a 12 word backup seed for a testnet wallet, I get the error "Could not import: not authorized". This wallet was originally created and used with Copay and I am able import into Mycelium to verify it's balance.

**Comment by gabrielbazan7** [comment]
Read #3856. 

> In order to import testnet wallet you need to modify the 'coin type' path element in the derivation path.
> Something like: m/44'/1'/0'
