### ISSUE TITLE
where the Bws/api/retrieve and bws/api/save are move to

### ISSUE THREAD

**Issue by 6cap-haipeng** [bitpay/copay#4128]
hi, I am trying to learn bitcore,copay-mobile codes, when run copay mobile app in debug mode @ reigiste new user page, which is accessing local "bitcore-wallet-service" instance like this 
http://192.168.164.145:3333/bws/api

but, the error code pop up, "http://192.168.164.145:3333/bws/api/email/retrieve?key=profile%3A%3Ab7cc99b2546d37fc8f23fd23633beb4441b53b32 Failed to load resource: the server responded with a status of 404 (Not Found)"

if I use cli command to create the wallet, successfully get  the wallet
"wallet-create -h http://192.168.164.145:3333/bws/api 'myWallet' 1-1"

And, I had configured the postfix server and running in behind, 
what else should i need to do to resolve this error?
I has installed insight-api, insight-ui, bws service and running in good.

thanks

Searoc

**Comment by matiu** [comment]
Please see

https://github.com/bitpay/copay-mobile#copay-mobile



On Mon, Apr 25, 2016 at 7:45 AM, 6cap-haipeng <notifications@github.com>
wrote:

> hi, I am trying to learn bitcore,copay-mobile codes, when run copay mobile
> app in debug mode @ reigiste new user page, which is accessing local
> "bitcore-wallet-service" instance like this
> http://192.168.164.145:3333/bws/api
>
> but, the error code pop up, "
> http://192.168.164.145:3333/bws/api/email/retrieve?key=profile%3A%3Ab7cc99b2546d37fc8f23fd23633beb4441b53b32
> Failed to load resource: the server responded with a status of 404 (Not
> Found)"
>
> I had configured the postfix server and running in behind,
>
> what else should i need to do to resolve this error?
> I has installed insight-api, insight-ui, bws service and running in good.
>
> thanks
>
> Searoc
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/4128>
>



-- 
BitPay.com

**Comment by 6cap-haipeng** [comment]
I use the default insight URL in copay-mobile, the same error cames like below.

insight.bitpay.com/api/email/retrieve?key=profile%3A%3Ab7cc99b2546d37fc8f23fd23633beb4441b53b32:1 GET https://insight.bitpay.com/api/email/retrieve?key=profile%3A%3Ab7cc99b2546d37fc8f23fd23633beb4441b53b32 403 (Forbidden)
copay.js:192 [info] [InsightStorage. err] PNOTFOUND: Profile not found
copay.js:25632 GET https://insight.bitpay.com/api/email/retrieve?key=profile%3A%3Ab7cc99b2546d37fc8f23fd23633beb4441b53b32 403 (Forbidden)run_xhr @ copay.js:25632request @ copay.js:25593request.(anonymous function) @ copay.js:25761InsightStorage._makeGetRequest @ copay.js:7748InsightStorage._brokenGetItem @ copay.js:7768(anonymous function) @ copay.js:7711(anonymous function) @ copay.js:7754on_end @ copay.js:25708on_state_change @ copay.js:25658
insight.bitpay.com/api/email/save:1 POST https://insight.bitpay.com/api/email/save 404 (Not Found)

is there any change to to the URL of bitpay BWS API?

**Comment by matiu** [comment]
Copay-mobile is not longer maintained. Please see its readme.

/api/email/retreive was deprecated more that a year ago.

**Comment by 6cap-haipeng** [comment]
thank you very much
