### ISSUE TITLE
Valid Payment Request fails (silently)

### ISSUE THREAD

**Issue by Derrick-** [bitpay/copay#4130]
Current Behavior:
> Using the following url
> bitcoin:1DPJ6MGr2mBtx9gX9h92mPmwERFj5TUbJR?amount=0.01337&r=https://agoristhosting.com/bip70/request/136a8d1b-d721-4c65-b704-ed296ef48fb4
> 
> Payment request fails with no error. Fields display only the address and amount.
> Same URL works fine on bitcoin Core and Mycelium.
> 
> Using a simplified format with the following URL does show an error:
> bitcoin:?r=https://agoristhosting.com/bip70/request/136a8d1b-d721-4c65-b704-ed296ef48fb4
> "Payment Protocol Invalid"
> 

Expected behavior:
> CoPay retrieves and validates the Payment request from https://agoristhosting.com/bip70/request/136a8d1b-d721-4c65-b704-ed296ef48fb4

To reproduce:
> Paste this into the To field on send tab: bitcoin:1DPJ6MGr2mBtx9gX9h92mPmwERFj5TUbJR?amount=0.01337&r=https://agoristhosting.com/bip70/request/136a8d1b-d721-4c65-b704-ed296ef48fb4

**Comment by Derrick-** [comment]
After combing the code, this looks like it's a problem with signature verification, however other wallet software tested does validate the certificate chain in the payment request. (Core, Mycelium)

**Comment by braydonf** [comment]
If the payment request is failing verification when it should, we could use more test cases in: https://github.com/bitpay/bitcore-payment-protocol

Sounds like it could be useful to diplay a note that payment protocol was not used when using a backwards compatible BIP72 URI, and give an error in the a case that non-backwards compatible BIP72 URI. Though this may be the case, since payment protocol will display differently (I believe with a small lock).

**Comment by matiu** [comment]
Thanks for the report.

Not sure I understand the issue. Could you describe one input in particular, and details which is current the result, and which should be the right result.

**Comment by Derrick-** [comment]
@matiu
I found the Session Log and can confirm the error is in certificate validation. The error message is "Failed to verify payment protocol signatures".

The signature verification is failing for the payment request, yet it is to the best of my knowledge and testing valid and contains the intermediate cert in additional certificates). It is expected that this Payment Request contains a valid certificate chain and should be accepted.

I have traced this (visually) as far as "bitcore-wallet-client/lib/paypro.js" function which seems to be returning verified:false. I am not equipped to debug the project currently.

The Certificate chain is:
-GeoTrust Global CA
--RapidSSL SHA356 CA
---agoristhosting.com

For offline testing, the Base64 encoded PaymentRequest is attached in the following file
[136a8d1b-d721-4c65-b704-ed296ef48fb4.txt](https://github.com/bitpay/copay/files/235187/136a8d1b-d721-4c65-b704-ed296ef48fb4.txt)

@braydonf 
Yes, I agree that there should be some visual queue that the payment request was attempted, failed and fell-back.

Thanks for your attention to this!

**Comment by braydonf** [comment]
Here is the location of other sample requests: https://github.com/bitpay/bitcore-payment-protocol/blob/master/test/samplerequest.js

**Comment by matiu** [comment]
Thanks @Derrick- for the details. Adding a test case for bitcore-payment-protocol repo will be the best way to get this solved.

> Yes, I agree that there should be some visual queue that the payment request was attempted, failed and fell-back.

+1 on that.

**Comment by isocolsky** [comment]
FYI, there seems to be a problem with expiration times when validating. [This test](https://github.com/bitpay/bitcore-wallet-client/blob/master/test/paypro.js#L52) from Bitcore-wallet-client is suddenly failing. Setting the local date to sometime in the past seems to fix the issue. @braydonf, @matiu

**Comment by braydonf** [comment]
@isocolsky Test updated https://github.com/bitpay/bitcore-payment-protocol/pull/34

**Comment by braydonf** [comment]
@Derrick- From the payment request, there is an error: `Error: Illegal group end indicator for Message .PaymentRequest: 10 (not a group)`, when running:
```
var data = PaymentProtocol.PaymentRequest.decode(paymentRequestData);
var pr = new PaymentProtocol();
pr = pr.makePaymentRequest(data);
```

**Comment by Derrick-** [comment]
@braydonf Thanks. I have deleted that data file as it was in error.

I am presently working through a test case and have found at least one problem. It appears that the chain validation is making an assumption that all the certificates in the chain have the same signing algorithm. This causes a failure in my case because i am using a SHA1 cert but the rest of the certs in the chain are SHA256.

This occurs in bitcore-payment-protocol\lib\index.js during
PaymentProtocol.verifyCertChain(chain, sigHashAlg)
at crypto.createVerify('RSA-' + sigHashAlg);

**Comment by Derrick-** [comment]
Pull request to fix mixed certificate cert hashes: 
https://github.com/bitpay/bitcore-payment-protocol/pull/35

**Comment by Derrick-** [comment]
@matiu I have added a test case here along with a fix for mixed certificate signature algorythms.
https://github.com/Derrick-/bitcore-payment-protocol

My test passes in Mocha, but fails sig-validation in Karma. I have not been able to get tooled up to debug in Karma. I'm hoping another developer who is better suited to this can take a look and see what's going on.

Thanks.

**Comment by braydonf** [comment]
I see, thanks for adding the test case.

**Comment by matiu** [comment]
This will be fixed in the upcoming version, with the updated bitcore-lib and root-certs.
