### ISSUE TITLE
it is reported by Windows Defender that the copay-win.exe has virius

### ISSUE THREAD

**Issue by pgp66992e0d** [bitpay/copay#4137]
as subject

**Comment by dabura667** [comment]
Where did you download the file?

Also, remember that some viruses like to infect other exe files randomly on the computer.

**Comment by monosux** [comment]
Have same problem. Downloaded from https://github.com/bitpay/copay/releases/tag/v1.11.0

Virustotal detected too: https://www.virustotal.com/ru/file/661682830dd28b329405f6c96504ea0d0ad5b2937bb3da5fc0caa136bf058937/analysis/1461757531/

**Comment by cmgustavo** [comment]
What version of Windows do you have? Do you have Windows Defender updated? 

I downloaded and installed it on Windows 10 without issue.

https://github.com/bitpay/copay/releases/tag/v1.11.0

**Comment by pgp66992e0d** [comment]
The virus is Torjan:Win32/Gatrid.E!cl

The virus database of Windows Defender is timestamp as 2016/4/26 version 1.219.25.0.

The url in question is https://github.com/bitpay/copay/releases/download/v1.11.0/Copay-win.exe
