### ISSUE TITLE
eh i need to keep 1 address for my wallet

### ISSUE THREAD

**Issue by walrusxi** [bitpay/copay#4138]
I own a shop, i want to keep 1 address

thanks!

**Comment by dabura667** [comment]
You can receive to the same address multiple times.

**Comment by walrusxi** [comment]
eh but it says for your privacy it changes after every paymente

**Comment by matiu** [comment]
Yes, your wallet can handle multiple address. You can see all the wallet's address in Settings > Advanced > Wallet Information.

It is recommended to use a new address for each payment, but it is not mandatory.
