### ISSUE TITLE
Error on build for android copay wallet

### ISSUE THREAD

**Issue by Canalytic** [bitpay/copay#4140]
I am using the `make android-prod` command but get the error:

Error: Registry returned 404 for GET on https://registry.npmjs.org/hu.dpal.phonegap.plugins.spinnerdialog

It seems I might have a PATH variable issue, but I have my crosswalk path as 

export CROSSWALK="/usr/local/lib/node_modules/crosswalk-app-tools/src/crosswalk-app"

Has anybody come across this error?  I am using IOS and following the linux instructions.

**Comment by matiu** [comment]
What cordova version you have installed?

**Comment by Canalytic** [comment]
6.1.1

**Comment by Canalytic** [comment]
6.1.1

**Comment by matiu** [comment]
This seems to be fixed now. Probably a temporary outage.
