### ISSUE TITLE
Help recovering a "corrupt" json.aes data file?

### ISSUE THREAD

**Issue by dmnyc** [bitpay/copay#4141]
I downloaded a file when creating a wallet on https://startwallet.com but when I tried to import it, I got an error message saying it was corrupt. I didn't create a profile, so this is all I have to go from. How can this be recovered?

**Comment by matiu** [comment]
Hi, you need to contact startwallet providers, we don't support it.

**Comment by dmnyc** [comment]
The support page on Startwallet seemed to direct me to Copay, but I was able to recover the wallet after a few attempts. Thanks.
