### ISSUE TITLE
Error : Signature rejected by server

### ISSUE THREAD

**Issue by Afzizul** [bitpay/copay#4142]
Im going to transfer the money from copay wallet to another but get this error.
This error was happen after i updating the version. Can anyone here explain about this?

**Comment by matiu** [comment]
Please see 

https://github.com/bitpay/copay/wiki/Signature-Rejected-by-the-Server-or-Cannot-verify-Server-Response

This error is currently been discussed here:
https://github.com/bitpay/copay/issues/4133
