### ISSUE TITLE
BWS started but cannot connect from client

### ISSUE THREAD

**Issue by sarawutpkg** [bitpay/copay#4143]
I used AWS EC2 
Ubuntu server 14.04 64 bit

I install AWS by  
- npm install bitcore-wallet-service

and start it by 
- npm start

![services_start](https://cloud.githubusercontent.com/assets/18715062/14878312/f4b192da-0d4c-11e6-8052-1808f6996f83.png)

my aws Inbound port

![aws](https://cloud.githubusercontent.com/assets/18715062/14878347/2663ec4c-0d4d-11e6-8a26-2ad144142c81.png)

I try   ps -ef
 
can't see BWS service

![psef](https://cloud.githubusercontent.com/assets/18715062/14878367/4f989a2c-0d4d-11e6-8cf7-85c35379526c.png)

I try to test service via http , but cannot load

![739681](https://cloud.githubusercontent.com/assets/18715062/14878566/8975d740-0d4e-11e6-995a-075c3c26251a.jpg)

thank you in advanced

**Comment by matiu** [comment]
Please report this issue on BWS's issue tracker:
https://github.com/bitpay/bitcore-wallet-service
