### ISSUE TITLE
Unknown error type: BADREQUEST

### ISSUE THREAD

**Issue by JulianTosh** [bitpay/copay#4150]
Working on Chrome and android 2-of-2 wallet using version 1.11.0.

I'm attempting to create a proposal to 'send all' funds and I get this from the session log:

```
Unknown error type: BADREQUEST
```

I am able to send "less than the full amount", but I'm afraid that with this error, this wallet will forever be tained with some amount of left over funds.

**Comment by JulianTosh** [comment]
I've tried sending to a different/known good address and changed the fees to priority|normal|economy. funds I'm spending are confirmed.

**Comment by JDonadio** [comment]
You tried with another device or just with your cell phone? Android 6 right?

**Comment by JulianTosh** [comment]
I've attempted to create the proposal on both devices. Same result.

Since, I have spent most of the funds out of the wallet, leaving only a single input left to spend. Current balance is less than 10,000 bits. I just tried to make another proposal, thinking it was a fee miscalculation, but its still giving me bad request.

**Comment by JulianTosh** [comment]
Opps, correct, phone is android 6. chrome is Version 50.0.2661.86 (64-bit) on fedora/linux

**Comment by JDonadio** [comment]
Sorry, did you transferred the funds without send max option?

**Comment by JDonadio** [comment]
Please try this tool to move of your funds left

https://bitpay.github.io/copay-recovery/

**Comment by JulianTosh** [comment]
I'd rather the private keys don't come together in one spot like that. Is there any way to get more detail on the source of the issue?

**Comment by matiu** [comment]
If 10,000 bits al you have in that wallet? Would you be willing to sell us
the wallet so we can try to debug the problem?

On Thu, Apr 28, 2016 at 2:31 PM, JulianTosh <notifications@github.com>
wrote:

> I'd rather the private keys don't come together in one spot like that. Is
> there any way to get more detail on the source of the issue?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/4150#issuecomment-215503397>
>



-- 
BitPay.com

**Comment by JulianTosh** [comment]
Eh, can't do that. I'll have to wait for a new release that offers more logging detail or get what I can out and /or recreate a new wallet.

**Comment by matiu** [comment]
ok, thanks anyways.

On Thu, Apr 28, 2016 at 2:45 PM, JulianTosh <notifications@github.com>
wrote:

> Eh, can't do that. I'll have to wait for a new release that offers more
> logging detail or get what I can out and /or recreate a new wallet.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/4150#issuecomment-215507382>
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by matiu** [comment]
To understand better the issue

1) Is this is a new wallet (ie with mnemonic backups) or it is an old one, imported?
2) Are you using the wallet were at the devices were it was created or you import it on new devices?

**Comment by JulianTosh** [comment]
This is a new wallet with mnemonic backups. It's a 2-of-2 split between a chrome app and and android phone. The wallet was created and is being used on the same/original devices.

The wallet has received numerous deposits over time. Up until this issue, most of the funds have been withdrawn successfully with the exception of a few thousand bits. At around 1-2 bitcoins remaining, I used the 'send all' feature and got the "BADREQUEST" error. I reduced the spend to less than the full amount and it worked. The wallet now only has a few thousand bits remaining with only a single input with the remaining funds. 'send all' continues to result in 'BADREQUEST'.

**Comment by matiu** [comment]
ok, thanks we will investigate that case.

On Thu, Apr 28, 2016 at 3:26 PM, JulianTosh <notifications@github.com>
wrote:

> This is a new wallet with mnemonic backups. It's a 2-of-2 split between a
> chrome app and and android phone. The wallet was created and is being used
> on the same/original devices.
>
> The wallet has received numerous deposits over time. Up until this issue,
> most of the funds have been withdrawn successfully with the exception of a
> few thousand bits. At around 1-2 bitcoins remaining, I used the 'send all'
> feature and got the "BADREQUEST" error. I reduced the spend to less than
> the full amount and it worked. The wallet now only has a few thousand bits
> remaining with only a single input with the remaining funds. 'send all'
> continues to result in 'BADREQUEST'.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/4150#issuecomment-215519269>
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by JulianTosh** [comment]
FYI, I have closed the app and used 'scan addresses for funds' just to make sure I had "good info" on the wallet. No change.

**Comment by JulianTosh** [comment]
I've identified an amount where the send amount doesn't return "insufficient funds" and starts returning the "bad request" error. I'm decrementing the amount to send by a satoshi to find the point where it goes through (in my free cycles while i'm waiting for processes to finish in my "day job" lol)... so doing this, I'm noticing that the fee has changed from 96 bits to 98 bits simply by changing the amount being sent by a satoshi. Again, there is only a single input with funds left in the wallet, so it indicates to me that the transaction has now become "more complex" by generating a change output. Dunno what that means in relation to this problem, but that's what I'm seeing so far. If I hit that magic number and the send goes through, I'll report back what the result was.

**Comment by JDonadio** [comment]
Great! thanks for your report. We are also working hard on this.

**Comment by JulianTosh** [comment]
Sanity Check...

I can send fractions of bits, correct? Example: When I try to spend "1111.11" bits, the confirmation screen displays something like "1,112 bits"

Just want to make sure the "badrequest" i'm seeing during this "experiment" is not being caused by an inability to spend a fraction of a bit.

**Comment by JulianTosh** [comment]
When I see that the fee bumps up as I'm decrementing the amount to send, I will stop decrementing and subtract the new fee from the available funds in the input. What's interesting is that I'll go one satoshi above that "just because" and i never get an "insufficient funds". So I'll keep decrementing the satoshi until the next fee increase. Been doing this a couple times now and I've gone from 96 bits to currently 102 bits for the fee.

My intuition tells me there's a bug in the fee calculation.

**Comment by JDonadio** [comment]
Finally we were able to reproduce the error. We are now trying to fix it and we'll keep you updated. Thanks alot for your feedbacks!

**Comment by pgp66992e0d** [comment]
The same here.  I test by "send max" from a 2x3 address and get error "Could not create payment proposal: BADREQUEST".  However, if send less the payment then everything ok.

**Comment by JDonadio** [comment]
There was a bug using send max creating transactions. I hope this fix solve all of "bad signatures" and "bad requesting" errors as well.

**Comment by matiu** [comment]
This should  be fixed in 0.12.x


please reopen if still valid.

**Comment by JulianTosh** [comment]
Confirmed fixed. You guys are awesome!
