### ISSUE TITLE
 "Uncaught ReferenceError: angular is not defined", source: file:///android_asset/www/lib/angular.js

### ISSUE THREAD

**Issue by seigneur** [bitpay/copay#4153]
After launching the debug or signed version I get the launch screen and then the above error. I am using the emulator Nexus 5 API 21

However the file exists in the assets folder in android under platforms.

Full Logcat:
D/SystemWebViewEngine( 2558): CordovaWebView is running on device made by: unknown
W/art     ( 2558): Attempt to remove local handle scope entry from IRT, ignoring
W/art     ( 2558): Attempt to remove local handle scope entry from IRT, ignoring
I/art     ( 2558): Background sticky concurrent mark sweep GC freed 3414(240KB) AllocSpace objects, 2(32KB) LOS objects, 0% free, 6MB/6MB, paused 509us total 127.789ms
D/OpenGLRenderer( 2558): Render dirty regions requested: true
D/Atlas   ( 2558): Validating map...
V/StatusBar( 2558): StatusBar: initialization
D/FileUtils( 2558): Unrecognized extra filesystem identifier: files-external
D/FileUtils( 2558): Unrecognized extra filesystem identifier: sdcard
D/FileUtils( 2558): Unrecognized extra filesystem identifier: cache-external
I/OpenGLRenderer( 2558): Initialized EGL, version 1.4
D/        ( 2558): HostConnection::get() New Host Connection established 0xa4861ed0, tid 2593
D/OpenGLRenderer( 2558): Enabling debug mode 0
W/EGL_emulation( 2558): eglSurfaceAttrib not implemented
W/OpenGLRenderer( 2558): Failed to set EGL_SWAP_BEHAVIOR on surface 0xa48ca2c0, error=EGL_SUCCESS
W/EGL_emulation( 2558): eglSurfaceAttrib not implemented
W/OpenGLRenderer( 2558): Failed to set EGL_SWAP_BEHAVIOR on surface 0xa48ca2e0, error=EGL_SUCCESS
I/ActivityManager( 1210): Displayed com.bitpay.copay/.MainActivity: +904ms
D/AndroidRuntime( 2547): Shutting down VM
E/AndroidProtocolHandler( 2558): Unable to open asset URL: file:///android_asset/www/icons/foundation-icons.css
D/TaskPersister( 1210): removeObsoleteFile: deleting file=12_task.xml
I/chromium( 2558): [INFO:CONSOLE(2)] "Uncaught ReferenceError: angular is not defined", source: file:///android_asset/www/lib/angular.js (2)
D/JsMessageQueue( 2558): Set native->JS mode to OnlineEventsBridgeMode
I/chromium( 2558): [INFO:CONSOLE(21)] "Uncaught ReferenceError: angular is not defined", source: file:///android_asset/www/js/copay.js (21)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
D/CordovaNetworkManager( 2558): toLower : mobile
D/CordovaNetworkManager( 2558): wifi : wifi
D/CordovaNetworkManager( 2558): Connection Type: 3g
D/CordovaNetworkManager( 2558): Connection Extra Info: epc.tmobile.com
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
D/CordovaNetworkManager( 2558): toLower : mobile
D/CordovaNetworkManager( 2558): wifi : wifi
D/CordovaNetworkManager( 2558): Connection Type: 3g
D/CordovaNetworkManager( 2558): Connection Extra Info: epc.tmobile.com
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
V/StatusBar( 2558): Executing action: _ready
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2558): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2558): **** ERROR unknown type 0x0 (glSizeof,72)
I/ConfigService( 1588): onDestroy

**Comment by matiu** [comment]
Are you building Copay by your self?

Did you run `npm i` and `bower i`?

**Comment by JDonadio** [comment]
Make sure that you're including angular.js library before call any process.

**Comment by seigneur** [comment]
Yes, we are suggesting using it to our clients, and just in case they do not use an app store needed an option. 

I missed the bower install all good now, thank you and sorry for the trouble.
