### ISSUE TITLE
"Signatures rejected by server" error when trying to send

### ISSUE THREAD

**Issue by TravellingGuy** [bitpay/copay#4158]
Similar to issue #3991, I'm getting an error "Signatures rejected by server" when trying to send money to another address.

I'm a new user of bitcoin and Copay, installed Copay on my Android device less than 2 weeks ago, so my problem shouldn't be related to having an old wallet (as referenced in issue #3991).

When I create the transaction and try to send it, it gives me this error message:
"The payment was created but could not be completed. Please try again from home screen."

When I go to the home screen and try to send it, it fails with the error "Signatures rejected by server".

I've tried to cancel the redo the payment numerous times, but it always fails.

**Comment by matiu** [comment]
Are you using Android 6?

Did you created the transaction using 'send-max'?

**Comment by TravellingGuy** [comment]
I am on Android 6, yes.

I did not use "send-max" when creating the transaction. The amount I'm trying to send is less than the amount I have in my wallet.

**Comment by matiu** [comment]
- Do you have multiple wallets in Copay?
 - Do you have you key encrypted? (request a password for sending funds)

On Fri, Apr 29, 2016 at 2:55 PM, TravellingGuy <notifications@github.com>
wrote:

> I am on Android 6, yes.
>
> I did not use "send-max" when creating the transaction. The amount I'm
> trying to send is less than the amount I have in my wallet.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/4158#issuecomment-215829943>
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by TravellingGuy** [comment]
I do not have multiple wallets in Copay, just the default wallet.

I do not have my key encrypted (it does not request a password for sending funds).

**Comment by matiu** [comment]
thanks a lot, we will check more.

On Fri, Apr 29, 2016 at 3:25 PM, TravellingGuy <notifications@github.com>
wrote:

> I do not have multiple wallets in Copay, just the default wallet.
>
> I do not have my key encrypted (it does not request a password for sending
> funds).
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/4158#issuecomment-215838885>
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by matiu** [comment]
Closing this one here: Please continue the discussion here: https://github.com/bitpay/copay/issues/4133

**Comment by matiu** [comment]
Hey, we think we have a solution:

Could you please try this version:

https://github.com/bitpay/copay/releases/download/v1.12.1/android-release-signed-aligned.apk

thanks a lot.

On Fri, Apr 29, 2016 at 3:30 PM, Matias Alejo Garcia <ematiu@gmail.com>
wrote:

> thanks a lot, we will check more.
>
> On Fri, Apr 29, 2016 at 3:25 PM, TravellingGuy <notifications@github.com>
> wrote:
>
>> I do not have multiple wallets in Copay, just the default wallet.
>>
>> I do not have my key encrypted (it does not request a password for
>> sending funds).
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/bitpay/copay/issues/4158#issuecomment-215838885>
>>
>
>
>
> --
> Matías Alejo Garcia
> @ematiu
> Roads? Where we're going, we don't need roads!
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!
