### ISSUE TITLE
Signature rejected by server/ Response could not be verfied 

### ISSUE THREAD

**Issue by mc25** [bitpay/copay#4163]
_What platform (device) are you using? If mobile device, please tell us the brand and model of your phone. **Samsung galxy s6 edge**

What Copay version are you using? v.1.12.1
What type of wallet is? (1-1 or multisig) **2/2
**When (approximately) the wallet was created? **2 months  ago**
Do you have mnemonic backups or file export? **just the words**
Did you imported the wallet on your current device (or you created the wallet somewhere else and then you import it)? **Created and resotrored on the same device, had the same problem im reporting now so i did a reset**
Do you have a password set for your wallet?_ no

**Comment by matiu** [comment]
Thanks. Please follow the discussion here:

https://github.com/bitpay/copay/issues/4133
