### ISSUE TITLE
android version has trouble in setting "Advanced"

### ISSUE THREAD

**Issue by pgp66992e0d** [bitpay/copay#4165]
After send-max fix and update to Version 1.12.1.

While click "Advanced", jump instantly to the "Delete wallet" or "Clear cache" tasks.

**Comment by gabrielbazan7** [comment]
It works for me now. You still having this issue ?

**Comment by pgp66992e0d** [comment]
issue still remains.  my testing android is GT-19300, 4.1.2 with kernel 3.0.31

**Comment by JDonadio** [comment]
Impossible to reproduce. I tried multiple times with 2 different android devices. @pgp66992e0d if this issue still remains in your device as you say, please check the session log (after click in advanced). You can find it in Settings -> About Copay -> Session log

**Comment by pgp66992e0d** [comment]
no confidential data as below.
----
Copay Session Logs
Be careful, this could contain sensitive private data


Starting Copay v1.12.11 #2a65945
Client: isCordova: true isChromeApp: null isNodeWebkit: undefined
Navigator: Mozilla/5.0 (Linux; U; Android 4.1.2; en-us; GT-I9300 Build/JZO54K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
Using file storage: true
Route change from: -  to: walletHome
Setting default language: en
Got main dir: file:///data/data/com.bitpay.copay/files/
Profile is not encrypted
Profile read
Preferences read: {"limits":{"totalCopayers":6,"mPlusN":100},"bws":{"url":"https://bws.bitpay.com/bws/api"},"wallet":{"requiredCopayers":2,"totalCopayers":3,"spendUnconfirmed":false,"reconnectDelay":5000,"idleDurationMin":4,"settings":{"unitName":"bits","unitToSatoshi":100,"unitDecimals":2,"unitCode":"bit","alternativeName":"US Dollar","alternativeIsoCode":"USD"}},"glidera":{"enabled":false,"testnet":false},"coinbase":{"enabled":false,"testnet":false},"rates":{"url":"https://insight.bitpay.com:443/api/rates"},"release":{"url":"https://api.github.com/repos/bitpay/copay/releases/latest"},"pushNotifications":{"enabled":false,"config":{"android":{"senderID":"1036948132229","icon":"push","iconColor":"#2F4053"},"ios":{"alert":"true","badge":"true","sound":"true"},"windows":{}}},"bwsFor":{"08fbb93f-3f45-4541-8fa5-4bbf1aea345b":"https://bws.bitpay.com/bws/api"}}
Preferences read
Set focus: 08fbb93f-3f45-4541-8fa5-4bbf1aea345b
Cleaning Index Instance
Updating Transaction History
Profile loaded ... Starting UX.
Route change from: -  to: walletHome
Syncing TXs. Got:0 Skip:5  EndingTxid: null  Continue: undefined
Finished Sync: New / soft confirmed Txs: 0
Tx History synced. Total Txs: 0
onGoingProcess openingWallet true
onGoingProcess openingWallet null
Wallet Opened
Binding touchstart elements...
Writing: txsHistory-08fbb93f-3f45-4541-8fa5-4bbf1aea345b []
onGoingProcess updatingStatus true
Updating Status: test null
Tx History saved.
Starting push notification registration
onGoingProcess scanning null
Status update. hash:0 Try:0
onGoingProcess updatingStatus null
Wallet Status: {"pendingTxps":[],"wallet":{"version":"1.0.0","createdOn":1462439427,"id":"08fbb93f-3f45-4541-8fa5-4bbf1aea345b","name":"test","m":1,"n":1,"status":"complete","copayers":[{"version":2,"createdOn":1462439427,"id":"e8dff42ec561f0de64a099e5ed7d42260935fefb1b6c7f551ff5790d07528f09","name":"me","requestPubKeys":[{"key":"03cd9b964543c497f67dcaa4c760db5abcdb833d30f381f9765256f91c2db670c3","signature":"3045022100c9de73edf9cbd99e7c7a7e664f6fa49cace87a8bfc508bbd7106c76fb2ca3e5b0220694091977ba36b42af38ea292504b6bb028f7fb4e7d514bee2f899527ab51e96"}],"encryptedName":"{\"iv\":\"7DAOUJv+tZksCvBUqCay7Q==\",\"v\":1,\"iter\":1,\"ks\":128,\"ts\":64,\"mode\":\"ccm\",\"adata\":\"\",\"cipher\":\"aes\",\"ct\":\"H1P3FdtmKAnLqg==\"}"}],"network":"livenet","derivationStrategy":"BIP44","addressType":"P2PKH","scanStatus":null,"encryptedName":"{\"iv\":\"eFySkuiTA6uxBmo3M6ni2A==\",\"v\":1,\"iter\":1,\"ks\":128,\"ts\":64,\"mode\":\"ccm\",\"adata\":\"\",\"cipher\":\"aes\",\"ct\":\"qs54oTF+nLzpfvXF\"}"},"balance":{"totalAmount":0,"lockedAmount":0,"totalConfirmedAmount":0,"lockedConfirmedAmount":0,"availableAmount":0,"availableConfirmedAmount":0,"byAddress":[],"totalBytesToSendMax":0,"totalBytesToSendConfirmedMax":0},"preferences":{"version":"1.0.0","createdOn":1462439429,"walletId":"08fbb93f-3f45-4541-8fa5-4bbf1aea345b","copayerId":"e8dff42ec561f0de64a099e5ed7d42260935fefb1b6c7f551ff5790d07528f09","email":null,"language":"en","unit":"bit"}}
Route change from: walletHome  to: preferences
Route change from: preferences  to: preferencesAdvanced
Route change from: preferencesAdvanced  to: preferencesHistory
Route change from: preferencesHistory  to: preferencesAdvanced
Route change from: preferencesAdvanced  to: preferences
Route change from: preferences  to: walletHome
Binding touchstart elements...
Route change from: walletHome  to: preferencesGlobal
Route change from: preferencesGlobal  to: about
Route change from: about  to: logs

**Comment by Matiasfx** [comment]
I have this problem, on my android phone and android tablet. Any news about it?

**Comment by matiu** [comment]
@Matiasfx that android version are you using?

**Comment by Matiasfx** [comment]
@matiu 4.1.2 on my phone and 4.2.2 on tablet. thanks

**Comment by matiu** [comment]
This will be probably fixed in Copay 2.0, releasing today.

**Comment by JDonadio** [comment]
@Matiasfx @pgp66992e0d you still have this error?

**Comment by pgp66992e0d** [comment]
@JDonadio no error now
