### ISSUE TITLE
A way to have a multisig wallet with myself

### ISSUE THREAD

**Issue by lucaszanella** [bitpay/copay#4167]
Hi, the act of writing a seed on paper and store them in your house is both good and bad. If someone steal my house, all by BTC are gone. However, is I had the option to store one seed in paper, and the other one in a secure place like LastPass or in another house, I'd have much more security. I can do it if I have a wallet on my PC and another one on my Android, or even one in each user of my Android, but I wanted to be able to fastly sign transactions, thus doing it inside the copay app. For that, I'd need to be able to create a multiwig wallet and join in with the same copay app that generated it.

What do you guys think of this idea?

**Comment by dabura667** [comment]
If the only concern is where you store the backup, why not write half of the backup on one paper and the other half on another?

There is no benefit to adding this feature and many detriments.

If you are smart enough to know the ramiffications of doing what you explain, then you are smart enough to install Bitcore Wallet CLI and do it yourself.

**Comment by algesten** [comment]
you can already do this. make a 2/3 multisig wallet – i.e. you need two out of three signatures to make a transaction.

then join the new wallet with a combo of copay apps to set it up. example:

1. mac os x version
2. ios version
3. chrome app version

write down the seed of the chrome version on a piece of paper and store in your house, then delete the seed and that app. this is your backup.

now you only need any two combos to make the transactions. for regular use, you use your laptop and phone. and if something gets stolen, you have a backup.
