### ISSUE TITLE
Can't send bitcoin. 

### ISSUE THREAD

**Issue by mandarln** [bitpay/copay#4168]
I get The payment was created but could not be completed. Please try again from home screen.

I go to home screen I see the payment proposal, if I try to accept it I get Signatures rejected by server. If I delete it and start new one, I will get to the same problem.

**Comment by matiu** [comment]
This seems to be related to a bug we have in certain android 6 devices. Please see "Workarounds" at #4133 (comment)

Closing this ticket. Please continue the thread in the link.
