### ISSUE TITLE
export wallet

### ISSUE THREAD

**Issue by plurant** [bitpay/copay#4169]
Hello,

I wanted to know what happens if copay disapears someday, how will we be able to recover our wallets to another provider ? Because i can not extract the private keys.

**Comment by matiu** [comment]
You backup *is* the key. The 12 words are the seed to generated the private key. 

You can access the funds on any BIP44 compatible wallet. There is also the Copay Recovery Tool:  https://bitpay.github.io/copay-recovery/.

Finally Copay and its backend server are open source you can even host it yourself.
