### ISSUE TITLE
Add support for BIP39 Italian wordlist

### ISSUE THREAD

**Issue by HostFat** [bitpay/copay#4170]
https://github.com/bitcoin/bips/pull/306

**Comment by isocolsky** [comment]
FYI, I opened this issue https://github.com/bitpay/bitcore-mnemonic/issues/46. Once this is done, Copay will be able to support Italian language for mnemonics. Thanks.

**Comment by isocolsky** [comment]
Done! Expect this feature on the next release. Thanks.
