### ISSUE TITLE
Where do I find my wallet address?

### ISSUE THREAD

**Issue by leeroyc** [bitpay/copay#4171]
Hi, I have downloaded the Mac App and create a wallet, but where can I find my wallet address? I need to add this to genesis miner for payouts when mining. I can see my wallet ID, but I need a wallet address.

Thanks!
Lee

**Comment by matiu** [comment]
Copay shows a receiving address in the 'Receive' Tab.

You can see you wallet's addresses in Settings -> Advanced > Wallet information.

**Comment by leeroyc** [comment]
Hi, thanks. Yeah, sill my, I saw it in the bottom of the preferences for teh wallet. Works fine now. 

Thanks for the speedy reply :)



Regards,
Lee









Lee Claughton
Solution Developer
Modulus Ltd

E: lee@modulus.co.nz <mailto:lee@modulus.co.nz> | P: +64 4 282 1477 | M: +64 27 220 5040 
W: www.modulus.co.nz <http://www.modulus.co.nz/> | Skype: modulusweb | Facebook: www.facebook.com/modulusweb <http://www.facebook.com/modulusweb>
