### ISSUE TITLE
Not able to send BTC

### ISSUE THREAD

**Issue by aeryx** [bitpay/copay#4172]
I get a "Signatures rejected by server" error. 

First device, never imported wallet, 
Samsung galaxy S6, 
Android 6.0.1,  
copay 1.12.1, 
1-1 wallet

Please help!

**Comment by matiu** [comment]
This seems to be related to a bug we have in certain android 6 devices. Please see "Workarounds" at https://github.com/bitpay/copay/issues/4133#issuecomment-215945361

Closing this ticket. Please continue the thread in the link.
