### ISSUE TITLE
Speed up first boot on Windows Phone devices

### ISSUE THREAD

**Issue by cmgustavo** [bitpay/copay#4174]
First boot takes about 20 seconds in some devices with Windows Phone.

**Comment by matiu** [comment]
is this still valid?

**Comment by cmgustavo** [comment]
Yes. Tested with an old phone (Lumia 630). It takes about 30 seconds with  the new version.

**Comment by jkokorian** [comment]
Same here, on a Lumia 640XL. After it has started up it shows 'Validating wallet integrity...' forever, and appears to be loading something.

**Comment by Derrick-** [comment]
After upgrade to v2.0.1, the splash screen time is about the same as it has been, around 12 secs on Lumia 929, but as of this version the app will not respond for another 20+ secs after the UI is visible, which is a new problem.

**Comment by cmgustavo** [comment]
It has been fixed on v2.1.0. Please, upgrade to the latest version and let us know how it 's going.

Thanks!

**Comment by jkokorian** [comment]
* The 'verifying wallet integrity...' message is not there anymore.
* Still about 25 seconds before you can scroll up and down.

**Comment by bitjson** [comment]
Closing in favor of #4654 and #4705 respectively.
