### ISSUE TITLE
Could not accept payment: No enough signatures after flatten

### ISSUE THREAD

**Issue by JulianTosh** [bitpay/copay#4182]
Wallet version is 1.12.11

This is a single signer wallet. It worked fine for the first few transactions. Now when I try to send, I get 

```
Could not accept payment: No enough signatures after flatten:m/1/1 Nr of inputs:1 Nr of derived privs: 1 Signatures:
```
Once the error message appears, in the activity screen, I see what looks to be a payment proposal. If I open it, there is a blue button that says "accept". Pressing accept just redisplays the error message and the funds are reported locked. If I delete the proposal, I can attempt sending funds again but the all fail, in any amount.

I have tried clearing the transaction cache and rescanning balances.

When I attempt to import the wallet into a new device, I get "could not import: not authorized".

Fortunately, the wallet words have not been removed from the original device, so I can verify that the wallet words in the wallet match what words were originally written on the piece of paper.

**Comment by JulianTosh** [comment]
Attached is a screen shot of the error message and the inputs the wallet sees.

I tried to input the seed words into the recovery tool but it found no balances.

![whatsapp-image-20160503](https://cloud.githubusercontent.com/assets/627143/15005806/32a57c3e-117e-11e6-8afa-770faa318bab.jpg)
![whatsapp-image-20160503 1](https://cloud.githubusercontent.com/assets/627143/15005816/45c818c6-117e-11e6-824e-b75536c1a677.jpg)

**Comment by matiu** [comment]
What device are you using?

this seems to be the issue reported here:
https://github.com/bitpay/copay/issues/4133

**Comment by JulianTosh** [comment]
Samsung Galaxy Note 5
![phoninfo](https://cloud.githubusercontent.com/assets/627143/15006545/dd1c1d78-1186-11e6-9cce-f7fbd8f96cc5.jpg)

**Comment by JulianTosh** [comment]
![phoninfo2](https://cloud.githubusercontent.com/assets/627143/15006568/0298da8c-1187-11e6-82f1-7f98704bce7d.jpg)

**Comment by matiu** [comment]
Thanks @JulianTosh for the detailed info. This is definitely related to #4133

I am closing this one here, and please write me to matias@bitpay.com so we can continue the conversation.

Please send me and email and we will give you further instructions.

matías
