### ISSUE TITLE
Complete Linux desktop wallet installation instructions

### ISSUE THREAD

**Issue by john-light** [bitpay/copay#4183]
The releases page just provides a `.zip` file for Linux installation. What is the user supposed to do with this file? Complete installation instructions should be provided.

**Comment by cmgustavo** [comment]
Just `unzip` it wherever you want, and run `Copay` binary file (double click from desktop or `./Copay` from command line).

We 'll update the README with a detailed instruction soon.

Thanks!

**Comment by john-light** [comment]
@cmgustavo thanks! I did figure it out. At first the binary would not run but I got it to work. My next issue is related to #3723, I can't get the desktop app to connect to the network.

**Comment by ivanrojasorg** [comment]
I cant install bitpay walley with the Commander ./Bitpay, how install bitpay walley un Ubuntu?
