### ISSUE TITLE
Error Exporting wallet including history cache

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#4189]
If addressbook and history cache are included, the export file generated is too long to copy on mobile clipboard, so it's not possible to import the wallet with this option. The size of this json file depends exclusively of the number of txs in the history, so if there is more than ~40/50 the import is not possible. Tested on android

**Comment by matiu** [comment]
Lets make 2 switches: one for address book and one for tx history, and lets hide the tx history switch in mobile.

**Comment by JDonadio** [comment]
I think the addressbook should be included always and only ask for history cache.
