### ISSUE TITLE
Blocked money.

### ISSUE THREAD

**Issue by Craysos** [bitpay/copay#4195]
I don't know but in my copay there's writed Total Locked Balance: 319 0.14 usd

**Comment by dabura667** [comment]
It's because you are waiting on a signature.

**Comment by Craysos** [comment]
How can i deblock it?

**Comment by dabura667** [comment]
Sign or reject the pending proposal.

**Comment by Craysos** [comment]
How can i reject it?

**Comment by Craysos** [comment]
Pls i need help.

**Comment by JDonadio** [comment]
Just open the proposal and scroll down, you will see the option to delete it ("Delete payment proposal").

**Comment by Craysos** [comment]
I can't find it.

**Comment by JDonadio** [comment]
![copay_-_multisignature_wallet](https://cloud.githubusercontent.com/assets/13851807/15081732/a10f6888-139a-11e6-8897-5ccf3b71f6c3.png)
![copay_-_multisignature_wallet](https://cloud.githubusercontent.com/assets/13851807/15081749/b476ce16-139a-11e6-93ff-73223d790f6c.png)

**Comment by Craysos** [comment]
But see this.
![immagine](https://cloud.githubusercontent.com/assets/19227352/15081794/ca7648c0-13c4-11e6-9e6b-c34e066173c3.png)

**Comment by JDonadio** [comment]
@Craysos try to tap on that unsent tx in order to open the tx detail. As you can see in the screenshots above.

**Comment by Craysos** [comment]
![asfwe](https://cloud.githubusercontent.com/assets/19227352/15082312/61edb8da-13c7-11e6-9d90-401dfc6aaad6.png)

**Comment by JDonadio** [comment]
Please, try updating the Copay version. Unfortunately in that version the option to delete proposals is not available.

**Comment by Craysos** [comment]
Ok! resolved thank you very much donadio!

**Comment by JDonadio** [comment]
Great!
