### ISSUE TITLE
Transparency (No New Address for each Transaction)

### ISSUE THREAD

**Issue by SirWagginston** [bitpay/copay#4197]
Hi there,

I'm the founder of CoinFest (www.coinfest.org), a major cryptocurrency event and the first decentralized conference for fintech. We had been using the blockchain to track all of our finances so that we could be fully transparent to the public, our donors and sponsors in our claims of being non-profit with no overhead.

Unfortunately, CoinKite went down so now we're using Copay, which required us to reduce our signatory count from 15 to 6. More concerning, though, is that we cannot turn off the feature that creates a new HD address for each transaction... we're not trying to achieve privacy, and this has damage the Transparency System we showcase at www.coinfest.org/transparency

I'm sure you guys are very busy, and I know this is a free service, but is there any way you could make that privacy feature optional? We would be very grateful, aiding us in our quest to spread cryptocurrency adoption worldwide.

Thanks,
Andrew Wagner
a.j.wagner.89@gmail.com

**Comment by dabura667** [comment]
You can continue to use the same address, and it will continue to manage funds in your copay.

The only problem is that you can no longer view your first address within the Copay UI after you have used it once.

As long as you know that first address, you can continue to use it and spend money that comes into it with no problem.

Also, you can confirm which addresses you have used in the past (and those that have current balance) in the wallet advanced details menu.

Thanks!

**Comment by dabura667** [comment]
Also, for the 15 signatories... This is limited on the server side... but when I looked at it right now, I think the person who created this limit was mistaken.

I have submitted a detailed issue to the server side repository, and perhaps in the next couple of versions maybe it can be supported.

Please follow https://github.com/bitpay/bitcore-wallet-service/issues/505 for more info.

**Comment by SirWagginston** [comment]
That would be awesome for organizations like CoinFest if you allowed more
signatories... supposedly 15 is the maximum possible before the
network/protocol acts up.

We're going to keep looking for a solution allowing us to keep all funds at
a single address, however, for accounting purposes. We have to list
everything at http://www.coinfest.org/transparency/, and you can see how
this will become more difficult both for me to web design and for members
of the public to sort through.

Sorry if this is an unusual request... the blockchain is just as good for
transparency as it is for privacy, however, if not better, and non-profits
like ours use it for that.

**Comment by dabura667** [comment]
I'm sorry, @SirWagginston I think you only read my second post. My first post stated that you CAN use one address if you want.

**Comment by SirWagginston** [comment]
Yes, but when we issue a transaction, it sends all the change to a new
address, so it is impossible to actually keep all of our funding in the
original address in practical everyday use. Or is there a way to turn that
feature off?

**Comment by matiu** [comment]
You can use a blockexplorer that let you input a extended public key, to report to the community, like:

https://blockchain.info/xpub/xpub6AoynT2YixgjHK2yNTDPJGmbFaNfiKTVNb4zVygVmSfhWktotj8woL2nT7FALSFEhggNemiy5KEGWxRpNYtsHVVvWCC99WuhzvAvZTJD1SH

Of if you are using Copay's Desktop version you can go to   Settings > Advanced > Transaction History and export a CSV with all the transaction history and publish that in the webpage (maybe so some preprocessing before). The Transaction History will show TX's notes and TXID in the blockchain.

**Comment by SirWagginston** [comment]
Hmm, the public key thing is actually a good idea. How do I find ours?

It would be simpler for everyone if we could just turn the privacy feature
off, though. We're looking for workarounds to an easy problem, right now

**Comment by matiu** [comment]
done in Copay 2.0

**Comment by SirWagginston** [comment]
What is done? You mean that I can disable the change addresses so all
change is returned to the sending address?

**Comment by isocolsky** [comment]
At wallet creation time you can choose to reuse a single address. This address will be the same for both receiving payments and sending tx change.

![image](https://cloud.githubusercontent.com/assets/2073468/15930020/f7d139d4-2e26-11e6-9302-84685bbc3eba.png)
