### ISSUE TITLE
SolarCoin support

### ISSUE THREAD

**Issue by nickgogerty** [bitpay/copay#4203]
Just curious if Copay is going to support solarcoin   www.solarcoin.org  We have some big projects under the hood at www.electricchain.org including micro-grid finance in Africa and collaborations with MIT medialab, NASA underway etc.

**Comment by pgp66992e0d** [comment]
Interesting but ironically. blockchain technology by design uses a lot of electricity.

**Comment by matiu** [comment]
Thanks for your interest in Copay. For the moment we dont plan to support Solarcoin, but since Copay is opensource it is possible to fork it and adapt it. Some  alt coins have done that already.

**Comment by nickgogerty** [comment]
thanks.  We may do a fork of the wallet.  We have Coinomi under development
as well.

Just FYI we use a POST algo vs. POW. estimates that are that it uses
250-300 times less energy per transaction at full capacity vs. bitcoin.

the model is online if interested and a white paper is available.

https://docs.google.com/a/solcrypto.com/spreadsheets/d/1QzIA5Nd3pVRGn2c48Oc_dqpImrOfYlwp74UzHXjArdE/edit?usp=sharing

best,

Nick Gogerty

Portfolio manager, analyst <http://thoughtfulcapital.com/> & Author: The
Nature of Value <http://thenatureofvalue.com/> How to invest in the
evolutionary economy.

+1.858.366.8674
linkedin:Nick Gogerty
<http://www.linkedin.com/inviteFromProfile?from=profile&key=654408&firstName=Nick&lastName=Gogerty>
skype:nickgogerty7166
Greenwich, CT
