### ISSUE TITLE
copay multisig business logic question

### ISSUE THREAD

**Issue by pgp66992e0d** [bitpay/copay#4204]
hihi, kindly hint me if i am wrong.

By my testing with copay multisig feature, take an example of a 2-of-3 address it is:
1. the first person to create in "create new wallet" by choosing 2-of-3
2. the first person pass the invitation to the second person to join
3. the first person pass the invitation to the third person to join

In this way, the first person can control who are the real persons behind the 2-of-3 address.  But things shall be symmetric, meaning that, the three persons are willing to be joined because they know who else are (at least in the sense of bitcoin address).

Ideally and fictionally, the first person is a staff and the second person is his boss and the third person supposed to be the general manager.  What-if the third person is someone the second person is not willing to be the copayers (may be a scam of the staff) ?

**Comment by isocolsky** [comment]
You are right there is an inherent asymmetry in the initial creation of a multi-sig wallet. But IMO, these issues need to be addressed by off-channel communication. Either an email, IM or a phone call between copayers sharing the first 4 digits or so of the wallet ID (available at Preferences -> Advanced -> Wallet Information) should do the trick.
