### ISSUE TITLE
ios shows 2 addresses on receive tab

### ISSUE THREAD

**Issue by XBTdev** [bitpay/copay#4207]
My friend installed copay on his iPhone and its showing 2 addresses on the receive tab.

When he taps the qr code it also copies the entire string of two addresses to the clipboard.
![702218895_3222910038724619939](https://cloud.githubusercontent.com/assets/3032137/15165512/18208596-16cb-11e6-809a-c2f4241b1ec3.jpg)

**Comment by JDonadio** [comment]
Hi @XBTdev, we had an issue like this once. Please try to generate new addresses and check if the problems remains.

**Comment by XBTdev** [comment]
> Hi @XBTdev, please try to generate new addresses and check if the problems remains.

That worked. Thanks.

**Comment by JDonadio** [comment]
We had the same issue a time ago but was an isolated case. If the problem is solved please close this, anyways we'll take a look again this issue.
