### ISSUE TITLE
Multiple wallet issue with signing

### ISSUE THREAD

**Issue by ChrisiJm** [bitpay/copay#4208]
Hi,
I am using a multiple wallet with 4 users, where 3 of them are currently unable to sign the transactions due to deleting the accounts on the devices. These devices are not in use anymore. My problem is, that only I can sign a transaction, but you need at least 2 devicecs to sign a transaction. Is there a way to fix this issue? Or can you delete the other three devices so I can pay alone?

**Comment by isocolsky** [comment]
If you have access to all 4 backups (12 words or export files), I would recommend you use the [Copay recovery tool](http://bitpay.github.io/copay-recovery/) to move funds to a new 1-of-1 wallet that will only require your signature.

**Comment by isocolsky** [comment]
Just to clarify: there is nothing that can be done server-side to help you with this. Private keys are held by copayers on their devices and are never shared with the server. If access to the devices is not possible for whatever reason, backups (which are mandatory on Copay BTW) should be used to restore access to the wallet.
From your post I guess yours is a 2-of-4 wallet. If you are able to get one of the other 3 backups (either as a 12 word phrase or as an export file) you could use that to import the wallet in a separate device and that would also allow you to transfer the funds.
