### ISSUE TITLE
Lost a motherboard, had to move HD to another PC now what?

### ISSUE THREAD

**Issue by rileyjalexander** [bitpay/copay#4216]
How can I go about importing my Copay wallet information off of my old HD? I had a paper backup of the seed phrase somewhere, I am sure it will turn up, but for the time being, whats the easy way to do this if I have the drive and all files in tact???

**Comment by dabura667** [comment]
What version were you using?

1. The Chrome Extension
2. The Installable Version

Also, what is your operating system? Windows 7? 10? Mac OSX? Linux? (Ubuntu?)

**Comment by rileyjalexander** [comment]
Windows 8. Installable version

**Comment by dabura667** [comment]
`C:\Users\USERNAME\AppData\Local\copay\Local Storage`

Do you have files in here with the file type `file__0.localstorage` etc?

Tell me how many files you have.

**Comment by dabura667** [comment]
the easy way to move from one PC to other is to reinstall on new PC and copy over the contents of that folder.

This will delete any existing wallets on your new computer if you have created a new wallet on the new computer.

**Comment by dabura667** [comment]
I wrote a python script to convert localstorage file into a plain text file where you can view your credentials. 1. Save this to a file called xxx.py (xxx is whatever) then run from command line prompt as:

`python xxx.py file__0.localstorage`

Assuming you are cd into the folder with both the python script, and the localstorage file, and you have python installed on your system.

```python
import sqlite3, codecs, sys

db = sqlite3.connect(sys.argv[1])
c = db.cursor()
c.execute('SELECT value FROM ItemTable WHERE key = "profile"')
blob = c.fetchone()
blob = str(blob[0]).decode('utf-16le')
with codecs.open("output.txt","wb","utf-8") as f:
    f.write(blob)
    f.close()
```
