### ISSUE TITLE
New release of copay no longer works with windows

### ISSUE THREAD

**Issue by adamcleary555** [bitpay/copay#4217]
Error: "The version of this file is not compatible with the version of Windows you are running. Check your... "

I am running Windows 7 32-bit  - is there another version I can install?

Can I use an older release to get the wallet working again?  And then move it.

Thanks

**Comment by JDonadio** [comment]
Hi @adamcleary555, you can run Copay in Chrome version from [here](https://chrome.google.com/webstore/detail/copay/cnidaodnidkbaplmghlelgikaiejfhja?hl=es-419l)
