### ISSUE TITLE
Coinbase

### ISSUE THREAD

**Issue by lf60** [bitpay/copay#4218]
I have a Coinbase account
How can I connect to this account from Copay Mobile App in order to buy/sell bitcoin ?
Thanks in advance
Best regards
Ludovico Ferrara

**Comment by cmgustavo** [comment]
Hi @lf60 , It 's simple. First review your global preferences if you have enabled *Coinbase Service*

![copay_-_multisignature_wallet](https://cloud.githubusercontent.com/assets/237435/15323874/57b5a7aa-1c1a-11e6-9486-4439e2539b00.png)

After that, click on *Buy And Sell*

![copay_-_multisignature_wallet](https://cloud.githubusercontent.com/assets/237435/15323904/73b18244-1c1a-11e6-9939-e436a8841f3b.png)

![copay_-_multisignature_wallet](https://cloud.githubusercontent.com/assets/237435/15323913/88461a30-1c1a-11e6-9386-70753408a5cf.png)

![copay_-_multisignature_wallet](https://cloud.githubusercontent.com/assets/237435/15323928/949fee96-1c1a-11e6-929c-351e505c021c.png)

Finally, click on *Connect to Coinbase* will open the browser in coinbase.com asking for your email and password. After authorise Copay to connect with Coinbase, you will be redirect back to Copay:

![copay_-_multisignature_wallet](https://cloud.githubusercontent.com/assets/237435/15324062/37c72166-1c1b-11e6-949e-48734ed341af.png)

I hope to have been clear with the explanation. Let me know if you need more help.
