### ISSUE TITLE
Glidera purchased Bitcoin sent to Bitpay but I can't find them

### ISSUE THREAD

**Issue by Densequera** [bitpay/copay#4219]
I purchased Bitcoin through Glidera a while back. Can't quite seem to locate where I sent it to. I believe I sent it to Bitpay. How do I find it?

**Comment by Densequera** [comment]
Anyone???

**Comment by matiu** [comment]
All outgoing transactions are shown on your wallet transaction history (Activity on the main Copay page). Check if the transaction is there.  Note that the bitcoins are *never* sent to Bitpay.

**Comment by Densequera** [comment]
Thanks for feedback. I must of sent them somewhere I can't recall. is there a way to find out where? Can I retrieve them somehow?

**Comment by matiu** [comment]
Please see my answer above. all transactions are shown on wallet's activity.

**Comment by Densequera** [comment]
How do I obtain private key with my Bitcoin address
This is the address 18jns8aAE94BZWsu59Gvb73nEB7ECV3tSp

**Comment by matiu** [comment]
For the latest comment, please check a tool like https://dcpos.github.io/bip39/
