### ISSUE TITLE
Send to multiple addresses

### ISSUE THREAD

**Issue by gabegattis** [bitpay/copay#4223]
Copay can only generate transaction proposals for sending to a single address (a single non-change output really). BWC/BWS can create transaction proposals for sending to multiple outputs, and Copay can sign them, but Copay cannot create these proposals itself.

This is a pretty fundamental feature for any Bitcoin wallet, IMO. The lack of this feature makes testing difficult for me, and I have to either use a different wallet or use BWC directly to satisfy such requirements. It also forces the user to create multiple single-output transaction proposals when just one multi-output proposal would do, thus potentially locking up extra funds unnecessarily.

**Comment by dan-da** [comment]
agree

**Comment by ajp8164** [comment]
Copay is already hard to use and is getting more difficult for the average person.  Many of the "advanced" features of Copay should be buried in a "developer mode" that is off by default.  If this feature can't be 100% transparent to "I wan to send a payment" then it too should be buried in a "developer mode".

**Comment by braydonf** [comment]
A simple "+" to add additional recipients I don't think would cause confusion *(in the case that the features isn't needed)*. This could also be useful for payment protocol that can specify multiple outputs by specification.

**Comment by gabegattis** [comment]
+1 what @braydonf said. Bitcoin Qt has a button with a "+" icon on it that says, "add recipient". It is simple, elegant, and obvious.

**Comment by ajp8164** [comment]
After you add a recipient how does Copay know how much money to send to each recipient?

**Comment by gabegattis** [comment]
Presumably it would work like Bitcoin Qt and simply display an extra field for address/amount for the additional recipient.
![bitcoinmultisend](https://cloud.githubusercontent.com/assets/4419243/15376335/65ff4a92-1d22-11e6-8435-98c9dbb01eec.png)

**Comment by ajp8164** [comment]
Recipient name [required]
Amount [required]
Label/memo [optional]

Should be able to toggle amount between bitcoin and wallet alternative currency.

All other rules (if any) are picked up from wallet config.

**Comment by dabura667** [comment]
I agree that UI should not be cluttered, but adding a little plus icon below the wallet icon (for selecting other wallet) won't clutter up too much.

+ 1

**Comment by dan-da** [comment]
Ideally it would show the total amount somewhere.  Eg: if I send 1 BTC each to Bob, Sally, and Sue, then somewhere I should see Total 3 BTC.

I don't see that in the bitcoin-qt screenshot.  not sure if it does it or not.

**Comment by matiu** [comment]
Agree on @dan-da  that the total must be shown if we implement this feature.

Note that the 'send-max' feature need to be defined. How it will work with multi outputs?  @isocolsky pointed out that in multisignature, shared ownership wallet, multioutput could be important at the end of a wallet life cycle: Return part of the funds to each owner, in a single transaction.

**Comment by ajp8164** [comment]
If send max is chosen then the amount for each recipient may need to be adjusted after a proposal is created.  Can you adjust a proposed tx after it's been created?

**Comment by ajp8164** [comment]
Thinking through this there are many "fearures" that can be layered here.  I suggest doing exactly what Bitcoin core does and enhance later.  Keep it simple for now.

**Comment by KeyJockey** [comment]
Much like my proposal for advanced miner fee control, seems to me that keeping the basic UI simple and clean for *most* users is essential BUT adding some extra advanced functionality for experts is very necessary too.  

If the overall SETTINGS preferences (or maybe per-wallet) had tick-boxes for enabling these advanced elements only by users who really want and need them, we can have it both ways :smile:  

I think it's not too much to ask of advanced users to go and flip a switch to get the extra powerful features we need to become visible, but otherwise keep 'em HIDDEN from MOST users, by default.

**Comment by martyzigman** [comment]
I concur.  I regularly send transactions to multiple people as I use btc to pay for services on a regular basis.  It's natural to constitute a single transaction for multiple recipients as I also reference the accounting in the same manner. Copay needs this capacity.

**Comment by Derrick-** [comment]
> Note that the 'send-max' feature need to be defined. 

I suggest to show the "Send max" button only on the bottom item, and if clicked it assigns the remaining balance to that recipient. 

I understand this might complicate the code a little bit, but from a user perspective I think it makes the most sense.

**Comment by msaggiorato** [comment]
I agree, this is now more important than ever now that the miner fees are actually high in terms of fiat value.

It actually helps saving by bundling several transactions into one. I hope this is in the roadmap somewhere soon.

**Comment by o-ayoub** [comment]
please, any solution for that ?

**Comment by gabrielbazan7** [comment]
https://github.com/bitpay/copay/pull/9289

**Comment by dabiellevargas** [comment]
where i can downlod this software
