### ISSUE TITLE
Transparency Feature. 0.5 BTC bounty

### ISSUE THREAD

**Issue by 21xhipster** [bitpay/copay#4225]
Everybody Hi!
We love to use Copay and it seems that there are no alternatives for us now.
What we don't love in Copay is the absence of a simple transparency feature.

All that buzz around blockchains is always touch a transparency topic. But when we build apps we forget about this. Issues #3130 #1159 #981 #4197 (this is not exhaustive list though) prove that people need ability to opt-out of privacy if they run public money. 

I fail to find any way to practically use xpub for this purpose. And to be honest I don't want to. What we want is a simple switcher for every wallet **enable transparency**. If it turned on change is always goes back to sender address and new addresses are not generated after every transaction.

I will list some use cases than transparency is mandatory:
- Crowdsales
- Private Equities
- Foundations
- Donations

We don't have enough competence to wrap what we want in pull request rapidly. That is why we (from SatoshiFund and cyberFund) assign small bounty for those who deliver us this simple and neat feature: 0.5 BTC. Without it we cant deliver awesome user experience for our purposes. Thanks!

**Comment by lomashuk** [comment]
+1

**Comment by 21xhipster** [comment]
I add $50 bounty more to be visible on bountysource

**Comment by matiu** [comment]
Thanks a lot for offering a Bounty for this feature.

Some comments about how this could be implemented:
1) There should be an `advanced` setting with a toggle activating this feature
When active:
 2) new addresses should not be created after receiving funds (see walletHome.js controller)
 3) transactions proposals should specify the changeAddress to the same wallet address (no sure if that is implemented already on BWS/BWC, but should be simple to do it)

**Comment by dan-da** [comment]
@matiu  I took a look at server.js in bitcore-wallet-service.  It seems that changeAddress is not presently supported as an argument.

The attached patch is a start.  It doesn't do any validation of the incoming changeAddress and also I'm not inclined to run BWS locally so this has not been built or tested.

Still, if your team can get it working in BWS somewhere I can access it then I'll take a look at the CoPay side... 

[txCreate.patch.txt](https://github.com/bitpay/copay/files/273386/txCreate.patch.txt)

**Comment by ajp8164** [comment]
I like this thread :-)  Bitcoin is it all about privacy.  Security and convenience are just as (if not more) important than security.  +1 for this.

**Comment by vitalylvov** [comment]
I confirm the need for this feature!

**Comment by dan-da** [comment]
any comment on the above patch?   Should I submit it as a BWS pull request?

**Comment by 21xhipster** [comment]
@dan-da I do not sure that I personally can. Maybe @tomarcafe can help?

**Comment by 21xhipster** [comment]
Cool! 2 questions:
1. Do I understand correctly that we should assign bounty to @gabrielbazan7?
2. When the feature will be in production to test it out?

**Comment by dabura667** [comment]
I believe @gabrielbazan7 is an employee of Bitpay, sooo idk what they decide on that.

You should view this as "Bitpay resolved the issue for me" and assign the bounty to whomever they see fit. (Or they might refuse it, idk)

**Comment by matiu** [comment]
@21xhipster 

1) @dabura667 is correct. @gabrielbazan7 is a BitPay employee, so, thanks a lot for the bounty, but we dont think it applies in this case. Have a beer for us and please keep letting us know useful feature for Copay

2) The feature will be bundles in Copay 2.0, scheduled to be submitted to the stores this week (the actual release dates depends on many factors, expect ~1week)

**Comment by matiu** [comment]
BTW, the feature was labeled 'single address wallets'. And it is only selectable on wallet creation.

**Comment by 21xhipster** [comment]
@matiu Thanks so much!

**Comment by matiu** [comment]
@dan-da Sorry we missed you patch. We decided to implement this as a wallet feature, so it will be transparent for Copay. If any copayer tries to generate and address, it will always return the same. This is also needed for refund address in payment protocol.

**Comment by dan-da** [comment]
@matiu -- I'm just glad it got done, thx.
