### ISSUE TITLE
calculo de comision

### ISSUE THREAD

**Issue by Ruso74** [bitpay/copay#4226]
tengo bitcoins en mi wallet, necesito pasarlos a una cuenta internacional de satoshitango para fondear una tarjeta visa prepaga. en satoshi tengo que ingresar el monto en dolares y me calcula cuanto tengo que transferir en bitcoins pero al colocar ese valor en la wallet, se le adiciona el monto de la comisión, lo que hace que los valores no coincidan y satoshi me rebote la operación.
Como puedo hacer para calcular el valor cierto a transferir para satoshi?

**Comment by dabura667** [comment]
1. https://bitcoinfees.21.co/api/v1/fees/recommended
2. fastestFee (ahora 60) x tamaño de transacción en bytes = comision en satoshis

Así que con el fin de calcular la comisión adecuada, se debe asumir que una transacción media es de alrededor de 260 bytes. Así 60 x 260 = 15600 (0,000156 BTC)

Lo multiplicamos por 2, y obtenemos 0.000312 BTC (que actualmente es de $ 0.14 USD)

Si usted tiene esta cantidad adicional, entonces lo más probable es que tenga suficiente, pero esto no da cuenta de la diferencia en las tasas de cambio en diferentes sitios web.

Yo recomendaría la compra de $ 1 o $ 2 extra, por si acaso.

**Comment by matiu** [comment]
Grande @dabura667 ! No sabía que también hablas español!

@Ruso74 si por comisión te refieres al % que cobra satoshi tango... entonces creo que es un problema de ellos, ellos deben decirte el importe exacto a transferir.

En Copay, el que envía "paga" el fee de bitcoin. Es decir, si tu envías 1234,  y el fee es 10, se descuentan de tu balance 1234+10= 1244, por lo que el receptor recibe exactamente 1234. No debería haber problema allí.

De paso te comento que usamos satoshitango diariamente sin problemas!

**Comment by Ruso74** [comment]
Hola Matías, pensé que lo que estaba generando el error era el fee de Copay. Porque a mi satoshi me muestra el numero exacto que tengo que transferir y cuando lo coloco en la wallet al momento de confirmar la operación se suma ese fee por lo cual cambia el numero. Entonces entendía que eso generaba el error. Voy a intentar de nuevo.
