### ISSUE TITLE
help

### ISSUE THREAD

**Issue by mhaynie** [bitpay/copay#4228]
using copay app on phone on wallet side showed 381  go to insight an see all my coins or usd how to get it to wallet?    thanks mark                                   

   email     haynie558@gmail.com

**Comment by matiu** [comment]
Hi,

Could you explain the issue with more detail? Maybe adding some screenshot will help.

thanks.

**Comment by mhaynie** [comment]
it is not transfering  insight  to my copay wattet

**Comment by matiu** [comment]
What "transferring insight" means? Insight is not a wallet, it just shows that state of the blockchain.

**Comment by mhaynie** [comment]
OK that helps I can see a lot bits or USD on the insight side how would you
get it to show copay side                 any help I would thank you  very
mu ch
On May 20, 2016 1:55 PM, "Matias Alejo Garcia" <notifications@github.com>
wrote:

What "transferring insight" means? Insight is not a wallet, it just shows
that state of the blockchain.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/bitpay/copay/issues/4228#issuecomment-220690049>

**Comment by mhaynie** [comment]
if it is in insight how should be to my wattet ?


Thanks Mark

**Comment by mhaynie** [comment]
https://powtoken.com/index.php?ref=POW55395
Thanks Mark
