### ISSUE TITLE
code address has changed and I have not received my payment‏

### ISSUE THREAD

**Issue by joshrage** [bitpay/copay#4238]
Good afternoon , I installed the application recive took the code applied this code on the website where I would get 12470 BTC they sent when I opened the app my code again had changed this 1G3mLC4nC1rHuf7SzbRLWvWLcXBmYkqEzU

for that here 19zz9L6eZTPJVjpA8oomKtCxhGESHxN7EL

and now I'm running out of my payment for your application to change the address?

**Comment by dabura667** [comment]
Copay manages all the addresses in the background. You can view them in the advanced wallet menu.

If you haven't received the payment, there was something wrong with the person who sent it to you. (maybe some virus changed the address that the other person input into their wallet or something)

**Comment by joshrage** [comment]
good day , the question is next came an email saying that was sent to me 12470BTC but the application only shows 127BTC in advanced wallet information 're the code and 12470BTC value but in the same application only shows 127BTC and when I 'm going to buy something speaks not I have enough value

**Comment by joshrage** [comment]
http://btc.blockr.io/address/info/1G3mLC4nC1rHuf7SzbRLWvWLcXBmYkqEzU link transacion

**Comment by dabura667** [comment]
I understand your confusion.

The site must have said to you 12740 SATOSHIS.

It looks like you are using a faucet of some sort (it was paying out small amounts to many many people) and faucets, because they pay so little, usually count in SATOSHIS.

1 BTC = 100000000 SATOSHIs
1 BTC = 1000000 BITs (or μBTC)
1 BTC = 1000 mBTC

You received 0.0001247 BTC, which is 12470 Satoshis.

**Comment by joshrage** [comment]
I took 2 prints with the application of the cell showing the value I received as I can send to you ?
![13227218_1003094709772988_8480486410695930539_n](https://cloud.githubusercontent.com/assets/19500844/15449187/0809aa90-1f4d-11e6-9748-996e409caff1.jpg)
![13267903_1003094799772979_1690409003517601260_n](https://cloud.githubusercontent.com/assets/19500844/15449188/081ad6f8-1f4d-11e6-9cd3-e02dc8012212.jpg)

**Comment by matiu** [comment]
it is 0.00012740 BTC
witch is equivalent to 127 bit (1,000,000 bits = 1BTC).

**Comment by dabura667** [comment]
Oh, I think I know what you mean:

When Copay displays the BITS unit, it hides the decimals. So 127.4 BITS is shown as 127 bits.

0.4 BITS is so small, you will definitely use it all up in fees, so Copay doesn't bother showing it to you... but it's there. Don't worry.

**Comment by gabrielbazan7** [comment]
@joshrage on the side bar you could go to "Preference Global" -> "Unit" and change the unit of your balance to BTC.
