### ISSUE TITLE
[META] I wonder if there's anything we can do about non-bug-related issues

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#4239]
New people who follow this pattern:

1. Don't understand Bitcoin at all
2. Run into one of the more confusing elements of Bitcoin.
3. Think it is a problem with Copay.
4. Talk about it here
5. Someone has to explain why it is not a problem.
6. Repeat.

The problem is exacerbated when the person doesn't know English very well. (Spanish and Japanese may be ok, but sometimes... it's hard to understand what's going on.)

I would like to brainstorm ways to lessen this problem.

Suggestions:

1. FAQ guide somewhere?
2. Add visible "Questions? Need Help?" link to send to FAQ.
3. "If you still don't understand what's going on, ask here:" and link them to some non-github place where they can ask people who are versed in Bitcoin, and maybe known about Copay. (Do we have a slack? Or a slack-ish chat thing that people pay attention to?)
4. In the FAQ have a question saying "What if I noticed a vulnerability/bug?" and clarify in the answe that "Only bug reports go here" and link github.

**Comment by matiu** [comment]
Great Idea,

I this a FAQ will be a great start:

 - Why my address changes?
 - Do I still own old addresses?
 - Do I need to backup my wallet many times?
 - etc.

Thanks.  We will start it next week.

**Comment by gabrielbazan7** [comment]
https://github.com/bitpay/copay/wiki/COPAY---FAQ. Just started this Copay FAQ. Feel free to make any suggestions.
