### ISSUE TITLE
Network Error Repeatedly

### ISSUE THREAD

**Issue by Gerbilz** [bitpay/copay#4241]
Hi All,

Wondering if anybody gets the Network Error consistently on their blitzpay wallet. Doesn't seem to be able to load anything. Any ideas? Thanks.

Jeff

**Comment by JDonadio** [comment]
Hi @Gerbilz, we had no problems with network connection. Regarding blitzpay wallet, unfortunately we are not able to give you support for that.

**Comment by matiu** [comment]
You can check the BWS status at http://stats.pingdom.com/dm8bfk2t3v6b/1640644
