### ISSUE TITLE
"Uncaught TypeError: window.Notification is not a constructor" on Android

### ISSUE THREAD

**Issue by mpolci** [bitpay/copay#4242]
In the log I noticed this error. It happens on Android device when receiving a transaction but Copay is in background (I opened it then I switched to a different wallet to send to the copay wallet some bitcoins).

The problem is described here https://developers.google.com/web/updates/2015/05/notifying-you-of-changes-to-notifications in the "Android Notifications" section.

**Comment by mpolci** [comment]
The error is originated in the notification.js file: https://github.com/bitpay/copay/blob/master/src/js/services/notifications.js#L229

**Comment by gabrielbazan7** [comment]
Thanks a lot. I think that code is old, we handle mobile push notifications with _phonegap-plugin-push_. That needs to be removed, but let me consult first.

**Comment by gabrielbazan7** [comment]
That part of the code is for desktop notifications when the app is minimize.
Mobile app should not enter to that _if_.
