### ISSUE TITLE
transation not yet confirmed, why?

### ISSUE THREAD

**Issue by joepadilha** [bitpay/copay#4248]
i've been sended bitcoins but in my wallet the status for this transation still "unconfirmed", my fees configuration is on normal, what's happend?

ty

**Comment by joepadilha** [comment]
my wallet number in copay

1DuM2rqfx3E9bSQWEy4DEMi4R4aguSxgy6

**Comment by joepadilha** [comment]
there the link:

https://insight.bitpay.com/tx/b271818b1eb137c54712e1dadabc8081a6378466f069cfec72da95538b3ab607



why is INPUT UNCONFIRMED?

**Comment by dabura667** [comment]
The network is congested. If you want to get confirmed quickly, change the fee setting to "Priority"

**Comment by matiu** [comment]
The funds you are trying to spend were not yet confirmed. Until they are confirmed, you TX will no be confirmed also.

By default Copay uses unconfirmed funds to create outgoing transactions. You can change that behavior  in settings.

**Comment by isocolsky** [comment]
The tx is confirmed now.
