### ISSUE TITLE
SCAMED depoist

### ISSUE THREAD

**Issue by joepadilha** [bitpay/copay#4250]
hi, i want 2 know if there is anyway to vindicate my bitcoins deposited, i have all proofs of payment and of the scam

**Comment by gabrielbazan7** [comment]
Hi ! I'am sorry but there is nothing Copay can do for you because bitcoin transactions cannot be reversed.

**Comment by JDonadio** [comment]
Hi @joepadilha, as @gabrielbazan7 says there is nothing that Copay can do in this case. Please check the disclaimer section in Copay, Settings > About Copay > Terms of Use.

**Comment by matiu** [comment]
It would be nice if you can comment about the details of the scam, so other users could learn from it.
