### ISSUE TITLE
problem migrating multiple accounts from Mycelium

### ISSUE THREAD

**Issue by dooglus** [bitpay/copay#4251]
I'm using the copay google chrome extension, and trying to access my Mycelium wallets.

I successfully imported the first Mycelium account by typing the 12 seed words and using the default m/44'/0'/0' derivation path.

When I went to import the next Mycelium account, using the same 12 seed words and derivation path m/44'/0'/1' I got an error message:

> Error creating wallet: Key already associated with an existing wallet

Is it not possible to have two wallets using the same seed words but different derivation paths?

I even tried deleting the first wallet, hoping that would allow me to import the 2nd one, but I still get the same error. It's as if something wasn't really deleted.

**Comment by isocolsky** [comment]
Hi, I think maybe you are trying to create a wallet that already existed at some point in the server. Could you please try to import (instead of create) the wallet using the seed and the m/44'/0'/1' path?

**Comment by dooglus** [comment]
OK, that seems to work. It's a little confusing that if I 'create' and then 'delete' a wallet I can't 'create' it again, but have the 'import' it the second time instead. Even the first time is really an 'import', since it was originally created by Mycelium, not Copay.

**Comment by isocolsky** [comment]
Yes, I agree. There is already an open issue related to deleting a wallet. Currently it is only deleted from the device but the server keeps the wallet record. About your last point, I agree the wording is not 100% clear but there are three main scenarios and it is hard to describe them with simple terms. To clarify:

1) Wallet creation. This means a new wallet is created in the server.
2) Wallet import. The wallet already exists in the server but the user wants to gain access from a new device.
3) Wallet re-creation. The wallet existed in *some* server instance (maybe a private server) and the user has access to the wallet in their device but would like to point to a different server instance where the wallet currently does not exist.

**Comment by dooglus** [comment]
I would suggest that the user shouldn't need to know about the fact that the server has wallets created on it. Most users won't even realize that there *is* a server.

When I give my seed words to the client, the client should figure out whether the wallet exists on the server or not, and 'create' or 'import' it as appropriate. I don't see why the user needs to be aware of the distinction.

**Comment by matiu** [comment]
Closing this one since it is resolved. Thanks for you feedback and try to explain better import/create options on the interfase.
