### ISSUE TITLE
Stuck updating wallet on All platforms (Mac, iOS)

### ISSUE THREAD

**Issue by holographics** [bitpay/copay#4252]
Hi, have all my funds locked. App stays stuck updating most of the time. Or throws an error saying "Could not update Wallet : Insight Error"

Need to recover these funds, please advice. I have the phrase and a json backup..

thanks,

Nicolas

**Comment by XBTdev** [comment]
Seems like insight server is down

**Comment by dabura667** [comment]
Server's down. Post pony pics.

**Comment by LinadD** [comment]
There is an alternative server's URL?

**Comment by matiu** [comment]
We had some problems with the Bitcore Wallet serivice hosting. We are very sorry with the inconveniences. it should be OK now.

See https://status.rackspace.com/

thanks.
