### ISSUE TITLE
I can't to open my wallet

### ISSUE THREAD

**Issue by Al123qaz** [bitpay/copay#4253]
"Error at Wallet Service: Insight Error"

**Comment by LinadD** [comment]
What happen - "Insight Error"?

**Comment by Al123qaz** [comment]
I can't to update my copay wallet - "Error at Wallet Service: Insight Error"



respond.175248@gmail.com
 
From: LinadD
Date: 2016-05-27 07:53
To: bitpay/copay
CC: Al123qaz; Author
Subject: Re: [bitpay/copay] I can't to open my wallet (#4253)
What happen - "Insight Error"?

**Comment by Al123qaz** [comment]
I can't to update my copay wallet - "Error at Wallet Service: Insight Error"

**Comment by sweetppro** [comment]
same thing here...

**Comment by thumbender** [comment]
So what is Insight Error and how do we prevent it in the future?

**Comment by LinadD** [comment]
There is alternative server's URL?

**Comment by Al123qaz** [comment]
WALLET SERVICE URL https://bws.bitpay.com/bws/api

**Comment by jaysander** [comment]
i am also having this problem right now please help. i am using the copay wallet for andriod its up to date too. please i am in fear for my coins

**Comment by LinadD** [comment]
Now that URL don't work

**Comment by jaysander** [comment]
i was in the middle of looking at my stuff any everything goes down

**Comment by webdevly** [comment]
Seriously bitpay, can you guys fix your Insight API server, or at least let us know whats going on? I don't want to have to create my own insight server just to run a simple wallet...You guys need to at least give us a warning before it goes down or have a backup server for redundancy. This is really hindering a lot of people.

**Comment by jaysander** [comment]
are my coins safe? is this happening to everyone?

**Comment by LinadD** [comment]
jaysander - don't worry, your coins is ok.

**Comment by jaysander** [comment]
linadD - do u know whats happening im extremely frightened that i cant access or even see my funds. and if u do know why this is happening, for how long do u think this is going to be a problem

**Comment by webdevly** [comment]
Yes, your coins are safe. YOu can actually export and move to another wallet if you want

**Comment by webdevly** [comment]
Unfortunately we won't know how long it'll be down for until bitpay decides to let us all know. Which you'd think they'd do so, considering how much competition there is these days for the majority share of btc wallets out there.

**Comment by jaysander** [comment]
webdevly - i cant export them i cant send them anywhere still getting an error

**Comment by alextheangel** [comment]
Same issue here. Hopefully be fixed soon

**Comment by webdevly** [comment]
You either need to create your own BWS (https://github.com/bitpay/bitcore-wallet-service) or you can use the Copay recovery tool, which will send your funds to another wallet address of your choice. You'll need to create a backup of your wallet to use the latter. Hope this helps.

**Comment by jaysander** [comment]
@webdevly i tried to back up on another divice and got the same "insight error"

**Comment by jaysander** [comment]
@webdevly also i tried using the recovery tool and got this error 
![bit](https://cloud.githubusercontent.com/assets/19603209/15600581/b90c8fbe-239f-11e6-89ad-56e7d9b77b97.PNG)

**Comment by anthony19114** [comment]
You can use Wallet Service URL: https://node.bitcoin.tt/bws/api
Until bitpay is back up.

**Comment by jaysander** [comment]
@anthony19114 link doesnt work im getting this on my mobile device and computer
![bit3](https://cloud.githubusercontent.com/assets/19603209/15600944/fa7aa86c-23a1-11e6-8159-b228599f9b74.PNG)

**Comment by LinadD** [comment]
Thank you. It is work.

**Comment by jaysander** [comment]
@LinadD what did u use

**Comment by webdevly** [comment]
Be careful which BWS you end up using, as if you use the wrong one they can steal your bitcoin...

**Comment by webdevly** [comment]
I'd recommend either creating your own BWS locally or just using the recovery files to send to another wallet

**Comment by anthony19114** [comment]
It works, you have to change the wallet url to that in your android or iPhone app.. Not sure where it is in android, but for iPhone it's under Settings > Advanced > Wallet Service URL

**Comment by LinadD** [comment]
@jaysander Go to "Wallet Preferences" --> "Advanced" --> "Wallet service URL"

**Comment by jaysander** [comment]
this url @LinadD https://node.bitcoin.tt/bws/api

**Comment by LinadD** [comment]
@jaysander Yes, replace default url

**Comment by knop13** [comment]
what is the nature of this url? can they intercept my keys?

**Comment by jaysander** [comment]
has anyone verified this link https://node.bitcoin.tt/bws/api besides the 2 promoting it

**Comment by knop13** [comment]
how to verify?

**Comment by LinadD** [comment]
Send 0.01 BTC to yourself

**Comment by jaysander** [comment]
copay back up im not changing shit

**Comment by jaysander** [comment]
my wallet is back online but does anyone suggest another wallet i do not want this to ever happen again

**Comment by matiu** [comment]
We had some problems with the Bitcore Wallet serivice hosting. We are very sorry with the inconveniences. it should be OK now.

See https://status.rackspace.com/

thanks.

**Comment by LinadD** [comment]
For such cases need backup server

**Comment by webdevly** [comment]
For such cases they need automatic redundancy

**Comment by thumbender** [comment]
I'm investigating Breadwallet for IOS no BWS

Jaco Pieterse
+27 (0)83 378 4572
jaco@cozamarketing.com
www.cozamarketing.co.za

COZA Marketing
Bringing you more customers for less!


[image: Qualified Google AdWords Professionals]
<https://www.google.com/partners/?hl=en-US#a_profile;idtf=6046473509>

**Comment by webdevly** [comment]
Breadwallets been around for quite a while on iOS. Its very simple to use, and is known to be a decent wallet. I'd recommend visiting https://www.cryptocompare.com/wallets/#/overview and doing some research for a wallet that meets your exact needs. Keep a lookout for Jaxx wallet, its out for desktop and should be coming to iOS soon.

Donations: 1GNpbvUYfnK3oN1wRknEVvdLzucCWMAJNS

**Comment by webdevly** [comment]
And please do not use unverified BWS URLs....this is the best way to get your BTC hijacked. Unless you absolutely trust the auxiliary BWS that was provided above, I'd recommend immediately moving your coin to a new wallet and switching back to the default URL. If you go to the URL, you'll see that there's nothing on the root domain. Not a good sign.

**Comment by rsalvi** [comment]
> And please do not use unverified BWS URLs....this is the best way to get your BTC hijacked. Unless you absolutely trust the auxiliary BWS that was provided above, I'd recommend immediately moving your coin to a new wallet and switching back to the default URL. If you go to the URL, you'll see that there's nothing on the root domain. Not a good sign.

How can BTC be hijacked from using a BWS that is a bad actor? Private keys are never sent to a BWS server. At the most, couldn't a bad acting BWS server just know how many coins are in a user's wallet?

**Comment by anthony19114** [comment]
I run node.bitcoin.tt. The root domain has no website since I have no use for it at the moment. It's a full node. I'm glad this started a discussion of security and the beginning of separating ignorance from truth.
