### ISSUE TITLE
Copay Error

### ISSUE THREAD

**Issue by KalboCommander** [bitpay/copay#4254]
![image](https://cloud.githubusercontent.com/assets/7940643/15598842/bd4ec396-2410-11e6-9eed-47264bc37eab.png)

Any idea what's causing this?  Can't access wallet.

**Comment by jaysander** [comment]
@KalboCommander getting the same thing for 25 min now. someone says coins are safe but who knows

**Comment by matiu** [comment]
We had some problems with the Bitcore Wallet serivice hosting. We are very sorry with the inconveniences. it should be OK now.

See https://status.rackspace.com/

thanks.

**Comment by sweetppro** [comment]
yup all good here now, thanks!
