### ISSUE TITLE
error updating wallet in app: "error at wallet service insight error"

### ISSUE THREAD

**Issue by knop13** [bitpay/copay#4255]
what does it mean ?

**Comment by jaysander** [comment]
it means you and i (and a couple hundred others) have to wait for a real answer. no one from github is doing anything atm, they will prob get to it when they feel like it, if u can try to back up your funds go for it ( i havnt been able too, some have though)

**Comment by matiu** [comment]
We had some problems with the Bitcore Wallet serivice hosting. We are very sorry with the inconveniences. it should be OK now.

See https://status.rackspace.com/

thanks.
