### ISSUE TITLE
Does breadwallet also use a BWS that can go down?

### ISSUE THREAD

**Issue by thumbender** [bitpay/copay#4256]

**Comment by matiu** [comment]
no. Breadwallet does not use BWS.

**Comment by thumbender** [comment]
Is there no way that the copaywallet can use this technology or are there other disadvantages?

**Comment by matiu** [comment]
There are advantages and disadvantages. 

Been a multisignature wallet, Copay needs a way to rendevous different Copayers, that is our main dependency with BWS.

We could have an 'emergency mode' in which Copay could work 'serverless', in case there is an outage of any kind. That is on our roadmap.

**Comment by dabura667** [comment]
Maybe you could do something like Electrum where people installing BWS on their bitcore node could opt to advertise their node and copay wallets could fallback on one of those in the event of an outage...

Though in Electrum's model, you do not give the server your xpub...
