### ISSUE TITLE
Coins Stuck in copay !

### ISSUE THREAD

**Issue by dantavares** [bitpay/copay#4258]
I can not understand, is it just me? Today copay is simply stop working, be scanning back forever, waited, started to give an error in the network / insight. I tried to reinstall the app, it automatically creates a wallet (does not give option to restore a backup at the start), try to delete the newly created wallet to import my backup again, and is forever with "Deleting wallet".
Finally, I tried to use the "copay-recovery-tool" works, but this message appears: "Could not broadcast transaction Please, try later.." When I click "Transfer".

Can someone help me ??

**Comment by matiu** [comment]
We had some problems with the Bitcore Wallet serivice hosting. We are very sorry with the inconveniences. it should be OK now.

See https://status.rackspace.com/

thanks.

**Comment by dantavares** [comment]
its not. I cant restore my backup, stay "deleting wallet" (on new and zero coins created wallet). Reinstall app, its create new wallet, try to delete (to restore my backup) and stay forever "deleting wallet".
Try to use copay-recovery-tool (just now) on google chrome and fire fox, and still having a message: "Could not broadcast transaction. Please, try later".
I just continue to not have acess to my funds !

**Comment by matiu** [comment]
I am sorry you are having problems with Copay.

You don't need to `delete the wallet` in order to import a new one. Copay can handle  multiple wallets.

Go to `Sidebar > Import wallet`
