### ISSUE TITLE
Stop ignore me !

### ISSUE THREAD

**Issue by dantavares** [bitpay/copay#4259]
this is ridiculous ! I trusted this app and now I have all my money stuck in it, and not the tool it was to recover in case of emergency works! I could hardly sleep that night because of it, it will be possible that no one can help me ?? There is no way to export the transaction and try to broadcast elsewhere? I need a solution, I'm desperate!

**Comment by dantavares** [comment]
Forget it ... I could transfer my money using google chrome app.
Thanks for nothing, bitpay never more !

**Comment by matiu** [comment]
I am sorry you had problems in Copay, but you are not been ignored.

When you say the tool does not work, what you mean exactly?  What was the issue?

Last night, our hosting provider had a network issue and there were problems in certain instances of Copay.

**Comment by dantavares** [comment]
This tool http://bitpay.github.io/copay-recovery/ i try to use, but not work, gave a message saying not able to broadcast transaction, even on service back online.
Is Ok now, i migrate my funds to blockchain.info.

On linux (ubuntu 14) do not work, and when google chrome update yesterday, stop work (blank screen). Honestly you need a general review of this app, it is getting worse, so I stopped using, do not trust him anymore.

**Comment by JulianTosh** [comment]
Can confirm Google Chrome App stopped working after an upgrade. When you open the CoPay app, it just gives you a blank window.

![copayblank](https://cloud.githubusercontent.com/assets/627143/15684405/d1dd4932-271b-11e6-9455-7842529cf1fe.png)

**Comment by JulianTosh** [comment]
Using Chrome Version 51.0.2704.63 (64-bit) on Fedora 23/Linux

**Comment by isocolsky** [comment]
Can confirm this. It was working on Chrome 50.0.2661.102 (64-bit) but stopped working on 51.0.2704.63 (64-bit). I'm on OS X.

**Comment by dantavares** [comment]
yes Using Ubuntu 15, have a blank screen after a google chrome update

**Comment by matiu** [comment]
This was just fixed in https://github.com/bitpay/copay/pull/4268

Version 1.12.15 already uploaded to the Chrome store.

Thanks for the report.
