### ISSUE TITLE
Signatures Rejected by Server

### ISSUE THREAD

**Issue by blueknight02** [bitpay/copay#4261]
This is the first time this has happened to me. Everything for the past few weeks has worked fine up to this. I am using a 2/2 with a ledger and my android nexus 6p running version 1.12.14. The wallet was made about 2 months ago. No password set for this wallet. I have my back ups but would prefer not to bring them online.

**Comment by matiu** [comment]
Could you please try the beta version (1.20) for Android available at https://play.google.com/apps/testing/com.bitpay.copay ?

Alternatively you can import you wallet in other device and sign there.

**Comment by blueknight02** [comment]
Should I download it on a different device? Will it affect my current copay app?

**Comment by blueknight02** [comment]
Problem solved. I was using the wrong hardware wallet. Very easy to mix those up. Thanks

**Comment by matiu** [comment]
thanks for th update
