### ISSUE TITLE
Delete Wallet is Broken

### ISSUE THREAD

**Issue by atpant** [bitpay/copay#4262]
How to reproduce:

1. Create a shared wallet.
2. Press "Cancel and Delete".
3. Nothing happens.

Alternatively:

1. Open "Personal Wallet" > Wallet Preferences > Advanced > Delete Wallet.
2. Confirm deletion.
3. Never completes "Deleting Wallet...".

Copay: 1.12.1.
iOS: 9.3.2.

**Comment by JDonadio** [comment]
Hi @atpant, I already found the error. Thanks for the report!
