### ISSUE TITLE
I forgot my copay wallet password. Is there a kind o method to reset it?

### ISSUE THREAD

**Issue by feudaltuna** [bitpay/copay#4265]

**Comment by matiu** [comment]
Sorry to hear that. No, there is not way to reset the password since it is an encryption key, only stored in the client.

**Comment by isocolsky** [comment]
If you still have the 12 words backup, try deleting the wallet and importing using the words.

**Comment by feudaltuna** [comment]
Yes, I have it. Let's try. Thank you

**Comment by JDonadio** [comment]
I recently made an import of an encrypted wallet from 12 words and works great.

**Comment by feudaltuna** [comment]
Done it. I didn't have any loss. God save the backups ;)

**Comment by isocolsky** [comment]
That's great to hear!

**Comment by matiu** [comment]
👍
