### ISSUE TITLE
Signature rejected

### ISSUE THREAD

**Issue by cavix** [bitpay/copay#4266]
Hello,

I'm pretty new to bitcoins and just bought a 50€ coupon an uploaded to my wallet which worked smoothly.
However I'm unable to send anything.

It always stops with error : Signature rejected
I tried on Android Marshmallow Galaxy S6, Ipad Air 2 latest IOS and Windows client.
Same error on all clients.

I also tried to send to different receiver adresses and high/low amounts.
But no success

What am I doing wrong?

Thanks,
Kev

**Comment by matiu** [comment]
Hi,

When you wallet was created? and in which device? Also, did you ever made an outgoing TX on your wallet?

thanks.

**Comment by cavix** [comment]
It was created on Android device.
I never did any outgoing transaction since they always failed.

Thx for your help

**Comment by matiu** [comment]
Thanks for the info. What Copay version are you using on Android? Could you please contact me at matias@bitpay.com so we can follow this privately?

**Comment by cavix** [comment]
Hello,

since there was no reaction on my emails in 3 weeks, can somebody else pls advice how to proceed?

I created a new wallet and received and sent asome bitcoins --> everything is working fine there.

However my old wallet is still not working and my bitcoins are caught.
The new android and IOS version shows following error:
Key derivation is not working in this device/wallet. Aczion cannot be performed on this wallet.

What can I do?
