### ISSUE TITLE
Chrome app broken after update

### ISSUE THREAD

**Issue by JulianTosh** [bitpay/copay#4267]
I just recently updated my Fedora 23 workstation, which included a new package from google-chrome repository. Since, CoPay has ceased to work. It just opens a blank screen.

Current OS version:
Fedora 23/4.4.9-300.fc23.x86_64

Current Chrome version:
Version 51.0.2704.63 (64-bit)

![copayblank](https://cloud.githubusercontent.com/assets/627143/15684667/fc75cad8-271c-11e6-8113-7c87febc0042.png)

**Comment by matiu** [comment]
Working on that now.

The new version of chrome does not allows:

```
      window.localStorage = chrome.storage.local;

```
on localStorage.js

**Comment by matiu** [comment]
OK it should be fixes in Copay 1.12.15 (just uploaded to Chrome Store).


thanks a lot for the detailed report.
