### ISSUE TITLE
Importing wallet error

### ISSUE THREAD

**Issue by Matiasfx** [bitpay/copay#4271]
When I try to import a 12 word seed created on mycelium or created on https://dcpos.github.io/bip39/ I get an "Could not import: Not authorized"  Why could it be?

I can import a copay seed on mycelium but not the other way around. And as I said I tried with a random one created by the bip39 website and I can import it on mycelium but not on copay.

Sorry if is something really simple. I'm new to all this.

Thanks

**Comment by matiu** [comment]
No problem!

If the wallet is not yet created in Copay, you need to go to: Add > CreateWallet > Advanced > Specify Seed. `Import` is only for Copay wallets (we need to enhance the wording there...)

**Comment by Matiasfx** [comment]
@matiu thanks Matias. it worked great.
