### ISSUE TITLE
UI Freeze on android 4.1 and 4.2 

### ISSUE THREAD

**Issue by BitMari** [bitpay/copay#4273]
I'm having an issue on copay android 4.2 , 4.1 when i try to install it freezes on the copay splash screen , and in some case displays the message browser not supported.

Does it mean i did not build the android code well??  
Thats the message that shows up , any idea where i went wrong while building android..

Unsupported
    Sorry, Copay is not supported by your Device/browser. 
    Note that localStorage should also be enabled (enabled by default in most cases).

**Comment by matiu** [comment]
Did you built Copay your self?
