### ISSUE TITLE
Migration to New iOS phone - wallet lost 

### ISSUE THREAD

**Issue by QuantumGlobal** [bitpay/copay#4284]
I performed a backup and restore of all data to move from an iPhone 4S to a 6 plus.  The Copay wallet application has migrated however the actual wallet did not, so there is no longer access to funds.

I have all the old data/passwords, however I do not have the phrase (nor do I recall if one was created).

How can I restore access?

**Comment by gabrielbazan7** [comment]
You should go to : Add Wallet > Import Wallet > File/Text Backup if you have the backup file or Wallet Recovery Phrase if you have 12 words

**Comment by gabrielbazan7** [comment]
If you don't have the 12 words in your old phone, you should go to Wallet preferences > Advanced > Export Wallet, set up a password and send the file to your email. In your new phone use that file in File/Text Backup option.

**Comment by QuantumGlobal** [comment]
Hi Gabriel, thanks for such a quick response.
I don't have the 12 words, and I no longer have the old phone, it was re-formatted and traded in after backup.
I still have the backup which was saved by iOS, would the data be in there somewhere?

**Comment by gabrielbazan7** [comment]
I'm sorry, you need your Copay Wallet backup to have access to your funds. You could not receive funds in your wallet without doing the backup, so, it might be in your email.

**Comment by QuantumGlobal** [comment]
Clarifying - this is something that would have been done setting up the wallet and prior to the first payment going into the wallet?
If so - any idea what it might have had as the subject heading?

**Comment by gabrielbazan7** [comment]
You should have seen this screen or a similar one ( if you have an old version of Copay ) when you create your wallet and switch to the receive tab for your wallet address.

<img width="465" alt="copay_-_multisignature_wallet" src="https://cloud.githubusercontent.com/assets/10999037/15808911/1de0d6a4-2b5a-11e6-9948-1c42b3a592c2.png">

**Comment by dabura667** [comment]
For future reference, only a locally stored backup with the "encrypt backup" checked in iTunes will back up app's secret data.

iCloud backups are useless except for grandma's iPhone.

**Comment by QuantumGlobal** [comment]
Hi Dabura - I agree, I don't use the cloud at all. The backup was local and encrypted - however it still did not pass the wallet to the new phone.

**Comment by QuantumGlobal** [comment]
@gabrielbazan7 I don't recall that screen but it has been about 2 years since the wallet was set up.
I went through emails with a comb, not finding anything.
Any other options?

**Comment by dabura667** [comment]
Oh. 2 years?

That is a different problem.

Go to Import wallet > File or text backup > import v0.9 legacy wallet and put in your login credentials.

**Comment by QuantumGlobal** [comment]
I'm getting profile not found.  The server entry should be left as the default?

**Comment by matiu** [comment]
Do you have the encrypted wallet text?

On Mon, Jun 6, 2016 at 1:39 AM, QuantumGlobal <notifications@github.com>
wrote:

> I'm getting profile not found. The server entry should be left as the
> default?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bitpay/copay/issues/4284#issuecomment-223867372>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAGCHGP8RPwXr8UfKZrxHLmFoA_1wfSyks5qI6ScgaJpZM4Iuas3>
> .
>



-- 
BitPay.com

**Comment by QuantumGlobal** [comment]
Not to my knowledge, isn't that what we are trying to retrieve by importing the old wallet?

**Comment by QuantumGlobal** [comment]
If you mean the 12 word recovery phrase I do not have it.

**Comment by JDonadio** [comment]
Refers to backup file, the plain text (encrypted).

**Comment by QuantumGlobal** [comment]
Where would the backup have been saved to back in May/June 2015? Is there still a server address I can use to try and recover it?

**Comment by matiu** [comment]
No, you need to have the backup yourself or export it again from the old device.

**Comment by QuantumGlobal** [comment]
Would the app have sent the backup to me as an email attachment?

**Comment by matiu** [comment]
> Would the app have sent the backup to me as an email attachment?

No necessary. In Copay Beta, the backup phase could be skipped by the user.
