### ISSUE TITLE
PowerPC applications are no longer supported.

### ISSUE THREAD

**Issue by BitMari** [bitpay/copay#4285]
i did a grunt desktop command and built well but wen i try to open the app on Mac i get the following message.

You can’t open the application “Copay” because PowerPC applications are no longer supported.

Any help?

**Comment by cmgustavo** [comment]
Hi @BitMari , are you using an old Mac with PowerPC processor?

Copay doesn't support PowerPC architecture, only x86-64. Node-webkit can not build apps for PowerPC, it 's an old architecture.

Anyway, try to open Copay from command line (without generate the binaries with `grunt desktop`):

```
/Applications/nwjs.app/Contents/MacOS/nwjs copay-folder/
```

**Comment by matiu** [comment]
Note there is also an issue on NW.JS related to this message: https://github.com/nwjs/nw-builder/issues/269

Check you NW.JS version.
