### ISSUE TITLE
[Bug] Fee selection

### ISSUE THREAD

**Issue by Kirvx** [bitpay/copay#4318]
The fee selection works visually with a double click to be set up, but if you click once on a choice (no visual change), go back, and return to the fee selection, the choice you have cliked will be selected.

Copay 1.12.15 and 2.0

**Comment by Kirvx** [comment]
Also, note that if you switch to a different language, the language of the strategies will not change.

**Comment by JDonadio** [comment]
Just to clarify, **Unit and Alt. Currency** should not be translated. Also, Super Economy (opt) is not translated yet.

**Comment by Kirvx** [comment]
@JDonadio Not really fixed if you alternatively click a lot on "Normal" and "Economy", you will see that the confirm time and the rate is the same for both :)

**Comment by JDonadio** [comment]
I was missing a refresh. Thanks a lot @Kirvx for this report!
