### ISSUE TITLE
Backup in progress Ux

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#4325]
When backing up the wallet using the "back up game", after I click on all the words in order I click the continue button.  The UI freezes with no feedback while the back is being verified.  Sometimes it takes 20-30 seconds to get the back up verified.  Recommend dimming the Continue button and displaying a progress indicator (spinner) on the UI.

**Comment by matiu** [comment]
This is fixed in Copay 2.0. I think there was a refresh problem.

**Comment by ajp8164** [comment]
Sorry, should have mentioned that I am using copay/master (v2.0.0), updated yesterday.  Just looked at outstanding commits and didn't see anything that addresses this issue.

**Comment by matiu** [comment]
What platform are you using? There is no CPU intensive process on the backup check and no network request either. We just tested on web and android.

**Comment by gabrielbazan7** [comment]
I could reproduce the issue

**Comment by JDonadio** [comment]
I'll take a look.

**Comment by JDonadio** [comment]
Done. Thanks @ajp8164 !
