### ISSUE TITLE
Error broadcasting a transaction

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#4343]
BWS allows to create TXs with output amounts considered dust by our boundary nodes (eg. amount = 10 bits).

 When trying to broadcast it, the node rejects the TX, and the TX remains stuck in Copay.

**Comment by braydonf** [comment]
Does the dust amount in bitcore-lib at: https://github.com/bitpay/bitcore-lib/blob/master/lib/transaction/transaction.js#L65-66 and https://github.com/bitpay/bitcore-lib/blob/master/lib/transaction/transaction.js#L250-L261 need to be updated?

**Comment by matiu** [comment]
Well, it seems that the dust is not a fixed number but a function of the node's `relayfee` and the size of the transaction. 

546 SAT is the average for a P2PKH, 1 input, 1 output TX.

https://www.reddit.com/r/Bitcoin/comments/2unzen/what_is_bitcoins_dust_limit_precisely/

So the dust would be: txSize * relayfee * 3.

For a 2-2 TX in Copay, with 1 input, size is ~ 740, for the default relay fee of 1000 SAT/kb,  dust will be ~ 2220 SAT

**Comment by braydonf** [comment]
Also the relevant method in bitcoin: https://github.com/bitcoin/bitcoin/blob/0.12/src/primitives/transaction.h#L160-L175

It does look like we need to update the logic in bitcore-lib.
