### ISSUE TITLE
pls help me

### ISSUE THREAD

**Issue by kianooshpa** [bitpay/copay#4355]
hi i create account in copay.io for payment how to add fund to copay app? (adnroid)
i want buy product
now i have 0 bits i want add 50$ for buy product

**Comment by matiu** [comment]
Hi!

You need to buy Bitcoins using your currency on a exchange.  There are several exchanges around the world, look for one in your country.  When buying, you will need to provide you Copay bitcoin address (on the receive tab) so  the  buycoins can be sent to you.

Note that you dont have  "an account at copay.io".  Copay is just a tool for handling your bitcoins keys, and the keys are only hold by your device, so be sure to backup them by writing the 12 words on a safe place.

matías
