### ISSUE TITLE
Question: Create NEW Wallet Periodically??

### ISSUE THREAD

**Issue by KeyJockey** [bitpay/copay#4357]
This is just a question not a bug report or feature request, but I was not sure if there's some other "copay forum" or somewhere else to ask things like this on, rather than here.

Just wondering IF there's any necessity to create a new wallet and "start over fresh" from time to time with Copay?  

Reason being: it just seems to me that *maybe* after using one particular wallet for a long time and accumulating hundreds or thousands of transactions, maybe things will tend to slow down or become more 'complex' over time?  Is a new, "empty" or "clean" wallet going to be faster to any real degree?

If so, at what point would you guys *think* doing this may become beneficial...?  100 transactions, or 1,000 or where's the tipping point?  

OR is it really not any possible concern, realistically?  

I'm just asking 'cuz it seems to me -- only *sometimes* -- that a couple of my wallets with a lot of transactions just feels more "sluggish" sometimes, versus other lesser-used wallets, but maybe it's just a co-incidence or just my imagination LOL

**Comment by matiu** [comment]
> Just wondering IF there's any necessity to create a new wallet and "start over fresh" from time to time with Copay?

It is not necessary.  Handling wallets with many transactions is one of the key objective of Copay. Currently there are many active wallets with tens of thousand transactions. Copay and BWS have some optimizations to reduce the impact of inactive wallet address in the UX and in the refresh procedures.

**Comment by KeyJockey** [comment]
OK @Matiu thanks for reply, good to know :thumbsup:

**Comment by matiu** [comment]
BTW, great question, we should add this to the FAQ  @gabrielbazan7
