### ISSUE TITLE
Create mnemonic seed in other language

### ISSUE THREAD

**Issue by songproducer** [bitpay/copay#4366]
Hi,

How can I change the mnemonic seed to be traditional Chinese words? I found this:

https://bitcore.io/api/mnemonic/

But I don't know how compatible it is.

**Comment by dabura667** [comment]
You need to wait until we release the next version.

The next version will automatically make mnemonic seeds in Simplified Chinese if you have your app set to Chinese.

Unfortunately, we currently can not support traditional AND simplified at the same time, so we decided to go with Simplified.

Currently, only Simplified Chinese wordlist is supported by bitcore.

https://github.com/bitpay/bitcore-mnemonic/tree/master/lib/words

**Comment by songproducer** [comment]
Would treating Traditional Chinese as a separate language (rather than as a subset of Chinese) make this easier?

**Comment by dabura667** [comment]
> treating Traditional Chinese as a separate language

We can not do this right now.

Currently, Copay only looks at the language setting, which is a standard that all devices follow.

ie.: en, zh, fr, jp

There exists a "region code" which is like en-GB en-US jp-JP zh-TW zh-CN but the app can not recognize this currently.

So our app will see Taiwanese iPhone and Chinese iPhone both as only "zh"

If the app could see "zh-CN" (Simplified) and "zh-TW" (Traditional) then we could support it, but currently it does not...

Adding this feature is difficult, as it affects all languages. ("en" would become "en-US" or "en-GB" etc.)

**Comment by songproducer** [comment]
I'd like to reopen this issue - as difficult as it is, because it's very hard to promote Bitcoin in Taiwan without a wallet that supports traditional Chinese.
