### ISSUE TITLE
question: disaster recovery procedure

### ISSUE THREAD

**Issue by juanjgit** [bitpay/copay#4369]
Hi

Let's say that copay.io disappears and that I only have an encrypted json export of my wallet. Is there a procedure to recover my funds? Is there any other wallet that can import that json?

**Comment by gabrielbazan7** [comment]
It is possible to recover funds from a Copay Wallet without using Copay or the Wallet Service, check the Copay Recovery Tool ( https://bitpay.github.io/copay-recovery/ )

**Comment by matiu** [comment]
You can also import you wallet recovery phrase on any BIP44 compatible wallet.
