### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by jdkamda** [bitpay/copay#4393]
hi

**Comment by jdkamda** [comment]
i have many transaction that being confirmed but not showing to my recipient,.,. PLEASE HELP!

**Comment by gabrielbazan7** [comment]
Try with: preferentes > preferences advanced > transaction history > clear cache

**Comment by matiu** [comment]
can you see the transactions.on the blockchain? if that is the case, then
it is probably an issue on your recipient's wallet.

**Comment by jdkamda** [comment]
it work now.. after i clear cache.. all of my transaction has been show to my recipient account.. thank you all for help.. kisses you both lol
