### ISSUE TITLE
Guide users in Create wallet to multi sig templates

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#4405]
Options should be something like:
 
 - Every day wallet  (For every day expenses, holding small amount of bitcoins) 1 of 1

 - Saving wallet (for holding larger amount of Bitcoins, multisignature) 2 of 2
 
 - Enterprise wallet (for shared ownership of funds, multisignature) 2 of 3
 
 - Custom

If the user choose one of the templates, we can store that info on the wallet, and better guide the use later in:
  - the backup process (eg: you need to backup your 2 devices for 2-2 wallets)
  - the signing process (eg: please now sign this transaction in your other device, no email notifications, etc)
  - the wallet delete process

**Comment by bitjson** [comment]
merging: https://github.com/bitpay/copay/issues/4900

**Comment by JDonadio** [comment]
IMHO this shouldn't be merged in the onboarding process but should be a separated section within the app.
