### ISSUE TITLE
Support Orbot - Android

### ISSUE THREAD

**Issue by HostFat** [bitpay/copay#4422]
Can you make it working with Orbot? (or Tor in general)
https://play.google.com/store/apps/details?id=org.torproject.android

I've made some tests but it doesn't seem to work correctly.

**Comment by braydonf** [comment]
I believe this is supported by running a personal BWS and bitcoin node.

**Comment by HostFat** [comment]
@braydonf are you saying that it is impossible to make it working only by using the client? (so, making it easier for the common user)

They are many softwares that works even with connections through Tor (socks5 proxy)

**Comment by braydonf** [comment]
Related: https://github.com/bitpay/copay/issues/4049

**Comment by HostFat** [comment]
Ouch!

This isn't very user-friendly :)

So it is even related to #3835

Maybe opening an onion address can be another solution ...

The user will set Orbot and then your onion address on the "Wallet Service URL" setting ...

**Comment by matiu** [comment]
Please see https://github.com/bitpay/copay/issues/3855

> For the moment, removing cloudfare for the public BWS is not an option, but you can host your BWS (https://github.com/bitpay/bitcore-wallet-service), for enhanced privacy.
