### ISSUE TITLE
perdi mi cartera bitcoin ya que mi celular se formateo todo

### ISSUE THREAD

**Issue by wolfdarkgold** [bitpay/copay#4431]
perdi mi cartera bitcoin ya que mi celular se formateo todo quiero ver si me puede ayudar a recuperar mis bitcoins  por favor anexo mi url bitcoin de copay 168EzHgNaE31hhJjVtd3xUsEQzxMf6LuvM
ademas adjunto mi correo de registro omynab@gmail.com
asi como algunos deposito 
![copay 2](https://cloud.githubusercontent.com/assets/19980982/16129086/007a75bc-33c9-11e6-84f0-0a477a9b10a1.png)
![copay](https://cloud.githubusercontent.com/assets/19980982/16129087/007da08e-33c9-11e6-8bf0-ff94d181700d.png)

**Comment by matiu** [comment]
Hola,

En Copay, las llaves sólo se encuentran en la app, por eso es necesario hacer un backup de las mismas antes de comenzar a usar Copay. Las llaves no están almacenadas en el server. No es posible recuperarlas sin un backup.  Tienes backup de tu wallet?

**Comment by wolfdarkgold** [comment]
entonces como le puedo hacer

**Comment by matiu** [comment]
lamentablemente si no tienes el backup de tu wallet no es posible recuperarla.

**Comment by wolfdarkgold** [comment]
no hay manera supuestamente en la app decia que se hacia un respaldo cada tiempo pero no se donde si sd o en telefono o si se manda por mail

**Comment by JDonadio** [comment]
Hola @wolfdarkgold, contestando tu duda Copay no realiza copias de seguridad automáticamente. Por motivos de seguridad y para evitar estos escenarios se "obliga" al usuario a realizar un respaldo antes de poder utilizar Copay. Lamentablemente si no tienes ningún respaldo ya sea el archivo o las 12 palabras, no podrás acceder de nuevo a los fondos de esa billetera.

**Comment by serweb** [comment]
A mi me paso algo parecido, se lleno la memoria entonces no permitia abrir la aplicacion en windows phone, luego de liberar espacio, no logro recuperar mis btc, tengo las 12 palabras pero al querer recuperar me tira un mensaje "ERROR No se pudo importar: La frase de recuperacion no es valida" sin embargo copio y pego las 12 palabras y nada, alguna sugerencia?

**Comment by wolfdarkgold** [comment]
Mejor baja bitcoin wallet copay no te echan la mano

**Comment by JDonadio** [comment]
@serweb el error `La frase de recuperación no es válida` hace referencia a que algún caracter está mal escrito, ya sea con mayúscula, acentos o algo así. Tene en cuenta que si tus palabras estan en español pueden tener acentos, sacaselos. De todas formas aqui tenes una lista completa de todas las palabras para tu lenguaje, podes chequearlas a todas y ver si las escribiste bien:

https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md

**Comment by Elimontilla** [comment]
buenas noches yo tengo el mismo problema me robaron mi telefono y ahora no logro recuperar mi cartera ya revise y todas las palabras estan en la lista pero me sigue saliendo frase de recuperacion no valida ayudaaaaaaa @JDonadio

**Comment by Elimontilla** [comment]
soy venezolana y la persona que me robo el telefono tambien se llevo todos mis ahorros ahora tengo dos dias sin dormir y nada que logro recuperar mi cartera existe otra manera de resolverlo? @JDonadio

**Comment by JDonadio** [comment]
Hola @Elimontilla, para el error que frase inválida pueden ser 2 cosas:

* Alguna palabra está mal escrita: mayúsculas, acentos, tildes. Todo tiene que ser en minúsculas y sin acentos si es en español.
* Que el orden de las palabras esté mal: en este caso no queda otra opción que comprobar todas las combinaciones posibles entre 12 elementos

**Comment by Elimontilla** [comment]
gracias señor Javier si estoy en eso pero nada, una pregunta las frases que colocaron arriba son las unicas frases posibles? ya que aunque todas concuerdan con palabras que estan en la lista estoy tan desesperada que no se si coloque alguna palabra mal

________________________________
De: Javier Donadío <notifications@github.com>
Enviado: jueves, 17 de agosto de 2017 09:17 a.m.
Para: bitpay/copay
Cc: Elimontilla; Mention
Asunto: Re: [bitpay/copay] perdi mi cartera bitcoin ya que mi celular se formateo todo (#4431)


Hola @Elimontilla<https://github.com/elimontilla>, para el error que frase inválida pueden ser 2 cosas:

  *   Alguna palabra está mal escrita: mayúsculas, acentos, tildes. Todo tiene que ser en minúsculas y sin acentos si es en español.
  *   Que el orden de las palabras esté mal: en este caso no queda otra opción que comprobar todas las combinaciones posibles entre 12 elementos

**Comment by JDonadio** [comment]
@Elimontilla si, la lista que corresponda a tu idioma tiene la lista completa de palabras que se pueden utilizar. Si por ejemplo vos tenes en tu frase:

aaaa bbbb cccc dddd eeee ffff gggg hhhh iiii jjjj kkkk épico, entonces esa última estaría mal por el acento y en la lista debería aparecer epico. Por lo que deberías sacarle el tilde y probar. 
Si en cambio tenes bien escritas todas las palabras y te sigue dando inválida tenes que probar el orden de alguna que hayas puesto mal. Tenes que tratar de recordar o re-crear el momento en el que las escribiste.

**Comment by Elimontilla** [comment]
Probe moviendo el orden de las palabras me sale lo siguiente:  No se pudo acceder a la billetera desde el servidor Verificar: La contraseña de la frase de recuperacion (si existe) la ruta de derivacion. Url de Wallet service. Nota: para importar una billetera de un software de un tercero debes ir añadir billetera crear billetera y especificar la frase de recuperacion @JDonadio

**Comment by JDonadio** [comment]
@Elimontilla, si te sale otro error diferente al de frase inválida, lo más probable es que hayas puesto una clave en tus 12 palabras y no la estes recordando.

**Comment by Elimontilla** [comment]
es que no recuerdo haber colocado ninguna clave solo la contraseña para transferir y el pin de desbloqueo


________________________________
De: Javier Donadío <notifications@github.com>
Enviado: jueves, 17 de agosto de 2017 11:13 a.m.
Para: bitpay/copay
Cc: Elimontilla; Mention
Asunto: Re: [bitpay/copay] perdi mi cartera bitcoin ya que mi celular se formateo todo (#4431)


@Elimontilla<https://github.com/elimontilla>, si te sale otro error diferente al de frase inválida, lo más probable es que hayas puesto una clave en tus 12 palabras y no la estes recordando.

**Comment by JDonadio** [comment]
Entonces no deberías tener otro problema que el tipeo o el orden, tendrás que seguir verificandolo. Lamentablamente desde aqui no podemos hacer más.

**Comment by LiderMundial** [comment]
Elimontilla.
Buena.Te puedo ayudar... Se mucho sobre el BTC... Y la matemática perfecta.Me dedico a buscar BTC perdidos... Cualquier duda comunícate a mí WhatsApp +5493435038788.
