### ISSUE TITLE
Inclusion of mBTC and µBTC as units for display and entry should be considered

### ISSUE THREAD

**Issue by fortran77** [bitpay/copay#4438]
I understand that some people have difficulty with prefixes such as milli- and micro- (e.g., milliBTC aka mBTC; microBTC aka µBTC aka uBTC) and find it easier to use "bits", where one "bit" equals one µBTC.

I myself am used to the idea of a bit being the basic unit of information, and being almost always used in strings  containing ones and zeroes evaluating to a power of two (8 bits, 16 bits, 32 bits, 64 bits) or a multiple thereof (80 bits, 160 bits). I keep getting confused by long strings of non-binary digits displayed by Copay when it displays "bits". And using BTC instead of "bits" yields inconvenient strings of zeroes after the decimal. By contrast, mBTC usually yields a convenient number of digits both before and after the decimal point.

I really think mBTC and µBTC should be available. They would be optional, so those who prefer "bits" could still use them.

Looking at previous issues, I see that the use of "bits" as default was proposed in issue #651, which referred to an official policy via a link which (today) yields a 404 error.

The inclusion of mBTC in the display (but not for input) was proposed in issue #1242. This issue was closed and merged into issue #1228, which was (I think) merged with issue #1243, but mBTC were barely mentioned and not implemented. Issue #1212 also mentions mBTC in passing, but again, it was closed without mBTC being implemented. I did not anywhere find any specific reason for not making mBTC and µBTC available.

I'm hoping that inclusion of mBTC and µBTC as units for display and entry will be reconsidered. The milli- and micro- prefixes are so common and universal in every other aspect of life that they really ought to be available here too.

**Comment by matiu** [comment]
NACK.

I believe this was long discussed on the Bitcoin community already, and there is an agreement to use BTC and bits (bitpay, coinbase, xapo, etc) . Adding more units could confuse users, so I am in favor of sticking to the 2 more common and wildly adopted.

**Comment by fortran77** [comment]
May I respectfully suggest that one or more links be added pointing to the most important of these discussions?   These will be helpful not just to me but to others who might come searching for this same topic.

**Comment by dabura667** [comment]
NACK

**Comment by matiu** [comment]
@fortran77

Sure. Some discussions start here:

https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2014-April/005290.html

On Wed, Jun 22, 2016 at 9:20 PM, Dabura667 <notifications@github.com> wrote:

> NACK
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/bitpay/copay/issues/4438#issuecomment-227915684>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAGCHOD-UNoFG1v-nEk0NDYmeYKwOZ2Sks5qOdFegaJpZM4I3_HI>
> .
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by fortran77** [comment]
Thanks very much for the link. I read the discussion there and found the arguments made by both sides quite unconvincing. I don't think *any* decision—whether pro or con bits/mBTC/uBTC—should be based on that particular discussion (the one at https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2014-April/005290.html). (I also followed some of the links embedded therein leading to other discussions, but not recursively.)

The people who favored the use of milli- and micro- prefixes should have pointed out, but did not, that the general public—evein the US—is in fact already familiar with these prefixes, as discussed below.

The micro- prefix came into English from ancient Greek many millenia ago, and is used in common English by the general public—even in the US—to refer to something tiny. E.g.: microorganism, microcassette, microprocessor, micro SD card, micro SIM, microUSB port. Thus, understanding and using micro- to stand for one-millionth of something would be but a small step from usage already common in English.

The "milli" prefix is understood in the US by anybody who has purchased wine (sold by milliliters and litres), has purchased an add-on lens for a camera (focal length always specified in millimeters), or purchased aspirin (dose almost always measured in milligrams). Official US government recommendations for limiting sodium or cholesterol in a diet plan are always in milligrams. People in the US know perfectly well from common usage that a milligram is a thousandth of a gram and a millilitre is a thousandth of a litre and a milli- of anything is a thousandth of that thing. If people in a country that supposedly does not use the metric system are so familiar with these terms, then surely people in countries that do use the metric system must understand them even better?

The people who argued that the general public would be confused by the use of milli- and micro- prefixes did not support their argument with any research whatsoever. It would have been so easy to do a simple experiment with actual people, and find out how confused they were by the use of these prefixes.

It's been said by a well-known author on user interface design that testing with 5 users is almost always enough (https://www.nngroup.com/articles/how-many-test-users/). Even if you disagree with that, and prefer a smaller or greater number, shouldn't you test with SOME number of actual users? The same writer once said: "The most striking truth of the curve is that zero users give zero insights." (https://www.nngroup.com/articles/why-you-only-need-to-test-with-5-users/) I didn't see even one person claim that they had actually verified their assertion, that lay persons found mill- and micro- prefixes confusing, by testing with actual people. (One person asked his wife, and she was technically knowledgeable, and familiar with these prefixes.)

They all just guessed.

I'm not going to argue with the Copay developers as to what they prefer in their UI. If their decision is final, as it appears to be from the NAKs I saw, then my case is already rested.

I do want to argue strongly that they have based their decisions on a set of poorly-made arguments.

**Comment by petermunnings** [comment]
I suggest **nakas** for milli BTC and **motos** for micro BTC.  It sounds so much more catchy.

Alternatively, another cool name would be zookos for one of them, seeing as Zooko (of ZCash fame) was around in the early days of crypto-currency.

**Comment by JDonadio** [comment]
No quorum
