### ISSUE TITLE
Copay v2.0.1 Android stuck on 'Connecting to Glidera...' Can't access app at all...

### ISSUE THREAD

**Issue by Paolinni** [bitpay/copay#4439]
Has been working flawlessly until as of late. But now everytime I open Copay it does these actions in this order:

1. 'Fetching Glidera Transactions'... (sometimes 3 sec sometimes stuck forever)

2. Validating Wallet Integrity... (usually no more than 10 sec)

3. Connecting To Glidera... (stuck on this forever)

The whole app is inaccessible because its always stuck on these loading states... 

What is going on? Are my coins safe? What should I do?

**Comment by Paolinni** [comment]
Ok I'm getting very nervous. I have two seperate wallets on my phone in which I only have my wallet words to one. I know my other wallet is still on my phone but if I can't access it b/c of these issues mentioned above then I'm screwed since I don't know my words for this particular wallet...

What are my options? I don't want to try to reinstall because that I could potentially lose my wallet forever..

**Comment by matiu** [comment]
your coins are safe. this is only a UI issue.

let us release 2.0.2 todat to fix this issue so you can test it. please
hold on we will let you know once it it fix.

btw, do you have a backup of your wallet?  you could  restore it on other
device to access your funds inmediately

**Comment by Paolinni** [comment]
Ok that sounds about right. And yes I recovered my wallet onto the Copay chrome extension in the menatime (need to store my wallet words a lot better ha).

Thanks for the reply and look forward to v2.0.2!

**Comment by matiu** [comment]
please check 2.1 on the stores. Thanks.
