### ISSUE TITLE
iOS wallet loading

### ISSUE THREAD

**Issue by Chris869218** [bitpay/copay#4443]
When opening copay on iOS it often hangs up while loading the wallet. When I switch to a second wallet within copay, that wallet loads fine. I can then switch back to the original wallet, which will also load fine,

**Comment by matiu** [comment]
Thanks for the report.

If you refresh the original wallet by tapping on the balance or swiping down), does the 'updating wallet' indicator appears for a bit and the goes away?

What ios device are you using?

thanks!

**Comment by Chris869218** [comment]
*If you refresh the original wallet by tapping on the balance or swiping
down), does the 'updating wallet' indicator appears for a bit and the goes
away?*

Yes

*What ios device are you using?*

6s

This happens when I haven't used the wallet for a bit. Nor sure if this is
a few hours or a day or two. I'm used to having to just switch to another
wallet and come back but I figured I'd report it in case it was an issue
others were having as well. If I have just opened copay recently then it
will open fine. It seems to get hung up indefinitely though if I don't
switch to another wallet and come back.

I have observed this in at least one other phone. I recommended a coworker
try copay instead of breadwallet. She was waiting for her wallet to load
and I suggest she get to a different screen in copay and come back and it
worked for her as well. She was on an iPhone SE.

Thanks,
-Chris

**Comment by dabura667** [comment]
This happens to me too.

iPhone 6

I find that it probably doesn't have to do with the wallet, but rather loading up components.

1. Open wallet, refresh the wallet so it is up to date.
2. Wait a few seconds just in case.
3. Close the app and kill it in the open apps menu (double click home button)
4. Open the app again.

It will show the wallet balance, but everything will be frozen, all buttons will not respond, then 15 seconds later, the buttons I pressed while it was frozen will execute in order. (If I tap the receive button, then the send button then the upper left menu button it will flash the address screen, switch to send screen, the open the menu really fast after the initial 15 second wait.

If I reopen the app soon after sending it to the background (without killing it) it works fine.

But every open after long time with no usage or after killing it will always freeze for 15 seconds.

This is true for wallets on bitpay bws as well as personal bws.

**Comment by dabura667** [comment]
v2.0.2 gave me this screen on first app boot

![image](https://cloud.githubusercontent.com/assets/6586275/16224428/06538b14-37dd-11e6-9201-cb35249c51d9.png)

**Comment by dabura667** [comment]
Copay refuses to boot. :-1:

**Comment by matiu** [comment]
Is the OP still happening to you in v2.1?

thanks.

**Comment by Chris869218** [comment]
Nope.

Seems to be fixed for me. Thanks!

-Chris

**Comment by matiu** [comment]
thanks for the update. Closing the issue.
