### ISSUE TITLE
Improve backup process for new users (Rev 2)

### ISSUE THREAD

**Issue by JulianTosh** [bitpay/copay#4450]
I'm resubmitting this because I believe I have a reasonable workaround for developer concerns and there has been no response in the previously closed issue. If this is similarly closed/not implemented, I'll shut my mouth about it. But I feel this revised solution would keep the wallet secure and make it more convenient for new users.

**Revised:**
If the wallet has not been backed up, then the receive tab will only show the "Request a specific amount" page where you have to enter in an amount. The interface will only display the address/qrcode if the amount+current_balance is less than 50,000 bits when the wallet has not been backed up. Otherwise, it will display some warning similar to "You must first backup this wallet before receiving more funds".

**Comment by matiu** [comment]
Closing this one in favor of https://github.com/bitpay/copay/issues/4568
