### ISSUE TITLE
Connecting to Glidera (I don't use it)

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#4451]
V2.0.1, iOS.

Each time I switch wallets I get a spinner about connecting to Glidera.  I don't even have a linked Glidera account.  It shouldn't be doing this.

**Comment by matiu** [comment]
thanks. this one if fixed in 2.0.2. pending review on the app store.

you must had a Glidera account at some time lined.

**Comment by matiu** [comment]
should be fixed in 2.0.2. Please reopen if not.
