### ISSUE TITLE
Can't scroll view when input field touched

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#4452]
V2.0.1, iOS.

On views with inputs (create wallet for example) if you touch an input and try to scroll vertically nothing happens.  I believe I had this problem and fixed it in my fork (don't recall details).

**Comment by gabrielbazan7** [comment]
Thanks for the report Andy. I was able to reproduce it on iOS.

**Comment by cmgustavo** [comment]
Closes #4511
