### ISSUE TITLE
Bitcoin URI on MacOS

### ISSUE THREAD

**Issue by sweetppro** [bitpay/copay#4453]
The bitcoin uri scheme doesn't work on MacOS 10.11.5, Copay 2.0.1
I have a valid uri, and the system doesn't recognise that Copay is an accepted application.
Even when i manually select it as the default application, uri links still don't open

**Comment by matiu** [comment]
Thanks for the report.

This is a known issue, reported before here https://github.com/bitpay/copay/issues/3994

We hope to  get is fix in the next few version.
