### ISSUE TITLE
UI not responsive immediately after launch

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#4454]
V2.0.1, iOS.

After launch and the UI is presented I can touch (for instance) the hamburger and have the menu open but then the UI is non responsive for about 45 seconds.  Once the UI starts responding it seems fine.  Happens every time I launch from closed.

**Comment by ajp8164** [comment]
Related https://github.com/bitpay/copay/issues/4443

**Comment by matiu** [comment]
This seems to be related to the new  'wallet integrity tests'.  Test result caching was broken in 2.0.1. It should work OK on v2.0.2  (ie: It will take some time on the first boot, but it should take long on the following, only when the OS is upgraded).

**Comment by ajp8164** [comment]
Works good in 2.1.0.  Thanks!
