### ISSUE TITLE
Copay on Ubuntu doesnt work

### ISSUE THREAD

**Issue by santipassa** [bitpay/copay#4455]
When i try to open copay on Ubuntu 14.04.4 LTS it shows me an error message: "Error at Wallet Service : Error de conexion a la red"
![captura de pantalla de 2016-06-18 14 54 33](https://cloud.githubusercontent.com/assets/11557722/16172745/c5400924-3564-11e6-8964-0c51f0f44a4f.png)

**Comment by matiu** [comment]
Thanks for you ticket.

This seems duplicated with:https://github.com/bitpay/copay/issues/3723
