### ISSUE TITLE
Create shared wallet

### ISSUE THREAD

**Issue by ans87gh** [bitpay/copay#4456]
Any time I attempt to create a shared wallet on my MacBook and add my iDevices to it, I get an error message 'bad wallet invitation'. I attempted using the QR code and by pasting the I tire invite. Neither effort worked on iPhone or iPad. Also wanted to ask what devices can create a hardware wallet. It only appears on my iPad and am unable to create it. Thank you.

**Comment by matiu** [comment]
Can you create a test wallet and share a screenshot with wallet invitation code and QR? So we can understand better what is happening?

thanks a lot.

**Comment by matiu** [comment]
Closing until more information is provided.

**Comment by ans87gh** [comment]
Sorry just saw this; attached are screenshots of the shared wallet created on my MBP and the attempted join on my iPhone. I hope this helps And thanks.

![img_0032](https://cloud.githubusercontent.com/assets/12764750/16213522/ad518e46-3758-11e6-88e2-5e7c3230279a.PNG)
<img width="1440" alt="screen shot 2016-06-21 at 2 30 52 am" src="https://cloud.githubusercontent.com/assets/12764750/16213523/ada2194c-3758-11e6-952b-a839ff58ec12.png">

**Comment by matiu** [comment]
I just scanned the QR on a iphone 6 plus (using copayer name hnn) and it worked OK.

( we are waiting for the 3rd copayer).

**Comment by ans87gh** [comment]
alright that's awkward;
could it be that I'm running iOS 10. I wouldn't know why that would interfere with QR recognition and processing, though i have found SSL though the mac is insecure on the MacOS sierra. maybe there is an issue with processing or connecting to the copay server?

**Comment by ans87gh** [comment]
And i just found you - hhh - as the additional user; I'm glad it works on your end!

**Comment by matiu** [comment]
looking at the code, the issue raises before connecting the server.

Thanks for the info that your are using ios10, we do not support ios10 yet, but we are definitely interested to fix this one.

Could you please try to join and immediately  go to 'Global settings > Advanced > About Copay > Session log' and check the ~ 10-20 last lines for an error:

The related code is:
```
      try {
        var walletData = bwcService.parseSecret(opts.secret);

        // check if exist
        if (lodash.find(root.profile.credentials, {
            'walletId': walletData.walletId
          })) {
          return cb(gettext('Cannot join the same wallet more that once'));
        }
      } catch (ex) {
        $log.debug(ex);
        return cb(gettext('Bad wallet invitation'));
      }
```
thanks.

**Comment by ans87gh** [comment]
do you have an email i can send it to you by; i wasn't able to find those lines of code but will use a text editor just to search and make sure

**Comment by ans87gh** [comment]
So emailed it to myself and reviewed it. Couldn't find anywhere that began with walletdata or had the bad wallet invitation entry.
