### ISSUE TITLE
Amount won't allow 0.xx 

### ISSUE THREAD

**Issue by CredibleFriends** [bitpay/copay#4459]
I copied and pasted an amount into copay and the send button was disabled. Very confusing at first. Then I realized it was because of the 0 before the decimal place.

0.6008877781	was the amount I was trying to paste in. Its not an allowed input.
![screen shot 2016-06-20 at 2 01 49 am](https://cloud.githubusercontent.com/assets/3032137/16188620/4cf42b30-368b-11e6-839c-02756bdb2866.png)
![screen shot 2016-06-20 at 2 01 44 am](https://cloud.githubusercontent.com/assets/3032137/16188624/4fd6aaa8-368b-11e6-884f-283e50a8067b.png)

**Comment by dabura667** [comment]
BTC only goes down to 8 decimal places.

0.001234567 will fail (send turns gray)

0.00123456 will succeed.

Yours has 10 decimal places.

Try entering 0.60146205 BTC.

**Comment by CredibleFriends** [comment]
Good catch, Maybe we can improve the UX a bit. I was copying/pasting from google sheets. It should probably round off /not allow any extra spots in the text input box

So 0.6008877781 does not work and .6008877781 does work... in this case the solution I arrived at was removing the "0", but I see that truncating to 0.60088777 would also work

**Comment by dabura667** [comment]
.6008877781 is viewed as 6008877781 bitcoins. You would get an error when trying to actually send.

**Comment by matiu** [comment]
fixed in 2.1.
