### ISSUE TITLE
BTC Private key for pools

### ISSUE THREAD

**Issue by MRePotatoes** [bitpay/copay#4461]
Hey i just wanna know how to get the private key for pools thx =P

**Comment by matiu** [comment]
not sure what you mean

**Comment by MRePotatoes** [comment]
The private key for mining pools, so i can mine bitcoins

**Comment by matiu** [comment]
I believe what you are asking is not correct.

Send us link or screenshot of what you need from the pool and maybe we can help you better. Closing this one until more information is provided.
