### ISSUE TITLE
[2.0.2] [Chrome] Import hardware wallet issue - Wallet does not registered at the wallet service

### ISSUE THREAD

**Issue by mahinzebpay** [bitpay/copay#4464]
Hi there,

First of all thanks for all your hard work. Copay is amazing. 

After 2.0.2 Chrome upgrade it looks like we are having issues in importing 2-3 multisig Trezor wallet. When we try to import it gives us  

"Could not import wallet : Wallet does not registered at the wallet service. Recreate it from creaste wallet using Advance options to set your recovery phrase"

On Create wallet it gives : Error creating wallet : Key already associated with an existing wallet.
Which looks correct as the wallet already exists and we have used it for transactions. 

We are using https://bws.bitpay.com/bws/api as BWS

Is it due to upgrade or we are missing something ?

Thanks and really appreciate what you guys are doing at copay :)

Regards
Mahin

**Comment by mahinzebpay** [comment]
I resolved it with below process
1. Setup new private BWS 
2. Use new BWS to recreate wallet. ( After creation it will not show any transaction history or balance )
3. Change BWS setting to point to original BWS ( bws.bitpay.com )

Would love to understand why this happened, because before this Import hardware wallet used to work seamlessly. 

Regards
Mahin

**Comment by matiu** [comment]
Thanks for your report.

On the first step:
""Could not import wallet : Wallet does not registered at the wallet service. Recreate it from creaste wallet using Advance options to set your recovery phrase"

Could you let us know more details of the options you used? Were you using the correct account, selecting Trezor at the Hardware wallet tab?

thanks

**Comment by mahinzebpay** [comment]
Yes. I was using correct account number. The only thing that was different after getting it working was it does not have address labels and participants show json metadata. 

Regards
Mahin
