### ISSUE TITLE
UI gets in bad state (w/wallet service connection error modal)

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#4466]
V2.0.2, iOS/iPhone 6.

When having trouble connecting to BWS and I get the "Tap to retry" button I tap to retry, and tap, and tap... and eventually I get the white popup telling me there is an error at the wallet service (this is not the problem, at least not here ;-)  The problem is that the UI becomes unresponsive; at the moment I have the popup modal displayed but the button cannot be pressed (modal won't go away).  At the same time, the view behind the modal is able to be scrolled up/down but now button presses are recognized.  And sometimes, pressing OK on the popup dismisses the popup but not the dark backdrop and the app does not respond to buttons.  At this point the app is not functional and I have to kill/restart it.  This is reproduce-able for me.

**Comment by JDonadio** [comment]
I think this is fixed in current version on master. Reopen the issue if the problem remains.
