### ISSUE TITLE
Reset Wallet Spending Password

### ISSUE THREAD

**Issue by gabymansiz** [bitpay/copay#4473]
Hi everyone. I can´t remember my spending password... So, I saw this at Copay FAQ 

> **I forgot my wallet spending password. Is there a method to reset it?**
> 
> There is no way to reset the spending password. However, as the spending password is only stored in the client you could delete your encrypted wallet and import it with the 12 words backup

I'm a newbie. Could someone please, please explain me how to import this wallet? And at which moment should I delete the encrypted one?

Thank you sooooo much.

**Comment by matiu** [comment]
Do you have the 12 words backup?

On Tue, Jun 21, 2016 at 2:00 PM, gabymansiz <notifications@github.com>
wrote:

> Hi everyone. I can´t remember my spending password... So, I saw this at
> Copay FAQ
>
> *I forgot my wallet spending password. Is there a method to reset it?*
>
> There is no way to reset the spending password. However, as the spending
> password is only stored in the client you could delete your encrypted
> wallet and import it with the 12 words backup
>
> I'm a newbie. Could someone please, please explain me how to import this
> wallet? And at which moment should I delete the encrypted one?
>
> Thank you sooooo much.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bitpay/copay/issues/4473>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAGCHNiO2jespVm3lfBmA_PBZ1DDjIeRks5qOBingaJpZM4I69NW>
> .
>



-- 
BitPay.com

**Comment by gabymansiz** [comment]
@matiu yes

**Comment by matiu** [comment]
then you can go ahead, and delete the wallet, and the go to Add new Wallet -> Import ->  and enter the 12 word recovery phrase.

If you want to be sure the backup is correct, you can first import the 12 words into other device running Copay (desktop or mobile).

**Comment by gabrielbazan7** [comment]
Also, you could try importing the wallet in your device : sidebar-> add wallet -> import wallet, and, if you receive a warning that the wallet already exist, it means it's correct. ( make sure that backup is not from other wallet you have on Copay )

**Comment by richardsuns** [comment]
@gabymansiz 
if you have lost tour phrase
the only option is to crack your backup password, if you need help in this regard contact me
