### ISSUE TITLE
Ios app deleted all of its Data

### ISSUE THREAD

**Issue by lello-eh** [bitpay/copay#4478]
I had been using the Copay app on my iphone for a few weeks now, everything was running fine. Last night, I sent a transaction before going to bed. Woke up this morning, opened Copay and fell on the initial set up page with no wallet history. All my wallets had been wiped out. I successfully got one of my main wallets right away with all my balance still intact but my other main wallet does not seem to import properly. I put in the 12 word and import it, yet the import shows no history and the balance is at 0. I sent a little something to the wallet in hopes it was just a bug and it would somehow "jump start it" but it just received them regularly. Help?

**Comment by matiu** [comment]
On one of the wallets that the import does not work, do you see any
transaction? are you using the default wallet service?

**Comment by lello-eh** [comment]
I see no transactions and I am using the default wallet service.

**Comment by matiu** [comment]
On that wallet, can you try:

Settings > Advanced > Wallet Info > Scan Addresses for funds.   Then wait 2-3 minutes and let us know.

**Comment by lello-eh** [comment]
I've done that a few times before, it only shows one transaction which would be 120 bits that I sent to it yesterday. I just tried it again, same results.

**Comment by matiu** [comment]
Can you send a screenshot? The wallet Id will also help. If you prefer to send it in private, send them to matias@bitpay.com

**Comment by lello-eh** [comment]
83673ef2-74b0-4e85-94d6-2ac363877ccb

![image](https://cloud.githubusercontent.com/assets/20080064/16278492/2d4ae2e6-3885-11e6-9417-9ba932dbc2ef.png)

**Comment by matiu** [comment]
I see that that wallet have 7 addresses in total:

"15Ki8E1VcWQNFemmWPBXJdwNxmHJYWh1ZU"

"12UMQ3LWZCXCA7xtitnKwaaHAmP5VFiQY2"

"1BQywFBvtb1DP7pVYSBH385DmmzB9murJN"

"14UG7VpC3Hy244d47NeXjrkTvAbeirHk81"

"1EX4BB3zJX1WkRzSH3gRd7ZFFNWP5Z9oa"

"1ANRzKd72dNPf7sj8ZpUbGPBax95hcdRTr"

"1PUiN5UrS4NNZH1n7kY2TtvVkuCuEMDhno"


and only 12UMQ3LWZCXCA7xtitnKwaaHAmP5VFiQY2

have 1 transaction (
https://insight.bitpay.com/address/12UMQ3LWZCXCA7xtitnKwaaHAmP5VFiQY2)

so  Copay seems to be OK according to this.




On Wed, Jun 22, 2016 at 3:26 PM, lello-eh <notifications@github.com> wrote:

> 83673ef2-74b0-4e85-94d6-2ac363877ccb
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/20080064/16278492/2d4ae2e6-3885-11e6-9417-9ba932dbc2ef.png>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/bitpay/copay/issues/4478#issuecomment-227834211>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAGCHDwX30NdUo8WsIeMWdGPVND_KneMks5qOX47gaJpZM4I7XuC>
> .
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by lello-eh** [comment]
Right, I saw that too. Could it be that the history was deleted and the funds stolen? Also, is it possible that I am importing the wallet using the wrong BWS? Would it solve it if the wallet was using another BWS?

**Comment by matiu** [comment]
> . Could it be that the history was deleted and the funds stolen?

No.

 You can derive the address from the recovery phrase using any external tool, for example:
https://dcpos.github.io/bip39/
then enter the xpub, here for example (https://blockchain.info)
(to scan the blockchain)
and you should get the same results.

If there were transactions, they should be on the blockchain, so there is not possibility of hiding them.

> Also, is it possible that I am importing the wallet using the wrong BWS? Would it solve it if the wallet was using another BWS?
no, the wallet is scanned from the blockchain, the history and balance should be equal in all BWSs.

What could happens is that you could have a passphrase related to the recovery phrase. is that possible?

With a passphrase, the recovery phrase lead to a different seed and then a different private key, so a different wallet. Did you remember setting a passphrase?

**Comment by lello-eh** [comment]
Yeah I think I did set up a passphrase, there are a few words noted down next to my 12 word. How should I proceed then?

**Comment by matiu** [comment]
Import again, enter the 12 work mnemonic AND the passphrase.

**Comment by matiu** [comment]
(the passphrase is in 'advanced' options)

**Comment by matiu** [comment]
Do not go to  'Create Wallet', stay in import wallet.

**Comment by lello-eh** [comment]
It worked !Thanks ! I will email you shortly to thank you for your help ;)
