### ISSUE TITLE
?

### ISSUE THREAD

**Issue by JOSE7781** [bitpay/copay#4494]
i dont know how to use this, i downloaded app on phone...now what?

**Comment by dabura667** [comment]
Tap on the icon to open the app, then Tap Create Wallet after agreeing to the Terms of Service.

Tap "Personal Wallet" and type in a name for the wallet.

Once it's done, tap "Receive" and it will ask you to back up your recovery phrase. Write down the 12 words (these words can recover your wallet in the event of your device blowing up or something. Keep it safe, if someone knows these words they can steal all your coins.

Once you have written the phrase, and tapped in the order, it will show you your first address. This is what you show other people to receive bitcoin from them.

Have fun!

**Comment by JOSE7781** [comment]
How do I receive bitcoins? Also how do I send it to my bank account?   Is there a phone number I can call?

Joseph Stevenson
Senior Account Manager 
800 380 0823 direct line

**Comment by dabura667** [comment]
> How do I receive bitcoins?

The address shown in your "Receive" tab is like your routing number, you must tell it, mail it, or somehow communicate it to the sender in order for them to send bitcoin to you. One wallet will have many many addresses, and every time you receive bitcoins, the wallet address will change (but bitcoins sent to old addresses will still be managed for you, don't worry)

> how do I send it to my bank account?

There are many services that would allow you to convert bitcoin to local currency. I notice you have an 800 number, so you are in the USA. Here are two sites that serve the US (and are regulated fully). Recently Coinbase just started to support PayPal, if you need to convert to USD and want to send via PayPal. Circle has a very quick setup process for withdrawing and depositing via debit card or ACH transfer.

1. https://www.coinbase.com/
2. https://www.circle.com/

> Is there a phone number I can call?

Circle phone number is for **URGENT ISSUES ONLY** apparently
> Call us for **urgent issues** 1-800-398-7172
> Available weekdays 10AM - 4PM EST

And I was unable to find a phone number for Coinbase.

**Comment by dabura667** [comment]
Oh, also, this app, "Copay" has support for selling bitcoin for USD directly from the app using Coinbase... so I would recommend signing up with coinbase. :-D

**Comment by JOSE7781** [comment]
So who do I get the funds from. You guys or coinbase?

Joseph Stevenson
Senior Account Manager 
800 380 0823 direct line

**Comment by dabura667** [comment]
> the funds

If this means "where do I get bitcoins?" then you can do a few things.

1. Convert USD to bitcoins via Coinbase. This requires creating an account on Coinbase, transferring USD to Coinbase, then sending bitcoin to one of your addresses on Copay. (or you can set up Copay to log in to Coinbase FOR YOU and you can transfer USD from your bank to Coinbase, then bitcoin from Coinbase to Copay with one click inside the Copay app.
2. Perform a service or sell goods to someone in exchange for their bitcoins. Most people price their services using USD, and when the person says "I'd like to pay in bitcoin," just look up the amount of bitcoin that will cover the USD cost at that time, then ask them to send your address the appropriate amount of bitcoins.
3. Ask for "testnet" bitcoin. When creating a new wallet on Copay, you can open the advanced options during creation to turn on "TESTNET" mode. These bitcoins are worthless and can not be used on exchanges or at any stores. These coins are great for "practicing using bitcoin" If you want some, send me your TESTNET wallet's address and I will send you some.
4. Bitcoin ATMs, these exist in some places around the US... large fees, but possible.
5. Go to a local meetup of bitcoin enthusiasts near you. meetup.com and search for "bitcoin <your city name here>" without the less than greater than signs. There are usually people there with bitcoin that are willing to sell you bitcoin for cash.

etc. etc.

**Comment by matiu** [comment]
Thanks for your contact.   This system is to track Copay related issues. I think you should check a general bitcoin explanation website, like https://bitcoin.org/en/

We will be happy to assist you with any Copay related question.
