### ISSUE TITLE
can't install copay / actions at wallet cannot be performed

### ISSUE THREAD

**Issue by rullahuuli** [bitpay/copay#4502]
Hi,

I have installed copay to my win8 phone at 2015.
Now copay says at my phone, that Key derivation is not working on this wallet. Actions cannot be performed on this wallet.

I tried to install Copay to my Win8 tablet, but after installation, program says that it's not working on this windows..

How can I access to my wallet?

br,
Jani

**Comment by matiu** [comment]
Hi,

Do you have the 12 words backup of the wallet you are trying to access?

**Comment by rullahuuli** [comment]
Hi!

Yes, I have stored the 12 words backup.
I also have "Personal Wallet-Copaybackup.aes.json" file.

Br,
Jani

2016-06-25 14:47 GMT+03:00 Matias Alejo Garcia <notifications@github.com>:

> Hi,
>
> Do you have the 12 words backup of the wallet you are trying to access?
> On Jun 25, 2016 07:45, "rullahuuli" <notifications@github.com> wrote:
>
> > Hi,
> >
> > I have installed copay to my win8 phone at 2015.
> > Now copay says at my phone, that Key derivation is not working on this
> > wallet. Actions cannot be performed on this wallet.
> >
> > I tried to install Copay to my Win8 tablet, but after installation,
> > program says that it's not working on this windows..
> >
> > How can I access to my wallet?
> >
> > br,
> > Jani
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/bitpay/copay/issues/4502>, or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AAGCHORv2qCEcKLWB2TIEJN-2vLIAWByks5qPQbOgaJpZM4I-Ucd
> >
> > .
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bitpay/copay/issues/4502#issuecomment-228535568>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ATNPvXf1dFahGEv70X46WUWZDNv1NLsOks5qPRVMgaJpZM4I-Ucd>
> .
>



-- 
Ystävällisin terveisin / Best regards,
Jani Sarkula

**Comment by matiu** [comment]
OK good.

To help us determine the source of the problem:
1) What version of Copay are you using on the phone?
2) Did you have a spending password set on the phone?

To solve the issue:
1.If you need immediate access to your funds, you can use the Copay recovery Tool (https://bitpay.github.io/copay-recovery/) to move them. 
2. if you want to try to fix you wallet, you can:
   -  import the wallet on a desktop version of Copay
   - delete the wallet on the phone (in settings > advanced)
   - import it again on the phone.


thanks and sorry for the inconveniences.

**Comment by matiu** [comment]
Please see https://github.com/bitpay/copay/issues/4444#issuecomment-228597117

**Comment by nectareon-technologies** [comment]
please help me to install linux version copay. when installed nodejs on my system, it doesnt work show error as copay package error. i have used latest copay version source code
