### ISSUE TITLE
When creating a transaction proposal without a private key, copay hangs on "signing transaction"

### ISSUE THREAD

**Issue by jojkaart** [bitpay/copay#4503]
While I was testing ledger support on the desktop version, it occurred to me that it'd be handy to use the mobile version to create transaction proposals. I figured I'll see if I can export the configuration to a mobile device and do that. Well, transaction proposal gets created and sent to other parties. However, copay hangs right after. UI is completely unusable and it gets stuck showing the info text "signing transaction".

Also another slight issue is that while the transaction proposal gets created, it doesn't get automatically relayed to the desktop copy of the same subwallet unless you restart it or switch back&forth between wallets, so it resyncs. Other parties in the multisig wallet do get them as normal though.

I didn't test this, but I suspect you'll see the same issues if you export a regular copay wallet without the private key and then import to another device.

**Comment by gabrielbazan7** [comment]
I was able to reproduce it. I'm working in this.

**Comment by gabrielbazan7** [comment]
> Also another slight issue is that while the transaction proposal gets created, it doesn't get automatically relayed to the desktop copy of the same subwallet unless you restart it or switch back&forth between wallets, so it resyncs. Other parties in the multisig wallet do get them as normal though.

It is not posible to distinguish the device that is creating the transaction proposal from another device when both are using the same wallet. However, the are some tickets in Copay to support exporting the wallet without private key to someone with his own identity, but, this idea is not yet being done.

**Comment by snehal-nair** [comment]
Can someone here help me move BTCs between wallets without a private key? Please email on prplx44@gmail.com if you can!
