### ISSUE TITLE
Can't use new wallet because seed backup check is impossible to complete

### ISSUE THREAD

**Issue by franamati** [bitpay/copay#4504]
Using Copay v2.1.0 on iPhone 5s the seed backup check is cropped, last line of words can't be seen, so choosing the correct words is not possible:
![seed backup](https://cloud.githubusercontent.com/assets/8605599/16366115/4ff34f20-3be8-11e6-97b1-2fe189e70658.png)

The same may be happening with iPhone 5 and iPhone SE.

**Comment by franamati** [comment]
Workaround: going to other app and coming back to Copay will make the scroll to go down, making it possible to select the words.

**Comment by matiu** [comment]
thanks for the workaround. we will fix it next version
