### ISSUE TITLE
Set "use unconfirmed funds" OFF by default for new wallets

### ISSUE THREAD

**Issue by isocolsky** [bitpay/copay#4510]
![image](https://cloud.githubusercontent.com/assets/2073468/16418822/d4291d1c-3d21-11e6-96a5-ef7c64cf4f95.png)

**Comment by dabura667** [comment]
With recent network congestion, it would be better to have newbies ask "why can't I send my money when I got it an hour ago?" rather than "I sent my money an hour ago and it's not confirming (due to unconfirmed parents)"

As long as parents are confirmed, Copay fares well even during congestion.

Explaining unconfirmed parents to new users... is not good UX.

So I +1 with condition that if we can ever get CPFP + malleability fixes (segwit) implemented, it should be returned, I think.

**Comment by Derrick-** [comment]
@dabura667  It seems like confirmations need to be explained to new users either way. i don't see new users as a compelling case for this change.

**Comment by dabura667** [comment]
@Derrick- I would rather they pump into our padded cushy wall, where the solution is "uncheck the box and try again" and add an explanation of unconfirmed inputs for good measure...

The alternative is new user panicking and our only solution is "maybe wait for 72 hours and hope it confirms some day??? Maybe??? We don't know..."

The former: worst case scenario Copay loses a user.

The latter: worst case scenario the user loses money and/or Bitcoin loses a user

**Comment by Derrick-** [comment]
I do have concerns about ease for new users. An in-app explanation would be an excellent complementary addition to this change.

One of the many features that i initially liked about CoPay was the default option to spend confirmed; I didn't actually notice the setting until months later.

I do think this change makes sense, and with the explanation it will be an improvement for new users.

**Comment by dabura667** [comment]
Maybe adding text to the warning when the send amount is greater than non-locked confirmed, but less than non-locked unconfirmed, we could suggest in the error message "try enabling unconfirmed spending in the wallet options"

Then when the user enabled unconfirmed spending, show a pop up explaining some possible problems they could run into:

1. Unconfirmed chains with low fees
2. Malleated parents causing the transaction to be nullified (rarer, but plausible)

How these could be explained to a new user........ I don't know... Haha.
