### ISSUE TITLE
lost bitcoin wallet

### ISSUE THREAD

**Issue by matheusHD** [bitpay/copay#4512]
good, my cell phone was stolen, I already bought another and such, but I downloaded the copay again and I can not put my bitcoin wallet that was about 4500 bits, porfavor me help.

**Comment by isocolsky** [comment]
Go to Add Wallet (sidebar menu) --> Import Wallet, type your 12 words backup and you should be ok.

**Comment by gabrielbazan7** [comment]
https://github.com/bitpay/copay/wiki/COPAY---FAQ#how-do-i-get-access-to-my-wallet-in-case-of-loss
