### ISSUE TITLE
Could not create: Invalid wallet recovery phrase

### ISSUE THREAD

**Issue by JulianTosh** [bitpay/copay#4528]
I'm trying to create a new shared wallet with a specific recovery phrase.

Is this possible? Because I'm getting the error "Could not create: Invalid wallet recovery phrase" on all attempts.

Test examples have been: 
```
dolphin source must vote notice bulb acquire release spin doctor gold pen
```
and 
```
usage purpose athlete floor theme cruel plug patrol beauty visual social dad
```

**Comment by dabura667** [comment]
These are both invalid phrases.

How did you generate these?

**Comment by dabura667** [comment]
It looks like all the words in both phrases exist on the wordlist, but the checksums do not match, so they are both invalid.

**Comment by JulianTosh** [comment]
I generated the word lists by randomly picking my own 12 words from the wordlist. Sorry, I was not aware there was a checksum involved. So is there no way for me to pick my own 12 words from the wordlist?

**Comment by JulianTosh** [comment]
I see there isn't a viable method for my purposes. closing. thx
