### ISSUE TITLE
Sidebar UI + Landscape support (on iPad) [iOS]

### ISSUE THREAD

**Issue by tycoonlover1359** [bitpay/copay#4531]
With the newest release of Copay (v. 2.2.0), the sidebar, on iPad/iOS anyway, is always there, which I prefer not to have with such little screen real estate in portrait position. This leads me on to my thing, please add landscape support on iOS! If you're going to keep the sidebar on iOS always showing, then please give us landscape mode so that we won't have to deal with such little screen space and buttons.

**Comment by jkokorian** [comment]
The same in windows 10. Although it is not necessarily a problem, it's also not very usefull. It would be great if it were possible to hide it!

**Comment by gabrielbazan7** [comment]
Hi, 
Landscape support was added in the newest release of Copay. I can't reproduce the fact that the device can't change the orientation. But, I will be working on this. Thanks.

**Comment by Endogen** [comment]
I'm on OS X and don't see a reason why the sidebar should be always visible (right now there is no option to close / hide it). In previous version the sidebar was not there. Any chance to get an option to show / hide it?

**Comment by JDonadio** [comment]
Sidebar was removed. Regarding screen orientation https://github.com/bitpay/copay/issues/4210
