### ISSUE TITLE
memory usage

### ISSUE THREAD

**Issue by BitMari** [bitpay/copay#4532]
Hello
Im having memory issues with my apps , iOS and android .. the apps will be using a lot of memory and thus extremely slow.

On my Firefox console there is this warning 
08:11:46.723 mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create1 angular.js:94:26539

is it related to my issue? Help.

**Comment by matiu** [comment]
Is there anything special about your wallets? To many txs? Or huge txs or many wallets in Copay? We cannot reproduce the memory problems in IOS and Android.

**Comment by BitMari** [comment]
I updated my code to the current copay repo and the issue disappeared.Thanks
