### ISSUE TITLE
bad touch responsiveness on windows phone 8.1 (lumia 640XL)

### ISSUE THREAD

**Issue by jkokorian** [bitpay/copay#4534]
* bringing up the menu's is very slow
* scrolling through the transactions ocassionally fails and instead some transaction's details are shown. When you then press 'close', half the screen remains white.
![wp_ss_20160702_0001](https://cloud.githubusercontent.com/assets/6113878/16542114/a58fb63c-409b-11e6-876f-383119b05e04.png)

**Comment by gabrielbazan7** [comment]
Could you try version 2.2.0 ? Should be an improvement. Thanks

**Comment by jkokorian** [comment]
Thanks for the fast updates! Unfortunately not everything is fixed...

* :-) The size is correct again
* :-) transaction details show fullscreen and close correctly when clicking on them
* :-( No inertial scolling in transaction list
* :-( user interface response is still very slow

**Comment by matiu** [comment]
Closing this one due the the OP bug report is fixed.

Please open new tickets of the other issues so we can track them. thanks.
