### ISSUE TITLE
Hello from SolarCoin

### ISSUE THREAD

**Issue by assaf8200** [bitpay/copay#4535]
Hello,

My name is Assaf Ben Or and i am the CEO of SolarChange (solarchange.co) and we developing and promoting the technology of SolarCoin (www.solarcoin.org). SolarCoin promotes equally Solar Energy world wide where eventually companies, investors and individuals will be more motivated to install and use the free clean energy from the Sun.

We would like to use CoPay for SolarCoin users and promote it in out websites. Would it be possible?

We would be happy to collaborate with you.
Assaf
assaf@solarchange.co

**Comment by dabura667** [comment]
If SolarCoin is a colored asset on colu, someone has already made a fork.

If it's a traditional alt, you will need to port bitcore, bitcore-lib, insight-api, bitcore-wallet-service, bitcore-wallet-client, and Copay.

Depending on how different your alt is from Bitcoin, the workload will vary.

However, we do not support altcoins. Sorry.

**Comment by matiu** [comment]
dup: https://github.com/bitpay/copay/issues/4203
