### ISSUE TITLE
Buy & Sell Bitcoin hard coded

### ISSUE THREAD

**Issue by buch8** [bitpay/copay#4540]
![buysell](https://cloud.githubusercontent.com/assets/18380191/16568267/6c0ba41e-4228-11e6-85a7-0f3878b05965.jpg)
I can't translate the text "Buy & Sell Bitcoin"

**Comment by martindale** [comment]
+1.  I'd like to see this feature completely removed from Copay, and instead replaced with a plugin architecture.  @BitPay can maintain and even include a `coinbase` and `glidera` plugin by default, but this should be decoupled from the base wallet codebase.

**Comment by matiu** [comment]
Thanks.

For the moment, only US based exchanges are available, so we didnt make those strings available to translate because we didnt want to add a lot of extra work for our translators. We plan to add new exchanges  and then we will make those strings available to translate.

**Comment by buch8** [comment]
Well, we translated the sidebar text already. It wouldn't be "lot of extra work" to translate this text too and have a consistent look.

**Comment by matiu** [comment]
agree. the sidebar should be translated. the test inside rhose section no

**Comment by isocolsky** [comment]
Maybe we could make it available for translation with an annotation for translators stating that it is optional and explaining the reason? It wouldn't hurt having this translated in advance for future exchange integrations.

**Comment by dabura667** [comment]
I think this area should be a plugin interface where a user can type in a URL and it will go fetch the exchange's parameters and add the exchange.

Maybe this would be a good BIP for wallets.

A standardized set of parameters to allow for exchange buy and selling through third party apps.

If it was something like that, translating would be good.
