### ISSUE TITLE
Recovery of copay wallet

### ISSUE THREAD

**Issue by silvio333** [bitpay/copay#4543]
Hi there,

My windows OS has broken and i had to reinstall it, so I have formatted the C: drive and reinstalled windows, but forgot that the passphrase was saved on a text document on my Desktop.

I have now used a software to recovery all from my harddisk, and I have found the copay files/databases but not and the passphrase.

Can you please tell me if there is anyway to recover my wallet with the .dat files i have on the old Copay folder or any other ways?

Thanks a lot looking forward for your reply

**Comment by matiu** [comment]
You can restore the Copay files to their original location and then open the Copay app. that will give you access to the wallets, but you still need your passphrase to decrypt your private key and sign transaction. there is no way to recover it from the files.

Do you have the mnemonic backups?

**Comment by silvio333** [comment]
Hi Matiu, thanks for replying.

I don't have too much experience with bitcoin, i hae installed the application after i've been told to create a key to receive a payment in bitcoin, i have the payment prove and everything, so thats why i did those mistakes and didn't saved the passphrase somewhere else than on desktop..

I don't have any idea if i did the mnemonic backup...

**Comment by JDonadio** [comment]
Hi @silvio333, the only way to recover you funds is with backup file or mnemonic words (12 words). Your first step before receive or send funds is get a backup of your wallet, following this

![image](https://cloud.githubusercontent.com/assets/13851807/16588239/a9fbdba0-42a4-11e6-96dc-ce16eccecb43.png)
![image](https://cloud.githubusercontent.com/assets/13851807/16588255/b705543e-42a4-11e6-83ea-5ba316b6a92f.png)

After that, you are able to delete it, uninstall Copay or whatever and import your wallet using that backup.

**Comment by matiu** [comment]
> Is there any way in my case if i have recovered the data with a software to get back access to the wallet? 

I am afraid not. The passphrase is a encryption key, it is not recuperable.  If you dont remember the passphrase, the only option is to import the wallet from the mnemonics.

**Comment by JDonadio** [comment]
I think there is a confusion with term "passphrase", that's the password for the recovery phrase (12 words).

**Comment by dmo580** [comment]
^ BIP39 spec has the mnemonic + a passphrase. Copay specifically allows you when adding a wallet to input the mnemonic and the password/passphrase. Those are two separate fields.

**Comment by Tulipsaki** [comment]
Where in the app do I put in my wallet recovery phrase?  I transferred bitcoin to a new copay wallet this past November, but it's showing nothing there now. And I can't see where to put in the wallet recovery phrase.

Someone help!

**Comment by JDonadio** [comment]
Hi @Tulipsaki,

In Copay: Menu > Add wallet > Import and display de advanced options to see the password field
In BitPay app > Home > '+' on wallet list > Import and display de advanced options to see the password field
