### ISSUE TITLE
Freeze/Hide/Select Inputs

### ISSUE THREAD

**Issue by JulianTosh** [bitpay/copay#4545]
I would like the ability to freeze, hide, and select specific inputs.

**Freeze** would restrict selection when making a payment, keeping the input's value added to the total wallet balance.

**Hide** would remove the input balance from the available balance and make the inputs unavailable for payments.

**Select** would allow you to specify which inputs you would like to use in a payment.

**Comment by matiu** [comment]
This feature seems to be too specific for a general purpose wallet as Copay. Could you explain the use cases? thanks.

**Comment by dabura667** [comment]
Note: Even if it were implemented. This could only be done on 1 of 1 single sig wallet.

**Comment by bitjson** [comment]
If this is trying to achieve privacy goals, it's possible to achieve better privacy (with a far simpler and easier to comprehend user experience) by using multiple wallets. If I want to definitely prevent any two particular inputs from ever becoming linked by transactions, I can simply isolate them to individual wallets.

I think the goal of hiding inputs can be even more thoroughly solved by this work: https://github.com/bitpay/copay/issues/3030

I'm going to close this for now in favor of that issue. Please let me know if it needs to be reopened.
