### ISSUE TITLE
Use dynamic fee when sweeping paper wallet

### ISSUE THREAD

**Issue by isocolsky** [bitpay/copay#4546]
It currently defaults to 100 bits (at 226 bytes this corresponds to a 442 bits/kib which is ok for current network load but could change in the future).

https://github.com/bitpay/copay/blob/master/src/js/controllers/paperWallet.js#L76

**Comment by rodgermoore** [comment]
+1 for this! 👍

**Comment by dabura667** [comment]
Current Master branch already uses dynamic fees for sweeping based on the global config setting.

I believe this should be closed.

**Comment by rodgermoore** [comment]
Ok weird... I just used this feature and it used low priority fee while my global config has the high priority fee setting configured.

**Comment by dabura667** [comment]
which version of the app are you using?

In the about tab it should have a commit hash written somewhere, that would be easiest to find which version you're using.

**Comment by rodgermoore** [comment]
iOS 10.2 / Copay v2.6.0.

**Comment by dabura667** [comment]
https://github.com/bitpay/copay/blob/v2.6/src/js/controllers/paperWallet.js#L72

Looks like the current Copay app does not use dynamic fees. Please wait for the next update, it should be in there.

**Comment by rodgermoore** [comment]
Ok cool, tnx for the quick response!

**Comment by JDonadio** [comment]
Already done [here](https://github.com/bitpay/copay/pull/5107)
Dup  https://github.com/bitpay/copay/issues/5105

**Comment by zuardi** [comment]
Im sorry but Im using iOS 10 / Copay v2.6.0 and it doesnt seem to be implemented.
Third time I sweep a paper wallet with minimum fee and had to wait days...

**Comment by JDonadio** [comment]
Thanks for reporting. We will check it again.
