### ISSUE TITLE
XBT not BTC

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#4548]
Use ISO currency code.

https://en.bitcoin.it/wiki/Bitcoin_symbol

**Comment by HostFat** [comment]
The common Bitcoin user knows it as BTC :)

Maybe it can be added as possibility, but I don't think that it should be enabled as default.

**Comment by ajp8164** [comment]
The common Bitcoin user needs an education.  The longer we wait to make the change the more resistance their will be to make the change.

**Comment by HostFat** [comment]
I'm not following you here, why do you need/want to make this kind of "education" ?

Is there a demand for it? (I mean, other then you)

**Comment by dabura667** [comment]
XBT nope
BTC nope
bits Yup

;-)

**Comment by martindale** [comment]
Let's just use `bits`.  We don't call dollars `USD`!

**Comment by gabegattis** [comment]
Every other BitPay project uses "BTC" as the currency code. All of our existing documentation and customer support language also uses "BTC". Regardless of what we pick, we should try to use the same thing everywhere.

**Comment by JulianTosh** [comment]
It should be noted that XBT is only a logically derived candidate and not an official declaration from ISO 4217.

**Comment by miguelmorales85** [comment]
I think XBT is more of a formal way of calling it, like if you have an exchange platform or something.
BTC is right for most users, I think there was an option no change denomination from BTC to bits.

**Comment by tab00** [comment]
I always use XBT.

**Comment by bitjson** [comment]
Where we're going, we won't need ISO currency codes. 😉
