### ISSUE TITLE
Importing Shared Wallet on Windows Desktop

### ISSUE THREAD

**Issue by rusnewton** [bitpay/copay#4549]
I don't see how to import shared wallet: I have a png image of the QR code & I have tried drag-and-dropping into the Copay 'QR Scanner' under Shared Wallet -> Wallet Invitation but it just hangs at that point

**Comment by JDonadio** [comment]
@rusnewton just go to Menu > Add wallet > Join shared wallet, put your nickname and scan that png

**Comment by dabura667** [comment]
@rusnewton Does your Windows desktop have a web camera attached to it? If not, you can not scan QR codes. The creator of the wallet must send you the invitation code as text instead. (there should be text written below the QR code on their screen.) Then you can paste that into the invitation code area.

So either scan the QR using a web camera, or copy paste in the text code...

dragging and dropping a QR code image file and having it be read is a rare feature, and I don't know of any apps that support such a thing. (though it would be nice)

**Comment by matiu** [comment]
So, to join a  shared wallet you need to paste the invitation code or to scan (using a web cam) the QR code. 

Please reopen if still valid.
