### ISSUE TITLE
Backup fails with 24 word wallets

### ISSUE THREAD

**Issue by JulianTosh** [bitpay/copay#4550]
Summary:
Externally creating a 24 word phrase breaks the backup logic so that it will always show the wallet as not backed up. Attempting the backup process always ends in a failed state.

To reproduce:

1. Create a valid 24 word BIP39 compatible phrase (outside of the CoPay). Example: https://github.com/dcpos/bip39
2. Create a new single signer wallet in CoPay.
3. Unhide advanced options
4. Select 'Specify Recovery Phrase' and input the 24 words
5. Inclusion of a password doesn't matter.
6. Create the wallet
7. When you view the wallet properties, it will show that the wallet has not yet been backed up. If you go through the backup procedure, the 'continue' button turns blue on the 12th correct word you select, then goes gray if you continue to select past the 13th word.
8. If a password was used in the creation of the wallet, you are prompted for the password. Typing in the correct password will result in 'Backup failed'.
9. Press 'continue' with only the first 12 correct words since that's the only way to proceed. This will result in "Backup Failed".

**Comment by matiu** [comment]
Thanks for the report.

When a wallet is created from a specified feed, the "haveBackup" flag should be on already, since the phrase was entered at creation time. We will fix this soon.

**Comment by JulianTosh** [comment]
What about the issue where selecting the first 12 words is sufficient to continue the verification process? There should not be enough seed to pass checksum with 12 words, no?
