### ISSUE TITLE
wallet update of 07/07/2016 too much zoom

### ISSUE THREAD

**Issue by mpumzi** [bitpay/copay#4554]
This update of today has toomuch zoom out
And it doesnt scroll smoothly on microsoft 535 and the sside panel it takes allmost the entire screen please reduce zoom out to 75% or just add screen option to zoom the display according to our needs ...because last update was having a toomuch zoomin now you did the exact opposit ...and this update started in chineese language later it changed to english

**Comment by JDonadio** [comment]
What device and operative system are you using?

**Comment by matiu** [comment]
@JDonadio microsoft 535

**Comment by matiu** [comment]
should be fixed in 2.2 

(https://github.com/bitpay/copay/issues/4534)
