### ISSUE TITLE
"Lock" app with PIN, fingerprint, or password

### ISSUE THREAD

**Issue by ivorpad** [bitpay/copay#4555]
I would like to have an option to hide the main balance or maybe lock Copay and open it with a PIN or Touch ID like Circle.app.

<img src="https://cloud.githubusercontent.com/assets/52452/16659212/27453f82-4437-11e6-9a86-239a5575765d.jpg" height="200">

**Comment by JDonadio** [comment]
Try to tap and hold balance for 1-2 seconds.

**Comment by ivorpad** [comment]
@JDonadio Yes I know but the balance should be hidden once I close the app.

**Comment by JDonadio** [comment]
The balance remains hidden if you close/open or pause/resume the app.

**Comment by gabegattis** [comment]
https://github.com/bitpay/copay/issues/3924 is a very similar issue. It was closed when https://github.com/bitpay/copay/pull/3872 was merged.

When I restart copay, the balance remains hidden for me. If it does not for you, that would be a bug. Do you have multiple wallets in Copay? The hidden balance feature is wallet specific, not a global setting.

**Comment by JDonadio** [comment]
> The hidden balance feature is wallet specific, not a global setting.

That's very important ;)

**Comment by ivorpad** [comment]
>When I restart copay, the balance remains hidden for me.

Agree, but anyone could grab your phone (let's say their checking in your photos with your permission) then out of curiosity they open Copay, 2-sec hold into Copay's balance and see it. It does not ask for a PIN, and for me this is a _security_ concern. 

I would like my balance to remain **private**. In BreadWallet if you want to check your balance you must enter a 4-PIN or Touch ID.

**Comment by gabegattis** [comment]
Ok. I see what you are saying. I think the proper solution would be to have a way to lock the entire app. That way someone couldn't even open the app at all, much less see your balance, without the password, touchid, etc.

What do you think of that?

**Comment by ivorpad** [comment]
@gabegattis That would pretty nice to have. 

I was googling around and found this: https://github.com/AlexDisler/ionic-lock-screen

**Comment by dabura667** [comment]
tbh, if you leave your device unlocked, no amount of software PIN screen will protect your data.

If you don't have a strong PIN set on iPhone or a strong password or pattern set with Android disk encryption, you're vulnerable.

That said. Unless it brings up some sort of bug, adding the feature shouldn't hurt. Electrum's Thomas V said this kind of stuff lowers security way back and is why Electrum doesn't do it.

I like the way breadwallet does it.

There should also be sanity checks. Having privacy locked but leaving spending open with no password or touchID, for instance, should not be allowed.

**Comment by dabura667** [comment]
fyi Electrum's situation is different, being a desktop wallet, the biggest threat is keyloggers. Electrum said that 99% of users, if asked to set two passwords for viewing and spending would choose the same, or similar passwords for both. Since the viewing password would be entered frequently, it increases the attack vector significantly, and if they actually use two unique passwords, it increase the already high rate of "I forgot my password and didn't back up my phrase" incidents.

Food for thought, as we support desktop.

**Comment by dabura667** [comment]
So I guess my reluctant ACK is under condition of mobile only... And don't enable by default.

**Comment by ivorpad** [comment]
>There should also be sanity checks. Having privacy locked but leaving spending open with no password or touchID, for instance, should not be allowed.

@dabura667 IMHO both balance and spending _should_ be protected by PIN, pattern or Touch ID. That's how BreadWallet works.

**Comment by dabura667** [comment]
That's what I said...

**Comment by ivorpad** [comment]
Yeah, well... Exactly. ;)

**Comment by robbiehanson** [comment]
> anyone could grab your phone (let's say their checking in your photos with your permission) then out of curiosity they open Copay, 2-sec hold into Copay's balance and see it. It does not ask for a PIN, and for me this is a security concern.

I've showed this app to about a dozen people, and every single one of them has had this exact same concern. (And I do too.)

> I think the proper solution would be to have a way to lock the entire app. That way someone couldn't even open the app at all, much less see your balance, without the password, touchid, etc.

I can't think of any banking software that doesn't work this way.

For me, the lack of this feature is a glaring hole in an otherwise excellent wallet.

**Comment by dmo580** [comment]
Why is this an iOS issue only? This should apply to Android too. Having a secure PIN/fingerprint lock is important for financial apps like this. There's a reason Venmo, Mint, Personal Capital, Banking apps, etc all have PIN options or lock upon exit.

**Comment by JDonadio** [comment]
Done.
