### ISSUE TITLE
Button to reject a transaction proposal is not displayed

### ISSUE THREAD

**Issue by gabegattis** [bitpay/copay#4556]
I have a single-sig copay wallet. On a separate server I am using a non private key backup of that wallet to create transaction proposals. I am trying to accept/reject those proposals from the copay gui. Copay displays the button to accept the transaction proposal, but does not display the reject button. At the bottom of that view, it does give me the option to delete the proposal, but I need to be able to reject it, not delete it.
![copayrejectbutton](https://cloud.githubusercontent.com/assets/4419243/16663914/fdd07c74-444b-11e6-8696-e144d250309e.png)

**Comment by matiu** [comment]
Its a feature, no a bug!

Maybe we can add it. We use to have it there, but users request to be removed since in single owned wallet reject your own transaction seems to make non sense (But, I do see value the case you are mentioning)

**Comment by JDonadio** [comment]
Functionality added in the new design
