### ISSUE TITLE
Copay hanging when canceling fingerprint scanner

### ISSUE THREAD

**Issue by isocolsky** [bitpay/copay#4557]
To reproduce: 
* Set up fingerprint protection.
* Sign a payment proposal but hit "Cancel" on fingerprint popup.
* "Signing transaction" spinner stays on forever...

**Comment by matiu** [comment]
Could not reproduce it this one (on Galaxy S7) not in 1-1 wallet nor in 2-2 wallets.

**Comment by isocolsky** [comment]
Sorry, it seems to only happen on multi-sig. I created a payment proposal from my PC and tried to apply the last signature on my phone. Canceling the fingerprint verification lead to this screen:

![image](https://cloud.githubusercontent.com/assets/2073468/16732119/ef5119a2-4751-11e6-8a8b-5d8c13e4d918.png)
