### ISSUE TITLE
Can't scan recovery phrase

### ISSUE THREAD

**Issue by JulianTosh** [bitpay/copay#4559]
I am attempting to import a wallet. I wish to use the camera to read a QR code of the recovery phrase, but it displays "Incorrect code format".

What is the correct code format?

Attached is the QR code with words to reproduce.

Words: immune blanket doll end age tumble fold denial safe gift explain surprise develop hazard fun close debate oak when gorilla include favorite entry warrior

![copaywords](https://cloud.githubusercontent.com/assets/627143/16692601/615e6234-44e6-11e6-96de-54e14c300333.png)

**Comment by matiu** [comment]
note this is an imported 24 word mnemonic.  QR export/import should be probably limited to Copay's 12 words

**Comment by isocolsky** [comment]
The import code expected by Copay has the format:
```
<type>|<words>|<network>|<derivation_path>|<has_passphrase>
```

where `type` should be `1` for mnemonics, `network` one of `livenet`/`testnet`, most common `derivation_path` should be `m/44'/0'/0'` for livenet & `m/44'/1'/0'` for testnet. `has_passphrase` is either `true` or `false`.
Note: there is nothing in the import procedure that prevents 24 words mnemonics. The only constraint is the code density used in the export UI but I guess if you are generating the code, it should be ok.
Hope this helps.
