### ISSUE TITLE
[BUG] No private key option and warning text remain on QR export screen

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#4561]
Reproduce:

1. Open export wallet
2. Open advanced
3. check the no private key button
4. tap QR option on the upper right
5. notice that the no private key button and warning text remain, BUT the QR still contains the xprv private key.

-----------------------

Recommended method of fixing:

1. Allow for exporting via QR without private key (include xpub instead of xprv)
2. remove button and warning text tags when switich over to QR screen.

I vote for # 1 personally :-D

**Comment by JDonadio** [comment]
Exporting without private key (using xpub) is not supported yet, but we'll to include this in the next release. For that reason there is not a switch to exclude the private key in the QR tab.

**Comment by dabura667** [comment]
In that case, it's a bug.

The screen says "it will not export the private key" directly below the QR... But it exports the private key.

**Comment by JDonadio** [comment]
Oh I see your point, advanced options should not be displayed on QR tab. Thanks for report this!
