### ISSUE TITLE
OSX: Options are over scrollbar

### ISSUE THREAD

**Issue by Endogen** [bitpay/copay#4563]
If the boolean options in the settings are enabled then they overlap the scrollbar

![copay_scrolling](https://cloud.githubusercontent.com/assets/226475/16707543/d0047f60-45d2-11e6-9b5d-1458fac91790.jpg)

**Comment by JDonadio** [comment]
What OSX version are you running? I cannot reproduce it with latest version of Copay (2.2.0) and OSX 10.11.3

**Comment by Endogen** [comment]
Copay 2.2.0 & OSX 10.11.5

**Comment by matiu** [comment]
I could reproduce it on OSX 10.11.5. it can be seen only while scrolling the screen .

**Comment by Endogen** [comment]
This is still there in 2.6.0
