### ISSUE TITLE
iOS 10 - Can't send any coins

### ISSUE THREAD

**Issue by kreuzberg** [bitpay/copay#4564]
Hey,

I'm on the Open Beta from iOS 10. I can't send any btc to any adress. I always get the message 'adress not valid' even when I try to send it to another copay wallet. There many graphic glitches and you can't hide the keyboard. Are there any iOS 10 Updates planned in the near future?

**Comment by JDonadio** [comment]
Please try to use another platform ([chromeapp here](https://chrome.google.com/webstore/detail/copay/cnidaodnidkbaplmghlelgikaiejfhja)) to run Copay and restore your wallet there. We'll to investigate this case and keep you posted. Thanks for the report.

**Comment by nickwnola** [comment]
Thanks this worked and I have access to my coins on my computer.  Can't wait for the update.  Love the wallet.

**Comment by matiu** [comment]
Closing this one in favor of: https://github.com/bitpay/copay/issues/4570
