### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by nickwnola** [bitpay/copay#4566]
Wallet completely unusable with iOS 10 beta.  

Receiving errors and camera unusable.  Bitcoin addresses get error when trying to send funds

**Comment by JDonadio** [comment]
Related https://github.com/bitpay/copay/issues/4564. @nickwnola, please follow that thread to be updated. Thanks for the report!

**Comment by matiu** [comment]
Closing this one in favor of : https://github.com/bitpay/copay/issues/4570
