### ISSUE TITLE
Disable scrolling for amount input

### ISSUE THREAD

**Issue by CredibleFriends** [bitpay/copay#4567]
Accidentally happened to me today.  Not a big deal because there is a confirmation screen, but sometimes users click the confirmation hastily... perhaps it should be disabled. Bumping the mouse just a tad made it jump quickly from 0.002 btc to 5 btc

http://stackoverflow.com/questions/9712295/disable-scrolling-on-input-type-number

**Comment by matiu** [comment]
good point,. thanks for reporting.
