### ISSUE TITLE
support IOS10

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#4570]

**Comment by cmgustavo** [comment]
XCode 8 is still very unstable to guarantee that Copay works on iOS 10 correctly. We 'll keep you informed about any progress. 

Note: The final version of iOS 10 will be released in fall

**Comment by kreuzberg** [comment]
Any updates? Final release is in around 30 days.

**Comment by gabegattis** [comment]
@matiu @cmgustavo https://github.com/bitpay/bitcore-build/pull/37 Bitcore-lib tests were failing in firefox 48 (the most recent update). Some of the test failures included the "chainCode has not the expected size: found 64, expected 32" errors. It seems like there was some kind of buffer problem that browserify could not deal with in newer browser versions

Updating browserify might fix the specific error seen in https://github.com/bitpay/copay/issues/4649.

**Comment by matiu** [comment]
thanks for the notice @gabegattis we will update BWC asap.

**Comment by JDonadio** [comment]
I'm testing IOs 10 on iPhone 6+ using the latest version of Copay (2.5.0) from AppStore and it's working fine. I made many test like create, delete, import, join, send, receive, etc. @kreuzberg @nickwnola can you try again and tell me if the error remains? thanks!

**Comment by matiu** [comment]
Fixed in Copay 2.6

**Comment by xelawafsTemp** [comment]
I have the same issue for several android devices with v 2.5. The thing is I can't upgrade to 2.6 right now, the fork we are using has significant differences. I and need a patch though for my current version. What fix was put in 2.6 to solve the issue?
