### ISSUE TITLE
Wallet

### ISSUE THREAD

**Issue by WIIZZPL** [bitpay/copay#4586]
My phone for no reason deleted EVERYTHINK and I can't get acces to my wallet and when I'm using recovery code it isn't working can you help?

**Comment by JDonadio** [comment]
Try to create a new wallet and use [this tool](https://bitpay.github.io/copay-recovery/) to move your funds there.

**Comment by JDonadio** [comment]
Please, can you give me more information about this? We need to know what happend. Thanks!

**Comment by WIIZZPL** [comment]
I don't really know what happend I turned my phone off beacuse I had some photos on micro sd card. And after I turn it i have lost every cookies in browser and information about copay wallet when I opened copay it's showed the same screen that i had when i opened it first time ever

**Comment by WIIZZPL** [comment]
oh and if I said somethink wrong (grammar) I'm sorry my English isn't perfect

**Comment by JDonadio** [comment]
Ok, thanks for clarify that. Probably your phone removed some data stored by Copay, but don't worry because your funds are still there. Try the option I gave you and tell me if you are ok.

**Comment by WIIZZPL** [comment]
Ok thanks but as i said in last comment my english is not very good and i don't really know what all that means -_-

**Comment by isocolsky** [comment]
When you first created your wallet, Copay gave you 12 words. Did you write those words down?

**Comment by WIIZZPL** [comment]
yes ... on phone and now they are dead -_-

**Comment by isocolsky** [comment]
Without those 12 words there is not much you can do to recover the funds.

**Comment by WIIZZPL** [comment]
ugh well at last i didn't had much on it

**Comment by isocolsky** [comment]
Remember to always write the phrase down and keep it safe. Preferably more than one copy, just in case. Good luck!

**Comment by WIIZZPL** [comment]
ok thx

**Comment by JDonadio** [comment]
Also you can use the export wallet option to get and additional backup data ;)
