### ISSUE TITLE
Lost Bitcoins

### ISSUE THREAD

**Issue by Elescuarno** [bitpay/copay#4599]
My mobile just die, I had some bitcoins with Copay. I still have the seed. can I recover them with that?

**Comment by gabrielbazan7** [comment]
https://github.com/bitpay/copay/wiki/COPAY---FAQ#how-do-i-get-access-to-my-wallet-in-case-of-loss

**Comment by Elescuarno** [comment]
@gabrielbazan7 Thx a lot mate
