### ISSUE TITLE
Renewed Focus on User Experience

### ISSUE THREAD

**Issue by martindale** [bitpay/copay#4600]
@ajp8164's comment from #4223 is on point:
> Copay is already hard to use and is getting more difficult for the average person. Many of the "advanced" features of Copay should be buried in a "developer mode" that is off by default.

From what I recall, one of the original objectives of the Copay wallet was to provide the best possible user experience for a Bitcoin wallet.  Extending that beyond today's current state of affairs, it would follow that Copay's vision includes **building the best possible payment experience**.

It seems that through continued development of the Copay product has made it more and more complex, which is a result of the fantastic effort being made into making it a full-featured wallet.  It would make sense for Copay to now renew its efforts to delivering a good payment experience, in

1. **Simple multi-signature wallet setup.**  Allow the user to select from two or three common configurations, including the 2-of-3 arrangement that replicates today's two-factor auth for most services (that's a mobile phone, a computer, and third backup key).  This is also an opportunity to open an "application marketplace", where a list of third-party key-holders can be supplied (like BitGo, cc: @jlopp) for convenience.  **Perhaps an open-source "signature policy server" could be constructed for people to host their own!**
2. **Addition of a new "~~Developer~~ Advanced Mode"** which exposes the more complex technical components, such as fee policies and wallet server configuration, to the desiring user.
3. **Addition of a Directory,** listing the nearest physical locations where Bitcoin can be spent.  BitPay has the largest directory of Merchants in the Bitcoin ecosystem, so it is surprising to not have seen this integration already.
4. **Lead the effort to research Bluetooth and NFC payments**, eliminating the ugly and inconvenient QR Code once and for all.
5. **Lead the effort to integrate payment networks** (like Impulse and Lightning) into the Wallet, abstracting the user away from the distractions of how a decentralized network functions.

It's time for Bitcoin to level up, and Copay can be a major part in this.  Let's renew our promise to the community and start leading the charge for payments, leveraging the massive amount of work that we've put in to making Copay so far.

**Comment by KeyJockey** [comment]
In general I'd like to agree with the sentiment of this post, but in fact any software must always struggle with the balance of ease-of-use versus power features.  This is a basic problem and never ending struggle, and the usual "way out" is, best method, via strong *DESIGN* principles and focus on user-first POV, in my opinion... but that is easier said than done.

One thing I see Copay straying away on lately is with the fairly non-essential added features like Coinbase and Glidera integration... especially since Glidera is only available in, what?  11 States of the USA only?  How is that really useful for the vast majority of users?

Prioritizing features like this -- even before something very NEEDED (and, should be, simple) --like allowing advanced users to precisely edit the transaction's miner fee value -- makes it seem to me like development priorities here are somehow severely out of whack...

Copay's done a lot of things RIGHT!  Despite flaws it's still my favorite wallet, bar none, but I think it can still become much better... so, yes, in general I'd support OP's post premise that the entire Copay dev team and BitPay's management (supporting this project) should all try and take a step back here, to try and re-prioritize this project, going forward, with a stronger renewed focus and emphasis on **User Experience** and **UI Design.**

**Comment by dan-da** [comment]
#1 @KeyJockey.    #1 @martindale.  

I agree it is time for CoPay to "level up".  I also agree the coinbase and glidera features were not time well spent, at least from my perspective as I will never use them.  

Personally, the features I would most like to see worked on are:
  1) creation of readonly copayers via the UI.  ( It is technically possibly now via backup, but so hidden as to be invisible. )
  2) Add a signer to an existing wallet.
  3) revocation of signing authority.

 I view both of these features as being core to Copay's mission as a multisig wallet.  They facilitate the following tightly linked real-world business use cases:
  1) A secretary or third party service eg payroll processor that prepares payments but has no authority to authorize (sign) them.
  2) when the secretary leaves the company or changes position, their key should be revoked.
  3) when a new secretary fills the position, a new key should be issued.

Additionally, these features would enable other use cases such as:
  1) A new CFO is onboarded that needs a signing key, in addition to existing signers.  We want to change 3 of 5 wallet to 4 of 6, yet retain transaction history.
  2) We want to give a readonly key to a 3rd party accountant so s/he can review or download the tx history at any time.

I understand there is technical difficulty with key revocation in bitcoin.  Still, I don't see why a new wallet couldn't be created under the covers using keys of the cosigners that are not being revoked, and still retain previous tx history.

To me, getting this functionality RIGHT would enable more serious use of Copay in organizations large and small.

**Comment by Derrick-** [comment]
For me, Copay is a powerful wallet and has no peer for the functionality I am looking for. That being said, it could be more useful to me and often I find that I may be going against the grain with my requests, as things like sending to multiple addresses are features that I'd much like to see available as well.

While I agree that it should remain easy to use initially, some sort of "Advanced mode" would be very valuable to me. I recommend against calling it "Developer mode"

Some people who start using bitcoin will pick up the concepts fast, and once they are ready to do things that are more complex, I think that Copay should be ready for those users and have those features available to them, optionally. 

Being able to separate "advanced" features from basic features may help resolve some of the conflict between feature requests and the Copay objectives.

**Comment by matiu** [comment]
Thanks for this ticket.  Regarding the items:

1. Definitely, that is priority: Dup:  https://github.com/bitpay/copay/issues/4405
2. That is currently Settings -> Advanced. It seems to cover the same objective to me: Hide advance features to first users.
3. Dup: https://github.com/bitpay/copay/issues/3940
4. I tend to disagree. It seems to me that NFC/Bluetooth cannot yet cover all the user cases QR have currently, eg the most common one: Scan a BIP21/BIP70 QR code in a web page from your phone.
5. When time is appropriate, we will definitely look at this.

I am closing this general ticket so we can discuss each item on the corresponding ticket. Please fell free to create new tickets as need for the missing items.
