### ISSUE TITLE
iPad Settings not working

### ISSUE THREAD

**Issue by creativable** [bitpay/copay#4601]
Im using Copay on iPad mini 2. The current version 2.2.0 setting on top right corner is not working. Nothing happen when tapped. Previous version was working fine. The current version is working on iPhone though.

**Comment by JDonadio** [comment]
Copay 2.3.0 is the latest version, can you please upgrade it on your iPad and tell me if the error remains? Thanks!

**Comment by creativable** [comment]
I already tired redownloading Copay from App Store. The version is still 2.2.0. App Store page state the latest version is 2.2.0. But I notice version on computer is 2.3.0. How do I upgrade version on my iPad?

**Comment by matiu** [comment]
2.3.0 is still under review on the app store. it should be available later
today.

**Comment by JDonadio** [comment]
@creativable try now, it's available now 👍

**Comment by creativable** [comment]
Setting gear is still not working on 2.3.0. I still can't access settings.

**Comment by creativable** [comment]
I don't know what happen but setting is now accessible. Thanks!

**Comment by JDonadio** [comment]
Ok thanks for the report!
