### ISSUE TITLE
Recover last word from seed in multisig wallet

### ISSUE THREAD

**Issue by capgros** [bitpay/copay#4604]
Hello,

I created a shared wallet with a friend. He formated his mobile and then realized he just only had 11 of the 12 words to recover his wallet. The one that is missing is the last one as it was on a piece of paper that got broken.
I've read that the last word is a Checksum, is it posible to recover this last word? I've been playing with https://dcpos.github.io/bip39/ but I don't really know how to do it.

Could anybody help with that?
Thank you!

**Comment by dabura667** [comment]
I'll write up a script for you when I get home in an hour or so, hold on a second.

Was it an English phrase? Or were the words in a different language?

**Comment by dabura667** [comment]
@capgros I was able to make a script that does what you need, but I must let you know:

Even if we remove the checksum, there are 128 possible words it could be.

Is it a lot of money?

**Comment by dabura667** [comment]
https://gist.github.com/anonymous/8631e091999904d4cd514c966b5b40c4

This can be run in python, just copy paste into a text file, change the 11 word phrase at the end, and save as .py file, then run in python. (Mac has python pre-installed)

**Comment by capgros** [comment]
Hello @dabura667.
Thank you for your help. It's not a lot of money but it's significant for us.
The words I'm using are from spanish dictionary, I've changed the array myself but it looks like UTF8 has some complications.
I'm still working on it.

**Comment by dabura667** [comment]
I can fix that.

For spanish words you must normalize the input from the user with NFKD unicode normalization first.

**Comment by dabura667** [comment]
All of the spanish words are NFKD normalized in the list already, so you need to add a step in the function to normalize the input.

**Comment by dabura667** [comment]
import unicodedata

text = unicodedata.normalize("NFKD", text)


Do the above to the phrase input at the very beginning of the method.

**Comment by dabura667** [comment]
Also, in case you didn't do so already, you should change all strings in the file to unicode strings by adding u to the beginning of the quotes.

u"donde" as compared to "donde"

Don't forget the u for the phrase input at the bottom as well

**Comment by dabura667** [comment]
https://gist.github.com/anonymous/93c44c97fc061ad7936077688172136d

Here, this will output a file, in case your on windows (the cmd window hates unicode most times)

It will output a file with all 128 possible valid words for the 11 word combo you enter.

**Comment by capgros** [comment]
@dabura667 Thank you for your help! It worked wonderfully. I'm really gratefull you are helping me. I've been trying to do this for more than a month without any result.

It has worked and given me 128 possibilities. I've tried all of them in copay "import wallet" without luck.
I've also tried in joining a shared wallet with the original invitation and all the combinations of the seed without succeding.

Maybe I'm doing something wrong or there's something I'm missing.

- I have the original wallet configured in copay in my mobile and my laptop. 
- I've  got the invitation. 
- I have 128 possible seeds for the second multisig wallet that I want to configure in my desktop computer.

I'm abusing at your kindness but, do you have any idea how I can do it?

**Comment by dabura667** [comment]
@matiu

Any ideas?

I don't have access to the database, but if you could send @matiu the wallet id then he could tell you the xpub of the mnemonic you are missing which would help with brute forcing to find the correct one locally.

Are you absolutely sure the missing word is the last one?

**Comment by capgros** [comment]
In my wallet (copay I've got installed in my mobile and laptop)  I can see the wallet ID, the extended public keys (mine and for my copayer friend) and all addresses created. Right now I'm not sure it was the last word. It looked obvius when we first realized it but maybe we were wrong.

I'm trying to recover the wallet with the tool at https://bitpay.github.io/copay-recovery/ puting my menmonic and testing all the possible mnemonics generated with your script as my friend mnemonic. I'll tell you if I succed.

**Comment by isocolsky** [comment]
Hi! Maybe I can help. Take a look at https://gist.github.com/isocolsky/b3a73aa6b33065b6f8d8396be8ecf5cc
The script will go through a list of candidate mnemonics (in a 'mnemonics.txt' file) checking each one for activity on the blockchain. Try it with a wallet you know has had some activity first so you know its working.
Let me know how it goes. Good luck!

**Comment by capgros** [comment]
Hello,
Sorry for the late response. I've not had much time last days to do the tests.
Thank you very much for the help you are providing, I'll check the script and run it with my wallet to sse it works. 
Maybe as it's a multisig wallet I'm not approaching it correctly... I'm a bit lost on this.
Any way I'll keep checking.
Again, thank you for the help!

**Comment by capgros** [comment]
I've tried with my spanish mnemonics and it just says invalid mnemonic.

Do I have to put the 11 words and add the mnemonics,txt with the variations?

Thank you!

**Comment by dabura667** [comment]
In scan.js, you want to replace the KNOWN_MNEMONICS array (it currently has English in it) string with the mnemonic of the other copayer (which you know is correct)

Then you must make mnemonics.txt file with all 128 possible 12 word phrases in Spanish separated by a LF line break (not CRLF like Windows uses)

Then run it.

**Comment by capgros** [comment]
I've runned it!
None of the addresses given had any activity.
So I have to think that maybe is not the last word that is missing but some other.
I've modified the python script so it gives me every possible combination in any position and passed the result to @isocolsky script and no addres has had activity.
I've the modified @dabura667 python script here: [https://gist.github.com/capgros/1c72bf27e110e6d641450f28c957faf5]
Is my first python script so maybe I did something wrong.

**Comment by matiu** [comment]
Marking this issue as closed since it is not a Copay specific issue. Please feel free to continue the discussion on this thread.

**Comment by capgros** [comment]
I've done it!

I checked in copay the first address created and it had no funds. So I modified scan.js to check addresses against this first address and it was there! (First node script for my by the way)

Thank you very much to all of you!

**Comment by dabura667** [comment]
Great to hear!
