### ISSUE TITLE
Old Version Can't Connect

### ISSUE THREAD

**Issue by KeyJockey** [bitpay/copay#4607]
Hey Copay People... help! 

I'm using an old version on my iPhone (v1.1.2) and ALL DAY today it's been struggling to connect to update balance and transaction history. 

The newer version running via Chrome extension on my home computer seems to be okay so thankfully I'll still have access to move my bitcoins if something is seriously broken here, BUT I'd still prefer to be able to keep using this old version on my PHONE if at all possible ...?

Has something changed recently - maybe with the BWS system - that could be causing this problem??

**Comment by dabura667** [comment]
I had the opposite problem:

My Copay for iOS updated and I couldn't connect to my BWS.

I upgraded BWS and it worked fine.

Perhaps something broke compatibility... What do your logs say?

**Comment by matiu** [comment]
It could be an issue related to Cloudfare. Check that you can access 

https://bws.bitpay.com/bws/api/v1/version

from that device. It could be that Cloudfare is banning your IP.


We did not change anything on BWS / BWS's servers in the last 2-3 days.

BTW, it is a VERY bad idea to use a version that old. We do not support it by any means and it literally has dozens of (already discovered and fixed) errors on it. Your bitcoins are in high risk, please upgrade.

**Comment by matiu** [comment]
(sorry, I closed this one by mistake)

**Comment by KeyJockey** [comment]
My Mac version is the same, and same problem... just can't connect except sporadically and then it retrieves balance but no transaction history.

Opened the copy of the wallet installed into Chrome extension on an old Windows laptop and seems to be working fine there... so I can get my bitcoins off the wallet from there if necessary.  I'll do that later tonite just as a precaution probably...

As you know I have been using these old versions JUST until (some day? hopefully?) we will get better miner fee control in the updated Copay.  IF my bitcoins are really at some risk due to that, then I suppose I'll have to grudgingly finally update to the newest version everywhere BUT I am really not gonna be happy about it.

Can you give me some HOPE that my UI DESIGN ISSUE / complaint about Advanced Users getting more precise control over setting the transaction's miner fee MIGHT be addressed some day soon??

If you can give me a shred of hope that will help me feel better about *having* to upgrade now, to "protect" my bitcoins from any old bug/flaw in old verson Copay (but, really, up to today it's been working fine and I have no other complaints... what could go wrong really?  HOW exactly are my bitcoins at risk...??)

**Comment by KeyJockey** [comment]
P.S. Doesn't seem to be a CloudFlare issue... my iPhone connected to that link and returned a mostly blank  page that says, " { "serviceVersion":"bws-1.9.0"}

**Comment by KeyJockey** [comment]
Well, I don't know what changed BUT it's better now... everything working okay again, both OLD and NEW versions, all good.

So I suppose this issue can be closed, but any idea WHAT was going on today that may have caused this?  Would be nice to know for the future in case it may happen again.

**Comment by matiu** [comment]
We did not had reports from other users or our monitoring system so I guess must be some local networking problem.

**Comment by KeyJockey** [comment]
Well I tried thru my home wifi first, then over the phone's 4G, then out at a coffee shop on their public wifi but in all cases it wasn't the local network as far as I could tell.

Anyway, it's seemingly resolved itself so -- knock on wood -- hopefully won't come back :smile:
