### ISSUE TITLE
copy and paste 

### ISSUE THREAD

**Issue by timstar25** [bitpay/copay#4608]
Hi, how do you copy and paste and address into my copay bitcoin wallet ? Ive tried to make a purchase but for some reason i cant copy and paste the address in to my wallet . i can copy the add ok but it wont paste onto the wallet ,

**Comment by JDonadio** [comment]
What platform and OS version are your running?

**Comment by timstar25** [comment]
Im using windows 10 . 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Javier Donadío <notifications@github.com> Date: 19/07/2016  21:17  (GMT+00:00) To: bitpay/copay <copay@noreply.github.com> Cc: timstar25 <timstar25@hotmail.co.uk>, Author <author@noreply.github.com> Subject: Re: [bitpay/copay] copy and paste (#4608) 
What platform and OS version are your running?

**Comment by matiu** [comment]
Can't you copy the address into the `To` field in the `Send` tab of your wallet?
<img width="459" alt="copay_-_multisignature_wallet_and_slack" src="https://cloud.githubusercontent.com/assets/98844/16983787/d6b50e2e-4e4c-11e6-9774-0c59cd72abfd.png">

**Comment by timstar25** [comment]
No.i cant. Thats the problem. Can copy address but it wont paste on to the send tab 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Matias Alejo Garcia <notifications@github.com> Date: 20/07/2016  11:37  (GMT+00:00) To: bitpay/copay <copay@noreply.github.com> Cc: timstar25 <timstar25@hotmail.co.uk>, Author <author@noreply.github.com> Subject: Re: [bitpay/copay] copy and paste (#4608) 
Can't you copy the address into the To field in the Send tab of your wallet?

**Comment by cmgustavo** [comment]
I 've tried to paste on Windows 10 without issue. Just to understand better, are you using keyboard combination (Ctrl+V) to paste? The contextual menu is disabled on NW, so you should use the keyboard always.

**Comment by will701** [comment]
2b59df4d3963f96603c2f83487f5cac8a6b692d5ea56943c78900b8cdf131db1

**Comment by timstar25** [comment]
Thanks for that. I have not been using the keyboard so will hive that a go. 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Gustavo Maximiliano Cortez <notifications@github.com> Date: 20/07/2016  13:52  (GMT+00:00) To: bitpay/copay <copay@noreply.github.com> Cc: timstar25 <timstar25@hotmail.co.uk>, Author <author@noreply.github.com> Subject: Re: [bitpay/copay] copy and paste (#4608) 
I 've tried to paste on Windows 10 without issue. Just to understand better, are you using keyboard combination (Ctrl+V) to paste? The contextual menu is disabled on NW, so you should use the keyboard always.

**Comment by timstar25** [comment]
Thankyou very much for your help. It works fine now. 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Gustavo Maximiliano Cortez <notifications@github.com> Date: 20/07/2016  13:52  (GMT+00:00) To: bitpay/copay <copay@noreply.github.com> Cc: timstar25 <timstar25@hotmail.co.uk>, Author <author@noreply.github.com> Subject: Re: [bitpay/copay] copy and paste (#4608) 
I 've tried to paste on Windows 10 without issue. Just to understand better, are you using keyboard combination (Ctrl+V) to paste? The contextual menu is disabled on NW, so you should use the keyboard always.
