### ISSUE TITLE
Extract Private Key for Single-Address Wallet?

### ISSUE THREAD

**Issue by KeyJockey** [bitpay/copay#4609]
Apologies if this is covered elsewhere already, but I looked around a bit and have been unable to accomplish this using the tools/info here for regular Copay wallets (so far).

I'm trying to extract the private key for one of the new SINGLE-ADDRESS Copay wallet.

I assume this would be same as a simple/usual single-address type key, i.e. able to be imported to a tool like bitaddress.org (?) in order to print a paper wallet for the derived address?  

This seems to me like this would be a useful extra backup, to store away safely for a long-term storage address, in addition to using the SEED WORDS as backup.

Anyway, I've backed up and decrypted the JSON for a test single-address wallet I made, but it seems like nothing in there (neither xPrivKey nor walletPrivKey, etc), are actually regenerating the wallet's address that Copay is giving me... but I'm sure I'm missing something simple here, LOL

Any help?  Thanks in advance...

**Comment by dabura667** [comment]
Generate m/44'/0'/0'/0/0 from xPrivKey

**Comment by matiu** [comment]
`xPrivKey` must be there, please recheck.

As @dabura667 suggested,  you can generate `m/44'/0'/0'/0/0` from it (using https://bitcore.io/playground/#/hdkeys) , of from the 12 word seed (using something like https://dcpos.github.io/bip39/)

**Comment by KeyJockey** [comment]
Thanks guys, that's what I need... I'll check it out 

(and, yes, the xPrivKey WAS there, no problem: it's just that I didn't know how to convert it to older-fashion key)
