### ISSUE TITLE
Public/Private key extraction

### ISSUE THREAD

**Issue by themovement919** [bitpay/copay#4611]
Hi i have exported a wallet backup file from Copay onto my mac. the file looks like a scramble of enrypted data. how do i find out my public and private (pgp encrypted) keys from this? 

or simply put how do i find out my public and private keys from a wallet on copay?

thanks

**Comment by matiu** [comment]
You can decrypt the backup using something like:

https://bitwiseshiftleft.github.io/sjcl/demo/

Then you will see keys like xPrivKey and xPubKey.


Also you can get you keys from the 12 word recovery phrase, using tools like:

https://dcpos.github.io/bip39/
