### ISSUE TITLE
Implement PIN / Fingerprint App lock

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#4617]
- Remove per-wallet fingerprint option
 - Keep per-wallet 'spending password' option (becuase that one actually encrypt the keys, for ultimate security)
 - Add a global fingerprint / pin option, something like:
 - Lock the app:
   - [ ] inmediatly
   - [ ] after 2 min
   - [ ] after 5 min
   - [ ] disabled
 -  [x] Use fingerprint (instead of PIN)
     
Fingerprint will be asked every time the app opens. On resume, it will be asked if x minutes passed since the last time the user enter the pin/fingerprint

Related:

https://github.com/bitpay/copay/issues/4508

https://github.com/bitpay/copay/issues/4555

https://github.com/bitpay/copay/issues/4589

https://github.com/bitpay/copay/issues/3061

**Comment by JDonadio** [comment]
Lock the app after 1 minute of inactivity

**Comment by bitjson** [comment]
https://github.com/bitpay/copay/issues/4555
