### ISSUE TITLE
idle CPU usage in desktop app

### ISSUE THREAD

**Issue by braydonf** [bitpay/copay#4621]
**Version**: v2.3.0
**System**: Ubuntu 14.04 (maybe others too?)
**Release**: Copay-linux.zip (f5ffb277a99a71ffbbb78a4d708594edef1d82e253e2e55f4f8beb67f4c3aa76)

**Expected Behavior**: 
Near idle CPU usage (1-3%) when application is not being actively used

**Actual Behavior**: While the desktop application has the wallet view open showing the balance, activity, and etc, there will be consistent ~16% CPU usage. Changing the view to anything else and the usage will drop down to below zero.

**Debugging**:
Running CPU profiler didn't lead to any useful insights yet:
```
./Copay --remote-debugging-port=9222
```

**Comment by matiu** [comment]
could not reproduce it on OSX. Usage goes to <1% when the app is not been used.

**Comment by braydonf** [comment]
It's related to `<ion-spinner>` and `<ion-infinite-scroll>`. Removing those elements from `public/views/walletHome.html` and the CPU drops to less than 1%.

**Comment by bitjson** [comment]
I think this was solved. Going to close for now, but please reopen if it needs to be reviewed.
