### ISSUE TITLE
[Feature Request] - Integrate Keepkey Hardware Wallet with Copay

### ISSUE THREAD

**Issue by JonFCortes** [bitpay/copay#4622]
Keepkey is becoming a very popular hardware wallet, and with Trezor and Ledger wallets already compatible with Copay, integrating Keepkey will further expand consumer choice and increase security by spreading out possible risk from bugs specific to one company.

The most common form of hardware wallet is a 2 of 3 setup; this would be most secure when all three signers are hardware wallets from three different companies (Trezor, Ledger, and Keepkey), in the case that one company is forced to include a backdoor or that one company has somehow missed a serious vulnerability.

In addition, it is my understanding that Keepkey uses a lot of Trezor code, so it should be easier to integrate.

Thank you for everything you all do!

**Comment by matiu** [comment]
Hello,

for the moment there are plans to integrate with Keykeeper.  You may also want to consider a 3-3 wallet, using 1 software key (like a cel phone) and 2 hardware keys. Or a 2-2 with on software key (cel phone) and 1 hardware wallet.  

 Note that compromising the funds on the mentioned 2-2 wallet would mean that the attacker hack the hardware key (something that AFAIK has never been done before) and also hack the key at the phone (which at least for Copay we never had reports before), so IMO it will be very secure while convenient  to use.

You may also want to explore our Air-Gapped operation flow (https://github.com/bitpay/bitcore-wallet#airgapped-operation) using a CLI client called 'bitcore-wallet'. You can have something like a  hardware wallet + air gapped copay signer.

**Comment by JonFCortes** [comment]
Hi Matiu,

Thanks for the response and suggestions!

Is there any chance you have an ETA on the Keepkey integration?

Thank you!

JFC

**Comment by matiu** [comment]
I meant to say there are *no* plans to integrate with keykeeper.

**Comment by dabura667** [comment]
lol worst typo to make.

You might want to edit the original post as well. Someone who stops reading halfway might think keepkey is on the way

**Comment by JonFCortes** [comment]
@matiu,

Ah, ok.  Disappointing, but thanks for everything else you do.
