### ISSUE TITLE
forgot password send money

### ISSUE THREAD

**Issue by cambitcambodia** [bitpay/copay#4625]
help me how to find my password sending fund

**Comment by JDonadio** [comment]
Do you have the 12 words or file/text backup? In that case, delete the wallet and import it again.

**Comment by gabrielbazan7** [comment]
https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-forgot-my-wallet-spending-password-is-there-a-method-to-reset-it

**Comment by JDonadio** [comment]
In the latest release of Copay if you import a wallet locked by spending password, it's unlocked automatically when import finish. Update your client and try this ;)
