### ISSUE TITLE
Description field cannot be edited hence errors cannot be corrected

### ISSUE THREAD

**Issue by fortran77** [bitpay/copay#4628]
The Description field can optionally be filled by the user when sending bitcoins. However, apparently, this field cannot be edited afterwards. If erroneous information was entered, it cannot be corrected.

It would be greatly desirable to allow editing of the Description field.

For multisignature wallets, an argument could be made that all parties that approved a transaction should also be required to approve a change in the Description field.

However, for 1:1 wallets, where only one person needed to approve a transaction, there is no security benefit to preventing editing of the Description field. So this at least should be made possible now. A solution for multisignature wallets can be considered later.

**Comment by matiu** [comment]
As you mention, because the multisig nature of Copay,  it will be tricky to let the users edit a transaction description. As a workaround, we added the TX comments, that can be edited by each copayer at anytime.

**Comment by fortran77** [comment]
The workaround makes sense at first reading. A user of a 1:1 wallet can simply enter nothing into the optional Description field, and later add a transaction comment instead.

This seems like a perfect solution, except for one thing.

Suppose we divide the universe of all users of 1:1 wallets into those who make mistakes and those who don't.

The ones who don't make mistakes will continue using the Description field and will not need to revise it.

Those who do make mistakes will sometimes absent-mindedly enter something incorrect into the Description field even though they know they should be leaving it empty and later entering a transaction comment instead.

To protect these error-prone users from their own failings, they should be able to adjust the Settings of a 1:1 wallet so they never see the empty Description field when they are sending a payment.

**Comment by dabura667** [comment]
"Large bags of weed"

NONONO I MEANT SEED! SEED!

*fbi watch list entered*

**Comment by dabura667** [comment]
But yeah, I agree this should be editable for 1of1.
