### ISSUE TITLE
Basic Math Error (?!)

### ISSUE THREAD

**Issue by KeyJockey** [bitpay/copay#4631]
Very weird: one of my older Copay wallets is making a very basic, simple MATH ERROR...

![matherror1](https://cloud.githubusercontent.com/assets/13903392/17214497/3288aff2-54a7-11e6-88a6-89073e95c41f.png)

That's the main balance value, but it's composed of only two simple addresses... 

![matherror2](https://cloud.githubusercontent.com/assets/13903392/17214512/45ef34e4-54a7-11e6-97c1-70e944d6080f.png)

...which I double-checked on the blockchain that they're just simple 4-digit values 1.0000 and 3.0005 

https://blockchain.info/address/3LatC5FNkXtcPR72uPXSjfTJF9wZ2Wz2Jh 
https://blockchain.info/address/3AkCQS7QtpKxpkcopz9MFNdaQpuUC8fWt8

Yeah, I realize this may be just a "quirk" and due to this being older instance wallet running in newest version (chrome extension) *but* at the same time it kinda does not inspire confidence in the wallet if it can't get simple MATH right, ya know what I mean? 😢  

This may be another instance of my supposition (elsewhere here, related to the miner fee control design) that large parts of Copay are getting 'squrreley' and may be due for a ground-up rewrite overhaul, soon...

**Comment by braydonf** [comment]
My guess is that it's a display issue. 

It's essential to assert that all values are integers and not floating point, e.g. this common rounding error:
```
> 3.0005 + 1.000
4.000500000000001
```

Isn't an issue with safe integers (`Number.MAX_SAFE_INTEGER`).
```
> 300050000 + 100000000
400050000
```

**Comment by isocolsky** [comment]
I could reproduce the issue. While it can be confusing, it is just a visualization issue. All amounts are handled internally in satoshi and are correct (if you switch to using bits you will see the expected amount).

**Comment by KeyJockey** [comment]
Hmm... ok well for what it's worth, I send another transaction to this wallet and it's OKAY now: 

![fixed](https://cloud.githubusercontent.com/assets/13903392/17218955/95f7ef2a-54b7-11e6-8af6-fd8b744bf51d.png)

...so, just a 'quirk' I guess?  Issue can be closed OR something still to be fixed here?

**Comment by isocolsky** [comment]
A fix has been submitted here https://github.com/bitpay/bitcore-wallet-client/pull/300, it will be reviewed and merged soon. Thank you for your report!

**Comment by matiu** [comment]
Fixed by https://github.com/bitpay/bitcore-wallet-client/pull/300.

Thanks for the report!
