### ISSUE TITLE
Scroll and recovery phrase problem when importing wallet

### ISSUE THREAD

**Issue by franamati** [bitpay/copay#4638]
Two problems when importing wallet in Copay v2.3.0 using an iPhone 5s:

* Scroll does not work: I can't find the button to import because I can't scroll.
* Imported recovery phrase is not seen after using the camera to complete the field.

Example:
![copay import](https://cloud.githubusercontent.com/assets/8605599/17297689/1dc3e436-57dd-11e6-846d-6d7e77c361ca.png)

**Comment by JDonadio** [comment]
We could reproduce it. We are working on that and will be fixed in the next release. Thanks alot for the detailed info!
