### ISSUE TITLE
lowering android version

### ISSUE THREAD

**Issue by BitMari** [bitpay/copay#4640]
a quick question , can i edit the copay code to be able to support lower android versions like android 3 without facing any compatibility issues?

**Comment by dabura667** [comment]
You COULD do it.

But it would be extremely broken.

Good luck.

**Comment by matiu** [comment]
I am pretty sure It wont work. We definitely don't support it, since many plugins (like the QR scanner) wont work with older Android APIs... but you can try.

**Comment by BitMari** [comment]
Ok guys , thank you!
