### ISSUE TITLE
Can't create wallet on iOS 10

### ISSUE THREAD

**Issue by ffxsam** [bitpay/copay#4649]
The following error occurs when I load the app for the first time and try to create a new wallet.![](http://i.imgur.com/9QSaj7s.jpg)

**Comment by dabura667** [comment]
Assertion Error, chainCode was 64 bytes long!!! O_o!!

Scary to think what a bug like that would do if it wasn't caught and tried to make your wallet anyways...

iOS10 is currently not supported afaik. :-(

Thanks for the report!

**Comment by ffxsam** [comment]
Yeah, I'm reporting it ahead of the iOS 10 release so the developers can fix it.

**Comment by gabegattis** [comment]
Yeah, invalid chain code length is pretty worrisome. We should definitely investigate this. Hopefully there is not a bug in bitcore-lib.

**Comment by matiu** [comment]
closing this one. Dup: https://github.com/bitpay/copay/issues/4570
