### ISSUE TITLE
Restore deleted shared wallet

### ISSUE THREAD

**Issue by ibagur** [bitpay/copay#4650]
Hi,

I have been doing an experiment to test CoPay multisig. I set up a 2-2 wallet, so I have it both on the phone app and the other on the desktop computer. Any transaction from any device will then require the approval from the other. I wrote down the 12 word phrases for each wallet on each device, but I did not store the backups externally. I put a small quantity  of mBTC in the shared wallet. Then I purposely deleted the wallet on the desktop Copay, to emulate the case the computer disappear or getting damaged, or the application getting uninstalled for some reason. Now if I want to operate with the phone account, it requires the approval from the co-sig (the desktop computer). But the wallet there was deleted and apart from the 12-word there is no backup. I would like to know if there is any way to recover a shared wallet in this case.  Thanks

**Comment by dabura667** [comment]
Import the 12 word phrase.

Did you even try?

**Comment by ibagur** [comment]
Before writing here, I tried that from the Import section (sorry I forgot to mention) but I was getting the following message:

"Could not access the wallet at the server. Please check:
The password of the recovery phrase (if set)
The derivation path
The wallet service URL"

I know I did not set any password for the recovery phrase when initially joining the shared wallet on the desktop app, so I went then to the 'Create wallet' and tried to recreated from there, I created a wallet specifying the recovery phrase I had and named 'test'...and a new wallet appeared using that same phrase, but empty and it did not show anything as 'shared'. It shows its name as 'test'

Then I deleted that, and now went back to the Import to try your suggestion. But after typing the recovery phrase, the only wallet that appears is that 'test' wallet empty. The original shared one I could not recover, not even using the 12-word.

Could it happen that when using that same phrase from the 'Creation' section I have somehow deleted the reference to the original shared wallet?

**Comment by ibagur** [comment]
Ok..I think I know the problem. It seems I wrote down the wrong 12-pass phrase for the desktop app (and used the phrase from a previous test single wallet I created). Now the problem..is there anyway to restore the shared on my desktop without neither the 12-pass phrase nor the backup? The only thing I have is the expended public key for the copayer desktop. I guess no...but just asking

**Comment by matiu** [comment]
thanks for the update.

no, it is not possible, you need the seed.
