### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by david-vardanov** [bitpay/copay#4651]
Hello! I am going to run a business and now I am looking for a wallet. I have some questions to understand does your wallet suits my business :)

1. Can I add your wallet to my gambling site?
2. Does your appi support C#?
3. What fees do we have to pay for using your wallet?
4. Is there any limit to generating addresses? And if yes what happens when we reach the limit?
5. Is there any fee for transfer coins from generated address to main wallet?

**Comment by dabura667** [comment]
1. Sure!
2. Currently only NodeJS, but it would be trivial to port bitcore-wallet-client to C# if you know how to read JS. Every main function basically culminates in a get or post request to bitcore-wallet-service
3. None! In fact you can run it on your own server, as everything is open source.
4. Nope. But you will need to use a flag on the generate address call to ignore a soft gap limit in place. Easy.
5. Nope.
