### ISSUE TITLE
Fee selection/override in send screen

### ISSUE THREAD

**Issue by JulianTosh** [bitpay/copay#4657]
I would like to be able to override the fee rate, specified in preferences, in the send screen.

Many times, I'm just moving funds between wallets I own for the purposes of managing budget accounts. I would like my normal spends to have a normal fee, but when spending to my own accounts, I want to be able to specify a 'super economy' fee because I'm not concerned about the timing of confirmation.

**Comment by matiu** [comment]
JFYI. We used to have it that way (https://github.com/bitpay/copay/issues/3045) but we removed to simplify the UI.

**Comment by isocolsky** [comment]
Would it make sense to preset an "external tx fee level" and an "internal tx fee level" globally in cases where there are more than one wallet on a device? Or would it be too hard to communicate?

**Comment by JulianTosh** [comment]
I imagine it to be used like a dropdown object that doesn't take up any space until pressed. then you'd see the normal fee descriptions when it expands. The default choice would be whatever is set in global preferences.

As for cluttering the UI, description area could be replaced with 'advanced features' expander where several other useful features could be tucked away, like description, fee selector, additional output addresses, and tx input selection.

**Comment by KeyJockey** [comment]
Please see my proposed SEND tab re-design for including an advanced-user feature for controlling the miner fee value more precisely... at this long-standing issue page here: https://github.com/bitpay/copay/issues/3111 

Scroll down to the bottom of the long thread, past all the noise LOL, to see the screenshots of the design proposal: @JulianTosh would this be a solution for what you need too?  Anyone/Everyone reading here IF you agree with me THERE, please speak up and add your support for miner fee control in Copay, ASAP!

It's getting to be almost a YEAR since I first posted that thread...........

**Comment by JulianTosh** [comment]
@KeyJockey I'm ok with CoPay's selectable presets and do not have a need to user specified arbitrary values. I only wish to be able to have a way to override the global default.

**Comment by KeyJockey** [comment]
@JulianTosh okay fair enough, but *if* they did it my proposed way anyway, wouldn't that work for what you need to do also?  Kill Two Birds With One Stone anyway, as it were, or provide what you want in an additionally powerful or flexible manner?

**Comment by bitjson** [comment]
With the simplifications in the new UI, I think we're ready design-wise to look at this feature again.

This is particularly relevant with the recent backlog on the network. I think we could come up with some very simple designs that also accomplish the goals from https://github.com/bitpay/copay/issues/3111.

We'll work on some mocks. 🚀

**Comment by KeyJockey** [comment]
@bitjson thanks for taking this up... looking forward to seeing new design.  

If possible please try to incorporate my idea from https://github.com/bitpay/copay/issues/3111 screenshot sims 😄

**Comment by tommcintyre** [comment]
Thanks for looking again at this issue, it's the only _tiny_ annoyance I have with an otherwise incredible app! 👍

+1

**Comment by kerohero** [comment]
I've read that the API's allows us to set fee per kb, It would be easy if the software calculates the size of the transaction, lets say that the size is equal to 1024 bytes (kb), and there's a slider in the advanced options tab. Let's say also that the minimum fee calculated for each byte is 5 Satoshi per byte, The minimum of slider will be 5 * 1024 (5120 Satoshi) now if the user changed the slider's value 1 more, it's now 6 sat per byte so the fee now is 6144 sat, 1 more and it's 7 * 1024 7186 sats, The user won't see the size but he will se the final fee. that's makes it more simple for him,  It's an easy idea for controlling and overriding fee manually, It's not a full controlling but now the "ADVANCED USER" has an option. Sorry for my bad English guys, Hope anyone get the idea! 🤞

**Comment by FaraFara** [comment]
@kerohero, This is nice idea!

**Comment by kerohero** [comment]
@FaraFara I wish that developers can get it, It's not a must to be a slider a drop down list or anything else like that will be ok.
If they gonna make a slider then the value should be in the center that's the recommended fee, and user can rise it or make it even lower (with a minimum and maximum of course) they said before that the ui is complex, and I think that will take more time from them :(( we should wait longer :(

**Comment by JDonadio** [comment]
Closed in favor: https://github.com/bitpay/copay/pull/6037

**Comment by kerohero** [comment]
@JDonadio How selecting fee from send screen is solving fee overriding issue?

**Comment by FaraFara** [comment]
@JDonadio, #6037 it's not about we told with @kerohero.

**Comment by JDonadio** [comment]
This issue is related to override the fee level at confirm, not select a custom fee out of the pre-set configuration of Copay as Julian mention in the [above comment](https://github.com/bitpay/copay/issues/4657#issuecomment-239153584)

**Comment by kerohero** [comment]
@JDonadio #3111 is merged into this issue, and 3111 is about overriding the fee and setting custom fees, And I don't think that #6037 is solving #3111, So please open this issue again or open #3111

**Comment by KeyJockey** [comment]
@kerohero @JDonadio @FaraFara Yes, this is NOT the same overall issue as I tried for over a YEAR in the old Copay Wallet design thread https://github.com/bitpay/copay/issues/3111 to get the devs to take *seriously* -- but seems like again they just don't get it about advanced users needing & wanting more exact precise fee control :( 

I've given up trying, frankly... and although I'm still using the older version of Copay (not BitPay as I really don't like the UI design changes) I've become resigned to the fact that I'll probably have to find some other wallet to move my main activity to soon, if/when the older Copay stops working or hits some problem or limitation (maybe after fork in August or something, if that ends up happening).

Anyway guys thanks for keeping up the fight for this IF you can eventually get it done somehow and get the devs to *finally* see and understand this needs to be changed.  But, I'm out... unfortunately.  Good luck.

**Comment by kerohero** [comment]
I'm searching for another wallet too, They will complain about the complexity of UI as always..

**Comment by KeyJockey** [comment]
LOL I know, right?

I mean, srsly I argued and complained in 3111 for over a year until I was literally blue in the face and now they merge *this* into *that* as if it's addressing the fee control UI issue at all?  And this even *after* the "upgrade" from great design old-Copay to current clusterf*ck BitPay design wallet??

I'm like, wait, what??  You guys did... what now?

So, I'm out.  Sorry just, out.  Can't deal any more.

I mean For Fock's Sake even the gawd-awful OmniWallet wallet has a SIMPLE option for the user to TYPE IN THE FEE VALUE HE WANTS, and even with it's buggy choppy behavior and confusing UI THAT wallet's designers "gets it" and they understand enough that ADVANCED USERS WANT TO DIRECTLY CONTROL THE FEE.

Anyway, yeah, no... last rant there. I'm out.

RIP Copay...

You were great while you lasted but ignorant dumbass clueless designers have killed you.

**Comment by kerohero** [comment]
If they really can't deal with THEIR UI, they should look for someone to help them. They just wanna get rid of the opened issues as soon as It's possible, Before complaining about the complexity of UI they should remember that they who made it more complex.

**Comment by matiu** [comment]
Hi Everyone:

Version 3.7.0 of Copay & Bitpay allows arbitrary fee rate (sat/byte) setting, per transaction, on the send tab.

The version is already on Android's play store, and it will be soon available on other platforms also.

**Comment by kerohero** [comment]
Finally , Good news, Thanks
