### ISSUE TITLE
recovery tool bug

### ISSUE THREAD

**Issue by papcoin** [bitpay/copay#4662]
we tried to recover 3 copayer and require 2 signature

from this tool :
https://bitpay.github.io/copay-recovery/

everytime we tried to recover from copay it got error as screenshot below :
![image](https://cloud.githubusercontent.com/assets/20924783/17512729/77f6e260-5e53-11e6-9686-d2ef9f079b7a.png)

though the recovery seed, etc is already correct, but it stuck on could not build transaction

may i know whats wrong?

**Comment by matiu** [comment]
Given the balance it is probably that the inputs are to small to pay for
the fee.

**Comment by papcoin** [comment]
ok now it is not about balance, as i have tested to increase it to 0.1 btc it is not too small

see screenshot : 
![image](https://cloud.githubusercontent.com/assets/20924783/17550316/9cfd9826-5f1e-11e6-8946-145ccddc4f86.png)

please check definitely something wrong

**Comment by matiu** [comment]
Thanks for the follow up and for trying again. Please hold, we will add more info to the error message and ask you to try again with the same wallet.

**Comment by JDonadio** [comment]
@papcoin can you try now? We already sent a little change to see the error in the view.

**Comment by papcoin** [comment]
it shows invalid address now, though it is a valid bitcoin address

https://blockchain.info/address/1GZ5a6B8ZkmPL9QdCj6R6uRqC8BByJS47B

![image](https://cloud.githubusercontent.com/assets/20924783/17559863/eded5c6e-5f49-11e6-94c2-82c3ce967507.png)

**Comment by JDonadio** [comment]
@papcoin we found an error (fixed). Please try again and tell me if the problem remains

**Comment by papcoin** [comment]
now it become this error :  

all 12 words seed are 100% correct

![image](https://cloud.githubusercontent.com/assets/20924783/17561857/2fb27582-5f52-11e6-8a6a-ea999851dd02.png)

**Comment by matiu** [comment]
We found the error, it seems to be only for M<N wallets, we will deploy a fix ASAP and let you know.

**Comment by matiu** [comment]
Should be fixed by https://github.com/bitpay/copay-recovery/pull/40

can you please try one more time?

**Comment by papcoin** [comment]
now it is working :)

thanks for the support and update
