### ISSUE TITLE
Old Versions Being BLOCKED Now...

### ISSUE THREAD

**Issue by KeyJockey** [bitpay/copay#4664]
Well, it seems that today I fired up Copay on my old iPhone and received the message that my old version will no longer work... it's blocked at the server, so I'm forced to upgrade if I want access to my money.

While I understand this is being done to "protect" users and force a minimum level version, I was preferring to keep the old version *specifically* because it's the last release that allowed user choice of exact miner fee values (i.e. not the dynamic fee, i.e. simple 0.0001 or 0.0005 etc)

Taking this away from me is really annoying... IF there was SOME progress on my long-standing complaint issue here ( https://github.com/bitpay/copay/issues/3111 ) for enabling more precise fee control for advanced users, maybe it would be less annoying and lighten the sting?  

SO how about it guys, CAN YOU give me some HOPE that the miner fee control issue WILL be addressed seriously, some time soon?  Like, maybe NEXT version???  WHERE are we AT on this?

**Comment by matiu** [comment]
The latest version of BWS deprecated some old API calls so it is easier to maintain, add new features  and test BWS source code. Sorry for the inconveniences.
