### ISSUE TITLE
I can not send my BTC from wallet...

### ISSUE THREAD

**Issue by Waldorio** [bitpay/copay#4666]
When i try send my BTC from waller i see bug:
**Could not send payment. Wallet service not found ....** 

Someone can help me ? .....

**Comment by matiu** [comment]
Please see https://github.com/bitpay/copay/blob/master/CONTRIBUTING.md#support-requests so we can help you better.

**Comment by matiu** [comment]
Please make sure you are using the latest version of Copay 2.4.x
