### ISSUE TITLE
UI bug: White bar between title bar and rest of UI

### ISSUE THREAD

**Issue by JonnyAC** [bitpay/copay#4678]
I've noticed this bug for a long time, I think ever since the new app UI came out. There's an ugly white bar between the title bar and the rest of the app, and it's also present and even taller on the side menu.

![screenshot_2016-08-10-22-06-59](https://cloud.githubusercontent.com/assets/20960885/17577232/34765e20-5f49-11e6-809a-6a0559a0a8f5.png)

![screenshot_2016-08-10-22-07-03](https://cloud.githubusercontent.com/assets/20960885/17577238/4a4790c0-5f49-11e6-802f-63df0e7b09ac.png)

I think the issue is only present on screens of smaller resolutions. It's not present on my tablet or my other phone with a higher resolution screen.

Thanks!

**Comment by gabrielbazan7** [comment]
Thanks for the report. Which device is the one from the photos ?

**Comment by JonnyAC** [comment]
@gabrielbazan7 It's on my Galaxy Core Prime and was also on my Blu Studio Selfie as well. Both screen resolutions are 800 x 480 and 854 x 480 respectively.

**Comment by bitjson** [comment]
Solved by the new UI 🎉
