### ISSUE TITLE
Could not send payment: Wallet service not found

### ISSUE THREAD

**Issue by Marko030** [bitpay/copay#4679]
Dear support,

I'm not able to make a payment from the copay.
it says: Could not send payment: Wallet service not found

Could you please help. What I have to do?

BR, Marko

**Comment by matiu** [comment]
Are you using the default BWS URL configuration? If yes, can you try to switch to a different Intenet Connection?

**Comment by Marko030** [comment]
Hi,

My wallet service Url

https://bws.bitpay.com/bws/api
Could you please advice what to put. Thank you in advance

11.08.2016, 15:15, "Matias Alejo Garcia" <notifications@github.com>:

**Comment by matiu** [comment]
click on "set default url"

Please try to change to a different internet connection.

**Comment by Marko030** [comment]
Done, The same issue appears: could not send payment: Wallet service not found.3 days ago I has been woring fine. What other possible solutions could be?    11.08.2016, 16:42, "Matias Alejo Garcia" <notifications@github.com>:click on "set default url"Please try to change to a different internet connection.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by isocolsky** [comment]
can you try to open this link https://bws.bitpay.com/bws/api/v1/version on a browser?

**Comment by Marko030** [comment]
Yes, done. Here is the message that appears

{"serviceVersion":"bws-1.9.1"}

11.08.2016, 17:08, "Ivan Socolsky" <notifications@github.com>:

**Comment by matiu** [comment]
Are you using Linux? could you please check https://github.com/bitpay/copay/blob/master/CONTRIBUTING.md#support-requests ?

**Comment by Marko030** [comment]
MAC OS

I did not do any changes. 3 days ago I could make a payment, but now it showing the connection error. 

Here is the info:


    Which platform are you using? (Which device and operating system)

MaC X Yosemite version 10.10.5

    Which version of Copay are you using? (Check Copay version on the side menu)
v 1.8.2

    Please import your wallet on a different platform. Does the problem persist?
    What type of wallet are you using? (multisig or singlesig)

    When the wallet was created? On which device / operating system
    Please check Copay logs (General Settings -> About Copay -> Session Logs). Look for any errors reported there (errors are shown in red)
    If possible, please provide a screenshot of the error / issue.

Starting Copay v1.8.2 #bb4fce8
Client: isCordova: null isChromeApp: null isNodeWebkit: true
Navigator: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36
Using file storage: null
Setting default language: ru
Profile is not encrypted
Profile read
Preferences read: {"limits":{"totalCopayers":6,"mPlusN":100},"bws":{"url":"https://bws.bitpay.com/bws/api"},"wallet":{"requiredCopayers":2,"totalCopayers":3,"spendUnconfirmed":false,"reconnectDelay":5000,"idleDurationMin":4,"settings":{"unitName":"BTC","unitToSatoshi":100000000,"unitDecimals":8,"unitCode":"btc","alternativeName":"Eurozone Euro","alternativeIsoCode":"EUR","defaultLanguage":"en","feeLevel":"economy"}},"glidera":{"enabled":true,"testnet":false},"rates":{"url":"https://insight.bitpay.com:443/api/rates"},"pushNotifications":{"enabled":true,"config":{"android":{"senderID":"1036948132229"},"ios":{"alert":"true","badge":"true","sound":"true"},"windows":{}}},"aliasFor":{"b3324d1d-230a-4228-ada0-b1cc83f6d156":"K2Master"},"colorFor":{"b3324d1d-230a-4228-ada0-b1cc83f6d156":"#9B59B6","9d9e27e1-2daf-4328-9f36-78e342f4b08d":"#9EDD72"},"bwsFor":{"9d9e27e1-2daf-4328-9f36-78e342f4b08d":"https://bws.bitpay.com/bws/api","4bcb5ad0-34b5-451d-a7e2-7fc975288f2b":"https://bws.bitpay.com/bws/api"}}


11.08.2016, 17:35, "Matias Alejo Garcia" <notifications@github.com>:
>  Are you using Linux? could you please check https://github.com/bitpay/copay/blob/master/CONTRIBUTING.md#support-requests ?
>
>  —
>  You are receiving this because you authored the thread.
>  Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by matiu** [comment]
OK you are using a very old copay version. We think that is the source of the problem. Could you please update it ? (https://copay.io)
