### ISSUE TITLE
[Question] Hidden/Password protected wallets on Trezor

### ISSUE THREAD

**Issue by RustyNomad** [bitpay/copay#4683]
I currently have 3 wallets on my Trezor device. The first is the 'standard' wallet which is protected by the pin and this wallet is linked to my Copay wallet.

I would like to import the other two wallets into Copay (even if only as watch-only wallets) so that I can monitor them on Copay. Is this possible?

**Comment by JDonadio** [comment]
@RustyNomad try importing your wallets from Add Wallet > Import Wallet > Hardware Wallet, then specify the wallet type (trezor in this case) and play with the account number (2, 3, etc)

**Comment by RustyNomad** [comment]
@JDonadio Tried that a couple of times, also with the Create Wallet option but it just hangs with message saying 'Waiting for Trezor'.

Will try again later and see if I can spot any error codes and report back.

**Comment by matiu** [comment]
password protected wallets (with the password set at Trezor) are not supported.
