### ISSUE TITLE
Coinbase integration: Can't get the Oauth Code

### ISSUE THREAD

**Issue by cmgustavo** [bitpay/copay#4686]
Only for desktop:
- After click on _Connect to Coinbase_, the opened window doesn't close and the Oauth Code appears on the title of window but it hasn't been copied to Copay.

To-Do:

1.- New versions of NW (v0.13 or above) Window.open is changed to passing the created window as the argument of the callback.
2.- There is an known issue with the event `loaded` that allows to copy the authorization code to Copay. https://github.com/nwjs/nw.js/issues/5101

**Comment by bitjson** [comment]
merging into #4894
