### ISSUE TITLE
[Android] Hardware-software back button doesn't works properly (2.4.2)

### ISSUE THREAD

**Issue by Kirvx** [bitpay/copay#4689]
![screen](https://cloud.githubusercontent.com/assets/6627786/17628283/0251cea8-60b5-11e6-8daf-5b4b3f51d4a2.png)

From the Google Play Store:

> "It is very annoying that pushing the back button doesn't return you to the previous screen but straight to the main (i.e. closes the whole chain of opened screens in preferences)"

I confirm.

Also, when touching a transaction and then press the back button, we have the "Press again to exit" notification.

**Comment by JDonadio** [comment]
@Kirvx the back button on copay-android just nav to home (wherever you are) and, if it's pressed twice, exit the app. Doesn't mean if you nav from i.e: Preferences > Advanced > Wallet Information and press back button should back to Advanced view. We know this is not actually the best implementation but we're working on a lot of improvements for UI, navigation, etc. and hopefully this will be fixed soon. Thanks for comment!
