### ISSUE TITLE
Backup Issue  with Wallet (1-2)

### ISSUE THREAD

**Issue by miguelmorales85** [bitpay/copay#4692]
I created a wallet (1-2) in Copay Linux version 2.4.0 and then invited another user who scanned the invitation from an android phone. 

One user has Copay installed in english and another in spanish.

The english wallet produced (copay linux 2.4.0) all the words for the passphrase and the backup has been made with no problem.

The spanish wallet (copay android v2.4.2) produced all the words for the passphrase but I noticed two words were repeated. When I follow the backup procedure the following message is displayed after confirming the words in the correct order: "Falló la copia de seguridad - No se pudo comprobar la copia de seguridad. Por favor verifique su informacion"

I tried to do the backup procedure selecting the repeated word in different order, even I dont know which goes first.

How can the passphrase words repeats??

It wont allow me to do a backup and erase those words for security purporses.

**Comment by matiu** [comment]
yes, the words can be repeated.

Please see the guidelines here: https://github.com/bitpay/copay/blob/master/CONTRIBUTING.md#support-requests so we can help you better. A screenshot will help.

**Comment by dabura667** [comment]
I think what he means, is that since the same word shows up twice, there's a 50/50 chance each time he get's the order right.

If it was "comer" that was repeated, then he doesn't know which "comer" to tap first and which to tap second.

**Comment by miguelmorales85** [comment]
@dabura667 got it right!
I have tried to do a backup selecting what I think is a different word but I always get the same result.

**Comment by dabura667** [comment]
How many times have you done it?

Should be a 50/50 chance you get it right.

**Comment by gabrielbazan7** [comment]
The backup flow works ok with repeated words. That should not be a problem.

**Comment by gabrielbazan7** [comment]
@miguelmorales85 could you try with this one: 

> sibling current sample sample ring keen horse census sauce body scan wisdom

**Comment by miguelmorales85** [comment]
@gabrielbazan7 still doesnt work, maybe its because its a 1-2 wallet with spanish words. one word repeated twice. I cannot finish the backup procedure neither erase the backup words.

**Comment by matiu** [comment]
Given that the wallet is new, can you share the words with us? Unfortunately we can't reproduce it.

**Comment by miguelmorales85** [comment]
@matiu  I'm sorry but I started using the wallet because the 1-2 wallet worked, I did not know it could fail to backup at the 2-2 wallet. I will try to test the 2-2 wallet in another device. I'll keep you all updated. thanks

**Comment by JDonadio** [comment]
Please let us know If you need more help on this.

**Comment by miguelmorales85** [comment]
I just test it by erasing and adding again the wallet and now it works.

**Comment by dabura667** [comment]
Yeah, if you import the wallet, it skips the backup step... I am curious as to why the backup step would fail...
