### ISSUE TITLE
Support for other currencies on Amazon Gift Cards

### ISSUE THREAD

**Issue by HostFat** [bitpay/copay#4696]
It seems that they support other currencies:
EUR, JPY, CNY, CAD

**Comment by dabura667** [comment]
JPY +1

I would love to use bitcoin for amazon.co.jp!

**Comment by matiu** [comment]
Thanks for the suggestion. This is part of the agreement with Amazon. As soon as we are enabled to sell Gift cards in other currencies, we will do it :)
