### ISSUE TITLE
[SOLVED] $10 in Bitcoins Missing

### ISSUE THREAD

**Issue by ktodd087** [bitpay/copay#4699]
Edit: All i had to do was wait an hour before they came back is this a bug or normal occurrence?
Please look at the photo above and explain to me why I'm missing 0.012473 bitcoins??

![14045192_1102532509840720_75424757_o](https://cloud.githubusercontent.com/assets/21083930/17740563/6c7d7d7e-64dc-11e6-9817-61cd6525e300.png)
Sorry for freaking out its just that i don't know if this is normal or not!?

**Comment by dabura667** [comment]
Your "missing" bitcoin is the bitcoin written after "Pending Confirmation:"

Those bitcoin are separate from your main balance because they have not yet been confirmed in a block.
