### ISSUE TITLE
Enable HSTS Preload in copay.io domain to avoid MITM attacks

### ISSUE THREAD

**Issue by i-rme** [bitpay/copay#4701]
At present, the copay.io domain does not send an HSTS header.

Bitcoin.com should send this header to avoid being loaded using HTTP
`Strict-Transport-Security: max-age=31536000; includeSubDomains; preload`

As an example, bitcoin-related websites already using HSTS preloading include Coinbase, Coinapult, Bitgo, Localbitcoins, bitcoin.de, blockchain.info, GDAX and Multibit.

**Comment by matiu** [comment]
copay.io no longer used.
