### ISSUE TITLE
Copay extremely slow on Windows Phone 10

### ISSUE THREAD

**Issue by busybit** [bitpay/copay#4705]
I was using Copay on a Nokia Lumia 630 with Windows Phone 8.1 and it was working ok. After switching to a Lumia 550 (nearly same processor speed) with Windows Phone 10, Copay is unusable slow, mostly no action when pressing buttons.
Is this a known problem? Is there some workaround?

**Comment by matiu** [comment]
Related https://github.com/bitpay/copay/issues/4174

**Comment by busybit** [comment]
I found that not ALL functions are slow, only some. Mainly the menu functions are unresponsive on WP10. It's nearly impossible to open the main menu.

**Comment by matiu** [comment]
Thanks for the report. The upcoming Copay 3.0 has a refactored UI that may help with this problem.

**Comment by bitjson** [comment]
https://github.com/bitpay/copay/issues/4999
