### ISSUE TITLE
Copay for Windowsphone (URL handlers not working on WP)

### ISSUE THREAD

**Issue by ponsaelius** [bitpay/copay#4707]
First - Thanks. It's nice to pretty much have the only usable app for Windowsphone. Yes thanks for including me.

I wanted to post an issue that I am having. I like to use the 'foldapp' http://coffee.foldapp.com to buy a Starbucks gift card instantly with Bitcoin. If you do this with Android then you get a little menu offering your installed Bitcoin apps as a way of transferring the money. Not so with Windowsphone. The URI seems to cause a Windowsphone to go to the Windows Store to search for an app. Then it fails because what I want it to do is pass the URI to Copay and send the Bitcoin.

So something is wrong. Foldapp say they just send a standard Bitcoin URI. Does something need doing to the Windowsphone registry? Does Edge not have the ability to call Copay with the correct parameters? I dont have a clue. It would be nice if it worked tho.

**Comment by matiu** [comment]
Thanks for you comments.

unfortunately  registering protocol handlers (ie `bitcoin:`) on WP has been broken for a while now due to a bug in one of our underlying libraries (Custom-URL-scheme).

**Comment by ponsaelius** [comment]
Thanks for letting me know. I feel better that at least it is an issue someone else knows about!

**Comment by bitjson** [comment]
Merging into #2892
