### ISSUE TITLE
Old copay browser app wallet file (recovery possible?)

### ISSUE THREAD

**Issue by xanatas** [bitpay/copay#4715]
Hi!
I try to recover a failed hard drives copay wallet (chrome browser plugin). it was a while ago in the old copay format not HD wallet. Does anyone know where the wallet file in the system (Mac OSX) might be saved?
Its like 0.9 bitcoin...so worth a try i guess.

Any insight is appreciated.

**Comment by matiu** [comment]
Copay was always HD.

You can try to decrypt it and extract the xPrivKey.

Please see https://github.com/bitpay/copay/blob/master/README.md#wallet-export-format

**Comment by xanatas** [comment]
The question was about the file on the harddrive representing the private key. i cannot boot the system i have it attached via USB and try to recover it.
Do you know where the file is located in OSX file system /Library/ApllicationSupport/Chrome for example? and what format that file has?
