### ISSUE TITLE
Can't delete unsent transaction - Copay Chrome

### ISSUE THREAD

**Issue by zbsb** [bitpay/copay#4717]
I have and unsent transaction in my Copay Chrome wallet.  I desire to delete it rather than send it.

<img width="758" alt="screen shot 2016-08-26 at 5 41 09 pm" src="https://cloud.githubusercontent.com/assets/16749034/18022428/7ece3610-6bb4-11e6-9275-23de59945c38.png">

If I click on the arrow to the right of the unsent transaction the following screen is displayed:

<img width="754" alt="screen shot 2016-08-26 at 5 44 12 pm" src="https://cloud.githubusercontent.com/assets/16749034/18022473/d4449738-6bb4-11e6-8927-9285bfe14dbe.png">

I seem to be stuck with 3 options that I can find:

1. Ignore it and be stuck with the current balance locked.  
2. Attempt to send it to the address shown.  Unfortunately I do not recall what wallet of mine (hopefully) that address is associated with.
3. Delete or cancel the Payment Proposal if I could just find where/how assuming that this option exists in some fashion.

Please help with pursuing option number 3, since the first 2 options are quite undesirable.
Thanks.

**Comment by matiu** [comment]
Can you try to scroll down on the popup contents. There should be a 'delete' button below.

**Comment by zbsb** [comment]
There WAS an option number 4!!!!  Thank you.  I'm going to blame it on my lack of a fine set of binoculars instead of my poor trackpad skills.  :-)
