### ISSUE TITLE
Error no start Copay on Linux KUbuntu 16.04

### ISSUE THREAD

**Issue by nikitushkin** [bitpay/copay#4718]
bash: ./Copay: cannot execute binary file: Ошибка формата выполняемого файла.
Kernel 4.4.0-34-generic x86.
Warning! Your exec file build for x86_64. Please build exec file for x86 architecture!!!

**Comment by matiu** [comment]
We only distribute _64 builds. You can build 32 bits binaries from the sources.(https://github.com/bitpay/copay/blob/master/README.md#desktop-versions-windows-os-x-linux)

**Comment by juanjgit** [comment]
Compilation only generates 64 bit binaries
