### ISSUE TITLE
Do not truncate the Bitcoin address on the "SEND BITCOIN" view

### ISSUE THREAD

**Issue by gabegattis** [bitpay/copay#4722]
We should display the entire bitcoin address in this view. We are only leaving out 8 characters, so we aren't really saving that much horizontal space anyway.

This is especially useful when sending a transaction where I did not specify the address myself (like the amazon gift card integration).

![sendbitcoin](https://cloud.githubusercontent.com/assets/4419243/18108104/c6fd8306-6ed8-11e6-9451-fadbe5428cb3.png)

**Comment by KeyJockey** [comment]
Actually, what's the real reason for shortening the numbers everywhere?

I mean, okay yah I get it that on the MAIN BALANCE big colored box the number looks cleaner if it's short... that one is okay.

But everywhere else in Copay where the bitcoin value to eight digits is cut off, what's really being accomplished except to add potential confusion?  Far as I can see there's *plenty* of space for the full eight-digits everywhere else in the wallet except for the BIG FONT main screen.

I can't even tell you the number of times I've had to go into the drill down "advanced" dialog and list addresses just to manually add-up actual values to get my REAL precise wallet balance, or (worse) had to look it up on an external block explorer by manually clicking thru several past transactions.  This caused way more inconvenience and time lost than whatever efficiency or UI "savings" is the point of truncating the bitcoin values.

IMHO *all* balances everywhere in Copay *except* for the one big-box main screen should be full eight digits...

**Comment by gabegattis** [comment]
Presumably because the UI elements would be too narrow on small/low-res displays, like mobile phones.

I didn't design it so idk

**Comment by dan-da** [comment]
Agreed.   It should either be 8 digits of precision fixed, or make it a user pref.

**Comment by JDonadio** [comment]
We have new design on Copay. I'll check if it's still happening and create a new issue based on this.
