### ISSUE TITLE
Allow qr codes to be copied and/or saved.

### ISSUE THREAD

**Issue by gabegattis** [bitpay/copay#4723]
In the "RECEIVE" tab, we allow the user to generate qr codes. A user may want to copy that image or save it to a file. This way, they can open it in another program (gimp, photoshop), print it out on paper, put it on their website, etc.

Bitcoin Core lets you copy or save the image as well as the URI string.

**Comment by JDonadio** [comment]
The QR code have the ability to be copied by clicking. About to copy/save the image either in mobile and desktop versions you can use many apps to save and edit images, so IMHO we don't need to add that ability.
