### ISSUE TITLE
Better transparency/verification of address when buying amazon gift card.

### ISSUE THREAD

**Issue by gabegattis** [bitpay/copay#4724]
When I purchase an Amazon gift card, I see the standard "SEND BITCOIN" view with the amount, address, and fee.

I did not enter this address myself, so I have no idea where it comes from.

What it is actually doing is creating a new BitPay invoice, and getting the address from there. It hides the fact that a BitPay invoice is created. This is fine, but the user needs some confidence that they aren't just sending coins to some random address.

Payment protocol would be ideal here. Instead of just seeing a random address, we(BitPay) could send a signed payment request so that the wallet can show the normal paypro info to the user.

We should also add a timer so that copay doesn't try to pay an expired invoice if the user waits a long time for some reason.

**Comment by matiu** [comment]
We do use paypro for buying amazon gift cards  but the confirm popup still show the outgoing address.

**Comment by getpayed777** [comment]
I just did the same thing payed for 32 dollar gift from my Copay  sent bitcoin + fee 24 hours a go.my wallet shows set payment still don't have the gift card on my wallet can you help me.
