### ISSUE TITLE
Allow setting fee policy on a per wallet and per transaction basis.

### ISSUE THREAD

**Issue by gabegattis** [bitpay/copay#4725]
Currently, the only way to set a fee policy is to do it at the global level. This same setting applies across all my wallets, including my testnet wallets.

On some wallets, like a livenet spending wallet, I may want normal or priority fee. For others, like my testnet wallets, I want to use the lowest fee possible.

I also may want to change the fee level when I actually send the transaction.

In order to do any of this, I have to change the global setting every time I want to do something different. Later, I have to remember to change it back so I don't accidentally send a tiny fee tx when I don't want to.

This is, once again, a scenario where we should look to Bitcoin Core for an example.

**Comment by KeyJockey** [comment]
Once again IMHO a simple way to address this would be to *just* add a very easy, direct ability to quickly and precisely TWEAK the actual fee NUMBER, via an off-by-default *Advanced User* feature for precise miner fee value control... 

![feecontrol](https://cloud.githubusercontent.com/assets/13903392/18207870/0117d180-70fb-11e6-9662-744a89ca3068.png)

...full details in the most-commented and over-one-year-old issue thread here: https://github.com/bitpay/copay/issues/3111 

Seriously do NOT understand WHY this idea is not getting more support around here.  

Copay is the best wallet out there in every other way *except* for this insane fee-design that does not offer the user ANY meaningful control over how we can spend OUR MONEY on miner fees, at all....

**Comment by gabegattis** [comment]
@KeyJockey Please stop spamming every issue about this. You already have issue #3111 for this. We don't need to have this taking up space and time in other threads.

To be honest, I actually agree with what you are saying about absolute fees, but it does not help to bring it up all the time on any issue that is even tangentially related.

**Comment by KeyJockey** [comment]
>To be honest, I actually agree with what you are saying about absolute fees, but it does not help to bring it up all the time on every issue that is even tangentially related.

OK, thanks.... and okay okay I'm sorry for bringing it up so much but it's just really frustrating that it seems to have so little actual support, and ZERO comment from any of the devs on IF or WHEN it will even be addressed.

If people like you who agreed with me on it would say so a bit more, especially actually over on my issue thread, instead of silently agreeing with me, then maybe I wouldn't feel so ignored on the issue so that I have to "spam" so much.

But... ok ok, I'll try harder to tone it down.

Would just be nice to hear SOME positive news on IF/WHEN maybe the miner fee control issue will be taken seriously for next version (?) of Copay proper (and not a fork version...)

**Comment by bitjson** [comment]
@gabegattis – do you think this issue would be adequately solved by: https://github.com/bitpay/copay/issues/4657?

If you're able to very-easily modify the fee on the send screen, I imagine that would solve for most use cases? Design-wise, it could get pretty complicated to override a global setting wallet-by-wallet.

**Comment by gabegattis** [comment]
I think that would take care of it. If I can specify the fee rate at the time of send, that would take care of most of my issues.

**Comment by bitjson** [comment]
Awesome. Merging to #4657
