### ISSUE TITLE
Fee popup when using "Send Max" is not styled

### ISSUE THREAD

**Issue by gabegattis** [bitpay/copay#4727]
I am using the 2.6.0 linux app.

When I use "Send Max", I get a popup that says, "0.000284 BTC will be deducted for bitcoin networking fees". This is not a very good user experience. The window is unstyled and does not match the rest of the UI. I am not actually making a decision, so having both "cancel" and "ok" seems unnecessary. There is already a "cancel" button on the main tx view. That amount is also not visible once I click "ok".

It might be best just to get rid of that popup completely. We could display the fee used on the main transaction view.

![fees](https://cloud.githubusercontent.com/assets/4419243/18109655/b436c87e-6ee0-11e6-83a9-ac77447659b2.png)

**Comment by JDonadio** [comment]
This is fixed in the new UI
