### ISSUE TITLE
Import backup failure: "Check input file and spending password"

### ISSUE THREAD

**Issue by gsakhel** [bitpay/copay#4730]
Hi all,  I'm having trouble with recovering an old singlesig copay wallet.  I was a beta tester and one day my app stopped opening (possibly when they moved out of beta).  This was on iOS and I created the wallet on Copay v0.9.1 in December 2014...I recently redownloaded the app and now have v2.6.0

I did NOT use the 12 word phrase but have the long backup plain text file.  When I try to import, I'm presented with this error:
"Could not import.  Check input file and spending password"

What's interesting is that when I try an incorrect password, I get a different error:
"Could not decrypt file, check your password"

I tried the online recovery tool but was presented with this error:
"The wallet configuration (m-n) does not match with values provided."

Any help or direction would be greatly appreciated.

*Screenshots of the 3 errors: http://imgur.com/gallery/u5S7N

**Comment by dabura667** [comment]
https://bitwiseshiftleft.github.io/sjcl/demo/

Try downloading the above site from github, and use it to decrypt your JSON into a decrypted JSON.

Seeing the decrypted values, if you could maybe tell us what kind of values are in it, and the "version" values etc. if any.

**Comment by gsakhel** [comment]
@dabura667 Thank you for your response and the helpful link.

Decrypting the JSON worked fine and it shows a lot of info including: walletID, copayerIndex, publicKeyRing, copayersExtPubKeys, txProposals, privateKey, extendedPrivateKeyString, version, fullName, password, email, etc...it even has a record of my transaction notes.

The decrypted JSON begins with `{"wallets":[{"opts":{"id":` and ends with `"backupNeeded":false}`

As for "version" values, there's a few:
1. wallets (at the beginning) shows 0.9.6
2. under "builderObj" version: 1 (this occurs three times, I'm guessing from multiple transactions)
3. under "merchant"..."payment_details_version":1
4. one last "version" is shown at the end in the same string as my fullName, password, & email: "version": "0.9.6"

Please let me know if any additional info is needed.  Thanks again for the help and direction.

**Comment by gabegattis** [comment]
You have the extended private key which is the important thing.

0.9.6 is a pretty old version of Copay. You might have to download and run 0.9.6 and try to import the wallet on that version. If you manage to do that, it would probably be best to create a new wallet on the most up-to-date version of Copay, and just sweep all the funds to that new wallet.

You can get the source code for 0.9.6 at https://github.com/bitpay/copay/releases/tag/v0.9.6

**Comment by matiu** [comment]
> I tried the online recovery tool but was presented with this error:
> "The wallet configuration (m-n) does not match with values provided."

This can only happen if your file does not match the settings of the recovery tool.  What can of wallet was it?  1-of-1?

**Comment by gabegattis** [comment]
@matiu He mentioned it was single sig. I don't know if that means 1-of-1 multisig or just traditional p2pkh.

**Comment by matiu** [comment]
The backup is just a encrypted JSON. The message 

> "The wallet configuration (m-n) does not match with values provided."

Appears if M/N  does not match the settings on the JSON. PRobably the JSON does not correspond to a 1-1 wallet.

**Comment by gsakhel** [comment]
@gabegattis Thank you for the link.  I've tried running v0.9.6 but it seems I'm hitting compatibility issues and am failing at "node-gyp rebuild".  I'll continue trying over the weekend.

@matiu I believe I picked the simplest option at the time so it should be a standard wallet; it was certainly not a multi-sig.  In the decrypted JSON I do see the fields: "requiredCopayers":1,"totalCopayers":1

**Comment by gabegattis** [comment]
Kind of a shot in the dark, but using an older version of nodejs might fix the node-gyp rebuild problems.

**Comment by matiu** [comment]
We will check the recovery tool, it should work then.

Regarding the issue, importing in Copay, Were you were using the  default BWS on the original wallet?

**Comment by matiu** [comment]
1. we will review the recovery tool and let you know. thanks for the
information.

2. what platform are you using for Copay?

we have identified a problem on the error display of import. we can build
an release a new version with that fix so.we.can undertand better what is
happening.

**Comment by gsakhel** [comment]
@gabegattis Good idea, thank you.  I noticed `WARN engine bitcore@0.1.41: wanted: {"node":">=0.10 <0.10.36"}`.  I tried your suggestion of downgrading nodejs and it did move me forward.  `npm start` worked and was "listening at localhost:3000" but my browser shows title "Copay - Multisignature Wallet" with a blank page.  Checking the console there appears to be a js error:
<details>
  <summary>Click to expand the browser console error details</summary>
  unreachable code after return statement[Learn More]copayBundle.js:7030:2
Error: [$injector:modulerr] http://errors.angularjs.org/1.3.20/$injector/modulerr?p0=copayApp&p1=%5B%24injector%3Aunpr%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.3.20%2F%24injector%2Funpr%3Fp0%3D%2524idleProvider%0AS%2F%3C%40http%3A%2F%2Flocalhost%3A3000%2Flib%2Fangularjs-all.js%3A6%3A417%0Acb%2Fp.%24injector%3C%40http%3A%2F%2Flocalhost%3A3000%2Flib%2Fangularjs-all.js%3A38%3A7%0Ad%40http%3A%2F%2Flocalhost%3A3000%2Flib%2Fangularjs-all.js%3A36%3A13%0Ae%40http%3A%2F%2Flocalhost%3A3000%2Flib%2Fangularjs-all.js%3A36%3A283%0Ad%40http%3A%2F%2Flocalhost%3A3000%2Flib%2Fangularjs-all.js%3A34%3A490%0Ag%2F%3C%40http%3A%2F%2Flocalhost%3A3000%2Flib%2Fangularjs-all.js%3A35%3A117%0Ar%40http%3A%2F%2Flocalhost%3A3000%2Flib%2Fangularjs-all.js%3A7%3A320%0Ag%40http%3A%2F%2Flocalhost%3A3000%2Flib%2Fangularjs-all.js%3A34%3A399%0Acb%40http%3A%2F%2Flocalhost%3A3000%2Flib%2Fangularjs-all.js%3A38%3A135%0Atc%2Fd%40http%3A%2F%2Flocalhost%3A3000%2Flib%2Fangularjs-all.js%3A17%3A381%0Atc%40http%3A%2F%2Flocalhost%3A3000%2Flib%2Fangularjs-all.js%3A18%3A179%0AJd%40http%3A%2F%2Flocalhost%3A3000%2Flib%2Fangularjs-all.js%3A17%3A1%0A%40http%3A%2F%2Flocalhost%3A3000%2Flib%2Fangularjs-all.js%3A252%3A171%0Aa%40http%3A%2F%2Flocalhost%3A3000%2Flib%2Fangularjs-all.js%3A165%3A217%0Alf%2Fc%40http%3A%2F%2Flocalhost%3A3000%2Flib%2Fangularjs-all.js%3A32%3A384%0A
S/<()
angularjs-all.js:6
g/<()
angularjs-all.js:35
r()
angularjs-all.js:7
g()
angularjs-all.js:34
cb()
angularjs-all.js:38
tc/d()
angularjs-all.js:17
tc()
angularjs-all.js:18
Jd()
angularjs-all.js:17
<anonymous>
angularjs-all.js:252
a()
angularjs-all.js:165
lf/c()
angularjs-all.js:32
angularjs-all.js:6:417
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.localhost:3000

</details>

**Comment by gsakhel** [comment]
@matiu I appreciate you reviewing the recovery tool!  I didn't really fool around with the options of the Copay wallet, so the original wallet should have been using the default BWS.

My original and new Copay wallets were installed on iOs.

**Comment by JDonadio** [comment]
@gsakhel I was working on recovery tool and there was a little bug but the fix was already sent. I'll update you so you can try to recover and move your funds to a new and safe wallet

**Comment by matiu** [comment]
@gsakhel we have made a small fix on the recovery tool, could you try again?

Would it be possible for you to install Copay desktop and try to import the backup there? We can release v2.6.1 with better import error logs, so you can check it there.

**Comment by matiu** [comment]
@gsakhel sorry, I was wrong. The recovery tool, nor Copay 2.6 support backups that old. We used to supported in a special import view, but that was removed ~4 months ago (in 2.1).

You option is:

 - extract the xPrivKey from the decrypted JSON
 - in Copay 2.6, go to import wallet
 - in the 'Recovery phrase' paste the xpriv (something like: xprvXXXXXXXX)
 - open the advanced options 
 - in the derivation path enter: `m/45'/2147483647`  
(details at https://github.com/bitpay/copay#wallet-export-format)

Please let us know how it goes.

**Comment by JDonadio** [comment]
@gsakhel if you problem remains I'll reopen this issue.

**Comment by gsakhel** [comment]
Thank you all for your help.  I was able to create a wallet following @matiu suggestions and the error instructions below, but I have zero balance (which may be correct).  Which addresses should I be double checking to verify this balance is correct?

@matiu When I tried following your exact instructions, I was presented with this error:

> Could not access the wallet at the server.
> Please check:
> The password of the recovery phrase (if set)
> The derivation path
> The wallet service URL
> 
> NOTE: To import a wallet from a 3rd party software, please go to Add Wallet > Create Wallet, and specify the Recovery Phrase there.

Combining these instructions with yours allowed me to create the wallet.
