### ISSUE TITLE
xPrivKey

### ISSUE THREAD

**Issue by terrylai** [bitpay/copay#4732]
Hello all,

Could I transfer the xPrivKey to a normal Private Key?

Or say, how to convert xPrivKey to privKey_1H_0?

BR,
Terry

**Comment by matiu** [comment]
You can use tools like https://bitcore.io/playground/#/hdkeys
to device privKeys from xPrivKey.

The reference for that process is at https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki

**Comment by terrylai** [comment]
Hello,

Could u teach me how to use these functions to get privKey_1H_0 from xPrivKey?

BR,
Terry

**Comment by dabura667** [comment]
It's very easy, just read the site.

**Comment by terrylai** [comment]
Hello,

OK, I finally worked out it.

Actually I am thinking to use this private key to find the signature of message so as to implement Bit ID in the wallet.

However, I find the signature length is different to that computed in bitcoind; where the calculation code of signature is found from bitcore wallet service.

So my final question is that is it possible to compute the same signature as in bitcoind?

Thanks!

**Comment by matiu** [comment]
thanks for the update!

bitcore-lib use determinist-k for signatures.
