### ISSUE TITLE
Coin control features.

### ISSUE THREAD

**Issue by nathaniel-mahieu** [bitpay/copay#4737]
Do we have any plans to integrate coin control functionality into Copay? I see this as a core feature.

**Comment by bitjson** [comment]
It's possible to get even better (and much simpler) privacy by separating funds into multiple wallets.

Is there another use case you're interested in with this feature? Could you describe what you'd like to do in a little more detail?

**Comment by bitjson** [comment]
Closing this for now, but please let me know if we should reopen.
