### ISSUE TITLE
Multiple Trezor signatures from single Copay instance

### ISSUE THREAD

**Issue by nathaniel-mahieu** [bitpay/copay#4738]
Can multiple people sign a transaction from a single Copay instance?

For example, If I make a payment proposal and sign it with my Trezor, can my friend then hook up and sign as well?

Currently this does not appear to be working.  I note several reasons:
 - If you are a member of a multisig wallet, signing the transaction once prevents any more signatures from your Copay instance.
 - You cannot add a second instance of the multisig wallet with a different "primary" xpub

These issues suggest two things which I find disappointing:
 - multiple Copay instances are needed to complete a multisig transaction
 - Copay is not an effective multisig cold storage solution

Let me know if there is a way to achieve this that I am missing!

**Comment by matiu** [comment]
no, using the same Copay instance for multiple copayers of the same wallet is not supported, and probably will not be supported on the short term.

Dup: https://github.com/bitpay/copay/issues/3545

**Comment by nathaniel-mahieu** [comment]
Could you suggest  how to get a Copay instance to let me sign as an alternate copayer on a multisig wallet?  When I import the backup it designates copayer 1 as the primary copayer and only allows signatures from that key.  This can involve a second Copay instance.

**Comment by martindale** [comment]
This is explicitly desirable for me.  Please re-open.
