### ISSUE TITLE
Have credentials need help recovering. Tool failed

### ISSUE THREAD

**Issue by MXAngel** [bitpay/copay#4742]
Can I recover my .47 btc? I have full mnemonic and withdraw phrase 

I suspect it was stolen but I did have almost half a bit coin in there ... And if it was stolen could you provide what ever applicable information you have to me? I went to withdraw or sell coin and for some reason the password wasn't accepted  multiple times even though I wrote it down  and right about that time I became aware that my android was hacked and I could actually see the hacker trying to take the money so I disconnected the screen function from my phone and now my phone no longer works so I'm not sure if the money is there or not but I do have all of the verification info and the Full account information regarding my ticket #158364.  I was directed to this site and I have attempted to use the recovery tool unsuccessfully it indicated that there was no balance and I would just like to confirm if the money was stolen or if it's hanging on out there

**Comment by isocolsky** [comment]
If the recovery tool indicated that there was no balance, chances are the coins are gone. To be sure, get a clean Copay install. Go to Add Wallet -> Import and enter the 12 words.

**Comment by gabrielbazan7** [comment]
Please reopen if still valid
