### ISSUE TITLE
I sent half of my bitcoins to one address but my Copay wallet is empty now?

### ISSUE THREAD

**Issue by jamesponce** [bitpay/copay#4745]
I received 8.15215176 btc today and sent out half of that amount to my Circle wallet. Once I made the transaction, the remaining balance in my Copay wallet is now 0. For some reason my transaction went through but the other bitcoins we magically sent off to a different address. I am not sure what is going on but how can I regain my lost bitcoins? Clearly in my activity it says received 8.15215176 btc and sent 4,076,075.50 bits. There is no other transaction that says where the other coins went I can only see in the blockchain that they were sent to a different address. For some reason Copay sent all of my bitcoins and then split it between two address but I do not own the other address.

**Comment by isocolsky** [comment]
This is just the way Bitcoin works. The rest of your coins were sent to a change address which is part of your wallet. Once the tx confirms (which should have already happened) you should see the expected balance.

**Comment by jamesponce** [comment]
yea it worked thanks for your help. I nearly had a heart attack lol If you
don't mind real quick, why does bitcoin send ALL of the coins then refunds
it back? Why not just take what you ask to send? Is this just for security
reasons?

**Comment by isocolsky** [comment]
Glad to hear everything is ok.
Funds in bitcoin are spent in chunks. These chunks correspond to the transactions you received but not yet spent. So if you receive a tx for 1 BTC and you want to send 0.8 BTC to someone else, you will be using that 1 BTC transaction as the input. Since partially spending is not possible you will need to specify where to receive the remaining 0.2 BTC (minus fees). So after the new transaction has been broacasted you will become the recipient of your own transaction which will be interpreted by the wallet as you having a 0.2 BTC balance.

**Comment by jamesponce** [comment]
oh but I never specified where I want the remaining balance to go. A
different address was used other than the ones associated with my wallets.
Or does the wallet automatically create this new address for the refund?

**Comment by isocolsky** [comment]
The wallet handles that for you so you would experience it as a simple spending operation. The address belongs to a separate branch of addresses called "change addresses" but is still part of your wallet.

**Comment by jamesponce** [comment]
this is so mind boggling. I love bitcoin lol thanks for your help! One more
question though. How safe is my information transferring from Copay? I
understand everything is on public records as far as the transactions are
handled but does Copay attach my addresses to my information? After all
crypto is supposed to be anonymous right?

**Comment by isocolsky** [comment]
We all love Bitcoin :D

WRT privacy, Copay does not collect personal information from the user or from the device. All sensitive data (like messages attached to txs) is locally encrypted before sent to the server. 

Having said this, servers are able to log info and it is a good practice to always assume they do.

If you are concerned about your privacy, and have the technical knowledge, there is always the option of running Copay's server [Bitcore Wallet Service](https://github.com/bitpay/bitcore-wallet-service) locally.

**Comment by jamesponce** [comment]
ok thanks ill take a look at it

**Comment by isocolsky** [comment]
One more thing

> After all crypto is supposed to be anonymous right?

Bitcoin is not anonymous. You could preserve your privacy while transacting but it is really hard to do so and it is usually possible to tie addresses together as belonging to the same person. This could change in the future though.

**Comment by jamesponce** [comment]
So in your opinion what is the most secured coin out there? I know there's
over 200 and since bitcoin is like the main one for currency exchange it
gets all the attention.

**Comment by isocolsky** [comment]
I do not have an opinion on that 🙊 😉 . Best thing is to do some research.
Good luck!
