### ISSUE TITLE
Updating Wallet Screen...

### ISSUE THREAD

**Issue by pooleja** [bitpay/copay#4746]
I just opened the wallet today and got stuck at "Updating Wallet..." for about 10 minutes with the UI looking like something went wrong.  There were overlapping objects and just a white background.  (sorry I should have screen captured but I didn't)

In the session log I see the following errors in red:

undefined is not an object (evaluating 'hexString.charAt')
self.resetForm is not a function. (In 'self.resetForm()', 'self.resetForm' is undefined) 

It would probably be better to have more information to the user explaining what is going on and also fix the UI issue (I thought the app was dead in the water).  Just thought I should report this because I could see someone getting freaked out if they can't get to the wallet and the screen looks like things have gone fubar.

After 10 minutes everything seems to have sorted itself out.

**Comment by gabrielbazan7** [comment]
Thanks for the report. Working on that. Related to : https://github.com/bitpay/copay/issues/4733
