### ISSUE TITLE
unusable

### ISSUE THREAD

**Issue by zwykx** [bitpay/copay#4749]
incredible !
You develop a product without providing any information to install it.
I dowloaded Copay-linux.zip and uncompressed it.
And now, I have some executable that don't do anything but no readme, nothing to explain to the user what to do !!!!!!!!!!!!!

**Comment by gabrielbazan7** [comment]
https://github.com/bitpay/copay/wiki/COPAY---FAQ#how-to-install-copay-wallet-in-linux

**Comment by zwykx** [comment]
$ run ./Copay
bash: run : commande introuvable

**Comment by gabrielbazan7** [comment]
Check if the path of the working directory is the same where you extract the contents of the zip file. Also, just write on the terminal "./Copay" without "run".

**Comment by zwykx** [comment]
./Copay works better. I have a window with menus to explore.
See you later

**Comment by gabrielbazan7** [comment]
Great! If you have more questions about how Copay works, feel free to open another issue. Personally, I could recommend you this Copay tutorial at youtube https://www.youtube.com/watch?v=9qgqPvc6kgM. 
Bye!
