### ISSUE TITLE
Exporting wallet through QR code yields QR code unprotected by password

### ISSUE THREAD

**Issue by RobinTick** [bitpay/copay#4750]
When I don't delete the recovery phrase (unsafe) I can export the wallet to a QR code that requires a password to be imported, which is safe.
When I do delete the recovery phrase (safe) I can only export to a QR code that does not require a password to be imported, which is unsafe.

Is this intentional ? this seems wrong to me.

**Comment by isocolsky** [comment]
Hi, nice catch.
What is happening is the QR will get generated 1. from the recovery phrase if available or 2. from the master extended private key if the recovery phrase was deleted.
When importing from a QR of type 1, the recovery phrase is used to generate the master extended private key but this step requires a password (if one was set at creation time). In the case of a type 2 QR, the private key is already there so no other data is needed from the user.
We will look into this.
Thank you for reporting!

**Comment by JDonadio** [comment]
In the new version of Copay the ability to delete the recovery phrase was removed, so I think this is not longer relevant.
