### ISSUE TITLE
Mobile wallet spending pass misplace

### ISSUE THREAD

**Issue by Mjons** [bitpay/copay#4751]
Hey guys,

So i would like to recover a wallet without needing my spending password because it seems to have been forgotten

I read in your FAQ "There is no way to reset the spending password. However, as the spending password is only stored in the client you could delete your encrypted wallet and import it with the 12 words backup."

If the wallet is on my mobile phone which steps do i take to delete the encrypted wallet and then import it on the desktop app. (I do still have my 12 word recovery pass)

Please advise, appreciate it.

**Comment by Mjons** [comment]
got it guys, thanks! But still- would like to know the steps to backup in case:)

**Comment by gabrielbazan7** [comment]
Hi! take a look at this question on the FAQ https://github.com/bitpay/copay/wiki/COPAY---FAQ#how-do-i-get-access-to-my-wallet-in-case-of-loss

**Comment by gabrielbazan7** [comment]
You could delete the wallet in "wallet preferences"->"advanced"->"delete wallet"
