### ISSUE TITLE
Windows Phone App: don't have a password to make transfers, backup or use the wallet

### ISSUE THREAD

**Issue by Dahveedon** [bitpay/copay#4753]
Hi,

I've created the wallet last year and never used till i tried today. Now, after the update of the windows phone app (i only configured on phone) it's asking me a password. i. If I remember well at that time, when I opened the account din not asked me for any password. I think this was introduced later.

I don't have a backup or phrase words, only the app on the phone, the email that is configured on that app. I know, it was easy to have these but please let's find a solution to recover the wallet or use it somehow.

Thank you!

**Comment by gabrielbazan7** [comment]
Without the file backup or the words you will not be able to recover the wallet. Try to remember the spending password, you should have set it on the past. Maybe, you could search for the file on your email.
