### ISSUE TITLE
1-1 to 2-2

### ISSUE THREAD

**Issue by blork047** [bitpay/copay#4754]
I coulnd't find the way to upgrade my wallet 1-1 to 2-2

I apologize since it shouldn't be that hard to find how but now i'm stuck with a 1-1

Any help woould be appreciate

thanks a lot!

**Comment by dabura667** [comment]
You can not "upgrade"

You have to click "create new wallet" and create a 2 of 2.

Copay can manage multiple wallets, but once you make a wallet, you can not change its signature structure.

**Comment by JDonadio** [comment]
Thanks @dabura667 for clarify this
