### ISSUE TITLE
Feature Request: Sub-accounts

### ISSUE THREAD

**Issue by drwasho** [bitpay/copay#4756]
This is more a cosmetic change, but it would be useful if I could allocate funds within a wallet into sub-accounts with different balances. 

This will enable the micro-management of funds within a wallet:
- I can set aside some of the funds to savings, bills etc without needing to create a separate wallet. 
- This is especially important for folks who get part of their income paid into their wallet
  - Asking them to split the distribution or make additional transactions into other wallets isn't ideal
- When I transfer funds to another address, it can drawdown the balance of the sub-account I'm choose to pay out of
- This replicates the kind of user experience people are used to with online banks, where funds can be easily moved back and forth
  - Unfortunately this isn't achieved with separate wallets as the transfer of funds between wallets involves a bitcoin transaction (and fees are tending to go up for the time being)

As far as I can tell, this won't require any changes in how transactions are made. Rather, this is an accounting change to help users better manage their money.

**Comment by gabegattis** [comment]
Sounds like the accounts feature in Bitcoin Core.

**Comment by TradZAllDay** [comment]
Yes 'BitPay' are crazy over FEEs!  What is the point of charging fee's for internal transfers🤔"GREED" of course! But I still l0ve BitPay, especially since recently receiving my new BitPay/Visa debit card ;)
I am now spoiled as this card is a MUST have! No more waiting for days for m0ney to arrive.  I'm a Bitcoin denominated day-TRADER so, being able to take profits out on any given day is the Business! 🤑

**Comment by TradZAllDay** [comment]
Bitcoin denominated day-TRADER meaning, I trade whatever market I choose(preferably forex) and I use Bitcoin denominated brokers who solely use Bitcoin.  So now when I profit, I can send right on over to my BitVisa ready to spend;)

**Comment by dabura667** [comment]
Bitpay doesn't charge fees.

The only fees in Copay are the bitcoin network fees. These fees are necessary to get miners to accept your transaction into the blockchain.

**Comment by JDonadio** [comment]
You can change the account index from derivation path displaying the advanced settings at wallet creation.
