### ISSUE TITLE
remaining funds became unavailable after payment

### ISSUE THREAD

**Issue by seekr** [bitpay/copay#4757]
I made a payment and after that  the remain funds became "unavailable" (showing as pending confirmation). Why is this? 

All funds where well confirmed (over a month ago with over 6 confirmations) in the wallet before I made the payment.

**Comment by gabrielbazan7** [comment]
Take a look to the Copay FAQ:  https://github.com/bitpay/copay/wiki/COPAY---FAQ#why-creating-a-transaction-proposal-lock-my-balance-and-is-significantly-higher-than-the-proposal-amount
