### ISSUE TITLE
activity list shows Chinese symbols instead of date and time.

### ISSUE THREAD

**Issue by RobinTick** [bitpay/copay#4759]
Often when I open the app my activity list shows Chinese symbols below the transactions where the date and time should be.
This is fixed temporarily when I choose Scan addresses for funds from the advanced menu.

Also the icon for "received" is missing, the icons for moved and sent do display.

Im running the app on Windows 10 Mobile on a Lumia 950XL.

**Comment by Derrick-** [comment]
I can confirm that this happens on Lumia 929 Win8.1 phone as well.

The buttons at the bottom of account page disappear sometimes. I have to restart app to recover.

**Comment by RobinTick** [comment]
![wp_ss_20160916_0001](https://cloud.githubusercontent.com/assets/9660062/18603033/5b2d7d04-7c6e-11e6-8b0c-ccbc64f2e266.png)

**Comment by dabura667** [comment]
oh wow...

That is real Chinese. In fact, it's the exact chinese we have on file for "one month ago" and "7 days ago" and "16 days ago"...

I'm guessing it's a bug with the library that replaces text based on the language settings... for some reason it's just replacing those specific places only...

Your wallet language is set to English right?

Could you try switching the language to something else, then immediately switch it back to English and let me know how that goes. (Remember the position of the buttons you pressed to get to the Language settings so you don't get lost)

**Comment by RobinTick** [comment]
Yes my wallet is set to English, I switched the language to Chinese and back to English, that did fix the date display which is now always in English.
The icons for received transactions are still not displayed however.
