### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ikee82** [bitpay/copay#4763]
Hello 
I am new to this and i want to make a Copay wallet on testnet.
Can you help me with some guidence?

thanks in advance

**Comment by dabura667** [comment]
When creating a wallet, tap "advanced options" and make sure the Testnet button is green.

**Comment by ikee82** [comment]
thanks, figured out meantime:)

**Comment by JDonadio** [comment]
@ikee82 glad to know it. If you need more help please let us know, enjoy!
