### ISSUE TITLE
Connecting with Coinbase issue

### ISSUE THREAD

**Issue by Bulldawg777** [bitpay/copay#4766]
Hey guys... I just downloaded the Windows app and I'm trying to connect my Copay app with Coinbase. Everytime I try, after viewing and accepting the permissions, I get this blank screen and nothing happens. Any suggestions?

Clay

**Comment by cmgustavo** [comment]
Hi @Bulldawg777 , this is an known issue that was not resolved.

There is a workaround that should work in most cases (only desktop versions):

https://github.com/bitpay/copay/issues/4703#issuecomment-242387974

Please, let us know how it goes. Thanks.
