### ISSUE TITLE
A few questions regarding development and contributions.

### ISSUE THREAD

**Issue by eddiejibson** [bitpay/copay#4769]
Hello,

So I'm quite new to working with Bitcoin and Java. However, I added some things which I think might make Copay even better but am actually unsure how to get the 'software' to be able to install/setup using one setup.exe? If anyone could help me with this, it would be great. I want to see if people like it before I actually submit the changes.

Thanks.

**Comment by bitjson** [comment]
Hey @eddiejibson – take a look at the latest version of the [readme](https://github.com/bitpay/copay/blob/master/README.md) – hopefully that should help to get you up and running. Looking forward to seeing your work!

**Comment by sid64** [comment]
Log off me and stop all SENDING THOSE crap !!!!!!!!!!!
 
ODHLASTE MNE A PŘESTANˇTE S POSÍLÁNÍM TĚCH BLBOSTÍ!!!!!!!!!!!
______________________________________________________________
> Od: Jason Dreyzehner <notifications@github.com>
> Komu: bitpay/copay <copay@noreply.github.com>
> Datum: 27.10.2016 05:03
> Předmět: Re: [bitpay/copay] A few questions regarding development and
>
Hey @eddiejibson <https://github.com/eddiejibson> – take a look at the latest version of the readme <https://github.com/bitpay/copay/blob/master/README.md> – hopefully that should help to get you up and running. Looking forward to seeing your work!

**Comment by bitjson** [comment]
@sid64 – if you'd like to stop receiving email notifications for GitHub activity, you can update your GitHub settings here: https://github.com/settings/notifications

You can also [unwatch](https://help.github.com/articles/unwatching-repositories/) this repo.
