### ISSUE TITLE
restoring copay on my new iphone trough icloud

### ISSUE THREAD

**Issue by NewNikola** [bitpay/copay#4772]
Hello,

i have installed copay app on my new iphone trought my icloud backup but now my e-wallet is empty.

Please i need help to get my bitcoins back :(

Thanks.

**Comment by dabura667** [comment]
1. Create New Wallet
2. Import Wallet
3. Type in the 12 word phrase that you copied down as a backup, or input from file/text the backup file that you made. (Depending on the version you created your wallet in, the backup method will vary)
4. It will be imported and you can use your wallet again.

Also, iCloud backups do not store secret information, so all your apps will require to re-login and all your bitcoin apps will require to restore backups.

If you create a backup via USB on iTunes with "Encrypted backup" checked, then restoring that backup should also restore all your passwords for all your apps as well as private keys for most bitcoin apps.

However, with bitcoin... you should ALWAYS backup your bitcoin separately just in case something happens to your phone backup.


If you don't have a backup... then I am sorry for your loss.

**Comment by NewNikola** [comment]
Damn i lose all my bitcoins there :(

can i get some restore trough the email which i used there?

Sent from my iPhone

On Sep 28, 2016, at 01:38, Dabura667 <notifications@github.com<mailto:notifications@github.com>> wrote:


  1.  Create New Wallet
  2.  Import Wallet
  3.  Type in the 12 word phrase that you copied down as a backup, or input from file/text the backup file that you made. (Depending on the version you created your wallet in, the backup method will vary)
  4.  It will be imported and you can use your wallet again.

Also, iCloud backups do not store secret information, so all your apps will require to re-login and all your bitcoin apps will require to restore backups.

If you create a backup via USB on iTunes with "Encrypted backup" checked, then restoring that backup should also restore all your passwords for all your apps as well as private keys for most bitcoin apps.

However, with bitcoin... you should ALWAYS backup your bitcoin separately just in case something happens to your phone backup.

If you don't have a backup... then I am sorry for your loss.

-

**Comment by dabura667** [comment]
When did you first create your wallet?

When was the last time you used it?

**Comment by NewNikola** [comment]
I have copay on my old iphone maybe one year ago (really not sure, im looking trough my emails for the first transaction but i can't find).

But i can find my last transaction and is this:

[image1.PNG]

i have used: 3ki.maki@live.com<mailto:3ki.maki@live.com> email on my old iphone in the copay app.

Sent from my iPhone

On Sep 28, 2016, at 01:53, Dabura667 <notifications@github.com<mailto:notifications@github.com>> wrote:


When did you first create your wallet?

When was the last time you used it?

-

**Comment by dabura667** [comment]
I cannnot see the image.

If the email was a login email (ie. you need to enter your email and your password every time you open the wallet) then you might be able to recover... but if the email was only for notifications, I think your bitcoins are gone.

Next time make a backup.

**Comment by NewNikola** [comment]
Last transaction: September 21, 2016 at 15:19, email: 3ki.maki@live.com<mailto:3ki.maki@live.com>

Sent from my iPhone

On Sep 28, 2016, at 02:17, Dabura667 <notifications@github.com<mailto:notifications@github.com>> wrote:


I cannnot see the image.

If the email was a login email (ie. you need to enter your email and your password every time you open the wallet) then you might be able to recover... but if the email was only for notifications, I think your bitcoins are gone.

Next time make a backup.

-

**Comment by dabura667** [comment]
Ok, in that case, you definitely have a newer wallet... there is no way to recover with just an email.

Sorry for your loss.

**Comment by NewNikola** [comment]
Damn ????

Sent from my iPhone

On Sep 28, 2016, at 02:22, Dabura667 <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, in that case, you definitely have a newer wallet... there is no way to recover with just an email.

Sorry for your loss.

-

**Comment by KeyJockey** [comment]
Is the old phone totally dead?  IF you can just get back on it at least once and LOOK at the old wallet, you'll be able to get the seed words and/or export a backup file so you can then restore on the new phone.

Good luck...
