### ISSUE TITLE
Bug - Payment Protocol 'Payment To' Missing

### ISSUE THREAD

**Issue by unusualbob** [bitpay/copay#4773]
When testing earlier I found that the 'Payment To' field did not show anything. It appears something is wrong with the domain name display, but the bug is potentially limited to testnet. This has been reproduced on multiple devices. These screenshots are done with test.bitpay.com. Tests with bitpay.com showed correctly.

Copay shows blank 'payment to'
![copay-testnet](https://cloud.githubusercontent.com/assets/739442/18894217/bb4b7e1a-84df-11e6-899f-dc633d4ec032.jpg)

See that core shows pay to field correctly
![core-testnet](https://cloud.githubusercontent.com/assets/739442/18894286/0f2375b0-84e0-11e6-8df2-220bca1a694c.png)

It appears the merchant & invoice info was correctly displayed despite the lack of the 'Payment To' field.

**Comment by JDonadio** [comment]
In the new UI the payments (using paypro) looks like:

<img width="449" alt="copay_-_copay_bitcoin_wallet_y_slack_-_bitpay" src="https://cloud.githubusercontent.com/assets/13851807/24913415/86a774d6-1ea7-11e7-9d23-6cd517845277.png">

And clicking on the 🔒 displays the payment detail

<img width="448" alt="copay_-_copay_bitcoin_wallet" src="https://cloud.githubusercontent.com/assets/13851807/24913512/cf46d3b2-1ea7-11e7-803b-90f6e7368158.png">

Please feel free to reopen it if you think I'm missing something else.
