### ISSUE TITLE
Nexus 6P Visual Problems

### ISSUE THREAD

**Issue by martindale** [bitpay/copay#4774]
Copay has rendering issues on Google's flagship Android device, the Nexus 6P (note the thin strip of white above the wallet name):
![screenshot_20160917-232951](https://cloud.githubusercontent.com/assets/129761/18898758/890602c8-84e8-11e6-988d-801598b47b5f.png)

A flexbox-based layout might permanently resolve these kinds of issues for all devices, for what it's worth.

**Comment by bitjson** [comment]
fixed in `master`, and also massively improved again in https://github.com/bitpay/copay/pull/5007

**Comment by martindale** [comment]
Thanks @bitjson!  Looking forward to seeing this land in production.
