### ISSUE TITLE
Two Requests - Activity Refresh & Private Key QR

### ISSUE THREAD

**Issue by jodyrb** [bitpay/copay#4775]
I am using the app for multiple purposes and there are a couple of features that would be beneficial:

1. I'm using the xpub key in another app which is creating new addresses and receiving payments. In Copay, when I refresh the wallet activity, the new transactions are not added. But, when I go to Advanced > Wallet Information > Scan addresses for funds, it will then find and display the new transactions. Would it be possible to do this automatically whenever the wallet activity is refreshed?

2. In 'Single Address Wallet', can you make an easy way to display the Private Key QR code? HD is great, but back in the old days, it was very easy to explain bitcoin with public addresses and private keys. I have an application that needs an easy way to scan private keys with a camera and I would promote your wallet if you can make a way to display the private key when using a 'Single Address Wallet', even if it needs to be password protected. 

Thanks.

**Comment by isocolsky** [comment]
Hi, your first request is discussed on issue #4603.
Could you please close this issue and reopen with just your second request? It will help to keep the discussion focused and improve traceability.
Thanks!
