### ISSUE TITLE
Easily Display Private Key QR Code

### ISSUE THREAD

**Issue by jodyrb** [bitpay/copay#4776]
In 'Single Address Wallet', can you make an easy way to display the Private Key QR code? HD is great, but back in the old days, it was very easy to explain bitcoin with public addresses and private keys. I have an application that needs an easy way to scan private keys with a camera and I would promote your wallet if you can make a way to display the private key when using a 'Single Address Wallet', even if it needs to be password protected.

**Comment by JDonadio** [comment]
Hi @jodyrb sorry for the delayed reply. You can use [this site](https://iancoleman.github.io/bip39/) to get what you need, but we are not planing to add this as a feature.
