### ISSUE TITLE
Different XPUB between 

### ISSUE THREAD

**Issue by steffink** [bitpay/copay#4781]
With a Trezor Hardware Device I created a Copay MultiSig Account. 

Under wallet.mytrezor.com I can see my Account public keys (XPUB) of my Trezor which is this one (last characters are replaced with .): 
xpub6CfQsUbhMjjqGTf9gQCToqvfSqBf4tkEJcrQMdaRmpEy97wKssfK8dTZEm7EKVvaiE7LsBKGbYb4XAUir6sZMUsvdk8Qh..............

But in my Copay Software I see within Wallet information 
xpub6CyiDNMRPYaj7eKDivMkAWhvh5cnPeBT68B8u2TjtHjRjZxt8WeUMhCS5EQu2zeFs7Yam6afhwDyonYyH4H9tbXd5r2PAJVYvXR........
(m/48'/0'/0')

So a different xpub. 

How can I reformate the xpub from Trezor so that I can double-check that Copay uses the same xpub?
Thanks for your help.

**Comment by dabura667** [comment]
> How can I reformate the xpub from Trezor so that I can double-check that Copay uses the same xpub?

Program your Trezor to show you the m/48'/0'/0' xpub

(default for myTrezor is m/44'/0'/x' where x is the account number - 1)

**Comment by steffink** [comment]
Thanks.
