### ISSUE TITLE
Amazon Giftcard

### ISSUE THREAD

**Issue by eziofer** [bitpay/copay#4782]
So I purchased a Giftcard with Copay

Tried to redeem it and amazon said it was locked, went to Copay, tried to Cancel it, just appeared a message above saying "you must provide a bitcoinaddress to refund this invoice"... And nothing happens, talked with amazon customer service and they told me that it have been refunded and I don't have my bitcoins back... ??????

**Comment by gabegattis** [comment]
please send an email to support@bitpay.com about this.
