### ISSUE TITLE
ошибка ввода

### ISSUE THREAD

**Issue by kydryawka** [bitpay/copay#4783]
Hello, please help. When you withdraw funds generated code is not indicated for the money and wallet ID, how to return the money in my wallet?

**Comment by matiu** [comment]
could you explain the issue on more detail?

**Comment by kydryawka** [comment]
When transferring money to your Bitcoin wallet, I pointed out the correct
ID is not to make money, or rather, I pointed out the ID of the purse.
Money is of course not been credited to my account, they probably already
stuck? I like that I can get the money into your account?

2016-10-14 15:06 GMT+03:00 Matias Alejo Garcia <notifications@github.com>:
