### ISSUE TITLE
Improving the view of Insight page

### ISSUE THREAD

**Issue by quinncomendant** [bitpay/copay#4785]
On iOS, the *See it on the blockchain* command opens an Insight page in a web view. I have a couple features to request:

- While viewing a transaction in this Insight view, if you click one of the language links at bottom it redirects to the Insight home page with the new language. It should display *the same page* in the language you choose.
- There should be a share option to copy link or send by email, etc.

**Comment by gabegattis** [comment]
Please open issues related only to insight itself at https://github.com/bitpay/insight-ui/issues

**Comment by quinncomendant** [comment]
Second point (share option for transaction info) is still an iOS issue. The Copay app would get that. 

I'll report the language switch issue to the insight project.
