### ISSUE TITLE
Build instructions out of date

### ISSUE THREAD

**Issue by OttoAllmendinger** [bitpay/copay#4790]
The commit https://github.com/bitpay/copay/commit/23f7f56f3f646b4ca6e60cc0fb2a673d5f1218d6 has changed the build process significantly, making the documentation out of sync in some places:

* https://github.com/bitpay/copay#android does not work: the `Makefile` in the root dir has moved to `cordova/`
* https://github.com/bitpay/copay/tree/master/cordova#build-the-project does not work: for instance, the target `android-run` does not exist

From what I could gather reading the Makefiles, the proper way to install the android apk is

```
cd cordvoa/
make project-android
cd project-android
make run
```

Is this correct? 

There is some code generation at `app-template/` that could use some documentation as well.

**Comment by gabrielbazan7** [comment]
Sorry about that. The proper way is:
npm i
grunt android-debug

**Comment by OttoAllmendinger** [comment]
Thanks, that helped!

It still requires to additional things

* `sudo npm i -g bower`
* `npm i grunt`
