### ISSUE TITLE
Windows 7 32bit

### ISSUE THREAD

**Issue by Dorf-On-Code** [bitpay/copay#4792]
Hello, 
is there anything I can do/download to make the windows version work on a 32 bit system?

Please respond to 
Postmybail@hotmail.com
if possible,
Thanks

**Comment by dabura667** [comment]
Use the Chrome app :-)

**Comment by JDonadio** [comment]
Please check this [Copay version](https://chrome.google.com/webstore/detail/copay/cnidaodnidkbaplmghlelgikaiejfhja?hl=en)

Thanks @dabura667 ;)

**Comment by matiu** [comment]
It is possible to make the 32 bit version from the source, but we dont distribute it.
