### ISSUE TITLE
Question regarding synchronization of transaction comments

### ISSUE THREAD

**Issue by RudyB** [bitpay/copay#4794]
how does copay sync transaction comments across multiple devices with the same wallet?

For example I create a wallet on my phone in copay and then I import the private key on my computer. How does copay know they are the same wallet and sync the comments?

**Comment by isocolsky** [comment]
Copay relies on [Bitcore Wallet Service](github.com/bitpay/bitcore-wallet-service) to keep wallets in sync across devices. The default Copay install points to the public BWS instance at BitPay's servers but you can run your own as it is all opens source.
