### ISSUE TITLE
use copay google chrome version, with trezor hardware wallet, but when export public key, loading forever

### ISSUE THREAD

**Issue by stone2y** [bitpay/copay#4799]
Hi, guy, I need help. 

I use copay google chrome version to add new wallet with trezor hardware wallet, 
but when I export public key, It shows loading all the time. Even though, I try to plug out and plug in again, when I export public key, it shows loading as well. 

I tried many times already. It's really frustrating!!
I need help.  

Thank you very much.

**Comment by JDonadio** [comment]
Sorry for the delayed reply. We actually move to a new design and functionality, please feel free to reopen this ticket if you are still running into that error.
