### ISSUE TITLE
Wallet Decred error to send/receive

### ISSUE THREAD

**Issue by rodrigofbi** [bitpay/copay#4802]
I can no longer send any value through the web wallet, when I put an address he only tells how invalid, and also can no longer receive it said it can no longer generate any more address. how I can fix this?

**Comment by JDonadio** [comment]
Sorry for the delayed reply. We have not a "web wallet" all of our platforms are available at www.bitpay.com/wallet and also the [chrome-extension](https://chrome.google.com/webstore/detail/copay/cnidaodnidkbaplmghlelgikaiejfhja?hl=es-419). 

We have a new design for Copay and BitPay app, feel free to reopen it if you are still running into that error.
