### ISSUE TITLE
invalid bitcoin address

### ISSUE THREAD

**Issue by apipke** [bitpay/copay#4805]
Hello my Copay app will not send my bitcoins to where I want. Every tim I put the code in my Copay app says it is invalid I have copied and pasted the code exactly tried a bunch of different times shut down the app restarted it, restarted my phone. Nothing works and I need it for work. Why won't it work?

**Comment by bitjson** [comment]
> Every tim I put the code in my Copay app says it is invalid

Could you clarify what code Copay is asking for? Are you trying to spend from a wallet with a "Spending Password"?

**Comment by apipke** [comment]
It is the bitcoin address when you go to send bitcoins. I took a pic but I can't add it on here. And there is no spending password

**Comment by bitjson** [comment]
It's unlikely this is a bug in Copay. Please confirm the bitcoin address is correct. You can also check the address' validity by pasting it in the search box here: https://insight.bitpay.com/

You can learn more about bitcoin addresses here: https://en.bitcoin.it/wiki/Address
