### ISSUE TITLE
invalid bitcoin address

### ISSUE THREAD

**Issue by apipke** [bitpay/copay#4807]
Hello, I have messaged you guys about my Copay app not working the bitcoin address keeps saying that it is in valid even though I have copied it exactly. It has been 3 days now. Everything you told me to do isn't working. So I am wonderingly if it is my phone so I have downloaded the Copay app on my computer. I have no idea how to log in with the current wallet I have tho on the app. How do I do this?

**Comment by isocolsky** [comment]
Hi! Could you please paste the address here so we can check? Thanks.

**Comment by bitjson** [comment]
Hey @apipke are you still having trouble with the bitcoin address generated by Copay being invalid? If so, could you copy and paste the bitcoin address here so we can review the issue?
