### ISSUE TITLE
welcome background should cleanly repeat-x

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#4816]
_From @bitjson on October 7, 2016 7:13_

@vanhue any chance we can get a version of the background on the welcome screen that cleanly repeats horizontally?

_Copied from original issue: bitpay/bitpay-wallet#291_

**Comment by JDonadio** [comment]
_From @vanhue on October 11, 2016 15:24_

See pull request #369

**Comment by bitjson** [comment]
fixed
