### ISSUE TITLE
implement email collection in onboarding

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#4818]
_From @bitjson on October 7, 2016 7:29_

Some serious work needs to be dedicated to making the email collection feel fast and clean, especially on iOS. 

I made a little progress in #253, but we still need feedback/animations provided to the user (eg. if the email address is invalid). I left it half-implemented.

We might want to cut our losses and try for a simpler design. Something like we did with the "pairing code" screen in [Bitcoin Checkout](https://itunes.apple.com/us/app/bitcoin-checkout/id929652207) would work well.

_Copied from original issue: bitpay/bitpay-wallet#297_

**Comment by JDonadio** [comment]
_From @bitjson on October 7, 2016 7:30_

At the very least, we need to have autofocus working reliably on every platform, and a clear call to action when the user has finished typing.

**Comment by JDonadio** [comment]
_From @matiu on October 10, 2016 19:11_

removed on the current master.

**Comment by JDonadio** [comment]
_From @bitjson on October 10, 2016 19:16_

Maybe an even better solution here is to only enable email collection on desktop platforms for launch? Mobile platforms have push notifications already, so users will probably like this better.

Also, on desktop, the email collection view is fantastic. Just needs a little more review.

**Comment by JDonadio** [comment]
_From @bitjson on October 11, 2016 14:59_

I think we at least need to have the email collection working on desktop for 1.0

**Comment by jameswalpole** [comment]
What needs to happen to progress on this in 2016, @JDonadio @bitjson?

**Comment by bitjson** [comment]
This is blocked by: https://github.com/bitpay/copay/issues/5016

**Comment by JDonadio** [comment]
Implemented in onboarding.
