### ISSUE TITLE
New Action Sheet Plugin

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#4819]
_From @jamal-jackson on October 7, 2016 13:57_

https://github.com/EddyVerbruggen/cordova-plugin-actionsheet

I need this plugin for a view I'm working on, and what we have currently isn't as flexible for non social sharing actions(https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin). 

After launch, I'd want to take some time to replace.

_Copied from original issue: bitpay/bitpay-wallet#308_

**Comment by bitjson** [comment]
(We have a better custom solution for this now.)
