### ISSUE TITLE
Make this modal nicer

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#4825]
_From @matiu on October 11, 2016 17:59_

![bitpay_-_secure_bitcoin_storage_and_bapp_ _-bash_ _100x49](https://cloud.githubusercontent.com/assets/98844/19282118/4c77cbd0-8fc3-11e6-81f7-8bed90872b94.png)

_Copied from original issue: bitpay/bitpay-wallet#374_

**Comment by JDonadio** [comment]
_From @bitjson on October 11, 2016 18:35_

Actually, is this type of modal used on anything but in-browser testing (`npm start`)? When we build the desktop apps, we'll want to use the native dialogs like we do on mobile.

**Comment by JDonadio** [comment]
_From @matiu on October 11, 2016 20:23_

this seems native... but I guess it should be more like other poppus, like:
https://cloud.githubusercontent.com/assets/98844/19242957/e472ff6e-8eeb-11e6-8d95-691ce68f0371.png

or it should have less text on it.

**Comment by bitjson** [comment]
Being done in #4890

**Comment by JDonadio** [comment]
I think we don't need a migration to do this.
