### ISSUE TITLE
Uncomment and polish pull-to-refresh on iOS

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#4828]
_From @bitjson on October 13, 2016 0:55_

It might just be a styling thing, but the view seems to snap back up too quickly, before the animation is finished.

Also, even if the app is already updated, the loading animation needs to take at least 200ms. That should give the user time to understand that it's working.

_Copied from original issue: bitpay/bitpay-wallet#427_

**Comment by JDonadio** [comment]
_From @gabrielbazan7 on October 13, 2016 18:13_

`$scope.$broadcast('scroll.refreshComplete'); ` seems that is not working on IOS. So, the spinner is out immediately. It's working great on Android.

**Comment by JDonadio** [comment]
_From @gabrielbazan7 on October 13, 2016 20:14_

Maybe we should add **Acceptable for 1.0** label

**Comment by JDonadio** [comment]
_From @bitjson on October 13, 2016 20:53_

If we can't get it working in a way that feels "right" on iOS, I would say we should just disable it there. If it's not there, I don't think it will be missed – if it is there, but feels "buggy", it will make the app look unstable.

**Comment by JDonadio** [comment]
_From @bitjson on October 13, 2016 20:53_

So I would say we either need to fix it or disable it.

**Comment by JDonadio** [comment]
_From @bitjson on October 14, 2016 15:35_

Choice above ^ was to disable – we can mark this card as acceptable for 1.0 when that PR gets merged.

**Comment by bitjson** [comment]
@msalcala11 is doing this here: https://github.com/bitpay/copay/pull/5007
