### ISSUE TITLE
Make Bitcoin Network Fee Policy more useful

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#4835]
_From @gabrielbazan7 on October 18, 2016 13:46_

<img width="409" alt="screenshot_20161018-104334_png" src="https://cloud.githubusercontent.com/assets/10999037/19480252/0f2eeaa8-9520-11e6-8ffc-2610c99af790.png">

_Copied from original issue: bitpay/bitpay-wallet#526_

**Comment by JDonadio** [comment]
_From @bitjson on October 18, 2016 21:32_

This came up in the #wallet Slack channel – this would be a lot more useful to users if they could have some context around what `633 bits/kb` actually means. I think it might be good to provide an estimated per-transaction range.

Looking here https://tradeblock.com/blog/analysis-of-bitcoin-transaction-size-trends:
median P2kH tx: ~250 bytes

Looking at my personal wallets, it looks like a good estimate for tx's from our multisig wallets is ~400 bytes. 

@ajp8164, @matiu, or anyone else – do we have a better way of estimating the average tx size from multisig Copay wallets?

When we get a solid estimate for both, I think it would be best to change this view to say eg:

> Average confirmation time:
> 20 minutes
> Estimated fee for this speed:
> 160 – 250 bits ($0.10 – $0.16 USD)

**Comment by Kirvx** [comment]
I'm in favor of this request.
A new bitcoin user can't have an idea of the cost of a transaction with a `198 satoshis/byte` indicator.

**Comment by dabura667** [comment]
The estimations will be extremely wide, though.

If I have 10 utxos on a 2 of 3 multisig, thats 297 bytes per input added, so a 1 input transaction would be 375 bytes, but a 10 input transaction is 3048 bytes. Around 8 times the fees.

"Fees will be $1.00 - $8.00" being written down will not do much to help a user understand anything imo.

**Comment by ajp8164** [comment]
The user is buying confirmation time with fee.  The number of tx inputs is simply a multiplier.  However, all fee estimation vs. time is an exercise in probability. There is no answer, just a range of possible outcome. IMO, the best way to present anything this complex is to use a graphical representation.  A probability cone or normal distribution could be used to render the relationship between fee and confirmation time using the number of tx inputs as a scalar.

**Comment by dabura667** [comment]
Mock up image.
![image](https://user-images.githubusercontent.com/6586275/28319000-9d25eb5e-6c07-11e7-9890-2d5587a9fff7.png)

**Comment by Kirvx** [comment]
That could be very informative for an advanced user, but seems very mathematical for a non tech-savvy user :confused:

**Comment by ajp8164** [comment]
I'll try to take a crack at it ;-)
