### ISSUE TITLE
Receive view feature request

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#4838]
_From @gabrielbazan7 on October 18, 2016 15:44_

When clicking on items like “next address” on receive view : mooth transaction like a fade or a flip or something than the flash-change we have now.

_Copied from original issue: bitpay/bitpay-wallet#532_

**Comment by JDonadio** [comment]
_From @bitjson on October 18, 2016 21:13_

This sounds like a job for @msalcala11 ✊

**Comment by bitjson** [comment]
completed by @jamal-jackson
