### ISSUE TITLE
Design: Simplify email notifications preferences

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#4844]
_From @bitjson on October 18, 2016 16:29_

Email notifications should be enabled by a toggle item. 

Above the "Email Address" field, there should be a toggle item labeled "Enable email notifications". It's either enabled or disabled. If it's enabled, the email address field is shown. Any changes then enable the save button to be clicked.

![slack_for_ios_upload_720-6](https://cloud.githubusercontent.com/assets/904007/19486889/30ea05ac-952e-11e6-9ee5-34037b6b813a.jpg)

_Copied from original issue: bitpay/bitpay-wallet#546_

**Comment by bitjson** [comment]
This is awesome: https://github.com/bitpay/copay/pull/4942 – I think we need to take it a little further to make it intuitive.

I really like simplifying all notifications into a global setting – right now it's pretty unintuitive that push notifications are global to the device, and email notifications need to be updated wallet-by-wallet.

It would really simplify the mental model for notifications if all "email notification" and "push notification" settings were part of global "Notification settings". If it's valuable at all (email filtering/labeling options are very powerful these days), I'd say the manual, per-wallet email address setup is just a kludgy way to get individualized hooks: https://github.com/bitpay/copay/issues/3458. I think we should remove it from wallet settings entirely, and move it all up to Notifications.

This also clears the way for us to provide much more individualized/powerful notification management options.

Slack, Github, Facebook for example:
<table><tr>
<td><img src="https://cloud.githubusercontent.com/assets/904007/19832003/8553fad8-9de6-11e6-8cba-033e7f918189.png" width="100" title="Slack Notification Settings"></td>
<td><img src="https://cloud.githubusercontent.com/assets/904007/19832004/877470b8-9de6-11e6-8fbb-212927da959b.png" width="100" title="Github Notification Settings"></td>
<td><img src="https://cloud.githubusercontent.com/assets/904007/19832017/e5b7c6ac-9de6-11e6-88dc-33a481388941.png" width="100" title="Facebook Notification Settings"></td>
</tr></table>
