### ISSUE TITLE
iOS – email entry should start with lower case letter

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#4845]
_From @bitjson on October 18, 2016 16:31_

From @ajp8164 – the email entry on contacts view starts with upper case first letter. Field should be all lowercase by default.

_Copied from original issue: bitpay/bitpay-wallet#548_

**Comment by gabegattis** [comment]
Email addresses are case sensitive. We should display it exactly as it is stored. Many mail servers ignore case, but the RFC specifies the inbox name as case sensitive.

**Comment by bitjson** [comment]
Huh, I never realized that. Looks like Gravatar requires [converting to lowercase for the hash](http://en.gravatar.com/site/implement/hash/), so we're still doing it right in the [gravatar directive](https://github.com/bitpay/copay/blob/master/src/js/directives/gravatar.js#L16) – though we should probably also insure whitespace is trimmed. (Even if we trim it before saving to storage.)

If possible, I still think the text field should default to beginning entry with a lowercase letter (on iOS, where it currently capitalizes the first letter if the user doesn't deactivate the shift key). But good to know – the solution to this issue should not force all characters to be lowercase.

**Comment by JDonadio** [comment]
Already done in current master branch
