### ISSUE TITLE
Bitcoin Network Fee Policy – no difference between Priority and Normal?

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#4847]
_From @bitjson on October 18, 2016 16:45_

Every time I've checked, the Priority and Normal fees amounts have been the same. Is that a bug?

![slack_for_ios_upload_1024-2](https://cloud.githubusercontent.com/assets/904007/19487404/a2875bea-9530-11e6-99a3-fdd3fc0bf4e2.jpg)

_Copied from original issue: bitpay/bitpay-wallet#553_

**Comment by bitjson** [comment]
Merging into https://github.com/bitpay/copay/issues/4835
