### ISSUE TITLE
Can't copy text out of log view to paste someplace else

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#4854]
_From @ajp8164 on October 18, 2016 23:47_

See title.

_Copied from original issue: bitpay/bitpay-wallet#571_

**Comment by JDonadio** [comment]
_From @bitjson on October 21, 2016 7:56_

@ajp8164 I guess this when trying to copy certain lines, rather than the whole log? (Testing, the primary copy button is working in master on all platforms.)

**Comment by JDonadio** [comment]
Related https://github.com/bitpay/copay/issues/4837

**Comment by ajp8164** [comment]
Correct, should be able copy just a portion of the log to the clipboard.  Button works fine.

--
Andy Phillipson
Director of Engineering Services, BitPay, Inc.
844A CCA5 F277 30C0 E86F  9799 0CEE 502F 2484 0854
