### ISSUE TITLE
Settings: heights are not consistent

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#4859]
_From @tonygallippi on October 19, 2016 15:55_

I don't see why the items under Preferences should be different heights than all the others.  

![screen shot 2016-10-19 at 11 36 21 am](https://cloud.githubusercontent.com/assets/7226673/19526572/cb4c3128-95f2-11e6-956b-5b7c24fc9edc.png)

_Copied from original issue: bitpay/bitpay-wallet#594_

**Comment by bitjson** [comment]
fixed
