### ISSUE TITLE
Remove empty Next Steps

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#4861]
_From @ajp8164 on October 19, 2016 23:46_

My Next Steps section is empty. Can't see bottom here since I can't scroll to bottom.  Should probably be removed if it is empty.

![img_4492](https://cloud.githubusercontent.com/assets/1063765/19541499/ba068e76-9634-11e6-898f-fff5375a1c69.PNG)

_Copied from original issue: bitpay/bitpay-wallet#603_

**Comment by cmgustavo** [comment]
Dup. #4879
