### ISSUE TITLE
Click receive tab from wallet view is confusing

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#4862]
_From @ajp8164 on October 19, 2016 23:59_

When I click on a wallet from Home and then click on Receive tab the address shown is that of the first wallet in my Home list.  It should be the receive address for the wallet I selected.  Otherwise I might receive to the wrong wallet.

_Copied from original issue: bitpay/bitpay-wallet#604_

**Comment by JDonadio** [comment]
@ajp8164 what about remove the tabs on the wallet details view?

**Comment by JDonadio** [comment]
<img width="411" alt="bitpay_-_secure_bitcoin_wallet" src="https://cloud.githubusercontent.com/assets/13851807/19780235/a126c39a-9c5a-11e6-86c4-4e8665e0dc55.png">

**Comment by ajp8164** [comment]
I think that hurts UX. @bitjson needs to look at how to get better utility out of the tabs based on context (in this case the context is a selected wallet).

Keep the tabs and when i select a wallet set a "selected wallet" and make the tabs do the following:

Home - Go back to home screen (same as tapping left arrow in wallet header).

Receive - Show receive view with selected wallet receive address chosen (qr is for selected wallet, scrolled item is selected wallet).

Scan - No change though the result of scan to pay should present the view defaulted to paying from the selected wallet.

Send - Flow should default to sending from the selected wallet.

Settings - Show selected wallet settings view (a child of the main settings view).

**Comment by gabrielbazan7** [comment]
I'm really against that @ajp8164, the tabs must be independent, otherwise cause even more confusion. I think that's the whole idea of the tabs and the difference between the old Copay. If there is some confusion @JDonadio idea is the best way to solve it.

**Comment by bitjson** [comment]
A few things – I think generally we can expect that users who "get" the interface enough to have multiple wallets will be able to understand the "tab paradigm". Nothing you do on one tab should effect the current navigational state of other tabs. (If I navigate somewhere in Settings, tap the home tab, and navigate into a wallet, tapping the Settings tab once should show me exactly what I was seeing before.)

On hiding tabs – the tabs are the "cornerstone" of the UI, they are the one familiar element in the app, and a big part of their function is to keep users feeling like they "know where they are". Whenever we hide the tabs, we break that context for the user.

The tabs should always be visible unless the user is in a "modal" view. [Apple's guidelines for modality](https://developer.apple.com/ios/human-interface-guidelines/interaction/modality/) are still the gold standard here IMO. The only time when it's acceptable to "steal the user's tabs from them" (and that's how we should think about it 😆 ) is when they absolutely must take an action or complete a flow. For us, I think that's onboarding, backup, and payment flows.

As for the core issue, I definitely agree this could be jarring (especially for users coming from the less-native experience of the old UI). I think the real issue may actually be with the Receive view – it may not be immediately clear (especially for new users) that the QR code displayed is associated with the wallet name at the bottom of the view. 

There are probably some design changes we should make to reduce the prominence of the address itself, and make the wallet card more prominent instead.

I think we can actually merge this into: https://github.com/bitpay/copay/issues/4891
