### ISSUE TITLE
Wrong label on sent transaction in history

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#4863]
_From @tonygallippi on October 20, 2016 17:22_

Copay has it right, BitPay is wrong.

![screen shot 2016-10-20 at 1 20 47 pm](https://cloud.githubusercontent.com/assets/7226673/19570456/1f879798-96c8-11e6-9197-1dcb2b546fb7.png)

_Copied from original issue: bitpay/bitpay-wallet#612_

**Comment by cmgustavo** [comment]
Closes https://github.com/bitpay/bitpay-wallet-to-be-deleted/pull/654
