### ISSUE TITLE
Scanner doesn't scan paper wallets

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#4866]
_From @bitjson on October 20, 2016 23:5_

I know this is a feature request, but with the scanner being so "intelligent" with other data types, it will probably feel like a bug...

Ok for after 1.0

_Copied from original issue: bitpay/bitpay-wallet#621_

**Comment by bitjson** [comment]
We should pick this up after #4916 is merged.

**Comment by bitjson** [comment]
@gabrielbazan7 – icon for this (based on the import icon):

`icon-import.svg` 
```
<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 24.4 23.9" style="enable-background:new 0 0 24.4 23.9;" xml:space="preserve">
<style type="text/css">
	.st0{fill:none;stroke:#000000;}
</style>
<path class="st0" d="M2.2,15.9v3c0,1.7,1.3,3,3,3h14c1.7,0,3-1.3,3-3v-3"/>
<path class="st0" d="M12.2,1.9v15"/>
<polyline class="st0" points="6.2,10.9 12.2,16.9 18.2,10.9 "/>
</svg>
```

**Comment by JDonadio** [comment]
Done in https://github.com/bitpay/copay/pull/5095
