### ISSUE TITLE
disappearing back button on amount view

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#4867]
_From @bitjson on October 21, 2016 7:46_

Reproduce:

1. Tap BitPay card, `Add Funds`, continue through amount screen, land on confirmation screen
2. Tap back, tap back
3. Tap Send tab, tap a contact, continue through amount screen, land on confirmation screen
4. Tab back, tap back
5. Repeat steps 1, 2, and 3.

Back arrow doesn't appear the second time step 3 is performed.
<img width="310" alt="screen shot 2016-10-21 at 3 36 14 am" src="https://cloud.githubusercontent.com/assets/904007/19590390/a1863836-973f-11e6-82a1-31e0af0f07ab.png">

_Copied from original issue: bitpay/bitpay-wallet#625_

**Comment by gabrielbazan7** [comment]
Fixes on https://github.com/driftyco/ionic-v1/pull/210
