### ISSUE TITLE
Design: onboarding TOU view

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#4869]
_From @ajp8164 on October 21, 2016 15:22_

Black background.  Small scrolling text view..

<img width="757" alt="screen shot 2016-10-21 at 11 21 04 am" src="https://cloud.githubusercontent.com/assets/1063765/19603829/8fa28a2a-9780-11e6-8802-2f3a51135931.png">

_Copied from original issue: bitpay/bitpay-wallet#637_

**Comment by JDonadio** [comment]
_From @bitjson on October 24, 2016 15:45_

The best solution here is to not use the modal view. In the mocks, the idea here was to slide the Terms of Use up from under the bottom white section, over the 2 other checkboxes. I think using the modal was a "quick fix", but we should get it working properly. On desktop, the scrollable Terms of Use text should fill the entire screen above the "I have read, understood, and agree with the Terms of Use" box at the bottom.

@vanhue could you post the mock animation?

**Comment by vanhue** [comment]
![tou-animation](https://cloud.githubusercontent.com/assets/4007284/19858685/c583ea32-9f58-11e6-9cfc-0bddabe1dde0.gif)

**Comment by vanhue** [comment]
![tou-animation](https://cloud.githubusercontent.com/assets/4007284/19861343/975a12b2-9f62-11e6-8c16-a3f448ad0e14.gif)

**Comment by vanhue** [comment]
Make sure to make margins for desktop on the TOU text. 
![image](https://cloud.githubusercontent.com/assets/4007284/19861393/c7bf4e72-9f62-11e6-9b6c-e9d601d17ca2.png)

**Comment by bitjson** [comment]
@jamal-jackson – mind taking a swing at this?

**Comment by bitjson** [comment]
The checkbox svgs also need to be polished (let me know when you're working on it, I clean them up).

**Comment by bitjson** [comment]
The outline of the checkbox svg is slightly off:

<img width="143" alt="screen shot 2016-11-14 at 1 55 31 am" src="https://cloud.githubusercontent.com/assets/904007/20255818/8f0ad6b8-aa0d-11e6-9a07-800cfaf53586.png">

**Comment by JDonadio** [comment]
Done.
