### ISSUE TITLE
Improve title of empty wallet send view?

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#4870]
_From @ajp8164 on October 21, 2016 15:29_

How about something like "You have no bitcoin" instead of "Start sending bitcoin"?  I think it's a bit more actionable; reaction should be "oh yeah, i need bitcoin!" ;-)

<img width="806" alt="screen shot 2016-10-21 at 11 26 57 am" src="https://cloud.githubusercontent.com/assets/1063765/19603982/53b694a6-9781-11e6-8e99-51f975ace519.png">

_Copied from original issue: bitpay/bitpay-wallet#638_

**Comment by matiu** [comment]
@bitjson what you think?
