### ISSUE TITLE
Paired devices should show my device name

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#4871]
_From @ajp8164 on October 21, 2016 15:48_

The SIN should not be shown.  We should grab the device name and app name and show something like "BitPay app on Andy's iPhone".

<img width="756" alt="screen shot 2016-10-21 at 11 45 58 am" src="https://cloud.githubusercontent.com/assets/1063765/19604598/fbdf001c-9783-11e6-9130-f34e4d391310.png">

_Copied from original issue: bitpay/bitpay-wallet#639_

**Comment by matiu** [comment]
This is a bitpay.com ticket, no Bitpay app, isn't it?

**Comment by ajp8164** [comment]
Really both.  The app needs to capture the device name "Andy's iPhone" and wallet t needs to be provided to the bitpay.com dashboard and displayed there.

--
Andy Phillipson
Director of Engineering Services, BitPay, Inc.
844A CCA5 F277 30C0 E86F  9799 0CEE 502F 2484 0854

**Comment by bitjson** [comment]
merging here: https://github.com/bitpay/copay/issues/4904
