### ISSUE TITLE
Send view logic: Transfer should only be visible of 2 testnet or 2 livenet wallets are available

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#4875]
_From @bitjson on October 23, 2016 15:42_

Feature request: if I only have one of each type of wallet, I don't need to see the "transfer" card, because it's still not possible for me to make any transfers.

![img_0200](https://cloud.githubusercontent.com/assets/904007/19627445/f51b3f4c-9914-11e6-9bbd-0813163365f5.PNG)

_Copied from original issue: bitpay/bitpay-wallet#652_

**Comment by JDonadio** [comment]
What if I just want to paste an address in the recipient input and I have only 1 wallet?

**Comment by JDonadio** [comment]
If I have 1 livenet wallet with funds, and 2 (or more) testnet wallets without funds, shoud I see the transfer card?

**Comment by JDonadio** [comment]
Same question for 1 testnet and 2 (or more) livenet wallets.

**Comment by bitjson** [comment]
I think you would only need to see the wallets for networks where you have more than one. That's probably a good solution for now at least.

(In the future we should rethink the design of this screen a bit though. Surely there's a more intuitive way of doing this.)

**Comment by JDonadio** [comment]
I almost forget it, if you have not funds the "Start with bitcoin" page is shown. You must have funds in a wallet in order to play with the transfer card. So, if I have funds in only one wallet, and have 2 or more with same network then show the card, else hide it. Make sense?

**Comment by bitjson** [comment]
Yep, :+1:

**Comment by gabrielbazan7** [comment]
This one is already done.
