### ISSUE TITLE
Glidera page has two settings gear - confusing

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#4876]
_From @ajp8164 on October 24, 2016 2:26_

Upper right gear should be an equalizer (like on bitpay card).

![img_4536](https://cloud.githubusercontent.com/assets/1063765/19631947/8aaa977e-996f-11e6-9c19-74cdde74de81.PNG)

_Copied from original issue: bitpay/bitpay-wallet#655_

**Comment by JDonadio** [comment]
Maybe we should hide the tab bar?

**Comment by ajp8164** [comment]
@bitjson?

--
Andy Phillipson
Director of Engineering Services, BitPay, Inc.
844A CCA5 F277 30C0 E86F  9799 0CEE 502F 2484 0854
