### ISSUE TITLE
Show the "unconfirmed balance" everywhere

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#4881]
_From @bitjson on October 25, 2016 3:44_

The Home tab and wallet views still display the "available balance" as the primary visible number. This should be the "unconfirmed balance".

This requires quite a bit of development work still (since Copay focuses on the "available balance"):
- implement the "Confirming" transaction items from the mocks (https://github.com/bitpay/bitpay-wallet/issues/539) – this will help to make it clearer why there are some funds which can't be spent
- Provide helpful error messages on the amount-entry view and the tx confirm view explaining when the "available balance" is lower than the required amount
- Consider enabling the "Use Unconfirmed Funds" by default, and instead of preventing it, issue a modal dialog when the user tries to spend uncofirmed funds (asking the to confirm they would like to send the transaction, even though it might be delayed)

A relevant conversation:
https://app.intercom.io/a/apps/2a3a0d58dd7819f5938cf908db897ecebb22df70/inbox/a/james@bitpay.com/conversations/6468816342

_Copied from original issue: bitpay/bitpay-wallet#668_

**Comment by bitjson** [comment]
This is working as it was originally designed, but I'm marking it as a bug, since it's unexpected and potentially scary.
