### ISSUE TITLE
Demo the onboarding flow without having to re-install the app

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#4882]
_From @bitjson on October 25, 2016 14:33_

We should consider ways of doing this. 

Especially as we focus more on developing new features, it's easy for onboarding flows to get neglected. Some way of re-initiating the full flow (from the very first screen in the app) could really help to keep onboarding "fresh" and well-tested with every future change. (In addition to some automated visual diff-ing I'm working on.)

_Copied from original issue: bitpay/bitpay-wallet#670_

**Comment by bitjson** [comment]
As of https://github.com/bitpay/copay/pull/5077, we have a `Developer Utilities` section in Advanced Settings – that would be the perfect place for this to be implemented initially.

We can add a `Demo Onboarding` item, with a `Start` button.

When the onboarding process creates a wallet, it should create a new wallet called `Onboarding Demo`, `Onboarding Demo 2`, etc. If the user doesn't back it up, they'll see the "needs backup" warnings for it (throughout the app) when they finish the demo. The user can manually delete the wallet if they don't want to keep it.

If the app is restarted, it should return to normal (this option shouldn't store any state that brings the user back to onboarding after a restart – in-memory demo only).

**Comment by JDonadio** [comment]
I think the onboarding is not useful after you finish it, because in the process you have options like allow push notifications and it's configurable from settings, create default wallet, accept disclaimer, etc. So why should the user get back to that process?

**Comment by JDonadio** [comment]
Also, we have not `Developer Utilities` section anymore.
