### ISSUE TITLE
"click to accept" should be fixed at the bottom of the view

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#4886]
_From @ajp8164 on October 25, 2016 18:27_

The accept button needs to be scrolled to - is this intended?  Seems like accept should be at top.

![screen shot 2016-10-25 at 2 24 44 pm](https://cloud.githubusercontent.com/assets/1063765/19698893/0a672fb8-9abf-11e6-9b1a-3b04346f8ee6.png)

_Copied from original issue: bitpay/bitpay-wallet#671_

**Comment by bitjson** [comment]
I think the issue here is that the element containing the `Click to accept` button (only appears on "no-touch" platforms) should be fixed at the bottom of the view (like the `slide to accept` component is on touch-enabled).

**Comment by ajp8164** [comment]
Yep, that's a better solution.  Should not have to scroll to accept.
