### ISSUE TITLE
Generate a QR code to receive a specific amount

### ISSUE THREAD

**Issue by bitjson** [bitpay/copay#4889]
It can be helpful to generate a QR code which requests a payment of a specific amount. This allows the person receiving the funds to do the typing, and makes it harder for the person paying to send an inexact amount.

This feature is in the current version of Copay, but has not been re-introduced in the new design.

**Comment by cmgustavo** [comment]
This feature is very useful for people that want to sell their services or anything. 
For example, 

* A taxi driver want to receive bitcoin quickly (without an intermediate). 
* A little kiosk. 
* Debt with a friend.

We know real use case of taxi drivers and little merchants (in Argentina) that use the specific amount to sell their product/services to clients.

**Comment by bitjson** [comment]
Definitely. I think we have some ideas for how to implement this into the receive view very cleanly. We'll get some mocks posted on this issue.

**Comment by bitjson** [comment]
The changes in #5020 will make this easier to do without sacrificing simplicity.
