### ISSUE TITLE
Design: Receive view can be confusing

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#4891]
Can we please make the address text larger?  I can barely read it.  All text this size is too small.

![img_4556](https://cloud.githubusercontent.com/assets/1063765/19709819/880a9e40-9af7-11e6-849d-169c9666ee34.PNG)

**Comment by bitjson** [comment]
The addresses primary purpose on this view is just to help the user understand what QR code they're looking at, so I'm not sure if we want to increase it's prominence at all (maybe increase the size and decrease the contrast).

I definitely agree that we should be using the standard font-size for the platform on this view. (Looking particularly at the wallet name and balance – definitely unnecessarily small.) I'll take this issue.

Related: https://github.com/bitpay/copay/issues/4836

**Comment by bitjson** [comment]
Issues here:

- Font sizes are generally too small – we should be using device-standard sizes
- On first-impression, It's not immediately obvious that I'm looking at my "Spending" wallet

The hierarchy of importance here is probably:
1. "this is a bitcoin address"
2. "this is the address for my 'Spending' wallet"
3. "other people can scan this"
4. "I can send it with the share button"

**Comment by bitjson** [comment]
merging into #5020
