### ISSUE TITLE
Start time is too long

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#4892]
We need to speed it up; present ui faster and do stuff in background could help.

**Comment by Kirvx** [comment]
The starting time is almost the same as Copay 2.6  https://github.com/bitpay/copay/issues/4654

**Comment by bitjson** [comment]
(Closing in favor of that issue)

**Comment by ajp8164** [comment]
Copay start time too long as well.  This is a general statement that we need to improve start time.  My experience is that 5 seconds is about the minimum but it has gone up to 10 secs.

--
Andy Phillipson
Director of Engineering Services, BitPay, Inc.
844A CCA5 F277 30C0 E86F  9799 0CEE 502F 2484 0854
