### ISSUE TITLE
Development needed before Chrome Apps are deprecated

### ISSUE THREAD

**Issue by bitjson** [bitpay/copay#4909]
Google is discontinuing support for Chrome Apps: https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html

> We will be removing support for packaged and hosted apps from Chrome on Windows, Mac, and Linux over the next two years. 

The Chrome App is the primary platform for the hardware wallet integrations – we/hardware wallet providers need to figure out how best to make those integrations available within the native desktop apps.

**Comment by ruimarinho** [comment]
@bitjson does this affect the nw.js-based Copay binaries as well?

**Comment by bitjson** [comment]
@ruimarinho no, this means Copay will **only** be available for desktop via the native desktop apps for each platform (currently nw.js).

**Comment by JDonadio** [comment]
Please check: https://blog.bitpay.com/copay-chrome-end/

We have no plans to support hardware wallets on desktop platforms for now. If we have news about that we'll reopen this.

**Comment by ruimarinho** [comment]
Got it. I will keep subscribed to this issue. Thanks!

**Comment by nathankaiser** [comment]
@bitjson Question for my understanding: does this mean that the Chrome App for ChromeOS will continue to exist? 

(in other words, does the deprecation "only" affect the Chrome App on Windows, etc.?)

Thanks!
