### ISSUE TITLE
Support request: Cant send my coins with the old Copay app [Win 7]

### ISSUE THREAD

**Issue by LittleBwoy** [bitpay/copay#4917]
# Support Request: Hi im a little confused with this hole github thing as i just had a little question:

I wannet to send my bitcoins from my win pc to my phone wallet as i klickt send copay (the old aplikation sad something like "coudl not send payment plase upgrade copay to perform this aktion") so nothing special (just a little fuckt up) i got on you webpage downloadet the latest version of copay (what now is bitpay) and here is the deal bitpay dose no recognise my copay bitcoin and copay dose not let me send dem away unless i do not update. What shall i do?

**Comment by JDonadio** [comment]
@LittleBwoy please try with [this](https://chrome.google.com/webstore/detail/copay/cnidaodnidkbaplmghlelgikaiejfhja?hl=es) version of Copay

**Comment by LittleBwoy** [comment]
@JDonadio is there any way to use this without Chrome? cuz my copay issnt a chrome version

**Comment by JDonadio** [comment]
@LittleBwoy can you give more information about _bitpay dose no recognise my copay bitcoin_ ?

**Comment by JDonadio** [comment]
Would be great if you add some screenshots

**Comment by LittleBwoy** [comment]
I meant after installing Bitpay. My wallet dose not apeare in Bitpay like in Copay.
As Bitpay (C:\Program Files (x86)\Bitpay) dose not use the same Folder as Copay (C:\Program Files (x86)\Copay) it make sense. 
my wallet also dose not apeare in the copay version for chome.

**Comment by bitjson** [comment]
The BitPay and Copay apps are entirely separate, and will not interfere with each other's data storage. To access your bitcoin, you can continue using the [latest release of Copay](https://github.com/bitpay/copay/releases/tag/v2.7.0).

**Comment by bitjson** [comment]
Closing this issue for now since it doesn't appear to be a bug, but please let me know if I need to reopen it. 🚀
