### ISSUE TITLE
32-bit Windows support

### ISSUE THREAD

**Issue by bitjson** [bitpay/copay#4918]
We're not currently building for 32-bit versions of Windows. Below is what Windows 7 32-bit users see:

![32-bit version for windows](https://cloud.githubusercontent.com/assets/904007/19747428/a47bcdb2-9ba9-11e6-892d-295e84f5214e.png)

Should we target 32-bit Windows?

**Comment by bitjson** [comment]
No

**Comment by maderero1** [comment]
existe una version para win 32 bits?
