### ISSUE TITLE
watch-only bitcoin addresses

### ISSUE THREAD

**Issue by axel2078** [bitpay/copay#4924]
Could you please add in watch-only accounts into the Copay app?  Right now,  I use Copay to buy/sell bitcoin and a different mobile wallet just to keep track of some watch-only accounts.  It would be nice to have this feature built in.  

Edit: This should have been titled Feature Request, not Support Request.

**Comment by bitjson** [comment]
Hey @axel2078 – this is actually possible already, in both the current version of Copay, and the recently released [BitPay distribution](https://github.com/bitpay/copay/releases/tag/bitpay).

You can import the full wallet into Copay, go to the wallet's settings, tap the "Advanced" or "More Options" item, and tap "Export Wallet". You can enable the "Do not include private key" option to export a watch-only copy of the wallet. Then delete the wallet, and import only the watch-only copy.

Here are the relevant screens:

### Latest Copay
![screen shot 2016-10-26 at 10 28 19 pm](https://cloud.githubusercontent.com/assets/904007/19752523/06c946a8-9bcc-11e6-8d8f-a6f5bfa23dc6.png)

### Latest BitPay
![screen shot 2016-10-26 at 10 28 00 pm](https://cloud.githubusercontent.com/assets/904007/19752521/039e8fce-9bcc-11e6-9b1f-202c9bfcb68d.png)

**Comment by axel2078** [comment]
I'm not quite sure I understand. This is the process to add a watch only address into Copay, such as a paper wallet?

**Comment by bitjson** [comment]
Ah – I misunderstood. I thought you were interested in a full watch-only wallet. We currently don't have a way to watch just a single bitcoin address. Updating the issue.

**Comment by axel2078** [comment]
Ok.  At least now I know.  Thank you for the clarification.

On Thu, Oct 27, 2016 at 11:07 AM, Jason Dreyzehner <notifications@github.com

**Comment by cmgustavo** [comment]
It 's possible creating a "Single address" wallet and export it to as @bitjson mentioned before (without include private key).

![screen shot 2018-06-25 at 15 13 33](https://user-images.githubusercontent.com/237435/41867823-93957984-788a-11e8-9ec3-fe21ee93b378.png)
