### ISSUE TITLE
Transaction pending for a WHILE

### ISSUE THREAD

**Issue by shep222** [bitpay/copay#4926]
I had some money transfer to my CoPay accountover 11 hours ago.  It still shows as pending, waiting confirmation.  I have never had one take this long.  Can you tell me whats going on with this please.
Thanks
John Shepler

**Comment by matiu** [comment]
Please see https://github.com/bitpay/copay/issues/4920#issuecomment-256512276

That problem is related to the bitcoin network itself/fees.
