### ISSUE TITLE
Use a native hook to avoid "testing" cameras on desktop

### ISSUE THREAD

**Issue by bitjson** [bitpay/copay#4935]
This will have to wait until after https://github.com/bitpay/copay/issues/4890.

From [this reddit thread](https://www.reddit.com/r/Copay/comments/59q0uz/this_is_somewhat_disturbingi_downloaded/): 

> ### This is somewhat disturbing...I downloaded Copay/Bitpay wallet for mac
> 
> ...and when I start it up the camera light flashes 3 times. Why is your wallet taking pictures of me????

[My response](https://www.reddit.com/r/Copay/comments/59q0uz/this_is_somewhat_disturbingi_downloaded/):

> I'm probably in the best position to answer this since I wrote [the code that does it](https://github.com/bitpay/cordova-plugin-qrscanner/blob/master/src/browser/src/createQRScannerInternal.js#L27)!
> 
> The code is part of the new [BitPay-developed QR scanning library](https://github.com/bitpay/cordova-plugin-qrscanner/).
> 
> Browsers try to protect users' privacy by refusing to "tell" applications anything about the cameras available to your computer. (I would argue this is just privacy-theater – as I have shown by my workaround – but that's another discussion.)
> 
> Basically, applications must "ask" for a camera of "at least width X and height X", and the browser will either provide access to a camera, or respond "no matching camera available".
> To work around this, I wrote a short "startup" process which quickly "tests" all the cameras connected to your computer, and remembers the best two. When you go to scan a QR code, we can instantly choose the best one. If you "rotate" the camera, we switch to the second-best camera.
> 
> It's silly, but necessary for a fast user experience.
> 
> In the future, I'm hoping we can instead tie into native functionality on each platform, and completely avoid the blinking privacy lights.
> 
> Thank you for the feedback! It's valuable to know that you 1) noticed and 2) were concerned. I've just [opened an issue](https://github.com/bitpay/copay/issues/4935) in the Copay GitHub project to get it on the list for future development.

The change would require changes in both Copay and [cordova-plugin-qrscanner](https://github.com/bitpay/cordova-plugin-qrscanner).

**Comment by huangbong** [comment]
I agree that this is a huge issue. The first thing I noticed when I open the app on my Mac was the 3 green flashes from the webcam light and I'm like wtf is going on. It feels like it's taking 3 snapshots of your face like you're passing under a toll booth in your car...

I wish the architecture for this project was React/React-Native rather than the Cordova/Angular/Ionic/Electrum mess that it's in right now otherwise I'd definitely be contributing.

Good luck on the move to Electrum on desktop @bitjson

**Comment by dabura667** [comment]
Move to Electrum?

The whole repo is being rewritten as a python app? lol I'm confused.

**Comment by huangbong** [comment]
@dabura667 sorry, meant Electron*

**Comment by seebq** [comment]
I know this is a closed issue, but man oh man, this scared me badly and I had to go searching and found this, and sighed a huge relief.  I had thought in the process of connecting coinbase I had done something to trigger the camera.   Phew.  This just happened last night on latest build that you can download.  I have not tried from master.

**Comment by bitjson** [comment]
Thanks for coming to the issues here first!

Yep, the next release will include the changes that do away with that functionality. We'll find a better way to prep the camera in the future.

**Comment by bitjson** [comment]
Just want to clarify – this was corrected in: https://github.com/bitpay/copay/pull/5440

New versions of the app should no longer be doing this "testing", instead we opted to have the camera start a little bit slower on desktop.

**Comment by seebq** [comment]
👍
