### ISSUE TITLE
Android: performance – scanner remaining active for too long?

### ISSUE THREAD

**Issue by Kirvx** [bitpay/copay#4946]
I can hear the auto focus of the camera on my Sony Z3 Compact (Android 6.0.1) in others tabs than the Scan tab :smile:

The problem is that my phone heats as if I was playing a game ~~, and it causes a significant decrease of performance in the app.~~

So it looks like a big app for my phone, requires a lot of resource :zap:

**Comment by bitjson** [comment]
Hey @Kirvx – thanks for the report! It's very possible the camera is staying activated longer than it should be.

With the new scanner, we've somewhat disconnected the UI the scanner itself to improve performance. The scanner first turns on when you open the scan view, but it remains functional (with scanning disabled) [for 10 seconds](https://github.com/bitpay/copay/blob/master/src/js/services/scannerService.js#L133) after leaving the view. This makes it extremely quick to reactivate if you switch back to the scan tab.

After that 10 seconds though, scanning should stop, and resource consumption should fall to nearly zero. (After a little longer, the scanner is also "destroyed" completely, and no longer consumes any resources.)

If the scanner is still clearly active on your device, it might be a bug with the native Android implementation. I'll test on some other Android devices and see if I can figure out the issue.

**Comment by Kirvx** [comment]
Thanks :)

Actually the scanner starts in background with the launch of the app, I don't have to run the scanner on the Scan tab an go back to notice the problem.

**Comment by bitjson** [comment]
Good to know. I should have also mentioned that we attempt to [pre-initialize the scanner right after the app starts](https://github.com/bitpay/copay/blob/master/src/js/services/scannerService.js#L83) to improve the initial load time a little more.

So that would also point to an issue with [the android implementation](https://github.com/bitpay/cordova-plugin-qrscanner/tree/master/src/android) of cordova-plugin-qrscanner.

**Comment by Kirvx** [comment]
Just to inform that the camera doesn't cause the "significant decrease of performance in the app" I described, it's the same when the camera is disabled (it still cause heat release).

I hope Ionic 2 makes the app faster :)

**Comment by Kirvx** [comment]
### How the camera working in the background cause problem for the battery life : 

> ### BitPay 1.2.1 consumes 47.8% more energy than "reddit is fun" for a duration of use lower by 81.50%.

![26](https://cloud.githubusercontent.com/assets/6627786/21750334/266a7bde-d5b1-11e6-84da-158ac2090b2c.jpg)

Note that the camera was not used to send payments, the app was used to view transactions, settings, create new wallets, and receive transactions.

BitPay consumed 4% of my battery life for these 409 secondes.

**Comment by JDonadio** [comment]
@Kirvx please can you try with this improvement?

**Comment by Kirvx** [comment]
Same problem with the beta version 1.3.2 on Google Play:
The camera is activated all the time the app is displayed (I can hear the autofocus) since the launch of the app.

**Comment by JDonadio** [comment]
We'll keep on this. Thanks!

**Comment by Kirvx** [comment]
Same problem with Honor 5C - Beta 1.3.2 - Android 6

**Comment by Kirvx** [comment]
Fixed in V4
