### ISSUE TITLE
Simplify Wallet Details view

### ISSUE THREAD

**Issue by bitjson** [bitpay/copay#4952]
# Current Mocks

<table><tr>
<td><img src="https://cloud.githubusercontent.com/assets/904007/19831844/893afa42-9de2-11e6-909d-ab5e54f5ea30.png" width="200"></td>
<td><img src="https://cloud.githubusercontent.com/assets/904007/19831847/8e08a2ea-9de2-11e6-8a9d-f080d99a3a5c.png" width="200"></td>
<td><img src="https://cloud.githubusercontent.com/assets/904007/19831848/90dca9b2-9de2-11e6-953e-d4b57680b613.png" width="200"></td>
</tr></table>

**Comment by bitjson** [comment]
To consider further – The description for incoming/outgoing payments should describe "from/to where". For paid payment requests, let's use the same iconography as transactions in the debit card (I'm writing a BIP 70 extension).

**Comment by bitjson** [comment]
For now, we can leave out the BIP 70 extension / merchant category stuff. We should get the rest of the design changes implemented and polished.

For the incoming/outgoing payments descriptions, lets use the name from the Address Book (if available, otherwise the truncated bitcoin address). The icon for those should use the associated gravatar. If the address book entry doesn't have an email (to fetch a gravatar) – we should fetch a [gravatar "identicon"](https://en.gravatar.com/site/implement/images/) based on the hashed bitcoin address. (also needs to be updated in the address book views)

**Comment by vanhue** [comment]
Extra points if you could implement this header animation
![wallet-header-transition](https://cloud.githubusercontent.com/assets/4007284/19897855/2b4c41e8-a030-11e6-89a7-0bcd9cfbddbf.gif)

**Comment by matiu** [comment]
@jamal-jackson nice!!! That would be awesome!

**Comment by jamal-jackson** [comment]
@matiu I think you meant @vanhue there

**Comment by matiu** [comment]
@jamal-jackson updated! :) thanks.

**Comment by bitjson** [comment]
Related: https://github.com/bitpay/copay/issues/5068

**Comment by bitjson** [comment]
Finished here: https://github.com/bitpay/copay/pull/5007
