### ISSUE TITLE
Desktop: after scan a QR code, the camera remain active

### ISSUE THREAD

**Issue by cmgustavo** [bitpay/copay#4967]
Note: I have to close the app

**Comment by bitjson** [comment]
@cmgustavo could you provide a little more detail on this? Do you mean the privacy light on your laptop stays active? Or the video preview is still active? (Is this still an issue with the new scanner work?)

**Comment by cmgustavo** [comment]
The light on the laptop stays active (for long time, I had to close the app)

Note: I tested it with a simple bitcoin address (bitcoin:1xxx...xxx)

**Comment by bitjson** [comment]
Right now it should stay "enabled" for [10 seconds](https://github.com/bitpay/copay/blob/master/src/js/services/scannerService.js#L133) after visiting the scan tab. Though if you scan something successfully, it should go off immediately.

Looks like there are some strange edge cases where scanning won't be properly deactivated after scanning. Definitely needs to be reviewed 👍

**Comment by gabegattis** [comment]
can confirm on linux
