### ISSUE TITLE
Import wallet (twice) from QR

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#4973]
After import a wallet from QR if immediately try to import a second wallet the text area remains empty, no warnings, no error, no message.

<img width="364" alt="bitpay_-_secure_bitcoin_wallet" src="https://cloud.githubusercontent.com/assets/13851807/19967372/b3f4ec32-a1ae-11e6-9d43-165725d13dbc.png">

>11-03 10:39:44.356: I/chromium(9112): [INFO:CONSOLE(107)] "Scan view state set to: visible", source: file:///android_asset/www/js/copay.js (107)
11-03 10:39:44.356: I/chromium(9112): [INFO:CONSOLE(107)] "Scanning...", source: file:///android_asset/www/js/copay.js (107)
11-03 10:39:44.376: I/chromium(9112): [INFO:CONSOLE(107)] "Scan view state set to: visible", source: file:///android_asset/www/js/copay.js (107)
11-03 10:39:44.376: I/chromium(9112): [INFO:CONSOLE(107)] "Scanning...", source: file:///android_asset/www/js/copay.js (107)
11-03 10:39:50.116: I/chromium(9112): [INFO:CONSOLE(107)] "Route change from: scanner  to: tabs.add.import", source: file:///android_asset/www/js/copay.js (107)
11-03 10:39:50.126: I/chromium(9112): [INFO:CONSOLE(107)] "            toParams:{}", source: file:///android_asset/www/js/copay.js (107)
11-03 10:39:50.126: I/chromium(9112): [INFO:CONSOLE(107)] "            fromParams:{"passthroughMode":1}", source: file:///android_asset/www/js/copay.js (107)
11-03 10:39:50.146: I/chromium(9112): [INFO:CONSOLE(107)] "Deactivating scanner...", source: file:///android_asset/www/js/copay.js (107)
11-03 10:40:00.156: I/chromium(9112): [INFO:CONSOLE(107)] "Scanner not in use for 10 seconds, hiding...", source: file:///android_asset/www/js/copay.js (107)

**Comment by gabrielbazan7** [comment]
I think this happens when you use the scan tab and then try to use the import or addressbook scanner.

**Comment by JDonadio** [comment]
Actually happens if you try directly from import phrase tab

**Comment by gabrielbazan7** [comment]
Also happens with Join scanner, Import phrase scanner and addressbook scanner. But, the scanner works well. Way to reproduce it : 

- Scan
- Go back to the previous page
- Go forward and try to scan again
