### ISSUE TITLE
Copay doesn't understand that Ledger app is installed

### ISSUE THREAD

**Issue by dskloet** [bitpay/copay#4986]
I tried so many times to import a wallet from my Ledger Nano S. Every time it opens the Ledger app but at the same time gives an error saying that the "Ledger Chrome application is not installed". In the end I realized that it only works if I open the Ledger app before clicking Import in Copay.

**Comment by JDonadio** [comment]
Yes unlike trezor extension, ledger extension needs to be initialized first.

**Comment by dskloet** [comment]
If you confirm what I said, why did you close the issue?
The message is clearly wrong.

**Comment by dskloet** [comment]
Hello?
