### ISSUE TITLE
Using Ledger to replace an existing Copayer

### ISSUE THREAD

**Issue by dskloet** [bitpay/copay#4987]
I have an existing 2 of 4 multisig wallet. I just got a new Ledger Nano S and I want to use it for one of the Copaying parties. So I enter the wallet seed of that party into my Ledger and try to import the Ledger wallet. But it seems that Copay tries to get the 48' path instead of the 44' path so it doesn't see the same wallet. How can I use my Ledger in my existing 2 of 4 wallet?

**Comment by dskloet** [comment]
I guess the reverse is even worse. If I create a new wallet with Ledger, and then I lose my Ledger, will I not be able to get to my money with just the word seed because it would try HD path 44' instead of 48'?

**Comment by dskloet** [comment]
I asked Ledger and they said it's Copay choosing the 48' path, not them. Could this be changed/optional please?

**Comment by dabura667** [comment]
Create a new multi-sig wallet with your Ledger as one of the copayers.

You also realize that what you are trying to do makes no sense, and ignores the point of why one should use a device like Ledger in the first place.

1. Create a new seed on the Ledger.
2. Create a new multi-sig on Copay using Ledger as one of the copayers.
3. Now it actually makes sense.

Copay uses 48 to prevent people from doing the security mistake that you are trying to do.

**Comment by dskloet** [comment]
I can create a new multi-sig wallet with Ledger, but if I lose my Ledger, I want to be able to use the written down seed and access my money, without first having to get a new Ledger.

> You also realize that what you are trying to do makes no sense

There's no need to be an asshole. If it doesn't make sense, please explain how I can use the written down backup seed to get to my money, in case I lose my Ledger.

And if a hardware wallet needs a different derivation path for security, why does Ledger normally (without multi-sig) use the standard m/44' path compatible with Mycelium etc.

**Comment by dabura667** [comment]
> I want to be able to use the written down seed and access my money, without first having to get a new Ledger.

You could get a Trezor or a ledger or any hardware wallet supported.

When you use a HW with Copay, you are telling copay "I don't want the private key to ever touch Copay, so I will register the HW with Copay in lieu of the seed."

Imagine if you lost your seed. There would be no way we can help you.

Now imagine you lost your ledger. There are two ways you can be helped: 1. buy a new (cheap) ledger HW.1 or any other Ledger / Trezor HW. or 2. hire someone to make you insecure software that will handle the seed (that you told Copay was never to touch a computer, ever).

So losing your ledger is MUCH better than losing your seed.

But to be honest tl;dr don't lose your ledger, and if you do, buy a new one. And if you need your money immediately after losing your ledger for some reason, then don't use HW with multisig.

I am not being condescending. I'm just not telling you what you want to hear so it sounds like I am condescending.

**Comment by dskloet** [comment]
This is condescending:

> You also realize that what you are trying to do makes no sense

Nobody asks for a feature that they already believes makes no sense.
