### ISSUE TITLE
how to move copay data directory?? 

### ISSUE THREAD

**Issue by themovement919** [bitpay/copay#4988]
i want to be able to store all of copay's files in truecrypt so that it can only be accessible through truecrypt when truecrypt is opened.

How do i do this?

**Comment by bitjson** [comment]
Hi @themovement919 – if you'd like to dig into the issue, take a look at the [NW.js project](https://nwjs.io/). The desktop versions of Copay use NW.js, so that would be the place to dig for info on where data is stored.

**Comment by bitjson** [comment]
Reviewing NW.js should help you get something working immediately if you'd like. Otherwise, this will hopefully be a lot simpler with the migration to Electron.

Merging this issue into that: https://github.com/bitpay/copay/issues/4890

**Comment by themovement919** [comment]
That is a little difficult for me to do. Is it possible to move Copay to an external drive so that it is not stored on my hard drive and can only be launched from the external drive?
