### ISSUE TITLE
missing script: start:desktop

### ISSUE THREAD

**Issue by frz-dev** [bitpay/copay#4992]
Hello,

I'm trying to run the Copay desktop app but when i type
`npm run start:desktop`
I get this error:
`missing script: start:desktop`

I previously installed NW globally, and run `npm run apply:copay`.

Any idea of what could be the problem?

I'm working on a Fedora 24 64-bit machine.

**Comment by bitjson** [comment]
Hey @frz-dev – it sounds like the `apply` task either didn't run or didn't complete. If you're still unsure about the issue, could you copy/paste the contents of `package.json` here?

root cause is this somewhat-messy system: https://github.com/bitpay/copay/issues/4921

**Comment by frz-dev** [comment]
@bitjson
This is the content of the package.json file:
`
 { 
  "//":"Changes to this file will be overwritten",
  "//":"        Modify it in the app-template directory", 

  "name": "copay",
  "description": "A Secure Bitcoin Wallet",
  "author": "BitPay",
  "version": "2.5.0",
  "keywords": [
    "bitcoin",
    "wallet",
    "bitpay",
    "copay",
    "multisignature",
    "bitcore"
  ],
  "main": "www/index.html",
  "title": "Copay",
  "window": {
    "title": "Copay - Copay Bitcoin Wallet",
    "icon": "www/img/icons/logo.ico",
    "toolbar": false,
    "show": true,
    "visible": true,
    "resizable": true,
    "frame": true,
    "width": 400,
    "height": 650,
    "min_width": 400,
    "max_width": 800,
    "min_height": 650,
    "position": "center",
    "fullscreen": false
  },
  "webkit": {
    "page-cache": false,
    "java": false,
    "plugin": false
  },
  "dom_storage_quota": 200,
  "id": "jid1-x7bV5evAaI1P9Q",
  "homepage": "https://copay.io",
  "license": "MIT",
  "repository": {
    "url": "git://github.com/bitpay/copay.git",
    "type": "git"
  },
  "bugs": {
    "url": "https://github.com/bitpay/copay/issues"
  },
  "engines": {
   "node": "6",
   "npm": "3"
  },
  "dependencies": {
    "adm-zip": "^0.4.7",
    "angular": "1.4.6",
    "angular-mocks": "1.4.10",
    "bezier-easing": "^2.0.3",
    "bhttp": "^1.2.1",
    "bitauth": "^0.3.2",
    "bitcore-wallet-client": "4.3.2",
    "bower": "^1.7.9",
    "chai": "^3.5.0",
    "cordova-android": "5.1.1",
    "cordova-custom-config": "^3.0.5",
    "cordova-plugin-qrscanner": "^2.3.1",
    "coveralls": "^2.11.9",
    "express": "^4.11.2",
    "fs": "0.0.2",
    "fs-extra": "^0.30.0",
    "grunt-angular-gettext": "^2.2.3",
    "grunt-browserify": "^5.0.0",
    "grunt-cli": "^1.2.0",
    "grunt-contrib-compress": "^1.3.0",
    "grunt-contrib-concat": "^1.0.1",
    "grunt-contrib-copy": "^1.0.0",
    "grunt-contrib-uglify": "^2.0.0",
    "grunt-contrib-watch": "^1.0.0",
    "grunt-exec": "^1.0.0",
    "grunt-nw-builder": "^2.0.3",
    "grunt-sass": "^1.2.0",
    "load-grunt-tasks": "^3.5.0",
    "mocha": "^2.4.5",
    "phantomjs-prebuilt": "^2.1.7",
    "shelljs": "^0.3.0"
  },
  "scripts": {
    "postinstall":            "bower install",
    "start":                  "npm run build:www && ionic serve --nolivereload --nogulp -s",
    "start:ios":              "npm run build:www && npm run build:ios && npm run open:ios",
    "start:android":          "npm run build:www && npm run build:android && npm run run:android",
    "watch":                  "grunt watch",
    "build:www":              "grunt",
    "build:www-release":      "grunt prod",
    "build:ios":              "cordova prepare ios && cordova build ios --debug",
    "build:android":          "cordova prepare android && cordova build android --debug",
    "build:ios-release":      "cordova prepare ios && cordova build ios --release",
    "build:android-release":  "cordova prepare android && cordova build android --release",
    "build:desktop":          "grunt desktop",
    "build:macos":            "grunt macos",
    "open:ios":               "open platforms/ios/*.xcodeproj",
    "open:android":           "open -a open -a /Applications/Android\\ Studio.app platforms/android",
    "final:www":              "npm run build:www-release",
    "final:ios":              "npm run final:www && npm run build:ios-release && npm run open:ios",
    "final:android":          "npm run final:www && npm run build:android-release && npm run run:android",
    "final:desktop":          "npm run build:desktop && npm run build:macos",
    "run:android":            "cordova run android --device",
    "log:android":            "adb logcat | grep chromium",
    "sign:android":           "rm -f platforms/android/build/outputs/apk/android-release-signed-aligned.apk; jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ../copay.keystore -signedjar platforms/android/build/outputs/apk/android-release-signed.apk  platforms/android/build/outputs/apk/android-release-unsigned.apk copay_play && ../android-sdk-macosx/build-tools/21.1.1/zipalign -v 4 platforms/android/build/outputs/apk/android-release-signed.apk platforms/android/build/outputs/apk/android-release-signed-aligned.apk",
    "apply:copay":            "npm i && cd app-template && node apply.js copay && cordova prepare",
    "apply:bitpay":           "npm i && cd app-template && node apply.js bitpay && cordova prepare",
    "test":                   "echo \"no package tests configured\"",
    "clean":                  "trash platforms && trash plugins && cordova prepare",
    "unstage-package":        "git reset package.json",
    "clean-all":              "git clean -dfx"
  },
  "devDependencies": {
    "cordova": "^6.3.1",
    "grunt": "^1.0.1",
    "ionic": "^2.1.0",
    "trash-cli": "^1.4.0",
    "lodash": "^4.3.0",
    "pre-commit": "^1.1.3"
  },
  "pre-commit": "unstage-package"
}
`
And here's the output of the `apply` script: [paste.fedoraproject.org/475935/14786417](http://paste.fedoraproject.org/475935/14786417/)

Thank for helping

**Comment by bitjson** [comment]
Hey @frz-dev – sorry, I just realized the issue. Documentation is a little outdated there.

There's actually not currently a "best" way of doing development inside the NW.js build – the choices are `npm start` (for simply developing in a browser) or `npm build:desktop` to test the final app. For day-to-day development, `npm start` is what you'll want. Since we do want to eventually get a `start:desktop` working cleanly, I'm just aliasing it to `npm start` for now in https://github.com/bitpay/copay/pull/4995.

Thanks for reporting!

**Comment by frz-dev** [comment]
OK
Thanks to you!
