### ISSUE TITLE
Provide the ability to disable push notification support at build time

### ISSUE THREAD

**Issue by UnderSampled** [bitpay/copay#4993]
Modern push notifications use non-open servers and non-open libraries (especially Google Cloud Messaging, which is not available without a closed-source build of android). For the same reasons someone may choose to disable push notifications in-app, there should be a way to build without these closed-source libraries.

**Comment by JDonadio** [comment]
We just moved to FCM which is basically the new version of GCM. It's more scalable and have more features. This new mode use `cordova-plugin-fcm` and you can disable it directly from `/app-tepmplate/config-template.xml`
