### ISSUE TITLE
Deprecate wp8, use the new Windows cordova platform

### ISSUE THREAD

**Issue by bitjson** [bitpay/copay#4999]
The old `wp8` platform has been deprecated by Cordova for a while, it's definitely time to upgrade to the new `windows` platform. 

@nacardin has made a ton of progress on the [scanner](https://github.com/bitpay/cordova-plugin-qrscanner/pull/40) part, but we need to finish the implementation here and polish it up for the external beta.

**Comment by bitjson** [comment]
Related:
- https://github.com/bitpay/copay/issues/4705
- https://github.com/bitpay/copay/issues/2892

**Comment by JDonadio** [comment]
Done
