### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by nicoalef** [bitpay/copay#5006]
Hi

I have a wallet copay in my phone but i lost wallet spending password and 12 words

How i can send bitcoins to other wallet without password and words 

Thanks

Nicolas

**Comment by JDonadio** [comment]
Unfortunately is not possible without a backup (12 words, exported file/text or exported QR code). Spending password is not necessary to recover your wallet.

**Comment by richardsuns** [comment]
@nicoalef 
if you didn't remember your password, I might crack it for you (if you still have the backup file)
