### ISSUE TITLE
Copay Wallet "Cache" Files On Disk?

### ISSUE THREAD

**Issue by KeyJockey** [bitpay/copay#5010]
Sorry if this is covered elsewhere but I looked around and didn't find any documentation on it anywhere... just wondering what the CACHE files saved on disk are really FOR, in Copay, and if they can be deleted to clean house a bit?

![copaycache](https://cloud.githubusercontent.com/assets/13903392/20225634/682781ce-a812-11e6-8346-fc6a362a2199.png)

That's screenshot from Mac OS X version, but info for other platforms would be good to know too.

Is there any significant reason to keep these files hanging around permanently, any big down-side to deleting them?

**Comment by JDonadio** [comment]
If you delete that folders probably your wallets probably will disappear. Be careful.

> Is there any significant reason to keep these files hanging around permanently

No, that's just the way to OS X manage the file system for their apps. For desktop platforms we strongly recommend encrypt the private key using the spending password option

**Comment by JDonadio** [comment]
Related https://github.com/bitpay/copay/issues/6541
