### ISSUE TITLE
Send view: "Frequently Used" Card

### ISSUE THREAD

**Issue by bitjson** [bitpay/copay#5012]
Not urgent – we should first implement as an experimental feature.

Mocks:
<table><tr>
<td>
<img src="https://cloud.githubusercontent.com/assets/904007/20226359/ce03eafc-a815-11e6-8bec-73fc2d063211.png" width="200">
</td>
<td>
<img src="https://cloud.githubusercontent.com/assets/904007/20226365/cff1c334-a815-11e6-91f4-e0403c4125a0.png" width="200">
</td>
</tr>
</table>

**Comment by matiu** [comment]
done.
