### ISSUE TITLE
Upgrade to Angular 2 & Ionic 2

### ISSUE THREAD

**Issue by bitjson** [bitpay/copay#5016]
Angular 2 [has been released](http://angularjs.blogspot.com/2016/09/angular2-final.html), and Ionic 2 is already in [release candidates](http://blog.ionic.io/announcing-the-ionic-2-release-candidate/). 

Angular 2 and Ionic 2 will give us access to some fantastic new tooling, features, and performance improvements. This will be a very big project, but it can (and should) be done very incrementally. 

[Angular 1 to 2 Migration Guide](https://angular.io/docs/ts/latest/guide/upgrade.html)
[Ionic 2 Migration Docs](https://ionicframework.com/docs/v2/getting-started/migration/)

- [ ] Use [ControllerAs Syntax](https://ionicframework.com/docs/v2/getting-started/migration/#controlleras-syntax) for all controllers
- [ ] Migrate to [component-based project structure](https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#folders-by-feature-structure)
- [ ] Enable Typescript usage
- [ ] Begin using the [Angular 2 Upgrade Adapter](https://angular.io/docs/ts/latest/guide/upgrade.html#!#upgrading-with-the-upgrade-adapter)
- [ ] Complete migration of all Copay components and services to Typescript and Angular 2
- [ ] Upgrade from Ionic 1 to Ionic 2, Remove Angular 1, and remove the Upgrade Adapter
- [ ] Enable [Ahead-of-Time Compilation](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html) and [Tree Shaking](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html#!#tree-shaking)

**Comment by gabrielbazan7** [comment]
@bitjson What about React Native? https://facebook.github.io/react-native/

**Comment by JDonadio** [comment]
We are actually working on a complete re-write of Copay/BitPay app using angular 4 and ionic 3. You can check it at [v4 branch](https://github.com/bitpay/copay/tree/v4)

**Comment by iganbold** [comment]
Hello @JDonadio . When will you release Copay/Bitpay v4? Thanks :)
