### ISSUE TITLE
[Security] Don't show unencrypted wallet json in logs for TouchID

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#5017]
Just realized:

I have no spending password but have enabled TouchID.

If someone hacks into my phone and steals my BIP39 phrase I don't mind... but if I lend someone my phone to do something else, they could open Copay, check the log screen and see my phrase unencrypted on the screen for them to memorize or write down.

Sure, it's impractical, but having the spending behind a TouchID wall, but the private key open for anyone to view at any time (in the logs) is unexpected and potentially dangerous.

**Comment by JDonadio** [comment]
We have a [new feature](https://github.com/bitpay/copay/pull/5726) (already merged but not published yet) for PIN/Fingerprint implementation. So I think this case is covered. What you think?

**Comment by JDonadio** [comment]
The private key is not longer in the logs section.
