### ISSUE TITLE
Wallet Issue

### ISSUE THREAD

**Issue by TonyMarq** [bitpay/copay#5018]
Hi,

I have an issue with my Personal CoPay wallet that I'm confused about. I just noted that I'm showing a completely different CoPay Receive Bitcoin address then I originally had. My original account # was
1DgC58PJbb4iiU2FANQuLJfpEecLL8W7L5

but now I'm showing this number:
1JAQM1Yq1LsGWQ12ZwE2f1oxBPHgUir3Zg

I do have another sub-wallet in the CoPay account and that number is okay. 

Can anyone help explain this?
I do have pending activity with my account. 

Thanks,

**Comment by dabura667** [comment]
Addresses automatically change on the fly, don't worry about it.

**Comment by bitjson** [comment]
Yep, your wallet contains many addresses, the Receive view only shows the most recent one. You can safely use any address from the wallet, and payments will still be added to your balance. 

We have some plans to make this clearer in the interface – I'm going to merge this issue into that one. https://github.com/bitpay/copay/issues/5020
