### ISSUE TITLE
wallets are maxing payments

### ISSUE THREAD

**Issue by Dorf-On-Code** [bitpay/copay#5019]
Hey,
When i try to send bitcoins from any of my wallets (3 total) i can only send the grand total of them all.  Once i scan the address i get locked out of the "address" & "amount" lines.  This is obviously a problem because i need to send different amounts, but it is also concerning because i thought they were completely seperate and it seems there is an exchange of information going on between them.

Is there a "send max" setting i am not aware of?
Thnx

**Comment by dabura667** [comment]
The only time a scanned QR will lock you out of the amount is if the QR code has a set amount encoded into it.

Try scanning a different QR code

**Comment by Dorf-On-Code** [comment]
That was it.  I had tried several codes from the same website but not elsewhere.  Turned out to be an issue with my account setting elsewhere.   So simple... so stupid.  Thanks for your patience/tolerance.

**Comment by bitjson** [comment]
Thanks @dabura667. Looks like this issue is solved, so I'm closing for now. Please let me know if I should reopen.
