### ISSUE TITLE
btc address generate new one

### ISSUE THREAD

**Issue by azenec1390** [bitpay/copay#5021]
Hi when i receive payment my btc address generate new one. i just want to know can I my old btc address receive 2 and more payment? thanks.

**Comment by bitjson** [comment]
Yes, old addresses will continue to work – all of your wallet addresses are permanently stored (and backed up by your 12 word backup). 

Hopefully this will be made clearer by https://github.com/bitpay/copay/issues/5020. I'll merge this issue into that one now. 🚀
