### ISSUE TITLE
BUG: UI problems with backup window on Android

### ISSUE THREAD

**Issue by gabegattis** [bitpay/copay#5029]
From a support email:

"I have downloaded the BitPay app to my Samsung Galaxy S3. When I try to get a receive address for Bitcoin under the Bitcoin wallet a partially hidden window pops up that I think is suggesting that I backup my wallet first. Unfortunately this window is mostly obscured and there is nothing I can click on to perform a backup or move to the next step. The BTC address is also obscured. It has been this way since I first downloaded the app. If I try to manually backup the wallet I get the same problem. Unfortunately the only way to get out of the window is to go to the task manager and kill the app. Due to this the BitPay app has been completely useless as I can't see or derive the BTC receive address."

**Comment by JDonadio** [comment]
There is

**Comment by JDonadio** [comment]
Related https://github.com/bitpay/copay/issues/4997

@bitjson there is any update on this? We couldn't reproduce it yet. Maybe it's caused by android version 4.x.x

**Comment by bitjson** [comment]
merging to that issue (#4997)

**Comment by gabegattis** [comment]
The user was using Android 4.3

**Comment by bitjson** [comment]
#4997
