### ISSUE TITLE
"Update Available" Card

### ISSUE THREAD

**Issue by bitjson** [bitpay/copay#5039]
For the desktop builds, Copay should automatically check for updates in the background, download them, and verify they are properly signed. Once an update is ready to be installed, an "Update Available" card appears in the home tab.

Title: `Update Available`
Message: `An update has been downloaded and verified. To install it now, restart Copay.`
Call to action: `Restart`
Secondary: `What's new?`

Users should be able to manually disable automatic updates in `Settings` -> `Advanced`, in which case the card says `Install & Restart`.

The card is not dismissable, but should be minimizable (like the `Next steps` card).

**Comment by vanhue** [comment]
<td width=200px>![image](https://cloud.githubusercontent.com/assets/4007284/20896071/121543c6-baea-11e6-9960-43a29d8f8fd0.png)</td>

**Comment by vanhue** [comment]
@bitjson I thought it made more sense for the cta to be "Install" over "Restart". Any thoughts?

**Comment by vanhue** [comment]
Invision link: https://projects.invisionapp.com/d/main#/console/7989750/208805731/preview

**Comment by JDonadio** [comment]
Related issue https://github.com/bitpay/copay/issues/4857
