### ISSUE TITLE
Balance calculation: don’t add worthless inputs

### ISSUE THREAD

**Issue by bitjson** [bitpay/copay#5040]
Inputs that are smaller than the transaction fee required to spend them set false expectations for users, since they'll never be able to reasonably. (Such that `Send Max` would be equivalent to a `Send All` feature.) These inputs should not be added when calculating a wallet's available balance.

Ideally, we should also maintain the `excludedBalance` of wallets. If the user tries to delete a wallet that seems to has a non-zero `excludedBalance`, the delete view should require an additional confirmation explaining the situation and showing the `excludedBalance`.

**Comment by JDonadio** [comment]
I think [this](https://github.com/bitpay/copay/pull/5196) solve some of that confusing scenarios when there are small or locked inputs.
