### ISSUE TITLE
Lock iOS app with fingerprint or password

### ISSUE THREAD

**Issue by CrispyB** [bitpay/copay#5052]
Is there a way to lock the iOS app, or require fingerprint or password?
I checked the scan fingerprint option and it does nothing.
I don't want to leave my wallet unlocked

**Comment by dabura667** [comment]
you can add a password and/or TouchID for spending.

However, anyone can view your balances and switch between your wallets, and spend from your wallets that don't have a password and/or TouchID enabled.

**Comment by dabura667** [comment]
Also: If you don't set a password, and you only set TouchID, there is a way for someone who has access to your unlocked phone to see the 12 word phrase backup for wallets without the password set. (even if they have TouchID set, it will be visible.) By just opening the developer logs screen. (in About Copay)

https://github.com/bitpay/copay/issues/5017

**Comment by dabura667** [comment]
tl;dr

lock your iPhone and don't let others use your iPhone if you have a lot of money on it.

**Comment by bitjson** [comment]
Thanks for submitting an issue @CrispyB – as @dabura667 mentioned, the best way to secure your wallet is to prevent potential thieves from getting access to your unlocked device. Particularly with iPhones, the best security is a phone-wide pin or password lock. The iPhone's hardware security is fairly solid as far as mobile devices go.

Fundamentally, even if Copay did provide an "app-only" pin or password, there are a variety of other ways attackers with physical access to your unlocked device might gain access to your bitcoin. (Regardless of security features that are possible to implement on an app level.)

We are working on a simple app pin/passcode lock in #4555, but it's absolutely critical to understand – only unsophisticated attacks will be prevented by this security feature (part of the reason it's not been a priority). It may prevent small thefts, but it will not keep your bitcoin safe.

For strong security, consider creating a "shared wallet" which requires multiple devices to sign transactions. This protects you both from simple thefts and from potentially-unknown vulnerabilities in any single device. More devices = more security. 🔒 

Merging this issue into #4555 for now, but please let me know if I should re-open.
