### ISSUE TITLE
npm start not working for me please check the bellow err!!

### ISSUE THREAD

**Issue by Deepakhc** [bitpay/copay#5081]
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! file cmd
npm ERR! path cmd
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn cmd
npm ERR! copay@2.5.0 start: `npm run build:www && ionic serve --nolivereload --nogulp -s`
npm ERR! spawn cmd ENOENT
npm ERR! 
npm ERR! Failed at the copay@2.5.0 start script 'npm run build:www && ionic serve --nolivereload --nogulp -s'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the copay package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:www && ionic serve --nolivereload --nogulp -s
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs copay
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls copay
npm ERR! There is likely additional logging output above.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! copay@2.5.0 start: `npm run build:www && ionic serve --nolivereload --nogulp -s`
npm ERR! Exit status -4058
npm ERR! 
npm ERR! Failed at the copay@2.5.0 start script 'npm run build:www && ionic serve --nolivereload --nogulp -s'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the copay package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:www && ionic serve --nolivereload --nogulp -s
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs copay
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls copay
npm ERR! There is likely additional logging output above.

**Comment by bitjson** [comment]
Hi @Deepakhc – do you see any other information logged before this error? There might be something about a package missing?

Also, could you confirm you ran `npm install` before running `npm start`?

**Comment by Deepakhc** [comment]
There is no other error except the errors which i being commented above and i have also checked all the packages and also latest npm is already been installed on my machine.

**Comment by Deepakhc** [comment]
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "D:\\copay\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:www"
npm ERR! node v6.9.1
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! copay@2.5.0 build:www: `grunt`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the copay@2.5.0 build:www script 'grunt'.
npm ERR! This is most likely a problem with the copay package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs copay
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls copay
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\copay\npm-debug.log

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! copay@2.5.0 start: `npm run build:www && ionic serve --nolivereload --nogulp -s`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the copay@2.5.0 start script 'npm run build:www && ionic serve --nolivereload --nogulp -s'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the copay package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:www && ionic serve --nolivereload --nogulp -s
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs copay
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls copay
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\copay\npm-debug.log

**Comment by nectareon-technologies** [comment]
for me also same error. please help me

**Comment by JDonadio** [comment]
Did you try with `node v4.2.6` ?

**Comment by JDonadio** [comment]
Feel free to reopen it you still need support with this.

**Comment by gabrielbazan7** [comment]
Could you try building step by step ?
First remove all files `npm run clean-all`
Then:
- npm i
-  cd app-template 
- node apply.js bitpay
- cd ..
- grunt
- ionic serve --nolivereload --nogulp -s

**Comment by imawhale** [comment]
Fatal error: Unable to find Gruntfile.
