### ISSUE TITLE
Transition between pages flash a white line in the statusBar (iOS)

### ISSUE THREAD

**Issue by cmgustavo** [bitpay/copay#5082]

**Comment by bitjson** [comment]
This is only when transitioning from a wallet detail view back to the home tab, correct?

**Comment by cmgustavo** [comment]
Yes, when back to the home tab, correct.

**Comment by cmgustavo** [comment]
This is on all back view transition. From Amazon.com Gift Card to home, Glidera to home, etc. 

When back from wallet preferences, the title disappears also.

![img_0290](https://cloud.githubusercontent.com/assets/237435/21502185/e16e6d7a-cc2c-11e6-8d90-8f20a6b93d62.png)
