### ISSUE TITLE
Share BitPay social buttons not working, showing loader animation only

### ISSUE THREAD

**Issue by Aclay16** [bitpay/copay#5084]
Upon tapping any social sharing button the loader is enabled for less than a second, then closes.

From Session logs:
`undefined is not an object (evaluating 'config.download.url')`

<img src="https://cloud.githubusercontent.com/assets/17866397/20435727/375b030e-ad7b-11e6-93b6-66ac26962435.PNG" width="200">

**Comment by bitjson** [comment]
Fixed in https://github.com/bitpay/copay/pull/5086
