### ISSUE TITLE
Transaction month label undefined for previous year

### ISSUE THREAD

**Issue by vanhue** [bitpay/copay#5085]
<img width="363" alt="screenshot 2016-11-18 10 40 59" src="https://cloud.githubusercontent.com/assets/4007284/20435874/c4ae434c-ad7b-11e6-9793-ab8aee921724.png">

But it's defaulting to "Recent"

Would be great if it could label transactions from previous year "Month (YYYY)" 

See example:

<img width="363" alt="screenshot 2016-11-18 10 40 59" src="https://cloud.githubusercontent.com/assets/4007284/20435891/d45ccee4-ad7b-11e6-90db-6cd11a710f1b.png">

**Comment by JDonadio** [comment]
Fixed.
