### ISSUE TITLE
Outdated Linux install instructions in FAQ

### ISSUE THREAD

**Issue by mandeep** [bitpay/copay#5090]
Hi all,

The Linux install instructions in the Copay FAQ tell the user to open a terminal and type the following command:
```
run ./Copay
```
I believe this command should be changed to the following:

```
./BitPay
```
I would be more than happy to submit a pull request with the change, however I don't believe GitHub has added Wiki pull requests as of yet.

**Comment by JDonadio** [comment]
Thanks for your suggestion. Definitely we'll change it 😉
