### ISSUE TITLE
Multisig on one device

### ISSUE THREAD

**Issue by oscartownsley** [bitpay/copay#5096]
Hello, is there any way I can set up a 4 of 5 Multisig wallet using Ledger Hardware wallets without needing 5 devices? I.e. Only using one computer

Many thanks

**Comment by JDonadio** [comment]
Unfortunately it's not possible. Each participant have to be in a different platform or device. If you build Copay you can run desktop app and browser and create a 2-2 but that's all you can do.

**Comment by oscartownsley** [comment]
Hey I actually found a way of doing it. Use multiple user profiles in
chrome :)

Hopefully this helps the next person

**Comment by dabura667** [comment]
> Hey I actually found a way of doing it. Use multiple user profiles in chrome :)

ingenuity! Good job!
