### ISSUE TITLE
Bitpay card view balance collapse

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#5103]
Top section should collapse nicely like the wallet views (rather than scroll away).

**Comment by JDonadio** [comment]
Reviewing the collapse process... honestly it's a huge (and dirty) code block for a simple animation that **only works for iOS**. So I'm not sure to do that for other section or view. 

@ajp8164 please re-open it if you think there is a clean way to do this and even better to improve the current collapse functionality.

**Comment by ajp8164** [comment]
@bitjson should comment on this.

**Comment by bitjson** [comment]
@msalcala11 has it working on all platforms on the latest version of Ionic. So maybe if not now, we can get it implemented everywhere during/after a migration?

**Comment by JDonadio** [comment]
About this code https://github.com/bitpay/copay/issues/5212
