### ISSUE TITLE
Can't import my wallet with recovery phrase after Windows Phone App reinstall.

### ISSUE THREAD

**Issue by molchwien** [bitpay/copay#5116]
I had to reinstall the windows phone app. I type the recovery phrase exactly as it was displayed before the reinstall (from a screenshot) – and I get an error saying it's supposedly invalid. How do I get my wallet back?

**Comment by JDonadio** [comment]
Can you try using a different platform? [Chrome app](https://chrome.google.com/webstore/detail/copay/cnidaodnidkbaplmghlelgikaiejfhja) maybe, and let us know how it goes

**Comment by molchwien** [comment]
That was the first thing I tried. It didn't work on the day, but worked when I tried again today – thanks!

**Comment by JDonadio** [comment]
Glad to read this!
