### ISSUE TITLE
Please evaluate BIP idea for "Boolean Addresses"

### ISSUE THREAD

**Issue by pilotniq** [bitpay/copay#5118]
Hello,

In [a post](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2016-November/013329.html) to the bitcoin-dev mailing list I solicited feedback on a proposal for standardising P2SH Bitcoin addresses which could be signed by an and/or combination of bitcoin addresses. A bit like Multisig, but more flexible.

I think copay would be an interesting platform to implement such an idea in, so I would particularly like your feedback on the usefulness and design of such a feature.

Please see the post linked above.

I could not find a better forum to communicate with you, so I hope writing an issue here is OK.

**Comment by BGalliotti** [comment]
This issue has been added to our Support Request List and we will be reviewing it.
Thanks for your contribution.
