### ISSUE TITLE
Recover Multisig Trezor wallet 

### ISSUE THREAD

**Issue by oscart1** [bitpay/copay#5119]
Hello I am trying to perform the same operation as chriswilmer here 

https://github.com/bitpay/copay/issues/3531

except with a Ledger. For some reason when I try and import the wallet from the Ledger it takes me to a new m-of-n invite screen. I noticed that when you select Trezor, there is a button for import 'shared wallet' but for ledger there is not. Is there any reason for this, and is this the issue?

**Comment by JDonadio** [comment]
@oscart1 please take a look [here](https://github.com/bitpay/copay#hardware-wallet-support)

**Comment by oscart1** [comment]
Hello @JDonadio I have looked at the documentation. I am following the instructions to recover a shared wallet from my Ledger. 

Add Wallet -> Import -> Hardware wallet

But when I click import it takes me to "share this invitation with your copayers" screen, so it hasn't recovered my shared wallet...

Any help much appreciated

**Comment by JDonadio** [comment]
Can you try to delete or update the chrome apps? **Make sure to get a full backup for all of your wallets**. I'm able to import my ledger and trezor accounts without problems...
