### ISSUE TITLE
Delete / Make New Multisig Ledger Wallet

### ISSUE THREAD

**Issue by oscart1** [bitpay/copay#5120]
Hello, I used some ledgers to create a 4 of 5 wallet, but now I have changed my mind and just want to do 3 of 4.

I understand that 'delete' does not actually delete them from the server, only from the device, but when I try to make a new shared wallet, Copay tells me that the key is already being used.

Is there any way to actually delete a multisig wallet or do i have to mess with the 'account number' field when I create a new shared wallet?

**Comment by JDonadio** [comment]
`Is there any way to actually delete a multisig wallet or do i have to mess with the 'account number' field when I create a new shared wallet?` Exactly

**Comment by BPiEnterprise** [comment]
no
