### ISSUE TITLE
Pending confirmation

### ISSUE THREAD

**Issue by Djole1506** [bitpay/copay#5125]
Hello,

I have a problem, I have bought some bitcoins but the status is "Pending Confirmation", and it has been like that for hours, and still haven't received my bitcoins.
Can you help me please?

Thank you in advance

**Comment by JDonadio** [comment]
Can you give us the txid?

**Comment by Djole1506** [comment]
Sure: 
459ba7adb29ba0cdaed1620443e1c6bb7a40e8bf4e4c120aa7083ffce68ce571

**Comment by JDonadio** [comment]
Ok I can see the feePerKb is lower than our economy fee rate, so this can take some hours to be confirmed. Also, you can check that the transaction fee is ** 0.0001 ** and could be a bad idea to set that as a fixed number and not based on the tx size instead. Where did you buy that bitcoins?

**Comment by Djole1506** [comment]
I needed some bitcoins, so I bought some from a bitcoin machine ATM, in a store close to my house. They sell bitcoins like that, never used it before, this was the first time. So, you think it will process, just it will take time?

**Comment by JDonadio** [comment]
Sure, but of course it does not work as fast as you expected 🤕

**Comment by Djole1506** [comment]
Ok, I was afraid I have lost my money. Nice to know that eventually I will receive it :)

**Comment by JDonadio** [comment]
We are not able to tell you how long will be, depends on ATM company services. I hope I've helped ;)

**Comment by Djole1506** [comment]
Sure I understand. Thank you very much for the help :)

**Comment by JDonadio** [comment]
Glad to be helpful ;)
