### ISSUE TITLE
Hidden balance

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#5128]
We must provide another way to do this, maybe not all the users knows this feature.
[This](https://github.com/bitpay/copay/issues/5093) is a critical bug and was reported in the feedback sheet.

> My balance is hidden and I don't know how to make it show again. Please create an easier way to fix this 

@bitjson are we able to send a quickly fix with this?

**Comment by JDonadio** [comment]
Fixed (in master) https://github.com/bitpay/copay/pull/5098

**Comment by dabura667** [comment]
Might want to remove user's email address imo
