### ISSUE TITLE
Delete recovery phrase after backup

### ISSUE THREAD

**Issue by frenchfaso** [bitpay/copay#5132]
With the old version (Copay) it was possible to delete the recovery phrase, now I can't find a way to delete it. And after going through the backup procedure it neither gets automatically deleted.
(talking about the Windows desktop vesion)

**Comment by JDonadio** [comment]
That feature was removed. In order to access privately to your recovery phrase you have to set the spending password.

**Comment by frenchfaso** [comment]
Ok, that doesn't sound terribly safe... do you plan bringing this feature back?

**Comment by JDonadio** [comment]
Not for now :(
