### ISSUE TITLE
Refresh balances on the home view immediately

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#5134]
When the home view is presented all of the balance information shown on all wallets, cards, etc should be refreshed from their source immediately on view load.  If the balance has not yet been read from the source then use a placeholder indicating that balance info is being fetched.  Cards in particular do not seem to refresh until navigation to the card view has occurred and the displayed balance seems to have been read from a cache which could have been long ago (an incorrect balance is shown).

**Comment by ajp8164** [comment]
Should also refresh any balances displayed on a view when the app comes forward from the background.

**Comment by JDonadio** [comment]
Working as expected now.
