### ISSUE TITLE
No way to remove redeemed Amazon card

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#5135]
Need a way to remove a redeemed card.  Ideally there is an AWS API we can use to refresh the card redemption status and if redeemed then remove it (or at least make it  removable).  The "Cancel" button at the bottom of the (redeemed) card view results in a "Failed to cancel AmazonGiftCard" dialog.  No idea what this does for an un-redeemed card..

**Comment by cmgustavo** [comment]
The AWS API doesn't have a way to check if a card was redeemed. There are only 3 responses  (success, failure, resend). I don't know if they have plan to add this feature.

Regarding the "Cancel" button, it tries to cancel the gift card but if it was already redeemed or has an error (that we don't know until this try), it returns error ("Failed to cancel"). I think that we should have another button to remove the gift card, what do you think?

**Comment by ajp8164** [comment]
Still don't understand the cancel button.

We should have a way to remove/hide a card that I know to be redeemed.  Maybe we offer an "archive" feature that hides the card rather than deleting it to prevent people from deleting possibly un-redeemed card accidentally Need a way to recover the card out of the archive (hidden list).

**Comment by cmgustavo** [comment]
Canceling initializes the refund process.

Good idea (Archived cards could be another view).
