### ISSUE TITLE
Send push or badge notifications when incoming funds are confirmed.

### ISSUE THREAD

**Issue by jameswalpole** [bitpay/copay#5155]
Users won't watch their apps for this, so some kind of notification (email or push or badge) would be appropriate.

**Comment by JDonadio** [comment]
Right now if your are out of the app you'll receive a push notification, within the app you'll see the activity card (if you have it enabled) on home view. Can you give me more information about how do you think this would be? thanks!

**Comment by JDonadio** [comment]
Cleared up. I think we should send a 2nd push notification once the tx was confirmed. Badge will not be completely clear to notify the user about this. Thanks @jameswalpole

**Comment by JDonadio** [comment]
Done
