### ISSUE TITLE
Recreate wallet - UI [Bug]

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#5158]
<img width="436" alt="copay_-_copay_bitcoin_wallet" src="https://cloud.githubusercontent.com/assets/13851807/20975644/d217b240-bc7e-11e6-9429-87b525c49b84.png">

**Comment by JDonadio** [comment]
Will be fixed [here](https://github.com/bitpay/copay/pull/5196)

**Comment by gabrielbazan7** [comment]
This was fixed ?

**Comment by JDonadio** [comment]
Yes. Closing this
