### ISSUE TITLE
Allow copying the 12 words on the backup screen to clipboard

### ISSUE THREAD

**Issue by gabegattis** [bitpay/copay#5167]
If I want to save my 12-word seed to a file, I have to manually type it out, which is slow and error prone. I can't even get it by inspecting it with the chromium dev tools since each word is its own html element.

**Comment by gabrielbazan7** [comment]
This is on purpose. We want the user to make a safe backup with physical paper and a pen (It's what we recommend on the onboarding process). You only do it once, there's no need for it to be fast.
