### ISSUE TITLE
Section headers on the settings tab look like incorrectly displayed settings options.

### ISSUE THREAD

**Issue by gabegattis** [bitpay/copay#5168]
Not sure any better way to name this issue but...

When I am on the settings tab, there are a bunch of horizontal bars. Each has the name of the setting, a description(optional) and a toggle switch.

These bars are divided up into sections, and listed under a header. ("Enabled Integrations", "Wallet Operation", "Experimental Features", etc.)

The problem is that the header is styled to look very similar to the actual settings bars. When I first saw this tab, I thought, "Why doesn't this setting have a toggle switch? It looks grayed out. Maybe it is disabled for some reason." Then I realized that those were section headings.

In the old Copay UI, it was a bit more obvious. The section headers had a slightly different indentation and the text was in ALL CAPS.

One specific setting that is really confusing is "Development Utilities". There is a header and a setting with the same name.

If the window is large enough that there is extra space at the bottom, the extra space is the color of the headers, which makes it a bit easier to figure out, but still not ideal.

There are countless ways to handle this, but here are some ideas:

* make header text center aligned
* make header text all caps
* make header text bold or larger font size
* make header text a different font
* make the color of the header text surround the sides of the setting bar, as if the setting was floating on top of a background that contains the header text

I added screenshots of the new and old UI for comparison.
![newsettings](https://cloud.githubusercontent.com/assets/4419243/20993366/bc77e804-bcb7-11e6-92d2-e9f833af76c2.png)
![oldsettings](https://cloud.githubusercontent.com/assets/4419243/20993371/c2ff5a2c-bcb7-11e6-9466-fc1d11e6bafc.png)

**Comment by gabegattis** [comment]
Having the description text be the same font, and almost the same size as the setting name also makes it look worse. The descriptions look similar to the setting name. The same solutions that apply to the headers/settings could apply here as well.

**Comment by JDonadio** [comment]
Done
