### ISSUE TITLE
Selected wallet does not persist across tabs.

### ISSUE THREAD

**Issue by gabegattis** [bitpay/copay#5173]
I have 3 wallets. I go to the home screen and I selected wallet Foo, which takes me to the main page with Foo's balance and tx history. I click on the receive tab, and it shows an address for wallet Bar.

Accidentally performing an action using the wrong wallet could be a serious problem for a number of reasons.

**Comment by gabrielbazan7** [comment]
Closing this one. Related to https://github.com/bitpay/copay/issues/4862
