### ISSUE TITLE
Back arrow in the top-left corner of the wallet screen can disappear

### ISSUE THREAD

**Issue by gabegattis** [bitpay/copay#5175]
I have had this happen a couple of times, but I'm not sure how I did this or how to reproduce. The back arrow on the wallet home screen disappeared for a while, and then randomly reappeared again.

It doesn't disappear while I am sitting there on the screen, only which I switch to it from another screen.

**Comment by gabegattis** [comment]
This also happens on the advanced settings page.

**Comment by JDonadio** [comment]
Waiting for https://github.com/bitpay/copay/pull/5864
