### ISSUE TITLE
multiple instance of bitcore-lib found

### ISSUE THREAD

**Issue by gabegattis** [bitpay/copay#5176]
Our old friend, the bitcore version check, rears its ugly head again. This happened after changing the BWS url on a wallet. The whole app went white. I caught this in the dev console:
```
angular.js:33 Uncaught Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.
bitcore.versionGuard @ angular.js:33
(anonymous function) @ angular.js:33
r.36../lib/address @ angular.js:34
s @ angular.js:27
(anonymous function) @ angular.js:27
(anonymous function) @ angular.js:58
r.125.../package.json @ angular.js:59
s @ angular.js:27
(anonymous function) @ angular.js:27
r.133../api @ angular.js:59
s @ angular.js:27
(anonymous function) @ angular.js:27
r.124../lib @ angular.js:58
s @ angular.js:27
(anonymous function) @ angular.js:27
r.1.../node_modules/bitcore-wallet-client @ angular.js:27
s @ angular.js:27
e @ angular.js:27
(anonymous function) @ angular.js:27
ionic.bundle.min.js:40
```
```
Uncaught Error: [$injector:unpr] http://errors.angularjs.org/1.5.3/$injector/unpr?p0=bwcServiceProvider%20%3C-%20bwcService%20%3C-%20sjcl%20%3C-%20profileService
(anonymous function) @ ionic.bundle.min.js:40
(anonymous function) @ ionic.bundle.min.js:77
d @ ionic.bundle.min.js:74
(anonymous function) @ ionic.bundle.min.js:77
d @ ionic.bundle.min.js:74
e @ ionic.bundle.min.js:75
invoke @ ionic.bundle.min.js:75
(anonymous function) @ ionic.bundle.min.js:72
invoke @ ionic.bundle.min.js:75
(anonymous function) @ ionic.bundle.min.js:77
d @ ionic.bundle.min.js:74
e @ ionic.bundle.min.js:75
invoke @ ionic.bundle.min.js:75
(anonymous function) @ ionic.bundle.min.js:72
invoke @ ionic.bundle.min.js:75
(anonymous function) @ ionic.bundle.min.js:77
d @ ionic.bundle.min.js:74
e @ ionic.bundle.min.js:75
invoke @ ionic.bundle.min.js:75
(anonymous function) @ ionic.bundle.min.js:77
q @ ionic.bundle.min.js:41
eb @ ionic.bundle.min.js:77
c @ ionic.bundle.min.js:54
yc @ ionic.bundle.min.js:55
startAngular @ copay.js:27
(anonymous function) @ copay.js:27
b @ ionic.bundle.min.js:220
Pf @ ionic.bundle.min.js:70
d @ ionic.bundle.min.js:70
```

We are probably going to remove that check in bitcore-lib v1.0.0, but we should still investigate. This could be a sign of other issues.

**Comment by JDonadio** [comment]
Already done

**Comment by murrekatt** [comment]
@JDonadio can you please share what was "done"? I see only the open "idea" on lib [here](https://github.com/bitpay/bitcore-lib/issues/67).

Please also share what you know about this issue why it's triggered etc. Thanks.

**Comment by troggy** [comment]
I'm now unable to build my Copay fork (based on Copay 2.7.0) because of this issue. It used to run fine and now it is not. I suppose it is somehow related to the npm version. Already spent multiple hours trying to figure out how to fix it, but no success.

Some observations:
bitcore-wallet-client v2.11.0 (the one used in Copay 2.7.0) depends on bitcore-lib 0.13.5 while some of other dependencies (like bitcore-mnemonic) depend on bitcore-lib 0.14.0 and bitcore-lib 0.13.9. All this soup is being browserified into the angular-bitcore-wallet-client — I have at least two copies on bitcore-lib there

**Comment by troggy** [comment]
Alright, I sorted it out.

The solution for my particular case is to explicitly set previous stable versions on bitcore-mnemonic and bitcore-payment-protocol to be used in bitcore-wallet-client:

```
    "bitcore-mnemonic": "1.1.1",
    "bitcore-payment-protocol": "1.1.0"
```
The reason? Bitpay released new "minor" versions of bitcore-mnemonic and bitcore-payment-protocol this March. These versions depend on bitcore-lib. So when bitcore-wallet-client is being browserified for Copay two bitcore-lib definitions slip into the result and — bam! — dreaded version guard is on duty.
Actually, this is a breaking change to me, so it should not be a minor version bump.
