### ISSUE TITLE
Show message on balance screen when we cannot connect to BWS

### ISSUE THREAD

**Issue by gabegattis** [bitpay/copay#5177]
I put a bogus BWS url for my wallet to see how it handled that. On the balance screen, there is a button that says "tap to retry", but I don't know what it is retrying to do. It should say, "could not get balance, tap to retry", or something like that.

**Comment by JDonadio** [comment]
We found that bug and will be fixed [here](https://github.com/bitpay/copay/pull/5196)

**Comment by JDonadio** [comment]
Done
