### ISSUE TITLE
Receive tab does not know that wallet is incomplete

### ISSUE THREAD

**Issue by gabegattis** [bitpay/copay#5178]
One of my wallets was a multi-sig wallet that I had not completed yet. I navigated to the receive tab and this wallet was selected. Normally, it says, "Incomplete wallet. All signing devices must...", but in this case, it behaved like a complete wallet. It had the "Next Address" part and the "B" logo next to where an address would be, but obviously no address or qr code.

I have not been able to reproduce, and I don't know how I made it happen.

**Comment by JDonadio** [comment]
I had also incomplete wallets to test similar cases but I couldn't reproduce it. Did you change any settings or something before navigate to receive tab and note that?

**Comment by gabegattis** [comment]
I don't know what steps I took to produce it, and I was not able to reproduce in further testing. I do not recall any specific settings that I had changed.

**Comment by JDonadio** [comment]
May be was caused by any bws interruption or so? Anyways we'll be alert.
Reopen this if happens again. Thanks @gabegattis
