### ISSUE TITLE
Scrolling through alternative currency takes forever

### ISSUE THREAD

**Issue by gabegattis** [bitpay/copay#5180]
The alternative currency page only shows about 20 results at a time. If I want to pick a currency at the bottom of the list, I have to scroll down a small bit, wait for it to load more currencies, scroll down some, more, wait, scroll, wait, scroll...

**Comment by gabegattis** [comment]
Also, I cannot use arrow keys or grab the scroll bar. Unless I have a mouse wheel, I have to use 2-finger scrolling. Most of the time, it interprets this as a side-swipe and takes me back to the previous page. The is an enormous PITA. I still have not successfully reached the bottom of the list.

**Comment by gabegattis** [comment]
The side swipe thing is even stranger, because I have horizontal touchpad scrolling disabled in my operating system.

**Comment by JDonadio** [comment]
I think we can implement a search box to reach any currency without scrolling. What do you think?

**Comment by gabegattis** [comment]
That could be part of the solution, but not a complete solution, imo. A better method would be to just load the whole list up front. I see no reason why we have to use paging for this list. It is not like a tx history report, where we are making a bunch of requests to the server. It should just be a hard-coded object in the code.

**Comment by JDonadio** [comment]
I agree 👍
