### ISSUE TITLE
Improvement suggestion for send max

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#5187]
Combined with idea for (settings optional) payment favorites or "last three sent".
![screen shot 2016-12-08 at 12 51 07 pm](https://cloud.githubusercontent.com/assets/1063765/21023421/776d0d7e-bd4e-11e6-832c-0a52f7fa7d86.png)

**Comment by JDonadio** [comment]
In order to avoid the amount section was compromised by space, we moved the send max option to an isolated menu at the top/right of the view.
