### ISSUE TITLE
SURBTC Integration for Buy & Sell

### ISSUE THREAD

**Issue by agustinf** [bitpay/copay#5190]
I'm director on a Latin American exchange (SURBTC). We are considering the possibility of dedicating some effort on submitting a pull request to Copay in order to integrate Buy & Sell functionality for Latin American users. 

Given the technical aspect is well handled by our team, would this be merged?

Thanks in advance.

**Comment by bitjson** [comment]
Hi @agustinf, we'd love to review a pull request for a SURBTC integration! 

I do want to warn you – we're actively working on a major refactor upgrading the application to Ionic 2 and Angular 2: https://github.com/bitpay/copay/tree/ionic2. So there's a good chance anything developed in the next 1-2 months will need to be refactored. That being said, we plan to continue expanding our exchange integrations, and we'd love to work with you!
