### ISSUE TITLE
"Tap to retry" always shows for wallet

### ISSUE THREAD

**Issue by gabegattis** [bitpay/copay#5205]
Got a support ticket from a user who is getting the "Tap to retry" message on the balance view.

Device is Asus nexus 7 tablet, android 5.1.1

The device does has an internet connection

**Comment by gabegattis** [comment]
Sounds like the wallet cannot connect to BWS for some reason.

**Comment by JDonadio** [comment]
Right, that's a connection problem with BWS. Is he using a custom bws? Or maybe was a network congestion with the public BWS. Do you know if still having connection errors?
