### ISSUE TITLE
Allow editing of contacts in address books 

### ISSUE THREAD

**Issue by jameswalpole** [bitpay/copay#5218]
Current app does not allow for editing of contact information. Add this feature, por favor.

![editing contacts](https://cloud.githubusercontent.com/assets/9257396/21152515/86d05796-c134-11e6-9dba-9f564d903825.png)

**Comment by JDonadio** [comment]
Related https://github.com/bitpay/copay/issues/5202

**Comment by JDonadio** [comment]
Thanks @jameswalpole
