### ISSUE TITLE
Negative amount - send max

### ISSUE THREAD

**Issue by gabrielbazan7** [bitpay/copay#5225]
Negative amount when trying to send max from a wallet with unspendable amounts 

![copay_-_copay_bitcoin_wallet](https://cloud.githubusercontent.com/assets/10999037/21189694/4a63b008-c1fe-11e6-9563-7e91c43dc269.png)

**Comment by JDonadio** [comment]
I couldn't reproduce it. If you run into this error again please let me know to reopen this issue. Also would be helpful provide the steps to reproduce it. Thanks!
