### ISSUE TITLE
Need more friendly and informative messages

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#5237]
This is an example.

We should not show text "DUST_AMOUNT:" (the format is not good) and "dust amount" is not very informative.

Something better - "Cannot create this transaction. The amount you want to send (0.00004547 BTC, 0.04 USD) is less than or equivalent the transaction fee (0.000054 BTC, 0.04 USD)."

![screen shot 2016-12-15 at 8 45 42 am](https://cloud.githubusercontent.com/assets/1063765/21226315/eb22381c-c2a2-11e6-87c2-b018863d6e8f.png)

**Comment by gabrielbazan7** [comment]
Solved here: https://github.com/bitpay/bitcore-wallet-client/pull/341 . 

But the message still needs to be more friendly 

<img width="271" alt="copay_-_copay_bitcoin_wallet" src="https://cloud.githubusercontent.com/assets/10999037/21233880/9e4631ba-c2cf-11e6-80b8-776d8596596e.png">

**Comment by ajp8164** [comment]
Agree. Also, I think "Error at confirm" is not correct or informative.  It's not an error.  Should say something like "Cannot create transaction".  It's a "policy" statement, not an error condition.

**Comment by JDonadio** [comment]
+1
