### ISSUE TITLE
Alternative currency shows entry triplicated

### ISSUE THREAD

**Issue by cmgustavo** [bitpay/copay#5238]
![bitpay_-_secure_bitcoin_wallet](https://cloud.githubusercontent.com/assets/237435/21227542/4826b112-c2b9-11e6-91fc-bb5a0825b468.png)

**Comment by JDonadio** [comment]
<img width="436" alt="copay_-_copay_bitcoin_wallet_y_loading_proposal_list" src="https://cloud.githubusercontent.com/assets/13851807/21233487/080eb2f4-c2ce-11e6-89c0-f4850655b90b.png">

Seems to be a load loop...
