### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by EnderB2** [bitpay/copay#5248]
Dear manager, 
I have a problem.  I use the money wallet.  I forgot my password: / 
tried all variations, did not happen.  Is there a solution? What do you recommend.
Respects

**Comment by EnderB2** [comment]
edit : Copay money wallet. 
My english failed. I am writing using a dictionary. A simple answer - narration - please

**Comment by gabrielbazan7** [comment]
There is no way to reset the spending password. However, as the spending password is only stored in the client you could delete your encrypted wallet and import it with the 12 words backup.

If you need more help, tell us. Also, I speak Spanish.

**Comment by EnderB2** [comment]
dear @gabrielbazan7 ; my language is Turkish. Let's continue in English no problem. I have read the forum now. I did not get a backup of 12 words. And I have not experimented with hundreds of variations. No solution? It must have been a formula

**Comment by gabrielbazan7** [comment]
You could not receive money without backing up your Wallet. Si you must have it in some place. Or maybe the file backup if you dont have the words.

**Comment by EnderB2** [comment]
@gabrielbazan7  One last question: can I try as many password combinations as I want? Would that be a problem? Would it be an error? Do you have the risk of locking? Please rush reply

**Comment by JDonadio** [comment]
> @gabrielbazan7 One last question: can I try as many password combinations as I want? Would that be a problem? Would it be an error? Do you have the risk of locking? Please rush reply

Absolutely

**Comment by EnderB2** [comment]
I did not understand ! Absolutely what?
My english failed. Simple answer please.
I can try - or - I can not @JDonadio , @gabrielbazan7

**Comment by JDonadio** [comment]
Yes, you can try without risk ;)

**Comment by EnderB2** [comment]
@JDonadio @gabrielbazan7 
This is good news. The only good news.
I close the subject. I want to leave without a comment.
I am a stranger to this system. It was needed 1 time. And I forgot the cipher - $ 100 left inside. The program did not warn me about this. This is a great weakness. I'm not calling a criminal. I'm looking for a solution. And no solution. Yes I am wrong. But it is a disgrace. Great failure example. Fiasco. I hope others will not make the same mistake. Respects AQ

**Comment by JDonadio** [comment]
@EnderB2 we are very sorry about that, but unfortunately without a wallet backup there is nothing we can do to help you. 

What distribution are you running, Copay or Bitpay? In any case, I'll share our recommendations, warning and course the terms of use.

* Backup needed - mandatory:

<img width="358" alt="copay_-_multisignature_wallet" src="https://cloud.githubusercontent.com/assets/13851807/21263755/3a7ff8fc-c377-11e6-8ebc-8da20c51dfc8.png">

<img width="361" alt="copay_-_multisignature_wallet" src="https://cloud.githubusercontent.com/assets/13851807/21263771/4c3e0232-c377-11e6-86ca-673579cde46c.png">


* Spending password - warning:

![warning - spending password](https://cloud.githubusercontent.com/assets/13851807/21263665/d9142dae-c376-11e6-96f0-ddb63a288341.png)

* Terms of use:

> 
> The software you are about to use functions as a free, open source, and multi-signature digital wallet.
> The software does not constitute an account where BitPay or other third parties serve as financial intermediaries or custodians of your bitcoin.
> While the software has undergone beta testing and continues to be improved by feedback from the open-source user and developer community, we cannot guarantee that there will be no bugs in the software.
> You acknowledge that your use of this software is at your own discretion and in compliance with all applicable laws.
> You are responsible for safekeeping your passwords, private key pairs, PINs and any other codes you use to access the software.
> **IF YOU LOSE ACCESS TO YOUR COPAY WALLET OR YOUR ENCRYPTED PRIVATE KEYS AND YOU HAVE NOT SEPARATELY STORED A BACKUP OF YOUR WALLET AND CORRESPONDING PASSWORD, YOU ACKNOWLEDGE AND AGREE THAT ANY BITCOIN YOU HAVE ASSOCIATED WITH THAT COPAY WALLET WILL BECOME INACCESSIBLE.**
> All transaction requests are irreversible.
> The authors of the software, employees and affiliates of Bitpay, copyright holders, and BitPay, Inc. cannot retrieve your private keys or passwords if you lose or forget them and cannot guarantee transaction confirmation as they do not have control over the Bitcoin network.
> To the fullest extent permitted by law, this software is provided “as is” and no representations or warranties can be made of any kind, express or implied, including but not limited to the warranties of merchantability, fitness or a particular purpose and noninfringement.
> You assume any and all risks associated with the use of the software.
> In no event shall the authors of the software, employees and affiliates of Bitpay, copyright holders, or BitPay, Inc. be held liable for any claim, damages or other liability, whether in an action of contract, tort, or otherwise, arising from, out of or in connection with the software.
> We reserve the right to modify this disclaimer from time to time.

**Comment by EnderB2** [comment]
dear @JDonadio 
I did not rude, did I? My purpose: was not disrespectful. Are you the company manager? Think of it as my site, suggest it as a suggestion. It 's too late now. I will try some different combinations. If not, I will throw away. I have no more work to do. Do not worry, my friend. But be careful, please. Recommended listening

**Comment by JDonadio** [comment]
@EnderB2 not at all. I'm just a developer of the BitPay company and I try to clarify what happened. First all, we are very sorry if you are having problems with your funds, I just want to show you all of our work in order to prevent this cases because it's not good experience for both you and our team work 🤒.

With the prints I posted above my purpose was "maybe he can try to remember where the backup is".

Our terms of use explain exactly your case, and unfourtunately we can't help you without a backup of your wallet 😢 

I hope you are not displeased or so, we can try to do our best for you and the community. Please, if there is anything else let me know it.

**Comment by EnderB2** [comment]
dear @JDonadio 
I will check the password.
To test it while paying, except
"Preferences"> "request spending password" - I can try to cancel!
is it correct ?

**Comment by JDonadio** [comment]
I don't know if I understand you correctly, but if you mean where you can try tu put your password is in preferences > resquest spending password switch.

**Comment by EnderB2** [comment]
@JDonadio arrow. very clear. I understand.
How do I know if I have made a backup before?
I persisted in this problem that we will solve

**Comment by EnderB2** [comment]
@JDonadio  Do we continue to write from here? Do you have an e-mail? I will send caps

**Comment by JDonadio** [comment]
Feel free to post here. My contact mail is _javier@bitpay.com_ as your prefer

**Comment by EnderB2** [comment]
Thank you for your support. I edit and send CAPs @JDonadio

**Comment by EnderB2** [comment]
@JDonadio  Please check the e-mail. I sent caps. I sent text. You can write from here. or . email . 
it does not matter. respects

**Comment by EnderB2** [comment]
@JDonadio 
Did my e-mail arrive? check it please. I'm waiting for feedback

**Comment by EnderB2** [comment]
Do you have anybody to answer my friend?
What a nonsense! There is no interlocutor

**Comment by gabrielbazan7** [comment]
@EnderB2 you could not receive money without doing the backup flow. If you don't do it, you should see this on the receive view 

<img width="358" alt="3a7ff8fc-c377-11e6-8ebc-8da20c51dfc8" src="https://cloud.githubusercontent.com/assets/10999037/21295269/053c4564-c530-11e6-850a-5e17f3052980.png">

**Comment by EnderB2** [comment]
dear @gabrielbazan7 
I forgot my password.
Yes I made it back up! I did not make a backup!
I do not remember that
I guess-I did it.
check it please. How can we do - look at the database

**Comment by gabrielbazan7** [comment]
We could not check that, you should find the 12 words so we could help you

**Comment by EnderB2** [comment]
Hypothesis 1 : I did not take notes in 12 words. but. I got a backup. Is there a solution in this case?
Hypothesis 2 : there are 2 wallets opening at the same time. 12 words of empty wallet - can it be the same as other wallet words? @gabrielbazan7

**Comment by gabrielbazan7** [comment]
There is no solution if you not take note of the 12 words. 
I don't understand the second hyphotesis, but the 12 words of a wallet can't be the same as other one.
Do not tell us the 12 words. As the spending password is only stored in the client you could delete your encrypted wallet and import it with the 12 words backup.

**Comment by EnderB2** [comment]
I understand. I will check it. I'll let you know again. @gabrielbazan7

**Comment by richardsuns** [comment]
@EnderB2 
when you lose 12 phrase, generally there is no solution.
however, only method that may work is cracking your password if you have backup. if you need help in this regard contact me.
