### ISSUE TITLE
[BitPay 1.2.0] A button doesn't works

### ISSUE THREAD

**Issue by Kirvx** [bitpay/copay#5250]
Android 6.0.1 - Z3 Compact
### The "Contribuer aux traductions" button doesn't works

![screenshot_20161216-004640](https://cloud.githubusercontent.com/assets/6627786/21246872/a62274c8-c32b-11e6-937f-e43a3fd54927.png)

**Comment by JDonadio** [comment]
It's working for me on 5.0. I'll try to test in a 6.0 version in a while.

_Thanks for all your comments @Kirvx_ 😃

**Comment by Kirvx** [comment]
The button works on the Translators page but not on this one :anguished:
