### ISSUE TITLE
[BitPay 1.2.0] UI bug

### ISSUE THREAD

**Issue by Kirvx** [bitpay/copay#5253]
Android 6.0.1 - Z3 Compact
https://crowdin.com/translate/copay/1/en-fr#1206

![screenshot_20161216-004558](https://cloud.githubusercontent.com/assets/6627786/21258462/719013da-c37d-11e6-8e54-76a477aebdaa.png)

**Comment by JDonadio** [comment]
Android 5.0 - Galaxy S5

<img width="435" alt="screenshot_2016-12-13-17-10-15_png" src="https://cloud.githubusercontent.com/assets/13851807/21262777/e164a9f2-c371-11e6-9c6f-4ff22ccf1096.png">
