### ISSUE TITLE
Venezuela Bolivar Fuerte Issue

### ISSUE THREAD

**Issue by gabrielbazan7** [bitpay/copay#5258]
Got this report from the BitPay App Feedback Spreadsheet:

```The VEF alternative currency does not reflect the real value of bitcoin in Venezuela. ```

I checked and could confirm it's true.

**Comment by rdymac** [comment]
It is an issue affecting all wallets (both open source/community driven wallets and hosted wallets) that harms adoption: https://twitter.com/btcven/status/839523601921556481 

Other open source wallets have integrated BitcoinVenezuela.com's average price as seen in [this screenshot](https://bitcoinvenezuela.com/img/electrum_vef.png) (screenshot is old and a little bit outdated) or other reference exchange rates based on real market prices.

**Comment by gabrielbazan7** [comment]
Seems to be fine now. I just tested. You could see the rates we use here : https://bitpay.com/api/rates

**Comment by rdymac** [comment]
@gabrielbazan7 [this price](http://imgur.com/EgnD1S1) doesn't look like the real value of bitcoin in Venezuela, which seems to be the feedback report you mentioned, checkout this post https://twitter.com/btcven/status/839905496601673729
