### ISSUE TITLE
Add some label to readonly wallets

### ISSUE THREAD

**Issue by gabrielbazan7** [bitpay/copay#5267]
Maybe we could add something here
<img width="437" alt="copay_-_copay_bitcoin_wallet" src="https://cloud.githubusercontent.com/assets/10999037/21268557/12e0ee98-c38e-11e6-8294-bd16e2b6f75c.png">

We only have this
<img width="466" alt="copay_-_copay_bitcoin_wallet" src="https://cloud.githubusercontent.com/assets/10999037/21268547/03a5a1f8-c38e-11e6-9404-0e4172421bf7.png">

**Comment by JDonadio** [comment]
Label added in `v4` (wallet detail view). What about set the wallet name cursive and/or gray?
