### ISSUE TITLE
Clearly label bitcoin wallet address

### ISSUE THREAD

**Issue by jameswalpole** [bitpay/copay#5270]
Many non-bitcoiners are confused about what a bitcoin address is/looks like and may confuse other numbers in the app (wallet ID, etc) for their address. We should do something to clearly label the string in the Receive view as "your bitcoin address" for these users.

**Comment by JDonadio** [comment]
Maybe we need something like:

<img width="398" alt="copay_-_multisignature_wallet" src="https://cloud.githubusercontent.com/assets/13851807/21362720/59565128-c6c8-11e6-8f7e-b8df9d284cc7.png">

**Comment by JDonadio** [comment]
We need design work here. Currently the QR code remains with the same size but we have not scroll in this view so there is not space to add information in small devices like:

iPhone 4 (320x480)

<img width="323" alt="copay_-_copay_bitcoin_wallet" src="https://cloud.githubusercontent.com/assets/13851807/21364239/bdd67578-c6ce-11e6-88de-9bd42e932112.png">

iPhone 5 (320x568)

<img width="320" alt="copay_-_copay_bitcoin_wallet" src="https://cloud.githubusercontent.com/assets/13851807/21364263/de79b7e0-c6ce-11e6-9af0-fa2129761390.png">

@bitjson please can someone of the design team give us a hand with this? 😄
