### ISSUE TITLE
The backup screen needs to be even more clear...

### ISSUE THREAD

**Issue by bitjson** [bitpay/copay#5274]
I'm afraid it's still not quite clear to some users that they should not email BitPay's support channel their 12 words...

Maybe some additional language on this screen would help?

![screen shot 2016-12-16 at 3 02 23 pm](https://cloud.githubusercontent.com/assets/904007/21277266/802f5ab0-c3a3-11e6-8933-df6741c13044.png)

I'm thinking:

```
Please carefully write down this phrase.
Do not share it with anyone.
```

```
BitPay support will *never* ask for your backup phrase.
```

**Comment by JDonadio** [comment]
IMHO covered by:

![wallet_name](https://user-images.githubusercontent.com/13851807/29229293-eb027810-7eb3-11e7-8def-830704ae039e.png)
![wallet_name](https://user-images.githubusercontent.com/13851807/29229304-f5f36662-7eb3-11e7-8b00-1e3055cfc5bb.png)
