### ISSUE TITLE
Add detailed instructions for installing on Linux desktop

### ISSUE THREAD

**Issue by john-light** [bitpay/copay#5278]
I am attempting to test on Linux Mint 17.1 and have gotten as far as verifying the download with PGP then I cannot go any further. This is what the BitPay desktop wallet folder looks like after I open it:  

![bitpaylinux](https://cloud.githubusercontent.com/assets/9424721/21283053/ef8d52ba-c3b0-11e6-98b5-71b3c1de9fef.png)  

I don't know what to do from here. There were no install instructions on the releases page, and the instructions in the readme were not very helpful either. I saw something mentioned about nwjs, so I downloaded that, but then ran into the same problem: nothing in that folder looks like an executable that I can run to install the program, and double-clicking all the icons didn't yield any helpful results either. NW.JS similarly lacks detailed instructions for installing their software.    

Please update your Linux install instructions with detailed step-by-step instructions so that the install process is easier for Linux users.

**Comment by gabrielbazan7** [comment]
Download BitPay Wallet linux version and extract the contents of the zip file to a new folder. Open terminal->Go to your newly created folder->run ./Bitpay.

Please re-open the issue if you need more help.
