### ISSUE TITLE
Creating Transactions With Multiple Outputs

### ISSUE THREAD

**Issue by martindale** [bitpay/copay#5292]
I'd like to make several payments in one transaction, to multiple parties.  This is possible with the Bitcoin RPC API, but not in the Copay wallet.  This is useful for both consumers and businesses in making consolidated payments, such as end-of-the-month bills which occur with some frequency.

**Comment by BGalliotti** [comment]
This issue has been added to our Feature Request List and we will be reviewing it.
Thanks for your contribution.

**Comment by gabrielbazan7** [comment]
#9289
