### ISSUE TITLE
Missing icons for iOS

### ISSUE THREAD

**Issue by cmgustavo** [bitpay/copay#5299]
![img_0276](https://cloud.githubusercontent.com/assets/237435/21356571/e6a16d96-c6b0-11e6-9294-da7dff6732fe.png)

![img_0277](https://cloud.githubusercontent.com/assets/237435/21356619/11d79332-c6b1-11e6-8879-b454d32d8910.png)

**Comment by bitjson** [comment]
I'm seeing it in both places on the version downloaded from the app store: ![img_0538](https://cloud.githubusercontent.com/assets/904007/21356891/3c732940-c6a1-11e6-96d0-63789103b2f9.PNG)

iPhone 6s (10,1), iOS 10.2

Are you looking at a version built for development?

**Comment by cmgustavo** [comment]
Yes, I 'm. If there isn't another report, we could close it issue.
