### ISSUE TITLE
[BitPay 1.2.1] Missing icon from notification - Android

### ISSUE THREAD

**Issue by Kirvx** [bitpay/copay#5300]
### Android 6.0.1 - Z3 Compact

![screenshot_20161220-164632](https://cloud.githubusercontent.com/assets/6627786/21357951/743767b6-c6d7-11e6-863d-e0006e85ab50.png)

**Comment by JDonadio** [comment]
This still happen after the migration to FCM

**Comment by Kirvx** [comment]
Still a problem

**Comment by Kirvx** [comment]
Fixed with the V4 on Android 8.
