### ISSUE TITLE
submitted for a user that does not want to register for a GH account, "Android App Bug"

### ISSUE THREAD

**Issue by kleetus** [bitpay/copay#5303]
Could you post it? I don't want to create an account and login at GitHub (?) just for this.

 
Hi,

Thank you for reaching out to us regarding the rendering bug. Please post your inquiry at https://github.com/bitpay/copay/issues and a member of our BitPay app team will follow up with you directly.

Thank you for your patience!

Best Regards,

![img_20161220_102127](https://cloud.githubusercontent.com/assets/12446/21358752/b7dbe3fa-c6a7-11e6-8604-38fe60c743e1.jpg)

 
Attached is image of a rendering bug on my Motorola Droid Turbo (2560x1440), Android 6.0.1, bitpay app, latest version. I thought you would like to know.

**Comment by JDonadio** [comment]
Sorry for the delayed reply. We recently shipped the new design of Copay, you can check it at https://copay.io/#download

Feel free to reopen this if you still having this error.
