### ISSUE TITLE
[V4] Design - The Navbar looks too much iOS on Android

### ISSUE THREAD

**Issue by Kirvx** [bitpay/copay#5304]
## This one is particularly ugly IMO

![3622](https://cloud.githubusercontent.com/assets/6627786/21359086/458a4948-c6db-11e6-8d4f-a947e268d06b.png)

### The Close button should be replaced withe the left arrow icon, and the Reject button is very discreet.

**Comment by JDonadio** [comment]
Agree. However the back arror means backward navigation, not close (for modals). The reject button was added in order to avoid the down scrolling. I'll improve this in the migration to ionic 3 (actually in progress)

**Comment by Kirvx** [comment]
:+1:

**Comment by Kirvx** [comment]
Nice evolution in the V4, but the close button is still a problem:

![screenshot_2018-04-04-20-12-16-640_com bitpay wallet](https://user-images.githubusercontent.com/6627786/38325956-cd3d5700-3844-11e8-88c2-e9bbf1cfadeb.png)
