### ISSUE TITLE
Icon looks blurry on Windows app

### ISSUE THREAD

**Issue by cmgustavo** [bitpay/copay#5309]
* Also missing icon from apps bar

![windows_10](https://cloud.githubusercontent.com/assets/237435/21362974/5572b258-c6c9-11e6-9c15-9ea0cb2bf7a2.png)

![windows_10](https://cloud.githubusercontent.com/assets/237435/21362991/6e5fb98c-c6c9-11e6-8bae-f23d772a418b.png)

**Comment by Aclay16** [comment]
Windows icons can be found here:
https://github.com/bitpay/archived-bitpay-wallet/tree/ref/design/resources/bitpay/windows/icon

**Comment by cmgustavo** [comment]
Thanks! 

JFYI: Windows uses ICO's file type with multiple sizes (I can use a PNG to generate it).
