### ISSUE TITLE
Amount back button - sometimes not there

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#5311]
![img_5065](https://cloud.githubusercontent.com/assets/1063765/21363828/2cc55c82-c6bc-11e6-91b4-901f61a039d7.PNG)

No back button - navigation state seems to get messed up sometimes.  I was just going forward and backward and then this.

The only remedy is to complete a tx or restart app.

**Comment by SilverPin** [comment]
I see this is on the iPhone app, however I can confirm that this also happens on macOS SIerra 10.12.2 with v.1.2.0

**Comment by JDonadio** [comment]
Waiting for https://github.com/bitpay/copay/pull/5864
