### ISSUE TITLE
Need access to private key

### ISSUE THREAD

**Issue by khaltire** [bitpay/copay#5322]
Hi guys, I accidentally sent an omni coin (maidsafe) to my copay address in error. What do I need to do to access this amount. It is a large sum. I have access to my 12 word recovery phrase, so please allow me access to the private key for this one address.

Let me know what my options or the next steps are.

Thanks

**Comment by dabura667** [comment]
Derive the private key using BIP44.

Do maidsafe addresses and private keys use the same kind of format as Bitcoin?

https://bip32jp.github.io/english/

I made this tool, you can download it and derive your BIP44 addresses and their private keys offline.

**Comment by khaltire** [comment]
Thanks I'm new to all this, is there anything you can do to walk me thru it
? I will donate an amount (large) towards your project if so.

Thanks

**Comment by dabura667** [comment]
Sure.

Some quick questions:

1. Are you using your phrase for anything besides the one time you accidentally sent omnicoin to it? Is there a lot of bitcoins on your Copay wallet? (This will be to guage how careful to be when recovering)
2. What wallet do you normally use for your omnicoin transactions? Does it have an option to "import private key" or "sweep private key" anywhere?

**Comment by khaltire** [comment]
Phrase isn't used for anything else, just to recover copay wallet which has
never been done

Yes large sum of maidsafe on there

Thanks

On Dec 22, 2016 7:02 AM, "Dabura667" <notifications@github.com> wrote:

Sure.

Some quick questions:

   1. Are you using your phrase for anything besides the one time you
   accidentally sent omnicoin to it? Is there a lot of bitcoins on your Copay
   wallet? (This will be to guage how careful to be when recovering)
   2. What wallet do you normally use for your omnicoin transactions? Does
   it have an option to "import private key" or "sweep private key" anywhere?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bitpay/copay/issues/5322#issuecomment-268817249>, or mute
the thread

**Comment by khaltire** [comment]
And regarding the maidsafe, yes it can be sent to Bitcoin addresses but the
problem with copay is it doesnt allow you to access the private key , so I
can't spend it.

Thanks for your help

On Dec 22, 2016 12:47 AM, "Dabura667" <notifications@github.com> wrote:

Derive the private key using BIP44.

Do maidsafe addresses and private keys use the same kind of format as
Bitcoin?

https://bip32jp.github.io/english/

I made this tool, you can download it and derive your BIP44 addresses and
their private keys offline.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bitpay/copay/issues/5322#issuecomment-268749171>, or mute
the thread

**Comment by dabura667** [comment]
https://bip32jp.github.io/english/

1. Type your backup phrase into "BIP39 passphrase"
2. Switch "Derivation Path" to "BIP 44 k'th account i'th keypair (receive): m/44'/0'/k'/0/i"
3. If you don't see the address in the "Address" place at the bottom, increase the "Keypair Index (i)" from 0 to 1, then 2, then 3 etc. etc. until you find the address.
4. "Private Key (WIF)" will be (probably) the private key you use to import to your omni wallet.

If you are afraid that your device might have virus or something, you can download the website from https://github.com/bip32JP/bip32JP.github.io/archive/master.zip and unzip to an offline machine, and open up the html file inside the english folder to find the above page.

**Comment by JDonadio** [comment]
Reopen if it's not solved yet
