### ISSUE TITLE
Error at Wallet Service: 403

### ISSUE THREAD

**Issue by OrlandX** [bitpay/copay#5323]
Hi,
I'm having the following problem on my android Copay version 2.6.0.
 I started to receive error message when I try to update my Wallet: Could not update wallet: 403

Please help me

**Comment by JDonadio** [comment]
@OrlandX sorry for the delayed reply. Have you been able to update it?

**Comment by Chicagobtc** [comment]
tengo el mismo problema porque sucede esos en varias billeteras

**Comment by mandotolas** [comment]
I have the same problem and I am worried about my stored bitcoins, for days I can not connect or make transactions, someone can help me please
