### ISSUE TITLE
Portuguese-Portugal Translation

### ISSUE THREAD

**Issue by FilipeOS** [bitpay/copay#5343]
Hi,

Please add pt-PT to the translation website and I can freely do that. Otherwise no one care about it.

Thank you.

**Comment by FilipeOS** [comment]
* Android app

**Comment by gabrielbazan7** [comment]
Portuguese is already added to crowdin Copay project. You could start translating here: https://crowdin.com/translate/copay/1/en-ptbr

Thanks

**Comment by FilipeOS** [comment]
That is pt-br not pt-pt.

If you guys want I can make a decent translation to pt-pt, pt-br is not the same, they speak a lot bad.

**Comment by JDonadio** [comment]
@FilipeOS that would be great!!!

**Comment by gabrielbazan7** [comment]
ok @FilipeOS. Thanks!!  https://crowdin.com/translate/copay/1/en-pt !

**Comment by FilipeOS** [comment]
I've finished the app store translation and many of the app strings, please verify them since it requires the previous guy to approve, an he is Chinese (I think)

Thank you. I'll keep updating the strings and re check after update released.

**Comment by JDonadio** [comment]
@FilipeOS thank you!
