### ISSUE TITLE
'Updating wallet', is that syncing with the blockchain or something else?

### ISSUE THREAD

**Issue by SuperHenkie** [bitpay/copay#5344]
I sometimes notice how Copay says "Updating wallet" on my desktop. 

Currently I'm using breadwallet on iOS and considering to use Copay there too, main reason being that breadwallet (although a great wallet) often has to "sync" for quite a long time. 

I understand this is because breadwallet is a real node on the bitcoin p2p network and thus has to sync its relevant blockchain data. **Is this also true for Copay?** Should I expect similar waiting times there, or does Copay rely on trusted APIs / nodes / servers (like e.g. Mycelium on android) and is "Updating wallet" something else?

**Comment by JDonadio** [comment]
Sorry for the delayed reply. 

Breadwallet synchronize directly from the blockchain while Copay does from `insight` which is always synchronized with the blockchain. For that reason the sync of Copay is really fast.
