### ISSUE TITLE
Various problems with BitPay 1.2.0 on macOS Sierra 10.12.2 - Crash on close, false transaction times, strange confirming amount

### ISSUE THREAD

**Issue by SilverPin** [bitpay/copay#5345]
1. When closing the app window using the red x in the top left hand corner, the app hangs. It is necessary to force quit and restart the app. This occurs every time without fail. I can copy the crash report here but if requested, though I decided not to this time because it is so large. If you want to specify which bits of the crash report you would find useful please let me know.

2. The times in the transaction history are false. 

In the first of these two screenshots you will see that the last transaction I have made was reported as occurring a few seconds ago. That transaction was actually made 3 or 4 hours earlier. Moreover, the transactions that are reported to have occurred on the 5th of December were more like the 19th or 20th of December:

![screen shot 2016-12-24 at 15 20 19](https://cloud.githubusercontent.com/assets/24178244/21467624/ca751c50-c9ec-11e6-84a0-aa179b12fd02.png)

Here you will see further transactions. At the bottom you will note that the date is reported as Dec 0, 16. All of these dates are false:

![screen shot 2016-12-24 at 15 20 39](https://cloud.githubusercontent.com/assets/24178244/21467627/08d35f84-c9ed-11e6-9693-663a1afdc8fc.png)

I am not sure if these inaccurate times are only being reported because a transaction is still occurring.

EDIT: I have just download the BitPay app for my iPhone, and these unusual transaction times are reflected there too.  

3. I do not know if this is just because I am new to bitcoin and do not know how these things work, however the "confirming" amount shown in the above screenshot is odd. I have no idea why that amount is confirming - as you can see in my transaction history I haven't sent or received anything of that amount. If this is normal I would appreciate if someone could briefly explain to me what is happening.

Thanks!

**Comment by babymylove** [comment]
hi

**Comment by JDonadio** [comment]
@SilverPin we made several changes for the next release, including a new balance information view (with detailed information), date format fixed, etc. So if these problems remains with the new version please update us. thanks!

**Comment by JDonadio** [comment]
Please reopen if the problem remains

**Comment by SilverPin** [comment]
Sorry for the slow reply. I have not been using the app lately. I just downloaded and ran the new app, and all the problems appear to be fixed. Thanks!

**Comment by JDonadio** [comment]
Awesome! :)
