### ISSUE TITLE
On Receive screen, QR code shifted right and cut off

### ISSUE THREAD

**Issue by cadethacker** [bitpay/copay#5346]
I'm *brand new* to the bitcoin world and downloaded this app as my first wallet.  When I click on the receive button at the bottom, the QR code that is shown is shifted to the right and is cut in half. 

The Settings --> About BitPay says:
Version: v1.2.1
Hash: 763ac28

My iPhone 6 is iOS 8.4 (12H143)

<img src="https://cloud.githubusercontent.com/assets/12255072/21487984/ffe6613a-cba6-11e6-8a7d-cda1f33b17c3.png" width="400">

**Comment by gabrielbazan7** [comment]
Sorry about that. It happens too you every time you click on receive? We will try to fix it soon.

**Comment by JDonadio** [comment]
Also happens in android: https://github.com/bitpay/copay/issues/5346

**Comment by cmgustavo** [comment]
Closes #5950
