### ISSUE TITLE
Custom exchange rate

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#5352]
BTC/JPY is much more expensive than BTC/USD now, and the prices are not even close to what Coincheck (our Bitpay) charges for items.

Since Japan is pretty much a one horse town (Coincheck is the only payment processor, 0 competition) I would love to enter some info to make the JPY price come from Coincheck.

```
Currency: Japanese Yen
API endpoint: https://coincheck.com/api/ticker
JSON price element: last
```

Adding those two extra fields and then Copay would just GET the API and parse the "last" key as the JPY value of one bitcoin.

Would be nice and convenient.

**Comment by dflipse** [comment]
Same problem in China/CNY, rates are well off actual rates on the major exchanges. And since most trade is from China, many potential Copay users would find an enhancement useful, indeed. May I suggest to review the Exchange Rate plugin in Electrum. Seems to do the job, nicely, indeed

**Comment by dabura667** [comment]
@dflipse Electrum just hard codes exchanges from user pull requests... so not very viable.

I like the Advanced method of inputting the price API manually, it makes it so anyone can use any exchange they want.

**Comment by dflipse** [comment]
Would work for me
