### ISSUE TITLE
Recovery documentation for multisig wallets is unclear

### ISSUE THREAD

**Issue by Chris869218** [bitpay/copay#5356]
Regarding this document (https://github.com/bitpay/copay/blob/master/backupRecovery.md), "WD" is referenced 7 times. "WD" is never defined. Should it read "WB" instead?

For example, it is clear a 4 of 6 multisig wallet could be re-created with all 6 wallet seeds. However, if 2 of the wallet seeds were lost, its not clear what would be needed in addition to the 4 remaining wallet seeds as "WD" is never defined. 

If "WD" should have said "WS" instead, would 4 of the 6 seed words and a WS that was exported with the "do not include private key" option selected be enough information to recreate the wallet?

**Comment by matiu** [comment]
It should said WB instead of WD, sorry about that. I Just sent a PR to fix it.

**Comment by Chris869218** [comment]
Thanks. When exporting a wallet backup, there is the option to include or omit the private key. Am I correct in assuming that if you exported the WB without a private key, but still had 4 wallet seeds elsewhere (of a 4 of 6) that you'd be able to recover the wallet? Or does the WB need to be exported with a private key included?

**Comment by Chris869218** [comment]
Sounds good. Thanks a lot. No enterprise use or large amounts of funds at play. I currently have a copay multisig with a small amount of funds. Since I'm using the default BWS, I was curious what would happen if that disappeared for any reason. Figured I would see what the documentation said before finding/creating a second BWS to experiment but the WD/WB typo confused me a bit. Thanks for the clarification.
