### ISSUE TITLE
Comparison table bitpay.com/docs/wallets is missing Copay

### ISSUE THREAD

**Issue by fortran77** [bitpay/copay#5358]
I see that the very useful web page https://bitpay.com/docs/wallets has replaced the Copay wallet with the Bitpay wallet.

Since these two wallets are not identical (and the Copay wallet is available as a Google Chrome app while the Bitpay wallet is not), it would be useful if the comparison table included both.

**Comment by JDonadio** [comment]
The simple reason for that is this: https://github.com/bitpay/copay/issues/4909
Regarding that the only app available in the chrome-store is Copay.
