### ISSUE TITLE
[Concept] New UX for the Import Wallet screen.

### ISSUE THREAD

**Issue by Kirvx** [bitpay/copay#5364]
### It's only a concept, but I think that the Import wallet menu can be more pleasant for the user. Feel free to pick up the ideas to improve the design.

___

### Default screen
![1](https://cloud.githubusercontent.com/assets/6627786/21531823/50ab8af0-cd4b-11e6-9dfb-5443762fe03e.png)
___

### If a word does not exist in the wordlist
![3](https://cloud.githubusercontent.com/assets/6627786/21532158/d8a65a5a-cd4d-11e6-9d1e-f6e26708f425.png)
___

### If the user disables the toggle
![more than_resultat](https://cloud.githubusercontent.com/assets/6627786/21544359/8699e5fc-cdce-11e6-8c73-159b4baf4fd7.png)

**Comment by Kirvx** [comment]
Updated

**Comment by JDonadio** [comment]
I'm not agree with the design, but definitely we need to be more clear with the label `Type the recovery phrase (usually 12 words)` 

![bitpay_-_secure_bitcoin_wallet](https://user-images.githubusercontent.com/13851807/29231025-e6bf5a4a-7ebb-11e7-9b13-6e687398c9f3.png)

Maybe something like this will be more clear
![bitpay_-_secure_bitcoin_wallet](https://user-images.githubusercontent.com/13851807/29231106-4b75aeda-7ebc-11e7-888c-41ff6399fbf8.png)

**Comment by Kirvx** [comment]
No problem, feel free to improve the elements that need an improvement  :+1:
