### ISSUE TITLE
Export without private keys should not require (spending) password

### ISSUE THREAD

**Issue by dflipse** [bitpay/copay#5366]
Currently, it does. With compromised environments, this creates unnecessary risk. Another desired enhancement would be to enable such public key only export via QR. Currently, QR exports inclusive of private keys, always. Also, QR should be password encrypted, as well, in my view.

**Comment by JDonadio** [comment]
Reviewing: NACK.

If someone take your wallet and export your wallet even without pk will be able to check your balance, transactions, create proposals (and lock your balance), etc.
