### ISSUE TITLE
btc transaction not reflecting in account

### ISSUE THREAD

**Issue by walkingatm** [bitpay/copay#5369]
Hello, this is the btc transaction ID for a transaction, which is not showing in my wallet..
https://blockchain.info/tx/965f5013e1963731470c965f742bfd9eea8da0226334a0f1d4cc1b75a0d04bc8

please check and rectify this.

Thanks

**Comment by walkingatm** [comment]
https://blockchain.info/address/1N6CiH8yi3WVGubpYjFiCQ1s8QDUrUaXrz

this is the transaction ID for ma wallet

**Comment by fortran77** [comment]
The Copay wallet seems to get out of sync easily. You can force it to resync:

⚙ ➡ Advanced ➡ Wallet Information ➡ Scan addresses for funds

**Comment by walkingatm** [comment]
I have done that but still the btc is not showing

**Comment by fortran77** [comment]
You didn't specify in your original report whether or not you had forced a resync. Nor have you specified the hardware and software platforms on which you are using Copay. This suggests to me that you didn't think carefully about how to write a good bug report. Try a Google search for [how to write a good bug report]. I'm not one of the Copay developers, just a user concerned with how many people make next to no effort to provide enough information for developers to make sense of a bug report.

**Comment by matiu** [comment]
Hi, 1N6CiH8yi3WVGubpYjFiCQ1s8QDUrUaXrz is not an address hosted by Copay.
Neither is, '1Juv6ErCPQWPkqAXgUgoB95hTCsga1yD51 ', the output address from TXID you mentioned. Please recheck and reopen the issue if still valid.
