### ISSUE TITLE
Backup from 02-2015 not restoring (spending password?)

### ISSUE THREAD

**Issue by Darkster1** [bitpay/copay#5382]
My Windows Phone has been repaired and reinstalled by the repair company.

Now I'm trying to import the copay backup (date created: 02-2015) but Copay displays the following error:

"Could not import. Check input file and spending password", If I type a wrong password the message: "Could not decrypt file. check your password".

I have never been asked for a spending password, so there's no spending password at all...

What can I do to solve this issue?

**Comment by matiu** [comment]
Hi,

Sorry the delay.

Please try our recovery tool at 

https://bitpay.github.io/copay-recovery/

**Comment by JDonadio** [comment]
@Darkster1 please if you still have any problem please feel free to reopen this.
