### ISSUE TITLE
Connecting Bitpay to Copay

### ISSUE THREAD

**Issue by Kenvisions** [bitpay/copay#5387]
Ive attempted to connect the correct accounts but have gotten confused. I need assistance. Thx.

**Comment by dabura667** [comment]
Please be more specific.

**Comment by Kenvisions** [comment]
I have the app on Android and I have the windows download for my PC..But
the accounts are not synced.

**Comment by dabura667** [comment]
> the app on Android

which one? which version?

> the windows download for my PC

which one? which version?

> the accounts

what kind? Personal wallet? Shared wallet? How many Copayers?

**Comment by Kenvisions** [comment]
The windows download for my PC and  personal wallet.

**Comment by Kenvisions** [comment]
Im the only copayer.

**Comment by Kenvisions** [comment]
All I want to do is be able to load the copay account and have it show on
all devices as same account.

**Comment by gabrielbazan7** [comment]
Import the wallet on your windows device. Sidebar -> add wallet -> import wallet and then enter your 12 words.

**Comment by Kenvisions** [comment]
I've done that but it says wallet is already used. Do I need to delete the
desktop version and start over?

**Comment by dabura667** [comment]
> I've done that but it says wallet is already used.

That warning message only appears when you try to "CREATE NEW" wallet. If you do "IMPORT WALLET" and put in your phrase it will work.

**Comment by Kenvisions** [comment]
Okay so I should use the phrase from the app via my Android device?

**Comment by dabura667** [comment]
If you want the wallet on "the app" to be also viewable from your Android device then yes.
