### ISSUE TITLE
After run final:desktop, did not generate Copay.exe

### ISSUE THREAD

**Issue by biallo** [bitpay/copay#5389]
Hi,
The copay version is 2.5.0, and I run it with macOS Sierra(10.12.1) and node.js 6.9.2

These are the files I get，Copay.exe is not generated.
>➜  copay git:(master) ✗ ls webkitbuilds
Copay         Copay-linux.zip     Copay.dmg           build-macos.sh      dmg-background.tiff setup-win.iss       volume-icon.icns

The full log of the terminal is here： https://shrib.com/see/rSUJpbwc3PevZ80ZqChymW7wg3TAx6PeOkn3CaW5p1rE0hegkC?v=nc

**Comment by biallo** [comment]
@JDonadio Thanks for answer.
I try with
> npm run clean-all
   npm run apply:bitpay
   npm run build:macos

I found BitPay.exe in webkitbuilds > BitPay > osx64
But It's an executable file, I think after the build, can get an installation file, like BitPay.dmg

Or that I need to use other methods to generate installation file?

**Comment by JDonadio** [comment]
@biallo sorry for the delayed reply. If you run `grunt macos` the `Copay.dmg` file will be created at `copay/webkitbuilds/` folder

**Comment by JDonadio** [comment]
Sorry for the delayed reply. Please see https://github.com/bitpay/copay/issues/5772#issuecomment-286736881

**Comment by Horbi** [comment]
https://tom-1040.blogspot.com

**Comment by biallo** [comment]
@JDonadio Got it thanks!
