### ISSUE TITLE
need help setting up wallet

### ISSUE THREAD

**Issue by JamesWhite54** [bitpay/copay#5395]
hello.  i don't know much about this but i want to get some bitcoin and i need to set up a wallet on my desktop.  it would really help if i could get some customer assistance.  is there a phone number i can call to talk to someone or do i have to wait for days while someone responds to this email.  i started out to get some bitcoin weeks ago but i can't seem to get any straight forward instruction from anyone.  i do not have a smartphone or zombie phone as i call them, and i do not want to give out my bank info.  i am looking to set up a wallet and find a physical exchange where i can buy bitcoin for dollars and this is turning into a gigantic shit-show.

**Comment by JDonadio** [comment]
Hi @JamesWhite54, when you install [BitPay app](https://bitpay.com/wallet) you can see our onboarding tour, explaining what bictoin is, how it works, etc. Please take a look there. Also, when you finish all steps a default wallet (Personal Wallet) will be created, so at that time you should be ready to start using bitcoins. Please if you have more questions feel free to post what you need.

**Comment by JamesWhite54** [comment]
i am not using a smart phone, i have a desktop and i don't really care so much about using it, i'll figure that out in time i just want to get some and hold it like a savings account and get some before it goes to 100k.  i just don't get why i am having so much trouble, this is suppose to be simple.  is there a fee for the wallet  is bank info required because i don't want to give that out.  it would help if you people had online chat or a actual phone number so i could talk to someone who can walk me through the process.  i found a place near by that has a bitcoin atm so all i need is the wallet and knowledge working it
 

    On Tuesday, January 3, 2017 1:38 PM, Javier Donadío <notifications@github.com> wrote:
 

 Hi @JamesWhite54, when you install BitPay app you can see our onboarding tour, explaining what bictoin is, how it works, etc. Please take a look there. Also, when you finish all steps a default wallet (Personal Wallet) will be created, so at that time you should be ready to start using bitcoins. Please if you have more questions feel free to post what you need.—

**Comment by dabura667** [comment]
If you look at the website, there are downloads for Windows PC and Macbooks etc.

There is also a Chrome app, so if you use the Chrome internet browser, you won't need to install any extra exe files to Windows. (It will open in a sub-window in Chrome)

Try installing one of those and read the tutorial on screen.

If you still don't get it come back here.

**Comment by JamesWhite54** [comment]
hello.  i opened a wallet with bitpay and i didn't set up a password but i can't figure out how to go back and set one up or cancel the wallet and make a new one.  i don't see how i am going to use this to buy bitcoin from a bitcoin atm which is what i plan to do.  i could sure use an online chat or someone to guide me because i am not using a smart phone and have nothing to 'scan'  what do i do put in the url numbers in the atm, i don't know. help please and thank you.
 

    On Tuesday, January 3, 2017 7:09 PM, Dabura667 <notifications@github.com> wrote:
 

 If you look at the website, there are downloads for Windows PC and Macbooks etc.There is also a Chrome app, so if you use the Chrome internet browser, you won't need to install any extra exe files to Windows. (It will open in a sub-window in Chrome)Try installing one of those and read the tutorial on screen.If you still don't get it come back here.—

**Comment by dabura667** [comment]
https://appear.in/copay-help-video

I will be waiting in this video chat for the next hour or so, let me know if you want to come and get help.

**Comment by dabura667** [comment]
@JamesWhite54 If you can, when you open the site, enable your mic and say something and I will notice... or click on the chat bubble in the lower right and type something and my computer will notify me.

I will be in the same room for the next few hours, so I should hear you if you make some noise somehow.

**Comment by JamesWhite54** [comment]
i don't have video.  and i apologize for being so retarded with all of this but i get nervous where money is involved.  i've since answered some of my own questions i scrolled down and found more info.  i hope to go to a bitcoin atm today and buy some but i am not sure what to do.  i would think i copy the wallet id number and put that into the atm. do you know about atm's
 

    On Wednesday, January 4, 2017 10:12 AM, Dabura667 <notifications@github.com> wrote:
 

 https://appear.in/copay-help-videoI will be waiting in this video chat for the next hour or so, let me know if you want to come and get help.—

**Comment by dabura667** [comment]
you don't need video. Just to watch and listen.

Enter the video chat and type "hello" and I will show you my screen and explain to you with my voice.
