### ISSUE TITLE
Add Bitcoin/BitPay 101 Screen and New User Experience Level Survey

### ISSUE THREAD

**Issue by jameswalpole** [bitpay/copay#5396]
Survey users for bitcoin experience upon wallet creation in onboarding flow. Direct completely new users to a brief Bitcoin/BitPay 101 screen in the app. Define terms and set expectations of what BitPay does with each product and what in the wallet is dependent on miners/the Bitcoin network/Bitcoin source code. Get aggregated anonymous data on percentages of new users vs. moderately experienced users vs. expert users.

**Comment by matiu** [comment]
done.
