### ISSUE TITLE
Payment Accepted but not yet broadcasted: Error Querying the Blockchain

### ISSUE THREAD

**Issue by gabrielmiron** [bitpay/copay#5401]
Hi I am getting this problem when I am trying to send Bitcoins and I have deleted the transactions several times but I get the same error.  Also I have tried with different amounts but it keeps saying the same.  Someone could help me out thanks!

**Comment by matiu** [comment]
We are checking the issue. Will update here.

**Comment by matiu** [comment]
ok, it should be OK now, could you try to broadcast the TX again?

The problem was that we had the fee limit too low on our bitcoin nodes. so multisig (or other type of bigger TXs) with high fees where been rejected. Sorry about that.

**Comment by bgmrk** [comment]
Worked for me thanks!

**Comment by gdawg123** [comment]
And me as well, thank you!
