### ISSUE TITLE
Add new fee warning/unconfirmed education language to wallet

### ISSUE THREAD

**Issue by jameswalpole** [bitpay/copay#5403]
The idea here is to educate a BitPay wallet user when they are trying to top-up their card using something non-standard in the transaction.  Let’s start with only the in-app card top-ups where BitPay controls the full experience.

**If user has low-fee setting:**

"Your transaction's fee is lower than recommended. Transactions with low or zero fees take longer to confirm.

Your fee policy is set to (Economy | Super Economy) which is too low for this type of transaction.   Based on Bitcoin network conditions, we recommend the Normal fee rate.  
  [Cancel]  [Accept]"

**Comment by JDonadio** [comment]
Already done
