### ISSUE TITLE
Specify service being reviewed in feedback flow

### ISSUE THREAD

**Issue by jameswalpole** [bitpay/copay#5404]
From @ajp8164: "Collect the identity of the service(s) for which the feedback applies. Ideally we could automatically forward this feedback directly to the service provider (e.g., Glidera) in real-time so they get a sense of the issues and urgency to provide fixes."

![feedback view](https://cloud.githubusercontent.com/assets/9257396/21652729/f5d38fe8-d27b-11e6-84fe-6c71692f6d6e.png)

**Comment by jameswalpole** [comment]
@bitjson @matiu Have a look at this part of the solution to the feedback confusion issue. I think @ajp8164 wants to forge ahead.

**Comment by ajp8164** [comment]
See https://github.com/bitpay/copay/pull/5414

**Comment by ajp8164** [comment]
![screen shot 2017-01-05 at 12 32 19 pm](https://cloud.githubusercontent.com/assets/1063765/21690628/0f70bbac-d343-11e6-849e-0542baa9c8c1.png)
