### ISSUE TITLE
UI issues on Android 4.4.2 (Samsung tablet)

### ISSUE THREAD

**Issue by cmgustavo** [bitpay/copay#5412]
![img_0301](https://cloud.githubusercontent.com/assets/237435/21681252/3c006a48-d32d-11e6-891e-81b77962aba7.JPG)
![img_0300](https://cloud.githubusercontent.com/assets/237435/21681253/3c02d030-d32d-11e6-950f-1baa9b343084.JPG)
![img_0299](https://cloud.githubusercontent.com/assets/237435/21681254/3c062294-d32d-11e6-9864-0212fe40b9b0.JPG)

**Comment by JDonadio** [comment]
Related https://github.com/bitpay/copay/issues/5346

**Comment by homeopatchy** [comment]
Here are more screenshots using an Android 4.4.2 phone.

![screenshot_2017-05-01-20-50-21](https://cloud.githubusercontent.com/assets/19495071/25597295/384f9ade-2ece-11e7-8622-ba201fca42b7.png)
![screenshot_2017-05-01-20-51-04](https://cloud.githubusercontent.com/assets/19495071/25597294/384ccbc4-2ece-11e7-9e62-144ae4076681.png)
![screenshot_2017-05-01-20-53-48](https://cloud.githubusercontent.com/assets/19495071/25597296/385041a0-2ece-11e7-8546-0742f2703c26.png)

**Comment by cmgustavo** [comment]
Closes #5950
