### ISSUE TITLE
Activity screen timestamps show sync time not tx time.

### ISSUE THREAD

**Issue by findkiko** [bitpay/copay#5416]
New transactions when you open the app after a period of time always show "A minute ago" despite upon being clicked, showing the proper time of broadcast eg. "45 minutes ago" or "A day ago" etc. The app needs to be force-quit and restarted for the expected timestamps to show on the transactions.

It feels like it was intentionally coded this way, but IMO it's unexpected behaviour; if I received bitcoin yesterday, I want the app to say I received bitcoin yesterday, not take extra clicks to get to the real time. I guess this is up for debate, let this be the place...

**Comment by JDonadio** [comment]
Thanks for the report @findkiko.

JFYI > We follow the next directive to showing dates:

"A time ago" notation is used when transaction was sent. Past a day, we use "Jan 4, 2001" notation.

**Comment by JDonadio** [comment]
Should be fixed in the next release. Also our servers are re-synchronized properly. Please feel free to reopen if the problem remains.
