### ISSUE TITLE
UI Idea - More info to the Unit page

### ISSUE THREAD

**Issue by Kirvx** [bitpay/copay#5419]
### Just an idea to take advantage of the empty space.

![3622](https://cloud.githubusercontent.com/assets/6627786/21720155/ee13beb6-d421-11e6-9815-6bc0ad0c3330.png)

**Comment by JDonadio** [comment]
I'm not completely sure about this. I'm agree with the fact this is a "sad" view 😂, but we should take care about all currencies not just US Dollar. Thoughts?

**Comment by JDonadio** [comment]
What about use a simple drop down? like:

<img width="417" alt="pantalla_completa_12_1_17_10_14" src="https://cloud.githubusercontent.com/assets/13851807/21891209/3b0b78b6-d8b0-11e6-9cde-5a12d54132c0.png">

**Comment by Kirvx** [comment]
The default fiat currency could be defined according to the alternative currency that the user specified in the settings, and yes you can use drop down to define the currency if the user tap on it.

My idea is more to avoid a "WTF is bits" than propose a good design about this :bowtie:

Another crazy idea: Add a devise converter, you have the space for that, even with the bits explanation :smile: Just kidding about this ^^ That would be cool, maybe not useful, but not a priority for sur.

**Comment by Kirvx** [comment]
currency converter*

Not "devise converter"...... that was 50% french............. I'm pretty sure you saw it as "device converter", and yes, a device converter sounds really crazy... :flushed:

**Comment by JDonadio** [comment]
I understood what you meant 😂, IMHO some extra info could be nice but add extra features without a real quorum is not the best idea

**Comment by JDonadio** [comment]
Unit view was removed.
