### ISSUE TITLE
Pending Confirmation

### ISSUE THREAD

**Issue by CorollaKid** [bitpay/copay#5428]
Hey there, about 4 hours ago i recieved roughly 90,000 BTC to my copay wallet via bitcoin ATM but in my wallet its saying its still pending confirmation ? when will i be able to spend my bitcoins?

**Comment by dabura667** [comment]
You bought over 70 million dollars worth of bitcoin at an ATM?...

do you mean "bits" (not bitcoins) which is 1/1000000 of a bitcoin.

90,000 bits is around $75

You can spend your bitcoins immediately if you check "spend unconfirmed" in the options menu.

**Comment by BPiEnterprise** [comment]
https://github.com/tellomichmich/PokeNoxBot.git

**Comment by JDonadio** [comment]
Reopen it if the problem remains
