### ISSUE TITLE
Can only find 11 of my 12 word recovery phrase

### ISSUE THREAD

**Issue by jonasmack** [bitpay/copay#5432]
Hi, I'm relatively new to Copay and brand new to github. I've just had to restore my iphone and now realized I only have 11 of the 12 words for my Copay recovery phrase.

Is there any way to recover my wallet with just 11 of the words? I tried to do a quick search in these forums but didn't see anything. If the solution involves running a script, could you please walk me through it as I've never ran one before.

Thank you very much for any help you're able to give.

**Comment by jonasmack** [comment]
I found the 12th word, how embarrassing. Not sure how to delete this thread but I will close it now.

**Comment by bitjson** [comment]
Hey there – do you have any hints as to what the remaining word is? If the words were copied down in a hurry, you may be able to compare them against the [full word list](https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md) (I assume you're looking for the [english one](https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt)?)

If you have no hints as to the final word, depending on the value, it might be worth it to you to attempt to search all possible wallets by trying all 2048 options. I'm not aware of any programs which have been written to do that specifically, but you'll probably need the [bitcore HD key documentation](https://bitcore.io/api/lib/hd-keys).

**Comment by bitjson** [comment]
Ah – glad you found it! No need to delete the issue. Hopefully someone else will find the info above helpful.

**Comment by jonasmack** [comment]
Thanks for the response! I'll leave this thread as it is.

**Comment by JDonadio** [comment]
JFYI same issue related [here](https://github.com/bitpay/copay/issues/4604)
