### ISSUE TITLE
Slide to accept (button) - Confirm view

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#5436]
Only "Accept" could be confusing for some users, actually was reported a couple of times.

**Comment by bitjson** [comment]
Just to explain this further – we've gotten a lot of support requests where it seems like the slide action is not clear enough.

My recommendation is that we make the slider for all bitcoin payment requests read:
`Slide to pay` ->

For sending bitcoin (without a payment request):
`Slide to send` ->

and for multisig proposals:
`Slide to accept` ->

BitPay card, buying/selling bitcoin, amazon card:
`Slide to complete` ->

If those words don't fit on the slider (in whatever language the user has enabled) I think they need to be reduced in size to fit (or maybe drop to a second wrapped-line). It's more important to have the language visible.

**Comment by JDonadio** [comment]
Awesome, I'll do the changes now 😉

**Comment by JDonadio** [comment]
@bitjson mobile "Slide", we must use "Click" or "Tap" for the rest of platforms instead?

**Comment by gabrielbazan7** [comment]
In my opinion "Slide to confirm" or "Slide to accept" (since you are in the confirm view) in all cases will be fine, and we don't have to worry about other actions, for example if you pay a payment request with a multisig wallet or a new action in the future.

**Comment by bitjson** [comment]
I don't have a very strong opinion on it, but I think "Slide to pay" and "Slide to send" add additional clarity that's kind of lost on the more generic statements.
