### ISSUE TITLE
Building and Debugging Chrome App

### ISSUE THREAD

**Issue by rakeshgn31** [bitpay/copay#5443]
Hi,

    I am trying to build chrome app version and debug i.e., set up my development environment. But, I am not able to build Chrome App version. I am following the ReadMe instructions. It fails saying 'Error: missing script: chrome'. Attached is the npm-debug.log. Please point me with instructions to set up a successful dev environment.

Thanks,
Rakesh G N.
[npm-debug.txt](https://github.com/bitpay/copay/files/701649/npm-debug.txt)

**Comment by JDonadio** [comment]
Can you be more specific? Did you get it build?

**Comment by rakeshgn31** [comment]
No. I was not able to build. I have node.js, npm everything installed but when I follow ReadMe instructions on building chrome app and use the command ¨npm run-script chrome¨. It fails stating an error. The error and the npm-debug log file is attached.

**Comment by JDonadio** [comment]
In copay folder try this:

* cd chrome-app
* make (build command)
* in chrome browser go to settings > extensions > load unpacked extensions > select `copay/chrome-app/build` folder
* init app

**Comment by JDonadio** [comment]
Try `npm apply:copay` and run `make` again

**Comment by rakeshgn31** [comment]
Half way through its fine. make is failing as it is not able to rsync some of the files and thus make is failing :-( 
![screenshot from 2017-01-12 15 13 33](https://cloud.githubusercontent.com/assets/17096344/21891136/c899ee3c-d8d9-11e6-800b-167b7b6ff5ad.png)

**Comment by JDonadio** [comment]
I have not a clearly response for that... maybe trying with `npm run clean-all` and start again?

**Comment by rakeshgn31** [comment]
I tried clean-all earlier. Again I tried it now. But it is the same error. I think some files are missing. I could see this issue too as in the attached image. I did the following steps in sequence.

Installed node.js and npm
Cloned the Copay repository
Did npm install
npm run apply:copay
cd chrome-app
make

Am I missing something?
![screenshot from 2017-01-12 15 33 10](https://cloud.githubusercontent.com/assets/17096344/21891660/72b8e84e-d8dc-11e6-967e-6947dd76e9ba.png)

**Comment by JDonadio** [comment]
I'll try a fresh install follow your steps. Please tell me what version of `node` are you running

**Comment by rakeshgn31** [comment]
Sure thank you! I am running node v6.9.4

**Comment by JDonadio** [comment]
Meanwhile try to use another version (4.2.6), you must to install `nvm` or `n` to manage multimple node versions

**Comment by rakeshgn31** [comment]
Sure!

**Comment by rakeshgn31** [comment]
Installed node 4.2.6 and verified the same with nvm current command and in the PATH variable. Did

npm run clean-all
npm run apply:copay
cd chrome-app
make

Make again failing with the same rsync file transfer issue.

**Comment by JDonadio** [comment]
With a fresh install I'm running into the same error. Let me check it deeper and I'll update you asap

**Comment by JDonadio** [comment]
Ok, try this:

in > `root of your copay project`/chrome-app/include > copy this content:

>./index.html
>./cordova.js
>./img/*
>./img/**/*
>./views/*.html
>./views/**/*.html

Then run > `npm run apply:copay && make`

**Comment by rakeshgn31** [comment]
Ah finally, it worked. Thank you! So, the issue was it was missing to include the required files? Are you delivering this code?

**Comment by JDonadio** [comment]
That's not a solution, the app builds but still getting errors.... I'll keep working on this

**Comment by rakeshgn31** [comment]
Okay. So, I hope I can continue with my code debugging?

**Comment by JDonadio** [comment]
The problem is there are some files that should (or not) be included in the build

**Comment by rakeshgn31** [comment]
Okay. So, I hope I can continue with my debugging with this build?

**Comment by JDonadio** [comment]
Ok, the ONLY problem there is (forgot the changes on include file), you need to run `grunt` before `make` 😂 .

So, let the `include` file back to the original state, run `npm run apply:copay` to update the files, run `grunt` and then `make`. Tell me how it goes!

**Comment by rakeshgn31** [comment]
Oh yes... Works like a charm. Thanks! Could you please update ReadMe?

**Comment by JDonadio** [comment]
Sure I'll. Thanks for the report!
