### ISSUE TITLE
Can't I recover my 2 of 3 wallet with just 2 recovery phrases?

### ISSUE THREAD

**Issue by lucaszanella** [bitpay/copay#5453]
I'm creating a 2of3 wallet. When I tried to backup the first phrase

> To restore this 2-3 shared wallet you will need:
> 
> Your wallet recovery phrase and access to the server that coordinated the initial wallet creation. You still need 2 keys to spend. OR the wallet recovery phrase of all copayers in the wallet OR 1 wallet export file and the remaining quorum of wallet recovery phrases.

Wait... Didn't I just need 2 of 3 phrases? Why not? Could somebody explain me this technically? I know about the opcode functionality of the bitcoin protocol but I can't remember why this wouldn't work. Also, why do I need access to the server that coordinated the wallet creation? What if the server vanishes or is hacked?

**Comment by isocolsky** [comment]
To recreate all addresses in a m-of-n wallet you need all n extended public keys. Once you have the addresses, you can build a tx using the corresponding UTXOs. The transaction will then need to be signed by m private keys.
If you have all 3 recovery phrases then you have all the info you need to regain access to the funds in your 2-of-3 wallet.
If all you have is 2 recovery phrases (i.e. 2 extended private keys & 2 extended public keys), you need to get the 3rd xpubkey from somewhere. This is where access to the server that hosted the wallet can help as the server holds all xpubkeys.
An alternative method is having an export of the wallet (which also has all the xpubkeys) + 2 xpriv keys.
Hope this helps.

**Comment by lucaszanella** [comment]
Can't I just save that pubkey somewhere? I could save it even in unsafe
places, right?

Em 13 de jan de 2017 17:11, "Ivan Socolsky" <notifications@github.com>
escreveu:

To recreate all addresses in a m-of-n wallet you need all n extended public
keys. Once you have the addresses, you can build a tx using the
corresponding UTXOs. The transaction will then need to be signed by m
private keys.
If you have all 3 recovery phrases then you have all the info you need to
regain access to the funds in your 2-of-3 wallet.
If all you have is 2 recovery phrases (i.e. 2 extended private keys & 2
extended public keys), you need to get the 3rd xpubkey from somewhere. This
is where access to the server that hosted the wallet can help as the server
holds all xpubkeys.
An alternative method is having an export of the wallet (which also has all
the xpubkeys) + 2 xpriv keys.
Hope this helps.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bitpay/copay/issues/5453#issuecomment-272521556>, or mute
the thread

**Comment by matiu** [comment]
Please see https://github.com/bitpay/copay/blob/master/backupRecovery.md

**Comment by agustinf** [comment]
I think this issue can be closed.
