### ISSUE TITLE
the loser of the week

### ISSUE THREAD

**Issue by blouisdiddy** [bitpay/copay#5457]
I have/had the windows 10 mobile version of the CoPay app. Through idiocy on my part and partially on Microsofts, my phone had to be hard reset....I think you know the story here.

Bottom line: I have lost my recovery mnemonic words and all I'm wondering is if there is any way to extract my wallet from my sdcard where the app originally was installed. 

Thanks for any help,

B

**Comment by bitjson** [comment]
Without a backup, the wallet is likely lost.

If it's worth it, your only chance is to try recovering the deleted data from the storage medium. You should stop using the disk immediately (it may have already been overwritten if you continued using the device), find a program that works on your operating system to recover deleted files from a storage device, and run the recovery tool. If you're (extremely) lucky, you may be able to find the app's storage in the "empty" space on the drive. If so, the "profile" key has a JSON object with an "xprivkey" field containing a private key you should be able to import back into the app (and sweep to a wallet which you have backed up).

Hope that helps!

**Comment by blouisdiddy** [comment]
I did stop using it so will try this today. Many thanks for the response
B

**Comment by agustinf** [comment]
how did it go @blouisdiddy ? perhaps this issue can be closed now?

**Comment by bitjson** [comment]
I'm going to close this for now, but please let me know if you think it should be re-opened.

**Comment by blouisdiddy** [comment]
Thanks, I still have very little to go on here…recovering files from the sd card did yield results but they appear to be encrypted by the file system.


You wouldn’t happen to know any consultants that specialize In this type of windows phone based recovery?

B
Sent from my Windows 10 phone

**Comment by blouisdiddy** [comment]
it just seems to me that knowing things like the name of the file and specific field names/lengths etc...might there be a way to decode the files I have found...I'm not a saavy in the arcane arts of bin/hex editor decrypting etc....

**Comment by blouisdiddy** [comment]
But man in hindsight I do really wish copay would NOT let you use the app until you have created the backup file in the same way mycelium does..

**Comment by bitjson** [comment]
Glad to hear you were able to recover some files, hopefully you'll be able to extract your keys.

I'm afraid I don't know of any such services – if you find one, please post here so people can find them in the future.

As for the design of the backup flow, I think this has been resolved in the [BitPay app](https://bitpay.com/wallet) and in the upcoming update to the Copay app. The backup process is significantly clearer and easier to understand, and we've put a lot of time into making sure users understand the consequences of not backing up a bitcoin wallet. (There are also more visible ongoing reminders.)

**Comment by blouisdiddy** [comment]
Thanks  just 2 more questions: (then I'll leave in peace :) )
1) is it a fact that copay stores the wallet keys on the sdcard local storage (for the windows phone version) or am I maybe chasing a pipe dream since for security reasons maybe it only stores on the phone memory. Just want to know that fact before I chase my tail with this encrypted SDcard
2) Is there any way to know from my public wallet address if I do have a backup on the server ?  

thanks
B

**Comment by guerrerocarlos** [comment]
Hello @blouisdiddy is the encrypted file part of a JSON? it looks anything like this?:

{"iv":"ide451FviUYK/4wK1BT38Q==",
"v":1,
"iter":10000,
"ks":128,
"ts":64,
"mode":"ccm",
"adata":"",
"cipher":"aes",
"salt":"OnoucoATMoI=",
"ct":"HJ2HYSb73ZXvz+tdnXubTVdcw8dOq9Ru1FUKpIA0aP [lots of letters here] RJs="}

If so, you can recover it using your password and this tool:
https://bitwiseshiftleft.github.io/sjcl/demo/
