### ISSUE TITLE
Feature Idea - Add a Bitcoin Price Chart Card

### ISSUE THREAD

**Issue by Kirvx** [bitpay/copay#5462]
### The first time I thought about this was with Luno Bitcoin Wallet (ex BitX), it's a card you can swipe:
![screenshot_20170116-175847_resultat](https://cloud.githubusercontent.com/assets/6627786/21992318/3f4d3810-dc16-11e6-978b-0eb39b96bed4.jpg)
### In addition, a general alert can appear as a popup if a big variation appears (>5%).

**Comment by matiu** [comment]
Love this idea.
