### ISSUE TITLE
CoPay App not responding on latest macOS

### ISSUE THREAD

**Issue by koalalorenzo** [bitpay/copay#5468]
Hello,
I have noticed that after importing watch-only wallets on my new Mac, when I close the CoPay app, it starts to not respond any click and I have to force quit it.

The branded version, that I don't trust, BitPay instead is fine.

Question 1: Are you still working on Copay?
Question 2: Are you going to fix these things if I provide the logs of the app crash?

**Comment by gabrielbazan7** [comment]
Hi! sorry about that.

1. Yes we are.
2. There will be a new Copay version soon. That issue should be solved there.

**Comment by JDonadio** [comment]
Should be working now. Please feel free to re-open if the problem remains.

**Comment by koalalorenzo** [comment]
When will this be released? Copay, or branded Bitpay app?

**Comment by JDonadio** [comment]
BitPay App it's working without problem regarding this issue, you can try it from www.bitpay.com/wallet. We know that Copay was not released quite a considerable time, but we are still working on that.

I'll leave this open until the next Copay release.

**Comment by JDonadio** [comment]
This should be fixed with the latest release.
