### ISSUE TITLE
Amount view layout broken on iTouch

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#5474]
iTouch gen 6

![img_5410](https://cloud.githubusercontent.com/assets/1063765/22066457/142e93a4-dd5b-11e6-809f-e204cbbd428c.PNG)

**Comment by JDonadio** [comment]
The device size is 640x 1136?

**Comment by ajp8164** [comment]
640 x 1136

**Comment by JDonadio** [comment]
Same error for small devices (i.e iPhone 4) but not sure with that resolution...

**Comment by JDonadio** [comment]
@ajp8164 please can you try with current master branch version?
