### ISSUE TITLE
[BitPay 1.3.0] Minor Bug - Coinbase account linking

### ISSUE THREAD

**Issue by Kirvx** [bitpay/copay#5484]
I linked my Coinbase account for the first time and it's Glidera that is displayed. So I have to touch the '+' button and select Coinbase to play with it.

![screenshot_20170119-015458_resultat](https://cloud.githubusercontent.com/assets/6627786/22111260/ff4aa298-de5e-11e6-9952-87634d17872f.jpg)

**Comment by cmgustavo** [comment]
It 's probably an UI issue. The first installation of BitPay have Coinbase disabled. This release enable Coinbase, but we think that only for first installations. We suspect that the option in `settings -> advanced` you must have Coinbase disabled. Please, check it 's off and let us know if it solves the issue.

Thanks!

**Comment by Kirvx** [comment]
@cmgustavo You're right, it solved this problem 👍
