### ISSUE TITLE
[Coinbase-France] Can't buy (debit card)

### ISSUE THREAD

**Issue by Kirvx** [bitpay/copay#5487]
I have a debit card configured as my primary payment method, works as expected with the website of Coinbase, not with BitPay 1.3.0

![screenshot_20170119-175423_resultat](https://cloud.githubusercontent.com/assets/6627786/22116611/4f262f64-de71-11e6-91ed-1dde4836caf0.jpg)

Debit cards are very popular in France.

**Comment by cmgustavo** [comment]
The app only receive an array of items from Coinbase asking for your available payment methods. If any of them has `allow_buy = true`, the apps will show in the form.  I think that Coinbase doesn't allow to buy with debit card using third party apps, but not sure. You should ask to Coinbase if there is any limitation there.

Thanks a lot for reporting.

**Comment by Kirvx** [comment]
Ok I contacted Coinbase, waiting for their response.

**Comment by Kirvx** [comment]
No response for the moment, but it works well with a positive balance for buying.

I will be in favor of an error message that is more complete by adding a thing like:
"Please note that direct buying with debit card is not possible outside of Coinbase."

Also, all Coinbase texts should be translatable, as it's mostly a worldwide service.

**Comment by aaronsace** [comment]
Why has this been closed?

**Comment by Kirvx** [comment]
Because it's up to Coinbase to allow debit card payment for other applications :confused:

**Comment by aaronsace** [comment]
What's the point of this then. 😕

That error message is clearly assuming a payment method be available.

**Comment by JDonadio** [comment]
The integration is not available for users that are registed outside of USA.

**Comment by aaronsace** [comment]
It as says 33 countries on the app and it works outside the app. You're clearly not using the API correctly.

**Comment by aaronsace** [comment]
You have to change it from us dollars to British pound and euros. Coinbase locks out trading in dollars outside the US. It works on the principle of three separate markets. How do you think we all buy Bitcoins outside US; through Coinbase.
