### ISSUE TITLE
[Coinbase-France] Can't sell (Insufficient funds)

### ISSUE THREAD

**Issue by Kirvx** [bitpay/copay#5488]
I'm stuck with this screen:

![screenshot_20170119-175730_resultat](https://cloud.githubusercontent.com/assets/6627786/22116789/ea47a9fa-de71-11e6-88b7-abc1ab29db4c.jpg)

I can go ahead if I touch the background, but it fails if I confirm the sale:

![screenshot_20170119-175755_resultat](https://cloud.githubusercontent.com/assets/6627786/22116848/16b34f94-de72-11e6-9c22-4ce87b3d5bd3.jpg)

I have a native balance of 4.70€, confirmed in the advanced settings in the app, so no problem of linking apparently.

**Comment by cmgustavo** [comment]
The native balance of you Coinbase 's account doesn't matter in selling process. In your case, seems to not have enough funds in the app (4usd + bitcoin fee). The BitPay app doesn't use funds deposited (from USD or EUR wallets) to sell bitcoin directly. The app sends bitcoin to Coinbase, then wait for confirmation, and finally sells exactly the same amount sent previously.

Please, let us know if it 's your case.

Regarding the first issue, I think that it 's an issue with the connection. We recommend to wait until it finished, not cancel manually. But we need more details to confirm this error.

Thanks.

**Comment by Kirvx** [comment]
Oh.......................... I completely misunderstood, I thought it was for selling bitcoins in my Coinbase account, not in my BitPay wallet :expressionless:

Sorry my bad 👎

**Comment by Kirvx** [comment]
And for the first issue, it's the same after fews minutes, stuck on the connection to Coinbase, but the connection is apparently ok because it telling me the Coinbase fees if I touch the background to quit, so maybe an UI problem of the popup..........
