### ISSUE TITLE
Update session log privacy warning language 

### ISSUE THREAD

**Issue by jameswalpole** [bitpay/copay#5493]
From Stephen: "Inform the user somewhere about exactly what kind of sensitive info is in the logs such that they can make an informed decision about whether to share it with someone trying to help debug something" 

Right now we just tell people that there is sensitive info in the logs. Makes them think that private keys are in there when it's just public keys.

**Comment by gabrielbazan7** [comment]
At current version of the app the warning says: 

The information you are about to share/export may contain sensitive data such us wallet IDs, addresses, balances, etc. Please be sure you trust the person or entity with whom you are sharing this information.
