### ISSUE TITLE
Displayed transaction and balance sometimes calculated using wrong change address

### ISSUE THREAD

**Issue by fortran77** [bitpay/copay#5495]
Intermittently, I see an incorrect balance caused by Copay having interchanged the destination address and the change address. Most recently, I observed this in the following situation.

I have both Mycelium and Copay wallets configured to use the same seed words. Any transfer made with one will naturally be visible in the other. In normal operation both wallets always show exactly the same transactions.

I made a payment using Mycelium to address A. As is usually the case, the payment presumably went from some internal address B to addresses A and C, where A was my desired destination address and C was the change addresses generated by Mycelium. Mycelium correctly showed the new balance. Copay showed a new transaction occurring, but it showed an incorrect balance, and its display of the latest transaction was as if the destination address was C and the change address was A.

So for some reason, Copay did not detect that address C was a change address, and treated A as the change address.

After I did Advanced => Wallet information => Scan addresses for funds, Copay resynced correctly and showed the correct transaction and the correct balance.

I have not observed this problem in the opposite direction, i.e., if I send using Copay, Mycelium always correctly shows the transaction and the new balance.

Using Copay 2.6.0 on Android 7.1.1 and also as a Chrome extension. Both the Android and the Chrome extension instances behave identically, i.e., both show either the incorrect or the correct display at the same time.

**Comment by matiu** [comment]
I am afraid this issue wont be fix in the near future. We support BIP32/44 to export/import seeds, but not to continuously use to different wallets with the same seed at the same time. That will imply checking forward derived addresses in the blockchain at BWS, something we are not doing now.

Closing the issue  for now, but I will update this issue if we ever implement it.
