### ISSUE TITLE
How to move copay data file to external drive or hidden volume?

### ISSUE THREAD

**Issue by themovement919** [bitpay/copay#5498]
does anyone know how to move the copay data file?

**Comment by JDonadio** [comment]
Why do you want to move the data file? The best way to move your wallets from a device to another, it's with export and import method.

**Comment by JDonadio** [comment]
Honestly I never tried and I'm not able to tell you if it's possible or not.

**Comment by matiu** [comment]
Related: https://github.com/bitpay/copay/issues/5503#issuecomment-274537201

Depending on the  plataform you are using using, NW.JS stored the file on different locations.

It is not a good idea to move the file for "portability". Just delete the wallet from Copay and the uninstall the app.  Keep the 12 words backup, that is all you need. When you need to access the wallet, import it from the 12 words backup.
