### ISSUE TITLE
Missing FAQ page?

### ISSUE THREAD

**Issue by aisamu** [bitpay/copay#5499]
Both the website and the github links to the FAQ point to:

     https://github.com/bitpay/copay/wiki/COPAY---FAQ

That gets redirected to:

    https://github.com/bitpay/copay

But I couldn't find a FAQ section on the Readme... perhaps someone moved it?

**Comment by JDonadio** [comment]
Seems like `wiki` was removed. Let us check it and we'll update you soon

**Comment by JDonadio** [comment]
Wiki is back 😉
