### ISSUE TITLE
Versioning and code collaboration on Copay based wallet

### ISSUE THREAD

**Issue by xelawafs** [bitpay/copay#5500]
I have a couple of questions around customizing the Copay code base for custom wallets:

* What sections/files should I look at (edit/build) for customizing Copay for a custom wallet?
* Building up on that, to what extent can I customize Copay code without breaking my copy for upgrades with future releases?
* In the case of collaborating on a single code-base with other developers, what set of files should we commit/share for version control? Put into consideration that we might be on different development environments eg Mac and Ubuntu.

**Comment by JDonadio** [comment]
Basically:

> What sections/files should I look at (edit/build) for customizing Copay for a custom wallet?

* `src/js`: you'll find controllers, directives, services, etc.
* `src/sass`: you'll find all scss files.

> Building up on that, to what extent can I customize Copay code without breaking my copy for upgrades with future releases?

I'm not sure to understand this. If you build your own (and customized) version of Copay you will not be able to update it from stores.

> In the case of collaborating on a single code-base with other developers, what set of files should we commit/share for version control? Put into consideration that we might be on different development environments eg Mac and Ubuntu.

All the ignored files and information are available on `.gitIgnore` file.

**Comment by xelawafs** [comment]
Do I ever need to look at or change anything in the the www folder?

I guess by customize I mean to **extend** Copay core sort of like adding plugins to it without altering the base code.

**Comment by JDonadio** [comment]
You can look the `www` folder just to make sure that you build is correct.

**Comment by JDonadio** [comment]
> I guess by customize I mean to extend Copay core sort of like adding plugins to it without altering the base code.

If you install a new plugin you must change some lines in the base code in order to use it.

**Comment by matiu** [comment]
Closing this issue, since it is responded already.

**Comment by xelawafs** [comment]
@JDonadio thanks. This was very helpful!
