### ISSUE TITLE
How to paste bitcoin address 

### ISSUE THREAD

**Issue by WToddR** [bitpay/copay#5502]
I know how to copy paste into an address bar, but the copay wallet will not allow me to paste a copied address. I have been having to do it by typing it all out and that's getting really old fast. Surely there is a way to copy paste a bitcoin address into copay. What do I need to do to get copay to allow me to paste a copied bitcoin address into it so I can send bitcoin? What am I doing wrong?

**Comment by JDonadio** [comment]
You are using Copay or BitPay App ? And what platform? Some screenshots would be great in this case.

**Comment by tabacitu** [comment]
Hi guys,

I also have this issue on CoPay for iOS, version 3.8.2. I click on a bitcoin address in my wallet, a notification says the address is copied to my clipboard, but when I try to paste it (anywhere) it looks like that hasn’t happened. Nothing gets pasted. It forces me to manually type the hash, which, you know, sucks :-)

Can we reopen and revisit this issue please?

Cheers!

**Comment by JDonadio** [comment]
Sure, can you please tell us what version of iOS are you running?

**Comment by ealtamir** [comment]
I'm having the exact same problem. I'm using iOS's 3.9.1 version commit 6277d1d. My iphone's version is 11.1.1. This problem is a pretty big deal because it makes transacting more cumbersome than it should be. Otherwise the app is great, so thanks for the hard work!

**Comment by wskinner** [comment]
I have this problem too. iOS 11.2.2 on iPhone 8. Copay 3.14.0 commit 66f11ba
