### ISSUE TITLE
[i18n missing] Receiving & Sending

### ISSUE THREAD

**Issue by Kirvx** [bitpay/copay#5507]
![3622_resultat](https://cloud.githubusercontent.com/assets/6627786/22210487/4abea50c-e18a-11e6-9d47-16d8537fc089.jpg)
![1233_resultat](https://cloud.githubusercontent.com/assets/6627786/22210486/4abd2948-e18a-11e6-85a9-9c1bcccf19eb.jpg)

**Comment by JDonadio** [comment]
Android, BitPay 1.3.0?

I'm changing to French language without problem.

**Comment by JDonadio** [comment]
Ok, I could reproduce it. Thanks!
