### ISSUE TITLE
Insufficient funds for fee

### ISSUE THREAD

**Issue by dhenderhan** [bitpay/copay#5511]
I am currently trying to send .082 BTC (~$75 USD) and it says I have insufficient funds for fee?  I have .102349 BTC (~$94.08 currently).  I tried it with the fee set to super economy with the same result.  Do I not have enough BTC?  Is it typical for there to be an almost $20 fee to send $75?  If so, it doesn't seem worth it to mess with BTC!  What am I missing.  Using what was an original Copay wallet changed into Bitpay wallet (version 1.2.1).

**Comment by matiu** [comment]
It depends how big is your transaction, how many inputs you have.

Is it could be possible you have a ton of very small inputs that are now economical worthy to move?

**Comment by dhenderhan** [comment]
I guess I don't understand.  I'm just trying to send 0.083 BTC in one transaction.  Forgive my ignorance, not that savy on the lingo for BTC.

**Comment by matiu** [comment]
If you received the 0.083BTC in thousands of small transaction, your TX will have to have thousands of signatures, therefore it will be big. The fee depends on how big is the transaction in kbytes.

Is 0.083 all you have on the wallet? If  that is the case, you can try "send max" which will optimice the output amount to move only worthy inputs.

**Comment by dhenderhan** [comment]
I did receive most of my total balance in a ton of small transactions (mining income) but I have 0.102349 BTC as a balance.  How do I determine what the fee will be for a $75 transaction?  The mining doesn't seem like a good Idea (at least on a small scale) if I can't spend it when I earn it?

**Comment by matiu** [comment]
You can get an idea of you "usable" balance by trying to send all funds to other wallet.

1. create a new wallet in bitpay app
2. "send all" from your current wallet to your new wallet. This will let you know how much money is really usable. Be sure you have your fee see to super economical.

**Comment by dhenderhan** [comment]
Here's what I see.
![2017-01-23_1153](https://cloud.githubusercontent.com/assets/25305757/22218539/88fc33f0-e164-11e6-8fd2-5eb72b848201.png)

Then when I click okay, it says this:
![2017-01-23_1156](https://cloud.githubusercontent.com/assets/25305757/22218565/abdcbfde-e164-11e6-9ea7-4e414f3596df.png)

**Comment by 55dmb** [comment]
Why is this marked closed?! I’ve been dealing with this for a loooong time and it’s finally gotten me too frustrated. I’m swimming to literally anything else.

**Comment by gabrielbazan7** [comment]
hi @55dmb could you create a new issue with more details of what is happening to you. Thanks !

**Comment by growtechknow** [comment]
Obviously working as intended. Time to dump bitpay. They are holding our coins.
