### ISSUE TITLE
My Copay wallet can not be sent btc !!

### ISSUE THREAD

**Issue by cyakkun** [bitpay/copay#5512]
Hello,

My wallet looks like not working well.

I requested to send some btc to other address but COPAY wallet indicated blockchain problem.
I notice that some btc are stopping on the blockchain which I sent.

Please solve my problem

**Comment by JDonadio** [comment]
If you get an error before send funds, they are not broadcast. Could you please, in your case, provide us the txid of your transaction? Also, any screenshot would be great
