### ISSUE TITLE
Error connection to coinbase "The access token was revoked" 

### ISSUE THREAD

**Issue by mybitpay** [bitpay/copay#5513]
![revoked](https://cloud.githubusercontent.com/assets/25313357/22231952/48e88a5c-e19b-11e6-9478-a829107d04c5.JPG)
Hello i accidently removed my coinbase Third-Party Applications from coinbase settings. How do i connect my Bitpay app to work with coinbase again? I uninstalled the bitpay app and want start over but when i reinstall the bitpay app for windows desktop again it is still recognize the coinbase i connected before which is not recognize the coinbase has a Third-Party Applications since i removed it off coinbase settings Third-Party Applications. Again how can i connect coinbase again? again  i accidently removed my coinbase Third-Party Applications from coinbase settings.

Reply back

**Comment by mybitpay** [comment]
How long do I have to wait for a response back????

**Comment by matiu** [comment]
> Again how can i connect coinbase again? again i accidently removed my coinbase Third-Party Applications from coinbase settings.

Sorry for the inconveniences. This is not yet supported. 

Could you please try from other device? (just to check that when you uninstall the app, you had erased everything).

**Comment by mybitpay** [comment]
Not yet supported??? than why is it available to download on your site? Also yes i have removed everything. I used bitpay uninstall file. Again whenever i try to reinstall the bitpay app on my windows 10 desktop. it still shows old coinbase connected.  Ok will try install from my windows tablet see if it don't show up
