### ISSUE TITLE
missing transaction

### ISSUE THREAD

**Issue by fries123** [bitpay/copay#5515]
hi i have made a transaction on my copay wallet, the transactions coming up not found on the blockchain?
can you let me know what has happened as the address i sent btc to was correct i sent it yesterday i think there might be a mailfunction on the nokia app, 
kind rgerads

**Comment by matiu** [comment]
Could you share the transaction ID or the address you used to sent?

**Comment by fries123** [comment]
Hi sorry its just gone through 
Thank you though


-----Original Message-----
