### ISSUE TITLE
i have funds

### ISSUE THREAD

**Issue by franciekoehler** [bitpay/copay#5516]
I HAVE FUNDS ON MY WALLET.. BUT NOT SHOWING ON MY APPS. HOW CAN I GET OR RECOVER MY FUNDS HELP PLS.

1NcjKNRFwepYt5RMWGkhUw7DSwFa4U18NU

**Comment by JDonadio** [comment]
Can you be more specific?

**Comment by franciekoehler** [comment]
saying that i have zero 
![image](https://cloud.githubusercontent.com/assets/25323648/22249809/73bfc472-e27f-11e6-88b2-831951d2bafd.png)

but someone send me 4btc in one of my past btc address that link to my copay which is 
1NcjKNRFwepYt5RMWGkhUw7DSwFa4U18NU . but when i check it. the funds in there.

**Comment by JDonadio** [comment]
Do you have enabled "Use unconfirmed funds" options from settings?

**Comment by franciekoehler** [comment]
its disable.. i now enable it. but still not showing.

**Comment by JDonadio** [comment]
Give us a moment to check the address and update you

**Comment by franciekoehler** [comment]
![image](https://cloud.githubusercontent.com/assets/25323648/22250226/221213a8-e281-11e6-978d-526fc1bc452f.png)
![image](https://cloud.githubusercontent.com/assets/25323648/22250250/309d3f06-e281-11e6-980a-db2f76020312.png)
![image](https://cloud.githubusercontent.com/assets/25323648/22250265/3e18455e-e281-11e6-800d-38085819a7fd.png)

ITS BELONG TO MY COPAY BUT THE BALANCE OF THE ADDRESS IS NOT SHOWING

**Comment by JDonadio** [comment]
Can you try this:

Go to preferences > advanced > wallet information > scan addresses for funds

**Comment by franciekoehler** [comment]
done but not work

**Comment by franciekoehler** [comment]
HELP PLS

**Comment by franciekoehler** [comment]
I HAVE MONEY IN MY ACCOUNT

**Comment by matiu** [comment]
Please see:

https://blockr.io/address/info/1NcjKNRFwepYt5RMWGkhUw7DSwFa4U18NU
or
https://insight.bitpay.com/address/1NcjKNRFwepYt5RMWGkhUw7DSwFa4U18NU

The address balance is still 0.

There are 2 incoming transactions since yesterday, but they are still unconfirmed, and some nodes seem to reject them. Fee for does transactions seems very low, so you will have to wait for them to be confirmed.
