### ISSUE TITLE
How does Copay avoid Double-spending? 

### ISSUE THREAD

**Issue by rakeshgn31** [bitpay/copay#5525]
How does Copay avoid Double-spending? 
Is it purely based on the transaction fees and risk factor or is there any way that Bitpay is using?
Because, When I transfer from one wallet to another (2 different phones), I immediately get credit into the second wallet though the status remains unconfirmed. How does that happen?

**Comment by dabura667** [comment]
No wallet can avoid transaction replacement of unconfirmed funds.

If you could give an example of a wallet that does I would love to use it.

**Comment by rakeshgn31** [comment]
@dabura667  I agree to your point. May be I should have rephrased my question as to how do Bitpay ensure strong guarantees against double spending? Or what makes it more trustable than other apps out in the market?  Is there some specific thing is what Im interested in. Please let know if you have some more details. Thanks!
