### ISSUE TITLE
Bad recognition of QR codes (still a problem)

### ISSUE THREAD

**Issue by jeroenvanagt** [bitpay/copay#5533]
Related to issue #5281

Copay is unable to read small QR codes (where other apps like Neoreader have no problem)

Here is a screenshot with a sample QR code which Copay has difficulty reading
https://postimg.org/image/xvp2kb8h9/

**Comment by jeroenvanagt** [comment]
Are you able to reproduce the problem? 

Did you check the Neoreader app on iOS? This app can scan the QR code from much bugger distance, easier and under different angels. It would be great if Copay can have the QR code reading performance.

**Comment by gabrielbazan7** [comment]
Copay can read small QR codes. Is another issue here. We will try to fix it.

**Comment by bitjson** [comment]
The new scanning is leaps and bounds better, but we might want to consider the zoom feature to improve further: https://github.com/bitpay/cordova-plugin-qrscanner/issues/59

**Comment by gabrielbazan7** [comment]
@jeroenvanagt should be fixed in the next BitPay app version. And also in the next Copay version. Thanks a lot.

**Comment by jeroenvanagt** [comment]
Just tested scanning small QR code with the new Copay App on iOS (v3.0.6) and it works great. Perfect!
