### ISSUE TITLE
Prevent pairing attempts for unactivated BitPay Cards 

### ISSUE THREAD

**Issue by jameswalpole** [bitpay/copay#5540]
Not sure if this is something we can do on the app side (as opposed to website side) but we need some way of making sure that people don't try to pair unactivated BitPay Cards to the BitPay wallet.

**Comment by ajp8164** [comment]
The server needs to not send inactivated to the wallet.  No way to detect this in the wallet.

**Comment by Monicasexy** [comment]
agree
