### ISSUE TITLE
delete my account

### ISSUE THREAD

**Issue by ghost** [bitpay/copay#5545]
magnumP1

thanks

**Comment by dabura667** [comment]
That's not how this wallet works...

**Comment by magnumP1** [comment]
cant i remove my account?` i had no problem making it

**Comment by magnumP1** [comment]
No installation directions in the software package
Account registration permanent

Sorry, not further confidence

**Comment by dabura667** [comment]
> Account registration permanent

What do you mean "account"?

Your account is a random number between 1 and 2^128 - 1 which never gets sent to the server.

**Comment by magnumP1** [comment]
http://oi63.tinypic.com/2ika8mp.jpg

Well, strangely github seem to support registration

**Comment by dabura667** [comment]
your link is broken...

I still have no clue what you're referring to when you say "account"...

github user registration has nothing to do with Copay...

I am still very confused, but if you're out, then good bye, I guess.
