### ISSUE TITLE
v1.3.1: Date Ordering/Assignment for BitPay Card Top-Ups is Inaccurate 

### ISSUE THREAD

**Issue by jameswalpole** [bitpay/copay#5546]
Just made a top-up to my BitPay Card for $52, but the record of transactions shows it as having processed a day ago at a completely different time (9:39 AM vs. actual load time of 2:38 PM). 

![bitpay app card transaction](https://cloud.githubusercontent.com/assets/9257396/22407271/332d2570-e631-11e6-86c3-e12bb013706f.png)

**Comment by JDonadio** [comment]
Should be ok now. If the error persist please reopen the issue.
