### ISSUE TITLE
Spending password issue

### ISSUE THREAD

**Issue by slinky2** [bitpay/copay#5547]
I never set up a spending password and I can no longer find my mnemonic for this specific wallet.  Is there a default password, assuming I never set one up, there should not a a password for spending. Without the password my bitcoin is essentially frozen without a way to transfer.  I have another wallet I can use, but I cannot transfer the bitcoin to it. Thank you.

**Comment by JDonadio** [comment]
Do you have the backup?

**Comment by slinky2** [comment]
Unfortunately not for this wallet, otherwise I would delete and reset. My issue is not understanding why it requests a sending password when I never set one. It only makes sense that there would be no password associated at this point. Understandably,  it is my duty to have the recovery phrase, but it is not my duty to have a password that was never set. This concerns me bc I can no longer access my Bitcoin.

**Comment by dabura667** [comment]
Have you ever left your phone unattended? Unlocked?

My son messed with my unlocked phone and managed to add a spending password to a wallet on Copay once... Almost as if he did it on purpose.

Luckily, I kept my phrase backups safe, so no harm was done.

**Comment by JDonadio** [comment]
Unfortunately without a backup there is nothing we can do.

**Comment by slinky2** [comment]
No, never.  I am the only person with access to my device and no password was set up. If I could send to my other wallet or even sell the bitcoin I would be fine with deleting and using my other wallet that has no spending password associated. Really do not understand the password request since there was never one set.

**Comment by dabura667** [comment]
If you really think Copay is lying to you:

1. Export the wallet. You will need to set a password, "a" is fine.
2. use sjcl to decrypt the wallet using the "a" password you just set.
3. If you see your phrase in there, you didn't have a password set, if you don't see it, then you have encrypted the phrase and need the password.

https://bitwiseshiftleft.github.io/sjcl/demo/

Paste the exported wallet in Ciphertext, and type "a" in the password box to see the raw wallet data.

**Comment by slinky2** [comment]
I know the wallets I have are separate identities, but aren't they connected in some way? 

And as far as my password, I am saying that I haven't set one up. I will see if that works.

**Comment by slinky2** [comment]
Also, my wallet in question has an option to delete recovery phrase. Obviously the mnemonic phrase is still in existence. Is there any way of showing/recovering the mnemonic phrase? 

I don't know how to export my wallet, as I'm not brushed up on all the tech points. I'm just a simple man with enough knowledge to know that there are doors that have been opened and not yet closed so to speak.

**Comment by slinky2** [comment]
IMG_4120.PNG

**Comment by slinky2** [comment]
It will not allow me to export, as it asks for spending password (which I did not set to begin with)

**Comment by slinky2** [comment]
Ok from what I'm seeing between my two wallets is that the one with the "phantom" spending password, the password is needed to allow and access any spending as well as the mnemonic recovery phrase off of my device for that wallet. The other wallet, I have no issues with a password when transferring bitcoin and I have no issue viewing my recovery phrase. In all honesty it looks like a glitch in the system and it has cost me frozen bitcoin that I cannot access in that wallet. I did not delete my recovery phrase on either of my wallets, yet I can only access to RP on the wallet that doesn't have a spending password. 
From reading several threads on this site, I'm not the only person on here with this "phantom" spending password problem. Seems there should be an easy solution to this problem.

**Comment by JDonadio** [comment]
@slinky2 to void all of this kind of scenarios, we strongly recommend on BitPay App (mandatory for Copay) write the RP down, so you can recover the access to your funds.

If the Private Key is encrypted, you will not be able to:

* Spend money
* Access to the RP
* Access to backup flow
* Export wallet

**Comment by slinky2** [comment]
To avoid these scenarios, I have the option to have the RP stored on my phone with a suggestion to write it down. I haven't lost nor deleted my RP, and I have now a password that I did not apply to my wallet that prevents access to any option other than adding Bitcoin to my wallet. This seems odd that the app has this issue with no way to resolve. I could see that there would be an issue if I made a password or if I deleted my RP, but it's still there, locked by the phantom "spending" password. Funny that I'm not spending, yet it will not allow me to access the RP without a "spending password". 
Sorry if this comes off rude or matter of fact, but this is an issue that needs to be resolved and is an error with the app, it seems. And there are many other threads that would suggest the same.

**Comment by slinky2** [comment]
And I do appreciate all help that has been suggested.

**Comment by fademar** [comment]
Hello,
I am experiencing the same problem. I didn't set up a "spending password" and now the app keeps asking for it for everything, even for the back up. Nobody has access to my phone but me. 
Thanks for the help.

**Comment by fademar** [comment]
Ok I am answering for myself for those who experience the same problem. I wrote down my secret phrase on a piece of paper as suggested during the set up of Copay. So I just deleted the wallet and created a new one with that phrase. This time, the app asked me if I wanted to set up a spending password. Don't know why it didn't ask for it the first time.

**Comment by AgentZ86** [comment]
Same for me. Installed bitpay for first time on windows desktop. It asked for email, then took me to the steps up to the point where it asked to create a password.  I never had any passphrase or anything just directly to the screen to create password I skipped it as noted and as the screen says I could set this up later. 
I transferred some bitcoin to bitpay and then tried to buy something and it still says setup backup and asks for password. It never EVER showed any passphrases or anything just directly to the password screens. Now I have bitcoin stuck in limbo that can't be used without spend password which was never created.

**Comment by rnwilson** [comment]
The same thing happened to me, I was never prompted to set a password and after a few weeks I went to send BTC and was asked for encrypted password. I struggled with it for hours going over many variations of the password formula I would have set if I were prompted with no luck. I luckily found the pass phrase to import the wallet once it was deleted and was asked to setup encrypted password. I am surprised I kept the pass phrase usually they get written down and lost somewhere on my desk forever.

**Comment by darakaye** [comment]
Help....I have the same "Phantom Password" issue.  I downloaded the bitpay app and sent btc to the wallet.  I am now trying to pay an invoice and cannot because its asking for a password I never set up.  I have spent hours with numerous configurations of passwords....but I dont make these mistakes.  I know my passwords.  This is a glitch.   Did anyone solve the above guys issue?

**Comment by BGalliotti** [comment]
Hello @darakaye 
Thanks for reaching out to us.

Please refer to [#5497](https://github.com/bitpay/copay/issues/5497#issuecomment-435405463)

Please let us know if you have any additional questions.
Kind regards.

**Comment by richardsuns** [comment]
@slinky2 
@darakaye 
@rnwilson 
@AgentZ86 
@fademar 
I can crack password for bitpay wallet spending pin if you have the text backup of your wallet.
most of the password are the result of letting the kids use the phone.
I can crack the password in 50% of the cases, if you need help send me message.
telegram username: @walletrecover
