### ISSUE TITLE
Disable spending password

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#5548]
Spending password should be disabled if the backup flow was not completed.

**Comment by dabura667** [comment]
Or require a spending password upon wallet creation and tell the user they may remove the password after writing down their backup by going into the menu.

This way it will make them keenly aware of having set a password for spending.

A side note: How can someone get money on to Copay if the backup hasn't been written down? Copay doesn't show any addresses without writing down the backup.

**Comment by JDonadio** [comment]
> Or require a spending password upon wallet creation and tell the user they may remove the password after writing down their backup by going into the menu.

Could be another option. Personally I prefer disable 🤓 

> A side note: How can someone get money on to Copay if the backup hasn't been written down? Copay doesn't show any addresses without writing down the backup.

It's mandatory for Copay but not for BitPay app. There was, are, and surely will be a lot of discussion about if this is correct or not, you probably knows this story. Honestly I don't have the lastest directive or ticket to tell you explicitly why we made it in this way.

**Comment by sadpandas** [comment]
I feel really dumb but this is how I lost $150.00
My Lastpass note didn't save so my generated password was lost
