### ISSUE TITLE
Does anyone know definitivelywherethe windows mobile version of Copay saves its private keys?

### ISSUE THREAD

**Issue by blouisdiddy** [bitpay/copay#5553]
Quite simply: 

do the wallet private keys get stored on the SD card if the copay app is installed on the sdcard? Or does it always store that state on the phone memory?

thanks,

B

PS: specifically this is a question about the windows 10 mobile version.

**Comment by JDonadio** [comment]
Sorry for the delayed reply. For mobile versions Copay store all their data in the device memory, not in the SD card.

**Comment by blouisdiddy** [comment]
Thanks!

Sent from Mail for Windows 10
