### ISSUE TITLE
Add copayer to existing shared wallet?

### ISSUE THREAD

**Issue by winneon** [bitpay/copay#5556]
Hello,

I couldn't find this mentioned anywhere on the issues tracker. Is it currently possible, or will it be possible in the future to add a copayer to an existing shared wallet? Say I have a shared 1-2 wallet that is already in use by 2 people. Is it possible to add a 3rd person to that shared wallet, making it a 1-3 wallet?

**Comment by JDonadio** [comment]
No, when you create a shared wallet you must specify the total signs and copayers in order to get the invitation code, once completed the wallet is created and that code is not longer useful.

**Comment by winneon** [comment]
Thank you for clearing that up!

**Comment by JDonadio** [comment]
And if you try to use the invite code with an extra copayer well see something like this:

<img width="395" alt="copay_-_copay_bitcoin_wallet" src="https://cloud.githubusercontent.com/assets/13851807/22522267/bbc73154-e899-11e6-8f7d-4fdc3efba3b6.png">

Glad to help 😉
