### ISSUE TITLE
Transferring funds issue! Bitpay Wallet doesn't show up!

### ISSUE THREAD

**Issue by BitPayUser** [bitpay/copay#5561]
I am using bitpay app and i had some issue with the wallet while doing transfers.

I created 5 wallets inside my bitpay app. Eg: Wallet 1, Wallet 2, Wallet 3, Wallet 4, Wallet 5.

I use the Wallet 1 as my main checking account and use the other wallets as savings accounts.

I had no issue transferring money into these wallets from external accounts.

However when i try to transfer money from Wallet 1 to more than 2 wallets within my bitpay app, the app won’t display Wallet 1 anymore in the “Send from” list. 

Use the following steps to replicate:
1. Click on Send
2. From the “Transfer to Wallet” section, select Wallet 2.
3. Enter the amount in USD
4. In the next screen select wallet 1 from “Send From” list. 

Repeat the above process again to send money from Wallet 1 to Wallet 3.

After 2 transactions, the app won’t display Wallet 1 anymore in the “Send From” list.

Not sure if there is a restriction you have set from within the wallet to not show up after 2 transactions?

Also it doesn't let me send money to my bitpay card since i did 2 transactions. My wallet doesn't show up in the list of wallets to "Send From".

**Comment by JDonadio** [comment]
The wallet list only shows the "available" wallets to make the payment in process, let's say:

W1 > 1 BTC
W2,W3,W4,W5 > 10 BTC

If I want to send 1 BTC > all wallets will be listed
If I want to send 1+ BTC > only the wallets which amount is enough to make the payment will be listed, in this case W2,W3,W4,W5.

**Comment by BitPayUser** [comment]
I understand what you are saying. But i did the transactions in USD and the amounts were sufficient enough. If they were insufficient, i would get insufficient funds message.

**Comment by JDonadio** [comment]
Did you get the "Use unconfirmed funds" options enabled? See the advanced settings. Also, can you post some screenshot about your problem? thx

**Comment by BitPayUser** [comment]
No, i do not have “Use unconfirmed funds” enabled. Its disabled right now. Do i need to enable it?

I was able to recreate this problem again and again. Just after two transactions, it is not letting me do another transactions until about an hour. It seems like its waiting for the funds to be confirmed before letting me do a third one.

Not sure what screenshot you need. Just follow the procedures i mentioned in my issue and you can recreate it yourself. The wallet doesn’t appear in the list of wallets if you do two transactions and try to do a third one.

**Comment by JDonadio** [comment]
The only 2 reasons why you cannot see a wallet in the list are:

1 Different network (obviously)
2 Insufficient funds

From 2: 

If you have unconfirmed funds and you are not including they, the wallet will not be listed up.

* Use unconfirmed funds **disabled**

<img width="411" alt="copay_-_copay_bitcoin_wallet" src="https://cloud.githubusercontent.com/assets/13851807/22594887/caea53da-ea03-11e6-9d97-6f119c2356ba.png">

* Use unconfirmed funds **enabled**

<img width="411" alt="copay_-_copay_bitcoin_wallet" src="https://cloud.githubusercontent.com/assets/13851807/22594876/bdd3e60c-ea03-11e6-8485-1df5fe372b72.png">
