### ISSUE TITLE
Haven't received Amazon GC even though payment/BTC has been taken out

### ISSUE THREAD

**Issue by fragiledream** [bitpay/copay#5562]
I just purchased a $4 AGC and even though the money is taken out, I haven't received the code and in the Gift Card history, there are no transaction history of this transaction. I still have the transaction ID of the blockchain which is 737bbb5d40e4ca52335ca64060453003b6c4155e9715ac69edebff9d44207cb1

**Comment by JDonadio** [comment]
Can you please take a screenshot on your wallet details view?

**Comment by fragiledream** [comment]
Here are the screenshots: (I purchased 2 AGC, $437 + $4. I received the first one but not the second, even though I was charged for both.)

![First](https://i.imgur.com/0TdfMrX.jpg)
![Second](https://i.imgur.com/2aeoDVk.jpg)
![Third](https://i.imgur.com/Ftl5Z0P.jpg)

**Comment by bitjson** [comment]
Hey @fragiledream – sorry I just saw this. GitHub issues are primarily monitored by our development team, so sometime issues that haven't been tracked down to a software bug can fall through the cracks.

Would you mind emailing us at support@bitpay.com? Our support team's average response time there is less than an hour, and even complex issues usually get solved in less than a day. I'll keep an eye out for your email, and we'll be sure to figure out what happened.

Thanks!

**Comment by bitjson** [comment]
I'm going to close this issue here for now (it may be a backend or service provider issue too). I'll reopen it and post technical details if we determine there was a bug with the app.

If anyone else experiences a similar issue, please feel free to leave a comment here, and I'll reopen too.

**Comment by fragiledream** [comment]
I have just emailed you guys. Please do check and resolve this matter asap. Thanks.
