### ISSUE TITLE
Sell bitcoin for amazon.es (spain) gift cards

### ISSUE THREAD

**Issue by encelebrado** [bitpay/copay#5565]
Hi, I heard that with copay app wallet it is possible to buy amazon.com gift cards with bitcoin. My question is... it is possible, taking into account that i am from Spain (euro) to buy amazon.es gift cards?

Thanks

**Comment by JDonadio** [comment]
Yes, it's possible. Actually I purchased one for 1k USD (from Argentina)

**Comment by JDonadio** [comment]
Sorry, it's only available in **Amazon.com**
