### ISSUE TITLE
Send funds from specific address in HD series

### ISSUE THREAD

**Issue by 1blockologist** [bitpay/copay#5568]
There is a feature in electrum that allows me to send bitcoin from specific addresses within my HD series. As well as label specific addresses in the HD series.

This is useful to help avoid input mixing that destroys anonymity within a wallet. My use case this time is more so for accounting, and I do not want inputs inadvertently mixed between addresses. Or, I don't want the Bitpay client to try to form a transaction by adding up available bitcoin across multiple addresses.

ie. I specify I want to send 5 bitcoin

1address has 2 bitcoin in it
2address has .5 bitcoin in it
3address has 5 bitcoin in it

Many client's default behavior is to take all the bitcoin in 1address, 2address and the remainder from 3address. 

I would like the behavior to form a transaction only using the funds available in 3address.

In Bitpay, I do not see the option to specify which address to 'send from' within my HD series.

Is there a way to do this in Bitpay currently?

**Comment by dabura667** [comment]
No there is not. Currently there are no plans that I am aware of to include such a feature.

**Comment by 1blockologist** [comment]
Can you elevate that? I think it increases the utility on the bitcoin network despite not being a large use case at this point in time.

This wallet is pretty user friendly compared to other multisig capable wallets. And if it could form transactions from a specific address within the HD series that would set it apart more

**Comment by 1blockologist** [comment]
Glad to see this was tagged for a feature request, I think you could look at how Electrum forms transactions within its own wallet for inspiration on how to implement this. They allow users to see 20 unused addresses, used addresses and change addresses. And select any one of them individual for sending a variable amount of bitcoin from.

**Comment by matiu** [comment]
There are no plans to implement this feature since it kind of out-of-scope of the idea of Copay. Adding input selections could complicate the UI and generate confusion to many users.
