### ISSUE TITLE
Using Testnet with Copay-Trezor hardware wallet?

### ISSUE THREAD

**Issue by rakeshgn31** [bitpay/copay#5569]
Hi, Is there a way that I can use testnet for testing my Copay-Trezor hardware wallet integration? Testnet is supported in normal wallet while not in case of Hardware wallet with Copay (at least in the options).

**Comment by JDonadio** [comment]
Nope, Copay doesn't support Testnet for hardware wallets.

**Comment by rakeshgn31** [comment]
@JDonadio It is very unfortunate that there is no other option.
