### ISSUE TITLE
Priority fee > 0.009 BTC / kB

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#5576]
nBlock 1 is returning > 0.009 BTC / kB

nBlock 2 is returning ~ 0.0013 BTC / kB

For the recent past 1 has been returning -1 and protecting users from abnormal fee estimates...

This is more an issue for insight-api and ultimately bitcoin/bitcoin.

I just wanted to leave a record of the fact that users on Priority will currently be paying fees that most fee estimation sites claim are way too high than necessary.

**Comment by matiu** [comment]
thanks!

IIRC, we are no longer using nblock=1 for priority, but 2. we will check.

**Comment by dabura667** [comment]
oops I was on an old version, it seems.

my iPhone says Priority is more reasonable

**Comment by JDonadio** [comment]
Reopen if the error remains.
