### ISSUE TITLE
problem with copay App

### ISSUE THREAD

**Issue by fredinisan7** [bitpay/copay#5589]
![screen shot 2017-02-08 at 3 19 28 pm](https://cloud.githubusercontent.com/assets/25649579/22762033/1b2dc176-ee12-11e6-9830-c981d0488b5a.png)
I am using your app on IOS and few minutes ago the app giving me errors at wallet service: Error querying the block 
do you know why?

**Comment by needykid** [comment]
im experiencing the same problem

**Comment by bakura316** [comment]
I just had the same problem a hour ago, i sent out one transaction then it started doing this.

**Comment by fredinisan7** [comment]
i had the same problem I send money at 2:53 PM then its start doing the errors

**Comment by matiu** [comment]
we are working to solve this, thanks. In the mean time, if you need access you your funds inmediatly you can use https://bitpay.github.io/copay-recovery/

**Comment by fredinisan7** [comment]
thank you

**Comment by matiu** [comment]
We are up again. See https://www.reddit.com/r/Bitcoin/comments/5swatp/bitpaycopay_wallet_issues_api_down/ddidixf/
