### ISSUE TITLE
"Error at Wallet Service: Insight Error"

### ISSUE THREAD

**Issue by mkassel22** [bitpay/copay#5590]
Why is this happening?

**Comment by matiu** [comment]
please see https://github.com/bitpay/copay/issues/5589

**Comment by mkassel22** [comment]
Hi Matias - When I now login to CoPay it shows a 0 balance even though I transferred funds from coinbase. Coinbase is showing the transaction as "complete."

**Comment by JDonadio** [comment]
@mkassel22 please try with precerences > advanced > wallet info > scan addresses for funds

**Comment by event15** [comment]
It is still not working. I had an error: "WALLET_BUSY: Wallet is busy, try later".
When I try to ping BWS api page, i had 404 error. What's happening?
