### ISSUE TITLE
Error In wallet - I have lost 6 Days of transactions

### ISSUE THREAD

**Issue by lugeflu** [bitpay/copay#5594]
Hello i have a big trouble, i have lost 1,5 Btc Balance in Copay. 
There are 6 days in lost transactions. Please Help me.

1Js4Q5LVqpR1eFB9G6iYpbNFdzECuLSAfd that´s my current  Wallet adress  
![16586420_10158577504195179_473176627_o](https://cloud.githubusercontent.com/assets/25650616/22763864/ac38c5d2-ee3d-11e6-8f2f-7f75bcba23e7.png) Here´s the problem that appeared.

![image](https://cloud.githubusercontent.com/assets/25650616/22763893/c0a985ec-ee3d-11e6-8e67-52e7082b4e36.png)

here is my new balance in pc

now is 346 $ balance is going up... well waiting for an answer

**Comment by lugeflu** [comment]
error "could not update wallet: error querying the blokchain appeared again"

Now Balance is 0,309047 BTC, Still missing 1.2xxxxx BTC

**Comment by JDonadio** [comment]
Please see https://github.com/bitpay/copay/issues/5595

**Comment by JDonadio** [comment]
Please feel free to re-open if the problem remains.

**Comment by lugeflu** [comment]
Thanks for your services ! It's ok now
