### ISSUE TITLE
Bitcoin Transaction missing from copay

### ISSUE THREAD

**Issue by joecheat** [bitpay/copay#5595]
Transaction missing from copay wallet

**Comment by JDonadio** [comment]
We had a connection problem, can you try with:

Copay > Preferences > advanced > wallet info > scan addresses for funds
BitPay > Receive > addresses view > scan addresses for funds

**Comment by demt78** [comment]
JDonadio I did this: "Copay > Preferences > advanced > wallet info > scan addresses for funds". But the funds still without appear at my wallet.
