### ISSUE TITLE
On settings view with no way out

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#5597]
![img_5543](https://cloud.githubusercontent.com/assets/1063765/22767545/f813955c-ee49-11e6-9962-f6b6e4ab9eed.PNG)

Opened app, went to settings>about>session log>back and not tab menu.

Update: tab menu appeared after resuming app from background.  Still an issue though ;-)

Update2: backgrounding the app and resuming once again and the tab menu is gone again.  Can't get it back now.

**Comment by JDonadio** [comment]
v1.3.6 right?

**Comment by ajp8164** [comment]
Yes, 1.3.6.
---
Andy Phillipson
Director of Engineering Services, BitPay, Inc.
844A CCA5 F277 30C0 E86F  9799 0CEE 502F 2484 0854

**Comment by JDonadio** [comment]
I was able to reproduce in v1.3.6 - Android in the related issue above. I'm not sure why it's happening in your case but definitely has to be the redrawing of the view.

**Comment by JDonadio** [comment]
Waiting for https://github.com/bitpay/copay/pull/5864

**Comment by gabrielbazan7** [comment]
Is this issue solve in the recent version ?

**Comment by JDonadio** [comment]
I think no. Probably the same problem as https://github.com/bitpay/copay/issues/6482#issuecomment-318717623

**Comment by gabrielbazan7** [comment]
Ok. Lets close this one in order to #6482
