### ISSUE TITLE
Privacy view - android

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#5603]
Related https://github.com/bitpay/copay/pull/5560

This plugin prevent to android users take screenshot in the app. IMO it's a good security feature, but  many times we need to take screen prints, mostly for support cases. Should we disable it for android?

<img width="436" alt="screenshot_2017-02-08-11-08-31_png__1080x1920_" src="https://cloud.githubusercontent.com/assets/13851807/22799611/37de100e-eee5-11e6-92f9-aa54431ad125.png">

**Comment by cmgustavo** [comment]
After use the wallet a bit with this plugin activated (iOS), I realized that it doesn't work as expected. When closing the app, it has a delay and shows the splash before close. This is very annoying. I think that we should roll-back and remove this plugin.
