### ISSUE TITLE
Merchant claims insufficient funds, must retrieve on my end...HELP Please 

### ISSUE THREAD

**Issue by drbillinns** [bitpay/copay#5605]
Sent bits to merchant address, over 600 confirmations. Sent additional very minor amount within "timeout" period. The two add up to more than the amt owed by me.
They claim their cryptocurrency handler rejected the payment(s) due to insufficient funds to cover my order...incorrect.
Copay does not provide a means for me to retrieve my funds; the merchant seems unwilling or unable to cause a refund to be issued.
Any help, advise, consoling remarks will be appreciated.
This is not an insignificant amount of funds to me. Thanks in advance.
fagan.brla@gmail.com

**Comment by dabura667** [comment]
Name of the merchant?
Name of the payment processor?

Have you contacted support for the payment processing company?

**Comment by drbillinns** [comment]
Yes, that is where the trouble lies. The people I have been dealing with at the merchant do not seem to know the name of their processing company or how to initiate a refund. This morning I am attempting to work up their chain to get to someone who has some knowledge.  "Customer Service" is their first priority, ha, perhaps training their help might be first.
Thank you for your response, I'll post any progress.

**Comment by dabura667** [comment]
Usually a 3rd party payment processor is very obvious.

On the merchant site it sends you to a site like bitpay.com or coinbase.com, and that site shows you a QR code.

Tell us the name of the site and we can tell you what payment processor they use.

**Comment by drbillinns** [comment]
Ha, great information. A few minutes ago, the merchant cut and pasted information from their processor.
I signed on to the site, Coinpayments.com, got a link for a refund, put in an address for my wallet, five min later I had my funds back.
Simply a case of the customer service person not knowing what BTC exchange is. I am just learning myself, but am not in a "service" position.  THANK YOU for your time and knowledge, I'm grateful and pleased to have my funds rescued.

**Comment by JDonadio** [comment]
Excellent support @dabura667 great job!
