### ISSUE TITLE
[Android - BitPay 1.3.6] Text overlay

### ISSUE THREAD

**Issue by Kirvx** [bitpay/copay#5609]
I can't take screenshot on android - privacy mode ( ͡° ͜ʖ ͡°)
Here is the photoshop version on windows:

![sans titre2](https://cloud.githubusercontent.com/assets/6627786/22854711/f0a0b08e-f074-11e6-97f4-827c5ee24529.jpg)

**Comment by JDonadio** [comment]
About the privacy https://github.com/bitpay/copay/issues/5603

Good catch, let me fix it in a bit. Thank you @Kirvx !

**Comment by JDonadio** [comment]
@Kirvx can you please check if the PR works? ;)

**Comment by Kirvx** [comment]
I can't test the PR, I haven't the tools and skills to compile it on Android :worried:
