### ISSUE TITLE
Beginner Question

### ISSUE THREAD

**Issue by QLAnimal1920** [bitpay/copay#5610]
hello,

Sorry I know this will be a dumb question BUT if someone got a hold of My phone what prevents them from sending BTC from My account to theirs?I have found nothing on this topic and know it is very elementary

Thank You

**Comment by JDonadio** [comment]
Hi @QLAnimal1920, we have 2 security preferences before confirm a transaction.

1) Spending password: if you set the spending password your private key will be encrypted, so each time that you want to send funds a request password prompt will be shown.

2) Fingerprint: if your device support fingerprint and have android 6+ you can also enable this security and the request fingerprint prompt will be shown. **This option don't encrypt your private key**.

Note: If for some reason you won't set spending password or enable fingerprint request, maybe a multi-sig wallet would be a good option.

Hope this help.

**Comment by QLAnimal1920** [comment]
Ok so spending/Sending same password,Gotcha,Thank You
