### ISSUE TITLE
Desktop App remembers spending password

### ISSUE THREAD

**Issue by RobinTick** [bitpay/copay#5611]
I'm using the Copay v2.7.0 on Windows 10 Pro desktop.
I have a wallet with a spending password, and recently made the first transaction using this app, so I entered the spending password once.

Now to my shock, I went to make a second transaction and was asked for the spending password, but it was already filled in ! I just had to click "ok" to make the transaction.
The password was filled in with *********** so not readable, like a browser would do.

Even worse, I went to disable/change the spending password, and in that dialog box it was also prefilled, so I didn't have to know the spending password to disable it.

I'm not sure if it's a Windows 10 feature or the Copay app that is doing this but this is not good, how do I make the app NOT remember my spending password ?

**Comment by dabura667** [comment]
Windows 10 new feature...

:-/ not good.

Thanks for the report!

Just in case, do you have any password manager software that you are aware of that you have installed on your system? If you do please let us know.

**Comment by RobinTick** [comment]
I don't use anything like password managers or software that fills in text for me.
I've been looking through Windows's settings but the only autofill thing I could find was for IE11, I turned that off and deleted it's cache, but that had no effect on the Copay app.

**Comment by dabura667** [comment]
just out of curiosity... do you have any other browsers installed on your Windows 10 besides IE11?

**Comment by braddersbury** [comment]
Hello. This issue is also still happening on the Bitpay v3.6.2 desktop app. The spending password is autofilling and there is no way in Chrome of removing the autofilling.

**Comment by JDonadio** [comment]
@braddersbury for windows platform?

**Comment by braddersbury** [comment]
Hi there. On windows 7. Thanks
