### ISSUE TITLE
problems with the recovery phrase

### ISSUE THREAD

**Issue by gordoelgomez** [bitpay/copay#5613]
The program says that the recovery prhase isn't that i wrote

**Comment by JDonadio** [comment]
Hi there,

Some quick question:

Are you sure that the recovery phrase was written in the correct order? Did you add a password to your recovery phrase? Have you the QR code or text/file backup?

If you can attach any screenshot of the error that are you running would be great.

Please tell me if you need spanish assistance.

**Comment by gordoelgomez** [comment]
thanks for everything Javier, i can import it with bitpay for android!. It was a problem with the acentos in one word

**Comment by JDonadio** [comment]
Thanks for the update!
