### ISSUE TITLE
Add option to re-enable hidden balance with security

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#5616]
On iOS allow finger print.  All devices allow pin.  Optional feature and off as the default to retain current UX.

**Comment by JDonadio** [comment]
Probably covered by https://github.com/bitpay/copay/pull/5726

**Comment by ajp8164** [comment]
Doesn't look like it to me.  Would like to be able to unhide balance by entering pin and/or fingerprint. At the moment it's just press and hold to hide and show.
