### ISSUE TITLE
I can't get the wallets data from localStorage

### ISSUE THREAD

**Issue by cssxn** [bitpay/copay#5620]
I can't get the wallets data from localStorage

I'm trying to get wallet data.

I'm using MacOS when I inspect the App I saw nothing in localStorage

**Comment by dabura667** [comment]
It is not stored using localStorage.

**Comment by cssxn** [comment]
@dabura667 
I examined all of the files about **storageService** that I could find. 

I'm finding there just two way to store the data which are **fileStorage** and **localStorage**.

but, when I debug the **StorageService** code, I found this.

Line 9, in StorageService.js
```
    var shouldUseFileStorage = platformInfo.isCordova && !platformInfo.isWP;
    $log.debug('Using file storage:', shouldUseFileStorage);

    var storage = shouldUseFileStorage ? fileStorageService : localStorageService;
    $log.debug('Which storage:',storage); // this line was I added.
```



What's showed in my console
```
Using file storage: null
Which storage: {}
```

So, in that case, Obviously it will use **localStorageService**

I was running it on platform MacOS

**Comment by JDonadio** [comment]
Hi @cssxn, Copay use `FileStorage` only for `iOS and Android`, in any other case use `LocalStorage`.

**Comment by JDonadio** [comment]
Sorry for the delay, for OSX versions we are using `chrome-storage`. In order to see for example the profile, you must to use:

> chrome.storage.local.get('profile', function(v) {console.log(v)});

**Comment by cssxn** [comment]
@JDonadio 

Think you very much!  It's working! 👍

**Comment by JDonadio** [comment]
Glad to help! 😀

**Comment by cssxn** [comment]
@JDonadio  are you working for the Bitpay company?  I'm intend to upgrade copay to ionic2+ng2

do have any idea？

**Comment by JDonadio** [comment]
> @JDonadio are you working for the Bitpay company?
Yep
> I'm intend to upgrade copay to ionic2+ng2 do have any idea?
We are planing to upgrade to ionic/angular 2 soon 😉
