### ISSUE TITLE
Addresses with balance section lies

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#5628]
The "addresses with balance" section on the "wallet addresses" view does not list all the addresses with a balance.  Looking at the "all addresses" view shows many more addresses with a balance.

**Comment by JDonadio** [comment]
Both lists shows the latest 5 addresses (if exists). All addresses view list all of the unused and with balance addresses (concatenated). Maybe we need to add a counter on each header list? Something like (5/24), what do you think?

**Comment by ajp8164** [comment]
Addresses with balance section should either show all addresses with a balance or provide an explanation.  If there is an explanation that excludes some addresses then i think it’s useless.
---
Andy Phillipson
Director of Engineering Services, BitPay, Inc.
844A CCA5 F277 30C0 E86F  9799 0CEE 502F 2484 0854

**Comment by JDonadio** [comment]
If you are using a big wallet the loading time for all the addresses used or not may be considerably large. And if you are looking for just the latest addresses or so, the first pre-load view will be enough (probably mostly of cases).
The latest mockups for this feature are [here](https://github.com/bitpay/copay/issues/5020) and the counter for both sections are missing. IMHO that simple change will clarify a lot this confusing.
