### ISSUE TITLE
Error when exporting Ledger Public Key

### ISSUE THREAD

**Issue by scarar** [bitpay/copay#5629]
My first time doing this and I got an Error your Public Key is being used by another wallet. Is their a way to delete the public key. I believe when I was trying to get my co-signer to get the invite that the Copay app crashed and I had to start over. When I did it again this error showed. Is their a way to delete the key from the wallet and do the process over again?  Please email me with solution at: 
moonshiner660@yahoo.com

Thank you for your time and I hope their a solution for this issue.

**Comment by dabura667** [comment]
Use "Import Wallet" instead of "create wallet"

**Comment by JDonadio** [comment]
How it goes?

**Comment by scarar** [comment]
Still have issues with my Ledger wallet and the copay Chrome app. I signed up on Bitpay, but not sure how to tell from Multi-Sig wallet account and Non-Multi-Sig wallet account. 
 

    On Tuesday, February 28, 2017 11:14 AM, Javier Donadío <notifications@github.com> wrote:
 

 How it goes?—

**Comment by JDonadio** [comment]
Ledger only works with multi-sig Copay wallets. That's means that at least you have to create a 2-2 wallet. If you already create one and delete it, you must to change the account number only.
