### ISSUE TITLE
Deposit delay

### ISSUE THREAD

**Issue by demt78** [bitpay/copay#5638]
Hello, I need your assistance, due I have made a deposit to my copay wallet by the amount of 0.00860851 BTC, to the generated address 18ymz1frAuAB8PH66yP5uEC6zNUkGeAu6g

At this time de transaction have 68 confirmations, but I do not have the funds credited to my copay wallet. The funds was sent from my wallet at poloniex exchange.

There you have the tx hash of the operation 7bf39f986e40e85bf0eeb89434ac0dad0f1b09d64e59609f00c524ced3c989e4

Thank you for your help.

![copay 1](https://cloud.githubusercontent.com/assets/25928118/23165588/b4174872-f81b-11e6-89fb-bdd63346264e.png)

**Comment by dabura667** [comment]
Please see #5595

**Comment by demt78** [comment]
I did it, but it was unsuccesful, the funds still without appear. I have tried at the google chrome app and android app of copay, with the same results.

**Comment by JDonadio** [comment]
Sorry for the delay, we must to investigate this further in order to check your address and wallet status. We'll let you know the update soon.

**Comment by JDonadio** [comment]
Those funds has been already spent.
