### ISSUE TITLE
Design issue

### ISSUE THREAD

**Issue by gabrielbazan7** [bitpay/copay#5653]
Is not align and also when clicking the button it opens the keyboard

<img width="321" alt="cursor_and_copay_-_copay_bitcoin_wallet" src="https://cloud.githubusercontent.com/assets/10999037/23224282/b6b67e3c-f8fb-11e6-910c-c0f09c41cfa4.png">

**Comment by JDonadio** [comment]
That's happens because the button is over the input field, with sure 😉
