### ISSUE TITLE
Pending BTC

### ISSUE THREAD

**Issue by priderc** [bitpay/copay#5666]
I have problems with 2 transactions, which first shows me the following id in blockchain and the other shows me not found:

Https://insight.bitpay.com/tx/5b3f8e3cf15a66fd1d270abb6c41fe79a938d9364399ec8e1bf93dd81fcd8bc4

https://insight.bitpay.com/tx/8952f95e4edc6cbd84736ab5cc8fc1dbdc67f86616e238185baeb537b2d859c4 

What is the problem?

**Comment by SoraKayy** [comment]
Looking at your transactions, I think it's that your transaction fees are too low

**Comment by priderc** [comment]
mmm is 0.1 BTC

**Comment by coketogm** [comment]
Gracias por salvarme pero es que. Me esta fallando el internet

jcgm

**Comment by coketogm** [comment]
Como le hiciste

jcgm

**Comment by coketogm** [comment]
Esta buen esa

jcgm

**Comment by priderc** [comment]
No entiendo

**Comment by JDonadio** [comment]
Both transactions have a `fee = 0.00065` that is lower than our **super economy** fee level (911 bits/kb) and takes over 4 hours to confirm, so you must wait for it...

**Comment by priderc** [comment]
I've been waiting since Tuesday

**Comment by JDonadio** [comment]
Sorry for the delay, the tx was confirmed?
