### ISSUE TITLE
Copay UI shows all UTXO amount of a transaction (instead of the real amount) sent, if configured using single address (nonHD)

### ISSUE THREAD

**Issue by knocte** [bitpay/copay#5674]
Steps to reproduce:
1. Create a Copay wallet with single address (nonHD). [In our case we tested with multi-sig, but not sure being mono-sig would mean there's no bug]
2. Send a transaction to somewhere. Amount: 0.05 BTC. [Let's assume the total UTXO was 0.07915376. e.g. this tx: https://insight.bitpay.com/tx/65254c00e9cf928f17c5facb89272a5384286e49d7ff96bdfaf72d070598cec6 ]
3. Wait until transaction appears in Copay UI.

Current results:
Last transaction shown displays "78,304 bits". (Which is total UTXO minus miner fees)

Expected results:
Last transaction shown displays "50,000 bits" (amount of tx), or "50,849 bits" (amount + miner fees).

**Comment by JDonadio** [comment]
Hi @knocte, sorry for the delay. I understand your point but this is how the bitcoin protocol works. Please take a look at [this comment](https://github.com/bitpay/copay/issues/5164#issuecomment-265569494). [This comment](https://github.com/bitpay/copay/issues/4803#issuecomment-254496226) could be useful too.

**Comment by gabrielbazan7** [comment]
I could reproduce the issue.

**Comment by gabrielbazan7** [comment]
Should be fix soon. Thanks for the report @knocte 
https://github.com/bitpay/bitcore-wallet-service/pull/625

**Comment by JDonadio** [comment]
My bad. This is a current bug that we are working to put it on production asap. Thanks @gabrielbazan7 @knocte !

**Comment by gabrielbazan7** [comment]
@knocte you will still see the last transactions wrong. But the new ones will be correct. I just test the PR.

**Comment by knocte** [comment]
@gabrielbazan7 great thanks. I'm using copay for Android, any ETA about when this will be included in an updated version? cheers

**Comment by gabrielbazan7** [comment]
This week :D
