### ISSUE TITLE
$10 Amazon GiftCard

### ISSUE THREAD

**Issue by SpecialEdition** [bitpay/copay#5676]
I purchased a $10 Amazon GiftCard and never recieved it.
https://i.imgsafe.org/20a5f0308e.png
https://i.imgsafe.org/20a6299229.png
https://i.imgsafe.org/20a62e521a.png

**Comment by JDonadio** [comment]
Can you please provide us your transaction id?

**Comment by SpecialEdition** [comment]
1a9a0a2133ab7c22a6d8e4e69e658ca2e50ec7bf678286c79af87dcf0dba30f6

**Comment by JDonadio** [comment]
Please, tap on your unconfirmed GC, click on "see invoice" and paste the link here.

**Comment by JDonadio** [comment]
@SpecialEdition please contact me to `javier@bitpay.com` if your problem persist.
