### ISSUE TITLE
Hanging when signing transaction with trezor seed

### ISSUE THREAD

**Issue by corebindallas** [bitpay/copay#5684]
Hi,

I am having a heck of a problem I can no longer sign my transactions with my trezor. Copay hangs indefinitely.

Using the trezor app I can find the wallet configure it etc. So all functionality is there on the computer in question I have tried on another computer and it doesnt work either.

This happened before when I was on a VPN and would go away when I logged off the VPN but now this doesnt work anymore

**Comment by JDonadio** [comment]
Copay shows an error on the screen? Did you check the session log?

**Comment by corebindallas** [comment]
theres actually no error it just stays stuck on signing indefinitely and I have to lose the app and the logs I think are purged when that happens from what I can tell so I havent been able to see anything that would signal an issue.

**Comment by JDonadio** [comment]
Did you update the trezor firmware? Maybe your Copay wallet is corrupt for some reason, please try to delete and import it, and be sure to do the backup correctly before.
