### ISSUE TITLE
"Transfer to Wallet" header height

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#5692]
On send tab.

It's like 71 px and all the other headers are like 51 ;-)

**Comment by gabrielbazan7** [comment]
I can't reproduce that, all items headers are 16px. Except for the "Recipient" header, but I think it's on purpose.

**Comment by JDonadio** [comment]
Should be homogenized.

**Comment by ajp8164** [comment]
[
![screen shot 2017-03-03 at 1 56 16 pm](https://cloud.githubusercontent.com/assets/1063765/23564802/781fbef2-0019-11e7-83ef-a4f723b37e24.png)
](url)

**Comment by gabrielbazan7** [comment]
Ok, just notice the issue. I'm sending a PR. Thanks @ajp8164
