### ISSUE TITLE
Pending Confirmation

### ISSUE THREAD

**Issue by Timoulis** [bitpay/copay#5705]
Hello ,

I have a ''Pending Confirmation'' for over a week now, and copay says that ''Transaction Not Found'' when i search it in blockchain. The transaction is small 0.00010001 btc.

Anyone know why the delay? State is Unconfirmed.

https://www.blocktrail.com/BTC/tx/2b308f6ff826a46d9df1af513bf3989703baf6be20a479c455a4674c645af0f8

**Comment by JDonadio** [comment]
Please take a look at [this ticket](https://github.com/bitpay/copay/issues/5693)

**Comment by Timoulis** [comment]
Finally after one week the transaction is finished.

**Comment by JDonadio** [comment]
Great! 👍
