### ISSUE TITLE
Unconfirmed transaction: Transaction not found

### ISSUE THREAD

**Issue by hitzg** [bitpay/copay#5710]
I made a [transaction](https://www.blocktrail.com/BTC/tx/b455e7b6a0445f11348b0a1dc05a1254fc1476582f0fc76e156b4e0fe1ceb2c9) with copay on android, which is still pending after 24h. If I try to "View it in blockchain" I get `Transaction not found`.

#5705 seems to describe the same problem.

Could it be that the fee was just too low? And if so, why would the app choose it? And more importantly: How can the transaction be completed?!

**Comment by JDonadio** [comment]
Yes, your fee is low (0.00010000 BTC), so you can only waiting for the confirmations.

Please, check your Fee Policy preferences. A normal level it's recommended.

**Comment by hitzg** [comment]
the fee that I have selected in the app states 0.00136 BTC/KiB, however the actual fee on the transaction turned out to be 0.00052083 BTC/KB which is less than half. How can that happen?

**Comment by matiu** [comment]
I think this is related to a problem in which fee estimation are not available at the point the TX was crafted, so a default (0.0001) is used.

This was enhanced on current version of Bitpay App, and it will be also available in the upcoming version (3.0.0) of Copay.

If the TX is not found by Copay, it was already dropped form our servers, so you should have the amount back in your balance. You can resend the TX, with other fee setting.

**Comment by hitzg** [comment]
Ok good to know. Thanks.

However, the transaction is now found again: [link](https://insight.bitpay.com/tx/b455e7b6a0445f11348b0a1dc05a1254fc1476582f0fc76e156b4e0fe1ceb2c9) Which I also find confusing...

So how will that resolve?

**Comment by babarrzephyr** [comment]
I got the same problem...Did you find a solution to your problem?
