### ISSUE TITLE
Amazon gift card nonredeemable/not showing up after two days on the copay app

### ISSUE THREAD

**Issue by Reschj1** [bitpay/copay#5717]
I purchased a $40 dollar amazon gift card two days ago and my btc has been taken out with 6+ confirmations, but no way to get the code for the gc.  The amount also just shows a blank line instead of the $40 before trying to access the card from the app as shown in the screenshots.  I have attached several screenshots to show the issue as well as provide the transaction id's. 

![img_2247](https://cloud.githubusercontent.com/assets/26183280/23578326/f87e44bc-0099-11e7-8de1-4d551af38ead.PNG)
![img_2243](https://cloud.githubusercontent.com/assets/26183280/23578329/fb6f72ae-0099-11e7-9a97-6236964800b0.PNG)
![img_2244](https://cloud.githubusercontent.com/assets/26183280/23578330/fd4a7f10-0099-11e7-9a27-4d2658132e51.PNG)

**Comment by JDonadio** [comment]
Please paste the invoice link here

**Comment by Reschj1** [comment]
The invoice is now archived but it should be b697e2ed-baa6-489f-893f-ecbee26a1083 as shown in the screenshot.

**Comment by JDonadio** [comment]
@Reschj1 we need an email contact you privately.
