### ISSUE TITLE
Jorlene

### ISSUE THREAD

**Issue by Jorlene** [bitpay/copay#5718]
I tried to send my first two btc transfers by copy and paste on my phone from an exchange to my  new copay and bitpay wallets. I have confirmation that they completed from the exchange. The bitpay wallet shows it still receiving after 9 hrs. The copay wallet shows nothing, I checked the wallet address are correct. I practiced with small amounts I would like to safely move larger amounts to store them soon, please help thanks so much.

![morrex btc transfer record](https://cloud.githubusercontent.com/assets/26186055/23579706/205dfbec-00b0-11e7-87e9-fd9996644ad5.jpg)

**Comment by JDonadio** [comment]
Please post here the transaction id, and also Copay/BitPay screenshots would be great.

**Comment by Jorlene** [comment]
I've done some reading and it looks like the fact that I sent a small
dollar amount at a high fee rate would still be not all that worth while to
the miners. Because of this it could take days or be returned and need to
be resent. Have I understood this correctly? I sent a larger amount today
at the highest fee rate so I'll see if that works better.

**Comment by JDonadio** [comment]
Just to clarify, did you made the transaction **_to_** or **_from_** Copay wallet?

**Comment by Jorlene** [comment]
Transfer was to Copay wallet.

**Comment by JDonadio** [comment]
So if your transfer was to and not from Copay you must verify your fee amount as you mention above. There is not much to do if the transaction was not generated by Copay.

**Comment by Jorlene** [comment]
Transactions both went through today thanks for your help. They were just
too small during this busy time. Larger ones went quicker.
