### ISSUE TITLE
Wallet cannot load card with a BTC amount, presents parsing error

### ISSUE THREAD

**Issue by jameswalpole** [bitpay/copay#5719]
Issue occurring for user on iOS, version 1.3.6. iPhone 6, iOS version 10.0.1. 
![issue](https://cloud.githubusercontent.com/assets/9257396/23583792/286eb922-011c-11e7-8571-b3b30be841f8.jpg)

**Comment by jameswalpole** [comment]
User comment: "Anytime I try to load in BTC denominations rather than USD, any amount 1BTC and over causes 'amount must be a number'"

**Comment by cmgustavo** [comment]
Should be fixed in the next release (also in beta 3.0). For now we are going to support only USD currency for topup the BitPay Card.

Thanks for report.
