### ISSUE TITLE
Japanese BIP39 phrases not exportable by QR

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#5727]
It looks like the Japanese is being garbled by the QR, and the same version copay can not read the QR that the other copay made if the mnemonic is Japanese.

I suggest encodeURI... but that is also long... maybe base64...

```javascript
> encodeURI('そこう　のいず　みほん　あまり　ひほう　めやす　うしろがみ　こまかい　ひんしゅ　ちらし　いらすと　ほくろ')
> "%E3%81%9D%E3%81%93%E3%81%86%E3%80%80%E3%81%AE%E3%81%84%E3%81%99%E3%82%99%E3%80%80%E3%81%BF%E3%81%BB%E3%82%93%E3%80%80%E3%81%82%E3%81%BE%E3%82%8A%E3%80%80%E3%81%B2%E3%81%BB%E3%81%86%E3%80%80%E3%82%81%E3%82%84%E3%81%99%E3%80%80%E3%81%86%E3%81%97%E3%82%8D%E3%81%8B%E3%82%99%E3%81%BF%E3%80%80%E3%81%93%E3%81%BE%E3%81%8B%E3%81%84%E3%80%80%E3%81%B2%E3%82%93%E3%81%97%E3%82%85%E3%80%80%E3%81%A1%E3%82%89%E3%81%97%E3%80%80%E3%81%84%E3%82%89%E3%81%99%E3%81%A8%E3%80%80%E3%81%BB%E3%81%8F%E3%82%8D"

> Base64.encode('そこう　のいず　みほん　あまり　ひほう　めやす　うしろがみ　こまかい　ひんしゅ　ちらし　いらすと　ほくろ')
> "44Gd44GT44GG44CA44Gu44GE44GZ44KZ44CA44G/44G744KT44CA44GC44G+44KK44CA44Gy44G744GG44CA44KB44KE44GZ44CA44GG44GX44KN44GL44KZ44G/44CA44GT44G+44GL44GE44CA44Gy44KT44GX44KF44CA44Gh44KJ44GX44CA44GE44KJ44GZ44Go44CA44G744GP44KN"
```

This should be fixed... but as is mentioned in the other issue... this feature is hard to pick up on... so it might not be high priority.

**Comment by JDonadio** [comment]
I don't really know if this is actually a bug or should be a feature request 🏷

**Comment by dabura667** [comment]
bug.

Current Copay tells Japanese users they can export/import with QR, but when they do, they get an error everytime without fail.

It is probably also broken for non-ASCII characters in general (UTF-8 2 byte chars or larger) so a Spanish phrase with some accent on it would also be broken I think... haven't tested though.

**Comment by JDonadio** [comment]
> Spanish phrase with some accent on it would also be broken I think... haven't tested though.

Yep, happening now. Thanks for reporting.
