### ISSUE TITLE
Copay Ubuntu

### ISSUE THREAD

**Issue by SoraKayy** [bitpay/copay#5737]
Hello, I am trying to install Copay for Ubuntu, but after I extract the file and open it, there isnt any executable file to open Copay/Bitpay. When i try to open it on terminal it says "command not found"

**Comment by JDonadio** [comment]
Please see this:

Download Copay linux version and extract the contents of the zip file to a new folder. Open terminal->Go to your newly created folder->run ./Copay

**Comment by SoraKayy** [comment]
Desktop/BitPay-linux: Is a directory
