### ISSUE TITLE
Copay wallet

### ISSUE THREAD

**Issue by andyy23** [bitpay/copay#5742]
My phone was damaged through a virus so I got new one. When I open Copay I don't know how to retrieve my Copay wallet that was on my old phone. All I have is my 12 word phrase from that account. How can I access this wallet?

**Comment by JDonadio** [comment]
Go to Add Wallet > Import and put your recovery phrase there.

**Comment by andyy23** [comment]
It asks for a password that I don't remember.

**Comment by JDonadio** [comment]
So you have your recovery phrase with password also. You can try as many time as you want. But unfortunately we cannot do nothing to help you in this case.
