### ISSUE TITLE
I DONT UNDERSTAND

### ISSUE THREAD

**Issue by Soulsurvivor1911** [bitpay/copay#5747]
CAN I COPY THE CODE AND START MY OWN WALLET SERVICE NAME BITCOINTRILLONAIREWALLET.COM

**Comment by Soulsurvivor1911** [comment]
OR DO I USE THE CODE AS AN AFFLIATE

**Comment by Soulsurvivor1911** [comment]
AFFILIATE

**Comment by Soulsurvivor1911** [comment]
so the question cannot be answered


________________________________

**Comment by BitLox** [comment]
There is a LOT to do if you want to run your own wallet + wallet service. 
Core bitcoind + insight-api + [optional] insight-ui + bitcore-wallet-service.
The wallet code here then will talk to your BWS instance.

**Comment by dabura667** [comment]
1. Purchase a server
2. Purchase a domain
3. Point your domain to your server
4. Setup Apache or Nginx on your server
5. Setup Bitcore on your server (This will sync the full blockchain using bitcoind and categorize the addresses in a database. This will use over 200 or 300 GB disk space)
6. A few days later, after it is synced, install bitcore wallet service (insight-api is automatically installed with bitcore)
7. Get a TLS cert using Let's Encrypt's Certbot for whichever subdomain you want pointing to your BWS
8. Set up a forced rewrite to redirect http to https in your Apache / Nginx config
9. Set up a reverse proxy in your Apache / Nginx config for https://bws.example.com/ to http://127.0.0.1:3232/ (where example.com is your domain, and bws is the subdomain you chose in step 7
10. open a local browser and test https://bws.example.com/bws/api/v2/feelevels/ and you should see a response like `[{"level":"priority","feePerKb":200367,"nbBlocks":2},{"level":"normal","feePerKb":181272,"nbBlocks":3},{"level":"economy","feePerKb":163598,"nbBlocks":6},{"level":"superEconomy","feePerKb":135781,"nbBlocks":24}]`
11. If you don't get any response, or there's an error, then fix the error.
12. If you got a similar response to the above, use https://bws.example.com/bws/api/ as your "Bitcore Wallet Service URL" in your Copay wallet.
13. If you want to re-brand Copay, go in and change all the images and assets, then also change the default BWS URL. To do this, I would do a grep of the whole directory recursively looking for the word "bitpay" and see what's in there. I just ran a quick search and it looks like the BWS URL is in a few places in the source code.

**Comment by Soulsurvivor1911** [comment]
will this be my own website and i can market it myself

**Comment by Soulsurvivor1911** [comment]
what kind of server can i use

**Comment by dabura667** [comment]
> will this be my own website and i can market it myself

Sure, why not.

> what kind of server can i use

Ubuntu >=16 should be fine, and easiest. I use Ubuntu 16.04. You will need a minimum of 200 GB of disk space ( >=300 GB recommended ) and at least 2GB of RAM (if you get less than 8 GB of RAM, I suggest setting up an 8 GB swapfile and using it for swap memory on boot.)
