### ISSUE TITLE
I swept my paper wallet yesterday and Copay still shows Pending Confirmation

### ISSUE THREAD

**Issue by EarlTh** [bitpay/copay#5753]
Why is this movement from paper wallet to my new Copay wallet taking so long?
Please help me figure this out.  I feel like my bitcoin was 'stolen' somehow.

**Comment by matiu** [comment]
Copay makes the sweep transactions using a fixed mined fee (0.0001 BTC) Given the current network status, it is probably that will never get mined.

Please wait for the TX for drop (normally 48 - 72hr) and retry using Bitpay App (which uses a dynamic fee).

Copay will implement dynamic fees in the upcoming 3.0 release.

**Comment by EarlTh** [comment]
Thank you.  To clarify, am I to understand that this 'sweeep' will not complete on Copay, and the bitcoin will 'return' to my paper wallet and then I try the sweep again with BitPay?

**Comment by gabrielbazan7** [comment]
Yes

**Comment by EarlTh** [comment]
Thank you, Gabriel and Matiu.  I appreciate your consideration and responses.  I am new to the bitcoin world, and am understandably apprehensive and sometimes confused.  At this point, patience will be my tool until the Tx has expired.  Take care, be well.

**Comment by expertschoice** [comment]
I have just had the same thing happen to me. I swept a paper wallet but the transaction is still pending after 2 days. I tried to sweep the paper wallet again, using a higher transaction fee, but it seems that the paper wallet has a zero balance now.  Just curious, **where** is the Bitcoin that was swept from the wallet? Its not in the paper wallet and not in the wallet it was supposed to be sent to.
