### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by buch8** [bitpay/copay#5758]
#: src/js/services/walletService.js:878
#: src/js/services/walletService.js:879 

`     title = gettextCatalog.getString('Confirm you new spending password');
askPassword(warnMsg, gettextCatalog.getString('Confirm you new spending password'), function(password2) {`

Please change "you" to "your".

**Comment by JDonadio** [comment]
You're right. Thanks for the report!

Typo https://github.com/bitpay/copay/blob/master/src/js/services/walletService.js#L878

Thanks @buch8 !
