### ISSUE TITLE
Installed 64bit programs on 32 Windows system 

### ISSUE THREAD

**Issue by bg111** [bitpay/copay#5760]
Installer, downloaded from https://github.com/bitpay/copay/releases/download/bitpay/BitPay.exe 

always install .exe (except uninstaller) for 64 bit architecture

**Comment by JDonadio** [comment]
You mean an uninstaller.exe?

**Comment by bg111** [comment]
i mean all exe, except unins000.exe

**Comment by JDonadio** [comment]
You can uninstall any application directly from your OS. Sorry but I don't understand your point here.

**Comment by bg111** [comment]
On Mon, 13 Mar 2017 06:00:58 -0700
  Javier Donadío <notifications@github.com> wrote:
> You can uninstall any application directly from your OS. 
>Sorry but I don't understand your point here.

Ok, I repeat again:
I download and install software from official github page.
By press on "Windows" image (without architecture notes).
But ALL executable installed (except uinst000.exe) is 
64bit application.
And can't runnable on my 32bit Windows.

So, it is right to installing 64bit executable to 32 bit 
OS?
I hope you understanding point.

**Comment by JDonadio** [comment]
Honestly I never tried. You can install it anyways and test what you need (create, import, export, send funds, etc) with testnet wallets.

**Comment by bg111** [comment]
Looks like you never listen me.

64 bit applications not runnable on 32 bit Windows systems

**Comment by gabegattis** [comment]
Copay does not support 32 bit windows.

**Comment by bg111** [comment]
:)

In this case better if installer deny installation with warning to user

**Comment by gabegattis** [comment]
That's probably a good idea. Best to give a reasonable error message if you try to use it on a 32 bit system.
