### ISSUE TITLE
2FA Support by Trusted Entity like Bitpay

### ISSUE THREAD

**Issue by Dworf** [bitpay/copay#5762]
This is a Feature Request

It would be really great if Bitpay would be available to co-sign the transactions with options to verify a transaction with 2FA or Email or SMS.

Currently there is only one option to use sig3.io but with them being unknown entity and with their SSL Cert expired for more then 200 days this does not give a huge confidence!

Having someone like Bitpay co-sign 2-3 keys would be really the final touch of this great app!

I know i can have a mobile phone sign + laptop sign the transaction but i would like to have same option for when im not behind a laptop (when sending payment at a bar for example) to co-sign with email confirmation, sms confirmation or 2FA

thanks and keep up the great work!

**Comment by JDonadio** [comment]
NACK.

You have spending password and also (if your device support it) fingerprint before send any transaction.
You have multi-signature wallets, that allow you create a proposal from the device A and require a second sign from the device B (assuming a 2of2 wallet).
You have read-only wallet, which is used to read, check, and create proposals. But without the possibility to sign it.
