### ISSUE TITLE
Request Spending Password UI issue

### ISSUE THREAD

**Issue by gabrielbazan7** [bitpay/copay#5764]
Request Spending Password switch is disabled if the wallet needs backup. But it feels like is broken.

<img width="406" alt="copay_-_copay_bitcoin_wallet_and_package_json_ ___documents_copay" src="https://cloud.githubusercontent.com/assets/10999037/23855935/630019ee-07d6-11e7-8f12-08e0aa3e5755.png">

**Comment by JDonadio** [comment]
It's disabled, not hidden.
