### ISSUE TITLE
Trezor wallet address not updating correct balance 

### ISSUE THREAD

**Issue by Willstar44** [bitpay/copay#5765]
I have noticed it for a while now, 
my IOS and chrome app never show the correct balance, I have tried re-syncing but is never the same as my razor wallet 

Have also deleted and try to add a new hardware wallet.

**Comment by JDonadio** [comment]
Note that Copay shows the balance based on your "Use unconfirmed funds" option in advanced settings. Can you check it?

**Comment by Willstar44** [comment]
I am talking about having 10 bitcoin, and it only showing 1 ... and also talking about waiting day and week so everything should be confirmed. and the balance are not correct

**Comment by dabura667** [comment]
Did you use Copay to generate all addresses you used with Trezor?

Or have you used MyTrezor or Electrum or some other wallet to generate new addresses for you?

**Comment by JDonadio** [comment]
No response. Feel free to re-open if the problem remains.
