### ISSUE TITLE
Uncaught Type error - exists is not a function in Copay

### ISSUE THREAD

**Issue by rakeshgn31** [bitpay/copay#5778]
I am trying to debug chrome app codebase while trying to experiment something. But, I am getting this weird error when I am trying to launch my application at this line in bindings.js code 

  , exists = fs.existsSync || path.existsSync

Could you please help me with this issue?

**Comment by JDonadio** [comment]
Hi there,

Please take a look [here](https://github.com/bitpay/copay/issues/5443) and tell me if you still having problems

**Comment by JDonadio** [comment]
Seems to be a problem with the storage service but I can't be sure.

You are customizing Copay but unfortunately we cannot give you a complete support on that.

**Comment by rakeshgn31** [comment]
@JDonadio  Hi... I solved this issue by replacing the deprecated exists function. Now, I have one another issue. I suspect this issue is related to Copay. It is trying to load a module and look for package.json during the app launch. It is not finding it and fails to load the app with following error

![image](https://cloud.githubusercontent.com/assets/17096344/24037263/dce20808-0b05-11e7-9049-a0213a0d6cd1.png)

**Comment by rakeshgn31** [comment]
@JDonadio And another one. All these errors are occurring after I updated my Copay clone repo. I am now not able to launch original Copay app built from the latest code (REMOVED ALL MY CHANGES). Please find the error below.
![image](https://cloud.githubusercontent.com/assets/17096344/24039539/4820d84e-0b0e-11e7-9622-25a5dad93551.png)

**Comment by JDonadio** [comment]
Hey @rakeshgn31, thanks for reporting that. I'm testing our current master version and the building is successful. Probably you have to run `npm run clean-all` in order to clean your project and try building again.

**Comment by rakeshgn31** [comment]
@JDonadio I did clean before. One change from the Copay codebase (I have in my code) is that I have cloned the bitcore-wallet-client, included two more node modules node-ffi and ref into client package.json and pointed out to the local repo in Copay package-template.json.

**Comment by JDonadio** [comment]
If you change any entry on template folder you must run `npm run apply:copay` to reflect the changes.

**Comment by rakeshgn31** [comment]
Yes, I ran so that It could give me the chrome-app. I did the following after changing the package-template.
npm run apply:copay
cd chrome-app
grunt
make

Now, when I load and launch Chrome-app, I get the above error.

**Comment by JDonadio** [comment]
Are you installing your modules with `--save` option?

Again, the Copay base code are working fine (I tried again to be sure)

**Comment by rakeshgn31** [comment]
Yes... I used --save option. But, I tried by manually adding to the bitcore-wallet-client/package.json too.

**Comment by JDonadio** [comment]
Are you linking your bwc module from copay to your own bwc local repo?

**Comment by rakeshgn31** [comment]
Yes!

**Comment by JDonadio** [comment]
Should looks like 

<img width="986" alt="1__javier_javier-mac____copay_node_modules__zsh_" src="https://cloud.githubusercontent.com/assets/13851807/24047359/3412b7fa-0b04-11e7-8d6d-59c5147b6a40.png">

Any change in your linked bwc must be reflected in your copay project with grunt. But that's all that I can tell you because we are not having any problems... so you must to research it further..

**Comment by rakeshgn31** [comment]
My _changes are reflected_ in the Copay code final JS file **angular-components.js** that is obtained after we do **'grunt'**. But when I do make and launch the app, this issue is not allowing me to open the app :-(
