### ISSUE TITLE
Urgent Fee Policy Setting – Not Showing Estimated Fee or Confirmation Time

### ISSUE THREAD

**Issue by jameswalpole** [bitpay/copay#5781]
![network fee policy](https://cloud.githubusercontent.com/assets/9257396/23964333/8308d63a-098a-11e7-88e6-2a73291316a7.png)

**Comment by jameswalpole** [comment]
In version 3.0.4 of app for Android 7.1.1 on Nexus 6P

**Comment by matiu** [comment]
This is because 3.0.x is still beta and the required server side support for this version is not yet deployed. Thanks for the report. I will close it since it will be fix once 3.0 hit the market and we deploy the new version of BWS.
