### ISSUE TITLE
Peether Personal Wallet no longer works and asks me to update to Copay. Are the two related ?

### ISSUE THREAD

**Issue by stephane-rolland** [bitpay/copay#5782]
My android wallet application Peether Personal Wallet no longer works.
It no longer connects, and reports an error. It's been some months I add not used it.

The error message is: 

> Could not update Wallet: Please upgrade Copay to perform this action

It suggests me to update to Copay, but I simply wonder how the 2 android applications are related, and how it could make me take control over my ETH coins again.

Do you have any information ?

Should I install Copay from Play Store ? Will take into account my former ETH coins that were managed by Peether ?

**Comment by dabura667** [comment]
No. This is a Bitcoin wallet only.

Please contact Peether support and tell them they have an error message that still says "Copay" and tell them to change it.

Then also ask them about your issue.

**Comment by stephane-rolland** [comment]
I have contacted the author. But got no answers from him.
As the application seemed to be using CoPay underneath, I wonder if it's some code from CoPay that was dealing with the private key. Could you indicate me where to find it in the files of the android system ? What file could contain the private key ?
