### ISSUE TITLE
How to make my Bitcoin in the Copay app unhackable

### ISSUE THREAD

**Issue by ne2canwin77** [bitpay/copay#5790]
Hi, I have Bitcoin in the Copay app and I want to make it unhackable. If I delete the app and write down the recovery phrase to recover the coin later, are my Bitcoin now unhackable? Or can they still be hacked at the Copay server or whatever. Thanks.

**Comment by dabura667** [comment]
If you download the app from the playstore, your device is on the internet.

If your device is on the internet, it is hackable.

If your device is already hacked and actively searching for Copay / other bitcoin apps to watch for and looking for private keys and recovery phrases, then the moment you generate your first wallet, you're already hacked.

If you want unhackable, you must generate the phrase / private keys offline.

Boot your PC via USB Tails OS, unplug all LAN cables and disable WiFi. Then generate the phrase. Write it down on paper, then shutdown without plugging the internet back in. Remove the USB and destroy the USB (it is possible someone hacked the USB controller chip and has saved your phrase and waiting til you plug it in to an internet enabled device to send it to the hacker.

Also, you might want to think about investing in a faraday cage, perhaps.

**Comment by ne2canwin77** [comment]
I sense sarcasm. I guess I asked a stupid question. Sorry I'm a n00b with bitcoin. I just want to know what I should do to protect myself from hacking.

**Comment by dabura667** [comment]
You said "unhackable"

I gave you an answer.

It was not sarcasm, you really do have to be super paranoid if you want "unhackable" bitcoins.

**Comment by ne2canwin77** [comment]
Yes I am paranoid. I am paranoid of the government seizing my $, that's why I invested in unseizable Bitcoin lol. I am paranoid of other things as well. Ok let me ask a different question. Does deleting the app make my bitcoins safer?

**Comment by dabura667** [comment]
If you assume that you are not hacked already and you delete the app, then you are safe from malware that hacks you AFTER you deleted the app.

The server only stores the public key information and addresses, but no secret info.

**Comment by ne2canwin77** [comment]
What do you recommend to keep my Bitcoin safe in the Copay app?

**Comment by dabura667** [comment]
One of the great features of the Chrome App version is the ability to support the Trezor hardware wallet.

You can use the Trezor to store your keys and use Copay to manage and send the funds from the Trezor. Very convenient. (Requires you to initially set up the wallet once using myTrezor beforehand)

**Comment by matiu** [comment]
you can also set up a 2 of 2 wallet using a phone and a desktop. That way,
both devices will have to be compromised to steal your Bitcoins. that is a
very secure set up.

**Comment by JDonadio** [comment]
You can also make a paper wallet and send your funds there. [This](https://www.youtube.com/watch?v=wfMHsLXx_qM) turorial can help you.

Note: you can also add a password to protect your funds.

<img width="818" alt="bitaddress_org" src="https://cloud.githubusercontent.com/assets/13851807/24100042/0e5a0ee2-0d51-11e7-8515-be99cbfb0107.png">
