### ISSUE TITLE
Reconsider support for other coins

### ISSUE THREAD

**Issue by plainas** [bitpay/copay#5793]
This has been discussed before. From a quick search on this issue tracker, not so much lately.

With a lot of question marks ahead on bitcoin's road in mind, is there are thoughts on possibly supporting other coins?

This is by far the best wallet out there. Available on many platforms with the same familiar gui. Easy to set up. Great usability and of course, easy to use multisig, which takes security to a whole other level than others.

**Comment by BGalliotti** [comment]
Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.


Thanks.
