### ISSUE TITLE
Recovery story is tricky

### ISSUE THREAD

**Issue by Quentin-M** [bitpay/copay#5800]
BIP44, BIP45, P2SH, P2PKH
Various BIP39 derivation paths (m/45', m/48, 2147483647, ...)
Multisig wallets, hardware wallets, BWS, SJCL, Copay

[...]

There're a lot of parameters and things that can go sideways. As a Bitcoin Wallet, the most important feature is not to let users create a transaction securely but to ensure they'll be able to recover their wallet no matter what. The documentation / tooling to do so should be considered  first-class citizen.

Currently, Copay allows users to export the recovery phrase of each copayer - or export the wallet itself as a JSON file. Then the README, baseDerivation.md and backupRecovery.md provides bits of information regarding to how a wallet can be recovered in Copay under different circumstances. However, it is still hard to understand how funds (especially with a multisig wallet) can be fully recovered in any other compatible HD multisig client (what is Copay / BWS disappears) - and what is technically required to do so. No one wants to be in the situation where they lost access to their funds and discover they are missing some piece of information to recover them.

I'd like to see a unified tool to export all raw data and verify that the data in possession is enough. Furthermore, documentation should exist to import a multisig wallet managed by Copay to another major client. Also, instead of relying on a third-party JS crypto library, the choice could be left to export clear-text the various keys on a USB stick for instance - and/or to use industry-hardened and standard encryption tool such as GPG.

Thanks.

**Comment by matiu** [comment]
see Copay recovery tool. ( in github)

**Comment by JDonadio** [comment]
Repo: https://github.com/bitpay/copay-recovery
Tool: https://bitpay.github.io/copay-recovery/

**Comment by JDonadio** [comment]
Note that after you scanned your wallet successfully you are able to send that funds to any wallet, not necessary a Copay wallet. Please feel free to re-open if you need more information.
