### ISSUE TITLE
unable to send coins from Windows Mobile wallet

### ISSUE THREAD

**Issue by uglitangeo** [bitpay/copay#5801]
I try to send my coins to another wallet. Every time I scan the address, the wallet puts the amount higher than I have. Trying to manually edit the amount doesn't work as the keypad doesn't appear on the screen.

Choosing "Send max" puts the correct amount but after the address is scanned it is changed. 
If I scan the address first the "Send max" gets grey and doesn't do anything.

At this time I am unable to move any coins. Have not had this problem before.

I run Copay 2.6.0 on MS Lumia 950 with all updates installed.

**Comment by JDonadio** [comment]
Please try with BitPay app from www.bitpay.com/wallet

**Comment by uglitangeo** [comment]
I applied for the Windows Mobile Beta.

Does the two apps share the wallet data or how does this help me?

**Comment by Derrick-** [comment]
I am also interested in release plans for a new Windows Mobile version.

**Comment by JDonadio** [comment]
Will be a new release for windows soon but it isn't available right now. I suggest try with another platform (with the latest version) in order to user your funds. If your problem persist please let us know.

**Comment by JDonadio** [comment]
Just a little update: We are planing to send a new windows mobile version this week ;)
