### ISSUE TITLE
"Trying to access beyong buffer length" error when signing multisig transaction with Trezor

### ISSUE THREAD

**Issue by Phanco** [bitpay/copay#5803]
We have a 3-5 multisig wallet, all using Copay, three of which are equipped with Trezor. Things went weird after receiving a payment. Any creation of proposal including that UTXO would return error. Here are the detailed steps to this problem

1. Create a payment proposal as usual, trying to spend this UTXO
2. A Trezor window pops up
3. Instead of prompting for passphase, the Trezor window closed unexpectedly 
4. Copay shows "Could not create payment proposal: The payment was created but could not be completed". The proposal is visible at home screen, unsigned.
5. Clicking the "Accept" button on the proposal from the home screen would pop up the Trezor window, but closed itself after seconds like step 2.
6. Copay shows "Hardware Wallet Error: Trying to access beyond buffer length"

OS : Mac OS X 
Copay Version : v2.6.0 Chrome Extension

I am look for a solution to spend those coins successfully, Much obliged :)

**Comment by JDonadio** [comment]
Hi @Phanco, can you please contact me at javier@bitpay.com? Regards.-
