### ISSUE TITLE
Bitcoin Address

### ISSUE THREAD

**Issue by Timoulis** [bitpay/copay#5805]
Hello,
I just update to v3.0.6 but i cannot find my Bitcoin Address. :-(

I search everywhere ( I think )

Can someone point the location within the program?

Regards
Tim

**Comment by JDonadio** [comment]
Hi @Timoulis,

In receive tab are listed the wallet and addresses/QR code, did you check it? 
If you cannot see it, can you provide some screenshot of your problem?

**Comment by JDonadio** [comment]
What device and SO are you using?

**Comment by Timoulis** [comment]
Ok i found it.

Last question. Can i use the previous address from the previous version or i must use the new ones.
Because i cannot find my old one.
Also what is the SO you are saying?

**Comment by JDonadio** [comment]
Yes, you can re-use the same address for multiple payments. You can check your addresses unused and with funds clicking on the address itself. Also, if you want to use only one addresses there is an option (at wallet creation) to avoid the re-create a fresh one for each payment arrived (by default).

<img width="401" alt="copay_-_copay_bitcoin_wallet" src="https://cloud.githubusercontent.com/assets/13851807/24207995/2f7833b8-0f01-11e7-8708-937dc0724cd5.png">

<img width="397" alt="copay_-_copay_bitcoin_wallet" src="https://cloud.githubusercontent.com/assets/13851807/24207934/01014984-0f01-11e7-8943-d30a6c955c9d.png">

Hope that helps

**Comment by Timoulis** [comment]
Ok found it.
I have to check at my second wallet.
Beside the ‘’Personal Wallet’’ at the ''Receive'' section there was a blur icon with the old wallet.
Within it was my old address.
Anyway thank you for your help my friend.

Regards
Tim
