### ISSUE TITLE
Sweep paper wallet removed

### ISSUE THREAD

**Issue by HostFat** [bitpay/copay#5806]
I can't find the sweep paper wallet function on both Copay/Bitpay versions.

Did you really removed it?

**Comment by JDonadio** [comment]
Hi there,

Both apps either Copay as BitPay app has the ability to sweep a paper wallet. 
In Copay navigate to Preferences > Advanced > Sweep Paper Wallet. 
In BitPay app just use the scanner (middle tab, send tab), or paste the private key in the send tab input and a contextual menu will be shown.

https://uploads.intercomcdn.com/i/o/20522004/3048f7b7d1a740b7ec6f097b/Copay_-_Copay_Bitcoin_Wallet.png

**Comment by HostFat** [comment]
I'm talking about the last version of both Copay/Bitpay wallet v3.0.6

Do you mean that it is the same on Copay v3.0.6 as in the Bitpay wallet? (with the scanner)

**Comment by JDonadio** [comment]
Yep, same functionality for both.

**Comment by HostFat** [comment]
Great, it was just little hidden ;)

**Comment by JDonadio** [comment]
😉

**Comment by LeaTex** [comment]
Hi @JDonadio, I've the same issue in Copay v3.2.0 (for Android) or BitPay v1.0.1 (for Windows).

There is no option for sweep paper wallet, and the "send" tab only has a "recipient" input field, and when I paste the private key there nothing happend.

**Comment by gabrielbazan7** [comment]
make sure that the private key you paste is correct. Try scanning the qr code on the paper wallet.

**Comment by LeaTex** [comment]
Thank's @gabrielbazan7 . It's working on Copay for Android, but not in BitPay for Windows

**Comment by gabrielbazan7** [comment]
Ok, we are going to check. Thanks !

**Comment by JDonadio** [comment]
@klepkosg please open a new issue for your case. In the meantime I'll check the sweeping process.

**Comment by JulianTosh** [comment]
Can this be enabled for TestNet. I am unable to scan testnet private keys from bitaddress.org or bitcoinpaperwallet.com.

This will be VERY handy and educational for my CoPay wallet classes!

**Comment by hopeseekr** [comment]
i'm having terrible trouble with testnet. I'm trying to make funds available for my dev team.
