### ISSUE TITLE
Disable/Clear the "Update" Notice?

### ISSUE THREAD

**Issue by KeyJockey** [bitpay/copay#5807]
Hey guys... I'm getting the Copay "new version" notice bar on my copy of Copay running on my MacBook, see screencap : 

![update](https://cloud.githubusercontent.com/assets/13903392/24224948/5c437c76-0f34-11e7-9bbb-43b64479af3a.png)

...but I'm not ready to update yet UNTIL I can see exactly what's changed in the new "BitPay Integrated" version.  As long as 'old Copay' is still working reasonably well (I have version 2.7) kinda don't want to deal with it.

SO is there any way to get RID of this update notice bar now, short of actually updating?

Pretty annoying to have to keep looking at this thing IF I am really not interested in updating yet. Yeah okay I get it you have notified me about the update but now "go away" LOL

Even a CLOSE BOX so the notice can get cleared at each startup would've been okay... but, nothing?

Some hidden text file setting or something I can edit to make this go away?

TIA for any help.

**Comment by matiu** [comment]
thanks. it is a good point, but I am afraid it is not possible yet. we will
do it for next releases (but you will have to upgrade ;-) )

**Comment by KeyJockey** [comment]
Hmm, okay.  Bummer.  I guess I'll just have to get used to overlooking it for now LOL

**Comment by KeyJockey** [comment]
Oops, re-opening issue to add: "OK then, so in the meantime any guidance if it's possible to just install a separate "clean" instance of the new Copay/Bitpay independent of old Copay version?"

That way in case of any issue, can I still run the old 2.7 wallet if needed and just import seed words into the new 3.0 wallet... OR are the two instances going to have to share folder or data files or something on my Mac somewhere?

**Comment by JDonadio** [comment]
TODO: Add close button for update notification.

**Comment by KeyJockey** [comment]
UPDATE: Okay I went ahead and just tried it, LOL

Installed the new BitPay from fresh download and made a new wallet first, then imported one of my old wallets from the old Copay backup as a test.

So far, so good.  Everything seems to be fine and both wallets appear to be capable of running side by side without issue (knock on wood).


![bitpaycopay](https://cloud.githubusercontent.com/assets/13903392/24254552/9783900c-0fb9-11e7-81a0-6a5fa7a3042e.png)


Just posting this here for benefit of others... DEVS: anything we need to be aware of in a situation like this just to be sure not to somehow corrupt either of the wallets or other possible issue?

Thanks.

**Comment by JDonadio** [comment]
Sorry but I'm disagree. Reviewing this topic, we shouldn't encourage people to use old versions.
I understand this may be annoying for some but we are always improving and fixing the code and also our support is based on that.
