### ISSUE TITLE
A 2 of 4 copay wallet, but only 1 user left

### ISSUE THREAD

**Issue by ChrisiJm** [bitpay/copay#5809]
Hallo, my issue is that :

**A 2 of 4 copay wallet, but only 1 user left.**
Wallet recovery words got lost.
3 devices got dammaged and can't be recovered only one User (Pc) left. 
Copaybackup.aes.json is available.

How can I confirm an transaction to another wallet or send it to coinbase or buy amazon gift cards ?

I am looking forward to find a solution.
Thank you.

**Comment by isocolsky** [comment]
Hi. Does the `.aes.json` file belong to a different copayer than the one you have on your remaining Pc?

**Comment by JDonadio** [comment]
To restore a wallet you need a backup, please see [this wiki entry](https://github.com/bitpay/copay/wiki/COPAY---FAQ#how-do-i-get-access-to-my-wallet-in-case-of-loss).
