### ISSUE TITLE
sync between mobile and desktop app

### ISSUE THREAD

**Issue by mrgren** [bitpay/copay#5810]
hello
thanks for providing such beautifull wallet, i am asking about sycn between my copy mobile/desktop wallet how can do that  ?

thanks.

**Comment by isocolsky** [comment]
Hi. 
To import on your desktop pc: go to Add Wallet -> Import wallet and enter your recovery phrase (12 words).
To import on your phone: from your desktop go to Settings -> <Select wallet> -> More options -> Export wallet -> Select QR Code. Then from your phone go to Add Wallet -> Import wallet and scan using the camera icon at the right side of the screen.
You can import on as many devices as you wish and the wallet will always be in sync.
