### ISSUE TITLE
Account Sorting

### ISSUE THREAD

**Issue by JulianTosh** [bitpay/copay#5818]
My wallet has over a dozen accounts and there seems to be no order for them in the new 3.0.6 release. It is very difficult to quickly identify accounts I need to use. Can we get them sorted alphabetically?

Thanks!

**Comment by JDonadio** [comment]
Right now there is not option to sort the wallet list. The only way to do it is importing one, then another... etc. 

Also related https://github.com/bitpay/copay/issues/2359. This have more priority now. Thanks for reporting.
