### ISSUE TITLE
Spending from TestNet accounts broken in 3.0.6

### ISSUE THREAD

**Issue by JulianTosh** [bitpay/copay#5821]
I am unable to select any testnet accounts under 'Transfer to Wallet' send screens. I am also unable to select a testnet account in 'send from account' if a testnet account is scanned.

**Comment by JulianTosh** [comment]
The testnet accounts are not even displayed when viewing these section on the screens.

**Comment by JDonadio** [comment]
Can you provide us more detail about what device and SO are you using?

**Comment by JulianTosh** [comment]
Android 7, Nexus 6. 
Linux version running on Fedora 25.
Chrome web app.
All demonstrate the same symptoms.

**Comment by JDonadio** [comment]
Can you see but not select them, or they are not in the list?

**Comment by JulianTosh** [comment]
The testnet accouts are not visible in the lists.

**Comment by JulianTosh** [comment]
The testnet accounts are visible in the home page, but when you go to spend testnet coins, it is not possible to see the accounts to select them for use. They are not in the list.

**Comment by JDonadio** [comment]
How many testnet wallets do you have, and what are their balances?

**Comment by JulianTosh** [comment]
Two, one is a single sig account with 31.5 coins. The other is a multi-sig with over 214 coins.

**Comment by JDonadio** [comment]
Let me check it and I'll keep you posted.

**Comment by dabura667** [comment]
I have iPhone 7 with the latest Copay. I tried out a bunch of stuff.

I had one testnet wallet, but made another just in case. Send 0.05 BTC to it.

Then I tried scanning testnet addresses from various QR icons, each one would bring me to a screen where I put in the amount and hit the right arrow.

Then, depending on the amount, it would auto-select the wallet with enough funds OR pop up with a selector to ask which testnet wallet I wanted to send from.

aka, nothing too out of the ordinary... though the new UI is hard to get used to...

@JulianTosh can you possibly record your screen somehow? Then upload to Google photo and post the share link?

Android: https://play.google.com/store/apps/details?id=com.spectrl.rec&hl=ja
Linux (for Chrome app and Linux app): http://www.maartenbaert.be/simplescreenrecorder/#download

**Comment by JulianTosh** [comment]
I'm going to chock this up to confusion with the new UI, but it is clear this issue is user error. I can only imagine the initial wallet creation for the other user did not include creating the wallet as a testnet wallet (even though I specifically went through the steps to make it so and for whatever reason, it didn't stick). And/Or, the change in the way the UI works compared to previous version: send/receive is now the first step, vs selecting the account to work with. I will be seeing this user again later this morning to verify the test wallet settings and identify where the mistakes were made.

But since this issue is clearly incorrect, I will close it in shame. Sorry for the lost cycles.

**Comment by matiu** [comment]
thanks for the update.
