### ISSUE TITLE
Needed features!

### ISSUE THREAD

**Issue by JokerJ420** [bitpay/copay#5824]
Bring back the "Send Max" button when sending funds.  Also when sending funds, it would be nice to see the amount thats in your wallet so you dont have to go back and look.  When sending funds its also nice if the wallet will determine the max amount with fees and not say "insufficient funds".

**Comment by gabrielbazan7** [comment]
The Send Max button is up the amount view. Also you could see the amounts of your wallets in the confirm view. Use the send max to determine the max amount.

**Comment by JDonadio** [comment]
> Bring back the "Send Max" button when sending funds

The send max option is now here

<img width="348" alt="copay_-_copay_bitcoin_wallet" src="https://cloud.githubusercontent.com/assets/13851807/24359080/a0dea1f0-12d9-11e7-91fc-c591f7227216.png">

> Also when sending funds, it would be nice to see the amount thats in your wallet so you dont have to go back and look

If you put an amount which is available in more than one wallet you will see a list with their balances

<img width="345" alt="copay_-_copay_bitcoin_wallet" src="https://cloud.githubusercontent.com/assets/13851807/24359051/888b9a54-12d9-11e7-99a2-ff7240888d94.png">
