### ISSUE TITLE
If i keep my funds in copay wallet & if HARD FORK happen who will take care of my fund 

### ISSUE THREAD

**Issue by shubh615** [bitpay/copay#5825]
If fork happen..what are the possible outcomes my coins will be afe or not before & after fork.And what needs to be done before & after fork as a bitcoin holder

**Comment by parth-gudhka** [comment]
This is a genuine concern, even I am wondering about. Does anyone know how we will handle the hard fork?

**Comment by matiu** [comment]
Hello,

> If i keep my funds in copay wallet & if HARD FORK happen who will take care of my fund

In Copay, only the user has the private key, not the server, so you will need to take care of the private key (needed to move funds), as always.

> If fork happen..what are the possible outcomes my coins will be afe or not before & after fork. And what needs to be done before & after fork as a bitcoin holder

As a Copay user you probably dont need to do anything. You are the only one that have the private keys, so your coins will be safe as before the hard fork.
