### ISSUE TITLE
Can't paste amount when sending transaction

### ISSUE THREAD

**Issue by romeroadrian** [bitpay/copay#5826]
I've recently updated copay to 3.0.6 and I've noticed that you can't paste the btc amount when sending a transaction with the new UI.

Tested in OSX, not sure about other platforms.

**Comment by matiu** [comment]
thanks for the report, it is a known issue in the new UI,we will try to fix it in the next release.

**Comment by matiu** [comment]
dup https://github.com/bitpay/copay/issues/5113
