### ISSUE TITLE
NPM start errors

### ISSUE THREAD

**Issue by BitMari** [bitpay/copay#5827]
Hie cloned the repo , did npm install , now trying to npm start and im getting errors

Running "sass:dist" (sass) task
>> Error: File to import not found or unreadable: ../../bower_components/ionic/scss/ionic
>>        Parent style sheet: /Users/bitmari/ls/copay2017/copay/src/sass/ionic.scss
>>         on line 4 of src/sass/ionic.scss
>> >> @import "../../bower_components/ionic/scss/ionic";
>>

**Comment by dabura667** [comment]
did you do npm run:copay or run:bitpay first?

**Comment by BitMari** [comment]
i did npm run apply:copay

Running "sass:dist" (sass) task
>> Error: File to import not found or unreadable: ../../bower_components/ionic/scss/ionic
>>        Parent style sheet: /Users/bitmari/ls/copay2017/copay/src/sass/ionic.scss
>>         on line 4 of src/sass/ionic.scss
>> >> @import "../../bower_components/ionic/scss/ionic";
>>    ^
Warning:  Use --force to continue.

Aborted due to warnings.

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:www"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! copay@3.0.7 build:www: `grunt`
npm ERR! Exit status 6
npm ERR! 
npm ERR! Failed at the copay@3.0.7 build:www script 'grunt'.
npm ERR! This is most likely a problem with the copay package,
npm ERR! not with npm itself.

**Comment by JDonadio** [comment]
Please, try it again doing:

* npm run clean-all
* npm run apply:copay
* grunt
* npm start

**Comment by gabrielbazan7** [comment]
@BitMari use the last version of master. Could be related to https://github.com/bitpay/copay/issues/5787

**Comment by BitMari** [comment]
restarted the clone getting errors on grunt


Running "sass:dist" (sass) task
>> Error: File to import not found or unreadable: ../../bower_components/ionic/scss/ionic
>>        Parent style sheet: /Users/bitmari/ls/copay20172/copay/src/sass/ionic.scss
>>         on line 4 of src/sass/ionic.scss
>> >> @import "../../bower_components/ionic/scss/ionic";
>>    ^
Warning:  Use --force to continue.

**Comment by BitMari** [comment]
Still getting the same error , anyone help, im using a  Mac

**Comment by gabrielbazan7** [comment]
@BitMari You are in master branch?

**Comment by JDonadio** [comment]
Please tell us what version of cordova, node are you running.

**Comment by BitMari** [comment]
cordova - v  
6.5.0

node -v
v4.4.0

**Comment by gabrielbazan7** [comment]
try updating node version. If nothing happens, look to the bower_component folder and check if an ionic folder exits, if not, try npm i ionic@1.3.1 and check again

**Comment by BitMari** [comment]
Hie , so i updated node , tried but still , then as i was going to your second recommendation i noted bower_components folder doest exists at all , what might be causing this ?

**Comment by JDonadio** [comment]
There is definitely a missing command. After the cloning:

* npm run clean-all > should complete clean your project
* npm i > should install all your node and bower packages.
* npm run apply:copay > should build the copay distribution
* grunt > already done but just in case
* npm start > should start your server listening at port 8100

**Comment by BitMari** [comment]
So i have tried all you recommended and totally failed , any possibly i have something broken on my machine , node, ? 

same error

>> Bundle angular-bitcore-wallet-client/angular-bitcore-wallet-client.js created.

Running "sass:dist" (sass) task
>> Error: File to import not found or unreadable: ../../bower_components/ionic/scss/ionic
>>        Parent style sheet: /Users/bitmari/ls/copay2017/copay/src/sass/ionic.scss
>>         on line 4 of src/sass/ionic.scss
>> >> @import "../../bower_components/ionic/scss/ionic";

**Comment by gabrielbazan7** [comment]
try with `bower install`

**Comment by JDonadio** [comment]
Try to upgrade node to v6 or higher.

I'm using:

* Cordova **6.3.1**
* Node **6.9.1**
* Npm **3.10.8**

**Comment by BitMari** [comment]
bower install  worked 

thanks
