### ISSUE TITLE
Wallet Recovery

### ISSUE THREAD

**Issue by ysk0ce** [bitpay/copay#5835]
Hello Copay team,

predicament I had my copay wallet on my android phone for a while but recently it died on me so I had to get a new phone, and now when I downloaded the app on my new phone I cant have access to my wallet because The recovery phrase was on my phone as a screenshot I toke. Will you be able to help me out of this situation?

Thanks,
YSK

**Comment by matiu** [comment]
In order to recover your wallet, you need to have the recovery phrase, the wallet's private keys are not stored on server side.

**Comment by ysk0ce** [comment]
so essentially there is no way to recover my wallet then.

**Comment by matiu** [comment]
if you dont have the backup, Im afraid not.

**Comment by JDonadio** [comment]
If you took a picture you can check into a different apps like Google Photos, Dropbox, etc. Probably  was synchronized automatically.

**Comment by simosimosi** [comment]
nel caso in cui uno ha cancellato per errore il portafoglio ma invece ha conservato la frase di recupero?

**Comment by JDonadio** [comment]
@simosimosi you can restore your wallet with your recovery phrase going to add wallet > import.

**Comment by JDonadio** [comment]
@simosimosi yes, you can restore your wallet with your recovery phrase going to Add wallet > Import.
