### ISSUE TITLE
$50 Amazon gift code de-activated and the wallet says account suspended

### ISSUE THREAD

**Issue by copayuser** [bitpay/copay#5837]
Hi, I'm a new user to copay wallet, I just bought $50 amazon gift code in it with no problem, but amazon says "claim code locked", and a few minutes later, it says"claim code de-activated", I contacted amazon support, they told me that the gift code is refunded. I checked my wallet, but there's no payment refunded to me

I tried to buy another gift code, but the wallet says "Error creating BitPay invoice Account is suspended"

don't know what's wrong and what should I do

**Comment by JDonadio** [comment]
Can you please provide us your wallet id, and also the invoice link of the $50 AGC.

**Comment by JDonadio** [comment]
@copayuser can you forward your issue to support@bitpay.com? They can help you better with your invoice problem.

**Comment by copayuser** [comment]
payment refunded and I can buy gift code again, thanks
