### ISSUE TITLE
Let someone buy bitcoin to my copay wallet

### ISSUE THREAD

**Issue by vintrr** [bitpay/copay#5842]
Hi,

I am trying to understand if there is a way I can have a client of mine buy bitcoin using his bank account to directly go to my Copay wallet without him having to create a wallet himself

Best,
Urvesh

**Comment by dabura667** [comment]
If you live near a bitcoin ATM, yes.

**Comment by JDonadio** [comment]
Your client can buy bitcoin from an ATM, Exchanges companies, other people, or whatever and just provide your address to send the coins to your wallet.
