### ISSUE TITLE
Error: Unknown Provider with Copay

### ISSUE THREAD

**Issue by rakeshgn31** [bitpay/copay#5846]
@JDonadio  Hi Javier... I wrote a new node module and wrote a new Angular provider for it and integrated it into Copay app similar to angular-bitauth and angular-bitcore-wallet-client. I have added module entries into app.js, Gruntfile.js and all. I am able to launch the app and after creating new wallet, In the home screen it does not list any wallets and it says unknown provider error in the console pointing to my new service. When I check the issue, it again traces back to the old issue fs.accessSync is not a function. I am not able to use any 'fs' module package related code in Copay. Could you please help me out if I am missing something?

**Comment by JDonadio** [comment]
@rakeshgn31 sorry but we cannot give you support for non Copay base code errors.

**Comment by rakeshgn31** [comment]
@JDonadio  But to test a new feature in Copay, we need to integrate with that. At least could you please let me know any other steps than listed in my request that has to be taken to integrate a new node module into Copay code?

**Comment by JDonadio** [comment]
@rakeshgn31 this is not a new feature but your own customization of Copay and unfortunately we cannot help you with that.

`angular-bitauth && angular-bitcore-wallet-client` are browserified, check the `Gruntfile.js` entries and his respectives directories.

**Comment by JDonadio** [comment]
I will leave this open for others to be able to give an opinion and help you.
