### ISSUE TITLE
Spinner on addresses screen hangs consistently

### ISSUE THREAD

**Issue by ziggamon** [bitpay/copay#5847]
Steps to reproduce:

Switch to "Receive" tab.
Click wallet symbol to scroll through wallets
On the wanted wallet it shows a QR code and an address
Clicking the address, or the arrow causes the wallet to hang, 100% of the time. 

Chrome v.58.x for Mac

**Comment by ziggamon** [comment]
Can confirm the same happens on iOS. 

Attaching screenshot. 

![img_3270](https://cloud.githubusercontent.com/assets/92292/24590316/378902a6-17eb-11e7-8b64-822ec28b4565.PNG)

**Comment by JDonadio** [comment]
Hi @ziggamon, this is a known issue with the loader spinner. Seems to be hanging while is getting the address info, but is not blocking the process at all in our test. Can you please confirm us if in your device/s is loading the addresses?

**Comment by ziggamon** [comment]
Hi @JDonadio,

I tried leaving it open now and it seems like in deed it does arrive successfully at a result in the end. Probably this has to do with this wallet having a long transaction history. On wallets with shorter history it doesn't hang so long at all.

During the hang however the entire app becomes unusable which caused my mistaking if for a full hang.

**Comment by JDonadio** [comment]
Ok thanks for report it and test it. 
We'll put an eye on this.
