### ISSUE TITLE
API

### ISSUE THREAD

**Issue by frisir** [bitpay/copay#5848]
Dear Sir/ Madam for my business i need an API code? Thank you Regard Hermann Troger

**Comment by JDonadio** [comment]
Hi @frisir can you explain a little more what do you need?

**Comment by gabrielbazan7** [comment]
@frisir if you still need our help reopen the issue.

**Comment by frisir** [comment]
Hello . Thank you for answering. For my homepage i need an API Code , so my clients can buy my services online. How can i get that? Thank you Hermann
