### ISSUE TITLE
add more fees on transaction 

### ISSUE THREAD

**Issue by bitcsarl** [bitpay/copay#5850]
Hi, 
it's possible to add more fees after import a paper wallet?
I would like to add more fees because the transaction (sweep) since the paper wallet is still not confirmed after 24h.
how do I proceed?

**Comment by JDonadio** [comment]
Hi @bitcsarl, 

What version of Copay/BitPay app are you running? Probably you need to use the latest release where the sweeping process also use dynamic fee. Please take a look at [this post](https://github.com/bitpay/copay/issues/5753#issuecomment-285700273).

**Comment by gabrielbazan7** [comment]
@bitcsarl If you have any question please reopen the issue.
