### ISSUE TITLE
sending balance issues

### ISSUE THREAD

**Issue by weesder** [bitpay/copay#5851]
i cannot edit the amount of bitcoins I want to send somewhere just says 1 bitcoin and I do not have nor want to send a full bitcoin

**Comment by JDonadio** [comment]
Can you give us more details about your case?

In a common scenario, the sending process (after select your recipient) leads you to this view:

![bitpay - secure bitcoin wallet_3](https://cloud.githubusercontent.com/assets/13851807/24684271/21841b62-197b-11e7-95f4-72c4f5749769.jpg)

Is it the view where are you having problems?

**Comment by weesder** [comment]
it just has the recipient category then there Is blank screen beneath that there is no option to add amount and if I try to continue it automatically assumes I'm trying to send 1 bitcoin and says not enough funds

**Comment by weesder** [comment]
yeah the view

**Comment by JDonadio** [comment]
If you can attach some screenshots would be great to understand your case better

**Comment by weesder** [comment]
![image](https://cloud.githubusercontent.com/assets/26912545/24684508/c7327062-1963-11e7-8e8a-6ecd25d7ba3c.png)
there is no amount option

**Comment by JDonadio** [comment]
The sending process has 3 steps:

1 - Choose your recipient (to)
2 - Choose the amount (attached above)
3 - Choose your sending waller (from)

In your image you are in the first step. So you put an address there (or scan one) and automatically will navigate to the amount view (step 2). Did you tried that?

**Comment by weesder** [comment]
this is the only thing that shows up when I put in a sending address, there are no other options
![win_20170404_20_12_14_pro](https://cloud.githubusercontent.com/assets/26912545/24686805/57760d28-1973-11e7-9f87-9f59b9c4dd79.jpg)

**Comment by JDonadio** [comment]
You never see the amount view in the process? That's weird,.. please tell me what version of the app are you running, and also your device OS version.

Can you check the session log and paste here after you arrive to the confirm view? You can find it in settings > about bitpay > session log

**Comment by weesder** [comment]
I am running v3.0.6 and android version 6.0

**Comment by weesder** [comment]
Copay Session Logs
 Be careful, this could contain sensitive private data



Copay v3.0.6 #f149c0a
Client: {"isAndroid":true,"isIOS":false,"isWP":false,"isSafari":false,"ua":"Mozilla/5.0 (Linux; Android 6.0; a500 Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.132 Mobile Safari/537.36","isCordova":true,"isMobile":true,"isDevel":false}
Using: FileStorage
Running head controller:Copay
Route change from: -  to: starting
            toParams:{}
            fromParams:{}
Starting...
Init profile...
Got main dir: file:///data/user/0/com.bitpay.copay/files/
Got main dir: file:///data/user/0/com.bitpay.copay/files/
Adding Buy and Sell service:coinbase linked:false
Adding Buy and Sell service:glidera linked:false
Got main dir: file:///data/user/0/com.bitpay.copay/files/
Adding NextSteps entry:amazon
Got main dir: file:///data/user/0/com.bitpay.copay/files/
Profile is not encrypted
Profile read
Preferences read: {"limits":{"totalCopayers":6,"mPlusN":100},"bws":{"url":"https://bws.bitpay.com/bws/api"},"download":{"bitpay":{"url":"https://bitpay.com/wallet"},"copay":{"url":"https://copay.io/#download"}},"rateApp":{"bitpay":{"ios":"http://itunes.apple.com/WebObjects/MZStore.woa/wa/viewContentsUserReviews?id=1149581638&pageNumber=0&sortOrdering=2&type=Purple+Software&mt=8","android":"https://play.google.com/store/apps/details?id=com.bitpay.wallet","wp":""},"copay":{"ios":"http://itunes.apple.com/WebObjects/MZStore.woa/wa/viewContentsUserReviews?id=951330296&pageNumber=0&sortOrdering=2&type=Purple+Software&mt=8","android":"https://play.google.com/store/apps/details?id=com.bitpay.copay","wp":""}},"wallet":{"requiredCopayers":2,"totalCopayers":3,"spendUnconfirmed":false,"reconnectDelay":5000,"idleDurationMin":4,"settings":{"unitName":"BTC","unitToSatoshi":100000000,"unitDecimals":8,"unitCode":"btc","alternativeName":"US Dollar","alternativeIsoCode":"USD"}},"recentTransactions":{"enabled":true},"hideNextSteps":{"enabled":false},"rates":{"url":"https://insight.bitpay.com:443/api/rates"},"release":{"url":"https://api.github.com/repos/bitpay/copay/releases/latest"},"pushNotificationsEnabled":true,"emailNotifications":{"enabled":false},"bwsFor":{},"colorFor":{},"aliasFor":{},"emailFor":{}}
Preferences read
Binding wallet:3f079459-fb4a-4a53-8ecf-4a9381af7b58 Validating?:false
Wallet + 3f079459-fb4a-4a53-8ecf-4a9381af7b58 status:undefined
Bound 1 out of 1 wallets
Profile loaded ... Starting UX.
Trying to pre-initialize QRScanner.
scannerService is reviewing platform capabilities...
A camera is available to this app.
Camera access is authorized.
Support for opening device settings is available on this platform.
A light is available on this platform.
A second camera is available on this platform.
Camera permission already granted.
Initializing scanner...
Route change from: starting  to: tabs.home
            toParams:{"fromOnboarding":""}
            fromParams:{}
Setting default language: en
scannerService is reviewing platform capabilities...
A camera is available to this app.
Camera access is authorized.
Support for opening device settings is available on this platform.
A light is available on this platform.
A second camera is available on this platform.
buyAndSell Service, updating nextSteps. linked/total: 0/2
Adding NextSteps entry:buyandsell
Initializing openURL
Updating Status: Personal Wallet null
Starting push notification registration...
startupService is showing the StatusBar...
startupService is hiding the splashscreen...
Get token for push notifications: c-DSuGrMujk:APA91bHDXzB-x7I8P_-WCQmx4KLBQlSabgoKxhiewFkydFcIuqEwDvjRExePy53EjOyfDTMCEHprHbxrAodcXHoINtrARrgdd9OSX-zH4adbkUu3zAnivit1BHQzLbWvjJqspd8h8uMr
Personal Wallet: Subscription Push Notifications success.
Status update. hash:536948 Try:0
Got Wallet Status for:Personal Wallet
Writing: balanceCache-3f079459-fb4a-4a53-8ecf-4a9381af7b58 {"balance":"0.005369 BTC","updatedOn":1491361902}
Route change from: tabs.home  to: tabs.send
            toParams:{}
            fromParams:{"fromOnboarding":""}
Wallet status cache hit:3f079459-fb4a-4a53-8ecf-4a9381af7b58
Route change from: tabs.send  to: tabs.scan
            toParams:{}
            fromParams:{}
Activating scanner...
scannerService is reviewing platform capabilities...
A camera is available to this app.
Camera access is authorized.
Support for opening device settings is available on this platform.
A light is available on this platform.
A second camera is available on this platform.
Scanner activated, setting to visible...
Scan view state set to: visible
Scanning...
Scan returned: "bitcoin:14674SCCouafidZjnYv3fGxjKRZo7SCZoA?amount=1&label=1"
Processing incoming data: bitcoin:14674SCCouafidZjnYv3fGxjKRZo7SCZoA?amount=1&label=1
Route change from: tabs.scan  to: tabs.send
            toParams:{}
            fromParams:{}
Route change from: tabs.send  to: tabs.send.confirm
            toParams:{"recipientType":"","toAddress":"14674SCCouafidZjnYv3fGxjKRZo7SCZoA","toName":"","toAmount":"100000000","toEmail":"","toColor":"","description":"","useSendMax":"","paypro":null}
            fromParams:{}
Wallet status cache hit:3f079459-fb4a-4a53-8ecf-4a9381af7b58
No wallet available to make the payment
Route change from: tabs.send.confirm  to: tabs.send
            toParams:{}
            fromParams:{"recipientType":"","toAddress":"14674SCCouafidZjnYv3fGxjKRZo7SCZoA","toName":"","toAmount":"100000000","toEmail":"","toColor":"","description":"","useSendMax":"","paypro":null}
Route change from: tabs.send  to: tabs.settings
            toParams:{}
            fromParams:{}
Route change from: tabs.settings  to: tabs.about
            toParams:{}
            fromParams:{}
Route change from: tabs.about  to: tabs.about.logs
            toParams:{}
            fromParams:{}
Route change from: tabs.about.logs  to: tabs.about
            toParams:{}
            fromParams:{}
Route change from: tabs.about  to: tabs.about.logs
            toParams:{}
            fromParams:{}
Route change from: tabs.about.logs  to: tabs.about
            toParams:{}
            fromParams:{}
Route change from: tabs.about  to: tabs.about.logs
            toParams:{}
            fromParams:{}

**Comment by JDonadio** [comment]
Ok, you are scanning an invoice to send exactly 1 BTC

> Scan returned: "bitcoin:14674SCCouafidZjnYv3fGxjKRZo7SCZoA?amount=1&label=1"

In this case you cannot change the amount because it is requested in the scanned information. To send a custom amount you must copy the testination address and just paste in the address input to navigate to the amount view.

**Comment by weesder** [comment]
thanks mate its working I tried that b4 didn't work but now it is for some reason

**Comment by JDonadio** [comment]
Great! 👍
