### ISSUE TITLE
Gift Card on copay

### ISSUE THREAD

**Issue by andremgh** [bitpay/copay#5854]
Compre una gift card en mi monedero de copay, el dinero fue retirado pero la gift card no aparecio. Adjunto un print de la transaccion. Muchas gracias.

![screenshot_2017-04-05-17-19-03](https://cloud.githubusercontent.com/assets/26940840/24727184/fec075b4-1a09-11e7-93cb-495fbbfa6259.png)

**Comment by JDonadio** [comment]
Hola @andremgh,

Al parecer hay algunos inconvenientes con Coinbase, por favor podrías darle una mirada a [este comentario](https://github.com/bitpay/copay/issues/5855#issuecomment-292004686)?

**Comment by andremgh** [comment]
por favor tengo dos giftcard perdidas una de $500 y otra de $1000 una comprada por copay aplicacion movil de android y otra comprada por bitpay aplicacion de windows. Me urge ese dinero para unas compras por amazon de emergencia.


por favor necesito tu ayuda




________________________________
De: Javier Donadío <notifications@github.com>
Enviado: miércoles, 5 de abril de 2017 19:56
Para: bitpay/copay
Cc: andremgh; Mention
Asunto: Re: [bitpay/copay] Gift Card on copay (#5854)


Hola @andremgh<https://github.com/andremgh>,

Al parecer hay algunos inconvenientes con Coinbase, por favor podrías darle una mirada a este comentario<https://github.com/bitpay/copay/issues/5855#issuecomment-292004686>?

**Comment by matiu** [comment]
Hola,

podrías escribirme a matias@bitpay.com? Mandame los address adonde enviaste las transactions.
gracias.

**Comment by matiu** [comment]
solved offline. Sorry for the problems.
