### ISSUE TITLE
Gift Card Copay problema.

### ISSUE THREAD

**Issue by anibaljpa** [bitpay/copay#5855]
Buenas tardes, compré una gift card por la aplicación Copay y me Debitaron los Btc pero nunca pude ver el código de la tarjeta. Cómo puedo hacer para recuperar el código?

**Comment by matiu** [comment]
Hola, podrías mandarnos el screenshot (o el  ID de transacción) a support@bitpay.com ?  gracias.

**Comment by matiu** [comment]
Por favor, reabre este ticket si todavía no lo resolviste. Gracias.
