### ISSUE TITLE
send btc

### ISSUE THREAD

**Issue by gdelaage** [bitpay/copay#5860]
Hello
I transferred bitcoin to a USD deposit at poloniex.
![2017-04-07 12 26 48](https://cloud.githubusercontent.com/assets/26985554/24779469/0a59e6b2-1b31-11e7-97e6-39ff721ac243.jpg)
![2017-04-07 12 34 36](https://cloud.githubusercontent.com/assets/26985554/24779470/0a5fa4da-1b31-11e7-9a1c-d219ed7f29e5.jpg)

The transfer is not confirmed.
what should I do?
thank you

**Comment by JDonadio** [comment]
Just wait 😉

**Comment by gdelaage** [comment]
thanks, the transfer is confirmed. 
I received BTC instead of USC
