### ISSUE TITLE
Copay Wallet deleted. I have roots of 12 words lie, ver-, win-, val-, etc

### ISSUE THREAD

**Issue by otziman** [bitpay/copay#5862]
Hello All!

MY girlfriend sent money to an old copay wallet and wrote down only the beginnings of the 12 words like

tap-, att-, ver-, val-, etc

Now I have come to 3456 possibilities of words but I can't try them one by one

Anyone know a script capable doing that?

Otherwise my money lost in copay nodes!

**Comment by dabura667** [comment]
was it all 3 letters?

**Comment by otziman** [comment]
No she wrote down 12 words
with python I am down to 4 words of which beginings I have like ver-, val-, att-..
I must be able to recover it somehow, please help
otherwise never gonna use copay ever again

**Comment by otziman** [comment]
Btw forgot to mention that I installed Python/BTCrecoveries/libsodium/armory etc 
I am new to those tho and try to handle it all myself with very little knowlegde

**Comment by gabrielbazan7** [comment]
So you have 4 incomplete words and 8 complete words ?

**Comment by otziman** [comment]
Yes indeed

**Comment by dabura667** [comment]
oh lol, that's not at all close to 3456 possibilities.

**Comment by dabura667** [comment]
more like 60 ish, especially if you have the first 3 letters of each of the 4 words

**Comment by dabura667** [comment]
Hold on a sec, I'll write a script

**Comment by otziman** [comment]
I was 4 sure words starting this, python kind of told me now 4 of them are not right..
Should mean that other 8 s right innit?
Thanks so much by the way dabura667

**Comment by dabura667** [comment]
wait..... how many words are right?... do you have the right order?

**Comment by otziman** [comment]
thanks god the only thin I can vouch 100% for is the order.
From writings on the notebook we are 100% about 4 words, now I tried different combinations for python and when I entered all 12, it said 4 of them was not right, that is why I thought I am now down to 4 words..
I might be wrong completely due to the fact that I don't know how to use Python.
I wish I can tell you all the words

**Comment by isocolsky** [comment]
Forget python for a second. Could you grab your notebook and identify the words 1 by 1 using this list https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt ? Tell us how many are in there.

**Comment by otziman** [comment]
Aren't copay wallets bip-0032 tho? Just asking

**Comment by dabura667** [comment]
> Python/BTCrecoveries/libsodium/armory

Armory uses a different word list.

> Aren't copay wallets bip-0032 tho?

Copay is BIP39 word list used to derive BIP32 HD keys using BIP44 derivation

**Comment by otziman** [comment]
Oh gosh ok I see

**Comment by gabrielbazan7** [comment]
tape

attack
attend
attitude
attract

verb
verify
version
very

valid
valley
valve

**Comment by dabura667** [comment]
Also, BIP39 English words are all unique by 4 letters. So if you have the first 4 letters of every word you can find every word with 100%.

**Comment by dabura667** [comment]
This is a script to see your possible combinations in nodeJS.

1. Go here: https://www.tutorialspoint.com/execute_nodejs_online.php
2. in the terminal in the bottom, type `npm install bitcore-mnemonic`
3. Once it is done and says sh4.3$ again, paste the script below in the editor on the top screen, overwrite the existing default script. THEN overwrite the phrase I wrote (where I wrote all words with 3 letters only just as an example) and write all full words you know and any words you don't know just write as many letters as you know from the beginning of the word.
4. Click the Save icon next to "New Project" in the upper left to save the script.
5. Click the "Execute" button in the top left of the screen.
6. you will see possibilities for each word AND the total number of possible phrases.

```javascript
var Mnemonic = require('bitcore-mnemonic')

// put your word parts here separated by space
var wordParts = "exo dev ank rot loc arr gaz tal rea aba kid sig"
var wordPartsArray = wordParts.split(" ")
var candidates = []

wordPartsArray.forEach(function (wordPart) {
  candidates.push(Mnemonic.Words.ENGLISH.filter(function (word) {
    return word.slice(0, wordPart.length) == wordPart
  }))
})

var candidatesCounts = candidates.map(function (item) { return item.length })
var totalPossibilities = candidatesCounts.reduce(function (a, b) { return a * b })

console.log("Possibilities for each word: " + candidatesCounts.toString())
console.log("Total possible combinations: " + totalPossibilities)
```

**Comment by dabura667** [comment]
Actually, lol, maybe you should install NodeJS on your computer.

**Comment by otziman** [comment]
Just installed Nodejs and tried to type npm install bitcore-mnemonic; should be run outside/ on your shell
When I type it on my terminal then:

![grafik](https://cloud.githubusercontent.com/assets/26942635/24804154/cf179e00-1bad-11e7-8a6b-4fdbf2f4c3fa.png)

**Comment by otziman** [comment]
I should run the script on my NodeJS you mean right? 
I typed npm install bitcore-mnemonic on the link, and downloaded the NodeJS, should I run it there?

**Comment by isocolsky** [comment]
Please note that this calculation only works if every single word part exists in the BIP39 list. You should make sure of that. Or maybe change the script so that if 0 matches are found, all 2048 words are added to the list of candidates.

**Comment by dabura667** [comment]
> Or maybe change the script so that if 0 matches are found, all 2048 words are added to the list of candidates.

I edited my script above.

**Comment by dabura667** [comment]
yes, you installed bitcore-mnemonic on C:\> so you want to save my script as xxx.js in C:\ and run it by the command `node xxx.js`

**Comment by otziman** [comment]
How can I save your script as .js in C?
Appreciate the effort! Indeed I would like to share my coins If I recover it :)

**Comment by dabura667** [comment]
Open My Computer.

Click on C drive

Right click blank space "Create New > Text document"

The default name is "newfile.txt" open it

paste in the script

save, then exit

right click and rename the file to something.js

now you have a js file in your C drive's root ( C:\ )

**Comment by dabura667** [comment]
You must have "show file extensions" enabled in the "Folder Options" for your file explorer.

**Comment by otziman** [comment]
I did and it said possible combinations 576

**Comment by dabura667** [comment]
no... you need to change the phrase to your phrase.

**Comment by otziman** [comment]
I did it as well it was 4096 combinations :(

**Comment by dabura667** [comment]
The one I have in there is just a test... but now you just need to open the file in text editor and change the phrase "exo dev ank rot loc arr gaz tal rea aba kid sig" with your phrase

**Comment by dabura667** [comment]
what was the list of possibilities?

1,2,5,3,7,4,5,6,1 etc.

**Comment by otziman** [comment]
1,1,1,6,1,4,1,4,7,3,1,3

**Comment by dabura667** [comment]
4096 shouldn't be too bad though, as 1/16 are valid, which means we would only need to check 256 accounts.

Let me update the script to actually check the balances of each possibility. Hold on a few minutes to an hour.

**Comment by otziman** [comment]
Oh my god! You are a decent man dabura667!
Thank you very very much

**Comment by dabura667** [comment]
You also need to install insight-cli
`npm install insight-cli`

Here's the final script, the valid check will finish and then all the responses from the server will come back slowly. Just wait.

```javascript
var Mnemonic = require('bitcore-mnemonic')
var insightRestClient = require('insight-cli').RestClient
var insightRest = new insightRestClient();

var wordParts = "exo dev ank rot loc arr gaz tal rea aba kid sig" // put your word parts here separated by space

var wordPartsArray = wordParts.split(" ")
var candidates = []
var indices = [0,0,0,0,0,0,0,0,0,0,0,0]
var validMnemonics = []

wordPartsArray.forEach(function (wordPart) {
  candidates.push(Mnemonic.Words.ENGLISH.filter(function (word) {
    return word.slice(0, wordPart.length) == wordPart
  }))
})

var candidatesCounts = candidates.map(function (item) { return item.length > 0 ? item.length : 2048 })
var totalPossibilities = candidatesCounts.reduce(function (a, b) { return a * b })

console.log("Possibilities for each word: " + candidatesCounts.toString())
console.log("Iterating over " + totalPossibilities + " possibilities...")

var finished = false
var correctPhrase = ""

var callInsight = function (addresses, myMN) {
  return insightRest.tx4addrs(addresses, {}).then(function (result) {
    var callbackMN = myMN
    if (result.totalItems > 0) {
      console.log("Found transactions on mnemonic: " + callbackMN.phrase)
      finished = true
      correctPhrase = callbackMN.phrase
    } else {
      console.log("No transactions on mnemonic: " + callbackMN.phrase)
    }
  })
  .catch(function (err) {
    console.log(err)
  })
}

while (!finished) {
  //console.log(indices.map(function (item) { return item + 1 }))
  //console.log(candidatesCounts)

  var currentPhrase = candidates.map(function(wordArray, index) {
    return wordArray[indices[index]]
  }).join(" ")

  //console.log("Trying phrase: " + currentPhrase)

  try {
    var currentMN = new Mnemonic(currentPhrase)
  } catch (e) {
    //console.log("Not valid mnemonic: " + currentPhrase)
    currentMN = null
  }

  if (currentMN) {
    validMnemonics.push(currentMN.phrase)
    var receiveKeys = currentMN.toHDPrivateKey().derive("m/44'/0'/0'/0")
    var addresses = []
    for (var i = 0; i < 20; i++) {
      addresses.push(receiveKeys.derive(i).publicKey.toAddress().toString())
    }
    callInsight(addresses.join(","), currentMN)
  }

  if (candidatesCounts.toString() !== indices.map(function (item) { return item + 1 }).toString()) {
    var roomToCount = false
    for (var i = 0; i < indices.length; i++) {
      if (indices[i] < candidatesCounts[i] - 1) {
        roomToCount = true
      }
    }
    if (roomToCount) {
      var ticked = false
      for (var i = indices.length - 1; i >= 0; i--) {
        if (!ticked) {
          if (indices[i] >= candidatesCounts[i] - 1) {
            indices[i] = 0
          } else {
            indices[i] += 1
            ticked = true
          }
        }
      }
    }
  } else {
    finished = true
    correctPhrase = ""
  }
}

console.log("List of valid mnemonics:")
console.log(validMnemonics.join("\r\n"))
console.log("WAITING ON RESPONSE FROM SERVER FOR BALANCES... THE ONE WITH A BALANCE IS YOURS.")
```

**Comment by dabura667** [comment]
1DHc1ae3rUJaZzYDSfS5qBTu4g9Bec7XRM

Hope it helps you!

**Comment by otziman** [comment]
I will run the script on insight and it will be able to show me the whole words? or? 
Thanks so much!

**Comment by dabura667** [comment]
To check 33 valid mnemonics out of 576 total combinations (for my test):

1. All 33 valid mnemonics were found in about 4 seconds.
2. All 33 wallet balance datas came back in about 1 minute.

Perhaps 250 ish queries to insight might cause the server to reject you for rate limiting... but hopefully that doesn't happen...

Also, here is my results from the example I have put in there:
```bash
Possibilities for each word: 1,3,1,1,2,4,1,2,3,1,2,2
Iterating over 576 possibilities...
List of valid mnemonics:
exotic develop ankle rotate local arrange gaze talent ready abandon kidney sight
exotic develop ankle rotate local arrange gaze talent reason abandon kid sight
exotic develop ankle rotate local arrest gaze talent real abandon kidney sight
exotic develop ankle rotate local arrest gaze talk ready abandon kid sign
exotic develop ankle rotate local arrive gaze talent real abandon kid sign
exotic develop ankle rotate local arrive gaze talent reason abandon kid sign
exotic develop ankle rotate local arrive gaze talk ready abandon kid sign
exotic develop ankle rotate lock arrange gaze talk ready abandon kid sign
exotic develop ankle rotate lock arrest gaze talent ready abandon kid sight
exotic develop ankle rotate lock arrest gaze talent real abandon kid sight
exotic develop ankle rotate lock arrest gaze talk reason abandon kid sign
exotic develop ankle rotate lock arrow gaze talent reason abandon kidney sign
exotic device ankle rotate local arrange gaze talk ready abandon kidney sign
exotic device ankle rotate local arrange gaze talk real abandon kid sign
exotic device ankle rotate local arrest gaze talent reason abandon kid sign
exotic device ankle rotate local arrive gaze talent reason abandon kid sight
exotic device ankle rotate local arrive gaze talent reason abandon kidney sign
exotic device ankle rotate local arrive gaze talk ready abandon kidney sign
exotic device ankle rotate local arrow gaze talk real abandon kid sight
exotic device ankle rotate lock arrange gaze talk ready abandon kid sight
exotic device ankle rotate lock arrest gaze talent ready abandon kid sign
exotic device ankle rotate lock arrow gaze talent reason abandon kid sign
exotic device ankle rotate lock arrow gaze talk ready abandon kid sight
exotic devote ankle rotate local arrange gaze talent reason abandon kid sight
exotic devote ankle rotate local arrest gaze talk reason abandon kidney sign
exotic devote ankle rotate local arrive gaze talent ready abandon kid sight
exotic devote ankle rotate local arrive gaze talent real abandon kid sight
exotic devote ankle rotate lock arrange gaze talent real abandon kid sign
exotic devote ankle rotate lock arrange gaze talk real abandon kidney sign
exotic devote ankle rotate lock arrest gaze talent ready abandon kid sign
exotic devote ankle rotate lock arrest gaze talent real abandon kidney sign
exotic devote ankle rotate lock arrest gaze talk reason abandon kidney sign
exotic devote ankle rotate lock arrow gaze talk reason abandon kid sight
WAITING ON RESPONSE FROM SERVER FOR BALANCES... THE ONE WITH A BALANCE IS YOURS.
No transactions on mnemonic: exotic develop ankle rotate local arrange gaze talent ready abandon kidney sight
No transactions on mnemonic: exotic devote ankle rotate lock arrest gaze talent ready abandon kid sign
No transactions on mnemonic: exotic devote ankle rotate lock arrest gaze talent real abandon kidney sign
No transactions on mnemonic: exotic devote ankle rotate lock arrest gaze talk reason abandon kidney sign
No transactions on mnemonic: exotic devote ankle rotate lock arrow gaze talk reason abandon kid sight
No transactions on mnemonic: exotic develop ankle rotate local arrange gaze talent reason abandon kid sight
No transactions on mnemonic: exotic develop ankle rotate local arrest gaze talent real abandon kidney sight
No transactions on mnemonic: exotic develop ankle rotate local arrest gaze talk ready abandon kid sign
No transactions on mnemonic: exotic develop ankle rotate local arrive gaze talent real abandon kid sign
No transactions on mnemonic: exotic develop ankle rotate local arrive gaze talent reason abandon kid sign
No transactions on mnemonic: exotic develop ankle rotate local arrive gaze talk ready abandon kid sign
No transactions on mnemonic: exotic develop ankle rotate lock arrange gaze talk ready abandon kid sign
No transactions on mnemonic: exotic develop ankle rotate lock arrest gaze talent ready abandon kid sight
No transactions on mnemonic: exotic develop ankle rotate lock arrest gaze talent real abandon kid sight
No transactions on mnemonic: exotic develop ankle rotate lock arrest gaze talk reason abandon kid sign
No transactions on mnemonic: exotic develop ankle rotate lock arrow gaze talent reason abandon kidney sign
No transactions on mnemonic: exotic device ankle rotate local arrange gaze talk ready abandon kidney sign
No transactions on mnemonic: exotic device ankle rotate local arrange gaze talk real abandon kid sign
No transactions on mnemonic: exotic device ankle rotate local arrest gaze talent reason abandon kid sign
No transactions on mnemonic: exotic device ankle rotate local arrive gaze talent reason abandon kid sight
No transactions on mnemonic: exotic device ankle rotate local arrive gaze talent reason abandon kidney sign
No transactions on mnemonic: exotic device ankle rotate local arrive gaze talk ready abandon kidney sign
No transactions on mnemonic: exotic device ankle rotate local arrow gaze talk real abandon kid sight
No transactions on mnemonic: exotic device ankle rotate lock arrange gaze talk ready abandon kid sight
No transactions on mnemonic: exotic device ankle rotate lock arrow gaze talent reason abandon kid sign
No transactions on mnemonic: exotic device ankle rotate lock arrest gaze talent ready abandon kid sign
No transactions on mnemonic: exotic device ankle rotate lock arrow gaze talk ready abandon kid sight
No transactions on mnemonic: exotic devote ankle rotate local arrange gaze talent reason abandon kid sight
No transactions on mnemonic: exotic devote ankle rotate local arrest gaze talk reason abandon kidney sign
No transactions on mnemonic: exotic devote ankle rotate local arrive gaze talent ready abandon kid sight
No transactions on mnemonic: exotic devote ankle rotate local arrive gaze talent real abandon kid sight
Found transactions on mnemonic: exotic devote ankle rotate lock arrange gaze talent real abandon kid sign
No transactions on mnemonic: exotic devote ankle rotate lock arrange gaze talk real abandon kidney sign
```

**Comment by dabura667** [comment]
> I will run the script on insight and it will be able to show me the whole words?

Just run the script like you did the last script, remember to change the phrase to the phrase you have and write as many letters for each word as you can. (just like last time when you got the possibility number)

**Comment by otziman** [comment]
I can't install wheter on my nodejs or online version :( ERR! not ok code 0
or in nodejs it says it should be run on the outside.. how can I install insight otherwise?

**Comment by dabura667** [comment]
@otziman I hope you found your phrase. Let me know if you didn't.

**Comment by dabura667** [comment]
Could you show me the actual error?

**Comment by otziman** [comment]
![grafik](https://cloud.githubusercontent.com/assets/26942635/24810650/4f797766-1bc3-11e7-927f-03bd70074579.png)

![grafik](https://cloud.githubusercontent.com/assets/26942635/24810679/7130a92e-1bc3-11e7-80e3-a1cfe5c36133.png)

**Comment by dabura667** [comment]
could you install the latest stable version of nodeJS?

https://nodejs.org/download/release/v7.7.2/node-v7.7.2-x64.msi

I think you have an old version...

try typing

`node -v` into command and if the version is lower than 7.7.2 install the one I linked you.

**Comment by dabura667** [comment]
then it should work fine.

**Comment by otziman** [comment]
now I installed the version 7 but still same error occurs on my node.js

**Comment by dabura667** [comment]
what does `node -v` say?

**Comment by otziman** [comment]
I started node with command promt with your script and it looks like searching 
no transactions and continuing, I don't know tho if I could install insight
node -v is 7 after I installed your link of nodejs

**Comment by dabura667** [comment]
ok good

If it says "no transactions" then just keep waiting until it says "Found Transactions on mnemonic : xxx" and THAT one is your phrase.

**Comment by dabura667** [comment]
if it completely stops and none of them say "Found Transactions" then let me know.

**Comment by otziman** [comment]
It stopped and now back in C:/ :(

**Comment by otziman** [comment]
inbetween I saw many different codes looking like private keys but they all disappeared

**Comment by dabura667** [comment]
Did any of them say "Found transactions" ?

**Comment by dabura667** [comment]
were you watching the whole time?

**Comment by dabura667** [comment]
http://stackoverflow.com/questions/1740876/more-lines-in-command-window

This is how to make the console for Windows to hold more lines, btw.

**Comment by otziman** [comment]
Yes I was watching but didint see found...

**Comment by dabura667** [comment]
I changed the script slightly so that it will stop completely when the transaction is Found, and it will make it very obvious.

Maybe try running it again.

But anyways, at least now you have a list of valid mnemonics that it could be...

Maybe you can look at the list of all the phrases and you might remember which ones the words are.

I need to go to sleep. Good luck.

**Comment by otziman** [comment]
Thank you very much man! I will let you know!

**Comment by dabura667** [comment]
@otziman

By the way, what number did your addresses start with? 1 or 3?

**Comment by otziman** [comment]
Public key you mean?

It starts with 1

I ran the script yesterday, unfortunately it showed partly " rate limit exceeded" but it continued so I tried whole night..

**Comment by dabura667** [comment]
rate limit exceeded means that insight won't answer you anymore, so you need to wait one day.

change the skipCount var near the top to skip balance check for a certain number of phrases. That way you don't re-query the same phrases you know are not correct.

**Comment by otziman** [comment]
like this:

var wordParts = " wordpart1 wordpart2 ....."

// 
// 
var skip balance = word1, word2, word3

**Comment by dabura667** [comment]
No.

It currently says:

```javascript
// in case you get rate limited, you can try tomorrow and skip the number of
// transaction balance queries that you did today and start off where you left off.
var skipCount = 0
```

you should change that to say

```javascript
// in case you get rate limited, you can try tomorrow and skip the number of
// transaction balance queries that you did today and start off where you left off.
var skipCount = 143
```

If you want to skip checking the first 143 valid phrases (since you know they don't have any balance.)

**Comment by dabura667** [comment]
check the source in the original script above (I have edited my comment a few times, make sure you have the latest version of the script)

**Comment by otziman** [comment]
Oh I see now, so I can start from the point I stopped.
Can I ask why it still continues checking after getting 2 or 3 limit rate exceeded messages..
I actually recovered one of old wallets like that, (yes it was partly words again :()

**Comment by dabura667** [comment]
> Can I ask why it still continues checking after getting 2 or 3 limit rate exceeded messages..

Once that happens you can hit Ctrl + C and your command prompt will kill the node process.

The reason why is because once the script tells you all the valid phrases, it sends off every request to insight very quickly. It takes insight a while to process each request, so it takes them all time to come back, and so if you go over the limit, all of the requests are already been sent, so a bunch of rate limit errors will come back all at once.

I could probably fix that so that one rate limit error would stop the process, but it doesn't really matter, you can just stop it manually with Ctrl+C

**Comment by otziman** [comment]
No no you don't need to write, I know now, I should stop for another day if exceeded...
And the skip number is not written anywhere right? I mean I have to count them no transactions one by one?
Thanks for the huge effort!

**Comment by dabura667** [comment]
actually it's 10800 requests per 3 hours.

So you only need to wait 3 hours.

**Comment by otziman** [comment]
10800 combinations for every 3 hours?

**Comment by dabura667** [comment]
is what the source says

https://github.com/bitpay/insight-api/blob/prod2/plugins/ratelimiter.js#L13

**Comment by dabura667** [comment]
I thought you only would have around 250 valid phrases (so only 250 requests)

Have you just been running the same script over and over?

**Comment by dabura667** [comment]
if all 250 (or however many valid phrases you have) come back saying "no transactions" then that means that you must have messed up the order, or something else.

**Comment by otziman** [comment]
With changing some of the words yes I've been running the script. 
I know 6 words sure but one of other 6 has wrong root I think..
Order is right, since my partner wrote it down on an order with shortened words, indeed 3 wallets like that, I recovered the other 2 but this is the wallet that she sent money in :/

**Comment by dabura667** [comment]
ok, well good luck.

If you have any questions about how the script works, let me know.

**Comment by otziman** [comment]
Thank you man! If only... With 6 full words and 6 words with first 3 letters the combinations are 12k and it doesn't even start so I'm trying to go easy on it with different combis 3-6k combinations..
Think rate exceeded right now anyways so I stop :/

**Comment by dabura667** [comment]
by the way

```javascript
wordPartsArray.forEach(function (wordPart) {
  candidates.push(Mnemonic.Words.ENGLISH.filter(function (word) {
    return word.slice(0, wordPart.length) == wordPart
  }))
})
```

This part means "for each wordPart, add an array filtered from the English mnemonic list where the filter condition is that the first part of the word is equal to the word part."

If you wanted to get all candidates that contain those letters (not necessarily at the beginning)

```javascript
wordPartsArray.forEach(function (wordPart) {
  candidates.push(Mnemonic.Words.ENGLISH.filter(function (word) {
    return word.includes(wordPart)
  }))
})
```

or all candidates that END with the word part

```javascript
wordPartsArray.forEach(function (wordPart) {
  candidates.push(Mnemonic.Words.ENGLISH.filter(function (word) {
    return word.slice(-wordPart.length) == wordPart
  }))
})
```

**Comment by otziman** [comment]
Like I said, she thought she should get over with it asap when backing up the wallet because she didn't know it was back-up. She wrote words down with order. 4 letter words are written and some 3 letter words like dis-, val-, man-, etc so I have the beginnings and orders for sure.. Of course if it's aff- or att- she can't read,!! Oh man, women and technology... :( my bad!

**Comment by otziman** [comment]
How do I know where to start next time after rate limit exceeded? Do I count the "no transactions"
or is it written somewhere?

**Comment by dabura667** [comment]
Here, I'll change the script so it tells you the number... holdon.

**Comment by dabura667** [comment]
https://gist.github.com/dabura667/33e629fc8ee5a2f736f08b93c0a764e3

I moved the script to a gist, this thread is getting long enough, as is.

**Comment by dabura667** [comment]
Let's continue this on gitter. You can log in to it using your git account. It is like a chat app for github.

https://gitter.im/dabura667

**Comment by JDonadio** [comment]
Thanks for the amazing support @dabura667.
