### ISSUE TITLE
Upgrade BitPay Howto?

### ISSUE THREAD

**Issue by Riceman1** [bitpay/copay#5866]
Hi,  I am new to Bitpay and want to know the process of upgrading.  My fear is of course loosing the Bitcoin i have in the wallet.  Can someone point me to a "how to upgrade" page?  Thanks

**Comment by JDonadio** [comment]
Why have you fear to upgrade your app? If anything happen to your wallet, you can always recover your funds with your backup either 12 words or file/text file format. Be sure to get backed up your wallet and upgrade with conffidence.

For mobile apps, just upgrade from the storages. 
For desktop you must visit www.bitpay.com/wallet and download/install the new version.

**Comment by JDonadio** [comment]
How it goes?
