### ISSUE TITLE
How to locate wallet.dat file on Mac

### ISSUE THREAD

**Issue by themovement919** [bitpay/copay#5867]
I am using mas os Sierra 10.12.4 and i have the latest version of copay and bitpay wallets installed, where can i locate the wallet.dat file?

If i uninstall bitpay/copay from my computer will it remove the wallet.dat file also?

thanks guys

**Comment by JDonadio** [comment]
Hi there,

There is not file such as ".dat", that file is used in `bitcoind`. Bitpay App/Copay use Chrome storage with "ldb" extension. In OSX are located at:

~/Library/Application Support/bitpay/Default/Local App Settings/<app id>/*.ldb

**Comment by themovement919** [comment]
Thanks for the help. Is there a way to delete all transactions that appear on the Application?

**Comment by JDonadio** [comment]
Is not possible because even if you delete it locally when the app is started will check the txs status for synchronize them directly from the server.

**Comment by JDonadio** [comment]
The only way to "delete" your history is moving your funds to a fresh wallet
