### ISSUE TITLE
Excessive fee when receiving bitcoin

### ISSUE THREAD

**Issue by bitcrzy** [bitpay/copay#5868]
Hi there, for some reason when I RECIEVE bitcoin there's a big amount of fee showing up on the screen

IE. received 0.0444444 BTC
     fee:  0.071693

I don't understand why there is a such a large fee?  I've compared with other people when they receive BTC, they somehow get a fee wayyyy less. 0.0003716

Can someone please help me understand what's causing this excess fee in my account?

Thank you

**Comment by bitcrzy** [comment]
Support request

**Comment by bitcrzy** [comment]
#supportrequest

**Comment by dabura667** [comment]
You don't pay the fees on received bitcoins.

That is showing you how much fees the person sending to you paid. You don't pay that fee.

**Comment by dabura667** [comment]
@JDonadio We should hide the fee on the transaction details for received bitcoins, it confuses people who don't understand how bitcoin works.

**Comment by JDonadio** [comment]
We added that info based on:  https://github.com/bitpay/copay/issues/3959

Also was a good point for all of us, IMO shouldn't be a problem but maybe we can add some toggle functionality or something...

**Comment by JDonadio** [comment]
Closed because is not an issue. Feel free to continue the fee discussion here.
