### ISSUE TITLE
Error accessing Gildera Account from Copay

### ISSUE THREAD

**Issue by jamesfmay** [bitpay/copay#5869]
After I login with my credentials, then I click to allow access to bitpay then get the following error:

This site can’t be reached

The webpage at copay://glidera?code=961ef61abce2a0043a0c294714ed6bb3 might be temporarily down or it may have moved permanently to a new web address.
ERR_UNKNOWN_URL_SCHEME

**Comment by jamesfmay** [comment]
However I can login fine bringing up a separate browser

**Comment by matiu** [comment]
what platform are you using?

**Comment by benwelt** [comment]
I'm having the same issue.

**Comment by JDonadio** [comment]
In order to help you guys we need more information about your scenarios, please provide us your platform, app version and whatever other information that you think it's relevant for you (i.e screenshots)

**Comment by benwelt** [comment]
Copay v3.0.6. 
After clicking the buy or sell Bitcoin button and selecting Glidera, I am routed to the Glidera web page to login. After logging in, it asks permission to allow copay to access my information. When the confirm button is clicked, a broken page is opened showing this error:

The webpage at copay://glidera?code=961ef61abce2a0043a0c294714ed6bb3 might be temporarily down or it may have moved permanently to a new web address.
ERR_UNKNOWN_URL_SCHEME

**Comment by benwelt** [comment]
I'm using Android

**Comment by jamesfmay** [comment]
Android...BTW, same thing happens trying to access Coinbase

**Comment by benwelt** [comment]
I found that the code contained within the URL in the error message is the confirmation code that you need for the app. Just copy and paste it.

**Comment by cmgustavo** [comment]
Please, see https://github.com/bitpay/copay/issues/5891#issuecomment-297076251 for a workaround.
