### ISSUE TITLE
Bought a $5.00 Amazon gift card no problem, tried to buy another, account suspended

### ISSUE THREAD

**Issue by jdc-cunningham** [bitpay/copay#5870]
Hello,

I'm trying to buy small increments in Amazon giftcards as the price of bitcoin goes up, today when I tried to buy another $5.00 I was prompted with a message saying "Account suspended" on my Copay Android app.

**Comment by jdc-cunningham** [comment]
Will contact support@bitpay and see what they say.

**Comment by matiu** [comment]
can you send a screenshot please?

**Comment by jdc-cunningham** [comment]
https://goo.gl/photos/Q3mH9j2gpaPaPmNe7

Sorry I'm on mobile right now, I think I have to drag-drop to upload to GitHub directly

**Comment by matiu** [comment]
Hi,  I just check and we are having a problem with our account (From whicj
we issue the gift card) Please stand by, we wi try to solve it as soon as
possible. I will let you know here.

**Comment by jdc-cunningham** [comment]
@matiu thanks

I guess I closed this issue somehow? I don't recall wanting to unless by sending that email I thought this issue was no longer necessary. Anyway thanks for the help. Nothing was lost, I'm just wondering why I was denied to buy "account suspended"

**Comment by matiu** [comment]
thanks. it is an issue affecting all users, not particular to your. I will
write once it is fixed.

**Comment by altafx** [comment]
@matiu 8 months and no response about it being fixed, is it fixed? is this standard for BitPay people to not reply to their customers when they say they will?

**Comment by jdc-cunningham** [comment]
This issue was resolved for me. Perhaps under a different ticket but I am
not missing anything.
