### ISSUE TITLE
Sent bitcoins, never arrived.

### ISSUE THREAD

**Issue by litohed** [bitpay/copay#5876]
I sent bitcoins to a booked address that i have as a contact and i do this weekly, today my wallet says transaction has 6+ confirmations and this was made 18 hours ago, usual fee and everything. The other person hasn't received anything. What happened?

**Comment by JDonadio** [comment]
Can you provide us the transaction id and your wallet id so we can investigate it further? thanks

**Comment by JDonadio** [comment]
The recipient is a Copay/BitPay app wallet?

**Comment by litohed** [comment]
The recipient is Jaxx app wallet, the transaction is this https://insight.bitpay.com/tx/af2eb937070bc18033314322be7bf0b9dcfb38f1b6988c443f8045a6a6b06a18 I don't know where to find my wallet id

**Comment by JDonadio** [comment]
You can find it going to Settings > Wallet > More opts > Wallet info

**Comment by litohed** [comment]
1be6a0e3-0738-4602-a162-90ce674c0358

**Comment by JDonadio** [comment]
@litohed you sent `0.06552683 BTC` to `15yURGuREuREkjapdUHKdRpr7GKMDi4C43` which belongs to Jaxx app. So, if your recipient cannot see the balance in the app then should contact to support team. Copay did generated and broadcasted the transaction sucessfully so from our end there is nothing to do.

**Comment by litohed** [comment]
Okay thank you very much!
