### ISSUE TITLE
Fund pending over 24hours 

### ISSUE THREAD

**Issue by boon1880** [bitpay/copay#5879]
https://blockchain.info/tx/ca8713c8171a687a471c8e82004b9f7c68ca99126c8571241542001068510335

Please check this transaction ID. Fund is receiving pending over 24hours. 

Earlier my wallet shown pending transaction, now absolutely no more receiving show at my wallet.

**Comment by matiu** [comment]
The fees of the transaction is very low, it will take a while (if ever) to confirm. Contact the send and ask him to use higher fees next time.

**Comment by boon1880** [comment]
noted with thanx
