### ISSUE TITLE
Moving bitpay/copay to usb?

### ISSUE THREAD

**Issue by themovement919** [bitpay/copay#5880]
Is it possible to move all of the contents of Bitpay onto a USB so that it can ONLY be accessed when my USB is mounted??

thank you in advance guys :)

**Comment by matiu** [comment]
Hi, it should be possible, but I am not aware of anyone doing that before.

Please if you manage to do it, it would be nice if you could comment about the results.

**Comment by themovement919** [comment]
i have no idea thats why i am asking on here haha i would never be able to figure it out!

**Comment by JDonadio** [comment]
If you do it, please share your experience with us!
