### ISSUE TITLE
Transaction

### ISSUE THREAD

**Issue by Gershon334** [bitpay/copay#5881]
Please coins recieved by this address has disapeared from my transactions 
the coins was also deducted please help

1HoQfBdabctRebvtpDEzGk5BYmrnC5ZNnj

**Comment by matiu** [comment]
There are not transactions for that address, you can check a block explorer, like:

https://blockr.io/address/info/1HoQfBdabctRebvtpDEzGk5BYmrnC5ZNnj

**Comment by JDonadio** [comment]
These funds were sent to another address, with sure. You must get the transaction id in order to view the detail in any block explorer.

**Comment by gabrielbazan7** [comment]
@Gershon334 if you still need assistance reopen the issue please.
