### ISSUE TITLE
How to reset/refresh my blockchain wallet

### ISSUE THREAD

**Issue by radenf54** [bitpay/copay#5887]
Pls guide me is there any way to refresh my wallet blockchain.
2. Y now it takes very long time to confirm sending/recieving btc approximate 9 to 11 hours or more
3.Why when I send btc n check the blockchain it shows no trxns
Your immediate n prompt respond appreciated.
Regards,
Faharudin

**Comment by JDonadio** [comment]
Do you mean how to reset/refresh Copay? If your problem is the confirmation time you must check your fees, probably they are low and the confirmation time will take a couple of hours.

**Comment by JDonadio** [comment]
In Copay there is not a reset/refresh option. Explain your case in detail so I can assit you better.

**Comment by gabrielbazan7** [comment]
@radenf54 re-open the issue if you need more help. Take a look to the Copay FAQ, could be useful for you https://github.com/bitpay/copay/wiki/COPAY---FAQ.
