### ISSUE TITLE
No push notification

### ISSUE THREAD

**Issue by MrTschi** [bitpay/copay#5888]
Since the Major Update the iOS Push Notification for received payments stops working. 
Push Notification is enabled in the settings and the iOS device.

**Comment by gabrielbazan7** [comment]
Can you try disabling and then enabling the push notifications ?

**Comment by MrTschi** [comment]
I tried turning it off and back on but didn't fixed the issue.

**Comment by gabrielbazan7** [comment]
So, just to be sure, in your phone settings -> notifications -> Copay or Bitpay the Allow Notifications switch is on? And, inside the app settings -> notifications ->  the enable push notifications switch is also on ?

**Comment by MrTschi** [comment]
![img_1858](https://cloud.githubusercontent.com/assets/9491895/25451434/76649b0e-2ac2-11e7-87b2-65c95c2d61b9.PNG)
![img_1859](https://cloud.githubusercontent.com/assets/9491895/25451433/7662f768-2ac2-11e7-852e-fdae94812ed1.PNG)

**Comment by cssxn** [comment]
@JDonadio 

I did not find any plugin of Cordova for notification in configuration files. What's the plugin called?

**Comment by cssxn** [comment]
@JDonadio  what platforms does it support?

**Comment by cmgustavo** [comment]
Firebase: `cordova-plugin-fcm`. Support Android and iOS.

**Comment by MrTschi** [comment]
With the previous version of the CoPay App push notification worked as expected...

**Comment by swehrli** [comment]
Same here. Push notifications stopped working after switching to Firebase. Tried to toggle off/on and checked the settings, no push notifications at all.

**Comment by gabrielbazan7** [comment]
We notify the user only when is out the app. Also we recently make a fix, that add new wallets to the push notifications service if it is on. This issue still valid?

**Comment by MrTschi** [comment]
- App is closed and I still did NOT receive push notifications when I receive a payment
- Its not a new wallet, I updated the App to the latest version and after that push stops working. 
- Issue still exists for me (iPhone 6, iOS  10.3.2)

**Comment by swehrli** [comment]
Same here. I still get no push notifications.

* App is closed
* Existing wallet migrated to the latest version
* iPhone 7 with iOS 10.3.2 and Copay v3.2.1

**Comment by JDonadio** [comment]
Should be ok now. If the error persist please report here
