### ISSUE TITLE
Fees extreamly ridiculous

### ISSUE THREAD

**Issue by joseravelo** [bitpay/copay#5893]
I have like BTC 0.010 and trying to send but every time I tryed to send 0.005 It says that only will get 0.00072 net because of the network fees. REALLY? $4 dollars for a BTC fee?, are you seriuos?... I had multiple wallets and I transfered between them and it charge me the same network fee. Did you know that Xapo.com doesn't charge anything if the amount to send or receive is larger that 0.00040900 ? yes 40 just 40 thousand satochis. Fix that problem, I don't want to loose any more satoshis with you.

**Comment by JDonadio** [comment]
Please see https://github.com/bitpay/copay/wiki/COPAY---FAQ#copay-requires-high-fees-for-low-amounts-transactions
