### ISSUE TITLE
Bit coin help

### ISSUE THREAD

**Issue by Vinnygiants** [bitpay/copay#5908]
How do I get my bitcoin's if coinbase dosent deal with a Canadian account?

**Comment by JDonadio** [comment]
You must use an external service, ATM, etc.

**Comment by gabrielbazan7** [comment]
Make sure to use as receive address of that Bitcoins you are buying, the one that Copay gives to you in the receive-tab.

**Comment by ajp8164** [comment]
Please see https://help.bitpay.com/
