### ISSUE TITLE
Allow users to add memos to received transactions, add edits to past sent transactions

### ISSUE THREAD

**Issue by jameswalpole** [bitpay/copay#5917]
For tax and reporting purposes, users need to be able to notate the sources of bitcoin income/payments. They also need way to assign more detailed notes to sent transactions after the transaction is sent.

**Comment by dabura667** [comment]
There is a memo button.

1. Tap the transaction.
2. Tap the Memo area.
3. Enter/edit the memo.
4. It gets synced with the server.

These memos can only be read by you. And can be changed as much as you want after the fact.

**Comment by JDonadio** [comment]
@jameswalpole we already have this feature, are we missing something? 😂
