### ISSUE TITLE
Super Economy Fee

### ISSUE THREAD

**Issue by asakpack** [bitpay/copay#5918]
So i have Super Economy selected and the fee for this policy is blank.  Yet when i go to pay it say not enough bitcoin for fee and doesn't list the fee.

What is the fee isn't blank zero?  if above zero then it should say the amount or say variable in settings and then say when trying to pay.

**Comment by gabrielbazan7** [comment]
Sorry, that is a known issue. Should be fix this week in the next release.

**Comment by JDonadio** [comment]
Could you try using **Economy**? _Super Economy_ actually is not working well and probably your transaction take a long time to be confirmed. We'll send a new release probably this monday.

**Comment by asakpack** [comment]
@JDonadio i could if it didn't cost so much in fee, thats why i was going for the slow but free option.  wouldn't have enough to get the thing i wanted if i choose that one.

@gabrielbazan7 thats awesome, hope its free or near that

**Comment by gabrielbazan7** [comment]
@asakpack maybe the better option for you is to use the "Send Max" feature. You could find it in the amount view. Feel free to open this issue again if you have more questions.

**Comment by alqaby** [comment]
Below is the issue and its still pending even though it was said couple of months ago that it will be rectified. 

So i have Super Economy selected and the fee for this policy is blank. Yet when i go to pay it say not enough bitcoin for fee and doesn't list the fee.

What is the fee isn't blank zero? if above zero then it should say the amount or say variable in settings and then say when trying to pay.
