### ISSUE TITLE
Sweeping Testnet Paperwallets ?

### ISSUE THREAD

**Issue by jflowers1974** [bitpay/copay#5922]
Just wondering if this functionality was ever implemented in the software.  I know livenet works - but trying out an educational experiment of late.  Any help greatly appreciated.

Thanks in advance

**Comment by JDonadio** [comment]
That's right, actually it's working for livenet wallets only. Maybe we could add it soon.

**Comment by jflowers1974** [comment]
Thanks - that was fast :-)  Totally understand.
