### ISSUE TITLE
Where did the Public Key file for verification of the installer go?

### ISSUE THREAD

**Issue by Planet6** [bitpay/copay#5923]
I can't find the public key file with which I can verify the integrity of the installer.

Old link gives 404: https://github.com/bitpay/copay/releases/download/bitpay/FE8956EA.asc

**Comment by dabura667** [comment]
https://pgp.mit.edu/pks/lookup?op=get&search=0x41D7D909FE8956EA

Check the keyservers. MIT being the most popular.

**Comment by dabura667** [comment]
`pub  4096R/FE8956EA 2013-07-31 Jason Dreyzehner <jason@bitpay.com>`

**Comment by Planet6** [comment]
Thanks!

**Comment by Planet6** [comment]
Maybe a dumb question but where can i find the fingerprint?

**Comment by dabura667** [comment]
https://pgp.mit.edu/pks/lookup?op=get&search=0x5CD600A61112CFA1

`pub  2048D/1112CFA1 2014-07-09 Copay (visit copay.io) <copay@bitpay.com>`

**Comment by Planet6** [comment]
@dabura667 

And how do verify the fingerprint of said certificate ?  Only the last part is shown : 5CD600A61112CFA1

Using GPG4WIN (cleopatra)

**Comment by dabura667** [comment]
Google "GPG4WIN verify full fingerprint"

first result:
https://www.gpg4win.org/doc/en/gpg4win-compendium_16.html

Looks like the full fingerprint is shown on the "Certificate Details" window.

**Comment by dabura667** [comment]
You can also check the full fingerprint on MIT by searching for the full fingerprint.
https://pgp.mit.edu/pks/lookup?op=get&search=0x9D17E656BB3B6163AE9D71725CD600A61112CFA1

**Comment by Planet6** [comment]
"Google "GPG4WIN verify full fingerprint" " I know how to use GPG4Win. See my post above.  But matching the fingerprint is an essential part of the verification process!

Example of published fingerprint: https://linuxmint.com/verify.php

 "You can also check the full fingerprint on MIT by searching for the full fingerprint."  This was the info I was looking for. Thanks
