### ISSUE TITLE
Error generating address on receive view

### ISSUE THREAD

**Issue by cmgustavo** [bitpay/copay#5930]
I select a wallet and get an error while trying to generate a new address. But I already have an address. So, if I have an address and get error, just show this one.

![windows_10](https://cloud.githubusercontent.com/assets/237435/25348075/6dbccf06-28f3-11e7-8d39-ddb6b4963165.png)

![windows_10 2](https://cloud.githubusercontent.com/assets/237435/25348084/72016108-28f3-11e7-86e9-7b194df9249c.png)

**Comment by JDonadio** [comment]
Also the error message is not clear.

**Comment by cmgustavo** [comment]
Dup. #5849
