### ISSUE TITLE
Transfer of .25 BTC to my Copay wallet shows a 0.0213 Fee on the Blockchain.  That's over $26!!

### ISSUE THREAD

**Issue by letitbegood** [bitpay/copay#5931]
Hello,

I just recently transferred .25 BTC from my Coinbase account into one of my CoPay wallets.  

Coinbase shows that 0.2504972 BTC was sent from my account which would seem normal (.25 BTC + .0004972 for the fee), and CoPay shows that I received .25 BTC into my account.  But according to the Blockchain, the transaction shows that the file size was 9660 bytes in size and the fee was 0.0213356 BTC, which is over $26 US.

Can this really be correct?  Did I have to pay 0.0213356 BTC for this transfer?

The transaction ID is: 29c2e25e588b8ca63d72c3e282256b624d1f890b324c9ba1729dbff1a0fa063e

Thank you for your assistance,

Alan Austin

**Comment by JDonadio** [comment]
Hi there, unfortunately you're right, that tx was paid with ~26 USD just for the fee. In this case Copay are only showing the fee in the received transaction, which is the same showed in the block explorer, but the transaction was created and broadcasted from Coinbase and you should contact with the support team to be assisted better.

**Comment by aga69** [comment]
Hi, thanks for the quick reply.  Something definitely does not make sense. I will contact Coinbase, although I have not had much success getting any response from them on other questions I have had.  

One other question for you.  Can you confirm that the actual amount showing in my CoPay wallet is .25 BTC?

Thanks.

**Comment by JDonadio** [comment]
I was reviewing your transaction and you have many inputs, so that's the main reason for the high fee. Take a look at [this](https://github.com/bitpay/copay/wiki/COPAY---FAQ#copay-requires-high-fees-for-low-amounts-transactions) entry to understand a little more what happend with your transaction.

**Comment by aga69** [comment]
Hi Javier,

Sorry, I am a little new to all of this, but are the inputs you are referring to the 100 or so links that show up on the left of the transaction page?

If so, I do not see how this makes any sense.  I just recently set up my Coinbase account.  The only money that has come into that account has been through purchases on their exchange.  None of the purchases were for less than $50 US, and several purchases were for a higher amount than that.  So sending .25 BTC ((around $300) would not have used more than 5 or 6 of the purchases (which I believe are the inputs?).  So I am not sure where these 100 or so inputs came from.

Since Coinbase shows that 0.2504972 BTC was taken out of my account, and CoPay shows that .25 was received, that would only leave 0.0004972 BTC left (around 60 cents).  If this is the case, I am not sure how there could have been a transaction fee of 0.0213356 BTC ($26).  Is it possible the rest was paid for by someone else (i.e. Coinbase)?

Still waiting for a response from Coinbase so thought I would ask you.

Thanks again.

**Comment by JDonadio** [comment]
> Sorry, I am a little new to all of this, but are the inputs you are referring to the 70 or so links that show up on the left of the transaction page?

Yes, all of that inputs made your transaction big.

> I do not see where it shows .25 BTC for the fee (.25 BTC is the amount I sent). What I see on the page is a fee of 0.0213356 BTC. 

The explorers shows the rate, not the fee amount itself. Before send any transaction you must to check how much fee are you spending to avoid cases like this. Copay display the rate and value (click to switch) but I don't know how Coinbase shows that info.

> Regardless, is it possible that Coinbase bundles several transactions together and the fee is paid by others as well?

We don't know, you must to ask to the support team.

**Comment by dabura667** [comment]
That is very possible.

They might have bundled your transaction together with other people and only show you "your portion" of the fees.

**Comment by letitbegood** [comment]
Thanks again for your responses. Coinbase does not show the fee prior to sending, but from getting more info it sounds like they bundled this together with other transactions.

Regarding the Copay app, I have just a couple of other questions: 

1. I created 2 wallets on my Copay app.  If I want to send BTC from one wallet to the other, does this go through the blockchain where paying transaction fee would be recommended?  Or does this happen off the chain with no fee?

2. One thing I've noticed with the Copay app is that it seems to use much more battery than many of the other apps I have on my iPhone. For this reason, I thought I would test out the BitPay app along side the Copay app to see if there is any difference.  My question is: If I import my wallet seeds into BitPay and play around with it, will this still keep my wallets on Copay as well?   If so, if I make a transaction on one app will the other be updated since they use the same seed?  Or could this pose a problem since one of the apps would create new wallet addresses without the other knowing about it?

**Comment by JDonadio** [comment]
> 1. I created 2 wallets on my Copay app. If I want to send BTC from one wallet to the other, does this go through the blockchain where paying transaction fee would be recommended? Or does this happen off the chain with no fee?

Yes, the transaction will go through the blockchain including the fee amount.

> 2. One thing I've noticed with the Copay app is that it seems to use much more battery than many of the other apps I have on my iPhone. For this reason, I thought I would test out the BitPay app along side the Copay app to see if there is any difference. My question is: If I import my wallet seeds into BitPay and play around with it, will this still keep my wallets on Copay as well? If so, if I make a transaction on one app will the other be updated since they use the same seed? Or could this pose a problem since one of the apps would create new wallet addresses without the other knowing about it?

Yes, if you have the same wallet in both apps all of your transactions moves will be synchronized either in Copay as in BitPay app.

**Comment by letitbegood** [comment]
Thank you.  Sorry, one final question and then I will close the comment thread.  Does the full synchronization you are referring to in question #2 apply to any wallet that allows the import of a 12 word seed, are is this synchronization only between Copay and BitPay?

**Comment by JDonadio** [comment]
Yes, and all of the different platforms available. You can import the same seed in both apps and also in any platform with the full sync 😉

**Comment by letitbegood** [comment]
Excellent, thanks for all of the prompt responses.
