### ISSUE TITLE
Improve visualization of tx fee for incoming txs

### ISSUE THREAD

**Issue by isocolsky** [bitpay/copay#5932]
Currently the `fee` value is shown. This is confusing for new users. It would be great if we could:

1. Show `fee per kb`/`sat per byte` instead of fee. This value is more appropriate as it takes the size of the tx into account. Also there are several online services that track this value (e.g. https://bitcoinfees.21.co/)

2. Show the legend 'paid by sender'. This would avoid new users thinking they received less than the tx amount into their wallets.

**Comment by JDonadio** [comment]
Related https://github.com/bitpay/copay/issues/5868

**Comment by cmgustavo** [comment]
Closes #6037
