### ISSUE TITLE
i buy amz gift card 100$ by BTC at copay but no card

### ISSUE THREAD

**Issue by golfistyle** [bitpay/copay#5933]
![18159569_1540162669350544_904101272_o](https://cloud.githubusercontent.com/assets/27992421/25371001/91873578-29b8-11e7-86bb-9861507710f7.png)
![18119829_1540164872683657_268828165_o](https://cloud.githubusercontent.com/assets/27992421/25371005/9594c478-29b8-11e7-96db-8cde67467466.png)
![18175611_1540162742683870_1613181116_o](https://cloud.githubusercontent.com/assets/27992421/25371008/99cca7b8-29b8-11e7-8dc3-479abdf4e101.png)

normally i buy every 1-2 days but today have some problem like this
1 buy AMZ GC 100$ by BTC but no card coming or any pending.
Please check and update forme 
Thank you.

**Comment by JDonadio** [comment]
Hi @golfistyle, sorry about that. Can you please provide us the transaction id ?

**Comment by golfistyle** [comment]
![18143127_1540788565954621_668007331_n](https://cloud.githubusercontent.com/assets/27992421/25395433/35a6630c-2a0b-11e7-83b0-3b08bad73bc2.png)

Transaction : c77598ae828bb1f88ccf2c4263c814e404a7f72f4fb6aafd39b1a2d29fdcf561

**Comment by JDonadio** [comment]
Thanks, we'll take a look and keep you posted.

**Comment by golfistyle** [comment]
Thank

**Comment by JDonadio** [comment]
Please, contact me: javier@bitpay.com

**Comment by JDonadio** [comment]
Or matias@bitpay.com

**Comment by golfistyle** [comment]
i'm send mail to you already

**Comment by golfistyle** [comment]
my mail
golffiesmmm@gmail.com

**Comment by JDonadio** [comment]
Solved 😉
