### ISSUE TITLE
Will you add Opt-in Replace-by-fee feature?

### ISSUE THREAD

**Issue by zono** [bitpay/copay#5935]
Do you have a plan to add Replace-by-fee feature? (Feature which is allowing users to create replaceable transactions and replace it) If not, I want to know the reason? (low demand, implementation costs, Replace-by-fee has something risks, etc)

**Comment by dabura667** [comment]
I don't know of any plans.

One huge reason is that it is hard to create a UI that accurately portrays what is going on to the user.

I have used RBF in Electrum and Bitcoin Core (through CLI) and had extremely weird UI bugs that would probably melt a normal user's brain.

**Comment by martindale** [comment]
It shouldn't be hard to add a button in the transaction history that says "bump" — then simply render a small UI that allows for a fee increase.

I'm curious where existing signed transactions are stored; this would help me scope out an implementation and maybe even get a demo working.  Any help from @matiu here?

**Comment by matiu** [comment]
We don't see demands from our users for RBF, and will introduce some risks, so this is not  a prioriti right now.

**Comment by martindale** [comment]
Can you direct me to an overview of the latest design for Bitcore so I can go implement this myself?
