### ISSUE TITLE
Images, Licence?

### ISSUE THREAD

**Issue by wzup** [bitpay/copay#5936]
Couldn't find any emails on your site. And the link you provided follows here. So I ask here.

Are some images in your site under any licence? May I use them for my work, for my site? Most probably for the same purpose - demonstrate sample app screenshots. I'm asking about images of the phone:

https://copay.io/images/secure-payment-phone.6547cda6.png
https://copay.io/images/livenet-testnet-base.994674bb.png
https://copay.io/images/faces-cell.0674131a.png
https://copay.io/images/code-trust.c76d3025.png
https://copay.io/images/base-phone.28f413ca.png
https://copay.io/images/code-phone-base.7e7bc484.png

If I they are under licence, would you please provide me with links where I could purchase them?

Thank you

**Comment by JDonadio** [comment]
@bitjson can you clarify this?

**Comment by bitjson** [comment]
Hey @wzup – you can find Apple's official product images and licensing info here: https://developer.apple.com/app-store/marketing/guidelines/#images

Hope that helps!
