### ISSUE TITLE
npm run final:android Error 

### ISSUE THREAD

**Issue by hhai9x** [bitpay/copay#5942]
"npm run start:android" run successfully.
I try to building the release version using "npm run final:android" and get error:  

> 
> > copay@3.0.6 sign:android E:\copay-3.0.6
> > rm -f platforms/android/build/outputs/apk/android-release-signed-aligned.apk;
> jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ../copay.keysto
> re -signedjar platforms/android/build/outputs/apk/android-release-signed.apk  pl
> atforms/android/build/outputs/apk/android-release-unsigned.apk copay_play && ../
> android-sdk-macosx/build-tools/21.1.1/zipalign -v 4 platforms/android/build/outp
> uts/apk/android-release-signed.apk platforms/android/build/outputs/apk/android-r
> elease-signed-aligned.apk
> 
> **'rm' is not recognized as an internal or external command, operable program or batch file**
> 

How to resolve that issue? Please help! Thank you!

**Comment by gabrielbazan7** [comment]
That's Windows ? You are using Git bash ?

**Comment by hhai9x** [comment]
@gabrielbazan7 Sorry for late.
And thank you.
That's Window and I try to using Git bash. That's Ok but I get other Error: 

> copay@3.0.6 sign:android E:\copay-3.0.6
> rm -f platforms/android/build/outputs/apk/android-release-signed-aligned.apk; jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ../copay.keystore -signedjar platforms/android/build/outputs/apk/android-release-signed.apk  platforms/android/build/outputs/apk/android-release-unsigned.apk copay_play && ../android-sdk-macosx/build-tools/21.1.1/zipalign -v 4 platforms/android/build/outputs/apk/android-release-signed.apk platforms/android/build/outputs/apk/android-release-signed-aligned.apk

rm: unknown option -- e
Try 'rm --help' for more information.

**Comment by hhai9x** [comment]
(Window) This issue has been resolved!
I using Git bash and I change package.json at line 111:
";" -> "&&"

> "sign:android":  rm -f platforms/android/build/outputs/apk/android-release-signed-aligned.apk; jarsigner -verbose -sigalg SHA1withRSA.......


to

> "sign:android":  rm -f platforms/android/build/outputs/apk/android-release-signed-aligned.apk **_&&_** jarsigner -verbose -sigalg SHA1withRSA.......

It worked.
