### ISSUE TITLE
Offering $350 bounty for unconfirmed BTC stuck on blockchain.

### ISSUE THREAD

**Issue by bnkprc** [bitpay/copay#5943]
I have time sensitive BTC worth $1300 stuck on blockchain. The funds show up in my wallet but are not accessible due to a low processing fee that seems to be stuck on blockchain. Anyone who can resolve this issue for me will get the equivalent of $350 in BTC. Any help is appreciated.

**Comment by gabrielbazan7** [comment]
Just wait. The TX will drop, normally in 72hrs.

**Comment by bnkprc** [comment]
What will happen it this point? Will the block finally go through and the
funds be available ? Or will the transaction itself drop?

**Comment by gabrielbazan7** [comment]
The transaction will drop. It's like the sender never sends you anything.

**Comment by dabura667** [comment]
There is a way to pull in the funds and (with a high chance) ensure that the money will arrive in your wallet and not return in the senders wallet.

It's called CPFP (Child Pays For Parent) and can be done with a simple script using bitcore-wallet-client

I would write one for you, but it is 2am and I am sleepy.

**Comment by bnkprc** [comment]
If the transaction drops I'm guessing I wou,d just bring it to the
attention of the 3rd party I went through, wallofcoins. The USD I paid for
the BTC was paid to his bank account. I assume the 3rd party would get
involved to either resolve this issue, correct?

**Comment by gabrielbazan7** [comment]
Yes. You should ask them for a refund or to send the bitcoins again to your wallet.

**Comment by dabura667** [comment]
@bnkprc To be honest, it is difficult to say whether the transaction will be dropped, and a refund may be difficult, as the transaction authorizing movement of the bitcoin has already been seen by the network and you never know when it could show up in a block.

Are you comfortable with using a command prompt at all?

**Comment by toomim** [comment]
I recommend trying a [transaction accelerator](https://www.viabtc.com/tools/txaccelerator/). You should be able to get this transaction in for far less than $350.
