### ISSUE TITLE
nave a income notice but not find in blockchain

### ISSUE THREAD

**Issue by Robycop1** [bitpay/copay#5945]
I recived from long time a inform to income but the action still are in waiting and in blockchain not have this movement. What can I do (The amount is 0.88488574 BTC)?

**Comment by Robycop1** [comment]
I answer myself. The problemi risolve along (I not have enough experience and I scare to lost money).
Thanks

**Comment by gabrielbazan7** [comment]
Ok. If you have more doubts feel free to open another issue. Also you could check the help center (http://help.bitpay.com/bitpay-secure-bitcoin-wallet)
