### ISSUE TITLE
[i18n] A few things

### ISSUE THREAD

**Issue by Kirvx** [bitpay/copay#5946]
- [x]  Starting should be translatable: https://i.imgur.com/we4HdW7.png
- [x]  Confirm should be translatable: https://i.imgur.com/lbeT25M.png
- [x]  Close should be translatable: https://i.imgur.com/nbU73fO.png
- [x]  Prompt and Cancel should be translatable: https://i.imgur.com/giUCdbv.png
- [x]  Alert should be translatable, No automatic capitalization for "Envoi Du Montant Maximal": https://i.imgur.com/LKDer66.png
- [x]  Automatic capitalization should be deactivated: https://i.imgur.com/Lhd5x0z.png
- [x]  "Receive in" should be translatable: https://i.imgur.com/CERkTwn.png
- [x]  "Insufficent funds" should be translatable : https://i.imgur.com/1C5YXCT.png
Also, this screen can be more simple if there is no wallets with funds, like this: https://i.imgur.com/c6GLZDp.png
___
- [x]  All fee levels should be translatable : https://i.imgur.com/3U2Vh9w.png
___
- [ ]  "Mais oui c'est clair" should be aligned with Test, Note, And Cancel : https://i.imgur.com/hpkB9Sc.png
___
- [ ]  Google Play: The slogan "Your bitcoin. Your wallet. Your terms" is auto translated: https://i.imgur.com/caZuGF6.png
If you want to conserve the anaphora "Your" in the translated french version, I suggest "Vos bitcoins. Vos portefeuilles. Vos conditions".
- [ ]  Clone French on Crowdin to French Canada, just to make very minor modifications, integration to Copay/BitPay is not a priority.

**Comment by Kirvx** [comment]
:loudspeaker:

:hammer: :clock5:

:stuck_out_tongue:

**Comment by Kirvx** [comment]
I will have another request:

- [ ] Clone French on Crowdin to French Canada, just to make very minor modifications, integration to Copay/BitPay is not a priority.

**Comment by Kirvx** [comment]
Updated.

Thanks @gabrielbazan7 for the works you did :)

**Comment by dabura667** [comment]
btw Google Play auto-translate is a feature.

Google Play doesn't allow localization of that text, it only allows English to be input and auto-translates based on the viewer's language.

**Comment by Kirvx** [comment]
@dabura667 Are you 100% sure? Bitcoin Wallet by Andreas Schildbach propose the translation of that text in the Transifex project with the ressource file "market-promo-text.txt" and it is well applied on Google Play :confused:
