### ISSUE TITLE
The iPhone learned my wallet seed

### ISSUE THREAD

**Issue by LinusU** [bitpay/copay#5947]
I'm not exactly sure that this is a bug, but I think that it could be considered some kind of security issue...

When I typed in my recovery seed, the predictive typing feature of iOS learned my wallet seed. The next time that I was typing my recovery seed in, it suggested every word as soon as I had typed in the first one.

This leads me to believe that my wallet seed is now saved somewhere in the os...

**Comment by Philos2000** [comment]
Actually, it is _you_ who gives iOS permissions to be **_predictive_**...
I guess the next time when you're typing the seed, hold down that earth button and turn off **_predictive_** will no longer let iOS learn your seed.
If you want to clear the predictions stored in your device, go to **Settings > General > Reset > Reset Keyboard Dictionary** will do.

**Comment by e5faf2** [comment]
Hey.

I think we should turn off autocorrection and autocomplete for recovery phrase input field. Its possible for iOS. Please take a look on my pull request #6082.
