### ISSUE TITLE
Receive tab shows wrong address

### ISSUE THREAD

**Issue by dskloet** [bitpay/copay#5949]
I have a 2-of-4 Copay wallet that I just wanted to send some more funds to.
I opened the Copay (Chrome) app and selected my wallet.
I verified that it was my wallet (amount and transactions looked familiar) and then clicked on the receive tab to send money to the address.
After sending, I noticed that Copay said my wallet wasn't backed up, which was weird because it definitely was.
But then I realized that the money hadn't gone to me 2-of-4 wallet, but to something called Personal Wallet, that I didn't create and didn't even know existed.

Why, after selected a specific wallet, does the receive tab show an address for a different wallet? One that's not even backed up, no less.

**Comment by toomim** [comment]
Yes, this affected me too. See https://github.com/bitpay/copay/issues/5808
