### ISSUE TITLE
Problem with an amazon giftcard

### ISSUE THREAD

**Issue by kromoxpro** [bitpay/copay#5951]
I bought an amazon giftcard and when I went to redeem it appeared locked, I canceled the giftcard in my copay wallet and I have not refunded the money. 

Why did it appear Locked?

Please help me.

**Comment by EJupiter817** [comment]
Please email help@bitpay.com with the following details so we can assist you further.

- Current device & operating system
- Current version of the wallet used
- Screen shot
- BitPay Wallet ID - To get your Wallet ID, open your BitPay application, then go to Settings > Wallets & Integrations > More Options > Wallet Information.
