### ISSUE TITLE
Custom Amount page's "Finish" button is ambiguous

### ISSUE THREAD

**Issue by toomim** [bitpay/copay#5956]
1. Click receive
2. Click on the address text string
3. Click "request a specific amount"
4. Type in an amount

Now you're on the "Custom Amount" page, and there's a "Finish" button in the upper-right. It's not clear what that does. The user might think that they need to finish requesting a specific amount before sending money to it. However, if they click this button, the whole page will disappear! And then they will have to start the process over again. That's a pretty annoying UI bug.

**Comment by dabura667** [comment]
+1

**Comment by gabrielbazan7** [comment]
Any suggestion ?

**Comment by toomim** [comment]
It should be called "Close."
