### ISSUE TITLE
Where did the Sweep Function go in 3.x?

### ISSUE THREAD

**Issue by dmo580** [bitpay/copay#5957]
Did this functionality go away? I looked in every corner of settings and could not find it (iOS, Android, Chrome)

**Comment by dabura667** [comment]
Scan a private key QR code using the scan button. It will pop up with "sweep private key" option.

**Comment by dmo580** [comment]
Hi I appreciate this information. I think it would be useful if one could sweep a private key by entering it/copy paste. QR code is nice, but there should be multiple input methods.
