### ISSUE TITLE
Where does Bitcoin go?

### ISSUE THREAD

**Issue by expertschoice** [bitpay/copay#5961]
I have just swept a paper wallet to my copay wallet and still, after 2 days, have an Unconfirmed Transaction.  I understand that this transaction will disappear after 48-72 hours and the Bitcoin will return to my paper wallet.

I just tried to sweep the paper wallet again, using a higher transaction fee, but it seems that the paper wallet has a zero balance now. 

Just curious, **where** is the Bitcoin that was swept from the wallet? Its not in the paper wallet and not in the wallet it was sent to.  Where exactly is it?

Just curious. I'm new.

**Comment by dabura667** [comment]
rescan

**Comment by dabura667** [comment]
Also, do you have multiple wallets on your Copay? Did you check all of them for the balance?

**Comment by expertschoice** [comment]
I have re-scanned the paper wallet and received the message "no funds found". I re-scanned with Copay and Bitpay both, as I have both installed on my phone. "No Funds Found" message on both tries.

Yes, I have two accounts (wallets) on my Copay, and I have checked them both. The wallet that I swiped the paper wallet to has that amount in it (0.31 BTC) but it is not available as it is "UnConfirmed"

**Comment by dabura667** [comment]
What version are you using? What is your fee setting at? (Priority? Economy?)

Current version (v3.1.3) has dynamic fees. Older versions had a flat fee.

v3.1.3 grabbing dynamic fees
https://github.com/bitpay/copay/blob/v3.1.3/src/js/controllers/paperWallet.js#L63

v2.7.0 wallet not dealing with fees at all, is then handled by bitcore-wallet-client as flat fee of 0.0001 BTC
https://github.com/bitpay/copay/blob/v2.7.0/src/js/controllers/paperWallet.js#L76
https://github.com/bitpay/bitcore-wallet-client/blob/bded7572002fa756243b0aaabb51a4af0e6acf54/lib/api.js#L660

**Comment by dabura667** [comment]
v3.1.3 went live on the Apple appstore on April 27th.

**Comment by expertschoice** [comment]
I am using Copay version 3.1.3.  But when I first did the sweep, I was using an earlier version. I updated Copay to the latest version this morning, thinking that the upgrade might help. It didn't.

The earlier version had a fee of 0.0001 BTC as I remember.

**Comment by expertschoice** [comment]
The earlier version of Copay was set to "Normal" fee setting, I think.  This is the version that I used when I did the sweep of the paper wallet.

**Comment by dabura667** [comment]
How many bytes was the transaction?

The blockchain explorer should say how many bytes it is.

**Comment by expertschoice** [comment]
191 bytes.

https://blockchain.info/address/1PiFpig5ByKZ5Cyik9b5ho51XUn3HiVdcx?filter=4

**Comment by dabura667** [comment]
Ok, this should be manageable.

1. Turn on "use unconfirmed funds" in advanced options.
2. Change fee rate to "Urgent"
3. Copy an address of your own wallet.
4. Send to your address, tap the upper right to select "Send all funds" and it will send your money with a high fee to one of your own addresses.
5. Go back and disable using unconfirmed and set your fee rate back to what you had it as.

This should get your bitcoins to comfirm quickly.

**Comment by expertschoice** [comment]
Thanks. I followed your instructions and am waiting for confirmation. It's been 9 minutes so far.

**Comment by expertschoice** [comment]
Thanks!  It took an hour but finally, all transactions confirmed and all is well now.

**Comment by dabura667** [comment]
You're welcome!

Just FYI, the current version now sweeps with a proper fee (following the fee setting of your app currently).
