### ISSUE TITLE
How can i delete an unconfirmed transaction in my Electrum wallet

### ISSUE THREAD

**Issue by popsmail2015** [bitpay/copay#5962]
I have an unconfirmed transaction for 48 h , after my transaction was rejected by   blockchain Node (Transaction rejected by our node. Reason: Transaction was previously accepted but has been pruned from our database.), but in my Electrum wallet, no update from the network (still unconfirmed transaction). how can i delete this transaction to resend my amount.  
regards

**Comment by dabura667** [comment]
This is not Electrum's support.

**Comment by popsmail2015** [comment]
yeah I know @dabura667 but i need help for this issue

**Comment by dabura667** [comment]
@popsmail2015 https://github.com/spesmilo/electrum/issues
