### ISSUE TITLE
Glidera payment pending

### ISSUE THREAD

**Issue by DLLRSox** [bitpay/copay#5963]
Is this normal? I entered sell of Bitcoin for USD in my wallet and the transaction is pending. Actually in area that says Payment Proposals. When selected, screen opens to Payment accepted. It will be broadcasted by Glidera. In case there is a problem, it can be deleted 6 hours after it was created.

**Comment by DLLRSox** [comment]
here is screenshot
![image1 1 1](https://cloud.githubusercontent.com/assets/28447928/25754092/0637f102-318c-11e7-8816-13131aceedf4.PNG)

**Comment by gabrielbazan7** [comment]
Sorry for the delay. You still having this issue ?

**Comment by DLLRSox** [comment]
All good thanks
