### ISSUE TITLE
Copay wallet fee = astronomical! 

### ISSUE THREAD

**Issue by emac79** [bitpay/copay#5966]
Not impressed with the copay app and the "fee" I was charged to receive only .188555 BTC (approx. $295USD) ...My fee totaled $135.79 USD! HOW IS THAT FAIR?! COPAY ROBBED ME BLIND. Is there anyway to rectify the issue? In previous copay receivables  I was charged as little as $0.42 to $5.00...but $130!? Is unacceptable. And I feel very taken advantage of. I'd like a solid explaination or majority of my BTC back. If not, I will be sure to let my other copay users know to switch. I won't be sticking around with those kind of fees especially when I didn't have an option to agree with the fee in the first place.

**Comment by emac79** [comment]
Who can I talk to? Who can actually help in this matter?

**Comment by dabura667** [comment]
1. Bitcoin transactions are free to receive. Any "fees" on a received transaction were paid by the sender, not you. No service I know of subtracts their sending fees from your amount they send. If they are doing so, please take it up with them, as that is not normal.
2. Fees calculated by Copay for sending are given to the Bitcoin miners, not Bitpay or anyone related to the Copay project.
3. Currently, bitcoin network congestion is making everyone bid higher and higher to try and get their transactions confirmed in the next block. The current average for transaction fees is about $0.75 regardless of sent amount. However, websites that sell and buy bitcoins tend to have large amounts of data requirements for sending transactions... which requires them to pay more fees.

**Comment by dabura667** [comment]
@emac79 I understand it might be hard to admit you overreacted based on a misunderstanding, but I would like to know whether or not you understood what I told you.

(I also would like to know if some website is out there scamming people like you into believing that the receiving wallet pays the fee so that they can justify cheating you out of bitcoins or something... If the site is scamming you, I would like to know.)

Which website sent you the 0.188555 BTC?

**Comment by emac79** [comment]
I'd like to send you a screen snap, because it's happened again. Gladiacoin is the company who is sending me the BTC's to copay.

**Comment by gabrielbazan7** [comment]
Copay do not charge any fee on receive transactions.

**Comment by dabura667** [comment]
Gladiacoin is a known scam.

Copay does not take, nor accept any fees. If you are being led to believe this, then you are being lied to.

**Comment by lxiaob** [comment]
I have $43 of bit coin in my wallet and tried to send them to another wallet or purchase a Amazon gift card, but I got a "insufficient funds for fee" message. What's the minimal mount the wallet holds?

**Comment by Warrioreuel** [comment]
Yup I am experiencing the same problems. Super high fees. When i first started using BTC it was around $500. Typical fees were 0.001 BTC which was about 50 cents. Now that same 0.001 means a minimum fee closer to $15-$20. I dont know where BTC is headed but for small transactions its useless, unless I am just totally clueless which is very possible. I am just leaving the current $100 in my wallet until all this transition of new services, wallets etc settles out. I will use a money order instead.

**Comment by Tuny1** [comment]
Hi!
On December 29th I received some satoshis on my Copay Wallet with a notification that says:
Amount too low to spend (฿0,0087=u$s114.-) ...
(this amount in the transaction is too low compared to the fees of the bitcoin network, to spend these funds it is required to have an amount higher than the commission required by the Bitcoin network)
Im new in all this world... Is it normal? Which amount is suppoused to be enough? Thank you, ;-)

**Comment by alvinmcduffie44** [comment]
If you want to sell large quantities of BTC, do so at www.liviacoins.com so you do not get tricked.
