### ISSUE TITLE
Purchased Amazon gift card not appearing in Copay app

### ISSUE THREAD

**Issue by StanickZ** [bitpay/copay#5967]
Buy a Gift Card for $ 47 and I have not received it, help

Windows 7 64 Bits
Copay v3.0.6
Screen shots
BitPay Wallet ID 96a742c2-62af-428f-bf9e-ddd80fc656e6 
Https://bitpay.com/invoice?id=6g7Qu8FPhyJQELzf6fcDr6

24 hours and my gift card does not appear please help!

**Comment by cmgustavo** [comment]
Please, upgrade to latest version (3.1) and check if problem persists. Thanks.
