### ISSUE TITLE
Problem with Bitcoin transaction 

### ISSUE THREAD

**Issue by Averi13** [bitpay/copay#5968]
Hi, i have a problem with bitcoin transfer from my partner. 2017-05-03 15:47:54 he sent me the amount of 9,019819 BTC, but still there is no a sign of these transaction  reflected in my copay wallet. My partner was using SpectroCoin wallet, and their support said that the transaction was processed, but not confirmed. What does that mean? Are there any problems from Copay side?

**Comment by gabrielbazan7** [comment]
You should see the transaction even is not confirmed in the wallet history on Copay Wallet. Check if the address you provide to you partner is correct.
