### ISSUE TITLE
Moving Wallet and Receiving Addresses to a New Phone - Support Request

### ISSUE THREAD

**Issue by stargem88** [bitpay/copay#5969]
I have a new Android phone and have to migrate the Copay wallet to the new Android phone, 
Currently 0.00 balance.

What I did:
Using the old phone, export the Wallet to text and email.
Installed the Copay App in the New phone, and follow the steps to create a new wallet.
Added a second Wallet and import from the copied encrypted Text from the email.
Successfully added.

Question:
I cannot see the old Receiving Addresses for the imported Wallet (from the old phone).
I have previously given the old Receiving Addresses.
When someone pays using the old Receiving Addresses, will the funds be received by the new phone?
How to view the old Receiving Addresses on the new phone?

Thanks.

**Comment by stargem88** [comment]
Please close the Support Request.

Resolved. 

Renamed the second Wallet and changed the color.
On the Receiving tab, slide left to view the second wallet and old Receiving Addresses.

Thanks.

**Comment by gabrielbazan7** [comment]
Check http://help.bitpay.com/bitpay-secure-bitcoin-wallet/do-i-still-own-old-bitcoin-addresses
