### ISSUE TITLE
swept a paper wallet but transaction seemed to be dropped for some reason

### ISSUE THREAD

**Issue by re43223546y** [bitpay/copay#5971]
Hi,
I swept a paper wallet into copay, and it just sat there, not being taken into a block for many hours. 12 hours later, I went into the "see it on the blockchain" option, the transaction seemed to be not found all together.

I check the blockchain.io. It is still unconfirmed. The fee used by copay was 0.0001 BTC, too low? I think it was specified by copay rather than myself.

What can I do not to lose it? Should I still use the old address and import again into copay or I might need to use other way ?

Thank you

**Comment by dabura667** [comment]
1. Keep your Copay app up to date. (the latest version of Copay does not have this problem anymore)
2. Check the solution here: https://github.com/bitpay/copay/issues/5961#issuecomment-299363788

(However, know that the solution I give there will only work well if the sweeping transaction is a small byte size (like less than 200 bytes) If the size of the sweep transaction is large, then you can wait for a week or so and then delete your cache and rescan.)

Just out of curiosity, how large was your sweeping transaction (in bytes)?

**Comment by re43223546y** [comment]
Thank you for the info. Yes, it worked very quickly.  Just got the first confirmation.

I'm using an old phone and could only install v2.6.0. I know I should update everything. I might not even able to now with the phone.

The fee for that problematic transaction was 192 bytes because I was sweeping a single address into copay. At the time, I thought the fee seemed a bit too small and was a little concerned. But I proceeded anyway since it was the default setting by copay.
