### ISSUE TITLE
What If Copay dies? How Do I Keep My Bitcoins?

### ISSUE THREAD

**Issue by ssakcoR** [bitpay/copay#5972]
Just like the title says. 

I have 12 words - are these usable only on Copay wallet or any other wallet?
Is there anything I should back up or write on paper (apart from 12 words) to restore my bitcoins on any other software if Copay dies? 

Thanks

**Comment by gabrielbazan7** [comment]
It is possible to recover funds from a Copay Wallet without using Copay or the Wallet Service, check the Copay Recovery Tool ( https://bitpay.github.io/copay-recovery/ )- GitHub ( https://github.com/bitpay/copay-recovery ). All you need is File/Text Backup or Wallet Recovery Phrase (12 words).

**Comment by ssakcoR** [comment]
Hi, what if that tool disappears too?

**Comment by gabrielbazan7** [comment]
You can import with the 12 words in Mycelium

**Comment by isocolsky** [comment]
Copay is open source so in the extremely unlikely event that you lose your app and the recovery tool disappears, at least someone can have access to the source code.
Also for your peace of mind, Copay's private keys are generated following Bitcoin standards BIP32, BIP44 and BIP39 which are all well documented and with multiple implementations available.

**Comment by ssakcoR** [comment]
Does this mean I can extrac those private keys from Copay and use those
anywhere else?

**Comment by isocolsky** [comment]
Not every wallet out there implements those standards. From those that do implement them, there are still some small differences. For example Breadwallet being an HD wallet (BIP32) which generates 12 words for you (BIP39) does not follow the path structure for key derivation specified in BIP44. So if you try to import your 12 words from Breadwallet into Copay, you will end up with a brand new wallet and 0 balance.

**Comment by ssakcoR** [comment]
So as long as the wallet uses your mentioned bips I should be able to
recover with those 12 words?

**Comment by isocolsky** [comment]
Yes, exactly.

**Comment by ssakcoR** [comment]
Great, I thought it's Copay words only. Apparently they are created
according to those Bips which are quite universal.

Is there another option to backup my wallet apart from these words? Like
backing up actual keys or something else?

**Comment by isocolsky** [comment]
Yes, you can generate an encrypted file backup from Settings -> [your wallet] -> More options -> Export wallet. If your password is strong enough you can even save a copy on the cloud.

**Comment by ssakcoR** [comment]
Thank you. I decided to make a paper wallet? How can I do it?

**Comment by gabrielbazan7** [comment]
https://www.bitaddress.org
