### ISSUE TITLE
Proposal: Why Not Adding a Entrance Pincode on OS Version?

### ISSUE THREAD

**Issue by ssakcoR** [bitpay/copay#5973]
Hi,

It would be awesome if there was a pin code to enter when opening the app for extra security. I have looked at settings and didn't find such option. Is there such?

What do you think?

Thanks

**Comment by pablomalatino** [comment]
It's a very good idea!

**Comment by gabrielbazan7** [comment]
There is an option for that on settings called "Lock App", but it's only for mobile versions.
