### ISSUE TITLE
Not possible to create backup

### ISSUE THREAD

**Issue by Endogen** [bitpay/copay#5974]
I have two wallets in Copay 3.1.3. One already has a backup, the other doesn't. I tried today to create a backup (12 words) again for the one wallet that already has a backup done.

After entering my password, copay shows me the 12 words. But after that i can't do anything anymore. I can't go back and i can't click on the button "I've written it down".  My cursor also doesn't change if i hover over the button.

I tried it few times and in one case it would have worked but i was kind of surprised and then just canceled it (entering the 12 words) and tried it again and it again didn't work.

I'm on Mac 10.12.4

**Comment by gabrielbazan7** [comment]
Yes, sorry. Take a look to https://github.com/bitpay/copay/issues/5959. Disable the spending password to do the backup. It will be fixed on the next release.
