### ISSUE TITLE
Copay-Trezor Integration

### ISSUE THREAD

**Issue by rakeshgn31** [bitpay/copay#5975]
In case of Copay-Trezor integration, when a trezor wallet account is being added to Copay, It gets the public key from Trezor twice using getXPubKey function within trezor.js file. Once it sends the path 0xb11e/44'/account' and the next time it sends a path 44'/coin_type'/account' and retrieves two public keys. First call becomes the source entropy and the second retrieves the master public key of that particular account.

All we are interested is to get the master public key of that account to identify the trezor account and derive the addresses from the master public key. Why is it necessary to get the source entropy?

**Comment by dabura667** [comment]
Because you need a shared secret for any watch-only wallets as well so they can all encrypt the messages on BWS. Otherwise, Bitpay would be able to read all your messages and memos, but because the entropy is good, Bitpay has no way to decrypt the metadata on their servers.

**Comment by rakeshgn31** [comment]
Okay. In that case, am I right in assuming that Copay derives the public addresses only with the public key obtained from the second getXPubKey call? Also, that is the hardened master public key with respect to that account?

**Comment by dabura667** [comment]
yes.
