### ISSUE TITLE
send max error - many utxos

### ISSUE THREAD

**Issue by gabrielbazan7** [bitpay/copay#5976]
<img width="1178" alt="bitpay_-_secure_bitcoin_wallet_and_developer_tools_-_chrome-extension___fmngdochkddijbbdhofcphjfnppjmkff_www_index_html_and_inbox__147_messages__19_unread__and_whatsapp_installer_png" src="https://cloud.githubusercontent.com/assets/10999037/25806872/2d92069c-33db-11e7-8906-d3472e68ec53.png">

**Comment by dabura667** [comment]
Try it again but this time while monitoring the network tab.

Then you can see how many bytes the post request was exactly by looking at content-length.
