### ISSUE TITLE
Fingerprint issue on android devices

### ISSUE THREAD

**Issue by gabrielbazan7** [bitpay/copay#5978]
Samuel Tee
Today 03:04 am
 
_Hello, I found an issue where you set up security and require a fingerprint to login, I am not able to unlock the app when the fingerprint doesn't work and I use the backup method instead. Entering my pattern returns me to the lock page, probably because the app was not focused for that moment._

Android devices

**Comment by dmo580** [comment]
I've noticed this too. The backup method is not clearly explained that it is your system's unlock password/pin. I think this is a UI/UX issue.
