### ISSUE TITLE
Problem with bitcoin transaction (sent)

### ISSUE THREAD

**Issue by Mecachoendie** [bitpay/copay#5987]
Hello, I sent a bitcoin transaction with priority fee, which is still unconfirmed. The wallet shows that it was sent "seconds ago" while it was sent many hours ago. It also shows the transaction as if it is "sending". I can find the transaction with at least 2 block explorers, but insight.bitpay.com retrieves a "no transaction found" message. 
TxID: 4b00d231ed73cf6333c980ad2d7713805bc03fa04c76c83c3e3a96c92822bd65

Please advise, thanks
Ariel

**Comment by dabura667** [comment]
https://bws.bitpay.com/bws/api/v2/feelevels

```
[{"level":"urgent","feePerKb":327401,"nbBlocks":2},{"level":"priority","feePerKb":218267,"nbBlocks":2},{"level":"normal","feePerKb":218267,"nbBlocks":3},{"level":"economy","feePerKb":198783,"nbBlocks":6},{"level":"superEconomy","feePerKb":161910,"nbBlocks":24}]
```

Bitpay's Copay backend sends fee rates using the above API.

"Priority" says 218 satoshis per byte, but your transaction is 108 satoshis per byte (lower than super economy, which is 161.)

What version of Copay are you using? And which BWS server are you using (if you know the versions of BWS and Bitcore running, also let us know)

**Comment by Mecachoendie** [comment]
Yes, I checked and for some reason it sent it with a very low fee despite having a "priority fee" set up on the settings. The wallet version is 2.4.0.  I don´t know what the BWS or Bitcore versions are (tell me where I can find them). 
Let me know if the wallet version is too outdated. 
Thanks,

**Comment by dabura667** [comment]
Yes, please update your app version.

Not sure how it was that low.
