### ISSUE TITLE
Confirmed Transaction not showing up at vendor.

### ISSUE THREAD

**Issue by rjh1134** [bitpay/copay#5989]
I have a payment that has been approved on blockchain but the vendor does not show that funds have been received.  I was told to contact my Bitcoin provider.  Bitcoins sent from Copay wallet.  What should I do?

**Comment by gabrielbazan7** [comment]
Could you send us the transaction ID ?

**Comment by rjh1134** [comment]
7d73641f3d523a23d1ff4644539a3251d3311b94767b55f694e723296195cab3

Thank you the reply Gabrielbazan7, I appreciate it very much.

**Comment by dabura667** [comment]
This payment is in the blockchain for 2 days.

I checked on my local node, insight, bc.i, blockcypher, tradeblock, and all say the same.

Did you send to a wrong address?

**Comment by rjh1134** [comment]
It appears to have been sent to correct address.  The website napsgear.org shows that the transaction has been initiated, but not confirmed.  Ugh.  It has been 6 days and they still tell me to wait.

Thank you for the reply daburra667.

**Comment by gabrielbazan7** [comment]
The transaction is already confirmed. https://insight.bitpay.com/tx/7d73641f3d523a23d1ff4644539a3251d3311b94767b55f694e723296195cab3
You should contact them again

**Comment by rjh1134** [comment]
I think I listed the wrong transaction ID, sorry I made 2 that day.  Here is the one in question:

a83873fa34947e1d2bbe9810a841e8f5a32fb057d416060ca976e73358f188c1

**Comment by rjh1134** [comment]
I am very sorry for the mistake.  If anyone could verify if the above ID is confirmed I would be most grateful.

Thank you.

**Comment by gabrielbazan7** [comment]
Yes is already confirmed

**Comment by rjh1134** [comment]
Okay, thanks again gabrielbazan7 much appreciated.
