### ISSUE TITLE
'sending' taking like for ever

### ISSUE THREAD

**Issue by Rimkevs** [bitpay/copay#5990]
Hi, 
yesterday I send bitcoin twice. The first transaction didn't take long for the second transaction it  took 14 hours. Only today I could sent bitcoin back to my paper wallet which was over 3 hours ago. 
Can you please explain why it is taking this long. Is it me? Or did the proces suddenly got a lot more complicated and that's why it takes more then half a day to be able to make an other transaction. For as long the 'sending proces' is not complete my BTC are stuck, locked-in!!
Is there a way around this?
Thank you for your time,
Rimke

**Comment by gabrielbazan7** [comment]
Hi the confirmation time depends on the fee of your sending transaction and the Bitcoin network congestion. The higher the fee, the greater the incentive a miner has to include that transaction in a block. Go to the tab settings -> Bitcoin Network Fee Policy and choose the fee Policy you want to use, you can see also an estimated time to get your transaction confirmed depending on the policy you choose. 

Remember that Bitcoin transactions are paid by the sender, so it's free for receiving transactions. And fees calculated by Copay or BitPay Wallet for sending are given to the Bitcoin miners, not to anyone else.

**Comment by rcastag** [comment]
I am having this same problem, but it looks like it is never getting to the blockchain at all.  I don't need it confirmed.  I just expect to see the unconfirmed transaction show up.  It does not.

Take a look:
I send a payment from my mobile copay wallet at 11/15/2017 2:22 PM MT 
15 minutes later still no unconfirmed transaction on insight?
https://insight.bitpay.com/address/1JusTLEuiWDV94QX3bHd1LUr4hr3gtqevX
