### ISSUE TITLE
Lost password for restore phrase

### ISSUE THREAD

**Issue by tomokick** [bitpay/copay#5991]
Hello.

I am creating a shared wallet.
One is PC
One is the iPhone

IPhone breakdown

Install Copay on the new iPhone.
Lost password for restore phrase.

You can not remit money from Wallet.
Help me. What should I do?

Thank you.

**Comment by dabura667** [comment]
日本語で失われた経緯をご説明いただけますでしょうか？

復元フレーズは端末の数だけ控えているはずなので、iPhoneの復元フレーズを使えば復元できます。

もしかしたら、無くされたのって12個の単語を羅列した復元フレーズですか？

**Comment by tomokick** [comment]
---
日本語で失われた経緯をご説明いただけますでしょうか？
---
まずiPhoneが故障してしまい機種の交換を行いました。

iPhone自体はバックアップから復元したのですが、
Copayのアプリの中までは再現されませんでした。

手元にとってあった復元フレーズを複数入力したのですが、
いずれも単独のウォレットのもので、
共有ウォレットの復元フレーズが見つからないという状況です。

PCの方からは見ることはできるのですが、
共有ウォレットの為、送金などができない状態です。

お手数ですがどうぞよろしくお願い致します。

**Comment by dabura667** [comment]
確認ですが、

お持ちのフレーズを試された際に、
ウォレットのインポートというタブから試されましたか？

以前の故障された端末はまだお持ちでしょうか？お持ちの場合、どのように故障されたでしょうか？

**Comment by tomokick** [comment]
ご返信誠にありがとうございます。

---
お持ちのフレーズを試された際に、
ウォレットのインポートというタブから試されましたか？
---
はい、こちらより試しました。

---
以前の故障された端末はまだお持ちでしょうか？
お持ちの場合、どのように故障されたでしょうか？
---
故障した端末は手元にありません。

液晶損壊から、
音声通話ができないなどの不具合も発生し、
店舗での交換対応をしていただきました。

**Comment by dabura667** [comment]
そうですか…

であれば、残念ながらiPhoneの方の復元フレーズが見つかるまでは送金ができない状況となります。

念の為、PCの方のフレーズが紙等に書き留めて安全なところに保管しているかご確認の上で、iPhoneの復元フレーズを思い当たるところすべて探すしか方法が無いです。

PCの復元フレーズを書き留めた紙に「2-of-2 共有ウォレット、PCの方」のようなメモ書きをしておいた方が良いかもしれません。

Mt. Goxのようにビットコインをお預かりしているようなサービスではないので、大変申し訳ございませんがご了承下さいませ。
