### ISSUE TITLE
Error connecting to glidera/coinbase

### ISSUE THREAD

**Issue by BitMari** [bitpay/copay#5992]
Hi Been getting an alert with the message error connecting to coinbase/glidera when i press the buttons , what might be the problem

**Comment by BitMari** [comment]
<img width="1280" alt="screen shot 2017-05-10 at 3 31 45 pm" src="https://cloud.githubusercontent.com/assets/15158255/25901056/d4362fbc-3595-11e7-9228-0f8c0dc3abf2.png">

**Comment by cmgustavo** [comment]
You need verified credentials to enable Coinbase in devel environment.

**Comment by BitMari** [comment]
Ok , i get them from coinbase or copay?

**Comment by cmgustavo** [comment]
Coinbase
