### ISSUE TITLE
Help, 

### ISSUE THREAD

**Issue by AProffi** [bitpay/copay#5997]
Good afternoon! Help, more than 12 hours are not subject to transaction, are not deduced on other purse and do not appear on mine. Here is an example of the last transaction:
https://insight.bitpay.com/tx/16699b84a7f1f11cfc96086c8679596d2579d4e05c0d43c2ef8f0fc20944d4d6

And such transactions are not one and not one has not been confirmed and btc where it hung

**Comment by gabrielbazan7** [comment]
That transaction is confirmed.
