### ISSUE TITLE
Scanned wallet, max fees and still no funds

### ISSUE THREAD

**Issue by smgmb** [bitpay/copay#6002]

**Comment by smgmb** [comment]
Scanned a paper wallet that I put funds on about 15000 bits, my copay was set to max fees.
I waited all night and  no funds. So I tried again to scan the paper wallet same thing,
Pending conformation, 
When I select see on block chain it says transaction not found.
I am afraid I do the wrong thing and poof like with the banks my money is gone.

**Comment by smgmb** [comment]
Many thanks o you that care.

**Comment by readybit** [comment]
Same problem. Been waiting six days already. Transaction not found and no funds. The only thing proves that it might happen is small writing which says "receiving"

**Comment by gabrielbazan7** [comment]
hi, this issue still valid ?
