### ISSUE TITLE
Multiple bugs!?

### ISSUE THREAD

**Issue by readybit** [bitpay/copay#6003]
Cant find my transaction history (it showed as recieved payments) now it has disapeared. 

Cant find all the addresses!

When trying to make a custom btc request the adress is at the very bottom barely seen and i cant scroll down! 

Iphone se.

This app is so buggy!

**Comment by matiu** [comment]
> Cant find my transaction history (it showed as recieved payments) now it has disapeared.

This could happen is the TX was dropped from the mempool (ie: it never got confirmed due to low fees).

> When trying to make a custom btc request the adress is at the very bottom barely seen and i cant scroll down!

we will check that, thanks.

**Comment by cmgustavo** [comment]
> Cant find all the addresses!

List of addresses has been moved to **Settings** -> **Wallet** -> **More options** -> **Wallet addresses**

**Comment by readybit** [comment]
"This could happen is the TX was dropped from the mempool (ie: it never got confirmed due to low fees)."

How to solve this problem then? It actualy still can be seen in the app as "receiving" but cannot be found in direct blockchain link from the app.

**Comment by smgmb** [comment]
And POOF! It's gone.......
Same thing here.
Loaded a paper wallet with $20 worth tried retrieving it with the same Copay,
It said low mining fees and it will take a very long time to retrieve. And I had the fees set to max.
So I took the rest of the coins off onto coincheck.
Lucky I got them.
Updated the copay and after a day of the same message, POOF!

**Comment by krolli53** [comment]
> List of addresses has been moved to Settings -> Wallet -> More options -> Wallet addresses

Why has that been moved? So uncomfortable! I need to create every day multiple addresses for different wallets.

**Comment by cmgustavo** [comment]
> Why has that been moved? So uncomfortable! I need to create every day multiple addresses for different wallets.

JFYI: If the current address receives bitcoin, the wallet creates a new address automatically. So, I think that in normal use, it 's not necessary to create addresses manually.

**Comment by krolli53** [comment]
> JFYI: If the current address receives bitcoin, the wallet creates a new address automatically. So, I think that in normal use, it 's not necessary to create addresses manually.

Absolutely - different people want to transfer bitcoin to me and I want to give each a different address. They will transfer in the next couple of days. But I don't want to wait for each transfer for a new address.

**Comment by dabura667** [comment]
@krolli53 You don't need to. Tap "Generate new address" on the receive tab. It will generate up to 20 empty addresses.

**Comment by krolli53** [comment]
@dabura667 no, not anymore in the new Version of Bitpay. Thats why I joined this conversation.

**Comment by dabura667** [comment]
@krolli53 Sorry, Just updated. The generate new address button is in the menu you told me about.

So you are upset that the generate new address button is hard to get at?

I just generated 20 addresses with the latest version in the menu you just told me.

**Comment by krolli53** [comment]
Yes, it is uncomfortable. I don't want to generate 20 addresses at once. I want to generate a new address each time a person is asking me for a new address. This could happen for example four times a day. And I don't want to go to this menu that often. You understand my problem? I don't know why this has been removed from the "Receive" tab.
