### ISSUE TITLE
Multiple wallet addresses: How to send BTC between wallet addresses with Copay?

### ISSUE THREAD

**Issue by mareng0** [bitpay/copay#6004]
I've created a brand new Copay wallet. It cointained one address. I've sent 5 BTC to this address in three transactions (all to the same address). After this deposits, I've sent a minimal amount of 0.001 BTC to a friend. Copay didn't only sent the 0.001 BTC. It also created a second wallet address and sent 0.05 BTC to it. Now I have two addresses linked with my Copay wallet. One address holds 4.949 BTC and the other 0.005 BTC.

How can I send the 0.005 BTC to the address that holds the 4.949 BTC or inverse?
And why does Copay do this? Why do they generate a new address and make a "ghost transaction"?

I want to do this, because I need all BTC in one address.

**Comment by gabrielbazan7** [comment]
Copay generates new addresses automatically once you use a bitcoin address ( every time you receive and send a payment ) to protect your privacy.

All bitcoin transactions are public, traceable, and permanently stored in the Bitcoin blockchain. When addresses are re-used, they allow others to much more easily and reliably determine that the address being reused is yours. 

Saying that, although not recommended ( if you care about privacy ) , you can reuse old addresses to manage funds in your wallet. We have an option for audit purposes when you create a new wallet that avoid new addresses generation. 

If you want more detailed information of how new addresses are generated please take a look to https://en.bitcoin.it/wiki/Deterministic_wallet, https://en.bitcoin.it/wiki/Address_reuse and take a look that discussion on Reddit that https://www.reddit.com/r/Bitcoin/comments/3euuka/still_confusedwhy_is_it_not_secure_to_reuse/ that is really informative. 

Tell me why do you need all your BTC in one address ?

**Comment by mareng0** [comment]
Thanks for your answer and the links.

It's simple why I want(ed) all BTC in on address: Byteball
Byteball distributes (every month) free GBYTE to all BTC holders. You only need to link you BTC address (where all your BTC is stored) with Byteball.

**Comment by gabrielbazan7** [comment]
Ok. You don't need to create a new wallet with the audit option. You can reuse old addresses there is not problem. You could see all your addresses on Tab settings -> choose your wallet -> more options -> wallet addresses

**Comment by mareng0** [comment]
I have two addresses in my wallet.
Is it possible to send BTC from one address to the other?

**Comment by gabrielbazan7** [comment]
Yes

**Comment by mareng0** [comment]
I am not sure, if I understand correctly. But if I have more than two addresses connected with my Copay wallet and every address holds some BTC, then how can I send BTC explicit from account 4 to account 2? Or from account 3 to 4?

**Comment by gabrielbazan7** [comment]
What do you mean by account ? 

Copay generates new addresses automatically once you use a bitcoin address ( every time you receive a payment ) to protect your privacy.

All bitcoin transactions are public, traceable, and permanently stored in the Bitcoin blockchain. When addresses are re-used, they allow others to much more easily and reliably determine that the address being reused is yours. 

Saying that, although not recommended ( if you care about privacy ) , you can reuse old addresses to manage funds in your wallet, because all of them belongs to that wallet.

If you want more detailed information of how new addresses are generated please take a look to https://en.bitcoin.it/wiki/Deterministic_wallet, https://en.bitcoin.it/wiki/Address_reuse and take a look to this discussion in Reddit https://www.reddit.com/r/Bitcoin/comments/3euuka/still_confusedwhy_is_it_not_secure_to_reuse/

**Comment by mareng0** [comment]
By _account_ I mean addresses. I am trying to make it more clear to you:

I have 2 BTC in my CoPay wallet. But these 2 BTC are conncted with different addresses. Let's say it is like this:

0.25 BTC on address **aaa**
0.75 BTC on address **bbb**
1 BTC on address **ccc***

How can I send the 0.25 BTC from **aaa*** and the 0.75 BTC of **bbb** to **ccc**?
The point is, that I want all BTC connected with ONE address. I told you why.

**Comment by dabura667** [comment]
Doesn't this site have a bitcoin wallet you can use? Why not use that?

And if they give out rewards based on balance, why not send them all your addresses? What is the benefit of consolidating into one address?

You can create a new wallet that is "single address mode".

**Comment by mareng0** [comment]
I could send them all addresses, but I have to validate it and send a little amount of BTC to them. So, I would save tx fee. Anyway, I will get it handled with your help.

By the way: Tx fees are going to be rediculous on some exchanges. They already take 0.001 BTC (Bittrex) or 0.0007 (Omniwallet). Crazy...

**Comment by Lalitpatadiya12** [comment]
mareng0 Can you please let me know how would you manage in one address?

**Comment by gabrielbazan7** [comment]
@Lalitpatadiya12 go to create new wallet, open the advanced settings and switch on "Single Address Wallet"
