### ISSUE TITLE
Send Transfer from same BTC address

### ISSUE THREAD

**Issue by ridjaldiallo** [bitpay/copay#6005]
Hi, Is it possible to make a transaction using the same BTC address of a previous transaction? I need to do it in order to confirm my identity in a crowdfunding I participated in.

Best regards

**Comment by dabura667** [comment]
When you create your wallet open advanced options and tick "single address wallet"

**Comment by ridjaldiallo** [comment]
Thanks. Can I still do it if the first transfer is already sent with multi-signature?

**Comment by gabrielbazan7** [comment]
No. You have to create a new one

**Comment by ridjaldiallo** [comment]
Oh ok. Then, is there any way you can suggest me to prove that I am the owner of the Transaction made?

**Comment by dabura667** [comment]
Single address or not has nothing to do with multisig.

You can make a single address multisig wallet.

However, you can not convert an existing wallet to a single address wallet.

What do you mean prove you are the owner?

What are you trying to do?

**Comment by Derrick-** [comment]
If you need to send again from a specific address that you have already sent from, you can send all the coins in that wallet to that address, then the next spend will surely come from that desired address.

**Comment by ridjaldiallo** [comment]
Ok, Thank you guys, I will try it!

**Comment by Derrick-** [comment]
Be aware that this (all coins thing) will only work the first time. After you spend that address will be drained and and everything not spend will be in a new change address in that account.

If you want to test, you'll have to repeat the procedure of spending the entire account to that address.

**Comment by dabura667** [comment]
Nope. Single Address mode sends change to the single address.

**Comment by Derrick-** [comment]
> Nope. Single Address mode sends change to the single address.
This is not a conversation about single address mode.
