### ISSUE TITLE
Amazon card never delivered

### ISSUE THREAD

**Issue by syberqbert** [bitpay/copay#6006]
Hello,

I understand this is an open source wallet so I am unsure if this is the best place to leave a support request, but I bought an amazon card through the wallet and was never delivered. I would like to provide the details of the transaction in a private way? Thank you.

**Comment by gabrielbazan7** [comment]
Please email help@bitpay.com with the following details so we can assist you further.

Current device & operating system
Current version of the wallet used
Screen shot
BitPay Wallet ID - To get your Wallet ID, open your BitPay application, then go to Settings > Wallets & Integrations > More Options > Wallet Information.
It would also be helpful for you to provide the bitcoin transaction details related to the specific Amazon gift card purchase.
