### ISSUE TITLE
Fund transferred but obviously not reached wallet

### ISSUE THREAD

**Issue by fsiebert63** [bitpay/copay#6008]
Hi, I created my wallet today and made a first transfer from my bicoin wallet - works fine! So I transfered a second trance which never appeared in copay wallet!!

TransactionID 77abdabc78ef5d398276d4bc37b05ad1acf84e31312b0f6f2ab35fd9a92e466b-000

**Comment by gabrielbazan7** [comment]
Sorry I can't find the transaction on the Block Explorer
