### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by amycv3** [bitpay/copay#6009]
I used a Bitcoin atm to deposit funds to my brand new Copay account.  It's been over a hour and there are still no funds in my wallet.  I've done this before with a different wallet and it was funded almost immediately.   I'm not sure how to get the tranasaction ID.  Can anyone help me?

**Comment by readybit** [comment]
I have been waiting a week already. Since May 5th. So ... :DD

**Comment by gabrielbazan7** [comment]
You could see the transaction in your wallet history ? like this : 
<img width="398" alt="bitpay_-_secure_bitcoin_wallet_and_please_help_ _issue__6009_ _bitpay_copay" src="https://cloud.githubusercontent.com/assets/10999037/25978025/116d26f0-3696-11e7-859f-283b87ac2952.png">

Click in that transaction and you have a button to see the transaction on the blockchain and there you have the transaction ID and the number of confirmations

**Comment by amycv3** [comment]
Guys, thanks for the help!!!

This is so embarrassing...
There is nothing in my actual wallet history.
So I went to the blockchain site and typed in my 'receive' address.
My purchase does show there.
But I'm not sure which is my actual transaction ID.
Under the "Transactions" heading are two long strings of numbers, with the oldest one first.
Is the ID one of those?

Because the most important thing I see here, is a big red box with the following:
1KSJqPGwdXPYiZm7eGBgeyj98JJYB4E9Gd 
0.06801388 BTC
Unconfirmed Transaction! 0.06801388 

I don't know what the 'unconfirmed transaction' means, or how I can fix/confirm it.
Any ideas??

**Comment by gabrielbazan7** [comment]
You should see the transaction even is not confirmed. So, I think that address is not from your Copay wallet. Could you confirm that ? Tab settings -> choose your wallet -> more options -> wallet addresses and search that address there

**Comment by amycv3** [comment]
Ok, I triple checked it. 
 That address under the 'wallet address' matches up exactly to my "Receive" address.  It is definitely the address under the QR code that the ATM used to transfer the funds.
Well, it was supposed to be the address the ATM used.  Obviously something is wrong, cause there is still no info whatsoever in my Copay account.  No transactions.  Nothing at all.

All of the following info I got from the blockchain.
The blockchain is stating there was only 1 transaction.
Under "Transactions" is the following:
Transactions (Oldest First) 
_2feb1c14d0fcf6d75ecc332b97900773df65fa2e24636eb136b65c23ca43a673
18p18aRBZPp3S4dDo

Then an arrow pointing to this, my receiving address:
1KSJqPGwdXPYiZm7eGBgeyj98JJYB4E9Gd 
(which is correct, I'm positive now)

And then, there is this:
_Unconfirmed Transaction! 0.06801388 BTCX8NUCBLMdjMFSEezy_

**Comment by Dynamitee** [comment]
I'll like to know when you get your coins in your brand new wallet. I'm having the same issues, though mine is a transfer from Blockchain wallet.

**Comment by amycv3** [comment]
Hopefully someone will reply soon....I can't believe this is happening when I used a Bitcoin ATM.  You are supposed to get your funds immediately.

**Comment by gabrielbazan7** [comment]
If you don't see the transaction on the wallet history (you should see the transaction immediately, like the photo I upload before) , you send to an incorrect address or the transaction was dropped because the low fee and you have to do it again. If is the first option you should search for the wallet where you copy that address, if the second option go to the ATM with the ticket and tell them that the transaction never get confirmed and ask for a refund.

**Comment by dabura667** [comment]
CPFP soon? I have a few pull requests open.

**Comment by gabrielbazan7** [comment]
On closer inspection, you transaction fee is too low. Go to the ATM with the ticket and tell them that the transaction never get confirmed and ask for a refund.
