### ISSUE TITLE
i deposited  but didnt come to my wallet . i cant see on history .

### ISSUE THREAD

**Issue by berkayylmz** [bitpay/copay#6011]
i deposited but didn't come to my wallet . i can't see on history . pls check my wallet

**Comment by berkayylmz** [comment]
my wallet is on copay 1BRnPWmQibreRe2Prqd1U86nGQNVmWXvJq

**Comment by gabrielbazan7** [comment]
Hi, where you see the transaction ? I check the block explorer and it seems that the transaction dropped due to low fee

**Comment by berkayylmz** [comment]
2db84dc1efab09dc555b47193e14a46fee7a6a41cb411cd65e4c0346de00bc5e
