### ISSUE TITLE
Bitcoin transcation

### ISSUE THREAD

**Issue by thunderberry1** [bitpay/copay#6013]
Hey, I use the copay app wallet on my laptop and I've had problems with one transaction that kept on updating saying that i received the payment ''a few seconds ago'' for 6 hours before it vanished, even receiving  other transactions after this one which led to the new transactions to go below the transaction with the problem saying ''a few seconds ago''.

it's been 60 hours since I first got the transaction and I've seen it in my wallet twice before it came back the second day after disappearing after 6 hours the first day, I even tried sending the bitcoin to a different wallet with a 18$ fee or 0.010 btc, and that's 1 hour ago so I haven't lost hope yet.

I'd like to know what this error might be if you know it.

Thanks

**Comment by gabrielbazan7** [comment]
Hi, you still having this problem ?
