### ISSUE TITLE
Transaction Not Found

### ISSUE THREAD

**Issue by ZAX001** [bitpay/copay#6014]
I received 5/12 1 bit. However, Transaction Not Found is displayed and BTC does not reach. What should I do? Thank you.

**Comment by gabrielbazan7** [comment]
Hi, you still having this problem ?

**Comment by ZAX001** [comment]
Hello. Thank you for your reply. The problem has been resolved. Thank you.




2017年5月16日(火) 3:48 Gabriel Edgardo Bazán <notifications@github.com>:
