### ISSUE TITLE
lost phone

### ISSUE THREAD

**Issue by mcastello29** [bitpay/copay#6017]
I downloaded the app and transferred my bitcoin off of Hive to Copay. Two weeks later I was robbed while traveling and the phone was taken, four days after that Southwest lost my luggage and it still has not been recovered. I wrote the code down separately and had it saved in a notebook. Both are gone. It seems like I am unable to retrieve my info but I really hope that is not the case. I didn't have it written down in 3-4 places because at that point its not secure. I've been trying to reach someone to help with this issue and really hope I can recover my funds.

**Comment by gabrielbazan7** [comment]
Hi @mcastello29 !
Sorry, there is nothing we can do for you. You need to find the notebook with your 12 words.

**Comment by mcastello29** [comment]
The airlines lost the luggage and its been almost 2 months. I don't believe it will be found. I can't believe 12 random words is the only way I can get my money! thats terrible

**Comment by mcastello29** [comment]
So Copay just has my money and bc I was robbed I am again out of luck? If I knew there was no support I would never had transferred. Im really really upset. I had a lot on the site. I can't believe a company can get away with that. Loss happens all the time. I was robbed on vacation then the airlines lost my luggage before I could even replace my phone and download it. This is worse than I could imagine

**Comment by gabrielbazan7** [comment]
BitPay do not have access to any of your funds. All private keys are stored locally. The private key never leaves the device, so for accessing a wallet funds it is necessary to have the device or a backup of the wallet.

**Comment by dabura667** [comment]
When you first installed Copay, the terms of service explained very clearly (I would know I translated it all into Japanese) that Bitpay and the Copay wallet do not have any access to your funds, and it is 100% your responsibility.

By holding your backup phrase and your phone on the same plane, you were carrying essentially a briefcase with all your money in it.

You lost a briefcase with all your money in it... but luckily, most people won't know that 12 words is worth anything... so keep trying and eventually you might get the luggage back.
