### ISSUE TITLE
Copay Wallet Problem?! Missing and Unconfirmed transactions.

### ISSUE THREAD

**Issue by dsjsantos** [bitpay/copay#6018]
Hello,

I'm trying Copay Bitcoin Wallet for a little time.
I already sent and receive some small bitcoins transactions.

But since May 9 I'm facing problems with my wallet.
I've been using the same address fro a sequence of small transactions and all was ok until may/9.
It was 12 successfully transactions, then a sent 0.0026664 and that transaction appeared in my wallet but took to long without any confirmation. After that I sent two other transactions that was ok again and confirmed normally but that one (a4aa15d6689eaae94855db298f0a593536773e13af58ae24439302f02bb3989e) stills unconfirmed.
At Copay application and mobile App this unconfirmed transaction keep showing as Receiving (unconfirmed) and time counting, but after few minutes the application reset the transaction time ans show received a few seconds ago (like I had just sent). 

Son on May 11 at morning I sent a new one to the same address of my Copay wallet of 0.01069893 (7538c6a202741b4648d6634df11edea382c2041c02afde6f219e2b3ec3076ce6) and that one never shows on my Copay wallet but it shows as unconfirmed in blockchain.

After I started a new test, I sent money from Copay wallet to another Wallet and the transaction was ok. Then I tried to send back 0,001 (a17c3b22e4c01a541185e928587734006ec12d881111226de10e2bf6c20f8c1e). Curious-ly this one shows in my Copay Wallet (differently  from the 0.01069893 transaction but is has the same behavior of the first problematic transaction (0.0026664) showing time like it was a few seconds ago and still unconfirmed.

All three transactions were sent with fee, including larger than other confirmed transactions,but don't confirm. 

Now, May 13 00:49 GMT ans all three transactions still unconfirmed and the second one (0,01069893) now is showing a "Double Spending" information on blockchain. 

I tried many other transactions with other wallet (online and offline) and everything were fine, I got problems only with this Copay Wallet (specially the second transaction - the one the don't show in Copay but shows in block chain).

Please help me? Why that happened. What can do? What happened with that transactions? If the transactions some day got dropped how do I get the money back to sender wallet?

Thank you in advance.

Sincerely
Daniel Santos

**Comment by thunderberry1** [comment]
I have this same problem and it seems like a copay wallet problem, so best thing might just be to change bitcoin wallet.

**Comment by gabrielbazan7** [comment]
Hi, the transaction is already confirm so I think it shows again in your wallet. We make some fixes, sorry about that, we would try that this don't happen again.

**Comment by Ernesto26** [comment]
Hello,

I've got the same problem today.

My transfer with adress 0aa61c797a067162df1101ea060bf59ddee5820fd4c61c300e77d00d45ca5cb6 is pending in unconfirmed and after some minutes it restarts the transaction time.

please help me!
