### ISSUE TITLE
Multiple unauthorized bitcoin purchases

### ISSUE THREAD

**Issue by maytherman** [bitpay/copay#6019]
Hello, 
I tried purchasing a denomination of bitcoin the other day, but when I tried to submit my request, an error message appeared and claimed that the attempt failed. I tried several other times, but all outcomes ended in errors. A couple of days later, I see several pending transactions within my bank account for a large sum of money being transferred to coin base. This is a giant problem... I want my money back in my account. Now

**Comment by dabura667** [comment]
This is not Coinbase support.

By using the Coinbase feature you are agreeing to the terms of Coinbase and any problems regarding Coinbase inappropriately charging your bank account should be dealt with through Coinbase support.

**Comment by maytherman** [comment]
So now the money is out of my account, and I can't see any bitcoins in my wallet. Is that on coin bases end or copay?

**Comment by dabura667** [comment]
Coinbase.

Please contact their support.
