### ISSUE TITLE
i deposited 2 days ago but my wallet looking 0 ? pls help me

### ISSUE THREAD

**Issue by berkayylmz** [bitpay/copay#6021]
i deposited 2 days ago but still , my wallet looking  0 , PLEASE HELP ME 

2db84dc1efab09dc555b47193e14a46fee7a6a41cb411cd65e4c0346de00bc5e

**Comment by maytherman** [comment]
I have the same issue. What is going on

**Comment by dabura667** [comment]
The fee is 120 satoshis/byte and the current network is flooded with transactions around that fee rate.

The fault is with the sender.

Contact their support if they are a business.

**Comment by dabura667** [comment]
The problem would have been avoided if the sender had set a proper fee.

Also

@maytherman I think your issue is different from this issue. Please contact Coinbase support.
