### ISSUE TITLE
cannot create wallet

### ISSUE THREAD

**Issue by ntounix** [bitpay/copay#6022]

**Comment by gabrielbazan7** [comment]
Could you provide more information ?

**Comment by ntounix** [comment]
That's interesting.. I didn't even really create that... I searched that.  When I attempted to make my wallet I recieved the error Cannot Create Wallet: Network Error Brett Turner

**Comment by gabrielbazan7** [comment]
Try to create the wallet, then go to settings -> about BitPay -> Session Log and send me the logs to gabriel@bitpay.com. Thanks!!
