### ISSUE TITLE
Installed Copay v3.2.0 and all my old addresses are gone

### ISSUE THREAD

**Issue by eryndlia** [bitpay/copay#6023]
After installing v3.2.0 of Copay, my old wallet addresses are no longer visible.  Some of them have not yet received any BTC, but I wish them to be visible to me, anyway.  Previous Copay upgrades did not do this.  I am very concerned:  Are these old addresses still connected to my wallet, even though I cannot see them?  How can I see them, if they are still there?

**Comment by dabura667** [comment]
Settings >> (Select the wallet) >> Other Options >> Wallet Addresses >> All Addresses

Kind of deep in the menus, but it should list all addresses from xpub/0/0 all the way to xpub/0/x where x is the last address you used.

If you tap the + icon on the Wallet Addresses menu, you can create a new address without receiving money.

**Comment by eryndlia** [comment]
Ok.  I should add that I am on Windows 10 64-bit.
Get ready; this is weird:
1) I do not have "Other Options" that I can find.
2) If I click on a specific wallet in the list of my wallets, it does not display a "back arrow" or a "home" button.  There is no way for me to go back to the Home screen except by reloading.
3) If I do other things such as "click on the 'Wallets +'" then that screen becomes my new Home page, and again I have no way to reach the real home page short of Reload.

Perhaps I need to re-install?

**Comment by dabura667** [comment]
1. Not "Other Options" but "More Options" sorry I do not have my app set to English. I just checked English.
2. There should be a small white arrow pointing left in the upper left corner of the app that will take you back home.
3. See 2

**Comment by eryndlia** [comment]
Yes, there should be a little arrow point left, but there isn't.  Also, there is neither "Other Options" nor "More Options."  I will re-install and report results here.

**Comment by eryndlia** [comment]
News flash:  I have not yet re-installed Copay; however, I just discovered an interesting effect, and I now have the "Left Arrow", and my "Home Page" problem is solved.  I normally pin the Copay program to my Windows taskbar for convenience, and I just realized that I had not "Unpinned" and repinned the newly installed version.  Doing so fixed those issues.

The "multiple addresses missing" and no "More Options" issues still linger.  So, I suppose I will have to reinstall in an attempt to fix these.

**Comment by eryndlia** [comment]
I did reinstall, and I have found "More Option"; however, it is not where you told me.
I previously was able to click "Receive".  There there was a "Right Arrow" which took me to the Addresses menu.  Now, I must click Settings -> (wallet name) -> More Options -> Wallet Addresses -> View All Addresses.

So.  I now have all my old addresses available to me.  Thank you for persevering!
