### ISSUE TITLE
Mac OSX Copay app won't let me send 

### ISSUE THREAD

**Issue by francerome** [bitpay/copay#6024]
Mac OS X Yosemite 10.10.5
Copay 3.2.0

I am attempting to send fund. I copy the address and paste it in the bitcoin address. Nothing comes up. 
HELP?

**Comment by gabrielbazan7** [comment]
Coudl you show me the address ?

**Comment by francerome** [comment]
gabreilbazaz7:

Which address are you referring to? The send to address?

**Comment by gabrielbazan7** [comment]
The address you paste in the label

**Comment by francerome** [comment]
Ripple Deposit Address:

rPDaXPjrE9j7X1wMTaNxRSwvdKP5bZmiLn

**Comment by dabura667** [comment]
This is a Bitcoin wallet. Not a ripple wallet.
