### ISSUE TITLE
Please Help!

### ISSUE THREAD

**Issue by AProffi** [bitpay/copay#6026]
Good afternoon! Help, more than 60 hours are not subject to transaction, are not deduced on other purse and do not appear on mine. Here is an example of the last transaction:

https://insight.bitpay.com/tx/1c14a6f6023b2addf7471365270264e62ed4fd9cdd7deffe92de9471eee53ef7
Please help!

**Comment by gabrielbazan7** [comment]
Hi. The transaction is not confirmed yet. Just wait

**Comment by AProffi** [comment]
Hi
So he does not leave for more than 60 hours constantly trying to re-translate to the purse will come! Previously, this was not just do not ever! And then with his purse in his purse and ued a confirmed transaction

**Comment by gabrielbazan7** [comment]
Sorry for the delay, it seems that the transaction was dropped due to low fee. Ask the sender to re try.
