### ISSUE TITLE
trying to understand fees 

### ISSUE THREAD

**Issue by gladbtc** [bitpay/copay#6033]
Hello I have just joined with Copay over the last month. I am trying to understand the fees. I just receive transaction of .17777 btc and fee  reads .097597 btc is this possible? This seems to be consistent high charges  example received .219944 and fee states .097655
 thx

**Comment by gabrielbazan7** [comment]
Hi ! Bitcoin transactions are free to receive. That fee you see there was paid by the sender.

**Comment by gabrielbazan7** [comment]
0.09 fees is to high, but it could happen. The parameter used for the fee calculation is the TX size, not the output amount. So, this could happen when you have many small inputs in your wallet, so you need to use all (or most) of them to build the transaction and your fee will be increase significantly.

**Comment by gladbtc** [comment]
thank you for the life of me i couldn't reconcile what was going on. So to receive btc should be low cost but to send is when i should be paying a transaction fee.  I have been receiving on a daily basis .2 , .177 , .05 etc So when I read fee it is referring to cost to sender correct and not me?

**Comment by gabrielbazan7** [comment]
Yes, correct. Not you. We got a lot of questions about that, so in the next release we are removing that label. https://github.com/bitpay/copay/pull/6029

**Comment by gladbtc** [comment]
Will fee change if i set to super economy? my account has been charged .63757224 btc on 2.46289 btc received,  seems really high
thanks from Newbie

**Comment by gabrielbazan7** [comment]
No no, it doesn't depend on you. You have not been charge of anything. That fee was paid by the sender.

**Comment by gabrielbazan7** [comment]
And all fee goes to the bitcoins miners, no BitPay or anyone related to this project.

**Comment by gladbtc** [comment]
thank you
