### ISSUE TITLE
Error Copay.exe para Windows

### ISSUE THREAD

**Issue by eskarabaj6** [bitpay/copay#6034]
Copay 3.2.0 version for Windows gives error

'La unidad o ruta de acceso UNC no existe o no es accesible'

wtf?

**Comment by cmgustavo** [comment]
Hi, I 'm sorry you are having trouble with Copay. Could you provide us more information?

* Did you download Copay from this link: https://github.com/bitpay/copay/releases/download/v3.2.0/Copay.exe

* What version of Windows do you have installed? 32 or 64 bits?

* Problem happens before or after install the app?

Thanks for your patience.
