### ISSUE TITLE
Issue with Copay transactions/balance

### ISSUE THREAD

**Issue by albey17** [bitpay/copay#6040]
I had about 8000 USD worth of btc in my wallet, plus 3 pending transactions that were sent to 3 different friends. The transactions were pending for more than 4 hours. I have a "normal" network fee policy selected. Suddenly i looked at my wallet and all 3 transactions are gone and im
Showing a $12 balance. What is going on? Never seen this before. Need help right away.
Thanks.

**Comment by boyweiser** [comment]
Hi Albey,
for my experience, the same thing happen with me, while using Copay, everything came back to normal after my transaction was confirmed. After this problem came back i few times, i start to use MyCelium and Jaxx wallet, and never had this issue anymore. Hope it help. 

jfb

**Comment by albey17** [comment]
Thanks i will definitely look into switching. However how can i get someone from Copay to answer my concerns? What is the issue and how long its gonna take to be fixed?

**Comment by Perlover** [comment]
About this problem here too:

https://github.com/bitpay/copay/issues/6056

**Comment by matiu** [comment]
Hello @albey17, In the last 24 hours the bitcoin network was very congested and fees keep going up, so TX had a lot of problems to get confirmed and many of then where dropped from the pool. Please let us know if the problem persist so we can assist you.

**Comment by Perlover** [comment]
Why balances are wrong in this situations from Copay?
