### ISSUE TITLE
Transaction not available

### ISSUE THREAD

**Issue by powerqc** [bitpay/copay#6041]
I have two transaction to receive. One of 0.04276 from an exchange 2 hours ago and the other one of 0.057084 from a friend 4 hours ago. My balance did not incease and when i click on the two recent transaction, there is the error transaction are not available.

**Comment by kazrasuya** [comment]
I also am having this issue. After the transaction showed up on my wallet, it briefly showed my total balance for about twenty minutes before going back to zero. Now when I click on the recent transaction it also says "error transaction not available at this time". This has me a little worried since it was my first time buying bitcoin and would like to know what is going on.

**Comment by powerqc** [comment]
I receive only the last transaction not the first one.

**Comment by albey17** [comment]
Having same problem. Submitted a ticket already. 3 transactions disappeared plus my balance went from !13,500 usd to $12, which was the balance that was available pending the 3 unconfirmed transactions. It is still unresolved.

**Comment by apocal1** [comment]
I have the same problem. I use copay wallet for the first time. First transaction worked well, so I started two new transaction to the same recipient. I got the confirmation that payment had been sent but blockchain says now no transaction available. And the best thing: all of a sudden my bitcoin credits are gone, zero bitcoins left in my wallet although there must be because I received bitcoins. You can see it in the wallet transactions but no left anymore!!!

**Comment by powerqc** [comment]
I juste receive the second amount

**Comment by Jthomas79** [comment]
i sent $1100 USD from a wallet to a website , have done this many times wihtout any errors . Now all of a sudden we are all having the same issue. Its like the website stole all of our cash and is running with it. What the hell is going on !!!

**Comment by glebabruzzy** [comment]
Same hear all money gone balace 0$ wtf is going ob guys?????

**Comment by glebabruzzy** [comment]
Is this happen 4 real or em I trippin?!

**Comment by apocal1** [comment]
I am new here  and I am confused now, too. Can anyone tell me: Does this kind of problems appear frequently or is it very unusual and singular? I read bitcoins can not disappear and not be lost forever! Is this true?

**Comment by Jthomas79** [comment]
Ive made multiple wallet payments using bitcoin for a few months now and have never had this issue before. Has me shitting my pants. Would be nice if they could throw us a bone as to how and when we will get our funds back. This shit cray.

**Comment by albey17** [comment]
I would say its probably some network issue but it is very very strange. Its the first time i have seen it. I have had transactions take hours to be confirmed but never disappeared from the "recent transactions" and the balance has always been updated. Right now i should have $13,500 and it only shows $12.

**Comment by glebabruzzy** [comment]
0.00 btc and no transactions listet .... 
is this firm a russian or Chinese?

**Comment by apocal1** [comment]
I hope its just a software problem and can be solved soon!!

**Comment by glebabruzzy** [comment]
The authors of the software, employees and affiliates of Bitpay, copyright holders, and BitPay, Inc. cannot retrieve your private keys or passwords if you lose or forget them and cannot guarantee transaction confirmation as they do not have control over the Bitcoin network.

**Comment by glebabruzzy** [comment]
To the fullest extent permitted by law, this software is provided “as is” and no representations or warranties can be made of any kind, express or implied, including but not limited to the warranties of merchantability, fitness or a particular purpose and noninfringement. You assume any and all risks associated with the use of the software.

**Comment by glebabruzzy** [comment]
This is criminal as f

**Comment by Jthomas79** [comment]
What the hell does that mean glebabruzzy ?

**Comment by albey17** [comment]
We have access to our wallets so that would not apply. Just the
transactions are missing and still unconfirmed. I just checked with my
contacts and they still have not received their coins but it shows up, just
unconfirmed. I'm guessing it will be sorted out once the transactions get
confirmed. Also I have pics of all of them which is helpful if lawyers need
to get involved which I doubt will happen.

**Comment by apocal1** [comment]
So if that has never happened before why the hell they should start with it now and rip us off here? I think its a software problem. Well I hope so and pray!

**Comment by glebabruzzy** [comment]
Well hope so 2 all my Open transactions are gone and ballance is showing 0.00 BTC i Hope its just Software mistake and will be gone After this Night

**Comment by apocal1** [comment]
@ glebabruzzy - nightmare on copay street!

**Comment by glebabruzzy** [comment]
Yeah i postet before the terms of Use https://copay.io/disclaimer

**Comment by apocal1** [comment]
I am no expert but could it be hacked or is this impossible?

**Comment by glebabruzzy** [comment]
Everything is possible i guess Bit still hoping its just a very Bad joke

**Comment by KeyJockey** [comment]
I have the same issue & apparently many other people here do too (see other posts today here saying the same thing)

I suspect it's something to do with the BWS "BitPay Wallet Server" that Copay uses to interact with the blockchain: my wallet WAS showing a pending but unconfirmed transaction ALL DAY today -- until it "disappeared" and now the most recent transaction listed is only from YESTERDAY ... and Copay wallet is now showing only 0.00 balance. NOT GOOD.

However the transaction is still the same on the blockchain so I'm hopeful it will reappear correctly again in Copay AS SOON AS THEY GET WHATEVER IS WRONG HERE, FIXED!!

**Comment by KeyJockey** [comment]
UPDATE: My transaction just *finally* got confirmed and now it's appearing in Copay again.

So, FWIW hopefully it seems this is just yet ANOTHER instance of the terrible mempool backlog and bitcoin congestion causing problems, but once you get a confirmation (hopefully not "if" you get a confirmation) then all is okay again.

Good luck out there folks... hang in there :)

**Comment by powerqc** [comment]
I just send a paiment and my remaining bitcoin just disappear.

**Comment by Jthomas79** [comment]
KeyJockey, funds showed up in my copay hours ago, it was once I sent funds that they all disappeared without a trace. I can still see it on the blockchain but im not code expert and honestly the blockchain reads like another language to me. It says status is 100% and sent but where in the actual fuk is it sent too ?

**Comment by KeyJockey** [comment]
@Jthomas79 my situation was the same and it was due to all the remaining balance of bitcoins from the transaction going into a "change address" -- that represented ALL the remaining balance that "disappeared" so it was showing 0.00 until the transaction confirmed... then the correct balance reappeared again.

Hopefully will be the same for you, but not sure either.  Fingers crossed.  BTW my transaction was pending for over seven hours before it got a first confirmation (and this was with a substantial miner fee over $2.00.... the fee/blocksize issue is getting freakin' ridiculous here)

**Comment by dabura667** [comment]
If anyone has transaction IDs post them.

Also, posting your wallet-ID (from the Settings >> wallet >> Wallet Details) will help Bitpay look at the database to see if something is wrong.

**Comment by dabura667** [comment]
Also, FYI, I have been receiving some low fee transactions recently using my own BWS backend, and none of these problems have occured.

It is probably a problem with Bitpay's BWS backend server or insight.

The public insight instance has been kind of wonky lately.

**Comment by Jthomas79** [comment]
Sounds shady , can anyone use our wallet-ID to steal funds?

**Comment by Jthomas79** [comment]
im still fairly new to wallets and bitcoin but havent had any issues in a few months until this afternoon, question when i check wallet addresses and find that their are addresses with balance.. is that my funds in those addresses?

**Comment by dabura667** [comment]
wallet-ID can only be used by Bitpay to look up your wallet's activity on their server.

Anyone who is not Bitpay can not do anything with your wallet-ID.

If you don't trust Bitpay with connecting your bitcoin activity with your Github account, why are you using any wallet that's not a fully verifying node (you don't need a third party to watch the blockchain for you)?

**Comment by Jthomas79** [comment]
Tell us what we need to do to get our funds back sir or maam . I am in desperate need of my 1100$ that is lost in limbo . please and thank you

**Comment by dabura667** [comment]
You can't "lose" money.

You either received it or you didn't.

The problem is that Copay seems to be confused about whether you received it or not.

Post the address which you gave to the person sending you $1,100 and I will tell you if the money arrived at that address or not.

**Comment by Jthomas79** [comment]
I received the money , it showed up in my wallet, but once i made a transfer the transactions went away and my wallet now currently has 1.28$. My recent transactions say received 7 hours ago but no sent transaction. That transaction disappeared.

**Comment by albey17** [comment]
How can i get someone from Bipay/Co-Pay to
Actually help? I still cant access those 3 transactions that were pending before they disappeared, and my balance still shows $12. It should be $13,500. These transactions were sent around 1:45pm.

**Comment by morrisallison** [comment]
I've been bitten by this as well. I've been using Copay with success for awhile now, but a bug if this magnitude without any response has me looking elsewhere. Please, at the very least, I would like some assurance that this is being looked into.

**Comment by powerqc** [comment]
dcf34dd6-5d3f-4c7f-bd6a-fe0dec8169fa wallet id
Now i have no incomming money note confirmed but sitt not access to all my money.

**Comment by liomojo** [comment]
I sent 0.26btc , but it is not confirmed for 15hours , now this morning the transaction disappeared and it is not in my wallet anymore and the coins are not received and are not in my wallet too. I see it on the blockchain still unconfirmed https://live.blockcypher.com/btc/tx/02b1ccedc2bff9db28c72ae4924e75a48a868b0d08936e3fa2a70fb833a96e9e/
What is going on , why it disappeared from my wallet? I see all my other transactions , but this one is gone?

**Comment by Perlover** [comment]
About this problem too:

https://github.com/bitpay/copay/issues/6056

**Comment by matiu** [comment]
Hello, In the last 24 hours the bitcoin network was very congested and fees keep going up, so TX had a lot of problems to get confirmed and many of then where dropped from the pool. Please let us know if the problem persist so we can assist you.

Please let me know you wallet-id at matias@bitpay.com and detail the TX you sent, and I can give you an accurate status.

**Comment by liomojo** [comment]
Hi 
It is ok now , I edited my post that it confirmed and appeared after 20hours
Thanks a lot for your support!

Sent from my Windows 10 phone

**Comment by zapient** [comment]
Similar issue. Copay is showing the incorrect balance but my Trezor is correct.
