### ISSUE TITLE
Problem Copay Wallet

### ISSUE THREAD

**Issue by joewardbt** [bitpay/copay#6042]
I sent .02 bitcoins to another wallet 3 hours ago and transaction was "pending" for a while. Now I get an Error "transaction not available at this time" and all of my funds are gone! 
Help needed please.

**Comment by Jthomas79** [comment]
I have the same issue. I load over $1,000 USD worth of bitcoin and now it is lost in outer space. I get the same "transaction not available at this time". All my money is gone as well. What the hell is going on !!

**Comment by dricharson5150** [comment]
Looks like I got a similar issue, had a 1,8 ish balance and sent 1 BTC then went onto the main window that had total available and confirming and there was 220,000 ish unconfirmed bits in my wallet???? All transaction into the wallet in cash and all confirmed. Then the 1 BTC was getting the same error message mentioned here and now the transaction has disappeared, I can see it at the other end as confirming and I've taken screen shots as proof but this has never happened before.

**Comment by nrajesh** [comment]
Similar issue. One transaction which mysteriously disappeared and another which shows up but with incorrect balance for the wallet. Hope this bug is fixed soon

**Comment by dricharson5150** [comment]
So will they make a balance correction to the wallet? Very strange that fiat deposits into the wallet that been confirmed get caught up like this. It seems other wallets are having issues too.

**Comment by Perlover** [comment]
About this problem too:

https://github.com/bitpay/copay/issues/6056

**Comment by matiu** [comment]
Hello, In the last 24 hours the bitcoin network was very congested and fees keep going up, so TX had a lot of problems to get confirmed and many of then where dropped from the pool. Please let us know if the problem persist so we can assist you.
