### ISSUE TITLE
Incorrect balance in my wallet

### ISSUE THREAD

**Issue by dricharson5150** [bitpay/copay#6043]
I had recently sent 1 BTC to Kravken and the transaction was part of a apron 1,889,000 balance the 1 BTC is still waiting conformation and my balance is somehow 664,145 so am estimate USD$225 less than it should be. There was a strange notification of potential unconfirmed funds amounting to that amount but going back over the transaction they have all been confirmed and they were all cash deposits not from any other source. Can you please investigate this as I'll use another wallet due to this loss.

**Comment by dricharson5150** [comment]
Just to be clear the transaction of 1 BTC was Tuesday May 16 approx 10am PCT, balance of wallet was approx  1,812,696 as I've gone back and reconcile all received and sent transactions and the balance of 666,145 and the sent transaction of 1 BTC is incorrect And doesn't add up also the sent transaction was coming up with an error message when I was trying to view it and now it has gone completely. I can see it in my Kracken account as still being confirmed but nothing on the copay side or in the history.

**Comment by nrajesh** [comment]
See #6047. Auto resolved after several hours. But it was scary as hell for a normal person new to bitcoins!

**Comment by Perlover** [comment]
About this problem:

https://github.com/bitpay/copay/issues/6056

**Comment by matiu** [comment]
Hello, In the last 24 hours the bitcoin network was very congested and fees keep going up, so TX had a lot of problems to get confirmed and many of then where dropped from the pool. Please let us know if the problem persist so we can assist you.

**Comment by Perlover** [comment]
Standard template for tons of issues here :(
