### ISSUE TITLE
Unconfirmed transaction COPAY 

### ISSUE THREAD

**Issue by Celeron1** [bitpay/copay#6044]
Hi, 

can someone please help me my transaction is still unconfirmed and is no longer in my wallet I cannot even see that it has been sent, it is like I have never sent the coin.  please check 1Q2zeqtkDSoxjkULZd3sDdqeTXU4cpFMXv

**Comment by Jthomas79** [comment]
I have the same issue, uploaded a large sum and i get the same error "transaction not available at this time" . There is no money in my Wallet . The cash is lost somewhere in the sky. What the hell is going on !!

**Comment by dricharson5150** [comment]
Same problem and been short changed with confirmed funds as all fiat deposits saying USD$225 unconfirmed and then once the BTC was sent then error message then that and the supposed unconfirmed all gone. I reconciled my wallet for transactions and all the fiat was confirmed and was the total I thought it was but now out 1,220,00 ?!?!?

**Comment by Celeron1** [comment]
Please keep me updated about this situation as I am about to lose $74.63 which I cannot afford to lose right now lol

**Comment by dricharson5150** [comment]
Looks like a lot of people having this problem now.

**Comment by nrajesh** [comment]
See #6047. Auto resolved after several hours. But it was scary as hell for a normal person new to bitcoins!

**Comment by Celeron1** [comment]
yes, it definitely was a scary night I have moved most of my bitcoins after this incident.
all coins confirmed now issue solved :+1:
