### ISSUE TITLE
Bitcoins disappeared

### ISSUE THREAD

**Issue by jsburgos** [bitpay/copay#6045]
My Bitcoins completely vanished from my account. I had received 9.9999 on May 10th and used some. Last transactions I sent went through but now it's not showing me anything. The transaction also doesn't show up in my wallet. Help please.

**Comment by apocal1** [comment]
https://github.com/bitpay/copay/issues/6041

**Comment by glebabruzzy** [comment]
Same Mois Go Tool sleep Hope its just software mistake and will be good tomorow

**Comment by nrajesh** [comment]
See #6047. Auto resolved after several hours. But it was scary as hell for a normal person new to bitcoins!

**Comment by Perlover** [comment]
about this problem:

https://github.com/bitpay/copay/issues/6056

**Comment by matiu** [comment]
Hello, In the last 24 hours the bitcoin network was very congested and fees keep going up, so TX had a lot of problems to get confirmed and many of then where dropped from the pool. Please let us know if the problem persist so we can assist you.

**Comment by jsburgos** [comment]
I got the Bitcoins now. Thanks a lot!

**Comment by dabura667** [comment]
Please close this issue if it is resolved.
