### ISSUE TITLE
Bug in copay?

### ISSUE THREAD

**Issue by nrajesh** [bitpay/copay#6047]
I use copay V3.2 (#664cec1). Today I did two big transactions with a larger commission fees. After more than the usual 30 minute wait period the transaction got credited to my multisig wallet. But by end of day I see that the amount of transaction is reflecting but the wallet total is incorrect!

A second transaction done was to my private wallet, again with larger commission. This took more than 6 hours before the transaction disappeared at both ends. Luckily I have noted the transaction id and it appears as unconfirmed in the block viewer!

I truly hope this is only a bug in the wallet app and nothing more. I have never transacted on this big an amount and the loss will be a heavy blow to my crypto currency enthusiasm!

**Comment by dricharson5150** [comment]
How to we get these issues resolved? This is not cool at all there are a lot of people now having the same issues. Apart from people missing coins they are missing opportunities too.

**Comment by Celeron1** [comment]
I am currently facing the same issue (we are missing opportunities indeed)

**Comment by nrajesh** [comment]
Seems resolved now. Faith in system restored 😊

**Comment by Perlover** [comment]
related bug is https://github.com/bitpay/copay/issues/6056

**Comment by matiu** [comment]
Hello, In the last 24 hours the bitcoin network was very congested and fees keep going up, so TX had a lot of problems to get confirmed and many of then where dropped from the pool. We will work to handle better this situation on the future.

**Comment by Perlover** [comment]
If you will read my issue (https://github.com/bitpay/copay/issues/6056) you will see that balances should be incorrect when the mempool of bitcoin network is big.
If your server see an unconfirmed transaction it should take in account or not completly.
I saw other situation: your server doesn't show and "doesn't see" an unconfirmed transaction but in balance outputs of this transaction is deducted!

**Comment by Perlover** [comment]
And after confirmations i didn't see right balance :-E
And after restoring of wallet...
