### ISSUE TITLE
Balance disappears

### ISSUE THREAD

**Issue by exppt** [bitpay/copay#6048]
I made a transaction . Keept unconfirmed

Then all my balance disappeared and the sent transaction is gone too
ID:
1PgYRCoqKgvBJt7sFSJZvUDKvptEomUQ35

**Comment by apocal1** [comment]
me too! We hope its a software mistake!

**Comment by KeyJockey** [comment]
I have the same issue & apparently many other people here do too (see other posts today here saying the same thing)

I suspect it's something to do with the BWS "BitPay Wallet Server" that Copay uses to interact with the blockchain: my wallet WAS showing a pending but unconfirmed transaction ALL DAY today -- until it "disappeared" and now the most recent transaction listed is only from YESTERDAY ... and Copay wallet is now showing only 0.00 balance. NOT GOOD.

However the transaction is still the same on the blockchain so I'm hopeful it will reappear correctly again in Copay AS SOON AS THEY GET WHATEVER IS WRONG HERE, FIXED!!

**Comment by exppt** [comment]
My first time ever to buy bitcoin , and it isn't so good as i think i have just lost 80$ which is a big sum for me :(

**Comment by dricharson5150** [comment]
What are these clowns doing?!?!?? We're all suffering! I sent a very harsh email to copay support, this is dirty.

**Comment by Jthomas79** [comment]
Apparently its been going on for a few days. My 1100$ USD is apparently floating around in the clouds. Or in some fuc&heads wallet . Fkn thieves !! Get this shit fixed. I need that dang money! 
:(

**Comment by Celeron1** [comment]
My $ 74.63 is also floating around right now I needed this to invest in another coin

**Comment by dricharson5150** [comment]
So is it only when you send from the wallet? I've had a fiat deposit today and it's confirmed and I'm my wallet but the 1BTC I sent is still after 7hrs confirming at an exchange, then there is the 220,000 bits missing also fiat that was in my wallet already confirmed that was supposedly unconfirmed in another window contradicting all the confirmed fiat deposits so WTF is going on and who do we get at to get this fixed?

**Comment by dricharson5150** [comment]
I want to liquidate my wallet now from this but scared it will disappear if I send it to my offline hardware.

**Comment by KeyJockey** [comment]
UPDATE: My transaction just *finally* got confirmed and now it's appearing in Copay again.

So, FWIW hopefully it seems this is just yet ANOTHER instance of the terrible mempool backlog and bitcoin congestion causing problems, but once you get a confirmation (hopefully not "if" you get a confirmation) then all is okay again.

Good luck out there folks... hang in there :)

**Comment by dricharson5150** [comment]
Great but I'm still out 220,000 bits if that's the case as my wallet balance doesn't add up correctly with transactions.

**Comment by Celeron1** [comment]
One of my transactions has been confirmed as well, however, the first transaction $ 68.23 is still unconfirmed.

**Comment by BangL** [comment]
same problem.. first time i use bitcoin.. just threw 91€ away. great experience! 10/10

**Comment by eman1774** [comment]
Fam same thing happening to me my transactions getting lost and blockchain still holding onto my transactions like fuckn release it cah I need it like

**Comment by nrajesh** [comment]
See #6047. Auto resolved after several hours. But it was scary as hell for a normal person new to bitcoins!

**Comment by exppt** [comment]
Transaction went good and my bitcoins appeared once again

**Comment by BangL** [comment]
Worked for me too now. It just took about 13 hours.
Would be less frightening if we would actually see our balance and transactions while the process is running.

**Comment by Perlover** [comment]
About this problem too:

https://github.com/bitpay/copay/issues/6056

**Comment by matiu** [comment]
Yesterday the Bitcoin network had a huge congestion and fee keep going up all day, therefore TX took a lot time to confirm. 

I see the original post by @exppt is solved. Please let us know if you still having problems.

**Comment by Perlover** [comment]
Yes, Bitcoin network is blame for Copay.
Other bitcoin wallets work and show right balances.
So draw conclusions!
