### ISSUE TITLE
Bitcoin transaction failed than bitcoin disapear

### ISSUE THREAD

**Issue by mathh26** [bitpay/copay#6049]
Wtf !! I sent today some BTC to my other phone brother and the transaction failed after few hours i told him they would put the money back, then wtf everything is disapear !!!! Whats gonna happen now ? 
Bitcoin you will loose my faith if it doesnt come back

**Comment by Perlover** [comment]
Related: https://github.com/bitpay/copay/issues/6056

**Comment by matiu** [comment]
Hello, In the last 24 hours the bitcoin network was very congested and fees keep going up, so TX had a lot of problems to get confirmed and many of then where dropped from the pool. Please let us know if the problem persist so we can assist you.
