### ISSUE TITLE
Transactions cancelled? Need to solve it asap

### ISSUE THREAD

**Issue by cryptony** [bitpay/copay#6051]
Hi I was in transaction of receiving money and sending to a customer and suddenly all my pending transactions cancelled leaving me fucked up like never before.. I hope its just a quick mistake of yours and that you will resolve this issu asap. Thanks.

**Comment by dabura667** [comment]
When the transactions eventually confirm, they should show up again.

There was a huge rush of transactions today that drove fees extremely high and many people are waiting long times to get their transactions processed by the bitcoin network.

Copay's app couldn't handle all the transactions, so some people lost the visual cue in their app, but the transaction should be out on the network.

Try searching for your address or the address you sent to on any block explorer website.
Here are a few:

https://blockchain.info/
https://live.blockcypher.com/btc/
https://blockr.io/
https://chain.so/

(This is the website front end of Copay's bitcoin node, so if it's gone on your app it probably won't show up here either)
https://insight.bitpay.com/

Try searching for the addresses on any of these and see if the transaction shows up.

If it shows up on any one of them, that means your transaction is out on the network.
