### ISSUE TITLE
Phrase

### ISSUE THREAD

**Issue by mike1968mi** [bitpay/copay#6052]
Hi, you may not believe me but my laptop crashed and I could not turn it back on. I have no idea what is wrong with it. It crashed not long after I purchased $100 in bitcoins from letsbuysomebitcoins.com and the bitcoins were delivered on May 15, 2017 12:57:36 AM to my copay wallet. And unfortunately, after I wrote down the phrase, I put it in my notepad on my laptop and I can't find the piece of paper. I know I ccan't recover it without that but is there ANY other way to recover my wallet? Please!!! I can not afford to lose $100. 

Please let me recover my wallet with another method. I can give you any information that you need. 

Maybe I can contact buysomebitcoins.com and see if you could send the funds back to them so they can resend it to me. Just an idea because I really can't afford to lose $100 and I am so upset because when I got back online today and re downloaded the copay wallet and signed in, I remembered I need that phrase and I don't have it now. 

Do you have a customer service department? I clicked on help and support on the website an dit brought me here to this site, github.com

Thank you and please reply ASAP.

Michael Januszewski

**Comment by mike1968mi** [comment]
Hello? Can someone help me please?

**Comment by gabrielbazan7** [comment]
Hi, sorry the delay. Unfortunately the only way you have to recover the wallet is using the words, and there is nothing we can do for you.

**Comment by mike1968mi** [comment]
I can't afford to lose $100. Can you send it back to buysomebitcoins.com if
I contact them and explain what happened?
PLEASE

**Comment by mike1968mi** [comment]
My wallet address is 1KKqJkYVFYb5o4FpohaVBqakgCs7gJ75L5.

https://live.blockcypher.com/btc/address/1KKqJkYVFYb5o4FpohaVBqakgCs7gJ75L5/

Balance

0.03879413

Thanks

**Comment by mike1968mi** [comment]
Please help me. This is terrible.



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=purchasenames@gmail.com&idSignature=22>

**Comment by mike1968mi** [comment]
No, this is not closed. My funds are on YOUR server and COPAY has to
recover my wallet so I can get *MY* money.


You need another recovery system in place n the case of a natural disaster
such as hurricane, earthquake, flooding, tornadoes. etc.
If someone loses their home and all of their belongings, they should not
lose their money too. That is when they will need it most. In a flood or
earthquake, everything could be lost. Even a safe deposit box could be lost
and it happens all the time.
The phrase recovery system is flawed because you don't have the recovery
phrase yourself and that is a very bad system.

You find a way to recover my funds. The funds are stored on your servers so
COPAY is responsible for it and should have a copy of the phrase so when
the customer shows proof that it is their wallet, it can be recovered.

Thanks,

Michael Januszewski

1KKqJkYVFYb5o4FpohaVBqakgCs7gJ75L5



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=purchasenames@gmail.com&idSignature=22>

**Comment by gabrielbazan7** [comment]
The funds are NOT stored on BitPay servers. The private key (words) never leaves the device, all private keys are stored locally, so BitPay do NOT have access to your words either.

**Comment by Derrick-** [comment]
Pretty sure we're getting trolled here.

**Comment by mike1968mi** [comment]
Where are the funds stored?



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=purchasenames@gmail.com&idSignature=22>

**Comment by gabrielbazan7** [comment]
https://bitcoin.org/en/

**Comment by mike1968mi** [comment]
https://www.linkedin.com/pulse/copay-wallet-flawed-michael-januszewski?published=t
<https://mailtrack.io/trace/link/6b1dfd48f0a5790c9716afead0dc666f1d4b779f?url=https%3A%2F%2Fwww.linkedin.com%2Fpulse%2Fcopay-wallet-flawed-michael-januszewski%3Fpublished%3Dt&userId=1292198&signature=d04557c15d88d176>



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=purchasenames@gmail.com&idSignature=22>

**Comment by mike1968mi** [comment]
If the Bitcoin is not stored on Copay servers then how does Copay charge a fee when customers use their wallet?

**Comment by gabrielbazan7** [comment]
2. Fees calculated by Copay for sending are given to the Bitcoin miners, not Bitpay or anyone related to the Copay project.

**Comment by mike1968mi** [comment]
So how is the fee taken from my wallet if you do not have access to it? You
also have not told me where the funds are stored. What servers are my
Bitcoin on now?



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=purchasenames@gmail.com&idSignature=22>

**Comment by matiu** [comment]
> So how is the fee taken from my wallet if you do not have access to it?

@mike1968mi you need to educate yourself about Bitcoin,  a good place to start is:
https://en.bitcoin.it/wiki/Transaction_fees
