### ISSUE TITLE
Bitcoins nicht erhalten

### ISSUE THREAD

**Issue by Treimann2017** [bitpay/copay#6054]
Die Auszahlung(16.05.2017) über 0.206120 BTC (batch: c90506bed00884224c76fc5f8b895171a6c36d4e95baf3c8fe7960efc5285e24) wurde erfolgreich an .....
Warum sind die Bitcoins nicht in meinem e-wallet zu sehen?

**Comment by gabrielbazan7** [comment]
Hi, you still having this problem?
