### ISSUE TITLE
Missing Bitcoins from withdrawal

### ISSUE THREAD

**Issue by leelucasphoto** [bitpay/copay#6055]
Hi There,

24 hours ago I sent approximately 0.5 bitcoins to Poloniex exchange with the deposit address supplied by them. The transaction seems to have withdrawn from my Copay wallet but has since disappeared. I can't seem to find any transaction history in my Copay wallet to even track the block chain.

Can you please assist?

Thanks,
Lee.

**Comment by Perlover** [comment]
https://github.com/bitpay/copay/issues/6056

**Comment by leelucasphoto** [comment]
Thanks Perlover. Is there any direct technical support for the Copay app? I've read some of the threads about refreshing and re-installing but nothing is working. Surely having bitcoins going missing can not be acceptable standards by CoPay?!?!? How do we contact them directly to fix this? 

Thanks.

**Comment by gabrielbazan7** [comment]
Hi, you still having this problem?

**Comment by leelucasphoto** [comment]
Hi Gabriel,

Thanks for getting back to me. After some 36 hours it seems to have dislodged. The transaction has now shown up and funds have been received.

Thanks again for responding.

Lee.
