### ISSUE TITLE
Android Fingerprint "Use Backup" is broken

### ISSUE THREAD

**Issue by dmo580** [bitpay/copay#6058]
My understanding is the "Use Backup" feature is supposed to use your Device Password. This is a bit confusing unless it's spelled out. For other apps that use the Fingerprint API like banking apps, etc. if you don't want to use your fingerprint, you're supposed to login the old fashioned way using your account password.

What I think would make for a better user experience is that when you let a user setup fingerprint access, it's supposed to be linked to a passcode/PIN that is used to lock Copay. If the desire is not to confuse the user with yet another set of credentials, then it needs to be made clear that you're using your Android device passcode/PIN, in which you're introducing the user to another set of credentials that needs to be used for Copay anyway.

I still think the usage of a dedicated Copay PIN/password makes more sense. And on that note this maybe brings up the whole issue of the spending password. Perhaps it's time to rethink how you want to use all these protections--spending password, Copay access password. Maybe those two should be the same thing? I'm thinking out loud here but maybe have a security tab that allows users to setup what kind of security they want for Copay, and if they're allowed to use a fingerprint in place of entering those passwords. And before I forget there's also a wallet backup password right? In terms of UI/UX you might want to sort this out so users don't need to think about 4 different passcodes.

**Comment by gabrielbazan7** [comment]
We use the fingerprint that is already configure on the phone, because we believe that the phone owner is the same owner from the wallet, and also to avoid all the configuration process of the fingerprint. If you feel that someone could get in with the Device Pin, set you own PIN on Copay Options. 
I don't think a security tab will be a good idea, because, the protection for access the app is global and the spending password and fingerprint to protect sensitive information is at wallet level.

But yes, we have plans to remove the password to secure the recovery phrase for new wallets.

**Comment by dmo580** [comment]
I mean that's fine if you want to use the Device Password, but it needs to be clear what "Use Backup" means. I have seen no other app use the device password as a backup--Authy (iOS), Bank of America, Chase, LastPass, PayPal all fall back to their standard password/PIN login for their service.

I guess what I'm getting at is most apps including the OS basically make you set a password before setting up the Fingerprint as an alternative. I feel like that's the most sensible too for Copay--so basically let someone lock via PIN or Password and then allow Fingerprint to unlock in place of PIN/Password.

What I'm getting at with regards to a security tab is that there's too many password options right now and its buried in different places.

By the way why are you removing the password to secure the recovery phrase? How do you protect the backup then?

**Comment by dmo580** [comment]
Similarly, the "Cancel" button just puts you in an infinite loop of a fingerprint prompt. I would think if you want to cancel, you are taken back to the main screen where you are told to enter a seed manually or you are booted out of the app (exit).

I'm basically pushing for a more friendly UI/UX.

**Comment by dmo580** [comment]
@gabrielbazan7 Have you had a chance to look into this?

At the very minimum I feel that the Use Backup button should not take me into an endless loop.

Then there are the UI/UX improvements I talked about such as clarifying all the different passwords that one can use in Copay.

**Comment by JDonadio** [comment]
> let someone lock via PIN or Password and then allow Fingerprint to unlock in place of PIN/Password.

The PIN/Fingerprint are not available until the backup process are done. So when your wallet is secure you can use whatever option to lock the app. Also we are using the device fingerprint setup, and as the PIN/Fingerprint in Copay, it can be only set if you have a previous PIN configuration.

> Similarly, the "Cancel" button just puts you in an infinite loop of a fingerprint prompt.

That was modified adding a "dummy" state so you will be able to re-scan your finger tip or close the app instead.

**Comment by gabrielbazan7** [comment]
Hi @dmo580 no yet ! the use backup button still broken.

**Comment by JDonadio** [comment]
I think it's working now. Please reopen this if the error persist.

**Comment by dmo580** [comment]
I also would argue the same issue occurs on the iOS side where there is no backup method to login once you lock the app via fingerprint.

This comes down to a UI/UX issue where the app should be protected by a PIN/Password that's separate from the device password so that someone can have a fallback from fingerprint lock. I invite the developers to take a look at apps that allow TouchID/Pixel or Nexus Imprint like LastPass, Chase/Bank of America/PayPal, etc.

**Comment by gabrielbazan7** [comment]
Use backup option is working in version 4. You could set a PIN to avoid using the same security set it for the phone.
