### ISSUE TITLE
Insufficient fee

### ISSUE THREAD

**Issue by PatjeFR** [bitpay/copay#6062]
[https://www.mupload.nl/img/qtz416guzinxa.png](url)

[https://www.mupload.nl/img/qx5skgck5ocn8.png](url)

https://www.mupload.nl/img/qtz416guzinxa.png
https://www.mupload.nl/img/qx5skgck5ocn8.png

What is the problem?
I have enough funds?

**Comment by gabrielbazan7** [comment]
I can't see the images but take a look at https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-always-get-insufficient-funds-for-fee-when-trying-to-send
