### ISSUE TITLE
My Money Please!!!

### ISSUE THREAD

**Issue by mike1968mi** [bitpay/copay#6063]
I would like to get MY money from MY wallet that I can not afford to lose. You really need another alternative wallet recovery because this is unacceptable. What if someone has a fire and they lose the paper they wrote the phrase on? That is not fair, There really needs to be a back up recovery because this is terrible that I can not get my money from you. And it is terrible customer service when I get forwarded to another website and when I post something, my github account gets flagged for SPAM. This is absolutely ridiculous and I need MY money from MY wallet.  I will not accept this ridiculous scam and lose my money.  

How would you like it if you lost money? What if there is a natural disaster like a fire, tornado, hurricane etc and you  would need your money at a time like that? It is NOT fair that you have no backup alternative recovery for clients to recover their money. I can send you any information you need to verify it is MY wallet and MY money. This is starting to feel like CoinBase and Paypal. Unacceptable and I will not let you keep my money.

**Comment by gabrielbazan7** [comment]
BitPay do not have access to any of your funds. All private keys are stored locally. The private key never leaves the device, so for accessing a wallet funds it is necessary to have the device or a backup of the wallet. It is your responsibility. I'm sorry but there is nothing we can do.

**Comment by mike1968mi** [comment]
That is unacceptable. What if there is a fire,hurricane, tornado,
earthquake??? This is terrible and I really need my $100 in Bitcoin that I
would really like to invest if you wouldn't mind. I am on disability and
was in a bad car accident and I am trying to find a way to make some money.
My auto insurance screwed me over just like every other company screws
every one over in this screwed up world.

I want MY money from MY wallet. By due process of law, you can not keep it
from me. It is MINE and I want it.

The company should have a backup recovery in place in the case of a natural
disaster or other unfortunate events.

The company has to help me get my money. I don't care ho wit is done, I
want my money. It is really rotten that this would happen and I already had
to go out and buy a new laptop and the first thing I did was go to my
wallet and I can't get in. That is rotten and unacceptable.

I want my money and I don't care how it is given to me. I don't care if I
have to file complaints or lawsuit, you are not entitled to keep my money
from me.

This is absolutely ridiculous. Regulated banks even have ways to recover
bank accounts. They don't just say we can't help you, its your
responsibility.

I entrusted Copay with my money and it is YOUR responsibility to make sure
that I get it back. I don't care if you have to take up a office collection
*,* I want *MY *money.

Thank you and you might want to get a customer service department on the
Copay.io website instead of sending your clients to another website that
they are not familiar with.

Thanks a lot and I will be the biggest pain you have ever seen until I get *MY
*money from Copay*.*







  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=purchasenames@gmail.com&idSignature=22>

**Comment by Derrick-** [comment]
One time (not really), I bought a wallet at JC Penny, then I lost the wallet, it had $100 in it (not really).

JC Penny wouldn't give me my money back, but they didn't have my $100 either.

**Comment by mike1968mi** [comment]
Seriously? I am forwarding your insulting email to Copay founders and
Executives on LinkedIn. Whoever you are, you have no business
insulting a customer and have no business in customer service.



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=purchasenames@gmail.com&idSignature=22>

**Comment by mike1968mi** [comment]
Hey Mr. Derrick, your incredibly bad customer service response has been
sent to th eco founders of Copay on linked mail.

Have a nice day!



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=purchasenames@gmail.com&idSignature=22>

**Comment by mike1968mi** [comment]
Hello Derrick? No response? Even more bad customer service that the senior
staff is going to read in their inbox including the co founders.

Is James Walpole one of your bosses?

**Comment by matiu** [comment]
FWIW, @Derrick- is not part of Bitpay Team. Anyone can respond this threat.


 Copay and most wallets for cryptocurrency wallets that way, *you* need to take care of the backups. If you prefer a more "bank" approach, in which a company manage your keys, I suggest you try Xapo or Coinbase.

matías

**Comment by mike1968mi** [comment]
No, the funds are kept on Copays servers and Copay is responsible for
helping the client recover any funds that are on Copays servers. You need
another recovery system in place n the case of a natural disaster such as
hurricane, earthquake, flooding, tornadoes. etc.
If someone loses their home and all of their belongings, they should not
lose their money too. That is when they will need it most. In a flood or
earthquake, everything could be lost. Even a safe deposit box could be lost
and it happens all the time.
The phrase recovery system is flawed because you don't have the recovery
phrase yourself and that is a very bad system.

You find a way to recover my funds. The funds are stored on your servers so
COPAY is responsible for it and should have a copy of the phrase so when
the customer shows proof that it is their wallet, it can be recovered.


Michael Januszewski




  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=purchasenames@gmail.com&idSignature=22>

**Comment by matiu** [comment]
> No, the funds are kept on Copays servers and Copay is responsible for
helping the client recover any funds that are on Copays servers.

That is incorrect. The only way to move your bitcoins is to sign a transaction that only the client has. The key is stored client side, and the is a forced backup procedure when a wallet is created. With that backup you can derive the key again and move the funds. But the key never is send outside the device.

**Comment by mike1968mi** [comment]
So where is the Bitcoin and the phrase stored exactly?



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=purchasenames@gmail.com&idSignature=22>

**Comment by gabegattis** [comment]
@mike1968mi  The funds are stored on your device and only on your device. BitPay has no possession or control of any funds stored in any Copay wallet at any time. This is by design. The user is the only person who ever has control and possession of the funds.

BitPay is not a bank. We do not hold funds on behalf of our users. We merely provide the software to allow users to manage the funds themselves. This is why we make it very clear that the user should write down the backup words and store them in a safe place. In this sense, BitPay is more analogous to a company that sells safes or physical wallets. If you forget the combination to your safe, or you lose your wallet, the company is unable to help. The only difference is that a Bitcoin wallet is like a safe that can never be cracked by a locksmith.

Without your private keys or the 12-word backup, there is no way to recover the funds. Without those, it would be impossible for us to recover those funds, even if we wanted to.

**Comment by mike1968mi** [comment]
If you buy a safe, the safe company has a copy of the combination and /or
key.

Every other currency company online is also not a bank like for example,
Paypal. However, if you lose your Paypal password, you can recover it from
Paypal.



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=purchasenames@gmail.com&idSignature=22>

**Comment by mike1968mi** [comment]
Did you start an office collection yet for my $100 loss because of the
Copay flawed system?



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=purchasenames@gmail.com&idSignature=22>

**Comment by bitjson** [comment]
@mike1968mi Bitcoin wallets provide the possibility for you to completely control your money and avoid losses from companies going bankrupt or getting hacked. We have no plans to turn this software into a custodial service. 

See the [Bitcoin Wallet Comparison](https://bitpay.com/docs/wallets) for alternatives that better suite your needs. You're probably looking for something in the "Bitcoin Account Services" section.
