### ISSUE TITLE
Feature request: Copy adresses to clipboard

### ISSUE THREAD

**Issue by MrTschi** [bitpay/copay#6064]
Hi,
I have a Feature request: I would like to copy adresses from the page "Settings > WalletName > Additional options > Wallet Addresses" to clipboard. This is atm not possible. 

Thank you,
Regards
Max

**Comment by dabura667** [comment]
Yes it is. Tap an address.

**Comment by MrTschi** [comment]
Hm okay after app hard restart everything works as expected. 
Thank you for your help!
