### ISSUE TITLE
The problem with the last transaction. The funds arrived and then disappeared from the wallet.

### ISSUE THREAD

**Issue by bitcsat68** [bitpay/copay#6065]
Hello all community.
 I have such a problem : On May 6, 2017 the funds were sent to my Copay wallet and went to the blockchain. 
ID 11dfa75d6514e4055eb9ff40b9025bbe5c87314effdf544bb59c13f930f80854
https://bitaps.com/11dfa75d6514e4055eb9ff40b9025bbe5c87314effdf544bb59c13f930f80854
Already here about two weeks I wait for confirmation.

PS Why do I write in this forum?
 As on May 6 the funds were on my Copay wallet already and the story showed the availability of funds on it. But today, at the entrance to the Copay wallet, I found a lack of history in my wallet and money, then I found my transaction unconfirmed.
It is very strange! Help me to understand.
If the transaction has not yet been confirmed - how did the money come to the wallet first and then the receipt history disappeared from the wallet??

Help please support the Copay!
I understand that there may be a problem in the low commission and because of this the transaction has not been confirmed for so long.
What can I do in this situation? How can you help me and how long do I need to wait for the transaction confirmation?
Thanks in advance.

**Comment by gabrielbazan7** [comment]
Hi! your transaction is already confirm, you still having this issue ?

**Comment by bitcsat68** [comment]
Now its fine.someone helped me with this transaction confirming. Can close this topic.
