### ISSUE TITLE
Cant create TestNet account with Specified Recovery Phrase option

### ISSUE THREAD

**Issue by JulianTosh** [bitpay/copay#6068]
When you try to create a testnet account and select "Specify Recovery Phrase" under "Wallet Key", the option "Testnet" and its selector disappear and revert to the off position.

It is impossible to create a testnet account with a custom recovery phrase.

![screenshot from 2017-05-18 07-50-53](https://cloud.githubusercontent.com/assets/627143/26208379/c39af6ce-3b9e-11e7-986c-0e5322fd8467.png)
![screenshot from 2017-05-18 07-50-13](https://cloud.githubusercontent.com/assets/627143/26208380/c3a23790-3b9e-11e7-98b5-45329f9020a2.png)

**Comment by JulianTosh** [comment]
Using version 3.2.0 on android and linux.

**Comment by matiu** [comment]
Hi @JulianTosh 

Please see:
https://github.com/bitpay/copay/issues/3520

you need to modify the path to support testnet. I know it not a great solution, but given the different paths, etc, and that this flow is not that common, we decided to do it that way.

**Comment by avibrazil** [comment]
So this is on purpose ?????????
Creation of specific wallets is already too cumbersome. To hide this flag makes it harder.

The workflow for specific wallets is very common when transferring wallets from one software to another or when dealing with backups. These kind of tasks are very needed in a world where the user is solely responsible of managing his funds. Also, I see no reason to hide it when you select to specify your own recovery phrase, both config items are completely unrelated. Is this to be more economic on screen space?

Testnet is extremely useful to teach about wallet management. Testnet is vital for basic bitcoin education.

Please bring the flag back.
