### ISSUE TITLE
"Add a passphrase" input control needs a visibility or verification option

### ISSUE THREAD

**Issue by JulianTosh** [bitpay/copay#6069]
Using 3.2.0 on android and linux.

When creating a wallet with an additional password option, it is too easy to mistype the passphrase and there is no ability to detect the mistake. There needs to be either a visibility option, or a confirmation input.

![screenshot from 2017-05-18 07-54-20](https://cloud.githubusercontent.com/assets/627143/26208591/592945a6-3b9f-11e7-8e2c-05a3694517e9.png)

**Comment by matiu** [comment]
agree, good catch.

**Comment by dmo580** [comment]
Yes, any password registration field IMO deserves a confirmation prompt.
