### ISSUE TITLE
access private key for a specific wallet address

### ISSUE THREAD

**Issue by seekr** [bitpay/copay#6071]
I "stored" maidsafe tokens on a copay wallet address before realising how difficult it would be to get the corresponding private key to let me manage those.

I can see the tokens in the address using omni chai. 
Then I used bitwiseshiftleft.github.io/sjcl with the copay wallet export file to get a xPrivKey. I then imported (not xPrivKey but the walletPrivKey) into OmniWallet, but the resulting public address is not the same as the one which has the maidsafe tokens stored.

Can someone help me understand whats going on? How can I regain control of the maidsafe tokens?

**Comment by dabura667** [comment]
> how difficult it would be to get the corresponding private key to let me manage those.

1. 12 word backup phrase you wrote down when you created the wallet.
2. plug into here under "BIP39 passphrase": https://bip32jp.github.io/english/
3. Change Derivation path to "BIP 44 .... (receive)..."
4. Keep adding 1 to Keypair Index (i) until you see the address. The private key is right above there.

You can download the website from github too and run it locally.

**Comment by seekr** [comment]
@dabura667 thanks, will this taken a billion tries? or are wallet addresses generated sequentially? I can see 20 address generated and listed in my Copay wallet (with a xPub/0 number) right now.

**Comment by dabura667** [comment]
xpub/0/13 is 13 on the Keypair index.

**Comment by seekr** [comment]
ahh just noticed that the address in question doesn't have a index number associated with it. in fact all address with btc stored do not have a index number (and the one I'm trying to get a priv key of, has some btc)

**Comment by seekr** [comment]
@dabura667 thanks! got it. It was missing the optional password. From this experience it looks like the address are indeed listed sequentially.
