### ISSUE TITLE
Unable to utilize purchased Coinbase funds

### ISSUE THREAD

**Issue by JChristen81** [bitpay/copay#6074]
I have successfully linked my Coinbase account with this co-pay wallet. I initiated a purchase,  and I received an error message in the Copay app stating transaction could not be found. However… The purchase of the Bitcoin  did indeed transact in coin base and they are in my Coinbase account, however, co-pay will not allow me to utilize the funds to send or anything for that nature it is as though it did not exist although it did. Could you please explain to me if this is a known bug or if this is a feature I'm not quite understanding? I'm not really sure what the point of being able to purchase bitcoin through Coinbase on Copay if I can't utilize the funds as well.

**Comment by JChristen81** [comment]
Sorry using version 3.2.1 on iOS 10.3.1

**Comment by goferit** [comment]
Same here.

**Comment by JDonadio** [comment]
Already fixed in the latest release and will work for new purchases. Sorry about that.
For new reports or updates please follow [this thread](https://github.com/bitpay/copay/issues/6189). Thanks in advance.
