### ISSUE TITLE
Unconfirmed transaction for days

### ISSUE THREAD

**Issue by saifesa1** [bitpay/copay#6075]
Hi, Have a transaction shown as unconfirmed since 17th May - has been 2 days++ so far. Any help please?
<img width="986" alt="screen shot 2017-05-19 at 10 08 06 pm" src="https://cloud.githubusercontent.com/assets/25971939/26251446/ddbba4b2-3cdf-11e7-93b2-8f04397d810b.png">

**Comment by gabrielbazan7** [comment]
Hi! your transaction fee is too low, the funds will return to your wallet in less than a week.

**Comment by hoangthanhzz** [comment]
Please help me -my transaction fee is average , but the funds pending more than 6 days, please help me

**Comment by gabrielbazan7** [comment]
Copy the transaction id here

**Comment by hoangthanhzz** [comment]
this was my transaction, it was pending 6 days , please check it and help
me , thanks for support

https://insight.bitpay.com/tx/ea4c72069285c2aba3d1af571413ab3c10e66365e716a460079b5f2d07f0f5cc


2017-05-22 19:58 GMT+07:00 Gabriel Edgardo Bazán <notifications@github.com>:

**Comment by gabrielbazan7** [comment]
Ok it seems that the transaction was dropped. You should see your funds in you wallet now. For future transaction, you could have an idea of a proper fee in this site https://bitcoinfees.21.co/
