### ISSUE TITLE
"Slide to accept" slider disappear 

### ISSUE THREAD

**Issue by gabrielbazan7** [bitpay/copay#6079]
Samsung s4

<img width="421" alt="screenshot_2017-05-19-10-16-31_png__1080x1920_" src="https://cloud.githubusercontent.com/assets/10999037/26260898/8276f6c2-3ca5-11e7-9d64-f90c55e05e0a.png">

**Comment by absordie** [comment]
do you know how to fix this problem? i have it to...

**Comment by gabrielbazan7** [comment]
Try sliding where the slider should be.
