### ISSUE TITLE
No recuerdo las 12 palabras de monedero Copay

### ISSUE THREAD

**Issue by Mariapazbr** [bitpay/copay#6083]
Buenas noches, he copiado las palabras de el monedero copay pero no me ha dejado ingresar, no estoy segura de la ultima palabra, por favor podrian ayudarmen con este problema.

**Comment by matiu** [comment]
Hola!

Las palabras se buscan entre una lista de ~2000 palabras, La lista esta aquí: https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md


tal vez la lista puede ayudarte a recordar la última palabra?

**Comment by Mariapazbr** [comment]
Muchas gracias, pude solucionarlo
