### ISSUE TITLE
  IP Address / Servers

### ISSUE THREAD

**Issue by mike1968mi** [bitpay/copay#6084]
What is my Copay Wallet IP address? What servers are my Bitcoin stored on? 

My wallet address is 1KKqJkYVFYb5o4FpohaVBqakgCs7gJ75L5

You have my Bitcoin somewhere on your servers so give it back. This is a scam.

**Comment by dabura667** [comment]
You don't know how Bitcoin works.

If you would like me to explain to you how Bitcoin works I can give you a simple non-technical explanation of how it works and walk you through the source code of Copay to show you why Bitpay has no access to your funds.

I am not associated with Bitpay in any way, but I have contributed to the project and understand how it works.

However, if you're just going to get emotional and curse at me and yell at me, then I don't want to waste my time.

The offer stands under the condition that you are civil.

Let me know when you are available to talk.

**Comment by mike1968mi** [comment]
When have I been "emotional", 'cursed" or "yelled" at anyone?

Other online currency wallets have a recovery using an email and other
forms of verification that I would have and not lose in a natural disaster
or an unfortunate event.

All I want is my Bitcoins and it has to be stored somewhere on a server.



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=purchasenames@gmail.com&idSignature=22>

**Comment by mike1968mi** [comment]
So Copay say's my funds are stored on my device but my devise has
malfunctioned and is not working. So how could I recover the wallet on
another devise if it is stored on the devise that I downloaded the wallet
software on?



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=purchasenames@gmail.com&idSignature=22>

**Comment by dabura667** [comment]
> So how could I recover the wallet on
another devise if it is stored on the devise that I downloaded the wallet
software on?

You install Copay on a new device and type in the 12 word phrase.

That 12 word phrase is placed into an algorithm that generates a key. The key is stored on your device. The same phrase will always generate the same key, therefore the 12 words THEMSELVES are a representation of your master private key.

The 12 words nor the key never leave your device. The Copay servers just answer your app's questions like "How many bitcoins are in address A? (So I can show it to my user)"

**Comment by dabura667** [comment]
Which is why there are 5 or 6 big red scary looking pop ups telling you to write down the phrase and never lose it, and don't screenshot it... because if anyone steals it, they can recreate your wallet perfectly.

**Comment by mike1968mi** [comment]
I know I install Copay on a new devise. My question is, where is that
phrase stored? If I am downloading the wallet on a new device, the phrase
is not on the software yet. It must be stored on Copay servers. What am I
missing here because it makes no sense to me what you are telling me.

And there is this:

https://insight.bitpay.com/address/1KKqJkYVFYb5o4FpohaVBqakgCs7gJ75L5
<https://mailtrack.io/trace/link/f4b4c2aa0bc6cd07e9a6a39626d41dff6693b881?url=https%3A%2F%2Finsight.bitpay.com%2Faddress%2F1KKqJkYVFYb5o4FpohaVBqakgCs7gJ75L5&userId=1292198&signature=ddba4b90be19cb40>

It appears my funds are stored on Copay servers and it is on the internet,
not just my wallet that no one supposedly has access to.

Is there *any *record of the phrase words on your servers for the time that
I created my wallet? I think there is a record of everything is done on the
internet. There has to be some way to recover my funds. I can look up the
wallet address online, in my browser and it shows my balance and
transactions.



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=purchasenames@gmail.com&idSignature=22>

**Comment by Derrick-** [comment]
This is really very simple.

The phrase is your money, and only you have a copy of it. There is no money on copay servers. If you have the phrase you have your money, if you do not have your phrase you don't.

No one else has your phrase, unless you told it to them, therefore no one else has your money.

CoPay stores your phrase on your device. If you put your phrase into another wallet software then you're money will be in that wallet software. Your loss of the phrase has nothing to do with CoPay.

**Comment by mike1968mi** [comment]
That does not answer the question. Where is the phrase right now, at this
moment? If it is in my wallet, on my devise that is no longer working, how
does it get moved to another devise? It must be on the internet somewhere
on some server. Right? If I lose my wallet with money in it and get another
wallet, I can't get the money from the lost wallet unless it is stored
online on a server.

You track my transactions on Bitpay too.

If I go to the bank, and deposit money, they track it. If I lose the
receipt, my wallet and even my account number, I can recover it from the
bank because they track it. If I lose my bank info in an earthquake, I can
go to the bank and recover my account.

If I have funds in my Paypal account and I forget my password, I can
recover my account by providing them information and they give back m]y
access to my funds.



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=purchasenames@gmail.com&idSignature=22>

**Comment by mike1968mi** [comment]
<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=purchasenames@gmail.com&idSignature=22>

**Comment by dabura667** [comment]
Your phrase is on the device you originally created it (which you say is broken) unless you wrote it down or something.

Just because you can see something on the internet doesn't mean anything.

I can place a camera in your locker, and broadcast the contents of your locker on the internet, but that doesn't mean that your locker's combination is definitely on the internet.

**Comment by mike1968mi** [comment]
That is a terrible analogy but anyways...

If the camera had the combination stored on it, it could possibly leave a
record of it on the internet.

Lets say I open a new wallet on a device and then download it on another
devise and then disconnect from the internet. Could I recover my wallet
with no internet access with the phrase when I open it for the first time?



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=purchasenames@gmail.com&idSignature=22>

**Comment by dabura667** [comment]
> Could I recover my wallet with no internet access with the phrase when I open it for the first time?

Yes.

I give up trying to explain to you. You're extremely rude.

**Comment by mike1968mi** [comment]
Excuse me??? I have not been rude to you at all. I am only trying to get my
bitcoin back from Copay servers.

I have a new Copay wallet since you won't help me recover my first wallet
where my Bitcoins are. So I was able to enable email notifications on the
wallet...how can I enable email notifications if you are not storing my
email on your servers? And how can I have the wallet URL if you are not
storing it on your servers? It makes no sense and now you won;t explain it
because you can't. The only thing that makes sense is the system is flawed
or not what you say it is.

Thank you.



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=purchasenames@gmail.com&idSignature=22>

**Comment by dabura667** [comment]
Email addresses are stored on the server.

Your phrase is not.

Read the user agreement that you agreed to when opening the app.

Ok, awesome. You say I don't understand how Copay works, so then I don't need to deal with you anymore because I can't, right. Perfect.
