### ISSUE TITLE
Warum kann ich nicht alles abheben?

### ISSUE THREAD

**Issue by neotribe** [bitpay/copay#6085]
Hi,ich habe auf meinem Konto 0.012 btc und wenn ich den gesamten Betrag minus Gebühren verwenden will, heisst es die Gebühr reicht nicht. Wie kann das sein,wenn die Gebühren auf normal eingestellt ist?

**Comment by matiu** [comment]
Hello, sorry  we only provide support for english or spanish.

**Comment by neotribe** [comment]
Ok thanks...

the problem is that I can not stand out anything. Although I have 0.01 btc in the account, it means the fees are not enough. That can not be
