### ISSUE TITLE
Unable to send

### ISSUE THREAD

**Issue by unsntoppable** [bitpay/copay#6086]
I am trying to send max amount from Copay.  A couple of times I have been asked to confirm the amount to send.  Otherwise, I am repeatedly getting 4 different errors:  Network error.  Unavailable unspent outputs.  Could not update wallets.  Insufficient funds.  It switches between the errors.  Regardless, it is not sending.  I just set copay up and this is my first send.

**Comment by matiu** [comment]
this is probably a network issue. Copay servers use cloudflare to prevent certain types of network attacks, and some networks are restricted. Try changing your network and try again.

**Comment by unsntoppable** [comment]
Thank you.  How do I change the network?

**Comment by unsntoppable** [comment]
It finally started showing sending yesterday morning and is still showing sending today.  I tried to Delete Payment Proposal and start over.  It say Error Could not delete payment proposal:  Network error.

**Comment by ChristianLawson** [comment]
I get the same

**Comment by nicoverna** [comment]
did you guys solve this issue? i get the same error, "insufficient funds for fee" while i have 0.009381 btc, and fee is about 0.00000122 BTC,  what i'm doing wrong?

**Comment by JDonadio** [comment]
@nicoverna please read https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-always-get-insufficient-funds-for-fee-when-trying-to-send

**Comment by nicoverna** [comment]
so, copay got my btc and now i can't use them?

**Comment by nicoverna** [comment]
I only buy BTC once, to see how it works. 
it's not the case you mention above.
i bought 0.01 btc in july and now i want to get my money back, @JDonadio i need your help please!

**Comment by JDonadio** [comment]
Copay is not the owner of your funds. If you import your backup in other wallet you'll see your balance there.

Provide us your wallet id, you can find it in settings > wallet > more opts > wallet information

**Comment by nicoverna** [comment]
e6bf910f-5555-4a63-9baf-5e55242341af

**Comment by JDonadio** [comment]
Try using the send max option

<img width="397" alt="cursor_y_copay_-_copay_bitcoin_wallet" src="https://user-images.githubusercontent.com/13851807/29972870-07a38332-8f04-11e7-8a5e-6254b041c33d.png">

**Comment by nicoverna** [comment]
Problem solved, transaction is pending but will be accredited in 1-2 days.
@JDonadio Javier sos una locura, despues te cuento si pude cerrar el ciclo del retiro, Gracias!
Thnx dude you are awesome!
