### ISSUE TITLE
"Delete recovery phrase" option disappeared

### ISSUE THREAD

**Issue by avibrazil** [bitpay/copay#6091]
I'm not sure if this in on purpose. If so I fail to understand the reason.
In Copay 3.2.1 (iOS) there is no option to delete the recovery phrase, when compared to 2.7.
Availability of recovery phrases make it a bit easier to steal your wallet, so they should be deleted after transferred to some sort of user backup.
Please bring this option back !
Thank you

**Comment by gabrielbazan7** [comment]
Look at: https://github.com/bitpay/copay/issues/5361. 
Remember that you could protect all the sensitive information with the spending password encrypt your privkey. 
Also, if you delete the words, someone could go to wallet settings -> more options -> backup and copy that backup with the private key or send it to his email. (the spending password also protect this option)
