### ISSUE TITLE
Testnet flag on wallet creation form disappears in certain conditions

### ISSUE THREAD

**Issue by avibrazil** [bitpay/copay#6092]
This is UI bug on 3.2.0 and 3.2.1 that can be reproduced like this:

1. New personal wallet
2. Show advanced options
3. Select "specify recovery phrase" on wallet key option
4. Bang! Testnet flag disappears.

**Comment by gabrielbazan7** [comment]
HI!! take a look to https://github.com/bitpay/copay/issues/6068

**Comment by avibrazil** [comment]
Handled by issue #6068
