### ISSUE TITLE
COPAY FRAUD. COPAY STOLE MY BITCOINS

### ISSUE THREAD

**Issue by mike1968mi** [bitpay/copay#6093]
How many others here have had their Bitcoin with held from them by COPAY? I'm sure the very rude, so called "customer support" will close and lock this issue before anyone can reply. 

I wonder how many Bitcoins COPAY is storing on their servers and won't let us have them back because we don't have their phrase that is also stored on their servers. **Complete scam.** And the worst customer service ever.

**Comment by matiu** [comment]
Copay servers do not store your bitcoins, it has been explained to you multiple times,and  copay itself explain this when it force you to do a backup. I suggest you to expend sometime trying to understand how bitcoin works before wasting your time, and ours, here.
