### ISSUE TITLE
Ability to delete private key from wallet

### ISSUE THREAD

**Issue by avibrazil** [bitpay/copay#6095]
I want to keep a watch-only version of one of my wallets.
Currently, on Copay UI, the only way to do it is to create/import the wallet through is phrase or QR code, export it without private key and re-import it again. Cumbersome.

It would be useful to simply delete an existing wallet private key to make it useless for spending but still "watcheable". Without export+import operations.

An additional feature of this idea is to start with a wallet without a private key (watch only wallet) and be able to re-add its private key again, through mnemonic typing, without having to delete the wallet and re-import it.

Thank you

**Comment by avibrazil** [comment]
BIP39/32/44 make wallet management easier.

But Copay UI is not optimized for a little bit more advanced usage scenarios. My wife can't used it. I can use it because I invested a lot of time studying what happens under the hood. Mycelium, although much simpler and limited, is more intuitive for multi-wallet management.

**Comment by JDonadio** [comment]
We are trying to get the best user experience for all of our users, sometimes a good feature for me could be unuseful for you. In this case we remove the delete option for recovery phrase https://github.com/bitpay/copay/issues/5361
