### ISSUE TITLE
Please support me, my transaction was pending 6 days

### ISSUE THREAD

**Issue by hoangthanhzz** [bitpay/copay#6098]
I sent 6.999btc , but it was pending , please support me!
 This is my transaction , it was unbeliveable

https://insight.bitpay.com/tx/ea4c72069285c2aba3d1af571413ab3c10e66365e716a460079b5f2d07f0f5cc

![image](https://cloud.githubusercontent.com/assets/28859229/26338038/4d8963dc-3fa7-11e7-8c5f-53d2faf999d2.jpg)

**Comment by gabrielbazan7** [comment]
Just wait for the transaction to get confirmed or dropped for the network ( the funds will return to your wallet ). I recommend you to set a fee based of this page https://bitcoinfees.21.co/ for the future in such big transactions.

**Comment by hoangthanhzz** [comment]
thanks for your explaination , gabrielbazan7

**Comment by hoangthanhzz** [comment]
oh my godness! my bitcoin has been gone back my wallet for 2 days, but today i log in in oder to transfer my bitcoin , bitcoin again are sending like this , why is the order again  processed , please support me

https://insight.bitpay.com/tx/ea4c72069285c2aba3d1af571413ab3c10e66365e716a460079b5f2d07f0f5cc

**Comment by hoangthanhzz** [comment]
i waited for 8 days to get back my bitcoin into my wallet, and now it continue to send my bitcoin again

**Comment by gabrielbazan7** [comment]
You set a low fee again. You use the super Economy option ?

**Comment by hoangthanhzz** [comment]
no , i set a urgent fee yesterday , but i did not send the bitcoin again , after 8 days in pending . in the evening i came back my wallet , i saw my bitcoin was sent again as old transaction , i do know what happen , i asks my friends ,they answered the copay 'error , this situation happened in blockchain wallet but it is oke now, and copay in this situation

**Comment by gabrielbazan7** [comment]
You should see the funds in you wallet now. Please re open the ticket if you still having problems
