### ISSUE TITLE
Feature request and v3.2.0 gets flagged as containing Uds.Dangerousobject (trojan?) by Kaspersky

### ISSUE THREAD

**Issue by Bits-of-Wisdom** [bitpay/copay#6101]
The latest release of Copay.exe v3.2.0 gets flagged as containing Uds.Dangerousobject (trojan?) by Kaspersky.
You can confirm that at:
virustotalDOTcom

So... I did not install it. The question is if this is a false positive or a real problem?
Also, it would be really helpful to users if SHA-256 checksums are provided for all the files, since these are much easier to check against using QuickHash(GUI) than checking pgp signatures.
In addition, a PIN to open the actual application would be nice as well as a BLACK theme for the application (night mode).

Many thanks! 
Please let me know when it is safe to use.
Best wishes!

**Comment by JDonadio** [comment]
Please see https://github.com/bitpay/copay/issues/6471#issuecomment-318103137
