### ISSUE TITLE
Copay won't connect with Coinbase

### ISSUE THREAD

**Issue by PelLihi** [bitpay/copay#6105]
I'm using an iphone 6 and did already sell BTC from Copay to Coinbase before. But since a couple of days it always gives me the error message "Error connecting to Coinbase - The access token is invalid"?!
Any ideas on how to solve this issue?

thx

**Comment by cmgustavo** [comment]
Could you try to close and restart the app? If it doesn't work, try to connect to coinbase again (as you did the first time). Probably it 's an issue from Coinbase while trying to get token twice.

**Comment by goferit** [comment]
Same here, re-connecting didn't work.

**Comment by cmgustavo** [comment]
Could you try to "Log out" from `Settings` -> `Wallets & Integrations` - Coinbase -> `Log out` and reconnect again?
