### ISSUE TITLE
Error. Could not send payment: The payment was created but could not be completed. Please try again from the home screen. 

### ISSUE THREAD

**Issue by Chris869218** [bitpay/copay#6106]
Hello, I'm getting the error in the title when I try to create or sign a transaction from a trezor hardware wallet that is part of a multisig wallet. The payment proposal gets created, and others are able to sign it, but I an unable to. Any reason why this could be happening? Using copay 3.2.1 (chrome extension). Thanks.

**Comment by JDonadio** [comment]
Hi there, can you please attach some screenshots?

**Comment by Chris869218** [comment]
Here is the error message: http://imgur.com/a/b2Yn9

**Comment by Chris869218** [comment]
I tried uninstalling and re-installing copay and that didn't work. I tried signing with a ledger hardware wallet instead (also part of the same multisig). It also fails, but with a different error. The ledger app displays a message that the signature was successful (https://imgur.com/a/3qTu7) but back in copay, the message is the signature failed: https://imgur.com/a/Z8QRk. Signing from a mobile Copay wallet had no problems.

**Comment by Chris869218** [comment]
I tried again and got another similar but different error message: https://imgur.com/a/4z8rz

**Comment by Chris869218** [comment]
More information: copay states "A payment proposal can be deleted if 1) you are the creator and no other copayer has signed, or 2) 24 hours have passed since the proposal was created." As far as I have seen, copay has always enforced these. In regards to this situation, copayers who were not the creator are able to delete a proposal even after others have signed (<24 hours elapsed) assuming they signed from non-hardware wallets (which are still unable to sign). Thanks in advance for any assistance.

**Comment by matiu** [comment]
This error was fixed on Copay 3.5.0.

The problem happened when importing Hardware multisig wallets with Account >1. The account number was not been set correctly, so the signatures where rejected.

To solve, please delete and reimport your wallet.

thanks.
