### ISSUE TITLE
Unconfirmed transaction 

### ISSUE THREAD

**Issue by M1bhai** [bitpay/copay#6110]
Hello, somehow I sent BTC with a low fee. Now it is unconfirmed transaction all day... How long will it take for the funds to go back to my wallet! 
Please see below 

https://insight.bitpay.com/tx/2539ee616cd0c8f878fcee4f1347a59be2254a5237183bccc38642ecf2171c55

**Comment by gabrielbazan7** [comment]
~ a week

**Comment by mnfirdaus** [comment]
just wait

**Comment by M1bhai** [comment]
Hi gents thanks my coins came back already in my wallet .. can I send now again? Or do I have to wait??

**Comment by JDonadio** [comment]
You can use that funds again, but make sure to use a higher fee 😉

**Comment by M1bhai** [comment]
Hello . I tried to transfer 1 BTC and it is showing transaction not found in "Bitpay" so it's hasn't even made it to the blockchain... I don't know why this is happening, as my coins came back and I tired to send with a notmal fee and it's showing as invalid transaction

**Comment by JDonadio** [comment]
@M1bhai first all create a fresh wallet, then use the [recovery too](https://bitpay.github.io/copay-recovery/)l to move your funds into the fresh one.

**Comment by M1bhai** [comment]
Well first I will wait till my coins come back again before I can do anything... i was told that I could use the coins once they come back to my account.. this is unnecessary and causing me grief. This is our savings we have invested in these coins and going through all this nonsense!!

**Comment by M1bhai** [comment]
May someone please explain to me if my bitcoin will come back to my copay wallet? ... after it says transaction not found.. and also will I ever be able to use my current wallet again? Is it necessary for me to use the recovery tool?

**Comment by anoxindv** [comment]
Good afternoon! He sent the coins to the Copay purse from another purse. By mistake, I managed with a low commission. On a blockchain, the transaction is displayed as unconfirmed. Has passed more than a day! How much longer do I have to wait? Will my coins reach? Thank you

**Comment by gabrielbazan7** [comment]
~ a week the funds will be on the sender wallet again, you have to wait. For future transactions you could have an idea of the fee you need to get a fast confirmation in this site https://bitcoinfees.21.co/

**Comment by M1bhai** [comment]
@gabrielbazan7 hello brother .. my coins came back after less than 2 days in my wallet. I tried to transfer 1 coin but it says unknown transaction in bitpay., so I'm very worried, please tell me what to do? If I wait will it resolve itself ? I don't want to use recovery tool if I can wait,  can you please advise me bro I appreciate it 😊

**Comment by gabrielbazan7** [comment]
Could you show me an screenshot of the error please ?

**Comment by M1bhai** [comment]
![img_0055](https://cloud.githubusercontent.com/assets/28943573/26523322/843db83c-42d2-11e7-83db-438399e9c53f.PNG)

**Comment by M1bhai** [comment]
@gabrielbazan7 there it is of you view that in bitpay it's unknown transaction 

![img_0055](https://cloud.githubusercontent.com/assets/28943573/26523328/a28fd05e-42d2-11e7-9be7-82bc655f1c76.PNG)

**Comment by gabrielbazan7** [comment]
Where is the error ? ajaj

**Comment by M1bhai** [comment]
![img_0056](https://cloud.githubusercontent.com/assets/28943573/26523352/27365468-42d3-11e7-9754-b8b4ac3207e9.PNG)
@gabrielbazan7 if I click to see in block chain it says unknown see pic and last pic shows the transaction I just click to see and it says unknown

**Comment by anoxindv** [comment]
Hello brother, I myself with such a problem, the transaction hangs over a
day and nothing happens. If your money has returned, please increase the
amount of transfer commission, it should help!

2017-05-27 20:44 GMT+03:00 Gabriel Edgardo Bazán <notifications@github.com>:

**Comment by M1bhai** [comment]
@gabrielbazan7 

Hello Gabriel. The coins came back. It was 1 week. i try to send out again and it says invalid transaction in the bitpay. So what am I supposed to do, will you please recommend a solution to this problem. Thanks MS

**Comment by gabrielbazan7** [comment]
Can you show a screenshot of the error ?

**Comment by M1bhai** [comment]
@gabrielbazan7 

When I click to view transaction this is what comes up it says invalid 

![img_9028](https://cloud.githubusercontent.com/assets/28943573/26657799/5c587420-4623-11e7-95c9-35c6228c6b47.PNG)

**Comment by M1bhai** [comment]
@gabrielbazan7 

Hi Sir. After 8 days the original transfer got confirmed. So everything is ok now and you can close this entry please... kind regards :)

**Comment by kkining** [comment]
Hi Sir, I got the same problem. I have three transactions that were unconfirmed for almost 48 hours. when I click to view these transactions, I was told "transaction not found" like your pictures show. Should I wait a week as you do? Is my bitcoin safe?

**Comment by M1bhai** [comment]
Yes. The way I got mine back Sir. In steps 
1. Get fully undressed 
2. Drive to a big field. 
3. Run around the field naked while screaming 
“BITCOIN COME BACK TO ME PLEASE” 
4. Repeat step 3 ; 22 times. 
5. Do 556 jumping jacks 
6. All finished 

After I did the above steps, then repeated on a daily basis, my Bitcoins came back to me very safe and unharmed. You have to put your full heart and soul into

**Comment by anoxindv** [comment]
https://pool.viabtc.com/tools/txaccelerator/

Five minutes before the end of each hour, start entering data until
there is a positive result and the system does not confirm the
acceleration of the transaction. I really helped!


2017-12-09 12:34 GMT+02:00 M1bhai <notifications@github.com>:

**Comment by kkining** [comment]
Thanks for your reply. Yes brother, my transactions have confirmed after I did the steps that you told me.  It's very efficient methods ：）
If anyone who gets the same problem and finds this page, don't worry, anything is OK, just do the six steps and wait.
