### ISSUE TITLE
GPG Verify WARNING ! !

### ISSUE THREAD

**Issue by torfhub** [bitpay/copay#6111]
gpg: Good signature from "Copay (visit copay.io) <copay@bitpay.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 9D17 E656 BB3B 6163 AE9D  7172 5CD6 00A6 1112 CFA1

**Comment by mnfirdaus** [comment]
ok

**Comment by mnfirdaus** [comment]
Primary key fingerprint??

**Comment by dabura667** [comment]
The signature is valid for that fingerprint.

If you trust that the fingerprint shown is actually the fingerprint of Copay's PGP key then you're fine.
