### ISSUE TITLE
Amazon Gift Card Purchase confirmed, but status is failure

### ISSUE THREAD

**Issue by williamrowell** [bitpay/copay#6112]
I purchased a $60 amazon gift card.  The transaction is confirmed, the invoice shows "This invoice has been paid', but the card is marked "FAILURE", with "There was a failure to the create gift card.  Please, contact BitPay Support."  No other error or troubleshooting information is obviously available.

Which platform are you using? iPhone 6s, iOS 10.3.2
Which version of Copay are you using? v3.2.1, #044de85
 
Please check Copay logs (General Settings -> About Copay -> Session Logs). Look for any errors reported there (errors are shown in red)
![img_0355](https://cloud.githubusercontent.com/assets/627365/26465486/401d4c8c-4140-11e7-988b-c9eaa699e86c.PNG)
![img_0354](https://cloud.githubusercontent.com/assets/627365/26465488/402dadac-4140-11e7-96c0-a3837ff4ae45.PNG)
![img_0353](https://cloud.githubusercontent.com/assets/627365/26465487/401f5c34-4140-11e7-881d-f28fb77df05a.PNG)

**Comment by gabrielbazan7** [comment]
Sorry, please email help@bitpay.com with the following details so we can assist you further.

Current device & operating system
Current version of the wallet used
Screen shot
BitPay Wallet ID - To get your Wallet ID, open your BitPay application, then go to Settings > Wallets & Integrations > More Options > Wallet Information.
It would also be helpful for you to provide the bitcoin transaction details related to the specific Amazon gift card purchase.

**Comment by williamrowell** [comment]
Thank you.  I submitted a help request to help@bitpay.com.
