### ISSUE TITLE
Received but not showing

### ISSUE THREAD

**Issue by rayray1983** [bitpay/copay#6114]
I have the confirmation email saying I received .006 but I don't see it in the wallet. I did see it as pending yesterday. New to this and wanted to try it out.

**Comment by my100bucks** [comment]
I have the same issue. I can see my pending transaction. It showed for a day or two now it's gone. But I can see the transaction on blockchain

**Comment by gabrielbazan7** [comment]
The sender probably set a low fee on that transaction, that's why the transaction was dropped by the network. Talk to the sender and ask them to re send the transaction. You could have an idea of a proper fee here https://bitcoinfees.21.co/ .

**Comment by my100bucks** [comment]
Did you receive your funds?

**Comment by rayray1983** [comment]
Yes I did. Just as you posted this.
