### ISSUE TITLE
My last two transactions not showing on copay

### ISSUE THREAD

**Issue by my100bucks** [bitpay/copay#6115]
My last two receiving transactions are not showing in copay. They both showed for a day or two as receiving and now both are gone! However I can see my last one as unconfirmed on blockchain. Insight would show the transaction number once in a while while it was always available on blockchain please help. 

Transaction number for the most recent one 
e44e1c9a4ed0b6e80484cab3404d2c797f378252421ac30d889d75f8f7b61e1f

**Comment by my100bucks** [comment]
Update: I already tried SCAN ADDRESSES FOR FOUNDS from setting and no changes. It can see my address but no balances on it.

**Comment by gabrielbazan7** [comment]
The transaction is not more on blockchain explorers. Tell the sender to re send the funds. You could have an idea of a proper fee on this site https://bitcoinfees.21.co/. Always check the fee when you are receiving money, and always wait for a confirmation.

**Comment by my100bucks** [comment]
Yes. I can still see that transaction on blockchain as unconfirmed but insight and copay app wouldn't show  and it would come back and disappear again. Insight has been failing in the past to show my transactions. Even confirmed ones or the ones that I already send and they have the confirmation. And later the transaction Gould show again. 
How come I can see the transaction in blockchain. Info but not insight?

**Comment by gabrielbazan7** [comment]
Check it here http://blockr.io/

**Comment by my100bucks** [comment]
please see bellow , one of them is only few hours old and yet never showed !
![blockchain](https://cloud.githubusercontent.com/assets/28977289/26524149/eeaf1a88-42de-11e7-85ec-0ced5b3de4b1.JPG)
![insight](https://cloud.githubusercontent.com/assets/28977289/26524151/f482fc18-42de-11e7-9f10-b7e6997def98.JPG)

**Comment by my100bucks** [comment]
even though they are unconfirmed but I should be able to see it? right?

**Comment by my100bucks** [comment]
Gabriel I just imported my address as a watch only to another app and it shows all my funds?! how come my copay shows that address as unused ! 
would you please open this issue again?

**Comment by my100bucks** [comment]
Finally I find a way around this whole situation . I got my bitcoins and sent them as I said both transactions exist but still insight and copay wouldn't show it ! I had to spend 8 hours to fix this but finally worked, thank you and your team and I hope the best for you but please work on this issue to fix it for good . half an hour after spending my money via a secondary app and other side got the confirmation of receiving all funds. copay still doesn't know what happened. my app doesn't show the transaction I also installed the app on my other phone to make sure this is not a local issue and still nothing. 

Thank you

**Comment by gabrielbazan7** [comment]
I'm opening this issue to check it with the wallet team

**Comment by gabrielbazan7** [comment]
This one was already solved.

**Comment by jtalweezy** [comment]
I am having a similar issue, however i sent funds and they are not in the receiving wallet. It shows up on copay as "sending" and subtracted the amount from my wallet. How can I make sure the wallet I sent funds to got them if I can find the transaction on insight or any other webpage?
