### ISSUE TITLE
BTC wallet recovery.

### ISSUE THREAD

**Issue by Cassiebas** [bitpay/copay#6118]
Please may someone help me. 

I had to reinstall my W10 OS since it had a lot of problems. Now the only thing I did was I wrote down the recovery phrase (12 words). Now as I installed Copay again and tried to import my wallet. It keeps saying the recovery phrase is invalid. I'm at a real loss right now. I'm fairly new to BTC and Copay. 

[removed]

I checked it multiple times for mistakes. I have e-mail transaction history and my BTC wallet addres for additional information.

In the hopes I can get it back.

**Comment by gabrielbazan7** [comment]
Check if all your words are here : https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt

**Comment by Cassiebas** [comment]
Thank you!. 

I have my wallet back. But the money that was on it is gone. 
https://gyazo.com/ca83c56b864e4cbbff109c8364fda281 | https://gyazo.com/53438f3b01370be86c639921834377d3

It says it has been send?! 
What is this about? Have I just been hacked or D:

**Comment by bitjson** [comment]
@Cassiebas what app are you using, and which version?

**Comment by gabrielbazan7** [comment]
I could happen. You copy the words here, everyone could have access to your funds =/

**Comment by bitjson** [comment]
@Cassiebas what was the process you followed to create your wallet?

**Comment by Cassiebas** [comment]
Nooo wayyyy

**Comment by Cassiebas** [comment]
I did mention my code

**Comment by Cassiebas** [comment]
I created my wallet using the the Copay wizard build in your app.
I am using the latest version downloaded from your Github.

**Comment by bitjson** [comment]
@Cassiebas 

There are currently 133 people "watching" this repo on GitHub, and most of us received your backup phrase in an email. Any of these people can now spend any money you send to the wallet. **Do not send funds to that wallet.**

You should assume that the wallet is compromised, and create a new one instead. 

Before you do anything else, take some time to learn more about Bitcoin: https://bitcoin.org/en/you-need-to-know

**Comment by Cassiebas** [comment]
I'm literally ashamed and in agony...
https://insight.bitpay.com/address/1GQDfLjQHfwBc7D93GND9WAM7BmCha3sad This guy got them.

I assume there is no way to contact him or get it back?.

**Comment by bitjson** [comment]
It's not possible to reverse a bitcoin transaction. The recipient must send the funds back to you.

Please note, BitPay (the company I work for) does not control your funds, and does not provide recovery services.

You got very lucky though – my transaction confirmed before anyone else was able to take it. Send me an email (github@bitjson.com), and I'll give it back to you.

**Comment by my100bucks** [comment]
Good job Jason -bitjson
@cassiebass - be careful in the future once it's gone you can't reverse it. He is a nice person to save your funds ✌️✌️

**Comment by Cassiebas** [comment]
Sended you an e-mail bitjson! (:
I'm really happy right now yes haha. Thank you!

**Comment by JDonadio** [comment]
Well done @bitjson ;)

**Comment by bitjson** [comment]
Glad it worked out. Waiting for [468256](https://insight.bitpay.com/block/000000000000000000ff3257259475a795b3b8eae1f8957db846f5077df3f6c7) to finally be mined (40 minutes later) was a bit nerve-racking. 😆

Returned:
[ef6413244974f6be1cf96df1ca8794f09e6af409d7134196a00b789083e011c3](https://insight.bitpay.com/tx/ef6413244974f6be1cf96df1ca8794f09e6af409d7134196a00b789083e011c3)

**Comment by JDonadio** [comment]
👏 👏
