### ISSUE TITLE
Where can I check my Private Keys?

### ISSUE THREAD

**Issue by diegotco** [bitpay/copay#6121]
![2017-05-26_1645](https://cloud.githubusercontent.com/assets/22822405/26513748/d1627aee-4232-11e7-9350-d869d836924d.png)

**Comment by JDonadio** [comment]
Please take a look [here](https://github.com/bitpay/copay/issues/5859#issuecomment-294537858)

**Comment by diegotco** [comment]
Awesome. Thank you @JDonadio  :)
