### ISSUE TITLE
Selling password

### ISSUE THREAD

**Issue by BreakHeadz** [bitpay/copay#6122]
When I trying to send funds this ask me password from wallet but I not setted it before, how to fix this problem?

**Comment by JDonadio** [comment]
You can use your backup (phrase, file, text). Please, be sure to get a correct backup of your wallet first, then delete it and import it again.

**Comment by BreakHeadz** [comment]
in app this ask me touchID and then pop up the window with some password from wallet, I do not remember that I setted it before, I tried the 12 phrases it shows me each time "not correct"

**Comment by gabrielbazan7** [comment]
What @JDonadio means is that if you don't remember your password, delete the wallet, and import you wallet again.

**Comment by BreakHeadz** [comment]
if I delete my wallet the funds in bitcoin will save or dissappear?

**Comment by BreakHeadz** [comment]
on each step this ask me each time "Enter your payment password" where can I set this password or change it?

**Comment by gabrielbazan7** [comment]
What do you mean by each step ?

**Comment by gabrielbazan7** [comment]
Your founds are in the 12 words. You have all of them ?

**Comment by gabrielbazan7** [comment]
You set the spending password on settings -> choose your wallet -> spending password

**Comment by BreakHeadz** [comment]
yes I have all of them, this is the "payment password" ? how should I type it. with space button or just all in couple? 
spending password in settings you mean in app for iphone I can found? or where?

**Comment by gabrielbazan7** [comment]
in the app. Could you send me an screenshot ?

**Comment by BreakHeadz** [comment]
in setting of my wallet there for set the password I should choose "Export wallet" ?

**Comment by gabrielbazan7** [comment]
<img width="398" alt="bitpay_-_secure_bitcoin_wallet" src="https://cloud.githubusercontent.com/assets/10999037/26515024/cf05fed2-424c-11e7-896e-8676252ba24b.png">

**Comment by BreakHeadz** [comment]
yes I pushed this button, and nothing happen

**Comment by gabrielbazan7** [comment]
Nothing at all ?

**Comment by BreakHeadz** [comment]
when I go and back there again this pushed button setting again to default "off"

**Comment by gabrielbazan7** [comment]
That's weird. Which version and device are you using ?

**Comment by BreakHeadz** [comment]
iphone 6s. the last version from appstore

**Comment by JDonadio** [comment]
You should have your backup, that's the first step before using the wallet either for receive as send funds. If you never made a backup, you will not be able (in this case) to access to your 12 words or export options. Maybe you set a spending password and not remember it?

**Comment by BreakHeadz** [comment]
I have all this words typed in paper just from there, ok what if I not remember how to recover spending password then? just its weird when I made backup it just showed me 12 words and I saved it on paper list. nothing did anymore after that.

**Comment by gabrielbazan7** [comment]
Ok. Delete the wallet, and go to tab home -> wallets ( + ) -> import -> type the recovery phrase and import. Tell us if you continue having problems

**Comment by BreakHeadz** [comment]
and what will be after I delete the wallet?

**Comment by JDonadio** [comment]
@BreakHeadz there is 2 step to clear your spending password:

1) Obiously put your password again to disable the encryption
2) Delete your wallet and import it again. In this case you must have your backup, if you have not you couldn't access to your funds.

Before delete your wallet, you can also use another platform (chrome, desktop, etc) and try the import

**Comment by BreakHeadz** [comment]
how can I use the mac os? where can I download the copay on PC? or maybe sign in on site?

**Comment by BreakHeadz** [comment]
I pushed "import" and this shows to me "Error the walled is already in copay"

**Comment by JDonadio** [comment]
https://copay.io/
www.bitpay.com/wallet

**Comment by gabrielbazan7** [comment]
That means that the words are correct haha . Go to tab settings -> choose your wallet -> more options -> delete Wallet, and delete de wallet.

**Comment by BreakHeadz** [comment]
and funds will be saved after that if I not imported the wallet nowhere before?

**Comment by gabrielbazan7** [comment]
Yes sure

**Comment by BreakHeadz** [comment]
and what is the next steps after that?

**Comment by gabrielbazan7** [comment]
nothing, the spending password will be turn off by default

**Comment by BreakHeadz** [comment]
ok I deleted it, how can I return the funds?

**Comment by gabrielbazan7** [comment]
import the wallet

**Comment by BreakHeadz** [comment]
ok did

**Comment by BreakHeadz** [comment]
huh wow... it was emotionally. thanks )
