### ISSUE TITLE
 Unverified transaction

### ISSUE THREAD

**Issue by anoxindv** [bitpay/copay#6123]
Good afternoon! He sent the coins to the Copay purse from another purse. By mistake, I managed with a low commission. On a blockchain, the transaction is displayed as unconfirmed. Has passed more than a day! How much longer do I have to wait? Will my coins reach? Thank you

**Comment by BitLox** [comment]
What is the transaction ID? Do you know what fee was paid (Btc/kB)?
It may take up to a week for the transaction to either confirm or be dropped from the mempool (unconfirmed waiting transactions).

In any case, the funds are NOT lost.

**Comment by anoxindv** [comment]
Биткоин-адрес Адреса являются идентификаторами, которые вы используете для
отправки биткоинов другому лицу.
Сводные данные
Адрес 1KMzN4x8DwC7VmkWtua3QvwgDvp3YQw11V
<https://blockchain.info/ru/address/1KMzN4x8DwC7VmkWtua3QvwgDvp3YQw11V>
Hash 160 c96a77bfa20af19d5840ccd7744998f83df05fd5
<https://blockchain.info/ru/address/c96a77bfa20af19d5840ccd7744998f83df05fd5>
Инструменты Связанные теги
<https://blockchain.info/ru/related_tags?active=1KMzN4x8DwC7VmkWtua3QvwgDvp3YQw11V>
 - Неизрасходованные выходы
<https://blockchain.info/ru/unspent?active=1KMzN4x8DwC7VmkWtua3QvwgDvp3YQw11V&format=html>
Транзакции
Число транзакций 1
Всего получено 1.92815 BTC
Итоговый баланс 1.92815 BTC
Запросить платеж Кнопка "пожертвование"
Депонирование платежей Транзакции (Сначала старые)
<https://blockchain.info/ru/address/1KMzN4x8DwC7VmkWtua3QvwgDvp3YQw11V?sort=0>
Фильтр
6ca9f8479615177d20d093c8deac802f078e716a04163ee65a9df8914bca6deb
<https://blockchain.info/ru/tx/6ca9f8479615177d20d093c8deac802f078e716a04163ee65a9df8914bca6deb>
(Плата: 0.00005 BTC - 26.04 sat/B - Размер: 192 bytes) 2017-05-26 09:14:56
15HgsRfRHW28c4ZAw7qkAE4rDazfrmjQ3H
<https://blockchain.info/ru/address/15HgsRfRHW28c4ZAw7qkAE4rDazfrmjQ3H> (1.9282
BTC - Вывод <https://blockchain.info/ru/tx-index/253734994/4>)
1KMzN4x8DwC7VmkWtua3QvwgDvp3YQw11V - (неизрасходованный) 1.92815 BTC
Неподтвержденная транзакция!

2017-05-27 15:49 GMT+03:00 BitLox <notifications@github.com>:

**Comment by anoxindv** [comment]
https://blockchain.info/ru/address/1KMzN4x8DwC7VmkWtua3QvwgDvp3YQw11V?filter=4

**Comment by anoxindv** [comment]
https://blockchain.info/ru/address/1KMzN4x8DwC7VmkWtua3QvwgDvp3YQw11V?filter=4

2017-05-27 15:49 GMT+03:00 BitLox <notifications@github.com>:

**Comment by BitLox** [comment]
Your fee is approximately 10x too low (just letting you know the scale here)
A “normal” fee for confirmation within 20 blocks (pretty much the slowest) is 0.00265766 BTC / kB [ ‎bitlox.io/api/utils/estimatefee?nbBlocks=20  ] 
This transaction has ~0.00026041 BTC/ kB

This will take quite a while to clear (maybe a 5-7 days) or it may just drop out by the end of the time.

Try this, inputting your TXID 6ca9f8479615177d20d093c8deac802f078e716a04163ee65a9df8914bca6deb

https://www.viabtc.com/tools/txaccelerator/

I have had positive results with similar transactions.

**Comment by anoxindv** [comment]
And what is this site? What happens if I enter the ID?


2017-05-27 16:50 GMT+03:00 BitLox <notifications@github.com>:

> Your fee is approximately 10x too low (just letting you know the scale
> here)
> A “normal” fee for confirmation within 20 blocks (pretty much the slowest)
> is 0.00265766 BTC / kB [ ‎bitlox.io/api/utils/estimatefee?nbBlocks=20 ]
> This transaction has ~0.00026041 BTC/ kB
>
> This will take quite a while to clear (maybe a 5-7 days) or it may just
> drop out by the end of the time.
>
> Try this, inputting your TXID 6ca9f8479615177d20d093c8deac80
> 2f078e716a04163ee65a9df8914bca6deb
>
> https://www.viabtc.com/tools/txaccelerator/
>
> I have had positive results with similar transactions.
>

**Comment by BitLox** [comment]
It's one of the larger mining pools. They provide a free service where if you put your transaction ID in the form (doesn't always submit, you may have to keep trying) and they automatically include your transaction in their "blocks to be mined" irrespective of the fee.

It worked for me, and there's no risk. Might as well try.

**Comment by anoxindv** [comment]
Thank you, I will try! If not, then the money will still come back? They
will not be lost?

2017-05-27 17:02 GMT+03:00 BitLox <notifications@github.com>:

**Comment by BitLox** [comment]
The coins will either go to the original destination, or will come back to the originating wallet.

**Comment by anoxindv** [comment]
Thank you very much!

2017-05-27 17:07 GMT+03:00 BitLox <notifications@github.com>:

**Comment by anoxindv** [comment]
He writes to me: "Submissions are beyond limit. Please try later", and:
"Your remaining Customer-Only use: 0 Times". What could this mean?

2017-05-27 17:07 GMT+03:00 BitLox <notifications@github.com>:

**Comment by BitLox** [comment]
Means they are busy. Just keep trying. You do not have to register as a customer, and it does not seem to make any difference.

**Comment by anoxindv** [comment]
Understood, thanks!

Understood thanks!


2017-05-27 17:10 GMT+03:00 Даниил Владимирович <anoxindv28@gmail.com>:
