### ISSUE TITLE
Unverified transactions!

### ISSUE THREAD

**Issue by plustrade** [bitpay/copay#6124]
Hello, we have 2 unconfirmed transactions almost 2 days now with putting urgent fees! Why is that happening can we cancel them what can we do??? Please help us!

**Comment by gabrielbazan7** [comment]
Could you paste here the transaction id or the link to a blockchain explorer ?

**Comment by plustrade** [comment]
Hello, I don't have any transaction id where I can find it?
On view on blockchain says not exist!

On 27 May 2017, at 20:36, Gabriel Edgardo Bazán <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you paste here the transaction id or the link to a blockchain explorer ?

**Comment by my100bucks** [comment]
Go to blockchain.info and search with your account numbers that you used to do the transaction and you will find it there

**Comment by my100bucks** [comment]
Insight has been doing terrible job in last two weeks !

**Comment by my100bucks** [comment]
did you receive your funds yet?

**Comment by plustrade** [comment]
They came back one by one!

**Comment by JDonadio** [comment]
Reopen if the problem remains.
