### ISSUE TITLE
Unconfirmed and disappearing Transactions

### ISSUE THREAD

**Issue by nobugz1222** [bitpay/copay#6125]
Recently created a wallet for one simple transaction to receive bitcoins. The transaction went unconfirmed for days with the proper fee rate. A few days later this transaction is no longer there and I can't even check the block chain anymore. Please give me some support

**Comment by gabrielbazan7** [comment]
Your transaction was dropped due to low fee. You need talk with the sender to re send the transaction with a higher fee.

**Comment by nobugz1222** [comment]
Is there any proof of this? How do I see this transaction was sent back?

**Comment by gabrielbazan7** [comment]
If you don't see the transaction on the explorer I can confirm that the transaction was dropped or never exist.

**Comment by my100bucks** [comment]
Look at blockchain.ifo for your account number if there is 0 transaction there. The transaction has been dropped and funds should be back in senders account if you see a transaction then copy and paste the link here

**Comment by nobugz1222** [comment]
https://blockchain.info/address/1Ct1eTDjkwJxKaExixYEeYUkyPgKUHCtmM

That's the link

**Comment by my100bucks** [comment]
I'm having the same problem but working on it , I'll let you know if i find any solutions.  hopefully they can resolve this issue soon :)

**Comment by my100bucks** [comment]
Just let you know I was able to accelerate your process your should have your funds soon :) 
but I'm still stuck with my own issue lol 
let me know if it shows in COPAY?

**Comment by nobugz1222** [comment]
Appreciate the help.. it was confirmed!

**Comment by my100bucks** [comment]
NP , Have a great day . 

"""
gabrielbazan7
Your transaction was dropped due to low fee. You need talk with the sender to re send the transaction with a higher fee.
"""
guys this is another proof that the transaction existed but insight and copay couldn't see it , please resolve this issue,
