### ISSUE TITLE
Big problems with Ethereum wallet

### ISSUE THREAD

**Issue by BreakHeadz** [bitpay/copay#6126]
Hello
I want to ask something.
I just download the Ethereum Wallet, it was installed on my iMac, ok it was too long because it saved all database.
but then, right now what I see: I can come and add the Basic wallet, already 48hours this still download something, there are 3million blocks, from all this time this only downloaded 1,600,000 blocks from 3,781,000 blocks.. but I can push "Launch application" ok.
and I can come on my wallet already.
so. I created the Basic wallet
I sent ETH from poloneix on Basic wallet adress, but can't see it, this show me "for display ETH's you must add the Contract wallet"
and, I added the new wallets "for contract", this show me "Creating..." but already second day they can't done!
what is that?!
status "Creating..." still yet for hours and hours and blocks download toooo slow...
so what about this application, and what about the ETh's which I sent, it show me I have zero 0 ETH, it is there? and what to do if any wallet which I push(I already added 3 contact wallets) is still "creating..." goshhh[](url)

**Comment by BreakHeadz** [comment]
![2017-05-28 20 54 45](https://cloud.githubusercontent.com/assets/28990443/26530933/f054d68e-43e7-11e7-813f-43e259616a45.png)

**Comment by gabrielbazan7** [comment]
Sorry, I don't know. You should ask on etherium repo https://github.com/ethereum.

**Comment by BreakHeadz** [comment]
can you tell me in which direction there I must go for ask my question? I not so understand in this site. please.

**Comment by gabrielbazan7** [comment]
Maybe here https://github.com/ethereum/ethereum-org/issues

**Comment by BreakHeadz** [comment]
thank you

**Comment by mnfirdaus** [comment]
:+1:
