### ISSUE TITLE
Cancel transaction

### ISSUE THREAD

**Issue by wilambert** [bitpay/copay#6127]
Hi,

I explain my problem, I made a transfer from my Copay wallet to a adv wallet.
The thing is I wanted to do one transfer of 100 euros because my adv account take only one transaction per Adresse of BTC, but there was a bug, and i've done the transfer 8 time, the same amount...

When I check my adv wallet, I h only 100 euros, I don't know where are the 700 remaining 

Help me

**Comment by JDonadio** [comment]
Sorry for the delayed reply. If you made 8 transaction, please provide us the 8 transaction ids so we can investigate it further. Thanks
