### ISSUE TITLE
My Personal Wallet Funds Dissapeared

### ISSUE THREAD

**Issue by KettleFeesh** [bitpay/copay#6128]
I had some funds in my personal wallet, and was waiting on a transfer to bittrex to be complete, everything was fine when i went into settings to see what there was, i didn't change anything but when i exited settings my balance was 0.00 and the transfer notification for bittrex was gone and never said anything, i still had $11 left in my wallet that would not have been transferred but just vanished, please help. Bittrex also still says the transfer never was completed.

**Comment by gabrielbazan7** [comment]
Sorry for the delay. You still having this issue ?
