### ISSUE TITLE
transfer fee

### ISSUE THREAD

**Issue by eksef** [bitpay/copay#6129]
there is a ridiculous transfer fee on my copay wallet, I only have a balance that is worth 1 €, the super economy fee is 5 €

http://i.imgur.com/grYuhQU.jpg

I just made a wallet at blockchain.info and their default fees are just over 1 €

I don't care if the transaction doesn't get included within a few hours, I could wait a few days just to have it transfer. 

Its ridiculous to have that kind of a fee on this.

I know 1 € is noting, its been there for over a year, left over cash. 

hopefully these fees go down, I don't see any reason to use bitcoin / copay wallet if the fees go up to 10€

**Comment by gabrielbazan7** [comment]
The parameter used for the fee calculation is the TX size, not the output amount. What you see there is the BTC/kb. Try creating a transaction and you will see the fee for your transaction. However that value depends on the bitcoin network, I would not recommend you to send a transaction will less than the "supereconomy" of Copay. Remember that fees calculated by Copay for sending are given to the Bitcoin miners, not Bitpay or anyone related to the Copay project. You could have an idea of a proper fee on this site https://bitcoinfees.21.co/. Also, in the next release we are changing BTC/kb for satoshis/byte in the app.

**Comment by eksef** [comment]
Yes I know how it works, blockchain.info gives the option to put your own fee on the transfer.

**Comment by gabrielbazan7** [comment]
We do not allow that option to avoid users with transaction that will never get confirmed.

**Comment by eksef** [comment]
the copay wallet only shows me the fee above, it doesn't change, it just reports that there isn't enough funds. The blockchain wallets default fee is already 5 times less than what your app gives me.

**Comment by eksef** [comment]
I don't see any reason to transfer btc into my copay wallet anymore, I will only transfer them between exchanges and maybe blockchains,info wallet if I plan to store them.

**Comment by gabrielbazan7** [comment]
Try using the send max option. You could find it on the calculator view. That way you could have an idea of the usable balance you have on your wallet. The reason to use Copay wallet is the security that your transaction will not get stuck.

**Comment by dabura667** [comment]
@eksef

> I only have a balance that is worth 1 €

... ok...

> I will only transfer them between exchanges and maybe blockchains,info wallet if I plan to store them.

... good luck with that...

lol

**Comment by eksef** [comment]
@dabura667 

right, I transfer zec into poloniex, conver it to bitcoin and then transfer that into a wallet or bitstamp. Now if I transfer 100 € to copay and then later want to sell it on bitstamp it takes 5€ fucking ridiculous. 

its -0.00010000 btc to transfer out of polo. I can just directly move it to bitstamp and sell it there.

so what is so funny about it for you?

it works.

**Comment by eksef** [comment]
@dabura667 

So do you understand my point, why would I ever transfer a balance into my copay wallet, I will just keep it on polo, I can send it to other people from there with a really small fee, or an exchange and have it cashed out into my bank account, why would I bother with copay at all ?
