### ISSUE TITLE
Unauthorized  transfer from copay 

### ISSUE THREAD

**Issue by Brathi1952** [bitpay/copay#6131]
Dear sir
Please note that on 17 may 2017, some unknown  person transferred 0.68 Bitcoin from my Co pay account to 1F6zjh5CzC5672FyFh1tXd8wJVj3wrHmYR

It was not authorized or transferred  by me. I was shocked to see this transaction and lost my faith on security of copay. Please help me to get back my bit coin and also trace who has transferred  this amount illegally. 
Your quick action shall be highly appreciated. I shall be thankful if you can get my money back. 
Regards 
Binod Kumar Rathi 
+919810070299

**Comment by gabrielbazan7** [comment]
Sorry, but there is nothing we can do for you. BitPay do not have access to your funds, and also a bitcoin transaction which has already been broadcast to the network cannot be reversed.

**Comment by Brathi1952** [comment]
Dear sir,
Please reply the following :

1.we were sure that Co pay wallet is safe as it has long password which
cannot be remembered  easily, but some one stole our Bitcoin,  will you
please explain how it could happen? No other person except me knew  about
Co pay.

2.What are the precautions  and safety measures we must take to save our
money.
3.How to save from hacking?
4.Should our mobile  also have Antivirus software installed,?
5.how  I can change my present password or details for safety?
6.why entire amount was not stolen?
Please reply in detail so as to make our account safe in future.  You
should have sent e mail to new account holders what precautions are to be
taken.
Before making any payment , otp  must be sent to our mobile ,  it saves
unauthorized  transactions.
Awaiting your reply in detail.
Regards
Binod Kumar Rathi.

**Comment by JDonadio** [comment]
@Brathi1952 just to clarify, Copay have security capabilities to keep your wallet safe like:

* PIN/Fingerprint to lock/unlock the app
* Spending password to encrypt your private key
* Fingerprint request
* Multisig wallets
* Read only wallets

If someone have access to your security data then your wallets are compromised. Unfortunately there is no way to proof if your transactions was made by you or any other person with access to your device.
