### ISSUE TITLE
Multi crypto currencies

### ISSUE THREAD

**Issue by kemoantemo** [bitpay/copay#6132]
I really love the copay wallet and i hope to see all crypto currencies on it or at least the most popular like doge ltc dash eth etc.... 
And all that in the same wallet so i can know all my currencies status hope you work on that please

**Comment by XWingNut** [comment]
Lite Coin would be nice to if you can please

**Comment by avibrazil** [comment]
Coinomi is HD wallet that supports all those coins and more. Android only for now.

**Comment by matiu** [comment]
done.
