### ISSUE TITLE
Addressbook scan button doesn't work

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#6142]
To reproduce it open the scanner from Addressbook and try to scan an address QR code from receive tab.

![screenshot_20170530-111847](https://cloud.githubusercontent.com/assets/13851807/26588095/ac49a840-452a-11e7-938a-84fb63c834aa.png)

**Comment by gabrielbazan7** [comment]
I can't reproduce it

**Comment by gabrielbazan7** [comment]
I reproduce it. It happens after scanning on the import view.
