### ISSUE TITLE
How to create multisig wallet

### ISSUE THREAD

**Issue by fluidirie** [bitpay/copay#6148]
Hi

Can you let me know how to create a multisig wallet? There doesn't seem to be any option to do this. I just want to set the option to confirm via my desktop and phone for personal use.

Thanks,

Aziz

**Comment by gabrielbazan7** [comment]
Click on Wallets `+` symbol -> Create shared wallet

**Comment by gabrielbazan7** [comment]
If you want, you can export a read only version on your phone. 

<img width="400" alt="bitpay_-_secure_bitcoin_wallet_and_how_to_create_multisig_wallet_ _issue__6148_ _bitpay_copay" src="https://cloud.githubusercontent.com/assets/10999037/26638207/f001e87c-45f7-11e7-9aa7-f52838db9806.png">

And set an spending password on your desktop version.

**Comment by fluidirie** [comment]
OK so if I am creating a 2 of 3 wallet, do I download the Copay app to my phone and then scan the wallet ID?
Will that mean for future payments I need to logon via desktop and also my phone to ocnfirm transaction?

What happens if I loose my phone? Can I use the backup to create the signatory on another phone?

Thanks!

**Comment by JDonadio** [comment]
When you create a multisig wallet a QR code will be shown in your screen, you must scan it from another device or simply share it.
2-3 wallet mean that you need 2 of the 3 available signers (copayers) to broadcast a transaction.
If you lose your phone for any reason you can restore your wallet from your backup phrase (12 words) or from your backup file/text and QR from export options.

Note in case of lost, damage etc, without a backup your funds will be inaccesibles. Be sure to get a complete backup of all devices.

**Comment by gabrielbazan7** [comment]
You will need to store the 12 words from all the devices (3 of them), if you lost your phone you could recover that wallet from the 12 words from that wallet, and if your computer broke you need the 12 words for that wallet. 

You are right that having a multisig wallet improves the security. But, in my opinion, having a shared wallet is for share funds with someone else. If everything you care about is security and you will be the only owner of all the wallets, I recommend you to create a single wallet and set an spending password or use the PIN/touch-id. That way you will have to store only 12 words.
