### ISSUE TITLE
Card UI

### ISSUE THREAD

**Issue by gabrielbazan7** [bitpay/copay#6151]
Still missing "View Confirmation Status" label. The transaction id is not coming on the invoice request.
<img width="599" alt="improvements_on_the_card_ui_by_gabrielbazan7_ _pull_request__6104_ _bitpay_copay" src="https://cloud.githubusercontent.com/assets/10999037/26648283/586f72ba-4618-11e7-813d-68fb4fb7e3f1.png">

<img width="376" alt="improvements_on_the_card_ui_by_gabrielbazan7_ _pull_request__6104_ _bitpay_copay" src="https://cloud.githubusercontent.com/assets/10999037/26648301/69fb928e-4618-11e7-932b-fe8ab3f913ae.png">

**Comment by JDonadio** [comment]
Is this already fixed?

**Comment by gabrielbazan7** [comment]
no
