### ISSUE TITLE
Ledger HW Issue

### ISSUE THREAD

**Issue by blueknight02** [bitpay/copay#6156]
Hello, I am trying to set up a second multisig account in Copay using the same Ledger hardware wallet I use for my original account. When I do this i get "Error creating wallet: COPAYER_REGISTERED: Copayer ID already registered on server"

To clarify, I want to use the same hardware wallet for 2 seperate multisig accounts

**Comment by JDonadio** [comment]
Let me check it and I'll keep you posted. Thanks for report it

**Comment by blueknight02** [comment]
Thanks for the response. Let me know what can be done.

**Comment by JDonadio** [comment]
@blueknight02 sorry for the delayed reply. I'm able to get many multisig wallets using the same ledger device. Maybe you are not changing the account number?

Wallet 1:

- In Copay go to Create shared wallet > Advance opts 
    - Wallet key (Ledger)
    - Account number **_1_**
    - Create
    - Share the invitation

Wallet 2:

- In Copay go to Create shared wallet > Advance opts 
    - Wallet key (Ledger)
    - Account number **_2_**
    - Create
    - Share the invitation

In your ledger interface will see something like

<img width="373" alt="ledger_wallet_bitcoin" src="https://user-images.githubusercontent.com/13851807/27436483-d01fcffc-5735-11e7-86c4-c5d723ec9744.png">
