### ISSUE TITLE
multisig wallet with funds locked

### ISSUE THREAD

**Issue by chivoX** [bitpay/copay#6160]
Hey i have a 2-2 shared wallet, i have it on my mac but the other signee seems like he sold the phone where he had the app installed. and today by mistake i tranferred funds into that wallet because i tought it was a new wallet i created today to do some transactions.

is there a way to recover the funds locked inside the wallet ?

**Comment by JDonadio** [comment]
Do you see the transaction proposal in your home/details view?. Use the backup of the lost phone and import that wallet in another platform. Or try with the recovery tool to transfer the funds into a fresh one. https://bitpay.github.io/copay-recovery/

**Comment by chivoX** [comment]
thanks for the answer, the tool requires 2 backups :S .

i dont think he has the phone anymore, did i just lost the money inside that wallet ?

**Comment by chivoX** [comment]
i did create the transfer proposal today since i tought i was just sending it over to another wallet but then later i found out that it was a 2-2 signature wallet :(.

**Comment by JDonadio** [comment]
Unfortunately he only way to recover your funds is with both backups. 
I thought the another phone had the app installed and the new owner can access to the app, in that case you can delete the proposal created by youself.

**Comment by chivoX** [comment]
if i can prove the money in that wallet belongs to me do you think there is a way to get that money back ? i have control of the wallet that put the money into that locked wallet.

**Comment by chivoX** [comment]
the other end seems to still have the phone he actually sold it to his brother. if we recover the data on the phone even if it was reseted to default.

if for example we recover the data with a forensics service would it be posible to take that money out?

**Comment by JDonadio** [comment]
If you are the owner or not doesn't matter because to get access to that funds you need both backups. If you have only one the another private key is stored in the phone but if the app was wiped out there is no way to get the money back.

**Comment by chivoX** [comment]
if we get the other private key? is there a chance to get it back ?

**Comment by JDonadio** [comment]
Sure
