### ISSUE TITLE
Confirming found 

### ISSUE THREAD

**Issue by j0va24** [bitpay/copay#6163]
![image](https://cloud.githubusercontent.com/assets/28759552/26706526/89130934-4714-11e7-8153-cdb23af763c1.png)

Hi, guys, it's been a week since this was shown in my wallet. Unconfirmed funds, what can be done? Since I can use my btc ..

**Comment by gabrielbazan7** [comment]
Wait to your transaction to get confirmed or go to settings "Advanced" -> click on "Use unconfirmed Funds"
