### ISSUE TITLE
Spending Passowrd Issue

### ISSUE THREAD

**Issue by wildjive** [bitpay/copay#6168]
I Haven't set a password but asked to put a password in when I try to send Bitcoin. I checked the setting and "request spending password" is off.

Do I have to restore from backup?
What if asked a password again after restore?

**Comment by Mirobit** [comment]
I have a similar problem. I had set a spending password before updating to the new Bitpay version. After the update the settings page said that I didn't have set a spending password. But the password was still required when I tried to spend funds/export. So I guess in my case it is just an UI issue.

**Comment by JDonadio** [comment]
Thanks for the report. We couldn't reproduce the issue, what version are you guys running and what platform? In the meantime try to restore your wallet from backup that should clean your spending password settings.

**Comment by wildjive** [comment]
Copay v3.3.0 on iOS 10.3..2(latest)

no such a problem reported?

**Comment by gabrielbazan7** [comment]
Hi! I just send a PR fixing the issue. Thanks for the reports https://github.com/bitpay/copay/pull/6175.
