### ISSUE TITLE
Copay and AngularJS

### ISSUE THREAD

**Issue by alexandrag2254** [bitpay/copay#6169]
Currently the codebase depends on a node module bitcore-wallet-client, but from my understanding there also must be a dependency/module client side as well in order for the Angular logic to work. Is there an Angular module that corresponds with the bitcore-wallet-client library being used and if so what is it? I've seen reference to a bwcModule but I'm uncertain where this is or where it came from. 
Thanks in advance!

**Comment by dabura667** [comment]
https://github.com/bitpay/angular-bitcore-wallet-client

I believe this is it, but it says they merged the angular client into BWC itself.

**Comment by JDonadio** [comment]
Yes, that's right. If you need something else let me know.
