### ISSUE TITLE
Wallet recovery phrase is not available

### ISSUE THREAD

**Issue by rvijgen** [bitpay/copay#6171]
When I try to make a backup of my wallet I get a message that says: "Wallet recovery phrase is not available. You can still export it from Advanced -> Export"

Which is what I did and it generated a machine readable code which I understand to be the equivalent of the human readable recovery phrase (is this correct). However, I would still like to keep a recovery phrase written down somewhere. How should I proceed?

**Comment by JDonadio** [comment]
@rvijgen the ability to delete your recovery phrase is not longer available in Copay, so I assume you are running an old version? Anyways you can create a fresh one and use the recovery tool to move all your funds into the new one.

https://bitpay.github.io/copay-recovery/

**Comment by rvijgen** [comment]
Hi JDonadio, i'm using 3.3.0 on iOS and i am trying to create a recovery phrase, not to delete one.
I go to settings -> My Wallet ->backup -> and then I get the message  "Wallet recovery phrase is not available. You can still export it from Advanced -> Export"

**Comment by gabrielbazan7** [comment]
@JDonadio means, that your wallet is old. Create a new one and move all the funds to that new wallet.

**Comment by JDonadio** [comment]
Do you remember when the wallet was created? If your wallet have a couple of years it's probably that it was created when the mnemonics (12 words) wasn't supported by Copay. If it's your case you cannot create a recovery phrase manually but you can move your funds into a new one using send max option or the [recovery tool](https://bitpay.github.io/copay-recovery/).

![bitpay - secure bitcoin wallet](https://cloud.githubusercontent.com/assets/13851807/26789571/1839d0a0-49e7-11e7-9bcc-0a7e68d9ba6a.jpg)

**Comment by rvijgen** [comment]
Ok, thanks! This works. Once all the funds are in the new wallet, and the old wallet has no more funds in it I can delete the old wallet right?

**Comment by JDonadio** [comment]
Yep :)
