### ISSUE TITLE
Funds potentially lost in multi-signature wallet after months of successful transactions

### ISSUE THREAD

**Issue by Chris869218** [bitpay/copay#6172]
Multisignature wallet comprised of both hardware and non-hardware wallets stopped working. 

I have attempted to import the recovery phrase from the hardware wallets along with the derivation path m/48'/0/(account#-1)' into 'import wallet' and I receive the following error:

"Could not access the wallet at the server. Please check: 
The password of the recover phrase (if set)
The derivation path
The wallet service URL
Note: To import a wallet from a 3rd party software, please go to add wallet > Create wallet, and specify the Recovery Phrase there"
https://imgur.com/a/sJQDX

I can't import the wallet as a hardware wallet, as I then get the error described here when I try to sign a transaction:
https://github.com/bitpay/copay/issues/6106

I can't re-create the wallet with the same seeds and cosigners, because I get the following error: 
Error creating wallet: 
COPAYER_REGISTERED. copayer ID 
already registered on server. 

What are the other options? Losing access to funds in a multisignature account that had been working fine seems like a very problematic issue. 

I feel like others should be warned this could happen at any moment if there is no known cause for this.

**Comment by dabura667** [comment]
afaik you can not import a copayer created by a hardware wallet without the hardware wallet. Importing the phrase of the hardware wallet to take place of the hardware wallet copayer is not possible iirc.

Someone correct me if I'm wrong.

**Comment by Chris869218** [comment]
The last section of this link seems to indicate you can:
https://github.com/bitpay/copay/blob/master/backupRecovery.md

"In case hardware based wallet is created and then the hardware device is lost, it is possible, using Copay, to access the funds in case the hardware device seed (mnemonic) is available."

It even specifically mentions hardware wallets used for multisig. 

Upon trying, it does seem this is not possible though. Somewhat of a false sense of security for those thinking this is possible.

**Comment by matiu** [comment]
To understand this issue better:

1. Is this a 2-2 wallet?
2. Was the wallet a ledger + a software copayer?
3. Do you have the full backup seed (words) from both the software and the ledger?

You dont need to recreate the wallet,the wallet is at BWS, you just need to import it on a new device.  Start with the backup of the software copayer and let us know.

**Comment by Chris869218** [comment]
1) This is a 4 of 6 wallet 
2) 2 software, 2 ledger, 2 trezor
3) The parties involved have the full backup seeds for all six pieces

Importing on a new device still isn't solving the errors when the hardware wallets sign. Only the 2 software wallets are able to sign, and those signatures still behave funny. The proposals are able to be deleted by other copayers when normally they would not be able to with less than 24 hours.

The wallet had been functioning fine (sending and receiving) for months previously, with no identifiable change when these errors began. 

Thanks for your help.

**Comment by matiu** [comment]
Given that the wallet is rather complex I think it will be better that we handle the problem by email. We will need some private info from the wallet (like the walletId), are you ok with that? My email is matias@bitpay.com

**Comment by matiu** [comment]
This problem was fixed on 3.5.0

 Every single request Copay does to BWS is signed using a key derived from the wallet. In normal software wallet, we use a hardened (1'/0) private key to sign, in a HW wallet, we cannot ask the  device to sign each request ... so we derive the "request signing key" using some entropy provided by the HW device. Because of that, "import from the seed" need a special proceeding if the seed is from a HW wallet. We add a toggle so the user can specify if the key is coming from a HW device. 

We have successfully test importing multisig HW wallets from seeds using the new interface. Thanks for the report.
