### ISSUE TITLE
Great Open Source Bitcoin wallet

### ISSUE THREAD

**Issue by Lyiono** [bitpay/copay#6173]
1. Dislike is that the app takes too long to open up. 1.Likes it's free and open source. 2. Works Great and does what it's suppose to do. 3. I'm just learning everything I can with bitcoin and this wallet is very user friendly especially for me learning a new money system,stock buying,selling with new Wallet system that seems to be pretty straight forward. Awesome job Developers

**Comment by dabura667** [comment]
Thanks!

**Comment by JDonadio** [comment]
Thanks 😄 !!
