### ISSUE TITLE
Two devices same recovery phrase?

### ISSUE THREAD

**Issue by drew345** [bitpay/copay#6174]
I am new to bitcoin and copay. I am about to move my bitcoin from coinbase to copay but want to understand these questions first.
I made my copay wallet on my windows laptop with the chrome app and then copied down the recovery phrase . It has zero balance.
Then I made a copay wallet on my android phone and I entered my recovery phrase there . It has zero balance.
So now I have two wallets on different devices with the same recovery phrase ? Is that right, or did I really mess things up when I entered my chrome app recovery phrase onto my android phone?
I just want to be really sure I have this recovery phrase straight before putting the bitcoin into my copay. I plan to put it in the chrome app.

**Comment by gabrielbazan7** [comment]
> Then I made a copay wallet on my android phone and I entered my recovery phrase there . It has zero balance.
You import your chrome app wallet in your phone ? 

> So now I have two wallets on different devices with the same recovery phrase ? Is that right, or did I really mess things up when I entered my chrome app recovery phrase onto my android phone?

It's ok. You could import that phrase in any device. So you could have the same wallet in your phone and in your chrome app.

**Comment by drew345** [comment]
Thanks. But I thought one thing about bitcoins is that they exist only in one place at a time . Is it really possible to have the same wallet on the phone and in the chrome app? I don't want to move my bitcoin in until I figure this out...  I am thinking to just erase both copay wallets and start fresh and not use my chrome app pass phrase when making my phone wallet.

**Comment by dabura667** [comment]
That phrase IS your wallet. Copay is just a tool to utilize that phrase to check balances and send money.

In general phones are more secure than desktop/laptops.

So what you could do is create a new wallet on your phone and delete the old wallet. Then export the new phone wallet as a json text file (be sure to check the box for "do not export keys")

Then import the file into chrome.

Now your chrome can watch your balance and create a transaction proposal, but only your phone can sign and broadcast the transaction.

**Comment by drew345** [comment]
I cannot find any information on how to export the phone wallet as a json text file (from android app). Can you give me pointer in the right direction for that? I like the idea of being able to see my wallet from Android even though only be able to make transactions from the phone.
Thank you,
Drew

**Comment by JDonadio** [comment]
Settings > Wallet > More options > Export wallet
<img width="373" alt="copay_-_copay_bitcoin_wallet" src="https://cloud.githubusercontent.com/assets/13851807/26832647/7ca4114e-4aa6-11e7-9195-77564446b2b6.png">
