### ISSUE TITLE
iOS softlock when using TouchID

### ISSUE THREAD

**Issue by staticfox** [bitpay/copay#6177]
Description:
If you enable TouchID on the iOS copay app and open the app, you pretty much have no choice other than to enter in your finger print or restart your phone as there is no alternative way to close the app. Hitting `Cancel` just re-spawns the dialogue and double tapping the home button to switch to another app does not work.

Steps to reproduce:
1. Open the copay app
2. Attempt to close out of the app by hitting cancel or tapping the home button

Proposed solution:
Have the `Cancel` button close the dialogue and just add a button in the middle of the splash screen with the TouchID logo to re-spawn the dialogue. Doing so would allow the end user to be re-prompted to enter their finger print while still allowing them to close the app as there would then be no TouchID session in progress without either a) having them manually initiating the session via tapping the button or b) initially opening the  app.

Let me know your thoughts on this! :)

**Comment by JDonadio** [comment]
Hi @staticfox thanks for your report. Can you please tell us what is your OS/app version?

**Comment by gabrielbazan7** [comment]
Hey! I just test it. You are right. We are sending a fix soon ! thanks

**Comment by staticfox** [comment]
Hi @JDonadio, details as follows:
OS: iOS 10.3.2
App Version: 3.3.0

@gabrielbazan7 :+1: 

I appreciate the prompt response to this, thanks! :)

**Comment by JDonadio** [comment]
Thank you @staticfox we'll working on that soon 😉
