### ISSUE TITLE
Bought bitcoin on Coinbase and didn't appear on Copay

### ISSUE THREAD

**Issue by alonsorl98** [bitpay/copay#6178]
I just bought 10 dollars worth of Bitcoin via the Copay app using Coinbase and I got charged but was never added to my account.

**Comment by JDonadio** [comment]
Maybe that's caused by a low fee and the network congestion. Can you provide the transaction id so we can take a look further? Thanks

**Comment by alonsorl98** [comment]
Where can I see the transaction ID? Thanks

**Comment by JDonadio** [comment]
Sorry about that, we found an issue and was fixed already. We are releasing a new version this week.

**Comment by JDonadio** [comment]
Your purchase for $10 probably is the source of the problem. Can you check your Coinbase account and tell me if the transaction was confirmed?

**Comment by alonsorl98** [comment]
Yes I have what I bought on Coinbase but not in my personal wallet on Copay. I transferred all of my bitcoins to Coinbase for now until there's a solution for it.
Thanks!
