### ISSUE TITLE
Best security on Android Copay App ?

### ISSUE THREAD

**Issue by drew345** [bitpay/copay#6179]
I have Copay as an Android app on my phone. My concern is that if I loose my phone, whoever finds it will have my fortune in bitcoins (not really fortune).  I have my phone screen locked by a pattern. And I found the way to lock the app with a 4 digit code. I am kind of surprised, that's it ?!?! a 4 digit code protecting my bitcoins ? A bank account for example would require a username and strong password. 
Is there more protection I can have for my copay android phone app? Even if there is a "send bitcoin" extra password, anyone who got it open could just hit "backup" and see my passphrase anyway.
Any advice for protecting my copay android wallet from phone thieves (or lucky taxi drivers) , appreciated.
Drew

**Comment by JDonadio** [comment]
Hi @drew345, the 4 digits (PIN code) is just an extra security capability an it is not "to protect" your bitcoins but to avoid in first instance someone check your balance or something. In the wallet settings you have 2 security options:

1- Spending password that encrypt your private key and it's required to access to your backup data, export options and obviously to spend your funds.
2- Fingerprint (if your device support it), this options doesn't encrypt nothing, simply require your finger check any time as above.

In addition, you can also create a multisig wallet that require 2 signers (in a 2 of 2) so if you lose your device no body can spend your funds. Another options is exporting your wallet without his private key and import it in another device, in this case you'll have a "read only" wallet to check your balance and transactions details but without the ability to send coins.

Hope that helps and clarify your inquiry.
