### ISSUE TITLE
Balance/Transactions not Showing in Chrome Copay from Imported Trezor xpub

### ISSUE THREAD

**Issue by mfitze** [bitpay/copay#6184]
I have 2 BTC accounts on my Trezor (Account 1 and Account 2), which I typically access using trezor.io.  I wanted to be able to monitor the balances with my ipad/iphone.  To set this up, I found instructions to, first of all, install the Copay Chrome extension and import the xPub of each account from the Trezor.  (From there you export the account info from the Chrome Copay app to the iOS Copay app, but that is not relevant to this issue at the moment - although, parenthetically, it did work fine for Account 1, and I can see Account 1 balance and transactions on my iPhone).

Everything on Chrome Copay works fine for Account 1 - I can see my balance and transactions.  However, for Account 2, Chrome Copay shows no balance and no transactions.  When using trezor.io, I can see both accounts exist, have a balance, and have several historical transactions.  I can also see that the xpub reported on trezor.io matches the xpub reported in the Copay Chrome app for both accounts (Account 1 and Account 2).

Any ideas why one account might work but not the other?  I have waited for about 16 hours so far with no "update," and, in advanced options on Chrome Copay under "Account 2", have tried clearing the cache and reloading the transactions.  Nothing.

**Comment by JDonadio** [comment]
We release a new version with a fix in the import process for hardware wallets, can you please try to upgrade your chrome extension and check if it is solved? thanks in advance.
