### ISSUE TITLE
Could not create address: cannot create new address for this wallet

### ISSUE THREAD

**Issue by ctettam9** [bitpay/copay#6187]
I just added my wallet to a phone and got this message when I hit the "receive" key:  "Could not create address: cannot create new address for this wallet. NULL"

The method of adding the wallet was using the IMPORT WALLET prompt and typing in my 12 secret words.  

I'm running the following:
Samsung Note 5
Android Version 7
Android Security Patch Level May 1, 2017
Kernel 3.10.61

Any thoughts to this error?  I've added my account to an iPad and it works.  

Chris

**Comment by JDonadio** [comment]
Sorry for the delayed reply. We release a new version 3.4 can you try again and tell me if the error remains? thanks

**Comment by ctettam9** [comment]
This is the original version I was using when I got this error.  I've also
uninstalled it, Rebooted, and reinstalled then fresh reboot.

**Comment by rokaHakor** [comment]
I have same issue

**Comment by jkokorian** [comment]
Same issue

**Comment by netstatsys** [comment]
I'm getting this right now and everything is up to date.

**Comment by netstatsys** [comment]
v3.8.3 getting this error, help?

**Comment by 1m0d** [comment]
+1

**Comment by JDonadio** [comment]
Maybe the same for https://github.com/bitpay/copay/issues/6066

We'll investigate it further.

**Comment by gabrielbazan7** [comment]
Sorry for the delay. It seems that is working well for v3.15 or v4.1
