### ISSUE TITLE
I have funds in my copay account and say insufficient funds

### ISSUE THREAD

**Issue by Rasino** [bitpay/copay#6190]
I have funds in my account in copay and says insufficient funds, when I try to withdraw even a few tell me that there are not enough funds to pay the commission and I do not know what to do

**Comment by gabrielbazan7** [comment]
Try with the send max option. On the amount view just click the "..." in the upper right of the view and tap "Send max amount". The wallet will now calculate how much bitcoin can be economically sent.

**Comment by Rasino** [comment]
Try to just try that alternative, I only have USD 337 and only send USD 5.6, the rest stays where?
Or do I have to lose UDS 331 ???
Were earned daily from Genesis mining

**Comment by gabrielbazan7** [comment]
The parameter used for the fee calculation is the TX size, not the output amount. So, this could happen when you have many small inputs in your wallet, so you need to use all (or most) of them to build the transaction and your fee will be increase significantly.

**Comment by Rasino** [comment]
And then I should do to remove my btc 0.118101, I try to change it to my other account that is in the same account and then I lose all my btc for wanting to remove them, there must be some way more intelligent to withdraw without losing my funds

**Comment by Rasino** [comment]
I'm using the google translator, I do not speak English, the translation may have flaws

**Comment by dabura667** [comment]
If I receive $500 in BTC one time, it will cost me about $2 to send that $500 of BTC, so I can only send $498.

If I receive $5 in BTC 100 times (total same $500), it will cost me $175 to send that $500 of BTC, so I can only send $325.

This is how Bitcoin works.

Don't receive small payments frequently. Try to receive as large payments as possible.

**Comment by Rasino** [comment]
![copay 2](https://user-images.githubusercontent.com/29239317/26858134-9dca445e-4afd-11e7-8632-d62a14101d58.jpg)
![copay 3](https://user-images.githubusercontent.com/29239317/26858135-a3a847a4-4afd-11e7-9b57-729ae83e4bf3.jpg)
![copay enviando 1](https://user-images.githubusercontent.com/29239317/26858139-a770dfc2-4afd-11e7-96e7-8e5252e3017c.jpg)

**Comment by Rasino** [comment]
Learning this way is very expensive
Gracias

**Comment by JDonadio** [comment]
@Rasino te recomiendo que para evitar el incremento en tus fees hagas un send max a tu misma wallet o a una nueva (como prefieras). De este modo lo que vas a lograr es que tengas únicamente 1 solo input con toda tu plata en vez de muchos con poca (como ahora). Hay que evitar, como dice @dabura667, de tener muchos inputs chicos porque luego para mandar vas a necesitar muchos de esos inputs y es ahí cuando el tamaño de la transacción crece y eso es lo que lleva a que tu fee sea costosa.

**Comment by Rasino** [comment]
Hola, de 332.56 usd, si los envio todos ( Max) solo rescato 5.34 usd.  el resto se pierde solamente. Trate de eliminar la direccion de wallet de copay en Genesis mining para que no me hagan mas envios pequeños y no se puede. Parece ser todo una linda trampa que beneficia a los mineros solamente. Gracias de todas maneras

**Comment by Rasino** [comment]
![cantidad max](https://user-images.githubusercontent.com/29239317/26887193-5a355710-4b75-11e7-8f57-417c1e22c9d2.jpg)

**Comment by Rasino** [comment]
Total                          BTC  0.118101
Cantidad MAX          BTC  0.001908
Pierdo (lost)             BTC  0.116193

Esto se junto en aproximadamente 6 meses  y ahora son solo 5.27 usd

**Comment by dabura667** [comment]
98% fee???

Currently "normal" fee is 474 sat/byte on Copay, which for a 1-of-1 input would be 148 bytes x 474 =~= 0.0007 BTC per input...

Looking at his screenshot, I see some big amounts there where 0.0007 BTC would be only a small percent, like 0.03 BTC... if "max" is saying 0.001908, something is screwed up.

I understand that Copay would check to make sure that utxos worth less than feeRate x inputbytesize but would it check for an unruly number of extremely close utxos? (ie, utxoVal - estFeeAdded = 1 satoshi, it would contribute to the total, sure... but it would pull up the median fee from a much much lower one that would leave the user with much more to send)

I think this is an edge case where the user has many many utxos that are worth just a tiny hair over 70152 satoshis each (the 148 byte x 474 satoshi per input amount) and it pulling up the total fee closer and closer to 100% but never crossing...

If he just sent only the 0.03 utxo I see on his screen he will be able to send 0.0293 BTC easily.

**Comment by dabura667** [comment]
Wait, it is late at night and I don't think anything makes sense anymore to me. I think maybe someone should look at this user's wallet on the DB.

**Comment by isocolsky** [comment]
I think your case is a good one for [VIA BTC's transaction accelerator](https://www.viabtc.com/tools/txaccelerator/). It works on transactions with a minimum of 0.0001 BTC/kB. The trick would be to gain access to your funds from a wallet that allows you to set your fee manually.

**Comment by Rasino** [comment]
habra alguna solucion para no perder tanto

**Comment by JDonadio** [comment]
Viendo tu caso me parece extremo. Yo para mover todos mis fondos necesito ~$60 USD. Otros compañeros ~$150 USD. No hay otra manera de que baje significativamente desde nuestro lado. No se si alguien de la comunidad podría ayudarte en este caso.

Reviewing your case I think it's extreme. I need ~$60 USD to move all my coins. My friends ~$150 USD.There is no way to decrease it significantly from our end. I don't know if someone else could help you with this.

**Comment by Rasino** [comment]
Gracias, los dejare mas tiempo en espera que se soluciones, esto esta mal
Gracias 
Rafael.

Thank you, I'll leave you more time waiting for solutions, this is wrong
Thank you
Rafael.

**Comment by JDonadio** [comment]
> The trick would be to gain access to your funds from a wallet that allows you to set your fee manually.

This is a good point, you should investigate it further.

**Comment by knoxcard** [comment]
To my understanding, Bitcoin Cash solves all of this right?  The problem of high transaction fees.

Also, do NOT send Bitcoin to Bitcoin Cash or vice versa, I think I read that your funds will be lost if you do so.
