### ISSUE TITLE
I have sent funds to my CoPay Wallet and they've not shown

### ISSUE THREAD

**Issue by RumbleDemon** [bitpay/copay#6192]
over the course of one day I sent at least 3 btc to my CoPay wallet; however they have not arrived.  Where are they?  I triple checked the accuracy of my bitcoin address.

**Comment by matiu** [comment]
Ask the send for transaction ID and check it on a block explorer. If it shows on a block explorer and the TX is confirmed let us know an we will check it. Please reopen is that is the case.
