### ISSUE TITLE
extremely high fee

### ISSUE THREAD

**Issue by themovement919** [bitpay/copay#6196]
i set the fee to the lowest possible amount and still one transaction that i made yesterday cost me 71GBP in fee's. what is going on here?

**Comment by doganakdag** [comment]
I totally agree, they cut extremely high fee during sending another wallet. I'm totally shocked about it and cannot transfer my significant amount of bitcoin.

**Comment by JDonadio** [comment]
Please see https://github.com/bitpay/copay/wiki/COPAY---FAQ#copay-requires-high-fees-for-low-amounts-transactions
