### ISSUE TITLE
OSX binary signature invalid

### ISSUE THREAD

**Issue by wskinner** [bitpay/copay#6198]
I downloaded the latest OSX binary from https://github.com/bitpay/copay/releases/tag/v3.4.0. 
I then attempted to import the public key using gpg, but it failed.
`21:29:44 willskinner@deepthought Downloads gpg --recv-keys 1112CFA1                                                                                                                                  1 ↵
gpg: requesting key 1112CFA1 from hkps server hkps.pool.sks-keyservers.net
gpgkeys: HTTP fetch error 60: SSL certificate problem: Invalid certificate chain
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver helper internal error
gpg: keyserver communications error: general error
gpg: keyserver receive failed: general error`

I was able to import the public key (fingerprint 9D17 E656 BB3B 6163 AE9D  7172 5CD6 00A6 1112 CFA1) via copy / paste from github.

However, the signature did not check out.
`21:29:35 willskinner@deepthought Downloads gpg -v --verify Copay.dmg.sig Copay.dmg
gpg: Signature made Wed Jun  7 10:36:04 2017 PDT using DSA key ID 1112CFA1
gpg: using PGP trust model
gpg: BAD signature from "Copay (visit copay.io) <copay@bitpay.com>"
gpg: binary signature, digest algorithm SHA256`

**Comment by wskinner** [comment]
I just tried to verify a couple of the other signatures on my linux machine. The latest Bitpay linux binary verifies, but the Copay binary doesn't.

**Comment by matiu** [comment]
Thanks for the info, it should be fixed now. We uploaded the wrong .sig file.

**Comment by JDonadio** [comment]
Reopen if the error persist
