### ISSUE TITLE
Amazon giftcard code not yet seen after confirmation from the blockchain network

### ISSUE THREAD

**Issue by JTCarcil** [bitpay/copay#6199]
Hi support, I made an order of 432 usd for the purchase of an Amazon giftcard using the lowest possible fees since the transaction fees was way too high and it took a while to be confirmed ,  the status on the invoice shows paid but the code has not been reflected. Please help look into it. Here's the transaction Id
78e3d3d57eeae17a4a03e8b517d3b4a801f959b466731f8507e1a42c94de1ac4

**Comment by JDonadio** [comment]
Hi @JTCarcil let me check your case and I'll contact your privately. Please send me an email to `javier@bitpay.com`

**Comment by JTCarcil** [comment]
j.carcil@yahoo.com
