### ISSUE TITLE
Blockchain Error Message - Fees Unpaid Transaction Unconfirmed

### ISSUE THREAD

**Issue by rafakortez** [bitpay/copay#6200]
Hi,
I've got a problem sending funds with a message ''Blockchain Error'', but it was completed anyway,
For some reason it's not showing on Windows Copay, Transaction:
[https://insight.bitpay.com/tx/9b4fc94bd1d9af7f87087d37eb5bd953cb30ba68336ffd410ac141ff43e1db4f](url)

Seems that it didn't went trough or didn't pay fees properly, but the balance is 0, even after received and confirmed amount:
![copay](https://user-images.githubusercontent.com/4512550/26914020-b86d1560-4c16-11e7-99ef-822c686cb839.png)

So, I've received the amount, than sent it (transaction above), but is not showing on Copay, 
and no confirmations so far.

Please check the last Received Transaction ID:
[https://insight.bitpay.com/tx/e846259e8089b5c754c6f05bf8ebce186c25175fd7a5b829c3a25b0706976a93](url)

Thank you

**Comment by rafakortez** [comment]
The Received transaction:
[https://insight.bitpay.com/tx/e846259e8089b5c754c6f05bf8ebce186c25175fd7a5b829c3a25b0706976a93](url)

The only thing missing is the last Sent one where i got the message ''Blockchain Error'' but sent.

**Comment by rafakortez** [comment]
How can the balance be Zero if the last transaction was received BTC?

**Comment by JDonadio** [comment]
Sorry for the delayed reply. Are you able to see your history correctly?
