### ISSUE TITLE
Shuffled Seed

### ISSUE THREAD

**Issue by otaviobps** [bitpay/copay#6201]
Hi everyone. I have all 12 words of my seed, but they are shuffled.

Is it possible to recover it? Bruteforce it untill find the correct order?

Thanks

**Comment by JDonadio** [comment]
Do you have any idea of the correct order or all of them are shuffled? If you have no idea then you have a problem, the number of possibles combination is `479.001.600`. However Copay doesn't have any failed attempts control, so you can try to import it any times as you want if you remember a possible pattern.

**Comment by otaviobps** [comment]
Unfortunately I don't have a clue.

**Comment by JDonadio** [comment]
There is no much to do I think. However there are another users with that problem or similar, you can take a look in the issues list and maybe someone can give you more support.

**Comment by otaviobps** [comment]
Thanks. I think the only way to recover it is brute forcing the seed, but I'm no coder, so I don't know how to build this script

**Comment by dabura667** [comment]
How much money is in there?

If you offer a bounty maybe someone will make it for you.

**Comment by parkermor** [comment]
@otaviobps 
If you have still your problem with the right order of your recovery phrase, I can find the right order and recover your wallet. if you want need help send me email : anywalletrecovery@gmail.com
