### ISSUE TITLE
Showing notification for outgoing transfers as if it were incoming transfer

### ISSUE THREAD

**Issue by RussianSwiss** [bitpay/copay#6207]
Showing notification for outgoing transfers as if it were incoming transfer

**Comment by JDonadio** [comment]
Could you explain it a little bit? If you can attach some screenshot would be great.

**Comment by RussianSwiss** [comment]
Too busy to post screenshots. I made an outgoing transfer, app immediately showed me notification about incoming transfer with same amount. No other transfers were made.

**Comment by RussianSwiss** [comment]
Hmm, this is wallet with single address (non-BIP32).

**Comment by gabrielbazan7** [comment]
We could not reproduce the issue
