### ISSUE TITLE
Keine Bestätigung seit 24 Std. 

### ISSUE THREAD

**Issue by jomo2013** [bitpay/copay#6210]
Hatte ich das letzte Mal auch hat dann 48 Std. gedauert und das Geld war wieder meiner Brieftasche gutgeschrieben, Ursache zu niedrige Gebühr denke ich. Nun habe ich die Gebühr auf 0.001074 erhöht und es passiert trotzdem nichts! Und immer wenn ich copay aufmache steht da bei senden vor ein paar Sekunden, dabei hab ich es gestern losgeschickt. Und wenn ich auf blockchain anzeigen gehe, wird die Transaktion nicht gefunden. Was soll das? Was soll ich jetzt machen?

**Comment by JDonadio** [comment]
Can you explain your issue in english? I tried with the google translator but isn't clear at all.

**Comment by jomo2013** [comment]
4  days before i send Bitcoins to a adress and it came back after two days... i think the Kind of the Problem was a too low Fee...  Yesterday i send it again with 0.001074 Bitcoins Fee and it send Not... The Problem yet is that it not send, and when i go to copay there stand by send the time from Yesterday, and one second after, there stand you send it for a few  seconds... I want my Bitcoins Back to my wallet... Sorry my English is Bad...

**Comment by jomo2013** [comment]
![screenshot_20170609-175716](https://user-images.githubusercontent.com/29284574/26984626-6632b9dc-4d40-11e7-8982-4d2f36c7ca9e.png)
![screenshot_20170609-175752](https://user-images.githubusercontent.com/29284574/26984635-723b8ad8-4d40-11e7-92a3-b92823ccc5a0.png)
![screenshot_20170609-181538](https://user-images.githubusercontent.com/29284574/26984655-81acb3fc-4d40-11e7-9435-b84a7922aeb0.png)

**Comment by jomo2013** [comment]
I dont can send bitcoins anywhere...

**Comment by jomo2013** [comment]
I cant send bitcoins anywhere...

**Comment by JDonadio** [comment]
Please try cleaning your cache and also scanning your addresses for funds:

Settings > wallet > more options > transaction history > clear cache
Settings > wallet > more options > wallet addresses > scan addresses for funds
