### ISSUE TITLE
BTC Multisig Hardware wallet Copay chrome app - Ledger Nano S getting "Error - bad signatures" when signing transaction proposal

### ISSUE THREAD

**Issue by j-vern** [bitpay/copay#6212]
I am using the Ledger Nano S 1.6.20 and the copay chrome app on windows v3.2.1.

I could import my copay shared wallet, however when I want to sign a transaction proposal, I get an error message on copay even though on Ledger Nano S, the signature is said "successful".

Anyone could help me on this?

Thx!

**Comment by abbyetwu** [comment]
Our company also use copay/ledger wallet at asset management, we also have the same problem.

**Comment by JDonadio** [comment]
Hi there, we are reviewing this case. We'll keep you posted. Thanks!

**Comment by JDonadio** [comment]
Hey, we release a new version for chrome-app. Can you try and tell me how it went?
