### ISSUE TITLE
Request: Signed git tags

### ISSUE THREAD

**Issue by kylemanna** [bitpay/copay#6213]
Hey all,

I was using the signed binaries for quite some time until recently there were some [issues](https://github.com/bitpay/copay/issues/6204) with them.

I'm now updating my [package](https://aur.archlinux.org/packages/copay/) to manually build the app from source, but struggle to authenticate the releases.  Would it be possible to sign the current `v3.4.0` and future git tags with the same PGP key so that source builds can be authenticated as well?

Thanks!

**Comment by dabura667** [comment]
GPG... so secure that no one uses it :sunglasses:

I wonder if Copay's revocation certificate is properly generated and backed up...

**Comment by BGalliotti** [comment]
Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will happy to help you.
Thanks.
