### ISSUE TITLE
Problem with recovery wallet !

### ISSUE THREAD

**Issue by ramiali1994** [bitpay/copay#6214]
i was have old iPhone 5s with application of copay wallet , and i move to iPhone 6s and i did the recovery to the new iPhone 6s from the old iPhone , then the iPhone 6s become damage and i didn't do backup to wallet , the only backup i have the it's the old one with the 12 sentences , i try to recovery it with it and password i got error , please can anyone enplane to me how to recover my wallet .

thank's

**Comment by JDonadio** [comment]
Did you import in first instance from old to new phone successfully and now you can't? Did you made a new backup from the new one or are using the same from the old one?

**Comment by ramiali1994** [comment]
the first time its successfully , then i try to to recovery from the old backup and is not successfully !

**Comment by JDonadio** [comment]
The only way to get access to your coins is with your backup, so please check the backup phrase (12 words), file/text backup, your password or whatever but unfortunately we can't do anything for you.
