### ISSUE TITLE
Wallet Balance Locked

### ISSUE THREAD

**Issue by johnvamo** [bitpay/copay#6219]
Hello How can I unlocked my wallet balance? It is configured with Trezor. What I should do?

Thanks for your cooperation. 

John

**Comment by JDonadio** [comment]
Can you explain your issue a little bit? maybe attaching some screenshots to see exactly what is going on.

**Comment by johnvamo** [comment]
Hello,
I just resolved the issue by deleting the payment proposal...I had not seen the option very down the window. I think I used the same address used in a previous transaction to the same merchant.

 Thank you for your replay.

**Comment by knoxcard** [comment]
Uhhh, what's the deal?

![wallet_locked](https://user-images.githubusercontent.com/7561190/31705537-a8cbfc98-b39a-11e7-9a4c-5666a1fa425b.png)

**Comment by knoxcard** [comment]
What's going on??

![2017-10-18_00h24_45](https://user-images.githubusercontent.com/7561190/31705562-c0d98dfa-b39a-11e7-8f24-eee32ddb1bc2.png)

**Comment by Soorena** [comment]
^^ I’m having the same issue as Knoxcard wtf

**Comment by BeefUnit** [comment]
I am as well when trying to connect to Steam. :(

**Comment by sbruinsje** [comment]
Same! getting the "wallet locked" error whenever i open the "receive" tab.

**Comment by JaysonH91** [comment]
Same error for me right now as well

**Comment by WISERY1** [comment]
Same error as well!

**Comment by deguzman1104** [comment]
WALLET LOCKED: Wallet is locked 
with Bitpay, please help.

**Comment by matiu** [comment]
We are investigating the issue now. I will update this ticket as soon as we have more information.

**Comment by matiu** [comment]
actually,  please follow,  https://github.com/bitpay/copay/issues/6930
