### ISSUE TITLE
Change default currency from USD

### ISSUE THREAD

**Issue by UnicornsOnLSD** [bitpay/copay#6221]
Not sure if this has already been done but as someone who lives in the UK, it is very confusing to have to measure costs in USD.

**Comment by JDonadio** [comment]
You can find the currency list in Settings > Alternative currency

![image](https://user-images.githubusercontent.com/13851807/27013182-511d4ce4-4eb5-11e7-9407-5d443e2081f0.png)

**Comment by UnicornsOnLSD** [comment]
@JDonadio I've set it to GBP but all currency related information on the program is still in USD

**Comment by JDonadio** [comment]
Can you attach an screenshot?

**Comment by UnicornsOnLSD** [comment]
http://i.imgur.com/MQOF5ul.png
http://i.imgur.com/tTmxrED.png

**Comment by JDonadio** [comment]
What version are you running and what platform? It's working for me with the latest version.

**Comment by JDonadio** [comment]
@UnicornsOnLSD are you trying to buy a Gift Card or Top-up your BitPay card or just send money normally to another address?
