### ISSUE TITLE
Amazon Gift Card code doesn't shows up.

### ISSUE THREAD

**Issue by XavierOrejarena** [bitpay/copay#6222]
Yesterday I bought a Gift Card from the Windows BitPay app, but the code doesn't shows up.

Here is the invoice: https://bitpay.com/invoice?id=3zsSPRbZFrJ34Qc6NewBFV

Here is a screenshot of what the app shows: https://prnt.sc/fihtev

Here is anotherone: https://prnt.sc/fihtq1

Here is the blockchain trasaction information: https://insight.bitpay.com/tx/05ca18a1f3dff8eca1b17c0e83343cbaf5b0e8651954827fbaf8eac630360de8

I tried to restart the app, my computer, clear wallet cache, login from another device, nothing works.

The amount of gift card was: 154.68$

**Comment by gabrielbazan7** [comment]
Please email help@bitpay.com with that information ! Sorry about that
