### ISSUE TITLE
I've lose my money

### ISSUE THREAD

**Issue by apenbaring** [bitpay/copay#6223]
So, i've made a transaction some days before, it was unconfirmed for a while (2 days), that's why I couldn't use my money. But now i can't see any money on my wallet, and transaction has disappeared from the history. Help me please

**Comment by dabura667** [comment]
Most likely the person who sent to your wallet set a low fee, and the transaction was reversed.

Tell them to send again, this time with a proper fee.

**Comment by JDonadio** [comment]
Do you have the transaction ids? Try refreshing your transaction history in settings > wallet > more options > transaction history > clear cache.

If doesn't work, send me your wallet id to javier@bitpay.com

**Comment by JDonadio** [comment]
Should be ok now. Sorry about that.
