### ISSUE TITLE
Fees in transaction 

### ISSUE THREAD

**Issue by bitexchangers** [bitpay/copay#6224]
Hello im developing and business using copay code, im sending approx 20.000 usernames to copay, Is there any way to charge another fee for my company, since I want to make an economic expense to improve the copay wallet and I would like to be able to recover the money invested

**Comment by dabura667** [comment]
Are you talking about the miner fees when sending bitcoin?

These fees are given to the miners, not Copay. Copay can not give you a discount because Copay does not take any money.
