### ISSUE TITLE
Amazon Gift Card

### ISSUE THREAD

**Issue by ToxicF3AR** [bitpay/copay#6226]
So I purchased an amazon gift card and money is deducted but I got nothing what the hell is this scam or what ?

**Comment by gabrielbazan7** [comment]
Can you show me screenshots of the transaction in your wallet history ?

**Comment by ToxicF3AR** [comment]
![screenshot_8](https://user-images.githubusercontent.com/3371405/27041291-346c2334-4fb1-11e7-9d75-9a2c7458daae.png)
![screenshot_9](https://user-images.githubusercontent.com/3371405/27041292-3475d078-4fb1-11e7-9524-9a6c474f590d.png)


So I bought an 160$ gift card but screenshot is 150$ because bitcoin price dropped and as you can see the gift card is not there in the app.

**Comment by JDonadio** [comment]
Please, check the tx on blockchain and copy/paste the transaction id here.

**Comment by ToxicF3AR** [comment]
https://insight.bitpay.com/tx/13271a6f6dc6cd43a4f93ec4ba6b5cc64f94b3836d46cfc64808dc85a722ca90

**Comment by JDonadio** [comment]
Please, contact the support team sending that info.

help@bitpay.com
