### ISSUE TITLE
Can't send bitcoin without using coinbase?

### ISSUE THREAD

**Issue by john3298** [bitpay/copay#6231]
Why is this a thing? When pressing send you can choose to buy bitcoin or show bitcoin address. So it makes sense that as long as i have money in my wallet i should be able to send it no?

**Comment by JDonadio** [comment]
Go to settings > advanced > use unconfirmed funds.

If you have not funds, or if you have **only** unconfirmed funds your send view will display this options.

![copay_-_copay_bitcoin_wallet](https://user-images.githubusercontent.com/13851807/27408015-1bcd8dfc-56b1-11e7-8a0c-a0e129c2d60a.png)

Once received and confirmed, you will be able to send that funds.
