### ISSUE TITLE
Bitcoin not reflecting in my Copay wallet

### ISSUE THREAD

**Issue by 09071981** [bitpay/copay#6232]
I transferred some bitcoin from my mine to my Copay wallet but it is not reflecting in Copay even though it was deducted from my mine.  I used an unused address from Copay. Please help.

**Comment by JDonadio** [comment]
If the transaction was not generated by Copay you must check it with the sender, in this case your mine.

**Comment by 09071981** [comment]
It finally reflected. Thanks
