### ISSUE TITLE
I cannot send payment...issue....

### ISSUE THREAD

**Issue by corethical** [bitpay/copay#6234]
It's about 4 hours I'm trying to pay 150 dollars, I ve in my wallet 200 dollars, each time I try to send bitcoins, it tells me not enough funds to 0ay transaction fee. I went on settings ti check and fees are 0.0037 bitcoins ahich are 10 dollars about. What can I do to solve this issue I'm locked for the moment...Please can someone teply to explain me if I do something wrong thank you very much

**Comment by gabrielbazan7** [comment]
https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-always-get-insufficient-funds-for-fee-when-trying-to-send

https://github.com/bitpay/copay/wiki/COPAY---FAQ#copay-requires-high-fees-for-low-amounts-transactions
