### ISSUE TITLE
Having trouble with insufficent funds message

### ISSUE THREAD

**Issue by tappers22** [bitpay/copay#6241]
I signed up for Copay today and I managed to send some Bitcoin to my wallet. I found a vendor I wanted to purchase from, but before I did that, I made sure I had enough in my account to purchase the item.

When I go and scan the vendors symbol to generate a payment amount and address, I keep getting the message, "insufficient funds". I tried several times without any success. 

Either it's not reading the amount I have in my account or something, I'm not sure. Any assistance you can provide would be appreciated.

**Comment by JDonadio** [comment]
https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-always-get-insufficient-funds-for-fee-when-trying-to-send
