### ISSUE TITLE
Send Button doesn't work

### ISSUE THREAD

**Issue by powerofshady** [bitpay/copay#6243]
Hi guys.
I am newbie and I use copay on Android.
I already did a transaction (send) but since two days, i am not able to send anymore. Everythibg is fine, no error is found but when i press the send button, it doesnt work.

**Comment by JDonadio** [comment]
Hi @powerofshady, can you add an screenshot of your send view so we can see what is happening? Also, if you can copy and paste your session log would be great, you can find it in: settings > about copay > session log.

Thanks

**Comment by gabrielbazan7** [comment]
Also which device are you using ?

**Comment by powerofshady** [comment]
Hi, i copied the sessions logs but there stands "Be careful, this could contain sensitive private data" so i wont paste it in an official forum.

![screenshot_2017-06-14-15-42-25](https://user-images.githubusercontent.com/29432240/27135929-1d01e5a2-511a-11e7-9136-7ecf1b197882.png)

So i clicked everywhere to send it but it doesnt react

i am using:
GT-I9192 (samsung s4 mini)
adroid version 4.2.2

**Comment by gabrielbazan7** [comment]
It seems to be an UI issue there. Should be a slider there at the bottom. Could you try sliding ? 
It looks like this: 
![image uploaded from ios 18](https://user-images.githubusercontent.com/10999037/27136606-1ff0e330-50f2-11e7-8541-4cf531984242.jpg)

**Comment by powerofshady** [comment]
Dude.... wtf.... i love you!

**Comment by powerofshady** [comment]
Thanks to all!

**Comment by JDonadio** [comment]
@powerofshady  your'e right! I should have suggested you send the info by email 😉. So, this an UI error regarding to android version 4.x.x. (I think the 4.4.x is working well). If you can update your OS, do it. If not, try to use another device to avoid this inconvenience. Sorry about that.
