### ISSUE TITLE
The bitpay website calculate wrong btc amount

### ISSUE THREAD

**Issue by ToxicF3AR** [bitpay/copay#6246]
![screenshot_11](https://user-images.githubusercontent.com/3371405/27161057-5f2db416-5196-11e7-9792-38b5ca764f70.png)

The website says to send 100$ but in the client it says its sending 101.72 this is 2$ lose out of nothing.

**Comment by matiu** [comment]
Please note the amount in btc is the same. If you click the carat on the bitpay invoice page you will see the details ( fees)

**Comment by ToxicF3AR** [comment]
There is nothing like even when I pay a 5$ it charges 6.70 is this a joke ?
