### ISSUE TITLE
Can we get to set our own desired fees ?

### ISSUE THREAD

**Issue by ToxicF3AR** [bitpay/copay#6247]
Can we?

**Comment by TAiS46** [comment]
We need this!

Blockchain recommend a fee of 87 sat/b while bitpay / copay asks for:

Urgent: 639
Normal: 352
Super Economy: 241

**Comment by jordansteeves** [comment]
Yeah who thought this was a good idea...

**Comment by Mirobit** [comment]
Copay definitely needs custom fees are at least a super super economy option. I choose super economy and paid 0.002x per KB. The transaction got confirmed in the next block. Current calculations are totally useless and overpay almost all the time.

**Comment by dabura667** [comment]
Copay and Bitpay use the same fee algorithm as bitcoind. (In fact, they just query bitcoind)

**Comment by mazamats** [comment]
Definitely need this feature. Even with the super economy option, it costs me $5 in fees to send $10...

**Comment by RussianSwiss** [comment]
Also we need **super extra economy fee.** :-)

**Comment by Mirobit** [comment]
Ping. This needs no happen asap. With the current settings Copay forces thousands of users to overpay and to feed greedy miners.

**Comment by dabura667** [comment]
I agree it would be nice to have an advanced feature to allow custom fees.

However, more importantly wallets need to fix fee estimation algorithms. Otherwise the 90% of people who don't care and just pick default will be driving up fees.
