### ISSUE TITLE
Network error 

### ISSUE THREAD

**Issue by Plies10** [bitpay/copay#6248]
Hello 
I keep getting network error on my copay and bitpay wallet 
Which lead to me deleting my copay app.
I have reinstalled the app but can't import my wallet anymore 
I even tried getting started with a new wallet 
But am still getting the network error. 
![img_6482](https://user-images.githubusercontent.com/29447914/27182102-1a1903e4-51d2-11e7-98d9-5efed2702868.PNG)
![img_6486](https://user-images.githubusercontent.com/29447914/27182104-1a946c78-51d2-11e7-80ea-e8b81b2969be.PNG)

**Comment by JDonadio** [comment]
@Plies10 sorry about that. That error is caused by a bad internet connection or maybe a congestion in our server but should be temporary. Can you try again in a minute and tell me if it is still happening? thanks in advance.

**Comment by JDonadio** [comment]
Also it could be caused by connection problems with cloudflare, you can check our bws status [here](http://stats.pingdom.com/dm8bfk2t3v6b/1640644). In addition you can try changing your network (i.e, 4g > 3g).

**Comment by Plies10** [comment]
It's actually still the same network error. 
Am surfing the internet fine.
I still don't know why am getting the network error

**Comment by Plies10** [comment]
My last transaction was on the 8th of June. 
I noticed the network error issue a couple of days back

**Comment by Plies10** [comment]
It's both on my copay and bitpay wallet 
I have asked someone else making use of copay
She said hers is working fine. I wonder why would mine not work as well.
Should I move the wallet from my tab to my laptop?

**Comment by dabura667** [comment]
@Plies10 Tell me what you see when you click this link on the same device as your wallet?

https://bws.bitpay.com/bws/api/v2/feelevels
