### ISSUE TITLE
Lower fee priority leads to higher fee

### ISSUE THREAD

**Issue by chrisrico** [bitpay/copay#6250]
Some labels blanked out for privacy.

![image](https://user-images.githubusercontent.com/3641429/27191588-da527006-51bd-11e7-9d22-fe59f76ebf2f.png)

**Comment by dabura667** [comment]
Hmm, seems like:

1. An unhandled edge case.
2. Fee estimation changed between queries.

One of these two...

I would assume if screenshots were taken, both fees were viewed twice at least, so number 2 seems unlikely.

**Comment by chrisrico** [comment]
I switched between priorities multiple times, with the same result every
time. Ranked from cheapest to most expensive they were always: normal,
super economy, economy.

**Comment by JDonadio** [comment]
Hi @chrisrico, yes we could reproduce it. We are reviewing the cause to get fixed ASAP. I'll keep you posted. Thanks for the detailed report.

**Comment by jlauwers** [comment]
Not sure if it's the same issue, but right now priority normal and economy have the same 353 sat/byte fee.

**Comment by JDonadio** [comment]
Should be fixed now. If the issue remains please reopen this. thanks!

**Comment by JDonadio** [comment]
Should be ok now. Thanks for the detailed report.
