### ISSUE TITLE
Giftcard issue

### ISSUE THREAD

**Issue by jesusinan** [bitpay/copay#6252]
Hello i have a problem with i giftcard that i bougth saturday. I redem it and it says that the code is desactived , i talk with Amazon and they said That is a problem with the seller Here is the id transaction 

https://insight.bitpay.com/tx/5dc034150115b89aa6a43bb67c865c60b55cbd913c08bb8fad090090884b8d29

**Comment by JDonadio** [comment]
Sorry about that, please send an email to help@bitpay.com to get a better assistance.
