### ISSUE TITLE
Manual Receive From Bittrex - Invalid Address

### ISSUE THREAD

**Issue by findamind** [bitpay/copay#6253]
I have attempted to send coin from Bittrex using the alpha numeric address presented beneath the QR code in the iOS app, again in the Windows App, then again in the Chrome app. These have all generated new alpha numeric codes. The Bittrex exchange does not support QR code transfers. Each time I have double and triple checked what I have typed as the CoPay app does not support "copy" to ensure accurate translation of the address from the app to the exchange.

Please advise if I am doing something wrong, or if you need more info from me. -- Thank You

**Comment by JDonadio** [comment]
Tap on the QR code to copy to your clipboard. Let me know if you have any problems.

**Comment by findamind** [comment]
Problem solved. User error. Thank you! I have now been able to transfer from Bittrex to CoPay and use CoPay to purchase a Ledger Nano S. Thank You Very Much!

**Comment by JDonadio** [comment]
Glad to help 😉
