### ISSUE TITLE
Lost BTC in transit to copay wallet

### ISSUE THREAD

**Issue by indonadian** [bitpay/copay#6261]
I bought some Bitcoin at a BTM & got them in a paper wallet that was created by the BTM. Later i tried to move the BTC a wallet, and Blockchain redirected me to a Copay Wallet, so i followed the instructions & was successful it transferring my BTC to the Copay and it said it would take 10 min to appear in my wallet. Now it's hours ago & the BTC still does not show in my wallet. Can anyone help me find my BTC? Thanks, this is worrisome already

**Comment by gabrielbazan7** [comment]
You sweep the paper wallet using Copay ? You should see a receive transaction on your wallet history, and you could check on insight you transaction status.

**Comment by indonadian** [comment]
Hi, yes, you are absolutely right with this answer. We didn't know that we
had to sweep the paper wallet in the process and that's why no money
appeared. Thankyou very kindly for your advice, it's much appreciated. The
BTC has now showed up and is no longer lost. Cheers !!
