### ISSUE TITLE
Such high fees for copay

### ISSUE THREAD

**Issue by Pal0720** [bitpay/copay#6264]
Why this useless structure of dynamic pricing. Its charging me more than I want to send. who takes 30 % of the transaction fees

**Comment by laudaa** [comment]
The mempool today (depending on where you look at) is very small. Therefore, transactions with 50-100 satoshis/byte were getting confirmed very quickly (sometimes even within the very next block). The super economy option (at the same time) in Copay asked for ~200 satoshis/byte. This makes the users **overpay by a large amount**. 
Copay either needs better dynamic fee estimation, or optimally an [advanced] option which let's the user pick their own fee rate.

**Comment by gabrielbazan7** [comment]
@Pal0720 Take a look to the FAQ : https://github.com/bitpay/copay/wiki/COPAY---FAQ#copay-requires-high-fees-for-low-amounts-transactions
