### ISSUE TITLE
Paper wallet withdraw not showing

### ISSUE THREAD

**Issue by wcoyote** [bitpay/copay#6267]
I have tried twice to put funds from Copay on to a paper wallet and withdraw back to Copay.

Both times I see the funds available when I scan the barcode but when I (sweep) to return them to Copay they seem to vanish.

**Comment by JDonadio** [comment]
Please add some screenshot and explain a little bit the error (if it's shown) to understand what is happening. Also what version of Copay are you running?

**Comment by wcoyote** [comment]
When I scan the barcode the screen looks like:
----------------------------------------
<---- Sweep paper wallet     sweep
     Funds found:
         xxxx BTC
     funds will be transferred to:
Personal Wallet
------------------------------------------

Version is 3.5.0   I just down loaded it yesterday.

**Comment by wcoyote** [comment]
Well I see there is some delay funds transferring ... my error
