### ISSUE TITLE
Reopening an Old Issue #2230 and a few others.

### ISSUE THREAD

**Issue by lquessenberry** [bitpay/copay#6269]
I have an AES file for one of the signers on a copay wallet and a password that he gave me. I have tried getting this to open and it doesn't work. What do I need to do?

**Comment by JDonadio** [comment]
Copay doesn't support AES files.

**Comment by lquessenberry** [comment]
UMMM It used to.

**Comment by lquessenberry** [comment]
Thanks for the help. Can someone who knows a little more about this maybe try to help me out here rather than close the ticket and say something that doesn't make any sense?

**Comment by JDonadio** [comment]
Sry, my bad. I'm wondering how are you trying to decrypt the file? For mobile

**Comment by JDonadio** [comment]
Sry, my bad. How are you trying to use the backup ?

**Comment by JDonadio** [comment]
For mobile you have to paste the content (json format). For desktop or chrome-app you should import it.

**Comment by lquessenberry** [comment]
A while back a friend of mine and I created a wallet. It's from 2015 or so. I have the backup file for his wallet and his password, and I will probably have to remember how I accessed my wallet. I am not sure my machine still exists. Anyway, the wallet has 1.25 BTC in it and it's probably stuck. It used to say that the file was corrupt, but that was a long time ago. Now I am unsure what it says. Anyway, it does not import properly.

**Comment by lquessenberry** [comment]
This is the address: 35dXhsRXZKdRHw5GLnJ6hXVjAS9wPLhT86

The wallet was between Greg Darden and me.

**Comment by lquessenberry** [comment]
http://www.giphy.com/gifs/3oKIPcOrfCmT450LMk Here's what I get. I assume it's a bad password, but I have tried every iteration of that password I can think of.

**Comment by JDonadio** [comment]
Definitely is your password. Copay has not limit of tries so you can check it many times. We have no access to your wallet or funds, so unfortunately if you are no able to decrypt your backup you cannot get access to these coins.
