### ISSUE TITLE
Cannot Send money from other created wallets.

### ISSUE THREAD

**Issue by cjhighway** [bitpay/copay#6270]
Hi,

I created two additional bitpay wallet addresses besides the default one that I've given. The problem is that I can only receive bitcoin to those two additional addresses but cannot send FROM them. Is there a fix for this?

**Comment by gabrielbazan7** [comment]
Sorry, could you explain a little more your issue ?

**Comment by JDonadio** [comment]
@cjhighway do you see any error, button missing? please attach some screenshot so we can understand the issue.
