### ISSUE TITLE
Tabs setting is show when touching the edge of the screen(only in iOS)

### ISSUE THREAD

**Issue by hoatv** [bitpay/copay#6271]
Hi guys, I've got stuck in this trouble for 2 days and I haven't figured out. Hope to receive help from you by describing below:
Currently, i'm at Setting page
![img_1815](https://user-images.githubusercontent.com/16910823/27314528-bcd2d040-559e-11e7-8194-259ed9d00b3f.PNG)

And go to Address Book
![img_1816](https://user-images.githubusercontent.com/16910823/27324501-9bda0594-55cf-11e7-8897-32c163071d33.PNG)

Go back to Setting page by touching the edge of screen(not touch back button on navigation bar).
The trouble is Tabs at the bottom of screen is shows at the very first time I touch the edge of the screen.(this trouble is only on iOS)
![img_1817](https://user-images.githubusercontent.com/16910823/27325044-58f022f2-55d1-11e7-96f3-83bed022318a.jpg)

If I release my finger off the screen, the Tab is shows on Address Book page
![img_1818](https://user-images.githubusercontent.com/16910823/27325051-5cbeb5ec-55d1-11e7-8a6c-61735f576cff.jpg)

 Hope receive help from you!!

**Comment by matiu** [comment]
hello, that seems to be a fork of Copay, please refer to its developers.
