### ISSUE TITLE
Default fee is ignored?

### ISSUE THREAD

**Issue by jlauwers** [bitpay/copay#6272]
Hello,

My default fee is "super economy" and still when I first try to do a transaction, it shows "super economy" but with normal fee.
After a manual fee change from "super economy" to "super economy" it is correctly refreshed.

You can see the screen shot [here](https://imgur.com/a/ceNeD)

**Comment by matiu** [comment]
thanks for the report, we will check it and reply here. What version/platform are you using?

**Comment by jlauwers** [comment]
It's android V3.4.0 commit #39f974d

**Comment by jlauwers** [comment]
Just tested on windows V3.4.0 commit #39f974d and same issue.

**Comment by JDonadio** [comment]
@jlauwers thanks for report it. Please follow [this issue](https://github.com/bitpay/copay/issues/6250) to be updated.
