### ISSUE TITLE
lose bitcoin

### ISSUE THREAD

**Issue by bergkam** [bitpay/copay#6275]
2017 June 6 transferred 3 bitcoins to the purse of COPAY
Today I committed transaction 0.04 after which the balance was lost, what to do and where my bitcoins are?

**Comment by truikki** [comment]
I received 0.013 on june 13 and today after small transaction i lost all that amount. We have same problem i think pls fix this.

**Comment by parkermor** [comment]
@bergkam 
@truikki 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
