### ISSUE TITLE
Didnt get btc into my wallet

### ISSUE THREAD

**Issue by yushybushy** [bitpay/copay#6276]
So I bought some BTC from a BTC atm in my town using copay as my wallet but now after 3 hours i have [this](https://prnt.sc/fm40kx) screen when i open my wallet. So i recieved the BTC however my wallet is [empty](https://prnt.sc/fm41jq) and if i click recent transactions i get [this](https://prnt.sc/fm42bj). Anyone know whats the problem. 

Please help 

Cheers!

**Comment by anoain88** [comment]
I send btc to my wallet too. When i look last transactionen i see them but when i want to click there stand the same like you. And on my wallet there is nothing. I want my money

**Comment by truikki** [comment]
Something is wrong i lost my last received bitcoins after todays transaction

**Comment by JDonadio** [comment]
Was related to a restart on our server. Should be ok now.
