### ISSUE TITLE
#support Error: Transaction not available at this time

### ISSUE THREAD

**Issue by kublikhan** [bitpay/copay#6277]
Hi guys, I have received a transfer but when I click on it on the copay iphone app it says : Error: Transaction not available at this time and the funds are not in my account. Anyone knows what can I do? is this a bug? 
I am using the iphone app version v3.5.0

Really appreciate your help!!

Thanks

**Comment by anoain88** [comment]
Yes. Same shit at my copay app. A lot of money. But nothing aarived at my wallet same error at samsung app. What should i do

**Comment by bergkam** [comment]
Same shit iOS support weare you?

**Comment by yushybushy** [comment]
I have the same problem.

**Comment by bergkam** [comment]
Upgrade you wallet, it's ok

**Comment by truikki** [comment]
Yes received payment from week ago lost pls fix this

**Comment by anoain88** [comment]
How i upgrade my wallet?

**Comment by mjanez** [comment]
Same problem here with the Android app v3.4.0. The transaction was visible but when clicked on said Error: Transaction not available at this time and the amount wasn't added to the balance, now it completely disappeared.

**Comment by cmgustavo** [comment]
It 's a known issue, please upgrade to v3.5.

@anoain88 go to Play Store and update the app

**Comment by Courtneycash** [comment]
I sent money to my wallet but none of my coins appeared even though I received an email saying that my payment was received my balance on the copay app is still empty

**Comment by lacmonte** [comment]
My funds are showing up in my co-pay wallet but I can't send them anywhere I type in Bitcoin address and there's no send button that allows me to send ..I've used this wallet a dozen times this has never happened until the update on the July 5th I believe..can someone help me please?
