### ISSUE TITLE
Bitcoins showed up one day gone the next

### ISSUE THREAD

**Issue by overlord001** [bitpay/copay#6280]
Forgive me beforehand if this question sounds ignorant, I am a late comer for Bitcoin. I sent my first Bitcoins yesterday to my Copay wallet. Even though the transaction was at the unconfirmed stage, it still showed up in my wallet with all the info. Today when I checked all the info was gone and my wallet is zero. I did adjusted the network fee, so not sure if that has anything to do with it. Kindly advise, I am already turned down with the unconfirmed transaction part (yet, I understand in a way why) and now this. Thanks.

**Comment by JDonadio** [comment]
Was related to a restart on our server. Should be ok now.

**Comment by overlord001** [comment]
It's there again, thanks. Can you tell me how long does it take for the transaction to be confirmed? I earned those Bitcoins  from a PTC site and withdrew from it. I'm new to Bitcoin. Thanks.

**Comment by JDonadio** [comment]
In a common scenario the confirmation time basically depends on the how much fee are you sending in your transaction, but also can be delayed by the network itself. Using a high fee will reduce that time but if you are receiving the fee is set by the sender.

You can take a look at [this article](https://en.bitcoin.it/wiki/Transaction_fees) to understand a little how the fee works.
