### ISSUE TITLE
Testing in browser does not display anything on localhost:3000

### ISSUE THREAD

**Issue by stephane-rolland** [bitpay/copay#6282]
I wanted to test and explore the code of Copay. So I tried to run it in browsrer mode.

I'm using Ubuntu 14,  with browsers Chromium, Google Chrome, Firefox and Vivaldi. 
In any of these browser, when I run in /coplay directory:
    npm install
    npm start

I can see it's installed, and I have the message "App listening on port 3000".
But as soon as I look at the address: localhost:3000, there is nothing displayed at all.

I correctly have the browser tab decorated with the coplay icon, and "Copay - Multisignature wallet".
But except the browser tab label and icon... the page is blank.

Is it normal ?

This is the warnings I get when I run npm install:

```
me@mylaptop:~/src/copay$ npm install 
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN prefer global npm@2.15.12 should be installed with -g

> phantomjs@1.9.20 install /me/src/copay/node_modules/phantomjs
> node install.js

PhantomJS is previously installed at /me/src/copay/node_modules/phantomjs/lib/phantom/bin/phantomjs

> ws@0.4.32 install /me/src/copay/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/cloud/owncloud/src/copay/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: Leaving directory `/cloud/owncloud/src/copay/node_modules/ws/build'
npm WARN EPEERINVALID karma-jasmine@0.3.8 requires a peer of jasmine-core@* but none was installed.
me@mylaptop:~/src/copay$ npm start

> copay@1.8.2 start /me/src/copay
> node app.js

App listening on port 3000

```

**Comment by JDonadio** [comment]
The port is 8100

**Comment by stephane-rolland** [comment]
@JDonadio are you sure ?
When I try to browse the address localhost:8100 I have the error message: ERR_CONNECTION_REFUSED

And the Copay documentation makes it clear to access localhost:3000
It says:

> Testing in a Browser
> 
> Note: This method should only be used for development purposes. When running Copay in a normal browser environment, browser extensions and other malicious code might have access to internal data and private keys. For production use, see the latest official releases.
> Clone the repo and open the directory:
> 
> git clone https://github.com/bitpay/copay.git
> cd copay
> Ensure you have Node installed, then install and start Copay:
> 
> npm install
> npm start
> 

Visit localhost:3000 to view the app.

**Comment by JDonadio** [comment]
What version are you running?

**Comment by stephane-rolland** [comment]
Copay version Release v1.8.2
commit 8da0d3982ab029afb2a6f98fd644c7231817193b

**Comment by JDonadio** [comment]
It's an old version... why you do not run the latest?

**Comment by cmgustavo** [comment]
@stephane-rolland Hi, first that nothing, try `npm run apply:copay`. It will copy the complete `package.json`

Then: `npm start`

I hope to be helpful.

**Comment by stephane-rolland** [comment]
@JDonadio I cannot make it npm install without tons of error message. Lattest version that seems to install nicely is V 2.4.2, but same symptoms: localhost:3000 remains a blank page with only the tab icon showing copay icon. I'm gonna checkout some more recent version and test again.

**Comment by JDonadio** [comment]
Be sure to update your node/npm and cordova projects.

**Comment by gabrielbazan7** [comment]
I could run Copay without problem using: 
Node v6.10.3
Npm v3.10.10
Cordova v7.0.1

with this commands: 
npm run apply:copay 
npm start

And it shows on http://localhost:8100

**Comment by stephane-rolland** [comment]
For the moment after running updates I have:
node 5.0.0
npm 3.3.6
cordova 7.0.1

But I seem not to be able to update nodejs to v6.10.3. That may be the problem.

**Comment by gabrielbazan7** [comment]
Download it from the website https://nodejs.org/es/

**Comment by JDonadio** [comment]
Try with node 6+ and npm 3.10.x and should work

**Comment by gabrielbazan7** [comment]
@stephane-rolland Could you make it work ?

**Comment by stephane-rolland** [comment]
Not yet. I still get several error messages. I'll post them here, after some things I'm gonna try again.
