### ISSUE TITLE
MULTISIGN  WALLET BACK UP

### ISSUE THREAD

**Issue by altobajo33** [bitpay/copay#6300]
Good afetrnoon guys i need your help with the next issue , we have created a multisign wallet of 4 different devices and signs , one of the devices has been lost and we do not have the back up for that device or sign , i would like to know if its possible to move transfer those funds to other wallet without the back up of the device losted. or back itup with other method help me 1 of the 4 signs its not with back up

**Comment by JDonadio** [comment]
Hi @altobajo33, sorry for the delayed reply. If your wallet is 4 of 4 unfortunately your funds are inaccessible, the only way to get access is with the 4 backups. However if your wallet is x of 4 (x <=3) and you have the x backups, you can move your funds to another wallet.
