### ISSUE TITLE
Will i get my refund?

### ISSUE THREAD

**Issue by Trizub** [bitpay/copay#6301]
Hi i wonder. Will I get my refund if my wallet address is changed automatically?
I make refund invoice on address 3Ngn4h5gT7KoGp47J43WD9w9vv7jiHjUdU. And now address of Wallet is 36Tgn4KV5y7oCkrjhrmmSbwgNye1SapHCM. The address is changed automatically when i got payment  http://imgur.com/G3pwvOE
Link on screenshot of invoice http://imgur.com/yf2MkIJ

**Comment by JDonadio** [comment]
Please check http://help.bitpay.com/bitpay-secure-bitcoin-wallet/why-does-my-bitpay-wallets-bitcoin-address-keep-changing

**Comment by JDonadio** [comment]
You can check your addresses in settings > wallet > more opts > wallet addresses
