### ISSUE TITLE
New version - No more coins !!!

### ISSUE THREAD

**Issue by August777** [bitpay/copay#6302]
I have got a Win 10 mobile, using copay, but not every day. But this morning I tried and all was gone, just away and I should create a new wallet. 
for cases like this, I thought the 12 words should fix the problem, but no succsess, just "can not restore wallet", or "wrong code".
It is just all away!
How can I get my coins back?

Please help

**Comment by xpetrv** [comment]
I have **exactly the same experience** 
How can I get my coins back?

**Comment by matiu** [comment]
The 12 words is what you need to restore your wallet. Could you please share the exact message you get when entering the words?

Please note you can also use your recovery tool 
https://bitpay.github.io/copay-recovery/

to scan and transfer funds from a wallet, using the 12 words.

**Comment by xpetrv** [comment]
Actually as is written above, I can just to create new walet, no restore option. So now I have new clear wallet, not backed up yet with zero balance.
Should I try the restore tool on it?

**Comment by matiu** [comment]
You need to go to "import wallet" and enter the words

**Comment by xpetrv** [comment]
OK, imported and the balance is back, thx!

**Comment by August777** [comment]
ok, so we got different problems. 
I tried to 'import Wallet' , filled in the 12 words, and used the 'import' button.  Answer was:
 -Error: Import not possible. Wallet-Recoveryphrase is invalid.- 
(This is my translation from the German version.)
Second step, I used the 'extra options' filled in my keyword, got the same text.
 so, now I used the recovery-tool( from the link above), filled in the 12 words in the last line and the keyword in the line before, nothing else in the upper lines . ?
 -No data provided-

**Comment by matiu** [comment]
@xpetrv thanks for the update. I am glad it worked.

@August777 because of the first thing you mention ("Error: Import not possible. Wallet-Recoveryphrase is invalid") it seems there is an error on the words.  The words are from a predefined list. Could you check they are ok? The lists (depending on the language) are at: https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md

Note also that order is import, the words need to be on the same order they were provided.

**Comment by August777** [comment]
OK, that was it, just two letters changed, now all is back. thank you for your support.
Danke, thx

**Comment by matiu** [comment]
glad it worked. Thanks for the update.
