### ISSUE TITLE
back up

### ISSUE THREAD

**Issue by altobajo33** [bitpay/copay#6303]
Good afetrnoon guys i need your help with the next issue , we have created a multisign wallet of 4 different devices and signs , one of the devices has been lost and we do not have the back up for that device or sign , i would like to know if its possible to move transfer those funds to other wallet without the back up of the device losted. or back itup with other method help me 1 of the 4 signs its not with back up

**Comment by gabrielbazan7** [comment]
Hi! take a look to : http://help.bitpay.com/bitpay-secure-bitcoin-wallet/i-lost-my-wallet-or-changed-my-phone-what-can-i-do-to-restore-my-wallet

**Comment by altobajo33** [comment]
what if i had the security back up or phrases of 3 signs of multisig wallet i still lose my funds just beacuase one device its lost without a copy .

**Comment by JDonadio** [comment]
If your multisig wallet was created as x-of-4, being x the required signatures, you will be able to move your funds to another wallet if x <= 3 without problem.

**Comment by altobajo33** [comment]
i created a multisig wallet of 4-4 signs and copayers .now ,we do have acces to the multi wallet from 3 of the 4 devices shring this wallet working no problem. but one of the devices the fourth one its been losted without a back up,can we trnasfer the funds to other wallet?? this will calrify my doudts right away , thnask a lot.

**Comment by gabrielbazan7** [comment]
No, unfortunately, you can't.

**Comment by altobajo33** [comment]
so what does this comment means?
If your multisig wallet was created as x-of-4, being x the required signatures, you will be able to move your funds to another wallet if x <= 3 without problem.???

**Comment by gabrielbazan7** [comment]
Necesitas X firmas para poder mover tus fondos. En tu caso necesitas 4 firmas.
