### ISSUE TITLE
I FOUND MY WORDS BUT THERE IS A SPELLING MISTAKE IN ONE WORD HELP

### ISSUE THREAD

**Issue by Chloe1234512345** [bitpay/copay#6306]
HELP

**Comment by gabrielbazan7** [comment]
Hi! here is a list of the valid words : https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt

**Comment by parkermor** [comment]
@Chloe1234512345 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com

**Comment by richardsonn09** [comment]
@Chloe1234512345
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
