### ISSUE TITLE
The scan is not working

### ISSUE THREAD

**Issue by Jexowa** [bitpay/copay#6307]
When i want to scan something, there is no image, just a black screen. All other apps works with my camera but Copay displays me a blackscreen.
Here are some information about my phone and the app : 
App :
Copay v3.4.0
Commit hash #39f974d (idk what this is)
Phone : 
meizu m2 note
model : M571H
Android version : 5.1
Build Number : Flyme 637.4.11G beta

**Comment by JDonadio** [comment]
Hi @Jexowa, can you please check your session log in settings > about Copay and send it to my email: javier@bitpay.com? thanks!

**Comment by Jexowa** [comment]
hey, i don't know why but the scan is now working. The only change i've
done is putting the pin code and since that, the camera is working.
Thanks a lot for your fast answer. Good bye :)

2017-06-26 0:27 GMT+02:00 Javier Donadío <notifications@github.com>:
