### ISSUE TITLE
LOST 1 OF 4 SIGNATURES ON MULTISIG WALLET

### ISSUE THREAD

**Issue by altobajo33** [bitpay/copay#6308]
Good afetrnoon guys i need your help with the next issue , we have created a multisign wallet of 4 different devices and signs , one of the devices has been lost and we do not have the back up for that device or sign , i would like to know if its possible to move transfer those funds to other wallet without the back up of the device losted. or back itup with other method help me 1 of the 4 signs its not with back up

**Comment by gabrielbazan7** [comment]
I already answer you here https://github.com/bitpay/copay/issues/6303
