### ISSUE TITLE
Shared wallet not allowing me to send bitcoins

### ISSUE THREAD

**Issue by facuperez87** [bitpay/copay#6311]
Shared wallet not allowing me to send bitcoins...

We have a shared wallet 3 of 3 address: 3JeZTR8V8rj5GJpcFCPWTqWrkf5sUXo4eJ

All of us signed but the payment still there we deleted the operation and try to do it 3 times and theres no possible

**Comment by matiu** [comment]
Could you share an screenshot of the error you are getting?

**Comment by facuperez87** [comment]
Theres no error, the thing is that is not allowing me to sign it so they can send the payment... the button is not showing up
![img_1577](https://user-images.githubusercontent.com/29446720/27707217-1f3f947e-5cda-11e7-8807-148fae22d961.PNG)

**Comment by gabrielbazan7** [comment]
Hace falta la firma de un copayer más. Supongo que vos sos Facundo por tu nick name. Vos ya aprobaste la transacción y Diana también. Faltaría uno más ya que tu wallet es 3 de 3.

**Comment by facuperez87** [comment]
Ese es el tema! Las dos firmas son de los otros 2 copayers y ami no me deja firmar me figura como que ya he firmado...

**Comment by gabrielbazan7** [comment]
Pero quien es la tercera persona? Vos cuando creas la propuesta de pago la aceptas automáticamente.

**Comment by facuperez87** [comment]
Y porque no le acepta ? Ya todos le hemos enviado necesito sacar esos Bitcoins ayuda por favor

**Comment by gabrielbazan7** [comment]
Tenes que comunicarte con esa persona y decirle que firme la transacción

**Comment by facuperez87** [comment]
Ya la han firmado todos

**Comment by gabrielbazan7** [comment]
Puede esa persona mandar una screenshot de la propuesta de pago ?

**Comment by johnvamo** [comment]
HI,

I am having a problem too with a copay shared wallet integrated with Trezor...(2 signers) When We send the transaction....it gets stucked opening the trezor windows...It holds indefinately there....And the copay windows holds saying: Sending transaction...

Each cosigner experenced the same from each wallet...Trezor support tolds us that everything from there part is working. We use the trezor as usual with its own interface and works perfectly. 

Note: two weeks ago we made successfully a similar transaction...

Please we need urgent support...Thanks
