### ISSUE TITLE
Coinbase transfer to Copay wallet never arrived! 

### ISSUE THREAD

**Issue by misnomer83** [bitpay/copay#6312]
I transferred $400 in btc from coinbase to my Copay wallet. It is confirmed 7 times and much time has passed and it did not make it to my wallet. Here is the transaction hash:fb3f9bb883b3be3ec575347796bf2a63acc44a554075c0f4cc39cbf7615b3427

**Comment by matiu** [comment]
Could you check if the bitcoins are in your coinbase account? You may have to transfer them manually back to your wallet.

**Comment by JDonadio** [comment]
Already fixed in the latest release and will work for new purchases. Sorry about that.
For new reports or updates please follow [this thread](https://github.com/bitpay/copay/issues/6189). Thanks in advance.
