### ISSUE TITLE
Not able to install on Windows 10 32 bits

### ISSUE THREAD

**Issue by drhimura** [bitpay/copay#6313]
It tells me it is not compatible with my windows version

**Comment by cmgustavo** [comment]
32 or 64 bits?

**Comment by drhimura** [comment]
32

**Comment by JDonadio** [comment]
Hi @drhimura, we don't support 32 bits platforms. You can try with the [chrome-app](https://chrome.google.com/webstore/detail/copay/cnidaodnidkbaplmghlelgikaiejfhja?hl=es-419)

**Comment by JDonadio** [comment]
Yes, sure. But if you won't erase your disk maybe with the chrome extension you will be fine.

**Comment by drhimura** [comment]
thanks for the suggestion, w10 its my tablet OS, ill try on my desktop

**Comment by JDonadio** [comment]
If you have another question just let me know.
