### ISSUE TITLE
2-3 multisig can only log in as 1 copayer

### ISSUE THREAD

**Issue by LS1904** [bitpay/copay#6314]
I am new to this, and am lost.
I created a 2-3 multisig wallet on the windows app. I created the other two copayers on my mobile. I transfered a small amount of btc into the multisig wallet. I went to make a transfer to bittrex and did it from my pc. Went to approve on my mobile, and realized i was logged in as the same copayer on both pc and mobile. I see the other 2 names are mine, but after erasing the app data on android, i have no idea how to log on as anyone else besides 1 copayer that is still on pc. Any help appreciated. Thank you

**Comment by gabrielbazan7** [comment]
Hi! each of those copayers have his own 12 words. You have the words ?

**Comment by LS1904** [comment]
I wrote down 4 different 12 word keys
Apparently, i made a personal wallet for what i thought was each account. I only have 1 key for the multisig account written down. The other 3 are for single signature wallets. I think i may have made a bad mistake. Is there anything i can do with wallet id or extended public keys? All the co payer names are the ones that i wrote down with the other 12 word keys, but when i put the keys in it only brings up the personal wallet until i put in the 1 key have for the 2-3 wallet

**Comment by gabrielbazan7** [comment]
When you create a shared wallet, you get an invitation, this invitation needs to be shared with the 
 other devices to join the shared wallet. You made that steps ?
<img width="395" alt="bitpay_-_secure_bitcoin_wallet_and_2-3_multisig_can_only_log_in_as_1_copayer_ _issue__6314_ _bitpay_copay" src="https://user-images.githubusercontent.com/10999037/27588352-44581abe-5b1e-11e7-89f9-5669630067c9.png">
<img width="395" alt="bitpay_-_secure_bitcoin_wallet" src="https://user-images.githubusercontent.com/10999037/27588381-55d65b0c-5b1e-11e7-9c8f-72cee0ec9923.png">

**Comment by LS1904** [comment]
When i created the wallet, yes. I sent the invitation to mobile and joined shared wallet. Then i erased app data on android and did it again with another name. I can see the other two copayers in my the 2-3 wallet options and they are both my names, i just do not know how to log into those now.... is there a different 12 word key that i forgot to write down?

**Comment by JDonadio** [comment]
I suggest watch this great video about shared wallets: https://www.youtube.com/watch?v=PJQmbA3j7yo

**Comment by gabrielbazan7** [comment]
Yes, each of that copayers have 12 words

**Comment by LS1904** [comment]
I watched the video. I remember putting in the nicknames. I can see the nicknames that i put in as copayers. When i put in the 12 word keys for what i thought were these nicknames, it brings up the personal wallets and not the shared one.  
My question is, what can i do to get back onto the co payers side of the 2-3 wallet

**Comment by gabrielbazan7** [comment]
You can't, unfortunately. The only way to have access to your funds is with the words.

**Comment by LS1904** [comment]
Okay, let's say i erase all the data from app and start over fresh. I go to import wallet. Are you saying that there are 3 different 12 word keys for the shared wallet?

**Comment by JDonadio** [comment]
You have the next scenario:

Create shared wallet > Wallet 3-3, name A, create wallet. A ready and listening for copayers to join. At this point, you only have one wallet and one backup (12 words) for it.

* **From another device**: go to join shared wallet, scan/paste the invitation code from A to join. Now you have the wallet B and another backup for it.

* Same for the third wallet C.

So you will have 3 different wallet with 3 different backups for each one.

Note: if you lose any backup you will not be able to access to your funds.

**Comment by LS1904** [comment]
so basically, i fucked myself and my funds are gone....

**Comment by JDonadio** [comment]
Sorry but there is nothing to do in this case. If your wallet was 2-3 you might transfer the funds because you only need 2 signs...
