### ISSUE TITLE
Buenos dias perdi mi cartera

### ISSUE THREAD

**Issue by lopo0000** [bitpay/copay#6315]
tengo la aplicacion de copay instalada en mi telefono y sin motivo alguno la aplicacion se reinicio tengo mi respaldo de 12 palabras para respaldo y me dice que es incorrecto ya es la 2da vez que me pasa esto como puedo recuperar mi cuenta? gracias de antemano

**Comment by JDonadio** [comment]
Buenos días, si tuviste algún problema con tu wallet puedes recuperarla con tu backup (12 palabras). Ahora, si no lo hiciste de manera correcta, es decir si alguna palabra está mal escrita o algo por el estilo no podrás recuperarla. Si tus palabras están en español te sugiero que verifiques los acentos porque generan conflictos (intenta no usar acentos) y decime si funciona. De todos modos aqui está una lista completa de las posibles palabras en español: https://github.com/bitcoin/bips/blob/master/bip-0039/spanish.txt

**Comment by lopo0000** [comment]
jdonadio las palabras estan en ingles, pero aun asi me dice incorrecto podrias por favor pasarme la gui de las palabras en españo muchas gracias

**Comment by JDonadio** [comment]
La que te pasé es español, aquí está en inglés:

https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt

**Comment by lopo0000** [comment]
jdonadio muchas gracias ya pude resolver el problema estaba creo que en mi coneccion de datos y se reinicio la app por q hubo una actualizacion mil gracias saludos

**Comment by JDonadio** [comment]
Bien! 👍

**Comment by kamiski** [comment]
Me podrian ayudar....se me daño mi telefono y al iniciar en mi nuevo celular con las 12 palabras me aparece la billetera personal pero se me desaparecio una billetera compartida q tenia

**Comment by kamiski** [comment]
Y necesito utilizar los fondos que tengo alli....como puedo hacer para q me aparezca la compartida? Gracias

**Comment by BGalliotti** [comment]
Hola @kamiski,

Debe realizar el mismo procedimiento que realizo para su billetera.
Importando la billetera compartida, aparecera en su telefono.

Tenga en cuenta que si por ejemplo, la billetera es una 3-2 (3 usuarios, 2 firmas), requerira que los tres diferentes usuarios la tengan instalada y que al menos dos aprueben la transaccion.

Cada una de las billeteras tiene su propio juego de doce palabras. 

Saludos cordiales.
