### ISSUE TITLE
Can't extract anything from backup file

### ISSUE THREAD

**Issue by dansator** [bitpay/copay#6317]
I export my wallet to a .json file.

Open the page suggested here: https://bitwiseshiftleft.github.io/sjcl/demo/ 
Fill everything according to data in .json (initialization vector, 10000 iterations, salt, ciphertext, password etc).

First press on "Decrypt" arrow generates a key leaving "Plaintext" section empty.
Second press popups a message "Can't decrypt: CORRUPT: ccm: tag doesn't match".
Nothing appears in "Plaintext".

What I'm doing wrong?

Tried both bitpay/copay latest versions.

**Comment by JDonadio** [comment]
Your json file exported should be pasted as plain text in `Ciphertext` field, and fill the password field as well and click on `Decrypt`.

**Comment by dansator** [comment]
That worked, thanks. Though don't see logic in this.
