### ISSUE TITLE
transfer from coinbase account to copay did not come in. sendersaccount says pending

### ISSUE THREAD

**Issue by newbcurrency** [bitpay/copay#6318]
Hi, earlier this evening I had my wife send bitcoin from her coinbase wallet to my copay wallet and I never received the payment. Her account shows the payment pending and funds were taken. it also shows 0 confirmations. How long will this take to come into my account. Also, she scanned the address from my copay app directly from her coinbase app. Please Help as my name suggest I am new to this but I am sure I did everything correct. As I have transffered from my coinbase account to my copay account in the past without a problem.

**Comment by JDonadio** [comment]
Hi @newbcurrency, the transaction was built from the Coinbase end, you should contact the Coinbase support team and ask for your pending transaction.

**Comment by newbcurrency** [comment]
Ty

On Jun 28, 2017 9:19 AM, "Javier Donadío" <notifications@github.com> wrote:

Hi @newbcurrency <https://github.com/newbcurrency>, the transaction was
built from the Coinbase end, you should contact the Coinbase support team
and ask for your pending transaction.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bitpay/copay/issues/6318#issuecomment-311657550>, or mute
the thread
