### ISSUE TITLE
copay on google chrome app sign in options

### ISSUE THREAD

**Issue by newbcurrency** [bitpay/copay#6319]
I just dowloaded the app on my desktop and the only option to sign into copay is to enter my backup phrase or create a whole new wallet. Is entering my 12 word phrase the only wy to access my account through the desktop app?

**Comment by Kirvx** [comment]
Yes :thumbsup:

**Comment by JDonadio** [comment]
In order to access to your funds in your wallet you must import it from any device using any backup format:

* 12 words
* file/text
* QR code
