### ISSUE TITLE
Sign macOS binaries

### ISSUE THREAD

**Issue by yangm97** [bitpay/copay#6320]
By default, macOS will not run unsigned binaries.

![screen shot 2017-06-28 at 01 51 49](https://user-images.githubusercontent.com/4412002/27621038-6a150ee8-5ba4-11e7-8de8-f0f6da3272a9.png)
![screen shot 2017-06-28 at 01 51 02](https://user-images.githubusercontent.com/4412002/27621039-6a94d2a4-5ba4-11e7-8bb6-4ed395649337.png)

**Comment by balupton** [comment]
Did this get implemented?
