### ISSUE TITLE
Amazing fees

### ISSUE THREAD

**Issue by christianfanego** [bitpay/copay#6324]
I transfer 0.0001118826 BTC from muy argentine exchange called ripio. I must pay 0.0008028 in commisions to copay.
I need an explanation adaptador.
Regates
Christian

**Comment by gabrielbazan7** [comment]
Copay no cobra comisiones por transacciones entrantes.

**Comment by christianfanego** [comment]
Y entonces quien me cobro esa comisión?

**Comment by gabrielbazan7** [comment]
Seguramente Ripio. Pero no estaría mal. Las transacciones Bitcoin son gratis para recibir, pero al enviar hay que pagar una comisión que es para la red bitcoin, esta comisión ayuda a que tu transacción se confirme.

**Comment by christianfanego** [comment]
Ripio me dijo que no me cobraron ninguna comisión, que me la cobro la red BTC. Q la comisión no siempre es fija. La respuesta fue q los fees del envío no están relacionados al monto del envío, sino al tamaño de la transacción, es decir la cantidad de Outputs e inputs que tiene dicha transacción, y no con el monto.
Si me pudieran aclarar el tema les agradecería.
Saludos

**Comment by gabrielbazan7** [comment]
Si. Tal cual te explicaron. Hay mucha documentación y videos circulando por la web que hacen referencia a ese tema. Te paso algunos... https://bitcoin.org/en/faq#how-much-will-the-transaction-fee-be  https://www.youtube.com/watch?v=nh5H59HyqAM . 

Saludos!
