### ISSUE TITLE
Getting redeem script from copay

### ISSUE THREAD

**Issue by papcoin** [bitpay/copay#6329]
Dear team,

since there are some company asking to proof ownership on one of my copay address by providing redeem script (p2sh address)

how do i get this information from the wallet?
is it dangerous if i give redeem script?

**Comment by kannix** [comment]
need that too for the stellar lumen giveaway :)

**Comment by MuhammedZakir** [comment]
AFAIK, you can't get redeemScript from Copay. When sending Bitcoin from a multisig address, your redeemScript is included in transaction. You can find your redeem script from a transaction using `https://webbtc.com/tx/txid.json` (replace 'txid' with txid of a transaction to your multisig address).

If you want to prove ownership of a multisig address, you have to either send Bitcoin from it to a specified address or sign messages with addresses corresponding to public keys used to create your address. Signed messages from 2 addresses are required for 2-of-n wallet, 3, if 3-of-n and so on. You can find which addresses are needed to sign using https://coinb.in/#verify.

If you want to sign messages with m-of-n addresses of your multisig address, read `https://bitcointalk.org/index.php?topic=1989369.msg19853098#msg19853098`. What is different in steps for Copay is that in Electrum, all 2 of your xPrv will in the file. For Copay, you have to export for each multisig wallet. Unless you know what you are doing, I deprecate doing it!

If you are doing it just for a giveaway, why don't you create a new address and send it to your wallet once you get Bitcoin?

E.g. https://webbtc.com/tx/eeab3ef6cbea5f812b1bb8b8270a163b781eb7cde10ae5a7d8a3f452a57dca93.json

https://coinb.in/?verify=524104a882d414e478039cd5b52a92ffb13dd5e6bd4515497439dffd691a0f12af9575fa349b5694ed3155b136f09e63975a1700c9f4d4df849323dac06cf3bd6458cd41046ce31db9bdd543e72fe3039a1f1c047dab87037c36a669ff90e28da1848f640de68c2fe913d363a51154a0c62d7adea1b822d05035077418267b1a1379790187410411ffd36c70776538d079fbae117dc38effafb33304af83ce4894589747aee1ef992f63280567f52f5ba870678b4ab4ff6c8ea600bd217870a8b4f1f09f3a8e8353ae

**Comment by Mikadily** [comment]
I figured it out.

To get redeem script you need a outgoing transaction from your multisig account. Look at the it's inputs on the blockchain.info

![image](https://user-images.githubusercontent.com/2736855/27773445-752aa572-5f82-11e7-8b56-378659e75f38.png)

The 3rd line starting "522" is normally your redeem script.

Enter your address and redeem script into stellar form, it will ask you to sign a message with certain addresses (multiple of them).

Type in mnemonic from all of required accounts into https://iancoleman.github.io/bip39/ - choose 12 word seed - what's normally required for Copay.
Pick required address from the list, copy it's private key.

![image](https://user-images.githubusercontent.com/2736855/27773489-6d77159e-5f83-11e7-9cae-fd2f1f6eb282.png)

Get https://github.com/weex/bitcoin-signature-tool
And sign stellar message with previously acquired private key.

![image](https://user-images.githubusercontent.com/2736855/27773481-4e0ff054-5f83-11e7-8b49-bd11a2d0a5cd.png)

Type in the signed message into stellar and repeat for the rest of addresses, don't forget spaces between signed messages.

If you find this useful - feel free to drop a tip: 1AZ8NvqELUsJAYHgXM1Di1PcjjZRiFHgiH

**Comment by kannix** [comment]
@Mikadily thx for that info.. worked like a charm for my first copay wallet... 

however my second one doesnt work. None of the possible signing addresses gets listet in the derived addresses section.. do you have any idea how to solve that?

It is a 2-4 wallet and i tried both of my currently accessable keys :(
generating more addresses didn't help and is unlikely a solution because that wallet was only used for one initial incomming transaction + two outgoing transactions..

the generated Account Extended Public Key matches the one displayed in copay..

**Comment by Mikadily** [comment]
Not sure I can help. The possible problems from what you described:
- when was the wallet created? Maybe it's old and copay was using something else than bip44
- two outgoing tx sounds suspicious (did you mean two outputs?). Copay should have automatically sent your balance to change address. Are you sure address was loaded during distribution - June 26th?

**Comment by kannix** [comment]
i've created both wallets at the same day with the same devices and settings..

i meant transfer instead of transaction.. to clarify: i've sent some initial bitcoins to it and used it only for two payments after that...

the address was loaded... the stellar giveaway form checks that before it moves to the "sign the message" step

**Comment by Mikadily** [comment]
@kannix, weird. I'm afraid it's beyond limits of my competence.

**Comment by kannix** [comment]
![image](https://user-images.githubusercontent.com/1192084/29236411-e11069d4-7f12-11e7-99c2-f2adec98b7bd.png)

I finally found my mistake.. my first wallet had just one initial transaction so everything worked without any problems.. the second one was used for a few transactions and i had to change the "External / Internal" setting to 1 in this tool https://iancoleman.github.io/bip39/ now it worked like a charm.. maybe this info is helpful for someone ;)
