### ISSUE TITLE
Amazon Gift Card Malfunction

### ISSUE THREAD

**Issue by sheldonmwaters** [bitpay/copay#6335]
When I try to purchase an Amazon Gift Card, the transaction goes and the amount is locked in my account.  There is an error message, that I get the error message "Could not send transaction http request error" and the transaction never enters the blockchain.  I have used this feature successfully before;  this has only started occurring in the last two weeks.

**Comment by JDonadio** [comment]
Sorry for the delayed reply. Probably was caused by the network congestion, did you tried again?

**Comment by sheldonmwaters** [comment]
Several times and it still does it.

*Sheldon M. Waters*
sheldon.m.waters@gmail.com
www.linkedin.com/SheldonWaters

**Comment by JDonadio** [comment]
Can you provide an address of your wallet so we can check your wallet status?

**Comment by sheldonmwaters** [comment]
Is that the wallet id?

Sheldon M. Waters
sheldon.m.waters@gmail.com
www.linkedin.com/SheldonWaters

**Comment by JDonadio** [comment]
I can use it too.

**Comment by sheldonmwaters** [comment]
154C2wkobPJmaWTxaNnGNQmUHoeUESrwri

Sheldon M. Waters
sheldon.m.waters@gmail.com
www.linkedin.com/SheldonWaters

**Comment by JDonadio** [comment]
Ok, the problem here is that your wallet have a lot of small inputs. Can you try to consolidate in just one using the send max option?

Note that could require a high fee. To understand about the fees: https://github.com/bitpay/copay/wiki/COPAY---FAQ#copay-requires-high-fees-for-low-amounts-transactions

**Comment by sheldonmwaters** [comment]
This is how it is delivered from my miner.  

Sheldon M. Waters
sheldon.m.waters@gmail.com
www.linkedin.com/SheldonWaters

**Comment by gabrielbazan7** [comment]
try using the sendmax option. That way you will have an idea of your usable balance.

**Comment by sheldonmwaters** [comment]
I don't have a sendmax option on my miner.  Is this a copay option?


*Sheldon M. Waters*
sheldon.m.waters@gmail.com
www.linkedin.com/SheldonWaters

**Comment by JDonadio** [comment]
> Is this a copay option?

Yes

**Comment by JDonadio** [comment]
![copay_-_copay_bitcoin_wallet](https://user-images.githubusercontent.com/13851807/28417260-cf6db2a0-6d2d-11e7-8876-b8f681748277.png)

**Comment by sheldonmwaters** [comment]
I did get a card to purchase yesterday, but now it is not showing up under my cards to add to my Amazon account.  How do I either get the number or get the refund on the non credited amount?

Sheldon M. Waters
sheldon.m.waters@gmail.com
www.linkedin.com/SheldonWaters

**Comment by JDonadio** [comment]
There is an error or simply it doesn't appear ? Can you attach an screenshot ?

**Comment by sheldonmwaters** [comment]
Sheldon M. Waters
sheldon.m.waters@gmail.com
www.linkedin.com/SheldonWaters

**Comment by sheldonmwaters** [comment]
It has been 7 days and the gift card does not show up in my account.  It has been deducted from my account. What gives?

Sheldon M. Waters
sheldon.m.waters@gmail.com
www.linkedin.com/SheldonWaters

**Comment by JDonadio** [comment]
Please contact to help@bitpay.com to get better assistance.
