### ISSUE TITLE
Unable to sign payment

### ISSUE THREAD

**Issue by abrkn** [bitpay/copay#6342]
I click "Click to send":

![image](https://user-images.githubusercontent.com/843958/27750918-ca45438c-5d8e-11e7-92ba-5cf442472e03.png)

Trezor passphrase entry shows up, which I complete. Confirmation prompt shows up on Trezor with correct address. I click "Confirm". Trezor shows "Signing transaction..." and then shows home screen.

Then:

![image](https://user-images.githubusercontent.com/843958/27750978-08bd1608-5d8f-11e7-8c70-08f2006c63ae.png)

- Multisig wallet (2-of-4)
- Proposal created by myself and signed by another
- Copay chrome app, v3.6.2 (macOS Sierra)
- Signing with Trezor (firmware v1.5.0)

I have tried unplugging the Trezor and rebooting my computer.

Copay log:

```
Requesting Trezor  to sign the transaction
Trezor signing multi-sig p2sh. Account: null
Trezor TX input path: m/0/*
Trezor TX input path: m/0/*
Trezor TX change path: m/1/*
Signing with TREZOR [{"address_n":[**************"],"m":2}}]
ongoingProcess signingTx null
statusChangeHandler:  signingTx undefined null
sign error:Failed to compile output
Got action for wallet 4**********
Updating wallet:RZ Subscribers
Updating Status: RZ Subscribers null
Unknown error type: The payment was created but could not be completed. Please try again from home screen
Error: Could not send payment: The payment was created but could not be completed. Please try again from home screen
Status update. hash:51******** Try:0
```

I have replaced possibly sensitive information with `*`

**Comment by abrkn** [comment]
I've solved the issue.

I have several m-of-n wallets with the same m, n, and signers. The account numbers I use are different for each wallet so that the xpubs do not collide. After reinstalling Copay, the order in which you import these shared wallets appears matter. In my first attempt, the incorrect wallet was imported. I assume this is a bug with either Copay, BWS or both.

**Comment by matiu** [comment]
Jfyi,

I think this is related to a recently fixed bug,  when importing HW wallets
with account number >1. Probably you are now using the currenr version,
with the fix. The order should not matter.
