### ISSUE TITLE
How can I recover the wallet when I lost my phone?

### ISSUE THREAD

**Issue by pupupapa** [bitpay/copay#6343]
I am using the copay wallet on my iPhone and I'm a bit worried about wallet recovery. How should I recover my wallet with a new phone and copay wallet app? I can't find any 'recovery' function in the wallet app.

**Comment by MuhammedZakir** [comment]
To recover funds from a Copay wallet, you must either have a seed(12 words) or text/file backup. You can use https://github.com/bitpay/copay-recovery to recover wallet if Copay is not available anymore or if you don't want to use it anymore. If you want to recover wallet with Copay, click "Add Wallet" -> "Import Wallet" and type seed(12 words) or backup text/file & password. You can create a new wallet and test it out.
