### ISSUE TITLE
Sweeping paper wallet into copay

### ISSUE THREAD

**Issue by sg19point3** [bitpay/copay#6345]
Have been trying for 2 days to transfer my paper wallet into copay by sweeping. After scan of private key the app is sweeping for hours. Sometimes stops but nothing happends. No funds transfered, ballance ia still 0. Waitfor hours more and nothing. Set priority or urget fee structure...wait for hours ...nothing ...

**Comment by zuardi** [comment]
Same problem here, Bitpay and copay.

**Comment by gabrielbazan7** [comment]
I will check! Thanks for the report

**Comment by JDonadio** [comment]
Please, reproduce the error and check your session log at settings > about copay > session log, and send it to javier@bitpay.com. Thanks!

**Comment by gabrielbazan7** [comment]
I found an issue. I'm sending a pull request, sorry about that.

**Comment by zuardi** [comment]
I`m so sorry but at this moment I don’t have any paper wallet to sweep anymore.
Can I help in any other way?

**Comment by sg19point3** [comment]
Well that is because after a day and a half of trying to do all kinds of stuff I installed Mycelium and had it done in half hour. I deleted Copay off my phone

Marko Moudrak
