### ISSUE TITLE
Address change but payment sent.

### ISSUE THREAD

**Issue by rarcntv** [bitpay/copay#6346]
Address change. But can I still get payment using that address? where I already earned money in the given address? if someone send money to the previous address. should I receive the fund?

**Comment by MuhammedZakir** [comment]
Yes.

**Comment by rarcntv** [comment]
Thanks for the info

**Comment by gabrielbazan7** [comment]
Hi ! If you have more doubts take a look to the help center https://support.bitpay.com/hc/en-us/categories/115000745946-BitPay-Secure-Bitcoin-Wallet
