### ISSUE TITLE
compile  with npm run apply:copay

### ISSUE THREAD

**Issue by zhy0313** [bitpay/copay#6350]
Failed to restore plugin "com.verso.cordova.clipboard" from config.xml. You might need to try adding it again. Error: Error: Cannot find module 'big-integer'

**Comment by gabrielbazan7** [comment]
It's working for me, try with this: `npm run clean-all && npm run apply:bitpay` with `cordova 7.0.1 ` `node v6.10.3`and `npm 3.10.10` ?

**Comment by zhy0313** [comment]
According to your compilation, everything is fine. Thank you very much。
