### ISSUE TITLE
Ledger 24 Word Seed Import Failure

### ISSUE THREAD

**Issue by praeluceo** [bitpay/copay#6354]
When verifying that my Ledger Nano S truly is configured correctly and that I accurately copied my seed, I enter the recovery phrase into Copay, enter the passphrase from the Ledger, check the "From Hardware Wallet: Ledger Hardware Wallet" box, and click on Import, but I get the error popup, "Could not import: Wallet Recovery Phrase is invalid."

Attempting the same recovery in Mycelium worked as expected.

**Comment by matiu** [comment]
It this is a multisig wallet? We only support Ledger multisig.

**Comment by ericlimpens** [comment]
The same here. I get this popup also while using the Copay wallet on a mac. I can not import my ledger wallet. I know my recovery phrase is 100%. I even made a new wallet with the same result. All 24 words are correct, but still..

**Comment by parkermor** [comment]
@praeluceo 
@ericlimpens 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com

**Comment by matiu** [comment]
@parkermor please stop spamming or you will be blocked.
