### ISSUE TITLE
Ungefragtes update lässt alle Wallet verschwinden 

### ISSUE THREAD

**Issue by Schoepi** [bitpay/copay#6355]
Als ich die Copay App nach ein paar Tagen wieder öffnen wollte, war "ungefragt" ein update durchgeführt worden. Beim Starten wurden dann gutgemeinte Warnungen gelistet. Aber kein Wort darüber verloren, dass die Wallets mit samt den Adressen weg sind und nicht übernommen werden.
Dieses Vorgehen ist eine Zumutung für alle Benutzer. Nicht nur dass nun einige ihre Bitcoins definitiv verloren haben. Auch diejenigen welche die Passphrase gesichert haben, werden die Passphrasen, hoffentlich, kaum mit auf die Reise nehmen und stehen beim shoppen od. einem Restaurantbesuch sau blöd vor der Kasse.
Ich bin äusserst verärgert über dieses vorgehen.

**Comment by matiu** [comment]
Sorry, we only support English and spanish.

**Comment by Schoepi** [comment]
Google translate.
When I wanted to open the Copay app after a few days again, "unasked" an update had been carried out. At the start, then well-meaning warnings were listed. But not a word about that the Wallets with the addresses are gone and are not taken over.
This procedure is an impertinence for all users. Not just that some have definitely lost their bitcoins. Even those who have secured the passphrase will pass the passphrases, hopefully, barely with the trip and are at the shop or a restaurant visit sau blöd (very very stupid) before the cash desk.
I am very annoyed at this.
There is no excuse or apology. If you make a update you have to be sure, you do not los any data. to everytime.
If this not possible, then you have to explan bevor.
I am so very angry to you.
