### ISSUE TITLE
In Russian lang buttons "Ok" and "Cancel" when adding memo for a tx are on wrong places

### ISSUE THREAD

**Issue by RussianSwiss** [bitpay/copay#6356]
In Russian language buttons "Ok" and "Cancel" when adding memo for a tx are on wrong places. And don't use upper case please! "ХОРОШО" is wrong. "Ok" (always used in Russian localizations everywhere) or "Сохранить" (save) сan be used.

Use "Ok" and "Отмена".

**Comment by gabrielbazan7** [comment]
I will be fix on the next release. Thanks !

**Comment by JDonadio** [comment]
Should be working ok now.
