### ISSUE TITLE
100% cpu usage on osx after the app was open for some days

### ISSUE THREAD

**Issue by matiu** [bitpay/copay#6357]

**Comment by lacmonte** [comment]
Can you please help me my co pay wallet shows my coins. It won't let me transfer them out of the wallet I type in Bitcoin address and there no "send" or "verify" forgot the exact word to send that address and proceed to next step it just lets me type the address in the caption box and then nothing ..my wallet was working fine last week I get the update and now it's not working ..can someone please help me?

**Comment by JDonadio** [comment]
@lacmonte https://github.com/bitpay/copay/issues/6390
