### ISSUE TITLE
ios create personal wallet  is error when it modify 'wall service url'

### ISSUE THREAD

**Issue by zhy0313** [bitpay/copay#6364]
ios create personal wallet  is error when it modify 'wall service url'  and it is ok in the android.
![image](https://user-images.githubusercontent.com/16641437/27897565-ad080452-6253-11e7-8575-9604483a265a.png)

**Comment by gabrielbazan7** [comment]
I will check

**Comment by zhy0313** [comment]
Looking forward to your reply

**Comment by JDonadio** [comment]
You are setting your own bws instance and seems like is something wrong in it. Check your url, port, and also the logs.

In the meantime try with port: 3232

**Comment by gabrielbazan7** [comment]
thanks for the report. I could reproduce the error.

**Comment by zhy0313** [comment]
Thank you very much for the solution to this problem or which branch has been modified

**Comment by JDonadio** [comment]
@zhy0313 if are you running your own bws, you must have running a `mongod`
