### ISSUE TITLE
Error is not translate

### ISSUE THREAD

**Issue by gabrielbazan7** [bitpay/copay#6368]
When sweeping paper wallet and passphare is incorrect

![slack_-_bitpay](https://user-images.githubusercontent.com/10999037/27914589-10f6cd46-623a-11e7-89ea-1eb4040837c7.png)

**Comment by johnjoe91** [comment]
Hi ! 
My copay app has switched completely over to Mandarin, and I do not know how to switch back to English. could someone please give me a hand via screen shots of which icon to click to go back to all English? I started with the settings tab, but from there its all Mandarin

**Comment by JDonadio** [comment]
![bitpay_-_secure_bitcoin_wallet](https://user-images.githubusercontent.com/13851807/28118167-74130e02-66e6-11e7-8188-989f3f3535c3.png)

**Comment by johnjoe91** [comment]
Thanks very much!
