### ISSUE TITLE
Bought €1000 worth of bitcoins and I'm still waiting on confirmation

### ISSUE THREAD

**Issue by tahsinipekci** [bitpay/copay#6369]
How long does it take to see my bitcoins in my wallet? I'm now waiting an hout and A half.

**Comment by gabrielbazan7** [comment]
Immediately. You should see it confirmed or pending to confirmation. Could you explain a little more your issue?

**Comment by tahsinipekci** [comment]
Hi Gabrielbazan. I've just recieved my bitcoins. So never mind. Thanks for commenting anyway
