### ISSUE TITLE
Stuck unsent transaction

### ISSUE THREAD

**Issue by notimethanks** [bitpay/copay#6370]
I have a stuck payment proposal that has all my coins locked.  I tried uninstalling the app and using my recovery words but the unsent transaction remains.  When i try to send it the blue "swipe to send" bar disappears.  If I'm quick I can swipe it before it vanishes, but it throws me a "could not send payment: Server response could not be verified" error.

![The error](https://user-images.githubusercontent.com/7215254/27925760-eb02e3d0-6253-11e7-9d49-d4163b722633.png)

![Wallet view](https://user-images.githubusercontent.com/7215254/27925783-f9114796-6253-11e7-8b9d-2841acba8ed3.png)

![before slide to spend vanishes](https://user-images.githubusercontent.com/7215254/27925789-01a32794-6254-11e7-9d53-6ecdd60ac622.png)

![after it vanishes. it happens very quickly](https://user-images.githubusercontent.com/7215254/27925815-15530674-6254-11e7-9193-fdff74ea3ab2.png)

**Comment by JDonadio** [comment]
Try deleting the proposal and creating a new one.

**Comment by notimethanks** [comment]
How do you delete a proposal?  Can't seem to find a way.

**Comment by JDonadio** [comment]
![copay_-_copay_bitcoin_wallet](https://user-images.githubusercontent.com/13851807/27926960-9438d034-6260-11e7-9f6e-a19f05faba63.png)

**Comment by notimethanks** [comment]
Sorry we must be using different apps. Mine doesn't have that option.  Which one is that?  Maybe I can recover into that one and delete it.  I'm using the Android bitpay wallet.

**Comment by notimethanks** [comment]
Whoops, found it.  Thanks.
