### ISSUE TITLE
The terms of use are cut off

### ISSUE THREAD

**Issue by Pixlers** [bitpay/copay#6371]
On smaller iPhones like the iPhone SE the terms of use are cut off at the end while registration process.

Here a screen shot (cut off after »we reserve …«)
https://www.dropbox.com/s/oi98t4ke3nj0hyj/Datei%2006.07.17%2C%2022%2053%2052.png?dl=0

**Comment by JDonadio** [comment]
Thank you very much for your report!. We will fix it ASAP.
