### ISSUE TITLE
Incorrect Balance and/or TX amount display

### ISSUE THREAD

**Issue by hortonelectric** [bitpay/copay#6372]
## One (and the most important) ROOT of the issue
Copay does not perform address lookahead for change addresses, so if you send using another app, and that app generates change address 4, Copay will still only be looking at change addresses up to 3, and see the new transaction and assume change address 4 is not your address because it hasn't generated it yet.

(Copay only generates change addresses when IT is the app that performs the sending)

IMO there should be a one address lookahead window for change addresses just for this use case of "sent from other wallet, want that properly displayed on Copay as well"

## Another fold in the plot: possible race condition, or other weirdness.
Sometimes, the BALANCE is wrong, sometimes it is right. But in both cases the transaction amounts are wrong because of the lack of change look-ahead. The real question is how did the balance become correct?

Take this example: I added my wallet to a BWS server, and it sync'd up like this (WRONG balance, WRONG transaction amount, -29.9993 was actually just -2 BTC):
![photo_2017-07-07_12-04-44](https://user-images.githubusercontent.com/1389381/27942808-9de8f6f2-630c-11e7-9ef9-c8282df85193.jpg)

then I added the same xpub to another BWS server and it sync'd up like this (CORRECT balance, STILL WRONG transaction amount):
![photo_2017-07-07_12-04-36](https://user-images.githubusercontent.com/1389381/27942809-a2dec5a6-630c-11e7-9cae-77fff8232926.jpg)

## Yet another weird thing. 
Address 0 is used, but change address 0 is NOT used... Same issue occurs.
YES THERE ARE times when there is NO CHANGE for a transaction (outputs+fee equal exactly the amount of inputs). But even so, when address 0 is used, but the change address lookahead still isn't trying to look at /1/....Or am I dreaming?

## Disclaimer, I don't know everything
I *think* that the root of this issue is the change address lookahead, and I KNOW for a fact that is causing some of the problem. But I'm not sure if something else is at work here.

**Comment by isocolsky** [comment]
Hi.
The first issue (wrong balance, wrong tx amount) is due to the lack of look-ahead. We do not recommend using the same keys in Copay and other software simultaneously (there could be issues with address look-ahead also form receiving addresses).
The second issue (correct balance, still wrong tx amount) could be due to a client-side caching of the tx. Once txs have 6+ confirmations they are cached locally to prevent unnecessary roundtrips (taking advantage of the assumption that Copay is the sole owner of the keys).

> But even so, when address 0 is used, but the change address lookahead still isn't trying to look at /1/....Or am I dreaming?

I'm not sure I follow. Could you please clarify what you mean by this?

Thanks!

**Comment by hortonelectric** [comment]
To be clear, I have my own fork and would be happy to contribute fixes
where your code is lacking support for my intended use cases. This is
clearly an issue that takes very little time to solve and it's specific to
hardware wallets. The last plea for a fix was ignored and the issue closed
despite the clear presence of an issue.

I am not using this wallet in two different apps. I am migrating once from
my old software. I have narrowed the problem down to the lack of change
address lookup, which causes the wrong transaction amounts. Whatever is
wrong with the balance is almost certainly related.

Can someone please describe where I can find the code that would do the
lookups for the main addresses gap, or any other information and advice so
I can figure out how to look ahead on the change addresses too?
