### ISSUE TITLE
Ethereum support

### ISSUE THREAD

**Issue by fabianovici** [bitpay/copay#6374]
Hello and congratulations for creating this superb BTC wallet.

The only suggestion I have so far is to consider adding ETH (Ethereum) support in the near future, as this is a needed feature and it would make Copay the best Wallet overall.

Thanks
John

**Comment by JDonadio** [comment]
Hi @fabianovici, ATM we are no planning to support another coin.

**Comment by XWingNut** [comment]
I would love it if you could add Litcoin as well if you ever add ETH :)

**Comment by JDonadio** [comment]
Close in favor of https://github.com/bitpay/copay/issues/6132
