### ISSUE TITLE
BIP38 private key trouble

### ISSUE THREAD

**Issue by BADGE463** [bitpay/copay#6375]
Each time I attempt to sweep my paper wallet to my copay I get an error message that say's, "could not decrypt BIP38 private key. This paper wallet was created on the bitaddress.org website. Can anyone help?

**Comment by gabrielbazan7** [comment]
Sorry about that. There is an issue on the prompt. Try entering 'cancel' instead of 'ok'. The buttons label is wrong.

**Comment by BADGE463** [comment]
Thanks so much for your reply! I tried the cancel but that button in fact worked to cancel it. I also tried to sweep the paper to my Jaxx account and it just freezes. I was wondering if it was an encryption issue with the bitaddress system.

**Comment by BADGE463** [comment]
The good news is that a great friend was totally stressing thinking he had lost everything and after using your advise he recovered everything!!! Thank you for that!

**Comment by JDonadio** [comment]
I think Mycelium have the option to decrypt BIP38. You can try it.

Thanks for your report, we will fix it ASAP.

**Comment by XWingNut** [comment]
I had the same problem with Copay & Bitpay with the same paper wallet. hit the Cancel button on Copay an it worked thanks for the answer

**Comment by parkermor** [comment]
@XWingNut 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
