### ISSUE TITLE
Coins is not available in my wallet 

### ISSUE THREAD

**Issue by Courtneycash** [bitpay/copay#6378]
I put money on my wallet but I see nothing my wallet is still empty, I got an email saying that my payment was received but my coins aren't in my wallet what do I do I really need someone's help

**Comment by JDonadio** [comment]
From where did you made the transaction?

**Comment by Courtneycash** [comment]
At the bitcoin machine

**Comment by JDonadio** [comment]
Then you must check the machine details (sender) and look your transaction details to know why your coins are not in your wallet.

**Comment by Courtneycash** [comment]
How what do I do I scanned the QR code so the money should be there how can
I check that

**Comment by JDonadio** [comment]
I've never used a machine to buy bitcoins, but I guess it gave you a ticket after the purchase or something where you can check the transaction status.
