### ISSUE TITLE
Pre-Auth Hold Info Button Link in Card View – Incorrect Text

### ISSUE THREAD

**Issue by jameswalpole** [bitpay/copay#6381]
The pre-auth hold view in the wallet includes an information icon, which, when clicked shows the following undescriptive and unhelpful modal. 

![bitpay card pre-auth](https://user-images.githubusercontent.com/9257396/27981913-e4e3cd60-6362-11e7-870e-7d7b066a4898.png)

The clickable information icon should lead directly to the following article explaining pre-authorization holds instead: https://support.bitpay.com/hc/en-us/articles/115003003563-Why-was-I-overcharged-on-my-BitPay-Card-account-Why-is-there-a-hold-on-my-account-

**Comment by jameswalpole** [comment]
If the same info modal is in place for pending/unconfirmed transactions, it needs to be modified to open the following in-browser: https://support.bitpay.com/hc/en-us/articles/115003014526-Why-do-you-require-one-blockchain-confirmation-for-BitPay-Card-loads-

**Comment by gabrielbazan7** [comment]
The confirmation popup purpose is to confirm that the user really wants to leave the app. Which message would you write there?
