### ISSUE TITLE
Uncaught error scanning wallet when block explorer configured incorrectly. Utxos contains corrupt data.

### ISSUE THREAD

**Issue by hortonelectric** [bitpay/copay#6383]
```/home/user2/bitcore-wallet-service/node_modules/mongodb/lib/utils.js:123                                                                   [40/1885]
    process.nextTick(function() { throw err; });
                                  ^

TypeError: Cannot read property 'path' of undefined
    at /home/user2/bitcore-wallet-service/lib/server.js:1134:48
    at arrayEach (/home/user2/bitcore-wallet-service/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/home/user2/bitcore-wallet-service/node_modules/lodash/index.js:3345:13)
    at /home/user2/bitcore-wallet-service/lib/server.js:1133:9
    at /home/user2/bitcore-wallet-service/node_modules/async/lib/async.js:607:21
    at /home/user2/bitcore-wallet-service/node_modules/async/lib/async.js:246:17
    at iterate (/home/user2/bitcore-wallet-service/node_modules/async/lib/async.js:146:13)
    at /home/user2/bitcore-wallet-service/node_modules/async/lib/async.js:157:25
    at /home/user2/bitcore-wallet-service/node_modules/async/lib/async.js:248:21
    at /home/user2/bitcore-wallet-service/node_modules/async/lib/async.js:612:34
```
When I try to create a watch-only wallet with unspent outputs, and then scan it for funds, this occurs.

Seems like the error should be caught by the system, and it's unclear how it occurred to begin with.

Upon inspection it seems the 'allUtxos' object was filled with 3741 items, none of which contained any address information, `{"confirmations":0,"locked":false,"satoshis":null}` 3741 times. So of course it will fail. 

The blockchain explorer was not configured properly, in fact was not even connected, and yet somehow a report of 3741 'unspent outputs' was being put into this object.

**Comment by JDonadio** [comment]
Just to clarify, do you have a Copay wallet which was exported without private key? Can you provide an addresses so we can check the wallet satus? thanks

**Comment by hortonelectric** [comment]
It is a watch-only wallet (import from extended public key or
importFromExtendedPublicKey which is somewhat experimental still). You can
do it with any wallet, I think. Just change the config.js in BWS, to set
the block explorer URL to http://localhost:3001/somethingwrong and then set
the apiPrefix option to 'somethingalsowrong'. Now restart the BWS server,
import any wallet.

Of course, this is a failure that is due to bad configuration, but there
should be better handling.

**Comment by JDonadio** [comment]
We do not support xpubkey for import process. 

https://github.com/bitpay/copay/blob/master/src/js/controllers/import.js#L145

That code should be removed btw.

**Comment by hortonelectric** [comment]
. Trezor wallet is xpub only right? Cannot send without connecting to
trezor to get private key? So....which is it
