### ISSUE TITLE
Importing Trezor seed; 4 characters of seed

### ISSUE THREAD

**Issue by 2ge** [bitpay/copay#6385]
Hi,

I bought recently cryptosteel, where I can save first 4 characters of each word of my 24 words seed. If I understand, this would be enough to calculate private key, but it seems, I have to type whole words - so here it is not really clear for me - https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki

Next (and I understand risks), I wanted to perform restore, so I downloaded Copay for OSX -> Restore from backup -> typed recovery phrase (24 full words - here would be good, if I could write just first 4 characters from each word...) -> (not set password, on my Trezor, I have some funds without recovery passphrase, and some with it, but for testing, no password is ok) -> Derivation path is m/44'/0'/0', -> From hw wallet (trezor selected) -> wallet service url is default (https://bws.bitpay.com/bws/api), the error is:

```
Could not access the wallet at the server. Please check:
The password of the recovery phrase (if set)
The derivation path
The wallet service URL
```

Also I am aware of guide here: https://99bitcoins.com/restore-trezor-seed-copay/

What I am doing wrong ?

Thanks

**Comment by JDonadio** [comment]
Sorry but it's not clear for me if you are trying to import with your incomplete seed (4 caracters for each of your 24 words)

**Comment by dabura667** [comment]
Copay does not support 24 word phrases.

**Comment by 2ge** [comment]
@JDonadio I tried both. I understand 4 characters for each of 24 words doesn't work (it would be nice if it would, why not?). 
@dabura667 I was under impression it is supported. So there is no way how to restore Trezor to Copay or I should use first 12 words only ?

**Comment by 2ge** [comment]
according https://99bitcoins.com/restore-trezor-seed-copay/ it should be possible.

**Comment by JDonadio** [comment]
Actually yes, we support it. I have a trezor seed here and it works fine creating and importing. I'm not aware about how 4 character for each word should work @2ge.
