### ISSUE TITLE
Payed For Amazon Card still don't have it showing Help

### ISSUE THREAD

**Issue by getpayed777** [bitpay/copay#6386]

**Comment by JDonadio** [comment]
Please, provide us the invoice id or transaction id so we can investigate it further.

**Comment by getpayed777** [comment]
Transaction 3fab260072a4da393bf23a998f91807271907fd3d750e275a4c1ed61d00fac72
Summary

Size	373 (bytes)
Fee Rate	0.003066514745308311 BTC per kB
Received Time	Jul 7, 2017 10:38:26 AM
Mined Time	Jul 7, 2017 10:38:26 AM
Included in Block	
0000000000000000013482243f2c9486188355d919b321669a44898dfffe919b
Details

 3fab260072a4da393bf23a998f91807271907fd3d750e275a4c1ed61d00fac72
mined Jul 7, 2017 10:38:26 AM
0.01032988 BTC
1BCqYZt8BQzub2p5a5VCdRh2YvLMmx1M7t
0.00721545 BTC
1CwfgywdeuTPFdNmE3Z48zxRcyNTRwQikj
0.013225 BTC (S)
0.00317652 BTC (U)
19cmBf9NabPJeGPw5pYS81TnyX4w1qmVy8
FEE: 0.00114381 BTC 213 CONFIRMATIONS 0.01640152 BTC

**Comment by JDonadio** [comment]
Thanks. I'll keep you posted.

**Comment by getpayed777** [comment]
Transaction 3fab260072a4da393bf23a998f91807271907fd3d750e275a4c1ed61d00fac72
Summary
Size 373 (bytes)
Fee Rate 0.003066514745308311 BTC per kB
Received Time Jul 7, 2017 10:38:26 AM
Mined Time Jul 7, 2017 10:38:26 AM
Included in Block
0000000000000000013482243f2c9486188355d919b321669a44898dfffe919b
<https://insight.bitpay.com/block/0000000000000000013482243f2c9486188355d919b321669a44898dfffe919b>
Details
 3fab260072a4da393bf23a998f91807271907fd3d750e275a4c1ed61d00fac72
<https://insight.bitpay.com/tx/3fab260072a4da393bf23a998f91807271907fd3d750e275a4c1ed61d00fac72>
mined Jul 7, 2017 10:38:26 AM
0.01032988 BTC
1BCqYZt8BQzub2p5a5VCdRh2YvLMmx1M7t
<https://insight.bitpay.com/address/1BCqYZt8BQzub2p5a5VCdRh2YvLMmx1M7t>
0.00721545 BTC
1CwfgywdeuTPFdNmE3Z48zxRcyNTRwQikj
<https://insight.bitpay.com/address/1CwfgywdeuTPFdNmE3Z48zxRcyNTRwQikj>
0.013225 BTC (S)
<https://insight.bitpay.com/address/14oQE3iE8wpTWhj7o9TL4eJb4pbKihAKKi>
0.00317652 BTC (U)
19cmBf9NabPJeGPw5pYS81TnyX4w1qmVy8
<https://insight.bitpay.com/address/19cmBf9NabPJeGPw5pYS81TnyX4w1qmVy8>
FEE: 0.00114381 BTC
213 CONFIRMATIONS0.01640152 BTC

**Comment by JDonadio** [comment]
Can you send an email to help@bitpay.com and including the transaction id ?

**Comment by getpayed777** [comment]
Any info for me about Amazon gift card

**Comment by getpayed777** [comment]
Still not on my Copay wallet help

**Comment by getpayed777** [comment]
14UYL5XqtfkozN7NH7fToLrjcM7KuSdBci
Can I get my bitcoin back in my wallet pleace

**Comment by JDonadio** [comment]
Sorry for the delay, we are working on that.

**Comment by getpayed777** [comment]
Ok let me know

**Comment by getpayed777** [comment]
Ok let me know

**Comment by JDonadio** [comment]
@getpayed777 please contact me: javier@bitpay.com

**Comment by getpayed777** [comment]
Eugenegurskiy727@gmail.com

**Comment by getpayed777** [comment]
What exactly do I need to do?
eugenegurskiy727@gmail.com

**Comment by getpayed777** [comment]
javier@bitpay.com Thank You for your help
