### ISSUE TITLE
Ammount too low

### ISSUE THREAD

**Issue by lufkum** [bitpay/copay#6388]
Hi

First of all english is not my firat language. So I'm sorry if it sound weird.

I've received a payment of 0.000666btc (quite low). 

Under the confirmation of payment there's a yellow square that says amount is too low and spending those would cost equal network charge.
My question is: Is the payment are in my account and this is just a warning who tell me if I want to spend those I'll have big fees. Or they canceled the payment.

I received plenty of time amount lower than this and this the first time I get this message.

Thank you

**Comment by JDonadio** [comment]
Hi, please check the link below to understand a little more your situation. Let me know if you have any question.

https://github.com/bitpay/copay/wiki/COPAY---FAQ#copay-requires-high-fees-for-low-amounts-transactions

**Comment by lufkum** [comment]
I get the fact that I need to pay fee if I send btc but for btc received I don't nees to pay those fees right ? I'm just unsure if my account got the 0.000666

**Comment by yuskl** [comment]
yes

**Comment by gabrielbazan7** [comment]
@lufkum yes, you have that money in your wallet, but you couldn't move it. And if you continue receiving low payments, and you have for example 50 dollars of little payments,  you're not going to be able to move it either. Is explain in the link JDonadio share to you.

>  So, this could happen when you have many small inputs in your wallet, so you need to use all (or most) of them to build the transaction and your fee will be increase significantly.

**Comment by lufkum** [comment]
Ok thanks I understand. So all my earning from faucet is a waste (main BTC revenue)
