### ISSUE TITLE
Can't write into Memo

### ISSUE THREAD

**Issue by blanka69** [bitpay/copay#6397]
I am using Android, and have been using copay multisig for 3 months now.  Suddenly, I can no longer write into the Memo. I click OK, but the memo doesn't update.  Please help! I need the memo function urgently.  Have tried rebooting.

Rgds,

**Comment by JDonadio** [comment]
Sorry about that, it's already fixed and merged. Will be working in the next release. Thanks for reporting!

**Comment by gabrielbazan7** [comment]
@blanka69 try entering 'cancel' instead of 'OK'.

**Comment by cmgustavo** [comment]
Fixes #6366
