### ISSUE TITLE
Cannot import wallet from 12 words

### ISSUE THREAD

**Issue by MazzyGirl** [bitpay/copay#6398]
Hi,
I am having a lot of trouble recovering my wallet.
The system tells me I have one incorrect word, impossible - these were written down and I am needing to be paid again.
My boss doesn't know my phone has crapped itself, so this is making me look very stupid- got it?

I need my wallet up and running asap.
I'm extremely pissed off about this too.
This means all my BTC is gone.
Contact me please on +61 423 464 902 to fully recover my wallet and renew passwords

Many thanks
MazzyGirl 2017

**Comment by JDonadio** [comment]
In the next link you can find a complete list of words for your language. Ensure to check your complete phrase and also write each word in lower case.

https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md

Hope that helps.
