### ISSUE TITLE
Cant Log Into My Wallet 

### ISSUE THREAD

**Issue by ColeAdams1** [bitpay/copay#6399]
I have gotten a new PC and Iphone recently and everything I had of my 12 word wallet thing is gone I have over 100 usd in there I would Like to use. Please help 
Contact me @ adamscole2002@gmail.com

**Comment by gabrielbazan7** [comment]
You already import the wallet on your new devices ?

**Comment by Gamboster** [comment]
Hello ColeAdams1.
I understand that you lost your 12 words backup.

To recover a wallet you need to have made at least one of this 3 backups:
1) The corresponding 12 words
2) The json file that you get when importing the wallet
3) Or the QR that you get when importing the wallet

If you do not have any of these 3 backups done. Unfortunately there will be no other way to recover that wallet.
