### ISSUE TITLE
Issues Linking Bitpay & Coinbase

### ISSUE THREAD

**Issue by Angellico** [bitpay/copay#6402]
I downloaded the bitpay app and linked my coinbase account to it but the wallet in bitpay shows no funds in it. I logged into coinbase to double check to make sure I had money in it and i did so im not sure what the issue is.

**Comment by JDonadio** [comment]
Linking your account will not show you the balance or history from Coinbase but from Copay.

**Comment by Angellico** [comment]
Is there a way to transfer my coinbase funds to my bitpay wallet app then?

Im just trying to figure out how to add funds to bitpay wallet app as a canadian resident

**Comment by JDonadio** [comment]
You should copy your wallet address and paste it in the `send form` from Coinbase and send your funds to your Copay wallet.
