### ISSUE TITLE
Obtaining Private Keys on the Latest Version of CoPay

### ISSUE THREAD

**Issue by Arszilla** [bitpay/copay#6412]
Hi.

I am trying to access my private keys and whatnot to be safe from this upcoming fork/split, not knowing if CoPay/BitPay will support one over the other or just remain neutral and allow users to choose one.

1) Many redditors said obtain your private key and I plan to do so; but I don't know what can I do with it?
2) If there is a split how can I choose my side? (Not UASF) Do I do that with my private key? And how?

Thanks in advance.

**Comment by gabrielbazan7** [comment]
Go to Settings -> Wallets -> Choose your wallet -> More Options -> Export Wallet -> File/Text -> Set up a password -> Download

  Then, go to https://bitwiseshiftleft.github.io/sjcl/demo/.  
Open your file and copy the whole text.
 Paste the text in Ciphertext text area.  
Enter your password on the Password input. (that password is the one that you enter in Copay) 
Then click in decrypt.
  In the Plaintext text area you could find the xPrivKey.

**Comment by Arszilla** [comment]
@gabrielbazan7 and how can I choose my side etc in this upcoming split etc? Like many people told me to get my privatekey, but I don't know what to do with it and such.

**Comment by zavan** [comment]
I'd disconnect from the internet after loading the https://bitwiseshiftleft.github.io/sjcl/demo/ page, just for  safety.

**Comment by zavan** [comment]
@Arszilla What do you mean with "choose my side"? If a hardfork happens, your private keys will give you access to the same amount of "coins" in both blockchains, you just need to import them in a wallets that support each one.

To "vote" before/after the hardfork is to run a full node containing code of the side you chose.
To vote after the hardfork is to sell one of the sides and buy the other.

**Comment by Arszilla** [comment]
@zavan As I am a noob to the technical aspect of BTC, once I have my private keys, I load them to any wallet and I can access my bits? And if there is Bitcoin Classic and Bitcoin Unlimited. I choose which one to use when I load my private keys?

**Comment by zavan** [comment]
That will depend on the wallet. Some wallets will only support one of the chains, other will support more than one, you can import your keys into more than one wallet, but choose carefully.

**Comment by JDonadio** [comment]
You can use your 12 words to be imported in other wallet which support BIP39.
