### ISSUE TITLE
Cant sweep paper wallet

### ISSUE THREAD

**Issue by klepkosg** [bitpay/copay#6413]
Hello, I have made a paper wallet in bitaddress.org load it with some btc and tried to sweep paper wallet and send some to my copay wallet, but it keeps telling that the encrypted passphrese is wrong. I have screenshoted the encrypted passphrase so it cant be wrong. What else can happened??

**Comment by balishag20** [comment]
Same issue here...must be a glitch??? Updates from Copay??

**Comment by klepkosg** [comment]
Not nice at all, fortunatelly i have sent very little btc to my paper wallet to test it, does anyone knows when or how it will be solved?

**Comment by balishag20** [comment]
https://github.com/bitpay/copay/issues/6414


Feed17 figured out a work around.

**Comment by klepkosg** [comment]
What do you mean what did he figured out?

**Comment by klepkosg** [comment]
What do you mean what did he figured out?

**Comment by balishag20** [comment]
Using Copay......"To fix this, I went back to bitaddress.org web archive.. entered my private key, and password-- then hit decrypt..it gave me a WIF compressed private key that I used instead of my private key in BIP38 Format.. hope this helps anybody stuck!"

**Comment by klepkosg** [comment]
Yes but now your paper wallet isnt encrypted right?

**Comment by XWingNut** [comment]
try hitting the Cancel button instead of OK after you enter you password. Worked for me

**Comment by klepkosg** [comment]
OMG it worked with cancel!!! not very good, they should fix that bug asap...too silly!!

**Comment by klepkosg** [comment]
@XWingNut thank you very much cause it was too frustrating

**Comment by klepkosg** [comment]
@XWingNut @balishag20 one last question I have transferred succesfully to Copay but is there a way to transfer only a specific ammount and not totally sweep the paper wallet. After putting the bip38 password and clicked on cancel the only option was to sweep and didn't show a screen were I could put a specific ammount. Do you know anything about that?

**Comment by JDonadio** [comment]
Sorry about that, the error was fixed and will be working for the next release. Thanks for your reports. Closed in favor https://github.com/bitpay/copay/issues/6359

**Comment by XWingNut** [comment]
@klepkosg no you can only sweep I have not seen anything that lets you enter an amount
