### ISSUE TITLE
Sweep paper wallet not working

### ISSUE THREAD

**Issue by feed17** [bitpay/copay#6414]
It says it could not decrypt private key BIP 38.. password is right.. is this glitch in latest update??

**Comment by balishag20** [comment]
https://github.com/bitpay/copay/issues/6413

**Comment by feed17** [comment]
To fix this, I went back to bitaddress.org web archive.. entered my private key, and password-- then hit decrypt..it gave me a WIF compressed private key that I used instead of my private key in BIP38 Format.. hope this helps anybody stuck!
