### ISSUE TITLE
Receiving money from Coinbase issue

### ISSUE THREAD

**Issue by jordankalk** [bitpay/copay#6420]
I just transferred money from Coinbase to Copay, the transaction is nowhere to be found. I doubt checked the address and it's correct, but there's nothing in my Copay app on my iPhone. Coinbase says it's Pending, but it's never taken this long before. Please help.

**Comment by JDonadio** [comment]
Did you buy bitcoins through Copay or using the Coinbase platform?

**Comment by jordankalk** [comment]
The Coinbase iPhone app. Then I transferred them to the Copay address, but nothing is showing up.

**Comment by JDonadio** [comment]
You should contact to Coinbase support cause the transaction was built from their end.
