### ISSUE TITLE
Card Load Flow Automatically Defaulting to Wallet/Does Not Allow Wallet Selection

### ISSUE THREAD

**Issue by jameswalpole** [bitpay/copay#6423]
My 2 of 2 wallet is what I normally use to load my card, and it has sufficient funds. However, the card loading flow is automatically defaulting to checking the balance of a 1 of 1 wallet which I do not use, so I receive an "insufficient funds" message every time I try to load. It won’t let me select which wallet I want to load from, so I’m kind of stuck. Using BitPay app version 3.6.3 on Android.

**Comment by cmgustavo** [comment]
Fixed #6376

Thanks for report.
