### ISSUE TITLE
Import paper wallet

### ISSUE THREAD

**Issue by Zavabobo** [bitpay/copay#6424]
Hi, i need to import a paper wallet to Copay, i only have the private key and the bitcoin address. How can i do it?

**Comment by JDonadio** [comment]
Use the main scan button to sweep your paper wallet from your QR code, if you don't have one, you can generate it from [here](http://goqr.me/)

**Comment by Zavabobo** [comment]
you mean the QR code that contains the bitcoin address? When i scan it, i only have the option to add it as a contact.

Do you speak spanish?

________________________________
De: Javier Donadío <notifications@github.com>
Enviado: sábado, 15 de julio de 2017 03:39 p.m.
Para: bitpay/copay
Cc: Zavabobo; Author
Asunto: Re: [bitpay/copay] Import paper wallet (#6424)


Use the main scan button to sweep your paper wallet from your QR code, if you don't have one, you can generate it from here<http://goqr.me/>

**Comment by JDonadio** [comment]
Si hablo español. Me refiero a que si tenes la privkey, generes el QR con eso y hagas el sweep desde Copay

**Comment by Zavabobo** [comment]
Muchas gracias por tu ayuda, ya lo logré.


________________________________
De: Javier Donadío <notifications@github.com>
Enviado: sábado, 15 de julio de 2017 05:45 p.m.
Para: bitpay/copay
Cc: Zavabobo; Author
Asunto: Re: [bitpay/copay] Import paper wallet (#6424)


Si hablo español. Me refiero a que si tenes la privkey, generes el QR con eso y hagas el sweep desde Copay

**Comment by JDonadio** [comment]
Genial!

**Comment by mnofresno** [comment]
No puedo sencillamente importar una dirección/clave privada a mi billetera con Copay? es decir, incorporar una dirección adicional usando su clave privada? Recién hice un scan del QR de la clave privada y detectó la dirección pero lo que hizo fue hacer automáticamente una transferencia a una de las direcciones que ya tenía en Copay, es decir, pagué el fee de la transacción por algo que no hacía falta pagar. Es bastante malo hacer pagar al usuario por algo que con cualquier billetera como por ejemplo electrum es gratis. (En electrum puedo importar una address/private key y no pago por eso, solo la empieza  monitorear y conociendo la private key puedo gastar ese dinero.)

**Comment by JDonadio** [comment]
@mnofresno Copay/BitPay no tienen la posibilidad de `importar una paper wallet` sino de barrer (sweep) los fondos de ésta. Es decir que lo que hiciste fue hacer un sweep de tu paper wallet hacia una billetera de tu app.

> Recién hice un scan del QR de la clave privada y detectó la dirección pero lo que hizo fue hacer automáticamente una transferencia a una de las direcciones que ya tenía en Copay

No hay procesos de pagos "automáticos" todos deben ser validados, confirmados y firmados por el usuario.

**Comment by mnofresno** [comment]
Gracias por tu respuesta @JDonadio que bueno que sería tener la posibilidad de importar una dirección sin tener que pagar fee. ¿No contemplan añadir esa feature? En caso afirmativo puedo ponerme a trabajar en ella en un fork y hacer un pull request cuando la termine.

**Comment by JDonadio** [comment]
> que bueno que sería tener la posibilidad de importar una dirección sin tener que pagar fee.

Copay no importa direcciones, únicamente wallets (BIP39 o en el formato exportado por Copay). No entiendo del todo el hecho de importar una dirección sola con sus claves

> En caso afirmativo puedo ponerme a trabajar en ella en un fork y hacer un pull request cuando la termine.

Por favor, todos los aportes son bienvenidos!!!!

**Comment by mnofresno** [comment]
> No entiendo del todo el hecho de importar una dirección sola con sus claves

@JDonadio 
- Te cuento mi caso personal a ver si se entiende mejor:

Yo tengo instalado en mi PC, Copay y Electrum

Y tengo instalado en el celular Copay

A veces por motivos que no vienen al caso hago movimientos con Electrum (otra wallet), Electrum crea una nueva change address y pone parte de mis fondos ahi.

Esa nueva change address, como no está dentro del scope de las addresses de mi wallet de copay, copay no se actualiza y pareciera que hubiera perdido una parte del saldo, por que hay addresess con fondos que están desvinculadas de copay pero están contempladas por Electrum.

- Ahora te cuento el caso de amigos, familiares, etc:

No saben nada sobre BTC, y quieren tener un poquito para ahorro. Compraron BTC y los guardaron en una paper wallet por que es lo que tenían a mano en el exchange y la mejor forma en que lo podían hacer sin ayuda.

Yo les recomendé que la pasen a Copay para poder monitorear sus valores. Cuando vamos a investigar cómo hacerlo, lo hice yo primero con una address mía que tenía desvinculada de Copay para probar la funcionalidad. Entonces me encuentro con ésta sorpresa, cuando ellos la quieran usar, le va a significar a lo mejor un costo del 10 % en fee cuando de por sí ya pagaron comisiones al exchange para comprar, comisiones de la red para transferir, comisiones del banco, etc.... entonces así es muy dificil convencer a la gente de las bondades de BTC. ¿Se entiende el punto?

**Comment by JDonadio** [comment]
Entiendo perfectamente tu punto, es más, está detallado en nuestra FAQ > https://github.com/bitpay/copay/wiki/COPAY---FAQ#different-balance-2-wallet-clients-on-same-wallet-seed

Eso es porque Copay no puede ver los change addresses generados en Electrum (justamente lo que mencionaste).

Con respecto a la paper wallet, es una wallet (valga la redundancia) por lo que si queres mover esos fondos va a significar un costo para los mineros, como cualquier otra transacción bitcoin. No es simplemente dirección en un papel, es una wallet. Creo que ahí está tu confusión.

**Comment by mnofresno** [comment]
@JDonadio entiendo que copay maneja un conjunto de addresses de las cuales posee address y private key para cada uno. Y no ve ni maneja fondos que no sean los que están dentro de esas addresses.

Conceptulmente te pregunto entonces: Ese conjunto, ¿no se puede "agrandar" con todas las direcciones que quiera, conociendo las private keys? Es decir, si tengo una paper wallet por ejemplo de la cual tengo una o dos direcciones, con sus respectivas private keys.... no puedo incluirla en la lista de addresses/keys que Copay maneja, Y Monitorea, para que se puedan adicionar los fondos?

A menos que me esté confundiendo y algo de lo que te dije no sea así, entiendo que se podría "visualizar" y "gastar" desde copay, los fondos de todas las addresess esas, sin que implique un costo para los mineros, sino simplemente el costo de modificar lo que copay tiene almacenado en el localstorage de electron/cordova/etc...

**Comment by JDonadio** [comment]
Me temo que no, porque todas las addresses se derivan a partir de la private key de la wallet en sí, con un determinado derivation path, no es tan sencillo como agarrar el address con sus claves y adjuntarlas, eso no va a funcionar.

**Comment by mnofresno** [comment]
Entiendo: ¡Fuck! Bueno voy a investigar un poco más y volvemos a hablar, quizás haya una solución. Gracias por desasnarme y muchas gracias por tu tiempo @JDonadio, fué un gusto.
