### ISSUE TITLE
Import paper wallet into Copay Windows app

### ISSUE THREAD

**Issue by veltin** [bitpay/copay#6429]
Hi, I have looked for an answer to this but could not find one.  Is it possible to import or sweep bitcoin from a paper wallet into the Copay Windows app? (3.6.2) I do not have a webcam so unable to use the scanner, and cannot find any option to import.  Thank you.

**Comment by dabura667** [comment]
Sorry, it is currently QR code only for paper wallet sweep.

**Comment by veltin** [comment]
Ok thanks, is there a guide on how to access my desktop app wallet on the IOS app so I can use my phone to scan the QR code?  Thanks again.

**Comment by JDonadio** [comment]
You should use your backup phrase or export your wallet as file/text or QR code and import it in your desktop app. Then, you will have the same wallet in both devices.

**Comment by JDonadio** [comment]
@veltin if you paste your private key in the send view, the contextual menu for sweep will be shown, can you try it and tell me how it went ?

**Comment by JDonadio** [comment]
![bitpay_-_secure_bitcoin_wallet](https://user-images.githubusercontent.com/13851807/28420349-3e693134-6d38-11e7-91f6-ada080ef29bc.png)

**Comment by veltin** [comment]
That worked, thank you.

**Comment by veltin** [comment]
Actually it does not seem to work, the wallet was stuck on "sweeping" and did not receive the funds

**Comment by gabrielbazan7** [comment]
Update to the last version

**Comment by chrischuks8** [comment]
Hi everyone, am using an android, i try to find how to sweep a paper wallet from the settings to advance option all to no avail. Please help direct me.

**Comment by JDonadio** [comment]
There is not an elegible option to display the sweep menu. Please read the above comments.
