### ISSUE TITLE
error when trying to sweep paper wallet funds

### ISSUE THREAD

**Issue by provxraytech** [bitpay/copay#6430]
using copay app I am unable to sweep my paper wallet funds.  It is password protected, and  I KNOW I am using the correct password, but I keep getting an error message stating : Error scanning funds: Could not decrypt BIP38 private key. Please advise!! thanks so much.

**Comment by dabura667** [comment]
Try making a new BIP38 wallet on your computer, and scan that one.

I just did, and there was no problem with decryption. I just got a "No balance" error (I didn't put any funds in)

But when I entered the wrong password on purpose I also got the Decryption error.

I think you are entering the wrong password.

**Comment by provxraytech** [comment]
I'm at a loss. My password is correct. I've initiated a wallet sweep previously to verify my bitcoin amount was correct. I just back out of going all the way through actually sweeping the funds. This I've done several times before and never had an issue.

**Comment by JDonadio** [comment]
Please, try the `cancel` instead of `ok` button. This is already fixed and merged, will be working ok in the next release. Sorry about that.

**Comment by provxraytech** [comment]
So, where does that leave me and this paper wallet? Will my password at some point be recognized again or did i just lose all my bitcoin on my paper wallet? It was not an insignificant amount.

**Comment by JDonadio** [comment]
We have an error in the confirmation and prompts buttons (inverted). Try hitting cancel instead of ok and should work.

The funds are in your paper wallet, the sweep process move your funds once the password is recognized.

**Comment by provxraytech** [comment]
Got it! Thanks so much!
