### ISSUE TITLE
Copay: cannot import wallets 

### ISSUE THREAD

**Issue by jennyyaaa** [bitpay/copay#6433]
I'm a Chinese user of Copay, I've to say Copay is really bad. My phone broke down so I had to reinstall Copay app on my new phone. When I downloaded the app, my old copay wallet was gone, so I used the 12 words which was given to me when I signed up to import my old wallet. But it have always been showing an error message that states, "wrong number of recovery words: 1". The thing is I am more than certain that I wrote all the 12 words down correctly on my notebook. I did another experiment, I registered a new Copay wallet and took a screenshot of the 12 words, then I deleted the wallet and tried to retrieve the wallet by retyping the 12 words based on the screenshot I took. Guess what?! The same error message appeared and this time my 12 words were 100% correct! But why could this happen?!? Can anyone explain why? Is it because I'm using the Chinese version of Copay and my 12 words are Chinese words? Copay to me is so unreliable which I cannot trust sending money anymore. PS I've money in my copay wallet. Thank you in advance!

**Comment by JDonadio** [comment]
Hi there, sorry about the problems. The error `wrong number of recovery words: 1` it's caused by non separations between words. Ensure to write each word separated by a space like a phrase (recovery phrase).
