### ISSUE TITLE
No makefile for Windows phone

### ISSUE THREAD

**Issue by zowki** [bitpay/copay#6441]
The instructions for compiling for windows phone 8 says to run "make wp8-prod", but there's no makefile.

What should I do to compile for Windows Phone 8?

**Comment by iop223** [comment]
If there is a new method to compile for windows phone 10, could it be added to the instructions?

**Comment by cmgustavo** [comment]
Try

```
npm run apply:copay ; npm run start:windows
```

Then open the project file with VS inside `cordova/platform/windows/`

**Comment by iop223** [comment]
I get this error:
```
Unhandled exception at line 5, column 1 in ms-appx-web://18c7659d.bitcoin.com-securebitcoinwallet/www/plugins/cordova-plugin-qrscanner/src/windows/lib/qrScanner.js
0x800a1391 - JavaScript runtime error: 'QRReader' is undefined occurred
```

What VS packages are required to build this for windows phone? Am i missing anything?

**Comment by gabrielbazan7** [comment]
Yes. You are missing something. Go to app-template -> config-template.xml -> then remove this line: `<plugin name="cordova-plugin-qrscanner" spec="~2.5.0" />` and then enable this one `<plugin name="phonegap-plugin-barcodescanner" spec="https://github.com/phonegap/phonegap-plugin-barcodescanner.git" />`

then try: npm run apply:copay ; npm run start:windows 

Should work in VS 2015 and 2017. 
I'm sending a PR to improve the documentation. Thanks !
