### ISSUE TITLE
Network Fee for 2BTC was $56.57 and more. Is this normal? 

### ISSUE THREAD

**Issue by best51451** [bitpay/copay#6442]
Hello there, 

I have experienced ridiculously high network fees on the following period of 6/30~7/13.
I thought due to the recent scalability issues, network fees went up though; since not so many people talked about this online, I did not even much doubt it.  Though, I had some chance to ask about this with some Bitcoin professional today, I have found that this happened only to me (or to all Copay user in this period of time?).  I was shocked. 

I wonder if I can take some BTC back or not?  I have some more transactions though; these are unbelievably high.  If you can help me this, I would really appreciate it. 

Date    | Sending BTC | Speed                                    | Network Fee
6/30/17 | 2.00000000 | Normal 1.2% of Transaction | $56.68
7/4/17 | 0.01000000 | Economy-7.23% of Transaction | $1.82
7/5/17 | 0.39233400 | Economy-0.71% of Transaction | $6.57
7/13/17 | 0.01000000 | Economy-4.21% of Transaction | $1.03
7/13/17 | 1.26207200 | Economy-0.89% of Transaction | $26.39

Thank you so much

**Comment by dabura667** [comment]
1. These fees are shown to you before clicking the "send" button. You should not be surprised by this now.
2. Network fees are not collected by wallets. Copay and/or Bitpay does not have anything to do with the fees at all. These fees are paid to the maintainers of the Bitcoin network, called "miners."
3. Network fees are calculated on a "per byte of data" rate. NOT "per amount sent" rate. Therefore you see huge fluctuations of the "% of Transaction (sent amount)"... because the fee has nothing to do with the amount sent.

Date | Sending BTC | Speed | Network Fee
:---: | :----: | :----: | :----:
6/30/17 | 2.00000000 | Normal 1.2% of Transaction | $56.68
7/4/17 | 0.01000000 | Economy-7.23% of Transaction | $1.82
7/5/17 | 0.39233400 | Economy-0.71% of Transaction | $6.57
7/13/17 | 0.01000000 | Economy-4.21% of Transaction | $1.03
7/13/17 | 1.26207200 | Economy-0.89% of Transaction | $26.39

**Comment by JDonadio** [comment]
For additional info you can check this entry: https://github.com/bitpay/copay/wiki/COPAY---FAQ#copay-requires-high-fees-for-low-amounts-transactions

**Comment by best51451** [comment]
Hello there, 

Thank you so much for your immediate reply. 
I really appreciated it. 

Thank you!

Regards, 

Best51451

**Comment by best51451** [comment]
Hello again, 

I have a couple of more questions.  I have talked about these very expensive fees with my Friends (3 people) over this weekend though;
all said that this fees were very unusual even under this fork situation. 

As matter fact, since I had to make a post to the Github forum (in public), I did not disclose all transactions. 
So, I posted all these high fee transactions since 6/21 below. 
The fee was calculated  based on 7/19 BTC pricing , so it would have been higher by now.
      7/19/17 10:36PM 1BTC= 2336.57 10:36PM  
      Date Sending BTC Network Fee  Speed Fee BTC Network Fee 
      6/21/17 1.49644000 $3,496.54 Normal  0.33%of Transaction 0.00500400 $11.99 
      6/24/17 2.00000000 $4,673.14 Normal  0.61%of Transaction 0.01227200 $28.67 
      6/30/17 2.00000000 $4,673.14 Normal 1.2% of Transaction 0.02426200 $56.68 
      7/4/17 0.01000000 $23.37 Economy-7.23% of Transaction 0.00077900 $1.82 
      7/5/17 0.39233400 $916.72 Economy-0.71% of Transaction 0.00281400 $6.57 
      7/13/17 0.01000000 $23.37 Economy-4.21% of Transaction 0.00043900 $1.03 
      7/13/17 1.00000000 $2,336.57 Economy-0.7% of Transaction 0.00709300 $16.56 
      7/13/17 1.26207200 $2,498.92 Economy-0.89% of Transaction 0.01130200 $26.39 
      Total 8.17084600 $18,641.77  0.06396500 $149.71 
         $149.46 


<<Question>>
1.  Why Copay’s fees (network fee) were higher than other Wallets?
     if you said these network fees were collected miners, why all other people including my friends got very reasonable fees like $1 per a transaction more than 2BTC while my transactions got unreasonable network fees from COPAY..
     I had only COPAY wallets and realized that in May, these fees were acceptable level though; all of sudden, a network fee went up dramatically with COPY while the same Miner’s fees were still reasonably charged by the other wallets (Blcockchain.info)?
     I have spoken with a couple of other people who used the different wallet rather than COPAY and they said that these transaction fees were way high and un acceptable.
    This was the reason why I contacted you guys at the first place. Please advise me why Copay’s charges were way higher than other wallets?

    I have joined some Bitcoin communities and these were over 1000 people and I posted this issue in there. Then, quite some people expressed that they were not going to use COPAY any more.  
    Especially, after some people engaged that topic, the difference between reasonable and unreasonable fees were compared and exposed in communities. 
    So, the impact was way larger than what I thought in there. Especially Copay use, since I have loved using COPAY,I had introduced COPAY to many of my friends.  Thus, this is very crucial answer for me to get from you
   so that I may be able to restore and recover this at each community. 

2. Could you explain me what is ” per byte of data “  rate?  You may realized that I had 2x 2BTC and 2x0.1BTC transactions and each of these had a different network rate.
This may be because each one came from the different transactions (blocks/chains) in past and so each size of chains has different byte size?

3. Bitcash and fork info
    Is Copay going to carry bitcash in a Copay walleta after 8/1? what about limitations for BTC transactions?
    Please advise me. 



Thank you so much!

Regards, 

Best5151

**Comment by dabura667** [comment]
1. Because bitcoind estimatefee command had trouble with decreasing after spam attacks during May pushed up the fee market. Copay uses the "estimatefee" command in the main Bitcoin Core software.
2. https://bws.bitpay.com/bws/api/v2/feelevels `{"level":"normal","feePerKb":180737,"nbBlocks":3}` this means for every 1000 bytes, you will pay 0.00180737 BTC. The smallest transaction is 225 bytes, which is 0.00040665 BTC fees. This API fee levels is from Bitcoin Core's "estimatefee" command. blockchain.info etc. have different fee rates because they use their own algorithms.
3. I don't know what their plans are, but I will assume that no, they will not support Bitcoin Cash.

**Comment by best51451** [comment]
Hello there 

Thank you so much for your reply. 

1. Below #1, OK, I understood that you guys have used “estimatefee”. But I believed that all Wallet’s companies used the same miners, correct?
If so Copay’s fees should be the same charges like others, but why Copay’s fees were higher than others wallet’s companies charges?
It sounded that Copay’s “estimatefee” has been miscalculated then? 
Even “banks” do not charge over $50 for wiring $10,000, but I paid $56.57 (0.024262, today was$66.79) to send $4600.

An inexpensive network fee was one of the benefit using Bitcoin platform. So if you were my situation, you would like to continue using COPAY?

2. Sorry, I still cannot figure out.
Can you provide me the formula for this particular 2BTC?  How can I get 0.0242620 for 2BTC transaction? I would like to know how I can translate 2BTC into bytes?
So, for 2BTC, how many bites 2BTC has? Seemed to me that each cost of levels already has  a different fee schedule, so, BTC amount must be calculated equally to any amounts at any levels, right?
Like once you tell me how many bytes for 2BTC, that amount should be used for all levels?  And even for 1 BTC transaction, simply it should be divided by 2?


3. Copay is the one of the most popular wallets in the planet and 8/1 is a week away, 
I am sorry to say, but I believe Copay should cope something with this, right?
I wonder you guys will announce the Copay’s decision on this matter to Public soon? And if so, when? 

Thank you!

Regards, 

Sue

**Comment by dabura667** [comment]
1 and 2. byte size has nothing to do with amount sent. I can send 1000000 BTC and it might be 225 bytes or it might be 100000 bytes. I could also send 0.0001 BTC and it could be 225 bytes or it could be 100000 bytes.

Bitcoin works ok a pay-per-data not a pay-per-amount. This is how Bitcoin has always worked.

3. Copay's backend would need an overhaul and can not be done in 8 days.

**Comment by best51451** [comment]
Hello there,  

OK, thank you so much for your reply. 
Regarding this byte matter, I need some class to understand. 
So, I give up at this time though; I really appreciated your reply.

I understand that Copay needs more than 8 days to overhaul, but if so, Copay has to announce officially, right?
If so, when it will be then?

Thank you!

Regards,

**Comment by best51451** [comment]
Sorry one more. 

So I gave up to calculate this. 
However, the bottom line is that when this fork matter become smoothly, these network fees should be back to the normal like before (less than $1) or same higher fees like now?
This is the most important!!

Thank you!

Regards,

**Comment by best51451** [comment]
Hello there, 

Sorry to bother you again.

Regarding this answer:
>>>>Because Bitcoin estimatefee command had trouble with decreasing after spam attacks during May pushed up the fee market. Copay uses the "estimatefee" command in the main Bitcoin Core software. 
From this, I assumed that the % of the Estimatefee in May and June have been changed based on what?  Because miners could not get paid to what they were supposed to receive in May, they or Copay changed the rate then?
If so, users made transactions through Copay in June paid higher fees to cover the deficits from the transactions fees which these miners could not collect in May?

Please advise me. 

Thank you!

Regards,
