### ISSUE TITLE
No money updating

### ISSUE THREAD

**Issue by Timoulis** [bitpay/copay#6444]
Today after i update to v3.7.0 of copay, i saw that the amount of money at my wallet, is stack, and no more updating regardless the ups and downs of BC.
Is it only me or it is happening to you also?

**Comment by JDonadio** [comment]
Hi @Timoulis, can you trying cleaning your cache from Settings > wallet > more opts > transaction history > clear cache

If the error persist, please provide us your platform and OS version. thanks

**Comment by Timoulis** [comment]
Did that. The problem remains.
I use a windows 10 64b pc. I saw that problem after the update to the new version.
No problem at all with previous ver.
I will restart the pc now to see what will happen.

**Comment by JDonadio** [comment]
Thanks for your report. I'll keep you posted once the problem be fixed.

**Comment by Timoulis** [comment]
Just restart. Nothing.
Problem remains.
Will wait news from you

Tnx
Tim

**Comment by Timoulis** [comment]
It just update. After 6 hours it update now.
I will keep an eye if the problem comes back and i will inform.

Tnx
Tim

**Comment by JDonadio** [comment]
Seems like it was an external error from an exchange rate API. Thanks for your report.
