### ISSUE TITLE
Nicehash miner work not shown in copay wallet

### ISSUE THREAD

**Issue by SOSOPI** [bitpay/copay#6445]
hallo , 

I have been able to mine for the first time and got my amount of BC at 0.0047. 
Now for all the time spend to get this small amount I would like it to also be seen in the wallet of copay because when I created that wallet  this miner's adress I used made this amount but it does not transfer?
How long must I wait  because it is already left for nearly 2 days now and there is still no change.
Software used NiceHashminer 2 and Copay.

**Comment by JDonadio** [comment]
You are sending **to** Copay, so we did not made the transaction, you should find the transaction made from your miner and check the fee or whatever that could be causing the delay.

**Comment by SOSOPI** [comment]
Hello Jdonadio,

With Zcash I use the Zcashwallet and it does show on my wallet the amount of what I have mined with fee or without fee. And also I m referring to just the miner doing his job that is without the send option of any amount to an adress from example one software to another. 
Now with Copay I have not seen any activity changes on my personal wallet :( and that was even 2 days ago even if it is just this 12 dollars but hey better now as later when it is maybe 120.
