### ISSUE TITLE
Copay

### ISSUE THREAD

**Issue by Mari075** [bitpay/copay#6446]
Hi, I Copay on IPad since May.
Normal Bitcoin Network Commissions Settings.
I've emptied cache and all transactions have become "Amount too low to spend" from the beginning.
What should I do? Thank you

**Comment by JDonadio** [comment]
Hi there, the latest Wallet version shows a warning on incoming transactions when the fee needed to redeem those funds in the future will be closer to the transaction amount itself. e.g.: if you receive 0.001 BTC, you will need to maybe 0.0005 BTC to move those funds in the future, so a warning is shown.

If this happens often to you, you may ask your payer to group your payments.

**Comment by Mari075** [comment]
Does this mean that Copay is no longer suitable for people who take free bitcoin faucet ? (payout minimum 25.000 satoshi)

**Comment by gabrielbazan7** [comment]
Copay or any Wallet. Take a look to this links: https://github.com/bitpay/copay/issues/5164
https://github.com/bitpay/copay/issues/6388
