### ISSUE TITLE
Action sheet vs. menu bar

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#6447]
On the receive view the action sheet should appear on top of the menu bar (highest z-index) not from behind it.

**Comment by JDonadio** [comment]
![copay_-_copay_bitcoin_wallet](https://user-images.githubusercontent.com/13851807/28467018-c5680f76-6e04-11e7-8ba6-156eaabadedb.png)

vs 

![copay_-_copay_bitcoin_wallet](https://user-images.githubusercontent.com/13851807/28467032-d705cbb0-6e04-11e7-855f-0659fd8f3f75.png)

**Comment by ajp8164** [comment]
Yes. Action sheet is a modal and should need to be dismissed before changing tabs. It also looks funny/not standard when the tab bar covers it.
