### ISSUE TITLE
Change email address?

### ISSUE THREAD

**Issue by samu16** [bitpay/copay#6450]
Hello,

I recently changed my email address.
How can I change it for my copay wallet, so I will receive e.g. Transaction notifications to my new email address?
I hope someone can help!

Thank You,
samuel

**Comment by JDonadio** [comment]
Hi there, 

In Settings > Notification you can set/change your configuration for email or push notifications.

**Comment by samu16** [comment]
Thank You!

**Comment by JDonadio** [comment]
Glad to help!
