### ISSUE TITLE
Private Key

### ISSUE THREAD

**Issue by prasanthsarath** [bitpay/copay#6451]
Hi, I am new to Bitcoin world and it's wallets. I was told that a private key is required to authorize a BTC payment from the wallet. But I don't see my private key in copay, am I missing something here?

**Comment by dabura667** [comment]
Your 12 word recovery phrase is your private key.

**Comment by prasanthsarath** [comment]
Hi There, Thanks for the quick response.

Please bear with my lack of knowledge here, I did save a copy of my 12 word
pass phrase and also tested it by uninstall/reinstall app on mobile. All
good till now.

But I learned that a 12 word back up pass phrase is different from private
key which has to be used to authorize a payment. But on copay during a
payment I am not authorizing specifically, I mean I am not entering my
private key or any such thing to let copay initiate the payment. What all
it's asking is just the recipients address. This is really confusing me.

Eranki Prasanth Sarath

**Comment by dabura667** [comment]
The phrase is your private key. The phrase is saved to your app as data. Every time you send to someone, your app opens the file, reads the phrase, uses the phrase to sign your transaction, sends the transaction.

You do have to enter the phrase if your app is deleted or your phone breaks... but after that, the app stores your phrase on your phone.

You can add an optional password in advanced options. As well as requiring things like fingerprint scanning or whatever, so the app will say "hey wait a second. Before I open this file with your phrase in it, I want you to enter a PIN or password or swipe your finger."

**Comment by dabura667** [comment]
If someone asks for a "WIF private key" they are talking about "Wallet Import Format" which is a format of private key.

Copay's 12 word phrase is a "BIP39 recovery phrase" which is another format of private key.

If you ever need the WIF private keys there are tools to convert your BIP39 phrase into a WIF key.

**Comment by prasanthsarath** [comment]
Thanks a lot for the detailed explanation :-)

Eranki Prasanth Sarath
