### ISSUE TITLE
Verification Needed

### ISSUE THREAD

**Issue by dragonceleste** [bitpay/copay#6453]
Hi i make a payment from Visa in blockchain, but i dont can make other payment. The message i read is
Please bear with us as our exchange partner verifies your payment information. This will only happen once, and you may resume buying or selling bitcoin in 7 day(s). 
I dont understand what i need make.

**Comment by JDonadio** [comment]
Are you using the BitPay Visa card? If it's the case, please contact with help@bitpay.com
