### ISSUE TITLE
Pre Auth hold and incorrect charges

### ISSUE THREAD

**Issue by bangincode** [bitpay/copay#6455]
I made a purchase online for 31.96 USD (30.66 EUR). There is a completed charge on bitpay for 35.36 USD along with a foreign fee of 1.06 USD. There is also a pre Auth hold for 35.03 USD since the day I made the purchase 6 July. Something is not correct here. Please assist

**Comment by sandem1340** [comment]
Pl

**Comment by JDonadio** [comment]
Please, contact help@bitpay.com for BitPay card assistance

**Comment by bangincode** [comment]
Thank you, 
I have emailed them. Should I delete this post?

**Comment by JDonadio** [comment]
Don't worry I'll close it. 

If you have any other problem feel free to reopen it and continue the discussion here.
