### ISSUE TITLE
Spending password recovery 

### ISSUE THREAD

**Issue by ajibadeui** [bitpay/copay#6457]
Please treat this as urgent as possible,.. I forget my spending password,  how can I recover it please.  Thanks in anticipation for your reply

**Comment by dabura667** [comment]
Do you have your recovery phrase written down?

**Comment by gabrielbazan7** [comment]
http://help.bitpay.com/bitpay-secure-bitcoin-wallet/i-forgot-my-wallet-spending-password-what-can-i-do

**Comment by ajibadeui** [comment]
No  I don't

**Comment by gabrielbazan7** [comment]
Sorry, but unfortunately there is nothing we can do. You need you backup phrase.

**Comment by parkermor** [comment]
@ajibadeui 
I can recover the spending password of your wallet if you want need help send me email : anywalletrecovery@gmail.com

**Comment by richardsuns** [comment]
@ajibadeui 
Do you still have the text backup of your wallet?
