### ISSUE TITLE
"Click to send" and all elements are not reacting after setting 1 sat/byte

### ISSUE THREAD

**Issue by RussianSwiss** [bitpay/copay#6459]
BitPay app on macOS Sierra 10.12.5 freezes - "Click to send" and all elements are not reacting after setting 1 sat/byte custom fee.

Checked on two different macs.

UPD: Only app on iPhone the allowed me to send. Thought tx didn't go through immediately.

Still on Mac the bug persists.

**Comment by gabrielbazan7** [comment]
Sorry, I could not reproduce the issue. Also in BitPay app on macOS Sierra 10.12.5.

**Comment by RussianSwiss** [comment]
Issue persists with different wallets on macOS.

**Comment by JDonadio** [comment]
@RussianSwiss can you confirm if your issue is the same related here: https://github.com/bitpay/copay/issues/6704
