### ISSUE TITLE
Wallet settings: last symbol of the name of the wallet goes on the next line

### ISSUE THREAD

**Issue by RussianSwiss** [bitpay/copay#6460]
Wallet settings: **last symbol** of the name of the wallet shown on the next line even if the name of the wallet is very short.

OS: macOS Sierra.

**Comment by gabrielbazan7** [comment]
Could you add an screenshot please ?

**Comment by RussianSwiss** [comment]
Yes, here: https://github.com/RussianSwiss/images/blob/master/copay_name_bug.png?raw=true
