### ISSUE TITLE
Wallet Addresses View Crash WP 10

### ISSUE THREAD

**Issue by gabrielbazan7** [bitpay/copay#6461]
Toff
Friday 06:44 am
 
Settings -> Personal Wallet -> More Options -> Wallet Addresses

Doing so makes the app close itself, 100% reproducible on both the current and the previous version of the app.

Using Lumia 950 XL

Sent from my Windows 10 phone

**Comment by bluethefoxyt** [comment]
is there going to be a fix for this

**Comment by JDonadio** [comment]
We are working on a complete platform migration to Ionic 3. For windows users the experience will be completely new and functional. Hope you understand the delay but we are giving our best to get it up ASAP.

**Comment by cashout1** [comment]
same problem: If I start scan or reading a qr code to send btc - the shut down. There is no way to read the qr code with the camera....

**Comment by JDonadio** [comment]
The recent Windows 10 update (10.0.15063.608) brakes all JavaScript apps using the camera preview. So, you will have to wait for an update of your phone system. You could take a look at the issue here: https://goo.gl/J9Jg35.
