### ISSUE TITLE
Error creating gift card

### ISSUE THREAD

**Issue by jmrondon** [bitpay/copay#6462]
Request id Too long , Max allowed length is 19

**Comment by jmrondon** [comment]
Wallet payment 1PfYgbnKUMggZ57XDBLQ2f4EzcXH5Pm1AE

**Comment by bit-bucks** [comment]
Received same error, Wallet payment 1HJ3YcvonSQLdMnsEoBwcRffEctY1ucNVZ

**Comment by jmrondon** [comment]
![whatsapp image 2017-07-25 at 9 04 41 am](https://user-images.githubusercontent.com/21158478/28573874-21d21f00-711a-11e7-9b21-699e8a520bf7.jpeg)

**Comment by JDonadio** [comment]
Please, send an email to help@bitpay.com and add your invoice id.

**Comment by jmrondon** [comment]
thank you very much @JDonadio
