### ISSUE TITLE
unable to add funds to bitpay debit card

### ISSUE THREAD

**Issue by exx1976** [bitpay/copay#6466]
Downloaded the new version, it says "Could not send transaction.  Server response could not be verified."

**Comment by matiu** [comment]
Hello, have you sent bitcoin before from you wallet? 

Is this is a multisig wallet? Could you send us a screenshot? Thanks.

**Comment by exx1976** [comment]
yes, I have sent funds before.  I'm using the bitpay wallet.  where should I send the screenshot?

**Comment by exx1976** [comment]
I just tried again.  Same error if I select "send max".  If I type in an amount, it worked fine.

**Comment by matiu** [comment]
Hi, we were able to reproduce this problem. It happens for certain amounts. We will send a fix ASAP, version 3.7.1.   As a work around, you can try the topup with a slightly different amount. Thanks.
