### ISSUE TITLE
Blockchain confirmed but didn't receive

### ISSUE THREAD

**Issue by vintrr** [bitpay/copay#6473]
I am expecting a txn of around $2k to my copay wallet and I checked that the txn has 6 confirmations and it is completed but it isn't showing in my wallet for some reason??

My address is: 1PbKkJub6m6m2wqtzZee4H7oq31BaJgJxj

Would appreciate any help

**Comment by gabrielbazan7** [comment]
Hi can you show me the transaction id and also you wallet id ?
