### ISSUE TITLE
Kindly confirm what will happen if hard fork occurs on 1st august 2017

### ISSUE THREAD

**Issue by meetdev8** [bitpay/copay#6475]
Hi, what will happen with copay wallet balance after 1st August 2017?
Will we able to get both bitcoin and bitcoin cash(bitcoin ABC)?

Thanks,
Dev

**Comment by meetdev8** [comment]
So if I will using 12 phrase password to import to bcc then I will have same amount of bitcoin as well?

**Comment by JDonadio** [comment]
Please follow https://github.com/bitpay/copay/issues/6464

**Comment by sushilraghav** [comment]
@meetdev8 @JDonadio @kleetus @saschad @eordano  For 500$, Can you hard-fork of bitcoin at block height of 500888 ,used the BCH reference ,total coins 21210000,and 210000 is pre-mine @saleemrashid  

my email is bitcoinemxmx@gmail.com and skype : sushilraghav
