### ISSUE TITLE
Bcc query

### ISSUE THREAD

**Issue by meetdev8** [bitpay/copay#6476]
So if I will using 12 phrase password to import to bcc to other wallet (which support bcc) then I will have same amount of bitcoin as well in copay?

**Comment by dabura667** [comment]
Sure. If you want to.

**Comment by alexWenhao** [comment]
when the Insight browser can support bcc query？

**Comment by dabura667** [comment]
Currently I only know of this one.
http://blockdozer.com/insight/

Also this one:
https://bch-bitcore2.trezor.io/

**Comment by alexWenhao** [comment]
thx..i meant ,when the bitpay Insight explorer project support bcc query?i want to build it for my project

**Comment by dabura667** [comment]
Bitcore is a Bitcoin project. The Bitpay Insight Explorer will most likely never support BCC, because it is not Bitcoin.
