### ISSUE TITLE
npm run apply:copay getting failed

### ISSUE THREAD

**Issue by LakshmananPonnusmay** [bitpay/copay#6478]
Hi ,

I am trying to run the project in Android, But i am getting error on the commend
npm run apply:copay

Please find attached the log.
[npm-debug.txt](https://github.com/bitpay/copay/files/1179772/npm-debug.txt)

**Comment by JDonadio** [comment]
Try updating your node version:

node v6.10
npm v3.10

**Comment by LakshmananPonnusmay** [comment]
@JDonadio ,
i have the latest version
node v7.4.0
npm v4.0.5

Do i need to downgrade?

**Comment by JDonadio** [comment]
Do you have windows 32 bit?

**Comment by LakshmananPonnusmay** [comment]
@JDonadio , 
My system is 64 bit Windows 7.
