### ISSUE TITLE
Can No Longer Create New Wallet From Trezor Seed

### ISSUE THREAD

**Issue by paintballpanda** [bitpay/copay#6480]
Using Bitpay Chrome App on MacOS.

When trying to create a new bitcoin wallet, and then selecting "new personal wallet", under advanced options the only two choices for a wallet key are "Random" or "Specific Recovery Phase". 

There used to be an option to use a hardware wallet such as a Trezor to create a new wallet but that feature is no longer there. Has this been moved or is the Bitpay/CoPay wallet app no longer supporting this feature?

**Comment by JDonadio** [comment]
I just tried with `v3.7.1` (latest) and the option for trezor is there.

**Comment by JDonadio** [comment]
Could you check your app version and also attach some screenshot? thanks

**Comment by paintballpanda** [comment]
App version is v.3.7.1. Have tried uninstalling and re-installing it, but no change.

<img width="472" alt="screen shot 2017-07-28 at 8 02 07 am" src="https://user-images.githubusercontent.com/13514580/28723382-6d1add64-736b-11e7-9124-673462660866.png">

<img width="471" alt="screen shot 2017-07-28 at 8 01 50 am" src="https://user-images.githubusercontent.com/13514580/28723393-75aceb0c-736b-11e7-8a51-60804ced8e9d.png">

**Comment by paintballpanda** [comment]
Also I did make sure that I have the Trezor Chrome Extension installed.

**Comment by JDonadio** [comment]
We found the issue and will send the fix ASAP. Thanks for report it!

**Comment by paintballpanda** [comment]
Thanks @JDonadio, is there a way to use an older version until a fix is released? I did try downloading the Copay dmg for OSX from a previous version but it had the same issue. Do you know of a version that is unaffected by the bug? Thank you!

**Comment by JDonadio** [comment]
Unfortunately no, the only platform that support HW is the chrome-app.
Don't worry, the chrome-app updates will take just a few hours (maybe less). We are working on that right now.

**Comment by paintballpanda** [comment]
Thank you!

**Comment by JDonadio** [comment]
Can you try now? v3.7.2 should be available.

**Comment by paintballpanda** [comment]
Worked! Thank you so much @JDonadio!
