### ISSUE TITLE
Tab bar disappears when cancel Request Spending Password

### ISSUE THREAD

**Issue by ajp8164** [bitpay/copay#6482]
Jeremie reported this.

Steps to reproduce.

1. Open app
2. Click Settings
3. Tap any wallet
4. Notice tab bar is visible
5. Tap Request Spending Password
6. Tap Cancel button
7. Notice tab bar is no longer visible

Looks as though there is a bad keyboard interaction during the step 6.

**Comment by JDonadio** [comment]
In `Ionic` the directives to hide/show the tabs are firing at `beforeEnter` and `beforeLeave` event. Sometimes when you are leaving a view (showing tabs) and navigate to a next one (hiding tabs) there is a `hide tabs` event triggered, and if you navigate to a next or previous (showing tabs) both events `beforeLeave/Enter` seems to be called at the same time. I think that is the cause for the tab bar issues.

**Comment by ajp8164** [comment]
Not the same as #5597 but the problem in #5597 was made irrelevant/obsolete due to the changes to the session log view (removal of the tab bar).
