### ISSUE TITLE
recovering wallet

### ISSUE THREAD

**Issue by Riceman1** [bitpay/copay#6484]
I lost my spending password.  So in order to access my wallet, do i need to uninstall the Bitpay app, and then reinstall the app,  Tthen restore the wallet with the original 12 word phrase i set the wallet up with when i first created it?  

Thanks

**Comment by gabrielbazan7** [comment]
Just, delete the wallet with the spending password and then yes, restore it with the 12 words phrase.

**Comment by Riceman1** [comment]
Thanks.  It is a little scary to delete the wallet.  Is it possible to create another wallet first? Restore, and then delete the old wallet?

**Comment by gabrielbazan7** [comment]
Try to import with the words. If you get "Wallet already in Copay". That means the phrase is ok and you can delete your wallet.

**Comment by Riceman1** [comment]
Thanks for the clarification and the help!  I get a message that says "Wallet Recovery Phrase is Invalid".  Although I am sure it is valid. Is my next option to Export the Wallet?  If i do that and then import will there still be a spending password, or does that get reset? I dont know if it make a difference, but I am on an older version of BitPay 1.3.6.

**Comment by Riceman1** [comment]
Or do I Backup the wallet instead of Exporting?

**Comment by JDonadio** [comment]
@Riceman1 if you delete your wallet and import it from any backup format (12 words, file/text, QR) the spending password will be removed.

About the `Wallet recovery phrase is invalid` message, for some reason is not recognized, you can check the complete list word for your language [here](https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md)

**Comment by Riceman1** [comment]
OK, perfect and thank you for all the help.  The original backup phrase was working, but I typed it in with all caps the first time.  One question.  Does the backup phrase allow me to import the wallet to ANY device?  Say I create the phrase with a new wallet on my laptop, would I then be able to import the wallet to my phone, or another computer?  If so, what happens to the original wallet balance? I assume it is put to zero. Do I have to delete the wallet first? And one more question.  Say my computer is stolen or simply dies. Would this process work to regain access to my BC on a new computer or phone?  Thanks again for ALL the help!

**Comment by gabrielbazan7** [comment]
>  Does the backup phrase allow me to import the wallet to ANY device? 

Yes

>  If so, what happens to the original wallet balance?

Not sure, what do you mean. But, you will have all your money in your new phone

> Do I have to delete the wallet first?

No, you could have the same wallet in different devices at the same time.

> Would this process work to regain access to my BC on a new computer or phone?

Yes

**Comment by Riceman1** [comment]
Great!  Thanks.  I didnt realize I could have the same wallet on different devices.  Cool!  That was what I meant by does it return the old wallet balance to zero.  I didnt realize that the wallet is synced between devices.
