### ISSUE TITLE
How to use Copay with cold storage ?

### ISSUE THREAD

**Issue by zonkazane** [bitpay/copay#6487]
I am new to Copay, and wallets in general.
Somewhere I read that Copay supports air-gap transactions from cold storage, but I did not find documentation to support that..

I presume "supporting cold storage" means, among other things:
-  Sign a transaction on an off-line computer, transfer signature information with USB stick, and broadcast the transaction from an on-line machine.
-  Being able to transact with keys important from a paper wallet.
- Createa 'watch wallet' to follow what is happening at the public address of a paper wallet.

Can Copay do the above, and/or support cold storage in different ways ?

**Comment by BGalliotti** [comment]
Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will happy to help you.
Thanks.

**Comment by boviz** [comment]
That would be a very important and nice feature.
