### ISSUE TITLE
Newbie: Windows copay wallet, doesnt have security on the program? just opens to see wallet items on my pc. 

### ISSUE THREAD

**Issue by minsikau** [bitpay/copay#6488]
Wondering why copay wallet just opens in windows 10? Should this not have at least minimal security? 
I have created the wallet and it has a wallet storage with zero in it.  However this is accessible just opening the program. 
How is this secure?

**Comment by JDonadio** [comment]
We have many security capabilities in the code. But in wallet features you have:

* Spending password: to encrypt your private key and request the password for any sensible move in the wallet like send funds, export the wallet, access to the recovery phrase, etc.
* Multi-sig wallets: that require co-signers to make payments
* Read-only wallets: which doesn't have the private key, so it's only for check and create proposals but cannot sign anything

**Comment by stephanefr** [comment]
I agree that the access to actions (send/receive) etc. are password protected.

But after launch, the app displays the amount stored in the wallet (under the wallet name).

That is not good at all, anyone who can see the screen when the app is on can see how much money I own.

**Comment by dabura667** [comment]
Long click the balance.

**Comment by stephanefr** [comment]
Excellent ! Thank you !
