### ISSUE TITLE
Always Says 'Insufficient funds'. Not able to transfer my BTC..kindly help plz !!

### ISSUE THREAD

**Issue by yashbakshi27** [bitpay/copay#6500]
Hi, i joined Copay yesterday & have created my new Personal Wallet. I received 8 BTC into my Personal wallet. But now every time i try to transfer BTC it always says 'Insufficient Funds'...Why So..??? I have received 66 confirmations for my BTC transfer to my wallet...Plz help ASAP..thnx..!!

**Comment by JDonadio** [comment]
What platform are you running and what version? thanks

**Comment by flagirl** [comment]
How was this issue resolved? I am having the same issue!

**Comment by JDonadio** [comment]
Explain your case and add some screenshot please

**Comment by yuryzar** [comment]
por favor de una solucion a este problema, a mi me pasa lo mismo

**Comment by JDonadio** [comment]
El error de fondos insuficientes es debido a que las transacciones que recibiste son tan mínimas que se convierten en inutilizables. Y esto es porque para crear una transacción de cierto monto (o todo el disponible) hay que usar varias (o todas) las entradas que recibiste y eso repercute en el tamaño de la transacción y la comisión necesaria (fee) para que sea minada.
