### ISSUE TITLE
Invisible transaction

### ISSUE THREAD

**Issue by arruah** [bitpay/copay#6501]
Yesterday I created a transaction.
https://insight.bitpay.com/tx/9af8eab3e81a8d12ae2933ee56b1e3ace1451214de94239eb63d17b2665f7172 
This transaction is in insight but it is not in blockchain.info.
If this transaction is not confirmed before the BCC fork and return to my wallet, will I have the same amount of BCC?

**Comment by JDonadio** [comment]
https://blockchain.info/tx/9af8eab3e81a8d12ae2933ee56b1e3ace1451214de94239eb63d17b2665f7172
