### ISSUE TITLE
Bitcoin Cash

### ISSUE THREAD

**Issue by fluidirie** [bitpay/copay#6504]
Hi,

Can you let me know how to claim my Bitcoin Cash balance on Copay wallet and how to go about selling it etc?

Thanks!

**Comment by iamlebing** [comment]
Same ask, thank you very much.

**Comment by insiderq** [comment]
i‘d like to specify details, so if i have copay multisig wallet, how to export private keys to be able to manually send the transaction? 

I know you have a js tool for multisig spending, can i use that not to send transaction but to receive it in a plaintext to brodcast on bitcoin cash network? If yes then what about replay protection?

**Comment by msfelipe88** [comment]
Waiting for the answer

**Comment by iamlebing** [comment]
I tried successfully as your reference. I empty the wallet first and use the seed in another BCC-support wallet, import the previous seed, BCC showed up . Done.

**Comment by matiu** [comment]
Hello,

Here is a procedure you can use now, for non-multisig wallets (personal wallets):

1- Move all your bitcoins to from your current Copay/Bitpay wallet to a new Copay/Bitpay wallet
 > (add a new wallet, back it up in a safe place, then go to send, select the new wallet, and then select "send max" and select the wallet you want to claim for BCC).

Because BCC implements transaction replay protection, moving your funds after the fork to a new 
wallet will generate a transaction that is invalid on the BCC chain. so, you BTC will move to your new wallet, and your BCC will stay on the old one.

2-  Import your old wallet seed (balance should be 0 in Copay) to a BCC compatible wallet (see wallets at https://www.bitcoincash.org/). 

So, your BTC will stay on your new wallet in Copay/Bitpay App, and your BCC will be on the BCC compatible wallet.


===

We are working to adapt our recovery tool https://bitpay.github.io/copay-recovery/ to support BCC. When that work is finished, you will be able to move your BCC balance with it, even for multisig wallets. Please follow the issue progress at: 

https://github.com/bitpay/copay-recovery/issues/49

**Comment by emx0r** [comment]
Hi Matiu,

_2- Import your old wallet seed (balance should be 0 in Copay) to a BCC compatible wallet (see wallets at https://www.bitcoincash.org/)._

This step is quite a hassle. I tried to do it in Electron Cash wallet but Copay seed is not compatible. Also when I exported my private key and tried the import BCC shows 0 balance.

Do you know which BCC/BCH wallet currently supports Copay SEED?

Thank you

**Comment by BabaJon108** [comment]
Hi,
Can you help me wiht this transition please?
I just caught onto the fact that MUtibit HD is really outdated and doesn't have support anymore. I ran into a nice tutorial they made 5 days ago about transitioning to an Electrum wallet, Now, I am wondering how to transition safely to make sure I don't lose my Bitcoin cash (BCC). I just bought more before the fork. I have my seed words.

Here is what I was thinking trying:

Upload my seeds to my new electrum wallet.

Transfer the Bitcoins (BTC) to a different Electrum wallet ( on another computer)

Then use my MULtibit HD seeds ( same as my new electrum right?) to  upload my BCC on the Bitcoin cash wallet.

Thanks a million for any help, tips or inputs. 

QUESTION: Should I even bother uploading my seeds from Multibit to Electrum or I could just transfer directly my BTC to a different Electrum wallet ?

**Comment by ngellner** [comment]
Matiu, in step 2, can I just import my wallet seed into Bitfinex directly, or do I have to first import it into a BCC compatible wallet and then from there put it on Bitfinex? Thanks.

**Comment by mhagelstrom** [comment]
ngellner, Bitfinex (or any other exchange) does not let you import a private key seed. You need to import your seed on a wallet and send the funds with a regular transaction.

**Comment by emx0r** [comment]
I finally found a guide how to get BCH. It's quite easy to follow: https://checksig.org/how-to-split-your-bcc-bch-from-your-btc-xbt-using-electrum-cash-cb91ca4a5961

All my BCH are now in my Electron Wallet

**Comment by ngellner** [comment]
Are there any legitimate mobile wallets we can transfer our BCH into yet?

**Comment by dabura667** [comment]
>  I tried to do it in Electron Cash wallet but Copay seed is not compatible.

You have to choose BIP39.

**Comment by SalenaJason** [comment]
hi im fairly new to this so a lot of the tech terms go over my head, wondering if someone can help me retrieve my BCC ? i had my BTC saved in a bitaddress.org paper wallet as i wasn't aware of nor had time to buy a nano s ledger or something like that before the fork. 
i have transferred my BTC out of the paper wallets but with the instructions above am still struggling to retrieve my BCC, any tips in laymen's terms would be greatly appreciated, thanks jason

**Comment by dabura667** [comment]
@SalenaJason If your bitcoins were in the paper wallet at the time of the fork, then your BCC are still in your paper wallet. Electron Cash allows you to create a new wallet with private keys directly, so just paste your private key in when starting a new wallet.

**Comment by SalenaJason** [comment]
Hi


Thank you I will look into it now

SalenaJason

On 6 Aug 2017, at 18:08, Dabura667 <notifications@github.com<mailto:notifications@github.com>> wrote:


@SalenaJason<https://github.com/salenajason> If your bitcoins were in the paper wallet at the time of the fork, then your BCC are still in your paper wallet. Electron Cash allows you to create a new wallet with private keys directly, so just paste your private key in when starting a new wallet.

**Comment by nemestrinus** [comment]
You can use your backkup seed phrase from copay/bitpay to recover your wallet using Coinomi. Open just the bitcoin wallet at first, then after your wallet opens, add the BitcoinCash wallet using +COINS from the menu., Make sure you use the advanced settings option and enter M/44H/0H/0H on the Derivation Path.

**Comment by matiu** [comment]
Copay/Bitpay app  recovery tool supporting Bitcoin & Bitcoin cash has been deployed. You can use it at https://bitpay.github.io/copay-recovery/  source at  https://github.com/bitpay/copay-recovery.

You can check and recover you BCH balance using that tool, for single or multi signature wallets.

I am opening a new ticket regarding Bitcoin Cash support on Copay itself at:  https://github.com/bitpay/copay/issues/6557

**Comment by vinicius03** [comment]
After scans my wallet and I tried to transfer it says: Could not build tx: bitcore.ErrorTransactionFeeErrorTooSmall: Fee is too small: expected more than 20000 but got 10000 - For more information please see: https://bitcore.io/api/lib/transaction#serialization-checks

**Comment by matiu** [comment]
@vinicius03 That was because the resulting TX had more that 1KB. Could you please try again, we just updated to a new version.

**Comment by insiderq** [comment]
@matiu what if it is 2-of-3 multisig wallet, can i use copay recovery if i have only 2 of mnemonic phrases?

**Comment by vinicius03** [comment]
@matiu, you're right, this is a 2015 wallet, lots of addresses used, when I sent the funds to other BTC address before the fork the transactions itself  cost 0.02, anyway now it worked, thanks a lot.

**Comment by fluidirie** [comment]
Hi,


Just to check, I presume this will still work if I move all my BTC to another external wallet not on Copay?


Thanks,

Aziz


________________________________

**Comment by JDonadio** [comment]
@fluidirie if you had balance before 1 Aug in that seed, you can move all your BTC out and your BCH will still be in the same seed.

**Comment by fluidirie** [comment]
Hi there,


I have done what you said am am now trying to import my private keys into a new Bitcoin Cash compatible wallet. However, it keeps saying the private key is not recognised, even though I have checked this a number of times and am using the right private key. The balance in my Copay wallet is 0 BTH and I send the max amount to another wallet already.


Can you help?


Is there any other way you can help me access my BTC?


Thanks,


Aziz


________________________________

**Comment by fluidirie** [comment]
Hi there,


I have managed to get by BCH balance in my Copay wallet. However, I cannot send the BCH balance to another external wallet. I go into the send screen, put in the wallet address where I want to send it, but then it takes me to a another screen that seems to just be frozen. It has 'sending' on it, and it looks like a field to enter another wallet address but I cannot type anything in. Is there a problem with the Copay site?


Thanks,


Aziz


________________________________

**Comment by JDonadio** [comment]
@fluidirie please check this out: https://github.com/bitpay/copay/wiki/COPAY---FAQ#sending-bch-shows-error-please-enter-a-valid-address

**Comment by fluidirie** [comment]
Hi,


No I think there is a problem with the Copay wallet. I tried sending it to another BCH address (begins with 1C) and again the wallet just freezes on the next 'Confirm' screen after I type in the address and amount I wish to send. Please can you look into this.


Thanks,


Aziz


________________________________

**Comment by JDonadio** [comment]
Both Copay as the Recovery tool accepts BCH addresses starting with C or H, which is a new convention to prevent errors (https://support.bitpay.com/hc/en-us/articles/115004671663-BitPay-s-Adopted-Conventions-for-Bitcoin-Cash-Addresses-URIs-and-Payment-Requests)

If you need to send to "old" addresses, and you are SURE those are BCH addresses, you can "translate" them using the BCH Translator tool: https://bitpay.github.io/address-translator/

Note: if you have copied your destination address, just use the `bitcoincash:` prefix in the send input field like this:

https://github.com/bitpay/copay/issues/7003#issuecomment-340542357

**Comment by fluidirie** [comment]
OK thanks, using the bitcoincash coverter in the app did the trick!


Kind regards,


Aziz


________________________________

**Comment by fluidirie** [comment]
One other question is that I still have a balance in my Copay wallet of BCH that I cannot spend/use. The reason is that only 1 blockchain has confirmed it. How long will this take to confirm as it's been  weeks since I originally claimed/transferred it.


Thanks,

Aziz

________________________________

**Comment by blockpool** [comment]
We have a 3 of 3 multi sig wallet and have a BCH balance that needs to be moved out of the Copay wallet. 2 of the 3 users can sign the transaction but the 3rd had imported the wallet into a ledger nano. He cannot now see the transaction to sign because of a BIP issue between Ladger and Copay. Is there any solution to this?

**Comment by pmartynov** [comment]
Same issue as @insiderq and @blockpool mentioned. I have 2-of-3 multisig wallet and 2 signatures out of 3. Can I restore my BCH?
