### ISSUE TITLE
How to export wallet to bitcoinqt core client?

### ISSUE THREAD

**Issue by tenk** [bitpay/copay#6507]
Hello,

I'm having a difficult time exporting my wallet into the core client. I've tried importing the private key via console and it does not seem to register. I tried exporting the wallet.dat file and replacing it in core but that does not work either. I would appreciate it if you could guide me through the process. 

Thank you.

**Comment by JDonadio** [comment]
Sorry but we cannot guide you through the import process issues for another wallet client. You need to contact to the `bitcoinqt` support team.
