### ISSUE TITLE
Seed password

### ISSUE THREAD

**Issue by tommyquite** [bitpay/copay#6508]
I think I now the answer to this, but for the sake of secruity I wanted to double check. As it isn't the case with many other wallets. Couldnt find this in the FAQ, while it seems to be a pretty important security topic.

Am I correct in assuming that when I  select "add a password" when creating a new wallet on Copay. The seed of this wallet is protected with a password.

So anyone that obtains my seed, will also need to know my password in order to steal my wallet? And I will always need a password to recover my own wallet to? Not just a seed or private key?

Thanks in advance.

Best Regards,

Tom

**Comment by JDonadio** [comment]
> So anyone that obtains my seed, will also need to know my password in order to steal my wallet? 

Exactly

> And I will always need a password to recover my own wallet to? Not just a seed or private key?

Yes. Your private key will be derived from your seed, but to derive it you'll need the password first.

**Comment by JDonadio** [comment]
You can try it creating a new one in testnet, send some funds there and try the import process so you can be sure how it works.

**Comment by emx0r** [comment]
well I'm more like interested what is the compatibility situation with the seed itsefl. I tried to import copay seed to Electrum but it did not work. I googled various issues of similar nature for different wallets. So my question is: how do I know what wallets are able to handle Copay seed?

**Comment by JDonadio** [comment]
Any wallet which support BIP39

**Comment by emx0r** [comment]
thanks, any recommendations? Because it's hard to find anything

**Comment by JDonadio** [comment]
I'm not sure, try with https://mycelium.com/
