### ISSUE TITLE
Copay/Trezor "error window blocked"

### ISSUE THREAD

**Issue by hb998277** [bitpay/copay#6510]
When I try to create a wallet using Wallet Key = Trezor, I get the a error popup that says:

Error
Window blocked

This is on a windows system.  I've tried allowing popups, javascript, flash and everything else in chrome settings.  Strangely, it works on my laptop which pops open a window asking me to insert my Trezor.  The chrome settings are the same between my laptop and desktop since I'm logged in as the same chrome user.

I also tried disabling my antivirus, windows defender, and any other security feature I could find.

**Comment by JDonadio** [comment]
Hardware wallets are only supported on `chrome-app` extension. You'll not be able to run it on other platform.

**Comment by uvasili** [comment]
I have the same problem. The Copay functionality for shared wallets using Trezor as wallet key has some issues. tried to re-install copay chrome-app, and allowed pop-ups but I still get the same "error window blocked" message.

**Comment by hb998277** [comment]
This problem occurs using the chrome extension.

**Comment by JDonadio** [comment]
Did you launch the Trezor extension before the creating wallet process?

**Comment by uvasili** [comment]
yes, I have launched the Trezor Chrome extention and then open Copay.
