### ISSUE TITLE
Bitcoin cash

### ISSUE THREAD

**Issue by Amansoni97** [bitpay/copay#6512]
I had transferred my Bitcoins to Copay wallet before 1st August. Since, the split has occurred, I wanted to know whether I will have the Bitcoin Cash of the equivalent amount.
If yes, How do I claim it?,

**Comment by emx0r** [comment]
Wondering the same thing. You should have your BCH. If you want to check it go to https://blockchair.com/ and put in the address where you received some BTC before the split. It should show you how much BCH you have on it. The other thing is how to claim it. I have not found any compatible wallet where I could put my seed from Copay, so currently I have no way how to access my BCH funds

**Comment by JDonadio** [comment]
Please follow https://github.com/bitpay/copay/issues/6504

**Comment by nemestrinus** [comment]
You can use your backkup seed phrase from copay/bitpay to recover your wallet using Coinomi.  Open just the bitcoin wallet at first, then after your wallet opens, add the BitcoinCash wallet using +COINS from the menu., Make sure you use the advanced settings option and enter M/44H/0H/0H on the Derivation Path.
