### ISSUE TITLE
Amazon Gift Card

### ISSUE THREAD

**Issue by CryptoBr0** [bitpay/copay#6518]
Hello. One hour ago I buy amazon gift card, but not recieve it. I try 2 times, but also see that bitcoin send from my copay wallet, and I not get my two amazon gift card... ;( Please repair it, and give me my card. Thanks.

**Comment by gabrielbazan7** [comment]
Please email help@bitpay.com with the following details so we can assist you further.
 Wallet ID - To get your Wallet ID, open your BitPay application, then go to Settings > Wallets & Integrations > More Options > Wallet Information. 

It would also be helpful for you to provide the bitcoin transaction details related to the specific Amazon gift card purchase
