### ISSUE TITLE
Unconfirmed transaction

### ISSUE THREAD

**Issue by mghostl** [bitpay/copay#6520]
Hi, I have send my bitcoins but with the low transaction fee. So my order is unconfirmed for a few days. How can I cancel my transaction ? Please help me with my problem

**Comment by JDonadio** [comment]
You cannot cancel a broadcasted transaction but it could be dropped by the mempool and go back to your wallet but unknowing the time.

**Comment by mghostl** [comment]
I find out that if transaction unconfirmed blockchain community doesn't know about this transaction. Only copay knows about it. So copay can decline it . It isn't right ? 

Отправлено с iPhone
