### ISSUE TITLE
12 word recovery jam on bitpay multisig

### ISSUE THREAD

**Issue by tegabitz** [bitpay/copay#6522]
hello github, I'm sad to report that i have an issue with over $700 possibly lost. Its a multisig wallet. A 3-4 wallet(bitpay). as you can probably tell atleast three signatures are needed to work with the funds, but i currently have just two signatures, the other two...well lets just say they are the reason i am seeking your assistance. one of the faulty party atleast has his recovery phrase which isn't working, the rp has a password as well, nothing working and the last person doesnt have her's. really annoying situation. please help, i know you are all technical, i really need help. please find time to help, please.

**Comment by tegabitz** [comment]
so the way out i see here is for my friend's recovery phrase to work. which isn't happening. help please. bitpay support haven't been able to assist.

**Comment by fnegongo** [comment]
Hi there 
I was having a phone and get lost were i  download copay app and there was my fund.now I buy new phone and download copay app but I can't find my fund .what can I do to recover my fund.please is very urgent help

**Comment by dabura667** [comment]
"Import Wallet" with the phrase should add them back to the multisig.

They probably wrote down their phrase incorrectly. Or if they have many other phrases from other wallets, they are probably entering the wrong phrase (maybe one for their breadwallet etc.)

What error is displayed when your friend says its "not working"?

**Comment by tegabitz** [comment]
Yea I'm guessing that's what's wrong, the order of the phrases but my friend doesn't agree it's wrong.  When we try using the Rp, it says invalid

**Comment by fnegongo** [comment]
Now what can do?

**Comment by tegabitz** [comment]
That's why I started this thread, I need help as well. Funds trapped.

**Comment by jorgeluna** [comment]
My phrases do not work either, according to what I researched the other platforms only accept phrases in Spanish, I would like to request to be able to reset these phrases and pass them to English, so we can export our wallet and get the bch, which will not happen to you as Coimbase that had a demand to not support the bch, formally asks for a solution to this problem

**Comment by dabura667** [comment]
@jorgeluna Electrum accepts Spanish BIP39 phrases if you activate BIP39 during recovery... so Electron Cash (the BCH fork of Electrum) should recover your Spanish BIP39 phrase fine.

> I would like to request to be able to reset these phrases and pass them to English

This is impossible. You need to create a new wallet with your language set to English and send the money to the new wallet.

**Comment by jorgeluna** [comment]
@dabura667 How do i care about electrum

**Comment by jorgeluna** [comment]
I already did the process with electrum but now I made the process with elctron cash and I do not appear the bch someone can help me

**Comment by tegabitz** [comment]
Hello guys I know we all have complaints but I started this thread for bitpay/copay multisig recovery phrase invalid issue. As I have $800 now being trapped. What's the solution.

**Comment by dabura667** [comment]
> What's the solution.

Your friend entering the correct phrase into the import wallet function. If they can't do that, you're out of luck.

**Comment by tegabitz** [comment]
The phrase is invalid, isn't there any hack for this, we need one more signature to access our shared wallet funds. Funds needed to pay off some folks. We will give out $100 to anyone who helps us. I know its not much but help.

**Comment by tegabitz** [comment]
In the mean time maybe I might be able to withdraw my bcc from this same wallet. Who has a clear idea on how to proceed about withdrawing bitcoin cash.  I don't think the multisig wallet security will affect the Bcc making it easy to get without multiple signatures.

**Comment by tegabitz** [comment]
Remember I'm talking about bitpay wallet here. Thanks. I anticipate some fruitful response

**Comment by jorgeluna** [comment]
I have the solution to export the btc of copay and import them in another wallet to claim the bch

**Comment by jorgeluna** [comment]
@tegabitz  
I have the solution

**Comment by tegabitz** [comment]
What wallet do I use then.

**Comment by jorgeluna** [comment]
@tegabitz  
I helped you get them out and claim the bch, you offered a reward

**Comment by jorgeluna** [comment]
whatsapp +57 3108771752  Solved twelve word error in copay

**Comment by tegabitz** [comment]
Lol, I haven't been able to do anything. I don't see how exporting from bitpay to copay will help.

**Comment by jorgeluna** [comment]
Cost 0.03 btc and you write to whatsapp +57 3108771752 and I solve the problem of bitpay and copay

**Comment by tegabitz** [comment]
cycle basic grape major leader crowd pride wish grab steel average search

Password attached to it is Alameen11 

Recovery phrase that's invalid. Please help.

**Comment by JDonadio** [comment]
@tegabitz you **never** share your keys, even if for some reason you couldn't make it work. If someone have access to your keys then can use your funds.

**Comment by tegabitz** [comment]
Okay..just getting damn too frustrated.

**Comment by jorgeluna** [comment]
I solved the problem, they contributed among all and I helped them to remove their bch
+57 3108771752 wht

**Comment by parkermor** [comment]
@tegabitz 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
