### ISSUE TITLE
Issue when compiling copay - Doesn't find the keystore

### ISSUE THREAD

**Issue by toxicologist** [bitpay/copay#6523]
When building Copay for android, I've managed to successfully run:
`npm run clean-all`
`npm run apply:copay`

However, on `npm run final:android`, after being requested a keystore passphrase, I get the following error:

`jarsigner error: java.lang.RuntimeException: keystore load: /home/alex/copay/../copay.keystore (No such file or directory)`

The full logs (starting from the error) are:

 rm -f platforms/android/build/outputs/apk/android-release-signed-aligned.apk; jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ../copay.keystore -signedjar platforms/android/build/outputs/apk/android-release-signed.apk  platforms/android/build/outputs/apk/android-release-unsigned.apk copay_play && ../android-sdk-macosx/build-tools/25.0.3/zipalign -v 4 platforms/android/build/outputs/apk/android-release-signed.apk platforms/android/build/outputs/apk/android-release-signed-aligned.apk`

Enter Passphrase for keystore: 
jarsigner error: java.lang.RuntimeException: keystore load: /home/alex/copay/../copay.keystore (No such file or directory)

npm ERR! Linux 4.10.0-28-generic
npm ERR! argv "/usr/bin/nodejs" "/home/alex/copay/node_modules/.bin/npm" "run" "sign:android"
npm ERR! node v6.11.2
npm ERR! npm  v2.15.12
npm ERR! code ELIFECYCLE
npm ERR! copay@3.7.1 sign:android: rm -f platforms/android/build/outputs/apk/android-release-signed-aligned.apk; jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ../copay.keystore -signedjar platforms/android/build/outputs/apk/android-release-signed.apk  platforms/android/build/outputs/apk/android-release-unsigned.apk copay_play && ../android-sdk-macosx/build-tools/25.0.3/zipalign -v 4 platforms/android/build/outputs/apk/android-release-signed.apk platforms/android/build/outputs/apk/android-release-signed-aligned.apk
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the copay@3.7.1 sign:android script 'rm -f platforms/android/build/outputs/apk/android-release-signed-aligned.apk; jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ../copay.keystore -signedjar platforms/android/build/outputs/apk/android-release-signed.apk  platforms/android/build/outputs/apk/android-release-unsigned.apk copay_play && ../android-sdk-macosx/build-tools/25.0.3/zipalign -v 4 platforms/android/build/outputs/apk/android-release-signed.apk platforms/android/build/outputs/apk/android-release-signed-aligned.apk'.
npm ERR! This is most likely a problem with the copay package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -f platforms/android/build/outputs/apk/android-release-signed-aligned.apk; jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ../copay.keystore -signedjar platforms/android/build/outputs/apk/android-release-signed.apk  platforms/android/build/outputs/apk/android-release-unsigned.apk copay_play && ../android-sdk-macosx/build-tools/25.0.3/zipalign -v 4 platforms/android/build/outputs/apk/android-release-signed.apk platforms/android/build/outputs/apk/android-release-signed-aligned.apk
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs copay
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls copay
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/alex/copay/npm-debug.log

npm ERR! Linux 4.10.0-28-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "final:android"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! copay@3.7.1 final:android: `npm run final:www && npm run build:android-release && npm run sign:android && npm run run:android-release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the copay@3.7.1 final:android script 'npm run final:www && npm run build:android-release && npm run sign:android && npm run run:android-release'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the copay package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run final:www && npm run build:android-release && npm run sign:android && npm run run:android-release
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs copay
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls copay
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/alex/copay/npm-debug.log

**Comment by toxicologist** [comment]
Also, for the record, creating a copay.keystore file doesn't help either:

`Enter Passphrase for keystore: 
jarsigner error: java.lang.RuntimeException: keystore load: null
`

**Comment by nohea** [comment]
I don't think you will get the copay.keystore file, as that would allow you to publish your version to the Google Play store. 

If you want to build and run your own version, you can copy/install your apk file as a sideload to your android device.
