### ISSUE TITLE
After the fork

### ISSUE THREAD

**Issue by RasoulAM** [bitpay/copay#6525]
Hello
Forgive me if my question is trivial. Is it safe to execute transactions after the 1st of August fork? Also, does Copay have anyway of accessing Bitcoin Cash as well?

**Comment by JDonadio** [comment]
>  Is it safe to execute transactions after the 1st of August fork? 

Of course, everything is working well.

> Also, does Copay have anyway of accessing Bitcoin Cash as well?

Not for now. But you can use your seed to import your wallet in some BCH software.

**Comment by JonSymons** [comment]
> But you can use your seed to import your wallet in some BCH software.

Can you suggest a BCH wallet where that is possible? I haven't been able to find one. Thank you.

**Comment by JDonadio** [comment]
Unfortunately I can't recommend you one, but I hear about `Coinomi` and `Electron Cash` or something. Hope that helps.
