### ISSUE TITLE
Last 2 versions lack the Android .apk

### ISSUE THREAD

**Issue by IzzySoft** [bitpay/copay#6526]
Looks like it was forgotten. Would you be so kind to add them? Thanks!

**Comment by IzzySoft** [comment]
@JDonadio Just closed without a fix or explanation? I still see no `.apk` on v3.8.2 (currently "latest") release. Would be nice for F-Droid users to find the up-to-date APK [here in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.bitpay.wallet) :wink:

**Comment by JDonadio** [comment]
Sorry, I didn't check it for the latest version. We'll upload the apk ASAP.

**Comment by IzzySoft** [comment]
@BGalliotti So I take it you decided to no longer publish an Android version; I've removed it from my repo as well.

**Comment by BGalliotti** [comment]
@IzzySoft  yes as the development team has confirmed me, we are no longer publishing the .apk.
Thank you for your interest and support.
Regards

**Comment by BGalliotti** [comment]
#

**Comment by IzzySoft** [comment]
Thanks for the feedback and explanation, @BGalliotti ! It's always a bit confusing if an issue gets closed without that :wink:

**Comment by BGalliotti** [comment]
Not a problem @IzzySoft 
Best regards
