### ISSUE TITLE
bitaddress.org paper wallet / before soft fork BCC retrieval advice as i can find non, thanks  

### ISSUE THREAD

**Issue by SalenaJason** [bitpay/copay#6527]
hi im fairly new to this so a lot of the tech terms go over my head, wondering if someone can help me retrieve my BCC ? i had my BTC saved in a bitaddress.org paper wallet as i wasn't aware of nor had time to buy a nano s ledger or something like that before the fork.
i have transferred my BTC out of the paper wallets into the copay ipad app and then over to coinspot, 
but with the instructions above/ on the other page on this site i am still struggling to retrieve my BCC, any tips in laymen's terms would be greatly appreciated,
ok so ipad copay app, its updated, bitaddress.org paper wallet, based in Australia,
the copay app has been freezing and logging me out a lot, i don't know if this is contributing to the problem or not.
thanks Jason.

**Comment by JDonadio** [comment]
You must to find a BCH wallet and import your seed/private key there to see your BCH balance. Copay doesn't support it for now
