### ISSUE TITLE
follow up question 

### ISSUE THREAD

**Issue by SalenaJason** [bitpay/copay#6529]
Hi Dabura667,
thanks for your email and advice, unfortunately the GitHub pages are way out of my league of understanding. its like a different language so i have no reference points to work from. 
the GitHub site i was reading is bran new, do you know if it will become more user friendly and that way i can just hold off until then to retrieve my BCC. thanks again for your time

**Comment by dabura667** [comment]
http://electroncash.org/

Use this, recover wallet, paste your paper wallet private key.

What does any of that have to do with Github?

**Comment by SalenaJason** [comment]
Hi Dabura


im guessing nothing ? i was trying to follow but lost my way lol, i will try again, thank you


Kind regards

Salena & Jason
ph: (S) 0477663338
ph: (J) 0400956911
E: salenajason@hotmail.com


________________________________

**Comment by SalenaJason** [comment]
Hi Dabura


yeah thats where i went, i downloaded the one for the mac twice but after that i got lost and i thought it was GitHub. i did go onto there site and message them but this olds school commodore 64 looking programs confuse me.



Kind regards

Salena & Jason
ph: (S) 0477663338
ph: (J) 0400956911
E: salenajason@hotmail.com


________________________________
