### ISSUE TITLE
textNoSuggestions missing on "Create Personal Wallet" mnemonic but present on "Import Wallet"

### ISSUE THREAD

**Issue by westonal** [bitpay/copay#6531]
Saw:

"Create Personal Wallet" makes suggestions and this also stores the mnemonic words and order in the suggestion cache. "Import wallet" mnemonic field does not do this. 

Expected:

Consistency between the two, and mnemonic fields to not write to cache.

Presumably a failure to have `android:inputType="textNoSuggestions"` on "Create Personal Wallet" field.

**Comment by JDonadio** [comment]
Good catch, thanks for report it!

**Comment by westonal** [comment]
@cmgustavo Was it fixed?
