### ISSUE TITLE
UNO online wallet

### ISSUE THREAD

**Issue by svi-kr** [bitpay/copay#6535]
I opened an online wallet on 6/21/2017. On 7/29, 8/2, and 8/3/2017  deposits of Unobtanium were made.
The location I had gone to, to log in was http://hydra-uno.cryptap.us/%20class=#!/  But it has been down for service since prior to the Bitcoin fork on 8/1/2017.  Where do I go to find my wallet and contents?

**Comment by dabura667** [comment]
This is the wrong place to ask.

**Comment by svi-kr** [comment]
The cryptap site sent me here. Any suggestions?

**Comment by JDonadio** [comment]
Sorry but we couldn't help with that problem. You must contact with UNO support team.
