### ISSUE TITLE
Help! How to restore the co-owner of the wallet?

### ISSUE THREAD

**Issue by Newwaybiz** [bitpay/copay#6538]
I have a common purse. I lost the second device on which was installed Copai how to restore the co-owner ??? I can not confirm the translation!

**Comment by JDonadio** [comment]
Can you clarify what co-owner means? Do you have a multi-sig wallet and the other copayer has lost their device?

**Comment by Newwaybiz** [comment]
Yes, I lost the second device. And I only have a share from the first.

**Comment by JDonadio** [comment]
The only way to recover your funds is with the backup. If your wallet is `2-2 (required signatures - copayers)` you need both backups, if your wallet is `2-3` you need only 2 backups.

**Comment by Newwaybiz** [comment]
There are no other options? Are the funds hanging in your wallet?

**Comment by JDonadio** [comment]
The keys are stored in the devices, not in our server or in any cloud. It's `strongly` recommended to made a backup for any wallet created, to avoid any kind of problems like yours. We have not access to any wallet, so unfortunately if you have not the backups you'll not be able to restore the multi-sig wallet.

**Comment by JDonadio** [comment]
https://support.bitpay.com/hc/en-us/articles/115003004363-I-lost-my-wallet-or-changed-my-phone-What-can-I-do-to-restore-my-wallet-
