### ISSUE TITLE
UNO wallet

### ISSUE THREAD

**Issue by svi-kr** [bitpay/copay#6540]
Why is this page down since 7/31/2017? It claims
Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
http://hydra-uno.cryptap.us/%20class=#!/
I can't access my UNO wallet.

**Comment by dabura667** [comment]
This place has nothing to do with "UNO Wallet"

I have never even heard of UNO wallet.

Most likely, UNO wallet was a scam and you have been tricked. I am sorry someone tricked you out of your money. Please be more careful next time.
