### ISSUE TITLE
delete/uninstall bitpay on macOS Sierra

### ISSUE THREAD

**Issue by guylepage3** [bitpay/copay#6541]
Hi, I was not able to submit an issue in your support forum so I came here.

I am trying to completely uninstall bitpay app on macOS Sierra as someone was recording the install process and has access to the backup phrase, etc. Please assist.

**Comment by JDonadio** [comment]
You have to use a software to uninstall apps, like https://freemacsoft.net/appcleaner/

BitPay and Copay install some dependencies in ~/Library/Caches/BitPay AND ~/Library/Application Support/BitPay

Remove both and you can start fresh (manually method not recommended)

**Comment by guylepage3** [comment]
Thank you very much @JDonadio. That worked like a charm. closing issue.
