### ISSUE TITLE
copay wallet transactions dissapeared from Blockchain

### ISSUE THREAD

**Issue by annalooksup** [bitpay/copay#6542]
Hi! I have been using fixed and backed-up Copay wallet from 18th of April 2017. Have more than 20 transactions there, before and after btc fork, receiving and sending btc.  
Today i decided to check my wallet at blockchain.info and there we no transactions displayed for this wallet, nor any balance, nothing. It looked like the brand-new wallet. How can it be? Can i continue to use this wallet safely?

**Comment by JDonadio** [comment]
If you have your mnemonics (12 words) and the balance is not displayed in another software that support BIP39 you must contact with the support team (Blockchain.info in this case).

Maybe [this thread](https://github.com/bitpay/copay/issues/6532) could be helpful
