### ISSUE TITLE
Importing hardware wallet need me to re-enter the seed?

### ISSUE THREAD

**Issue by phuongnd08** [bitpay/copay#6543]
I guess the point of hardware wallet is to keep the seed contained inside the device.
Not sure why copay asking me to submit the seed (recovery phrase) when I want to import the trezor?

<img width="464" alt="screen shot 2017-08-09 at 9 10 51 am" src="https://user-images.githubusercontent.com/184037/29104566-b9f7ad9a-7cf0-11e7-929f-b5e2ac80c195.png">

**Comment by phuongnd08** [comment]
Beside the trezor come with 24 words recovery phrase. And copay doesn't seem to understand the recovery phrase anyway.

**Comment by JDonadio** [comment]
<img width="399" alt="copay_-_copay_bitcoin_wallet_y_importing_hardware_wallet_need_me_to_re-enter_the_seed__ _issue__6543_ _bitpay_copay" src="https://user-images.githubusercontent.com/13851807/29121908-de1eb3a8-7ce6-11e7-8a7f-659469fed2b6.png">

The only platform that supports HW is `chrome-app`

**Comment by phuongnd08** [comment]
Thank you I attempted the chrome-app version.
It is making progress. However, when I try to import Trezor, I get this:
<img width="409" alt="screen shot 2017-08-12 at 9 58 41 am" src="https://user-images.githubusercontent.com/184037/29237265-fa1375a2-7f44-11e7-95d4-bea53d1ffc96.png">

**Comment by Lau07** [comment]
This might help! https://github.com/bitpay/copay/blob/master/backupRecovery.md

**Comment by dabura667** [comment]
@phuongnd08 You have to choose "New Personal Wallet" and NOT "Import Wallet"

![_001](https://user-images.githubusercontent.com/6586275/29271145-0ee2bd5c-8135-11e7-804e-17fcc2e6c256.png)

**Comment by dunghuynh** [comment]
This method words well. Thanks a lot

**Comment by axenter** [comment]
In the new update this option got removed it looks like?  Wallet key option got removed? I can't import any hardware wallet in anyway for the multisigs.
