### ISSUE TITLE
Always Says 'Insufficient funds'. Not able to transfer my BTC. 

### ISSUE THREAD

**Issue by flagirl** [bitpay/copay#6547]
Anyone know how to fix this issue? It would be very kind for some help. Thx.

**Comment by JDonadio** [comment]
Explain your case and add some screenshot please

**Comment by flagirl** [comment]
jDonadio - I don't know how much more explanation is required.  I completed a small transaction this morning which went through without issue.  I then attempted another transaction to the same company for a higher amount.  I have more than enough BTC in my wallet to cover this transaction but the error keeps coming up. Insufficient funds.  I just got the app yesterday so it should be up to date.  My funds show available in my wallet.  What would you need a screenshot of?

**Comment by flagirl** [comment]
As this is completely new to me, I am confused as to what to do.  I read the info on the link above which was dated 2 years ago.

**Comment by JDonadio** [comment]
I have not details about how much are you trying to spend and how much do you have available in your wallet. Please, provide me any address or your wallet id so I can check your status.

**Comment by flagirl** [comment]
I just tried the transaction again, and it went through.  I had 3.2.... BTC and I was trying to spend 1.05...BTC

Do you work for Copay, what is a collaborator?  I am being cautious about providing information because it is very confusing reading the previous threads.

**Comment by Boris0011** [comment]
why more than 0.01 BTC sent, and the Commission so big?!
![img_1361](https://user-images.githubusercontent.com/31154139/29484677-73eeeb22-84cc-11e7-98f8-a8535b5789bb.PNG)
![img_1363](https://user-images.githubusercontent.com/31154139/29484678-73f6e49e-84cc-11e7-98b2-dc74df3cc742.PNG)

**Comment by JDonadio** [comment]
https://github.com/bitpay/copay/wiki/COPAY---FAQ#copay-requires-high-fees-for-low-amounts-transactions

**Comment by MrTysonsHacks** [comment]
This is fucking stupid, I recieved ALL of my bitcoin in 1 transaction, I have 0.006005 bitcoin, and I'm trying to send it ALL as in 1 transaction. Yet; I'm recieving an error that I have insufficient funds for fees. So basically, Bitpay/Copay stole my Bitcoin. Nice.

**Comment by jakelthomas** [comment]
I get the same issue, I've tried like 3 different platforms now and still sane issues here using namecheap.com

**Comment by BGalliotti** [comment]
Hello @jakelthomas 
Thank you for reaching out to us.

The app gathers many inputs to create a transaction. What happens sometimes is that the funds are spread in too many inputs, so despite you have enough funds, they "do not fit" in the transaction so you get this error. Please check if this could be the problem

Please let us know if you have any additional questions.
Kind regards.

**Comment by Digisaman** [comment]
If you want to transfer/BUT immediately after you Receive BTC, this might be your problem
your Wallet Balance increases after you receive BTC but the total Amount is not usable before your BTC transaction is Confirmed
which could take up to an hour.
So your Balance is actually less than you think which is why you get the error
