### ISSUE TITLE
Copay - is it possible to withdraw a transfer?

### ISSUE THREAD

**Issue by NZKrypto** [bitpay/copay#6553]
I've sent a payment to another wallet (Armory) but that needs me to install a full node and the Estimated Time To Finish is 12 weeks! and my machine is not running but crawling.

Is it possible to reverse the transfer so I can transfer to an alternative wallet?

Thanks ... in astonishment :-)

**Comment by JDonadio** [comment]
Unfortunately no. Broadcasted transactions couldn't be cancelled or reversed by the user.
