### ISSUE TITLE
How to get privkeys and addresses from xprivkey?

### ISSUE THREAD

**Issue by RussianSwiss** [bitpay/copay#6558]
I have transactions stuck for more that 72 hours. According to Bitcoin protocol how long the tx will hang in mempool before it is dropped?

How to get **privkeys** and addresses from **xprivkey** exported from Copay?

**Comment by JDonadio** [comment]
> I have transactions stuck for more that 72 hours. According to Bitcoin protocol how long the tx will hang in mempool before it is dropped?

Normally ~72 hs

> How to get privkeys and addresses from xprivkey exported from Copay?

Check this out https://github.com/bitpay/copay/issues/6451

**Comment by dabura667** [comment]
@JDonadio this was changed from 72 hours to 2 weeks recently.
