### ISSUE TITLE
Does copay usually change public addresses by itself?

### ISSUE THREAD

**Issue by aizhiman** [bitpay/copay#6560]
I withdrew some Bitcoin last night from earn.gg and I matched up my copay public address that I've been using fine and dandy and it said it was right on my phone and on earn. Usually I get it within an hour. This morning I checked it and my copay is saying a different wallet address then it said yesterday when i withdrew and stuff and the transaction isn't there. Does this usually happen? Blockchain says my stuff is confirmed but I lost it I guess since copay changed on me at the last frickin minute

**Comment by dabura667** [comment]
All wallets rotate addresses.

All money sent to any address in your wallet will be yours forever. Don't worry.

You can check your old addresses in the wallet options.

**Comment by aizhiman** [comment]
What happens if money was sent to an old address

**Comment by dabura667** [comment]
You will receive it.

In fact, addresses only rotate when the user presses a button or the address receives bitcoin. So the fact that it is old means you already have your bitcoins.

**Comment by aizhiman** [comment]
i've recieved it but now it says amount too low to spend which is weird because i have amounts lower that i've gotten.. does this fix itself on its own

**Comment by dabura667** [comment]
> amount too low to spend

Currently the bitcoin network's fees are very high. This means "It would cost more fees to spend this bitcoin than the actual value of the bitcoin itself."

Usually a bitcoin input is 148 bytes, and currently the recommended fee rate is 199 satoshis per byte, so 29452 satoshis. Which means any transaction where you received less than 0.0003 BTC will probably have this message.

**Comment by dabura667** [comment]
When the network fees go down, eventually you will be able to send that money again.

**Comment by aizhiman** [comment]
weird cause it was .001 something of Bitcoin but I guess I'll figure it out. Thanks for your help

**Comment by dabura667** [comment]
are you using multisig? 2 of 3?

Multisig bitcoins use more data, so the cut off amount is much higher.

**Comment by aizhiman** [comment]
Honestly not sure I'm new to this

**Comment by dabura667** [comment]
Do your addresses start with a 3 or a 1?

**Comment by aizhiman** [comment]
A 1

**Comment by dabura667** [comment]
ok, your wallet is not multisig. Inputs in your wallet are about 148 bytes.
