### ISSUE TITLE
Coinbase - Error: No payment method available to buy

### ISSUE THREAD

**Issue by WorMartiN** [bitpay/copay#6563]
Hi. I’m trying to buy BTC through Coinbase and I keep receiving this error despite having connected my debit card and succesfully tested it by buying small amount of BTC into my Coinbase wallet. Even when I tried to buy into the Coinbase wallet, my card often disappeared on the page for buying, it might be relevant.

**Comment by Kirvx** [comment]
https://github.com/bitpay/copay/issues/5487

**Comment by WorMartiN** [comment]
I've seen that, it didn't actually get answered. I could obviously just get some Euros into the Coinbase wallet but then I'd have to pay two kinds of fees.
