### ISSUE TITLE
Copay didn't give me my amazon.com gc

### ISSUE THREAD

**Issue by bitbuyer** [bitpay/copay#6564]
HI 
I MADE A PURCHASE OF $46/- AMAZON.COM GC.
IT HAS BEEN MORE RHAN 6 HOURS BUT STILL I DEDNT RECEIVE ANY OF THE GC CODES.
I SENT AN EMAIL TO CTHE HELPCENTER BUT NO PROPER RESPOND.

PLEASE MAKE NECESSARY ARRANGEMENTS FOR ME TO RECEIVE RHE AMAZON.COM GC

THANKS

**Comment by bitbuyer** [comment]
I received an email awhile ago asking for 2-3 business days to resolve the issue.

But why does it take all these time.

@ the beginning they just showed that the amazon.com gc will pop up immediately. 

But this's totally unacceptable.

Please guys 

Resolve @ get me the amazon.com gc asap

**Comment by JDonadio** [comment]
Hi, sorry about that.

Please send an email to help@bitpay.com

**Comment by bitbuyer** [comment]
Hi JDonadio

I emailed them, first they said they will get back within a day & again they said they will work on it & get back within 2-3 business days.

So I'm waiting for their reply.

**Comment by JDonadio** [comment]
Can you please provide the transaction id?

**Comment by bitbuyer** [comment]
Hi
Please find the transaction details on this link

https://insight.bitpay.com/tx/3e724fa046dc2b6d09e4aba0156b56db490f84b4deff948a417b5589a828cd94

Also here's a screenshot of same
[Image]

Awaiting for a positive response

Thanks & Regards

Mohamed Nafli Nawas
+974 3030 8600

Sent from my iPhone
________________________________

**Comment by bitbuyer** [comment]
Hi 
Please find the transaction details on this link 

https://insight.bitpay.com/tx/3e724fa046dc2b6d09e4aba0156b56db490f84b4deff948a417b5589a828cd94

**Comment by bitbuyer** [comment]
Today is the fifth day
No proper response yet

**Comment by JDonadio** [comment]
Followed by `BitPay support team`
