### ISSUE TITLE
NPM start errors

### ISSUE THREAD

**Issue by DadaNet** [bitpay/copay#6566]
I clone from the repo and installed:
git clone https://github.com/bitpay/copay.git
cd copay
npm run apply:copay
npm start
It said there is a problem with grunt, i installed it manually. But still there is errors while i try to run npm start.
Running "browserify:dist" (browserify) task
Error: Cannot find module 'elliptic' from 'D:\bitpay-wallet\copay\node_modules\create-ecdh'
Warning: Error running grunt-browserify. Use --force to continue.
I intalled this module manually. But nothing changed:

> copay@3.7.1 start D:\bitpay-wallet\copay
> npm run build:www && ionic serve --nolivereload --nogulp -s --address 0.0.0.0
npm WARN invalid config loglevel="notice"
> copay@3.7.1 build:www D:\bitpay-wallet\copay
> grunt
> "grunt" is not recognized as an internal or external command, operable or batch file

What else i can do?
Log is:

>npm ERR! code ELIFECYCLE
>npm ERR! errno 1
>npm ERR! copay@3.7.1 build:www: `grunt`
>npm ERR! Exit status 1
>npm ERR!
>npm ERR! Failed at the copay@3.7.1 build:www script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>
>npm ERR! A complete log of this run can be found in:
>npm ERR!     C:\Users\Dada\AppData\Roaming\npm-cache\_logs\2017-08-14T12_58_03_019Z-debug.log
>npm ERR! code ELIFECYCLE
>npm ERR! errno 1
>npm ERR! copay@3.7.1 start: `npm run build:www && ionic serve --nolivereload --nogulp -s --address 0.0.0.0`
>npm ERR! Exit status 1
>npm ERR!
>npm ERR! Failed at the copay@3.7.1 start script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>
>npm ERR! A complete log of this run can be found in:
>npm ERR!     C:\Users\Dada\AppData\Roaming\npm-cache\_logs\2017-08-14T12_58_03_051Z-debug.log

**Comment by JDonadio** [comment]
Ensure to get the latest node and npm version and try with `npm run clean:all` then `npm run apply:copay`. If you run into any error in the build process try with just `npm i`.

**Comment by DadaNet** [comment]
My versions are:  
node v6.11.2
npm  v2.15.12
After npm run clean:all there is error:
npm ERR! missing script: clean:all
and after npm i also errors :

> npm ERR! Windows_NT 10.0.14393
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "D:\\bitpay-wallet\\copay\\node_modules\\npm\\bin\\npm-cli.js" "run" "make-dist"
> npm ERR! node v6.11.2
> npm ERR! npm  v2.15.12
> npm ERR! code ELIFECYCLE
> npm ERR! bitauth@0.2.1 make-dist: `sh scripts/make-dist.sh`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the bitauth@0.2.1 make-dist script 'sh scripts/make-dist.sh'.
> npm ERR! This is most likely a problem with the bitauth package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     sh scripts/make-dist.sh
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs bitauth
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!
> npm ERR!     npm owner ls bitauth
> npm ERR! There is likely additional logging output above.

**Comment by JDonadio** [comment]
`npm ERR! npm v2.15.12`
