### ISSUE TITLE
Public Wallet ID ?

### ISSUE THREAD

**Issue by wally000** [bitpay/copay#6567]
Hello,

I just did a sweep of a paper wallet, and waiting for that transaction to be confirmed. Cheking on inisight.bitpay.com, I see the bitcoins going to a wallet that starts with '15b' but I cannot locate any wallet ID in Copay app (on iPhone) that starts with this chars.

Question 1: how can I get my public wallet ID in Copay app v3.7.1 on iPhone ?

Question 2: do you allow multiple wallet ID in your app and if so, hot to understand which ones are in use?

Thanks.

**Comment by JDonadio** [comment]
> Question 1: how can I get my public wallet ID in Copay app v3.7.1 on iPhone ?

Settings > wallet > more options > wallet information

> Question 2: do you allow multiple wallet ID in your app and if so, hot to understand which ones are in use?

No, each wallet has an unique id.

**Comment by wally000** [comment]
So in the "Settings > wallet > more options > wallet information" I get a Wallet ID that starts with '6052' while in the sweep transaction I see my bitcoin sent to a wallet ID that starts with '15bW'. Can you please clarify? Are my bitcoins going to my Copay wallet or where?

**Comment by JDonadio** [comment]
Can you paste the transaction id here so I can check it?

**Comment by wally000** [comment]
here:

https://insight.bitpay.com/tx/a10dd3ba73139755dff5477bd57537db6c5c476fe51d676878f46b8321ce574c

the destination wallet address was automatically set by Copay when I selected my only wallet available in the iOS app. Any clue?

**Comment by dabura667** [comment]
Ahhh, that's not a "wallet ID" it's one of your many "wallet addresses" which can be found in:

"Settings > wallet > more options > wallet addresses (and View All Addresses if you want to view the specific BIP32 paths of each address)"

**Comment by JDonadio** [comment]
Your wallet id: 6052e6e0..

You have a total of 0.99932555 which is the exactly amount of the sweeped transaction. As dabura says, you was confusing your wallet id with an address.

**Comment by wally000** [comment]
Hello, thanks for clarifying, I was actually looking for the wallet public address, maybe I used a confusing wording! Thanks for helping.

Out of curiosity, why you allow to have multiple wallet addresses? I find it a bit confusing since, as a backup, I'd like to have an address/key pair which I can save somewhere in order to avoid losing it.

thanks

**Comment by JDonadio** [comment]
Please take a look [here](https://github.com/bitpay/copay/wiki/COPAY---FAQ#why-my-address-keeps-changing)

**Comment by dabura667** [comment]
> I'd like to have an address/key pair which I can save somewhere in order to avoid losing it.

Your key is your 12 word phrase. That is all you need to generate every address and key in your wallet.

Using the same address every time is dangerous. No wallet does that anymore.

**Comment by wally000** [comment]
Hi Dabura,

thanks for clarifying. Can you confirm that, in order to recover the private keys in Copay, all we need to backup and keep safe if our 12 words phrase?

In addition, can you please confirm that the private key is the 'xPrivKey' field found in the decrypted file downloaded from the app? Is this private key valid for all the wallet addresses available in the app?

Thanks.

**Comment by dabura667** [comment]
12 word phrase >>> special hash >>> xprv ("xPrivKey") >>> path logic >>> individual private keys

Above is the order of operations to get from 12 words to a specific private key.

Copay holds some redundant data to save time. (They store the phrase AND the xprv)
