### ISSUE TITLE
Topped up my card from my wallet and funds never showed up

### ISSUE THREAD

**Issue by daughterovwater** [bitpay/copay#6568]
I sent (topped up) $1,500 from my wallet to my card and even though the transaction was confirmed on the blockchain the funds never made it to my card. Bitpay customer support won't respond to me so am I really out $1,500? Please help!

**Comment by JDonadio** [comment]
There is not listed as pending? can you provide the transaction id? thanks

**Comment by daughterovwater** [comment]
This is what is now showing when I click on show on blockchain:




I don't understand? 
Can I forward you the email I sent to Bitpay customer support I had included a link that was working to show transaction to them...

**Comment by daughterovwater** [comment]
Wow when I click on the link I emailed them it takes you to the same blank page??? Wtf?!

https://insight.bitpay.com/tx/cf206bb7e3ae836fa5ace655922b1bf181ab005e3157b29250dc24fb4fb74e4b

This is terrible! 



❤️💧Water Blessings💧❤️

**Comment by daughterovwater** [comment]
Where else can I find the transaction ID?

**Comment by daughterovwater** [comment]
Hey,
The funds just showed up on my card!!! Thank you so very much!!
Not sure what or how but I'm very grateful :)
Thanks again,
Corey

**Comment by daughterovwater** [comment]
Can you please help me? I sent funds with my Bitpay wallet and they haven't shown up. They have been confirmed on Blockchain however 


❤️💧Water Blessings💧❤️

**Comment by Gamboster** [comment]
Hello @daughterovwater 

Can you provide the transaction id? Thanks
