### ISSUE TITLE
Changing default currency does not work

### ISSUE THREAD

**Issue by iamMichaelBanks** [bitpay/copay#6570]
Hi,

I have Bitpay on both OSX and iOS (version 3.7.1 on both).

I have changed the Alternative currency to Pound Sterling on both, but both are still showing in USD.

![img_0203](https://user-images.githubusercontent.com/31038750/29318012-4f89c0da-81c6-11e7-9824-5d081d0f90a8.PNG)
![img_0202](https://user-images.githubusercontent.com/31038750/29318015-4fad59fa-81c6-11e7-8abd-1f42330c0239.PNG)

Please advise, as it is difficult to purchase the correct amount when it is not in the correct currency.

Thanks,

Michael

**Comment by cmgustavo** [comment]
Hi,

Coinbase integration doesn't support another currency. Only USD.
