### ISSUE TITLE
Been 4 hours and the bitcoin still says "Receiving"

### ISSUE THREAD

**Issue by abood101** [bitpay/copay#6573]
Hello guys,

I am using Copay as my phone wallet and have received about 0.12306 btc to my wallet, however, it is saying "This transaction could take a long time to confirm or could be dropped due to the low fees set by the sender" I don't understand what this means, it has already been 3 hours and still nothing. Here is a screenshot:

https://image.prntscr.com/image/i_p6GSQ7Sf6pPWZx2NSNJw.png

**Comment by JDonadio** [comment]
Hi there. 

You receive a transaction with low fee, that means the transaction could take several hours to be confirmed. If you don't understand how the fee works, please read this:

https://en.bitcoin.it/wiki/Transaction_fees

**Comment by abood101** [comment]
Thing is it has been 24 hours and the money is still not in the wallet. Do I contact the seller and ask them for a refund or do I just sit here and keep waiting and hope the money comes in?

**Comment by JDonadio** [comment]
I suggest you contact to the sender and let it know what is happening with your payment.
