### ISSUE TITLE
Blockchian says Transaction susccess but my wallet hasn't received.

### ISSUE THREAD

**Issue by myzinke** [bitpay/copay#6574]
The bloackchain shows the transaction is successful, but the wallet received nothing.

Hi, this is the details of this transaction from blockchain.

Summary:
--
Address | 1A9k21ZhUqFYvoFQyvoMtHvgJypJi8iRTo
Hash 160 | 64605e6e7515fe13af30cb0f37b84ee9340159dc
Tools | Related Tags - Unspent Outputs

ansactions
--
No. Transactions | 1 |  
Total Received | 0.0684 BTC |  
Final Balance | 0.0684 BTC

![_20170816140640](https://user-images.githubusercontent.com/11768912/29349375-274558a2-828c-11e7-953e-7a0c263cc652.png)
![_20170816140634](https://user-images.githubusercontent.com/11768912/29349376-274aa0b4-828c-11e7-9527-9235d5f6c207.jpg)
![_20170816140626](https://user-images.githubusercontent.com/11768912/29349377-274d0b74-828c-11e7-9dce-75cb872e9423.jpg)

**Comment by JDonadio** [comment]
Please provide us the transaction id so we can investigate it further.
