### ISSUE TITLE
Funds received into CoPay wallet but not..?

### ISSUE THREAD

**Issue by Dzsjohn** [bitpay/copay#6575]
Made a transfer into my CoPay wallet, received email confirmation, but wallet still says 'receiving' for almost 2 hours now, never had a transaction take more than 10 minutes previously, please let me know what information you require to address this issue, thanks...

**Comment by JDonadio** [comment]
If the transaction have a low fee, then will take several hours to be confirmed. In that case you have to contact to the sender because the transaction was built and the fee was set from his end.
