### ISSUE TITLE
Transaction sending

### ISSUE THREAD

**Issue by timbow888** [bitpay/copay#6577]
Dear, I've sent some bitcoins in 2 separate transactions with a normal Bitcoin fee. Average confirmation time with this fee is 30 minutes. But both transactions are sending for about four hours. Can you please tell me what can be wrong? Thank you!

**Comment by JDonadio** [comment]
Can you provide us both transaction id? thanks.

**Comment by timbow888** [comment]
Seems now there are two confirmations but in the blockchain in one transaction it says 'Output is spent'. Can you please tell me what this means? Thank you.

cd0c8064e909621400118a6434a56749c69941397f5da102b9adaee977aa5e3f
&
0ca5a8ab46b493d505db647e79f3593498b76e2697685b95f54bcddebb7671e3

**Comment by JDonadio** [comment]
Confirmed: https://insight.bitpay.com/tx/cd0c8064e909621400118a6434a56749c69941397f5da102b9adaee977aa5e3f

You sent `0.434369 ` to `198nUjBmURcQN8YTf1RXUQE4rivi9uCQd3` and the receiver moved these funds to another address.

Confirmed:
https://insight.bitpay.com/tx/0ca5a8ab46b493d505db647e79f3593498b76e2697685b95f54bcddebb7671e3
