### ISSUE TITLE
24 hrs sin comprobar transferencia 

### ISSUE THREAD

**Issue by Jhonatans1725** [bitpay/copay#6580]
Buenos días , ya casi se cumplen 24 hrs de haber hecho 3 transferencias diferentes desde mis billeteras en copay, y aun no me han confirmado ninguna, que está sucediendo ?

**Comment by JDonadio** [comment]
Hola, vos mandaste o recibiste? podes pasarme los tx id asi me fijo?

**Comment by Jhonatans1725** [comment]
Mira aquí están

488540428d58a9390da7e77a49decef4aa0080430efecb79a99daaef3900e736

bb81df7396aff85ec89df387d8d04acecff56a224904dfbe8588bc3e00c7d539

dbb8c5f36503bd2b004c863f9ce3432c8cc225eca3e289e660740f8bbdd1a235



El 16/08/2017 9:51, "Javier Donadío" <notifications@github.com> escribió:

Hola, vos mandaste o recibiste? podes pasarme los tx id asi me fijo?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bitpay/copay/issues/6580#issuecomment-322797127>, or mute
the thread

**Comment by JDonadio** [comment]
Mira, para los valores de las fee que mandaste en esos momentos la red por lo visto estuvo congestionada y usando valores muy altos. Lamentablemente vas a tener que esperar a que se confirmen o bien a que se caigan de la mempool y tener de nuevo los fondos disponibles en tu wallet.

**Comment by Jhonatans1725** [comment]
A bueno dale muchas gracias , osea que es mejor manejar a copay en "normal"
para que no suceda esto o economico es aceptable ?

**Comment by JDonadio** [comment]
Eso ya depende de cada uno, si no tenes apuro en que una transacción se confirme podes usar un valor más bajo. Particularmente yo uso normal, siempre.

**Comment by Jhonatans1725** [comment]
Yo usaba económico y no pasaba nada , ahora ya llevo 36 hrs sin confirmar
las transferencias al cuanto tiempo las devuelven?

**Comment by JDonadio** [comment]
Si, pero como te dije antes a veces la red se congestiona y las transacciones tardan más de lo normal. Antes si una transaccion se caía era en ~72 hs aprox, hace poco lo cambiaron a 1 semana. Lamentablemente no te queda otra opción que esperar, pero ojalá que no sea mucho más.
