### ISSUE TITLE
24 hours and bitcoin is still not in my wallet because the seller set low or no fees at all what should I do?

### ISSUE THREAD

**Issue by abood101** [bitpay/copay#6584]
I understand the issue of the bitcoin not arriving is due to the seller setting low or no fees at all. However, it has been 24 hours and nothing has happened yet, the seller told me they sent the money. Now, I don't know if I should keep waiting longer than 24 hours for the money to come in or should I contact the seller?

**Comment by dabura667** [comment]
Keep waiting til it gets in a block. If he says "I SENT IT GIVE ME THE MONEY!" tell him "I won't give you the money until it gets x confirmations. That's how bitcoin works. Sorry for the wait, but you should have used a higher fee."

DO NOT GIVE HIM THE MONEY UNTIL HIS TRANSACTION IS IN THE BLOCKCHAIN. He will probably try to scam you by RBF or something.

Could you post a transaction ID?

**Comment by dabura667** [comment]
Ahh you already sent the money?...

Wait and pray.

Nothing you can do.

If the transaction is lost, then I will be sorry for your loss.

**Comment by abood101** [comment]
Ya I have the "Use unconfirmed funds" enabled. Been using Copay for like a whole year with this feature on, but this is the first payment that is taking forever. I did contact the seller and letting them know about the problem, hopefully they fix it.
