### ISSUE TITLE
perdida billetera

### ISSUE THREAD

**Issue by alquimiq** [bitpay/copay#6587]
buen dia yo tenia en mi telefono la billetera con barias billeteras a la vez pero en un momento me dio por abrir la billetera y me salio descargar nueva billetera y des de ese momento desaparecieron todas, cual seria el paso a seguir

**Comment by JDonadio** [comment]
Hola, si por alguna razón perdiste el acceso a tus billeteras, podes importarlas nuevamente usando los backups. Fijate en este link: https://support.bitpay.com/hc/en-us/articles/115003004363-I-lost-my-wallet-or-changed-my-phone-What-can-I-do-to-restore-my-wallet-

**Comment by alquimiq** [comment]
BUENA NOCHE INGRESE LAS PALABRAS DE SEGURIDAD Y NADA EN LAS DIFERENTES
BILLETERAS

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-08-16 15:37 GMT-05:00 Javier Donadío <notifications@github.com>:

**Comment by JDonadio** [comment]
Las transacciones no se hacen automáticamente, por lo que si no tenes fondos alguien las tuvo que mandar manualmente. Estás seguro de que tus backups no están comprometidos o que no tenías capas de seguridad como la huella digital o la contraseña para gastar los fondos?

Sólo para comprobar tus balances, me podes mandar los id de tus wallets y te digo si realmente están en cero o no. Podes encontrar los id en Settings > wallet > more options > wallet information.

**Comment by alquimiq** [comment]
Oye yo no tengo esos ID que mencionas solo las 12 palabras

**Comment by JDonadio** [comment]
@alquimiq te recomiendo que verifiques con detalle todos los pasos de seguridad que proveemos a través de la app para que puedas evitar este tipo de escenario en un futuro. Lamentablemente no se puede hacer nada en tu caso, las transacciones no se pueden dar marcha atrás o ser canceladas.

**Comment by alquimiq** [comment]
2.2 BTC tenia en billetera y me dice que no se puede hacer nada. OK muy
bien por mi parte no utilizaré esa billetera en la vida y también le daré
malas recomendaciones por que no hay seguridad ni respaldó.  Pude recuperar
una pero no me dieron el saldo que tenia son unas ratas

**Comment by JDonadio** [comment]
@alquimiq nuestra app provee:

* PIN o Fingerprint (huella digital): para bloquear/desbloquear el dispositivo en las versiones mobile
* Contraseña para gastos: para cada billetera, podes configurar una contraseña diferente la cual encripta tu clave privada y será requerida obligatoriamente antes de efectuar cualquier pago e inclusive al intentar acceder a información sensible como tu backup, un export, etc.
* Fingerprint: cumple la misma función que la contraseña para gastos, pero sin encriptar tu clave privada. Será requerida en todos los casos descriptos en el caso anterior.
* Billetera sólo lectura: la cual no posee la clave privada (para firmar), por lo cual únicamente podes chequear el balance y crear propuestas de pago. Repito, sin posibilidad de firmar nada.
* Multi-firma: la cual requiere más de una firma para poder enviar fondos.
* Mensajes de alerta, precaución, notificaciones, confirmaciones, etc.

Creo que hay suficientes capas de seguridad. Lamento que hayas tenido que pasar por todo eso, pero desde nuestro lugar no podemos hacer nada al respecto.
