### ISSUE TITLE
BTC/IDR 17-08-2017, rate seems to be wrong

### ISSUE THREAD

**Issue by johnmichaelgabriel** [bitpay/copay#6588]
Indonesian Rupiah rate to BTC seems to be very low. Kindly update so I can see it in my denomination, instead of USD - USD rate OK. Thanks.

**Comment by Gamboster** [comment]
I checked and It seems to be ok. Do you have some proof to check what you say?

Anyway, you have to keep in mind that it is only an estimate. An exchange could offer you more than others for your BTC.
