### ISSUE TITLE
Amount too low to spend!!!

### ISSUE THREAD

**Issue by napan1978** [bitpay/copay#6591]
i have message in copay wallet after Sweep peper wallet 0.004705BTC "This transaction amount is too small compared to current Bitcoin network fees.Spending these funds will need a Bitcoin network fee cost comparable to the funds itself." 
this transaction have confirmed. all that's mean?

**Comment by JDonadio** [comment]
Please see https://github.com/bitpay/copay/issues/6562#issuecomment-322762885
