### ISSUE TITLE
Blockchian says Transaction susccess but my wallet hasn't received.

### ISSUE THREAD

**Issue by charlitos85** [bitpay/copay#6594]
Blockchain says transaction susccess but my wallet hasn't received.
the wallet is a in IOS sierra App
wallet: 1LjcBAk69rbVuMmrvCjzNbw8mR3m3ibim3

confirmation:
https://www.blockchain.info/address/1LjcBAk69rbVuMmrvCjzNbw8mR3m3ibim3

**Comment by JDonadio** [comment]
What is the transaction id?

**Comment by charlitos85** [comment]
https://insight.bitpay.com/tx/246bdd69e072e521532904af0864c0b9c9cb3f47b678f4890b4f6243e4c8e317

**Comment by JDonadio** [comment]
Can you provide also your wallet id? You can find it in settings > wallet > more opts > wallet info

**Comment by JDonadio** [comment]
Everything seems to be ok and the amount of `0.18636637` is already on your wallet. Try scanning your addresses in settings > wallet > more opts > wallet addresses

**Comment by charlitos85** [comment]
24607984-d2ca-4333-aef8-3d25216939aa

**Comment by JDonadio** [comment]
Your wallet ID doesn't match with the transaction above.

Wallet ID: 24607... > Balance 0

So basically you send these funds to another wallet.

**Comment by charlitos85** [comment]
no that was imposilbe, I used this ID `1LjcBAk69rbVuMmrvCjzNbw8mR3m3ibim3 `generated by wallet app. I don't have other wallet in the APP

**Comment by JDonadio** [comment]
Go to Settings > wallet > more opts > wallet addresses > view all addresses and check if `1LjcBAk69rbVuMmrvCjzNbw8mR3m3ibim3generated` is there.
