### ISSUE TITLE
How to get bitcoins in Copay?

### ISSUE THREAD

**Issue by Goofy2k** [bitpay/copay#6598]
I am new to this, so need to learn.

I installed Copay and acquired some bitcoins via Coinbase which is linked to Copay. I can see the amount in Coinbase, but 

1) how do I get the bitcoins into Copay
2) how can I get Euros on my bank account by selling bitcoins

Regards

**Comment by JPMORIN33** [comment]
Did you figure out how to do it? I am also in the same boat

**Comment by Goofy2k** [comment]
In the end I managed, but I have to recall it. I'll write it down for you.

Next step is how to convert to Euros again and get it out to my bank
account.
Either from Copay or....?

Fred

Op 20 aug. 2017 00:56 schreef "JPMORIN33" <notifications@github.com>:

**Comment by fictioncode** [comment]
Did you write it down somewhere?
Having same problem. Managed to 'load' some bitcoins into coinbase but unable to transfer into copay.
What is the secret?

**Comment by plkoehn** [comment]
I'm in exactly the same boat.  I have submitted two support tickets over the last two weeks, but I still haven't heard anything.

**Comment by JDonadio** [comment]
> how do I get the bitcoins into Copay

If you bought bitcoins without using coinbase integration in Copay, your bitcoins will not been reflected in Copay.

> how can I get Euros on my bank account by selling bitcoins

Copay only manage bitcoins. The currencies (USD, EUR, etc) are just for references. You should check your coinbase account settings or contact to the support team and ask them for it.
