### ISSUE TITLE
Bitcoin Cash

### ISSUE THREAD

**Issue by Gooperative** [bitpay/copay#6599]
Hello!
I can't describe this problem in detail in English. It is written in Russianю
I'm sorry.

Здравствуйте!
Не могу получить свои Bitcoin Cash из кошелька с мультиподписью. Получается на разных устройствах две мнемоники.
[По инструкции](https://golos.io/bitcoin/@encryptmymoney/kak-poluchit-svoi-bitcoin-cash-iz-koshelkov-electrum-copay-bitcoin-core) создал кошелек на Electron Cash. С других кошельков все сработало и кэш зачислился, а с кошелька с мультиподписью - нет.
Сначала ввел мнемонику с устройства, где кошелек создавался первым. Но Bitcoin Cash не начислился,позже попробывал мнемонику со второго устройства. Результат тот же.
Вопрос: В чем причина?

**Comment by JDonadio** [comment]
Sorry, we cannot give you support on `russian`.

I was trying to use a traductor but I cannot understand you with clarity. 

* If you are trying to recover your BCH then try with the [recovery tool](https://bitpay.github.io/copay-recovery/)
* If you have a multi-sig wallet (i.e. 2-3) you will need the 3 backup (12 words or file/text format)

**Comment by Gooperative** [comment]
Thank you!
Tell me please, how to use correctly "RECOVERY TOOL" ? 
Where can I find the manual?

**Comment by JDonadio** [comment]
Hi @Gooperative you can check this example video: https://youtu.be/oL6uDd2YUdI

Note: for backup files you just have to add the password required at the export time.

Hope that helps.
