### ISSUE TITLE
How to recover removed second copay wallet? 

### ISSUE THREAD

**Issue by copaywallet** [bitpay/copay#6600]
I have created the second wallet in the same copay app but after creating the wallet I use the BTC address to receive payment and before receive my payment I removed one wallet from my copay app account now I received payment in removed wallet  I want to recover my second removed wallet. I don;t have recovery phrase but I have same device and same copay app. how can I recover my removed wallet please help. I received payment after removed.

**Comment by JDonadio** [comment]
You cannot recover the access to your wallet if you have not a backup. Unfortunately that's the only way. Please check this https://support.bitpay.com/hc/en-us/articles/115003004363-I-lost-my-wallet-or-changed-my-phone-What-can-I-do-to-restore-my-wallet-
