### ISSUE TITLE
How Do I Get My Bitcoin Cash?

### ISSUE THREAD

**Issue by ssakcoR** [bitpay/copay#6602]
Hi,

Updated to the newest version of Copay, however it doesn't have Bitcoin Cash wallet yet.
Will it be added any time soon?

If not, what is the procedure of claiming BCC?

Thanks

**Comment by dabura667** [comment]
The recovery tool supports BCC sweeping. Download the recovery tool.

**Comment by JDonadio** [comment]
https://bitpay.github.io/copay-recovery/

Set the chain for BCH and scan your wallet backup.
