### ISSUE TITLE
Error de direccion

### ISSUE THREAD

**Issue by saitam2006** [bitpay/copay#6603]
Transferi BTC desde mi billetera Copay a otra billetera propia pero erroneamente a una direccion de BCH. Como puedo recuperarlo?

**Comment by LeaTex** [comment]
@saitam2006 me temo que no podés hacerlo. si te confundiste la dirección de destino, no hay vuelta atrás.

si la transacción todavía no se confirmó, la única opción que tenés es reemplazarla por otra transacción a la dirección correcta con una comisión más alta para darle prioridad.

**Comment by saitam2006** [comment]
Gracias por ls respuesta. La duda es, los BTC se transfirieron a una direccion de Bitcoin Cash que tambien es mia, pero de distinta Wallet, por lo que nunca se acreditaran en ningún lado. Aún asi no se pueden recuperar?  Desde Copay me figura el pago como "enviado"

**Comment by LeaTex** [comment]
Pasá la dirección de destino que lo buscamos en algún explorador de transacciones.

Si el envío lo hiciste desde Copay, lo mandaste a una dirección X en la cadena de Bitcoin. La cadena de Bitcoin Cash ni se entera.

Ahora, si entiendo bien, es dirección X la generaste vos desde una billetera de Bitcoin Cash, entonces si es una billetera que administrás vos, y podés obtener las claves privadas o las palabras para regenerarla, podrías usarlas para restaurarla en una billetera Bitcoin y ahí tendrías tu saldo esperando en la dirección X.

¿Se entendió?

**Comment by saitam2006** [comment]
1Mj424CgryW52TS2f5L6kfE5CRK2XC1ksF
Esta es la direccion de mi billetera de Bitcoin Cash de Coinomi a la cual envie por error mis BTC desde Copay

**Comment by LeaTex** [comment]
Bueno, acá la transacción en la blockchain de Bitcoin:
https://blockchain.info/es/tx/64263937006536a626427e8cf2e7047899ef57e4c78a0c9b418f1af212dd092a

Pregunta 1: Por lo que entiendo, tenías 0.1872 y mandaste 0.1 por lo que debería aparecerte la diferencia (0.08) en tu billetera de Copay. ¿Es correcto?

Pregunta 2: Cuando creaste la billetera en Coinomi te dio 18 palabras, supongo que las tenés. ¿Es así?

Pregunta 3: ¿Qué monedas seleccionaste en Coinomi cuando creaste la billetera, solo Bitcoin Cash?

Respondeme estas 3 cosas así vamos de a poco.

**Comment by LeaTex** [comment]
Mmm... si ya añadiste BTC y no los ves, seguramente las direcciones generadas, por más que las 18 palabras sean las mismas, tienen algo diferente.

Probá si restaurando la billetera con Electrum lográs que te aparezcan.
Acá dice cómo: https://coinomi.freshdesk.com/support/solutions/articles/29000009715-how-to-import-a-coinomi-seed-into-electrum-

Sino creo que ya no tenés muchas alternativas.

**Comment by JDonadio** [comment]
Hola, fijate si podes usar la [recovery tool](https://bitpay.github.io/copay-recovery/) para encontrar los fondos y mandarlos de nuevo a otro lado.

**Comment by jauszenker** [comment]
@saitam2006 me pasó lo mismo.
Pudiste solucionarlo?

**Comment by saitam2006** [comment]
Aun no....ni con la recovery tool ni desde la pagina de coinomi.
Mi caso se asemeja a este: 
https://coinomi.freshdesk.com/support/solutions/articles/29000014189-accidentally-sent-btc-to-coinomi-bch-wallet-or-sent-bch-to-coinomi-btc-wallet-faq.
De todas formas seguire intentando, de encontrar la solución la comparto.

**Comment by jauszenker** [comment]
A mí me pasó con una dirección de Freewallet. Al parecer me pueden ayudar. Comento cuando sepa algo más.

**Comment by jauszenker** [comment]
Al final, después de 4 días, Freewallet me recuperó todo!

**Comment by saitam2006** [comment]
Bien! Yo finalmente también, creo que es mas bien una cuestión de tiempo. Saludos!

**Comment by jhonga** [comment]
Hola, a mi me sucedió algo parecido por error envie BCH que tenia en coinpayments a una dirección de BTC que tengo en Xappo. Díganme que opciones tengo para recuperar ese saldo? Gracias.

**Comment by JDonadio** [comment]
Hablar con la gente de xapo

**Comment by veronica08** [comment]
Hola saludos, espero que puedan ayudarme, por error  mande mis bitcoin de mi billetera copay a una de mis billeteras bitcoin cash en uphold aun no me ha llegado ¿como puedo recuperar lo? Agrade seria mucho su ayuda si podría aportar información.

**Comment by josemariabooymts** [comment]
Vero?
