### ISSUE TITLE
Where is my bitcoin cash?

### ISSUE THREAD

**Issue by Brayheart** [bitpay/copay#6604]
On August 19th I exchanged  0.35 BTC for 1.90460769 BCH. I had the received address on my copay account as its destination however I have no bitcoin cash. Where is it and how can I get access to it? 

I understand that I need to use a recovery tool. I'm not sure what this means or how to use it. If I cannot use copay to store my bitcoin cash, then where can I? Thanks!

**Comment by Brayheart** [comment]
No one did, I mistakenly assumed it would support it. Is there a way I can get access to my bitcoin cash or is it just gone?

**Comment by dabura667** [comment]
Read the wiki and download the recovery tool.

All the instructions you need are on the github wiki for this repository.

**Comment by JDonadio** [comment]
You can use the [recovery tool](https://bitpay.github.io/copay-recovery/) to scan your wallet and send your funds to a proper BCH wallet.

Note: ensure to select the BCH chain to scan the correct balance.
