### ISSUE TITLE
Bitcoincash & Recovery tool

### ISSUE THREAD

**Issue by Sputnik365** [bitpay/copay#6605]
Using the recovery tool https://bitpay.github.io/copay-recovery/ I tried to access the multisig wallet (2-of-3 conf.) with BCH. I used a mnemonic phrase from 3 copay accounts. Attempts did not bring results, the balance was not reflected. At the same time using the explorer, I saw an available balance of BCH.
How to fix the situation and gain access to BCH?
1. Can I use the mnemonic phrase from the multisig wallet?
2. Is it possible to use a mnemonic phrases from 2 accounts, if the 3rd is provided incorrectly or lost?
3. Perhaps there are still some ways to gain access to BСH (F.e. using multisig's mnemonic with other services?)

**Comment by JDonadio** [comment]
> 1. Can I use the mnemonic phrase from the multisig wallet?

Yes

> 2. Is it possible to use a mnemonic phrases from 2 accounts, if the 3rd is provided incorrectly or lost?

No, please follow this: https://github.com/bitpay/copay-recovery/issues/54

> 3. Perhaps there are still some ways to gain access to BСH (F.e. using multisig's mnemonic with other services?)

Sure, but we have not one for recommend.

**Comment by Sputnik365** [comment]
@JDonadio 
- Can I use the mnemonic phrase from the multisig wallet?
- Yes
- You mean that I can use https://bitpay.github.io/copay-recovery/ by entering only the mnemonic phrase directly from multisig (without using backups of the copayers)? In this case, which wallet configuration will be chosen correctly, 1-1?

Thanks!
