### ISSUE TITLE
[BitPay Card] Confirmation of reloading is still there after blockchain confirmation

### ISSUE THREAD

**Issue by Kirvx** [bitpay/copay#6606]
My balance is OK, it's just a bug in the wallet.
### The 200€ in orange should disappear as the reloading is ok (green 200€).
![screenshot_20170821-152442 1](https://user-images.githubusercontent.com/6627786/29524272-a8de4ce6-868f-11e7-87c7-3830cd2eefe9.png)

**Comment by cmgustavo** [comment]
Hi @Kirvx , 

Yes, it 's a known issue for INTL cards. We 're working on a fix.

Thanks for report.
