### ISSUE TITLE
Slow sending payment

### ISSUE THREAD

**Issue by Copai** [bitpay/copay#6608]
Hi,

I sent a payment which is still sending 7 hours later, is the transaction stuck or is there anything I can do to speed it up? It was sent with super economy, but it said 4 hours at most to send a payment on that, not almost 8. 

Thanks!

**Comment by JDonadio** [comment]
> is there anything I can do to speed it up?

Unfortunately no. If the transaction was broadcasted there is no way to reverse it or cancel it.

> it said 4 hours at most to send a payment on that, not almost 8.

This is an estimation, not an affirmation. In general for economy values the transaction could take several minutes/hours to be confirmed.
