### ISSUE TITLE
Deposit to Bitpay card still showing as pending for over 10 hours

### ISSUE THREAD

**Issue by LindaMorris** [bitpay/copay#6609]
There was a deposit made to my bitpay card early this morning (appx 3:30 am) and it is still showing as pending 10 hours later.  I have never had this to happen before.  It is showing that only one blockchain confirmation was needed.  I have used this many times and have never had it still stuck as pending.  Please advise.

UG
21

BitPay
Atlanta, GA 3:07 AM
View Confirmation Status

Top-Up

+ $1,310.00
PENDING

**Comment by JDonadio** [comment]
Please provide the transaction id

**Comment by LindaMorris** [comment]
Transaction 05616f4fd0af007e539f6a6de1164f5325d2569d217e566cfe2cdfc2a24ef7fe

That is the address...is this what you are looking for?  This is the number that shows on the page when I click on the confirmation status.

**Comment by JDonadio** [comment]
If you click on the previous transaction you'll see many small inputs and one (or more) of them are still unconfirmed. So until all of these inputs get confirmed your transaction will not move forward.

https://insight.bitpay.com/address/1FLiuVM4F4frRbQRSrCCZchn1vTuvgYsvm

**Comment by LindaMorris** [comment]
Why would you close this...it is still not resolved? I still do not have the funds nor habe they been returned to the sender. How much longer? I have never waited this long so please tell me what is going on.

**Comment by JDonadio** [comment]
@LindaMorris, we have nothing to resolve because a broadcasted transaction cannot be cancelled or reversed, you have to wait for the confirmations or to be dropped for the mempool. This process unfortunately could take over a week. Sorry about that.
