### ISSUE TITLE
Change address not considering in Copay balance

### ISSUE THREAD

**Issue by LeaTex** [bitpay/copay#6610]
I sent 0,015 Btc from my wallet with 2.67781863 Btc, so I can see the change of 2.662547 in transaction explorer.

https://blockchain.info/tx/050ff24c8ce737a3cfb8cd71edd0c8169e8365f28161ea98fd747f8da3c1d933

But Copay shows me the total (2,677 Btc) to the destination address, it's not considering the change.

The only consideration is that I make the transaction using Electrum wallet, not Copay.

![copaychange](https://user-images.githubusercontent.com/6115573/29534870-153aeffe-868e-11e7-9829-7bb5e3549b15.png)

**Comment by dabura667** [comment]
Perform a rescan.

It's because you made that teansaction outside of Copay.

**Comment by LeaTex** [comment]
How to perform a rescan?

I made a clean cache, but I see the same information in Copay.

**Comment by JDonadio** [comment]
Settings > wallet > more opts > wallet addresses > scan addresses

**Comment by LeaTex** [comment]
Gracias @JDonadio !! Funcionó.
Tuve que hacer ambas cosas, primero busqué direcciones con fondos. Con eso me mostró el balance correcto.
Y luego limpiar la caché de transacciones para que se refresque, y así que los movimientos reflejen el monto correcto (si no hacía esto, me seguía mostrando el envío de la primera imagen con el monto que en realidad corresponde al cambio).

Gracias de nuevo. Pueden cerrar el ticket.
