### ISSUE TITLE
Payment not processed

### ISSUE THREAD

**Issue by FatMacGaming** [bitpay/copay#6611]
I made an auto payment for Copay to process into my wallet August 7th to be processed and verified by 11th August but transaction doesn't show. Where/how do I get this verified?

**Comment by JDonadio** [comment]
Please provide us the transaction id.

**Comment by FatMacGaming** [comment]
My last 3 deposits haven't gone in, below are 2 and the next one was August 14th from my other bank account
![screen shot 2017-08-23 at 11 35 58 am](https://user-images.githubusercontent.com/31231166/29592286-433c8948-87f7-11e7-88e6-e7b253f0d4ff.png)

![screen shot 2017-08-23 at 11 32 55 am](https://user-images.githubusercontent.com/31231166/29592216-e436f2d0-87f6-11e7-9005-5e8d698b7a88.png)

**Comment by JDonadio** [comment]
@FatMacGaming I can't do anything with that information, if you don't provide a transaction id or any other information regarding your wallet issue unfortunately I can't help you.
