### ISSUE TITLE
Copay Copying wrong address

### ISSUE THREAD

**Issue by tomgeschke** [bitpay/copay#6612]
When I want to copy my address to receive BTC a wrong address is copied. If I create a new one and want to copy the new one, a different wrong address is being copied. What's wrong?

**Comment by dabura667** [comment]
Virus on your PC.

**Comment by tomgeschke** [comment]
Well then. Is it sufficient to delete my wallet/uninstall copay or I have to do some more tasks?

**Comment by JDonadio** [comment]
> Well then. Is it sufficient to delete my wallet/uninstall copay or I have to do some more tasks?

Ensure to get your wallet backed up before to remove/delete anything.

Try using the mobile version until you fix the desktop problem. Ensure to scan and remove the possible malwares on your computer.

**Comment by tomgeschke** [comment]
Hello! I installed Bitdefender and tried the 30 days free of it. I scanned the whole system, the issue was found, removed and now everythink works fine :)

**Comment by JDonadio** [comment]
Glad to know it!
