### ISSUE TITLE
1 transaction stuck and 2 don't show on blockchain

### ISSUE THREAD

**Issue by phamduy2310** [bitpay/copay#6613]
the transaction stuck made in 21 Aug but always showing that 2 mins .
And the others 2 made today 22 Aug but no tx id found on blockchain
Here is 3 transactions : 
https://insight.bitpay.com/tx/9e416d997a66deeae2e31cfb92293a34648764d719a71c6edd3a656d095e7a52

the others 2  : 
https://insight.bitpay.com/tx/f74e407be699ae6c553783dd5b21a4b73e3b4668cfe7ae075eef6269136646d2
https://insight.bitpay.com/tx/c0f13e316c24250d8c4b7609ca5d7ce651b8f29928df092bf919731aeca4a58a

Is it possible to cancel the 2 transactions that don't show on blockchain ?

**Comment by JDonadio** [comment]
You just have to wait. Unfortunately there is nothing we can do.

> Is it possible to cancel the 2 transactions that don't show on blockchain ?

No, there is no way to cancel a broadcasted transaction.

**Comment by miguelmorales85** [comment]
I have the same issue, How long do we have to wait?
Everytime I open the wallet the tx is shown like is made "a few seconds ago"
Maybe that is why it is not being sent or cancelled? because the app is always trying to send it everytime one check on it?

**Comment by JDonadio** [comment]
The three transaction are confirmed.
