### ISSUE TITLE
How long should it take maximum to send bitcoins?

### ISSUE THREAD

**Issue by fersijones** [bitpay/copay#6615]

**Comment by JDonadio** [comment]
The confirmation time depends on the how much fee are you adding on your transaction. That fee is for miners and basically the translation is high fee = low time and vice-versa. Sometimes the bitcoin network may be congested claiming even more amount for fee than normal. If for some reason your transaction is not confirmed then will be dropped for the mempool and returned to your wallet in ~1 week as worst case.
