### ISSUE TITLE
Message "Error at confirm 413"

### ISSUE THREAD

**Issue by miguelmorales85** [bitpay/copay#6616]
It seems there is a wallet with a lot of incoming transactions with a low amount. The wallet marks them all as "Amount too low to spend". 
Is there some way to transfer all those BTC to unified them in another wallet?
When I try to move them the message "Error at confirm 413"is shown

**Comment by JDonadio** [comment]
Yes, using the send max option. Go to Send tab > put your recipient address > in the amount section hit the `...` (top-right) and select the `Send max` option.

**Comment by miguelmorales85** [comment]
Following that procedure is exactly how I get to "Error at confirm 413" and cannot send them

**Comment by JDonadio** [comment]
Can you try making a transaction for ~80% of your total amount?

**Comment by miguelmorales85** [comment]
@JDonadio  I think that might work because the error is no longer present when I try to send 0.27 BTC but I want to wipe it all. Do you think a solution could be to send an amount of say 0.5 BTC to that address and now when I get to send all the funds the fee will be taken from that 0.5 BTC and not from all the other bits? Maybe I'm wrong and bitcoins TX doesnt work like that.

**Comment by JDonadio** [comment]
To understand about the amount of fee read [this](https://github.com/bitpay/copay/wiki/COPAY---FAQ#copay-requires-high-fees-for-low-amounts-transactions). Also [this](https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-always-get-insufficient-funds-for-fee-when-trying-to-send) would be helpful.

In the meantime you can try to wipe your wallet using the [recovery tool](https://bitpay.github.io/copay-recovery/)
