### ISSUE TITLE
ayuda error  importar frase

### ISSUE THREAD

**Issue by jonathann22** [bitpay/copay#6617]
buen dia por favor tengo un problema con mi billetera restableci mi telefono y se me elimino la app copay la instale y al momento de importar la copia de seguridad me dice error en la frase de acceso tengo las 12 palabras pero no recuerdo si tenian tildes o no como puedo recuperar mi cuenta para recuperar mis bitcoins gracias por su ayuda

**Comment by JDonadio** [comment]
Hola, mira fijate en esta lista, buscá una por una tus palabras y dejalas tal cual están en esa lista, es decir: sin mayúsculas, tildes, etc.

https://github.com/bitcoin/bips/blob/master/bip-0039/spanish.txt

Espero que te sirva.
