### ISSUE TITLE
wanting to sweep a paperwallet, yet option to do so nowhere to be found in copay v 3.7.1

### ISSUE THREAD

**Issue by JeanLucLejoly** [bitpay/copay#6619]
Hello, I installed the Linux version of the app on my centos7 linux pc. 
The app starts fine, the bottom bar shows me home, receive,scan,send and settings.and in settings the preference option does not show anythign related to 'swipe' as suggested on other forums. 

How can I swipe my paper bitcoin wallets. that I saved prior to the HF with bitcoin cash... and then eventually swipe the bitcoin cash elsewhere.. but for now I just want/need to swipe my Bitcoin from this wallet.

**Comment by JDonadio** [comment]
Hi @JeanLucLejoly, if you scan the privatekey QR from the main scan button a contextual menu will be shown. However if for some reason your camera is not working you can also paste the privatekey in the input situed in the send tab.
