### ISSUE TITLE
No se envia el pago .

### ISSUE THREAD

**Issue by Spectral12** [bitpay/copay#6621]
En horas de la madrugada realize un envio de Copay hacia mi wallet , cuando entro a revisar me notifica Enviando y sin confirmaciones , segun la nota que aparece es debido al Low Fee hay alguna manera de realizar algo estilo CPFP (child pays for parent) para que la transferencia no tarde mas de lo debido ? 

https://insight.bitpay.com/tx/25d8a8f8e98bbeb72cca79fd9145093f0dc0b721712d1cdf53a98083baca0092

**Comment by JDonadio** [comment]
Hola @Spectral12, nosotros no recomendamos ni tenemos una funcionalidad dedicada a eso pero una posible solución es realizar un send max de tus fondos a tu propia wallet, es decir unificar todos tus utxos consolidandolos en uno solo.

**Comment by Spectral12** [comment]
Hola @JDonadio  realizo el envio a cual wallet a la de Copay o a mi otra wallet ?

**Comment by JDonadio** [comment]
A la misma wallet desde donde hiciste la transacción que no se confirma.

**Comment by Spectral12** [comment]
@JDonadio Osea envio todos mis fondos a Copay y luego me los vuelvo a enviar a mi wallet local ?

**Comment by JDonadio** [comment]
Si vos hiciste una transacción desde una wallet A a una B y esa transacción no se confirma y querés acelerar el proceso, entonces tenes que hacer un send max de tus fondos en la wallet A hacia la misma wallet A. 

Pero en este caso no vas a poder, acabo de verificar que tu transacción no tiene change address, por lo que no tenes otra alternativa que esperar a que se confirme o a que se caiga de la mempool. Lamentablemente es la única forma.
