### ISSUE TITLE
How to recieve Bitcoin Cash

### ISSUE THREAD

**Issue by kaiser1919** [bitpay/copay#6622]
Hello!

I've some BCH on the Poloniex. How can I receive this coin from it? 
I should create "BCH only" wallet in Copay. But I don't understand, how... Help, please)

**Comment by JDonadio** [comment]
We do not support BCH yet, but it's on our plans. Please see [here](https://github.com/bitpay/copay/issues/6557). 

For now you must to find another wallet like Coinomi, Electron Cash, etc.

**Comment by kaiser1919** [comment]
Oh, what's a pity!
But Ok, thanks for help.
