### ISSUE TITLE
My transaction doesn't exist, Help please!

### ISSUE THREAD

**Issue by Henrytheluckystick** [bitpay/copay#6623]
Hi, I am trying to send myself some bitcoin from my other Bitcoin wallet to my Coinbase Bitcoin wallet. I put in the right address and everything, and the Bitcoin left my wallet, but after 2 hours It still hasn't been received. I looked up the account Receiving on block explorer and it remains at 0. I then looked up the transaction # on Block explorer and it says "No Transaction Exists" Any idea what happened?

**Comment by Henrytheluckystick** [comment]
![screenshot 4](https://user-images.githubusercontent.com/31292255/29639005-095d1bc2-880e-11e7-9e02-98f17d072f85.png)

**Comment by miguelmorales85** [comment]
TX fee is too low, it happened to me. Maybe in 3 or 4 days the BTC will be back in the sender's wallet.

**Comment by Henrytheluckystick** [comment]
I hope so, that would be great.   thank you.  if it isn't back by next wednesday, I will be updating this post.

**Comment by JDonadio** [comment]
Unfortunately we cannot give you support for another wallet sofware.

> TX fee is too low, it happened to me. Maybe in 3 or 4 days the BTC will be back in the sender's wallet.

Yes, even more.
