### ISSUE TITLE
Cant receive bitcoin?

### ISSUE THREAD

**Issue by coleycdr** [bitpay/copay#6624]
So I was using my miner to mine Bitcoin, I saved up some and spent them on an online store, then my CoPay address changed without my knowledge and I kept mining with the original one and I have $35 unpaid balance on my miner that won't pay because the address "does not exist anymore" when technically it is still the same wallet. Please help me because I really need that money, thank you all for your time.

**Comment by JDonadio** [comment]
Every time a transaction arrives to Copay/BitPay a fresh address is generated, so in a common scenario you'll have many addresses. However, you can create a wallet without this functionality switching on the "Single address wallet (for audit purposes)" in advanced options at the wallet creation time.

Note: All generated addresses are yours and reusable as many times as you want.

**Comment by coleycdr** [comment]
how exactly do I get access to my old address? Because i have that $35 which is still unpaid balance on my miner that I need to login to that address(the old one) to get that money

**Comment by JDonadio** [comment]
In Settings > wallet > more options > wallet addresses you will finde a complete view about your addresses information, even a complete list of used/unused.
