### ISSUE TITLE
Payment Help 

### ISSUE THREAD

**Issue by stepl5** [bitpay/copay#6626]
My payment is not showing in recipient address? Can you advise please!

**Comment by JDonadio** [comment]
Please explain it with more detail

**Comment by stepl5** [comment]
Usually it would say unconfirmed transaction immediately in recipient account, I've sent the payment but it's not showing on recipients account? The address has not changed either

Sent from my iPhone

On 24 Aug 2017, at 15:38, Javier Donadío <notifications@github.com<mailto:notifications@github.com>> wrote:


Please explain it with more detail

**Comment by stepl5** [comment]
1KTqxCZ9HZc1h5UegHiRotQTQJQ4nCGPmV that's the address it was sent to. Is this ok mate? [image1.PNG]

Sent from my iPhone

On 24 Aug 2017, at 15:42, Javier Donadío <notifications@github.com<mailto:notifications@github.com>> wrote:


Attach an screenshot from the sender, paste the tx id, give us more info so we can assist you better.

**Comment by JDonadio** [comment]
No, we need the transaction id associated to your wallet.

**Comment by stepl5** [comment]
On where would I find that mate?

Sent from my iPhone

On 24 Aug 2017, at 15:53, Javier Donadío <notifications@github.com<mailto:notifications@github.com>> wrote:


No, we need the transaction id associated to your wallet.

**Comment by JDonadio** [comment]
Open the app, select your wallet and you will see the history there, select the transaction made and scroll down and tap on "view on blockchain" button. Then copy/paste the transaction id here.

**Comment by stepl5** [comment]
I believe this is it: fbe3458830d07ae301defeacdddb8b0437a9f7cd45435fa9003c23326cbaf2fd
Is that ok?

Sent from my iPhone

On 24 Aug 2017, at 15:58, Javier Donadío <notifications@github.com<mailto:notifications@github.com>> wrote:


Open the app, select your wallet and you will see the history there, select the transaction made and scroll down and tap on "view on blockchain" button. Then copy/paste the transaction id here.

**Comment by JDonadio** [comment]
Yes, thanks. 
Seems like your transaction have a low fee and will be hanging for a while to be confirmed or maybe could be dropped from the mempool in which case the funds will be returned to your wallet.

**Comment by stepl5** [comment]
Ok is that the reason it hasn't shown on recipent end? I've done similar transactions and it shows straight away?

Sent from my iPhone

On 24 Aug 2017, at 16:29, Javier Donadío <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, thanks.
Seems like your transaction have a low fee and will be hanging for a while to be confirmed or maybe could be dropped from the mempool in which case the funds will be returned to your wallet.

**Comment by stepl5** [comment]
??

Sent from my iPhone

On 24 Aug 2017, at 16:29, Javier Donadío <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, thanks.
Seems like your transaction have a low fee and will be hanging for a while to be confirmed or maybe could be dropped from the mempool in which case the funds will be returned to your wallet.

**Comment by JDonadio** [comment]
For Copay/BitPay the recipient should be notified and appear in your history like:

<img width="395" alt="cursor_y_copay_-_copay_bitcoin_wallet" src="https://user-images.githubusercontent.com/13851807/29677462-8fde91da-88d1-11e7-8f22-eba098b37360.png">

**Comment by stepl5** [comment]
Ok well the recipient address has not been notified what do I do? I had a similar issue last week and someone sorted it straight away?

Sent from my iPhone

On 24 Aug 2017, at 17:42, Javier Donadío <notifications@github.com<mailto:notifications@github.com>> wrote:


For Copay/BitPay the recipient should be notified and appear in your history like:

[cursor_y_copay_-_copay_bitcoin_wallet]<https://user-images.githubusercontent.com/13851807/29677462-8fde91da-88d1-11e7-8f22-eba098b37360.png>

**Comment by JDonadio** [comment]
The recipient use Copay as main wallet app or he just use an external seed and imported it into Copay?

**Comment by stepl5** [comment]
I have paid from my copay account into another wallet, I have an address and sent it there and have confirmed the address also

Sent from my iPhone

On 24 Aug 2017, at 17:46, Javier Donadío <notifications@github.com<mailto:notifications@github.com>> wrote:


The recipient use Copay as main wallet app or he just use an external seed and imported it into Copay?

**Comment by stepl5** [comment]
No it's not their main wallet

Sent from my iPhone

On 24 Aug 2017, at 17:46, Javier Donadío <notifications@github.com<mailto:notifications@github.com>> wrote:


The recipient use Copay as main wallet app or he just use an external seed and imported it into Copay?

**Comment by JDonadio** [comment]
So we cannot help in such case. You just must to wait to the confirmations for your transaction.

**Comment by stepl5** [comment]
I sent a payment to the same address 4 days ago and it appeared immediately and processes after 2 days. Same transaction fee % also

Sent from my iPhone

On 24 Aug 2017, at 17:46, Javier Donadío <notifications@github.com<mailto:notifications@github.com>> wrote:


The recipient use Copay as main wallet app or he just use an external seed and imported it into Copay?

**Comment by stepl5** [comment]
Fair enough mate I've used you twice and both times it's gone awry. I appreciate you tried but this hasn't been very helpful at all, you've given me no real help just what "should be". Think this will be my last attempt. Keep up the good service.

Sent from my iPhone

On 24 Aug 2017, at 17:51, Javier Donadío <notifications@github.com<mailto:notifications@github.com>> wrote:


So we cannot help in such case. You just must to wait to the confirmations for your transaction.

**Comment by JDonadio** [comment]
The fee amount depends on the bitcoin network status, if for some reason it's congested your transaction will need more fee, if not, will be haning for a while or maybe be dropped as I mentioned above, which is probably your case. There is not error from our end so if the transaction (successfully broadcasted) is not showing on the recipient app, you must to contact to their support team and ask they about it.

**Comment by stepl5** [comment]
I have a transaction not showing on the blockchain now, says not found could you please advise? Sent to 1KTqxCZ9HZc1h5UegHiRotQTQJQ4nCGPmV

Sent from my iPhone

On 24 Aug 2017, at 17:56, Javier Donadío <notifications@github.com<mailto:notifications@github.com>> wrote:


The fee amount depends on the bitcoin network status, if for some reason it's congested your transaction will need more fee, if not, will be haning for a while or maybe be dropped as I mentioned above, which is probably your case. There is not error from our end so if the transaction (successfully broadcasted) is not showing on the recipient app, you must to contact to their support team and ask they about it.
