### ISSUE TITLE
how do I sweep a paper wallet with CoPay v3.7.3 ?

### ISSUE THREAD

**Issue by b0yk33mp33** [bitpay/copay#6628]
I was testing on sweeping from a paper wallet created from bitaddress.org with CoPay v3.7.3  but I kept getting an error-- "Error sweeping wallet: Insufficient funds. "  after I hit Sweep.  Paper wallet only has 0.000206 btc on it.  Could it be the btc on paper wallet is insufficient to be swept?
![21076546_10155924454995982_2061074444_n](https://user-images.githubusercontent.com/31322005/29683501-2b2443fa-8941-11e7-9e99-730a3ab5160b.png)

**Comment by JDonadio** [comment]
> Could it be the btc on paper wallet is insufficient to be swept?

Yes, that's the only reason.
