### ISSUE TITLE
Transaccion perdida ?

### ISSUE THREAD

**Issue by Spectral12** [bitpay/copay#6629]
Creo de nuevo este post debido a que no he podido solventar el problema que previamente habia posteado Post #6621 . Hice una transferencia de Copay a mi wallet local hace 2 dias . La transaccion se tardo debido al lowfee , cada vez que abria la app me decia que se habia enviado hace 0 segundos y me daba el TX ID 

https://insight.bitpay.com/tx/25d8a8f8e98bbeb72cca79fd9145093f0dc0b721712d1cdf53a98083baca0092

Y este me decia sin Confirmar. Ahora al ir a buscar dicho TXID , me dice Transaction Not Found , y tampoco los BTC estan en mi Wallet de Copay ni en mi Wallet local . Se perdieron mis fondos  ?

**Comment by JDonadio** [comment]
Tu transacción no ha sido confirmada ni tampoco se ha caído, por lo que tendrás que esperar, podes verla aquí: https://blockchain.info/tx/25d8a8f8e98bbeb72cca79fd9145093f0dc0b721712d1cdf53a98083baca0092

De todos modos vamos a investigar el por qué no se puede verla desde Copay. Gracias por reportarlo

**Comment by JDonadio** [comment]
Confirmada
