### ISSUE TITLE
Wallet does not sum up all the BTC's

### ISSUE THREAD

**Issue by wally000** [bitpay/copay#6630]
Hello,

I am new to Copay and this morning I had 0.99 BTC in my wallet. Then, a friend of mine just sent me another 0.5 BTC which I see confirmed in the blockchain (plus I also received an email about the reception from Copay), and I also see it received in the wallet address (see first screenshot). But the main wallet in the initial screenshot does not reflect this new 0.5 BTC just received, like if it wasn't summed up. See attached screenshots. Can you please help?

![image](https://user-images.githubusercontent.com/31010273/29712035-162ecb8a-8998-11e7-8616-5cfba12ff887.png)

![image](https://user-images.githubusercontent.com/31010273/29712048-27f3ff2a-8998-11e7-8a93-092798e72aa8.png)

**Comment by JDonadio** [comment]
Please try using the `scan addresses for funds` option, you can find it at Settings > wallet > more otps > wallet addresses

**Comment by wally000** [comment]
Hi Javier

As you can see in the screenshots that I attached I had already checked the
wallet addresses  and in there I can see my new 0.5 BTC. Nevertheless, I
think this should also reflect in the global balance of the wallet in the
initial page, summing up all the wallet address amounts?

Thanks.

**Comment by JDonadio** [comment]
The error issue remains after the scan? Can you provide us an address or your wallet id?
