### ISSUE TITLE
BAD SIGNATURES Error

### ISSUE THREAD

**Issue by j-vern** [bitpay/copay#6631]
I am having an issue with my multisignature copay wallet with Ledger Nano S: when I need to send a proposal+sign one, I get an error message from copay "Error-BAD SIGNATURES", while on Ledger Nano S, the signature is marked as successful. However, with my professional laptop, it is working as usual.

I am using the copay version 3.7.2 and ledger nano S v1.9.2 on a windows 10 computer on my personal laptop.

Have you already encountered the issue?

**Comment by BGalliotti** [comment]
Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will happy to help you.
Thanks.
