### ISSUE TITLE
Payment from Hash

### ISSUE THREAD

**Issue by bud1316** [bitpay/copay#6632]
It was in my recent transactions this morning, now its gone and my balance is 0.  when i click on it, it says its not available at this time.  any ideas whats going on here?

**Comment by ArneDBKey2info** [comment]
Same for me, did transaction to Jaxx. Now suddenly my balance is 0

**Comment by JDonadio** [comment]
Please provide us the transaction id

**Comment by JDonadio** [comment]
Should be ok now. Please feel free to comment if the error persist
