### ISSUE TITLE
Fees costing OVER $14.58?

### ISSUE THREAD

**Issue by Caiky** [bitpay/copay#6633]
I can't move any money out of my wallet at all. The fees are absolutely insane. I have $14.58 in my wallet, and it is saying that my funds are insufficient.
Is there a way I can fix this?

**Comment by JDonadio** [comment]
https://github.com/bitpay/copay/wiki/COPAY---FAQ#copay-requires-high-fees-for-low-amounts-transactions

**Comment by dabura667** [comment]
The bitcoin network is currently under attack.

It may take a couple weeks to calm down.

Until then, please read the link above.

**Comment by ArneDBKey2info** [comment]
How do you mean, under attack?
