### ISSUE TITLE
Sent BTC to Jaxx, but I can't see the transaction in Copay

### ISSUE THREAD

**Issue by ArneDBKey2info** [bitpay/copay#6634]
On the 19th of August I send BTC's from Coinbase to Copay

A few days later I transferred these BTC's from Copay to Jaxx, for a 1% fee of the entire amound. (around 426 satohis)

Now I haven't received the payment on Jaxx yet, and when I go check my transaction History I only see the payment Coinbase -> Copay.

There is no track of a transaction to Jaxx.

If you need more information, feel free to ask.

**Comment by JDonadio** [comment]
Do you have these funds in your Jaxx wallet?

**Comment by ArneDBKey2info** [comment]
No, they have not appeared in my Jaxx wallet.

**Comment by ArneDBKey2info** [comment]
https://i.gyazo.com/ac569534fa9474116416bd9f5633b5aa.png

This is how my wallet looks like right now. As you can see it's weird. I have received a payment, but I have no outgoing, but my balance is 0

**Comment by ArneDBKey2info** [comment]
Tried sending transaction again after it came back. Same issue, it's stuck on sending. Have not received any BTC's in my Jaxx wallet

**Comment by JDonadio** [comment]
Hi, sorry for the delay. The bitcoin network is congested and claiming more fee than normal. You just have to wait. Do you have the tx id?
