### ISSUE TITLE
Lost transactions

### ISSUE THREAD

**Issue by subik2** [bitpay/copay#6636]
Hi,
Not sure what to do.... i had two uncorfimed incoming transactions, now they gone and balance shows 0.
Thx for help

**Comment by torotto** [comment]
I have the same issue. Payment received was showing on the top but wallet is 0

**Comment by ArneDBKey2info** [comment]
I've had the same problem.
https://github.com/bitpay/copay/issues/6634

**Comment by subik2** [comment]
All sorted now, just took long time
