### ISSUE TITLE
not getting paid?

### ISSUE THREAD

**Issue by coleycdr** [bitpay/copay#6637]
so on my miner I have $37 unpaid balance and I contacted my miner and they said that I need to contact CoPay support because my CoPay address changed and I continued mining on the old one and now it won't pay, is there any way you can work with NiceHash or get the balance to go through or transfer it to my new address? I really need this money, thank you for your time and help.

**Comment by JDonadio** [comment]
By default the wallets created in Copay changes their addresses once receive a payment, but you still are the owner of the "old" address. Please check this out: 

https://support.bitpay.com/hc/en-us/articles/115003004423-Do-I-still-own-old-bitcoin-addresses-

You can find a complete list of your addresses in settings > wallet > more opts > wallet addresses

**Comment by JDonadio** [comment]
If you need a wallet without the default behavior just create a new one and turn on the single addresses (for audit purposes) in advanced options.

<img width="401" alt="cursor_y_copay_-_copay_bitcoin_wallet_y_not_getting_paid__ _issue__6637_ _bitpay_copay" src="https://user-images.githubusercontent.com/13851807/29773615-a71cc29e-8bd4-11e7-9426-1bb15e773427.png">
