### ISSUE TITLE
where do you point copay to communicate with a custom instance of BWS

### ISSUE THREAD

**Issue by streetbits** [bitpay/copay#6638]
In the documentation it says its very easy to switch instances of BWS, but didn't find any docs detailing where to do this?
is it hardcoded or in some config file?

**Comment by dabura667** [comment]
Wallet options > more options > wallet service URL

**Comment by streetbits** [comment]
Oh, it's shown only while creating a new wallet.
Thank you

**Comment by JDonadio** [comment]
At wallet creation time > advanced options
Once created > settings > wallet > more options > wallet service URL
