### ISSUE TITLE
unconfirmed Transactions disappeared and therefor copay shows old balance

### ISSUE THREAD

**Issue by M4goro** [bitpay/copay#6641]
Hi,

I made two transactions from two of my Wallets in copay yesterday on the 25.08.17 and today I noticed that these transactions are now missing in my wallet and my wallet shows my old balance again.
I clicked in the options on update the addresses but didnt change anything. I just saw that the two transactions i made are not confirmed yet but that should delete them out of my wallet and lead to show a wrong balance. Even when i check the box t show not confirmed funds it doesnt change my balance and doesnt bring back the two transactions.

**Comment by JDonadio** [comment]
Please provide us the transacion ids

**Comment by M4goro** [comment]
After the transactions got confirmed - everything was fine again. But it would be nice if you could fix that issure for the future that unconfirmed transactions dont disappear from the wallet and create an chaos in it.

**Comment by JDonadio** [comment]
Thanks for your update. We'll work on that.
