### ISSUE TITLE
Incorrect Funds transferred into copay

### ISSUE THREAD

**Issue by sureena** [bitpay/copay#6642]
The amount I transferred from my wallet was $100 CAD but only .11 came thru into Copay.

**Comment by sureena** [comment]
Sorry it was actually 171.00 MAID on August 18. Please take a look as the currency is missing

**Comment by JDonadio** [comment]
Sorry but I don't understand you. Can you explain it in detail? also we need the transaction id in order to check the amounts. Thanks

**Comment by sureena** [comment]
Hello,

Let me first apologize for the terrible message - the first message posted in error before I could add the information.  Here is what happened - for a test run I transferred 171.00 maidsafe currency which equaled to approx $100.00 Canadian funds from my Coinpayments account to Copay. For some reason the transactions was confirmed in CoPay but only $.11 displayed.  The objective is that I am trying to liquidate all the maid into BTC so I can get all the funds out.  This was a test transaction to make sure it would work okay before I started to move more.

I have attached a screen shot from my Copay account - please let me know what I did wrong and how I can rectify this.

Thanks.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by JDonadio** [comment]
@sureena, you didn't attach any screenshot.

> I transferred 171.00 maidsafe currency which equaled to approx $100.00 Canadian funds from my Coinpayments account to Copay

Provide us the transaction id so we can investigate it

**Comment by sureena** [comment]
Here it is - please let me know if It comes through okay.

Thanks.
Rich

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by sureena** [comment]
Hi Javier,

I see you closed my ticket. I have attached another file with more information that may help you.  Can you plse let me know if you the money is still available and how it can be transferred into my Copay account. Thank you.

Sureena

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by JDonadio** [comment]
> I have attached another file with more information that may help you.

Actually not. I ask you for it twice but you never attach nothing. All you have to do is open your transaction, copy the transaction id and paste it here.

Anyways, you send that transaction **to** Copay, so if you have any problems with your transaction you must contact to the sender. If you provide me the transaction id then I can take a look and try to find something for you, but again, no files/screenshots attached.

**Comment by sureena** [comment]
Hi Javier,

There must be an issue with how I am attaching the files. I am so sorry for the inconvenience. I will email the sender immediately to see if they can help me with this situation as suggestion.

Here is the Traction ID 0a5bc995bc9f34feaab254c54d89a0d73eb0d315ca5860c2f88c1bdbf0d1ccf9

I hope this is correct as I am new to using Copay.

[IMG_4747.PNG]

Thanks for your help and quick responses.

-s

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by JDonadio** [comment]
Ok, now I can see your transaction status. It's already confirmed. You can check it here:

https://insight.bitpay.com/tx/0a5bc995bc9f34feaab254c54d89a0d73eb0d315ca5860c2f88c1bdbf0d1ccf9

Can you provide us your wallet id? You can find it in settings > wallet > more opts > wallet information

**Comment by sureena** [comment]
Thanks - yes I saw that it was confirmed but since i'm a novice I don't understand where the currency went or why it was not received.

As suggested, I have now emailed the Sender Support as well.

Here is my wallet ID: [866dfddf-6e26-4939-a5fb-f087a3f0a63a](http://866dfddf-6e26-4939-a5fb-f087a3f0a63a/)

-s

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by JDonadio** [comment]
These funds are in your wallet. What is your total amount displayed in your screen?

**Comment by JDonadio** [comment]
Try scanning all your addresses, go to settings > wallet > more opts > wallet addresses > scan addresses for funds.

**Comment by sureena** [comment]
Hi Javier,

For the transaction I only received 0.11 USD for this transaction not $100.00 (ish). Its does say confirmed but where is the money! Show me the money :)

So I scanned addresses - there is a section for unused addresses and addresses with balance.  Please let me know what exactly I should be looking for.

Sureena

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by JDonadio** [comment]
The scan addresses process will lead you to the Home screen, but the scan is running in background and your balance will be update.

The transaction is confirmed and these funds (0.0000273) are in your wallet. If you was expecting more money then you have to contact to the sender. Everything looks Ok
