### ISSUE TITLE
Unconfirmed transaction since 2 days - and transaction not found

### ISSUE THREAD

**Issue by Alagagus** [bitpay/copay#6644]
Hello,
2 days ago i sent some btc to another wallet.
 (this transaction dc0caa94557814823ac65f75f25d3ff8a61370bf33e6ba0069159639d97af967)

Then 30h after i sent it, it was still unconfirmed and it was shown in my wallet again and the transaction got deleted out of my wallet history.
Then i just sent it again with a higher fee (another wallet address), and when i try to view it on blockchain it says "transaction not found"
(link: https://insight.bitpay.com/tx/e077950bf3fa07df9f5c07fa3e1f0e0397a6691d89e9eb099adf8acbf362efb1 )
Transaction (not found) but it shows my wallet (e077950bf3fa07df9f5c07fa3e1f0e0397a6691d89e9eb099adf8acbf362efb1)

Please help me,
Thanks

**Comment by ArneDBKey2info** [comment]
I've had the same problem.
https://github.com/bitpay/copay/issues/6634

**Comment by JDonadio** [comment]
This transaction is already confirmed: https://insight.bitpay.com/tx/dc0caa94557814823ac65f75f25d3ff8a61370bf33e6ba0069159639d97af967

This transaction `e077950bf3fa07df9f5c07fa3e1f0e0397a6691d89e9eb099adf8acbf362efb1` is not on the blockchain because was dropped from the mempool caused a low fee.

**Comment by TheProphetz** [comment]
Caused a low mofu, are we here to share with every transaction 1 coffee?
