### ISSUE TITLE
'Could not broadcast payment: error querying the blockchain'

### ISSUE THREAD

**Issue by mouaadBenAllal** [bitpay/copay#6646]
Yesterday i wanted to tranfser my bitcoins to bitfinex, but i couldn't..   i have read that it might be the fee problem.. what can i do now? my bitcoins are locked atm.

Hope to hear soon from anyone!
<img width="443" alt="screen shot 2017-08-27 at 01 20 10" src="https://user-images.githubusercontent.com/17025763/29749338-4227459a-8b29-11e7-9ebf-0901cc2f9f24.png">
<img width="428" alt="screen shot 2017-08-27 at 01 20 58" src="https://user-images.githubusercontent.com/17025763/29749339-4554b2c0-8b29-11e7-9f5f-eeb2cdfe6ef6.png">
<img width="429" alt="screen shot 2017-08-27 at 01 20 28" src="https://user-images.githubusercontent.com/17025763/29749340-49292174-8b29-11e7-87c7-5f8dd3f93228.png">

**Comment by JDonadio** [comment]
Please, try deleting the proposal (scroll down in that view) and create it again.

**Comment by mouaadBenAllal** [comment]
Ty, the payment was broadcasted and received it!
