### ISSUE TITLE
Recovery tool for Bitcoin Cash

### ISSUE THREAD

**Issue by btcrida** [bitpay/copay#6648]
I had deposited some BTC in my Copay wallet late July, before August 1.   I have now removed the BTC out of that wallet, and am trying to retrieve my Bitcoin Cash.  

When using the recovery tool, and choosing the bch/livenet chain, it's telling me I have 0 Bitcoin Cash.  

What am I doing wrong here?

Thank you.

**Comment by JDonadio** [comment]
> I had deposited some BTC in my Copay wallet late July, before August 1

Are you completely sure? 

If your BCH balance is 0 then try using a major GAP (like 30).

Please, for recovery tool issues please create an entry [here](https://github.com/bitpay/copay-recovery/issues)
