### ISSUE TITLE
Url scheme copay:// is not handled by Android app

### ISSUE THREAD

**Issue by lewixlabs** [bitpay/copay#6650]
As i wrote in subject issue,
connecting copay app to coinbase service doesn't work because custom url scheme
copay://
is not registered in copay app activity.
Workaround is copy/paste long authorization code in copay app (by "register code" menu)

**Comment by cmgustavo** [comment]
Hi, it 's a known issue for some android versions/devices. Could you provide us more info of your device? Android version? Thanks.

**Comment by lewixlabs** [comment]
Hi Gustavo,
my device is
- Nexus 6
- Android 7.1.1
- url copay:// tested on Google Chrome for Android v60

I developed an app for Android wich uses url scheme and with Chrome i never
had issues
If you need more infos tell me.

Hi,
Lewix


Il giorno lun 28 ago 2017 alle ore 17:10 Gustavo Maximiliano Cortez <
notifications@github.com> ha scritto:

**Comment by BGalliotti** [comment]
Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will happy to help you.
Thanks.
