### ISSUE TITLE
Lost copay wallet

### ISSUE THREAD

**Issue by hengdog** [bitpay/copay#6651]

**Comment by JDonadio** [comment]
Explain your issue so we can try to help you

**Comment by hengdog** [comment]
I recently dropped my iPhone in the lake. Fortunately, the iPhone allegedly backs everything up to the cloud. When I got my new iPhone and they downloaded Copay from the cloud it only had one of my "wallets", and I can't seem to recover the other one with what I believe is the recovery phrase.

**Comment by JDonadio** [comment]
Yes, in order to recover your funds you need a backup. Please take a look here: https://support.bitpay.com/hc/en-us/articles/115003004363-I-lost-my-wallet-or-changed-my-phone-What-can-I-do-to-restore-my-wallet-

**Comment by hengdog** [comment]
I have my recovery phrase, but when I put it in, it says it's not valid. Any other ideas?

**Comment by JDonadio** [comment]
You written it down in a wrong order or with any missing/wrong character. You can check the complete list of your language here: https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md

**Comment by hengdog** [comment]
Thank you for your help, JDonadio. All the words in my phrase are.viable. I copied and pasted them, so the order should be correct. It appears I am out of luck. I'm curious who gets to "scoop up" all these lost digital accounts? Someone has to have the ability to track these accounts and retrieve them.

**Comment by JDonadio** [comment]
Unfortunately it does not work that way. The keys are stored in each device so the user is the only owner of these funds.

You must to review the sort if each word was written correctly.
