### ISSUE TITLE
No anote las 12 palabras claves

### ISSUE THREAD

**Issue by xMathh** [bitpay/copay#6653]
Por problemas de la resolucion de pantalla al abrir el programa, la ventana me aparecia cortada por la mitad, cerre el programa y no anote las palabras. Se puede cerrar la cuenta y abrir una nueva desde mi PC? Muchas gracias.

**Comment by JDonadio** [comment]
Hola @xMathh, Copay no maneja cuentas ni usuarios. Podes cerrar y abrir Copay cuantas veces quieras, si no anotaste las palabras, abri Copay y en Settings > wallet > backup vas a poder ver las palabras y anotarlas.

**Comment by xMathh** [comment]
Muchas gracias, ya lo solucione, saludos!
