### ISSUE TITLE
Recovering multisig wallet with Trezor 

### ISSUE THREAD

**Issue by koalalorenzo** [bitpay/copay#6655]
Hello,
I am trying to figure out how I can recover access to my wallet. I have 2of3 multisig wallet, where 1 signature is my Trezor wallet, and the other two are iPhones. I formatted one iPhone, thinking that I had the backup, but apparently the one that I got had no private keys inside (I think anyway I wrote the passphrase somewhere).

To easily access the funds, I would like to transfer them, I already made a proposal that got accepted by one key, but I want to recover the wallet and use the Trezor to sign the other one. I do have access to the trezor, but I have no idea how and if it is possible to restore the shared wallet by using the Trezor.

How can I get my funds back?
Probably this is not an issue, probably this is more a feature request if this is missing.
Note: I am using the Chrome App.

**Comment by HostFat** [comment]
Can this be useful?

https://github.com/bitpay/copay/blob/master/backupRecovery.md

**Comment by koalalorenzo** [comment]
@HostFat I am checking it quickly... it doesn't speak about Hardware wallet with multisig :(

**Comment by koalalorenzo** [comment]
The main problem is that the backup that I have is restoring a wallet without the private key (that is stored on the Trezor) and I am not sure how to restore it, with the connection to the hardware wallet.

Is there any procedure for this somewhere?

**Comment by koalalorenzo** [comment]
Found a way to do it actually:

When I am importing the wallet from the Trezor, I need to specify "Shared wallet" and I need to change the account ID to the one used. (I didn't know that as it was not clear). So if you live the account to 1, it will lead to one wallet. If you modify it to the right number it will provide you the right one. Clever, but not easy to understand.

I thought that was a missing feature. but it is there... it is just hard to get to it if you have an Hardware Wallet.
