### ISSUE TITLE
Can I backup wallet anytime again and again?

### ISSUE THREAD

**Issue by McFuhr** [bitpay/copay#6660]
I've created a wallet and obtained its backup phrase. Can I backup again, and get a brand new backup phrase, which makes the previous phrase obsolete?

I was wondering if this could be done, if the wallet is still active and I forgot or lost its backup phrase?

**Comment by Gamboster** [comment]
You can backup as many times as you want. But you will always get the same result for the same wallet. 
The backup phrase will never change for a particular wallet.

To do the backup you should go to:
Settings -> YourWallet -> Backup
