### ISSUE TITLE
Receiving bitcoin not being displayed, unless I reboot iPad

### ISSUE THREAD

**Issue by McFuhr** [bitpay/copay#6661]
Now I'm emailed that my wallet is receiving/received bitcoin. But it doesn't show on my CoPay iPad wallet. I need to reboot the iPad to see if the transaction actually happened. This is a real pain.
Will this be rectified? I don't think this was happening a few days ago. But now has happened for my last 2  receiving transactions.

**Comment by JDonadio** [comment]
Thanks for report it. Please follow your previous ticket to be updated. https://github.com/bitpay/copay/issues/6654
