### ISSUE TITLE
Been trying to send funds ... it says sending but never received been like that for 7 days 

### ISSUE THREAD

**Issue by asaprencie** [bitpay/copay#6669]
I'm trying to send bitcoins to another wallet .. it says sending but never have no confirmation or is seen on the block chain board .. what's the issue??

**Comment by JDonadio** [comment]
Provide the transaction id

**Comment by asaprencie** [comment]
Idk where it is but this what it's been saying

**Comment by JDonadio** [comment]
Open the transaction detail, scroll down and click on `view on blockchain`

**Comment by asaprencie** [comment]
It says that ...

**Comment by JDonadio** [comment]
If you do not provide the transaction id I cannot help you. You can wait for the confirmation or be dropped from the mempool.

**Comment by asaprencie** [comment]
I just told you I don't know what you mean when you say transaction ID ...
obviously you see on the screenshot it says transaction not found ..

**Comment by asaprencie** [comment]
And it keep saying it's sending and you seen it's been sending for like 7
days ...

**Comment by JDonadio** [comment]
Clicking on the `View on blockchain` button leads you to the insight page, like this **example**: https://insight.bitpay.com/tx/6f1b8e0cc4d31efa51949db2afb0e31be337275a9abb01c74ca0fffb33058856

Check the entire code after `/tx/` that's your transaction id. Please copy and paste it here.

**Comment by asaprencie** [comment]
I click on it on mines and it says NOT FOUND

**Comment by JDonadio** [comment]
Go to settings > wallet > more opts > wallet information, copy and paste your wallet id. Also I need to know the exactly amount of that transaction and whatever other information will helps.

**Comment by asaprencie** [comment]
0b2e4664-5731-49ca-bcc7-56957a755bce and it was 49.78 USD AND 24.68 USD

**Comment by JDonadio** [comment]
Both sent august 15?

**Comment by asaprencie** [comment]
Yes

**Comment by JDonadio** [comment]
https://insight.bitpay.com/tx/48468bddf8a5aff33c7eebc864d5e58e8a0fd043e7d146a10a3b49a779bb4e5a
https://insight.bitpay.com/tx/aec837a277c7b80dd23d6280dadb1e0dc58d2098e4c4281a79696d5170b11bff

Both transactions are already confirmed. In the meantime go to: 

* Settings > wallet > more opts > wallet history > clear cache. 
* Settings > wallet > more opts > wallet addresses > scan addresses for funds.

Check for the update of your balance and history.

**Comment by JDonadio** [comment]
Can you attach an screenshot of the error showing the `Not found` message please?

**Comment by asaprencie** [comment]
Okay
