### ISSUE TITLE
Cannot Access my BCH using Recovery Tool

### ISSUE THREAD

**Issue by blueknight02** [bitpay/copay#6670]
I have all my multisig mnemonic back up seeds, one of which being from a Ledger HW. I believe this is causing the issue. How can I access my BCH from my multisig Copay account if one of the keys is from a Ledger HW? Like I mentioned, I have all the backup seeds and figured this would be relatively simple.

**Comment by JDonadio** [comment]
Unfortunately you cannot use the recovery tool if one of your seed comes from HW. Please check https://github.com/bitpay/copay/issues/6645

**Comment by blueknight02** [comment]
This seems to be a major oversight...What can be done about the many people
who use Copay and HW wallets together? There must some sort of remedy.

**Comment by JDonadio** [comment]
Your private keys are all what you need to keep your funds safe. Unfortunately the recovery tool does not support that cases for now, but you can use any other software to claim your BCH coins.

**Comment by blueknight02** [comment]
Please recommend a software that would allow me to do this considering
yours does not. I've been searching and unable to find anything that works.

**Comment by JDonadio** [comment]
We are not aware about other software, but as I mentioned in #6645 we will support BCH soon, sorry for the inconveniences.
