### ISSUE TITLE
Other cryptocurrencies

### ISSUE THREAD

**Issue by rmdedreu** [bitpay/copay#6672]
Hi,

I was wondering if it is possible to store IOTA and other cryptocurrencies in my copaywallet.
Can I add exchanges different from coinbase to my copay app?

Thanks,

**Comment by JDonadio** [comment]
Hi,

Copay only support BTC for now, but very soon will support BCH as well. https://github.com/bitpay/copay/issues/6557

About the integration to buy and sell unfortunately there are not more options than the currently provided, Coinbase and Glidera.
