### ISSUE TITLE
Excessive fees, even on super economy

### ISSUE THREAD

**Issue by pablolarrimbe** [bitpay/copay#6677]
Is Copay getting info from the mempool before suggesting the fees?

As we saw, a couple of hours ago the mempool cleared up and there were pretty much only transactions with 0-5 satoshi / byte left. However Copay's Super Economy option was suggesting to use 120 satoshi / byte.  I wonder if that value is hardcoded or it's obtained based on real-time data.  I would suggest you to do the latter which will save money to the user.

BTW, I know you can customize it but a lot of users don't really know what is a good fee at a particular time and it seems that people end up overpaying transaction fees.

**Comment by dabura667** [comment]
Copay uses Bitcoin Core's estimatefee command. Super Economy is with the nBlocks argument set to 24.

Bitcoin Core fee estimation is broken.

**Comment by pablolarrimbe** [comment]
@dabura667 Should we file a bug to Bitcoin Core?

**Comment by dabura667** [comment]
There are already many bugs.

They don't concentrate much on the wallet related functions, and are more concerned with performance improvements to make it easier to run a full node.

iirc 0.15.0 should have a new estimatesmartfee command, which should be a little better, but looking at your mempool directly is a tad dangerous without activating RBF on the transaction.

You never know when a block won't be found for 50 minutes and fees skyrocket from 5 to 150 sat/byte.

**Comment by JDonadio** [comment]
We know the estimation for the current levels are not the best but you can now set your own custom fee.
