### ISSUE TITLE
Any other way to recover my account

### ISSUE THREAD

**Issue by ThidasAponsu** [bitpay/copay#6682]
I had a copay account last year with a balance of 0.003BTC but I lost the recovery phrase and deleted the app from my device. I was wondering whether there is ANY possible way whatsoever to recover my account. I'd be willing to provide necessary details. Any reply would be appreciated.

Thanks.

**Comment by JDonadio** [comment]
Hi @ThidasAponsu,

Unfortunately not. Without a backup your funds are lost. Please take a look here: https://support.bitpay.com/hc/en-us/articles/115003004363-I-lost-my-wallet-or-changed-my-phone-What-can-I-do-to-restore-my-wallet-
