### ISSUE TITLE
spending password lost

### ISSUE THREAD

**Issue by sunotis** [bitpay/copay#6691]
seems i forgot my spending password.
i have read some other issues here about that, but that doesn't work for me.
e.g to simply delete and import it again .. because when importing it does not allow me without spending password again.
i know my recovery phrase. but it's totally blocked with that spending password

**Comment by sunotis** [comment]
i tried this on the mac desktop copay wallet version

**Comment by JDonadio** [comment]
Hi @sunotis, please check this out: https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-forgot-my-wallet-spending-password-is-there-a-method-to-reset-it

The import process does not ask for the spending password but for the encrypted backup file.

**Comment by parkermor** [comment]
@sunotis 
I can recover crack your wallet password if you want need help send me email : anywalletrecovery@gmail.com
