### ISSUE TITLE
Is it possible to recover old account?

### ISSUE THREAD

**Issue by wildunne** [bitpay/copay#6692]
Back in the days when you logged in with in account I had a wallet with some coins. Is it possible to recover this?

**Comment by wildunne** [comment]
I think it relates to https://copay.io/in/0.9 being down? I'm guessing that's where it would need to be done

**Comment by JDonadio** [comment]
To gain access to your wallet you need a backup file. It's the only way. Please check this out: https://support.bitpay.com/hc/en-us/articles/115003004363-I-lost-my-wallet-or-changed-my-phone-What-can-I-do-to-restore-my-wallet-

**Comment by wildunne** [comment]
Hi JDonadio, this wallet was from back in the account days using the insight servers to log in. Or should I still have a backup? If I should it will unfortunately be lost

**Comment by yue816** [comment]
Hi JDonadio, I have the similar issue. I followed the instruction of importing previous wallet "Add Wallet > Import Wallet > Wallet Recovery Phrase". I did remember the 12 words phrase, but it shows that" Error -Wrong number of recovery words:1" . Can you help me with this issue? I saw there is a blank of password in "Advanced Options", which password dose this indicated to?

**Comment by dabura667** [comment]
@yue816 you need to place spaces between each word. ie: `我 是` OK  but `我是` NOT OK

**Comment by dabura667** [comment]
and leave the password blank

**Comment by parkermor** [comment]
@wildunne 
@yue816 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com

**Comment by richardsonn09** [comment]
@wildunne
@yue816
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
