### ISSUE TITLE
Incorrect balance

### ISSUE THREAD

**Issue by ghost** [bitpay/copay#6693]
I created a new wallet and sent some funds from another wallet (Exodus). When the funds arrived, the BTC amount was correct but the fiat currency equivalent was wrong, i.e. much less. This does not inspire much confidence. Any idea how to resolve this?

I've already scanned addresses for funds to no avail.

**Comment by matiu** [comment]
Can you send a screenshot? That is the expected Exchange rate?

**Comment by maxzahariadis** [comment]
Thanks for your reply. 

I'd rather not share my balance if at all possible. The BTC amount is correct but the fiat equivalent is much much less than it should be (using current BTC to USD rate). Have you seen this issue before?

**Comment by maxzahariadis** [comment]
Thanks for your reply. 

I'd rather not share my balance if at all possible. The BTC amount is correct but the fiat equivalent is much much less than it should be (using current BTC to USD rate). Have you seen this issue before?

**Comment by matiu** [comment]
What exchange rate do you expect?

**Comment by maxzahariadis** [comment]
Current official exchange rate is $4648 per BTC (Coinbase). When I multiply this with the BTC showing in my Copay BTC balance, the figure I get is significantly higher than the amount in my Copay dollar balance. (Copay seems to use a lower exchange rate of approx $4521 per BTC which is significantly lower than actual exchange rate). Does that make sense?

**Comment by matiu** [comment]
Copay uses Bitpay 's rates:
https://bitpay.com/bitcoin-exchange-rates

Usd amount are only shown for reference.

**Comment by maxzahariadis** [comment]
Thanks—I'm still confused however. How can the Bitpay rate be hundreds of dollars lower than the  rates offered by the biggest exchanges (Coinbase, Kraken, Bitfinex, etc)?

**Comment by maxzahariadis** [comment]
ok thanks

**Comment by BlackTiger1500** [comment]
I made another issue request and I have a similar situation.
