### ISSUE TITLE
Make Bitcoin Network Fee Policy per wallet

### ISSUE THREAD

**Issue by abrkn** [bitpay/copay#6696]
The setting is currently app-wide. I would like to use "Economy" for my Bitcoin-wallet and "Super Economy" for my Bitcoin Cash-wallet.

**Comment by matiu** [comment]
Hi, for the moment, Bitcoin Cash wallets always used "normal" policy fee (fixed in the code). Given the Bitcoin Cash network status, there is no value difference for the different policies (and we except to be always like that ;-) )  We need to adjust the UI to better reflect that.

**Comment by abrkn** [comment]
Assuming there will be more forks (SW2MB, SW1MB, SW2MB-Schnorr, SW2MB-NoSchorr, SW1MB-Schnorr, SW1MB-NoSchnorr, possibly all the way to SW2MB-NoSchnorr-NoMAST, etc) I think it's better just to make the setting network-specific today

**Comment by JDonadio** [comment]
The global settings for fee policy is app-wide. However you can change it at confirm time before send the transaction. As matiu said, BCH transactions use "normal" but it's extremely low, like ~0.000002
