### ISSUE TITLE
Imported a private key from paper wallet. 

### ISSUE THREAD

**Issue by kew02** [bitpay/copay#6698]
I imported a private key from a paper wallet. I wrote in my 12 word phrase, and private key password. The correct amount was stated, but it had not shown up in my copay wallet, and it does not say uncomfirmed. It's been over 24 hours since I swept my paper wallet into copay app. Any suggestions how I can see the amount in my wallet?
Thank you.

**Comment by Gamboster** [comment]
Could you provide us the transaction ID? Or sen a photo? so I can check

**Comment by kew02** [comment]
Hello,
Thank you for getting back to me so quickly. I'm new to copay and I can't locate a transaction Id. After I swept my paper wallet I saw the correct amount on the copay screen for a few seconds and then gone. My wallet is showing zero bitcoin and no transactions. 
I tried sweeping it again, but it says that the paper wallet amount is already in copay. 
I can't find it anywhere in my copay app. 
It's still shows up in blockchain. Any other suggestions? 
Thank you,
Karen

**Comment by Gamboster** [comment]
Could you tell me the exact amount you tried to swept and when it was?

**Comment by kew02** [comment]
The amount I swept was 0.1172 and it was either on September 2 or 3. Thank you for your continued help.

**Comment by Gamboster** [comment]
When you seep a paper wallet, you choose to which wallet you want to send your funds.
So go to that wallet, and check if you have the receiving transaction there.
If you can see the transaction, go to transaction details and then you can click on "View on blockchain".

If you can not do that. Please provide me your wallet ID
Go to settings > wallet > more opts > wallet information, copy and paste your wallet id.

**Comment by kew02** [comment]
Hi, my wallet ID is-
f40fd776-df2e-43d0-941e-336a3f75c857
Please let me know if you find my transaction for 0.1172 on Sept 2 or 3. 
It's no longer in my blockchain.info account. It's out of my paper wallet and not in my copay wallet. 
Karen Widman

**Comment by JDonadio** [comment]
> I tried sweeping it again, but it says that the paper wallet amount is already in copay.

There is not message like that in Copay. But just to confirm can you attach some screenshot?

> my wallet ID is- f40fd776-df2e-43d0-941e-336a3f75c857

I'm afraid that id doesn't belong to Copay. Did you paste it? please check all the characters. In the meantime, you can provide an address from that wallet as well.

**Comment by kew02** [comment]
My wallet address- 
19tavYcqj7hhMdEfPE3HxzetRchxCtY9mQ.  Please take a look and let me know if you can locate my imported wallet from a paper wallet. The amount- 0.1172.

**Comment by JDonadio** [comment]
@kew02 Copay have not the ability to `import` paper wallets, just sweep it. The sweep process is just scanning your private key QR code in order to find the amount stored and give you the option to send these funds into an already created wallet.

Your wallet is empty. So you didn't send or sweep any funds.
