### ISSUE TITLE
Insufficient funds

### ISSUE THREAD

**Issue by HenryBt** [bitpay/copay#6700]
I received 0.19 btc and they are in my account, but when I try to send any amount to my other wallet, the message: insufficient fund

**Comment by dabura667** [comment]
Did you try tapping "send max" with the option on the upper right?

**Comment by JDonadio** [comment]
![cursor_y_copay_-_copay_bitcoin_wallet](https://user-images.githubusercontent.com/13851807/30061700-c7c72d2c-921e-11e7-95be-1a4670e33850.png)

**Comment by HenryBt** [comment]
Print: https://imgur.com/gallery/TwVsP

**Comment by JDonadio** [comment]
Can you please provide your wallet id? you can find it in settings > wallet > more opts > wallet information

**Comment by HenryBt** [comment]
b81f212c-7c01-406d-921e-51fcbb5f06f9

**Comment by HenryBt** [comment]
@JDonadio News? How can we solve this?

**Comment by JDonadio** [comment]
Your wallet is `testnet` but anyways I'm checking.

**Comment by JDonadio** [comment]
You're trying to send funds from a `testnet` wallet to a `livenet` wallet.
