### ISSUE TITLE
Help with copay addresses (Support request)

### ISSUE THREAD

**Issue by Sklopoaybr** [bitpay/copay#6701]
Hello!

I used copay wallet to contribute to Aeternity project and sent 0.1 BTC.
I see that transaction was made from address 1598YbBQVxFTmxnVVQtLRF2NTbT2Gg3wNv but this address doesn't correspond with my wallet mnemonic phrase and is not in the list of wallet addresses. In fact, I need address-mnemonic phrase combination to access tokens.
Is there any way to access private key/mnemonic phrase for 1598YbBQVxFTmxnVVQtLRF2NTbT2Gg3wNv address?

Transaction ID, contribution to AE
https://insight.bitpay.com/tx/566344e8a7b8d3c4b655bf25a7cea40e80154aed27f562204a15ba51680746e3

Address 1598YbBQVxFTmxnVVQtLRF2NTbT2Gg3wNv was credited from my address 16u9GdrDjfEiFb7mMuJrjT9NFF4MUy9Cdc (for this I have mnemonic phrase)
https://insight.bitpay.com/address/1598YbBQVxFTmxnVVQtLRF2NTbT2Gg3wNv

**Comment by dabura667** [comment]
Aeternity is a scam. I'm afraid you just lost 0.1 to scammers.

**Comment by dabura667** [comment]
Also, 1598YbBQVxFTmxnVVQtLRF2NTbT2Gg3wNv is a change address in your wallet.

Don't enter your mnemonic phrase in their app though. It will steal the rest of your bitcoins.
