### ISSUE TITLE
Bitcoin cash

### ISSUE THREAD

**Issue by Between1stand2nd** [bitpay/copay#6702]
I had a small amount of bitcoin in the wallet on August1.  Is there any chance to receive bitcoinCash?

**Comment by JDonadio** [comment]
Please try with https://bitpay.github.io/copay-recovery/

**Comment by JDonadio** [comment]
Ensure to select `bch/livenet` chain

**Comment by Between1stand2nd** [comment]
Thank you so much for your quick turnaround.
However, I received an error message saying "Mnemonic wallet seed is not
valid."
Is it because the backup phrase is in Japanese?  For your info, I attach
the schreen shot.

Please let me know what to do.

Thanks and best regards,
Sunie

2017-09-05 23:00 GMT+09:00 Javier Donadío <notifications@github.com>:

**Comment by JDonadio** [comment]
There is not screenshot attached. Please, do not share your recovery phrase. If your mnemonic phrase is not valid, check each word in this list: https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md

**Comment by Between1stand2nd** [comment]
I have checked all the words and tried again but the same message appears.
I don't know what is wrong.

2017-09-05 23:31 GMT+09:00 Javier Donadío <notifications@github.com>:

**Comment by JDonadio** [comment]
If you have an invalid seed, you could not use it. You must to verify what are you missing, if it's grammatical issue, sort issue, etc.

**Comment by dabura667** [comment]
@Between1stand2nd I just tested the valid Japanese BIP39 phrase:

`げこう　はそん　つわり　ややこしい　きびしい　かいつう　ちょさくけん　とちゅう　ぽちぶくろ　にんげん　たいよう　たいねつ`

And it worked in the recovery tool, it did not give me an "Mnemonic wallet seed is not valid." error.

So the tool supports Japanese phrases fine... your phrase was probably written down wrong...

日本語が母国語ですか？それとも外国の方ですか？

**Comment by LeandroCaboGuillot** [comment]
Hi, I had BTC in my copay account until August 7. How can I claim my Bitcoin Cash? Thanks

**Comment by JDonadio** [comment]
https://bitpay.github.io/copay-recovery/

**Comment by valckeh** [comment]
about https://bitpay.github.io/copay-recovery/  Do you have to enter the recovery phrase and/or a backup password and/or the private key password? Or just one of those three boxes? And what happens then? How will you see where your bitcoin cash is? Please provide me with some more details if possible. Thanks.

**Comment by LeandroCaboGuillot** [comment]
Thanks for recomend me to use the recovery tool https://bitpay.github.io/copay-recovery/ but when I enter de 12 words password the result is showing I don´t have enought funds because on the 7 of august I sent mi BTC to Trezor. How can I claim my Bitcoin cash them?

**Comment by valckeh** [comment]
Hi Leandro, my comment was ment for JDonadio, sorry about that, maybe I should have opened a new issue with my comment/questions...  There seems to be quite a lot of people who have questions about how to claim btc cash... Also for me it is not clear how to do it with this copay-recovery tool. They should give step-by-step details on how it works. I found an article that might help you? https://blog.btc.com/how-to-recover-your-trapped-bitcoin-cash-from-other-wallets-24b929543f26

**Comment by Between1stand2nd** [comment]
I have no idea why I am included in the chain of emails.
Please exclude me as I am not relevant.
Thanks

2017-09-07 15:10 GMT+09:00 valckeh <notifications@github.com>:

**Comment by JDonadio** [comment]
Just put your backup (and password if you have one), select the `bch/livenet` chain, accept the terms and scan.

**Comment by JDonadio** [comment]
@Between1stand2nd you must unsubscribe (unwatch) from this thread.

**Comment by Between1stand2nd** [comment]
Hi Javier,
I accessed the BTC site and tried to import copay wallet.  As copy is not
BIP44 compatible, I chose "simple private keys" and filled in the recovery
words.  However, it didn't work.
Please let me know what to do.

Thanks

2017-09-07 22:26 GMT+09:00 Javier Donadío <notifications@github.com>:

**Comment by JDonadio** [comment]
@Between1stand2nd 

> I accessed the BTC site

You mean the recovery tool?

> tried to import copay wallet

There is not website for import process, just the wallet app. If you are using the recovery tool it's just for check and move your copay wallet funds.

> As copy is not BIP44 compatible, I chose "simple private keys" and filled in the recovery
words.

I have not idea where are you looking. We cannot give you support for another external platforms

**Comment by Between1stand2nd** [comment]
In the wallet app, there is "import external wallet" process.  Please
confirm with the app.

Thanks

2017年9月7日(木) 22:52 Javier Donadío <notifications@github.com>:

**Comment by JDonadio** [comment]
@Between1stand2nd there is not "import external wallet" process. If you have a recovery phrase from another wallet software you must to `create` a new Copay wallet specifying the custom phrase in advanced options.

**Comment by Between1stand2nd** [comment]
Javier,
Sorry that I wasn't clear enough.
I opened the BTC site following the message from Valckeh to Leandro.
Please see the mail.

Also, please see the attached schreenshots I've seen.  There is certainly
"import external wallet" at the BTC.com site.

Thanks

2017-09-08 0:20 GMT+09:00 Javier Donadío <notifications@github.com>:

**Comment by JDonadio** [comment]
We have nothing to do with BTC.com.

**Comment by Between1stand2nd** [comment]
Dear Javier,
I successfully recovered bitcoin cash by clicking the link you first
emailed to me.  I don't know what I'd been wrong.  Anyway, I'm relieved now.

On the other hand, would you let me know how to restore the bitcoin cash in
my copay wallet?  I don't see any bitcoin cash in my copay wallet.

Thanks

2017-09-08 21:34 GMT+09:00 Javier Donadío <notifications@github.com>:

**Comment by JDonadio** [comment]
@Between1stand2nd Bitcoin Cash is not supported yet, we are still working on it.

**Comment by JDonadio** [comment]
Follow [this](https://github.com/bitpay/copay/issues/6557) to be updated
