### ISSUE TITLE
App freezes after manually setting fee

### ISSUE THREAD

**Issue by dmerrick** [bitpay/copay#6704]
I'm on macOS 10.12.6.

On the version 3.7.4 of bitpay and copay, when I set a custom fee, the app becomes unresponsive and I have to restart or reload it.

Steps to reproduce:

1. Select '`Send`' from the bottom navbar
2. Paste in a wallet address
3. Click the '`...`', and choose '`Send maximum amount`'
4. Pick the wallet you wish to send from
5. Click to change the fee
6. Choose '`Custom`' and enter a new amount
7. Click '`OK'` at the prompt
8. App is now unresponsive, and nothing can be done

**Comment by JDonadio** [comment]
Hi there,

I could not reproduce it. How much is your custom fee?

**Comment by JDonadio** [comment]
Ok I did, let me check it. Thanks for report it

**Comment by dmerrick** [comment]
Thank you for looking!

**Comment by miguelmorales85** [comment]
This happens to me in Ubuntu 16.04 LTS when I set the fee to 1 or 2 sats.

**Comment by JDonadio** [comment]
Thanks @miguelmorales85, I'm working on it.
