### ISSUE TITLE
Cant send BTC from Copay Wallet

### ISSUE THREAD

**Issue by thelifeisfun** [bitpay/copay#6706]
Trying to send btc to another wallet.
I paste de wallet address in the Send "section", but nothing happens. There is no Confirmation or Send or Done Button. Am I doing smth wrong ?

**Comment by JDonadio** [comment]
Can you share the address?

**Comment by thelifeisfun** [comment]
Today it worked. I dont know what was the problem. 
Thanks anyway!!
