### ISSUE TITLE
BTC sent to wrong Bittrex Address

### ISSUE THREAD

**Issue by bitcoinenthusiast** [bitpay/copay#6707]
Hi,

I was using the copay recovery tool to be my bitcoin cash, but didnt know I had to change the chain.
https://bitpay.github.io/copay-recovery/

Hence, I sent the BTC from my copay to my Bitcoin cash account on Bittrex, instead of the BTC account.

It is saying unconfirmed transaction.
Should I wait for a week to get my BTC back or contact Bittrex and pay them for recovery?

https://insight.bitpay.com/tx/1ad75060e2b061514ddc9e82886f51efab0eec9f3093359c8318f231287d0040

**Comment by JDonadio** [comment]
Your transaction is confirmed, so these funds are already in your Bittrex "wallet". You have to contact to Bittrex support and explain your situation because they have the access to that wallet seed. Definitely we need to improve the UI for the recovery tool to clarify what coin are you checking and sending to avoid this cases.

**Comment by bitcoinenthusiast** [comment]
Ive read a lot of threads on closed copay issues that if the transaction is sent to the wrong type of wallet, it comes back in a week or so, do you think thats a possibility here? 

I contacted Bittrex, waiting to hear back. Because both my BTC and Bitcoin Cash wallets are empty.

**Comment by JDonadio** [comment]
> if the transaction is sent to the **wrong type of wallet**, it comes back in a week or so

I'm afraid not. If your transaction was not confirmed and dropped from the mempool due the low fee your funds will return to your wallet.

All you have to do is contact to Bittrex and hopefully they will give your BTC back. Unfortunately we cannot help you in this case.
