### ISSUE TITLE
claiming bitcoin cash

### ISSUE THREAD

**Issue by valckeh** [bitpay/copay#6708]
@JDonadio /  Hi, about https://bitpay.github.io/copay-recovery/ Do you have to enter the recovery phrase and/or a backup password and/or the private key password? Or just fill in one of those three boxes? And what happens then? How will you see where your bitcoin cash is? I would appreciate to provide me with some more details if possible. Isn't it possible to give step-by-step explanation about how to use this recovery tool correctly? I'm not the only one with issues about this problem. Thanks.

**Comment by JDonadio** [comment]
Check this out https://github.com/bitpay/copay/issues/6702#issuecomment-327798592
