### ISSUE TITLE
I've been robbed

### ISSUE THREAD

**Issue by Guido1980** [bitpay/copay#6711]
Hello, today I opened my wallet in iOS and I found that my balance was 0 so I was immediately my app in the macbook pro and the balance also figured as 0.

I have a money send from 9/2/2017 at 3:13 pm. Shipping I did not do and no one can have done more than I do since nobody has my credentials to do it.

Could you confirm that I was stolen / hacked? thank you very much!

**Comment by dabura667** [comment]
Yes. You were hacked.

**Comment by JDonadio** [comment]
No, unfortunately we cannot confirm "who" did it. Just the user have access to the private key, if you did not, someone else have the access to your pk.

**Comment by JDonadio** [comment]
Can you provide your wallet id so we can check?
