### ISSUE TITLE
Ativei opção testnet e não consigo usar os fundos da minha carteira 

### ISSUE THREAD

**Issue by lucaspessoa194** [bitpay/copay#6719]
Quando tento enviar informa que não há carteiras disponíveis, mas eu tenho carteira e com saldo para ser utilizado.
![img_0479](https://user-images.githubusercontent.com/31787331/30236831-891de650-94f9-11e7-855f-2c53c30a40ee.PNG)
![img_0480](https://user-images.githubusercontent.com/31787331/30236832-893f74aa-94f9-11e7-97ad-344bccabd860.PNG)
![img_0481](https://user-images.githubusercontent.com/31787331/30236833-8940659a-94f9-11e7-9946-13da52320d32.PNG)

**Comment by Inkeliz** [comment]
You are trying to send Bitcoin from Testnet to the Mainnet, this is already explained in #6713 and #6700.

The mainnet (the true bitcoin network) have an address with a prefix of `0x00`. So, this always start with `1` (like `18HNoBcmt...` in your screenshot). The Testnet address have a prefix of 0x6F, as a result the address begin with `m` ou `n`. Is impossible to send coins from the Testnet to Mainnet for obvious reasons.

The Testnet is only for testing purpose, they don't have any value. You can't buy anything with it, as already explained in the app and on the related issue, mentioned above.

-------------
**Translated (I do some changes manually):**

Você está tentando enviar Bitcoins da Testnet para a Mainnet, isso já foi explicado em #6713 and #6700.

A mainnet (a verdadeira rede do Bitcoin) tem um endereço com um prefixo de `0x00`. Então, esse endereço sempre começa com `1` (como  `18HNoBcmt...` , contido na sua captura de tela). O endereço da Testnet tem um prefixo de `0x6F` , como resultado o endereço sempre começa com `m` ou `n`. É impossível enviar moedas da Testnet para a Mainnet por motivos óbvios. 

O Testnet é apenas para propositos de testes, ele não possui valor algum. Você não pode comprar nada com isso, como foi explicado no aplicativo e nas questões relacionadas, mencionado acima.
