### ISSUE TITLE
Newbie - just logged in and it says I have 0 balance

### ISSUE THREAD

**Issue by hk2017ont** [bitpay/copay#6722]
I've used Copay to send funds twice (the last time a month or so ago).  I just launched Copay and it says I have zero funds.  Have I been hacked?  It shows zero transactions.  Sorry I'm not very technical.

**Comment by dabura667** [comment]
Are you looking at the right wallet?

**Comment by hk2017ont** [comment]
Not certain - it shows 2 wallets  in the home screen, and one "Personal Wallet" and one with my custom name.  Both say 0.00 BTC.  There was a non-zero amount when I made my second purchase a month ago.
![copay_-_copay_bitcoin_wallet](https://user-images.githubusercontent.com/31812979/30246095-fb6c8bd4-95bd-11e7-94e5-8ee82b0da0f4.png)

**Comment by JDonadio** [comment]
Please provide us the wallet id. Go to settings > wallet > more opts > wallet information

**Comment by hk2017ont** [comment]
5c7d808e-e3cf-4b32-8164-dfb0de306bb1

**Comment by JDonadio** [comment]
This wallet `5c7d808e-e3cf-4b32-8164-dfb0de306bb1` is empty and never receive any transaction.

**Comment by JDonadio** [comment]
If you need more help just let us know.
