### ISSUE TITLE
How to get wallet setup on new iPhone via iCloud, can this be done?

### ISSUE THREAD

**Issue by McFuhr** [bitpay/copay#6723]
I'll be getting a new iPhone and using iCloud backup to restore everything from my old iPhone.
How do I make sure that my Copay wallet from my old iPhone is the same on the new iPhone?

**Comment by dabura667** [comment]
Write down the 12 word backup phrases for each wallet inside your Copay app.

Then install Copay on the new iPhone, and add new wallets using the "Import Wallet" option.

To avoid confusion, when you first install Copay on your new phone it creates a new wallet automatically. You might want to delete that before importing all your wallets (in case you have a wallet with the same name... it'll get confusing)
