### ISSUE TITLE
Bitcoin Cash with hardware-wallet copayers

### ISSUE THREAD

**Issue by Clamenda** [bitpay/copay#6724]
Hello

How can I recover BCH from a multi-signature Copay wallet with hardware-wallet copayers?
In my case I have a 2 of 3 multi-signature wallet with 2 Ledger copayers. Tried already the recovery-tool without success.

Thanks

**Comment by JDonadio** [comment]
Unfortunately the recovery-tool is not working for HW wallets. But we are working on it, I'll keep you posted. Also you can follow [this](https://github.com/bitpay/copay/issues/6557) for updates

**Comment by matiu** [comment]
We are working on this this week, please see https://github.com/bitpay/copay/issues/6645
