### ISSUE TITLE
newbie : wallet 

### ISSUE THREAD

**Issue by cullsin** [bitpay/copay#6726]
Hi,  

I am a newbie @ digital currency. I have a requirement to launch a new digital currency like litecoin, bitcoin, monero, dash and so on. 

Do I replicate copay wallet code and launch a new wallet for my currency ? Does this wallet support multiple currencies? If so, how do I introduce my currency.e

Please correct me if I am wrong.

Raja K

**Comment by JDonadio** [comment]
Copay/BitPay only support BTC for now. The code is opened to everyone who want to use it and modify it but unfortunately we have not any guide for that.
