### ISSUE TITLE
Cant pay to anyone with copay

### ISSUE THREAD

**Issue by ville1001** [bitpay/copay#6727]
When i try to pay to make a transaction nothing happends, it just says pending, i have treyed to pay to steam and g2a (both using bitpay). I also have tryed buying amazon giftcards trough the copay but the transaction just says pending, i have waited 2+ hours and still nothing!

**Comment by JDonadio** [comment]
Hi, provide the transaction id so we can take a look there.

**Comment by ville1001** [comment]
I dont have a transaction id cause it is just "payment proposal"

**Comment by JDonadio** [comment]
Provide your wallet id please, you can find it in settings > wallet > more opts > wallet information

**Comment by ville1001** [comment]
be97f692-3532-4149-a0b2-02884f1943e6

**Comment by JDonadio** [comment]
Your wallet is a `shared wallet`, so each transaction will create a proposal which need to be signed by the other copayer.

**Comment by JDonadio** [comment]
The only you have to do is sign it with the other copayer wallet.

**Comment by ville1001** [comment]
Thanks!
