### ISSUE TITLE
copay app android makes very silent ticking sound when app opened??

### ISSUE THREAD

**Issue by siouxzie** [bitpay/copay#6729]
any idea what this is?

**Comment by siouxzie** [comment]
is there someone from copay itself that can comment?

**Comment by JDonadio** [comment]
Hi, we don't use sounds in Copay. Probably your launcher does?

**Comment by siouxzie** [comment]
Hi, Thanks for your response. what do you mean by "Launcher"?
the sounds (very silent, almost impossible to hear...) are like a microphone or speaker being turned on. a slight continuous " grey noise" in the far background when the copay app opens. It disapears again when closing the app. i don't have any other app on my android phone that starts this noise. 
i have no idea what it can be, but obviously i find it quite worrying and suspicious.. any ideas/suggestions?
thanks in advance

**Comment by JDonadio** [comment]
Launcher is the name given to the part of the Android user interface that lets users customize the home screen (e.g. the phone's desktop), launch mobile apps, make phone calls, and perform other tasks on Android devices (devices that use the Android mobile operating system). For some distributions (cyanogen, miui, etc) are customized with sounds, animations and so.

**Comment by siouxzie** [comment]
do you have any suggestions what i should do? should i be worried?

**Comment by JDonadio** [comment]
> should i be worried?

Not at all. Just ensure to keep your backup safe and all the security settings ready for your normal use.

**Comment by siouxzie** [comment]
ok, thanks for your help.
