### ISSUE TITLE
Import private key problem

### ISSUE THREAD

**Issue by aradell** [bitpay/copay#6731]
So i had imported a wallet from copay to blockchain and now i want to transfer theme to another wallet and when i try to use send it's asking me for a private key, now that i imported the wallet is gone from my copay. From copay i recived just a password that i used when i had made the import.The same password it was used to decrypt the message and i got my xPrivKey but i have no ideea what to do with it and if i try to use it to send the money to another wallet it is saying that is not valid key. Anyone have any ideea what i can do ? Or a method to recover my bitcoins from the imported wallet.

**Comment by JDonadio** [comment]
> So i had imported a wallet from copay to blockchain

1 - How did you do that?
2 - What wallet are you using, Copay or Blockchain?

> From copay i recived just a password that i used when i had made the import

I have not clear this point. From Copay, if you export a wallet you must (mandatory) encrypt the file with a password. That encrypted backup file is **just for Copay app** you cannot use it to import your wallet in other software.

**Comment by aradell** [comment]
Thx for answering my issue.

1.This is how i made it:Settings -> Wallets -> Choose your wallet -> More Options -> Export Wallet -> File/Text -> Set up a password -> Download Then, go to 
https://bitwiseshiftleft.github.io/sjcl/demo/.

Because in copay i had some fee problems,do not let me to send founds to another wallet,that`s why i chosed to export the wallet.

2.I use both wallets:copay and blockchain.

3.The btc are in blockchain now,but with the copay wallet adress that i exported.
  
4.All I need is the priv key so i can transfer them to a trading platform

**Comment by JDonadio** [comment]
Why you did not use the 12 words instead of the export backup format?

**Comment by aradell** [comment]
![blockchain error](https://user-images.githubusercontent.com/31050777/30453137-8866b7fe-99a0-11e7-9427-fc162d3ccb07.png)

Where i can use them?

This is error that i get in blockchain and import adress is the copay wallet that i try to import

**Comment by 92161898515** [comment]
To unsubscribe or change subscriber options visit:
http://www.aweber.com/z/r/?LGzMbCxsHLRsjJwsLKwcDLRGtMzszAysjJwM

Edvaldo Silva dos santos

Em 13/09/2017 5:38 da tarde, "aradell" <notifications@github.com> escreveu:

**Comment by aradell** [comment]
Dear people so...my funds are blocked with the copay adress wallet in blockchain.How i solve this....problem!!!!IT IS POSIBBLE OR NOT?

**Comment by JDonadio** [comment]
@aradell we cannot give you support for an external software. You must contact to the support team of the third party service which are you using.
