### ISSUE TITLE
USD > Bitcoin

### ISSUE THREAD

**Issue by al9ska** [bitpay/copay#6732]
Hello guys! I am going to recieve funds through ICO and currently looking for a crypto wallet where I can store the funds that I will recieve in near future, i have couple of questions:
1) Is it possible to make an account for two people at the same time? Thing is we are partners and we want to have both of ours authorization in order to make a transaction. 
2) You work only with bitcoin? If yes, can you recommend mi simmilar platform like yours but which works with ethereum

4) Can you cash out bitcoin into bank account?

**Comment by JDonadio** [comment]
> 1. Is it possible to make an account for two people at the same time? Thing is we are partners and we want to have both of ours authorization in order to make a transaction.

Of course. All you have to do is create a shared wallet (2 of 2 maybe for your case) and all transactions will be created as a proposal signed by the creator (copayer 1) and waiting for be signed by the other copayers. Once all of **required signers** have signed the transaction will be broadcasted to the network.

> 2. You work only with bitcoin? If yes, can you recommend mi simmilar platform like yours but which works with ethereum

Yes, just for bitcoin and working on bitcoin cash integration. Unfortunately we cannot recommend any wallet sotfware.

> 3. Can you cash out bitcoin into bank account?

Copay have integrated Coinbase and Glidera to buy and sell bitcoins. Maybe that is what are you looking for.

**Comment by al9ska** [comment]
Thanks for clear answers! 
> Copay have integrated Coinbase and Glidera to buy and sell bitcoins. Maybe that is what are you looking for.

Can I use Copay but cash out with 3rd party program? Avoid Coinbase and Glidera.

I have couple more questions 😄
Is there a platform or tool to build an access to 3rd party that has never used block chain. I want to store info in blockchain and give keys for people to access the blockchain  through mobile app?

And whats best platform for blockchain programming for ETH type blockchains. 

Thank you!

**Comment by JDonadio** [comment]
> Can I use Copay but cash out with 3rd party program? Avoid Coinbase and Glidera.

Copay just send/receive bitcoins, you can use it as you wish with the 3rd party program what you want. Coinbase and Glidera are the services already integrated in the app.

> Is there a platform or tool to build an access to 3rd party that has never used block chain. I want to store info in blockchain and give keys for people to access the blockchain through mobile app?

As I said before, we cannot recommend external software.

> And whats best platform for blockchain programming for ETH type blockchains.

I have no idea
