### ISSUE TITLE
Invalid amount of Bitcoins shown on the wallet

### ISSUE THREAD

**Issue by BlackTiger1500** [bitpay/copay#6733]
I exchanged some Bitcoins to Ethereum. After the exchange, I was left with 0.0101869 BTC on my wallet which can be seen on the service I used
![image](https://user-images.githubusercontent.com/26808641/30404934-249ff88c-98b7-11e7-9430-6d5608f04ca8.png)
But Copay shows only 0.004049 BTC
![image](https://user-images.githubusercontent.com/26808641/30404962-4baf1020-98b7-11e7-9b1c-12d4b4813f2c.png)
And the amount I exchanged is also invalid on Copay
![image](https://user-images.githubusercontent.com/26808641/30404986-69e58fa6-98b7-11e7-998a-f6f31ef3c28a.png)
![image](https://user-images.githubusercontent.com/26808641/30404992-72807248-98b7-11e7-9b54-7fef2a6ed6bb.png)

**Comment by JDonadio** [comment]
@BlackTiger1500 we cannot check any external service or process. If you provide us the transaction id we can check the parameters and also your wallet status.

**Comment by BlackTiger1500** [comment]
I am not sure what my wallet status is, but this is the transaction ID 0xb2f4b34712754be3fc20fd9c00339105a592bbc1aaf09e4cd560c69b13adafa2

**Comment by BlackTiger1500** [comment]
Copay still shows i have 0.004049 BTC and on Exodus I have about 0.010149 BTC on the same wallet.

**Comment by JDonadio** [comment]
That transaction id was not made from Copay/BitPay

**Comment by JDonadio** [comment]
Go to Settings > wallet > more opts > transactions history > clear cache. Then,
Go to Settings > wallet > more opts > wallet addresses > scan addresses for funds

**Comment by BlackTiger1500** [comment]
I know that, but my main concern is the amount of bitcoins shown on my wallet differently. Copay says I have 0.004049 and Exodus says I have 0.0101869. Ill try your suggestions

**Comment by BlackTiger1500** [comment]
Thanks for the suggestions, the second one worked. Now it shows the correct amount of BTC on the wallet
