### ISSUE TITLE
Restore Multi wallet 

### ISSUE THREAD

**Issue by fredinisan7** [bitpay/copay#6737]
Question: I have a join wallet on Copay with my partner, and he lost his phone, and I guess he never backup his wallet. I still have access to the join wallet, but I can't move this money because I need him to approve it as well. Do you know how I can restore his wallet? Or how I can make sure he joins back to this wallet? 
thank you,﻿

**Comment by JDonadio** [comment]
Hi, unfortunately without a backup your wallet is not accessible. Please check this: 

https://support.bitpay.com/hc/en-us/articles/115003004363-I-lost-my-wallet-or-changed-my-phone-What-can-I-do-to-restore-my-wallet-

**Comment by fredinisan7** [comment]
HI, i have access to the Multi wallet and i can see the money in my wallet,but my partner don’t have. how can i fix it? 
do you have tech support ? i have 10k in this wallet and i need to fix this asap

**Comment by JDonadio** [comment]
The keys are stored locally in each device, not server side. If you never backed up your wallet and you lose it, damage it, etc, then the private key is lost as well. If it's your case, there is nothing we can do to help you.

**Comment by fredinisan7** [comment]
HI, i have access to the Multi Sig wallet and i can see the money in my wallet,but my partner don’t have. how can i fix it? how can he join back to the wallet with out having his backup code?
do you have tech support ? i have 10k in this wallet and i need to fix this asap
