### ISSUE TITLE
Is a newer version of this app available for Windows Mobile users?

### ISSUE THREAD

**Issue by rvwong** [bitpay/copay#6741]
I really like CoPay, I run it on my Windows 950 Mobile phone, recently I wanted to be able to change the fees when I'm doing a transaction, but noticed it isn't available on my version (3.5.0). I checked an the latest version of CoPay does in fact have that feature (3.7.3).  The Windows Store does not have that version, has anyone out there compiled the latest version of CoPay for Windows Phones?

**Comment by gabrielbazan7** [comment]
No yet. But we will try to send the update soon.
