### ISSUE TITLE
Android beta: Wallet page misses colored balance header

### ISSUE THREAD

**Issue by yamnikov-oleg** [bitpay/copay#6744]
**Steps to reproduce:** Open any wallet's page in beta app.

**Observed behavior:** Colored header showing wallet's balance is missing and I can't scroll to it

<details>
<summary>Screenshot</summary>

![Screenshot](https://i.imgur.com/qpe5j4J.png)
</details>

**Expected behavior:** Header should be present like in the old version.

<details>
<summary>Screenshot</summary>

![Screenshot](https://i.imgur.com/p6Zr4YI.png)

</details>

**App version:** 3.8.1
**Device:** LG Nexus 5 2013
**Android version:** 6.0.1

**Comment by JDonadio** [comment]
I could reproduce it, I'm checking now. Thanks for report it.
