### ISSUE TITLE
Please help!  Problem with Copay recover phrase

### ISSUE THREAD

**Issue by Tulipsaki** [bitpay/copay#6745]
I'm using the correct 12 words, but I keep getting this message: 

Could not access wallet at the server. Please check: Password [there isn't one, I've always only used the 12 word phrase] The derivation path THe wallet service URL

Has anyone had this problem, and any suggestions how to solve it? Please help!

**Comment by dabura667** [comment]
When did you create the wallet originally? What app did you use to create the original wallet?

**Comment by Tulipsaki** [comment]
@dabura667 I created the wallet on the copay android app back in November 2016.

**Comment by Tulipsaki** [comment]
Could someone please help me with this problem? is there someone I can talk to at Copay about it?

**Comment by JDonadio** [comment]
I'm pretty sure that you have used a password in your wallet recovery phrase.

**Comment by JDonadio** [comment]
I the error "wallet recovery phrase is invalid" then you are writing it wrong. Check if all your words match with the list for your language: https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md

**Comment by Tulipsaki** [comment]
Yes, they matched. I eventually got access this afternoon. I'm afraid, though, I won't use copay anymore. This was all too stressful.

**Comment by kmkrause** [comment]
I'm having the same problem can you tell me how you gained access?
