### ISSUE TITLE
i can't use my bitcoin- balance on copay

### ISSUE THREAD

**Issue by friend01** [bitpay/copay#6746]
please for help! i've got 115$ in my wallet and csn only use 5$, so whats the matter? 110$ are reserved for open transactions- but i have no open  tranactions...this 110$ are "gesperrt" not useable about 4 month! what can i do????

**Comment by JDonadio** [comment]
Please provide your wallet id so we can check your wallet status. You can find it at settings > wallet > more opts > wallet information

**Comment by boxur** [comment]
Also am having an issue
