### ISSUE TITLE
How do I change the email linked to the copay on my phone?

### ISSUE THREAD

**Issue by jzwicks** [bitpay/copay#6747]

**Comment by JDonadio** [comment]
In settings > notifications

**Comment by jzwicks** [comment]
Shows no way to change email in my phone like that.

**Comment by JDonadio** [comment]
Please, provide a screenshot of your problem so we can check

**Comment by JDonadio** [comment]
![copay_-_copay_bitcoin_wallet](https://user-images.githubusercontent.com/13851807/30598675-ca3b0200-9d30-11e7-9886-cfff09100067.png)

Switching on:

![copay_-_copay_bitcoin_wallet](https://user-images.githubusercontent.com/13851807/30598697-d8a08be4-9d30-11e7-8a38-a7f6840d12bc.png)
