### ISSUE TITLE
Support Bitcoin Cash switch

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#6749]
Fresh install > restore from backup a testnet BTC wallet > settings: Support bitcoin cash shows enabled (icon colored), select that option > Switch disabled but shows the scan button instead of message.

**Comment by Tulipsaki** [comment]
I have been asking repeatedly for help. Would you please respond to my threads?

**Comment by allthatmoney** [comment]
do not use the extractor. some one is getting our code words and emptying our copay wallets. they got mine and a friends wallet already. we got our bitcoin cash and then they came back and got our bitcoins. i repeat don't use the extractor. it's a hacker's tool
