### ISSUE TITLE
Support Request Cannot Access Wallet

### ISSUE THREAD

**Issue by Tulipsaki** [bitpay/copay#6750]
@JDonadio I followed your advice in 2016 and was able to import my wallet easily with my recovery phrase. But now i am getting this message when I try to import my wallet with my bitcoin in it. 
![img_0170](https://user-images.githubusercontent.com/24768034/30553497-61bc6d3e-9c6f-11e7-8b60-385207f0914c.JPG)

What do I do? I want my bitcoin back! I paid for them!

**Comment by Tulipsaki** [comment]
And when I use the recovery tool, I'm told the mnemonic wallet seed is not valid, but I was using it for a year! What is going on?

**Comment by JDonadio** [comment]
Please follow your original thread https://github.com/bitpay/copay/issues/6745
