### ISSUE TITLE
Transaction still not confirming 12 hours later

### ISSUE THREAD

**Issue by nathancainer79** [bitpay/copay#6753]
Hi I made a transaction stupidly on Super Economy last night its still yet to confirm 

ID # da021bf16a968599769a145b24e0e0dfa6078809a2f368b43944b05c5934bbbf

Any help would be appreciated, do I just wait it out or is it gone?

**Comment by JDonadio** [comment]
Already confirmed.

https://insight.bitpay.com/tx/da021bf16a968599769a145b24e0e0dfa6078809a2f368b43944b05c5934bbbf
