### ISSUE TITLE
Amazon gift cards [BCH]

### ISSUE THREAD

**Issue by kjaved** [bitpay/copay#6754]
How do I  purchase Amazon gift cards with my bitcoin cash BCH?

**Comment by JDonadio** [comment]
Unfortunately the buy and sell process with BCH are not supported yet.

**Comment by Edgarliendo** [comment]
Any update on this? when it will be available?

**Comment by 1mish** [comment]
it would be nice to add this in the next update :)
thanks

**Comment by pedromvu** [comment]
Any estimate on when is this going to be available?
