### ISSUE TITLE
how to lower the transfer fee

### ISSUE THREAD

**Issue by rogerwmwong** [bitpay/copay#6756]
I just tried to transfer 0.001 BTC from my exchange account to my copay wallet. However, it turns out that a charge of 0.000438 was deducted. 

Is that normal? Is it related to copay? Any means to reduce this charge?

**Comment by JDonadio** [comment]
For transactions builds out of Copay you should contact to the exchange support and ask for that.

For transactions builds in Copay, the charge (fee) is based on the transaction size, please check this out: https://github.com/bitpay/copay/issues/5164#issuecomment-265569494

Also this would help: https://github.com/bitpay/copay/wiki/COPAY---FAQ#copay-requires-high-fees-for-low-amounts-transactions
