### ISSUE TITLE
Copay fee

### ISSUE THREAD

**Issue by Flicherx** [bitpay/copay#6763]
Hello, 

I have not seen this information anywhere so i will ask here. 
When i use QR code payment the transaction fee is added to the transaction or is taken from wallet ?

Thanks for reply

**Comment by JDonadio** [comment]
During the transaction building process the fee is included in the total amount and will be deducted from your wallet.

This is a `testnet` transaction, just to clarify:

![copay_-_copay_bitcoin_wallet](https://user-images.githubusercontent.com/13851807/30604033-da34cd26-9d3f-11e7-9448-32839153dd58.png)

So a total of 1.000004 BTC will be deducted from your wallet selected in the `From` field.

**Comment by Flicherx** [comment]
Woah, this is gorgeous. Thank you.
