### ISSUE TITLE
BTC Reveral 

### ISSUE THREAD

**Issue by rayklay** [bitpay/copay#6765]
Is there anyway I can reverse the BTC I sent off, the transaction number is d2270d1745a51a97ac722d3ab9faad930686f378913b1f301ae71a2e85c384b4, if I don't receive product can I refund?

**Comment by JDonadio** [comment]
Unfortunately not. A bitcoin transaction which has already been broadcast to the network cannot be reversed. This is an important feature of the bitcoin protocol which prevents payment fraud.
