### ISSUE TITLE
Hi, hello, I have a startup problem, why can't I support 64-bit operating system

### ISSUE THREAD

**Issue by thunderstreak** [bitpay/copay#6774]
> copay@3.8.1 start G:\copay
> npm run build:www && ionic serve --nolivereload --nogulp -s --address 0.0.0.0

npm WARN invalid config loglevel="notice"

> copay@3.8.1 build:www G:\copay
> grunt

Loading "sass.js" tasks...ERROR
>> Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (57)
>> For more information on which environments are supported please see:
>> https://github.com/sass/node-sass/releases/tag/v3.13.1
Warning: Task "sass" not found. Use --force to continue.

Aborted due to warnings.

**Comment by paOol** [comment]
update to latest node/npm, maybe?

**Comment by thunderstreak** [comment]
I updated the latest node to 8.5.0, but I still couldn't run, which confused me, this is my latest version.
-----------------------------------------------------------
:\copay>node -v
v8.5.0

:\copay>npm -v
5.3.0
-------------------------------------------------------------

**Comment by thunderstreak** [comment]
I'm running successfully, so let's review the process.
You need to update node and NPM to the latest version.
2. Run the NPM run apply:copay, if the following error is found:
(2-1).'Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (57)'. Please uninstall node-sass and install the latest version.
(2-2). 'This' sh' is not an internal or external command, nor is ita running program or batch file', please reinstall bitauth.
3. Then run the NPM I
4. Finally run NPM start
These are the processes that I currently solve and run. If you have the same problem with me, maybe my experience can give you reference. Thank you
