### ISSUE TITLE
lost 4 bitcoins because i had the wrong chain selection in the recovery tool

### ISSUE THREAD

**Issue by allthatmoney** [bitpay/copay#6779]
i forgot to change the chain btc to bch in the recovery tool and i searched and found my bitcoins. but i thought it was more bch it had missed on the first search so then i sent my bitcoins to a bitcoin cash address thinking they were bitcoin cash coins. is there any way to get these coins back since i have the bitcoin hash address they were sent to? i sent them to livecoin and there is nothing showing up there so i guess they have my coins but i can't get them back. i sent in a support ticket but that usually takes 2 days to get answered. so does anyone know anything else i can do other than wait for support to get back from livecoin. and when i sent them there shouldn't they have them someplace? when you send other coins they go into pending until they get approved so you would think they could see them in the account and refuse them so they would go back. but who knows? anyone?

**Comment by allthatmoney** [comment]
some one needs to work on that recovery tool. why would it even have a bitcoin search on it anyway? and since we will be getting a lot more mistakes like that from other people couldn't someone make it at least start on bitcoin cash instead of starting on bitcoins?

**Comment by JDonadio** [comment]
@allthatmoney you need to scan the recipient wallet and move your coins back to your wallet.

**Comment by allthatmoney** [comment]
the only bad thing is the recipent wallet is on livecoin trade exchange. i can't get the 12 words for that wallet

**Comment by matiu** [comment]
What are you talking about? What you.mean by the extractor?

**Comment by matiu** [comment]
You should talk to the exchange to claim the bitcoin you sent to them by mistake.

**Comment by allthatmoney** [comment]
i sent them a support ticket yesterday but it can take up to 48 hours for
them to reply back. i guess i have another day.

**Comment by parkermor** [comment]
@allthatmoney 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com

**Comment by richardsuns** [comment]
@allthatmoney 
did you find your lost bitcoins? i think they are recoverable, I can recover them you can talk to me in telegrm. my telegram id is: walletrecover
