### ISSUE TITLE
Balance Says 0.00 Still.

### ISSUE THREAD

**Issue by TaeBalla456** [bitpay/copay#6782]
I Scanned The Bar Code And Everything Even Has Receipt No Money Has Come Yet 3 Hours Has Passed.

**Comment by solid0pc** [comment]
Has your payment arrived in your wallet? Im having the same issue today. Been about 4hrs now.

**Comment by JDonadio** [comment]
Hi guys, did you scan a QR code and send a transaction **from** Copay? Can you guys put the transaction id so we can check the status?
