### ISSUE TITLE
BTC Transaction Not Showing up in Wallet

### ISSUE THREAD

**Issue by solid0pc** [bitpay/copay#6784]
Hi. Ive not used a bitpay or copay wallet before. Ive never experienced this with Coinbase os Mycellium wallets. At around 14.00hrs I made a £100 cash deposit at the bitcoin machine in the Cex store ( a UK gaming/electronic store ). Transaction went through as usual. I scanned the qr code from the receive bitcoin tab in the wallet and took a photo of the qr code that is given at the end, as a kind of receipt I suppose. But as of yet, nothing. Is this usual this delay? How can I get the transaction to go through? I dont even see any pending transaction. I am starting to worry. But am not sure how scanning a qr code can go wrong. Id love some advice and help from those in the know. Many thanks.

**Comment by JDonadio** [comment]
@solid0pc did you buy bitcoins from a bitcoin machine? if you did, the machine gives you a ticket with the transaction id?

**Comment by solid0pc** [comment]
Hi. I did buy from a machine. It doesn't do paper print out receipts. Instead it gives a qr code receipt you take a picture of. I took the picture and have scanned the qr code. I get this . 08728fac-14da-4969-bb7a-d32db801e5b7   . Ive no idea other than a reference number what it is.

**Comment by JDonadio** [comment]
If the transactions was not built from Copay but it's just arriving to your wallet, only you have to do is wait. I assume the machine use a low fee and your transaction is hanging on the mempool. You must contact to the support team of the ATM services to get more information about your transaction, unfortunately we cannot do anything from here.
