### ISSUE TITLE
Why can't I recover BCC, while I had funds before and after august 1st?

### ISSUE THREAD

**Issue by Vilscon** [bitpay/copay#6786]
Hey guys,

I have two wallets in my Bitpay 3.6.2 macOS wallet with both 2BTC in it. Today I realised I hadn't retrieved my Bitcoin cash, so I tried both the [Copay recovery tool](https://bitpay.github.io/copay-recovery/) and the Import Bitcoin Cash wallet function from btc.com. Both show I have no funds available, i.e. I have no Bitcoin cash.

I thought that pretty much the only requirement was to have Bitcoins in your wallet pre-August, which I had. I just moved all my Bitcoins from Bitpay to Bittrex (personal reasons) and by doing so, as suggested by Bitpay's guide, have an empty wallet. Yet it still says I have no bitcoin cash.

So what am I doing wrong? Am I missing some prerequisites?

**Comment by JDonadio** [comment]
@Vilscon if you had btc balance in your wallets before 1 aug, all you have to do is use the recovery tool, selecting `bch/livenet` as main chain. Can you please check it and tell us how it goes?

**Comment by Vilscon** [comment]
Hi @JDonadio. The amount of BTC in my wallet was exactly the same, all way through July till pretty much today.

I used the tool as described in [the guide](https://blog.bitpay.com/bitcoin-cash-recovery/). I didn't change any setting, uploaded the .json files (separately, of course) I exported via the macOS 3.7.3 Bitpay application and filled in both passwords.

Then I saw a black opaque screen that went running for about 5-10 minutes each. One of them went up to 3 addresses and 20 inactive, whilst the other one stood on a single address and 20 inactive ones. Both ended with 0.0000000 Bitcoin Cash, i.e. 'insufficient funds'.

I can even show the transaction history that, if calculated, show the funds were untouched for a few months in total, during the 1st of august.

I haven't done over 20 transactions (default value in the tool) in either wallet (not even 10 I think..), so I assume that value remains correct.

I don't know what to do.

-

For the record, I'll be doing a full clean install of my macOS tonight. I will keep the .json files to restore the wallets (even though all funds is, as of today, at Bittrex (due to the clean install, as safety procedures)). I hope that won't be a problem, since I have the backup :)

**Comment by JDonadio** [comment]
@Vilscon can you please try with a major gap like ~30 or 40?

**Comment by Vilscon** [comment]
I'm currently scanning both wallets, one in Safari (the one described above, now with 40 gap), one in Chrome. The one in Chrome  found the correct amount of BTC, so that's nice.

Only thing, but perhaps that is solved in Chrome (as it isn't finished though..) is that both my Bittrex BCC address (starts with '1') and my BTC.com wallet (starts with '3') were called 'not a valid address'.

Unless you are aware of this problem, I'll wait what Chrome will say. 

Thanks already guys!

**Comment by JDonadio** [comment]
JFYI, the recovery tool was designed to scan Copay/BitPay wallets only. It can be useful for another software but probably will not find balance.

**Comment by Vilscon** [comment]
Yeah, I'm only using it for my Bitpay macOS wallet :)

**Comment by Vilscon** [comment]
Update: odd, stuck at a little bit than less the actual wallet fund.. (strangely, exactly 0.5 BCH). The other one did correctly.

Both, however, say "invalid address" when trying to move the funds..
