### ISSUE TITLE
Bitcoin Cash recovery tool keeps saying 'Enter valid address'

### ISSUE THREAD

**Issue by Vilscon** [bitpay/copay#6788]
I finally succeeded in finding my Bitcoin cash I 'received' during the split with BTC I had in my Bitpay wallets. However, [the recovery tool ](https://bitpay.github.io/copay-recovery/) keeps saying 'Please enter a valid address' when trying to send over the found Bitcoin cash.

I've tried Bittrex, Poloniex, BTC.com and the ElectronCash macOS desktop wallet. These include a starting digit with either a '1' or a '3' (as I've read this may cause a problem I've searched for wallets with either digit).

So.. What's wrong? Both desktop and cloud wallets are having problems..

**Comment by JDonadio** [comment]
Check this out: https://github.com/bitpay/copay-recovery/issues/75#issuecomment-332009446

**Comment by 92161898515** [comment]
email com problema de digitação
