### ISSUE TITLE
Steps to import a BCH wallet from Coinomi. 

### ISSUE THREAD

**Issue by robinhcooper** [bitpay/copay#6791]
I can't import my coinomi BCH wallet. It's an 18word mnemonic, and the derivation path is shown as M/44H/145H/0H  (bip32) but when I put that into the import form I get an "invalid derivation path" message.

**Comment by matiu** [comment]
That is not supported. Please create a new wallet and move your funds

**Comment by bitsofchange** [comment]
I would also like to request this functionality. Copay hasn't supported multiple coins before, but now that you're supporting BCH Copay should be able to derive and utilize both BTC and BCH restored from a BIP39 seed.

**Comment by matiu** [comment]
> I would also like to request this functionality. Copay hasn't supported multiple coins before, but now that you're supporting BCH Copay should be able to derive and utilize both BTC and BCH restored from a BIP39 seed.

Copay does that. We support BIP39 seeds, using BIP44 and BIP45 derivation. We don't support custom, non-standard, derivation path.

**Comment by matiu** [comment]
Sorry, I misread the OP. Please see https://github.com/bitpay/copay/issues/6803 to follow this issue.
