### ISSUE TITLE
Invalid bitcoin cash address

### ISSUE THREAD

**Issue by unixfox** [bitpay/copay#6793]
When I try to send my bch using Electron cash to my copay bitcoin cash wallet I get "invalid lines" and blockdozer doesn't recognize my bch address:
![image-20170927-01](https://user-images.githubusercontent.com/4016501/30887180-851650b8-a31a-11e7-8fb5-a8fa069de900.png)
![image-20170927-02](https://user-images.githubusercontent.com/4016501/30887196-9b45ad0c-a31a-11e7-8c4d-9fc18959526f.png)

A screenshot from the receive tab on copay:
![image-20170927-03](https://user-images.githubusercontent.com/4016501/30887219-b59917ac-a31a-11e7-9422-ec1a0948ee8a.png)
Bitcoin cash address: `CY3YR6scqSdrvtYmQHr9mG8mVHM4mQzvqM`

**Comment by unixfox** [comment]
Ok I need to translate my address using this tool: https://bitpay.github.io/address-translator/
Not very user friendly.

**Comment by spotworks** [comment]
But it doesn't allow you to copy and paste the new address.  Totally useless!!!!

**Comment by unixfox** [comment]
It's works on Chrome but not on Firefox @spotworks.

**Comment by spotworks** [comment]
Awesome thanks!
