### ISSUE TITLE
Support BCH testnet

### ISSUE THREAD

**Issue by neldredge** [bitpay/copay#6794]
It is great that Bitcoin Cash is now supported.  It would be nice if the Bitcoin Cash testnet were supported as well, so that people could experiment with BCH transactions or practice using the app.

**Comment by myself659** [comment]
Bitcoin Cash testnet is available now ?

**Comment by ikram81** [comment]
Bitcoin Cash testnet up?

**Comment by neldredge** [comment]
Yes, there is a Bitcoin Cash testnet.  It's not terribly active but it works fine.  You can see current activity at https://www.blocktrail.com/tBCC

**Comment by gabrielbazan7** [comment]
We already support testnet in the last version 4 of the app.

**Comment by knoxcard** [comment]
I need BCH testnet coins

bchtest:qr4cq9hlkum6mweuecs8q7wrm3f0sj3kwcmatezufu

**Comment by BGalliotti** [comment]
@knoxcard  Please check this out: 

http://www.mundosatoshis.com/bitcoin-cash-bch-faucets/

Kind regards.

**Comment by knoxcard** [comment]
@BGalliotti - this isn't what I want, I need BCH testnet coins not real BCH.

**Comment by neldredge** [comment]
This bug report is not an appropriate place to discuss this. Please take it somewhere else.
