### ISSUE TITLE
Cannot send BCH

### ISSUE THREAD

**Issue by jackajm** [bitpay/copay#6800]
I am trying to send my BCH, but can't due to this error. I have attached a picture of the problem I'm getting. 
<img width="431" alt="screen shot 2017-09-27 at 11 04 38" src="https://user-images.githubusercontent.com/32336984/30924200-b2944640-a373-11e7-9f78-b25abf365ad0.png">

**Comment by alexatsatoshi** [comment]
Me too, with a multisig wallet 2-3

**Comment by meinharrd** [comment]
+1

**Comment by cmgustavo** [comment]
Are you trying with a bitcoin cash address that start with 1xx...x? If it 's your case, try to convert it to the new address format for bitcoin cash with this online tool: https://bitpay.github.io/address-translator/

**Comment by jackajm** [comment]
Gustavo I am trying to convert my bch to btc through Changelly, so if you know why this is please let me know. Here is another photo. Thanks!
<img width="1293" alt="screen shot 2017-09-27 at 11 44 31" src="https://user-images.githubusercontent.com/32336984/30925991-53f8602a-a379-11e7-8a66-e658c8e2c3f0.png">

**Comment by cmgustavo** [comment]
I 'm just talking about to change address format. I mean, your address "12Q...." to the new format valid for copay that start with `C...` for 1-1 wallets or `H...` for multisig.

For example (my own experience), I sent BCH from Copay to mi wallet Bitcoin-ABC that doesn't support the new address format. So, I had to convert an address from Bitcoin-ABC to the new format using our online tool and paste the new address in Copay. After some seconds, my funds were in my wallet Bicoin-ABC.

**Comment by jackajm** [comment]
It worked!! Thank you very much!

**Comment by alexatsatoshi** [comment]
Error message instead of frozen screen would be nice, though.
