### ISSUE TITLE
Can’t create BCH wallet with m/44'/145'/0'

### ISSUE THREAD

**Issue by avibrazil** [bitpay/copay#6803]
145 is the coin type number for BCH but Copay won’t allow me to create a wallet with m/44'/145'/0' failing with invalid derivation path message.

BCH wallets imported from BTC wallets should use m/44'/0'/0' derivation path. But new BCH wallets should use by default m/44'/145'/0'

See coin type spec on https://github.com/satoshilabs/slips/blob/master/slip-0044.md

**Comment by matiu** [comment]
Hello, thanks for the information. Do you know that wallet software are already using the 145' path?

**Comment by dabura667** [comment]
Coinomi uses 145 coin path

**Comment by bitsofchange** [comment]
Trezor apparently uses it, since it was SatoshiLabs which originally proposed 145 as the registered coin type. See below:

https://github.com/satoshilabs/slips/pull/91/commits/43bea284fd0c90571a43d81a8ad2a353cc73b6d5
https://github.com/satoshilabs/slips/blob/master/slip-0044.md

**Comment by avibrazil** [comment]
This one is always my reference: https://iancoleman.github.io/bip39/ (or download the source code to run it locally)

**Comment by avibrazil** [comment]
Newest Copay version 3.8.6 still creates new BCH wallets with wrong m/44'/0'/0' path.

And manually setting path to m/44'/145'/0' still fails with invalid derivation path.

I’m looking forward to see this fixed so I can use same phrase for all my coins in a standard way.

Thank you in advance

**Comment by avibrazil** [comment]
Version 3.9.1 still doesn’t support m/44'/145'/0'

Is there any plan to support this ?

**Comment by atteeela** [comment]
This is a serious issue because it effectively means that you cannot import other wallets via Seed Recovery Phrase into Copay. 

Please, can someone allow us to enter derivation path of m/44'/145'/0' and make it the default?

Thank you,

**Comment by monsterbitar** [comment]
I'll just add that this is an issue for me too. Another wallet had a bug in it that prevented me from accessing my funds, and trying to import the seed here fails with invalid derivation path.

**Comment by matiu** [comment]
Path 145' is not supported by Bitpay Wallet, while it is an easy fix, it will break old wallet's compatibility.  We would need to support both, and scan both after wallet import, we plan to do it someday, but it is not in our immediate priority task list

**Comment by matiu** [comment]
fixed.
