### ISSUE TITLE
Missing option to use TREZOR for Shared Wallet

### ISSUE THREAD

**Issue by myq** [bitpay/copay#6804]
I am using the Chrome extension from the Chrome Web Store.

Previously (about a month ago), I could select the option to use a TREZOR hardware wallet for the Wallet Key on the "Join Shared Wallet" screen, but now the only options are:

* Random
* Specify Recovery Passhrase...

Note that my TREZOR is plugged in and the TREZOR Chrome extension has no issue communicating with my TREZOR device.

Is it possible that this feature was broken in a recent update, or am I doing something else wrong?

**Comment by myq** [comment]
I now see that my issue seems to be a duplicate of this issue reported yesterday: https://github.com/bitpay/copay/issues/6796

Sorry about the duplicate. Can you please advise how soon this will be fixed and the new build deployed to the Chrome web store?

**Comment by JDonadio** [comment]
Sure, I personally will update #6796 once the fix have deployed.
