### ISSUE TITLE
Bitpay exe for desktop  treated as a virus by Norton 

### ISSUE THREAD

**Issue by bitterly** [bitpay/copay#6806]
Filename: bitpay (1).exe
Threat name: WS.Reputation.1Full Path: e:\working file 2015\software\scoped_dir7088_2671\bitpay (1).exe

____________________________

____________________________

On computers as of 
28/09/2017 at 21:27:34

Last Used 
28/09/2017 at 21:31:43

Startup Item 
No

Launched 
No

Threat type: Insight Network Threat. There are many indications that this file is untrustworthy and therefore not safe

____________________________

bitpay (1).exe Threat name: WS.Reputation.1
Locate

Very Few Users
Fewer than 5 users in the Norton Community have used this file.

Very New
This file was released less than 1 week  ago.

Medium
This file risk is medium.

____________________________

Source: External Media

Source File:
bitpay (1).exe

____________________________

File Thumbprint - SHA:
6ea6e29b64d2d85520bbc5800070dec279f7d939968118f637c43c50f94b50e5
File Thumbprint - MD5:
a6e79169f0985232ddde6f395dbdfdd5

**Comment by JDonadio** [comment]
Check https://github.com/bitpay/copay/issues/6471#issuecomment-333117704
