### ISSUE TITLE
v3.8.2 bugs

### ISSUE THREAD

**Issue by paOol** [bitpay/copay#6808]
![2017-09-28_19h57_25](https://user-images.githubusercontent.com/5941389/30999028-432fe2d6-a487-11e7-9101-ab99e4a2b268.png)

I generated an address, and created a QRcode of it using the old style `1ajlkdfjalksjl`.
I scan the QR code and CoPay notifies me that it was converted to the `Cxjadklfjal` format.

When I get to the `Confirm` Page, the fee calculation seems to be set to BTC, not BCC.
I would always get $0.00-$0.01 fees in Bitcoin Cash, but when using the bad QR code, the fee is $0.04 or higher. It's also disabled to click into so I cannot change it.

If I generate the `CXjalsdfjl` Qrcode , there are no issues and everything works as expected.

**Comment by gabrielbazan7** [comment]
It's working for me. We will investigate a little more.
