### ISSUE TITLE
BCH doesn't work

### ISSUE THREAD

**Issue by caveman1973** [bitpay/copay#6811]
When you open Copay and try to send BCH funds, it simply doesn't work. 

To replicate: 
- Click on SEND tab.
- Scan address.
- Click on BTC to change to BCH and insert any value (I inserted a number below what I had). 
- Click the green (SEND) button. 

Then it goes to a CONFIRMATION screen that's blank.

**Comment by gabrielbazan7** [comment]
Hi. Take a look at this article: https://support.bitpay.com/hc/en-us/articles/115004671663 . 

If you trying with a bitcoin cash address that start with 1xx...x, try to convert it to the new address format for bitcoin cash (c.. for 1-1 wallets ) with this online tool: https://bitpay.github.io/address-translator/
