### ISSUE TITLE
BCH not receiving

### ISSUE THREAD

**Issue by jpwinther** [bitpay/copay#6812]
2 days ago I transferred a small amount to the BCH wallet. It has yet to arrive.
Transaction code is: d97589ab36c20c64d07cccbbbf7f32832fc2a8aa341ad56f82d30d9fa81d21a1

JPW

**Comment by JDonadio** [comment]
https://bch-insight.bitpay.com/tx/d97589ab36c20c64d07cccbbbf7f32832fc2a8aa341ad56f82d30d9fa81d21a1

Have already ~500 confirmations

**Comment by jpwinther** [comment]
OK, so the actual transaction is confirmed, that's good. Thank you. But then the problem must rest with the Copay app, because it doesn't appear in the BCH wallet there. I've checked the address at both ends and they are identical. 

JP
