### ISSUE TITLE
Duplicate for BCH generates an incorrect wallet name

### ISSUE THREAD

**Issue by cmgustavo** [bitpay/copay#6815]
The wallet can be imported but the name has not been decrypted.

Not sure but I think that it could affect that wallet balance is always zero.

**Comment by Gamboster** [comment]
A screen of this bug:
![screenshot_20170928-100844](https://user-images.githubusercontent.com/10983458/31021030-ff369884-a50a-11e7-9e54-350870f428e5.png)

The BCH wallet is an attempt to duplicate "Gabriel Wallet"

**Comment by cmgustavo** [comment]
Due to use this wallet during development version. It has been solved deleting wallet from BWS.
