### ISSUE TITLE
deposit BCC TO MY BTC copay wallet by mistake

### ISSUE THREAD

**Issue by phil72565** [bitpay/copay#6816]
That pretty much sums it up?
I made a deposit using BCC address to a BTC address.
Is there any way to recover this coin?
I am using copay wallet that has both BCC and BTC

**Comment by JDonadio** [comment]
Yes, please use the https://bitpay.github.io/copay-recovery/ and scan your BTC wallet using the `bch/livenet` chain to found your BCH.
