### ISSUE TITLE
I deleted one of share wallet without back up

### ISSUE THREAD

**Issue by masann** [bitpay/copay#6818]
Hello
I need your help.

I deleted one of share wallet account without back up.
It means my friend can access it but I can't.
And there are some BTC in there.

Do you know any idea to send BTC from it??
Coz it's required a password to send it.

I shared it with 2 people including me.

I'm looking forward to a solution.
Regards

**Comment by gabrielbazan7** [comment]
Hi ! how many signatures you need to send ?  If it is a 3-3 wallet, unfortunately there is no way to broadcast the transaction without your wallet.

**Comment by masann** [comment]
It's 2-2 wallet

**Comment by dabura667** [comment]
There is no solution. With a 2-2 wallet, BOTH PEOPLE need to have a backup.

If one of the 2 people loses their backup and their device breaks or they delete their wallet, then the bitcoins are frozen forever, there is no way to recover them except to find the 2nd person's backup.

Good luck finding your backup.
