### ISSUE TITLE
BCH transaction stuck in receiving, although cleared

### ISSUE THREAD

**Issue by wansei** [bitpay/copay#6820]
I've retrieved my Mycelium wallet (no BTC in Mycelium wallet, only BCH) via your online recovery tool, which worked fine. Transaction went through, appeared in my bitpay wallet, status - receiving. Next day I checked again - still receiving (with receiving symbol next to the wallet name). Somehow I managed to get to a page (now, later on I can't seem to find this info again) showing 1. Funds (showing correct amount) 2. Spendable funds (showing zero). After that the receiving symbol disappeared and the balance showed up correctly in the home tab. But transaction itself was in receiving status still. Only after I cleared cache through settings, both showed correctly. Please let me know if this helps you, seems buggy to me
PS. app was on ios updated just before the transaction on 27/09/2017

**Comment by JDonadio** [comment]
@wansei that's caused by the "Use unconfirmed funds" options in settings/advanced. If it's off, you'll see that Button in your main balance section which will lead you to a detailed view of your balance. When the transaction get confirmed, that option will disappear because all your funds will be spendable.

**Comment by wansei** [comment]
@JDonadio the transaction showed as unconfirmed (or i think the exact status was "receiving") about 18hrs after the transaction (transaction has been confirmed long before). That got me initially little worried, but after I cleared cache via settings, all was fine. It seemed buggy, just saying
