### ISSUE TITLE
Added a new wallet with a specific seed - no BTC imported

### ISSUE THREAD

**Issue by dafterapps** [bitpay/copay#6822]
Hello,

I have just followed the steps to import a wallet from another application (Breadwallet) but without success. 

I tapped New wallet -> Advanced -> Specific phrase and I put the 12 words generated in Breadwallet. The wallet was added but it is showing 0 BTC while there should be some (I can still see them in Breadwallet).

What may I be doing wrong?

**Comment by JDonadio** [comment]
We cannot give you support for external software. You must contact with Breadwallet support team and ask they for your problem.
