### ISSUE TITLE
BCH TRANSACTION STUCK IN RECEIVING id b293928b13695fd3044514e857d2b62c9e6c773829cd6f12d242e300f421eeda

### ISSUE THREAD

**Issue by phil72565** [bitpay/copay#6824]
sent some bitcoin cash from my bittrex wallet (they call BCC) to my copay wallet they call (BCH) and has been stuck in receiving mode all day long.
I see it on the blockchain with 1 confirmation.
Why is it taking so long?

**Comment by phil72565** [comment]
Summary confirmed



Total Received 0.78829137 BCH 
Total Sent 0.59959505 BCH 
Final Balance 0.18869632 BCH 
No. Transactions 53

**Comment by paOol** [comment]
this is not a copay issue.
Miners are triggering a difficulty adjustment. so a median block time of 6~ hours (or was it 12) of blocks not being mined is required to get the difficulty down again.

Last time it took place pretty quick, so i'd say another day and things will be back to confirming every 10 min~ or so.

**Comment by phil72565** [comment]
It went thru.  Thank you so much for your input



Sent on my Virgin Mobile Samsung Galaxy S® 5


-------- Original message --------
