### ISSUE TITLE
Coins not confirming

### ISSUE THREAD

**Issue by boxur** [bitpay/copay#6827]
This has been happening a lot latly coins just glitching say they were revived a few seconds ago when I kno it was sent from coin source over 30 min ago why does this take so long 5931b2e925cec1307636c125eba96136f83c372d6e7b8189091d426c26ac6de9

**Comment by dabura667** [comment]
This has nothing to do with Copay.

Confirmation time is 100% the responsibility of the SENDING WALLET. The receiving wallet can do nothing.

Contact "coin source" at their support. Copay can not help you.

**Comment by boxur** [comment]
So how does copay say I have 7$ available to spend if it doesn't recognize it. Also balence appears but not spendable

**Comment by dabura667** [comment]
> copay say I have 7$ available to spend if it doesn't recognize it.

I have no idea what you're talking about. Paste a screenshot or something.

And contact "Coin Source" support please. I am only asking for a screenshot because I have no clue what you are saying. Copay can not do anything to help you in this situation. That will not change.

**Comment by JDonadio** [comment]
Transaction confirmed. @boxur keep in mind what @dabura667 says, he is right.
