### ISSUE TITLE
refound Amazon gift card

### ISSUE THREAD

**Issue by yaderperez1983** [bitpay/copay#6830]
Hi 2 days a go I buy a gift card of 500 USD because I wanna buy something in Amazon.it but my surprise was this gift card is just only to use in Amazon.com (USA). Bat I living in Italy and I want to use in Italy not in USA. I have the possibility to refunds my BITCOINS?thanks

**Comment by JDonadio** [comment]
Hi @yaderperez1983, unfortunately we cannot make refunds, the GC are only available for Amazon.com. You must contact to the Amazon.com support team (USA) and ask they for a transfer or refund into your Amazon.it account. Hope that helps.
