### ISSUE TITLE
avast detects malware

### ISSUE THREAD

**Issue by bymaximus** [bitpay/copay#6831]
I'm getting avast block due malware detection at coplay.exe
<br/><br/><br/><br/>

![avast detection 2017-09-30 21 07 49](https://user-images.githubusercontent.com/595991/31050538-76346bbe-a623-11e7-8263-cb3680241049.png)

**Comment by dabura667** [comment]
Before running any file, verify the PGP signatures. If the PGP signatures are valid:

1. How much do you trust that you have the correct PGP key for Bitpay?
2. How much do you trust Bitpay?

If your answer to 1 or 2 is less than what is acceptable for you, don't run the program.

**Comment by dabura667** [comment]
FYI, here's what I got:

```
Copay PGP key Fingerprint: 9D17 E656 BB3B 6163 AE9D  7172 5CD6 00A6 1112 CFA1
Copay.exe.sig SHA256: 2de9a2e4eadb467671d63b83b864d81cd0785e5c3bc738e5ec1178711b33dd31
Copay.exe SHA256: 039f93900ab1422e6e30824507495a17b82d2dfef7797ae9f19df45f40d86cf9
Status: Valid signature
```

So the question is: How much do you trust `9D17 E656 BB3B 6163 AE9D  7172 5CD6 00A6 1112 CFA1` is actually owned by Bitpay, and that they manage the key securely so no one can steal it?

Also, it's not coplay.exe but Copay.exe

**Comment by dabura667** [comment]
Also remember, Github admins could replace the data I posted, so you should really check the signatures yourself.

**Comment by bymaximus** [comment]
Thanks for the reply, never got any virus block related to copay.exe before, I will check sign
