### ISSUE TITLE
Problem with sending Bitcoin

### ISSUE THREAD

**Issue by Azverin** [bitpay/copay#6832]
I am trying to send max amount from Copay, but my transaction is still waiting for approve and didn`t sent above 24 hours. I am trying to resend and problem still actually
![problem](https://user-images.githubusercontent.com/32433641/31055031-062dda72-a6c7-11e7-8a37-11256bb92750.jpg)

**Comment by junderw** [comment]
You meed to approve the payment with your other copayers.
