### ISSUE TITLE
Copay app not receiving

### ISSUE THREAD

**Issue by jpwinther** [bitpay/copay#6834]
Transaction d97589ab36c20c64d07cccbbbf7f32832fc2a8aa341ad56f82d30d9fa81d21a1 is confirmed, but nothing is received in the app.

**Comment by jerffesoncunha** [comment]
Hello, I made a transaction to the address 12yMCrX1bGqwuNYJN5eDwChgPhFMuEgBWd and was not received in the wallet, but in the blockchain is already confirmed.

**Comment by JDonadio** [comment]
@jpwinther your transaction is not found. It was dropped from the mempool due a low fee.

@jerffesoncunha please follow your open issue: https://github.com/bitpay/copay/issues/6836
