### ISSUE TITLE
Copay did not receive

### ISSUE THREAD

**Issue by jerffesoncunha** [bitpay/copay#6836]
Hello, I made a transaction to the address 12yMCrX1bGqwuNYJN5eDwChgPhFMuEgBWd and was not received in the wallet, but in the block chain is already confirmed.

**Comment by JDonadio** [comment]
Can you please provide the transaction id?

**Comment by JDonadio** [comment]
This is the transaction: https://insight.bitpay.com/tx/9c3f05bba4fe7c3804412e423931ce363c587e6fe978111b6af6d46ae957c6f9

It's already confirmed. Please go to settings > wallet > more opts > wallet addresses > scan addresses for funds.

If your wallet was imported in Copay/BitPay from an external seed, the synchronization will not work automatically, you'll need to do the above steps to reflect the correct balance in your wallet.

**Comment by jerffesoncunha** [comment]
![image](https://user-images.githubusercontent.com/32454652/31082016-10d7dc6e-a764-11e7-823f-372e3eff1e0c.png)
look for image, not loading

**Comment by JDonadio** [comment]
There is an UI problem (we are working to fix it). Could you check your mobile internet connection? seems like your wallet is not connected with `bws`.

**Comment by jerffesoncunha** [comment]
Many thanks, I modified the proxy and solved the problem.
