### ISSUE TITLE
Can’t send bitcoin cash

### ISSUE THREAD

**Issue by suleimanaibek** [bitpay/copay#6844]
Why I can’t send bitcoin cash, when I write wallet(correct wallet) app steps to empty page?

**Comment by JDonadio** [comment]
Are you trying to send to a BCH address starting with 1... ? If so, please check this out: Sending BCH shows error "Please enter a valid address"

**Comment by suleimanaibek** [comment]
Yes! What canI Do?

**Comment by JDonadio** [comment]
Sorry, this is the link: https://github.com/bitpay/copay/wiki/COPAY---FAQ#sending-bch-shows-error-please-enter-a-valid-address

**Comment by ivojoel** [comment]
I have the same problem, when I try to send BCH, it does not allow me to add the address (starts with 1)

**Comment by Berndinox** [comment]
So if i would like to send BCH from another Wallet who do not use the new Naming Style, i have to convert my Receiving Address (CX......) on that site above to an 1... BTC Address?
