### ISSUE TITLE
Can not Transfer BCH from CEX.io to Copay BCH

### ISSUE THREAD

**Issue by Berndinox** [bitpay/copay#6846]
Cex.io says "Invalid address".
 Checking BCH blockchain, did not found that Adresse aswell.
Ähm, Whats wrong here?!

**Comment by JDonadio** [comment]
What is Cex.io and what are you trying to do?

From Copay, BitPay, or Recovery Tool: If you have the `invalid address` error please follow: https://github.com/bitpay/copay/wiki/COPAY---FAQ#sending-bch-shows-error-please-enter-a-valid-address

**Comment by Berndinox** [comment]
hy @JDonadio and thanks for the response.

It's just an trading plattform for Alt-Coins. But, cause i did not find the Address in official on severel BCH Blockchain Sites as well, it seems the "Bug" has to do with Copay.

What i trie to archive is:
Send BCH from another BCH Trading/Wallet Plattform to my Copay BCH Wallet

Ok, so it seems like Copay has introduced a new Address "Pointer".
Well, but:
- did anyone else take care of this
- from within the App there is no information
- did someone else, outside of Copay discuss how the new Address should look like

If you use your own, new Address-Style you definitly have to inform your user directly in the App and not on an sub, sub FAQ Site nobody is findinge.

Sorry, but for that i'll swtich my Wallet.

BR

**Comment by JDonadio** [comment]
We are working on that, actually the changes were already merged in order to inform about these changes: https://github.com/bitpay/copay/pull/6790. Sorry about that.

**Comment by Berndinox** [comment]
Thanks for the Update!

**Comment by Berndinox** [comment]
@JDonadio is it save to receive BCH on that new Addresses yet?

**Comment by JDonadio** [comment]
Yes, just ensure to verify the original BCH address before translate it, and if you want you can translate it again to check if it's the same as original.

**Comment by Berndinox** [comment]
Thanks!
