### ISSUE TITLE
Windows Client GUI Issue

### ISSUE THREAD

**Issue by Berndinox** [bitpay/copay#6847]
Version:  3.8.2
OS: Windows 10

Whenn starting the App, swtiching to Options and open any random Menu, going back to the Wallets and open one Wallet, back Button appears:
![image](https://user-images.githubusercontent.com/1122698/31178702-27c453aa-a91a-11e7-8c76-38c589e455ee.png)

When open the App and directly swtich into a Wallet, the back Button is missed:
![image](https://user-images.githubusercontent.com/1122698/31178774-569f1ad4-a91a-11e7-90f0-9d6115c130b3.png)

**Comment by JDonadio** [comment]
We are working in a complete refactor of the app. Hopefully we'll release the new version soon which fix a lot of UI bugs, performance, etc. Please be patient, we'll keep you posted.

Thanks for your reports!

**Comment by FlorisRX** [comment]
Yup, this is extremely annoying, as I have to restart the app over and over
