### ISSUE TITLE
Wallet recovery from json file & wallet words does not recover my mining address

### ISSUE THREAD

**Issue by Miner01-PC** [bitpay/copay#6850]
Hard drive died, wallet recovery from json file & wallet words does not recover my wallet address I had used for mining.

Is this what you call successful backup & recovery?

Is this normal?

Please help!

**Comment by JDonadio** [comment]
You can check all your addresses in settings > wallet > more opts > wallet addresses

**Comment by Miner01-PC** [comment]
Thanks. Probably you should show old addresses so noobs won't freak out. Thank you for your help.

**Comment by parkermor** [comment]
@Miner01-PC 
I can recover your wallet from any file type. I an expert in this regard. if you want need help send me email : anywalletrecovery@gmail.com
