### ISSUE TITLE
Please support private key WIF import on new wallets

### ISSUE THREAD

**Issue by bitsofchange** [bitpay/copay#6852]
I work in Bitcoin customer support with inexperienced users who often need to import private keys from paper wallets. While Copay does a fine job with this for QR codes, there still remains the edge case where a user wants to sweep the funds off of a paper wallet into a brand new Copay installation on desktop without a camera.

Old Copay used to do this adequately (just type the private key string into the address field of the Send UI), but more recent Copay/Bitpay versions instead hide the normal Send UI when the wallet is empty and replace it with one instructing the user to either purchase bitcoin or display their receive address.

**Easy fix:**

Simply add a way (even a hidden command) to the UI that would bypass the new screen and present the user with the standard Send screen and address field on a wallet that is empty. This way even the most inexperienced users will be able to be walked through on how to sweep private key strings on Copay desktop.

**Comment by bitsofchange** [comment]
**Could I please have an update or comment on this?** It is still an issue for paper wallet customers who have damaged their QR codes and require manual input of the private key string.

I just need a way to bypass the add funds reminder screen when pressing "Send" so that I can access the normal Send UI and type in or paste the private key.

**Comment by JDonadio** [comment]
This is not an issue in Copay. We provide the ability to sweep paper wallets, not to import one.
