### ISSUE TITLE
Unable to spend BCH

### ISSUE THREAD

**Issue by nagarajhubli** [bitpay/copay#6854]
I am unable to spend BCH using Copay wallet, please find attached the screen below that I see when I try to confirm the transaction, basically, no information is getting populated on the Confirm screen
![screenshot_20171005-163321](https://user-images.githubusercontent.com/259447/31224468-a7b23808-a9eb-11e7-8d77-7206c90ad26c.png)

Where as, spending of BTC is working fine

**Comment by JDonadio** [comment]
Please check this out: https://github.com/bitpay/copay/wiki/COPAY---FAQ#sending-bch-shows-error-please-enter-a-valid-address

**Comment by JDonadio** [comment]
We are releasing a new version which handle that situation and have more information.

**Comment by bchuser** [comment]
Yes I've got this issue as well.  Any idea when we can expect a the new version with the fix ?

**Comment by JDonadio** [comment]
In a few days with sure.

**Comment by stewbertqp** [comment]
I have a time sensitive payment required with BCH. I am experiencing the same error as shown above. Do you have a workaround or do you recommend another product that will be capable of executing this transaction?  Thanks!

**Comment by stewbertqp** [comment]
P.S. When I scan the QR it also populates with "bcc:[account number]Amount[requested transaction amount]" rather than just the account number.

**Comment by Edgarliendo** [comment]
When will I be able to purchase Amazon gift cards with my bitcoin cash BCH?

**Comment by rickf44** [comment]
still seeing this same error, please advise.  we understand you want to promote your C-addresses but seriously you must continue to support the rest of the ecosystem.  surely you understand this.

**Comment by bchhh** [comment]
yes, it's been more than the few days indicated above.  Any idea when this will be fixed ?

**Comment by nagarajhubli** [comment]
I was able to claim my Bitcoin Cash (BCH/BCC) using http://www.exodus.io/ wallet, and successfully converted it to Bitcoin (BTC)

http://support.exodus.io/article/64-how-do-i-claim-bitcoin-cash

**Comment by miltonwg** [comment]
nagarajhubli, have you recovered your Copay Backup in a new Exodus wallet to do so?

**Comment by miltonwg** [comment]
@nagarajhubli have you recovered your Copay Backup in a new Exodus wallet to do so?

**Comment by nagarajhubli** [comment]
@miltonwg I used the 12 word mnemonic passphrase from Copay wallet, and restored the wallet in Exodus

**Comment by valmassoi** [comment]
Any update on this @JDonadio ?

**Comment by JDonadio** [comment]
Sorry about the delay, we're working on many things. The new release should be available soon handling this issue properly.

**Comment by JDonadio** [comment]
You can also add the prefix `bitcoincash:` and next the "old" address format like:

> bitcoincash:1xD....
