### ISSUE TITLE
BTC denominated deposit value showing in $X.XX format

### ISSUE THREAD

**Issue by picnicbear** [bitpay/copay#6861]
User made a BTC debit card top-up, and the card activity view on BitPay wallet is showing a dollar amount when confirming

 i.e. 0.230011 BTC showing as "$0.23"

**Comment by BGalliotti** [comment]
Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will happy to help you.
Thanks.
