### ISSUE TITLE
Claim BCH: Copay + Trezor Multisig

### ISSUE THREAD

**Issue by gittub29** [bitpay/copay#6864]
Requesting instructions for claiming BCH for a shared Copay wallet that is signed using multiple trezor devices. Thanks in advance!

**Comment by JDonadio** [comment]
Please follow https://github.com/bitpay/copay/issues/6789

**Comment by corebindallas** [comment]
Hi Please help resolve the issue with not being able to sweep the BIP48 derivation path multi sig trezor wallet or give us some guidance
