### ISSUE TITLE
I sent BCH to my BTC copay wallet address. 

### ISSUE THREAD

**Issue by wealthcollective** [bitpay/copay#6865]
How can I recover the funds?

**Comment by dabura667** [comment]
Click “recover BCH”

**Comment by JDonadio** [comment]
For Copay/BitPay wallets:

* Ensure to get the correct backup for your BTC wallet, which has received the BCH coins.
* Using the recovery tool (https://bitpay.github.io/copay-recovery/)
    * Fill each field with your current wallet settings and ensure to select **bch/livenet** as chain.
    * Fill the backup field and/or passwords if exist.
    * Accept the terms and begin the scan wallet process. Depending of the wallet, this process could take several minutes.
* Once the scan is complete you will see your BCH available balance with the option to send these funds to another BCH wallet.

**Comment by wealthcollective** [comment]
It didnt find my BCH. The recovery tool gave me this message: Available balance: 0.00000000 BTC. Insufficents funds.

This is the link to the block explorer info: 
http://blockdozer.com/insight/tx/a777ef25d535a2ffefa2a5ae9582bfe1dc889de11814783d3b0f1c93cf50a5f5

**Comment by dabura667** [comment]
All the bitcoins in that transaction have been sent to another place.

Are you sure you weren’t hacked?

**Comment by JDonadio** [comment]
> It didnt find my BCH. The recovery tool gave me this message: Available balance: 0.00000000 BTC. Insufficents funds.

If your balance is shown in BTC, please check your network, it should be `bch/livenet`
