### ISSUE TITLE
I sent btc to my wallet and it never arrives.

### ISSUE THREAD

**Issue by AbeLaw** [bitpay/copay#6866]
I copied the btc address and sent btc to the copay wallet.  I have been doing this for several months and it never arrives.  They have all been confirmed.  Where is the btc?

**Comment by JDonadio** [comment]
Can you provide us the wallet id? you can find it in settings > wallet > more opts > wallet information

**Comment by AbeLaw** [comment]
My wallet id is:     af1edf28-253c-4e49-8eec-bf1beeaa949c

**Comment by JDonadio** [comment]
Your wallet have only one transaction received. Do you have all the transaction ids sent to your wallet?

**Comment by AbeLaw** [comment]
Here is one of the transactions: 
Transaction 78e08c134086fae3748638fc86cd0a152c02b773c3913714b84d45bbd8b3e7fc

**Comment by JDonadio** [comment]
Unfortunately that transaction will not arrive to your wallet: `af1edf28-253c-4e49-8eec-bf1beeaa949c`

**Comment by AbeLaw** [comment]
Where are they going?  Can I recover them?

 

    On ‎Sunday‎, ‎October‎ ‎08‎, ‎2017‎ ‎12‎:‎47‎:‎28‎ ‎AM, Javier Donadío <notifications@github.com> wrote:  
 
 
Closed #6866.

**Comment by JDonadio** [comment]
I'm afraid not. There is not way to revert an already broadcasted transaction. Your wallet have just one transaction, so all others has been arrived to another recipient wallet.

**Comment by AbeLaw** [comment]
Thank you so much for looking into this for me!  You have a wonderful day! 

    On ‎Sunday‎, ‎October‎ ‎08‎, ‎2017‎ ‎12‎:‎55‎:‎32‎ ‎AM, Javier Donadío <notifications@github.com> wrote:  
 
 
I'm afraid not. There is not way to revert an already broadcasted transaction. Your wallet have just one transaction, so all others has been arrived to another recipient wallet.
