### ISSUE TITLE
My phone died - cannot recover anything, had funds in my Copay wallet... HELP

### ISSUE THREAD

**Issue by alexexit** [bitpay/copay#6867]
So long story short, I always used copay to purchase Amazon Gift Cards and a few days ago my phone died, they told me the data isnt recoverable therefore im not sure how to get back my wallet with my money and stuff, I used to purchase amazon gift cards from there, i've done many purchases , I do have some transactions I did a few days ago before it died. Is there any way to get it back?

**Comment by jb55** [comment]
The ony way to recover your wallet is with your backup seed words. If you didn't save those then your money is gone.

**Comment by alexexit** [comment]
How do I get that seed words? Not really familiar with this

**Comment by alexexit** [comment]
Couldnt they do anything if I gave my btc address from that wallet

**Comment by dabura667** [comment]
Nope.

When you first created the wallet, Copay told you YOU NEED A BACKUP.

You didn’t write down your seed phrase backup.

**Comment by alexexit** [comment]
I took a picture of that....................with the phone..

**Comment by dabura667** [comment]
That’s not a backup. I’m sorry.

Check if any apps you had installed might have auto-backed up your screenshots folder.

**Comment by JDonadio** [comment]
> Check if any apps you had installed might have auto-backed up your screenshots folder.

**Comment by JDonadio** [comment]
> The only way to recover your wallet is with your backup seed words. If you didn't save those then your money is gone.

Exactly. This is the only way.
