### ISSUE TITLE
I'm not being able to transfer BCC from a Copay wallet to no-copay wallet.

### ISSUE THREAD

**Issue by PeVal-17** [bitpay/copay#6868]

**Comment by martyzigman** [comment]
Likewise.  It seems the Copay Bitcoin Cash wallet doesn't know how to send to a BCH address.  It thinks I want to send Bitcoin and thus it is confused.

**Comment by JDonadio** [comment]
Hi,

Copay/BitPay wallets (and also the recovery tool) use a new address format, please read:

https://github.com/bitpay/copay/wiki/COPAY---FAQ#sending-bch-shows-error-please-enter-a-valid-address

**Comment by PeVal-17** [comment]
Thanks for your response
In my case there's no error message. The wallet just stand still doing nothing.
You mean that even in this case I have to translate to a BTC Address format, and then I'll be able to send the Bcash?
If it is the case, and sorry for my lack of knowlegde, when I translate the address in the translator is it  changed in my Copay wallet?

Thanks

**Comment by JDonadio** [comment]
If your send view is empty, you have not the latest version. But the problem is the same, you need to translate the old address format into a new one using the translator tool. Once translated, use that new format in your transaction.

**Comment by PeVal-17** [comment]
I checked and I have the latest version (v 3.8.2)
I don't know how to do the address translation you refers to.
I know that the site is (https://bitpay.github.io/address-translator/) . Once the translated address is given I don't know what to do with it.

I'll appreciate you help
Thanks

**Comment by JDonadio** [comment]
You must to copy the new address and use it as your destination address in your BCH transaction.

**Comment by Berndinox** [comment]
Hopefully that Address translation thing will be removed soon.
