### ISSUE TITLE
Trezor no longer works

### ISSUE THREAD

**Issue by phuongnd08** [bitpay/copay#6869]
I think trezor changed their API and thus copay no longer play nicely with.

**Comment by JDonadio** [comment]
Hi there,

Are you having problems with your wallet? please we need more details.

**Comment by phuongnd08** [comment]
Looks like we can't send more than 50btc. But it seems it's trezor issue on
Chrome browser

**Comment by JDonadio** [comment]
So it's an API restriction, not an issue with our `chrome-extension`, we well check it.

**Comment by phuongnd08** [comment]
Right our mistakes.

**Comment by lionello** [comment]
Please check https://github.com/trezor/connect/issues/82

Changing copay to use trezor connect v3 fixed my issue.

**Comment by runn1ng** [comment]
It was an issue with segwit. When sending from an account that had even 1 transaction with segwit inputs, it threw an error. We used old bitcoinjs-lib version, that didn't know how to parse segwit transactions. It is fixed now.

**Comment by runn1ng** [comment]
It should be fixed on all the versions

**Comment by matiu** [comment]
Thanks for the info @runn1ng . So there is no need to make any change in our side

**Comment by matiu** [comment]
fixed on Trezor side.
