### ISSUE TITLE
AVG shows malware on download copay.exe

### ISSUE THREAD

**Issue by bigsk1** [bitpay/copay#6870]
cancels download because of malware alert
![avgscan](https://user-images.githubusercontent.com/32640296/31338635-f2d5ec6e-acb4-11e7-99aa-426f6606d11f.png)

**Comment by bigsk1** [comment]
I have update copay many times and never had this issue till now

**Comment by matiu** [comment]
This seems to mean that the file has "bad reputation" (https://forum.avast.com/index.php?topic=124265.0) , not really a it has something wrong on it.

I guess bad reputation can be gambled but a few users.
