### ISSUE TITLE
Funds sent without knowlodge

### ISSUE THREAD

**Issue by luisdmerizalde** [bitpay/copay#6873]
Dear Sirs.
This transaction surprises  me!!
Never made?
Could you help please.
Thanks.
![screenshot_20171009-111516](https://user-images.githubusercontent.com/31590551/31353944-536c0fb6-ace9-11e7-882c-c586742ee132.png)

**Comment by luisdmerizalde** [comment]
Transfer never made
Never received any email regarding this transaction.
Thanks

**Comment by JDonadio** [comment]
If you did not send that transaction, maybe someone else with access to your device did. The keys are stored locally in your device, so only you can access to your funds. If you never set any extra security capability like PIN/Fingerprint to open the app, PIN/Fingerprint to spend, spending password, read-only, etc, anyone can access to your wallet.

**Comment by luisdmerizalde** [comment]
Thanks
No one did. Had the phone all time with me.
I don't know that address at all.
Why did not received an email related to that?
Thanks
