### ISSUE TITLE
The config.xml file is missing a content element

### ISSUE THREAD

**Issue by masterom77** [bitpay/copay#6876]
Hello there , i got an error every time when i run this application on my machine. i am getting error, i,e 
"Error : DEP10403 : The config.xml file is missing a content element that defines the start page." I tried everything and googling a lots of time but not get rid of this error. please help me as soon possible. 

I am using VS 2017 with Cordova.

**Comment by gabrielbazan7** [comment]
I could run the project with no problems in VS2015. Let me try VS 2017. Remember to follow this guide : https://github.com/bitpay/copay#windows-phone

**Comment by masterom77** [comment]
i am getting the same problem ? can u please sort this issue.

**Comment by gabrielbazan7** [comment]
It's not working for me in VS2017. But not the same error. You try it in VS2015 ?

**Comment by masterom77** [comment]
i tried it in VS 2015,  but i m getting the same error ?if anyone have the information regarding this error, please share it with me ?

**Comment by BGalliotti** [comment]
Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will happy to help you.
Thanks.
