### ISSUE TITLE
loss of transaction

### ISSUE THREAD

**Issue by Khristofor** [bitpay/copay#6885]
Hi
Help is needed. Yesterday I bought bitcoins from my friend, he sent me a purse of 0.2174 btc from my wallet to Blockchain. I saw the transaction first. On the mail I received a confirmation (the file in the application). The total balance increased and showed the amount along with this transaction (total 1 160 dollars). This morning I opened the purse and found that there is no last transaction at all, the amount on the wallet shows such as before the last transaction was received (0.0235 btc - 111 dollars). How can this be? What to do now? Where can I find the last transfer amount (0.2174 btc)? Where did she go? How to recover it?
![img_6203 1](https://user-images.githubusercontent.com/32698456/31435038-0b454ef6-aea0-11e7-88b9-6ee02788eaeb.PNG)

**Comment by JDonadio** [comment]
This issue is not related to Copay/BitPay.

**Comment by Khristofor** [comment]
And with what it is connected? Where should I go? who can help me?


>Среда, 11 октября 2017, 19:42 +06:00 от Javier Donadío <notifications@github.com>:
>
>This issue is not related to Copay/BitPay.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением, 

Христофор Серчиди

Учредитель

ТОО ФУДМаш Сервис (ТМ Трапеза)

тел. +77772333090

**Comment by JDonadio** [comment]
You must contact to the support team for your wallet.

**Comment by Khristofor** [comment]
I can not find him. Do not you know their address?


>Среда, 11 октября 2017, 22:27 +06:00 от Javier Donadío <notifications@github.com>:
>
>You must contact to the support team for your wallet.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением, 

Христофор Серчиди

Учредитель

ТОО ФУДМаш Сервис (ТМ Трапеза)

тел. +77772333090

**Comment by JDonadio** [comment]
Do you have the transaction id?

**Comment by Khristofor** [comment]
trapeza72@mail.ru  


>Среда, 11 октября 2017, 22:34 +06:00 от Javier Donadío <notifications@github.com>:
>
>Do you have the transaction id?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением, 

Христофор Серчиди

Учредитель

ТОО ФУДМаш Сервис (ТМ Трапеза)

тел. +77772333090

**Comment by JDonadio** [comment]
Go

**Comment by Khristofor** [comment]
Thank you for your help !!! I contacted the support of the wallet and received an answer.


Отправлено из мобильной Почты Mail.Ru


среда, 11 октября 2017 г., 23:55 +0600 от Javier Donadío  <notifications@github.com>:
