### ISSUE TITLE
Sending BCH out from wallet

### ISSUE THREAD

**Issue by xiaokwang88** [bitpay/copay#6888]
I am having an issue when sending out BCH from my wallet. The screen just stops as per attachment.

Please assist.

![whatsapp image 2017-10-12 at 2 18 19 pm](https://user-images.githubusercontent.com/32728766/31481905-4c267b44-af58-11e7-9b60-570a5c4bd38f.jpeg)

**Comment by JDonadio** [comment]
Please check: https://support.bitpay.com/hc/en-us/articles/115004671663-BitPay-s-Adopted-Conventions-for-Bitcoin-Cash-Addresses-URIs-and-Payment-Requests

If you need to send to "old" addresses, and you are SURE those are BCH addresses, you can "translate" them using the BCH Translator tool: https://bitpay.github.io/address-translator/
