### ISSUE TITLE
Windows Cross Plamform Sync & GUI issues

### ISSUE THREAD

**Issue by CorpCaleCloud** [bitpay/copay#6889]
Greetings

first many thanks for supporting the windows community I can assure you its much appreciated and welcomed, thanks

I'm have sync and GUI issues. I have the copay app installed on windows 10 mobile my 950 and windows 10 surface book. I setup the wallet on my phone initially and made changes e.g. wallet name, etc however when imported the wallet to the desktop version all then option are default e.g. no wallet rename, no password, etc. even though I backed up the setting or I assume its backing up the settings.

I used the passphrase and it was accepted so I assumed it would see all the same settings, names etc bit to no avail also the GUI option at the bottom don't appear on my phone all the time basically the the desktop version I can see scan, settings, home, scan and receive and on the mobile app nothing

**Comment by JDonadio** [comment]
@CorpCaleCloud this is the common behavior for all platforms. Settings like: color, password, pin, etc, are stored locally so the import process in a different device will start your app with default settings.

**Comment by CorpCaleCloud** [comment]
Will you updating to UWP to illimate this issue as its one source code for all devices as the scale automatically?? 

Sent from my Windows 10 phone

**Comment by gabrielbazan7** [comment]
We already use UWP for windows phone versions. Right now we are migrating to ionic 2 and angular 2, we hope some of those issues will be solved. Thanks !

**Comment by CorpCaleCloud** [comment]
Thanks for the update much appreciated and thanks for your update. I'm starting a Microsoft blog soon so would like the chance to interview you to hear your views on Microsoft and UWP

I only use Microsoft 1st party apps e.g. OneDrive, exchange, etc with some dedicated 3rd party like yours so interested in hear your views ease and hardship of working with Microsoft and yep especially.

Sent from my Windows 10 phone

**Comment by CorpCaleCloud** [comment]
Greetings

 

Can you recommend any good windows based bitcoin mining software that work with your wallet

 

Thank you

 

P.S. as you can see I’m new to bitcoin and advice would be welcome and I won’t plague you with constant email anymore

 

thanks
