### ISSUE TITLE
Transaction not confirmed

### ISSUE THREAD

**Issue by carteramillonaria** [bitpay/copay#6892]
Yesterday 11:41 a.m. made a transaction and has not yet been verified, the Transaction ID is 5f3036dfd3408aa3a43d9144e05022e4a6f70ffdf7d5b8913e66e360c89e08a2.

Please fix it and  let me know what's the problem.

Thanks
César Velázquez

**Comment by JDonadio** [comment]
For your transaction, the super economy fee level suggested by Copay is ~0,00045756 BTC. Your transaction fee is lower than recommended (0.00029998 BTC), so you just have to wait more than normal.

**Comment by carteramillonaria** [comment]
thanks for your quick response Javier, just one question, normal I was
receiving 30 minutes, or less, it's been nearly 23 hours, how much more do
you think this will be delayed?

thanks
César Velázquez

2017-10-13 7:35 GMT-05:00 Javier Donadío <notifications@github.com>:

**Comment by JDonadio** [comment]
The average time depends on the how much fee are you paying for your transaction, and also how much the network are "claiming" as normal depending on their status. Also the mempool have a lot of transactions, so that could be another reason.
