### ISSUE TITLE
How to cancel transaction

### ISSUE THREAD

**Issue by infernotower** [bitpay/copay#6894]
Hi,

I created a txn id since Oct 14, 2017 0b9dd51cf85898da716cbcf35222cdb23ab6ee3488afc23db2152c6950853337 and this has been pending for 1-2days. This transaction is no longer relevant. How can I cancel this. I would appreciate your help

Thanks,
Nick

**Comment by JDonadio** [comment]
Unfortunately not. Please check https://github.com/bitpay/copay/wiki/COPAY---FAQ#can-a-transaction-be-reversed
