### ISSUE TITLE
Transaction Not Confirmed

### ISSUE THREAD

**Issue by pedrocartaxo** [bitpay/copay#6896]
Hello.

I sent coins to a wallet that did not confirmed yet (16 hours waiting). What happened?

Transaction ID:

 1a556641413fdac8afa1f4c5694f1ebe36e60dc8a6f36cc6fc81efe05fce5bea

**Comment by JDonadio** [comment]
Your fee is a little lower than normal but you just have to wait, the bitcoin network is a little congested right now.

**Comment by pedrocartaxo** [comment]
Can I change the fee to make it faster?

**Comment by JDonadio** [comment]
We have not an option available to do it. You can check https://github.com/bitpay/copay/issues/5102 for more info

**Comment by pedrocartaxo** [comment]
But is it possible to choose the fee in the next transactions?

**Comment by JDonadio** [comment]
It's confirmed now.
