### ISSUE TITLE
How to Import Wallet? 

### ISSUE THREAD

**Issue by yue816** [bitpay/copay#6900]
I downloaded Copay app in my iPhone and set up account the get everything (incl. back up wallet) last month, but deleted the app carelessly last week. Now I'm trying to import my previous wallet in the app. I do remember the **Recovery Phrase** (12 Words), but it shows that" the recovery phrase could require a password to be" in the Advanced Options. Which password dose this indicate to? Already tried all the passwords I used during account setting, but it's still failed to import the wallet. 

Please kindly help. 
Many Thanks!

**Comment by dabura667** [comment]
don't enter a password, leave it blank

**Comment by yue816** [comment]
I entered the 12 WORDS, but it shows that" Error  - Wrong number of recovery words:1". What dose the number "1" represent for? I do not think my 12 WORDS are wrong because there was a step that needs me to input the 12 Words based on what I wrote down.

**Comment by dabura667** [comment]
Enter spaces in between each word:

我是 is WRONG

我 是 is RIGHT
