### ISSUE TITLE
copay wallet network error all the time, all my wallet is same issue

### ISSUE THREAD

**Issue by stone2y** [bitpay/copay#6903]
copay wallet network error all the time, all my wallet all have the same issue

no matter I choose WIFI or 4g or 3g. Always show network error. 

And the wallet cannot update the most recent wallet balance correctly. 
Some payment I paid 1 week ago, the balance shows back to my wallet balance again from payee wallet. But receiving wallet showed received already. 

pls, help me to fix it. It's very important. and I feel unsecured.

**Comment by Zanoufb** [comment]
same thing with me i ever tried deleting the app and getting back in and now I cant even login with my 12 words because of network error. not a pleasant experience at all

**Comment by Magalon** [comment]
It's probably an error with the API. Give it some time (about 10 minutes open without trying to be into one wallet(if you have more than one) and it will connect back to it 👍

**Comment by stone2y** [comment]
It's been an hour now. Waiting is not a good solution. Can any copay IT can fix this problem？

**Comment by stone2y** [comment]
It's been working now. Can anyone explain to me what exactly happened?

**Comment by JDonadio** [comment]
Please check https://github.com/bitpay/copay/issues/6945
