### ISSUE TITLE
Did not receive Bitcoin cash 

### ISSUE THREAD

**Issue by NadiiaS** [bitpay/copay#6906]
Hi,
I created new Bitcoin cash wallet. I sent 2 Bitcoin cash from exchange to new wallet which had an address : 16xLnCfYZ2v9L73UXG3EgCPE2BVbaCvz2h. I was using this exchange for Bitcoin previously and it worked. But with Bitcoin cash new wallet did not work and I did not receive the 2 Bitcoin cash which I sent. After couple ours I did back up of the wallet and it changed the address to bitcoincash:CRPwmpfzoLzUcraP35RXzoSBXbNw9FkrqJbitcoincash:CRPwmpfzoLzUcraP35RXzoSBXbNw9FkrqJ. Could you help me to solve this issue. I have screen shoots which prove transaction. Thank you very much

**Comment by dabura667** [comment]
https://blockchair.com/search?q=16xLnCfYZ2v9L73UXG3EgCPE2BVbaCvz2h

You did not receive any bitcoin OR bitcoin cash... at all...

This is not Copay's fault. Your exchange has not sent anything yet.

**Comment by NadiiaS** [comment]
Hi Dabura,
Could please look at the transaction withdraw which I attached.
Unfortunately, It shows that transaction is confirmed. I did not have any
problems with bitcoin, only with bitcoin cash. Plus, also another thing
which confused me that I sent bitcoin cash to wallet Before I created the
backup phrase. But after I created backup phrase the address automatically
changed.
Thank you for your help,
Nadiia

**Comment by NadiiaS** [comment]
When I opened the transaction it shows my other wallet
https://blockchair.com/bitcoin-cash/address/16SE97nkQPnsHYayiFo6QuTnsDu9yU2J4x
.
This wallet I use for bitcoin. It is possible that I accidentally sent
bitcoin cash to bitcoin wallet:( Is it possible to recover that bitcoin
cash?

**Comment by NadiiaS** [comment]
I attached two screenshots as proof, just in case.

**Comment by JDonadio** [comment]
@NadiiaS for incoming transactions you must contact to the sender, your exchange in this case. The transaction was built and broadcasted from they end. We cannot do anything from here.
