### ISSUE TITLE
No tengo muy claro el tema de las comisiones.

### ISSUE THREAD

**Issue by Eugeniomoroz** [bitpay/copay#6907]
Hola, envié $Arg 61 en bitcoins y me cobraron $Arg 56 de comisión. He utilizado la comisión normal para el envío. A cuánto se reduciría la comisión si selecciono la opción "supereconomica" y cuánto tiempo más podría demorar?.

**Comment by JDonadio** [comment]
@Eugeniomoroz hola, el tema de las comisiones es algo que tenes que mirar en términos de bitcoin, no de pesos. Aqui tenes una explicación muy buena de como funciona:

https://github.com/bitpay/copay/issues/5164#issuecomment-265569494

Esto también te puede ayudar:

https://github.com/bitpay/copay/wiki/COPAY---FAQ#copay-requires-high-fees-for-low-amounts-transactions

Hay que tener en cuenta que enviar $61 ARS es (hoy por hoy) un monto demasiado bajo y no conviene económicamente como te ocurrió a vos.
