### ISSUE TITLE
Recovery Bitcoin cash from Bitcoin copay wallet 

### ISSUE THREAD

**Issue by NadiiaS** [bitpay/copay#6909]
I sent my Bitcoin cash to Bitcoin copay wallet. Who know legit way to recover Bitcoin cash from Bitcoin copay wallet?

**Comment by JDonadio** [comment]
Please check this out: https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-sent-bch-coins-into-a-btc-address-what-can-i-do-to-recover-my-bch-coins
