### ISSUE TITLE
Issues sending BCH 

### ISSUE THREAD

**Issue by mrauchs** [bitpay/copay#6910]
Hello,

When I'd like to send Bitcoin Cash (BCH) from my Copay wallet to another wallet, the screen suddenly freezes after I enter the recipient's address and the transaction amount (see screenshot). 

![image1](https://user-images.githubusercontent.com/12615254/31608436-a593e6f6-b270-11e7-9108-4ac77f675999.png)

I'd be happy if somebody was able to help with this issue.

Thanks in advance.

**Comment by JDonadio** [comment]
Hi @mrauchs, can you tell us what version are you running?

**Comment by mrauchs** [comment]
Hi @JDonadio, I'm using v3.8.2. (downloaded for the first time a few days ago).

**Comment by JDonadio** [comment]
@mrauchs it's caused by the translation to the new address format for BCH. Please take a look here: https://support.bitpay.com/hc/en-us/articles/115004671663

We'll improve the UI for this case. Thanks for report

**Comment by mrauchs** [comment]
Hi @JDonadio, OK I see - so if I translate the recipient address format into the new format supported by Copay, it should work?

**Comment by JDonadio** [comment]
Yes. If you need to send to "old" addresses, and you are SURE those are BCH addresses, you can "translate" them using the BCH Translator tool: https://bitpay.github.io/address-translator/

**Comment by mrauchs** [comment]
Great, thank you very much!
