### ISSUE TITLE
Seed words translation

### ISSUE THREAD

**Issue by xelawafsTemp** [bitpay/copay#6915]
I have several questions about how seed words string translation occur:

1. How are seed words translations done?
2. Is this supported via a devices global language setting or through use of translation strings within the app?
3. What languages are supported in terms of translation and is it possible to add more languages on my copay fork?
4. What happens when I use seed words say in French then later try to recover a backed up wallet in a different language setting. I guess what I'm asking is if one can only recover backed up wallets when copay/the device is set to the same language used when the seed words were first generated.

**Comment by dabura667** [comment]
https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki

**Comment by JDonadio** [comment]
Hi @xelawafsTemp,

1- We do not translate the seed word, it's a BIP (check above link)
2- Copay use the default language set in your device
3- Check https://crowdin.com/project/copay
4- Your seed cannot be translated and must be used without changes
