### ISSUE TITLE
Can I transfer BTC from Copay Wallet to Zebpay Wallet or transfer to bank?

### ISSUE THREAD

**Issue by della1** [bitpay/copay#6917]
Dear Copay,

I just want to know that can I transfer BTC from Copay to Zebpay? 

Secondly, at the time of creating account, there was no option of Bank Details or KYC! So if in case, I need to withdraw money to Bank, how would I be able to do that?

Please help.

**Comment by JDonadio** [comment]
@della1 Copay doesn't work with bank accounts. Your funds are stored only in your wallet.

> I just want to know that can I transfer BTC from Copay to Zebpay?

Sure, you can move your funds to any BTC address. Just scan the recipient QR code (or copy/paste the destination address), select your amount and sign.

**Comment by della1** [comment]
Thanks team! Thanks for this info!
