### ISSUE TITLE
BCH is not available as currency when you send money

### ISSUE THREAD

**Issue by NadiiaS** [bitpay/copay#6922]
![1](https://user-images.githubusercontent.com/29939451/31685357-81040042-b337-11e7-9764-991104560b22.png)

I was trying to send BCH, but after I chose a recipient. I have to put the amount of money and it automatically set the currency to BTC. I can not change it to BCH.

**Comment by JDonadio** [comment]
Hi @NadiiaS, if the recipient address doesn't use the new bitcoin cash address format, will be read as a regular bitcoin address. Please, before set the recipient address translate it and the BCH amount will be shown.

Both Copay as the Recovery tool accepts BCH addresses starting with C or H, which is a new convention to prevent errors (https://support.bitpay.com/hc/en-us/articles/115004671663-BitPay-s-Adopted-Conventions-for-Bitcoin-Cash-Addresses-URIs-and-Payment-Requests)

If you need to send to "old" addresses, and you are SURE those are BCH addresses, you can "translate" them using the BCH Translator tool: https://bitpay.github.io/address-translator/

**Comment by NadiiaS** [comment]
Thank you very much
