### ISSUE TITLE
Copay - Error at Confirm

### ISSUE THREAD

**Issue by Brad123ghost** [bitpay/copay#6923]
When i try send some bitcoins it says WALLET_LOCKED: Wallet is locked how do i fix this

**Comment by franckbonin** [comment]
same issue here !

**Comment by rickygu** [comment]
Getting this too. The error seem to be coming from the BWS server in the file here:

https://github.com/bitpay/bitcore-wallet-service/blob/7f928b0afe92297e3da6559deb4b0da85f6382ab/lib/lock.js

It could be the BWS server hosted by Bitpay is having problems.

**Comment by rickygu** [comment]
I've also created an issue on BWS here:
https://github.com/bitpay/bitcore-wallet-service/issues/711

**Comment by matidu7777** [comment]
Same here this morning (18.10.2017) 

" Could not create transaction" 
"WALLET_LOCKED: Wallet is locked"

What that means? I lost some money now because of the exchange rate. That is not accaptable! 

What is the issue?

**Comment by matiu** [comment]
Could you please follow https://github.com/bitpay/copay/issues/6930 ? We are working on this issue.
