### ISSUE TITLE
Why my wallet is locked?what the hell?

### ISSUE THREAD

**Issue by tr0j4n** [bitpay/copay#6924]
![wechatimg652](https://user-images.githubusercontent.com/2802698/31701822-8b933846-b398-11e7-94f0-f42e4b41203f.jpeg)

the message say: 

WALLET_LOCKED: Wallet is locked

Now I can't transfer bitcoin to another address

**Comment by Temidayo62** [comment]
I'm experiencing the same problem too. What's is the ultimate solution?

**Comment by ninakor** [comment]
have same issue today. A lot of coins are locked. What to do?

**Comment by sonofman2009** [comment]
What is the solution to this wallet locked?

**Comment by jk219** [comment]
my wallet says same thing

**Comment by jk219** [comment]
where can I get help for this

**Comment by jk219** [comment]
what is the number for bitpay>??

**Comment by zhaodong1982** [comment]
Same problems....

**Comment by jk219** [comment]
where is the support for this issue??

**Comment by jk219** [comment]
my wallet is also locked cant send

**Comment by jk219** [comment]
how do u unlock??

**Comment by 2m0rr0w2** [comment]
I have the same problem!!

**Comment by 777taka777** [comment]
I have  the same problem!
What is the solution to this wallet locked?

**Comment by tr0j4n** [comment]
the version is 3.7.3

**Comment by jk219** [comment]
what/?

**Comment by ninakor** [comment]
where is support? already lost a lot of money and wallet not fixed yet!

**Comment by jk219** [comment]
I don't know but my money is stuck in wallet now...

**Comment by JediIsa** [comment]
Same Here. Pisswd off too

**Comment by Impostah** [comment]
Same.......

**Comment by r6nr6n** [comment]
stuck like chuck until IT department wakes up, see you all tomorrow, best of luck everyone

**Comment by junderw** [comment]
WALLET_LOCK means the server wasn't responding for over 300 seconds, so the request failed.

It has nothing to do with locking your wallet, the "lock" (aka the server will prevent other requests from the same wallet) kept another process waiting for too long. (the timeout is 5 minutes currently)

They are probably getting DDOSed right now or something to cause their servers to be slow.

**Comment by matiu** [comment]
Could you please follow https://github.com/bitpay/copay/issues/6930 ? We are working on this issue.

**Comment by ebcmate** [comment]
my bitcoin wallet was locked also why bitpay is not solving this issue
