### ISSUE TITLE
Wallet_Locked

### ISSUE THREAD

**Issue by peacekeeper03** [bitpay/copay#6925]
Hello 
I have a problem with a locked wallet. Why is the wallet locked?
How to unlock?
![screenshot_20171018-081007](https://user-images.githubusercontent.com/14297358/31703388-a52a8414-b3dc-11e7-9a7f-7ce9147923c4.png)

But resyncing the payment protocol under options does not fix it.

**Comment by JediIsa** [comment]
Same Issue

**Comment by ninakor** [comment]
A lot of people have same issue and losing money. Support doesn`t answer

**Comment by peacekeeper03** [comment]
May its a temporary network problem?



Am 18. Oktober 2017 8:44:25 vorm. schrieb ninakor <notifications@github.com>:

**Comment by junderw** [comment]
WALLET_LOCK means the server wasn't responding for over 60 seconds, so the request failed.

It has nothing to do with locking your wallet, the "lock" (aka the server will prevent other requests from the same wallet) kept another process waiting for too long. (the timeout is 5 minutes currently)

They are probably getting DDOSed right now or something to cause their servers to be slow.

**Comment by matiu** [comment]
Could you please follow https://github.com/bitpay/copay/issues/6930 ? We are working on this issue.
