### ISSUE TITLE
Yet another locked wallet

### ISSUE THREAD

**Issue by DFpxz** [bitpay/copay#6926]
How the fuck do we fix this?
![untasdsaitled](https://user-images.githubusercontent.com/32893545/31704521-87e4877c-b3c0-11e7-9e4d-e8d66c63f09d.jpg)

**Comment by M-sala** [comment]
I can confirm also - seems like a problem on BitPay side, since nothing works. Cannot create new wallets (testnet too) or send BTC. Tried on two different smartphones and chrome CoPay extension.

Same.

**Comment by cryptolayer** [comment]
Confirmed, same problem here. Annoying.

**Comment by knoxcard** [comment]
Same

**Comment by r6nr6n** [comment]
🐌 same here never recieved an email claiming my account was locked or anything, so I was kind of confused check the block for transactions it was confirmed four times but didn't go through still pending meanwhile the price of Bitcoin is decreasing like crazy

**Comment by emekacollins** [comment]
Same issue here😈😈😈😈😈😈😈😈😈😈😈😈

**Comment by matiu** [comment]
Could you please follow https://github.com/bitpay/copay/issues/6930 ? We are working on this issue.
