### ISSUE TITLE
Trouble loading bitpay card from bitpay wallet

### ISSUE THREAD

**Issue by dpark15** [bitpay/copay#6927]
Hi,

I can't load my bitpay card from my bitpay wallet even though there are btcs in the bitpay wallet. This is the error message I see: "When I try to add money to my bitpay card from my bitpay wallet, the phone shows me this error message: "Could not create transaction WALLET_LOCKED: Wallet is locked"

**Comment by r6nr6n** [comment]
Having same issue

**Comment by matiu** [comment]
Could you please follow https://github.com/bitpay/copay/issues/6930 ? We are working on this issue.
