### ISSUE TITLE
Wallet locked 

### ISSUE THREAD

**Issue by r6nr6n** [bitpay/copay#6928]
Tried loading some funds to make a quick purchase, transaction took awhile, nothing new, but when i tried transferring them My Wallet is locked. I'm seeing others are having similiar issuues, guess its on bitpays side, really been contemplating making the switch to xapo.

**Comment by junderw** [comment]
WALLET_LOCK means the server wasn't responding for over 300 seconds, so the request failed.

It has nothing to do with locking your wallet, the "lock" (aka the server will prevent other requests from the same wallet) kept another process waiting for too long. (the timeout is 5 minutes currently)

They are probably getting DDOSed right now or something to cause their servers to be slow.

**Comment by matiu** [comment]
Could you please follow https://github.com/bitpay/copay/issues/6930 ? We are working on this issue.
