### ISSUE TITLE
Wallet locked

### ISSUE THREAD

**Issue by sbcreed** [bitpay/copay#6929]
Wallet locked. What to do?
Кошелёк заблокировали. Что делать?

**Comment by junderw** [comment]
WALLET_LOCK means the server wasn't responding for over 300 seconds, so the request failed.

It has nothing to do with locking your wallet, the "lock" (aka the server will prevent other requests from the same wallet) kept another process waiting for too long. (the timeout is 5 minutes currently)

They are probably getting DDOSed right now or something to cause their servers to be slow.

**Comment by r6nr6n** [comment]
I highly doubt they are undergoing a DOS Attack, ps it times out way before 5 min go play kiddie script in perl

**Comment by matiu** [comment]
please follow https://github.com/bitpay/copay/issues/6930, we are investigation the issue
