### ISSUE TITLE
Wallet locked?

### ISSUE THREAD

**Issue by WaiterTom** [bitpay/copay#6930]
Don't get my btc' s please need help thx

**Comment by matiu** [comment]
We are investigating the issue now. I will update this ticket as soon as we have more information.

**Comment by matiu** [comment]
We had a problem with one of our backend servers, it should be fixed now, could you please retry?

**Comment by WISERY1** [comment]
Yes it work now!! Thanks ;)

**Comment by matidu7777** [comment]
Yes it works now again!!! Great service, like all the time!!!!!!!

**Comment by matiu** [comment]
Thanks for the update.  We are sorry for the inconvenience. 

Please note:  in case there is an error with the backend, and you need immediate access to your funds you can import your backup on any BIP39 compatible wallet or use our static Recovery Tool (https://bitpay.github.io/copay-recovery/).

**Comment by WISERY1** [comment]
I have a BIG problem now! I have deinstalled the Bitpay app and now i don't have my old wallet !!
please help

**Comment by WaiterTom** [comment]
Thx all fine ...fastest service ever

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------
An 18. Okt. 2017, 12:13, Matias Alejo Garcia schrieb:

**Comment by matidu7777** [comment]
First I was a little disappointed, but looking back, the Bitpay Support is very fast and always successful!!!! Thanks guys for making a great job !!!!

**Comment by Serpico27** [comment]
I'm getting the same error. It either says network error or wallet locked.

**Comment by lolazo0** [comment]
Me too

**Comment by dre5025** [comment]
I am also getting the network and wallet locked error

**Comment by JDonadio** [comment]
@dre5025 please follow https://github.com/bitpay/copay/issues/6945

Closing this, locked error was fixed already.

**Comment by pvrooyen** [comment]
@matiu Do you mind sharing how what the fix was?  I am having a similar issues based on recent forks of copay and BWS

**Comment by BitLox** [comment]
@matiu Yes, it would be very helpful to we who run BWS instances ourselves to get a bit of info as to how/why this happens and how to fix it. Please?

**Comment by keeperlink** [comment]
I just for the error. Reloading the app doesn't help. Last time I used it to pay out just yesterday with no issues.
