### ISSUE TITLE
copay scanning funds since 3 days :( please help me

### ISSUE THREAD

**Issue by anonym12345** [bitpay/copay#6935]
hello. i press scanning funds. since 3 days i cant do anything with my btc because copay scanning funds. what can i do that copay stop scanning funds?

**Comment by JDonadio** [comment]
Hi there, could you please attach some screenshot of your problem?

**Comment by anonym12345** [comment]
http://www.bilder-upload.eu/show.php?file=091dd2-1508427238.png

**Comment by JDonadio** [comment]
Can you go to settings > wallet > more opts > wallet addresses > scan addresses for funds

Tell me how it went

**Comment by anonym12345** [comment]
yes wallet adress  scan adress!!! yes . what can i do

**Comment by JDonadio** [comment]
I mean, did you use that function and it remains scanning?

![copay_-_copay_bitcoin_wallet](https://user-images.githubusercontent.com/13851807/31783147-9cfb8304-b4d3-11e7-9bd0-a5a65a6f9c61.png)

**Comment by anonym12345** [comment]
yes i press scan adress for funds. and it dont stop scanning. yes it remains scanning

**Comment by anonym12345** [comment]
?

**Comment by anonym12345** [comment]
?

**Comment by wesdacar** [comment]
same issue here

**Comment by graburn** [comment]
I have the same issue also. It has been stuck at "Scanning funds..." for weeks! Please help; I would like to get my BCH out.

**Comment by bartonaz** [comment]
Did anyone solve this issue? I have the same problem with a BTC wallet in the BitPay app.

**Comment by gabrielbazan7** [comment]
Hi! everything is working as expected for me. You still having this issue ?

**Comment by bartonaz** [comment]
Yesterday I've removed, then installed the BitPay app, and recovered my wallet. It was still showing the `[Scanning funds]` message for several hours. But then at some point it showed me the balance.

I have no idea what caused this behavior. There were also no changes to the balance of the wallet during all this time.

**Comment by graburn** [comment]
Not closed for me! I am still stuck at "Scanning funds..." even after re-installing the Copay app.

**Comment by bartonaz** [comment]
@graburn Although it doesn't sound logical, my balance showed up right after I made a left or right swipe over my wallet in the main screen with the list of all wallets. Like when you swipe a message in Mail to `delete` or `mark as read`, if you use iOS. I doubt it's related, but I mention it just in case.

**Comment by graburn** [comment]
Alas, I have an Android phone. I went into the app and tried to replicate what you described, but I couldn't get that sort of "swipe" functionality to work in the Android app. I also recovered the wallet with the latest version of the PC desktop application and my "Scanning funds" issue exists there too.

**Comment by graburn** [comment]
Help! Although it does reflect the correct balance, it still says "Scanning Funds" and if I try to transfer any of the BCH out, it says "Insufficient Funds."

**Comment by oohnajra** [comment]
I'm having the same issue with Copay v3.11.1 on Windows 10:

![image](https://user-images.githubusercontent.com/161342/34945870-157bbd14-fa05-11e7-99d7-06ecf2e19bba.png)

And I'm seeing the following warning in the session log:

[2018-01-15T13:58:15.275Z] [warn] Unknown error type: WALLET_BUSY: Wallet is busy, try later

Any help would be appreciated.
