### ISSUE TITLE
Copay BCH (BitcoinCash) wallet funded but unable to send Bitcoincash to other BCH recipient 

### ISSUE THREAD

**Issue by jasperzandstra** [bitpay/copay#6939]
How can I possibly send BitcoinCash from my copay wallet too another wallet?

There is no send option, only receive.

Many thanks in advance

**Comment by nirbhaiiy** [comment]
same issue with me.
There is no option for sending BCH. Like there is option for inserting recepient address for BTC.

**Comment by JDonadio** [comment]
Hi guys, 

Both Copay as the Recovery tool accepts BCH addresses starting with C or H, which is a new convention to prevent errors (https://support.bitpay.com/hc/en-us/articles/115004671663-BitPay-s-Adopted-Conventions-for-Bitcoin-Cash-Addresses-URIs-and-Payment-Requests)

If you need to send to "old" addresses, and you are SURE those are BCH addresses, you can "translate" them using the BCH Translator tool: https://bitpay.github.io/address-translator/

**Comment by jasperzandstra** [comment]
thanks, works for me

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Kind regards,
*Jasper Zandstra*

**Comment by nirbhaiiy** [comment]
I have translated my BTC address into BCH. I saw BTC into BCH so I inserted
my BTC address. I followed your translator as it displayed.
https://bitpay.github.io/address-translator/

Now I have sent all my BCH to that translated address. Please do something
and help me getting back my BCH to copay wallet. Please communicate
blockchain team.



Regards,
Nirbhay A. Chawhan,
Advocate, Nagpur.
9730902824.

**Comment by nirbhaiiy** [comment]
Go through the attachment. See what others think about bitpay and it's
illogical settings.

Regards,
Nirbhay A. Chawhan,
Advocate, Nagpur.
9730902824.

On 22 Oct 2017 10:11, "Nirbhay Chawhan" <nirbhaiiy@gmail.com> wrote:

I have translated my BTC address into BCH. I saw BTC into BCH so I inserted
my BTC address. I followed your translator as it displayed.
https://bitpay.github.io/address-translator/

Now I have sent all my BCH to that translated address. Please do something
and help me getting back my BCH to copay wallet. Please communicate
blockchain team.



Regards,
Nirbhay A. Chawhan,
Advocate, Nagpur.
9730902824.

**Comment by nirbhaiiy** [comment]
Shame on you BitPay team. It is after l lost my BCH due to you causal and
poor support that you have published a remark in that translator page. See
the attached image. Shameful. You are liable to give back my 1.6 BCH.

Regards,
Nirbhay A. Chawhan,
Advocate, Nagpur.
9730902824.
