### ISSUE TITLE
您好，COPAY钱包对于SW2+分叉，怎么对待？

### ISSUE THREAD

**Issue by hjqdfj** [bitpay/copay#6940]
根据纽约共识达成协议，先隔离验证，今年于11月启动SW2+，原主链由1M扩容至2M，块高度大约494784后进行分叉。假如分裂成两个，原主链1M的bitcoin存在你们开发的钱包中，会不会被吞掉？你们会采取什么样的措施保证我拿真金白银购买的bitcoin币不受到损失？

**Comment by hjqdfj** [comment]
该怎样保证我的利益不受到损害？

**Comment by JDonadio** [comment]
Translation from google: 

> According to the agreement reached in New York agreement, first isolated verification, launched in November this year, SW2 +, the original chain from 1M to 2M expansion, block height of about 494,784 after the fork. If split into two, the original main chain 1M bitcoin exist in your development of the wallet, will not be swallowed? What measures will you take to ensure that I take the real money to buy the bitcoin currency is not lost?

We are evaluating the best options for our wallet users and the best way for the apps to react the Segwit2x fork set to happen in mid-November.

In Copay and BitPay wallets the users – and only the users – hold their private keys. For that reason, it will be always up to the user to decide exactly what path to take and when and how to move their funds.

We are committed to maximizing our users' security. In the coming weeks, we will provide more details about the Copay and BitPay apps' plans for the fork.

**Comment by Roddy1219** [comment]
我也在使用BitPay ,并且我想了解一下对于BTG你们会不会支持？

**Comment by BGalliotti** [comment]
Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will happy to help you.
Thanks.
