### ISSUE TITLE
Support for Android 4.0

### ISSUE THREAD

**Issue by xelawafsTemp** [bitpay/copay#6941]
I see copay has support for android 4.4 and up on the Playstore. What specific changes can I do on my app to get support down to 4.0?

**Comment by JDonadio** [comment]
Unfortunately the versions below 4.4 are not supported, there is not a "hack" to make it work properly on these versions.

**Comment by xelawafsTemp** [comment]
@JDonadio as always, thanks for the quick feedback. This is something I'll actively be looking to solve. Any material/copay sections you could point out for me to focus on will be helpful.

If it's in line with Copay's project direction, I'll definitely do a pull request.

Thanks!

**Comment by JDonadio** [comment]
We had tons of issues for that versions, so we decide to not support lower versions. https://github.com/bitpay/copay/issues/5030

Related posts:
https://github.com/bitpay/copay/issues/5412
https://github.com/bitpay/copay/issues/5346
https://github.com/bitpay/copay/issues/3686
https://github.com/bitpay/copay/issues/3682
https://github.com/bitpay/copay/issues/3553
https://github.com/bitpay/copay/issues/4273
https://github.com/bitpay/copay/issues/4480
etc etc etc
