### ISSUE TITLE
How to send BCH to other BCH users?

### ISSUE THREAD

**Issue by nirbhaiiy** [bitpay/copay#6942]
I have received BCH in wallet. But there is a remark that no wallet support BCH. There are many wallets  supporting BCH. Permit us to send and receive BCH.

**Comment by JDonadio** [comment]
Could you provide your wallet id? you can find it in settings > wallet > more opts > wallet information

**Comment by nirbhaiiy** [comment]
Hi, this is my BCH wallet ID-

ef7eccc3-bf79-4674-b97e-4d27d2e4ea92


Regards,
Nirbhay A. Chawhan,
Advocate, Nagpur.
9730902824.

**Comment by JDonadio** [comment]
Did you check the settings > bitcoin cash support > scan your wallets for bitcoin cash

**Comment by nirbhaiiy** [comment]
Yes, but there is a remark saying there are no walee Rs to support BCH. I
could not click on that remark or any other option after that.

Regards,
Nirbhay A. Chawhan,
Advocate, Nagpur.
9730902824.

**Comment by nirbhaiiy** [comment]
I am attaching screenshot of the same. After I click on scan BCH wallet
option I get this. please see the attachment.

Regards,
Nirbhay A. Chawhan,
Advocate, Nagpur.
9730902824.

**Comment by JDonadio** [comment]
I could not see any attached file, you can send it to `javier@bitpay.com`

**Comment by nirbhaiiy** [comment]
i have sent email on your address. Tge file attached says that no wallets
eligible for BCH.

Regards,
Nirbhay A. Chawhan,
Advocate, Nagpur.
9730902824.

On 20 Oct 2017 22:58, "Javier Donadío" <notifications@github.com> wrote:

I could not see any attached file, you can send it to javier@bitpay.com

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bitpay/copay/issues/6942#issuecomment-338271292>, or mute
the thread

**Comment by JDonadio** [comment]
Thanks for the screenshots. Your wallet is not listed in that list because it was already duplicated. You can use it without problems.

**Comment by nirbhaiiy** [comment]
Hi, I could not understand what you said. My issue still remains the same.
I am not able to send BCH to other BCH address. There is only sending
option for BTC.

Regards,
Nirbhay A. Chawhan,
Advocate, Nagpur.
9730902824.

**Comment by JDonadio** [comment]
> I am not able to send BCH to other BCH address. There is only sending
option for BTC.

This info is much more clear. 

Both Copay as the Recovery tool accepts BCH addresses starting with C or H, which is a new convention to prevent errors (https://support.bitpay.com/hc/en-us/articles/115004671663-BitPay-s-Adopted-Conventions-for-Bitcoin-Cash-Addresses-URIs-and-Payment-Requests)

If you need to send to "old" addresses, and you are SURE those are BCH addresses, you can "translate" them using the BCH Translator tool: https://bitpay.github.io/address-translator/

**Comment by nirbhaiiy** [comment]
Sorry to say but you are still beating around the bush. Issue is most
simple.
 There is no option in Copay wallet to send BCH or to sell BCH.

What are we going to do with BCH in our wallet? Where is the option to
insert BCH address.
You are given links and talking about old address, errors, translate BCH.
What's wrong?

Regards,
Nirbhay A. Chawhan,
Advocate, Nagpur.
9730902824.

On 21 Oct 2017 18:47, "Javier Donadío" <notifications@github.com> wrote:

I am not able to send BCH to other BCH address. There is only sending
option for BTC.

This info is much more clear.

Both Copay as the Recovery tool accepts BCH addresses starting with C or H,
which is a new convention to prevent errors (https://support.bitpay.com/
hc/en-us/articles/115004671663-BitPay-s-Adopted-
Conventions-for-Bitcoin-Cash-Addresses-URIs-and-Payment-Requests)

If you need to send to "old" addresses, and you are SURE those are BCH
addresses, you can "translate" them using the BCH Translator tool:
https://bitpay.github.io/address-translator/

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bitpay/copay/issues/6942#issuecomment-338393860>, or mute
the thread

**Comment by JDonadio** [comment]
> There is no option in Copay wallet to send BCH or to sell BCH.

Buy and sell integration (Coinbase and Glidera) are not working with BCH.

> Where is the option to insert BCH address.

Send tab > address input

<img width="364" alt="copay_-_copay_bitcoin_wallet" src="https://user-images.githubusercontent.com/13851807/31852546-ca13f88a-b64f-11e7-8004-5281e45c89b4.png">

Copay have not an alternative flow to receive or spend BCH. It's the same for BTC.

**Comment by nirbhaiiy** [comment]
Please don't close the issue. I can deposit and send BTC from the Copay
wallet.But not BCH. Why are you not answering this simple query sir. How to
send BCH from copay wallet to other BCH address?

Regards,
Nirbhay A. Chawhan,
Advocate, Nagpur.
9730902824.

**Comment by JDonadio** [comment]
> How to send BCH from copay wallet to other BCH address?

As I said before, there is not an alternative flow to BCH, it's the same as BTC.
Put your BCH destination address in the input field on send tab (should use the new BCH address format, if not, will be treated like BTC address).

**Comment by nirbhaiiy** [comment]
The image you have sent dear Sir is for sending BTC. Not BCH. How can I
send BCH by inserting address in that column which for BTC.

Regards,
Nirbhay A. Chawhan,
Advocate, Nagpur.
9730902824.

**Comment by nirbhaiiy** [comment]
Javier I think I did it. Sorry if I am troubling you. But please just help
me this one time. I am sending a screenshot attachment. I translated my BTC
address into BCH. And sent my BCH to that translated address. My BCH are
deducted now. Will I receive those BCH in that translated BTC address?
Please help me out.

Regards,
Nirbhay A. Chawhan,
Advocate, Nagpur.
9730902824.

**Comment by nirbhaiiy** [comment]
Sorry file was not attached. Here it is.

Regards,
Nirbhay A. Chawhan,
Advocate, Nagpur.
9730902824.

**Comment by nirbhaiiy** [comment]
I thought I have to convert BTC address. As the option was BTC into BCH. I
did so. what to do now? I have sent all my BCH to that address.

Regards,
Nirbhay A. Chawhan,
Advocate, Nagpur.
9730902824.

**Comment by nirbhaiiy** [comment]
Regarding my issue I have to inform the Copay team that there has been a
serious mismanagement. Please I need some information on following points-

1. Please inform me about the translator which you have suggested. I
translated my BTC ADDRESS INTO BCH ADDRESS.

2. Please give me some information about how the translator works and what
is the translated address.

3. Please inform as to what happens if BTC ADDRESS is translated into BCH
address mistakenly?

Regards,
Nirbhay A. Chawhan,
Advocate, Nagpur.
9730902824.


On 22 Oct 2017 00:47, "Nirbhay Chawhan" <nirbhaiiy@gmail.com> wrote:

I thought I have to convert BTC address. As the option was BTC into BCH. I
did so. what to do now? I have sent all my BCH to that address.


Regards,
Nirbhay A. Chawhan,
Advocate, Nagpur.
9730902824.

**Comment by nirbhaiiy** [comment]
Shame on you BitPay team. It is after l lost my BCH due to you causal and
poor support that you have published a remark in that translator page. See
the attached image. Shameful. You are liable to give back my 1.6 BCH.


Regards,
Nirbhay A. Chawhan,
Advocate, Nagpur.
9730902824.

On 31 Oct 2017 23:25, "Nirbhay Chawhan" <nirbhaiiy@gmail.com> wrote:

Regarding my issue I have to inform the Copay team that there has been a
serious mismanagement. Please I need some information on following points-

1. Please inform me about the translator which you have suggested. I
translated my BTC ADDRESS INTO BCH ADDRESS.

2. Please give me some information about how the translator works and what
is the translated address.

3. Please inform as to what happens if BTC ADDRESS is translated into BCH
address mistakenly?


Regards,
Nirbhay A. Chawhan,
Advocate, Nagpur.
9730902824.


On 22 Oct 2017 00:47, "Nirbhay Chawhan" <nirbhaiiy@gmail.com> wrote:

I thought I have to convert BTC address. As the option was BTC into BCH. I
did so. what to do now? I have sent all my BCH to that address.


Regards,
Nirbhay A. Chawhan,
Advocate, Nagpur.
9730902824.

**Comment by tiejungle** [comment]
Hello Nirbhay

I had the same problem. Bitpay wallet is not user friendly for BCH transactions. You have to first "translate" the recepient BCH address. Then input this new address into the "Search or enter BITCOIN address" field.

They dont have a tutorial about this on their site. Hopefully you will not lose your money.
