### ISSUE TITLE
 About 2of 2 Backup Lost

### ISSUE THREAD

**Issue by pickles333** [bitpay/copay#6943]
Hello. I am a Japanese user and I am pickles

Let me question about copay.
I could not send money to the wallet I used with copay.
The reason is that one of the terminals set up in 2 of 2 has broken down.
I do not have the backup code of the one who failed due to my own mistake.

I am very embarrassed.

In this case, is it impossible to retrieve the BTC inside?

Please tell me the way that is possible a bit.

Please lend me your wisdom.

I am using translation software, so I'm sorry by bad english.

**Comment by JDonadio** [comment]
In your case the only way to recover your funds is having the exported backup file for at least one of these wallets. If you have one, you must use the [recovery tool](https://bitpay.github.io/copay-recovery/) filling the backup input with the content of your backup file and the password field as well.

Note: this process will work only with the backup file. For 12 words backup you need all of them.

**Comment by pickles333** [comment]
ご丁寧にありがとうございます。
片方のｱｶｳﾝﾄは手元にあります。
このｱｶｳﾝﾄを操作することで、問題は解決しますか？

また、解決するならば、詳しい手順を教えていただけると幸いです。

宜しくお願いします

**Comment by pickles333** [comment]
thank you for your politeness.
One account is on hand.
Do you solve the problem by operating this account?

Also, if you solve it, I would appreciate it if you could tell me the detailed procedure.

Thanking you in advance

**Comment by JDonadio** [comment]
@pickles333 We cannot manage your wallets. The keys are stored locally in the device, so only you can manage your funds. For recovery procedure review my last comment and use the recovery tool to scan your wallets and move your funds into a new one.

**Comment by pickles333** [comment]
Thank you for your quick reply.
I am very struggling because I am poor at both copay and English.
I'm sorry.

I am sorry if it was the same question, but the terminal of the failed terminal has not saved anything including 12 words.

Is this impossible in this situation?
Sorry I have asked you many times.
If this seems to be difficult, I will try to make the question at the end.

**Comment by JDonadio** [comment]
@pickles333 don't worry, we are here to help you.

1- First all, export your wallet going to settigs > wallet > more options > export wallet. Set a password and download it or copy it. 

2- In the [recovery tool](https://bitpay.github.io/copay-recovery/) select 2 as required number of signatures and 2 for total number of copayers. Also ensure to set `btc/livenet` as chain.

3- For the first form (Backup for copayer 1) upload your exported backup (step 1) and fill the Backup password field (set in the step 1 for the exported backup). Let the Encrypted private key password field empty.

4- Accept the terms and scan.

5- Tell me how it went

**Comment by pickles333** [comment]
I am grateful for the very gentleman's response.
Despairful feeling, thanks to you, I could see hope.

I will follow your instructions.
I am working on it while referring to the Japanese site now.
I will tell you as soon as there is progress.
Please wait a moment.
Thank you very much.

**Comment by pickles333** [comment]
It may have worked!
"Search completed" was displayed, but would you solve this problem if you send an address here and send money?

**Comment by JDonadio** [comment]
Once complete the search, you must put a destination address (when these funds will be send). I personally recommend create a new wallet, make the backup process and then send the funds to that new wallet which is already backed up.

**Comment by pickles333** [comment]
I chose forwarding, but it says "Could not build tx: bitcore.ErrorTransactionMissingSignatures: Some inputs have not been fully signed Use Transaction#uncheckedSerialize if you want to skip security checks. See http://bitcore.io/guide/transaction.html#Serialization for more info." and it failed. Please let me know if there is a procedure after this.
Sorry to trouble you, but thank you.

**Comment by JDonadio** [comment]
@pickles333 I'm so sorry, for M-N wallets you must have at least M backups (2 for your case). With just one you'll not be able to sign the transaction even if the scan process found your coins. I was dealing with other things and I gave you the wrong instructions before, I apologize.

**Comment by pickles333** [comment]
そうなりますと、やはり、壊れた端末を修理するほかに方法はないということでしょうか?

**Comment by pickles333** [comment]
Does that mean that there is no way other than repairing a broken terminal?

**Comment by JDonadio** [comment]
I'm afraid not. Without backups there is no way to access to lost wallets.

**Comment by pickles333** [comment]
Okay, is there any other action I can do for you?

**Comment by pickles333** [comment]
Is there any other way to think about it?

**Comment by JDonadio** [comment]
@pickles333 Unfortunately not. Sorry about that.

**Comment by pickles333** [comment]
Okay, thank you very much.
I will not forget this kindness
