### ISSUE TITLE
Network Error!!

### ISSUE THREAD

**Issue by Wokeface** [bitpay/copay#6945]
Hi I'm unable to access my funds in the Copay wallet. 
It shows Network Error message since the last few hours. Please help. I'm freaking out. 
I've also tried scanning my wallet for funds from the settings tab. But still nothing. 
Please tell me what i should do?

**Comment by JDonadio** [comment]
Hi @Wokeface, sorry about your problem. The network error shown in the app could be caused mainly:

* Client-side: Internet connection
* Server-side: Synchronization

Your wallet will be working in a few minutes without user interaction.

Note: your funds will never leave your wallet without your concern. Don't worry your funds are safe.

**Comment by Wokeface** [comment]
Thank you for your support and reassurance.


Best,

Vardhaman Choksi

**Comment by kanimercado** [comment]
Hi I'm unable to access my funds in the Copay wallet.
It shows Network Error!!!

**Comment by Sheriff316** [comment]
Help Me I’ve got Network Error on my Copay and I don’t see my $1k worth of BTC yet and it’s been 2 hrs and it shows Network Error

**Comment by BGalliotti** [comment]
Hello @Sheriff316 
Thanks for reaching out to us.

- Are you properly connected to the internet?

Please make sure you do. If everything was fine with your internet connection and you were still getting the error, try with another internet connection.

If it was not working either, please refer to [9070](https://github.com/bitpay/copay/issues/9070#issue-355185017)

Please let us know if you have any additional questions.
Kind regards.
