### ISSUE TITLE
Network Error!!! Please Help 

### ISSUE THREAD

**Issue by Wokeface** [bitpay/copay#6946]
Hi I'm unable to access my funds in the Copay wallet.
It shows Network Error message since the last few hours. Please help. I'm freaking out.
I've also tried scanning my wallet for funds from the settings tab. But still nothing.
Please tell me what i should do?

**Comment by Jimmar** [comment]
APIs are down
http://stats.pingdom.com/dm8bfk2t3v6b/1640644

**Comment by lolazo0** [comment]
Then we have to wait ?

**Comment by Jimmar** [comment]
apparently, the only thing I can do atm

**Comment by lolazo0** [comment]
Working !

**Comment by lolazo0** [comment]
When i trying to send i see wallet is locked ... wtf??

**Comment by lolazo0** [comment]
Still same ... network error or wallet locked

**Comment by Wokeface** [comment]
Still showing network error!! 
Any idea when it will work???

**Comment by Jimmar** [comment]
seems to be working now, close this issue I guess

**Comment by JDonadio** [comment]
Please follow https://github.com/bitpay/copay/issues/6945
