### ISSUE TITLE
ERROR DE RED AYUDAAAAAAAAAAAAA!!

### ISSUE THREAD

**Issue by erichr10** [bitpay/copay#6947]
Hola. No puedo acceder a mis fondos en la cartera de Copay. 
Muestra mensaje de error de red desde las últimas horas. Por favor ayuda. Estoy enloqueciendo. 
También intenté escanear mi billetera en busca de fondos desde la pestaña de configuración. Pero aún nada. 
Por favor digame que debo hacer?

**Comment by JDonadio** [comment]
Hola, perdón por las molestias que estás teniendo, pero no te preocupes porque tus fondos están a salvo.

Por cualquier consulta, voy a dejar el siguiente ticket de referencia para que puedas estar al tanto: https://github.com/bitpay/copay/issues/6945

Si tenes alguna otra consulta por favor avisanos.

**Comment by kanimercado** [comment]
Hola. No puedo acceder a mis fondos en la cartera de Copay.
Muestra mensaje de error de red

**Comment by macuza** [comment]
Hola ! En la aplicación de CoPay me tira error de red y no me deja acceder al saldo que tengo que hacer ? Gracias

**Comment by BGalliotti** [comment]
Hola @macuza  @kanimercado ,

El mensaje **Error de red** comunmente aparece cuando hay algún problema de conexión. 
Pueden probar una conexión diferente, si están usando una red WiFi, pueden probar con otra diferente, por ejemplo una conexión de banda ancha móvil (3G/4G/5G). 

Si podían conectarse anteriormente y ahora no, comprueben si algo cambió (configuración), si cambiaron de proveedor de internet. Pueden consultar con su operador quizás el bloqueo viene de parte de ellos.

Cerciórense de no estar detrás de un firewall o proxy que pueda estar bloqueando conexiones.

**Consulten si el país donde se encuentran, les permite operar con Bitcoin**

Saludos cordiales.

**Comment by macuza** [comment]
Hola gracias por la respuesta pero ya chequee todo eso !! Lo empezó a hacer de golpe y no me muestra el saldo . Cómo puedo hacer ? Gracias espero respuesta 
Adjunto lo que me aparece 


Enviado desde mi iPhone

**Comment by BGalliotti** [comment]
Hola @macuza ,

Como mencionamos anteriormente, éste error normalmente se debe a la conexión. 
A veces los tiempos de respuesta de **BWS** pueden ser altos y provocar este error. 

Por favor, intente nuevamente.

Pruebe lo siguiente:

**Abre tu aplicación BitPay y prueba los siguientes pasos:**

- Configuración > Billetera (la billetera que desee consultar) > Más opciones> Historial de transacciones > Limpiar cache

- Configuración > Billetera (la billetera que desee consultar) > Más opciones> Direcciones de la billetera > Busca direcciones con fondos

** No desinstale la aplicación ni elimine la billetera si no la hizo correctamente, en tal caso, hágalo. Esta es la única forma de recuperar su billetera. **

Si necesita más ayuda, infórmenos.

**Comment by macuza** [comment]
Gracias nuevamente por la respuesta , intente ambos pasos pero me sigue diciendo lo mismo , nunca desinstale ni borre nada aún . Sigo sin poder ingresar . También me apareció en la segunda opción que me diste esta pantalla Quw adjunto 

Espero tus comentarios muy amable !
Enviado desde mi iPhone

**Comment by BGalliotti** [comment]
Hola @macuza ,

**Para que podamos ayudarlo más, proporcione tantos de los siguientes detalles como pueda:**

- Dispositivo actual utilizado: modelo de teléfono
- Versión actual del sistema operativo para el dispositivo: iOS, Android ...
- Versión actual de la billetera utilizada: Aplicación Bitpay> Configuración> Acerca de Bitpay
- Cualquier archivo de registro que contenga detalles del error: Aplicación Bitpay> Configuración> Acerca de bitpay> Registro de sesión> Toque la esquina superior derecha (tres puntos)> Enviar por correo electrónico (también puede capturar el contenido y adjuntar las imágenes a su correo electrónico En tal caso, asegúrese de mover el deslizador a la posición **Debug**.
- Captura de pantalla de error: en [iPhone] (https://apple.co/1DAB204) en [Android] (https://www.wikihow.tech/Take-Screenshots-on-an-Android)
- Pasos para replicar: pasos necesarios para que aparezca el error.
- ID de Wallet de BitPay: para obtener su ID de Wallet, abra su aplicación BitPay, luego vaya a `Configuración`> [Su billetera]>` Más opciones`> `Información de la Billetera`. En su teléfono, si toca la Wallet ID, la copiará en el portapapeles para que pueda pegarla en su correo electrónico.

**Esperamos con interés escuchar de usted.**

Pruebe lo siguiente:

**Abre tu aplicación BitPay y prueba los siguientes pasos:**

- Configuración > Billetera (la billetera que desee consultar) > Más opciones> Historial de transacciones > Limpiar cache

- Configuración > Billetera (la billetera que desee consultar) > Más opciones> Direcciones de la billetera > Busca direcciones con fondos

**No desinstale la aplicación ni elimine la billetera si no la hizo correctamente, en tal caso, hágalo. Esta es la única forma de recuperar su billetera.**

Si necesita más ayuda, infórmenos.

**Comment by macuza** [comment]
Ok agregué algunas cosas entre paréntesis al final de las consignas . Alcanza ?  Fotos del error ya envié.  Espero que si. Gracias nuevamente ! 

Enviado desde mi iPhone

**Comment by BGalliotti** [comment]
@macuza 

Pudimos chequear su billetera, éste es el reporte:

* Balance
  Total: 0.57809942 btc (0.00000000 btc locked)
  Confirmed: 0.57809942 btc (0.00000000 btc locked)
  Available: 0.57809942 btc (0.57809942 btc confirmed / 0.00000000 btc unconfirmed)
  
* No pending tx proposals.

* Tx history
  [Mon Apr 09 2018 22:45:16 GMT-0300] 86258740880a0953e85db573848822401959d65ba9e322a17e5b510f8520cac8 <= received 0.00706109 btc (fee/kb 0.00008798 btc) (16014 confirmations)
  [Mon Mar 12 2018 11:12:59 GMT-0300] 6e4f45c86e6540fbe7c64ff39411d3b027e61e70c11e0a8d59c9dc8e882c0c8c <= received 0.00360000 btc (fee/kb 0.00002890 btc) (20286 confirmations)
  [Tue Mar 06 2018 17:57:48 GMT-0300] 0159828147350246663fd684cf3fa2408921f190df3eb4a503c1e03aa7666577 <= received 0.04086481 btc (fee/kb 0.00012815 btc) (21162 confirmations)
  [Tue Feb 20 2018 20:36:05 GMT-0300] 59b4507ac619433864e967b37e65af955e9435f5e42312b8f73d1ae61405008a <= received 0.50000000 btc (fee/kb 0.00039175 btc) (23335 confirmations)
  [Thu Feb 08 2018 16:33:11 GMT-0300] 91703722dc75958d920909f8dcbb75337ef64d80342f81592fecd28223536c27 <= received 0.02657352 btc (fee/kb 0.00099039 btc) (25200 confirmations)
`

Para que podamos ver sus capturas por favor péguelas en su respuesta en Github, no responda desde su email.

Podemos sugerirle que pruebe instalando la aplicación de escritorio.

Esperamos su respuesta.

**Comment by macuza** [comment]
Buenos dias, muchas gracias por la respuesta. Que seria pegar las capturas de pantalla en githhub ? Donde seria eso ? En la pagina? Perdón pero no entiendo demasiado. Ahora tratare de bajarme la aplicación de escritorio.  Y como hago entonces para ver correctamente desde la aplicación del teléfono el saldo correspondiente? Como se solucionaría eso? Muchas gracias

**Comment by BGalliotti** [comment]
Hola @macuza ,
> Que seria pegar las capturas de pantalla en githhub ? Donde seria eso ?

En el mail que recibe, abra el link que aparece al final, algo como ésto **<#6947 (comment)**, responda desde la página de github. Puede pegar/adjuntar sus capturas directamente en el mensaje.

Para ver el saldo necesita tener sus billeras, luego:

Abra la aplicación Bitpay, en la pantalla principal vera las billeteras que tiene. Toque la billetera consultar.

**Comment by macuza** [comment]
Pregunto lo siguiente , si instalo la aplicación de escritorio en otro ordenador, tengo que entrar por donde dice restaurar con las 12 palabras ? 
O puedo también eliminar la aplicación del celular y volverla a instalar ?

**Comment by BGalliotti** [comment]
Hola @macuza ,

>  tengo que entrar por donde dice restaurar con las 12 palabras 

**Si**

> O puedo también eliminar la aplicación del celular y volverla a instalar ?

**Puede hacer cualquiera de las dos cosas. En caso de que no tuviera exito con su teléfono, podría probar con su computadora u otro dispositivo.**

**Primero cerciórese que tiene una copia de seguridad de todas sus billeteras, en otro caso, si desinstala la aplicación, no podrá recuperar sus billeteras y perderá todos sus fondos.**

Para saber como hacerlo por favor diríjase a #8532 Por favor no proceda antes de leer las instrucciones.

El post se encuentra en inglés, puede usar un [traductor](https://translate.google.com/) si le resulta más sencillo.

**Comment by macuza** [comment]
Ok gracias por la respuesta , donde puedo chequear que tengo una copia de seguridad realizada ? 

Enviado desde mi iPhone

**Comment by BGalliotti** [comment]
Hola @macuza 

Abra su aplicación de Bitpay.
Si hay alguna billetera con un mensaje en rojo diciendo "Necesita respaldar", necesita realizar el respaldo de esa billetera.

Para hacerlo: 

Toque la billetera que necesita respaldo
Toque **Billetera sin respaldo**
Siga los pasos
Anote la frase de recuperación en un papel, guardelo en lugar seguro y no lo comparta.

Para saber como hacer ésto por favor lea la explicacion en #8532 
Se incluyen videos explicativos.

Para las billeteras que no tengan el mensaje de  "Necesita respaldar" haga lo siguiente:
Abra la app de Bitpay
Vaya a **Configuración**
Abra la billetera que necesite ver
Toque la opción **Frase de recuperación**
Anote la frase. 

Nota: si se le pidiera una contraseña deberá ingresarla. Si la olvidó no hay nada que podamos hacer para recuperarla.

**Comment by macuza** [comment]
Hola buen dia, gracias ya chequee y cargue nuevamente las 12 palabras ( con esto es seguro que ya esta hecho el backup verdad ?)
Por otro lado como sigue apareciendo el error de red  me gustaría entrar desde el escritorio de la maquina , me pasarías los pasos que debo hacer para  ingresar desde otro lado sin usar la aplicación ? Asi puedo ver y utilizar el saldo, gracias 

Por que puede ser que aun siga el error de red en la aplicación ? Si desinstalarlo y vuelvo a bajarla cual serian los pasos? Gracias por la información

**Comment by BGalliotti** [comment]
Hola @macuza 

Respecto de las 12 palabras, anotelas en un papel y guárdelas en un lugar seguro.

Puede instalar la versión de escritorio, la encontrará [aquí](https://github.com/bitpay/copay/releases)
Desplácese hacia abajo hasta ver los botones para cada sistema operativo disponible (windows, linux, mac).

>  Por que puede ser que aun siga el error de red en la aplicación ? 

No sabemos exactamente a qué puede deberse, pero algún problema relacionado con la conexión.

> Si desinstalarlo y vuelvo a bajarla cual serian los pasos?

para desinstalar la app lea el siguiente artículo: https://support.apple.com/es-es/HT207618
Luego para instalarla nuevamente, abra la aplicación AppStore, y busque "bitpay"
Puede leer este artículo: https://support.apple.com/es-es/HT204266

Una vez instalada la aplicación, importe las billeteras que quiera usar, usando las doce palabras:

**Apoyo**
Si no ha hecho una copia de seguridad de su billetera, primero vaya a Configuración> Nombre de su billetera> Copia de seguridad. [Escriba la frase de respaldo de 12 palabras y asegúrela] (https://blog.bitpay.com/private-key-security/). No recomendamos que se lo envíe por correo electrónico.

** Actualización (en caso de necesidad) **
También puede intentar usar otro dispositivo en caso de que no pueda actualizar el sistema operativo de su teléfono.

Si está utilizando la billetera BitPay en su dispositivo móvil, actualice la aplicación de billetera en [App Store (iOS)] (https://itunes.apple.com/us/app/bitpay-secure-bitcoin-wallet/id1149581638 ) o [Google Play Store (Android)] (https://play.google.com/store/apps/details?id=com.bitpay.wallet). Si está usando la billetera en una computadora de escritorio, puede descargar la versión más reciente de la billetera BitPay [aquí] (https://bitpay.com/wallet).

**Restaurar**
Consulte el [artículo siguiente] (https://support.bitpay.com/hc/en-us/articles/115003028346
wallet-from-Copay-to-BitPay-) para conocer los pasos para restaurar la billetera desde una copia de seguridad.

Aquí hay un [video] (https://www.youtube.com/watch?v=U23E-dZEuYs&t=1s) de nuestro canal de soporte para obtener una explicación más clara.

Para importar la billetera en otro dispositivo, puede hacer clic en ** + ** junto a Billeteras y luego elegir ** Importar billetera **. Ingrese la frase de respaldo de 12 palabras y ahora tendrá acceso a la billetera desde ambos dispositivos.

Consulte el siguiente artículo para conocer los pasos para restaurar su billetera con la frase de recuperación: https://support.bitpay.com/hc/en-us/articles/115003004363-I-losme-my-wallet-or-changed-my- teléfono-Qué-puedo-hacer-para-restaurar-mi-billetera-

** Si tiene un problema, aquí hay algunas cosas que puede verificar: **

- ¿Estás seguro de que la frase de recuperación se escribió en el orden correcto?
- ¿Usaste todas las letras minúsculas y sin puntuación?
- ¿Agregaste una contraseña a tu frase de recuperación?
- [¿Tiene el código QR o la copia de seguridad de texto / archivo?] (Https://support.bitpay.com/hc/en-us/articles/115003004363-I-lost-my-wallet-or-changed-my- teléfono-Qué-puedo-hacer-para-restaurar-mi-billetera-)
- ¿Separó cada palabra con un solo espacio (sin comas ni ningún otro signo de puntuación)?

También asegúrate de:
** - Tu teléfono no usa mayúsculas para la primera letra de las palabras **

** - No estás escribiendo espacios: **

- antes de la primera palabra
- más de un espacio entre palabras
- Después de la última palabra

Asegúrese también de que sus palabras estén todas contenidas en la siguiente lista de posibles palabras:
https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt
Para otros idiomas, haga clic en [aquí] (https://github.com/bitcoin/bips/blob/master/bip-0039).

**Comment by jamesscookk** [comment]
Lock all assets hes a hacker on my account call me with my former number on
my bitpay 7632026237 voice confirm only lock all assets and i will give you
the local sheriffs department. Umber looking into it since i have his
orignal ip now

**Comment by macuza** [comment]
Hola !! Buenos días !! Estoy queriendo restaurar la billetera desde otro equipo sea PC o celular y me tira error ( no se pudo importar la frase de recuperación no es válida ) pero cuando la chequeo en mi teléfono original me la muestra tal cual . Porque podría ser ?
Espero respuesta gracias !

Enviado desde mi iPhone

**Comment by BGalliotti** [comment]
Hola  @macuza 

Por favor corrobore:
- Acentos y puntuacion.
- Espacios adicionales
- mayusculas

Las pablabras son todas en minuscula, pueden contener acentos dependiendo del idioma (espanol puede contener), debe haber solo un espacio entre palabras y no debe haber espacios antes de la primera palabra ni despues de la ultima.

Por favor intente nuevamente y dejenos saber si pudo importar su billetera.

Muchas gracias

**Comment by mauropicon** [comment]
hola buenos dias, tengo un problema,
quiero depositar fondos en iq option con mis btc que tengo en copay, no me deja, me tirar error como si estuviera errando el id wallet, . necesito resolver esto gracias
