### ISSUE TITLE
Issue with Copay v3.6.0 on Windows phone

### ISSUE THREAD

**Issue by lionmsmall** [bitpay/copay#6948]
Okay, I am really at wits end with this issue. I sent a payment to Copay on my phone and I was going to send it to my Bitpay card but when I try to scan a QR code, the app crashes. It doesn't tell me anything, it just closes. I can't send payments at all. I tried exporting my wallet and importing it to Electrum but found out that doesn't work. I uninstalled the app, reinstalled it, reset it, nothing works. How do I fix this problem?

**Comment by JDonadio** [comment]
Sorry about your problems, but this seems to be a windows phone error. Please follow https://github.com/bitpay/copay/issues/6461#issuecomment-333837413 to be posted.

**Comment by lionmsmall** [comment]
Any idea on when it will be fixed?

**Comment by JDonadio** [comment]
Depends on windows phone team. check the above link and follow the original issue to be posted
