### ISSUE TITLE
Won't let me send / Wallet Locked

### ISSUE THREAD

**Issue by Glaril** [bitpay/copay#6949]
Hey, sometimes I I get the error I don't have enough funds but I have nearly $2,00 and I can't even send $0.10. And sometimes I get the error my wallet is locked?

**Comment by JDonadio** [comment]
Hi there, in your case your wallet isn't locked, your funds are too small to be used as inputs for a transaction. Please read the next entries to know a little bit about this:

https://github.com/bitpay/copay/wiki/COPAY---FAQ#copay-requires-high-fees-for-low-amounts-transactions
https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-always-get-insufficient-funds-for-fee-when-trying-to-send
https://github.com/bitpay/copay/wiki/COPAY---FAQ#amount-too-low-to-spend

Also there is a really good explanation about the bitcoin network fees:

https://github.com/bitpay/copay/issues/5164#issuecomment-265569494
