### ISSUE TITLE
BTC address translated into BCH

### ISSUE THREAD

**Issue by nirbhaiiy** [bitpay/copay#6952]
BTC address was translated into BCH address. Will I receive my BCH on that translated address without any error?
 I hope the transaction if not confirmed my BCH will be returned back in my wallet. I need help.

**Comment by JDonadio** [comment]
@nirbhaiiy no, the new format for BCH address is: https://support.bitpay.com/hc/en-us/articles/115004671663-BitPay-s-Adopted-Conventions-for-Bitcoin-Cash-Addresses-URIs-and-Payment-Requests

BTC doesn't have anything to do with BCH, you must use BCH addresses. If the format of that BCH address is "old" and looks like a BTC address, then you must translate it.

**Comment by nirbhaiiy** [comment]
But Javier my BCH are sent on that incorrect address. Please help me Copay
Team. Please get my BCH returned back in my wallet.
BTC address was translated into BCH. I have already sent BCH Javier to that
translated address. Please help.

Regards,
Nirbhay A. Chawhan,
Advocate, Nagpur.
9730902824.

On 22 Oct 2017 01:03, "Javier Donadío" <notifications@github.com> wrote:

Closed #6952 <https://github.com/bitpay/copay/issues/6952>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bitpay/copay/issues/6952#event-1304282975>, or mute the
thread

**Comment by nirbhaiiy** [comment]
I have already sent my BCH to that translated address. Please try to understand. BTC address was translated into BCH mistakenly. They ought to be returned back in my wallet because address was not correct.

**Comment by nirbhaiiy** [comment]
There is so much of confusion. Translate the old address and all. In this confusion I translated my BTC address into BCH using BitPay translator. Please help me out getting my BCH back to my copay wallet.

**Comment by nirbhaiiy** [comment]
Entire confusion created by Copay resulted in loss of my all BCH coins. Every exchanger is using BCH address as it is. And are smoothly transacting. But Copay has created no separate option for sending BCH and when BCH are mistakenly sent to BTC address copay team are not taking any responsibility. Support regarding trival issues are given by all. But actually difficult situations you shift your responsibility. Sad.

**Comment by JDonadio** [comment]
Please check this out: https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-sent-bch-coins-into-a-btc-address-what-can-i-do-to-recover-my-bch-coins

**Comment by nirbhaiiy** [comment]
Sorry this is of no use. The recovery process is only showing the balance
funds. Not those funds which are wrongly sent to BTC ADDRESS. Let it be. I
have no more hope from Copay team.

Regards,
Nirbhay A. Chawhan,
Advocate, Nagpur.
9730902824.

On 23 Oct 2017 17:55, "Javier Donadío" <notifications@github.com> wrote:

Please check this out: https://github.com/bitpay/
copay/wiki/COPAY---FAQ#i-sent-bch-coins-into-a-btc-address-
what-can-i-do-to-recover-my-bch-coins

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bitpay/copay/issues/6952#issuecomment-338642124>, or mute
the thread

**Comment by nirbhaiiy** [comment]
See the attachment. And now let it be. You have been in hurry of closing
the ticket. Good bye.

Regards,
Nirbhay A. Chawhan,
Advocate, Nagpur.
9730902824.

**Comment by nirbhaiiy** [comment]
Shame on you BitPay team. It is after l lost my BCH due to you causal and
poor support that you have published a remark in that translator page. See
the attached image. Shameful. You are liable to give back my 1.6 BCH.

Regards,
Nirbhay A. Chawhan,
Advocate, Nagpur.
9730902824.
