### ISSUE TITLE
transaction lost.

### ISSUE THREAD

**Issue by nirbhaiiy** [bitpay/copay#6953]
My BCH are sent on wrong BTC address. But the confirmations are received. How will I get them back because BCH are not received by that address. I want to cancel the transaction.

**Comment by JDonadio** [comment]
The bitcoin transactions could not be cancelled. Check: https://github.com/bitpay/copay/wiki/COPAY---FAQ#can-a-transaction-be-reversed

For your case, please check this: https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-sent-bch-coins-into-a-btc-address-what-can-i-do-to-recover-my-bch-coins

**Comment by nirbhaiiy** [comment]
Shame on you BitPay team. It is after l lost my BCH due to you causal and
poor support that you have published a remark in that translator page. See
the attached image. Shameful. You are liable to give back my 1.6 BCH.

Regards,
Nirbhay A. Chawhan,
Advocate, Nagpur.
9730902824.
