### ISSUE TITLE
can I have more than one BTC wallet set up on Copay?

### ISSUE THREAD

**Issue by nambia** [bitpay/copay#6954]
I already have a BTC wallet on Copay. Separately, I have another BTC wallet which I operate using a different app. I want to setup this wallet in Copay, concurrently with the pre-existing Copay BTC wallet. 

Is this possible?

**Comment by Susankalk** [comment]
I have a btc Wallet for Gopay on my laptop but also a btw Wallet of gopay on my IPhone. I also want to combi these two Wallet to one Wallet with the same adddress and exsisting password. Is this possible ?

**Comment by JDonadio** [comment]
No, is not possible to "merge" or "combine" a wallet.

We do not recommend use an external software and Copay at the same time. For this reason: https://github.com/bitpay/copay/wiki/COPAY---FAQ#different-balance-2-wallet-clients-on-same-wallet-seed

Our recommendation is create a new one in Copay and move all your funds there.
