### ISSUE TITLE
Unable to Verify Payment Card

### ISSUE THREAD

**Issue by mcrae1977** [bitpay/copay#6958]
I am trying to add a card into my buy/sell account.  However whenever i do that and enter the details into the card section, they ask me to check for two transactions made to the card amounting from $1.00 to $1.99.  

When i log onto my banking online statement, they do not reflect even after refreshing multiple times on the same day or even days after. Please advise.

**Comment by BGalliotti** [comment]
Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will happy to help you.
Thanks.
