### ISSUE TITLE
Lost BCH ?

### ISSUE THREAD

**Issue by asdfrer** [bitpay/copay#6973]
Been wanting to sell my BCH so got a BCH address from my chosen exchange which started with 19

I ran this through the translator to get an address beginning with C, typed this address in to Copay (double checked address before hitting send) and swiped to send but no BCH has arrived at the exchange account.  I got an email saying it was sent but when I clicked the link to 'View it on the Blockchain' it said 'transaction not found' - have I done something wrong ?  Is my BCH lost ?

**Comment by matiu** [comment]
Can you share the BCH address? Did you look it on a blockexplorer yourself?

**Comment by rewds** [comment]
Ok turned out I wasn’t being patient enough. It’s arrived at the Exchange now. Thanks

Take away - the Translator tool worked for me
