### ISSUE TITLE
BITCOIN GOLD INSTRUCTIONS

### ISSUE THREAD

**Issue by Teakw00d** [bitpay/copay#6975]
Bitcoin Gold website says that they will be issuing instructions for adding bitcoin Gold to wallets that don't automatically accept BTG....My question....Will COPAY be doing the same...And will those instructions be sent to our email adresses?  OR....What exactly is Copay going to do or not do otherwise?

**Comment by JDonadio** [comment]
Please check this: https://github.com/bitpay/copay/issues/6904
