### ISSUE TITLE
Multiple transactions unconfirmed from 1 day 

### ISSUE THREAD

**Issue by sergiuum** [bitpay/copay#6982]
Hello , i have a quite big problem . 

From yesterday all the payment i try to recive / send are unconfirmed . 

What should i do ? 
Hope this has a resolve .... 

Thanks all ! 

https://i.imgur.com/eYTRjcT.jpg

here are transaction links : 

https://insight.bitpay.com/tx/b1c45fe10052ebca7722b51d648566a958597f5817506b1b80fb89094c6e7dc7
https://insight.bitpay.com/tx/a7e2e9ed3f8440c8b337ef7bf01d2f3ef76ffc403c82188cccf175b6d3df2bee
https://insight.bitpay.com/tx/6a6c466a3a1262d4b737ad7aa492fe7922470d5302ee6f12c9356be7d347ca86
https://insight.bitpay.com/tx/8de16b1f586ae30951893dcd23a895d35e8aabedbbb624e4706e0f481d8dd3d3

**Comment by sergiuum** [comment]
https://insight.bitpay.com/tx/b1c45fe10052ebca7722b51d648566a958597f5817506b1b80fb89094c6e7dc7

https://insight.bitpay.com/tx/a7e2e9ed3f8440c8b337ef7bf01d2f3ef76ffc403c82188cccf175b6d3df2bee

https://insight.bitpay.com/tx/6a6c466a3a1262d4b737ad7aa492fe7922470d5302ee6f12c9356be7d347ca86

https://insight.bitpay.com/tx/8de16b1f586ae30951893dcd23a895d35e8aabedbbb624e4706e0f481d8dd3d3

**Comment by dabura667** [comment]
Wait for them all to confirm. (maybe a day or two)

OR

(Make sure you have "Spend unconfirmed funds" active in the advanced settings of the app)
1. Copy an address from your wallet's receive tab
2. Paste it into the Send tab (send bitcoin to yourself)
3. For amount, tap the top right an tap "Send Max"
4. On the send screen BEFORE confirming, TAP THE FEE
5. Choose "CUSTOM" fee.
6. on a computer or separate app, go to https://core.jochen-hoenicke.de/queue/#2h
7. Look at the 3rd graph, and mouse hover (or tap once on mobile) the far right.
8. You should see a list of numbers which get higher kB as you go lower.
9. Check for the lowest number that has LESS THAN 500 kB
10. Take that number (currently 160) and multiply it by two. (320)
11. Enter that number into your Custom fee (320 in my example)
12. Fee will be much higher.
13. The extra fees on this transaction will help pay for the other low fee transactions you are waiting on.

**Comment by sergiuum** [comment]
If i choose Max amount in forst tab is saying not enought founds for fee ... 

can i do this from another waller or smth like this ?
