### ISSUE TITLE
Re-Send Invitation

### ISSUE THREAD

**Issue by gerbz** [bitpay/copay#6985]
Wallet was setup as 1 of 2. User 2 was sent an invite and was successfully using the wallet for a few months.  Now she had to reformat her phone. How can I re-invite her to the wallet?  I'm on Android and she's on iPhone.

**Comment by JDonadio** [comment]
You cannot "re-invite". Once the wallet was created the invitation code doesn't work anymore. In order to restore your 2nd copayer wallet you must use the backup (12 words or file/text). And import it in the new device.

**Comment by gerbz** [comment]
But if she imports the private key, it's not a multisig wallet anymore correct? It's just one wallet on 2 devices.

**Comment by JDonadio** [comment]
A multi-sig wallet is composed by 2 (or more) "normal" wallets, the only behavior that differs from single wallets it's the broadcast process. 

The import process doesn't change the type of wallet (single or multi-sig).
