### ISSUE TITLE
No history of transaction for bitcoin received!

### ISSUE THREAD

**Issue by rca7891** [bitpay/copay#6987]
The following address was assigned to my personal wallet: 14hrjQy6cQRU1irPDZSebDBYoZmjK7MPDt xpubpub/0/68 2017-10-26T17:27:43.000Z
The address was used to receive bitcoin. The TxID is as follows: b91fb30b901a94fa35bd082bfbacd0e2b34f4759cc0f1eee30e3c4ded7d79f4
Insight.Bitpay shows no record of the transaction, yet blockchain.info and live.blockcypher.com do:
https://blockchain.info/tx/b91fb30b901a94fa35bd082bfbacd0e2b34f4759cc0f1eee30e3c4ded7d79f4a
https://live.blockcypher.com/btc/tx/b91fb30b901a94fa35bd082bfbacd0e2b34f4759cc0f1eee30e3c4ded7d79f4a/
https://blockchain.info/address/14hrjQy6cQRU1irPDZSebDBYoZmjK7MPDt
https://live.blockcypher.com/btc/address/14hrjQy6cQRU1irPDZSebDBYoZmjK7MPDt/
I need the address above to reflect it's true balance so that I can access my funds

**Comment by JDonadio** [comment]
Hi there,

This address: `14hrjQy6cQRU1irPDZSebDBYoZmjK7MPDt` belongs to a Copay/BitPay wallet, but that transaction is not associated to any Copay/BitPay wallets.

**Comment by rca7891** [comment]
yes it is. I even received an email about this transaction

**Comment by rca7891** [comment]
it appeared in my bitpay wallet then just disappeared

**Comment by rca7891** [comment]
Can you at least send me QR code with the private key to that wallet so I
can import into another wallet and funds by scanning the private key

**Comment by JDonadio** [comment]
The transaction remains unconfirmed. You can check this for more info about unconfirmed transactions: https://github.com/bitpay/copay/wiki/COPAY---FAQ#transaction-not-confirmed

**Comment by rca7891** [comment]
regardless, the amount should show as an unconfirmed balance. You are wrong
Sir. Stop brushing off my issue and dismissing at simple or unimportant.
This is serious and it may be subject to happen to anyone and it just might
involve a large sum of money next time. Really take a second to look into
my issue.

**Comment by JDonadio** [comment]
@rca7891 for incoming transaction we have nothing to do, only wait to the confirmations because the tx was created, built and broadcasted from another software.

**Comment by rca7891** [comment]
I fixed the issue myself. You were of no help. I changed the wallet service
url to bws.bitcoin.com/api. then I refreshed the wallet and there was my
balance
