### ISSUE TITLE
BitPay Amazon Gift Card Fraud

### ISSUE THREAD

**Issue by daemawong** [bitpay/copay#6989]
I paid for the Amazon gift card, yet they just took my coin and provided no gift card at all. I went to "My Card," and there's nothing. I asked for help but they just say they are escalating, yet without any resolution nor refund.

**Comment by matiu** [comment]
Hello, We are sorry you are having problems with the Amazon integration. Could you please check the transaction history of your wallet and let us know the details of the payment you did to BitPay so we can issue the card to you manually?

**Comment by daemawong** [comment]
The transaction history says that I spent $250 for the gift card and you never provide me with any. In “Your cards,” there’s no card to redeem.

**Comment by daemawong** [comment]
Please note that you have not issued anything yet.

**Comment by JDonadio** [comment]
What matiu mean is in your transaction detail ($250) copy the transaction (or invoice) id and share it with us so we can check the status and give you a solution

**Comment by daemawong** [comment]
what sort of detail do you want?

**Comment by daemawong** [comment]
https://insight.bitpay.com/tx/325cdbeffc42c6867bcb2d4854d39f43a6b62818dd12beb6f2afda8775312fb1

**Comment by daemawong** [comment]
I've sent 1BfS3BC3rCkdgd1w7G2QwYhXqg7stCrpsS $250 for the Amazon gift card, but I do not have any gift card. WHERE IS THE CARD THAT I CAN REDEEM?

**Comment by daemawong** [comment]
Here the screen capture after the "FAILURE." ![1237](https://user-images.githubusercontent.com/32944021/32139945-6671e300-bc0d-11e7-9be6-f4354f9525c0.png)

Yet BitPay just took my coin without any gift card to redeem.
![1240](https://user-images.githubusercontent.com/32944021/32139954-b4699a94-bc0d-11e7-8f61-43a044582e0f.png)

without any gift card. Here you can see no record or gift card to redeem in "Your cards."
![1241](https://user-images.githubusercontent.com/32944021/32139955-b9778244-bc0d-11e7-8021-6de8fd39b30c.png)

Bottomline, BitPay just took my coin without providing any gift card to redeem. Please fully refund or provide the gift card so that I can redeem. Thanks.

**Comment by JDonadio** [comment]
Thanks for the info provided. I'm forwarding your request.

**Comment by daemawong** [comment]
What's going on here? Why are you still not refunding my money?

**Comment by JDonadio** [comment]
Sorry about the delay, I just re-sent your request. I'll keep you posted

**Comment by JDonadio** [comment]
@daemawong your request was solved. Sorry about the delay.

**Comment by jalalalami** [comment]
@JDonadio i have the same issue how csn we solve it?

**Comment by jalalalami** [comment]
@JDonadio I've sent to 12Bw4Qf6ZpLE3CoTVCmBEhnCBdBQno19mu
An amount of 48.95 USD & i received nothing since December 12th
