### ISSUE TITLE
Menu disappears after sharing wallet address via email

### ISSUE THREAD

**Issue by quinncomendant** [bitpay/copay#6990]
After sharing my wallet address via email, I'm unable to navigate away from the *Receive* screen because the menu at bottom (red arrow indicating where menu should be) has disappeared:

![image1](https://user-images.githubusercontent.com/6884276/32131447-b61e732e-bbcb-11e7-9db5-4fce7423c539.PNG)

I can repeat this issue by these steps:

1. Open Copay
2. Go to the Receive screen
3. Tap the share icon in the top-right
4. Share by email: enter email address, subject, and send.
5. Back on the Receive screen, the menu is now gone.

Only way to restore menu is force-quit Copay and re-launch. It doesn't make a difference if I'm connected to Personal Hotspot or not.

Copay v3.8.6
iOS 10.3.3

I saved my session logs, if someone wants I can share privately.

**Comment by JDonadio** [comment]
Hi @quinncomendant, this is a known issue with Ionic v1. We are working to migrate to a new version which will fix a couple of UI bugs that unfortunately we are having now. Sorry about that.

**Comment by Berndinox** [comment]
Same like #6847

**Comment by JDonadio** [comment]
Thanks @Berndinox !
