### ISSUE TITLE
Bitcoin Address Error

### ISSUE THREAD

**Issue by PoisonXS** [bitpay/copay#6996]
Hi there,
I had a bitcoin address in which I used for selly.gg
However I accidentally generated a new address.
The transaction was successful but the payment does not show in my address.

Can you fix this please?
I can show you all the proof of the transaction.

**Comment by JDonadio** [comment]
Hi, I cannot understand you... if you generate a new address, the payment was sent to that new address so you will not see it in your previous address. Can you explain a little more your issue ?

**Comment by JDonadio** [comment]
Closed in favor of https://github.com/bitpay/copay/issues/6997

**Comment by PoisonXS** [comment]
this one was a mistake sorry.
This is what I meant:
I had someone purchase a product using bitcoin. The transaction details said it was successful but when I looked in copay it didn't show anything.
