### ISSUE TITLE
Build error "ParseError: Unexpected token" on mac

### ISSUE THREAD

**Issue by xiawu** [bitpay/copay#7001]
i build copay 3.8.6 on mac, find the following error:

```
Running "browserify:dist" (browserify) task
>> /Users/xx/source/copay/www/index.html:1
>> <!doctype html>
>> ^
>> ParseError: Unexpected token
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.
npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! copay@3.8.6 build:www: `grunt`
npm ERR! Exit status 6
npm ERR! 
npm ERR! Failed at the copay@3.8.6 build:www script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

@kleetus @saschad @ryanxcharles @colkito

**Comment by guerrerocarlos** [comment]
isolated the bug, execute:
`browserify angular-bitcore-wallet-client/index.js`

**Comment by xiawu** [comment]
@guerrerocarlos i execute the command you mentioned, get the following error
`
$ ./node_modules/.bin/browserify angular-bitcore-wallet-client/index.js 

/Users/xx/copay-3.8.2/www/index.html:1
<!doctype html>
^
ParseError: Unexpected token
`

**Comment by guerrerocarlos** [comment]
Exactly, meaning that the problem is caused by **angular-bitcore-wallet-client/index.js**

**Comment by xiawu** [comment]
@guerrerocarlos How to fix it? i have tried the copay releases including 3.7.3, 3.8.2, every release have encountered the problem.
My step is the following:

> wget https://github.com/bitpay/copay/archive/3.7.3.tar.gz
> tar xvfz 3.7.3.tar.gz
> cd copay-3.7.3
> npm run apply:copay
> npm start

**Comment by guerrerocarlos** [comment]
Yes, I believe it doesn't matter the release, because the *angular-bitcore-wallet-client* module is installed by npm in the latest version anyway, and the bug must be in that module, not in copay code itself.

**Comment by guerrerocarlos** [comment]
Found the problem,

Inside module **asn1.js-rfc5280** there is a **require('../..');** that browserify doesn't understand correctly.

Comment as follows:

```
// try {
  var asn1 = require('asn1.js');
// } catch (e) {
  // var asn1 = require('../..');
// }
```

**Comment by matiu** [comment]
I renamed the ticket, removed "Critical Error".

**Comment by xelawafsTemp** [comment]
@guerrerocarlos I'm still experiencing the same issue with the latest copay build 3.8.2

**Comment by simonsmartza** [comment]
For now the fix is to just edit the first 4 lines in:
copay/node_modules/asn1.js-rfc3280/index.js
and
copay/node_modules/asn1.js-rfc5280/index.js
like above, and run again

**Comment by xelawafsTemp** [comment]
I'm getting a blank page on `npm start`

1. `npm run apply:copay`
2. edit `copay/node_modules/asn1.js-rfc5280/index.js` as mentioned above
3. `npm start`

Output on terminal:
`[WARN] Error with ./www/lib/ionic/version.json file: FILE_NOT_FOUND, trying ./bower.json.`

Output on browser console:
```
Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.  angular-components.js:84449:11
Copay v3.9.0 #52bc711  ionic.bundle.min.js:150:8
Client: {"isAndroid":false,"isIOS":false,"isWP":false,"isSafari":false,"ua":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:56.0) Gecko/20100101 Firefox/56.0","isCordova":false,"isMobile":false,"isDevel":true,"supportsTrezor":true,"versionIntelTEE":"","supportsIntelTEE":false}  ionic.bundle.min.js:150:8
Error: [$injector:unpr] http://errors.angularjs.org/1.5.3/$injector/unpr?p0=bwcServiceProvider%20%3C-%20bwcService%20%3C-%20sjcl%20%3C-%20storageService%20%3C-%20configService%20%3C-%20fingerprintService  ionic.bundle.min.js:40:416
```

**Comment by simonsmartza** [comment]
You can fix the bitcore error by installing an older version before it was broken:
npm -g install bitcore@4.1.0 (see: https://github.com/bitpay/bitcore/commit/ad4e25ef1b562163c398518079e796f9f704afe6)
However I also still get the blank page

**Comment by sagar-ga** [comment]
Hi @xelawafsTemp, I'm getting the same error. Did you find any solution ?

**Comment by lclc** [comment]
What worked for me:

vim node_modules/asn1.js-rfc5280/index.js
Change:
```
  // var asn1 = require('../..');
  var asn1 = require('../' + '..');
```


@xelawafsTemp: The problem you mention seems to be unrelated to this issue (I had it much earlier already, before this one). I fix it by simply deleting the additional bitcore-lib instances:

```
find . -type d -name "bitcore-lib"
rm -rf ./node_modules/bitcore-mnemonic/node_modules/bitcore-lib ./node_modules/bitcore-payment-protocol/node_modules/bitcore-lib
```

I saw no negative side-effects so far...

**Comment by xelawafsTemp** [comment]
I just cloned the latest repo and these changes have been made. Copay builds without any errors right now. @lclc thanks for the info.

@sagar-ga try out the latest build, hope it works out for you.

**Comment by sagar-ga** [comment]
@xelawafsTemp, it worked for me too. Thanks for pointing it out.
@lclc, i did't try your solution but seems like it could've worked for me. Thanks guys for your input.
