### ISSUE TITLE
Bitcoin cash from my copay wallet to my ledger nano s: problem

### ISSUE THREAD

**Issue by jmettes81** [bitpay/copay#7002]
Hello,

I want to send my bitcoin cash (0.999975) from my Copay wallet to my ledger nano s (bitcoin cash platform).
I follow all the steps: first i click on "send". By recipient i give in my ledger nano s bitcoin cashadres. I click on the 3 ... and sellect "send max amount". Than i gat the confirmationscreen, but than it will get no further. On that screen there are the words "sending" and "to", but i can"t click on this words, or type something. The confirmationscreen stays all the time. There's also no confirmation button.

Hopefully someone can help me.

Gr,

J

**Comment by JDonadio** [comment]
Both Copay as the Recovery tool accepts BCH addresses starting with C or H, which is a new convention to prevent errors (https://support.bitpay.com/hc/en-us/articles/115004671663-BitPay-s-Adopted-Conventions-for-Bitcoin-Cash-Addresses-URIs-and-Payment-Requests)

If you need to send to "old" addresses, and you are SURE those are BCH addresses, you can "translate" them using the BCH Translator tool: https://bitpay.github.io/address-translator/

**Comment by fortran77** [comment]
It would be very convenient if something like the following could be done:

- On screens on which a Bitcoin Cash address is in use, Copay includes a button to visit the BCH Translator tool.* 
- The translated address and its QR code are already on the BCH Translator tool page that is reached.*

----

*Similar to how in other places in Copay a button is used to visit insight.bitpay.com, and a relevant address is fed by including it in the URL, and results are automatically available on the destination page.

**Comment by Roogle24** [comment]
Same issue.  Although I converted the address to one starting with C, I still am unable to get Copay to send my BCH. I click send on Copay, enter the recipient (Nano S) address and then nothing.  Copay only has "transfer to wallet” showing but nothing to click or activate.  What am I missing?

**Comment by fortran77** [comment]
This appears to be an intermittent issue. I have observed similar behavior in the Coinomi app for Google Chrome when trying to send BTC. I think the app is trying to look something up (maybe the exchange rate, maybe a fee estimate, etc.) and hanging. If you wait long enough it may work. Otherwise going back to the previous screen and retrying usually works.

**Comment by Roogle24** [comment]
I tried again and it worked.
It took about 12 different attempts which isn’t efficient since I have to translate address. Unlikely to use this again. 

Regards,
Rob

**Comment by qtrf417** [comment]
How Can I copy the translated old address to receive bcc???

**Comment by JDonadio** [comment]
Use: https://bitpay.github.io/address-translator/
Or use the prefix: `bitcoincash:`xxxxx
