### ISSUE TITLE
Invalid BCH addresses

### ISSUE THREAD

**Issue by dmaybris** [bitpay/copay#7003]
I cannot send my BCH to my wallet because I am told the addresses are invalid. No problem with BTC only BCH. Have tried generating new addresses but still the same. Can you help?

**Comment by gabrielbazan7** [comment]
Hi ! take a look at this https://github.com/bitpay/copay/wiki/COPAY---FAQ#sending-bch-shows-error-please-enter-a-valid-address

> If you need to send to "old" addresses, and you are SURE those are BCH addresses, you can "translate" them using the BCH Translator tool: https://bitpay.github.io/address-translator/

**Comment by mpumzi** [comment]
Can i translate using mobile?

**Comment by mpumzi** [comment]
I wanted to bring my bch coins from luno but now my wallet of bch are interpreted as invalid

**Comment by gabrielbazan7** [comment]
Yes. Copy you Copay Wallet address and paste it on the tool. Then use that address as recipient for your transaction.

**Comment by mpumzi** [comment]
Please provide me with the tool is it available for mobile?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gabrielbazan7** [comment]
You could also write this on the recipient field `bitcoincash:destination_address`. 
for example : 

<img width="400" alt="bitpay_-_secure_bitcoin_wallet" src="https://user-images.githubusercontent.com/10999037/32188864-c00b04a2-bd87-11e7-8b6c-2ab6a04f4019.png">

so the address translation is done directly from the app.

**Comment by dmaybris** [comment]
That worked.
Thanks gabrielbazan7
