### ISSUE TITLE
Coinbase and copay two step verification required

### ISSUE THREAD

**Issue by sasscole321** [bitpay/copay#7005]
Hello I just performed 2 transactions by clicking on coinbase in the Copay app. It looks like it's purchase d in coinbase but not transferred to my copay wallet. The error reads "Two step verification required to complete this request. Re-play the request with CB-2FA-Token header."

**Comment by cmgustavo** [comment]
Could you confirm if you have the latest version of Copay (v3.6.8)? When have you linked your Coinbase account? We need to know these details to assist you further.

BTW, If you are planning to buy again, try to "Log out" from Coinbase in the app: "Settings" -> "Integrations" -> "Coinbase" -> "Log out". Then, re-connect your Coinbase Account again. It will force to use the 2FA Token. 

Your previous purchases can't sent automatically. You should do it manually from Coinbase website.

Thanks.
