### ISSUE TITLE
Ayuda

### ISSUE THREAD

**Issue by FreeCashYG** [bitpay/copay#7006]
I have a problem on having unloaded the program to have my BITCOIN's purse, the problem is that my PC says that on having installed the program I have a mistake... And not since this one arrange problem please help me
![asasasasasas](https://user-images.githubusercontent.com/33043726/32188339-e7c8b138-bd7d-11e7-8ae0-18f9849deb45.png)

**Comment by JDonadio** [comment]
The reason is: Copay and BitPay wallets are not designed to run in 32 bits platforms but only 64 bits.
