### ISSUE TITLE
Unconfirmed transaction received disappears in Copay and senders did not get bitcoins back

### ISSUE THREAD

**Issue by awilliam235** [bitpay/copay#7008]
A transaction received was pending (unconfirmed) in my copay wallet because of unsufficient fees, and than suddenly disappeard from my wallet whilst the sender did not receive the bitcoin back yet. The blockchain states 'unconfirmed transaction', but where are the bitcoins now. Not in any wallet!!!!

**Comment by gabrielbazan7** [comment]
Could you share the transaction id ?

**Comment by awilliam235** [comment]
Hello,

58ff57f38b07010bf9591988507c0c98074c2cbd600e4448e71c7c193503f8c2

Thanks!

2017-10-31 0:54 GMT+01:00 Gabriel Edgardo Bazán <notifications@github.com>:

**Comment by dabura667** [comment]
The transaction will take a few days, and the reason it was dropped by insight and Copay is because the transaction is version 2.

Please do not give the sender any cash or product until the transaction is confirmed in the blockchain.

**Comment by awilliam235** [comment]
Thanks for your reply.

version 2?

Do you mean the sender resent the transaction?



2017-10-31 1:48 GMT+01:00 Dabura667 <notifications@github.com>:

**Comment by dabura667** [comment]
No. That’s not what version 2 means.

**Comment by Roddy1219** [comment]
@awilliam235  Tx fee is too low !!!   I can use Transaction Accelerator
complete this tx,   only  send to me  0.001 BTC, OK?

**Comment by awilliam235** [comment]
Hello,

Why is the transaction version 2? The sender uses the latest version of
bitcoin core 0.15.01.

Thanks.

2017-10-31 6:01 GMT+01:00 Dabura667 <notifications@github.com>:

**Comment by awilliam235** [comment]
Hello again,

The transaction is still stuck in the verification process...

Tried all solutions like -zapwallettxs and mempool deletion with
-walletbroadcast. With the latter I could 'abandon transaction' because
this option wasn't greyed out anymore, but a few moments later the status
was '?' again and the options 'abandon transaction' and 'increase fee' were
greyed out again.

What next?

Thanks


2017-10-31 12:30 GMT+01:00 Albert William <awilliam235@gmail.com>:

**Comment by JDonadio** [comment]
We cannot do anything for incoming transactions which are waiting for confirmation. You must contact to the sender and ask him about your transaction.
