### ISSUE TITLE
Accidentally sent bth cash to btc account. 

### ISSUE THREAD

**Issue by shawnsetia** [bitpay/copay#7010]
It was from my coinami account to my copay account. 
The transaction id is: 9403f58f23df92dc050763198a1503a9622de788d7b18d30bce776645f6b4e0f

Sent from thi address at coinami:

**Comment by shawnsetia** [comment]
Coinami address was from: 1J9DaMwLtuFTbXoGZ68RZpX94ZFpuGhk7w

Copay that received at: 1MfHNxPu979U9yA6yaNrdfCQu3Ux88j6en

**Comment by matiu** [comment]
Hello, You just need to create a new BCH wallet, using the backup (the 12 words) from the BTC wallet, and you will have access to the BCH.

**Comment by JDonadio** [comment]
Check this out: https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-sent-bch-coins-into-a-btc-address-what-can-i-do-to-recover-my-bch-coins
