### ISSUE TITLE
33€ btc

### ISSUE THREAD

**Issue by drago23456** [bitpay/copay#7012]
Look you said that i had my last transaction 9 days ago but i go a email yesterday so wtf man get your shit together and give me my 33€

**Comment by drago23456** [comment]
![screenshot_20171031-143319](https://user-images.githubusercontent.com/33255577/32226306-8586273c-be48-11e7-8fbd-919b64931390.png)

**Comment by drago23456** [comment]
Wallet id d8746da0-9bb0-4d10-bc8b-e5e880263e5d

**Comment by JDonadio** [comment]
You can continue posting in your original ticket (https://github.com/bitpay/copay/issues/7011), not need to create a new one.
