### ISSUE TITLE
Segwit2x

### ISSUE THREAD

**Issue by cmarco84** [bitpay/copay#7015]
Hi,
please could you tell me if the copay wallet support BTC segwit2x?

Thank's,
Marco

**Comment by kirksu** [comment]
To elaborate on the question: 
I have a copay 3 of 6 wallet with BTC in it.  After the hard fork that creates B2X (Segwit2X)  later this month, Will I be able to access the B2X from this wallet?  If the answer is yes, how can I access it?
When the hard fork a few months ago created BCC (BitcoinCash), I was unable to access the BCC from my copay 3 of 6 wallet because one of the 6 seeds had been lost.  I want to avoid a similar situation after the Segwit2x fork.

**Comment by matiu** [comment]
@kirksu you dont need all the seeds to access BCH, just upgrade Copay and enable BCH support, you can create a BCH wallet based on one of current BTC wallet you have on Copay.

**Comment by matiu** [comment]
Regarding Segwit2X, please refer to:
https://blog.bitpay.com/segwit2x-and-bitpay/

**Comment by kirksu** [comment]
Dear Matias,
Thank you so much for this very welcome news.  I'll let you know if I have
any problem, but if all goes well I won't write back.  Thanks again.
Best,
Kirk Ulbricht
Free Ross

**Comment by kirksu** [comment]
Hi Marias,
I was able to recover the BTH from my 3 of 6 capay wallet, but not before
using this work around:

https://github.com/bitpay/copay/issues/6797
<https://mailtrack.io/trace/link/bc0f213f7a796eaae32b1aa75f3659553ede7a76?url=https%3A%2F%2Fgithub.com%2Fbitpay%2Fcopay%2Fissues%2F6797&userId=1904977&signature=4737efe42e7919d6>

meinharrd commented on Sep 27
Issue

BCH balance remains 0.00 after wallet duplication from BTC. A manual
address scan corrects the balance, but it's hard to figure out even for an
advanced user that this step is needed. This feels like a bug.

Reproduce

Go to "Settings" > "Enable Support Bitcoin Cash" > Switch on "Support
Bitcoin Cash"
Press "Scan your wallets for Bitcoin Cash"
Press "Duplicate for BCH" on the wallet that should contain BCH
New wallet created by duplication will display 0.00 balance, even if the
wallet contains pre-1-August BCH
Work-around / fix

Go to "Settings" > "Wallets & Integrations" and select newly created BCH
wallet
Select "More Options" > "Wallet Addresses" > "Scan addresses for funds"
Scanning completes, correct balance will be displayed (phew!) 😅
Suggested solution

Automatically initiate an address scan after "Duplicate for BCH" is pressed
Environment

Tested on v3.8.2 iOS and Windows

Thank you again,
Kirk

**Comment by sushilraghav** [comment]
@cmarco84 @kirksu @matiu @kleetus @saschad    For 500$, Can you hard-fork of bitcoin at block height of 500888 ,used the BCH reference ,total coins 21210000,and 210000 is pre-mine @saleemrashid  

my email is bitcoinemxmx@gmail.com and skype : sushilraghav
