### ISSUE TITLE
Btc

### ISSUE THREAD

**Issue by drago23456** [bitpay/copay#7018]
Hello i made already 2 tickets but i couldent find them so i have 39.00 $ dollar in my wallet but i csnt use them and second why  was my btc wallet completly empty and you from  copay said that i have nothing on my wallet but now is my money back but icant use it please help me .
![screenshot_20171031-213657](https://user-images.githubusercontent.com/33255577/32247755-a536027e-be83-11e7-8342-ceb3d32c2b37.png)

**Comment by JDonadio** [comment]
If you tap on that button a detailed view will be shown. You have 2 transactions pending and your balance is locked. Check our [wiki](https://github.com/bitpay/copay/wiki/COPAY---FAQ) section to know about how the bitcoin transactions works and why your balance is lock.

**Comment by drago23456** [comment]
Ok but how long will it be locked and why was my wallet for a few hours completly empty ? Thank you and sry for my previous ticket

**Comment by JDonadio** [comment]
Your transactions will be waiting to be confirmed or (in the worst case) dropped from the mempool. Your wallet shows 0 as balance because your funds was locked.

**Comment by JDonadio** [comment]
In the wiki section you can find detailed info about your questions.
