### ISSUE TITLE
More than one instance of bitcore-lib found

### ISSUE THREAD

**Issue by guerrerocarlos** [bitpay/copay#7019]
![screen shot 2017-10-31 at 9 26 20 pm](https://user-images.githubusercontent.com/82532/32248141-5f56ce00-be8d-11e7-8517-40400e1e053f.png)

Temporary solution:
Clone https://github.com/bitpay/bitcore-wallet-client checkout tag v5.3.0 and set static versions in it's **package.json** file:
    "bitcore-lib": "0.14.0",
    "bitcore-mnemonic": "1.2.2",
    "bitcore-payment-protocol": "1.2.2",

So that it doesn't use newer releases that use different bitcore-lib versions between them.

After these changes, inside local bitcore-wallet-client repository folder execute 
`npm link`

Then, execute inside copay repo, execute:
`npm run apply:copay`
`rm -rf node_modules/bitcore-wallet-client`
`npm link bitcore-wallet-client`
and the rest of the normal commands like:
`npm start`
`grunt`
`make`
etc

**Comment by rickygu** [comment]
I'm having this problem. What's a more permanent solution?

**Comment by gabrielbazan7** [comment]
I think this issue is solved in the most recent version of the app. I will close this issue. Reopen if it's necessary.
