### ISSUE TITLE
If I delete my wallet can I recover it?

### ISSUE THREAD

**Issue by mkaand** [bitpay/copay#7028]
Hello,
I like copay. I believe this is the best soft and open source wallet. I use copay on my laptop ipad and iphone. If I delete a wallet on three of them can I recover it? (I have 12 words + private key)

**Comment by JDonadio** [comment]
Sure, the delete process just remove the access from the device used but you can always import it using your backups. Ensure to backup all your wallets before delete them.

**Comment by mkaand** [comment]
Thank you :) Just warnings are scary that's why I ask you.

**Comment by JDonadio** [comment]
Glad to help
