### ISSUE TITLE
Can't buy bitcoin cash because the address in Copay begins with 'C'. Not accepted!

### ISSUE THREAD

**Issue by awilliam235** [bitpay/copay#7029]

**Comment by JDonadio** [comment]
Use the [address translator](https://bitpay.github.io/address-translator/)

**Comment by awilliam235** [comment]
Hello,

If I use the address translator it gives a Bitcoin address that already is
being used for receiving BTC/bitcoin.

Should I better just use a new BTC address than, in stead of a BTH address
that being translated into an 'old' BTC address?

Thanks



2017-11-02 12:34 GMT+01:00 Javier Donadío <notifications@github.com>:

**Comment by JDonadio** [comment]
The address translator is not for BTC addresses, only for BCH addresses. You can receive as many payment as you wish in one or more addresses. Just for private (and also security) reasons we generate a new one for each received transaction.

Check this out: https://github.com/bitpay/copay/wiki/COPAY---FAQ#why-my-address-keeps-changing
