### ISSUE TITLE
Bitcoin Cash mistakenly transferred to the upgraded Copay BTC wallet

### ISSUE THREAD

**Issue by Amansoni97** [bitpay/copay#7030]
I wanted to transfer my BCC to some other wallet but it got transferred to my Copay wallet. When I searched for BCC in copay, it said that the same is not eligible to support BCC.

How do I then recover my BCC?

**Comment by JDonadio** [comment]
Scan your BTC wallet using the [recovery tool](https://bitpay.github.io/copay-recovery/) selecting `bch/livenet` as chain.

Check this out: https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-sent-bch-coins-into-a-btc-address-what-can-i-do-to-recover-my-bch-coins
