### ISSUE TITLE
无法发送bch

### ISSUE THREAD

**Issue by Hansizhan** [bitpay/copay#7032]
你好，我无法发送bch到别的钱包
如何用转换器转换旧地址，我试过可是没有转换键

**Comment by JDonadio** [comment]
https://github.com/bitpay/copay/issues/7003#issuecomment-340542357

Or 

https://bitpay.github.io/address-translator/

**Comment by Hansizhan** [comment]
我试过，可是没有改变，怎么操作？

**Comment by Hansizhan** [comment]
iphone手机浏览器能够打开吗？

**Comment by JDonadio** [comment]
The translator tool is working well. Use it filling the original address field with your "old" address and it will be translate into a new format.

For example, this is a BCH address (old format): `1JgxthjKF96oa8e5W7HUFYwQ4Wt1cA4RiA`
Translated as: `Ca9rTk5P8C5LUGYWBrcPq4ZRge6RR1kfRu`

**Comment by Hansizhan** [comment]
Safari no working ?

**Comment by JDonadio** [comment]
It's working on safari as well
