### ISSUE TITLE
Pending activity shows nothing after placing order for btc

### ISSUE THREAD

**Issue by avKeHe** [bitpay/copay#7036]
I had placed order for BTC via coinbase integration a couple of days ago. The purchase status went to pending right away. 
Today,  I see the coinbase activity tile, but nothing shows up there. I don't see any of the purchased btc anywhere in the copay wallet either. What happened to my purchased btc?

**Comment by cmgustavo** [comment]
Are your BTC available/confirmed on Coinbase.com website? Could you provide screenshots or more details of the Coinbase Integration View (go to Home->Coinbase)?

Thanks.
