### ISSUE TITLE
Does Copay store my private key online?

### ISSUE THREAD

**Issue by RichardJECooke** [bitpay/copay#7038]
Hi, support question: does Copay keep my private key / pass phrase on a server where it could be stolen, or is it only on my local machine running the Copay app?

**Comment by JDonadio** [comment]
No, Copay doesn't store any keys or passwords in the cloud or server but in the device used. It's marked in the `readme` as main feature:

> Device-based security: all private keys are stored locally, not in the cloud

Also it's mentioned during the onboarding process (for fresh installs)
