### ISSUE TITLE
Bittcoin kommen nicht an

### ISSUE THREAD

**Issue by colamucke** [bitpay/copay#7041]
Ich bekomme keine Bitcoin kommen nicht an obwohl Bit4Coin vor drei Stunden transferiert hat

**Comment by JDonadio** [comment]
Please explain your issue in detail so we can assist you better.

**Comment by colamucke** [comment]
Ich bekomme keine bitcoin, obwohl vor drei Stunden bit4coin es schon transferiert hat.

**Comment by colamucke** [comment]
Es kommt von bit4coin

**Comment by JDonadio** [comment]
For incoming transaction please contact to the sender

**Comment by colamucke** [comment]
Wallet Adresse stimmt alles, wurde auf diese transferiert, aber mein wallet Konto zeigt seit 4 Stunden 0 Euro an.
