### ISSUE TITLE
I have a 28$ transaction flagged as a "too low to spend" in my bitpay wallet, it already has over 6 confirmations is there anithing i can do to reclaim my money?

### ISSUE THREAD

**Issue by Enriquetnt** [bitpay/copay#7042]
i received a small 0.0037BTC (20$) at the time, deposit to my bitpay wallet, and it got flagged to low to spend, now is nearly 30$ and STILL is flagged, is there any way to unlock them? even if it means paying the "fee" they claim 28$ might not cover, (ludicrous BTW)
txid: c1d9d501daffdd51dbd4245fc7c8d5de4cc87c9b04e9cfe6635f38fa705e9283

**Comment by JDonadio** [comment]
Please check this out: https://github.com/bitpay/copay/wiki/COPAY---FAQ#amount-too-low-to-spend

Also remember you can use the custom fee to set an appropriate amount for you.
