### ISSUE TITLE
Fraud by Copay

### ISSUE THREAD

**Issue by nirbhaiiy** [bitpay/copay#7049]
The address which l obtained from the translator 
given by copay team was not valid. Kindly check https://blockchair.com/search?q=HCsd4k9EhabArheP9vZBiVieg6r4NJasLd  
My BCH were easily sent from my copay wallet. There has been serious mismanagement and fraud kind of support and guidance given by the Copay team while I was asked to use the BitPay translator.
Copay team is responsible for loss of my 1.6 BCH.
A serious damage caused because of Copay team in handling the issue. Copay is liable to bring back my BCH from that address. 
See the link below.
https://bitinfocharts.com/bitcoin%20cash/address/17MVgQDiJN489N4vB9ESKUqBVvYKvFwiBx

**Comment by monsterbitar** [comment]
If you translated a non-copay BCH address to a copay BCH address, and sent BCH to that address, then it should have sent properly and only be spendable by the recipient, but their wallet might not understand the BCH address and won't see the fund.

In that case, the reciever could export their seed and import it into copay to be able to see the copay BCH address, and the funds. They can't send them to a non copay BCH address from there though, unless copay fixes that issue.
