### ISSUE TITLE
cant send BTC from my wallet

### ISSUE THREAD

**Issue by OffaRex** [bitpay/copay#7050]
hey i have 14.5 $ BTC in my wallet cant spend it or send it to my main wallet

**Comment by JDonadio** [comment]
Hi @OffaRex can you explain your issue? Also if you can attach some screenshot would be great.

**Comment by OffaRex** [comment]
I have 0.002012 Btc 14.50 $ I tried to send 10.8$ and got this message “error .. incuffient funds”

**Comment by OffaRex** [comment]
I have 0.002012 Btc 14.50 $ I tried to send 10.8$ and got this message “error .. incuffient funds”

**Comment by OffaRex** [comment]
![d3dc79b3-83f4-466b-8ad9-1b370f4dd9b9](https://user-images.githubusercontent.com/33370375/32425057-80e25692-c2c1-11e7-9a2c-e2875048f65b.png)

**Comment by JDonadio** [comment]
https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-always-get-insufficient-funds-for-fee-when-trying-to-send
