### ISSUE TITLE
Transered money from wallet to a site but the money never showed up.

### ISSUE THREAD

**Issue by Jthomas79** [bitpay/copay#7051]
72$usd was sent to a website from my copay wallet . It was never confirmed but the money never showed up. Now the cash is MIA. Help !
![img_2870](https://user-images.githubusercontent.com/28742515/32412420-53f86dee-c1c5-11e7-80b9-7b395c9f33bc.PNG)
![img_2871](https://user-images.githubusercontent.com/28742515/32412421-54022cf8-c1c5-11e7-88f3-2a1518066bb9.PNG)
![img_2872](https://user-images.githubusercontent.com/28742515/32412422-540b8172-c1c5-11e7-95c2-f6df601ef1f7.PNG)

**Comment by JDonadio** [comment]
Please copy and paste the transaction id here

**Comment by Jthomas79** [comment]
What good will that do ? Do you represent copay ? 

Joshua Johnson
Jthomas79@aol.com

**Comment by JDonadio** [comment]
The transactions are public, you can check and trace them in all of block explorers. Yes, I'm part of Copay staff.

**Comment by Jthomas79** [comment]
31cbb6824631a96f307c7e484c0cbd56799803553b631029590774fb7c02c3cd

Joshua Johnson
Jthomas79@aol.com

**Comment by JDonadio** [comment]
Your transactions seems to be ok and was already confirmed. There is not issues in Copay for your case. 

If for some reason these funds are not showed up in the destination site, you must contact to their support and provide that transactions as a proof.

**Comment by JovialGrace** [comment]
If it is an unconfirmed transaction, I had the same problem.
Did you send enough fee?
You may need to send/spend/move the entire balance to another wallet with a high fee.
This forces a child pays for parent tx.  
Good luck

**Comment by Jthomas79** [comment]
Much appreciated , it was confirmed but the funds never showed up once it left my wallet . Confusing 🤦🏼‍♂️

Joshua Johnson
Jthomas79@aol.com
