### ISSUE TITLE
BCH not arrived

### ISSUE THREAD

**Issue by docreygaerts** [bitpay/copay#7052]
Hi. I send BCH at the adress of the paperwallet created from Cashadress : 16hyGkaEeGBGGxUbyikn87ec8J6roVy5E7 and it never arrived but wel on a adress onknown from me CNArqnvJXK9oB6P2fU5hhdGdkRKGieesDM. What happens?

**Comment by JDonadio** [comment]
Please copy and paste the transaction id here

**Comment by JDonadio** [comment]
https://blockchair.com/bitcoin-cash/transaction/244271685
https://blockchair.com/search?q=16hyGkaEeGBGGxUbyikn87ec8J6roVy5E7

**Comment by docreygaerts** [comment]
Sorry but it means that blockchair is right while https://bch-insight.bitpay.com/ is wrong?
Insight<https://bch-insight.bitpay.com/>
Bitcoin Insight. View detailed information on all bitcoin transactions and blocks.
bch-insight.bitpay.com

×

Roland Reygaerts
44, rue Alphonse et Maurice Hellinckx
1083 Ganshoren (Bruxelles)
Tel: +32.2.4255344 et +32.478.565151
dr.reygaerts@hotmail.com
________________________________
De : Javier Donadío <notifications@github.com>
Envoyé : lundi 13 novembre 2017 21:19
À : bitpay/copay
Cc : Roland Reygaerts; Author
Objet : Re: [bitpay/copay] BCH not arrived (#7052)


https://blockchair.com/bitcoin-cash/transaction/244271685
https://blockchair.com/search?q=16hyGkaEeGBGGxUbyikn87ec8J6roVy5E7
