### ISSUE TITLE
my coins become zero in my wallet ... as suddenly the wallet adress changes itself and i lost my 1191 coins please help me out ASAP

### ISSUE THREAD

**Issue by CRYPTOMINER22** [bitpay/copay#7054]
my coins become zero in my wallet ... as suddenly the wallet adress changes itself and i lost my 1191 coins please help me out ASAP

**Comment by JDonadio** [comment]
Please check our wiki section first: https://github.com/bitpay/copay/wiki/COPAY---FAQ

**Comment by CRYPTOMINER22** [comment]
i have checked but not able to understand how can i get my coins back to my wallet

**Comment by CRYPTOMINER22** [comment]
JDonadio please help me out

**Comment by JDonadio** [comment]
Go to settings > wallet > more opts > wallet information. Copy and paste your wallet id so I can check your wallet status.
