### ISSUE TITLE
BITCOIN GOLD

### ISSUE THREAD

**Issue by berkinnn** [bitpay/copay#7055]
After hard fork,will you be able to give btc gold in our copay accounts or do we need to do anything to receive btc gold from you?

**Comment by JDonadio** [comment]
There are many entries for this question: https://github.com/bitpay/copay/issues/6904

**Comment by JDonadio** [comment]
We'll not support BTG for now. But using your seed you can claim them in another wallet software.

**Comment by lukeinfinger** [comment]
How can we claim them in another wallet?
