### ISSUE TITLE
Miltisignature problem

### ISSUE THREAD

**Issue by Sakuro396** [bitpay/copay#7056]
I’m using 2 of 3 multi-signature.
I lost cellphone the other day,,, I recovered one of these but  I can’t recovered others cause didnt save secret key.

I recovered wallet, but I can’t send bitcoin cause its multi signature.
Are there any ways to cancel malti signature wallet ?

**Comment by JDonadio** [comment]
Do you have 2 available wallets or just one?

**Comment by Sakuro396** [comment]
Just one,,,😢😢

**Comment by JDonadio** [comment]
You need at least 2 backups available, otherwise and unfortunately you cannot access to the funds.
