### ISSUE TITLE
Amazon asking for details about gift card

### ISSUE THREAD

**Issue by OffaRex** [bitpay/copay#7057]
"If you did not buy the gift card, we request you to get in touch with the original purchaser to provide the gift card receipt."

These was the words from Amazon's mail asking for detail as how can I get this data

**Comment by JDonadio** [comment]
Please create an issue here: https://help.bitpay.com/requestHelp

**Comment by OffaRex** [comment]
thanks, JD but there isn't a specific choice for Amazon gift cards issues in this page

**Comment by JDonadio** [comment]
Yes, sorry. Just put Bitcoin Payment / Transaction

**Comment by JDonadio** [comment]
Please, specify all the relevant details and also provide the transaction id for the AGC purchase.
