### ISSUE TITLE
I’m annoyed about these different wallets in my personal wallet

### ISSUE THREAD

**Issue by tgibbs006** [bitpay/copay#7058]
You guys call it my personal wallet but the fact you use different addresses for receipt every time is not so clear. So now I’ve got like $20 worth of BTC between all these damn wallets that basically is going to disappear. I thought I was leaving a little bit in my personal wallet every time so it would build up a little bit every time, and now its just going to be eaten up by 80% fees. Yes, I’m new to this, but I’m not stupid, so I know this shit has happened before. How can I get this money together back in my “personal Wallet” without you guys stealing all of its in fees?????

**Comment by dabura667** [comment]
1. The wallet doesn’t take the fees. The Bitcoin miners do.
2. You pay the same fees using one address as you do using multiple addresses. Fees depend on the number of UTXOs in the wallet, not addresses.

**Comment by tgibbs006** [comment]
What is a UTXO? And why would it cost me 80% to send bitcoin from 15 different wallet addresses, and I can send it with my other wallet blockchain for $1.99??

**Comment by JDonadio** [comment]
Please check our [FAQ](https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-always-get-insufficient-funds-for-fee-when-trying-to-send) to learn more about that.
