### ISSUE TITLE
COPAY think they are smart but they are just thieves, Don’t use COPAY

### ISSUE THREAD

**Issue by tgibbs006** [bitpay/copay#7065]
This excuse they are giving for automatically generating individual wallets inside your personal wallet, and then you just end up losing hundreds, even thousands of dollars in fees if you don’t transfer every single dime out of that address immediately.

**Comment by dabura667** [comment]
lol no

**Comment by JDonadio** [comment]
The complete code of Copay is open source, you can check and verify each process for creation, receiving, sending, etc.

The default wallet created called "Personal Wallet" is part of the onboarding process, but you can delete it or just leave it and create as many as you want in the app.

About the fees, you can customize your own amount of fee, the pre-set values (normal, priority, etc) are just suggestions.
