### ISSUE TITLE
MyBitcoinZ Wallet 504 error will not sync

### ISSUE THREAD

**Issue by oadsifuh** [bitpay/copay#7066]
Just as the title says, wallet will not sync, also will not recover with the 12 word passphrase on another PC.

**Comment by bumbiashvili** [comment]
i have the same problem it was working fine but 3 hours ago it stopped. cant send or receive coins..

**Comment by Biimier** [comment]
I've got same problem and somehow my wallets address have changed too.

**Comment by JDonadio** [comment]
Sorry about that, will be ok in a few minutes

**Comment by Leokon8** [comment]
MyBitcoinZ Wallet is not working. "Could not update wallet: Network error"

**Comment by JDonadio** [comment]
We are not BitcoinZ wallet. Probably they forked our repository and didn't change the support link. This is Copay/BitPay wallet.
