### ISSUE TITLE
BitcoinZ wallet adress changed 

### ISSUE THREAD

**Issue by ninkovic90** [bitpay/copay#7067]
Hi.
I am a miner. I use your BitcoinZ wallet, and today my address changed itself. Where are my miners sending it's funds now?! Why did it change?

**Comment by Biimier** [comment]
Hi.

I had same unwanted surprize and I have same questions.

**Comment by JDonadio** [comment]
Hi please check our [FAQ section](https://github.com/bitpay/copay/wiki/COPAY---FAQ#why-my-address-keeps-changing)
