### ISSUE TITLE
Cant send BTC 

### ISSUE THREAD

**Issue by drago23456** [bitpay/copay#7069]
Hello i tried to send 50$ but unfortenelly i cant so what fee is needed to send all of my btc ? it dosent matter how long it takes but i have to send all so what would you say ? 0.006608 BTC :)

**Comment by JDonadio** [comment]
Please check this out https://github.com/bitpay/copay/wiki/COPAY---FAQ#copay-requires-high-fees-for-low-amounts-transactions
