### ISSUE TITLE
Btc not showing

### ISSUE THREAD

**Issue by boxur** [bitpay/copay#7072]
I definitely had at least 80$ in my account 6 hrs ago now it says I have 5 where are my coins I didn't make a transaction today yet where is my money

**Comment by JDonadio** [comment]
Please provide your wallet id so I can check your wallet status. You can find it at settings > wallet > more otps > wallet information

**Comment by boxur** [comment]
735c55fb-53a0-468a-8847-5ea064679c35

**Comment by boxur** [comment]
What do u mean wallet status are my funds being held after 6+ confirmations

**Comment by boxur** [comment]
I had my last transaction confirm over 6 times in my wallet but the funds now aren't showing up

**Comment by boxur** [comment]
What's wrong with this I don't see a transaction for any besides what I spent and coins just disappear makes no sense

**Comment by PHUCTHINH2007** [comment]
I also lost bitcoin when there were more than 6 confirmed. Please check carefully for me. My wallet address: 1FYkGdaN9NwRttk5rcDcH8TdBpjDVWXhPN
I think the mistake from copay wallet.
Please check and help me regain bitcoin not showing up. Thank you...

![copay3](https://user-images.githubusercontent.com/33478942/32538179-bc3128cc-c497-11e7-9bf8-6eb74964cb65.jpg)

![copay2](https://user-images.githubusercontent.com/33478942/32538175-b8ee2f0c-c497-11e7-8c1b-d849c29801f7.jpg)
![copay l i1](https://user-images.githubusercontent.com/33478942/32538161-af6e2180-c497-11e7-9b80-523be4d9699c.jpg)

**Comment by JDonadio** [comment]
@boxur your wallet it's ok, you have balance there ~80 USD. If for some reason you are not seeing balance in your wallet, please go to settings > wallet > more opts > wallet addresses > scan addresses for funds

@PHUCTHINH2007 same process for you, scan your addresses please.

**Comment by PHUCTHINH2007** [comment]
@boxur <https://github.com/boxur> Still not getting bitcoin when I have
followed your instructions. please help me get back the lost 8bitcoin, that
is a huge sum I borrowed.

2017-11-08 20:02 GMT+07:00 Javier Donadío <notifications@github.com>:

**Comment by PHUCTHINH2007** [comment]
![copay4](https://user-images.githubusercontent.com/33478942/32552121-7408b802-c4c5-11e7-96b9-7ea32454f840.jpg)

**Comment by PHUCTHINH2007** [comment]
Let me just what I should do now, I'm waiting and worried about 8bitcoin not showing up. what should I do now???
@boxur

**Comment by PHUCTHINH2007** [comment]
bitcoin has been shown after 24 hours, thank you for the talk.
![copay6](https://user-images.githubusercontent.com/33478942/32554493-89c222b2-c4cc-11e7-997d-ebad4f115c42.jpg)

**Comment by Jedwards18** [comment]
I'm having a similar issue. I have tried transferring funds at least twice now and they never confirm, despite paying the "priority" transfer fee
