### ISSUE TITLE
Don't enter the wallet 

### ISSUE THREAD

**Issue by ryzhaya88** [bitpay/copay#7073]
I need help to enter the wallet. When I restore the purse to my phone, importing does not happen. Writes: Failed to access the wallet on the server.

**Comment by Jacobbubble** [comment]
@ryzhaya88 Could be a network issue.

Can you create a new, local wallet? No issues?

If you need quick access to funds and you have your backup mnemonic, you can use copay's  recovery tool: https://bitpay.github.io/copay-recovery/

**Comment by ryzhaya88** [comment]
by this link I could not restore my wallet. Here it shows me that the account is empty, although I checked the transactions and funds on the purse is. But I can not get them out until I go into my wallet. Are there any ways to restore my purse or perhaps transfer money from there to a new wallet?

**Comment by JDonadio** [comment]
Are you able to use the recovery tool and scan your wallet? Even if doesn't find any amount, the scan process is complete without errors?

**Comment by ryzhaya88** [comment]
The phrase recovery is 12 keywords right? Scanning is done but as a result nothing. Shows 0.00 
On my wallet now there are funds and there is a confirming transaction. But I can not restore my wallet.

**Comment by JDonadio** [comment]
If you are able to use the recovery tool using your recovery phrase (12 words) you should be able to import it from Copay/BitPay as well. If not, please take some screenshot of your problem and send the report to `javier@bitpay.com`

**Comment by ryzhaya88** [comment]
At this address they don't answer me.

**Comment by ryzhaya88** [comment]
unfortunately it did not work out(
Hello Tell me, how can I be in this situation? I can not withdraw my money. Now they are already saying that the keywords are not valid. Here is the transaction link of my wallet. There must be a way to restore it.
