### ISSUE TITLE
 Recommended to move BTC from Copay to Trezor before upcoming Segwit2x fork?

### ISSUE THREAD

**Issue by McFuhr** [bitpay/copay#7074]
It has been suggested by Bitcoin.org to move all BTC from Copay wallets to Trezor wallets.  This has something to do with BitPay/Copay being in agreement with the Segwit2x fork and the suggestion that this might cause a loss of your BTC somehow if it’s in a Copay wallet instead of a Trezor wallet(or a similar wallet that is not in agreement of the Segwit2x fork).

Should I do as Bitcoin.org suggests or is this unnecessary?  Can someone at Copay add some clarification.  I'm still undecided if I should move all my BTC from my Copay wallets to my Trezor wallets.

**Comment by loboestipario** [comment]
Mi billetera esta en error...como lo arreglo por favor es copay.

**Comment by loboestipario** [comment]
Mi billetera no se actualiza hace 5 diasz

**Comment by loboestipario** [comment]
Mi billetera no se actualiza hace 5 diasz

**Comment by conmed** [comment]
Alguien solucionó el error 403? La billetera no muestra los BTC
