### ISSUE TITLE
BitPay Amazon Gift Card Fraud

### ISSUE THREAD

**Issue by sirazrin** [bitpay/copay#7079]
i paid for the amazon gift card but nothing have been provided.its already been 2 days since the transaction.i already sent request to bitpay support but nothing have been replied back to me.i want my refund back.i feel like i been scam even tho i believe bitpay will not do such thing but thing get frustrated on my side.i hope bitpay will resolve this matter asap

**Comment by sirazrin** [comment]
![thumbnail 2](https://user-images.githubusercontent.com/33444997/32537669-67132406-c49e-11e7-8579-f171ef375c21.jpeg)

**Comment by sirazrin** [comment]
![thumbnail 3](https://user-images.githubusercontent.com/33444997/32537684-776f1ec2-c49e-11e7-9d78-998094b809f3.jpeg)

**Comment by sirazrin** [comment]
![thumbnail 4](https://user-images.githubusercontent.com/33444997/32537703-878bf8c0-c49e-11e7-8c4c-3899addcfdbc.jpeg)

**Comment by JDonadio** [comment]
@sirazrin we are sorry about your problems, can you please follow [this procedure](https://github.com/bitpay/copay/wiki/COPAY---FAQ#amazon-gift-card)? thanks

**Comment by sirazrin** [comment]
@JDonadio i already sent to bitpay help center before this matter on gifhub

**Comment by JDonadio** [comment]
Do you have the ticket number? please send it to `javier@bitpay.com` and I'll escalate it to the help team.

**Comment by JDonadio** [comment]
Found it, thanks. @sirazrin can you please provide the transaction id or the invoice id in that ticket?

**Comment by sirazrin** [comment]
what happening with the issue?..still not resolve until now

**Comment by JDonadio** [comment]
Without the transaction or invoice id we cannot track your issue. Please, provide us and I'll forward your request.

**Comment by sirazrin** [comment]
how to get the transaction id or invoice id...i check my bitpay wallet but i cannot find the id 

    On Saturday, November 11, 2017 5:30 AM, Javier Donadío <notifications@github.com> wrote:
 

 Without the transaction or invoice id we cannot track your issue. Please, provide us and I'll forward your request.—

**Comment by JDonadio** [comment]
Each AGC purchase generates a transaction which will be listed in your wallet details view.

<img width="395" alt="copay_-_copay_bitcoin_wallet" src="https://user-images.githubusercontent.com/13851807/32679717-2fc7488e-c646-11e7-8fa3-441151795733.png">

**Comment by JDonadio** [comment]
This is an example

<img width="396" alt="copay_-_copay_bitcoin_wallet" src="https://user-images.githubusercontent.com/13851807/32679740-49c45308-c646-11e7-92d4-15bd1aff7654.png">

**Comment by sirazrin** [comment]
@Javier
i follow your sample..now i screenshot from my bitpay app at my phone because i using bitpay wallet on my phone..now can you tell me which one the transaction id or invoice id on the screen shot

 

    On Saturday, November 11, 2017 5:38 AM, Javier Donadío <notifications@github.com> wrote:
 

 This is an example—

**Comment by JDonadio** [comment]
@sirazrin you share the transaction screenshots above, but not the ID. I just need the ID

**Comment by sirazrin** [comment]
@Javier i know but i can't find the id 

    On Sunday, November 12, 2017 3:16 AM, Javier Donadío <notifications@github.com> wrote:
 

 @sirazrin you share the transaction screenshots above, but not the ID. I just need the ID—

**Comment by sirazrin** [comment]
@Javier now i share another screen shot..you tell me where can i find the id..i follow the sample you sent to me before this


 

    On Sunday, November 12, 2017 3:16 AM, Javier Donadío <notifications@github.com> wrote:
 

 @sirazrin you share the transaction screenshots above, but not the ID. I just need the ID—

**Comment by JDonadio** [comment]
@sirazrin there is not screenshots attached. I don't need screenshot, i need the transaction id. When you find it send it to my email.

**Comment by javier** [comment]
Please kindly note you are using the github user name Javier in this
conversation, so I'm getting notifications for a project I'm not related to.

Please use the proper nick from now on so I don't receive notifications,
but the user you were intending.

Thanks!

On Nov 11, 2017 20:31, "Javier Donadío" <notifications@github.com> wrote:

@sirazrin <https://github.com/sirazrin> there is not screenshots attached.
I don't need screenshot, i need the transaction id. When you find it send
it to my email.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bitpay/copay/issues/7079#issuecomment-343688532>, or mute
the thread
