### ISSUE TITLE
 About 8btc does not show up when there are more than 50 validations. (Copay Wallet)

### ISSUE THREAD

**Issue by PHUCTHINH2007** [bitpay/copay#7080]
I also lost bitcoin when there were more than 6 confirmed. My wallet address: 1FYkGdaN9NwRttk5rcDcH8TdBpjDVWXhPN
I think the mistake from copay wallet.
Please check and help me regain bitcoin not showing up. Thank you...
![copay l i1](https://user-images.githubusercontent.com/33478942/32538498-c8cad08c-c498-11e7-8e54-50473cd3d62f.jpg)
![copay2](https://user-images.githubusercontent.com/33478942/32538506-ce87ef28-c498-11e7-9982-3892867952a8.jpg)
![copay3](https://user-images.githubusercontent.com/33478942/32538511-d2dd7a7a-c498-11e7-9faf-8d36a18f85c8.jpg)

**Comment by loboestipario** [comment]
Mi billetera no se actualiza hace 5 días...
.dice: no se pudo actualizar

**Comment by JDonadio** [comment]
@PHUCTHINH2007 me temo que tu billetera no posee esa cantidad, debido a que enviaste más de 11 BTC en esta última transacción de salida: https://insight.bitpay.com/tx/7f46d9c1c341881b3ab03e197296f11ed9017aa560c7bdb9b26b6009b0c0d92a

@loboestipario no hace falta que comentes en todos los tickets lo que te sucede, lamentablemente hay varios con el mismo problema y sentimos mucho que así sea. Por favor, verificá tu situación y comentá lo que necesites en [este ticket](https://github.com/bitpay/copay/issues/7053)

**Comment by PHUCTHINH2007** [comment]
I have 26.9xxxBTC at that time. But I only transfer 19-20btc, so I have
8btc in my wallet. I've been using bitcoin for so long and many times
before, I can confirm this is a bug from Copay wallet.
Please check the transaction history, and you will understand. Hope you can
help me regain my bitcoin.

    https://blockchain.info/address/1FYkGdaN9NwRttk5rcDcH8TdBpjDVWXhPN

The number of bitcoins in the wallet is not enough compared to the bitcoin
I have. I will send proof to you.

2017-11-08 20:22 GMT+07:00 Javier Donadío <notifications@github.com>:

**Comment by JDonadio** [comment]
@PHUCTHINH2007 please provide your wallet id, you can find it in settings > wallet > more opts > wallet information

**Comment by PHUCTHINH2007** [comment]
bitcoin has been shown after 24 hours, thank you for the talk.


2017-11-08 21:18 GMT+07:00 Javier Donadío <notifications@github.com>:
