### ISSUE TITLE
Can't send BCH to exchange

### ISSUE THREAD

**Issue by Michi1982** [bitpay/copay#7082]
I can't send BCH to exchanges. Massage: "Copay only supports Bitcoin Cash using new version numbers addresses"
But i don't ge a better address from the exchange. I created new addresses there, but this didn't solve this problem. What can I do?

**Comment by loboestipario** [comment]
Mi billeteta esta sin actualizarmhace 5 dias....ayuda por favor

**Comment by Michi1982** [comment]
I tried it with a few other wallets and exchanges. Everytime the same Massage.

DON'T SEND BCH TO THIS WALLET. THEY ARE ALL LOST:

**Comment by JDonadio** [comment]
Hi there, please check our [FAQ](https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-cant-send-bch) section, there is a procedure to solve this.
