### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by Amansoni97** [bitpay/copay#7083]
I had sent my BTC from another wallet to Copay wallet. It showed Network error and the amount is yet to be received. Till when will the error be rectified?

**Comment by JDonadio** [comment]
Hi there, this is probably a network issue. Copay servers use `cloudflare` to prevent certain types of network attacks, and some networks are restricted. Try changing your network and try again.

In addition, can you tell us in what country are you located to check the above restriction?

**Comment by Amansoni97** [comment]
The issue has been resolved.
Secondly, should I transfer my BTCs from Copay to some other wallet before the fork? There seems to be rumour that you guys are not supporting the fork and have network issues.

**Comment by ALBERTBITCOIN** [comment]
i am albert from Ecuador Sudamerica 
good morning I have a problem in my copay account where the system tells me that there is an update error and I can not use my bitcoins account

**Comment by matiu** [comment]
@Amansoni97 regarding upcoming fork, you should check https://blog.bitpay.com/segwit2x-and-bitpay/ .

**Comment by ALBERTBITCOIN** [comment]
but because blog.bitpay.com blocks ECUADOR South America

Error 1009 Ray ID: 3ba98ce17a028279 • 2017-11-08 15:26:22 UTC
Access denied
What happened?
The owner of this website (blog.bitpay.com) has prohibited that the country or region in which his IP address (EC) is located to access this website.


How do I recover my account?

**Comment by matiu** [comment]
@ALBERTBITCOIN you can recover your wallet using any BIP39 compatible wallet. We are sorry but can not serve your country, due to local regulations.

**Comment by ALBERTBITCOIN** [comment]
@matiu hello, it's an app BIP39?

**Comment by JDonadio** [comment]
BIP39 is a standar: https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki
You can use any wallets that support it to import your Copay/BitPay wallet. In the meantime you can use the [recovery tool](https://bitpay.github.io/copay-recovery/) and move your funds to anywhere you wish.
