### ISSUE TITLE
Not able to send bitcoin

### ISSUE THREAD

**Issue by pah8000** [bitpay/copay#7086]
after i key in the address, i not able to type the amount of bitcoin.

**Comment by JDonadio** [comment]
We need more detail to investigate, could you please attach a screenshot of your problem ? thanks

**Comment by WTF82** [comment]
I also have that problem .. what should I do? ... I live in Ecuador

**Comment by WTF82** [comment]
I need a solution as soon as possible ... it's my money and I need it

**Comment by JDonadio** [comment]
@WTF82 your problem isn't related to this issue but `Network error`. Please check this out: https://github.com/bitpay/copay/issues/7053

**Comment by pah8000** [comment]
Thank you.

**Comment by pah8000** [comment]
Can it be my money is from all small transactions, when I want to send BTC,
it need to combine all previous transactions. This make the block larger
and costly.

**Comment by JDonadio** [comment]
Yes that could be the reason, please check our [wiki section](https://github.com/bitpay/copay/wiki/COPAY---FAQ) for more info.
