### ISSUE TITLE
High ridiculous sending fees

### ISSUE THREAD

**Issue by pah8000** [bitpay/copay#7087]
I would like to send bitcoin (worth 0.110307BTC) to LUNO. 
However, the fee is 0.024871 BTC.
Why?

**Comment by monsterbitar** [comment]
The network is congested and there is not room for everyone. Only those who pay more than others can use the network.

You might want to look into Bitcoin Cash, it works in Copay and doesn't have ridiculous sending fees.

**Comment by pah8000** [comment]
can i change my bitcoin to bitcoin cash inside copay?

**Comment by Berndinox** [comment]
0,2BTC that just could be a bug,... 0,2 are 600$

**Comment by pah8000** [comment]
Yes, even with super economy. To trnasfer 0.125BTC (USD905.71), I will need to pay 0.021137BTC (USD152.19).
How to solve this problem?

**Comment by matiu** [comment]
It depends on how big is your TX, not the amount you are trying to send.

**Comment by JDonadio** [comment]
Please check this out https://github.com/bitpay/copay/wiki/COPAY---FAQ#copay-requires-high-fees-for-low-amounts-transactions

**Comment by JDonadio** [comment]
Btw there is a custom option to set a value manually if consider the pre-set levels are high for you.

**Comment by jwebbstevens** [comment]
Wouldn't this be solved if Copay supports SegWit?  I'm unclear if it does. I think the wallet is pre-segwit still.  Having a hard time understanding if it is or is not.

**Comment by monsterbitar** [comment]
It would not be solved automatically if copay supported segwit.
It would partially be allievated if everyone, including copay, would support segwit.

Not everone does though, and the real issue isn't segwit; but that there is more demand for transaction space than there is allowed space to be used for transactions.
