### ISSUE TITLE
Btc not broadcasted and stuck

### ISSUE THREAD

**Issue by milahajek** [bitpay/copay#7088]
Hello, I think I double spend by mistake my bitcoin from what I read. I tried to send it from my shared copay wallet in ipad to my iphone copay wallet and the transaction did not propagate to the network. I can’t get id of the transaction. It calculated fee over two dollars and I am waiting already one day for something to happen. Transaction is not visible on blockchain. Thnaks for any help.

**Comment by JDonadio** [comment]
If you are using a shared wallet, then you must create a proposal and sign it. That proposal will be hanging for the rest of co-signer of your shared wallet. If the other copayers didn't sign it, your transaction will not be broadcasted.

**Comment by milahajek** [comment]
JDonadio thanks so how should I do it? It was definitely a shared wallet. One on ipad and one iphone. How can I create that proposal and sign it? Am not sure if I am skilled enough for this.

**Comment by JDonadio** [comment]
To create a proposal you must try to make a payment:

* Put the destination address
* Put the required amount
* Check your fee and sign

You'll see a green screen that says your proposal was created, and going to your wallet details view you'll see it in the history section. If you tap on it the transaction proposal details will be shown. 

For the rest of devices that compose your shared wallet, to broadcast that proposal they need to sign it until reach the N required signatures.

Shared wallets needs more than 1 signs. So, if your wallet is N-M, you need at least N signs to broadcast the transaction, if you didn't sign it N times, then the proposal will be hanging in your wallet detail view.

**Comment by JDonadio** [comment]
To clarify, N-M:

N > Required signatures
M > Number of copayers

**Comment by milahajek** [comment]
Thank you very much I will see what can do

**Comment by milahajek** [comment]
So I tried to send two transactions from available balance on differend wallet brand. And the same thing happened. No tx found.

**Comment by JDonadio** [comment]
Open one of that `sending` transaction and share that screen please

**Comment by milahajek** [comment]
![83013d49-e242-4aa9-b4b8-5f060d4c7be0](https://user-images.githubusercontent.com/33515343/32614209-adaac89e-c564-11e7-8e84-d91d7fe48566.png)

**Comment by milahajek** [comment]
I am confused now. It says sent with four confirmations but I cant see it anywhere. I dont know where it went

**Comment by milahajek** [comment]
I think I found it. What i did was i deleted all my copay wallets with stuck payment because i was thinking maybe it will keep trying to send it while the wallet is on-line so i deleted it. Then i tried to recover from the seed on several wallets and now it appeared on bread wallet. This is crazy.

**Comment by Johnfxp** [comment]
Tengo un problema similar, hice un envio y no me aparece en la blockchain y el saldo se desconto de mi monedero copay, que hago en este caso, muchas gracias.

**Comment by Johnfxp** [comment]
![whatsapp image 2017-11-14 at 2 35 02 pm](https://user-images.githubusercontent.com/33670061/32805489-92664698-c957-11e7-976a-490674d6209a.jpeg)

**Comment by JDonadio** [comment]
@Johnfxp por favor enviame tu wallet id a `javier@bitpay.com`
