### ISSUE TITLE
Spending password is not working

### ISSUE THREAD

**Issue by roywismans** [bitpay/copay#7089]
I created a Copay account for my Bitcoins.
Therefore I created a spending password. I am sure this is the right password.
However this password is not working.

My back-up code is gone, so I was not able to make a back-up.🙁

**Comment by JDonadio** [comment]
The first step is backup your wallet. If you have any problems you'll always available to restore it, but if you didn't there is no way to recover it.

**Comment by roywismans** [comment]
okay that's less for me, it's crazy that my spending password does not matter ?!

Thx for reaction!

**Comment by JDonadio** [comment]
We cannot control your password, as all your keys and passwords are located in your device so we cannot manage it.

Unfortunately without a backup there is nothing we can do to help you.

**Comment by parkermor** [comment]
@roywismans 
if you have text backup I can crack your password and recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
