### ISSUE TITLE
Questions about Copay

### ISSUE THREAD

**Issue by kikkokikko** [bitpay/copay#7094]
Hi, I'm a Copay's customer and I have few questions about it:

1) Is there any way to completely empty a wallet in Copay? I'm asking because every time I try to transfer all my btc to another address (or an exchange) there's always a fraction of btc left in the wallet I'm moving them from. Moreover, I can't spend or move these small amounts of btc because of the fees, then they'll be lost forever.

2) This morning I have sent all my btc to an exchange; after 8 hours I have 0 confirmations, surely because I've set very low fees. Is it possible to cancel the transaction and re-send the btc with higher fees, as long as there are 0 confirmations?

3) I have some bch on my Copay wallet as well and in the next days I want to send some bch from an exchange to my Copay's bch wallet. Ive heard about some issues about different addresses format that can invalidate this kind of transactions. Can you tell me more about it.

Thanks a lot, best regards.

**Comment by JDonadio** [comment]
> Is there any way to completely empty a wallet in Copay? I'm asking because every time I try to transfer all my btc to another address (or an exchange) there's always a fraction of btc left in the wallet I'm moving them from. Moreover, I can't spend or move these small amounts of btc because of the fees, then they'll be lost forever.

From Copay/BitPay you have the send max option (tapping on the 3 dots at top-right on the screen). This option will calculate all the available utxos, excluding the not viable economically (smaller).

> This morning I have sent all my btc to an exchange; after 8 hours I have 0 confirmations, surely because I've set very low fees. Is it possible to cancel the transaction and re-send the btc with higher fees, as long as there are 0 confirmations?

Unfortunately no. Copay have not options for CPFP. A work-around for this it's use the send max option to move all your funds to your own wallet, but will pay a higher fee of course.

> I have some bch on my Copay wallet as well and in the next days I want to send some bch from an exchange to my Copay's bch wallet. Ive heard about some issues about different addresses format that can invalidate this kind of transactions. Can you tell me more about it.

Yes, that's because [this](https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-cant-send-bch)

For more info please check our [wiki section](https://github.com/bitpay/copay/wiki/COPAY---FAQ)

**Comment by kikkokikko** [comment]
Hi, thanks for the answer, sorry, I have a couple of questions again: 

I went into "Extended Private Key" just to check the new function and I "tapped" ( I'm on iPad) on the key. That's what I saw: "Copied to clipboard". What does it mean? Did I do something wrong? 

Another question is about BTG. Do you have any plan to support it? Thanks a lot.
