### ISSUE TITLE
Unable to send BCH

### ISSUE THREAD

**Issue by NeoNeoNeo** [bitpay/copay#7097]
Hi,

After entering the recipient address, selecting BCH, entering in my amount, and selecting the forward (arrow) button, I am met with a blank page.

I have triple checked the address and gone through the BCH settings multiple times, but the issue still occurs.

Please help!

Many thanks :)

**Comment by JDonadio** [comment]
Check this out: https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-cant-send-bch
