### ISSUE TITLE
BCH SENT FROM COPAY WALLET TO EXCHANGE 1600 CONFIRMATIONS IN INSIGHT BUT NEVER ARRIVED

### ISSUE THREAD

**Issue by urivalls** [bitpay/copay#7101]
I sent my BCH to kraken and never arrived to destiny. Looking the blockchain the transfer has more than 1600 confirmations....
![111](https://user-images.githubusercontent.com/33543626/32652413-77cddfcc-c604-11e7-93f3-23ac06f62161.jpg)

**Comment by urivalls** [comment]
TRANSACTION ID: bec8e1e3d52f704978b6ceb33c205df7d52e171148e236cad5102af9bb9cdd40

**Comment by JDonadio** [comment]
We cannot do anything in this case, the transaction was built and broadcasted successfully and even confirmed. So you need to claim your coins in the exchange providing that transaction as a proof.
