### ISSUE TITLE
Blue screen when updating block database Bitcoin core 0.15.0.1

### ISSUE THREAD

**Issue by awilliam235** [bitpay/copay#7102]
Hello,

It's driving me crazy. Bitcoin core gives blue screen laptop failure after 10 minutes of updating the blockdatabase. Tried another simular laptop. Same result! Errors on the blue screens:
- stop: 0x000000F4
- KERNEL_DATA_INPAGE_ERROR, stop: 0x0000007A, volmgrx.sys
- dxgkml.sys

What's hapening?

**Comment by JDonadio** [comment]
We can only give you support for the wallet itself.
