### ISSUE TITLE
Bitcoin Cash sent to account not showing or problem

### ISSUE THREAD

**Issue by joreilly28** [bitpay/copay#7105]
Bitcoin Cash was sent from my livecoin account last night, but I was told that the address is not correct, but it is the address showing in my wallet for Bitcoin Cash : Cdxpg4NUS8BzFVbJBF67X5qTUxP1rarfay

Please help

**Comment by joreilly28** [comment]
My address is not showing on the blockchain for Bitcoin Cash, but this is the address my wallet shows for receiving my funds.

**Comment by JDonadio** [comment]
Please check this out: https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-cant-send-bch

**Comment by joreilly28** [comment]
I did check this out, but it does not have a solution for my problem

Jessica O'Reilly

**Comment by joreilly28** [comment]
Thank you for trying to help.

Not receiving my BCH in my copay and my copay address does not appear on blockchain Explorer for Bitcoin Cash.

Jessica O'Reilly

**Comment by JDonadio** [comment]
Please describe your problem in detail and also if you have a transaction id please provide it

**Comment by joreilly28** [comment]
This is the information that I have from livecoin.

PENDING TRANSACTIONS
TypeAmountFrom/toNotes
Withdrawal 0.10377718 BCH  Wallet: Cdxpg4NUS8BzFVbJBF67X5qTUxP1rarfay
I put in the request to withdraw .10377718BCH from my Livecoin account
This is the address in my copay account for my BCH account.

[image: Inline image 1]

I have been using copay for a while for my Bitcoin transactions, this is my
first transaction for BCH.Did I do something wrong? Is the address not
valid?
Any help is appreciated. Thank you again for trying to help.




Jessica O'Reilly

On Nov 11, 2017, at 5:20 AM, Javier Donadío <notifications@github.com>
wrote:

Please describe your problem in detail and also if you have a transaction
id please provide it

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bitpay/copay/issues/7105#issuecomment-343589789>, or mute
the thread

**Comment by JDonadio** [comment]
We cannot give you support for transactions made by another software. You must contact to the `Livecoin` support team and ask they why your transactions is pending.

**Comment by joreilly28** [comment]
I did that, they said that my BITCOIN Cash address is not valid.
copy of message:
Support (assistant):
Hello.
I can't find this address in blockchain. If this address correct why it not
available in block explorer?
10.11.2017 15:30Joreilly:
(Support reply: Since you ignored this warning, funds that you sent to
wrong wallet address will be lost)

Since you implied that I made an error
Where is my mistake, PLEASE SHOW ME.

PENDING TRANSACTIONS
Type Amount From/to Notes
Withdrawal 0.10377718 BCH Wallet: Cdxpg4NUS8BzFVbJBF67X5qTUxP1rarfay In
execution

MY copay bitcoincash: Cdxpg4NUS8BzFVbJBF67X5qTUxP1rarfay



10.11.2017 15:03Joreilly:
What do you mean the wrong address. I had the address checked and that’s
the address to my co-pay bitcoin cash address . Can I have a copy of the
transaction ? I want to make sure , if I made a mistake I will accept it.
10.11.2017 14:09Support (assistant):
Hello
We have a warning message in withdrawal form "Please verify your withdrawal
address.
In case of incorrect address, your FUNDS WILL BE LOST. Please note that
funds cannot be returned"
Since you ignored this warning, funds that you sent to wrong wallet address
will be lost
10.11.2017 05:46Joreilly:
My withdrawal bitcoin cash has not posted yet. It has been 5 hours.

**Comment by JDonadio** [comment]
check this out: https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-cant-send-bch

You must to use the proper address format for BCH transactions **_to_** Copay/BitPay

**Comment by joreilly28** [comment]
Javier,
My copay Bitcoin Cash is showing this address for me to receive BCH

Cdxpg4NUS8BzFVbJBF67X5qTUxP1rarfay

Is this format wrong? I just copied the exact address that is shown in my co-pay for my bitcoin cash address

Jessica O'Reilly

**Comment by JDonadio** [comment]
@joreilly28 did you read the above article?

**Comment by joreilly28** [comment]
Whatever!! ( live and learn )
Thanks for the help.

Jessica O'Reilly
