### ISSUE TITLE
Btc not showing 

### ISSUE THREAD

**Issue by ChevBenzo** [bitpay/copay#7107]
I sent btc to app then I called to see if it had been confirmed they said yes and now it’s not showing me so I can’t send my btc to an site I need y’all to fix this

**Comment by ChevBenzo** [comment]
Can y’all fix my wallet or something

**Comment by dansuperman** [comment]
The same happened for me.  Sent in a coin that is confirmed by Blockchain but does not show up in my account.   Bitpay is currently being unprofessional at the moment.  

Also, I had filed a report as to why Bitpay Merchant isn't working 9 days ago, and yet still no response.  Does anyone know why, or anyone that works at Bitpay that can respond?

**Comment by JDonadio** [comment]
Provide your transaction id so we can check the status

**Comment by ChevBenzo** [comment]
Transaction 5941601c764522b6353cfdada5272b6b506c29e727b0db1e35a62d1c5101eff5

**Comment by JDonadio** [comment]
Your transaction remains unconfirmed due the huge amount of transactions in the mempool, you just have to wait. Unfortunately there is nothing to do.

**Comment by ChevBenzo** [comment]
How long do I have to wait ?😑

**Comment by JDonadio** [comment]
Depends on the network, in the worst case ~2 weeks.
