### ISSUE TITLE
Sent in error BTC to BTH  How do I cancel or reclaim my coins sent between my Copay wallet & Exodus.  Thanks in advance for your assistance!

### ISSUE THREAD

**Issue by KyleCrypto** [bitpay/copay#7108]

**Comment by filipesmg** [comment]
I had the same issue, and found the solution here:
https://github.com/bitpay/copay/issues/7106

It worked well for me. (phew!)

**Comment by KyleCrypto** [comment]
...it certainly was a relief to fix my error!
I received a fast reply from Exodus where I sent my BTC from Copay to BHC on Exodus to and here's the reference link: http://support.exodus.io/article/156-ive-sent-bitcoin-cash-to-my-bitcoin-address

**Comment by JDonadio** [comment]
Check this out: https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-sent-bch-coins-into-a-btc-address-what-can-i-do-to-recover-my-bch-coins
