### ISSUE TITLE
Trasacction with 24 hours

### ISSUE THREAD

**Issue by armandomendez1** [bitpay/copay#7109]
Hello, I have almost 24 hours waiting for a transfer from a Copay wallet to another Copay wallet, although the fee was very cheap, I think it takes too long and there are no confirmations, then the address of the transaction:
https://insight.bitpay.com/tx/8a4b3ebfc93b816bb2a22d4c28e1f72dc94da79f59b9e80238516b0fe4f3df05
Thanks in advance for your support.
Armando M.

**Comment by JDonadio** [comment]
The bitcoin network is congested, there are a lot of transactions in the mempool. I have the same problem but we cannot do anything, just wait.
