### ISSUE TITLE
Incoming Transaction Still Receiving

### ISSUE THREAD

**Issue by the3vil1** [bitpay/copay#7110]
I have an incoming transaction that is still in "receiving" state. It has been over 24 hours.
https://insight.bitpay.com/tx/acbb597213738ebda688fe781926fa80de4b3210ae833664f62c3350d98ffda4
If someone can verify please.
Many thanks,
Anthony

**Comment by ChevBenzo** [comment]
I’m having this same problem

**Comment by JDonadio** [comment]
Bitcoin network is congested, you just have to wait. Unfortunately there is nothing to do.
