### ISSUE TITLE
How do I send BCH to another BCH wallet using copay?

### ISSUE THREAD

**Issue by phil72565** [bitpay/copay#7111]
using copay wallet I enter a valid BCH address and hit send then it freezes up?
I can send BTC but not BCH?
am I doing something wrong?
I can also set wallet option to receive between BCH and BTC but no option to send BCH 
here are some screenshots is what happens when I try to send BCH
![dscn2448](https://user-images.githubusercontent.com/32394294/32691423-f24f2846-c6cc-11e7-980b-31dfad3e7782.JPG)
![dscn2447](https://user-images.githubusercontent.com/32394294/32691433-0c335a5c-c6cd-11e7-8189-45f803bb1e28.JPG)

**Comment by phil72565** [comment]
figured it out!
had to use the copay translation tool

**Comment by rllola** [comment]
Could you explain how you have done it ? I have the same issue.

**Comment by gabrielbazan7** [comment]
Take a look at this: https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-cant-send-bch

**Comment by phil72565** [comment]
use this


https://bitpay.github.io/address-translator/

________________________________
