### ISSUE TITLE
My first transaction to COPAY goes wrong

### ISSUE THREAD

**Issue by nino1983** [bitpay/copay#7113]
I have bought 131.26 euro is BTC 0.02200000 at btcdirect.eu to my wallet copay 192wexVmT7rPBtHV8Nm4MoLb8BKbvqFVmU. But without a good result.
My copay account address that I mentioned above is no longer available.
I was searching for why my account address could change or disappear. I saw that you also have an option to generate new address than you get a new address. So that may have happened to me and my address was changed. But my question is now where my btc transaction remained, someone can help me with this

**Comment by JDonadio** [comment]
Please check our [wiki section](https://github.com/bitpay/copay/wiki/COPAY---FAQ), there are some items which explain how Copay works
