### ISSUE TITLE
BCH Address Format Translator doesn't work in Firefox

### ISSUE THREAD

**Issue by patrikr** [bitpay/copay#7114]
Your BCH Address Format Translator (https://bitpay.github.io/address-translator/) doesn't work in Firefox: it's impossible to copy the converted address.

**Comment by JDonadio** [comment]
You must use Chrome instead

**Comment by patrikr** [comment]
LOL wut? If Chrome is a requirement the page should say so. But better would be to fix your shit.

**Comment by patrikr** [comment]
Anyway, this issue should not be closed without any fix.

**Comment by gabrielbazan7** [comment]
@patrikr feel free to send a PR with the fix. It is not a priority for us.
