### ISSUE TITLE
Wallet made transaction but there is no same in blockchain

### ISSUE THREAD

**Issue by wewakawaka** [bitpay/copay#7116]
Hi,

I have sent some volume of BTC to another BTC wallet. Wallet was correct. In app (android) I see that it was sent few minutes ago, but when I am trying to check it in blockchain is says that there is no such ID. Also my balance becoming bigger or lower each time I am pushing some buttons and going back to main screen.

**Comment by wewakawaka** [comment]
Also it says sometimes when I am trying to check sent transaction in app, that Transaction is not available in this moment.

**Comment by wewakawaka** [comment]
App gives me this link to ID
https://insight.bitpay.com/tx/7f506522b2f7a94442905ded97a0bb99eb888cb9cd09fa1d7cc5442fff25d68f
But there is no nothing in here

**Comment by JDonadio** [comment]
Your transaction was droppped from the mempool. Please go to settings > wallet > more opts > wallet addresses > scan addresses for funds. And also reset your history going to settings > wallet > more opts > transaction history > clear cache
