### ISSUE TITLE
shapeshift transaction was not showing in app

### ISSUE THREAD

**Issue by paOol** [bitpay/copay#7117]
My friend did a BTC -> BCH shapeshift in the morning.

It had btc confirmations, and bch confirmations.

did not appear in the copay app and his balance did not reflect it.

Until I told him to go to Settings -> (select the wallet) -> More Options -> Wallet Addresses 

then choose `scan addresses for funds` .

Never experienced this issue myself, but It appears to be a bug?

also unrelated: the BCH account balance (in USD) does not appear reliably . BTC always appears.

**Comment by JDonadio** [comment]
Hi @paOol thanks for your report. Can you please provide your wallet id? send it to `javier@bitpay.com` and I'll check the wallet status. In the mean time - in adition to wallet id - provide what is your expected amount.
