### ISSUE TITLE
No me deja retirar bch a otra Billetera

### ISSUE THREAD

**Issue by magcoin87** [bitpay/copay#7118]
Hago todo para retirar y al momento de retirar me dice solo soporta la nueva versión de direcciones, pero no me deja retirar a ninguna billetera que tenga la misma dirección actualizada ya probé con bittrex, hit btc,  coinomi, etc.  Como se hace para retirar?  Solicito una solución urgente, gracias

**Comment by JDonadio** [comment]
Para mover BCH **fuera** de Copay, tenes que convertir el formato "viejo" (1...) en el nuevo (que empiezan con C o H). A ese proceso lo haces con la [herramienta de traducción de direcciones](https://bitpay.github.io/address-translator/).

Si por el contrario querés enviar BCH desde otro lugar **hacia** Copay, tenes que hacer el mismo proceso pero convirtiendo el formato nuevo (C... o H...) al viejo (1...) usando la misma herramienta.

Si es para enviar BCH desde Copay y tenes la dirección copiada, podes simplemente ir a la pestaña enviar, y en el input donde pones la dirección usas el prefijo `bitcoincash:` es decir, q pondrías por ejemplo `bitcoincash:CVMo46KXPfMdgGqmB.......` y automáticamente te lo interpreta como BCH.
