### ISSUE TITLE
Bitpay 

### ISSUE THREAD

**Issue by NNeelissen** [bitpay/copay#7123]
I have received some payment a few days ago on my Bitpay wallet but I can't do anything with it. Do I have to confirm this?? I have the same problem with sending bitcoins.

Awaiting your reply.

Gr. Naut

**Comment by JDonadio** [comment]
Bitcoin network is congested, you just have to wait. Unfortunately there is nothing to do.

For more info check our [FAQ](https://github.com/bitpay/copay/wiki/COPAY---FAQ) section.
