### ISSUE TITLE
Copay transfer stuck

### ISSUE THREAD

**Issue by arkcfze** [bitpay/copay#7127]
My transfer request in copay stuck. App says Sending for 6 hours plus. In Insight it says Unconfirmed. How to cancel or make it work?

**Comment by JDonadio** [comment]
Bitcoin network is congested, you just have to wait. Unfortunately there is nothing to do.
Bitcoin transactions cannot be cancelled, please check our [FAQ](https://github.com/bitpay/copay/wiki/COPAY---FAQ) section for more info.
