### ISSUE TITLE
 Why did my wallet address change?

### ISSUE THREAD

**Issue by sarff** [bitpay/copay#7128]
Why did my wallet address change?
was - t1drsVN188qnV5QuiPvmWmD9HcvYidsrdQs 
changed to - t1aVJEKv1vynkhp9mv6eoHF7jvf9MahTWP9

my miner worked on the old address. will I get the coins?

**Comment by gabrielbazan7** [comment]
https://github.com/bitpay/copay/wiki/COPAY---FAQ#why-my-address-keeps-changing
