### ISSUE TITLE
Cant send from bitcoin cash wallet copay

### ISSUE THREAD

**Issue by joopykiller** [bitpay/copay#7130]
Hi there, 

I have a problem , i'm trying to send some bitcoin cash (BCH) but the i get the following screen...
![naamloos](https://user-images.githubusercontent.com/33599853/32700079-220b780c-c7c0-11e7-83e2-a2d7046a2fc9.jpg)

Do i do something wrong? 
Thanks!

**Comment by Jacobbubble** [comment]
@joopykiller I've seen that be a network issue or an app instance issue. Try closing and re-opening the Copay application and trying again. Also check your network connection.

**Comment by gabrielbazan7** [comment]
Take a look at this https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-cant-send-bch

**Comment by joopykiller** [comment]
Thanks guys , Still have the same problem , its costing me a hell of a money , some one else got a suggestion ?

Thanks

**Comment by joopykiller** [comment]
Problem solved , only thing i had to do is convert the adress... you can do it her. https://bitpay.github.io/address-translator/ 

Thanks Guys!
