### ISSUE TITLE
Bitcoin Cash Does Not Show Up In Wallet

### ISSUE THREAD

**Issue by bc2013** [bitpay/copay#7131]
I recently did an exchange For Bitcoin Cash using Shapeshit.io and the Bitcoin Cash does not show up in my wallet. Shapeshift says that transaction is complete but it is not in my wallet. The wallet was a chrome app and am running Windows 7. A link to the shapeshift order is below. Thank you for your time.

https://shapeshift.io/#/status/430bedb9-c398-452c-a198-6c695db00d57

**Comment by JDonadio** [comment]
Contact to shapeshift and ask for your transaction. We cannot do anything for transactions that were built by an external software. If the transaction was confirmed and your funds are not showing up then let us know.

**Comment by bc2013** [comment]
Is this it?
https://shapeshift.io/#/status/430bedb9-c398-452c-a198-6c695db00d57

And they also had a link to this:
https://blockchair.com/bitcoin-cash/transaction/04a296224dfdfb7a26c35ad3ea08579c4f951b5a7dc81b2f7d69c0219a3b4f4e

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by bc2013** [comment]
I replied with information that you asked for. Can you please reopen this thread and get this fixed please?

**Comment by JDonadio** [comment]
@bc2013 this is not related to the wallet. As I said before, you must contact to shapeshift support team, we cannot give you support for transactions made for other software.
