### ISSUE TITLE
dont received btcz

### ISSUE THREAD

**Issue by miningfarm** [bitpay/copay#7132]
hi i didnt receive btcz . hash  transaction  
 00000002e3eb82e8812ce82cf230cf7fb086b788cc7493ffe13a7093c3c0eb87   
51000  btcz . please resolve this problem asap

**Comment by JDonadio** [comment]
What is btcz? Copay only support BTC and BCH.

**Comment by miningfarm** [comment]
Btcz is BitcoinZ . I just go to support on my wallet BitcoinZ and when i
pressed go to support showing me your website.  Can you help me ???

Kind Regards


     RADOSLAW  LYZWA

      General Director


    M:  +447411931760

   E:   radek@miningfarm.co.uk


         www.miningfarm.co.uk



13.11.2017 12:49 "Javier Donadío" <notifications@github.com> napisał(a):
