### ISSUE TITLE
Import from Bread had no effect

### ISSUE THREAD

**Issue by ffxsam** [bitpay/copay#7133]
I created a new wallet in Copay and imported using my 12-word phrase from Bread. However, my BTC balance is 0. I realize I can send money from one wallet to another, but I was hoping to just link to the same wallet balance temporarily so I can try out Copay without committing to it.

EDIT: Whoa, been a while since I've used Bitcoin. $7 to send money now?! So yeah, I'd rather import my wallet somehow if I can, rather than send myself money and waste $7.

**Comment by gabrielbazan7** [comment]
I think can not directly import your Breadwallet seed into Copay. You will need to create a new wallet and move your funds there.

**Comment by ffxsam** [comment]
Ok. And do you know if it's possible to move funds between BTC & BCH wallets within Copay?

**Comment by gabrielbazan7** [comment]
Yes

**Comment by ffxsam** [comment]
Thanks!
