### ISSUE TITLE
Of 2 funded BCH wallets in Copay multisig wallet, only one can send BCH

### ISSUE THREAD

**Issue by kirksu** [bitpay/copay#7134]
I  have 2  funded BCH wallets in my copay multisig wallet.  When I try to send BCH from one of them to an external address, only one of them populates.  And it populates with a check box already checked. There is no option to choose which of the 2 wallets to send from.
please advise.
Kirk Ulbricht

**Comment by Derrick-** [comment]
Hey Kirk.

Does that address you are trying to send to begin with a 1 or a C ?

**Comment by gabrielbazan7** [comment]
Hi ! Sorry I can't understand your issue, could you describe the steps you follow to send to that external address ? Maybe you could add some screenshots. Thanks

**Comment by kirksu** [comment]
Derrick,  I'm using the bitpay/copay address translator.  The answer is C.
Gabriel,
OK, I will.  probably tomorrow morning.  Thanks for your help!
