### ISSUE TITLE
Recovering BCH 

### ISSUE THREAD

**Issue by PBreed321** [bitpay/copay#7136]
I have followed the steps necessary to recover my BCH, but there is never any coins recognized. Any pointers?

**Comment by Derrick-** [comment]
After the account is split, it may show an account balance of zero.

If so, "try a 'scan address for funds' in Settings > Wallet > More Options > Wallet addressess."
https://github.com/bitpay/copay/issues/6884#issuecomment-341903910

**Comment by PBreed321** [comment]
I am searching for BCH in what was a BTC wallet so when I do as you say it shows $0 BTC. I sent all my BTC to a breadwallet because it was recommended to remove BTC to extract the BCH. I had roughly 0.9 BTC before the split so i know it is in the copay code somewhere.

**Comment by Derrick-** [comment]
I thought you may have already created the "split" BCH wallet. If the split tool is reporting that it didn't find and BCH after scanning your BTC wallet, the problem may be elsewhere. Perhaps someone else has an idea.

**Comment by gabrielbazan7** [comment]
Share your wallet id please, so we can check if there is some BCH in that wallet. Thanks !

**Comment by PBreed321** [comment]
Below are my two copay wallets. I moved any BTC to another wallet. Thank you! 
1NvyWvPK5yV5VaRdHfAMzSWezAdqADFEAm
18EusjbhAdbF2yFfz7JCenE3Dm8wh5Km2u

**Comment by gabrielbazan7** [comment]
That is not the wallet id. You could see your wallet id on your wallet settings ( We need the wallet id of the wallet you said it has some BCH on it )

**Comment by PBreed321** [comment]
Sorry, these are two wallets that I had BTC's in during the split. 

4a626154-0e1a-4a63-bff2-aaa15e6e8814

910b4ca6-3ed1-4cc2-a659-fde1808077fe

**Comment by gabrielbazan7** [comment]
@PBreed321 could you try using the recovery tool ? https://bitpay.github.io/copay-recovery/

**Comment by PBreed321** [comment]
​I have been trying this by switching the Chain to bch/livenet then typing
in my recovery phrase, but nothing seems to show up. Are there other steps
I should be taking in this window?

Where you able to see if there were BCH in the wallets once I provided you
with the ID's?

**Comment by PBreed321** [comment]
Yes, I have those two wallets and I have tried several times. I just played
around with the copay wallets and duplicated my BCH wallets and it appears
I sent the BCH to these wallets addresses on September 3rd which is
strange. I remember trying to extract the BCH, but nothing ever showed. I
don't see these wallet addresses on any BTC or BCH blockchains.

CUZsdrdfddn8GysoBc65wNih8G7axQ1zVr

CQSDRHx199rZG1z7qwou3E1AsJrWFsmquy

**Comment by Wheaties466** [comment]
Does anyone know if this is going to be addressed in an app update? This seems to be breaking for many people.

**Comment by PBreed321** [comment]
I hope so. I found my transaction on the blockchain and it is just sitting
there untouched. I have no idea what wallet it was sent to or how. This
should be interesting. ​

**Comment by PBreed321** [comment]
@gabrielbazan7 how were you able to see that I have dormant BCH in those wallets?

**Comment by PBreed321** [comment]
Copay is working for me now as well.

This is the address where all my BCH
are: CQSDRHx199rZG1z7qwou3E1AsJrWFsmquy

Can anyone find this on the BCH blockchain? I cannot.

**Comment by PBreed321** [comment]
I converted the wallet address and this is the wallet ID I see now where
all my BCH sits. Would someone be able to help me recover this within
copay?

18yKrFbwG6t2Mt5hACUyTiP9FBe6MRsBdK

**Comment by Wheaties466** [comment]
Mine is working too

- Sent from my iPhone

**Comment by karloshagen** [comment]
i have bch on my copay wallet and cant access it, i have tried sending it to another bch wallet and it says the address is not supported. i have tried the recovery tool and it finds nothing!!! can anyone help?

**Comment by gabrielbazan7** [comment]
@karloshagen https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-cant-send-bch

**Comment by karloshagen** [comment]
thanks @gabrielbazan7 i converted the address and it came through. i would like to think im pretty savy with these things but it didnt seem to be that clear on the app without digging around on github
cheers
