### ISSUE TITLE
I couldn't receive BCH in my wallet.

### ISSUE THREAD

**Issue by fizgy** [bitpay/copay#7137]
I did an exchange 16 hours ago (12.11.2017 GMT +3 at 17:52) for Bitcoin Cash using Shapeshit.io. BCH isn't transferred to my wallet wallet. Shapeshift says that transaction is complete but it is not in my wallet.

**Comment by JDonadio** [comment]
Contact to shapeshift support and ask they for your transaction, they must build and broadcast your transaction.
