### ISSUE TITLE
Transaction not found

### ISSUE THREAD

**Issue by mbarlas123** [bitpay/copay#7138]
Hello I've made a transaction to my Bitpay wallet , received the email that it was received. But my balance is not updated, and transaction became invisible after some time. 

https://insight.bitpay.com/tx/218f915f74caa1740297a43289ed9de4ce748c731f06ee01e181186ff2fa39a0

I would appreciate your help..

**Comment by JDonadio** [comment]
Your transaction was dropped from the mempool. That is why you are not able to found it.
