### ISSUE TITLE
TX not found 

### ISSUE THREAD

**Issue by icofunnelz** [bitpay/copay#7141]
After sent the tx vanished then showed back then  vanished again  how can we fix i have all screen shots ,emails etc

https://insight.bitpay.com/tx/6f005bce3c7e9d4c679e5a44cf1643c9897d63a778530a398fe64713041114ef

**Comment by JDonadio** [comment]
Your transaction was dropped from the mempool. That is why you are not able to find it.

**Comment by icofunnelz** [comment]
Where are my funds ?

**Comment by icofunnelz** [comment]
where are my funds ?

**Comment by JDonadio** [comment]
Your funds should be returned to your wallet. You can force a scan manually going to settings > wallet > more opts > wallet addresses > scan addreses for funds

**Comment by icofunnelz** [comment]
No luck but now i can see my funds are sending to my bitpay card but the tx
still not found

**Comment by JDonadio** [comment]
Try the next one: settings > wallet > more opts > transaction history > clear cache

**Comment by icofunnelz** [comment]
Same the transaction shows up as sent a few seconds ago to my Bitpay Card

**Comment by JDonadio** [comment]
Ok thanks for check it. We'll take a look that process to remove the unnecessary item listed.

**Comment by icofunnelz** [comment]
So what's next?

**Comment by icofunnelz** [comment]
TX id still showing  invalid . Never had this issue before as i always send
the with the highest fees

**Comment by icofunnelz** [comment]
Any Luck?
