### ISSUE TITLE
error 1009 copay Ecuador Sudamerica Urgent

### ISSUE THREAD

**Issue by ALBERTBITCOIN** [bitpay/copay#7142]
but because blog.bitpay.com blocks ECUADOR South America

Error 1009 Ray ID: 3ba98ce17a028279 • 2017-11-08 15:26:22 UTC
Access denied
What happened?
The owner of this website (blog.bitpay.com) has prohibited that the country or region in which his IP address (EC) is located to access this website.

How do I recover my account?

ALBERT

ECUADOR

**Comment by JDonadio** [comment]
Hi Albert, please check this out: https://github.com/bitpay/copay/issues/7053
