### ISSUE TITLE
copay wallet not transferring bitcoins at all

### ISSUE THREAD

**Issue by brenz16** [bitpay/copay#7143]
![copay wallet error4](https://user-images.githubusercontent.com/33578627/32740708-a6b0053e-c908-11e7-9640-df6e7431d1c3.png)

15icH1ibHMf4RGebL2g5G8B6PmV67ToWQ4 I been trying to transfer to this account it still has showed up? I don't whats going on?

**Comment by JDonadio** [comment]
Scroll down, tap on "View on blockchain" and copy/paste the transaction id.

**Comment by brenz16** [comment]
![copay wallet error5](https://user-images.githubusercontent.com/33578627/32747608-3006c218-c91e-11e7-895b-b76ceedea21e.png) its says this when i clicked on it

**Comment by brenz16** [comment]
https://insight.bitpay.com/tx/e0754c8907c2d94aa7a5ff10bcf51e8fbb896fbfeecf285d88d07bcc17d80ac7

**Comment by brenz16** [comment]
thats the transaction link

**Comment by brenz16** [comment]
![copay wallet error6](https://user-images.githubusercontent.com/33578627/32748131-2898f7f6-c920-11e7-887a-d23f803cab12.png) its says its been sent but nothing turns up it my blockchain

**Comment by matiu** [comment]
Your transaction has a conflict, probably a double spent.

The raw transaction is:

0100000004a1f3aaa1f19c4234a6d1eca672c3f44574a917afd5dd0b20864ae34ef8fee187010000006b4830450221008535b79522ced91fb7d5322bacaceb5f872bce480a696bc1215fe78e7a9b8d7802206bf275c49ea5a274f7993f6a112ca261dd8dcac72720e887430e745e67bcce08012103a345039eba093ac54ff5abcbc5bc569b8b255adf1b988b595ac74d3405d26e27ffffffffecd623266138ab11928cea3c2957d25d353c76e3d7b4782410599a9e961f5517000000006b483045022100a42a3a49af86f84aa4f52411c142cffc3b18fc4e342b132ad33a89ab3e699974022041bc00602c7eebb383735a99ba69ce24ff3965616988027f243c9b3ae499e5c6012102cf96ddf044bb257956c7f97c2342401db14752580caf846114eb10c41c8b8be2ffffffff67f057974fc397945d0a3869459ddef8fa2c25ea17e25b4d238754f147750f04010000006b483045022100e4f55be9caade25cc7596ade8cc0a5341e9e639a858fea87528c8577d30c0e5c02202e111e3fb6521eb39d2097001519e43d7654fb163582cf279e48cc18fbdf192501210210c2f17be4a8f13c9a5c7a11c038b9de1f935415682e445914143c785cfa40f0ffffffff6cc7c3577ec683821e4c203f942bc7ee237e427cb9760f74e5b2893e818398c51a0000006b483045022100884698a5ff6c2c60dbeb0265e9a9a820fba59fbb5167da47594e4856f938b81c022069ee631cc9dc604a22700ad256d660b6d88abb7e970dfaed528092762118c44501210210c2f17be4a8f13c9a5c7a11c038b9de1f935415682e445914143c785cfa40f0ffffffff014cfc0d00000000001976a91433bf012a64f2f21fa034ba14b59409c6dd5890df88ac00000000


Maybe on of the inputs of your tx was used or dropped before your TX was confirmed. The TX cannot be broadcasted any more.

The TX decoded is:

```
{
   "lock_time":0,
   "size":636,
   "inputs":[
      {
         "prev_out":{
            "index":1,
            "hash":"87e1fef84ee34a86200bddd5af17a97445f4c372a6ecd1a634429cf1a1aaf3a1"
         },
         "script":"4830450221008535b79522ced91fb7d5322bacaceb5f872bce480a696bc1215fe78e7a9b8d7802206bf275c49ea5a274f7993f6a112ca261dd8dcac72720e887430e745e67bcce08012103a345039eba093ac54ff5abcbc5bc569b8b255adf1b988b595ac74d3405d26e27"
      },
      {
         "prev_out":{
            "index":0,
            "hash":"17551f969e9a59102478b4d7e3763c355dd257293cea8c9211ab38612623d6ec"
         },
         "script":"483045022100a42a3a49af86f84aa4f52411c142cffc3b18fc4e342b132ad33a89ab3e699974022041bc00602c7eebb383735a99ba69ce24ff3965616988027f243c9b3ae499e5c6012102cf96ddf044bb257956c7f97c2342401db14752580caf846114eb10c41c8b8be2"
      },
      {
         "prev_out":{
            "index":1,
            "hash":"040f7547f15487234d5be217ea252cfaf8de9d4569380a5d9497c34f9757f067"
         },
         "script":"483045022100e4f55be9caade25cc7596ade8cc0a5341e9e639a858fea87528c8577d30c0e5c02202e111e3fb6521eb39d2097001519e43d7654fb163582cf279e48cc18fbdf192501210210c2f17be4a8f13c9a5c7a11c038b9de1f935415682e445914143c785cfa40f0"
      },
      {
         "prev_out":{
            "index":26,
            "hash":"c59883813e89b2e5740f76b97c427e23eec72b943f204c1e8283c67e57c3c76c"
         },
         "script":"483045022100884698a5ff6c2c60dbeb0265e9a9a820fba59fbb5167da47594e4856f938b81c022069ee631cc9dc604a22700ad256d660b6d88abb7e970dfaed528092762118c44501210210c2f17be4a8f13c9a5c7a11c038b9de1f935415682e445914143c785cfa40f0"
      }
   ],
   "version":1,
   "vin_sz":4,
   "hash":"e0754c8907c2d94aa7a5ff10bcf51e8fbb896fbfeecf285d88d07bcc17d80ac7",
   "vout_sz":1,
   "out":[
      {
         "script_string":"OP_DUP OP_HASH160 33bf012a64f2f21fa034ba14b59409c6dd5890df OP_EQUALVERIFY OP_CHECKSIG",
         "address":"15icH1ibHMf4RGebL2g5G8B6PmV67ToWQ4",
         "value":916556,
         "script":"76a91433bf012a64f2f21fa034ba14b59409c6dd5890df88ac"
      }
   ]
}
```

**Comment by brenz16** [comment]
How can I get my money back?

**Comment by kater19** [comment]
Did you get your money back? I think I am in the same boat.

**Comment by kater19** [comment]
Did you get your money back? I think I am in the same boat.

**Comment by brenz16** [comment]
Yup I had to install it on my laptop I think my phone to slow for the conformations to verify the transactions
