### ISSUE TITLE
Bitcoin Cash Strange transaction.

### ISSUE THREAD

**Issue by joshuatancq** [bitpay/copay#7144]
Hello

Something terribly strange happned today. When i checked copay i noticed i was short by 0.5 BCH. And when I checked the transactions to my surprise there is a transaction back dated to Sep 2017. I have never made such a transaction and I checked my wallet pretty much everyday.

The thing is I never made this transaction and its impossible that a backdated transaction would just appear out of nowhere. How can this happen? How can I lose 0.5bch out of the blue. I get an error 525 when i try to view on block chain.

![transaction](https://user-images.githubusercontent.com/33636677/32743732-3563a8b0-c8e8-11e7-920a-772707f6f7cb.JPG)

Please help...

**Comment by JDonadio** [comment]
Unfortunately there is nothing we can do. The keys are stored in your device, not in our servers or in the cloud, so you are the only one with access to move the funds. Please, change your passwords and any security capability on your wallet. 

My recommendation is create a new fresh wallet, make the backup process, set spending password and (or) fingerprint, and also add a pin or fingerprint to lock/unlock your app.

**Comment by joshuatancq** [comment]
You mean IF i got hacked, transactions can be backdated???

I only got my BCH in october, the transactions backdate to september.
