### ISSUE TITLE
Copay not showing any BCH

### ISSUE THREAD

**Issue by Wheaties466** [bitpay/copay#7146]
I just checked my wallet a few days ago and the BCH was showing properly. But now it is showing a 0 balance for BCH. Was there a change I was unaware of? Is there a reason it would be showing no BCH?

**Comment by matiu** [comment]
We had a problem with our backend. It should be fine now.

Can you please check the following:

Procedure 1:
Go to Settings > [Choose Wallet ] > More Options > Transaction History > Clear Cache.

and check.

If still broken, or if the balance is not OK:
Procedure 2:
Go to Settings > [Choose Wallet ] > More Options > Wallet Addresses > Scan Addresses for Funds.

Thanks and sorry for the inconvenience.

**Comment by matiu** [comment]
please seehttps://github.com/bitpay/copay/issues/7148#issuecomment-344134740
