### ISSUE TITLE
Claimed BCH funds show insight 

### ISSUE THREAD

**Issue by clonea1** [bitpay/copay#7148]
a week or so ago I enabled BCH on my walled did a scan and claimed my BCH however today when I went to make some action (BCH was doing VERY good) I am unable to do anything with the funds

![bch error](https://user-images.githubusercontent.com/33642521/32756239-25b010ca-c8a7-11e7-9cc8-5c02b9e62d5b.PNG)
![bch error2](https://user-images.githubusercontent.com/33642521/32756248-3071ed9e-c8a7-11e7-8ea0-657ff361adca.PNG)
![bch error 3](https://user-images.githubusercontent.com/33642521/32756263-42599cc8-c8a7-11e7-9f42-9301a6ac13c1.PNG)

**Comment by paOol** [comment]
same here.
v3.8.6

**Comment by Magalon** [comment]
Some people seem to have an issue with that at the moment.. I do to..

**Comment by ffxsam** [comment]
Same here. Is this a Copay issue or BCH network issue? Doesn't instill a lot of confidence..

**Comment by clonea1** [comment]
ok so this may just be some type of burp and our stuff is not lost ?

**Comment by PBreed321** [comment]
I am currently have the issue. Any pointers?

**Comment by paOol** [comment]
@clonea1 they are not lost because they have not been moved (we can't move them).

this is entirely speculation on my part  but i think it may be either

- Core supports are DDoS'ing the bitpay node/server and thus the bitcoin cash chain is unable to communicate.

or

- It's related to the bitcoin cash hardfork earlier today and bitpay needs to upgrade bitcore or copay accordingly.

**Comment by matiu** [comment]
We had a problem with our backend. It should be fine now.

Can you please check the following:

 Procedure 1:
 Go to Settings > [Choose Wallet ] > More Options > Transaction History > Clear Cache.

and check.

If still broken, or if the balance is not OK:
Procedure 2:
 Go to Settings > [Choose Wallet ] > More Options > Wallet Addresses > Scan Addresses for Funds.

Thanks and sorry for the inconvenience.

**Comment by RussianNeuroMancer** [comment]
It's fine for me now, thanks for fix!

**Comment by matiu** [comment]
thanks for the update.

**Comment by PBreed321** [comment]
Copay is working for me now as well.

This is the address where all my BCH
are: CQSDRHx199rZG1z7qwou3E1AsJrWFsmquy

Can anyone find this on the BCH blockchain? I cannot.

**Comment by clonea1** [comment]
I am back online, in fortunitlly I have missed the oppurunity to make a stack of money :(

**Comment by matiu** [comment]
@PBreed321 you need to translate the address to use the 1xxx addr format. check https://github.com/bitpay/address-translator

**Comment by PBreed321** [comment]
Okay, this is the translated wallet which shows zero transactions on the
blockchain. I am trying to log onto bch-insight.bitpay.com , but having
server issues.
18yKrFbwG6t2Mt5hACUyTiP9FBe6MRsBdK
<https://blockchain.info/address/18yKrFbwG6t2Mt5hACUyTiP9FBe6MRsBdK>

**Comment by ffxsam** [comment]
>We had a problem with our backend. It should be fine now.

So, how exactly does Copay work? I probably don't fully understand how Bitcoin works, but I thought software wallets connect directly to the blockchain. Is each wallet software (Copay, Coinbase, Bread, etc) running their own server that connects to the blockchain?

**Comment by clonea1** [comment]
well weird thing happened could be because I don't know what I am doing but I tried to send my bch to bittrex and it looks like I only succeeded in sending it to my self shows 'moved' instead of sending/sent

**Comment by matiu** [comment]
@PBreed321 you need to check it on a BCH block explorer, like https://blockdozer.com/insight/

**Comment by matiu** [comment]
@ffxsam 
>So, how exactly does Copay work?

See Readme at https://github.com/bitpay/copay

**Comment by matiu** [comment]
@clonea1  do the procedure described at
https://github.com/bitpay/copay/issues/7148#issuecomment-344134740

**Comment by clonea1** [comment]
@matiu I tried that, did send put in the bittrex wallet and it still wen back to to personal wallet bch
