### ISSUE TITLE
Err msg: Could not update wallets

### ISSUE THREAD

**Issue by pradeeprajr93** [bitpay/copay#7149]
Unable to send my BCH due to this error. Please help.

**Comment by matiu** [comment]
We had a problem with our backend. It should be fine now.

Can you please check the following:

Procedure 1:
Go to Settings > [Choose Wallet ] > More Options > Transaction History > Clear Cache.

and check.

If still broken, or if the balance is not OK:
Procedure 2:
Go to Settings > [Choose Wallet ] > More Options > Wallet Addresses > Scan Addresses for Funds.

Thanks and sorry for the inconvenience.

**Comment by sreenicam** [comment]
Hi,

I am still seeing the same issue of Insight error even after doing what you suggested about above about clearing cache, scan address for funds. Please help! I am not able to transact BTC
