### ISSUE TITLE
Transit Bitcoin Cash to the address Bitcoin Core Wallet Copay

### ISSUE THREAD

**Issue by Denozavr699** [bitpay/copay#7150]
Ladies and gentlemen! On November 13, 2017 I sent BTH in the amount of 7.0059 C of the purse 3L829MqLnugmtWtiuqV538uJww98JBWZSz to the purse of BTC 13PeHUay1eubEKmoVPLzwWofUsDd6M32wy. information about the receipt of funds on the purse BTC Copay came to me by e-mail, and for some time was displayed in the purse. at the same time there were no transfers to the balance. Help to understand please.

**Comment by paOol** [comment]
you can't send BCH to a BTC address.

well you can, but it doesn't cross chains. you send BCH to a BCH address of `13PeHUay1eubEKmoVPLzwWofUsDd6M32wy`

see here.
https://blockchair.com/bitcoin-cash/address/13PeHUay1eubEKmoVPLzwWofUsDd6M32wy

**Comment by Denozavr699** [comment]
I am very grateful to you, you reassured me. maybe you know how to make it so that the wallet would display the arrival correctly in the application?

**Comment by JDonadio** [comment]
This could be helpful as well: https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-sent-bch-coins-into-a-btc-address-what-can-i-do-to-recover-my-bch-coins
