### ISSUE TITLE
Copay testnet "Could not update wallet: Insight Error" - Problem with desktop/chrome app wallet

### ISSUE THREAD

**Issue by denisr1989** [bitpay/copay#7152]
Using desktop/chrome app wallet with testnet, shown Insight Error. No possibility to send/transfer btc  via testnet.

![image](https://user-images.githubusercontent.com/18192442/32772693-4d4fdd26-c92f-11e7-9d76-cc4d243ef8f5.png)

Version: 3.8.2

**Comment by tstrg** [comment]
I am facing the same issue.

**Comment by Emanuelserrano** [comment]
Estoy con ese problema no se actualisa la wallet
Ayuda por favor

**Comment by JDonadio** [comment]
We are very sorry about that, please check: https://github.com/bitpay/copay/issues/7149#issuecomment-344134793
