### ISSUE TITLE
problems with sweeping paper wallet

### ISSUE THREAD

**Issue by thor23111** [bitpay/copay#7153]
I was sweeping 3 of mine BTC paper wallets with the copay iOS app. Two times it worked perfectly fine the third transactions is shown as proceeding but doesn't arrive (since 30 hours). We talk 3.998544 BTC
pls support me
![img_2970](https://user-images.githubusercontent.com/33654595/32773886-ea7b28e4-c92a-11e7-99b3-ddb67f93040b.PNG)
![img_2971](https://user-images.githubusercontent.com/33654595/32773924-08be7a72-c92b-11e7-9205-2fc112a1c9e9.PNG)

**Comment by JDonadio** [comment]
You have to wait, the bitcoin network is congested and your transaction could be hanging for a while. Don't worry, your coins are safe, even if the transaction is never confirmed and dropped from the mempool, these funds will not left your paper wallet and you will be able to sweep it again.

**Comment by thor23111** [comment]
thx for feedback
I’ll try

brgds
Alex
