### ISSUE TITLE
Amount too low to spend

### ISSUE THREAD

**Issue by ffxsam** [bitpay/copay#7159]
I'm seeing a warning in my wallet that my balance is too low to spend. I'm not seeing a way to set my desired transaction fee anywhere. There is a network fee policy setting, but I can only set it to urgent, priority, normal, economy, or super economy, and currently the three latter are all the same (709 satoshis/byte).

This is kinda crazy. Is this telling me in order to spend my $30, it would cost me $30 in fees?

**Comment by JDonadio** [comment]
You can use the custom option and set an amount manually. If you are not able to see that option, please update your wallet.

**Comment by ffxsam** [comment]
@JDonadio What do you mean update my wallet? The Copay app is up to date. There's no "Custom" option.

![image](https://user-images.githubusercontent.com/12532733/32800744-c930bb20-c940-11e7-9313-71f9fc20fbab.png)

**Comment by JDonadio** [comment]
I mean at the confirm time.

<img width="397" alt="bitpay_-_secure_bitcoin_wallet" src="https://user-images.githubusercontent.com/13851807/32800884-4c61456e-c95a-11e7-845a-6902ba4a9fad.png">

Clicking on that option will display the pre-set list of levels and additionally the custom option.

**Comment by ffxsam** [comment]
Ah, thank you!

**Comment by trustee79** [comment]
I have the same issue with .01363btc. Which is roughly $200.00 I just wanna know what l have to do to get my funds unstuck. I've been waiting for days. No response from support at all.

**Comment by 3dPrinter44** [comment]
Recently my Copay started to say that 2 payments I received weeks ago are "Amount too low to spend".

I received:
 .016 BTC on 12/01/17
 .014 BTC on 11/17/17

I don't see how the amount could be too low since both are about $200, and neither said it was too low when I received them weeks ago.
