### ISSUE TITLE
How to transfer from BTC wallet to BCH within Copay?

### ISSUE THREAD

**Issue by ffxsam** [bitpay/copay#7160]
It's not immediately intuitive how to do this. I've tried tapping "Send" and then using "Transfer to Wallet". I choose my BCH wallet and enter an amount, but it always says insufficient funds. I guess for transferring I would expect a typical interface where I choose the "From" and "To" and then specify an amount.

**Comment by gabrielbazan7** [comment]
You can't transfer BTC to a BCH wallet

**Comment by JDonadio** [comment]
Why do you want to transfer BTC into a BCH wallet?

**Comment by ffxsam** [comment]
@gabrielbazan7 Ahh ok.. you said in another thread that it was possible. https://github.com/bitpay/copay/issues/7133#issuecomment-343785706

So I'll have to withdraw from BTC to my bank, then buy BCH, sounds like.

**Comment by gabrielbazan7** [comment]
Sorry. I misunderstood. You have to use an exchange to buy BCH.
