### ISSUE TITLE
Bitcoins are still sending!

### ISSUE THREAD

**Issue by NNeelissen** [bitpay/copay#7162]
Hi a few days ago I have sent twice some bitcoins to an transfer company but it is never sent. It says that it is still busy with sending. Could you cancel the sending? Because the bitcoins is already gone from my wallet.

This is a screenshot from my phone:
![copay](https://user-images.githubusercontent.com/33593147/32806663-a26d2f76-c98d-11e7-8acc-729980e74968.png)

I hope you can help me.

Kind regards Naut Neelissen

**Comment by Roddy1219** [comment]
@NNeelissen  What is the transaction ID ？ I can help you speed up。

**Comment by allenvivas** [comment]
I try to transfer my payments account and it tells me insufficient funds ... and I own 0.00076000 satoshis

**Comment by JDonadio** [comment]
@NNeelissen the bitcoin network is congested, you just have to wait... unfortunately there is nothing  to do.
