### ISSUE TITLE
BTC not sent

### ISSUE THREAD

**Issue by williamtech814** [bitpay/copay#7163]
I sent a transaction a few days ago but I cannot see it on the blockchain. Here are some screenshots: http://prntscr.com/hal4ic http://prntscr.com/hal4kz

https://insight.bitpay.com/tx/c53245b44a099906690e7d9ea737b0541f3e3b0642ec7dca0bbbd4c07fa3ab1c

**Comment by Roddy1219** [comment]
Are you sure?   I bitpay wallet is OK.  What version is it?

**Comment by allenvivas** [comment]
I try to transfer my payments account and it tells me insufficient funds ... and I own 0.00076000 satoshis

**Comment by Roddy1219** [comment]
@allenvivas  Transaction  fee is too low  or your select custom fee

**Comment by JDonadio** [comment]
Your transaction doesn't exist in the blockchain: https://blockchain.info/search?search=c53245b44a099906690e7d9ea737b0541f3e3b0642ec7dca0bbbd4c07fa3ab1c

Was dropped from the mempool.
