### ISSUE TITLE
Transaction

### ISSUE THREAD

**Issue by kandy81** [bitpay/copay#7164]
Dear sir

Sorry to inform that my withdrawal transaction show that has been confirm but my account not show th amount , please help me to check th below transaction link thank u 

https://insight.bitpay.com/tx/8cc3242ac43b7b4a0966cfc0e43ea5a16609d1f349ada420a38b662cd3bc8450

**Comment by Roddy1219** [comment]
@kandy81  The transaction not have problem, Please restart your bitpay wallet program
