### ISSUE TITLE
portafoglio

### ISSUE THREAD

**Issue by francometal** [bitpay/copay#7165]
buongiorno,ho caricato dei bitcoin ma il portafogli risulta vuoto
![copay](https://user-images.githubusercontent.com/33685079/32827859-cd6f2cbe-c9ed-11e7-8d15-ddbe89cc4b29.PNG)

**Comment by JDonadio** [comment]
@francometal you have to wait until your transaction get confirmed. Then you'll be able to see your change amount available to spend it.

You can change this behavior in settings > advanced > use unconfirmed funds. But it's not recommended due the bitcoin network congestion.
