### ISSUE TITLE
recover BCH with copay wallet 

### ISSUE THREAD

**Issue by stone2y** [bitpay/copay#7166]
I'm using 5 of 3 multi sign copay wallet. 
but I can not find one of the copayer's private key. 

Is that possible to recover BCH from my wallet? 

is there any other possible ways under this situation?

**Comment by JDonadio** [comment]
Your wallet is N of M (3 of 5 in your case). If you have at least 3 backups you'll be able to recover your funds. If you have less than 3 unfortunately there is nothing to do.
