### ISSUE TITLE
Problem receiving transaction

### ISSUE THREAD

**Issue by Sergioamiz** [bitpay/copay#7167]
Hi,
I just sent an amount of bitcoins to an old address of my copay account. It was an address generated on October 23rd. The transfer did not arrive yet. Did i lose my money?
May i do something to get it back my money?

Thank you.

**Comment by JDonadio** [comment]
The bitcoin network is congested and many transactions are hanging, there is nothing to do unfortunately... only wait. If the address is "old" have nothing to do with the confirmation time, don't worry, you will not lose your funds.

**Comment by Sergioamiz** [comment]
Hi,

I still didn't receive my funds into my copay wallet with the address i mentioned in my previous post.
It's been 8 hours since i did the transfer.
Is it normal? Is the network still congested?
