### ISSUE TITLE
Transaction low??

### ISSUE THREAD

**Issue by cislerk** [bitpay/copay#7168]
I have a message of my transaction that is too low for fees?? Its over 40 dollars in btc i dont untherstand!  Can you help me??

**Comment by cislerk** [comment]
I use copay.. i gad the same isue eith a very low transaction long befour but was for a dollar.. now is 40 dollars

**Comment by JDonadio** [comment]
That message depends on the bitcoin network fees. Please check this out: https://github.com/bitpay/copay/wiki/COPAY---FAQ#amount-too-low-to-spend
