### ISSUE TITLE
BCC transfer issue

### ISSUE THREAD

**Issue by auntiekristin** [bitpay/copay#7169]
I tried moving my BCC from my freewallet to my newly created bitpay BCC wallet. On the free wallet side it shows almost 250 confirmations and that it is complete but bitpay BCC wallet shows no transactions. I have cleared app cache and scanned for funds but it comes up with nothing. It's been over 3 days. I feel like I made a huge mistake

Transaction details...

http://blockdozer.com/insight/tx/f7775fa3508b25bfb96cfc7fc936b3854ed29497b0bd3831105b721394104297

**Comment by JDonadio** [comment]
Please open your wallet and go to settings > wallet > more options > wallet addresses. Check all the addresses generated and send they to `javier@bitpay.com`. I'll check your addresses.

**Comment by qtrf417** [comment]
Please how Can I Tranfer my Bitcoin Cash from copay address to another address?? When I try to, it will ask me to translate my address. How Can I translate and paste??

**Comment by JDonadio** [comment]
Use: https://bitpay.github.io/address-translator/
Or use the prefix: `bitcoincash:`xxxxx
