### ISSUE TITLE
Which order do Copay create new multisig addresses

### ISSUE THREAD

**Issue by Mrostgaard** [bitpay/copay#7170]
So lets say i have 2-of-3 multisig wallet. 
Is it just ordered smallest to largest keys using a simple sort algorithm?

**Comment by dabura667** [comment]
Yup. Just a simple canonical sort.

lowest msb first.

**Comment by Mrostgaard** [comment]
Okay now i have another problem. How is return address calculated. I have a UTXO 0.01BTC  and want to send 0,001 BTC. It will cost me 0.004 BTC in TX fee. I send the 0,001 to another address. I pay the tx fee and because it is a HD wallet it creates a new address to send the change back to. How do i derive this address? I have run through the first 50 multisig address and couldn't find one matching the address i can see in copay?

**Comment by Mrostgaard** [comment]
Okay, so i found them deriving my bip32  xpubs using depth 1 instead of depth 0. Are these the only 2 depth used? Or should i check BIP32 to depth N?
