### ISSUE TITLE
recover BCH by using copay app's option 

### ISSUE THREAD

**Issue by stone2y** [bitpay/copay#7175]
I'm using copay app to recover BCH. 
It 3 of 5 multi sign wallet. 

1 question 
All 5 copayer already select to support for BCH and scan for funds. 
after that All chose " duplicate for BCH" nothing showed, "0" balance. 
but when the scan was done, it showed some balance of BCH. 

2. question. 
When I was trying to find my private key over time phone. 
I can choose setting and back up again, then I can see the exactly private key was backed up before. 

but why some of my phone and computer didn't show the backup phrase. only showed, " wallet recovery phrase not available"
how to find private key over my copay app via my mobile phone? 

Thank you

**Comment by gabrielbazan7** [comment]
You mean the phrase for your BCH wallets? if the BCH wallet was duplicated from a BTC wallet, they share the same recovery phrase.

We are sending a release to make the private key available for the user. Right now is not possible.
