### ISSUE TITLE
How can $80 worth of BTC be too low to spend? I have multiple error messages

### ISSUE THREAD

**Issue by Chris4678** [bitpay/copay#7177]
Screenshot: https://imgur.com/a/24Tds

I have multiple transactions in this price range that all say "amount too low to spend" I feel like 0.011 BTC should easily be enough to spend or how will this currency ever going to be of any practical value? Is this a real issue or just an error?

**Comment by paOol** [comment]
my guess?

is the address made up of a bunch of tiny transactions adding up to $80?
like lets say 80 $1 transactions?

that could be why. The amount of data that transaction takes up might be very costly with current BTC congestion. That would never  happen on Bitcoin Cash.

**Comment by Chris4678** [comment]
This is 1 transaction that was sent to me from NiceHash. I do not know how it would be made up of a bunch of small transactions. If it is how do I consolidate all of my BTC into one place? Would sending everything to a Trezor do this?

**Comment by junderw** [comment]
Copay has a weird way of calculating this.

It assumes that you make a transaction with only this input and two outputs, then it checks to see if the fees from that (using normal fee rate) are greater than 30% of the amount of the input.

Also, it only checks this at the time of receiving... you received this transaction during a high fee time... 1200 sat/byte was common... so the calculation of "too small to spend" is skewed...

What type of wallet is yours? Multisig? is it 2 of 3? or 4 of 6? or what?  (This will help find out how large your single input transaction should be)

**Comment by Chris4678** [comment]
How do I know what type of wallet I have? I never changed anything from
when I first downloaded the app.

**Comment by cynhen** [comment]
My amount is also too low (don't know why).  Isn't it supposed to automatically transfer into my coinbase acct?

**Comment by JDonadio** [comment]
Please read https://github.com/bitpay/copay/wiki/COPAY---FAQ#amount-too-low-to-spend

That message is just to warn you but you'll be able to move these funds. Probably your best option to move these funds will be set a custom fee (at confirm time) .
