### ISSUE TITLE
Please have devs sign release key 5CD600A61112CFA1

### ISSUE THREAD

**Issue by jonathancross** [bitpay/copay#7180]
Would be great if recognized devs sign the release key so that we can be assured of its authenticity.

Good candidates:
* `15EDAD8D9F2EB1AF` @cmgustavo
* `EC1F4E04B2BFA730` @JDonadio 
* `02470DB551277AB3` @matiu
* `D813A67D567D6C88` @ajp8164 (Please upload key to GH too :-)

Ideally devs should also cross-sign each other's keys as well.

**Comment by BGalliotti** [comment]
We are closing this thread, please if you still need support, open a new one, we will happy to help you.
Thanks.

**Comment by matiu** [comment]
Btw we will to this next week. Thabks for the suggestion.

**Comment by jonathancross** [comment]
Only @matiu signed the key from that list...  Guess it doesn't make much difference after 1.5 years of being ignored though.

**Comment by matiu** [comment]
we are doing it now, with current most active devs: @cmgustavo @gabrielbazan7 @rastajpa @Gamboster . Thanks for you help and patience, we are reorganizing github support.
