### ISSUE TITLE
BTC Transaction in Copay Wallet that I Didn't Make

### ISSUE THREAD

**Issue by pallen812** [bitpay/copay#7181]
Hi, 

I have a sent transaction in my Copay Wallet that I didn't make. It appears to be still going through the blockchain and confirmation. The sent amount is more than I have available in my wallet too but my wallet has not been completely emptied. I also don't seem to have received an email notification to say payment sent. 
1. How has payment been sent from my wallet when I didn't do it? 
2. If the sent amount is far greater than the available amount, will this get stopped and reverted? 
3. Is there anyway of finding out whats happened? 

![btc](https://user-images.githubusercontent.com/33702809/32861108-a9175202-ca4b-11e7-85d8-30dbe8a1f9d5.jpg)

**Comment by pallen812** [comment]
Since the send transaction above I have had 3 Received transactions into my wallet but the amount has not been added to my total amount in the wallet. 

Anyone know what is going on here? 

![image](https://user-images.githubusercontent.com/33702809/32895428-f36b4502-cad7-11e7-9d21-48ec28932361.png)

**Comment by pallen812** [comment]
Hi Gabriel. Thanks for getting in touch. I followed both steps above and everything looks as the same, just as the last screenshot.

**Comment by gabrielbazan7** [comment]
Ok. So, it might be a problem on the backend. But don't worry your money is safe. Thanks for the report. We will let you know when it start working as expected.

**Comment by pallen812** [comment]
I hope you're right Gabriel. Thanks!

**Comment by matiu** [comment]
Hi @pallen812 In order to make investigate further, we need information about your wallet (an address, for example). Could you please write us directly to matias@bitpay.com.

**Comment by matiu** [comment]
It seems your wallet have some transactions not crafted by Copay. We have recently installed a fix to handle them correctly. Can you please clear the TX cache and try again?

**Comment by pallen812** [comment]
Hi,

I’ve cleared the TX cache and pasted the before and after results. How is appearing as a Received transaction and after clearing the cache becomes a Sent transaction?

Before clearing cache….
[cid:image005.jpg@01D35F1D.053C13F0]

After clearing cache….
[cid:image006.jpg@01D35F1D.053C13F0]

**Comment by swcrusade** [comment]
Hello Pallen812, were you able to get any further than I?  I do like the messages from  gabrielbazan7 "Ok. So, it might be a problem on the backend. But don't worry your money is safe. Thanks for the report. We will let you know when it start working as expected." however at the end of the day for me, I never got my BTC back, so I am SOL and have deleted the wallet from copay.  I will set another up, copay is a great wallet, I am just not sure what can be done.

**Comment by Daniel18R** [comment]
I have the same issue. I had .15 btc yesterday and now its empty. Can someone help me?

**Comment by matiu** [comment]
@pallen812 

> How is appearing as a Received transaction and after clearing the cache becomes a Sent transaction?

Because that transaction was not originated from Copay. Had multiple inputs, some from your wallet, and some from others, so our backend was not parsing it correctly. Check the TX in a block explorer.

**Comment by matiu** [comment]
@Daniel18R  please provide screenshots / txid or some other element so we can check what is happening.

**Comment by matiu** [comment]
@swcrusade @gabrielbazan7 was wrong.  The wallet had a transactions not crafted by Copay, therefore was been parsed incorrectly by our backend. We fix that to handle better the situation in the future.

**Comment by Daniel18R** [comment]
Thanks.
The address sent to is 1HyURNAt7fGMp8jCxN8BjPodtEZEimHwfZ

I have no idea who's address that is

Transaction ID
0a1ada58282e8b0c5d1bd386424c50df00db75ac2f98e8aa233f8df32ee6af7f

**Comment by matiu** [comment]
@Daniel18R I see transaction 0a1ada58282e8b0c5d1bd386424c50df00db75ac2f98e8aa233f8df32ee6af7f

It has already 28+ confirmations. 

If you are the owner of that wallet and you do not recognize that transaction, your keys must have been compromised, and someone else signed that transactions using your keys.

**Comment by Daniel18R** [comment]
I didnt give the keys to anyone. I wrote them on a small piece of paper and
saved it. Can it be tracked to the wallet that was sent to?
