### ISSUE TITLE
Copay blockchain location 

### ISSUE THREAD

**Issue by jaanos123** [bitpay/copay#7183]
Recently installed Copay and my HDD is basically full and my internet provider has said I've used all my allowance - assuming this is the 96 GIG bitcoin blockchain being downloaded... 

I would like to move this to an external HDD or at least off my SS. Only problem is I can't find where it is? 

Any help or guidance on how to find and move this would be very much appreciated. 

Cheers

**Comment by matiu** [comment]
no, Copay is not a full node. You can check https://bitcore.io/ for a full node.
