### ISSUE TITLE
Still ain’t get my btc 

### ISSUE THREAD

**Issue by ChevBenzo** [bitpay/copay#7190]
It’s been 1week son and I still ain’t get my btc yet what the hell son

**Comment by ChevBenzo** [comment]
When am I going to get my shit

**Comment by ivanmervill** [comment]
I'm having the same problem

**Comment by JDonadio** [comment]
Explain your issue so we can assist you better

**Comment by ChevBenzo** [comment]
Never mind my account is fixed
