### ISSUE TITLE
Transfer all funds from wallet

### ISSUE THREAD

**Issue by uralovs** [bitpay/copay#7194]
Hey all

I would like to see a new feature in BitPay wallet which allows me to transfer all available funds from wallet, such that nothing remains in wallet. 
Currently, to transfer all funds, i need to do it in two steps. First, i find out the approximate transfer fee by "pretending" to transfer the sum. Once i know the approximate fee, i need to subtract this fee from "all" amount and then initiate the transfer of "all minus fee" amount. I'd love the app to do this instead of me.
For example, lets say i have 0.01 BTC in my wallet and i want to transfer all of that. I first find out the fee by "pretending" to transfer an amount close to that, e.g. 0.008. Next screen gives me the fee for operation, e.g. 0.001007. Now, that i know the fee, i return to previous screen and select "all minus fee" amount to be transferred, which should result in 0.0 BTC left in my wallet, i.e. now i transfer 0.01 - 0.001007 = 0.008993. 

I have seen this "Transfer All" feature in other places which i found very convenient.

**Comment by Jacobbubble** [comment]
The Bitpay wallet already has a max send feature.

At the send screen, at the top right there are three dots. Select them and you'll get an option to "Send max amount".

**Comment by matiu** [comment]
The feature is already in Copay. @Jacobbubble is right. Thanks.

**Comment by uralovs** [comment]
Great stuff, didn't notice it there!
Amazing product, many thanks
