### ISSUE TITLE
Copay Recovery Tool error: "Could not build tx: TypeError: Address has mismatched network type."

### ISSUE THREAD

**Issue by tab00** [bitpay/copay#7197]
My original bitcoin wallet is an old BIP45 wallet, so the app could not automatically duplicate the BCH into a new wallet.

The BCH balance shown is correct, so the recovery tool scan was successful.

After the scan I get the above "Address has mismatched network type" error when attempting transfer of the BCH.

The destination address was from a newly created ordinary livenet BCH wallet in Copay version 3.8.6.

Please fix the problem so that I can transfer the funds from the scan into the new BCH wallet.

Thank you.

**Comment by matiu** [comment]
please see https://support.bitpay.com/hc/en-us/articles/115004671663-BitPay-s-Adopted-Conventions-for-Bitcoin-Cash-Addresses-URIs-and-Payment-Requests

**Comment by tab00** [comment]
So what are we meant to enter in the Destination Address field of the recovery tool?

Simply copying the address from a Copay BCH wallet and pasting it into the Destination Address field doesn't work (when intuitively it should), so after reading that page I added the prefix "bitcoincash:" to the address but then the error message "Please enter a valid address." appears after pressing the Transfer button.
