### ISSUE TITLE
My wallet got cleared during the night

### ISSUE THREAD

**Issue by Daniel18R** [bitpay/copay#7199]
I have an issue with my wallet as well. I received an amount yesterday and today everything i had on the wallet is gone. I had .15 anf now its empty

**Comment by matiu** [comment]
Rep #7181

**Comment by Daniel18R** [comment]
Can you assist on the issue before closing it. Thanks

**Comment by matiu** [comment]
I have replay ot the other ticket you posted exactly the same.

**Comment by parkermor** [comment]
@Daniel18R 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
