### ISSUE TITLE
Problem with recovery

### ISSUE THREAD

**Issue by aslakandersen** [bitpay/copay#7201]
Hi,

I have used the recovery tool to find som wrongly sent bitcoin cash.

Now this is the status, and has been for a few days
https://bch-insight.bitpay.com/tx/68a90858b2a8ba3e8e19864aec3c406eac7eabeb52d4cd72d91a3610c4409609

The recovered amount wont send. And I believe i know why.
The  0,01446407 is an amount that I had in my wallet of bitcoin earlier - sent from kraken Ce2ga91EFW1smSmnfxVFyKL7BRQFFR7u8W 
But it should not be there anymore because I moved that amount already https://insight.bitpay.com/tx/2b252bc2287ddd5e6b908f3ab0bcd54d5e41181fe7c1a55fc91c7b9368690f74

The 0,58261 is a bitcoin cash amount and the amount I was trying to recover, but are not able too

Why is the recovery tool finding that bitcoin amount? How can I fix this?

**Comment by aslakandersen** [comment]
Hi, is this the only way to get help with copay? I would really like to solve this issue

**Comment by aslakandersen** [comment]
After studying this more, I see that I need access to my privkey if I should be able to do this since the recovery tool is not able to differentiate between the amounts that the recovery tool found. I have seen that this on the way for copay. When will this be rolled out?

**Comment by gabrielbazan7** [comment]
Sorry, I can't understand your issue. Set the chain as 'bch/livenet' to find Bitcoin Cash.

**Comment by aslakandersen** [comment]
@gabrielbazan7 Hi, I find the bitcoin cash using the recovery tool with chain bch/livenet, see #7151 
The problem is that the recovery tool find bitcoin cash that I already have sent to another wallet as BITCOIN (not bitcoin cash) which you can see by the links above.

So for some reason the tool found something that should not exist. I'm not able to explain it better now

**Comment by gabrielbazan7** [comment]
you can't send bitcoin cash as bitcoin.

**Comment by aslakandersen** [comment]
Problem solved, suddenly the "wrong" transaction didn\t arrive in the recovery tool
