### ISSUE TITLE
BCH alternative currency value not showing

### ISSUE THREAD

**Issue by coincrazy** [bitpay/copay#7202]
I successfully recovered my BCH into a new bitpay wallet via the method described. My Bitcoin Cash wallet shows my BCH but it does not show the alternative currency value. My Bitcoin (BTC) wallet shows both my BTC and the alternative currency value. Am I doing something wrong or is this a know issue? Thanks

**Comment by JDonadio** [comment]
Sorry about that, for now it's only available in USD.

**Comment by coincrazy** [comment]
thanks very much for your reply.

**Comment by pryetranka** [comment]
@JDonadio Any ETA on this for other currencies?
