### ISSUE TITLE
Sent Bitcoin Cash to BTC address by mistake (CoPay Wallet)

### ISSUE THREAD

**Issue by spotworks** [bitpay/copay#7204]
I sent BCH (Bitcoin Cash) funds from an exchange house to my BTC CoPay wallet address by mistake.  Is there a way to get it back?

**Comment by spotworks** [comment]
No need to respond to this issue.  I did a scan for funds within my BCH wallet and the funds came in.

**Comment by symbiot100** [comment]
how did u do that ? i have the same issue i've send bch to my btc wallet by accident .

**Comment by spotworks** [comment]
I only know how it worked in the Copay wallet. It had a feature to scan for BCH funds.  Search for information on how to retrieve the funds for your specific wallet, that's all I can offer.
