### ISSUE TITLE
Coinbase BTC a BCH Uphold

### ISSUE THREAD

**Issue by javicisco** [bitpay/copay#7207]

**Comment by javicisco** [comment]
Transferi BTC desde mi billetera Coinbase  a otra billetera propia pero erroneamente a una direccion de BCH. Como puedo recuperarlo?

**Comment by JDonadio** [comment]
> a otra billetera propia

Una de Copay/BitPay? si es así, fijate en [este post](https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-sent-bch-coins-into-a-btc-address-what-can-i-do-to-recover-my-bch-coins). Si no es así, deberás comunicarte con Coinbase y pedirle soporte a ellos para solucionar tu problema.

Nota: `Para billeteras Copay/BitPay únicamente` 
* Si enviaste BTC a una billetera BCH, en la recovery tool debes cargar todos tus datos de tu billetera BCH y seleccionar `btc/livenet` como main chain. 
* Si enviaste BCH a una billetera BTC, el proceso sería el inverso.
