### ISSUE TITLE
Transaction Not Found 

### ISSUE THREAD

**Issue by grelka111** [bitpay/copay#7213]
Why is this: Sent today with wallet Copay certain amount of BTC to the exchange, it is in the blockchain the transaction is "not found"?
https://insight.bitpay.com/tx/efc6f973a36f5bf658ab9a5ee4cc6437a27b31213382639b2060794b37239a5d

**Comment by JDonadio** [comment]
Your transaction was not broadcasted to the network, you can check your transaction id in any blockexplorer like: https://blockchain.info/search?search=efc6f973a36f5bf658ab9a5ee4cc6437a27b31213382639b2060794b37239a5d

**Comment by grelka111** [comment]
Why is transaction not broadcast to the network and for how long?
