### ISSUE TITLE
Import with recover phrase but wallet is empty

### ISSUE THREAD

**Issue by davehthepom** [bitpay/copay#7217]
Hi,

I have imported my wallet with a recovery phrase after a machine crash but the wallet is empty !

What can I do ?

Dave

**Comment by domin880720** [comment]
Hello 

I have similar problem, It was network error so I could not use my wallet. After it was fixed my balance is 0 BTCZ. What to do now ?

**Comment by gabrielbazan7** [comment]
Hi! we need your wallet id in order to assist you. Thanks !

**Comment by davehthepom** [comment]
Thanks for responses but I have resolved the issue, found an old copy of the wallet.
