### ISSUE TITLE
Wrong transaction adress

### ISSUE THREAD

**Issue by Gurkankucukel** [bitpay/copay#7219]
Hi...I used my btc wallet link to while exchanging my coin to bch...Transaction confirmed but there is no bch in my copay wallet as you guess..is there anything to do for this case? Could anyone help me about this?

**Comment by JDonadio** [comment]
Sorry, can you explain your issue in detail?

**Comment by Gurkankucukel** [comment]
I wanted to exchange my civic coins to bitcoincash using jaxx wallet with shapeshift,but unfortunately I pasted my bitcoin transaction hash adress in order to bitcoin cash adress which in copay e wallet.Transactions confirmed but there arent any bch in the wallet of course... ( my civic link 0xea4d5676dea989d075ffd6bab6027977edf5f306 ) Is there anything to do take back the coins ?

**Comment by JDonadio** [comment]
We have nothing to do with your problem. For your transaction you have used an external software, we cannot help you with that. You must contact with jaxx or shapeshift support and explain your issue.

**Comment by Gurkankucukel** [comment]
Thank you for your help,

I will try,

iPhone’umdan gönderildi

Javier Donadío <notifications@github.com> şunları yazdı (27 Kas 2017 16:06):
