### ISSUE TITLE
Japanese translation is inappropriate "Bcash" 

### ISSUE THREAD

**Issue by jnst** [bitpay/copay#7220]
Bitcoin Cash is `ビットコインキャッシュ` in Japanese.
But now, It is`ビーキャッシュ`.
https://github.com/jnst/copay/blob/master/i18n/po/ja.po#L366

`ビーキャッシュ` means `Bcash` ....😩
Who translated it?!

hmm... It's Ok. Should I send pull request? or something?

**Comment by dabura667** [comment]
https://crowdin.com/project/copay

Create an account and suggest a change.

**Comment by JDonadio** [comment]
For translation contributions please follow the above link and instructions. Thanks @dabura667

**Comment by JDonadio** [comment]
Check this out: https://github.com/bitpay/copay#translations
