### ISSUE TITLE
Some strings in the german translation are from the croatian

### ISSUE THREAD

**Issue by DanielWeigl** [bitpay/copay#7221]
eg here: https://github.com/bitpay/copay/blame/968efd672170948533f4a0d6e20a5991de855fdf/i18n/po/de.po#L376

"Bitcoin novčanik" is croatian and should be "Bitcoin Geldbörse" or "Bitcoin Wallet" (=Anglicism)

The wrong translation is very prominent on the first screen the user sees when the app opens:
![image](https://user-images.githubusercontent.com/1370302/33066771-8938bc04-ceac-11e7-944b-2f539e157b61.png)

**Comment by cmgustavo** [comment]
Thanks for report. Will be fixed in the next release.
