### ISSUE TITLE
Fee is to high to spend amount?

### ISSUE THREAD

**Issue by cislerk** [bitpay/copay#7222]
Hi! I get a tx and is said that tx fee is to high to soend it! But the amount is added in my total amount of bitcoin... i habe like 500 dollars and the tx was for 30 dollars... ehy is this message for the 30 dollars tx?? I cant spend them?? I dont untherstand rhis message

**Comment by cislerk** [comment]
Sorry my english... im spanish speaker

**Comment by cmgustavo** [comment]
Hola, el mensaje dice que el monto que quieres enviar, no deja fondos disponibles para la comisión (fee). Hay que ver la cantidad de inputs que tiene tu wallet: ve a "Settings" -> [ Wallet ] -> "More Options" -> "Wallet Addresses". Ahí deberías ver el total de "inputs" que tiene esa wallet, y cuánto sería el aproximado de fee que tendrías que pagar para mover los fondos.

**Comment by Plippito** [comment]
Estamos hablando sobfre el app (para iphone)? Porque yo no tengo esas opciones. Yo en Settings solamente tengo la opcion de cambiar el transaction fee/prioridad. 

Como un test estoy tratando de mandar ca 7 USD de un paper wallet a otro wallet mio, pero no puedo porque el app me dice "Insufficient funds for fee", aunque escojo el fee mas bajo.

**Comment by JDonadio** [comment]
https://github.com/bitpay/copay/wiki/COPAY---FAQ#copay-requires-high-fees-for-low-amounts-transactions
