### ISSUE TITLE
Error 504 and can't get any update with procedure 1 and 2 you mentioned.

### ISSUE THREAD

**Issue by Peterkkkk** [bitpay/copay#7223]
Error 504. 
can't get any recovery from the procedures you have given.
Is there any other way I can try to solve the problem?

Procedure 1:
Go to Settings > [Choose Wallet ] > More Options > Transaction History > Clear Cache

If the problem remains:

Procedure 2:
Go to Settings > [Choose Wallet ] > More Options > Wallet Addresses > Scan Addresses for Funds

**Comment by wagonstill** [comment]
I have the same issue (error 504) and the procedure didn't solve the problem for me either.

**Comment by kolekurs** [comment]
i have the same problem, step 1 and step 2 won't work...

**Comment by ValentinAconi** [comment]
I have the same and it tells me "This wallet is not registered at the given Bitcore Wallet Service ..... tap top recreate dont work. Wallet service address is https://bws.bitcoinz.ph/bws/api.
Tried the above methods, not working.

**Comment by rradulescu2017** [comment]
same problem

**Comment by ujemski** [comment]
Same problem . Help

**Comment by wagonstill** [comment]
If you don't have a error 504 but "This wallet is not registred..." make a restoration with your privat key and it's work

**Comment by wagonstill** [comment]
It seems that the service is down again

**Comment by kolekurs** [comment]
someone help us ??

**Comment by ujemski** [comment]
i have some BTCZ on wallet and  I cant payout now :(

**Comment by ujemski** [comment]
OK. ALL working

**Comment by wagonstill** [comment]
The seam for me... 2 times in 2 days.
Did someone try another wallet solution?

**Comment by JDonadio** [comment]
We have nothing to do with BitcoinZ

**Comment by VahtangKyiv** [comment]
CAN NOT RESTORE THE WALLET THROUGH 12 WORDS ( BTCZ )

WALLET MyBitcoinZ 10.0.1

AFTER RESETTING WINDOWS, I TRIED TO RESTORE THE WALLET - 12 WORDS AND PASSWORD, BUT NOTHING HAPPENS WHAT HAPPENS? LIKE THIS FRAUD ?

**Comment by BGalliotti** [comment]
Hello @VahtangKyiv   ,

Thanks for reaching out to us.

Please refer to #8532  

If there is any other question or concern please post it there so we can help you.

Kind regards.
