### ISSUE TITLE
Could not update wallet: Network error

### ISSUE THREAD

**Issue by arhistrateg777** [bitpay/copay#7224]
Could not update wallet: Network error

**Comment by Levino** [comment]
Did this get solved @arhistrateg777 ?

**Comment by SkyzohKey** [comment]
Got this error today on the bitpay wallet too. How to solve it?

**Comment by rmax** [comment]
It looks like they block the IP by country. I was getting the error when I was abroad and now that I'm back home it works just fine.

**Comment by SkyzohKey** [comment]
I've fixed that by whitelisting 'bws.bitpay.com', 'bitpay.com' and 'blog.bitpay.com'.
