### ISSUE TITLE
BCH SENT FROM COPAY WALLET TO EXCHANGE 1600 CONFIRMATIONS IN INSIGHT BUT NEVER ARRIVED

### ISSUE THREAD

**Issue by urivalls** [bitpay/copay#7226]
Hello I´ve transfered 0.38 BCH to the exchange.
The transaction is the following.
aa558ebf3fa3c317df3841e214ce2e9a8ae9b14240de0d35882eb8230c046329
Spoken and shared with the exchanger (Kraken).
Kraken says that the wallet of the transaction is not in the kracken account.
This is because I´ve used your translation tool. https://bitpay.github.io/address-translator/

Could you please help me to receive my transaction?

Thank you!

**Comment by dabura667** [comment]
You deposited your BCH to Kraken’s BTC deposit address.

**Comment by urivalls** [comment]
This is not true I've sent the BCH to the Kraken BCH adress.
Could you send me please in which information is based your statement?

**Comment by matiu** [comment]
@urivalls the 0.38 BCH output address of that TX translates to 1QAFjmF4654SopjEqjdX1afdF7zdhGWxqo

You can see the TX on a BCH  blockexplorer here:

https://blockdozer.com/insight/tx/aa558ebf3fa3c317df3841e214ce2e9a8ae9b14240de0d35882eb8230c046329


Ask Kraken if they recognize that address.

**Comment by urivalls** [comment]
solved thanks
