### ISSUE TITLE
Funds never arrived to my wallet but were debited from my account 

### ISSUE THREAD

**Issue by Sjcolo28** [bitpay/copay#7228]
I submitted bitcoins to this address: 162BNoMW1BpP616D2AGskq5HoRRh7K1tcU with confirmation that the transaction was completed but it never posted on my bitpay wallet.

**Comment by matiu** [comment]
162BNoMW1BpP616D2AGskq5HoRRh7K1tcU is not an address associated with any Copay BTC wallet.

**Comment by mr10008** [comment]
@matiu Just curious how you can see that the address is not associated with Copay wallet. Can you disclose the 'secret'? :-)
