### ISSUE TITLE
Package Name

### ISSUE THREAD

**Issue by IzzySoft** [bitpay/copay#7229]
Just to clarify: Is the switch of the Android APKs package name intentional? One release has it as `com.bitpay.wallet` (eg. v3.7.3), the next `com.bitpay.copay` (e.g. v3.9.0). That makes app updates complicated, to put it euphemistically.

Can you please state what's the strategy here, and how to figure *before* one tries to install the APK? Thanks in advance!

**Comment by JDonadio** [comment]
`com.bitpay.wallet` is for BitPay app
`com.bitpay.copay` is for Copay

**Comment by IzzySoft** [comment]
Thanks for clarification! But when you look at the releases page: how can you tell which is which? Both have only a release number, and in both cases the `.apk` file is just named `android-release-signed-aligned.apk` or `android-release-signed.apk`. So how shall one know which one is which?

**Comment by IzzySoft** [comment]
May I suggest to at least name the APK files accordingly (e.g. `com.bitpay.wallet.apk` and `com.bitpay.copay.apk`)? Otherwise I'll have to disable auto-updates [in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.bitpay.wallet) – and manual updates will only happen occasionally when I find time. The longer the "manual list" gets, the longer it takes to walk it.
