### ISSUE TITLE
Coins not received in BTCZ wallet

### ISSUE THREAD

**Issue by aamirmushtaq9** [bitpay/copay#7231]
I had 12600 BTCZ sent to a different wallet around 19 hrs ago but they were never received. Wallet: t1YiwA2HrtcaYQfSnc33MLi2ysG8Gn82WW1

**Comment by JDonadio** [comment]
We only support BTC and BCH. What is BTCZ ?

`t1YiwA2HrtcaYQfSnc33MLi2ysG8Gn82WW1` doesn't belong to any Copay/BitPay wallet

**Comment by aamirmushtaq9** [comment]
BitcoinZ wallet takes me this github support.

**Comment by aamirmushtaq9** [comment]
BitcoinZ wallet takes me to this github support.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by JDonadio** [comment]
We are not BitcoinZ. Probably is a fork and he didn't change the support link.
