### ISSUE TITLE
BCH balance is not available in multisig Bitcoin Cash wallet

### ISSUE THREAD

**Issue by RussianSwiss** [bitpay/copay#7235]
The balance is discovered after BCH wallet duplicating, but no balance and zero transactions are shown after. Can't send my BCH.

**Comment by RussianSwiss** [comment]
recovered. but the issue exists.

**Comment by JDonadio** [comment]
You must to scan your addresses manually, go to settings > wallet > more opts > wallet addresses > scan addreses for funds.

**Comment by RussianSwiss** [comment]
Man, sure I've done this. Didn't help.
