### ISSUE TITLE
BCH old > new address format tool

### ISSUE THREAD

**Issue by RussianSwiss** [bitpay/copay#7236]
Need to sell BCH to old address. All exchanges use old addresses.

Where can we find a tool to convert old address to new?

**Comment by JDonadio** [comment]
https://bitpay.github.io/address-translator/

For future inquiries please check our [FAQ section](https://github.com/bitpay/copay/wiki/COPAY---FAQ)

**Comment by RussianSwiss** [comment]
Thank you!
