### ISSUE TITLE
copay and bitcoin.com BCH wallet balances do not match

### ISSUE THREAD

**Issue by ik8sqi** [bitpay/copay#7237]
I use the bitcoin.com iOS wallet app to manage my bitcoin cash. The app shows a certain balance (18.447299 BCH). If I import the wallet using the 12 word backup into the same bitcoin.com wallet app in another iPhone, the resulting balance and list of transactions matches.

If however I import wallet using the 12 word backup in the Copay app (I tried both two separate iOS iPhones and the MacOS version), the balance shows as being 0.093904 BCH! I tried clearing the cache of transactions, but it always remains the same, and the transactions are different.

I think the issue is with these transactions:
https://bch-insight.bitpay.com/address/CefBwqJDEMsoio98EStfdh28LUMdQu7RGn

On Nov 8th I spent 9.113638 BCH and received 9.084603 BCH on the same day. The bitcoin.com wallet handles this properly (I hope...) but Copay thinks both are BCH that I spent, not sent/received.

Is there a way to see what my balance actually is...? I hope this is a bug with Copay, but I'd like to make sure I didn't just loose 18 BCH.

**Comment by JDonadio** [comment]
If you use an external seed in Copay you'll have that kind of inconsistency in your balance. Please check this out: https://github.com/bitpay/copay/wiki/COPAY---FAQ#different-balance-2-wallet-clients-on-same-wallet-seed
