### ISSUE TITLE
Copay.exe.sig file missing on the download page

### ISSUE THREAD

**Issue by mr10008** [bitpay/copay#7241]
On the github  download page https://github.com/bitpay/copay/releases/tag/v3.9.0 there is signature  available for Bitpay.exe file but there is no signature file available for Copay.exe, that's the **Copay.exe.sig** file.
Can you please provide that on the github download page?
Thanks!

**Comment by JulianTosh** [comment]
Linux is missing the signature as well.

**Comment by BGalliotti** [comment]
Please check https://github.com/bitpay/copay/releases/tag/v3.15.2

Regards
