### ISSUE TITLE
unauthorized payment sent from my iPhone bitpay wallet

### ISSUE THREAD

**Issue by vichy52** [bitpay/copay#7244]
I have a Bitpay wallet on my iPhone that was wiped clean by one payment transaction that was sent to an unknown address.  I haven't used the wallet for months.  I have 2 factor authentication enabled.  How can that happen?

**Comment by gabrielbazan7** [comment]
The only way is that someone has access to your wallet

**Comment by vichy52** [comment]
No one but me has physical access to my phone.  The transaction occurred at about 2 am on Nov 15.  I was at my mother's house that day and night, no one visited.  The wallet is not on my home computer.   How else can my phone wallet be accessed?   The payment went to a single address which I can view on the blockchain (funds are unspent...).

**Comment by gabrielbazan7** [comment]
I mean by access to your wallet that someone has access to your 12 words.

**Comment by JDonadio** [comment]
The keys are stored client-side (in your device) not in the cloud, not in our/any server. So the only way to sign and broadcast a transaction is using your device. Please check your security settings and ensure to reset your passwords. If your device support fingerprint we **strongly** recommend to use it.
