### ISSUE TITLE
Feature Request: Comprehensive TREZOR Support

### ISSUE THREAD

**Issue by cryptographicturk** [bitpay/copay#7245]
With the end of life of Chrome Webapps approaching, I want to implement TREZOR support into the desktop and possibly android mobile application. Before I start working on that and submitting it, I want to know if there is a reason that it has not been done already.

**Comment by JDonadio** [comment]
Hardware wallets team doesn't provide an API to implement it. And also they are not giving any support so basically we'll remove to avoid issues which we couldn't provide assistance.
