### ISSUE TITLE
Transactions stuck on my blockchain 

### ISSUE THREAD

**Issue by Oks001** [bitpay/copay#7246]
t1YiwA2HrtcaYQfSnc33MLi2ysG8Gn82WW1   i have unconfirmed transactions showing on my wallet please help.

**Comment by gabrielbazan7** [comment]
Hi! we need your transaction id in order to assist you. But, in this cases there is nothing we can do. You have to wait for your transaction to be confirmed or dropped from the mempool, the last option takes about 2 weeks.
