### ISSUE TITLE
BCH wallet addresses in Copay useless??

### ISSUE THREAD

**Issue by awilliam235** [bitpay/copay#7247]
Can't receive BCH on CVcRUZLCwG7hU7j7BN5CNft6BABho4eTsV because the format is not accepted on the sellers/senders side.

What next?

**Comment by gabrielbazan7** [comment]
https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-cant-send-bch

**Comment by awilliam235** [comment]
Thanks for your reply but I can't *receive* bch on a walletaddress that
begins with a 'C'... Seller says 'not a valid address'...

Thanks

2017-11-23 14:01 GMT+01:00 Gabriel Edgardo Bazán <notifications@github.com>:

**Comment by gabrielbazan7** [comment]
Did you read the link?

**Comment by awilliam235** [comment]
I read it... technical bla bla I don't understand and is so confusing...

I just want to buy BCH with a valid address but no one can tell me how...



2017-11-23 15:52 GMT+01:00 Gabriel Edgardo Bazán <notifications@github.com>:

**Comment by gabrielbazan7** [comment]
Ok. So you didn't read the link. From the link: 

> If you need to send to "old" addresses, and you are SURE those are BCH addresses, you can "translate" them using the BCH Translator tool: https://bitpay.github.io/address-translator/ 

So, copy the address with "C" from your BCH copay Wallet, enter it on the address-translator. Then use that address on your sellers page.
