### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by Begemot2500** [bitpay/copay#7248]
Hi. 
I sent bitcoin cash to the address bitcoin in my wallet. what should I do?

**Comment by Begemot2500** [comment]
Copay wallet

**Comment by Begemot2500** [comment]
I scann my wallet to bcc, and see “no wallets eligible for bitcoin cash support”. What is it? Why?

**Comment by Begemot2500** [comment]
What can I do? I need my bitcoin cash coins

**Comment by gabrielbazan7** [comment]
Hi! Create a new BCH wallet in Copay. Then use the recovery tool ( https://bitpay.github.io/copay-recovery/ ), set the chain as bch/livenet, and enter the 12 words of your bitcoin wallet. Then transfer the BCH to your new BCH wallet.

**Comment by Begemot2500** [comment]
scanning wallet btc shows bcc, but recovery tools does not find bcc

**Comment by Begemot2500** [comment]
I choose bch/livenet and write 12 words. And press scan. That’s all?

**Comment by gabrielbazan7** [comment]
yes. Use the 12 words of the wallet where you sent your bch by mistake.

**Comment by Begemot2500** [comment]
What about password? I need write wallet address?



Отправлено из myMail для iOS


четверг, 23 ноября 2017 г., 17:44 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by gabrielbazan7** [comment]
No. Only the 12 words and bch/livenet. At least you have set a password for those 12 words.

**Comment by Begemot2500** [comment]
I cant. I write 12 words from my wallet. See attach file please. What can I do???



Отправлено из myMail для iOS


четверг, 23 ноября 2017 г., 17:49 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by gabrielbazan7** [comment]
Your words are correct ? Could you try the import option in Copay to test that the words are ok ?

**Comment by Begemot2500** [comment]
Yes correct



Отправлено из myMail для iOS


четверг, 23 ноября 2017 г., 18:53 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by gabrielbazan7** [comment]
Ok. give me the wallet id

**Comment by Begemot2500** [comment]
Where is id?



Отправлено из myMail для iOS


четверг, 23 ноября 2017 г., 18:56 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by Begemot2500** [comment]
422b4809-de54-4595-9d8d-ca2e52e64760
It’s id?



Отправлено из myMail для iOS


четверг, 23 ноября 2017 г., 18:56 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by Begemot2500** [comment]
the balance walks then 1.02 then 0.95 BTC.



Отправлено из myMail для iOS


четверг, 23 ноября 2017 г., 18:56 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by Begemot2500** [comment]
0.95 BTC it’s wrong balance. I have 1.02 BTC. What is it?



Отправлено из myMail для iOS


четверг, 23 ноября 2017 г., 18:56 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by Begemot2500** [comment]
Recovery tool see my BTC in my copay wallet. But can’t see my bcc in to the same wallet. But my wallet see my 2.7 bcc. 



Отправлено из myMail для iOS


четверг, 23 ноября 2017 г., 18:56 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by gabrielbazan7** [comment]
Did you set the chain as bch/livenet ?

**Comment by Begemot2500** [comment]
Yes of course 



Отправлено из myMail для iOS


четверг, 23 ноября 2017 г., 19:59 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by Begemot2500** [comment]
And what’s wrong with my balance??? It’s my copay wallet the same time in different device 



Отправлено из myMail для iOS


четверг, 23 ноября 2017 г., 19:59 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by Begemot2500** [comment]
What can I do? How I can take my BCC??? I can see my coins in to the wallet BTC. But I can’t take my coins



Отправлено из myMail для iOS


четверг, 23 ноября 2017 г., 19:59 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by cmgustavo** [comment]
Hi @Begemot2500 , just to clarify. We need to understand your situation In order to assist you further.

BTC wallet has been created on **Wed Aug 02 2017 12:35:40 GMT-0300**,and the app only scan BCH on wallets created before 1 Aug 2017. That 's the reason you saw `no wallets eligible for bitcoin cash support`

So, if sent BCH to a BTC wallet by error, the only way to recovery the funds is using the Recovery Tool (https://bitpay.github.io/copay-recovery/). 

The recovery tool works for BTC and BCH. To do that select carefully the coin you want to recover. 

Hope that helps.

Thanks.

**Comment by Begemot2500** [comment]
Now I see my bcc coins in to the BTC wallet. But recovery tool doesn’t found this coins. 
Why? What can I do? Help me!



Отправлено из myMail для iOS


четверг, 23 ноября 2017 г., 20:57 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by Begemot2500** [comment]
In this form https://bitpay.github.io/copay-recovery/
I choose bch/livenet 
Write my 12 words and that’s all? Maybe something else???
And tell me please why my BTC balance change from 1.01 to 0.95 with out me???



Отправлено из myMail для iOS


четверг, 23 ноября 2017 г., 20:57 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by Begemot2500** [comment]
When I scann my wallet in to the recovery tool - scanned addresses - 0! Why zero? It’s mistake. How I can take my bcc coins??? Help me



Отправлено из myMail для iOS


четверг, 23 ноября 2017 г., 20:57 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by Begemot2500** [comment]
Please explain me. Why copay wallet see my bcc coins, but recovery tool can’t see my coins in to the same wallet. 



Отправлено из myMail для iOS


четверг, 23 ноября 2017 г., 20:57 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by gabrielbazan7** [comment]
> Why copay wallet see my bcc coins

Could you explain this ? Could you add a screenshot of what are you seeing ?

**Comment by Begemot2500** [comment]
Screenshot from my copay wallet. 


Отправлено из myMail для iOS


четверг, 23 ноября 2017 г., 21:31 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by gabrielbazan7** [comment]
Yes

**Comment by Begemot2500** [comment]
I send u screenshot !!! 



Отправлено из myMail для iOS


четверг, 23 ноября 2017 г., 21:33 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by gabrielbazan7** [comment]
where ?

**Comment by Begemot2500** [comment]
Attach file. 



Отправлено из myMail для iOS


четверг, 23 ноября 2017 г., 21:35 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by gabrielbazan7** [comment]
Sorry I can't see it.

**Comment by Begemot2500** [comment]
Give me email. And I send u



Отправлено из myMail для iOS


четверг, 23 ноября 2017 г., 21:37 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by Begemot2500** [comment]
https://imgur.com/a/EYCDo



Отправлено из myMail для iOS


четверг, 23 ноября 2017 г., 21:37 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by Begemot2500** [comment]
https://imgur.com/a/EYCDo

Why copay wallet see my coins, but recovery tool can’t see


Отправлено из myMail для iOS


четверг, 23 ноября 2017 г., 21:37 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by Begemot2500** [comment]
Now u see screenshot? 
https://imgur.com/a/EYCDo




Отправлено из myMail для iOS


четверг, 23 ноября 2017 г., 21:37 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by Begemot2500** [comment]
Now can u explain, why copay wallet see my bch coins (https://imgur.com/a/EYCDo) but recovery tool can’t see my coins. What can I do???



Отправлено из myMail для iOS


четверг, 23 ноября 2017 г., 21:37 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by gabrielbazan7** [comment]
That option is for wallets created before the fork ( 1st august 2017 ). Your wallet was created the Wed Aug 02 2017 12:35:40 GMT-0300. There could be an issue with that "duplicate to bch" option, but if you scan the wallet in the recovery tool and your balance is 0, so you don't have BCH.

**Comment by Begemot2500** [comment]
I send today 2.7 bch in to my BTC address into the copay wallet. And u wallet see this coins. U see my screenshot? Yes!!! How I can take my coins??? Help me



Отправлено из myMail для iOS


четверг, 23 ноября 2017 г., 22:01 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by JDonadio** [comment]
@Begemot2500 if you sent erroneously BCH into a BTC wallet, check this out: https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-sent-bch-coins-into-a-btc-address-what-can-i-do-to-recover-my-bch-coins

In order to help you, we need the transaction id.

If the recovery tool doesn't find anything, you probably sent that coins to another wallet by mistake.

We are very sorry about the wrong BCH balance shown within the app for the duplicate process, seems like a bug (it is happening to me as well) but we'll verify and fix it ASAP.

**Comment by Begemot2500** [comment]
*  Address:  1PTeddSo9RNBYJ5Rzs7RctzWJaWCs6jEx3
* 
TxId:  2ae06e8a6138b34a3e3267aef71f205be85f7d734ef4b8f822bb567749ba182d

What information u need? It’s my btc address and id transaction

Отправлено из myMail для iOS


четверг, 23 ноября 2017 г., 22:08 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by Begemot2500** [comment]
Today I send BCH to my btc adress:

*  Address:  1PTeddSo9RNBYJ5Rzs7RctzWJaWCs6jEx3
* 
TxId:  2ae06e8a6138b34a3e3267aef71f205be85f7d734ef4b8f822bb567749ba182d

2.7 BCH.

My copay wallet see this coins in to btc wallet https://imgur.com/a/EYCDo)

But recovery tool can’t see in to the same wallet. 
What can I do???????

Отправлено из myMail для iOS


четверг, 23 ноября 2017 г., 22:15 +0300 от Кирилл Стрельников  <4106868@bk.ru>:

**Comment by JDonadio** [comment]
We are reviewing your case. Please be patient we'll find a solution

**Comment by gabrielbazan7** [comment]
Click in duplicate for BCH. Then go to settings -> choose the BCH wallet -> more Options -> Wallet addresses -> scan addresses for funds. And tell me if you see any difference

**Comment by Begemot2500** [comment]
Yes!!!! Thanks )))))



Отправлено из myMail для iOS


четверг, 23 ноября 2017 г., 22:40 +0300 от notifications@github.com  <notifications@github.com>:
