### ISSUE TITLE
BCH stuck on the blockchain

### ISSUE THREAD

**Issue by pabloojs** [bitpay/copay#7250]
On November the 11th I used the recovery tool, I translated the adress with the tool but they still haven't made it through. Transaction number is :

 f165d06b64ec9f58f33a4f13a6a1b064c462ed296c2780ebbe4e514283696b77

https://bch-insight.bitpay.com/address/CYms18opefm5tGhKPThJtUC97x3QYE2Nxt

thanks in advance

**Comment by gabrielbazan7** [comment]
You still having the issue?

**Comment by pabloojs** [comment]
Yes, they are still stuck somewhere

**Comment by JDonadio** [comment]
Sorry, this is an error with the explorer cache. Your transaction doesn't exist.

https://blockchair.com/search?q=f165d06b64ec9f58f33a4f13a6a1b064c462ed296c2780ebbe4e514283696b77

https://blockdozer.com/insight/tx/f165d06b64ec9f58f33a4f13a6a1b064c462ed296c2780ebbe4e514283696b77

**Comment by pabloojs** [comment]
ok thanks, where can I find them? I used the recovery tool so I'm not sure where they're supposed to be now
