### ISSUE TITLE
BCH address translator gives an existing BTC address

### ISSUE THREAD

**Issue by awilliam235** [bitpay/copay#7251]
Because the Copay BCH wallet addresses bigin with 'C' are useless I tried the so called translator. But if I translate a BCH address I get a existing, earlier created BTC Address. Is this correct?

**Comment by JDonadio** [comment]
https://bitpay.github.io/address-translator/

This tool translate BCH addresses from old to new format (and vice versa), not BTC addresses.

**Comment by awilliam235** [comment]
Once again.

If I type in a BTC address into the translator, it translates this address
( which starts with a 'C') into an *exisiting* BTC address (thats starts
with '1') I already have used in my BTC Wallet.

Is this correct? Can I use this address for receiving BTC?

Thanks

2017-11-24 20:35 GMT+01:00 Javier Donadío <notifications@github.com>:

**Comment by awilliam235** [comment]
Correction:

If I type in a BCH address into the translator, it translates this address
( which starts with a 'C') into an *exisiting* BTC address (thats starts
with '1') I already have used in my BTC Wallet.

Is this correct? Can I use this address for receiving BCH?

2017-11-24 21:58 GMT+01:00 Albert William <awilliam235@gmail.com>:
