### ISSUE TITLE
Balance

### ISSUE THREAD

**Issue by Begemot2500** [bitpay/copay#7254]
Why my balance change from 1.01 BTC to 0.95 btc

**Comment by JDonadio** [comment]
https://github.com/bitpay/copay/issues/7248

**Comment by Begemot2500** [comment]
What’s wrong with my bcc? 



Отправлено из myMail для iOS


четверг, 23 ноября 2017 г., 20:19 +0300 от notifications@github.com  <notifications@github.com>:
