### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by ValeryVPetrov** [bitpay/copay#7257]
Hi,
When I do the backup, what folder the backup files copied to?
Or somewhere in the cloud? How can I restore the wallet?
Thanks

**Comment by JDonadio** [comment]
If you backup your wallet doing an export:

* From mobile > the backup text will be copied into your clipboard
* From another platform > the backup file will be downloaded into your computer

No, we never send your keys to anywhere. Always are stored client-side.

**Comment by ValeryVPetrov** [comment]
Sorry I am lost.
There 2 different functions:
1) Security /backup
2) More option / Export Wallet

What happen if I do Security /backup? Any files created? Where?
For what purposes export Wallet is used?

**Comment by JDonadio** [comment]
That words are your backup (recovery phrase). Ensure to write it down in the same order and grammatically.

![copay_-_copay_bitcoin_wallet](https://user-images.githubusercontent.com/13851807/33186562-2493160a-d069-11e7-8de3-7403e5581f42.png)

**Comment by JDonadio** [comment]
There are 3 backup formats:

* Recovery phrase
* Exported format
   * File/Text > depends if it's done from mobile or desktop
   * QR code > used to a fast migration from one device to another

**Comment by ValeryVPetrov** [comment]
Thanks.
I would like to go off-line with my BTC for a while and I am going to delete my wallet on PC.
Would be enough to recover the wallet later, if I have:
EITHER <Recovery phrase> OR <Export file-Personal Wallet-Copaybackup.aes> OR <Private key>
Correct?

**Comment by ValeryVPetrov** [comment]
EITHER Recover phrase OR backup file OR private key

**Comment by JDonadio** [comment]
Yes, absolutely. But I **strongly** recommend you try it first. Do not delete anything, made all the needed backups and try it in another platform from scratch. If the import process finish successfully then you'll be able to delete your wallets without risks.
