### ISSUE TITLE
I do not have the 12 words to make the recovery of my wallet

### ISSUE THREAD

**Issue by fmarce43** [bitpay/copay#7260]
My cell phone was stolen and when I activated my Copay wallet on my new cell phone, I did not see my Bitcoin. In order to make my recovery I need to have the 12 words and I do not have them. How can I get to get those 12 words and be able to recover my bitcoin?
if I do not get to have the 12 words or my recovery key, how can I get them, so have my bitcoin in my Copay wallet ... ??

**Comment by avibrazil** [comment]
Unfortunately your bitcoins are probably lost forever. The phrase is what contains your coins.

If you don’t have any form of backup of your phrase or private key, there is no way to access your funds anymore.

See, different from regular money and associated banks that take care of your money, crypto currencies require the user to take care of its own funds. This is a complicated task and standards such as the phrase scheme try to make it a bit easier.

There are “banks” in the Bitcoin world, such as Coinbase, but they are considered insecure cause if attacked, you lose your funds.

**Comment by avibrazil** [comment]
Next time please backup your phrase outside your wallet software. Here is standard way to document your phrase and pass it along to your family. Put there your phrase without the phrase password and tell the password to your family.

https://docs.google.com/spreadsheets/d/1TRnLywLYsVi8iYIfGq3ALrBP9kL_Y5goPD4YvSJAekU
