### ISSUE TITLE
Copay fees

### ISSUE THREAD

**Issue by hungryhippo88** [bitpay/copay#7261]
Hi all,

I am enquiring about why the fees for one of my BTC transfers were so high in comparison to the acutal transfer? 
Checking the blockchain it seems to have had a high transfer size (17kB) with a total fee of 0.157 BTC. This was approximately 1/3 of the total BTC transfer - seems a bit steep and does not seem completely logical. Just wanting to know how/why this occurred as it seems that a huge chunk of my transfer was lost to fees.

**Comment by junderw** [comment]
See #7203 ... there is a solution to lower fees by 50% and just waiting for Bitpay to implement it. (and if they implement segwit too, that's another 40%, so overall 70% off the current fees)

**Comment by JDonadio** [comment]
See also https://github.com/bitpay/copay/wiki/COPAY---FAQ#copay-requires-high-fees-for-low-amounts-transactions
