### ISSUE TITLE
ПРОБЛЕМА

### ISSUE THREAD

**Issue by fourclub** [bitpay/copay#7262]
На кошелек пришло ооочень много транзакций, баланс там тысячи.. но сегодня он показывает историю транзакций, а баланс равен нулю.. Это как понимать? 

Проходит время, баланс опять нормальный... потом опять баланс равен нулю или вообще пишет что кошелек не зарегистрирован.

**Comment by JDonadio** [comment]
It's working as expected. Please if the problem remain feel free to comment here again.
