### ISSUE TITLE
Copay insufficient funds for fee (sending €150 worth of BTC???)

### ISSUE THREAD

**Issue by hrnbc** [bitpay/copay#7264]
HI,

Seen some other threads concerning this message: Unsufficient funds for fee. Most of the time the answers contain remarks or questions about large volumes of small payments received.
I Only have two transactions, for testing the BTC-thing: about €50 and €100 worth of BTC (total 0,0229 BTC).
For the credabillity of BTC and my inderstanding I want to withdraw this 0,0229 BTC from my wallet.

Or do I get the message because I try to withdraw ALL of my BTC?

**Comment by JDonadio** [comment]
Please check: https://github.com/bitpay/copay/wiki/COPAY---FAQ#copay-requires-high-fees-for-low-amounts-transactions
