### ISSUE TITLE
Cредства входят в поступившие в UTXOs  / funds are included in UTXOs

### ISSUE THREAD

**Issue by kolyasik86** [bitpay/copay#7266]
**Добрый день**
У меня в кошельке 0,022445 БТС но я их не могу отправить, 
Максимально могу перевести только 0.007995 БТС и получаю ошибку "Эти средства входят поступившие в UTXOs меньше чем комиссия сети" 

**предлагает комиссию в 0.007099 - за что???**

**Как мне перевести свои БТС ??**

__________________________________________________________

**hi** 
good afternoon
At me in a purse 0,022445 БТС but I can not send them,
The maximum I can translate only 0.007995 БТС and get an error "These funds come from UTXOs smaller than the network fee provided"

**offers a commission of 0.007099 for what ??**

**How can I transfer my БТС ??**

**Comment by SquirrelCoder** [comment]
That's the miner's fee. I think your Transaction size is big, hence the fee! Select Economy fee (something like that), but it may take a lot of time, before it gets confirmed, there is a chance, that your TX never get confirmed too :(
