### ISSUE TITLE
Deleted Bitpay app coins gone

### ISSUE THREAD

**Issue by uncleJr68** [bitpay/copay#7273]
Hello , I mistakenly deleted my Bitpay app . I do not have my 12 word phrase . Are my coins gone. I do have a Bitpay visa if that would help in any way.

**Comment by uncleJr68** [comment]
I’m using an IPhone 7

**Comment by goehteg** [comment]
Hey im german, was hab ich? Was hab ich den genau gemacht un ich versuchs hinzukriegen, was hab i dir den getan? 

Von meinem iPhone gesendet

**Comment by matiu** [comment]
I am afraid the only way to recover your funds is to have our 12 words. There is no other copy of your keys.

**Comment by goehteg** [comment]
funktioniert es jetzt den?

Von meinem iPhone gesendet

**Comment by goehteg** [comment]
ok was can i make now

Outlook für iOS<https://aka.ms/o0ukef> beziehen
_____________________________
