### ISSUE TITLE
BTC to BTG after the fork

### ISSUE THREAD

**Issue by Mattia14** [bitpay/copay#7278]
Hallo, is it possible to duplicate the btc wallet in to btg today with CoPay wallet?

**Comment by dabura667** [comment]
No it is not.

**Comment by Mattia14** [comment]
so am I F(/&cked?
I lost the possibility to have the same amount of BTG?

**Comment by matiu** [comment]
no, you own the private keys, you can use any wallet that support btg and import it to access your BTG, or use our recovery tool https://bitpay.github.io/copay-recovery/

**Comment by Mattia14** [comment]
Thank you for your answer.
Is there a guide?
How does it works?
Will I have to use another wallet that support BTG?

thank you

**Comment by Mattia14** [comment]
Matiu?

**Comment by goehteg** [comment]
kannat du mir helfen my all kontos is money buy buy

**Comment by Mattia14** [comment]
Is there any guide?
