### ISSUE TITLE
Accidentally lost my recovery phrase. Can I get it back somehow?

### ISSUE THREAD

**Issue by Amansoni97** [bitpay/copay#7281]

**Comment by mr10008** [comment]
IF you have made the backup or exported the wallet - yes, otherwise...

**Comment by matiu** [comment]
Do you still hace the app installed with your wallet?

**Comment by Amansoni97** [comment]
Yes, I have the app. I want to use the recovery phrase for getting BTG and BTD

**Comment by Amansoni97** [comment]
Copay app has not given me the option of either export or backup

**Comment by gabrielbazan7** [comment]
You could check your recovery phrase in settings -> choose your wallet -> backup.

**Comment by otiobic** [comment]
I have a back up .... what do i do to retreive my back up?
