### ISSUE TITLE
Amazon gift card code I got was already refunded?

### ISSUE THREAD

**Issue by wftheory** [bitpay/copay#7282]
Im not quite sure what to do, as I can't redeem a $75 amazon card that I got.
Amazon supports tells me it was refunded already, and there isnt anything they can do. And if I try to cancel the gift card through copay, it says "Invalid BTC address" 

im wondering if theres anything I can do to get this fixed, or get my money back. Thanks

**Comment by JDonadio** [comment]
Hi, for support about Gift Cards please go to: 	https://help.bitpay.com/requestHelp

Or send an email to help@bitpay.com
