### ISSUE TITLE
Didn´t see my correct balance in MyBitcoinZ copay wallet (but on blockchain)

### ISSUE THREAD

**Issue by nettrip** [bitpay/copay#7284]
Hi,

i made yesterday a tx from one on my wallets to MyBitcoinZ address  t1V2dbYR5cePKUwwZBrWExNFU8P23Ykn7Cr over 10.170 BTCZ ans 0.4 BTCZ. Ervery time i open this the balance is shown 0, despite i tried it on 3 different kind of machines but no success. I have my 12 word seed phrase and generated my address a few times after deleting the client, also no success. I´m quite a bit desperated. Did anyone have a solution that i get access to my coins?

Kind regards
nettrip

**Comment by goehteg** [comment]
hey ich sprevhe deutsch, es hat sicj jemand bei mir reingehackt und bei mir ist auch alles wwg, tut mir leid, dwr hund ht sich auch npch gels vom konto uber paypal und so all my coints is oooooo

egal wo alles wwg! 

wennichhelfen kanm mach ich daz gerne

**Comment by mr10008** [comment]
BTCZ is not supported by Copay or BitPay. You have to use BTCZ software: https://github.com/bitcoinz-pod/bitcoinz-wallet/releases or https://play.google.com/store/apps/details?id=com.btczcom.btcz
Post your issues here instead: https://github.com/bitcoinz-pod/bitcoinz-wallet/issues
