### ISSUE TITLE
A single authorized transfer shows two separate transactions on blockchain

### ISSUE THREAD

**Issue by ogcadbane** [bitpay/copay#7287]
I transferred a small amount of bitcoin to a broker (0,192742 BTC) -- the transaction is pending, but when I inspect the Bitcoin Transaction (hash) via block cypher, I see the amount I transferred and a completely separate transaction (0.16276423BTC) also transferred to an unknown wallet address - I did not authorize that transfer!

IS this fraud?

**Comment by gabrielbazan7** [comment]
Could you share your transaction id ?

**Comment by JDonadio** [comment]
No, this is how bitcoin works. For example: Sending 0.1 BTC but having just one input of 1 BTC, you'll send 1 BTC but splitting in the amount to pay (0.1) and the change amount (~0.9 which will return to your wallet).
