### ISSUE TITLE
Another try to get an answer. BCH address with 'C' not accepted.

### ISSUE THREAD

**Issue by awilliam235** [bitpay/copay#7289]
Copay BCH addresses start with 'C'. Litebit.eu does not support this format. 

Can I buy BCH at litebit.eu with an alternive wallet address format and send BCH  to my Copay BCH wallet?

If I fill in a BCH address ('C') into the translator and I then get an address that is simular to an existing BTC wallet address. Is this correct? Can I use this (BTC) address to receive BCH in Copay?

**Comment by JDonadio** [comment]
Both Copay as the Recovery tool accepts BCH addresses starting with C or H, which is a new convention to prevent errors (https://support.bitpay.com/hc/en-us/articles/115004671663-BitPay-s-Adopted-Conventions-for-Bitcoin-Cash-Addresses-URIs-and-Payment-Requests)

If you need to send to "old" addresses, and you are SURE those are BCH addresses, you can "translate" them using the BCH Translator tool: https://bitpay.github.io/address-translator/

> If I fill in a BCH address ('C') into the translator and I then get an address that is simular to an existing BTC wallet address. Is this correct? Can I use this (BTC) address to receive BCH in Copay?

Yes, that is the correct behavior.
