### ISSUE TITLE
Multisig wallet - Balance Locked

### ISSUE THREAD

**Issue by ketchupfles** [bitpay/copay#7292]
I'm trying to send BTC to GDAX. In the past, the other user just had to slide to accept the proposal but now the funds are locked.

Any help is appreciated.

**Comment by ketchupfles** [comment]
![24203830_10210483794833024_1235908485_n](https://user-images.githubusercontent.com/17167757/33378781-35d9f508-d516-11e7-860f-af8b9d3254c9.jpg)
![24252005_10210483797153082_1689648420_n](https://user-images.githubusercontent.com/17167757/33378785-3a661872-d516-11e7-8656-1618b5be9921.jpg)

**Comment by JDonadio** [comment]
Your wallet is a shared wallet, so each transaction created from one device should be signed from the another device (which compose the shared wallet).

**Comment by ketchupfles** [comment]
Yes but how do you sign the transaction from the other device?

**Comment by JDonadio** [comment]
![33378785-3a661872-d516-11e7-8656-1618b5be9921_jpg__332x720_](https://user-images.githubusercontent.com/13851807/33379831-f214ac28-d4f7-11e7-9192-e9740e563da3.png)

Open the transaction proposal created and sign it from the other device.

**Comment by ketchupfles** [comment]
![24172503_10210483978477615_452073022_n](https://user-images.githubusercontent.com/17167757/33380410-480ff6d2-d51b-11e7-9d7f-50f5f2735b7b.jpg)
There is no slide on the other person's device.

**Comment by JDonadio** [comment]
Scroll down
