### ISSUE TITLE
Can't remember spending wallet password 

### ISSUE THREAD

**Issue by SignatureXZ** [bitpay/copay#7295]
I don't remember personal spending password is there anywhere you help me retrieve it?

**Comment by gabrielbazan7** [comment]
https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-forgot-my-wallet-spending-password-is-there-a-method-to-reset-it

**Comment by richardsuns** [comment]
@SignatureXZ 
did you restore your lost password?
i can find your lost password
