### ISSUE TITLE
Insufficient funds for fee? What the heck, I'm sending $80+?

### ISSUE THREAD

**Issue by JacobHeymann** [bitpay/copay#7297]
I'm sending .008BTC, plenty to cover for a sending fee at 149 sat/byte. Why can't I send/buy/sell my bitcoins?

**Comment by Schknheit** [comment]
Use another wallet that supports segwit or makes your set your fees manually, Shitpay is horrific, they are charging fees without the need of it, tx are being confirmed normally with 109sat/b but they fuck you up with 149.

**Comment by JDonadio** [comment]
You can set a custom fee tapping on the fee option at confirming time.
https://github.com/bitpay/copay/wiki/COPAY---FAQ
