### ISSUE TITLE
regarding bitcoin cash

### ISSUE THREAD

**Issue by LALITHKR** [bitpay/copay#7298]
hello sir,
i was download copay chrome extension in my pc and added some amount of bitcoin cash into it and later due to some problem in my pc, copay extension was removed .
later again iam added extension created another wallet and and i am added previous wallet backup data and here i can see the amount in my wallet  but iam unable to withraw and send that bitcoincash.
please help me to solve this scenario.
thanking you

**Comment by gabrielbazan7** [comment]
https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-cant-send-bch
