### ISSUE TITLE
BTC Hard Fork with BTG

### ISSUE THREAD

**Issue by bravesagi** [bitpay/copay#7300]
Hi
During the time of the last official hard fork on BTC by creating the BTG I had 5 BTC in my Copay wallet. 

I subscribed and transfered my BTC because Copay promised on their website that there will support the fork and will give Copay Customers the BTG equivalent of there BTC holding.

Can you please tell me I and when this promise will be realized?

Thank you a lot in advance for your help and answer.
Sincerely,
Melik

**Comment by gabrielbazan7** [comment]
Hi ! which website ? You could use the recovery tool to have access to your BTG https://bitpay.github.io/copay-recovery/

**Comment by bravesagi** [comment]
Hi Gabriel!
The recovery does show, that I dont have any BTC. But where is the BTG
(Gold) from the fork?
Do you know how this functions?

[image: Inline-Bild 1]

2017-11-28 15:22 GMT+01:00 Javier Donadío <notifications@github.com>:

**Comment by gabrielbazan7** [comment]
set the chain as btg/livenet

**Comment by bravesagi** [comment]
You know what Gabriel, you are my Angel Gabriel!!! Really! I really thought
I have lost that money.
Excellent support from you.
I thank also myself of knowing how to do the rest. "Normal" non IT people
wouldnt stand a chance....
Thanks a lot and have a good one!

2017-11-28 15:43 GMT+01:00 Gabriel Edgardo Bazán <notifications@github.com>:
