### ISSUE TITLE
Need Help with Amazon Gift Card-Getting a runaround from Bitpay Support

### ISSUE THREAD

**Issue by fringel10706** [bitpay/copay#7301]
I purchased a $100 Amazon Gift Card BitPay Invoice ID: XiuRZNoMq5CB1ve5cb1VNR with the funds sent to address 1Hat7QpE2dJXRqDwkC5Jutj7hcTiyKy7Sz. The invoice shows that it was paid in full but the card was not issued and shows an error message telling me to contact Bitpay Support.
Bitpay support tells me the invoice was fully paid and I should contact the merchant, but the only entity I dealt with was Bitpay (I purchased the Gift Card out of my BitPay Wallet). In fact the Invoice calls the card "Amazon Gift Card by Bitpay."
 I'm getting the runaround. 
In the meantime I am out the bitcoin and do not have the giftcard.
Does anyone know how to get an issue like this resolved?
Thanks,
C

**Comment by JDonadio** [comment]
Hi, for support about Gift Cards please go to: https://help.bitpay.com/requestHelp

Or send an email to help@bitpay.com

**Comment by fringel10706** [comment]
That is exactly where I went to get help with this. They are the ones who I contacted first and are giving me the run around and telling me to contact the Merchant, who I thought was Bitpay. Who is the "merchant" when you purchase an amazon gift card through the Bitpay wallet? They will not tell me who to contact, only that the invoice was paid, the money was transferred and I have to take up the issue with an anonymous merchant who they will not identify. If it is Amazon.com, they have not told me that.

**Comment by JDonadio** [comment]
Do you have the ticket so I can check that information? I can escalate your issue if you did the request.

**Comment by fringel10706** [comment]
Yes, I would very much appreciate that. I do not see a number on the confirming email I received when I submitted the ticket, all I see at the end of the email is the following: Request Id: 44fea41dc80c56f1. Is there some way to look up the ticket number. It is no on the confirming email?

**Comment by JDonadio** [comment]
Found it. I escalate the request but there is not much we can do from here.

**Comment by fringel10706** [comment]
Thank you.
