### ISSUE TITLE
where is my money?

### ISSUE THREAD

**Issue by pabloojs** [bitpay/copay#7304]
I lost my money 
I want to recovery my bch , I know my trasaction doesn't exist but where are my bchs?

https://bch-insight.bitpay.com/address/CYms18opefm5tGhKPThJtUC97x3QYE2Nxt

 f165d06b64ec9f58f33a4f13a6a1b064c462ed296c2780ebbe4e514283696b77

Regards

**Comment by JDonadio** [comment]
Your transaction doesn't exist.

Your address `CYms18opefm5tGhKPThJtUC97x3QYE2Nxt` translated to `1HJyS6TkmcnYz8nthiNPJxa7VppzYUdaEg`

https://blockdozer.com/insight/address/1HJyS6TkmcnYz8nthiNPJxa7VppzYUdaEg
https://blockchair.com/bitcoin-cash/address/1HJyS6TkmcnYz8nthiNPJxa7VppzYUdaEg

If you are not seeing your balance properly, go to settings > wallet > more opts > wallet addresses > scan addresses for funds

**Comment by JDonadio** [comment]
You shouldn't open a new issue for each reply. https://github.com/bitpay/copay/issues/7305

**Comment by pabloojs** [comment]
Sorry I thought you closed it, I looked in my wallets and I scanned in my directions but the bch are not there!
Sorry I thought you closed it, I looked in my wallets and I scanned in my directions but the bch are not 
![image](https://user-images.githubusercontent.com/33934652/33340726-aed6b9b6-d45b-11e7-98a7-99779fb369b2.png)
![image](https://user-images.githubusercontent.com/33934652/33340751-bc7732bc-d45b-11e7-8eb4-18fd3d4eb249.png)

**Comment by pabloojs** [comment]
Any News?

**Comment by JDonadio** [comment]
The money was sent to:

https://blockdozer.com/insight/address/1HJyS6TkmcnYz8nthiNPJxa7VppzYUdaEg
https://blockchair.com/bitcoin-cash/address/1HJyS6TkmcnYz8nthiNPJxa7VppzYUdaEg

Your address `1HJyS6TkmcnYz8nthiNPJxa7VppzYUdaEg` doesn't belong to Copay/BitPay wallet.

**Comment by pabloojs** [comment]
I think we're not following each other. On september the 11th I went through the same process with the recovery tool and I rescued my BCHs to this wallet 1HJyS6TkmcnYz8nthiNPJxa7VppzYUdaE
which is not "Copay" and I got them perfectly. One month ago I did the same process but this time using the translator, now my BCHs are not on the original wallet and neither in 1HJyS6TkmcnYz8nthiNPJxa7VppzYUdaEg and all I got from you is that the transaccion doesnt exist and that they were sent to the direction you're telling me now, but that wallet only contains data from september the 11th, a transaction took place because they are not on the Copay wallet. I've scanned it a dozen times and they're not there. I don't know where else to look for and I cant get a satisfactory answer from you

Regards

**Comment by JDonadio** [comment]
Provide an address or the id `from` the wallet who sent the BCH.

**Comment by pabloojs** [comment]
Hello again.
I believe there’s a misunderstanding. On September 11th, I used the Copay recovery tool and was able to successfully recover my BCH and transferred them in the following wallet: 
1HJyS6TkmcnYz8nthiNPJxa7VppzYUdaEg
I must mention that this wallet DOES NOT belong to Copay. Nevertheless, I was able to recover my BCH.
About a month ago, I used the same method (That is, Copay recovery tool) only that this time, I used an address translator. The problem is my BCH are missing and not located on neither the Copay wallet nor on the previously mentioned wallet which, again, does not belong to Copay.
Unfortunately, you are only telling me that my transaction does not exist. I understand my transaction does not exist. However, the reason why it does not exist, it is simply because of an unconfirmed transaction error that is not of my making. The error can be appreciated in the following image:
![image](https://user-images.githubusercontent.com/33934652/33679798-81e480de-da9e-11e7-9961-ba0e89da948c.png)

 
Approximately eight days ago, I was told that this “bug” is an explorer cache related issue. Again, not of my making. 
 
![image](https://user-images.githubusercontent.com/33934652/33679822-90c43306-da9e-11e7-89d8-e5cd89a646a5.png)

The links were of no help. They did not depict any transactions since, again, the transaction was not confirmed as I stated and showed in the first image. Not only do I not get a clear answer from you and feel like we are running in circles but, most importantly, my BCH remain missing as a result of these issues. 

I do not know the bch wallet because I use the tool with the twelve words. I can give you the id of btc and the wallet


8db990c5-5020-452a-89e1-9f7c77b8e37e


1JXoiMBaNk8bYev4jUCuYgAfueJeWrwSc3

**Comment by JDonadio** [comment]
@pabloojs your information have no sense. You are not providing any helpful information about the context wallet (the BCH wallet).

If you have the key (12 words) use it to import your wallet into the Copay app, and go to settings > wallet > more opts > wallet information. Copy and paste the wallet id.

This address: `1JXoiMBaNk8bYev4jUCuYgAfueJeWrwSc3` belongs to a BTC wallet. Not to the BCH (missing) wallet.

**Comment by JDonadio** [comment]
If your destination wallet doesn't belong to Copay, we cannot do anything to help you.

**Comment by pabloojs** [comment]
I give you the wallet and ID

5274b28c-dc18-4f6e-9dd3-8a19f3330e4d

CZzhHPXeFo78SnpVRDXq8BnhXmX4Qupf6e
CWKLJky1j3KvYFcbga7fTUm2RT83N6NdY7
CfCQakpVc63ijwJd6RBBV39GwzkmyzqKeY

**Comment by JDonadio** [comment]
This is your wallet detail:

```* Balance
  Total: 0.00000000 bch (0.00000000 bch locked)
  Confirmed: 0.00000000 bch (0.00000000 bch locked)
  Available: 0.00000000 bch (0.00000000 bch confirmed / 0.00000000 bch unconfirmed)```

Your wallet never receive any transaction. 

As I said in:

https://github.com/bitpay/copay/issues/7304#issuecomment-347633641
https://github.com/bitpay/copay/issues/7304#issuecomment-349664302
https://github.com/bitpay/copay/issues/7304#issuecomment-349744465

Your information doesn't match. You probably sent the funds to another wallet address.

**Comment by pabloojs** [comment]
It was correct to send as I did on September 11 and it went well
use the translator
![image](https://user-images.githubusercontent.com/33934652/33681678-000a7a40-daa4-11e7-9738-e89c04d2ccc2.png)

Here the transaction number and the transaction of September 11: https://bch-insight.bitpay.com/address/CYms18opefm5tGhKPThJtUC97x3QYE2Nxt
![image](https://user-images.githubusercontent.com/33934652/33681751-48237dea-daa4-11e7-84ba-6553364410b6.png)

But you told me it was a browser cache error and the transaction does not exist then the bch never came out , but I re-analyze my wallet and they are not

![image](https://user-images.githubusercontent.com/33934652/33682021-fddc7a9c-daa4-11e7-8989-e4b2ba69c751.png)

**Comment by JDonadio** [comment]
You are mixing the information. You told me "my funds never arrive into my wallet" so:

What wallet? > 5274b28c-dc18-4f6e-9dd3-8a19f3330e4d this one, empty.
What address? > CYms18opefm5tGhKPThJtUC97x3QYE2Nxt this one, doesn't belong to Copay
Another address? > 1JXoiMBaNk8bYev4jUCuYgAfueJeWrwSc3 belongs to a BTC (not BCH) wallet
What transaction? > f165d06b64ec9f58f33a4f13a6a1b064c462ed296c2780ebbe4e514283696b77 this one, which doesn't exist: https://github.com/bitpay/copay/issues/7304#issuecomment-347633641

So tell me, what more can I do for you?

**Comment by pabloojs** [comment]
Hi

I'm not mixing things up, what I'k telling you is that in september I did the exact same process and got my BCH back. I sent them to my wallet "1HJyS6TkmcnYz8nthiNPJxa7VppzYUdaEg", which is not Copay and everything went out just fine

I got this wallet "CYms18opefm5tGhKPThJtUC97x3QYE2Nxt" by using the translator. I had to do it that way because otherwise it wouldnt work. I've sent you the pic showing that I did the transaction that means your tool created this wallet so I could send my BCH to my wallet

This transaction was the result of the last thing i wrote you about "f165d06b64ec9f58f33a4f13a6a1b064c462ed296c2780ebbe4e514283696b77" and you're telling me the transaction doesn't exists and that's ok but if that happened the BCH must be in the wallet that copay created, that would be xxx BCH

**Comment by JDonadio** [comment]
> the BCH must be in the wallet that copay created, that would be 0.98789 BCH

Yes, please `give me the wallet id of that wallet`

**Comment by pabloojs** [comment]
No seriously, I never created a wallet because I had to rescue them from the mirror BTC wallet, you can't ask for the wallet's ID if I used the recovery tool to take them out and send them to another wallet, you should tell me where they are

**Comment by pabloojs** [comment]
any news?
