### ISSUE TITLE
Fingerprint is recognized, but no action is taken

### ISSUE THREAD

**Issue by octohank** [bitpay/copay#7306]
On Android Oreo (OnePlus 3T)
When I try to view my backup phrase, or my private key for that matter, I have setup the requirement for a fingerprint. When I try to perform a task like viewing a backup phrase, the prompt recognizes my fingerprint but does not show me the backup phrase. It just goes back in the program flow 1 step (for backup phrase this is the 'Are you sure you're not being watched?' page).

This happens on my 2 wallets. The version is v3.9.0

I'm by no means an expert in Angular, or even a beginner, but maybe it has something to do with this: https://github.com/bitpay/copay/commit/3defd2d370431203b34778eb97ce292d2b95564f#diff-c3089b95802afc1128e94281a3841280

**Comment by JDonadio** [comment]
Hi, I have a OnePlus 3T with android 8.0.0 and it's working as expected. Can you please provide your wallet id ?

**Comment by octohank** [comment]
Not gonna post that here publicly. I have the same problem on trying to spend Bitcoins, the fingerprint verification completes on the Android popup, but copay says it's incorrect. Do posting screenshots help?
I did reset my fingerprints at one point. Using pincode as backup yields the same result.

**Comment by JDonadio** [comment]
Please send all relevant information to `javier@bitpay.com`
