### ISSUE TITLE
BITCOIN DEBIT CARDS 

### ISSUE THREAD

**Issue by rollyrules01** [bitpay/copay#7308]
Hi Copay, I just want to say that your service has been awesome and I just want to suggest another service which you guys can introduce into your company. If you guys can start supplying the Bitcoin debit cards, it's going to be awesome and amazing. You're going to gain more and more customers cuz most bitcoin debit cards companies only supply their cards to EU members, even if you do a card for $300-$500 per card, none EU members will purchase in millions and I'll be the first to order. Consider this request.
Thanks.

**Comment by JDonadio** [comment]
https://bitpay.com/card ;)

**Comment by rollyrules01** [comment]
Hello, I’m trying to do a transfer and I’m getting something like
error getting transfer fee and that’s all. Attached is a screenshot of
what I’m getting.
