### ISSUE TITLE
BCH lost ?

### ISSUE THREAD

**Issue by sharninder** [bitpay/copay#7309]
Hi,

I had a balance of some BCH tokens and wanted to transfer them to my local exchange. I used the translator tool to translate the address but only after I completed the transaction I realised that the translator tool generates addresses that are only bitpay compatible. Are all my BCH lost or is there hope ?

**Comment by avibrazil** [comment]
I had similar problem.

I had to use this wallet on my computer to get acces to my BCH funds: https://electroncash.org

Use the same phrase, password and derivation paths you used on Copay to restore your addresses and funds.

**Comment by sharninder** [comment]
I'm using the same phrase but its not recognising it. It's a 12 word phrase but the "next" option in the wizard doesn't get highlighted. Any other option?

**Comment by avibrazil** [comment]
I remember setting up my wallet on Electron was tricky cause they call things differently in the form. Keep trying different advanced options until you see your funds.

**Comment by sharninder** [comment]
So I got access to my wallet. How do I now reverse the previous transaction ?

**Comment by sharninder** [comment]
Never mind, this is a non issue. I got the money
