### ISSUE TITLE
send BTC

### ISSUE THREAD

**Issue by cece58** [bitpay/copay#7311]
hello, I sent BTC first time all is ok !
second time I'm not able to do , see attach to understand what i mean.
please help me 
regards

Cesare
![schermata 2017-11-29 alle 10 13 15](https://user-images.githubusercontent.com/33513697/33367304-5bdec706-d4ee-11e7-9273-7631827717fa.png)

**Comment by JDonadio** [comment]
Because you have not balance available to spend. Once your transaction get confirmed you'll be able to send more funds.
