### ISSUE TITLE
BTG Recovery Tool

### ISSUE THREAD

**Issue by Mrostgaard** [bitpay/copay#7312]
When using your recovery software i find my BTG fine enough. 

When i try to send them to a legit and tested BTG address it takes forever. When looking into the console i see: 

`error: "66: min relay fee not met. Code:-26"
headers: Object { normalizedNames: Map, lazyUpdate: null, lazyInit: t/this.lazyInit<() }
message: "Http failure response for https://btgexplorer.com/api/tx/send: 400 Bad Request"
name: "HttpErrorResponse"
ok: false
status: 400
statusText: "Bad Request"
url: "https://btgexplorer.com/api/tx/send"`

Leaving me to belive there might be an bug in the software. I have quite a few address associated with my wallet.

**Comment by JDonadio** [comment]
I used this tool many times for BTG transactions without problem. If you still have this problem please post in the recovery tool repo to get a better assistance.
