### ISSUE TITLE
Does it keep the wallet online or offline ?

### ISSUE THREAD

**Issue by derozgurg** [bitpay/copay#7315]
Hi, I inspected the app so when I import a backup file.json the copay requests a login from https://bws.bitpay.com/bws/api/ then  request wallet is that true does it keep wallets online on https://bws.bitpay.com/ and the backup file is only wallet request information of the real wallet on vhttps://bws.bitpay.co 
? 

thanks

**Comment by JDonadio** [comment]
There is not login modules in Copay. Our bws (https://bws.bitpay.com/bws/api/) is connected by default, but you can use any other bws instance.
