### ISSUE TITLE
Not showing balance from imported wallet

### ISSUE THREAD

**Issue by maribontempo** [bitpay/copay#7317]
Hi guys,
I imported a wallet provided by a 3rd party, but the app is not showing the balance (its showing 0 when the balance is not). I tried to scan for funds, without success. Any advice on this? Thanks

**Comment by JDonadio** [comment]
https://github.com/bitpay/copay/wiki/COPAY---FAQ#different-balance-2-wallet-clients-on-same-wallet-seed
