### ISSUE TITLE
recovery phrase not working

### ISSUE THREAD

**Issue by Rociomai** [bitpay/copay#7319]
Hello. My BLU cellphone has been totally blocked since the last firmware update I downloaded and installed today. I cant' access and all I can do is reset and reinstal everything. Therefore, I am trying to access my Copay wallet in another mobile, a Huawei with Android. When I go to Create a New Wallet and Import Wallet, I write the 12 words and I get the error invalid. I am 100% sure the words are well written, I double checked with two different places I wrote them down in. I also looked at the list of possible Spanish words and there are no similar words with which I could have been mistaken. There is no mistake in the words, I have no other ideas of what to do and I am really worried. Someone can help? 
The copay version I am using is 3.9.0

**Comment by matiu** [comment]
You need to input the words in the right order, are you following the original order?

**Comment by Rociomai** [comment]
Absolutely! I never changed them!!

**Comment by JDonadio** [comment]
> When I go to Create a New Wallet and Import Wallet

Just to be sure, did you go to create and specify your words or go to import ?

**Comment by Rociomai** [comment]
I first installed Copay in the new phone. I followed all the steps to create a new wallet because from the beginning you are forced to create one. Once I did that, I clicked in the plus symbol near Bitcoint Wallets: 

![image](https://user-images.githubusercontent.com/34114169/33440339-7ba4161e-d5ce-11e7-9719-67b00983e371.png)

Then I clicked Import Wallet (Importar Billetera) and then I typed the 12 words and clicked Import. And that's when I get this message: 

![image](https://user-images.githubusercontent.com/34114169/33440466-ce87231c-d5ce-11e7-98c3-1ef5eb8c7840.png)

I don't understand what's wrong. I am totally positive that the key is correct. I found this issue here: 

https://github.com/bitpay/copay/issues/4808

It describes pretty much the same that is happening to me, although this person has some doubts about the way she is writing the words, but she is almost sure she is doing it right. I don't know if they found the solution. The difference in my case is that I do have a significant (at least for me) amount of money here that I cannot afford to lose. And for the same reason I guess it wouldn't be advisable for me to provide the 12 words to someone to try. 

What should I do???

Thanks!

**Comment by JDonadio** [comment]
You **NEVER** share your keys!

**Comment by JDonadio** [comment]
@Rociomai if you share your keys anyone can access to your funds.

**Comment by Rociomai** [comment]
I know! That's why I need someone to help me in some other way! But actually I don't know how could anybody access my founds if I am trying to and I can't!! I wish someone can tell me!

**Comment by gabrielbazan7** [comment]
check all the words here: https://github.com/bitcoin/bips/blob/master/bip-0039/spanish.txt.

**Comment by Rociomai** [comment]
I just got this email!!! 
![image](https://user-images.githubusercontent.com/34114169/33442549-28c78952-d5d4-11e7-91bd-da568d94d7ed.png)
 What does it mean???

**Comment by gabrielbazan7** [comment]
There are almost 200 users subscribe to the GitHub repository. It seems that someone see your words and takes your money.

**Comment by Rociomai** [comment]
what words? I didnt sent them?

**Comment by Rociomai** [comment]
How could they if I didn't wrote the words anywhere? And how could they if I couldnt?

**Comment by JDonadio** [comment]
Yes, you share the screenshots with your keys.

**Comment by JDonadio** [comment]
Contact me `javier@bitpay.com`

**Comment by gabrielbazan7** [comment]
Yes, we all receive the email notification with a screenshot with your keys here. You have a wrong word: Caimán -> con acento.

**Comment by dbalieiro** [comment]
. … please, can you tell me something about this message? I didn’t request help.

**Comment by JDonadio** [comment]
Open a new ticket with your request

**Comment by dbalieiro** [comment]
. … WOW … I’m reading the chain … #lol
