### ISSUE TITLE
Transaction appears as "Sending" in Copay but it is not in mempool

### ISSUE THREAD

**Issue by tab00** [bitpay/copay#7320]
I created a new bitcoin wallet and transferred bitcoin into it from an old wallet. I set a very low fee (1 sat/byte), as I didn't care how long it would take, as both wallets are my own.

Whilst funds were still unconfirmed in the new wallet, I made a transaction that spent some of it (sent to someone else), as "Use Unconfirmed Funds" was enabled.

Copay shows the transaction to the other person as "Sending" in the new wallet. However in all blockchain explorers that I tried the transaction is not found at all and the destination address has 0 transactions and balance. It is as if no transaction actually happened outside of Copay, whilst inside Copay it did, as it still shows the transaction as "Sending", and the transaction amount is accounted for in the total wallet balance.

The explorers I used were insight.bitpay.com, blockchain.info, blockexplorer.com, blockcypher.com, btc.com, blockchair.com.

So what is going on?

Will the recipient, who is still waiting, eventually receive what I tried to send? Or should I treat the transaction as if it never happened (and expect it to disappear from Copay), and just make a new transaction (using confirmed funds only) to the person who is waiting? I am tempted to make a new transaction, but am worried that I may end up giving the person twice what he should be getting.

**Comment by tab00** [comment]
> the transaction amount is accounted for in the total wallet balance
I have found that the wallet balance keeps changing between with and without accounting for the transaction amount, e.g. when clicking multiple times on the balance to refresh it.

**Comment by tab00** [comment]
If the transaction using unconfirmed funds (and there may never be confirmation due to low fee) is not in the mempool then can we assume that it will never get into the mempool, regardless of what Copay currently says ("Sending")?

If so, then I should assume Copay (and Bitpay wallet server) will be corrected and I should just go ahead with making a new transaction (using confirmed funds from a different wallet). Am I correct?

**Comment by tab00** [comment]
The transaction disappeared from Copay so I did make a new transaction for the person so that's settled.

Now today I made a new transaction from the old wallet (that I had referred to in my first post, first line) and it appears fine in Copay as "Sending" but got the same problem - searching for the transaction ID shows no results in any block explorer. Is it because the transfer from the old wallet into a new wallet had not settled yet?

**Comment by tab00** [comment]
Now the two transactions just disappear and reappear in Copay randomly (as "Sending" in the origin wallet, and "Receiving" in the destination wallet), and the net balance also changes.

The balance is independent of whether the pending transaction is apparent in history at the time. So sometimes there can be a non-zero net balance but no transactions in history in the new wallet, and at other times a 0 balance but a "Receiving" transaction.

One of the transactions is not in the bitcoin network mempool, whereas the other is and has remained unconfirmed because of low fee. But this does not seem to have any bearing on whether either transaction appears in Copay at any time.

So you need to fix synchronization of Copay / BitPay wallet server with the actual bitcoin mempool, and also of the transaction history and the balance shown.

Also, a transaction attempt should only be shown as successful in Copay (with the "Payment sent" green screen) if it actually makes it into the mempool. From my experience some transactions never made it into the mempool even though everything looked fine during transaction creation and submission in Copay, and still shows "Sending" in the list (but sometimes disappears).

**Comment by omietrice** [comment]
Anndd they don't answer. Having the same problems.

**Comment by miguelmorales85** [comment]
I have the same problem, a Transaction is labeled like "sending" and its not in the mempool.
I would like an "abandon transaction" feature, that could help us.

**Comment by JDonadio** [comment]
You can open the view, copy the url (before the insight page did load completely) and use the transaction id in any other block explorer to check their status. Sorry about that, we must fix our public insight to show the transactions properly.
