### ISSUE TITLE
¿Que pasa si no genero un nuevo código para recibir btc ?

### ISSUE THREAD

**Issue by JackelineA** [bitpay/copay#7322]
Que pasa si no genero un nuevo código para recibir btc  y envió el mismo código que use la ultima vez? es que creí que era mas segura usar el mismo que aun seguía apareciendo en mi monedero ya que estaba segura que me había llegado la ultima vez que me enviaron.. ahora estoy preocupada porque lo hice y no se si me llagara el dinero :(

**Comment by JDonadio** [comment]
Todas las direcciones generadas por Copay pueden ser reutilizadas sin ningún problema. De hecho, si únicamente necesitas una sola, al momento de crear una billetera en las opciones avanzadas podes seleccionar `single address`.

Más info: https://github.com/bitpay/copay/wiki/COPAY---FAQ#why-my-address-keeps-changing

**Comment by dbalieiro** [comment]
. … buena información, la posibilidad de “single address”, interesante para algunas situaciones...
