### ISSUE TITLE
stuck transaction

### ISSUE THREAD

**Issue by kvlasenko** [bitpay/copay#7324]
Hi i need some help.
I`ve got some bad situation
I had two purses and I decided to transfer everything to one so as not to be confused and all that. Both these purses were at BitGO. I transferred all the money from the first to the second and after the transfer went into pending, I removed the purses from the system, and then the account (deactivate account). But the time was quite long, and the transaction was still pending.
And now I have problems because of the low commission my transfer can be stuck. And then completely go to the non-existence after 14 days of the wallets of the wallet for which they could return simply does not exist anymore. What should I do? can you advise something?
UPD : id of this trans - e5d00246d9e15dea2dadbecf5471e8dfe1a4945d0535ff0c58e55fc3db27bff5

**Comment by kat3300** [comment]
I don't know how to do this

**Comment by goehteg** [comment]
im german, im understand not good! 

kannst du mir vllt dabei helfen oder das machen, und kannst du mir die erklarung auf deutsch/german schicken Lieben Gruß

**Comment by MelioraCogito** [comment]
If I understand correctly, why would you delete your wallets and then deactivate your account before receiving at least some confirmations by the blockchain?  A "pending" is not a confirmation.

**Comment by BGalliotti** [comment]
Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will happy to help you.
Thanks.
