### ISSUE TITLE
Fee 70% of total transaction. WTF? 

### ISSUE THREAD

**Issue by Oztops** [bitpay/copay#7326]
<img width="400" alt="screen shot 2017-12-01 at 7 33 55 am" src="https://user-images.githubusercontent.com/34145069/33460834-fc6d1b3c-d66a-11e7-935d-6bf222796769.png">

Is this the end of Bitcoin?

**Comment by tab00** [comment]
The percentage value should be 234% of the transaction amount.

I usually use custom fee level. 1 sat/byte used to work OK.

**Comment by dabura667** [comment]
Did you receive like 20 payments of 0.0003 BTC?

That is why.

Your transaction is around 3-4 kilobytes large.

Try sending with 1 sat/byte custom fee and just wait for a week or something.

**Comment by JDonadio** [comment]
Please check: https://github.com/bitpay/copay/wiki/COPAY---FAQ#copay-requires-high-fees-for-low-amounts-transactions

You can use a custom amount, just tap in the fee detail and choose the `custom` option.
