### ISSUE TITLE
Copay 2-2 Signature Wallet Problem

### ISSUE THREAD

**Issue by PeterDavid33** [bitpay/copay#7328]
Is it possible to restore a 2-2 Signature wallet if only 1 of the 2 parties has his recovery phrase? If so, how would we go about doing that?

Look forward to hearing a response from you guys!

**Comment by JDonadio** [comment]
Hi, unfortunately not. If you have not both backups your funs will not be accessible.

**Comment by PeterDavid33** [comment]
What if we have the the extended private key?

**Comment by dabura667** [comment]
Then yes. But it requires using bitcore-wallet-client with a custom app.

**Comment by PeterDavid33** [comment]
Thank you so much! Would you mind dropping the instructions below?

**Comment by parkermor** [comment]
@PeterDavid33 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
