### ISSUE TITLE
Duplicated balance on Copay and Exodus

### ISSUE THREAD

**Issue by ssakcoR** [bitpay/copay#7331]
Hi,

A month ago I installed Exodus wallet and backed it up with 12 word phrase. All my then balance was shown on Copay and Exodus including BCH. The reason I decided to use Exodus - to exchange BCH to BTC, as Copay was glitching on transfers back then. 

So, I exchange 3 BCH to 0.23 BTC back in October. Now I am not sure how this all works, having in mind that it is the same wallet under same 12 words, however balances are different.
On copay I have 2.36 BTC while on Exodus I am shown to have 2.41 BTC and 2.1 BCH.

Why does BTC amounts differ? I'd like to store all BTC in Copay, but not sure if I should send all BTC to Copay address or only the discrepancy...

Can anyone advise?

Thank you

**Comment by JDonadio** [comment]
https://github.com/bitpay/copay/wiki/COPAY---FAQ#different-balance-2-wallet-clients-on-same-wallet-seed
