### ISSUE TITLE
Do not come btcz on MyBitcoinZ wallet

### ISSUE THREAD

**Issue by mainM00007** [bitpay/copay#7334]
Good afternoon. Help, sent 2600 btcz to your address MyBitcoinZ wallet, funds do not come.
https://bitcoinz.ph/tx/77a7420f7012d4816c1cd9542da84089f87d54971e3e586b464d5a8fbd692a97

Bad work wallet((

**Comment by gabrielbazan7** [comment]
BTCZ is not supported by Copay or BitPay. You have to use BTCZ software: https://github.com/bitcoinz-pod/bitcoinz-wallet/releases or https://play.google.com/store/apps/details?id=com.btczcom.btcz
Post your issues here instead: https://github.com/bitcoinz-pod/bitcoinz-wallet/issues

**Comment by mainM00007** [comment]
Link does not work

**Comment by mainM00007** [comment]
How is this not supported? I already sent the exchange to the MyBitcoinZ wallet earlier
https://github.com/anthony19114/mybitcoinz/releases

**Comment by gabrielbazan7** [comment]
You are complaining in the wrong place
