### ISSUE TITLE
Did I lost my money

### ISSUE THREAD

**Issue by miadar** [bitpay/copay#7335]
Good evening, 2 days ago i did sent my money to the copay account but to adress that was generated before. I didnt see that new adress was generated and i put to old one. How can I receive money that i have sent?

**Comment by JDonadio** [comment]
https://github.com/bitpay/copay/wiki/COPAY---FAQ#why-my-address-keeps-changing

You can reuse all the addresses generated, and also check their status in settings > wallet > more opts > wallet addresses
