### ISSUE TITLE
Multisig problem

### ISSUE THREAD

**Issue by georgen77** [bitpay/copay#7336]
Could you please help me get my coins from my copay multisig wallet. In accordance with copay Administration precautions as to termination of chrome app from the beginning of next year I decided to move my bitcoins from my multisig 2of2 to my other wallet. Unfortunately I could only initiate the transaction, but my other signatory (which also belongs to me)  does not receive a transaction confirmation request - so the transaction cannot go ahead. Thank you in advance.

**Comment by JDonadio** [comment]
If for some reason you are not able to move your funds from the app, try using the [recovery tool](https://bitpay.github.io/copay-recovery/) and move all your funds to a new fresh wallet.

**Comment by georgen77** [comment]
Thank you. However, I am a bit suspicious as this tool asks you to provide mnemonic in an open way.
