### ISSUE TITLE
Can’t find my mined bitcoin record on my wallet

### ISSUE THREAD

**Issue by april9009** [bitpay/copay#7337]
I have not been able to find my bitcoin in my wallet for sometime, can anybody help?

**Comment by JDonadio** [comment]
I don't understand your issue sorry, explain it in detail please.

**Comment by april9009** [comment]
I have used this wallet address on Genisis mining to receive bitcoin and I should have a daily payout, never the less, I cannot see the receiving record in my copay app bitcoin wallet.

**Comment by JDonadio** [comment]
You must contact to Genesis and ask they for your transactions, we cannot do anything with that information.
