### ISSUE TITLE
Created new wallet by mistake, wanted to restore old one

### ISSUE THREAD

**Issue by mobi100** [bitpay/copay#7339]
Hi, I installed Copay on my computer and created new wallet by mistake, instead of restoring my old one.

I reinstalled the program, but it logs me directly in the new wallet I created and I can't go back and restore my old one? What should I do to get the restore option again?

**Comment by RefX32** [comment]
Once you generate an address, that address is yours forever. So, when you sent to the old address, it should still appear in Copay. Can you re-check and see if you've got them? If not, I was hugely misinformed.

**Comment by JDonadio** [comment]
@mobi100 to restore your old wallet please go to import instead of create, and set your seed there. You can have multiple wallets in your app, if you created a new one my mistake, just delete it from settings > wallet > more opts > delete wallet. Ensure to get the wallet empty before delete it.
