### ISSUE TITLE
Can we remove a copayer from a multisign wallet?

### ISSUE THREAD

**Issue by Matththom** [bitpay/copay#7340]
Hi,
I and some firends are using a multisign Copay wallet to store the bitcoins that we have earned through some mining.
One of us want to quit the team, and so we would like to remove him from the wallet and add someone else. But I can't find out how to do it. Is it even something possible?

**Comment by JDonadio** [comment]
No, you cannot "remove" a copayer. You must create a new one and share the new key with your new copayer.
