### ISSUE TITLE
Notifications show BTC received even though it was actually BCH

### ISSUE THREAD

**Issue by hpernu** [bitpay/copay#7342]
Main screen, push-ups and e-mail notifications show BTC received even though BCH was actually received.

Wallet balances are correct.

This applies to at least Android Mobile wallet and Windows wallet and e-mail notifications.
Likely to iOS as well.

**Comment by hpernu** [comment]
This applies to e-mail notifications(if enabled) as well.
I.e. all notification show BTC instead of BCH

**Comment by JDonadio** [comment]
Thanks for the report, we'll send a fix for the next release.

**Comment by hpernu** [comment]
THis same issue seems to affect almost everything: payment proposals, popups, incoming transaction, transaction history: that is, you almost invariably see BTC even though it is BCH.

**Comment by BGalliotti** [comment]
**Are you still experiencing this issue?**
We look forward to hearing from you.
Regards
