### ISSUE TITLE
Bitcoin transfer issues. (COPAY)

### ISSUE THREAD

**Issue by DarrenDevane** [bitpay/copay#7344]
Hello, I tried sending money to my wallet about 15 minutes ago and have received nothing. I am thinking it has something to do with me trying to link my coin base account to it, it said it would send me an email confirmation and never did. I just sent $249 to my wallet and can’t see it.

**Comment by mr2sweet** [comment]
I sent btc from my coinbase to copay wallet. It still says pending on coinbase but there is no transaction ID, and it has 0 confirmations. Please help me!

**Comment by JDonadio** [comment]
@DarrenDevane Just wait until the transaction get confirmed.
