### ISSUE TITLE
Sending $5

### ISSUE THREAD

**Issue by slizzle87** [bitpay/copay#7346]
All I have is $5 in my account but I can't send it because it keeps saying insufficient funds I can't send $1 I can't send $2 but I thought the sending fee is only 10% so I really don't get it why can't I send my last $5 somewhere?

**Comment by JDonadio** [comment]
https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-always-get-insufficient-funds-for-fee-when-trying-to-send
