### ISSUE TITLE
Insane fee!

### ISSUE THREAD

**Issue by tonno84** [bitpay/copay#7349]
I've an issue: when i try to transfer my bits from my copay wallet (on my windows phone) to another wallet, copay blocks the transfer and says that i have an insufficient funds or (sometime) asks me an insane fee (1500 - 3500 bits).
Someone can help me?

**Comment by JDonadio** [comment]
https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-always-get-insufficient-funds-for-fee-when-trying-to-send

You can set a custom fee tapping on the fee section at confirm time.
