### ISSUE TITLE
Can't send btc from Bitcoin wallet

### ISSUE THREAD

**Issue by Doctordradd** [bitpay/copay#7352]
Hello
Created new wallet and received btc, but at send it, can't to change amount, can't to send my btc. Trying to import wallet to another client, have error. But can to see balance.
Please help me, how can to send it... 
Thanks

**Comment by Gamboster** [comment]
What amount of BTC are you trying to move? Maybe it's a very small amount.

Could you provide your wallet id?

**Comment by Doctordradd** [comment]
Hello! Thank you for response! This is my wallet id:28850aff-3572-4fad-b521-07e440f3374d
I only created it and exchanged for make 1 payment, have ~$400, but can't to change amount, when go to Send. Have my 12 words mnemonic, decrypted Keys, but at importing only can from Android wallet to PC wallet the same client, and the same problem at sending money. Importing to another client have 403 error. Can to see my adresses and 1 adresses is green color with funds. Attaching screen shots of my balance and screen when go to Send option. Please help me... Thank you very much Alina. 






Enviado desde Yahoo Mail para Android 
 
  El mié., 6 de dic. de 2017 a la(s) 9:12, Gabriel Masclef<notifications@github.com> escribió:   
What amount of BTC are you trying to move? Maybe it's a very small amount.

Could you provide your wallet id?

**Comment by Doctordradd** [comment]
Hello! 
Thank you for response! 
This is my wallet id:
28850aff-3572-4fad-b521-07e440f3374d

I only created it and exchanged for make 1 payment, but can't to change amount, when go to Send. 
Have my 12 words mnemonic, decrypted Keys, but at importing only can from Android wallet to PC wallet the same client, and the same problem at sending money. 
I NOT HAVE any error message about amount, when insert adress to send, go to insert amount and here is can't to change amount o destination, have 0,00 and it's like inactive. But I received btc and can to see in configurations my adress with balance...

**Comment by JDonadio** [comment]
`28850aff-3572-4fad-b521-07e440f3374d` doesn't belong to Copay

**Comment by arangsalimi** [comment]
Hi there
I'm using bitcoin.com wallet and I can't send anything from my 0.005BTC, the amount is too low apeared in front of my transaction.
but when I go through my send page nothing is working
