### ISSUE TITLE
can't connect coinbase walled

### ISSUE THREAD

**Issue by hungmoon** [bitpay/copay#7353]
trying to connect coinbase wallet.  Enter authentication code, says authorizing but never goes through.

**Comment by cmgustavo** [comment]
What device are you using? Please check this link and let us know if it 's your same issue: https://github.com/bitpay/copay/issues/5891

**Comment by hungmoon** [comment]
I am using an Android 7.0 phone, a Motorola Droid turbo 2

On Dec 5, 2017 4:40 PM, "Gustavo Maximiliano Cortez" <
notifications@github.com> wrote:

What device are you using? Please check this link and let us know if it 's
your same issue: #5891 <https://github.com/bitpay/copay/issues/5891>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bitpay/copay/issues/7353#issuecomment-349490283>, or mute
the thread

**Comment by hungmoon** [comment]
Reviewed the issue ticket you linked, I don't believe it's the same problem. I try to connect my coinbase wallet through Copay, enter the verification code sent to me, hit the "authorize" button , it says"authorizing" but never finishes, just continues saying authorizing. I do get emails saying they are linked but when I go to the Copay app all my wallets are empty.

**Comment by BGalliotti** [comment]
Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will happy to help you.
Thanks.
