### ISSUE TITLE
I sent BCH to the wrong address format

### ISSUE THREAD

**Issue by wealthcollective** [bitpay/copay#7354]
Copay doesnt accept the address format that QCX uses. I sent BCH from my copay wallet to QCX in the past and copay made me use an address conversion tool. It worked fine and I received the BCH in my QCX account. Today I tried to send BCH to my QCX account and copay automatically converted my QCX address into a format copay accepts. As of now there has been 9 confirmations on the blockchain and I havent received my BCH in QCX. Did copay mess up the address format? Is there anyway to fix this?

**Comment by Gamboster** [comment]
Both Copay as the Recovery tool accepts BCH addresses starting with C or H, which is a new convention to prevent errors (https://support.bitpay.com/hc/en-us/articles/115004671663-BitPay-s-Adopted-Conventions-for-Bitcoin-Cash-Addresses-URIs-and-Payment-Requests)

If you need to send to "old" addresses, and you are SURE those are BCH addresses, you can "translate" them using the BCH Translator tool: https://bitpay.github.io/address-translator/

The new address format works fine. If you are sure you did the procedure properly, then you should ask QCX why your funds are not credited.
