### ISSUE TITLE
Can't recover with recovery phrase

### ISSUE THREAD

**Issue by jojowasem** [bitpay/copay#7355]
I'm pretty sure I write down right all the 12 words, there are anyways to you devs heck if my words match a wallet? Maybe I am the one doing something wrong

I broke my phone where the wallet was (looking for a way to fix it). There is any way a may have changed those 12 words in the past? I also write down some codes that might help (probably a qr code number)

**Comment by JDonadio** [comment]
> And remember, NEVER share your keys!

☝️

**Comment by parkermor** [comment]
@jojowasem 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
