### ISSUE TITLE
How to use the the BT gold recovery tool

### ISSUE THREAD

**Issue by Mattia14** [bitpay/copay#7356]
I have already asked it but someone close the topic without answering:
Hallo, is there a guide in how to use the recovery tool (https://bitpay.github.io/copay-recovery/)? thank you

**Comment by Gamboster** [comment]
The recovery tool allows you to recover your btc, bch or btg, from your Copay wallet.
For a common wallet (No multisig) You should fill in the signature and copayer fields with 1.
Select the string corresponding to what you are trying to recover, for example: If you want to recover your BTG, you must select 'btg / livenet'. Initially you should not change the address gap value.

In the input: "Recovery phrase (mnemonic) or File / Text backup", place your 12 words correctly

Accept the terms and services and you can scan your funds.
Once the funds of the corresponding wallet are found, an input will appear, which must be filled in with the address to which you wish to send your funds.

The procedure is simple
