### ISSUE TITLE
Error importing the backup file

### ISSUE THREAD

**Issue by onleines** [bitpay/copay#7357]
I would like to import a backup file in json format.
The file was generated February 2015.
I am asked for a password. I can not remember that a password was required.
Was it in the former Copay version (V1.2?) Maybe not and in the current version it is required?
Is a backup possible without a password?
Thank you very much

**Comment by JDonadio** [comment]
@onleines the backup file require a password to be encrypted and exported from the wallet. This password is `mandatory`. In addition, the old versions (probably used by you) also export the backup file format with the private key encripted (if you set the spending password). In that case you `must` remember both to import your wallet.

**Comment by richardsuns** [comment]
@onleines 
If you have still the text i may crack it.
i have cracked similar wallet backups from copay wallet.
