### ISSUE TITLE
Transaction was not found and was showing sending 

### ISSUE THREAD

**Issue by QuestBit** [bitpay/copay#7358]
I send out 2 btc and the transaction was showing not found. How do I go about it ?

**Comment by nicoandmee** [comment]
I am having the same issue.

**Comment by blueknight02** [comment]
Has this been resolved? I've also sent a transaction that is not showing up on the blockchain explorer

**Comment by jtor99** [comment]
I have the same problem, and when i try to send btc my antivirus alert me that copay is trying to use the webcam

**Comment by JDonadio** [comment]
You can open the view, copy the url (before the insight page did load completely) and use the transaction id in any other block explorer to check their status. Sorry about that, we must fix our public insight to show the transactions properly.
