### ISSUE TITLE
Wallet busy 

### ISSUE THREAD

**Issue by QuestBit** [bitpay/copay#7359]
Showing wallet busy

**Comment by JDonadio** [comment]
It's caused when your wallet send many request to bws. But should last a short time.

**Comment by QuestBit** [comment]
What is bws ?
    On Wednesday, December 6, 2017, 9:58:47 PM GMT+8, Javier Donadío <notifications@github.com> wrote:  
 
 
It's caused when your wallet send many request to bws. But should last a short time.
