### ISSUE TITLE
Best practices when customizing copay

### ISSUE THREAD

**Issue by xelawafsTemp** [bitpay/copay#7362]
What's the best approach to use when customizing Copay eg adding new views and editing existing ones? I get lost on the builds. At what point should I start changing code in a way that's easy to keep up with future updates from Copay when looking at these steps:

1. Clone Copay
2. npm run apply:copay
3. npm start ?

**Comment by JDonadio** [comment]
Follow the readme instructions to the build process. For "how to customize" the app we have not guides or recommendations.
