### ISSUE TITLE
Where is my money? 

### ISSUE THREAD

**Issue by pabloojs** [bitpay/copay#7363]
Please don't close thiss issue

I think we're not following each other. On september the 11th I went through the same process with the recovery tool and I rescued my BCHs to this wallet 1HJyS6TkmcnYz8nthiNPJxa7VppzYUdaE
which is not "Copay" and I got them perfectly. One month ago I did the same process but this time using the translator, now my BCHs are not on the original wallet and neither in 1HJyS6TkmcnYz8nthiNPJxa7VppzYUdaEg and all I got from you is that the transaccion doesnt exist and that they were sent to the direction you're telling me now, but that wallet only contains data from september the 11th, a transaction took place because they are not on the Copay wallet. I've scanned it a dozen times and they're not there. I don't know where else to look for and I cant get a satisfactory answer from you

Regards

**Comment by JDonadio** [comment]
https://github.com/bitpay/copay/issues/7304
