### ISSUE TITLE
Help me!!!

### ISSUE THREAD

**Issue by Newwaybiz** [bitpay/copay#7366]
Hello! How do I get a private key for my address: 3AeC5uH63eFJ2ckNrqmWEJPKvrMiAYv7VK
When using bip32jp.github.io I get the address: 166wUfksZUHDfnhfmxgjLxFbbEZT19E4ar
But I need a private key to: 3AeC5uH63eFJ2ckNrqmWEJPKvrMiAYv7VK
How to do it???

**Comment by JDonadio** [comment]
Sorry, Copay doesn't provide that option.

**Comment by parkermor** [comment]
@Newwaybiz 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
