### ISSUE TITLE
Moved instead of sent

### ISSUE THREAD

**Issue by ctinola** [bitpay/copay#7368]
Unable to recover funds that were sent to same address? Shows up but can’t recover or move

**Comment by JDonadio** [comment]
What do you mean with recover funds? if you moved your funds to your own wallets, why you have to recover them?

**Comment by ctinola** [comment]
My first time using bitcoins for purchase, I sent them to the receive
address.
They are not in my wallet but show up as ‘Moved’
Is there a way to move them back into my wallet?
I can’t get to them.

Thanks for your help

**Comment by JDonadio** [comment]
Moved means you sent funds to your own wallet, no to another one.

**Comment by ctinola** [comment]
They are not showing up in my account only on transaction page
How can I get them to show up in my account total

**Comment by JDonadio** [comment]
You have to wait to the transaction get confirmed

**Comment by VSBIT** [comment]
Transaction Is confirmed, but still the balance did not change

**Comment by ctinola** [comment]
Please help me with Moved bitcoin transaction
