### ISSUE TITLE
put a small commission, help!

### ISSUE THREAD

**Issue by FrankyPol** [bitpay/copay#7369]
I gave too little commission for the transfer, and the translation was not carried out, the remainder of the purse froze until the transfer disappears. What should I do?

**Comment by JDonadio** [comment]
Use a major fee for your next transactions to avoid this cases.

**Comment by FrankyPol** [comment]
now it remains only to wait?

**Comment by JDonadio** [comment]
Yes

**Comment by FrankyPol** [comment]
thank you
