### ISSUE TITLE
copay bitcoincash

### ISSUE THREAD

**Issue by basstripper** [bitpay/copay#7372]
I don't get it, i want to transfer my Bitcoin-cash to another wallet but it doesn't work? its says copay only supports new upadated adresses????

**Comment by Gamboster** [comment]
Copay accepts BCH addresses starting with C or H, which is a new convention to prevent errors (https://support.bitpay.com/hc/en-us/articles/115004671663-BitPay-s-Adopted-Conventions-for-Bitcoin-Cash-Addresses-URIs-and-Payment-Requests)

If you need to send to "old" addresses, and you are SURE those are BCH addresses, you can "translate" them using the BCH Translator tool: https://bitpay.github.io/address-translator/
