### ISSUE TITLE
Problem Loading Bitpaycard.

### ISSUE THREAD

**Issue by minitzi** [bitpay/copay#7377]
Hello,
6 hourese ago i try loading my bitpay card with 0.19 btc. 
In the application says Confirming buy the transaction have allready 38 confirmations.
https://insight.bitpay.com/tx/de5c97cbec90065ec99aec9740f829013ffa9266a926937be7008e8b698f29b9

And the money are still not advaible
Any ideea?
Thanks

**Comment by JDonadio** [comment]
Please contact with:

help@bitpay.com
or
https://help.bitpay.com/requestHelp

Providing all the relative information about your issue.
