### ISSUE TITLE
Un-confirmed transaction for almost 7 hours and now transaction cannot be found

### ISSUE THREAD

**Issue by MARTECHGURU** [bitpay/copay#7378]
Copay says I still have a pending un-confirmed transaction but when I view it on the blockchain it says not found. This is the link: https://insight.bitpay.com/tx/cb15f32db029266a983f0aafa7d5a585b2e8e8c61de14338b050d1e461cf9c2d

I also can no longer access my Bitcoin.  It says "All your Bitcoin wallet balance may not be available for immediate spending". This needs to be fixed asap!

**Comment by JDonadio** [comment]
Your transaction is still pending for confirmation. https://blockchain.info/tx/cb15f32db029266a983f0aafa7d5a585b2e8e8c61de14338b050d1e461cf9c2d

Our public insight could not be showing your transaction (need to be fixed) but your funds were sent and you only have to wait.

https://blockchain.info/tx/cb15f32db029266a983f0aafa7d5a585b2e8e8c61de14338b050d1e461cf9c2d

**Comment by MARTECHGURU** [comment]
What about the fact that I cannot access the remaining unsent coins? I still receive the error insufficient funds and that it says "All your Bitcoin wallet balance may not be available for immediate spending". When will this be fixed? My wallet is pretty much unusable at the moment

**Comment by JDonadio** [comment]
Is not an issue. That is how bitcoin works

**Comment by MARTECHGURU** [comment]
That doesn't make any sense.  I've held Bitcoin since August and all the transactions have confirmed long ago.  Now they are un-confirmed?

**Comment by MARTECHGURU** [comment]
To be exact I only transferred 10% of my holding that has an un-confirmed transaction and the rest of my 80% still in my wallet suddenly became un-confirmed an unusable?
