### ISSUE TITLE
transaction has not arrived yet

### ISSUE THREAD

**Issue by AleSmaz** [bitpay/copay#7382]
I sent btc to my wallet, but after 1 day they have not arrived yet. 
The transition was immediately confirmed and I received the email. now if I check in the Copay app it's still in progress ..... but the btc are not back in the wallet. 

what should I do??

**Comment by AleSmaz** [comment]
copay keeps trying to send the btc to my wallet but it does not start. How can I cancel the request and still request to be sent?

**Comment by JDonadio** [comment]
If the transaction is confirmed, your funds are in your wallet. If your balance is not reflecting the correct amount please go to settings > wallet > more opts > wallet addresses > scan addresses for funds
