### ISSUE TITLE
Unconfirmed transaction after more then 20 hours of waiting!

### ISSUE THREAD

**Issue by alex11157** [bitpay/copay#7383]
Hello Support

My Transaction still unconfirmed almost after 24 hours of waitng. And it writes me on blockchain transaction is not found:
https://insight.bitpay.com/tx/d8a5ffd2b98af5eeacc78f27e7328ca06ed8b42bcf80bab4d31f12d1a80bd402

Can you please help me to resolve this issue?

Big thanks

**Comment by JDonadio** [comment]
Your transaction is still pending for confirmation. https://blockchain.info/tx/d8a5ffd2b98af5eeacc78f27e7328ca06ed8b42bcf80bab4d31f12d1a80bd402

Our public insight could not be showing your transaction (need to be fixed) but your funds were sent and you only have to wait.

**Comment by alex11157** [comment]
Ok, thx for reply

Can you predict average time i have to wait?

пт, 8 дек. 2017 г. в 15:29, Javier Donadío <notifications@github.com>:

**Comment by JDonadio** [comment]
In Settings > Bitcoin network fee policy you can set the default level for your transactions. In that view you can see an average time and how much sat/byte are the network claiming in that moment. But you can use a custom value tapping on the fee section (in the confirm view, before send the funds).

**Comment by alex11157** [comment]
Yes, but I RECIEVE bitcoins not SEND in my case. So as I understand my
sender had to put fee not me.

Am I right?

if not, I can change fee in my settings if its helps me to get BTC faster.
Tell me please what better to do in my case.

2017-12-08 15:50 GMT+02:00 Javier Donadío <notifications@github.com>:
