### ISSUE TITLE
Pending transaction with Unconfirmed sending since more than 22 hours 

### ISSUE THREAD

**Issue by milestone77** [bitpay/copay#7384]
Which information do  I need to provide here to get support for this problem?

**Comment by milestone77** [comment]
Wallet Network: livenet
Adress Type : PSPKH
Derivation Strategy: BIP44

**Comment by JDonadio** [comment]
Use a proper fee for your next transactions to avoid this scenario.

**Comment by milestone77** [comment]
The fee was choosen economy and the balance in the wallet was high enough to cover the fee. The transfer is still unconfirmed and not returned.

**Comment by JDonadio** [comment]
https://github.com/bitpay/copay/wiki/COPAY---FAQ#copay-requires-high-fees-for-low-amounts-transactions

**Comment by milestone77** [comment]
So I assumed the transaction is not going to take place at all. Correct?
