### ISSUE TITLE
Pending transaction for more than 25 hours!

### ISSUE THREAD

**Issue by holymana** [bitpay/copay#7385]
I have a pending transaction for more than 25 hours now, the BTC in my account disappear and when trying to see my transaction in the blockchain (insigth bitpay) it says "transaction not found".

Guys, I need to get this operation completed or I need to cancel it, but I cannot have my BTC pending to be sent forever.

**Comment by JDonadio** [comment]
You can open the view, copy the url (before the insight page did load completely) and use the transaction id in any other block explorer to check their status. Sorry about that, we must fix our public insight to show the transactions properly.

**Comment by JDonadio** [comment]
If you do not want be waiting for hours, use a proper fee for your next transactions.

**Comment by holymana** [comment]
Hey @JDonadio, 

Thank you for your answer... But related to your comment: I kind feel you implying that is my fault to wait for a day for a transaction, because I have not choose the **proper** fee... 

I understand that for a faster transaction I need to pay a better fee. 

My problem is **not** that, my problem is when someone tell me that the average time of my transaction will be 2 hours and it is taking more than a day. 

When someone deliver me an information that is more than 1300% incorrect and nowhere in the app says that the transaction can take a lot longer for whatever reason, and on top of it, the app says that your transaction does not even exists...

Anyway, you do understand my side, that this can raise some concerns, right?

But thanks for the answer.

**Comment by JDonadio** [comment]
I get your point, but we cannot handle it. The average times is taking for the core algorithm of bitcoind, isn't set by us. And also are suggestions, you can set your own fee at confirming time tapping on the fee section and selecting the custom value.
