### ISSUE TITLE
NEW WALET, CAN'T RECONIZE MY WORDS

### ISSUE THREAD

**Issue by FredKenchan** [bitpay/copay#7386]
I have download a new wallet, since you warned us to stop using the one from google.
But it doesn't recopgnize the word list i wrote.
why?
Possible accent I didn't pay atention to, and I don't which word should have or not any accent?
I wrote all the words with capital letters? was it like that?
I just wrote the word one by one with a pace in between. Is that the correct way to do so?
What's wrong?

Thanks
Fred
diabriet@gmail.com

**Comment by JDonadio** [comment]
Do you speak spanish?

**Comment by FredKenchan** [comment]
Si, esta arreglado gracias por su repuesta tan rápida

**Comment by JDonadio** [comment]
Genial!

**Comment by parkermor** [comment]
@FredKenchan 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
