### ISSUE TITLE
Copay unconfirmed transaction

### ISSUE THREAD

**Issue by tomaspalazzo** [bitpay/copay#7390]
Hello, i've made a transaction 2 days ago with Copay to Bitfinex, with the lowest possible fee, and it's still unconfirmed. I understand the delay provoked by the low fee, but when i try to see the transaction on Insight (directly from the Copay app button) i get "Transaction not found".

Why does it takes that long? I should be able to see the transaction (unconfirmed or not) in Insights also, right?

Thx! Regards

**Comment by JDonadio** [comment]
You can open the view, copy the url (before the insight page did load completely) and use the transaction id in any other block explorer to check their status. Sorry about that, we must fix our public insight to show the transactions properly.
