### ISSUE TITLE
Still Unconfirmed after more than 30 hours ? I need to recieve

### ISSUE THREAD

**Issue by Martin1970nl** [bitpay/copay#7394]
What can i do than only wait i need to recieve btc ? Thisnis the first time that i have this problem but its really i portant i know that your blockchain site i down i saw it on a other site.. 
How long does i gonna take ?

**Comment by JDonadio** [comment]
You can open the view, copy the url (before the insight page did load completely) and use the transaction id in any other block explorer to check their status. Sorry about that, we must fix our public insight to show the transactions properly.
