### ISSUE TITLE
 unwittingly changed my adres of wallet

### ISSUE THREAD

**Issue by LedoM1337** [bitpay/copay#7396]
Hello! 

Today 6 hours ago I dent my btc to my new walley on Your Copay, I didnt get them and now I incidentally changed address of wallet from 15bVjsE7y57zWsHxQniuKcB4e38nd4z3pz to 19JqFyFxh1VJZcwzTrNpTbnzUrp4gDwuAY. I'm afraid that I lost my btcs :( Please answer my problem

**Comment by JDonadio** [comment]
This is not a Copay or BitPay issue. Unfortunately we cannot do anything in this case. The bitcoin transactions cannot be cancelled or reversed.
