### ISSUE TITLE
Pending transaction for more than 96 hours。。。

### ISSUE THREAD

**Issue by Zaijin** [bitpay/copay#7397]
I have a pending transaction from blockchain.info to my Copay wallet for more than 96 hours now, the BTC in my account disappear and when trying to see my transaction in the blockchain (insigth bitpay) it says "transaction not found".

but, I got some information from blockchain.info.
ScriptSig
Hash 160

Please help, I need to get this operation completed or I need to cancel it, but I cannot have my BTC pending to be receive forever.....

**Comment by JDonadio** [comment]
If your transaction was sent from blockchain.info to Copay, you should contact with their support team.

**Comment by Zaijin** [comment]
Thanks

2017/12/12 2:33 "Javier Donadío" <notifications@github.com>:
