### ISSUE TITLE
Can’t recover wallet with Copay and recovery phrase

### ISSUE THREAD

**Issue by prestonjr** [bitpay/copay#7399]
I have my 12 word recovery phrase and past wallet addresses/verification of past transactions and all that but cannot import my wallet onto my new device. I no longer have my old phone and therefore am now at a loss. I thought the recovery phrase was all I needed? An error message is asking me to check the derivation path and wallet service url. They are auto filled as m/44’/0’/0’ And https://bws.bitpay.com/bws/api respectively.

**Comment by prestonjr** [comment]
My wallet was created and funds were transacted in October of 2016, if that changes the derivation path or service url, I’m not sure.

**Comment by JDonadio** [comment]
In order to restore your wallet you have to use the `import` option, not the create.

**Comment by parkermor** [comment]
@prestonjr 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
