### ISSUE TITLE
Impossible to send bitcoin

### ISSUE THREAD

**Issue by MaximeBrl** [bitpay/copay#7400]
Hello, 
I have 0.0108 btc on Copay, and I tried to send 0.0108 btc with Copay, but the application displays "insufficient funds".

But I have the necessary amount.
Sorry for my English, I'm French

**Comment by mr10008** [comment]
You could try to do the following:

On the window "Confirm" before you click on the bottom to send, there is a field "Fee: ....". Click on it and it will open a window "Bitcoin Network Fee Policy". Change the fee level to "Super Economy" and try again. 

If it does not work, change the fee again again to what is displayed on top of this page: https://btc.com/stats/unconfirmed-tx
That rate is fluctuating all the time and I think during weekends in the morning is lowest.
If that does not work you could set it even lower, like 50 or 30 but then there is always a risk that the transaction will not go through or may even get stack for many days - it's your own risk.

**Comment by patrykzz** [comment]
I have the same problem. Can you tell me how to set it lower? There is no option to lower the fees in the app (to make it any lower than 'super economy').

**Comment by mr10008** [comment]
Yes, there is one more option in the 'Fee level': "Custom" and there you can put even lower fee than Super Economy, but as I said if you put it very low it may not get through or get stuck for many days.

**Comment by patrykzz** [comment]
I went to "Settings" -> "Bitcoin Network Fee Policy" and there I have only 5 options: "Urgent", "Priority", "Normal", "Economy" and "Super Economy". I swear there is no option such as "Custom". What am I overlooking? 
I don't know if it makes any difference but I'm on the iOS app (it looks exactly the same as the Windows app).

**Comment by JDonadio** [comment]
If you need to send all your funds, go to send tab > select your recipient (or put the destination address) > tap on right-top on 3 dots to display the send max option > try to send your funds.

**Comment by MaximeBrl** [comment]
I succeeded yesterday with the same solution as JDonadio

**Comment by mr10008** [comment]
Yes, Patryk, in the Settings there is no option for selecting "Custom", but when you prepare for sending, when the "Confirm" window comes up, just above "Add Memo", you'll see a field "Fee: Super Economy" (if you selected Super Economy in the settings before). So click/tap on that field and a new window will open - "Bitcoin Network Fee Policy" - where under "Fee Level" you can select "Custom" as well. This selection is available on Windows and Android versions. Double check that you have the latest version of Copay.
But check JDonadio's comment above - it resolved the problem of the OP.
