### ISSUE TITLE
Copay BTC funds disappearing act.

### ISSUE THREAD

**Issue by rc009** [bitpay/copay#7401]
Transferred BTC from Bitstamp to new Copay wallet..then to retailer..at which time I was informed of a 20% fee, then the funds vanish. Copay BTC balance now zero. Retailer did not receive.
WTF is going on? I have the blockchain report.

Size | 3443 (bytes)
-- | --
Fee Rate | 0.004340752250943944 BTC per kB
Received Time | Dec 9, 2017 9:44:09 AM
Mined Time | Dec 9, 2017 9:44:09 AM
Included in Block | 000000000000000000817014d9b020715ea313bb04f2946a02942237007f17c2

**Comment by STr8BItcoin** [comment]
IS it showing up now? You have to be patient.

**Comment by rc009** [comment]
No,  When I went back to confirm the fee notice, the window was closed. Then I went back to Copay and it apparently opened a 2nd account- with nothing in it.  I appears I have mistakenly opened 2 copay wallets.  I have the codewords for the first wallet. How can I get to back to the first wallet?

**Comment by JDonadio** [comment]
You can create as many wallets as you want. Please go to settings > choose your wallet (which should receive the payment) > more opts > wallet information, copy the wallet id and paste it here.

**Comment by JDonadio** [comment]
Also, provide us the transaction id made from bitstamp.

**Comment by QuestBit** [comment]
How do we retrieve the missing fund ?

**Comment by BGalliotti** [comment]
Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will happy to help you.
Thanks.
