### ISSUE TITLE
Not received the money on the wallet

### ISSUE THREAD

**Issue by oskolkova** [bitpay/copay#7402]
Hello! Help me.
08.12.2017 15:30:10 
вывод 0.01439116 BTC
address: 19d9ghWqUKeu7HactLKCVJsdmpSs7eos1m 
The money is not received until now

**Comment by Conans14** [comment]
I wish !

**Comment by oskolkova** [comment]
Confirmation from the stock exchange came in the mail, but in the wallet the money was not received

**Comment by Conans14** [comment]
Please explain, this is only my first day as I only opened the wsllet 2hrs ago

**Comment by oskolkova** [comment]
Excuse me, but with whom I communicate?

**Comment by Conans14** [comment]
Conans14

**Comment by KORABIK222** [comment]
hello I've sent my 50000 btcz from exchange to my wallet and still not received them  does anyone have the same problem ?? and the question is how to resolve that

**Comment by Eric31415** [comment]
I am a newbie. When I tried to authorize Coinbase,  I got a error saying Copay was trying to reach an obsolete url. What should I do?

**Comment by JDonadio** [comment]
@oskolkova you just have to wait, unfortunately there is nothing to do in this case.
