### ISSUE TITLE
copay balance fluctuates after funds went missing. sometimes funds there...unable to withdraw

### ISSUE THREAD

**Issue by gasupraman** [bitpay/copay#7404]
I received funds into copay mobile wallet 5 days ago. It took 3 days to process, after clearing there were two unauthorized transactions going out for the full balance. I assumed I was hacked and funds lost but now funds are sometimes there and sometimes gone. I can refresh the app on my Samsung note 8 and every time the balance changes. So confused. when the in there, it still shows insufficient when I try to transfer. Any ideas? There are also other transfers in my wallet leger that are not mine. Thanks!!!

**Comment by omietrice** [comment]
Are you still having the issue. My funds are completely gone and not showing up anywhere. Not to the address I sent to or not in my wallet.

**Comment by gasupraman** [comment]
yes, as of two seconds ago it still shows "Receiving XXXX BTC" under recent transactions. when I swipe down and refesh, the funds are gone. The initial funds were received on Dec 6th and still unable to be withdrawn.

**Comment by omietrice** [comment]
Me too.. where the hell is support? I will be posting a huge thread on Reddit today and have it voted up to the top of the list so no one uses this wallet anymore. Will be attaching all proof copay is stealing funds . Would love to hear what the admins have to say if they even show up.

**Comment by JDonadio** [comment]
@gasupraman please provide your wallet id so I can check the wallet status.

**Comment by QuestBit** [comment]
How do we retrieve the missing fund ?

**Comment by gasupraman** [comment]
082707e5-41da-4f9e-9228-c38850a53ef0

Thanks!

**Comment by gasupraman** [comment]
what is the best way to send the ID securely?

**Comment by JDonadio** [comment]
You can share an address (not necessary with funds) if you want, I can find your wallet with that.

**Comment by gasupraman** [comment]
I really appreciate your help. Is there an email address I can send it to?

**Comment by JDonadio** [comment]
Sure, `javier@bitpay.com`

**Comment by gasupraman** [comment]
Thanks! I just emailed it

**Comment by bearwhalebandit** [comment]
Was this resolved? I experienced the same issue but have not received a reply from support

**Comment by gasupraman** [comment]
Not yet, It has been 6 days which seems a bit long. The sender said they have not received the notification that it has been completed

**Comment by gasupraman** [comment]
also any idea why there would be 3 or 4 other transactions that are definitely not mine in my wallet history?

**Comment by bearwhalebandit** [comment]
Does your transaction show up on a block explorer ?

**Comment by gasupraman** [comment]
In the copay app, when I click on view on  block chain, it's takes me to
insight when it reads "transaction not found"

The funds have still not truly  posted. My balance fluctuates between it
being their and not every time swipe down to refresh

Thank for the help

**Comment by bearwhalebandit** [comment]
Check on blockchain.info and see if it shows up there. I'm curious if it was sent on blockchain at all

**Comment by gasupraman** [comment]
So the transfer I am waiting on says "transaction not found" after clicking
"view on blockchain"

The other random deposits/withdraws that are not mine can be found on the
blockchain ...weird

**Comment by bearwhalebandit** [comment]
How about the transaction you are waiting for. Does that show up on blockchain.info

We are only concerned about the one that's missing at the moment . Insight doesn't work so we need to know if it's showing on other explorers.

Paste the transaction id into blockchain.info

**Comment by gasupraman** [comment]
![image001](https://user-images.githubusercontent.com/34406760/33962011-164409a0-e01e-11e7-8caa-e6fed95c006b.png)

**Comment by gasupraman** [comment]
I tried to copy and paste and I all I have in a JPG from the sender. I tried to manually post the first number and my receiving address and  both came up with nothing. Thoughts?

**Comment by bearwhalebandit** [comment]
Well yours is on blockchain from what I can see meaning it's been sent. Mine the money is gone and it wasn't even transmitted on blockchain

Try using viabtc accelerator to speed it up

**Comment by Condebk717** [comment]
Please what is going on, I use my key, the fucking right key still yet is telling me it doesn’t match with my address, same key I used on the 10th, this is frustrating please tell me what’s going on?

**Comment by carlosgfranco** [comment]
Similar to https://github.com/bitpay/copay/issues/7807
Any solutions?

**Comment by gasupraman** [comment]
Not really,  the sender canceled it
