### ISSUE TITLE
Copay you guys need to address these situations...

### ISSUE THREAD

**Issue by omietrice** [bitpay/copay#7407]
There's a ton of users here with disappearing txs and funds including me. Can a mod please give us insight as to what's going on? How are we supposed to be able to rely on copay going forward if there are mishaps like this. Where is the support ?

**Comment by JDonadio** [comment]
You're right, and we are working on that. You can open the view, copy the url (before the insight page did load completely) and use the transaction id in any other block explorer to check their status. Sorry about that, we must fix our public insight to show the transactions properly.

**Comment by omietrice** [comment]
Why is this closed ? You didn't address the issue.. I'm aware I can view it in other block explorers but the tx is not valid in ANY block explorer and my Bitcoin is gone. What kind of support are you? You keeping answering the same thing on everyone's ticket.

**Comment by omietrice** [comment]
6cca5478-6331-4df5-9f8c-b280e7a12b1e


Wallet I'd... Please look

**Comment by JDonadio** [comment]
That is the transaction missing?

**Comment by omietrice** [comment]
How can I show you a screenshot ?

**Comment by omietrice** [comment]
Do you have an email where I can better explain the situation .. the missing transaction shows up when you clear the transaction cache.

**Comment by omietrice** [comment]
It is showing up as recieved in the recipients phone but then disappears. He is also using copay.. the funds have been sent from my wallet but the transaction I'd doesn't work in any block explorer.

**Comment by omietrice** [comment]
Please view this Reddit thread where I show you what I mean..


https://www.reddit.com/r/Bitcoin/comments/7j31d5/copay_stealing_funds_upvote_this_so_no_one_is/

**Comment by omietrice** [comment]
https://insight.bitpay.com/tx/83309d5858cf226c3c0edd360c36a2c0c059db3da3a3582f47df6cd468bf2f80



Still not addressed.
