### ISSUE TITLE
I sent BTC ON 9 DECEMBER BUT NOT ARRIVED

### ISSUE THREAD

**Issue by AleSmaz** [bitpay/copay#7408]
I sent BTC ON 9 DECEMBER BUT NOT ARRIVED. I have confirmation of the blockchain .... where are they ????

**Comment by omietrice** [comment]
Their support is garbage and they are pretending like it's "Bitcoin"

**Comment by AleSmaz** [comment]
Please answer...

**Comment by QuestBit** [comment]
How do we retrieve the missing fund ?
