### ISSUE TITLE
BitPay Amazon Gift Card Fraud

### ISSUE THREAD

**Issue by sirazrin** [bitpay/copay#7409]
i have pay for amazon gift card but nothing have been provided..i want a refund or amazon gift card code

https://insight.bitpay.com/tx/123d74ffa0b9009502e8b1120d3e04223c18ccd6b87422bd73bc3e058b003fac

**Comment by JDonadio** [comment]
https://github.com/bitpay/copay/wiki/COPAY---FAQ#amazon-gift-card
