### ISSUE TITLE
Funds not received

### ISSUE THREAD

**Issue by cryptoforex** [bitpay/copay#7411]
Hello I have the APP wallet of BTCZ(BTCZ Wallet) the funds were sent to this wallet but it don't appears in my app.

I checked the blockchain and the transaction is ok.

https://btczexplorer.blockhub.info/address/t1X8AWVnNTa3nmvV3KMrRAuXTJc5kt8rt6L

Thanks.

**Comment by gabrielbazan7** [comment]
BTCZ is not supported by Copay or BitPay

**Comment by cryptoforex** [comment]
In the APP appears this site as support.
Thanks.

**Comment by QuestBit** [comment]
How do we retrieve the missing fund ?
