### ISSUE TITLE
I can't send my bitcoins.

### ISSUE THREAD

**Issue by patrykzz** [bitpay/copay#7416]
I have 0.00055 BTC and there is no option to lower the fees in the app (to make it any lower than 'super economy') so I cannot send my money anywhere.
To be precise - I went to "Settings" -> "Bitcoin Network Fee Policy"  and ticked the "Super Economy" option.
I tried the option to ''send the max amount'' and I got an error - "not enough funds for fee".
What should I do?

**Comment by JDonadio** [comment]
https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-always-get-insufficient-funds-for-fee-when-trying-to-send
