### ISSUE TITLE
transaction not found

### ISSUE THREAD

**Issue by kadekchelsea** [bitpay/copay#7422]
im just send bitcoin 0.01 and unconfirmed , when i check on insight, they say transaction not found, but in bitpay APP still say "sending" 

https://insight.bitpay.com/tx/5de736f2ade7d77375dcce50c837817ac4ffcf4e8a05efd91e0448ce2690809b

i lost my money ?

**Comment by militant13** [comment]
Have same problem bitpay wallet is terrible
