### ISSUE TITLE
Payment options

### ISSUE THREAD

**Issue by ThomasFreedman** [bitpay/copay#7424]
I think it's great you are adding support for BCH in BitPay's wallets, but I want to see merchants accept it too. 

If a merchant currently uses the BitPay service, what must they do to begin accepting payments in BCH? None of the merchants I use that use BitPay to process their crypto payments allow me to pay with BCH and I don't know if that's a limitation of BitPay or the merchant.

I hate seeing the cost of BTC transactions going up so much, they're ridiculous! BitPay complained that a transaction fee of .00075BTC was too low (that was like 4% of transaction value) and so it might cause delays!!!

The mainstream invasion has begun, and with it mainstream greed and corruption comes. This trend is contrary to the vision, precepts and purposes cryptocurrency was invented for.

What is BitPay doing to help?

**Comment by JDonadio** [comment]
This repo is for Copay and BitPay wallets only. If you have suggestion or inquiries please go to https://help.bitpay.com/requestHelp or send an email to help@bitpay.com.

In the meantime, I can tell you they are working a lot to support BCH ASAP.

**Comment by ThomasFreedman** [comment]
That's good news. Hope they hurry!
