### ISSUE TITLE
Transaction not received on my MybitcoinZ wallet

### ISSUE THREAD

**Issue by Visents** [bitpay/copay#7425]
Hello, I need help. I sent a transaction of 30000 btcz of tradesathosi yesterday and I I have not received the coins in my MyBitcoinZ wallet.
The transaction number is:
494d716555b413b515ac8ea9c0aadb0ff15fd73db6886369ef094bbf921a8162
Thank you

**Comment by JDonadio** [comment]
We don't support BitcoinZ
