### ISSUE TITLE
Transaction not found

### ISSUE THREAD

**Issue by whatgoesaround** [bitpay/copay#7426]
tx id: 80432116d99a01c21e4666f07f8bdc10ef7d51f16b2644e2fd0bf01357e7aa33

0.25BTC sent to 1PGHei7a8nDegojsoYN6SaMaqfkpE9HJN3

Insight block explorer shows no transaction, yet copay app shows the tx and is unconfirmed.

**Comment by JDonadio** [comment]
Please check your transaction here: https://blockchain.info/tx/80432116d99a01c21e4666f07f8bdc10ef7d51f16b2644e2fd0bf01357e7aa33

For some reason our public insight are not working as expected, we are trying to find a solution.
