### ISSUE TITLE
Cant  send  my  btc  i have 0.00285  

### ISSUE THREAD

**Issue by CheSchamil** [bitpay/copay#7439]

**Comment by CheSchamil** [comment]
why  cant  i  send  them

**Comment by JDonadio** [comment]
Do you have only one input ? you can check it in settings > wallet > more opts > wallet addresses and scroll down

**Comment by JDonadio** [comment]
If you have many small inputs, your balance is not economically viable to be spend. However, you can try setting a custom fee in the confirm view, tap on the fee section, select the custom option and set a low value.
Another option is using the send max, in the amount view tap on the top-right (3 dots) to display the send max option.

**Comment by CheSchamil** [comment]
what is  the lowest amount  that  i  can  send

**Comment by JDonadio** [comment]
You can set even 1 sat/byte. But obviously it's not recommended. You must know that a low fee means more time to be confirmed or even never confirmed. 

For more info check this out: https://github.com/bitpay/copay/issues/5164#issuecomment-265569494
