### ISSUE TITLE
Never put mone in this  site !!

### ISSUE THREAD

**Issue by CheSchamil** [bitpay/copay#7443]
sry  but  this is  a scram  if ist not  then  explain it to me....
i put 50€ in btc  and got 0.00285 btc hmm  ist ok but After sending the 0.00285 to my other wallet, I only had  0.00142 are u kidding me ?!?
 bitpanda is better  that this  site 
never had  a Problem with it  and  never  that Kind of greedy site !!

**Comment by interfect** [comment]
That sounds like you ended up paying a high transaction fee. Transaction fees on BTC can easily get up into the tens of Euros.

BCH might have lower transaction fees. But that's not Bitcoin; it's a different currency.
