### ISSUE TITLE
Funds lost when sweeping paper wallet

### ISSUE THREAD

**Issue by krcs3865** [bitpay/copay#7445]
Hi,

I just swept my paper wallet that had a balance of .001 BTC into my mobile Copay app. For some reason, it only withdrew .000275 BTC, and now my paper wallet is empty when I scan it. Is there something I'm missing here? Why did I just lose 73% of my money?

**Comment by JDonadio** [comment]
You have the tx id in your wallet, please provide us

**Comment by jkokorian** [comment]
The 0.000725BTC you lost was very likely used as the transaction fee. Transaction fees are very high at the moment. Quote from https://bitcoinfees.earn.com/:
> The fastest and cheapest transaction fee is currently 390 satoshis/byte, shown in green at the top.
> For the median transaction size of 226 bytes, this results in a fee of 88,140 satoshis.

This means that for the same transaction you made four days ago, today you would pay a fee of:  
88140 satoshis * 0.00000001 btc/satoshi = 0.0008814 btc. Compared to your input value of 0.001BTC, this is a fee of more than 88%.
