### ISSUE TITLE
5 Transactions Not found

### ISSUE THREAD

**Issue by legendsum** [bitpay/copay#7446]
Here r those tx id:
3a809f30adeb167c12b53927b935cec748a8f9c8e502ce3eca00bc3158a12bb8
3324f9f44bf075e6c71460fdd1cdd27f061602dc3cbe40a5cd0fb54b2b5baed7
56c7a12803dfaf9b138f0cd0894c7aa7ab7a389a2905cad7ead2681bc26a2852
970b783231e56dea05600e0c080717178f53230380fca576c37b8b17e9ccb8bd
7fdb47188579699cbf2243967f822432dc4516af71704c407575273983059856
recevie address:
15iMzFeV8cY3qGBoCJ7VFo21jbe7jTtEha
15iMzFeV8cY3qGBoCJ7VFo21jbe7jTtEha
16VB7Sj1Z7jK3kSuAEp9EDf7fapVnPYXhn    
15Gvrw2XNipSnB5Zggankm6wpVYUFwJqoc
1GUdtCMu1ETwvpCPwm7dh18A7sy8kSWawQ

When i click  view on blockchain it show transaction not found
Some time bitpay show me this error "Transaction not avaliable at this time"
![yulandaxo](https://user-images.githubusercontent.com/33971271/33919150-06f371a6-dff2-11e7-9e89-ba510be7cf29.jpg)
![transaction nt avaliable at this time](https://user-images.githubusercontent.com/33971271/33919153-0ca9e40e-dff2-11e7-99ca-e4b8e1ff1c4c.jpg)
Here r one of those transactions.

**Comment by carlosgfranco** [comment]
hi legendsum, was your issue solved? Similar issue: https://github.com/bitpay/copay/issues/7807

**Comment by legendsum** [comment]
had been solved. thx

2018-01-15 3:19 GMT+08:00 Carlos <notifications@github.com>:
