### ISSUE TITLE
Stolen BCH please help!

### ISSUE THREAD

**Issue by SergGT** [bitpay/copay#7447]
Yesterday I discovered a transaction in Copay which I did not do on an unknown wallet. Everything that was there. Please help me get my BCH back?
![photo5298683703079315525](https://user-images.githubusercontent.com/34500448/33923933-c922b9d4-dfe4-11e7-819a-0a43686740bc.jpg)

**Comment by gabrielbazan7** [comment]
Sorry but there is nothing we can do for you.
