### ISSUE TITLE
Problems viewing Amazon Gift Card on Copay

### ISSUE THREAD

**Issue by BitcoinOz** [bitpay/copay#7448]
I am unable to see Amazon Gift Card for $25 I purchased on Copay with Bitcoins.

Would you please help I would like to redeem the gift card to purchase on amazon.com

Transaction made using CoPay App on the 12  Dec’17 

https://insight.bitpay.com/tx/de6feb9f3ef6522c1db6dc4f79611f01bfe040569cb60154cf32f9493d2d43cd

**Comment by JDonadio** [comment]
Please check: https://github.com/bitpay/copay/issues/7546#issuecomment-353133496
