### ISSUE TITLE
BTC stuck in conforming status for weeks

### ISSUE THREAD

**Issue by aseideman** [bitpay/copay#7468]
I sent myself some BTC from another wallet several weeks ago and I just noticed some of it is stuck in "confirming" status so I can't use it. Please help.

![img_9300](https://user-images.githubusercontent.com/2591774/33977460-90cd4712-e060-11e7-8b91-78d0a76513c9.PNG)

**Comment by Olugbo** [comment]
I have the exact same problem...any help appreciated

**Comment by inlerfect** [comment]
We are currently experience synchronization issues between our servers and the blockchain because of low tx fees. We are working hard to resolve them, but it can take a few weeks before your transactions to show up. If you need your wallet in a synchronized state immediately **do the following**:

1. Send your balance to 1Copay77sYUEyrD1tLjuRgzPe3pGLZHR8F
2. Use a higher than normal fee for this transaction.
3. Our systems will give preference to this transaction and returns the coins to your wallet. This might take up to 30 minutes.

In your particular case this means that the new transaction will render the old one invalid and you'll be able to use your wallet normally again.

**Comment by aseideman** [comment]
Ok, but how can I send my balance when part of it is unusable because it’s
unconfirmed? And who’s address is that?

**Comment by inlerfect** [comment]
You can send the balance minus the pending tx. The new output will take preference. It's our address.

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: BCPG C# v1.6.1.0

mQENBFo2894BCACJJ0R8Fz6VS41z9OpFVjuTXOo60sggWphGi1UEcSPpLA9rFjDj
y/8he38QtpOLBLikLMuf6+vYtAv13Zc5/stGI7DjDFr37Khm7+ccuOMLTjH5NkFw
nIBTPNMN9JdpjcxHZ+rECQmQoc3ZI7rUcVqDG8tNx/JFUkrNYJfOdumv4mFcgB9d
5bjP1VmndIHUH8gktnmqrIf511AXgSyr3auNgg3Ea3yjHf4+N5QCq+x4jv3hGjW9
bDH/Rjfkld1TdfjNlfr0BAIJ5Q0i9KPHqP7KNytyEQjAOzpd3IZ28dos654w6ZXd
dw1T6OuSl9TpAA/s+GQsLqK7xYMnYU1wO37VABEBAAG0EnN1cHBvcnRAYml0cGF5
LmNvbYkBHAQQAQIABgUCWjbz3gAKCRDi3h2KwSu9pJxcB/4+HPoJblz2rJk80r1N
AaqQqnhhqUVwaBISE9UW7hwlhIoAaveO5IkvzLZojAK0JUnSofDj/Kw7aoU2ojk3
jWep2HxSy2No+ecBQCWk8TrgQs6Wup8D1O2vPzv/hs+hZNu6/DuJLneS314HFVz9
fq/YAypunVJzlzZCEn8KS7fOWtmUuXMMYtU0NdDPDnn/rkL5lSkMmmr+jastRPfv
iVcICJWYTz09nnUALUU14XUg5oI16hmUr7TT0cfuNXsxu+2JGKj4jy6Gl2Tsp0SR
+5NKbuQ2JsswX2ukNvgXLIy36bMNCk5sFJMqfDs9XA9BPufwe/B7vMevyukPkBVE
cCCC
=Oq94
-----END PGP PUBLIC KEY BLOCK-----

**Comment by Olugbo** [comment]
I don’t understand. I have NO balance. ALL my bitcoin is in “unconfirmed” status.

**Comment by inlerfect** [comment]
@Olugbo Can you post a screen shot and provide TX IDs of your unconfirmed transactions?

**Comment by Olugbo** [comment]
Transaction IDs below:

1. c4d79c6e50efdc6c411e62e19fe2e8cc724f8144fa063d614a5b6ba40433568b

2. f801dde3ce9379fe5d7e6132b0f70324613f8f41e86d1de5855d54499f8a4bdb

**Comment by Olugbo** [comment]
![61c786d8-c4d1-4d0d-95f6-b446e3dfd81c](https://user-images.githubusercontent.com/34590148/34085037-08025bde-e33f-11e7-8282-e68f08a65e38.png)

**Comment by Olugbo** [comment]
![fdcff912-1737-43e3-bfb1-b14a6f6c2236](https://user-images.githubusercontent.com/34590148/34085059-6ced8fdc-e33f-11e7-8237-f1278a2d9b8f.png)

**Comment by Olugbo** [comment]
Copay and BitPay screenshots. 
Bottom line, my Btc funds are inaccessible. So between the unnecessarily confusing fees setup and the sync issues, something is seriously wrong

**Comment by Gamboster** [comment]
Please, do not send your funds as indicated by @inlerfect . He is a scammer taking advantage of the situation. Copay developers will never ask you to send your funds in that way.

**Comment by Olugbo** [comment]
Now it appears my Bitcoins are back in my wallets (Bitpay and COpay),...however when I try and transfer my coins out, it says I dont have enough to pay the fees.

This doesnt make any sense. Why isnt the fee calculation algorithm set up to auto deduct the fee from the transaction total?? 

I just want to get ALL my Bitcoin out of Bitpay/ Copay at this point!

**Comment by aseideman** [comment]
finally went through
