### ISSUE TITLE
Try to use unconfirmed output to confirm previous transaction

### ISSUE THREAD

**Issue by telexqwerty** [bitpay/copay#7477]
Hi guys,

I sent a transaction with a low fee and now it got stuck for 2 days. I have seen previous posts that just wait until the funds return. I would like to ask, how to stop the Copay app from re-broadcast the transaction? Can I just simply don’t open the app on the phone?

Thanks for any help!

**Comment by telexqwerty** [comment]
Sorry, let me keep going. Then today I just sent another transaction from the remaining balance om copay and set a higher fee. I saw somewhere that they yse this method to confirm the precious transaction. Because the miners want the fee of the second transaction, which is depend on the first transaction, they will include both transactions in their blocks. Is that true?

**Comment by militant13** [comment]
Any solution?
