### ISSUE TITLE
Restoring wallet addresses

### ISSUE THREAD

**Issue by Numline1** [bitpay/copay#7484]
Hello, I was testing a wallet restore from a seed yesterday. I created a new wallet and generated 5 brand new addresses, deleted the app and re-created the wallet using the restore process, just using the original 12 words.

What caught my eye was the fact that not only it restored the wallet, it also restored all 5 unused addresses. I went through BIP44 documentation and my understanding is the restore process should check the first derived address, figure out whether there are any funds available on it and if so, derive additional addresses, repeating the process. However, as mentioned, these addresses were unused and empty, yet Copay managed to restore them.

The grand question is: Are these addresses backed up with Copay servers, and if so, how are they matched with a wallet? Is the seed also uploaded to Copay/Bitpay and what other information is shared online?

Thank you!

**Comment by JDonadio** [comment]
Each address generated by Copay/BitPay belongs to your wallet. You can check all your used/unused addresses in settings > wallet > more opts > wallet addresses. Once you receive a payment into an unused address, a new one will be derived automatically (reseting the max gap -20- to 0).
