### ISSUE TITLE
Didn’t get 0,27 BTC!

### ISSUE THREAD

**Issue by dragoyyy** [bitpay/copay#7487]
Hello, 2 hours ago I bought 0,272951 BTC via bitcoin atm  general bytes and didn’t get anything! I have a receipt. What happend ?  Please help! Address: 1L85wc4riJajYLRwRPgq3cYCDNitCaD1S3

**Comment by Numline1** [comment]
Bitcoin purchases can take up to several hours, depending on many factors, like networks current amount of transactions, used fee and others. Try to look for transaction ID, check for its recipient address (Copay generates a new address for each transaction). This address should display a pending transaction and depending on the transaction fee, it may take several hours to several days to complete.

**Comment by dragoyyy** [comment]
This address is in the list of unused transactions without any info of pending etc. Besides that I have two other transactions that are uncorfirmed since 13.12.2017.  They are 19Amsvw7SVGdeJLNtN1x1zqAJB3jrZRGkW
1NPM957AriMS2KY4P1a3zyz9WmKvb9jpcq
Why?

**Comment by Numline1** [comment]
I'm not sure about your original transaction, as you said, the address you stated doesn't have any pending transactions. This is something you should probably discuss with the ATM owner. Is the transaction amount the amount that's currently waiting to be transferred to one of the addresses in your recent post?

If so, the problem with your recent transactions (the string you've posted is not a transaction number, it's a BTC address) is the fee, which is extremely low.

For both 

https://www.blocktrail.com/BTC/tx/edaee258b5c692998db100e685c438bd0a41ea0a374b7bf1b651a37d7558fbcb

and

https://www.blocktrail.com/BTC/tx/c4630e43922e7e0f8218916c6f2a048476eb9f570335d3f4291511e1f0ca7d52

the fee is about 10 satoshi per byte. Lower fees take longer to confirm, 100 satoshi/byte is usually a few days, 10 can be months or never, see https://bitcoinfees.earn.com/

I'm not sure how you got these BTC, whether it was the ATM as well, but make sure, next time, to check whether you can bump the fee (300 satoshi (0,00000300  BTC) per byte is usually the average at this moment, but changes constantly). As for your current unconfirmed transactions, if I were you, I'd look into options on how to bump the fee a bit higher. This can be Googled fairly easily.

**Comment by dragoyyy** [comment]
Thanks, now it’s fine, I received everything
