### ISSUE TITLE
Amazon Giftcard - Coins send - nothing received

### ISSUE THREAD

**Issue by KimInSky** [bitpay/copay#7491]
Hello,
I wanted to buy an Amazon giftcard and transfered a big amount in Bitcoins. Then it said Error. Coins were send but no giftcard received. 
How can I get my money back or the giftcard I tried to buy??

**Comment by chetorro** [comment]
+1

**Comment by effektz** [comment]
+1

**Comment by altafx** [comment]
+1

**Comment by JDonadio** [comment]
Please check: https://github.com/bitpay/copay/issues/7546#issuecomment-353133496
