### ISSUE TITLE
SCAM? Amazon Gift Card Failure - Bitcoins are gone, no gift card, no response from support

### ISSUE THREAD

**Issue by altafx** [bitpay/copay#7493]
The title says it all, **FOUR DAYS** ago I tried to buy an amazon gift card and the purchase failed, but my bitcoins were _still_ removed from my wallet. I contacted BitPay support and I have not received a response back other than "we will reply in 1-3 days". Well it has been over FOUR DAYS now with NO response. I sent the blockchain transaction, the bitpay invoice, bitpay wallet ID, screenshots, etc.

I need to know what the hell is going on with my funds, and _when_ I am either going to get my bitcoin refunded, or my gift card added to my account, because at this point I feel like I've been scammed out of almost $1,000 by bitpay

**Comment by altafx** [comment]
Here we are, 7 days after the failed purchase, no response from anybody at BitPay...

**Comment by Ted-Mohamed** [comment]
same thing happened to me, I emailed them and they that I should talk to the merchant...

**Comment by altafx** [comment]
@Ted-Mohamed so they actually replied back to you? still no reply to me yet!

And BitPay _is_ the merchant, they are the one taking our bitcoin and giving us an amazon gift card in exchange. Who the hell do they expect us to contact to get our gift card, _BitPay_ is the company who took my money, and they are the ones who need to fulfill their side of this order.

**Comment by Ted-Mohamed** [comment]
That's screenshot of the reply I got
![screenshot](https://user-images.githubusercontent.com/735234/34170519-71c81498-e4eb-11e7-90e7-808f8cc5c948.jpg)

**Comment by altafx** [comment]
@Ted-Mohamed What merchant are you suppose to contact to get the order fixed, Amazon? This seems totally unacceptable...

Imagine if I went to Walmart.com and bought an Amazon gift card. Walmart takes my money but doesn't provide me with a gift card, and when I ask for a refund or my gift card, their response is "not our problem, contact the merchant"?

It's BitPay's app, it's BitPay's invoice, its BitPay's responsibility to fulfill the order their customer placed with them.

**Comment by Ted-Mohamed** [comment]
@altafx yep I know, I emailed them asking who is the merchant I'm supposed to contact I have not heard back yet :(.

**Comment by altafx** [comment]
@Gamboster @cmgustavo any input or assistance? you seem to be active on other issue threads but these ones are being ignored, why?

**Comment by JDonadio** [comment]
Please check: https://github.com/bitpay/copay/issues/7546#issuecomment-353133496

**Comment by altafx** [comment]
@JDonadio I have been waiting _TEN DAYS_ for a response from anybody at BitPay which is the entire reason I am bringing up this issue publicly, because I can't get any other response.

**Comment by altafx** [comment]
13 DAYS LATER - Still no response from anybody at BitPay through official support channels, or unofficial channels like Github, Reddit or Twitter.

**In fact the official BitPaySupport twitter account hasn't said or done anything in OVER A MONTH! 😆 :rofl:** [https://twitter.com/bitpaysupport](https://twitter.com/bitpaysupport). If BitPay gave up on support publicly over a month go, why would ANYBODY think they'd get a reply from customer support through official channels?

THE COMMUNITY WANTS A RESPONSE, THOSE OF US WHO HAD BITCOINS STOLEN FROM US AND NO GIFT CARD GIVEN TO US DESERVE AND DEMAND TO KNOW WHATS GOING ON, AND TO HAVE THE SITUATION FIXED BY BITPAY.

**Comment by altafx** [comment]
19 days later, no response, no update, no contact, absolutely NOTHING from BitPay

**Comment by altafx** [comment]
To follow up, after requesting help here, reddit and twitter I finally did get a response from BitPay and got the redemption code. Thanks

**Comment by Ted-Mohamed** [comment]
@altafx good job and congrats on getting it back 👍. I guess I have to wait a month too..
