### ISSUE TITLE
Problems importing wallets

### ISSUE THREAD

**Issue by XaviSF** [bitpay/copay#7496]
Hello all, i 've seen some problems like that one, but i couldn't fix it with any of the solutions I found.

I changed my iphone some days ago, and with the new iphone I downloaded the copay app, The problem is when i try to import my old wallet,  It appear this message:

Could not access the wallet at the server. Please check:
The password of the recovery phrase (if set)
The derivation path
The wallet service URL

OK, i have a password but i add it and it shows same error. So i'm not sure what to do with the derivation path and the wallet service URL.

Anyone can help me?

Thanks!

**Comment by telexqwerty** [comment]
Have you tried just to import the seed words, no need the password?

**Comment by XaviSF** [comment]
Yes, this is the first thing i did.
The “funny” thing is that i could import another wallet with no problema. But this wallet that i have  some money give me this error. Im quite frustrated

**Comment by JDonadio** [comment]
That message will appear:

* If you put a wrong password or do not provide one (if was set)
* If you put one (or more) words in a different order
* If you set a different derivation path

**Comment by XaviSF** [comment]
Thanks @JDonadio . It 's the password. I typed another one.

**Comment by Alexatkc** [comment]
I have the same problem,please help what can I do?
