### ISSUE TITLE
Copay 2-2 Signature Wallet Problem

### ISSUE THREAD

**Issue by PeterDavid33** [bitpay/copay#7503]
Is it possible to restore a 2-2 Signature wallet if only 1 of the 2 parties has his recovery phrase? If so, how would we go about doing that? 

And I have heard that if we have our extended private keys ( which I do ) we can recover the bitcoin but it requires using bitcore-wallet-client with a custom app but I don't know how to do that so any instructions would be nice.

Look forward to hearing a response from you guys!

**Comment by Gamboster** [comment]
Hello @PeterDavid33 Peter, unfortunately to recover the funds of your wallet 2-2 you will need the backup of both parties.
If you could recover the funds with just a signature, the 2-2 format would be meaningless (For this there are 1-2 wallets)

**Comment by PeterDavid33** [comment]
@Gamboster But if someone has access to an extended private key wouldn't they have access to the funds?

**Comment by PeterDavid33** [comment]
@Gamboster Or are you saying that sense this is a multi-sig wallet there 2 private extended keys that are needed to move the funds?

**Comment by Gamboster** [comment]
> But if someone has access to an extended private key wouldn't they have access to the funds?

No, what you will need are the two extended private keys. Sorry
Each part corresponds to one
