### ISSUE TITLE
Stuck in sending/ unconfirmed 

### ISSUE THREAD

**Issue by Olugbo** [bitpay/copay#7505]
I have a transaction stuck in sending/ unconfirmed for over 24 hours. Any advice appreciated

**Comment by militant13** [comment]
Me to on bitpay

**Comment by Olugbo** [comment]
Now it appears my Bitcoins are back in my wallets (Bitpay and COpay),...however when I try and transfer my coins out, it says I dont have enough to pay the fees.

This doesnt make any sense. Why isnt the fee calculation algorithm set up to auto deduct the fee from the transaction total?? 

I just want to get ALL my Bitcoin out of Bitpay/ Copay at this point!

**Comment by militant13** [comment]
I finally got my money out send with a incredibly high fee

**Comment by melvinhines** [comment]
I have a powerful mining setup running on solar panels and I can process/confirm your transaction in 4 hours tops. Contact me at melvinhines@protonmail.com with the transaction ID and amount. Service is free.

**Comment by BGalliotti** [comment]
Hello, sorry for the delay,
We are closing this thread, please if you still need support, open a new one, we will happy to help you.
Thanks.
