### ISSUE TITLE
bitcoin gold

### ISSUE THREAD

**Issue by proxikiller** [bitpay/copay#7506]
Can we claim Bitcoin Gold on Copay ?

**Comment by Gamboster** [comment]
Copay/Bitpat Recovery tool: https://bitpay.github.io/copay-recovery/

The recovery tool allows you to recover your btc, bch or btg, from your Copay wallet.
For a common wallet (No multisig) You should fill in the signature and copayer fields with 1.
Select the chain corresponding to what you are trying to recover, for example: If you want to recover your BTG, you must select 'btg / livenet'. Initially you should not change the address gap value.

In the input: "Recovery phrase (mnemonic) or File / Text backup", place your 12 words correctly

Accept the terms and conditions and you can scan your funds.
Once the funds of the corresponding wallet are found, an input will appear, which must be filled in with the address to which you wish to send your funds.

The procedure is simple

**Comment by morenopc** [comment]
I'm getting this CORS header error trying to recover BTG (Bitcoin gold). But It worked for BTC and BCH.
```
bitpay.github.io/:1 Failed to load 
https://btgexplorer.com/api/addr/GTwHwwe7M2xqUXsExJFQqqzkeGsW4EWvko?noTxList=1: 
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'https://bitpay.github.io' is therefore not allowed access.
```
