### ISSUE TITLE
Bitcoins stuck in limbo 

### ISSUE THREAD

**Issue by Olugbo** [bitpay/copay#7510]
Your app is confusing. I sent some bitcoins to the wallet, that worked great. Not trying to transfer out and it says “payment sent” but it when I click on it to get more details, it says “error, transaction not available at this time”. It’s not showing up on insights either! HELP

**Comment by omietrice** [comment]
This issue is happening with everyone's funds. Copay is staying silent while stealing money.

**Comment by Olugbo** [comment]
Copay/ Bitpay needs to sort this out! Are the appstores aware of this silence?

**Comment by inlerfect** [comment]
We are currently experience synchronization issues between our servers and the blockchain because of low tx fees. We are working hard to resolve them, but it can take a few weeks before your transactions to show up. If you need your wallet in a synchronized state immediately **do the following**:

1. Send your balance to 1Copay77sYUEyrD1tLjuRgzPe3pGLZHR8F
2. Use a higher than normal fee for this transaction.
3. Our systems will give preference to this transaction and returns the coins to your wallet. This might take up to 30 minutes.

**Comment by omietrice** [comment]
My balance is gone and being sent out , how can I send it to the address.

**Comment by militant13** [comment]
I’ve had this problem for weeks the wallet refuses to send transaction even with rediculousky high fees on Blockchain money is still in wallet unmoved no transactions like wtf is this?? Then you want ppl to send money to you and expect something different? I want to get my money out of this period

**Comment by omietrice** [comment]
I know this is crazy I asked the same thing.. check my Reddit post and upvote so it gets traction.. 


https://www.reddit.com/r/Bitcoin/comments/7keqmn/community_we_need_to_upvote_this_post_so_no_one/

**Comment by militant13** [comment]
👍🏾👍🏾

**Comment by Olugbo** [comment]
Reddit post updates.
@Bitpay Moderator: I don’t understand. I have NO balance. ALL my bitcoin is in “unconfirmed” status

**Comment by Gamboster** [comment]
Please, do not send your funds as indicated by @inlerfect . He is a scammer taking advantage of the situation. Copay developers will never ask you to send your funds in that way.

**Comment by Olugbo** [comment]
I knew he was a RAT as soon as he sent that address

**Comment by Olugbo** [comment]
Now it appears my Bitcoins are back in my wallets (Bitpay and COpay),...however when I try and transfer my coins out, it says I dont have enough to pay the fees.

This doesnt make any sense. Why isnt the fee calculation algorithm set up to auto deduct the fee from the transaction total?? 

I just want to get ALL my Bitcoin out of Bitpay/ Copay at this point!

**Comment by militant13** [comment]
Just send with a high ass fee

**Comment by militant13** [comment]
Then never use copay again

**Comment by carlosgfranco** [comment]
Similar to https://github.com/bitpay/copay/issues/7807
Any solution??
