### ISSUE TITLE
Bitcoin Gold

### ISSUE THREAD

**Issue by rhys86** [bitpay/copay#7511]
How do I claim my Gold?
Will you be adding support for Gold like you did with Bitcoin Cash?

**Comment by Gamboster** [comment]
Copay/Bitpat Recovery tool: https://bitpay.github.io/copay-recovery/

The recovery tool allows you to recover your btc, bch or btg, from your Copay wallet.
For a common wallet (No multisig) You should fill in the signature and copayer fields with 1.
Select the chain corresponding to what you are trying to recover, for example: If you want to recover your BTG, you must select 'btg / livenet'. Initially you should not change the address gap value.

In the input: "Recovery phrase (mnemonic) or File / Text backup", place your 12 words correctly

Accept the terms and conditions and you can scan your funds.
Once the funds of the corresponding wallet are found, an input will appear, which must be filled in with the address to which you wish to send your funds.

The procedure is simple.

>Will you be adding support for Gold like you did with Bitcoin Cash?
Not for the moment.
