### ISSUE TITLE
does not come bitcoin

### ISSUE THREAD

**Issue by shikhovets** [bitpay/copay#7512]
![default](https://user-images.githubusercontent.com/34610244/34074686-b4282ac6-e2c5-11e7-9128-01f96999e566.JPG)

does not come bitcoin
18z2wSUxTMpJ5RVXT9aTssjUuzBb88B4mf

**Comment by shikhovets** [comment]
sent from kassa.cc

**Comment by interfect** [comment]
I checked both the Bitcoin and Bitcoin Cash blockchains and it looks like nobody has ever sent anything to 18z2wSUxTMpJ5RVXT9aTssjUuzBb88B4mf. Kassa.cc still has your Bitcoins.

**Comment by Gamboster** [comment]
If you have not received the funds at that address, and you are sure that this is a valid address for your wallet, you should contact the support of kassa.cc

**Comment by shikhovets** [comment]
thanks for the answer

**Comment by korison** [comment]
@shikhovets 
I can recover your lost fund if you want need help send me email : anywalletrecovery@gmail.com
