### ISSUE TITLE
btc recovery - noob needs help

### ISSUE THREAD

**Issue by purplemer** [bitpay/copay#7514]
I have lost the seed and passcodoe  for my electrum lite wallet. The wallet is an electrum lite and contains just over 0.4 btc.

I have manged to extract the wallat data file from my old phone. I think i need to extract the kdf file from this and get it cracked.

This is above my remit. I like plants and herbs not computers. Can anyone help me with a walk through. Happy to pay with btc if it works

thank you

**Comment by Gamboster** [comment]
What is the wallet data file?

If you have lost your private key, there is nothing we can do to help you.

**Comment by JDonadio** [comment]
Please contact with the electrum support team and ask they for your problem.

**Comment by korison** [comment]
@purplemer 
I can recover your electrum wallet and i recovered electrum wallets for my customers.  if you want need help send me email : anywalletrecovery@gmail.com
