### ISSUE TITLE
I want my bitcoin cash back.

### ISSUE THREAD

**Issue by Computeridiot1** [bitpay/copay#7515]
How could my bitcoin cash be delivered and sent in February 2017 when it wasn't even issued until August 7 2017?

**Comment by dabura667** [comment]
............. because BCH has the same history pre-August as BTC....

That means when you copy a BTC wallet, the history before August will be the same as the BCH wallet.

**Comment by Computeridiot1** [comment]
How can I claim my bitcoin cash?

**Comment by Gamboster** [comment]
Copay/Bitpat Recovery tool: https://bitpay.github.io/copay-recovery/

The recovery tool allows you to recover your btc, bch or btg, from your Copay wallet.
For a common wallet (No multisig) You should fill in the signature and copayer fields with 1.
Select the chain corresponding to what you are trying to recover, for example: If you want to recover your BTG, you must select 'btg / livenet'. Initially you should not change the address gap value.

In the input: "Recovery phrase (mnemonic) or File / Text backup", place your 12 words correctly

Accept the terms and conditions and you can scan your funds.
Once the funds of the corresponding wallet are found, an input will appear, which must be filled in with the address to which you wish to send your funds.

The procedure is simple.

**Comment by PassiveQuest** [comment]
Hello,

The procedure is indeed simple, although for me it remains stuck in infinite loading for hours when I tried from both mobile and PC. The ironic part is that under the loading animation, the 'Found funds:' are actually the correct amount
[MoE Events - Status.xlsx](https://github.com/bitpay/copay/files/1569691/MoE.Events.-.Status.xlsx)
, but the process does not end to redirect me to the next page and if I refresh the page the request is being canceled.
Can I have your feedback on this asap please ?

For more details please consult the attachment.

Best regards,
Passive Quest

**Comment by Gamboster** [comment]
Hello @PassiveQuest. Sorry for the delay. Please if you continue with that problem, then open a new issue and I will help you.

**Comment by Computeridiot1** [comment]
How do I claim my bitcoin gold?

**Comment by Gamboster** [comment]
In the same way that you claimed your BCH
