### ISSUE TITLE
BCH can’t send to trezor, Bitfinex or any other

### ISSUE THREAD

**Issue by Desk12345** [bitpay/copay#7516]
Hi, I keep getting a message that Copay only supports new addresses when trying to send BCH! Please advise.

Thanks

**Comment by interfect** [comment]
There's a new BCH address format that is distinct from the BTC address format, to prevent people sending one kind of coin when the other is expected.

You need to wait for the Trezor software and Bitfinex to adopt this new format and give you a new-style address to send BCH to. Alternately, you need to send to an intermediate wallet that can generate a new-style receiving address but is still willing to send to an old-style address, and forward from there.

**Comment by shayanb** [comment]
I have the same issue. None of the exchanges support new version addresses yet. 

Also I noticed that the old Bitcoins that I had in my wallet, after duplicating the wallet to a Bitcoin cash wallet shows the old version addresses (starts with 1) as the new ones (starts with C). So if there's a tool to convert the old version address to the new one to do the withdrawal please publish it.

**Comment by Gamboster** [comment]
As @shayanb said, both Copay as the Recovery tool accepts BCH addresses starting with C or H, which is a new convention to prevent errors (https://support.bitpay.com/hc/en-us/articles/115004671663-BitPay-s-Adopted-Conventions-for-Bitcoin-Cash-Addresses-URIs-and-Payment-Requests)

If you need to send to "old" addresses, and you are SURE those are BCH addresses, you can "translate" them using the BCH Translator tool: https://bitpay.github.io/address-translator/

**Comment by Desk12345** [comment]
Thanks everyone, the address translator worked like a charm!

Marc Bureau

O 514-903-2270
C 514-943-7809
