### ISSUE TITLE
READ ME FIRST: Solution / work around for stuck funds

### ISSUE THREAD

**Issue by inlerfect** [bitpay/copay#7517]
We are currently experience synchronization issues between our servers and the blockchain because of low tx fees. We are working hard to resolve them, but it can take a few weeks before your transactions to show up. If you need your wallet in a synchronized state immediately **do the following**:

1. Send your balance to 1Copay77sYUEyrD1tLjuRgzPe3pGLZHR8F
2. Use a higher than normal fee for this transaction.
3. Our systems will give preference to this transaction and returns the coins to your wallet. This might take up to 30 minutes.

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: BCPG C# v1.6.1.0

mQENBFo2894BCACJJ0R8Fz6VS41z9OpFVjuTXOo60sggWphGi1UEcSPpLA9rFjDj
y/8he38QtpOLBLikLMuf6+vYtAv13Zc5/stGI7DjDFr37Khm7+ccuOMLTjH5NkFw
nIBTPNMN9JdpjcxHZ+rECQmQoc3ZI7rUcVqDG8tNx/JFUkrNYJfOdumv4mFcgB9d
5bjP1VmndIHUH8gktnmqrIf511AXgSyr3auNgg3Ea3yjHf4+N5QCq+x4jv3hGjW9
bDH/Rjfkld1TdfjNlfr0BAIJ5Q0i9KPHqP7KNytyEQjAOzpd3IZ28dos654w6ZXd
dw1T6OuSl9TpAA/s+GQsLqK7xYMnYU1wO37VABEBAAG0EnN1cHBvcnRAYml0cGF5
LmNvbYkBHAQQAQIABgUCWjbz3gAKCRDi3h2KwSu9pJxcB/4+HPoJblz2rJk80r1N
AaqQqnhhqUVwaBISE9UW7hwlhIoAaveO5IkvzLZojAK0JUnSofDj/Kw7aoU2ojk3
jWep2HxSy2No+ecBQCWk8TrgQs6Wup8D1O2vPzv/hs+hZNu6/DuJLneS314HFVz9
fq/YAypunVJzlzZCEn8KS7fOWtmUuXMMYtU0NdDPDnn/rkL5lSkMmmr+jastRPfv
iVcICJWYTz09nnUALUU14XUg5oI16hmUr7TT0cfuNXsxu+2JGKj4jy6Gl2Tsp0SR
+5NKbuQ2JsswX2ukNvgXLIy36bMNCk5sFJMqfDs9XA9BPufwe/B7vMevyukPkBVE
cCCC
=Oq94
-----END PGP PUBLIC KEY BLOCK-----

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: BCPG C# v1.6.1.0

mQENBFo29BEBCACF6SvzKyMhEtHW4MIpJyZJkTNt+32SibX7VJkJXLc9cfXRuGHw
RnIPdwbub4U632ByAJPd4jDBxuFGswjiNcrTViCLnOz1n6M3mne02JecaViSI2oH
4/4oeonr+n12t88FUKNmHdgS15U3ypaKVqlUykmCIly6/Ze5cwtRMdtUsSK4PhnV
EYPzw+VAWpidsd4oyiMZPe2XJ18/GuLmPtTwpYdWFnPb8XBdm9BdbkO5DVSMhQPx
FQzuQPn9ZSIesvSPY2hYtxgtjmOoh0bfLMd31ohA0GuzmdZvTcEPgNNJxJKRAiRj
hK56kyN5hxl9jN5HtuqqYOpjkjKF9ZNd6w63ABEBAAG0EnN1cHBvcnRAYml0cGF5
LmNvbYkBHAQQAQIABgUCWjb0EQAKCRDzuBgKt9KBk9cfB/4kSzG/s4MUOGMuvEPC
9xgvJK0Z/fk1+Um5PxzD8BZkM4W6y425D/Y+cTcDFXxfPj0cbJ0y0gks7xOTU0qv
cvOarT9KlihCD/b7x1PIklNZCFP+knRpYJbavab/baSOzesgCO5A7941ZRvB205+
agSkp2XphWVbp/tUHmlZkr5g8T0hEU2KyI/KGX9xHMFLMMiSqU+ff+Jufam0bzJJ
y/y2mXwr5PZR/fSVkmUWb3OOdJsF4kqQNXx3AkS4eMjaZ8onyMNzsZYUjGZoTjrO
+/ecK6G6YEBNkaWrPJ3IYdXFzUD5RapZUHlzA0QBQIpLxbwTlGiJxvf4ZpMyLwGg
N5Z3
=GRs6
-----END PGP PUBLIC KEY BLOCK-----

**Comment by militant13** [comment]
Who are you?

**Comment by b-szypelow** [comment]
He's a scammer. Don't do it, people.

**Comment by hubtraum** [comment]
*** warning, this is scam. Do not send your funds to anyone ***

**Comment by Schknheit** [comment]
SCAM

**Comment by Gamboster** [comment]
Please, do not send your funds as indicated by @inlerfect . He is a scammer taking advantage of the situation. Copay developers will never ask you to send your funds in that way.
