### ISSUE TITLE
#7189?!? Why is there a forum if after the problem is explained to developers, NOTHING CHANGES!

### ISSUE THREAD

**Issue by david2254** [bitpay/copay#7519]

**Comment by dabura667** [comment]
#7189 is a number.

**Comment by militant13** [comment]
Bitpay is scamming people I am convinced!! We don’t need businesses like this in our community

**Comment by david2254** [comment]
Yes it is the number of the previous issue opened and unsolved two weeks ago. Thank you for your diligence detective!

**Comment by david2254** [comment]
I agree "militant13" We need to find a more broad way of publicizing this. It's straight BullShit

**Comment by militant13** [comment]
Someone started a thread on reddit

**Comment by militant13** [comment]
https://www.reddit.com/r/Bitcoin/comments/7keqmn/community_we_need_to_upvote_this_post_so_no_one/

**Comment by militant13** [comment]
That’s starting to get traction we got to push that

**Comment by matiu** [comment]
In the original ticket we asked for any information to identify the wallet so we can investigate further. That information was not provided.

**Comment by david2254** [comment]
False I sent three separate emails in regards
