### ISSUE TITLE
Bitpay has a "Custom fee" option but it doesn't warn you that your money can be lost forever.

### ISSUE THREAD

**Issue by pushplayent** [bitpay/copay#7522]
![bitpay](https://user-images.githubusercontent.com/33581979/34123943-07152088-e3e6-11e7-80fa-c286657345d6.jpg)
Please remove this option until it makes sense to a layperson. The custom feature should be removed since it is causing so many issues. When national reporters uncover these major issues, it could do lasting, major harm to Bitpay. I was testing the custom option to see how long it would take. It's been over 18 hours, and I read on your Bitpay that if the network drops it without confirming, my money is gone forever. How can I up the fee for miners to save this transaction?

**Comment by junderw** [comment]
> if the network drops it without confirming, my money is gone forever.

This is not true for money you SEND. But it is true for money you RECEIVE.

**Comment by junderw** [comment]
The money doesn't disappear, it returns to its original owner... so if A sends to B, and the fee is super low and gets dropped, the money returns to A.

**Comment by boxur** [comment]
Yet I paid a decent fee today and my transaction was never broadcasted why is thiz
