### ISSUE TITLE
Transactions to not add up, .002428 BTC missing, no record

### ISSUE THREAD

**Issue by hkutcher** [bitpay/copay#7525]
My Copay wallet should have 0.003 BTC in it, but instead, it tells me there's only 0.000572 BTC there. You do the math: 5 transactions, 2 received, 3 sent. 
+0.032 received
-0.01 sent
-0.01 sent
+0.05 received
-0.059 sent
=0.003
Where is the other 0.002428?!

**Comment by militant13** [comment]
Please file a complaint with https://www.bbb.org/ as they are only ones to take notice with our issues! 2 weeks nothing from bitpay customer service other people months.. people want their money every complaint builds traction!!


BitPay keeps closing my issues with no solution everything is being recorded and I will not stop until the end of this company or people get there money back!! I have tried the input of 12 words into another wallet doesn’t work I tried everything I can do on my end doesn’t work and my BTC isn’t even in the same wallet anymore something is very fishy here!!!!

**Comment by dryazanov** [comment]
@hkutcher maybe 0.002428 are the transaction fees?

**Comment by gabrielbazan7** [comment]
@hkutcher do you check the trasaction fees of that 3 sent transactions ?

**Comment by korison** [comment]
@hkutcher 
I can recover your lost fund if you want need help send me email : anywalletrecovery@gmail.com
