### ISSUE TITLE
Txid

### ISSUE THREAD

**Issue by dubwoofy** [bitpay/copay#7527]
I have transferred around 300 € at 30. November, now the company which should send me the order for it, wants to see the transaction-id. I cant see one at the app, please can you send it to me? My e-mail adress is nass.lahr@web.de

**Comment by Gamboster** [comment]
Hello @dubwoofy  You can go to:
Bitcoin Wallets -> Click in the wallet which you sent funds -> Select the transaction which you want to know the "txid" -> scroll down and click in "View on blockchain" -> Then you could see the transaction id
