### ISSUE TITLE
Only 1 of 2 Multisig Copayers available for trasnaction

### ISSUE THREAD

**Issue by scottystone** [bitpay/copay#7530]
Is it possible to move BTC out of a multisig wallet where only one of two the copayers is competent? The other copayer lost both the Recovery Phrase and Wallet Backup (or never made one) for the Multisig wallet on their lost device.

**Comment by junderw** [comment]
Sorry, unfortunately you need both keys if the wallet is 2 of 2.

If it is 1 of 2 you can send by yourself.
