### ISSUE TITLE
Missing BTC

### ISSUE THREAD

**Issue by vincecross** [bitpay/copay#7531]
I sent a BTC payment with a high fee from copay to an exchange two weeks ago. It's been showing as a pending transaction for the last week. What's the first step to complete the transaction?

**Comment by militant13** [comment]
Please file a complaint with https://www.bbb.org/ as they are only ones to take notice with our issues! 2 weeks nothing from bitpay customer service other people months.. people want their money every complaint builds traction!!


BitPay keeps closing my issues with no solution everything is being recorded and I will not stop until the end of this company or people get there money back!! I have tried the input of 12 words into another wallet doesn’t work I tried everything I can do on my end doesn’t work and my BTC isn’t even in the same wallet anymore something is very fishy here!!!!

**Comment by carlosgfranco** [comment]
Similar to https://github.com/bitpay/copay/issues/7807
