### ISSUE TITLE
Can't buy amazon gift card

### ISSUE THREAD

**Issue by slavap75** [bitpay/copay#7536]
Getting error: No wallets available.
I do have a wallet with positive balance.

Please help.

**Comment by cmgustavo** [comment]
Do you have BTC or BCH wallet? Buying gift card is only available with BTC wallets

**Comment by slavap75** [comment]
I do have BTC wallet with active balance on it.

Thanks,
Slava.

**Comment by Gamboster** [comment]
Could you provide us the wallet id of your BTC wallet with which you want to buy the gift card?

Settings -> Bitcoin Wallets ( Click in your wallet ) -> More options -> Wallet information -> Wallet Id

**Comment by slavap75** [comment]
4fab7b23-b313-436e-a9c7-529b42d52e14

**Comment by JDonadio** [comment]
@slavap75 probably your balance was not loaded properly. Please go to settings > wallet > more opts > transaction history > clear cache. Then try again, if the problem persist please feel free to comment here and I'll reopen the ticket.
