### ISSUE TITLE
Bitcoin cash missing 

### ISSUE THREAD

**Issue by yycc6** [bitpay/copay#7537]
I sent 3 bitcoincash by mistake to a Bitcoin adress in my copay wallet, the 3 bitcoincash are sent with success from my sending account but nothing has arrived to my new wallet! Now those 3 bitcoincash are still missing, no answer from anyone from the platform copay. Please pay attention to their service!

**Comment by love5461** [comment]
shit

**Comment by Gamboster** [comment]
Hello @yycc6. Sorry for the delay.
Check this out: https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-sent-bch-coins-into-a-btc-address-what-can-i-do-to-recover-my-bch-coins

Or also you can create a new BCH wallet, using the backup (the 12 words) from the BTC wallet, and you will have access to the BCH.

Another option: Go to settings -> Bitcoin Cash -> Choose the BTC wallet -> Duplicate for BCH
