### ISSUE TITLE
Can't send BTC

### ISSUE THREAD

**Issue by arangsalimi** [bitpay/copay#7538]
I have 0.005BTC and the issue "the amount is too low to spend" appeared in front of transaction.
but as i got from other issues it is related to transaction fee but my problem is why I can't use my sent icon in bitcoin.com wallet and the page is totally frozen when I write down the recipient address?
I can not enter any amount in my send page?
would you please clarify?

**Comment by militant13** [comment]
Please file a complaint with https://www.bbb.org/ as they are only ones to take notice with our issues! 2 weeks nothing from bitpay customer service other people months.. people want their money every complaint builds traction!!


BitPay keeps closing my issues with no solution everything is being recorded and I will not stop until the end of this company or people get there money back!! I have tried the input of 12 words into another wallet doesn’t work I tried everything I can do on my end doesn’t work and my BTC isn’t even in the same wallet anymore something is very fishy here!!!!

**Comment by Gamboster** [comment]
This is not the support of bitcoin.com
