### ISSUE TITLE
I sent bitcoin to some address that wasn't copied. 

### ISSUE THREAD

**Issue by EricPeterson3** [bitpay/copay#7539]
Where is my bitcoin????

**Comment by Gamboster** [comment]
Could you explain your issue better?

**Comment by EricPeterson3** [comment]
Yes!
I put in an address: 18M9wyy9EAt7mP8zjwHTMVNQWcFkA6A3RR

And tried to send 0.14 bitcoin to it

but instead, this address was used: 1AWAp2is6o1guZeXbWurbTmHVAHQVXsMkD

And I have NO idea where this address came from. I did not input it to 
the Copay system.

Now, my 0.14 Bitcoin is stuck in limbo. What is going on????

**Comment by militant13** [comment]
Please report this business to https://www.bbb.org/

**Comment by Andrewdron** [comment]
У меня такая же проблема!(

**Comment by gabrielbazan7** [comment]
Hi! sorry but if the money was sent to a wrong address there is nothing we can do.
