### ISSUE TITLE
Lost money

### ISSUE THREAD

**Issue by boxur** [bitpay/copay#7542]
I sent money to myself and it was never sent but copay gladly takes their 20$ out of my fee please I'm trying to move my coins out this wallet asap been experiencing problems all week

**Comment by boxur** [comment]
I sent from a copay wallet and was given an error that I transaction was not found

**Comment by militant13** [comment]
First thing first report problem to https://www.bbb.org/
Sad to say there is nothing you can do at the moment people have been having problems for months with no support from copay/bitpay

**Comment by militant13** [comment]
Please file a complaint with https://www.bbb.org/ as they are only ones to take notice with our issues! 2 weeks nothing from bitpay customer service other people months.. people want their money every complaint builds traction!!


BitPay keeps closing my issues with no solution everything is being recorded and I will not stop until the end of this company or people get there money back!! I have tried the input of 12 words into another wallet doesn’t work I tried everything I can do on my end doesn’t work and my BTC isn’t even in the same wallet anymore something is very fishy here!!!!

**Comment by carlosgfranco** [comment]
Similar to https://github.com/bitpay/copay/issues/7807
