### ISSUE TITLE
BITPAY TRAPPED FUNDS NO SOLUTION FROM SUPPORT FOR MONTHS

### ISSUE THREAD

**Issue by militant13** [bitpay/copay#7543]
Please file a complaint with https://www.bbb.org/ as they are only ones to take notice with our issues! 2 weeks nothing from bitpay customer service other people months.. people want their money every complaint builds traction!!

**Comment by gabrielbazan7** [comment]
dup #7508

**Comment by militant13** [comment]
Y you close with no solution just making shit worst for yourselves I promise I will bring down this company

**Comment by militant13** [comment]
People want their money
