### ISSUE TITLE
Bitpay fee scam 

### ISSUE THREAD

**Issue by militant13** [bitpay/copay#7545]
Looked into it with a QR code scanner, it turns out that they write the invoice number into the OP_RETURN of the tx. Greatly increasing the tx fee 10 fold. 

What’s going on here bitpay!!!

**Comment by militant13** [comment]
Let’s see what they say if they say something

**Comment by militant13** [comment]
It’s not just the QR code though. Even when I click to open the wallet. It for some reason adds to OP_RETURN which of course jacks my fees using @LedgerHQ

**Comment by militant13** [comment]
Hello I’m 100% talking about bitpay wallet @dabura667

**Comment by luckykcc17** [comment]
**Did Bitpay ever respond to this question??** Thank you for explaining why the fees are higher at Bitpay then any other wallet I have used.
