### ISSUE TITLE
Amazon gift card failure coins sent no card received

### ISSUE THREAD

**Issue by Ted-Mohamed** [bitpay/copay#7546]
it's clear I'm not the only one having this issue here I'm posting a new one since the other seem to be ignored too. 

I requested an Amazon Gift card it the transaction was successful, but there was no card issued, I contacted BitPay, but they said the can't do anything and I should contact the merchant

**Comment by JDonadio** [comment]
Hi, the criteria to report the amazon gift card issues is following: https://github.com/bitpay/copay/wiki/COPAY---FAQ#amazon-gift-card

**Comment by chitrabaral** [comment]
Being a honest indivisual we need to put this comment everywhere to make this stop scamming people money !!!! Please join google review and spread your aituation thanks
