### ISSUE TITLE
Don't Confirm transaction

### ISSUE THREAD

**Issue by maumolcr** [bitpay/copay#7547]
Hello I have wallet in BitPay, I send to other wallet Satoshis with low fee and no confirmed only pending and say me in the link transaction not fount. You can help me pls

**Comment by carlosgfranco** [comment]
Similar to https://github.com/bitpay/copay/issues/7807
No solution yet

**Comment by maumolcr** [comment]
Is not solution.
I need help with this transaction

**Comment by maumolcr** [comment]
Why is close? I thif me the money
