### ISSUE TITLE
Me olvide la contraseña de pagos.

### ISSUE THREAD

**Issue by LEDEZMA2020** [bitpay/copay#7552]
Buenas tardes equipo de Copay. Me olvide la contraseña de pagos de mi billetera copay quiero recuperarla ya que sin esa contraseña no puedo usar BitCoins.

Desde ya muchas gracias.

**Comment by JDonadio** [comment]
Si no tenes un backup hecho, no vas a poder acceder a tus fondos. Para más info fijate aqui: https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-forgot-my-wallet-spending-password-is-there-a-method-to-reset-it
