### ISSUE TITLE
Issue - Insufficient funds for fee

### ISSUE THREAD

**Issue by syf000** [bitpay/copay#7554]
Dear all,
I have a small amount of bitcoin in my bitpay wallet, about 30$
The issue is that I cannot sell by Conbase, nor transfer out.
Please is there any way out?
Can you please help me?
Thanks in advance

**Comment by Muratist** [comment]
I have same issue? did you solve it?

**Comment by rome4guest** [comment]
Same problem!

**Comment by syf000** [comment]
So what, my friends?

**Comment by gabrielbazan7** [comment]
Hi! Fees calculated by Copay for sending are given to the Bitcoin miners, not Bitpay or anyone related to the Copay project. Currently, bitcoin network congestion is making the fees getting higher and higher. You could check the current average fee for transactions here : https://bitcoinfees.earn.com/.
Also, check the FAQ for more information : https://github.com/bitpay/copay/wiki/COPAY---FAQ#copay-requires-high-fees-for-low-amounts-transactions
