### ISSUE TITLE
Transacción no confirmada hace dias

### ISSUE THREAD

**Issue by juanote81** [bitpay/copay#7558]
Creo otro reporte ya que el anterior solo otros usuarios respondieron, el reporte es el #7502, transferí hace días 170 dólares y coloque un bajo fee, tampoco es el mínimo pero reconozco que fue bajo, quisiera saber si se va a reversar o se procesará en algún momento, cuánto tardaría ya que por la caída del bitcoin, esos 170 se me han convertido en 145 y es molesto perder dinero por retrasos, aparte que no me responde nadie de bitpay/copay

El ID de la transacción es https://blockchain.info/tx/f8d1d4fb024db780d4228ff077592fb692bb77308a4aa91b43d0092c3a6ed4f6

**Comment by cmgustavo** [comment]
BitPay no maneja el tráfico en la red de bitcoin. Tu transacción depende de la red (no de la billetera que utilizaste, sea Copay o cualquier otra), y si el fee es bajo, no se va a confirmar en corto tiempo. Y con respecto a eso, si pasado una semana la transacción no se confirma, los fondos vuelven a estar disponibles (se revierte la transacción).

**Comment by carlosgfranco** [comment]
Similar to https://github.com/bitpay/copay/issues/7807
