### ISSUE TITLE
Can not upload my Bitpay card!!!

### ISSUE THREAD

**Issue by sib44** [bitpay/copay#7559]
Hello 
I want to upload my Bitpay card but I always get this error message:

"Could not create the invoice
'amount' must be a number"

What's going on? Always there is a problem with uploading the card and this makes Bitpay useless.
Thanks

<img width="250" alt="bildschirmfoto 2017-12-20 um 04 11 54" src="https://user-images.githubusercontent.com/32338322/34189495-feba140a-e53b-11e7-870b-43639434f6d8.png">

**Comment by cmgustavo** [comment]
Are you trying with USD or BTC values?
