### ISSUE TITLE
hello. about send

### ISSUE THREAD

**Issue by love5461** [bitpay/copay#7563]
Hi i send some btc  i chose simall fre  now all btc is hold  can you help me

**Comment by love5461** [comment]
<img width="300" alt="_20171221035118" src="https://user-images.githubusercontent.com/21037152/34225693-405ee4be-e602-11e7-9ea6-b69c06038599.png">

<img width="300" alt="_20171221035110" src="https://user-images.githubusercontent.com/21037152/34225688-3ed029a0-e602-11e7-8b15-2ee3756cc3bd.png">
<img width="300" alt="_20171221035128" src="https://user-images.githubusercontent.com/21037152/34225687-3ce83d4e-e602-11e7-9f24-1c5223e1d871.png">

**Comment by gabrielbazan7** [comment]
This could be useful for you https://github.com/bitpay/copay/wiki/COPAY---FAQ 

Re open the issue if you still having issues. Thanks
