### ISSUE TITLE
Bitcoin Cash to Bitcoin Wallet Accidentally 

### ISSUE THREAD

**Issue by kpeereboom** [bitpay/copay#7564]
Update - The transaction is no longer appearing at all. Please tell me there is a way to recover this? I have screen shots and email proof.

Hi there

I have accidentally transferred Bitcoin Cash into my Bitcoin Wallet from the broker and the transaction seems to be hung. I copied the incorrect address when transferring. 

It appears in my Copay account but I don't know how to move it into the correct location.

Could someone kindly advise how I move the Bitcoin Cash stuck in to the BCH Wallet please?

Thank you

**Comment by JDonadio** [comment]
https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-sent-bch-coins-into-a-btc-address-what-can-i-do-to-recover-my-bch-coins
