### ISSUE TITLE
Bitcoin amount issue

### ISSUE THREAD

**Issue by beatume78** [bitpay/copay#7565]
Hello,

I just transfered some bitcoin from my copay wallet to another wallet and somehow, I lost few bitcoin during the transaction.
The amount lost is not linked to the fees

Here is the transaction https://live.blockcypher.com/btc/tx/b9e039eac21bc790170bf7dbb5ef7928cd235b9698ca567e8152722349c66ee8/
The amount of the transaction but the balance of my wallet misses some bitcoins.

Any ideas ?
Thanks

**Comment by gabrielbazan7** [comment]
Each transaction you do, have a transaction fee associated. Fees calculated by Copay for sending are given to the Bitcoin miners, not BitPay or anyone related to the Copay project.
