### ISSUE TITLE
transaction not recevied

### ISSUE THREAD

**Issue by wintergarten** [bitpay/copay#7566]
My transaction isn´t showing up on my copay wallet. I don´t have money on that account anymore and I can´t find any email adress to write to an support. Maybe you can help me.

**Comment by bitcoinchan** [comment]
same here such cunts!!!

**Comment by wintergarten** [comment]
what do you mean?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virenfrei.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-12-24 3:29 GMT+01:00 bitcoinchan <notifications@github.com>:

**Comment by wintergarten** [comment]
can someone admin please write an adresse or else to get my transaction somehow? i need an support please! i want to transfer my money to another wallet!!!
