### ISSUE TITLE
Bitpay card Top Up not showing on app or website

### ISSUE THREAD

**Issue by zachariahthegreat** [bitpay/copay#7573]
Hello,
I sent Bitcoin to my Bitpay debit card using the top-up feature on the website. I used the Exodus desktop wallet to send the BTC. The transaction did not show up on the card at all but I can see the transaction on the Blockchain. What do I need to do to get it on the card?

TX - https://insight.bitpay.com/tx/8497dedb1d3b538af21da03a0450702362ff002205a5b81d27c347b58218f384

**Comment by BGalliotti** [comment]
Hello, sorry for the delay,

We are closing this thread, please if you still need support, open a new one, we will happy to help you.
Thanks.
