### ISSUE TITLE
Transaction Not Found!

### ISSUE THREAD

**Issue by karanmartian** [bitpay/copay#7574]
I made a spend of 0.00044 today @ 28 satoshis/byte. I received an email saying "Payment sent" but when I check this link I get "Transaction Not Found" error:

https://insight.bitpay.com/tx/0e2e4f600be38768007567b702387354182eb126d9c41dac2019a4b1efd70e1d 

Also its not there on blockchain.info either. My wallet shows 0 btc now. I just want to understand if this is a bug with CoPay or is this a pervasive problem when spend is made with low fee. And how does one exactly track such lost transactions. Does the btc come back to your wallet?

**Comment by iv4n0ff** [comment]
I have exactly the same problem https://insight.bitpay.com/tx/01e31a11649f99ffeea6b1ec908a198470bad51cd2d4a35945d60e0caf81b909

**Comment by Concvest** [comment]
The same shit guys, what shold I do to resolve it?

**Comment by karanmartian** [comment]
well i got back my coins in about 36 hours i believe. the solution would be to deposit and transfer larger funds in and out of your copay

**Comment by karanmartian** [comment]
and ofcourse pay a larger fee at least select Normal fee
