### ISSUE TITLE
Send a payment from December 19 at 930 am from copay to poloniex and no verification has arrived or come

### ISSUE THREAD

**Issue by latiendae** [bitpay/copay#7580]
Good afternoon, more than 24 hours ago send a copay to poloniex payment and it still does not arrive. neither does the transaction hash, and it does not return my resources. what should I do?

my copay address is: 1L6hfssm6YK2tSQ5iuxdbWCuh2boKT8Kvj

![envio poloniex](https://user-images.githubusercontent.com/34725733/34232959-d08c57da-e5b0-11e7-9c1d-d235b64ed1f4.png)

**Comment by leweissy97** [comment]
Same as me im waiting until now the payment is not yet confirmet and the transaction is not found on the insight

**Comment by leweissy97** [comment]
Please my friend notify me if they fix your issue

**Comment by latiendae** [comment]
Ok, perfect

**Comment by xereaz** [comment]
Seems like quite a few of us are having same issue sent .4 earlier today its holding 1.6 and cant find my transaction luckily saved the transaction id? I can see it on the blockchain but not the additional 1.2 it is holding!!!! WTF will notify if i hear anything as well

**Comment by latiendae** [comment]
Realice otra transacción y tampoco ha sucedido nada, de mi billetera aparece que salio y ya no aparece la transacción, a la billetera que envié, sale que esta en proceso y carga y desaparece el valor, pero cuando se mira la transacción, dice que no la encuentra, como nos pueden ayudar amigos de copay, teniendo en cuenta que los fees que cobran se están pagando, no es un servicio gratuito.

Adjunto pdf, con las dos transacciones
[Imagenes Copay transacciones que no ha confirmado.pdf](https://github.com/bitpay/copay/files/1580483/Imagenes.Copay.transacciones.que.no.ha.confirmado.pdf)

**Comment by carlosgfranco** [comment]
Similar to https://github.com/bitpay/copay/issues/7807
