### ISSUE TITLE
I bought some BCH and provided my Copay BTC wallet address in error...

### ISSUE THREAD

**Issue by edintheclouds** [bitpay/copay#7582]
Rookie mistake - first time I've used Copay and I supplied my BTC wallet address rather than my BCH wallet address .  Both are in the same Copay account.  The seller completed the transaction, so is there some way I can use some transfer/import/export process to move the funds into the right wallet or do I just have to wave goodbye to them?

TIA for any help anyone can provide.

**Comment by bitjson** [comment]
You can go to `Settings` -> `Bitcoin Cash` to scan BTC wallets for Bitcoin Cash. It takes a few minutes to scan for funds after you've duplicated the wallet, so you may need to wait a little while before the funds appear.
