### ISSUE TITLE
Duplication of participants in setup of shared Bitcoin Cash wallet

### ISSUE THREAD

**Issue by Jiminnk** [bitpay/copay#7585]
I am trying to setup a shared Bitcoin Cash wallet 2-of-4 with myself as 2 of the copayers and my daughters as the other two.  This would allow me to operate independently while I am alive and kicking, and allow my daughters to easily take control on my demise.  I have done the initial "create shared wallet" process on my smartphone and emailed the invitation. I have then tried to add myself as a copayer via a different smartphone using the "join shared wallet" option.  The initial create process works fine but when I confirm the join process on the second smartphone I get an error message "Wallet already in Copay". 
The original wallet has been updated  with ME as one copayer and the new participant is listed twice???
The second wallet that was used to join the already created wallet also lists 3 copayers, the original wallet users name, Me, and the second wallet users name.
Any ideas as to what's happening.  Thanks.

**Comment by gabrielbazan7** [comment]
HI ! sorry for the delay. Do you still having problems with the setup ? 
It working fine for me.
Re open the ticket if you still having problem.
