### ISSUE TITLE
I met this problem.

### ISSUE THREAD

**Issue by fjdkwangaa** [bitpay/copay#7586]
![tim 20171221181111](https://user-images.githubusercontent.com/10125068/34251378-dd5a5622-e67a-11e7-89b5-98c0b6b65d3b.png)

I met this problem when i am recovering wallet on a different device. It is strange that some of my wallets can be recovered but some cannot. Anyone know this issue.

**Comment by gabrielbazan7** [comment]
Did you check that all that things are correct when you import the wallet ? Re open the ticket if you still having issues. Thanks

**Comment by korison** [comment]
@fjdkwangaa 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
