### ISSUE TITLE
Transaction not found

### ISSUE THREAD

**Issue by prodriguez41188** [bitpay/copay#7589]
Hi, I've done a transfer to bitfinex 48 hs hours ago and it's still sending with no confirmation. When i try to see the transaction in the insight i get the messagge "transaction not found".
the hash of transaction is 3f1cd0df8ffe76889de61c78cc1660494ac6cf118d593d1e3c393ea6daad0221. Could you help me? Tks

**Comment by mattpmcqueen** [comment]
I am currently in this same situation! What's going on?

**Comment by carlosgfranco** [comment]
Similar to https://github.com/bitpay/copay/issues/7807
