### ISSUE TITLE
Copay is a SCAM

### ISSUE THREAD

**Issue by iv4n0ff** [bitpay/copay#7591]
Lost 700 US$ in fees and lost transactions for a balance of 1500 $. I DONT RECOMMEND IT

**Comment by chitrabaral** [comment]
This the similar issue with me as well

**Comment by JDonadio** [comment]
Please check: #7546 (comment)

**Comment by korison** [comment]
@iv4n0ff 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
