### ISSUE TITLE
Fees are ridiculous 

### ISSUE THREAD

**Issue by chitrabaral** [bitpay/copay#7598]
Copay is a Big scam and Copay is looting  people through unrecordable fees( because they dont have any set fees or % set at all ... I sweeped BTC 0.04051222 from my paper wallet and the fees charged was $58.00 ... this is F...king a joke or what ? Another joke was fees for transferring the BTC in between the Copay account also charge 3% fee ... I have lost almost $168.00 to tranfer my BTC to Copay and out .... this is really a ripping off the customer ,... I will review this company to everywhere in media so I can save other peoples money !!!!

**Comment by Cr250cra1** [comment]
I put $160 dollars in the machine. I  got 134 to copay wallet and copay says the amount is too low to spend. I read the wiki and it's saying the transaction fee will be higher than the ammount... I've never had this problem until now.. How can the fee be that high?
