### ISSUE TITLE
Transaction issues

### ISSUE THREAD

**Issue by Dave02951** [bitpay/copay#7600]
Hey guys i used Changelly to change some BCH into BTC. I received the amount today but it hasn't been confirmed yet.
There is a message below which says the sender didnt used enough transaction cost for it to be confirmed.

Is this a issue that Changelly caused and if so how can it be fixed?
Or should i just be patient(it took 1 full day already)

Thanks

**Comment by casiodad** [comment]
Also...What's up with the new address molarchy for sending the airdropped BCH to my other wallet?

**Comment by Gamboster** [comment]
If the exchange uses a very low fee, it will be something that you must report to them. 
On the other hand, when sending a tx with low fee, you should wait for it to be confirmed. It can even take weeks
