### ISSUE TITLE
Funds gone and transaction hanging somewhere for ages

### ISSUE THREAD

**Issue by 23mystiq** [bitpay/copay#7602]
I Sent 0.1445 btc from Copay on 12th Dec 2017. To this day the fee is still confirming (I set up low custom fee). Because Copay didn't seem to do anything and it was showing me the funds are still accesible to be operated with I have tried to send it again this time with calculated super saver fees (haha so high fees!). Nothing happened again after many days of waiting I tried to do it again today. Now the funds are gone from my wallet and I don't see my transaction anywhere on Insight. What is going on? Did I just lost thousands of $$ because your app is not working properly? Please solve this issue as I need to access and transfer my funds out of Copay. Thank you. The wallet address: 1LmL5iR8LcSXvcXEp1jcc7YocCrBXZL4M

**Comment by mgraves9803** [comment]
Try this: https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0ahUKEwjw_YHjoZzYAhUY4WMKHSvVBpwQFggxMAE&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dycq7O48aPvQ&usg=AOvVaw2MpS02LcovUO0o8yaK993z

**Comment by 23mystiq** [comment]
Solved. Thank you.

**Comment by mgraves9803** [comment]
*|MC:SUBJECT|*    

 		  [1] 

	Dear 23mystiq, 

	maxg@kmail.org is only allowed to receive email from approved
senders. This means that your email to maxg@kmail.org will be delayed
until the parent of this child reviews and approves the message. There
is no guarantee that your message will be delivered to its intended
recipient. SUBJECT: Re: [bitpay/copay] Funds gone and transaction
hanging somewhere for ages (#7602)
 STATUS: Delayed / In Parent's Mail Queue

	This approval process is due to a safety setting being set by this
child's parent. The parent is using KidsEmail.org to protect his/her
family. 

	Protect your family with KidsEmail.org! 

 		  [2] 

 		  [3] 

 		  [4] 

 		  [5] 

 		  [6] 

This message was intended for
reply@reply.github.com.
If you do not wish to receive _ANY_ emails from KidsEmail.org in the
future, please follow the link below to unsubscribe.
http://www.kidsemail.org/unsubscribe.php?SM_USER=reply@reply.github.com&DE_USER=cde176b53ed8056440f08be0fc3e404bfb2b445c

Links:
------
[1] https://www.kidsemail.org
[2] https://twitter.com/KidsEmail
[3] https://www.instagram.com/kidsemail/
[4] https://www.facebook.com/KidsEmail.org
[5] https://www.pinterest.com/kidsemail1/
[6] https://www.kidsemail.org
