### ISSUE TITLE
PAPER WALLET SWEEP 

### ISSUE THREAD

**Issue by BLAGZ84** [bitpay/copay#7604]
I swept my bitcoin paper wallet into my Copay walet on the 21/12/17 at about 11pm AWST. It has now been about 12hrs and my funds have still not been confirmed.
It still says RECEIVING. 
It also says that due to the low fees set by the sender, the transaction might take a long time or be dropped altogether..

How long will it take??

Insight now says transaction not found

My Copay wallet ID is;
7afafe00-bf39-4f6d-a434-2a5ff21945b5

The wallet address with a balance showing is;
1MQTi4VyWoSdnKFU4Ch5ptnH4BGEPfVKJ3

but it is not confirmed and therefore available.

Please advise asap.

I need help.

**Comment by Gamboster** [comment]
Hello.
Please, if the problem persists, open a new ticket and we will give you support. Sorry for the delay. Regards.

**Comment by BLAGZ84** [comment]
Mate it's taken you like 4 months to reply.  You guys really are shit at
customer service.

Yours truly..
