### ISSUE TITLE
Missing funds

### ISSUE THREAD

**Issue by Doublef1000** [bitpay/copay#7606]
Hello a couple of weeks ago i sent 1776 tethers to my copay wallet and only received 10 usd please help me

**Comment by erikbritto** [comment]
Please send me a message. I can guide you with some instructions.
My email eriksilva@aim.com

**Comment by BGalliotti** [comment]
Hello,
We are closing this thread, please if you still need support, open a new one.
Thanks.

**Comment by Doublef1000** [comment]
my question is, is there a way you can re mine the block to unlock the funds I have lost to do so I will provide you with all available information like the hash number the wallet address the date etc

________________________________
De : BGalliotti <notifications@github.com>
Envoyé : 20 avril 2018 12:03:01
À : bitpay/copay
Cc : Doublef1000; Author
Objet : Re: [bitpay/copay] Missing funds (#7606)


Closed #7606<https://github.com/bitpay/copay/issues/7606>.

**Comment by Doublef1000** [comment]
Is there a way to retrieve the missing funds because i can prove i sent 1800 usd in tethers and only retrieved 0.10 usd

**Comment by BGalliotti** [comment]
Hello, unfortunately there is no way to recover those funds other than recovering the wallet with the backup (12-word phrase, file,..)

What you raise in this comment 

> my question is, is there a way you can re mine the block to unlock the funds I have lost to do so I will provide you with all available information like the hash number the wallet address the date etc
> 
(re mining a block) would need to at least own 51% of the nodes of the bitcoin network to begin.. Practically impossible, this is not affordable neither it is worth it. 

Thanks for your contribution.

**Comment by BGalliotti** [comment]
>

**Comment by korison** [comment]
@Doublef1000 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
