### ISSUE TITLE
I haven't receive my Bitcoinn

### ISSUE THREAD

**Issue by Tamako820** [bitpay/copay#7608]
I sent 0.6 bitcoin from copay to 1EJEUoQnGkvK1Z5vSZjHGwebUbbMzrhfdc
on 18th Dec.
But I haven't receive 0.6 bit.
![s__31531134](https://user-images.githubusercontent.com/34764872/34289996-7e0467f8-e738-11e7-8160-2f120f89f953.jpg)

**Comment by erikbritto** [comment]
Please send me a message. I can guide you with some instructions.
My email eriksilva@aim.com

**Comment by BGalliotti** [comment]
Hello,
We are closing this thread, please if you still need support, open a new one.
Thanks.
