### ISSUE TITLE
Missing BCH

### ISSUE THREAD

**Issue by ycarogabriel** [bitpay/copay#7611]
I would like to check the reason that my Bitcoin wallet alerted me about a bitcoin cash wallet with more or less 5 BCH and when I clicked to redeem it accused 0 BCH and disappeared that option.

**Comment by johnjaves** [comment]
The addresses of BACH appear to me as not valid to make deposits, I hope they can help me

**Comment by ycarogabriel** [comment]
Now It shows. But just 0.28 BCH. What do I do?

**Comment by korison** [comment]
@ycarogabriel 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
