### ISSUE TITLE
Funds gone and transaction not confirmed

### ISSUE THREAD

**Issue by alexsventures** [bitpay/copay#7612]
Hi, I have a seems to be common issue - I made a transaction on December 20th, selected a bit lower than recommended fee, and the transaction got stuck - funds gone, but not confirmed. Also it disappeared from transaction history, being replaced by another transaction (with a much lower amount), that has the constant status "made 4 hours ago". Please advise on the right steps to recover the funds.

Regards,

Alex

**Comment by bitcoinchan** [comment]
same here and i dont know what to do

**Comment by Andrewdron** [comment]
У меня такая же проблема, только с большей суммой

**Comment by karlbalagtey** [comment]
Same here! It disappeared on my transaction history!

**Comment by BGalliotti** [comment]
Hello,
We are closing this thread, please if you still need support, open a new one.
Thanks.

**Comment by korison** [comment]
@karlbalagtey 
@alexsventures 
@bitcoinchan 
@Andrewdron 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
