### ISSUE TITLE
I Send BCH from my copay wallet and i never recieved the payment

### ISSUE THREAD

**Issue by panos1223** [bitpay/copay#7613]
I Send BCH from my copay wallet and i never recieved the payment , although i could see that my payment is Completed!
What should i do guys?

**Comment by panos1223** [comment]
Please if somebody can help me !

**Comment by Roddy1219** [comment]
what?

**Comment by gabrielbazan7** [comment]
Hi! you still having this issue ?

**Comment by panos1223** [comment]
Yes , i haven't receive anything yet to my wallet!!

**Comment by gabrielbazan7** [comment]
Send me the transaction id.

**Comment by panos1223** [comment]
Should i send you the email?
To see it in the blockchain ?

**Comment by gabrielbazan7** [comment]
Where do you see that the payment is completed ?

**Comment by panos1223** [comment]
I really appreciate your Help , please let me know if you Understand What
Happened !!

**Comment by panos1223** [comment]
Did you Notice anythhing wrong?

**Comment by BGalliotti** [comment]
We are closing this thread, please if you still need support, open a new one.
Thanks.
