### ISSUE TITLE
Cannot find the Transaction in blockchain

### ISSUE THREAD

**Issue by Adrin5887** [bitpay/copay#7614]
I have made a transaction from my Copay wallet - in the wallet it says unconfirmed, however when I try to track it in the blockchain it says transaction cannot be found. below is the transaction id.
e2a3fd6a0154b45eda0ad6ccfa26297062d52459f98efa9c67bd0784405db391

not sure what should I do in this case.

**Comment by Falci** [comment]
https://blockchain.info/tx/e2a3fd6a0154b45eda0ad6ccfa26297062d52459f98efa9c67bd0784405db391
