### ISSUE TITLE
I buy an amazon gift card but lost my cellphone and in can not redeem 

### ISSUE THREAD

**Issue by jcplazas** [bitpay/copay#7615]
Hi,  I lost  my cellphone and i have a newone, i recover my copay wallet with my backup

My last transaction was buy a amazon gift card, but i do not redeem the card in amazon 

Now when i see in my copay wallet i can not see the amazon gift card number again

**Comment by Gamboster** [comment]
Hello @jcplazas, Please read this link: https://github.com/bitpay/copay/wiki/COPAY---FAQ#amazon-gift-card

**Comment by BGalliotti** [comment]
Hello,
We are closing this thread, please if you still need support, open a new one, we will happy to help you.
Thanks.
