### ISSUE TITLE
closing account and sell all low bitcoin

### ISSUE THREAD

**Issue by yysiew** [bitpay/copay#7616]
Hi, can someone help to solve my problem? My bitcoin is very low to send and not enough bitcoin for the exchange charges fees, and I have stop mining bitcoin, how I sell all the bitcoin before I close account. Please help!!!

Thank you.

**Comment by erikbritto** [comment]
Please send me a message. I can guide you with some instructions.
My email eriksilva@aim.com

**Comment by BGalliotti** [comment]
Hello, sorry for the delay,
We are closing this thread, please if you still need support, open a new one, we will bappy to help you.
Thanks.
