### ISSUE TITLE
Insufficient funds for fee???!!??

### ISSUE THREAD

**Issue by Cr250cra1** [bitpay/copay#7619]
I'm sending 131usd..How much is the fee to send btc? Why are you holding our btc hostage ?

**Comment by rome4guest** [comment]
Hello I have the same issue 'insufficient funds for fee' for 100 usd. Please explain us...

**Comment by Muratist** [comment]
I have same problem. its bullshit... How can we get back coins I don't know.

**Comment by Cr250cra1** [comment]
This is either a scam or a technical error . There's no other explanation.

**Comment by krasota1** [comment]
Ребята, давайте решим с выводом монет.  если вы хотите принимайте участие с нами и остальными программистами в улучшении транзакций. Желающие пишите vitalikorlov.iwowwe@gmail.com 
Я хочу использовать свои монеты. 
Guys, let's decide with the withdrawal of coins. if you want to participate with us and the rest of the programmers in improving the transactions. Those wishing to write vitalikorlov.iwowwe@gmail.com
I want to use my coins. I wanted to withdraw and 1000 and more you do not give to withdraw. give us an answer. or leave the market in the hole of the scum.

**Comment by cholito1** [comment]
Report this to the BBB many people have. Its the only way to make these guy do whats right. Takes just a few minutes.

**Comment by Cr250cra1** [comment]
I have not reported yet but if they dont release my money I will.

**Comment by cholito1** [comment]
For sure bro. I have received mine after 4 weeks. They just say that its not them its the blockchain and they have no control. Use electrum instead to deposit to your Coinbase. They tell me my fee is to low. So I sent them a snapshot of my payments thru electrum of around .015btc  with about a 7 dollar fee.  This was around 3 weeks ago. And another snap 2 minutes later showing 1 confirmation. They never responded back to that. So I reported to bbb. With proof. They have been   contacted by the BBB already.  Don’t threaten them with bbb. Just do it and watch your credit be their in a few days if not less. Best of luck bro

**Comment by krasota1** [comment]
Hello! can the address of the site be BBB? Thank you . I tried different transactions and btc is also not output.
--
Отправлено из Mail.Ru для Android понедельник, 25 декабря 2017г., 21:07 +03:00 от cholito1  notifications@github.com :

>For sure bro. I have received mine after 4 weeks. They just say that its not them its the blockchain and they have no control. Use electrum instead to deposit to your Coinbase. They tell me my fee is to low. So I sent them a snapshot of my payments thru electrum of around .015btc  with about a 7 dollar fee.  This was around 3 weeks ago. And another snap 2 minutes later showing 1 confirmation. They never responded back to that. So I reported to bbb. With proof. They have been   contacted by the BBB already.  Don’t threaten them with bbb. Just do it and watch your credit be their in a few days if not less. Best of luck bro
>

**Comment by cholito1** [comment]
BBB stands for 
Better Business Bureau

**Comment by krasota1** [comment]
Thanks. 
--
Отправлено из Mail.Ru для Android понедельник, 25 декабря 2017г., 15:38 +03:00 от cholito1  notifications@github.com :

**Comment by krasota1** [comment]
Thank you very much 
--
Отправлено из Mail.Ru для Android вторник, 26 декабря 2017г., 02:22 +03:00 от cholito1  notifications@github.com :

>
>BBB stands for 
>Better Business Bureau
>

**Comment by gabrielbazan7** [comment]
Hi!  Fees calculated by Copay for sending are given to the Bitcoin miners, not Bitpay or anyone related to the Copay project. Currently, bitcoin network congestion is making the fees higher. You could check it here : https://bitcoinfees.earn.com/. 
Also, check the FAQ for more information : https://github.com/bitpay/copay/wiki/COPAY---FAQ#copay-requires-high-fees-for-low-amounts-transactions

**Comment by Cr250cra1** [comment]
130$ is not a low transaction. Why did you close this ticket? The calculation for fees does not follow suit or make sense. There's plenty of people being fucked around by Copay with this same method and this is the support you give?  Worthless

**Comment by krasota1** [comment]
let's prielem in the office butpay-copay and will talk with them about the compensation and service of the service. they do not respond to emails. we invite to co-operation of single-minded people in the creation of the system of public utilities and wallets. Now we are developing a reliable system with a friend. all the best .
--
Отправлено из Mail.Ru для Android вторник, 26 декабря 2017г., 17:35 +03:00 от Cr250cra1  notifications@github.com :

**Comment by krasota1** [comment]
let's come to the butpay-copay office and talk to them about the compensation and the work of the service. they do not respond to emails. we invite co-thinkers to cooperate in the creation of a payment system and wallets. Now we are developing a reliable system with a friend. all the best .
--
Отправлено из Mail.Ru для Android вторник, 26 декабря 2017г., 17:35 +03:00 от Cr250cra1  notifications@github.com :

**Comment by matiu** [comment]
@Cr250cra1 it depends on how big is the transaction. It is impossible to know only with the amount. if you have multiple inputs, the transactions get bigger, therefore a bigger amount is needed to pay the fee.
