### ISSUE TITLE
Funds Missing from Copay Wallet

### ISSUE THREAD

**Issue by SA124** [bitpay/copay#7620]
Hello,

I logged into my Copay account today and was shocked to see my wallet was completely empty. I did  not create a transaction, nor did I receive a notification that funds were pulled from my account two days ago.

Please advise on next steps or if there's anything I can do to retrieve these funds.

Thank you,

**Comment by mr10008** [comment]
Try to trace the transaction. Click on Settings > the wallet that had the funds > More Options > Transaction History > Export File 
The file will be csv that you can open in Excel. Find the Destination address for the amount that is missing and check on https://blockchain.info/ where it's gone

**Comment by SA124** [comment]
Thank you for your help :) 

When I try the route you suggest, after clicking "Transaction History" there's no link or indication of being able to export a file. 

I also tried to pinpoint where it went by searching a transaction number in insight.io but it doesn't provide any leading information.

**Comment by mr10008** [comment]
You are using the mobile version, right? I just checked on android version there is no option to export the file - you are right. So install the latest PC version from here: https://github.com/bitpay/copay/releases/latest 
Make sure that when you install it you RESTORE the wallet using the same seed as for your mobile version.

**Comment by BGalliotti** [comment]
Hello, sorry for the delay,
We are closing this thread, please if you still need support, open a new one.
Thanks.
