### ISSUE TITLE
Funds not transferred 

### ISSUE THREAD

**Issue by golddudu** [bitpay/copay#7622]
I sent

**Comment by golddudu** [comment]
I sent 16 mBTC from my blockchain.info wallet to my copay wallet, transaction marked complete in blockchain but i see no mention of that in my copay wallet. Can you please assist or point me at some help ?

**Comment by mr10008** [comment]
Try to trace it here: https://blockchain.info by searching the receiving address

**Comment by golddudu** [comment]
It was delivered after 48 hours
