### ISSUE TITLE
When you lose your spending password

### ISSUE THREAD

**Issue by sebastiaanvaz** [bitpay/copay#7623]
Is it still possible to backup your wallet and spend the BTC anyway? Also, how to set the back up password? I want my backups to be password protected. Thank you so much such a great community here.

**Comment by sebastiaanvaz** [comment]
With backup your wallet I meant to recover from a backup and then spend the funds, effectively making the spending password useless if one has your backup phrases.

**Comment by fmonts** [comment]
You don't need a spending password if you have the private key/backup password, so your backup password is also a "spending password"

**Comment by gabrielbazan7** [comment]
Check https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-forgot-my-wallet-spending-password-is-there-a-method-to-reset-it and https://github.com/bitpay/copay/wiki/COPAY---FAQ#what-the-spending-password-does. 

You could add an aditional password to secure your 12 words. But you could set it at creation time only in advanced options.
