### ISSUE TITLE
Payment Bitcoin on 20th December 2017 have yet receive

### ISSUE THREAD

**Issue by NOOREZWAN** [bitpay/copay#7624]
I made a transferred 0.038206 Btc from WIREX on 20th December 2017, 01:51 and got a confirmation about Btc received by email from walletservice@bitcore.io on 20th December 2017, 02:02. But untill now, I still not received the 0.038206 Btc in my wallet Copay. Please solve it as soon as possible.

**Comment by Roddy1219** [comment]
You have btc transaction id?

**Comment by NOOREZWAN** [comment]
Luckily after 1 day I issuing this matter, the transaction was succesfull.. but still not showing the transaction history.. but the amout received already..

**Comment by gabrielbazan7** [comment]
Try going to settings -> choose the wallet -> more options -> Wallet Addresses -> Scan addresses for funds. Or go back and try on transaction History option -> clear cache. Tell me if the problem persist. Thanks
