### ISSUE TITLE
Error at confirm: Error getting SendMax information

### ISSUE THREAD

**Issue by krasznahorkai** [bitpay/copay#7627]
Hello,

When attempting to send the max amount from one wallet to another, I am now receiving the error in the title of this post:

Error at confirm
Error getting SendMax information

Note: this is on iOS

Is this a known bug at this point?

Thank you.

**Comment by ThoHah** [comment]
I have the issue too

**Comment by gabrielbazan7** [comment]
You still having this issue ?

**Comment by krasznahorkai** [comment]
This appears to be fixed - thank you!
