### ISSUE TITLE
ERROR 403 

### ISSUE THREAD

**Issue by Ianongkianping** [bitpay/copay#7629]
Received error 403 could not update my wallet. Even with my 12 word phase i could not import it too. Any ideas on how to tackle this issue? Thank you in advance.

**Comment by gabrielbazan7** [comment]
You still having this issue ?

**Comment by Holiyo4** [comment]
I'm having same Issue right now.

**Comment by BGalliotti** [comment]
Hello @Holiyo4 
Thanks for reaching out to us.

This thread is closed. Please refer to #9070 regarding this issue.

Kind regards.

**Comment by Holiyo4** [comment]
Okay
