### ISSUE TITLE
solicitud de reembolso de dineros

### ISSUE THREAD

**Issue by mercabuc** [bitpay/copay#7630]
buenos dias solicito reembolso de dineros fueron enviados desde mi billetera y no reflejo el pago muchas gracias

jurisdiaz@gmail.com
![solicitud de devolucion de fondos copay](https://user-images.githubusercontent.com/34496247/34327514-c23f16f4-e894-11e7-87eb-5c849c1f9144.png)

**Comment by gabrielbazan7** [comment]
No existe tal cosa como reembolso. Las transacciones bitcoin son irreversibles. Tenes que esperar a que se confirme.
