### ISSUE TITLE
BCH ADDRESS ARE NOT VALID, DEPOSITS ARE NOT ACCEPTED

### ISSUE THREAD

**Issue by johnjaves** [bitpay/copay#7631]
I can not make deposits to the BCH addresses, it sends message that the address is not valid in the network to receive deposits, help please

**Comment by Roddy1219** [comment]
please use   tools  to get  BCH  address  https://bitpay.github.io/address-translator/

**Comment by gabrielbazan7** [comment]
https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-cant-send-bch
