### ISSUE TITLE
Ошибка в транзакции, потеря биткоинов

### ISSUE THREAD

**Issue by Andrewdron** [bitpay/copay#7632]
Вчера, 23 декабря, я переводил 0,018 биткоинов с кошелька copау по адресу: 1JBDYfxtJ2UuArLb98GiS3wAc27iHEtCU8. После того, как я произвёл перевод, вылезла табличка со словами ..ошибка.. Я эту табличку закрыл. Далее, я обнаружил, что ушли всё биткоины с кошелька, на другой адрес: 18ZhRkja3kwb2J2hffDFJbe46YqbF8Azuf. Я очень расстроен и прошу вашей помощи.
![screenshot_20171224-225829_01](https://user-images.githubusercontent.com/34818587/34329199-5622ddca-e907-11e7-9644-d3adccc5cfdd.jpg)
![screenshot_20171224-214137_01](https://user-images.githubusercontent.com/34818587/34329200-56480230-e907-11e7-8c58-1ca9398cc2e1.jpg)
![screenshot_20171224-214656_01](https://user-images.githubusercontent.com/34818587/34329201-566aa2c2-e907-11e7-82ae-19e04036c850.jpg)

**Comment by gabrielbazan7** [comment]
Hi. Sorry we only give support in English and Spanish.
