### ISSUE TITLE
Sending funds stuck

### ISSUE THREAD

**Issue by Kvis-Dev** [bitpay/copay#7633]
I sent money 4 days ago, but set very low fee (my bad, I know)
According to bitcoin.com/faq #27  
> If a transaction fails to confirm after 72 hours, the funds will be sent back to the original sender’s wallet.
But every time I open an app, I see this:
"sending, a few seconds ago". How can I return the transfer, so I can send it one more time with higher fee?

**Comment by gabrielbazan7** [comment]
You have to wait for your transaction to be confirmed or dropped.
