### ISSUE TITLE
BitPay 3.9.1 saves and autofills passwords on on Mac

### ISSUE THREAD

**Issue by yunesj** [bitpay/copay#7635]
You can probably imagine that people don't want their wallet passcodes being saved to disk.

![bitpay store, autofill password](https://user-images.githubusercontent.com/152988/34329879-25add67c-e8c6-11e7-8716-67773222bf4f.png)

Purging `~/Library/Application\ Support/bitpay/Default/Login\ Data` sqldb and `Login Data-journal`, and linking them to `/dev/null`, seemed to work as a workaround, but caveat bitcoiner.

May be related to https://github.com/bitpay/copay/issues/5611

**Comment by gabrielbazan7** [comment]
Fixed in version 4. Please, reopen the ticket if you still seeing this issue.
