### ISSUE TITLE
Stuck at sed bower install

### ISSUE THREAD

**Issue by samuelg78** [bitpay/copay#7637]
I am using node 9.3 and stuck at sed bower install. I had installed node_modules/asn1.js-rfc5280/index.js and checked is valid. Someone please help me out. Thank.

> copay@3.10.1 postinstall D:\github\copay
> sed -i -e "s/.*require(...\/...);//g" node_modules/asn1.js-rfc5280/index.js; bower install

sed: can't read node_modules/asn1.js-rfc5280/index.js;: No such file or directory
sed: can't read bower: No such file or directory
sed: can't read install: No such file or directory

**Comment by gabrielbazan7** [comment]
It's working for me on node `v6.10.3` and npm `v3.10.10`. Try with that versions, and remember to run `npm run clean-all && npm run apply:copay && npm run start`

**Comment by casquejo** [comment]
Using node v6.10.3 and npm v3.10.10 but still arriving at the exact same issue.

**Comment by samuelg78** [comment]
After downgrading ro v6.10.3...... encountered this error now.

npm ERR! bitauth@0.2.1 postinstall: `npm run make-dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bitauth@0.2.1 postinstall script 'npm run make-dist'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bitauth package,
npm ERR! not with npm itself.

**Comment by samuelg78** [comment]
Still stuck with the same error.

**Comment by gabrielbazan7** [comment]
Is working for me. I will re open the issue, let's see if someone know what could be wrong.

**Comment by samuelg78** [comment]
@casquejo Hi, have you managed to resolve the issue?

**Comment by casquejo** [comment]
@samuelg78 No, the error still shows up the same way as in your OP even after downgrading my Node and npm versions.

**Comment by samuelg78** [comment]
It worked on my MAC but not on windows. My MAC executed the sed command successfully though.

**Comment by skazhikadyadya** [comment]
Any solution for Windows?

**Comment by BGalliotti** [comment]
Hello,
**Are you still experiencing this issue?**
We look forward to hearing from you.
Regards

**Comment by BGalliotti** [comment]
Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will happy to help you.
Thanks for your contribution.
