### ISSUE TITLE
Funds never arrived

### ISSUE THREAD

**Issue by hokusai1** [bitpay/copay#7638]
Sent a payment from my copay wallet on Thursday to a BTC address. Transaction was sent with a low fee so was expecting it to take a while. My copay wallet is saying that the BTC was finally sent last night. However, it is nowhere to be seen in the wallet it was sent to. It was definitely the correct address as it was showing an impending deposit the whole time. Any help or have copay just scammed me?

**Comment by gabrielbazan7** [comment]
Try this on your recipient wallet: go to settings -> choose the wallet -> more options -> Wallet Addresses -> Scan addresses for funds. Or go back and try on transaction History option -> clear cache. Tell me if the problem persist. Thanks

**Comment by hokusai1** [comment]
Tried both of these options and unfortunately nothing has changed. My copay wallet says it has sent but the coins have not been received in the other account.

**Comment by gabrielbazan7** [comment]
Send me the transaction id

**Comment by hokusai1** [comment]
26a9efc1d38007cbc5f82b83c47bc37e2e9860c32db82c695736fb973ba50cfb
A few hours before the end transaction confirmed, the funds were returned to my copay wallet so I thought the transaction was dropped due to the low fee. But the next day I checked again and it shows as sent but nothing has arrived in the other wallet.

**Comment by hokusai1** [comment]
??

**Comment by hokusai1** [comment]
Can someone please help!?

**Comment by mr10008** [comment]
Did you send  0.006 BTC to this address?
1TAAAHSwpWVXgYTDKPpqiivdUNAsNnF2X

**Comment by hokusai1** [comment]
Yes

**Comment by mr10008** [comment]
Then if you look up on https://blockchain.info/  for 1TAAAHSwpWVXgYTDKPpqiivdUNAsNnF2X you'll see:
Total Received | 0.006 BTC
Final Balance | 0.006 BTC

**Comment by BGalliotti** [comment]
We are closing this thread, please if you still need support, open a new one.
Thanks.
