### ISSUE TITLE
where is my money?

### ISSUE THREAD

**Issue by nottewae** [bitpay/copay#7639]
i have 4 transaction
1: +0.0515
2: + 0.015
summ: 0.0665
_________
3: - 0.006256
4: - 0.0289905
________
remain: 0.00631
How can this happen?
if it is not difficult to calculate that the remainder should be: 0.031339 btc
![2017-12-25_16-54-41](https://user-images.githubusercontent.com/3255009/34340425-6519e110-e994-11e7-986f-133318f1d953.png)

**Comment by nottewae** [comment]
in https://insight.bitpay.com/tx/3dcec9ff05e138c7f14f670e4e82a4e26d10231803c9729faedc5796a8344724
i see next:
my btc send to two adress 1 wrong not my transaction 0.02016185 BTC 
and 1 is my transaction: 0.028905 BTC

**Comment by gabrielbazan7** [comment]
Remember that in each transaction you do, you pay a fee.
