### ISSUE TITLE
Why is 0.005118 BTC to low to spend/Send?

### ISSUE THREAD

**Issue by Pi4q402** [bitpay/copay#7640]
0.005118 which is@$70. - $78. USD
and cannot use any of it doesn't make any sense, considering there would be a remaining balance after fees?

**Comment by gabrielbazan7** [comment]
Hi! Fees calculated by Copay for sending are given to the Bitcoin miners, not Bitpay or anyone related to the Copay project. Currently, bitcoin network congestion is making the fees getting higher and higher. You could check the current average fee for transactions here : https://bitcoinfees.earn.com/.
Also, check the FAQ for more information : https://github.com/bitpay/copay/wiki/COPAY---FAQ#copay-requires-high-fees-for-low-amounts-transactions
