### ISSUE TITLE
Bitcoin not received

### ISSUE THREAD

**Issue by vivek21st** [bitpay/copay#7641]
My transaction is 41 nodes confirmed in blockchain but have not received the bitcoins yet. Please check.

My id- vivek.agarwal8919@gmail.com

My address-
19h5ceJXYfCprx84LibqrJ2RZBJm7pEx9h

**Comment by gabrielbazan7** [comment]
Try going to settings -> choose the wallet -> more options -> Wallet Addresses -> Scan addresses for funds. Or go back and try on transaction History option -> clear cache. Tell me if the problem persist. Thanks
