### ISSUE TITLE
Recovering BCH using the recovery tool incomplete

### ISSUE THREAD

**Issue by johannkaupen** [bitpay/copay#7642]
Hi, I used a multi sig wallet for my niece a while ago and want to move both BTC and BCH. According to your help page on how to use the recovery tool, we moved BTC first and started recovery for BCH.
For some reason, we only found a certain amount.

Back when I set up the wallet I transferred only a small amount initially and later the correct amount. Let's assume I transferred one BTC initially and added another nine BTC later.
Now, we can only find one BCH, the remaining nine can't be found using the recovery tool.

When we started, we still had a backup but it could be that this backup was from the time when I only had one BTC in the wallet.

Is this the reason that we only found the one BCH and not the other nine? If so, shouldn't a new backup also find the remaining nine BCH? We tried this but the tool still only found one BCH.

Any help on how to solve this would be amazing.

**Comment by gabrielbazan7** [comment]
> When we started, we still had a backup but it could be that this backup was from the time when I only had one BTC in the wallet. Is this the reason that we only found the one BCH and not the other nine?

No 

If you have the backup you could import the wallet in Copay choosing first BCH as coin. Remember that all the BTC from your original wallet should be there before the fork date, so that you can see it now on the BCH wallet.

**Comment by johannkaupen** [comment]
Hi Gabriel,

thanks! They were in the wallet long time before the fork (both of the transactions happened in 2014).

Unfortunately the import with the backup didn't work as I hoped it would. It only said that this wallet is already imported. I also tried this with a new Copay on another machine. Again, after selecting BCH and Import wallet, it imported the wallet, but only as BTC wallet.

The recovery tool found at least 5% of the original value in BCH, this import doesn't work at all.

Any other ideas?

Thanks!

**Comment by johannkaupen** [comment]
@gabrielbazan7 Unfortunately this didn't work. I also opened another issue explaining why it didn't work and asking for more help. Didn't receive a message with that one either.
I think there is something wrong with the recovery tool and I'd like to check what I can do.
