### ISSUE TITLE
Cannot transfer BCH

### ISSUE THREAD

**Issue by romankomurka** [bitpay/copay#7643]
Hello,

I let the app create BCH wallet from my primary BTC wallet. I can see it in the app with correct balance, however I cannot transfer my BCH funds from the app. When I click on Send and select a recipient, there is no option to enter BCH amount, just BTC. When I select "Send max amount" it gives me "insufficient funds" (makes sense, the BTC wallet has 0 balance). I don't see any option to change the wallet from which the funds are sent. Am I missing something?

**Comment by gabrielbazan7** [comment]
You cannot send BCH to a BTC Wallet.

**Comment by romankomurka** [comment]
I am not sending BCH to BTC. I am _trying_ to send BCH to BCH wallet but when scan the QR code with BCH address the app doesn't let me input how many BCH I want to send, it just offers BTC.

**Comment by gabrielbazan7** [comment]
Ok. So take a look to the Copay FAQ : https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-cant-send-bch

**Comment by gabrielbazan7** [comment]
If your address is not starting with C and you are sure is a BCH wallet, you have to convert that address to the new convention

**Comment by romankomurka** [comment]
I created a second BCH wallet in the Copay app and tried to transfer the BCH funds there (just to see if it works between my wallets). It's been about an hour or so and there has been no confirmation so far. Once that transaction is finished (if ever?), I will try the converter (thanks for that).

**Comment by romankomurka** [comment]
Just to be sure before I proceed with sending the funds to the converted address. I am trying to send BCH to Kraken. The BCH generated address is 1J7dxQggHpF6vSK91AJRTrGCbFQkjXwusB which translates to CZaXXT2kAsDdpaDZgudM3MtEDNdAekBFiv. If I proceed with the new address, will the BCH appear in my Kraken account? Thanks for help, much appreciated :).

**Comment by gabrielbazan7** [comment]
Yes !
