### ISSUE TITLE
transfer

### ISSUE THREAD

**Issue by wheremymoney** [bitpay/copay#7644]
I have 18 dollars and it won't let me transfer 5 dollars , why???? How much commission you guys charging

**Comment by gabrielbazan7** [comment]
Fees calculated by Copay for sending are given to the Bitcoin miners, not Bitpay or anyone related to the Copay project.
If you need more information check the FAQ https://github.com/bitpay/copay/wiki/COPAY---FAQ#copay-requires-high-fees-for-low-amounts-transactions
