### ISSUE TITLE
unable to transfer , money stuck with copay

### ISSUE THREAD

**Issue by wheremymoney** [bitpay/copay#7645]
![wp_ss_20171226_0001](https://user-images.githubusercontent.com/34843260/34356763-b18ae70c-ea38-11e7-9116-f33257fbe8dc.png)                     so if i have 18dollars how much can i send , how much ? Because i am scared to put money on because all your tickets seem to be about the same problem...whats going ? Does this money belong to me or copay???????

**Comment by gabrielbazan7** [comment]
try using the send max option, you could find it on the enter amount view

**Comment by wheremymoney** [comment]
that option doesnt exist on my phone

**Comment by gabrielbazan7** [comment]
<img width="399" alt="bitpay_-_secure_bitcoin_wallet" src="https://user-images.githubusercontent.com/10999037/34358711-f3152f3c-ea30-11e7-875f-16b438368e42.png">

**Comment by Cr250cra1** [comment]
Report Copay here ..https://www.bbb.org
You will not receive support. Read closed cases!
Gabrielgazan7 will close this ticket like the others. Your money is stolen

**Comment by wheremymoney** [comment]
OMG....well thank you for your advice , i guess its best to just not transact with COPAY , this level of cooperate fraud must have consequences , thank God its just 18 dollars

**Comment by wheremymoney** [comment]
closed???? wow  , just sweep it under the carpet, outstanding customer service !!!! NOT

**Comment by wheremymoney** [comment]
WHAT  A BUNCH OF KNOB HEADS
