### ISSUE TITLE
transaction not found 

### ISSUE THREAD

**Issue by ivrylobs** [bitpay/copay#7677]
TX ID : 26aec191df9e42ef7a4424d30f35779bedb6c6251b795800806db0490c05d647

my transaction still stuck in mem for a day with normal fee whattttttt

**Comment by gabrielbazan7** [comment]
You could check the status of the network here https://bitcoinfees.earn.com/ and here https://jochen-hoenicke.de/queue/#24h

**Comment by ivrylobs** [comment]
@gabrielbazan7  yeah i've checked the network fee and pay a fee with a best price but first i've sent some amount of transaction(first transaction)  with a very low network fee and it's stuck in mempool for a week till my wallet show me a recent balance  (not sure is an error or delay of transaction ) and i've tried to send again by using normal network fee recommended by wallet issue about 1000+ sat/byte now the latest transaction(second transaction) is show on my wallet history but when i click to view in block it not found i don't got it  and i don't know how to fix that
<img width="393" alt="screen shot 2560-12-27 at 13 20 45" src="https://user-images.githubusercontent.com/13993037/34372649-cb02a244-eb08-11e7-85ec-677a75e8081a.png">
<img width="399" alt="screen shot 2560-12-21 at 21 25 24" src="https://user-images.githubusercontent.com/13993037/34372669-e3fa8b36-eb08-11e7-8d66-4622d726d60b.png">

**Comment by carlosgfranco** [comment]
Similar to https://github.com/bitpay/copay/issues/7807
