### ISSUE TITLE
transaction amount of 25.86 % ??

### ISSUE THREAD

**Issue by tom6454** [bitpay/copay#7679]
Hi, today i sent 0.0037 BTC. this transaction will cost me 17.07 Euro ~more then 20 USD !!?? That can not be. My network fee is configured to "super economy". Also i got the messages "This transaction amount is too small..."
What is wrong here ? How can i fix it ? 
Thank for helpt
tom
![auswahl_229](https://user-images.githubusercontent.com/30191620/34361986-b4563536-ea6f-11e7-88d0-3e74e8b5a44c.png)

**Comment by gabrielbazan7** [comment]
Hi, you could have an idea of the network fees on this site https://bitcoinfees.earn.com/. If you want you also have the option to set the fee manually on the confirm view. Currently, bitcoin network congestion is making everyone bid higher and higher to try and get their transactions confirmed in the next block. The current average for transaction fees is about 189,840 satoshis regardless of sent amount.
