### ISSUE TITLE
Difference in Bitcoin received 

### ISSUE THREAD

**Issue by nibupraju** [bitpay/copay#7684]
I have transferred. 013389 to Copay and the same was show as receive. But I am able to access only. 011158 only. 

Can you pls clarify why is this difference 
My address is 

1HFg8WtsFw7p29ff3mR5cKUWy4UeDCWJKb

**Comment by gabrielbazan7** [comment]
what do you mean by "I am able to access only" ? When you try to make a transaction ?

**Comment by nibupraju** [comment]
In the Copay Wallet it is showing as .013399 received

But when I try to transfer only my balance was available  .0115 is
available only

Transfer id of .013399

https://insight.bitpay.com/tx/e981f8b8bd51a4a233894749414640
fe3ebf5ca461b5f1d24d92004749566c3a

**Comment by gabrielbazan7** [comment]
The rest is the miner fees.

**Comment by nibupraju** [comment]
When I tranfered the initial amount it included the miner fee as well

The amount I transferred was 0.01338992 which included .0013 miner fees as
well

**Comment by gabrielbazan7** [comment]
Could you try a "send max" (you could fin the option in the amount view) ?. That is the money you have available in your wallet. If you have unconfirmed funds you could use them by setting "use unconfirmed funds" in settings -> advanced

**Comment by nibupraju** [comment]
I tried. It's still showing 0 balance even with unconfirmed funds enabled
