### ISSUE TITLE
Fee

### ISSUE THREAD

**Issue by Frzks** [bitpay/copay#7685]
![img_20171227_082440](https://user-images.githubusercontent.com/34881200/34374330-fdc18344-eae0-11e7-8593-b4608e525ef2.png)

Hello, I have a problem
Why I have more than 40% for send btc?
Thanks to help me

**Comment by gabrielbazan7** [comment]
Check the FAQ https://github.com/bitpay/copay/wiki/COPAY---FAQ#copay-requires-high-fees-for-low-amounts-transactions .
