### ISSUE TITLE
Transaction NOT showing in History.

### ISSUE THREAD

**Issue by scifimollex** [bitpay/copay#7686]
Bitonic (they send me proof of that action) tells me that on december 13th, 2017 they transfered 0.00059051 BTC to my Electrum (version 3.0.3) wallet "14RtbqbSmpSYAFKqHtgQt3rXhtGEfCZvZa",
but on my "History" I do not see that transaction. 

How is that possible? Or any reaction about this.

SciFi.

**Comment by gabrielbazan7** [comment]
Sorry, we only do support for Copay or BitPay wallet

**Comment by scifimollex** [comment]
When I try to report something in Electrum, I am direct to this foum.

How in the  world is it possible to NOT support a Electrum wallet?

**Comment by scifimollex** [comment]
Where can I put questions and / or problems with Electrum?

SciFi.

**Comment by luckykcc17** [comment]
@gabrielbazan7 Do you really support BitPay and CoPay cause not one seems to respond to this issue that is happening to many users of your services.
