### ISSUE TITLE
Multiple Copay wallets on one device

### ISSUE THREAD

**Issue by awilliam235** [bitpay/copay#7687]
Is it possible to create multiple Copay installations on one device such as a PC? We have one computer but multiple people who want a personal Copay wallet. Or is there another way to get the same result?

**Comment by BGalliotti** [comment]
Hello, sorry for the delay,
You can try with many users in windows. That should work.
If the above does not work, you can install bitpay and copay apps, which are pretty much the same.
If this does not work, one way could be to use many virtual machines (like virtualbox/vmware)and install copay in each of them, though is not very practical, it is a solution.

We are closing this thread, please if you still need support, open a new one, we will happy to help you.
Thanks.
