### ISSUE TITLE
Transaction not completed

### ISSUE THREAD

**Issue by DKad96** [bitpay/copay#7690]
I'm using the BitPay app and I've been having this issue.
It's been almost a week since I transferred funds to my wallet and it just keeps "receiving" 
![image](https://user-images.githubusercontent.com/14855022/34396694-4d6a8520-eb3c-11e7-81a5-d28518e34497.png)

I've checked my btc address on https://blockchain.info: 
![image](https://user-images.githubusercontent.com/14855022/34396708-72a4f1d6-eb3c-11e7-8a1d-ed68e37e4d97.png)

And the transaction on the same site:
https://blockchain.info/tx/c7d3a60fbb5846205c525bd4a07c9ac5f25fd2d9cb6d1790c9b1d7a803de00e1

What bugs me is that right now, 5 minutes after I started to write this, on the app the status has changed to "confirming" and the "View on blockchain" button is no longer available:
![image](https://user-images.githubusercontent.com/14855022/34396767-6ce71066-eb3d-11e7-948e-b0ddd02b0a60.png)

I trust that my btc are still there and that it can take sometimes days for it to complete the transaction, but now I've changed that priority to Urgent on the app and I'm not seeing results.

Thanks in advance!

**Comment by mr10008** [comment]
It looks like the funds are there:
https://blockchain.info/address/3Cg9HQUPnGeKa9fuexMkn6mrC46r1Z2uAi
Total Received | 0.03447189 BTC |  
Final Balance | 0.03447189 BTC
so I don't think that changing the priority to Urgent will affect anything.
Are you using the latest version of the app? Perhaps reinstalling it will fix the issue? Back up the seed first!
