### ISSUE TITLE
Payment Protocol Invalid

### ISSUE THREAD

**Issue by szuranski** [bitpay/copay#7694]
I am getting a payment protocol error when using a testnet wallet. I am using the BitPay Rest API to create an invoice. On 12/21/2017 I was able to scan the QR code from the generated invoice, make a payment and receive the IPN from BitPay. When I tested the morning of 12/22/2017 I started receiving the errors. This happens with Copay, BitPay mobile and desktop apps. I understand this may be a network problem and not a problem with the app itself.  

This link indicates there was disabling of payments smaller than $100. While this was in regards to the BitPay card it was done at the same time I started noticing problems. Is it possible the testnet network has been disabled or affected in some way?
[BitPay Card Status Updates](https://support.bitpay.com/hc/en-us/articles/115005859043-BitPay-Card-status-updates)

![Invalid Payment Protocol ](https://i.imgur.com/XPUwH8e.jpg)

**Comment by cmgustavo** [comment]
Please, see https://github.com/bitpay/copay/issues/7676 for more details.
