### ISSUE TITLE
Single address multi sig wallet: How is the derivation path?

### ISSUE THREAD

**Issue by SimonBelmond** [bitpay/copay#7703]
This issue is related to #6884.

Where can I find a documentation in regards to the derivation of a single address multi sig wallet address from the seed(s)? Googling, Wiki and FAQ do not seem to help here. In #6884 I describe how we have this problem to get our BCH out of our wallet. Meanwhile I am convinced it is related to us having used a single address multi sig. I meanwhile tried the recovery tool also, but it does also show a 0 balance although the wallet is clearly loaded with approx. 10 BCH.

https://blockchair.com/bitcoin-cash/address/32kpHBZCHDUsC1xDCFMB6kAGHcgPaU9bkm

Wallet ID: e6c7e587-7be5-46fc-b7cd-45f39e9b7a5c

2 of 6 multi sig with single address.

Any help to finally get these funds out is mostly appreciated. I have tried the following:

1. Create BCH wallet from existing BTC wallet: Shows 9.7 available but once BCH wallet is created shows 0 balance also after rescan.
2. Restoring BCH wallet from the BTC wallets seeds. Same effect as above. Gives me a wallet with 0 balance also after forced rescan.
3. Recovery tool: Shows a balance of 0.

So I am looking for other options and meanwhile I have the feeling I need to know the derivation path (or similar) or a single address multi sig wallet. How can you give that option when restoring a wallet?

**Comment by mr10008** [comment]
You may find the documentation on this page https://github.com/iancoleman/bip39 and/or links contained on that page.

**Comment by SimonBelmond** [comment]
@mr10008 That did not help me much, I must say. I think someone from BitPay/Copay needs to chime in and answer this one. We can not be the only ones, that have this issue and many have chimed in on issue #6884 that things are not working for them either. There must be a copay specific docu that describes all this a bit more in detail. I am not a dev, would probably go and check the wallet code myself for what they use...

**Comment by BGalliotti** [comment]
Hello,
**Do you still need support with this issue?**
We look forward to hearing from you.
Regards

**Comment by BGalliotti** [comment]
Hello,

We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.

Regarding the BCH funds recover, please follow #8586

Please if you still need support, open a new issue, we will happy to help you.

Thanks.
