### ISSUE TITLE
Fundos insuficientes

### ISSUE THREAD

**Issue by wesllye** [bitpay/copay#7708]
Eu recebi um pagamento, está confirmado mais quando vou transferir para outra carteira btc ele diz que não tenho fundos suficientes

**Comment by Gamboster** [comment]
Hello @wesllye .Perhaps the amount you received is too small and it is considered meaningless to send it, since the network commissions will be much more expensive than your funds. How much BTC are you trying to send?

**Comment by wesllye** [comment]
I am trying to send 0.006298 BTC

Em 2 de jan de 2018 3:06 PM, "Gabriel Masclef" <notifications@github.com>
escreveu:

**Comment by BGalliotti** [comment]
We are closing this thread, please if you still need support, open a new one.
Thanks.
