### ISSUE TITLE
Missing transaction in Copay wallet

### ISSUE THREAD

**Issue by gizmoanden** [bitpay/copay#7709]
I transferred 0.28 BCH from cryptopia to my Copay wallet, but I cannot see it yet. 

TransactionID: b524c4350cec3c6eef1f9aa6a98ecedc23eb71e9e9f8d1072b880127d65ea9a1

Adress:
1Kxj23YrFo4CRLj1xvBG7QLRAAhv4c1cxL

Can anyone help?

**Comment by irynchik93** [comment]
Odyvanchik2026

**Comment by BGalliotti** [comment]
Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will happy to help you.
Thanks.

**Comment by korison** [comment]
@gizmoanden 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
