### ISSUE TITLE
bitcoin cash

### ISSUE THREAD

**Issue by Edititi** [bitpay/copay#7710]
I want to send my bitcoin cash before 2018 at my bitso account, because Copay will no longer work. I enter my address and you do not accept it because it has to have the new format. Either does not accept the address of Coinbase with the same excuse. I want to get my Bitcoin cash and I can´t

**Comment by Gamboster** [comment]
Please, read this link:
https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-cant-send-bch
