### ISSUE TITLE
¿Como hago para obtener mis btc gold, pues mi llave semilla esta en español ?

### ISSUE THREAD

**Issue by JackelineA** [bitpay/copay#7717]
¿Como hago para obtener mis btc gold, pues mi llave semilla esta en español ?, sucede que por tener mi llave de las 12 palabras en español de es compatible con coinomi que es una de las que esta dando los btc gold.... que puedo hacer?

**Comment by TurnUpforButt** [comment]
No sé con el oro. Creo que es un poco dificil pa' obtener si ya tuvieste la billeta de btc.

**Comment by gabrielbazan7** [comment]
Utilizando la recovery tool https://bitpay.github.io/copay-recovery/

**Comment by 270815** [comment]
Usar exchange

**Comment by sebaviegas** [comment]
excelente! me funcionó!!! muchas gracias!
