### ISSUE TITLE
HELP....Is Bitpay stealing bitcoins from sent transactions?

### ISSUE THREAD

**Issue by luckykcc17** [bitpay/copay#7720]
I sent bitcoin with economy fee, which usually works fine but this time it has been stuck in sending for over 8 hours. When I search blockchain with sent address, no transaction shows up so this means that Bitpay has not even broadcasted the transaction to the block. The bitcoin amount is gone from my wallet, the transaction doesn't show up in my history unless I "scan for funds" only to disappear again if I close Bitpay. THIS IS NOT A BITCOIN NETWORK ISSUE!!! THIS IS A BITPAY ISSUE!!! Here is the sent address: 191LvNb4EDQm8876p27Rfqi4z4jf4jyWzS

**Comment by magnetarc** [comment]
Hi,

I am having the same issue today.

I sent 0.5BTC to an address and, although Bitpay remained stuck on 'sending', it appeared to hit the blockchain. However, 17 hours after initiating the transaction, it has disappeared from the blockchain and Bitpay is still stuck on 'sending'.

**Comment by Keensyst** [comment]
Man I can't even find a PayPal card in Greenville Al

**Comment by carlosgfranco** [comment]
Similar to https://github.com/bitpay/copay/issues/7807
