### ISSUE TITLE
Copay me demande 0.001936btc

### ISSUE THREAD

**Issue by lucky884** [bitpay/copay#7721]
Hello on copay i want to send 5 euro and when i go in the wallet he says the transaction tuition will be important no matter how much he asks me 0.001936btc i start with copay i hope not to be have me help please

Bonjour sur copay je veux envoyer 5 euro et quand je vais dans le portefeuille il le dit les frais de scolarité transaction seront important peu importe le montant il me me demande 0.001936 btcje débute avec copay j'espère ne pas être fais avoir aidé moi svp

**Comment by Gamboster** [comment]
It does not make sense to make a transaction for 5 euros, since the commission of the bitcoin network will be much greater than the amount sent.

https://support.bitpay.com/hc/en-us/articles/115003393863-What-are-bitcoin-miner-fees-

**Comment by lucky884** [comment]
Bonjour j'aimerais bien les avoir les 0.001936BTC les miens de copay on disparu    Le lundi 23 avril 2018, 20:36:27 UTC+2, BGalliotti ***@***.***> a écrit :  
 
 
Closed #7721.
