### ISSUE TITLE
Can I transfer the bitcoin that I have in my copay wallet to another wallet ?

### ISSUE THREAD

**Issue by QuestBit** [bitpay/copay#7722]
Hi, I made a transfer earlier from copay to blockchain wallet. It has been more than 3 weeks, the receiver has not receive the bitcoin. But the bitcoin is been deducted from copay wallet. I’m losing my trust on copay. Even my previous ticketing was not reply. I have some balance in copay wallet. Can I transfer out the bitcoin into different wallet ?

**Comment by Gamboster** [comment]
Hello QuestBit, You can transfer your bitcoins to the wallet you want. If you made the send process correctly, you should ask in blockchain wallet support, why you did not receive your funds.
Could you provide us the transaction id?

**Comment by QuestBit** [comment]
Alright thanks a lot. I have sent the transaction id earlier whereby I’ve been replied that you guys are rectifying it. But till now I din get a reply on that. The receiver is making lots of noise now because he has not received the bitcoin whereas in copay wallet, it says that the bitcoin has been transferred. And I have emailed blockchain support as well. Waiting for their reply.

**Comment by Keensyst** [comment]
Good luck I'm beginning to think it's a rip-off

**Comment by QuestBit** [comment]
Are you the admin keensyst?

**Comment by QuestBit** [comment]
https://insight.bitpay.com/tx/4c37091528a48b64505bcc293b62005e32b414b57dd7c32e84aa57dd3e79e080

**Comment by QuestBit** [comment]
Please check this. The receipient who is using blockchain has not received the bitcoin from copay

**Comment by gabrielbazan7** [comment]
That transaction is confirmed, so if you enter the address correctly the recipient should see the funds.
