### ISSUE TITLE
Incoming transfer not confirming 

### ISSUE THREAD

**Issue by patsfan1975** [bitpay/copay#7727]
Hello,

I have received a bitcoin transaction from a source and it is still not confirming after 3 days. They keep transmitting it back so it just keeps saying processing. I am getting an error that states "this transaction could take a long time to confirm or could be dropped due to the low fees set by the sender. What are my options?

**Comment by Gamboster** [comment]
Hi @patsfan1975 , Sorry for the delay. Are you still having problems with this transaction? If the sender put a very low fee, it may take a while to confirm, usually up to two weeks. If it is never confirmed, it will eventually fall out of the mempool and the balance should be available again on the wallet from which it was sent.
