### ISSUE TITLE
Spending this balance will need significant Bitcoin network fees

### ISSUE THREAD

**Issue by audiopathik** [bitpay/copay#7728]
I know this issue has been discussed and clarified multiple times on here already, but since these articles don't provide the answer that I'm looking for I am asking once more.

I have a balance of 50.74 EUR in my Copay Wallet and there is the orange warning notification "Spending this balance will need significant Bitcoin network fees" below it.

That balance is a result of 2 transactions I received, one being the rest of a former payment that I made, making up approx. 1 EUR and the other being approx. 50 EUR that I transfered to my wallet for my next purchase.

Now I was trying to pay 12.41 EUR to a webshop [Play-Asia.com](www.play-asia.com) (Video Games Webshop, using BitPay), including fees for bitcoin payment method they charged 22.43 EUR and including the significant Bitcoin network fees Copay added it totalled to 35.33 EUR - so 22.92 EUR fees for a 12.41 EUR payment compared to 0.- EUR fees for paying with Paypal?!

I was reading through other issues and discussions on the bitpay / copay github and according to articles Javier Donadío links in the [FAQ](https://github.com/bitpay/copay/wiki/COPAY---FAQ#copay-requires-high-fees-for-low-amounts-transactions) this significant Bitcoin network fee is charged when you received your funds in multiple transactions.

Now in my case the second transaction I received was approx. 50 EUR so more than enough to pay 12.41 EUR multiple times and there is no need to withdraw funds from other transactions I received - so where does that enormous Bitcoin network fee come from?

In other words, if I didn't have approx. 1 EUR balance left in my wallet before adding 50 EUR more balance to it I wouldn't have this significant Bitcoin network fee because I didn't receive funds from multiple transactions then?

So to recap - for adding balance to a wallet which already has balance on you will be charged fees of 70% because you received funds from multiple transactions?!

There was another question I had: In Copay you can see bitcoin addresses for all the funds you received seperately (See Screenshot), how can I choose which bitcoin address to withdraw funds for a payment from to avoid using funds received from multiple transactions and reducing data that needs to be computed by the Bitcoin network?
Or, why can I not transfer all the funds on the bitcoin addresses with balance to a single bitcoin address one-by-one to not withdraw funds from multiple addresses in one transaction?
![2018-01-01 2](https://user-images.githubusercontent.com/25881235/34493137-d96df978-efea-11e7-832a-4cff4003a41c.png)

**Comment by Gamboster** [comment]
Hello @audiopathik Did you read this comment ? https://github.com/bitpay/copay/issues/5164#issuecomment-265569494

dabura667 explains it perfectly.

>So to recap - for adding balance to a wallet which already has balance on you will be charged fees of 70% because you received funds from multiple transactions?!

Copay (and any other wallet) only set the fee for the miners when sending a transaction. When you receive payments, you do not have to pay any fees.

If you have many small inputs and you want to send money, in which those small inputs must be included, then you will have a large transaction in Bytes and the fees for the miners will be very large compared to the amount you want to send (The fee is calculate in satoshis / byte)

>how can I choose which bitcoin address to withdraw funds for a payment from to avoid using funds received from multiple transactions and reducing data that needs to be computed by the Bitcoin network?

In Copay you can not choose the addresses from which to send the funds. It is assumed that the wallets are for that and does it in the most efficient possible way.

**Comment by Gamboster** [comment]
I will close this issue precisely because it is a subject so treated before and explained as it should be.

**Comment by rickmts40** [comment]
![IMG_20201106_120255_1.jpg](https://user-images.githubusercontent.com/73891504/98328330-118a7780-2028-11eb-9d30-c5300bcf6bc7.jpg)

insane!

**Comment by audiopathik** [comment]
Necro, but this was also the reason why I never used Bitcoin again, I'll rather let that cash rot in the wallet than pay those ravenous fees to miners.
