### ISSUE TITLE
New bitcoin cash address format

### ISSUE THREAD

**Issue by dabura667** [bitpay/copay#7730]
Found a JS implementation that works:

https://github.com/afk11/bech32/tree/cashaddr
https://github.com/junderw/bech32/tree/cashaddr

check src/base32.js for the implementation and the fixtures for examples.

Spec is here: https://github.com/Bitcoin-UAHF/spec/blob/master/cashaddr.md

**Comment by paOol** [comment]
here is another

https://github.com/bitcoincashjs/cashaddrjs

**Comment by Gamboster** [comment]
Thanks for the contribution. The new Bitcoin Cash address format was implemented in Copay v3 and v4, in these PR. So I'll close this issue.
v3:
https://github.com/bitpay/copay/pull/7838
v4:
https://github.com/bitpay/copay/pull/7850
