### ISSUE TITLE
Bitcoinz Wallet - synchronization error

### ISSUE THREAD

**Issue by hectorrojas150** [bitpay/copay#7731]
Hello, I have two bitcoinz wallets but they do not synchronize, I send coins and the transactions are confirmed by the blockchain but they are not reflected in the wallet.
Can you help me? I have already deleted the cache and it remains the same.

**Comment by imperialgames** [comment]
Same problem here

**Comment by Gamboster** [comment]
We are not bitcoinz, apparently your company copied our code and they did not change the redirect links.
