### ISSUE TITLE
Comisiones para vender bitcoins

### ISSUE THREAD

**Issue by nikorp** [bitpay/copay#7732]
Me podrían pasar por favor una explicación en español del tema de las comisiones para vender bitcoins? He encontrado referencias pero todas en inglés y no termino de entender cómo funciona. Cuántos dólares/bitcoins necesito como mínimo para poder al menos vender algo?

**Comment by Gamboster** [comment]
La comisión blockchain, también conocida como la comisión del 'minero', es una comisión de transacción bitcoin que se cobra a los usuarios cuando realizan transacciones bitcoin. Se recoge esta comisión como recompensa a los mineros por el mantenimiento de la red Bitcoin.

Usted debe pagar la comisión blockchain para asegurar que sus transferencias bitcoin lleguen a tiempo. La comisión blockchain es una de las principales herramientas utilizadas para acelerar las transacciones, que a veces son lentas por una alta congestión en la red. Generalmente, cuanto mayor sea la comisión, más rapido se verificará sus transacciones.

El cuanto debes pagar, no tiene un valor fijo, depende del tamaño de tu transacción y varía, como se menciona anteriormente en base a la congestión de transacciones en la red.
Mientras más transacciónes esperando confirmación haya, las comisiones, logicamente cada vez serán mayores para poder obtener una confirmación relativamente rápido.

Una comisión muy baja podría ocasionar que tu transacción nunca se confirme y eventaualmente se caiga de la mempool (Cola de transacciones a la espera de confirmación)

Las comisiones tienen como unidad Satoshis/Byte, . Si mandaras una comisión de 100 sat/byte, esto significaría que si tu transacción pesara 1 Byte, pagarías 100 satoshis. Multiplica esos satoshis por el precio en moneda fiat en el que se encuentre el BTC en esos momento, y obtendrás el valor aproximado de dólares, pesos, etc..

Aquí puedes ver en detalle los valores que se manejan actualmente en la mempool y hacer tus cálculos correspondientes:
https://jochen-hoenicke.de/queue/

**Comment by nikorp** [comment]
Muchas gracias por la respuesta, me resultó muy útil. Una última consulta, donde puedo ver el peso de mi transacción?

**Comment by Gamboster** [comment]
El tamaño de la transacción tampoco es fijo, varía en función de la cantidad de inputs que sean necesarios para conformarla.

Si tienes que enviar 1 BTC producto de 1 input, pagarás menos que si tienes que enviar 1 BTC producto de haber recibido 4 inputs de 0.25 BTC.

Si usas la wallet Copay, puedes ir a settings -> tu wallet particular -> More Options -> Wallet Addresses -> scrollea hasta abajo del todo, y podrá ver el total de inputs de su wallet, y el costo aproximado en BTC que le costaría mover todos sus fondos.

Quizás te sea de ayuda. Saludos
