### ISSUE TITLE
BTC transaction still waiting 

### ISSUE THREAD

**Issue by malekcsgo** [bitpay/copay#7734]
hey guys i sent 0.0205 (250€) btc to my friend the 25dec and it still on waiting and not "sent" how can i cancel and do it again or do something else about it ?

**Comment by malekcsgo** [comment]
guys please up

**Comment by Gamboster** [comment]
If you put a very low fee, you will have to wait a while (up to two weeks maximum). If the transaction is never confirmed, it will fall out of the mempool and you will have your funds in your original wallet again.

**Comment by malekcsgo** [comment]
ok thank you left me with a hope i will see the 8th then it will be 2 weeks

**Comment by malekcsgo** [comment]
still nothing guys please someone have an issue ?

**Comment by luckykcc17** [comment]
On Bitpay's website is states, "Make your bitcoin transaction confirm faster (see how transaction confirmations work) or refund unconfirmed transactions. " That is like stealing....no??? What happens to unconfirmed transactions? Goes into bitpay's wallet?

**Comment by tab00** [comment]
Can you provide the link of the page in which BitPay says that?

**Comment by malekcsgo** [comment]
guys i have still nothing someone can help ? my money gone or smth ?!

**Comment by malekcsgo** [comment]
up

**Comment by carlosgfranco** [comment]
Similar to https://github.com/bitpay/copay/issues/7807

**Comment by malekcsgo** [comment]
still nothing after one month and cant cancel the transaction :( im fucked ?

**Comment by carlosgfranco** [comment]
hi @malekcsgo , do you have a transaction ID? 
- If you do; try this free TX accelerator (http://www.hooli1.net/). Also, on this bitcoin forum (https://bitcointalk.org/index.php?topic=2455333.0) people offers (free) help to accelerate transactions. give it a try. I did both and got my "low-fee" TX confirmed in less than 24 hours.
- If you don't; try and look up your wallet on a blockchain explorer, and trace where your funds are. the beauty of blockchain is that the ledger is publicly available to everyone.
Good luck!

**Comment by malekcsgo** [comment]
here is the ID (ef0b838a33724be0097c740b0056300e786a3337fd5637c92a498bfe854cce99) it said its confirmed but still not received.

**Comment by Gamboster** [comment]
@malekcsgo , according to your transaction Id your tx was confirmed more than 4k blocks ago. What exactly can not you see in your wallet?
If you think your balance may not be showing right, try rescanning your funds:
Settings -> Wallet Settings -> More Options -> Wallet Addresses -> Scan addresses for funds

**Comment by malekcsgo** [comment]
i send it to someone i know and he has nothing on his wallet still (0BTC)

**Comment by Gamboster** [comment]
Are you sure that the destination address you entered corresponds to your friend's wallet?
Send me your friend's wallet ID and the address to which you made the payment and we will check it.

**Comment by malekcsgo** [comment]
my friend adress : 1LZf3onk6h4HCbpZbe64Vg8qsdkNqX4U4K
 and here is all the info of the transaction : https://blockchain.info/fr/address/148GmyzJ1wuGAXFSjrGQog8SsCTknPRLZ9

**Comment by Gamboster** [comment]
I can see that your friend has the BTC you sent him in that address, effectively. You can tell him to follow the steps I told you earlier:
rescanning addresses:
Settings -> Wallet Settings -> More Options -> Wallet Addresses -> Scan addresses for funds

**Comment by malekcsgo** [comment]
he s got (copay wallet) on his phone that all can he do it through it ? 
and thank you very much for your help

**Comment by Gamboster** [comment]
He will have to do it himself from his phone.

**Comment by malekcsgo** [comment]
he try but still nothing, i made him remove the app and reinstall (recovery with words etc) still nothing :O do you have other idea ?

**Comment by malekcsgo** [comment]
guys ?

**Comment by malekcsgo** [comment]
up please

**Comment by Gamboster** [comment]
Ask your friend the wallet ID of the wallet that should show the funds and pass it, so we can check
Settings> wallet> more options> wallet information

**Comment by malekcsgo** [comment]
here is the id : d78f2565-5b6f-42b4-b912-e3bc47dce501

**Comment by malekcsgo** [comment]
guys ?

**Comment by malekcsgo** [comment]
up :)

**Comment by malekcsgo** [comment]
please my boys

**Comment by malekcsgo** [comment]
up my boys

**Comment by malekcsgo** [comment]
up please boys

**Comment by malekcsgo** [comment]
guys pleassssssssssssseeee

**Comment by Gamboster** [comment]
@malekcsgo 
That wallet id does not seem to match the address to which you sent your funds.

It seems as if you had sent those 0.0205 BTCs to an address in your same wallet, and never to your friend.

Your friend's wallet does not contain funds, no one ever sent him BTC. It is not a failure of Copay. Regards

**Comment by luckykcc17** [comment]
@tab00 Here is the link you wanted to see on bitpay where I quoted that text from:

[](https://support.bitpay.com/hc/en-us/articles/115004832363-Why-can-t-BitPay-help-me-with-my-bitcoin-wallet-transaction-)

**Comment by luckykcc17** [comment]
@tab00 Sorry link did not post:

https://support.bitpay.com/hc/en-us/articles/115004832363-Why-can-t-BitPay-help-me-with-my-bitcoin-wallet-transaction-
