### ISSUE TITLE
Transaction Not Found

### ISSUE THREAD

**Issue by jkristoph** [bitpay/copay#7742]
Hello

I sent a transaction 2 days ago from copay wallet using a high transaction fee option.

This transaction still shows as sending in my wallet, however on inspection of the Transaction, it cannot be found!

TX: 9538f869e62ca3a23911d34a551a7e0c6bc52799eb7f21b3637e98689b4b48aa

The funds can no longer be accessed. It seems like many ppl are having the same issues.

**Comment by heliosilva82** [comment]
Hello, I had this same problem ... but after a few hours (around 10 hours) the transaction was confirmed on the network.

**Comment by luckykcc17** [comment]
Really, it got confirmed eventually?? Can you show us an image to prove this please???

**Comment by jkristoph** [comment]
This is quite alarming. I have used high transaction fees and the coin has been removed from my wallet, yet the Transaction ID cannot be found 48-hrs later.

**Comment by Keensyst** [comment]
Man I appreciate it but I can't find it on my site

**Comment by jkristoph** [comment]
<img width="790" alt="screen shot 2018-01-03 at 8 48 27 pm" src="https://user-images.githubusercontent.com/2474370/34546025-8daf436a-f0c7-11e7-8070-d09839f575e5.png">
<img width="1294" alt="screen shot 2018-01-03 at 8 48 15 pm" src="https://user-images.githubusercontent.com/2474370/34546026-8dc6b52c-f0c7-11e7-9b97-d312a056ffef.png">

**Comment by luckykcc17** [comment]
Thank you **jkristoph** but I believe you, as having exact issue with Bitpay wallet...I wanted **heliosilva82** to show us proof that his got confirmed after 10 hours and with what fee?? heliosilva82 probably associated with Bitpay.

**Comment by Keensyst** [comment]
I feel ya brother I don't know what is going on with my shit

**Comment by Roddy1219** [comment]
export you key to another wallet

**Comment by carlosgfranco** [comment]
Similar to https://github.com/bitpay/copay/issues/7807
@Roddy1219 I tried to do that, to Mycellium. Copay master seed does not work

**Comment by wblac** [comment]
Now have 2 different "Transaction not found" events. Jan 5th I bought BCH from an ATM. Got the confirmation email but no sign of transaction. Today (15th Jan) tried sending from my CoPay wallet which would not accept the recipients address! So tried sending 0.003849 BTC which have also vanished! WTF? Who do I complain to? "wallet-sevice@bitcore.io" is not accepting emails.

**Comment by carlosgfranco** [comment]
In my case it helped that I had at least one of the transactions showing up on the blockchain. Sorry I can't be of much help
