### ISSUE TITLE
Sent bitcoin transaction NOT broadcasted to block

### ISSUE THREAD

**Issue by luckykcc17** [bitpay/copay#7744]
I made 2 bitcoin transactions yesterday with the economy fee...first confirm was received instantly and fully confirmed (6+) within an 40 minutes. The second transaction sent about 30 minutes later is still "sending". I received an email from Bitpay for both transactions confirming that they were sent (please see attachment) but the second one over 24 hours later has not even been broadcast to a block, as I have searched the address on numerous block search websites and the transaction doesn't exist. 

**WHAT IS GOING ON HERE WITH BITPAY????**

The fees Bitpay charges are WAY higher then any other wallet I use, but there seems to always be an issue. My other wallets with cheaper fees have NEVER had any issues like this. 

Bitpay doesn't seem to want to address any issues that users are experiencing even though they have our bitcoin somewhere in their system because they have not even broadcasted the bitcoin to be sent. 

PLEASE SOMEONE EXPLAIN TO ME WHAT IS HAPPENING??

Thank you in advance. 
![bitpay email - wallet sent confirm](https://user-images.githubusercontent.com/34752144/34544303-89a9ab66-f0b3-11e7-85cd-750e1c60eade.jpg)

**Comment by paOol** [comment]
these are BTC congestion issues... not CoPay wallet issues.

your first transaction being confirmed was pure luck.

https://bitcoinfees.earn.com/

all this fee nonsense is due to bitcoin not wanting to increase the blocksize.

Try using BCH and you won't have to worry about fees, they'll all confirm next block at under $0.01.

**Comment by magnetarc** [comment]
I am having the same issue today.

I sent BTC to an exchange address and, although Bitpay remained stuck on 'sending', it appeared to hit the blockchain. However, 17 hours after initiating the transaction, it has disappeared from the blockchain and Bitpay is still stuck on 'sending'. Both sent funds and remaining funds are unusable.

Two other transactions processed fine on the same day. I received emails for these two transactions but none for the 'stuck' transaction.

I am hesitant to clear the cache and rescan the wallet as others have tried that which just resulted in the transaction disappearing from Bitpay altogether.

I do not believe this is to do with congestion, paOol.

**Comment by luckykcc17** [comment]
This is totally **# NOT** from bitcoin network congestion, as I have other wallets and none of them have this issue with half the amount charged in fees. This is a Bitpay wallet issue, as my transaction was NEVER broadcasted to a block as no transaction shows up when searched and never did. 

Please whomever is trying to convince us that this is due to bitcoin congestion is lying, as proof is in the email sent from Bitpay that my transaction was "SENT" and clearly it NEVER was.

**Comment by Keensyst** [comment]
I don't know what is wrong with.y shit bra

**Comment by luckykcc17** [comment]
The transaction that was "sent" has no TXID so that is why I no it never got broadcasted in the first place.

**Comment by luckykcc17** [comment]
**Does BITPAY ever respond to issues??** 

This problem is happening to numerous users of their wallet so do not understand how they get away with this?

**Comment by carlosgfranco** [comment]
Similar to https://github.com/bitpay/copay/issues/7807
