### ISSUE TITLE
Transaction showing "sending" & not found in bitpay insight

### ISSUE THREAD

**Issue by yasminsalim** [bitpay/copay#7756]
Please help me.
My transaction is still showing "sending" from last two days.

**Comment by Keensyst** [comment]
What is up with that? Wow

**Comment by yasminsalim** [comment]
Transaction is unconfirmed from last two days.

Bitpay insight says transaction not found

**Comment by yasminsalim** [comment]
please help me

**Comment by yasminsalim** [comment]
Anybody help please

**Comment by dryazanov** [comment]
Your transaction was sent but it's not confirmed yet. Apparently your fee 0.001566 wasn't good enough. Check transaction fees distribution https://btc.com/stats/unconfirmed-tx and keep in mind that there are ~200K unconfirmed transactions.

**Comment by yasminsalim** [comment]
what i must do now to confirm this transaction?  any suggestion?

thanks in advance

**Comment by magnetarc** [comment]
Hello,

I have had the same issue.

On 3rd January I sent a payment, however, it remained as 'sending' in Bitpay. It initially showed up on Insight but then disappeared (although it was still visible on blockchain.info).

I posted here which was no help.

I waited 72 hours and it seemed to finally return to Bitpay.

I attempted the same transaction with a much larger fee and now have the exact same problem. I contacted Bitpay on 3rd January and have had no reply yet. What is going on??

**Comment by yasminsalim** [comment]
now my transaction is not showing on bitpay android app.

its also not found on bitpay insight.

its only available on blockchain.

i am waiting from last 4 days but its still unconfirmed.

 anybody help please?

**Comment by magnetarc** [comment]
@yasminsalim 

It seems that this is being largely ignored. There have been a number of similar posts all with no solutions.

My next move is to wait another three days for it to hopefully return to the account then try to rescue it all by using my passphrase in to import it into a different wallet. If it doesn't work, it will be very costly.

**Comment by yasminsalim** [comment]
Not getting any reply from BitPay support.

my transaction is not showing on bitpay android app.

its also not found on bitpay insight.

its only available on blockchain, but its unconfirmed from last 4 days.

**Comment by 2pacisALIVEE** [comment]
https://insight.bitpay.com/tx/c773aa4621c58a1190902479f243e01591980cf66adccc6511aa27c8733c4313

This Scares the shit out of me, I wonder how long it might take for the transaction to get through, and if it will get through at all? Can I do something to speed up the process? (I have one week to get it through)

![34739215-e5ea1d8a-f57b-11e7-9d69-df9119376e40](https://user-images.githubusercontent.com/35273402/34763379-32d98bd4-f5eb-11e7-95aa-8426c61c4df1.jpg)

**Comment by 2pacisALIVEE** [comment]
Worst of all is that Copay any sort of support, isn't that like the standard for a company?

**Comment by magnetarc** [comment]
You were scared?...I had 0.5 BTC floating around in limbo for a week!

Update to my situation...the second transaction finally went through after around further two days and it was okay.

Yes, the Copay support is non-existent. I emailed them over a week ago and still have received no reply.

Good luck!

**Comment by yasminsalim** [comment]
https://insight.bitpay.com/tx/13fb4495be34eaec6a3d21dfb82dd1579c147ec1751e39efafff1a4b3713e939

This transaction was made on 03/01/2018 from my bitpay wallet.

Until today, it's unconfirmed on blockchain.

This transaction not display on my bitpay wallet history & on bitpay insight page. (Transaction not found).

I did sent many emails to bitpay support team regarding this issue but not getting any response from them.

I want my money. Otherwise i am going to report BBB regarding this scam.

**Comment by carlosgfranco** [comment]
Similar to https://github.com/bitpay/copay/issues/7807
