### ISSUE TITLE
wallet fee 

### ISSUE THREAD

**Issue by joemanfred** [bitpay/copay#7757]
Hi,
is there a wallet fee for transactions from copay, and if yes how high is it
thx

**Comment by avibrazil** [comment]
No, Copay itself doesn’t charge transaction fees.
But the Bitcoin network charges high fees, independent from which wallet software you are using.

**Comment by luckykcc17** [comment]
That is NOT true!!!

There is a network fee charged by copay/bitpay that will not be seen on the transaction invoice, as it seems to disappear once transaction is completed. and it seems to keep getting higher by the day.

And Copay/Bitpay's network fees are RIDICULOUSLY HIGH.....I send from other wallets and the fee is 10% of Copay/Bitpay's and it gets there super fast. It makes no sense!!! Seems like something smells.

**Comment by 2pacisALIVEE** [comment]
https://github.com/bitpay/copay/issues/7790

Can anyone give me a solid answer for this?
I choose the lowest transaction fee possible, it just says "sending", Idk what to do? How long will this take? I need to get this transaction through ASAP
