### ISSUE TITLE
not displaying address

### ISSUE THREAD

**Issue by whatever220039** [bitpay/copay#7765]
Hello,i am trying to buy something but i can't because the payment system is displaying the bitpay url instead of the address that i am supposed to send $ to: 

https://gyazo.com/e948b061fef8bf863c762b33622bca3c

**Comment by whatever220039** [comment]
Nevermind,i read the stupid changes you did to the system,literally forcing me to work with other wallets

**Comment by Keensyst** [comment]
Well fix them

**Comment by BGalliotti** [comment]
We are closing this thread, please if you still need support, open a new one.
Thanks.
