### ISSUE TITLE
Bitcoin.com Issue

### ISSUE THREAD

**Issue by HartlPet** [bitpay/copay#7766]
when i want to open my bitcoin btc wallet it keeps saying insight error and try again later..

**Comment by Keensyst** [comment]
Mine too

**Comment by onatbas** [comment]
Same.

**Comment by dabura667** [comment]
bitcoin.com is not copay.

It uses copay's source code... but please, Copay is already getting slammed with issues and have no people to deal with them... please send bitcoin.com support requests to bitcoin.com.

Also, "Insight error" means that bitcoin.com's insight server is probably down... and Copay can not touch their servers, because Copay is not bitcoin.com.

**Comment by CryptoKidd** [comment]
My Bitcoin Core wallet is back up and running fine now.  Bitcoin Cash wallets didn’t seem to have any issues.

**Comment by majinpsycho** [comment]
Just did a transaction to the wallet, and i see the insight error.... Is my transaction safe??

**Comment by sreenicam** [comment]
I am not able to do any transactions because of this "Could not update wallet: Insight error"
There was some recommendations in issue #7149 . I did those and did help. Still seeing the same error!

**Comment by setar** [comment]
my both wallet - on win desktop and on mobile android have too same problem.

**Comment by CryptoKidd** [comment]
I’m really unsure how many signs the world needs to know that Bitcoin score is not a place to keep your money...  Bitcoin Cash is Bitcoin my friends 🌎✌🏻

**Comment by dsnkostic** [comment]
Same issue here: Insight error, on both Windows and Android client...

**Comment by Keensyst** [comment]
What is going on with this nonsense.

**Comment by yerlegrev** [comment]
I exported my wallet from Bitcoin.com Wallet app. I downloaded the copay.exe file from [here](https://github.com/bitpay/copay/releases/tag/v3.9.1) and imported my wallet using from file/text. I already transferred by bitcoin to my other wallet :-)

It worked for me and hope this helps.

**Comment by vuduy67215** [comment]
Vào 07-02-2018 0:29, "Gabriel Masclef" <notifications@github.com> đã viết:

**Comment by vuduy67215** [comment]
Vào 08-02-2018 0:44, "phim hay" <vuduy67215@gmail.com> đã viết:

**Comment by fredbuluku** [comment]
> git unlock Bitcoin Blockchain operation to BitPay
