### ISSUE TITLE
12 words passphrase not working

### ISSUE THREAD

**Issue by offerm** [bitpay/copay#7767]
Hi,

I'm trying to use bitpay with 12 words passphrase but getting an error " Wallet Recovery Phrase is invalid"

The Phrase was created when I opened a counterparty account. It is working well with counterwallet.io. 

I have check and found that not all the words are here  (some are missing) https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt

How can this be explained? are there multiple ways to create the 12 words? Beside moving the BTC is there any other option I can use?

Thanks

**Comment by Gamboster** [comment]
Here is the list of all the words of the bip-0039 in all languages: https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md
Maybe you're looking for the words in the wrong language?
I really do not know how counterwallet.io works, but it should create your seeds with the words contained in that standard document.

**Comment by BGalliotti** [comment]
We are closing this thread, please if you still need support, open a new one.
Thanks.

**Comment by harrisondel** [comment]
@offerm 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
