### ISSUE TITLE
Something wrong with my wallet

### ISSUE THREAD

**Issue by kavvak** [bitpay/copay#7768]
Hi,

I have a personal wallet on copay and used to work fine till I sent a transaction with low fees and it is stuck in unconfirmed state. After that another one with higher fee and got stuck again. Then i sent another with the same fee as the first one but higher fee but it even did not show up in transaction but updated the first transaction but my balance shows that both have been sent out unconfirmed. Now today i sent another one with normal fee which is pretty weird. I cannot click on the transaction (transaction not found). Also my wallet address used to be something else and now the address has changed automatically??!! And i try to import the original one but it says it already exists.
And this new address in blockchain shows zero balance and the original address shows only 2 transactions out of 4 but my balance is zero as well. 
What is going on?
Anyone any ideas?

**Comment by Keensyst** [comment]
I got the same problem if you can figure it out please let me know.
On Jan 6, 2018 1:35 PM, "Kaveh Vakili" <notifications@github.com> wrote:
>
> Hi,
>
> I have a personal wallet on copay and used to work fine till I sent a
transaction with low fees and it is stuck in unconfirmed state. After that
another one with higher fee and got stuck again. Then i sent another with
the same fee as the first one but higher fee but it even did not show up in
transaction but updated the first transaction but my balance shows that
both have been sent out unconfirmed. Now today i sent another one with
normal fee which is pretty weird. I cannot click on the transaction
(transaction not found). Also my wallet address used to be something else
and now the address has changed automatically??!! And i try to import the
original one but it says it already exists.
> And this new address in blockchain shows zero balance and the original
address shows only 2 transactions out of 4 but my balance is zero as well.

**Comment by RaneLiteas** [comment]
Same issue here! Refresh wallet, transactions and refresh again no transaction and no bitcoin!!! I have been waiting almost a week for my bitcoin deposit!!!

**Comment by luckykcc17** [comment]
Same thing happening to me since December 7, 2018

**Comment by Keensyst** [comment]
I been waiting a week and still don't have any money on my account

**Comment by carlosgfranco** [comment]
Similar to https://github.com/bitpay/copay/issues/7807
