### ISSUE TITLE
Платежный пароль

### ISSUE THREAD

**Issue by kobecstanislav** [bitpay/copay#7770]
Забыл платежный пароль.Что делать ?

**Comment by Gamboster** [comment]
Please, the support is in English. If you forgot your spending password, but you have a backup of your wallet (Qr, file or the 12 words) You can delete the app, and then install it again. Import your wallet with the backup that I mentioned, you will not have set spending password.
Important: Before removing the application. Make sure your backup was done correctly.

**Comment by vuduy67215** [comment]
Vào 07-02-2018 0:50, "Gabriel Masclef" <notifications@github.com> đã viết:
