### ISSUE TITLE
Bitpay wallet amount to low to spend - fix

### ISSUE THREAD

**Issue by jusp0426** [bitpay/copay#7780]
I've had a small balance in my Bitpay wallet for a while that I was unable to transfer to my card. The error message " Amount to low to spend" should be changed to " Our fees are ridiculous".

Yes, their fees are HIGH, but I was able to take out the little I had out; before I shred or burn the card.

I had a small balance of about $40 left in my bitpay wallet and was able to get a remaining $11 after the fees were deducted.

STEPS: Using the Bitpay mobile app
- Go to settings
- Bitcoin Network Fee Policy
- Fuck the Normal option.. I went "SUPER ECONOMY"
- Go back to Homepage
- Hit the SEND icon
- Enter BTC address you want to send to

After you'll get some BS note about the fees that will be collected.
(Make them EAT their fees) and go ahead and hit "Accept" or "I understand"

*** My SAD $11 dollars was probably anxious to get out that it showed up in my COINBASE wallet in 5.3 seconds after I hit SEND.

**Comment by gabrielbazan7** [comment]
Hi! sorry for the delay... take a look to: https://github.com/bitpay/copay/wiki/COPAY---FAQ#copay-requires-high-fees-for-low-amounts-transactions.

Also, the send max option in the amount view could be useful for you, now that the network fees are lower, you will be available to move most of it.
