### ISSUE TITLE
bitcoinz wallet

### ISSUE THREAD

**Issue by hellooods** [bitpay/copay#7781]
Could not update wallet: 502, anyone know what the issue is?

**Comment by coindings** [comment]
Same here, what´s going on?

**Comment by Killerfrog423** [comment]
Same waiting for response.

**Comment by coindings** [comment]
Seems like the server isn´t responding :-( hope they will fix it soon...

**Comment by coindings** [comment]
It´s working again!

**Comment by vule11** [comment]
Yesterday I sent btcz coins around 15 o'clock and nothing has been done so far. Does Anyone Know What It's About?
