### ISSUE TITLE
Bought an amazon gift card did not receive it

### ISSUE THREAD

**Issue by DemoHam** [bitpay/copay#7783]
I just bought an amazon card using bitpay and I did not get the gift card and it already has 6+ confirmations am I ever going to get it?

**Comment by kferrer** [comment]
Did you get a solution for this? i had the same issue a while ago (jan 13) and i'm still waiting for a reply from the support team (contacted them through email).

**Comment by Gamboster** [comment]
Hello @DemoHam Sorry for the delay and the problems related to Amazon integration.
If for some reason your Amazon Gift Card is not getting the code to redeem it, please contact to the bitpay help center: https://help.bitpay.com/requestHelp, select the BitPay payment/transaction and describe your issue providing the invoice id or transaction id for your Amazon Gift Card purchase. Also you can send an email to help@bitpay.com.

@kferrer ^^
