### ISSUE TITLE
Confirm transaction for more than 3 weeks

### ISSUE THREAD

**Issue by matt77unltd** [bitpay/copay#7792]
My wallet worth of $600 till now has not been confirmed in my copay wallet for 3 weeks now, all it keep displaying is receiving and today I can't even see any Bitcoin display. What is wrong is my coin lost or what?

**Comment by brewmium** [comment]
Did you not pay enough of a mining free to transfer?  I exported my bitpay wallet to Electrum, then was able to increase the fee (and accept a bit less) to get mine unstuck.

**Comment by yasminsalim** [comment]
https://insight.bitpay.com/tx/13fb4495be34eaec6a3d21dfb82dd1579c147ec1751e39efafff1a4b3713e939

This transaction was made on 03/01/2018 from my bitpay wallet.

Until today, it's unconfirmed on blockchain.

This transaction not display on my bitpay wallet history & on bitpay insight page. (Transaction not found).

I did sent many emails to bitpay support team regarding this issue but not getting any response from them.

I want my money. Otherwise i am going to report BBB regarding this scam.

**Comment by yasminsalim** [comment]
How to export bitpay wallet to electrum?

How to get confirmed struk transaction?

Please reply

**Comment by carlosgfranco** [comment]
Similar to https://github.com/bitpay/copay/issues/7807

**Comment by brewmium** [comment]
were you sending the coins to yourself?  If so, you can bump the fee on the receiving wallet, or move the Wallet to Electrum & it will allow you to do this, if you wallet does not. That's how I got an inbound transfer to my bitpay wallet, that had gotten stuck. BitPay wallet really should add support for this! It's a real problem with unconfirmed transactions!!!  And will probably only get worse.

**Comment by brewmium** [comment]
@yasminsalim I searched youtube for moving my wallet over. To Electrum was the only sane option. Search for it, you will find it.

**Comment by carlosgfranco** [comment]
Hi @brewmium, I tried to import the wallet in mycellium but copay’s Master seed comes up as incorrect...

**Comment by brewmium** [comment]
did you choose BIP44 and get the warning about it not being secure enough?  ou mean Electrum right?  don't know mycellium.  I'm not tech support... just trying to give help. :-)

**Comment by carlosgfranco** [comment]
hi @brewmium , the app I tried does not have the option that you mention. Or I couldn't find it. I tried this wallet https://wallet.mycelium.com/ which I found googling around.
I was able to solve my issue. Thank you for your interest in helping others. Much appreciated.

**Comment by brewmium** [comment]
Glad to hear that!!  Yea, having your coins stuck in the netherworld is much less than fun! I found it a bit stressful.
