### ISSUE TITLE
BitPay STOLE my bitcoins, literally disappeared. I have proof....

### ISSUE THREAD

**Issue by luckykcc17** [bitpay/copay#7797]
All my "sending"transactions have disappeared from my BitPay history....and none of the botcoin has been crested back to my balance.

WHERE IS MY BITCOIN, BITPAY??

![bitpay sending history](https://user-images.githubusercontent.com/34752144/34754646-0bb68696-f58d-11e7-9561-a7be7c3a0ce9.jpg)

And that is only the half the transactions that have disappeared....only took picture of first half. 

PLEASE HELP!!!!????

**Comment by luckykcc17** [comment]
Is this even BitPay's support forum cause I have sent two support tickets and also reported BitPay to the BBB.....not a single word from BitPay.

**Comment by luckykcc17** [comment]
@gabrielbazan7 Do you really support BitPay and CoPay cause not one seems to respond to this issue that is happening to many users of your services.

**Comment by allthatmoney** [comment]
bitpay is a free wallet and volunteers help you when they can most of the time. this is bitpay and copay help forums. if your bitcoin has disappeared you need to find out why. have you gotten any bitcoincash from your wallet? and if you did have you used the extractor tool where you put the 12 words in? that's the first part of the process though is trying to find out what you have done, or what someone else has done. there is a hacker in the system though and we need to be carefull. i made a new wallet a couple months back and i got my bitcoin receive address out and i sent a small 40 dollar deposit to that address and it never showed up. after writing into support i was told the bitcoin address i used was not a copay bitcoin address. so how did it get into my copay wallet if it was not a copay address, we will never know, but we do know it had to be a hacker because the address came from my copay wallet. i was just lucky because i had a 500 dollar deposit i was going to make rite after my test deposit. if i had went ahead without a test i would have been ut 500.00

**Comment by luckykcc17** [comment]
@allthatmoney Thank you for your response, but BitPay is by far not a free wallet. They charge highest fees I have ever seen, as I use other wallets, send same amount with a quarter or less of a fee and it transfers quickly. Also, Botpay charges a network fee for loading debit card, which is. about $30-$40 ontop of their ridiculously high mining fee. 
BitPay should have legitimate customer service, as they have employees not volunteers working there. They just expended and opened offices in San Francisco and New York City so obviously they are making money. 
To get back to your answer, I have never bought bitcoin cash and don't plan too. 
I had no idea that there is a confirmed hacker within bitpay/copay system???  That is very unsettling....

**Comment by allthatmoney** [comment]
i know man. i hated to get hacked from my copay wallet but it's a lain and
simple hack if the wrong btc address came from it when i clicked the
receive button. plain as day it was a hack. they do have someone working
for support i think but most of the time other members pitch in. as for the
transaction fees you can go into your wallet and set the fee lower and it
will save you some money. i have mine set on economy and it works fine. you
will notice though that any true private wallet you will pay more for trans
fees. i guess the third party wallets like coinbase has a special deal with
blockchain. i put in 100.00 in copay the other day but did not send, i just
wanted to see the send price and i think the fee was 18.00. then i put the
same amount in coinbase and the fee was only 8 dollars. so it looks like if
we want the security of a private wallet we have to pay for it. coinbase is
very dangerous but i use it, what i do is i put in about 500.00 and when i
use it up i put in another 500. coinbase is very useful when you want to
send cash to your bank account or get a good debit card. the debit card
they use will only take the exact amount of bitcoins needed to make your
purchase as you need it and they don't charge a fee for it. it's the shift
card in case you want to tie it into a coinbase account. just sign up and
they will give you the instructions on how to link it.

**Comment by yasminsalim** [comment]
https://insight.bitpay.com/tx/13fb4495be34eaec6a3d21dfb82dd1579c147ec1751e39efafff1a4b3713e939

This transaction was made on 03/01/2018 from my bitpay wallet.

Until today, it's unconfirmed on blockchain.

This transaction not display on my bitpay wallet history & on bitpay insight page. (Transaction not found).

I did sent many emails to bitpay support team regarding this issue but not getting any response from them.

I want my money. Otherwise i am going to report BBB regarding this scam.

**Comment by luckykcc17** [comment]
Just sent bitcoin from my Local bitcoins and the fee was 0.00028607 btc = $4.02 usd. So BitPay’s fee are ASTRONOMICALLY high and unnecessary.

**Comment by luckykcc17** [comment]
@allthatmoney BitPay is not different then any other wallet....you got hacked using BitPay/Copay wallet so how did the higher fee help you???

**Comment by allthatmoney** [comment]
i did not say a higher fee helps. all i said is if you want a lower fee you can go in and pick the economy and it will be cheaper to send.  but really, if you sent a transaction for 4.02 that is cheap. what wallet was that? i have been paying an average of 18 to 22.00 to send bitcoin.

**Comment by allthatmoney** [comment]
but also as it was proven you can still get hacked even when you use a private wallet.

**Comment by gabrielbazan7** [comment]
@luckykcc17 you could set a custom fee if you want.

**Comment by luckykcc17** [comment]
@gabrielbazan7 BitPay doesn't send with super economy or custom fees. All the transactions from picture I posted were done with fees. So where is my bitcoin?? Not in balance and not received either. Plus now since the latest Bitpay update that history no longer shows up...so Bitpay has my bitcoin cause they were never broadcasted to the network in the first place. 

@gabrielbazan7 Are you a Bitpay rep?? You close posts so you must have some kind of authority.Why is Bitpay doing this to users?

**Comment by kiwina** [comment]
No sure if any of you realized but bitpay dosn't control your wallet you do!!

**Comment by luckykcc17** [comment]
@kiwina So where is my bitcoin if Bitpay doesn't have it and did not send it out to a block to be processed???? Bitpay does control where your bitcoin goes when doing a transaction....not sent and not in my wallet balance.

**Comment by luckykcc17** [comment]
@gabrielbazan7 PLEASE RESPOND......HELP US OUT!!!

**Comment by allthatmoney** [comment]
you can't track it if you don't have a transaction number. do you have a
transaction number in your history?

**Comment by luckykcc17** [comment]
@allthatmoney I have the sent bitcoin address but since Bitpay NEVER broadcasted the transactions, none of them got txd numbers, obviously.

**Comment by allthatmoney** [comment]
now that one is for support. there is no way bitcoin should ever be able to
be sent out of your wallet without a tx number. it really shouldn't be
possible.

**Comment by Hillsongnit** [comment]
I was scammed 24.00btc, lost my money, it is heart breaking once you figured you cannot withdraw your crypto currency. I read on bitcoin forum referral to hire bitcoinrecovery AT consultant() com for help to recover my money and as instructed, the group was able to recover my funds within 20hours after I explained myself. So if you happen to have fallen victim of binary options, investment scam or lost you wallet key, give +One51SIX341187one a call or text for conversations on how to go about a chargeback from the scammer, you can as well get in touch using the professional mail contact  B I T C O I N R E C O V E R Y @ Consultant Com and thank me later, very good, trust worthy certifiably the best just for the fact that they had been getting funds recovered for victims for quite a while now with enough recommendations, I made use of their service and you could as well.

**Comment by Hillsongnit** [comment]
I was scammed 24.00btc, lost my money, it is heart breaking once you figured you cannot withdraw your crypto currency. I read on bitcoin forum referral to hire bitcoinrecovery AT consultant() com for help to recover my money and as instructed, the group was able to recover my funds within 20hours after I explained myself. So if you happen to have fallen victim of binary options, investment scam or lost you wallet key, and how to go about a chargeback from the scammer, you can as well get in touch using the professional mail contact B I T C O I N R E C O V E R Y Consultant Com and thank me later, very good, trust worthy certifiably the best just for the fact that they had been getting funds recovered for victims for quite a while now with enough recommendations, I made use of their service and you could as well.

**Comment by btcbobbi** [comment]
High on June 4th 20/20 that happened to me. I'm made two transactions into my bitpay wallet totaling $696 as soon as my transactions were finished into my Bitcoin wallet 2 transactions were being made without my consent or doing and my colleagues and I
![Screenshot_20200616-113211_Gmail](https://user-images.githubusercontent.com/67070148/84932266-e6a78300-b088-11ea-9ff0-ab02be62fde4.jpg)
![Screenshot_20200616-113216_Gmail](https://user-images.githubusercontent.com/67070148/84932284-ec9d6400-b088-11ea-9858-886247e8fbcd.jpg)

 literally watch my big coin disappear right out of my wallet I contacted bitpay support center through email cuz that's the only way you can get a hold of them. And they're only reply was our employees can't get into your wallets we are unable to help you they will assume no responsibility your Bitcoin will not be safe in bitpay wallet somehow someone's getting into their system and taking your transactions that you put into bitpay and taking it right out. I bet they will just say some random bullshit that is unhelpful and they will not help you receive your Bitcoin back I have gone to the FBI and the BBB as of yesterday to get help
![Screenshot_20200614-151458_BitPay](https://user-images.githubusercontent.com/67070148/84932092-9c260680-b088-11ea-82b7-304581a0535f.jpg)

**Comment by btcbobbi** [comment]
If it happens to you you can get ahold of the FBI through ic3.gov to open up a file like I did

**Comment by btcbobbi** [comment]
And I want to reiterate I said bitpay the wallet numbers the TX ID numbers show them pictures times and dates and they just state that the BTC is stored on my phone that I need to use my 12 word phrase key but I tell them I didn't lose my wallet and I use my 12 bass key to see if I can get my Bitcoin back and when I did the 12 phase key it says my wallets already there I tell them this but they just tell me the same thing over again they are unhelpful so beware if you use bitpay because your crypto will get stolen as it has to me and the other people above bitpay will not help you whatsoever they're totally incompetent and take no responsibility

**Comment by btcbobbi** [comment]
I want my Bitcoin back bitpay you can tell by looking on here that is happening to a lot of other people what the hell is wrong with you and your company help us we want our Bitcoin back I left the 1 * comment on the Google Play Store to ward off anyone else from using your app and ATM card

**Comment by btcbobbi** [comment]
You're lucky I don't live by the person who makes the decisions at bitpay or I would be down there going postal.. I guarantee you that!

**Comment by btcbobbi** [comment]
Everyone that's on here and has lost crypto through bitpay needs to get ahold of the FBI through ic3.gov so we can stand this one and get our crypto back!!

**Comment by sixxgunzz** [comment]
It looks like comments have been minimized above that means they're important so I would take a look at them comments.. obviously bitpay does not want you to know that they incompetent and uncaring did you not care if your Bitcoin gets stolen they will just put it off on you read all the comments that are minimized to help you make a good decision..

**Comment by sixxgunzz** [comment]
![Screenshot_20200614-151458_BitPay](https://user-images.githubusercont up tom/24799551/84953742-ea4b0200-b0a8-11ea-8f26-66145b67468b.jpg)
This is a picture for transactions the two receiving ones were done by me the two outgoing ones right after each of the receiving ones was done by some fraudulent activity done individuals through the bitpay app bitpay will not recognize what's going on they only want to say that your wallet is not there and you have to use your 12-step t or bet your phone got compromised I used my 12-step key it came back with the message your wallets in there and I tried to tell them this and they don't care if they do not care about anything I tried to tell them and send pictures and txid information they just said there's no way for their employees to get into our keys or wallet which makes no sense when you show them proof of stuff that's going on and they know from all the activity in this GitHub conversation that something's going on but they failed to do anything about it nor do they want to so be careful I would not use bitpay

**Comment by sixxgunzz** [comment]
![Screenshot_20200614-151458_BitPay](https://user-images.githubusercontent.com/24799551/84953984-65acb380-b0a9-11ea-94e0-0daea4afac67.jpg)

**Comment by sixxgunzz** [comment]
Hi on June 14th 2020 that happened to me. I'm made two transactions into my bitpay wallet totaling $696 as soon as my transactions were finished into my Bitcoin wallet 2 transactions were being made without my consent or doing and my colleagues and I literally watch my btc disappear right out of my wallet I contacted bitpay support center through email cuz that's the only way you can get a hold of them. And they're only reply was our employees can't get into your wallets we are unable to help you. they will assume no responsibility. your Bitcoin will not be safe in bitpay wallet somehow someone's getting into their system and taking your transactions that you put into bitpay and taking it right out. they will just state the same thing over again that is unhelpful and they will not help you receive your Bitcoin back!! I have gone to the FBI and the BBB as of yesterday to get help

**Comment by sixxgunzz** [comment]
And I want to reiterate I sent bitpay the wallet numbers the TX ID numbers show them pictures times and dates and they just state that the BTC is stored on my phone that I need to use my 12 word phrase key but I tell them I didn't lose my wallet and I use my 12 word key to see if I can get my Bitcoin back and when I did the 12 phase key it says my wallets already there I tell them this but they just tell me the same thing over again they are unhelpful so beware if you use bitpay because your crypto will get stolen as it has to me and the other people above bitpay will not help you whatsoever they're totally incompetent and take no responsibility. They are totally uncaring and play ignorant without wanting to investigate even though everybody above and I'm sure countless others that it's happen too have complained! they(bitpay) just act stupid like it's your fault

**Comment by sixxgunzz** [comment]
If more people want to get help go to ic3.gov that is the FBI's website for fraudulent internet activity and fraudulent businesses

**Comment by sixxgunzz** [comment]
1Xo2DkFyBPL6ZUyhgJWzA4ZDgpF5cJNSm

My bitpay my bitpay BTC wallet please put my Bitcoin back it was stolen through your app despite if the Bitcoin is on my phone it was taken through your app it is your fault I want my Bitcoin back and I will change my reviews and get ahold of the FBI and tell them that you put it back cuz I did make a case

Picture below shows how much they stole to your app whatever my Bitcoin resided it this thieving done through your app.
![Screenshot_20200614-151458_BitPay](https://user-images.githubusercontent.com/24799551/84955658-832f4c80-b0ac-11ea-95fe-56ed7ce92152.jpg)

**Comment by sixxgunzz** [comment]
Here's a partial picture of my FBI report if you don't think I'm telling the truth I just want my Bitcoin back
![Screenshot_20200617-151453_Gallery](https://user-images.githubusercontent.com/24799551/84956141-6c3d2a00-b0ad-11ea-9ed9-ac1df91c25c6.jpg)

**Comment by sixxgunzz** [comment]
Go ahead bitpay put my money back in my wallet watch it disappear real quick I'll show you how the hell is this happening??!
Get me back my Bitcoin you incompetent people!!

**Comment by matiu** [comment]
Threats and hateful comments won't be tolerated. In those cases, users will be block and issues closed.
