### ISSUE TITLE
CoPay Stole my Bitcoins

### ISSUE THREAD

**Issue by CryptoKing911** [bitpay/copay#7798]
I was having very difficult time being able to transfer out my bitcoins from copay to the binance exchange. Finally, I had to reduce the fee to 0.1 and it allowed the Transaction to go through. I got an email saying the money was sent but now the money is gone from copay and its not in binanace.  What us up, where are my bitcoins. 

Any Help

**Comment by luckykcc17** [comment]
Join the club.....

Just sent bitcoin from my Local bitcoins and the fee was 0.00028607 btc = $4.02 usd. So BitPay’s fee are ASTRONOMICALLY high and unnecessary.

**Comment by wblac** [comment]
You think  $4USD is high - Copay wants 51% as a fee on £64GBP! Also BCH purchased are not on the Blockchain

**Comment by luckykcc17** [comment]
@wblac No I agree with you....re-read what I wrote as I said local bitcoins wallet sent it for $4provinf that bitpay’s fees are ridiculously high.

**Comment by CryptoKing911** [comment]
Copay sucks they did the same thing to me

**Comment by harrisondel** [comment]
@CryptoKing911 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
