### ISSUE TITLE
Bitpay’s Transaction fees do NOT need to be so high.....fact!!!!

### ISSUE THREAD

**Issue by luckykcc17** [bitpay/copay#7800]
Just sent bitcoin from my Local bitcoins and the fee was 0.00028607 btc = $4.02 usd. So BitPay’s fee are ASTRONOMICALLY high and unnecessary.

**Comment by SuBPaR42** [comment]
Sending TX confirming in 15 minutes (next block) for ~55 sat/byte and Super Economy is 293 sat/byte.

Need to work on this!!

**Comment by gabrielbazan7** [comment]
You could set a custom fee for your transactions in the confirm view.
