### ISSUE TITLE
Transaction not found 

### ISSUE THREAD

**Issue by wblac** [bitpay/copay#7801]
Despite receiving a confirmation email the BCH I bought appeared briefly in my Copay wallet.  Now it has vanished and is not found on the Blockchain.  Have I lost my money?

**Comment by JDonadio** [comment]
@wblac could you please go to settings > wallet > more opts > wallet addresses > scan addresses for funds, and tell me if the problem was fixed or remains? thanks

**Comment by wblac** [comment]
Wow thankyou! That has fixed that particular problem but now I cannot send
my BCH to a vendors wallet address. I read the help file and have loaded
the latest version of CoPay but this has not helped. What now?
Thankyou

**Comment by gabrielbazan7** [comment]
@wblac use the address translator https://bitpay.github.io/address-translator/. BitPay and Copay BCH wallets use the CashAddr format by default. I think that the one you need is the Legacy BCH Format.
