### ISSUE TITLE
gpg sig not trusted?

### ISSUE THREAD

**Issue by chorfan** [bitpay/copay#7803]
Just checked the sig on BitPay-linux.zip and got:

> 
> gpg: Signature made Tue 09 Jan 2018 12:25:51 PM PST
> gpg:                using DSA key 9D17E656BB3B6163AE9D71725CD600A61112CFA1
> gpg: Good signature from "Copay (visit copay.io) <copay@bitpay.com>" [unknown]
> gpg: WARNING: This key is not certified with a trusted signature!
> gpg:          There is no indication that the signature belongs to the owner.
> Primary key fingerprint: 9D17 E656 BB3B 6163 AE9D  7172 5CD6 00A6 1112 CFA1

Fresh new sig and completely unverified? I don't think I want to install this.

**Comment by dabura667** [comment]
“Good signature from xxxx” means the signature is ok.

What GPG is telling you is “currently Copay’s public key is not signed by a trusted key. So for all I know, this public key could be a bad guy pretending to be Copay”

I can verify that the fingerprint I am looking at matches the one I am looking at in your comment.

It should be fine.

Google “gpg web of trust” for more info on why gpg says “good signature” and “no trusted signature” in the same command.

**Comment by chorfan** [comment]
Thanks, I actually understand the concept perfectly. Which is probably why I don't think "it should be fine." People are using this app to hold serious sums of money. If you think there's no meaningful incentive to spoof a key here, please reevaluate. This situation is exactly the kind where key endorsement should be used.

**Comment by dabura667** [comment]
> key endorsement should be used.

I agree. Who do you think they should get to sign their key?
