### ISSUE TITLE
Transaction not found - Copay

### ISSUE THREAD

**Issue by Lucasbravo84** [bitpay/copay#7807]
My transaction was made on 07/01/2018 from my copay wallet to :
12vVvSi6M8WTt4dUPjkTSLRMLwFgPLPs1n
I put a small fee 0.000121
Until today, it's not present on blockchain. The transaction on my copay wallet history is "send in progress"  and on copay insight page is "transaction not found"
what was the problem? The tax?
I await answers
Tnx

**Comment by luckykcc17** [comment]
Same thing happening to me too!!!

**Comment by carlosgfranco** [comment]
Same here

**Comment by Roddy1219** [comment]
me too!!!

**Comment by tab00** [comment]
I've just experienced the same thing today.

Copay should return an error message if the transaction was not successfully broadcasted, and it should not appear as "Sending" in the transaction list. Users may not know whether they should resend with a higher fee or to wait (and the intended recipient is not going to be happy if the transaction finally disappears after days of waiting).

**Comment by gustavoguzman00** [comment]
Same situation here, had anyone received response from a copay/bitpay staff member ?

**Comment by halilayyildiz** [comment]
same thing for me... any solution ?

**Comment by gustavoguzman00** [comment]
Nothing, im trying to contact a staff member but no luck.

2018-01-11 15:25 GMT-04:00 Halil AYYILDIZ <notifications@github.com>:

**Comment by Lucasbravo84** [comment]
I didn't receive any reply from Copay Assistance but my transaction was canceled and the btc returned to the total amount
Now I wait a few days then I try to do the transaction with a normal tax

**Comment by carlosgfranco** [comment]
Hi Lucas, so I’m your case it took 4 days for the transaction to be automatically cancelled, correct?

**Comment by Lucasbravo84** [comment]
Yes

**Comment by carlosgfranco** [comment]
I can see the transaction in Insight again. I also got an email from Coinbase saying that the funds are going their way, however in Insight the transaction is still unconfirmed (perhaps 1 of the 6 confirmations were completed? No idea...)
I will wait a couple more days before I try to find alternatives like double-spending...
Anyone knows if, by opening Copay, the transaction is pushed again to the network? Maybe I need to wait without opening the app to allow the transaction to time-out?

**Comment by Lucasbravo84** [comment]
Without doing anything, the transaction has appeared and is again in the sending status. The submission date is the same and isn't in the blockchain....

**Comment by carlosgfranco** [comment]
My transaction never confirmed. After 48 hours without opening Copay, balance was back and I was able to send again with proper (higher) fees

**Comment by gustavoguzman00** [comment]
After 5 days of the transaction on processing, now i have the fund back again on the wallet. I used the economic fee, i might use a highe one when ill try to send them again.

**Comment by carlosgfranco** [comment]
Earlier this morning I tried to send the funds again to Coinbase. Again transaction not found and funds are gone.
What worries me the most is that looking up my copay wallet address in blockchain.info or insight.bitpay.com does not show any past transactions at all... but the iPhone copay app shows them.

**Comment by gustavoguzman00** [comment]
About 4 months ago i transfered without problems.

**Comment by carlosgfranco** [comment]
Ok, so my story came to an end. Fortunately. 
On this bitcoin forum https://bitcointalk.org/index.php?topic=2455333.0 I got help to accelerate the "old" transaction 2f3da8c8241fb53f9a60367416e7dbf5aa5f6974d166fb2ca20d115fe73bdba1, which has been finally confirmed, so once the BTC went to Coinbase I was able to cash out.
The "new" transaction 30f9f3fd7e08b487142bfb7b2fe1673c4c8c988d95a0d4e5cb91047628a65deb never showed up. Lucky me, as the latter was an attempt to double-spend with higher fee.
Both transaction IDs I was able to obtain by checking the link that copay opens in Insight; on an iPhone I had to click in Safari "back" and then "stop" so I could retrieve the TX ID from the URL.
Wish you all luck with your issue and I hope my experience helps you. One thing I know: I won't be using Copay anymore.

**Comment by matiu** [comment]
@carlosgfranco this has nothing to do with Copay. If you put a fee lower that is recommended by a bitcoin network, you can end up with this situation. Your TX will be unconfirmed up to 3 weeks, some nodes will have it on the mempool, others no.

**Comment by carlosgfranco** [comment]
hi @matiu, I agree that the unconfirmed transaction can be due to low fee. However, copay should create a TX ID. It is not always the case and that's what this support request was originally about.

Have a nice day.
