### ISSUE TITLE
Missing a half dozen payments

### ISSUE THREAD

**Issue by shn-tank** [bitpay/copay#7810]
I have a single user wallet that hasn't received the last few payments sent to it.

They've been confirmed a bunch, but still they don't show in my wallet.

**These 3 specifically:**

https://blockchain.info/address/1HBw7cyFSxMBYeENvWXUrhE4LMbzwcaqw5

https://blockchain.info/address/126QiT7XbJJCefaLs5XfVcDqWWjsGLVEBs

https://blockchain.info/address/1zkah8SGKFosLgNBt4EUrtPu4FoeDmyNa

All of them were sent on January 8th 2018. 

Can anyone help shed some light on this?

I have been receiving payments to this wallet for awhile now and there's never been an issue.

After I realized I was no longer receiving money in this wallet, I stopped all payments and opened a new wallet and all new payments have been coming in fine.

Thanks

**Comment by mr10008** [comment]
In your place I would install Mycelium wallet and set it up by using recovery with the same seed Copay has for that wallet and see how the transactions are displayed there.

**Comment by shn-tank** [comment]
Thanks for the information. Will do.

**Comment by harrisondel** [comment]
@shn-tank 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
