### ISSUE TITLE
Is not confirmed

### ISSUE THREAD

**Issue by golberdoria** [bitpay/copay#7815]
My transaction to the Address t1fSut1PCT8UxKZqna8wJ525LsD4vgcZJbA
Is not confirmed and not found and my funds are missing until now.

**Comment by gustavoguzman00** [comment]
Same happened to me. Do you see your transaction on the blockchain ?

**Comment by mr10008** [comment]
@golberdoria that is not a proper address so nothing is displayed on the https://blockchain.info
