### ISSUE TITLE
Every single Bitcoin CASH address created is INVALID

### ISSUE THREAD

**Issue by unixwizzard** [bitpay/copay#7817]
copay creates BTC addresses just fine, created new wallet for bitcoin cash, creation went fine, backed up the wallet, however every place I go says to the effect of "invalid address"..  tried creating several addresses but none work.

upgraded to version 3.11.1, same behaviour

guess this is a BTC only wallet

**Comment by junderw** [comment]
Google is your friend.

https://support.bitpay.com/hc/en-us/articles/115004671663-BitPay-s-Adopted-Conventions-for-Bitcoin-Cash-Addresses-URIs-and-Payment-Requests

**Comment by winchell** [comment]
UPDATE, 1/16/18: The BitPay and Copay wallets now use the BitcoinABC Cashaddr address format, starting in version 3.12.1. This article is now outdated and only applies to BitPay and Copay wallet versions before 3.12.1. https://blog.bitpay.com/cashaddr-bch-format/

**Comment by JDonadio** [comment]
Please check https://bitpay.github.io/address-translator/
