### ISSUE TITLE
Missing Bitcoin in my copay wallet

### ISSUE THREAD

**Issue by matt77unltd** [bitpay/copay#7820]
A payment of 0.045411 BTC has been received into your wallet.

See it on the Blockchain
3405 Piedmont Rd NE, Atlanta - BitPay 
bitpay.com

 After receiving that msg I went to my wallet and I saw it, then later when I try to send out it say insufficient fund, write now I can't even see any Bitcoin in my wallet this is the transaction id. 08e1bf2a943f130ca46fd4b5acc9b1ebdceb6105b410f7cfebdea66ec1ad742a

**Comment by mr10008** [comment]
https://blockchain.info/tx/08e1bf2a943f130ca46fd4b5acc9b1ebdceb6105b410f7cfebdea66ec1ad742a
it says Unconfirmed Transaction - probably because too low transaction fees.
