### ISSUE TITLE
Transaction pending - missing funds copay

### ISSUE THREAD

**Issue by gustavoguzman00** [bitpay/copay#7821]
Made a transaction to: 37wQHSiT2qbG5HKKCN7gT6Rag7rWddsHWY

10 hours and still no response. Missing funds from wallet, status: pending and no confirmation on the blockchain, cant see it.

**Comment by carlosgfranco** [comment]
Similar to our issue? https://github.com/bitpay/copay/issues/7807

**Comment by luckykcc17** [comment]
This is happening to lots of Bitpay/copay users.....company is. Or responding at all.

**Comment by carlosgfranco** [comment]
any chance you try to retrieve the TX ID? maybe then it can be accelerated. Try checking the link that copay opens in Insight; on an iPhone I had to click in Safari "back" and then "stop" so I could retrieve the TX ID from the URL. good luck getting your funds back!
