### ISSUE TITLE
When will loading BitPay debit card with BCH be available?

### ISSUE THREAD

**Issue by GHDanno** [bitpay/copay#7825]
I have BTC and BCH wallets linked to my BitPay card in the BitPay app.

When clicking on "Add Funds" in the app, only BTC is available to load the card.  How do I default to the BCH wallet instead?

**Comment by Gamboster** [comment]
Currently you can not top up your card with BCH. We are thinking about implementing that feature. But there is not yet a certain date for the launch.

**Comment by stolencatkarma** [comment]
As it stands today (jan-26th-2018) it takes 20$ to send btc to the bitpay wallet and then ANOTHER $20 to load it on the bitpay card. A total of $40.00 just to load a card is WAY too much. 

This should be top priority as your card is unusable atm.

**Comment by GoHome93** [comment]
I really don't understand why they're dragging their feet on the bch card loads. Everything about the card is useless because you can't load the card without paying ridiculous fees. Please FFS ad BCH card loads.

**Comment by writingabout** [comment]
+1 for bch top-up a higher priority please! Many people would love to default bch in the wallet. Really looking forward to this feature thank you!

**Comment by 79b79aa8** [comment]
one more vote for enabling BCH top ups. thanks for your great work!

**Comment by rhelwig** [comment]
Came here wondering the same thing. Since Blockstream's Tulip Coin (BTC) is no longer viable, we need an alternative ASAP. And Segwit has done very little to improve things, and LN is still too far away from both being available as well as what crypto is supposed to be.
