### ISSUE TITLE
Sed postinstall not cross platform compatible

### ISSUE THREAD

**Issue by kiwina** [bitpay/copay#7826]
HI, in the postinstall sed isn't cross platform compatible so anyone oin windows trying the wallet will fail

**Comment by JDonadio** [comment]
Sorry but I don't understand your issue. Can you explain it with more detail?

**Comment by Allar** [comment]
Copay's package.json uses the unix `sed` command in its `postinstall` script. `sed` does not exist on Windows.

Am trying to test on Windows and currently am having this issue (after addressing a similar problem with bauth's outdated `secp256k1` dependency.

**Comment by anxiaohe** [comment]
I have account for the  same problem,have you solved?@Allar

**Comment by BGalliotti** [comment]
Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will happy to help you.
Thanks
