### ISSUE TITLE
amazon gift card

### ISSUE THREAD

**Issue by perm22** [bitpay/copay#7833]
hello 17 hours ago i bought an amazon gift card with copay for 950 dollars (0.072378 BTC) however i did not receive the amazon gift card it has 6+confirmations please help

**Comment by DemoHam** [comment]
same happened to me except I paid $50 and did not get it

**Comment by Valochecocardo** [comment]
Me too and I send 300$. What can we do ? 👎

**Comment by kferrer** [comment]
Wish i saw this before trying to buy a gift card, because the same thing happened to me with copay a while ago, 108 usd (+39 on fees), never got the code.

**Comment by jshanaa** [comment]
Hi guys, does bitpay send your gift cards yet?

**Comment by JDonadio** [comment]
Hi guys, please read this: https://github.com/bitpay/copay/wiki/COPAY---FAQ#amazon-gift-card
