### ISSUE TITLE
Como hago para enviar BCC a otra persona, mi billetera no me esta dejando 

### ISSUE THREAD

**Issue by JackelineA** [bitpay/copay#7837]
Actualicé la aplicación en Androi  y no pasa nada, igual no me deja enviar mis Bitcoin Cash. que debo hacer para poder utilizarlos ?

**Comment by chudacontreras** [comment]
a mi me pasa lo mismo

**Comment by Gamboster** [comment]
Copay accept new ABC's addresses format for BCH, something like this: BitcoinCash:qzrdwfunndxcumjx5c93hss6n3w4g2fwfzq3k5m4fcj1, which is a new convention to prevent errors (https://blog.bitpay.com/cashaddr-bch-format/)

If you need to send to "old" addresses, and you are SURE those are BCH addresses, you can "translate" them using the BCH Translator tool: https://bitpay.github.io/address-translator/
