### ISSUE TITLE
Need help recovering bitcoins 

### ISSUE THREAD

**Issue by vapadilla** [bitpay/copay#7841]
I have not been able to access my bitcoins. It is not showing in my wallet.

**Comment by mr10008** [comment]
Before anyone can help you you have to provide more details about the problems - no one can read your thoughts directly  ;-) 
So details like: Were you able to view the balance before? Did the problem come up after the transaction? include transaction details etc.

**Comment by Gamboster** [comment]
@vapadilla You have not provided enough information, as @mr10008  said. I'll close this ticket. If for some reason you still do not see your funds, please open it again with more information.

**Comment by harrisondel** [comment]
@vapadilla 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
