### ISSUE TITLE
How do you access funds after selling bitcoin

### ISSUE THREAD

**Issue by alioily** [bitpay/copay#7844]
Hi, i purchased bitcoin a few years ago and have a copay wallet. If i wanted to convert it to an alternative currency how would I do that and how could I access the cash. I am not sure if it is linked to my bank account or credit card. I can’t find that information in my copay wallet. 
Thank you in advance.

Dg

**Comment by Gamboster** [comment]
Hello @alioily 
Copay does not link wallets or funds with bank details or credit cards.
You can move your funds freely. If you want to exchange them for another crypto currency, or convert it to fiat money, the common thing is to trade with exchanges that work in your country, or exchange person to person. You must find out on your own.
