### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by replay777** [bitpay/copay#7847]
Hello can not send a bitcoin cash to another cache address, why? Write copay only supports bitcoin cash using new version members addresses. Help

**Comment by replay777** [comment]
https://support.bitpay.com/hc/en-us/articles/115004671663-BitPay-s-Adopted-Conventions-for-Bitcoin-Cash-Addresses-URIs-and-Payment-Requests    I read it! 
Tell me how to send from your new address code to a regular address bitcoin cash

**Comment by JimNim** [comment]
Use the address translator
https://bitpay.github.io/address-translator/

**Comment by rollinglow19** [comment]
1BHxqMa1cyx36YpNynsUpYXXyguYu6Gehj

**Comment by rollinglow19** [comment]
Hi this is unrelated to this thread,but I have a testnet key i,wanted to post

**Comment by rollinglow19** [comment]
1BHxqMa1cyx36YpNynsUpYXXyguYu6Gehj

**Comment by JDonadio** [comment]
Please check this out: https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-cant-send-bch

1- Translate the "old" address into a new format and use it in the copay input field.
2- Use the prefix `bitcoincash:` before the "old" address, like `bitcoincash:1xR.....`
