### ISSUE TITLE
Restore Wallet Account

### ISSUE THREAD

**Issue by Volstagg44** [bitpay/copay#7848]
Hello, how can I restore my copay account, I had to reset my phone to factory settings and did not have the app on it anymore.

**Comment by rollinglow19** [comment]
1BHxqMa1cyx36YpNynsUpYXXyguYu6Gehj

**Comment by JDonadio** [comment]
Please check this out: https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-lost-my-wallet-or-changedamage-my-phone

**Comment by Volstagg44** [comment]
What's this
