### ISSUE TITLE
How to cancel a transaction to my own wallet to my own wallet..

### ISSUE THREAD

**Issue by ozguruz** [bitpay/copay#7849]
Hello,
I’ve just sent some of my bitcoins from my wallet to my same named wallet. It was a mistake. How can I cancel it? The fee was 7$ and in super economy. I know it is a very fool mistake but maybe there is a solution. 

Thanks for help.

**Comment by JDonadio** [comment]
Unfortunately there is nothing to do. If the transaction was broadcasted it cannot be reversed or cancelled.
