### ISSUE TITLE
Bitcoin address/url in QR code is all uppercase

### ISSUE THREAD

**Issue by DanielWeigl** [bitpay/copay#7855]
The address in the QR code in the receive tab is incorrectly all uppercase, which prevents other wallets/ATMs from scanning it.

Screenshot from a fresh installed CoPay on Android, v 3.12.1:
![image](https://user-images.githubusercontent.com/1370302/34985322-f8aec4c4-fab3-11e7-9809-1c4597259aad.png)

decodes to:
`BITCOIN:16S8BFCT6TV2YZ5TZ45U3JSTHP8EM5KZFF`

most likely introduced in:
https://github.com/bitpay/copay/blame/6de2e85e3e4b08ce594e8f739d4ee5c958ed8013/src/js/controllers/tab-receive.js#L29

**Comment by gabrielbazan7** [comment]
Thanks for the report. Working on it.

**Comment by JDonadio** [comment]
Thanks for the detailed report, we are sending a new release with the fix.

**Comment by DanielWeigl** [comment]
Thx for the quick fix - can confirm, last update fixed it.
