### ISSUE TITLE
Did not receive the bitcoin 

### ISSUE THREAD

**Issue by QuestBit** [bitpay/copay#7866]
Hi,

I transferred approximately 0.39 Btc  from copay wallet to my blockchain address yesterday evening. The coins are no longer in my wallet and they have not arrived in my blockchain account.
Please help with this issue,

Regards,

QuestBit

**Comment by QuestBit** [comment]
Another thing was after sending about an hour when I checked. There was error saying that transaction not found.

**Comment by Donaldino** [comment]
Questbit, we are facing technical glitch in our server database. We are trying to relocate the missing database that contains the send and receive info of your bitcoin. We have checked the transaction hash as well but we could not locate it only managed to identify two send-out transaction from your copay wallet which we are trying to retrieve. We will try our best to rectify this problem. We apologize for the inconvenience. Thank you.

**Comment by QuestBit** [comment]
Please do it ASAP. The recipients are making hell of a noise and because of the bitcoin price difference as well

**Comment by QuestBit** [comment]
The two send out transactions is 2 Btc and 0.38 Btc, right ?
