### ISSUE TITLE
Imported wallet copay to copay show no funds

### ISSUE THREAD

**Issue by max-doronin** [bitpay/copay#7867]
I'm trying to move a copay wallet from one Android phone to another.
I  export to QR on the source phone and scan it on the target phone. It imports successfully asking for the password that I enter, but the imported wallet shows no funds. Wallet ids are different on both phones in case that's important.

Thanks

**Comment by gabrielbazan7** [comment]
Wallet id should be the same in both phones. Let me check if it works for me

**Comment by max-doronin** [comment]
I remember the fact something was odd when I created the original wallet. I don't remember what exactly though. Still I'd expect export/import to work. Are you from the copay team? If you are and are willing to a investigate it further then please let me know. Otherwise I will just send the coins to a new wallet that I'm going to create.
