### ISSUE TITLE
Stuck on 'Loading transaction info'

### ISSUE THREAD

**Issue by paOol** [bitpay/copay#7868]
steps taken
BCH
- desktop, opened the receive tab
- mobile, scanned QR code beginning with `q`
- sent self a transaction of $0.25~ from the same wallet 
- broadcasted 

it appears in the 'Recent Activity'

I click into it, and it's stuck on Loading Transaction Info
I click into the wallet I sent from/to; It shows an infinite loading icon
the transaction does not appear in under `Recent`

My other wallets behave normally as expected.

**Comment by rastajpa** [comment]
Sorry for the delay. 

Try cleaning cache. Go to Settings -> {your wallet} -> More Options-> Transaction History and tap on 'Clear cache'. 

If you still have this problem please open this ticket again. Thanks.
