### ISSUE TITLE
Wallet "Sweep" Error...?

### ISSUE THREAD

**Issue by KeyJockey** [bitpay/copay#7870]
Hey guys... I'm cross posting this here from a post on bitcoin.com forum for their copay-forked wallet version JUST because I'm kind of in a small panic and hopefully someone here will be able to help/reassure me a little faster, LOL.

Sorry if it's not appropriate to ask bitcoin.com-version wallet questions here on the main Copay thread... and admins please feel free to delete if necessary (but, again, kinda worried here as it's a large balance at risk and I need some help to figure out what's going on with this)

Anyway... cross-post text from there, here below.

Thanks in advance for any/all replies.

---

bitcoin.com wallet "sweep" error...?

Wed Jan 17, 2018 11:17 am

I'm having a problem with a transaction I just made using the latest version of the bitcoin.com wallet.

"Sweeping" a balance from a private key at first, the transaction appeared to work and it's showing in my wallet, but still unconfirmed.

I have "use unconfirmed funds" enabled so I went ahead and did another transaction to SEND some BCH to another address.

That transaction also appeared to work, and it is in the wallet also showing unconfirmed.

HOWEVER there is nothing appearing on the blockchain for either transaction... the original "swept" address still shows the full balance (i.e. "unswept" still... untouched) and with only ONE transaction on that address (i.e. the initial "deposit" for that address, cold wallet).

It kind of appears like the wallet did not "broadcast" anything... but it THINKS it did...?

I tried also to use another wallet to sweep the original address again... but that gave an error message (somewhat frighteningly) about something like nothing available to sweep or no inputs or something like that.... even though on several block explorers the full original balance IS showing there.

Hopefully someone knows what's going on here... and I hope I have not lost these funds (it's kind of a large balance so I'm worried...)

Thanks in advance for all advice how to resolve this and get access to my BCH again.....

**Comment by KeyJockey** [comment]
UPDATE: I just realized that the bitcoin.com wallet has it's own GitHub here... duh, sorry.

I posted the above over there instead: can be deleted here if needed (or, still, anyone know what's going on with this?  It seems very weird, I'm really worried some kind of strange glitch happened here and has somehow killed my bitcoins :( ...

**Comment by JDonadio** [comment]
We didn't receive any report regarding this behavior for now, but anyways thanks for the report and of course we'll put an eye on this.
