### ISSUE TITLE
Lost 12 word....how else can i retrieve my wallet? 

### ISSUE THREAD

**Issue by munirh** [bitpay/copay#7871]
I have Visa BitPay card. They attach a CoPay wallet with your account. They try and make it easy to access your funds....try too...I transferred 2k worth of bitcoin from my Coinbase account to CoPay Wallet. The trasnfer went through just fine. When I tried to move the bitcoin over from CoPay wallet to my Visa Card attached to it, it kept giving me an error. I deleted the app and reinstalled the app (I dont know why I did this). I am running into the same issue as everyone else. I do not have the 12 words. Is there a back up of my words on my iphone some how? I have updated all my apps before and never had to resign back in. Is it possible to find the password!? Please help!

Is there anything I can do?!

**Comment by JDonadio** [comment]
If you did not made a backup, your funds are not accessible. Unfortunately without a backup your wallet cannot be restored.

**Comment by JDonadio** [comment]
https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-lost-my-wallet-or-changedamage-my-phone
