### ISSUE TITLE
Lost my Coins SMD

### ISSUE THREAD

**Issue by justship00** [bitpay/copay#7878]
I went to the machine loaded up 50 yes 50 and I didn’t receive anything not even the email I’m usually sent it their a problem smh

**Comment by JDonadio** [comment]
We have nothing to do with bitcoin machines. Contact to their support team and ask for your transaction.

For incoming transactions, the recipient wallet cannot do anything (Copay or whatever other software). The sender is the responsible for build and broadcast the transaction properly.
