### ISSUE TITLE
I transferred 0.0210553 to CoPay but it says there is only 0.021055

### ISSUE THREAD

**Issue by skyworlka** [bitpay/copay#7879]
I transferred 0.0210553 to CoPay but it says there is only 0.021055. Why is that?

Thanks.

**Comment by mr10008** [comment]
Double check by viewing on blockchain - Copay is displaying the amounts with up to 6 decimal places but on blockchain you may find the full amount displayed.

**Comment by skyworlka** [comment]
Hi,

Yes Blockchain has the full amount of 0.0210553. Am I able to transfer that full amount out of CoPay?

**Comment by mr10008** [comment]
Yes, full amount should be OK but there will be some transaction fee.
