### ISSUE TITLE
BCH weirdly "transferred" before BTC/BCH fork - cannot access my BCH within my Copay wallet

### ISSUE THREAD

**Issue by gorillaleon** [bitpay/copay#7886]
Hi,
I recently imported the copay BCH wallet for my copay BTC wallet with the public key 16eNjKQrjYJJSnjE71Afdnz3iP2JDKDpJm. Within the newly imported BCH wallet, however, an outgoing payment of -0.406747 BCH is shown on April 5, 2017 (i.e. before the fork!) to this public address (qpmedxvk4xg8zh89kugsy3f3k237r6u4qqa9cjhjn8). 

There is no corresponding BTC payment, except approx. 9 minutes earlier a BTC payment of -0.07588 BTC went to this public key (1P96PAyN1wtNknqzikncQNxPj4uAcKfaW5) - this was a payment to a restaurant that accepts BTC payments with a terminal.

With the "weird" BCH transaction of -0.406747 BCH (which I never carried out, which as I said does not have a corresponding BTC transaction, and which was clearly before the fork) I now cannot access my BCH, as they seem to be on the public address described above, which does not open with my Copay 12 private words (qpmedxvk4xg8zh89kugsy3f3k237r6u4qqa9cjhjn8).

What happened, and how can I import my BCH of 0.33086729?
Many thanks
Leon

**Comment by JDonadio** [comment]
Please use the [recovery tool](https://bitpay.github.io/copay-recovery/) and scan your BTC wallet using the `bch/livenet` chain.

**Comment by gorillaleon** [comment]
Hi it worked and the BCH were found ;) However, when I try to transfer it to the "destination address" it won't let me, as it says "Please enter a valid address".

I have tried my ledger BCH account and a friends wallet that should be able to receive BCH - but neither seems to work.

Any ideas?
Thanks!

**Comment by gorillaleon** [comment]
I just stumbled over an old post here with a similar problem.
Is it that only "new" formats of BCH addresses are allowed in the recovery tool?

BCH address on ledger: 16oP3z3XtyQJjbnaNVv8B7EgKtsqhUDyc9
Current Cash address format: bitcoincash:qqleu2ahln56hz728parvc5zmz5qfzlu7cu9sfkj9w
Legacy BitPay BCH Format: CNGGd2Pbn2Nqdjh14FF3kcrhx26FeFeREa
Legacy BCH Format: 16oP3z3XtyQJjbnaNVv8B7EgKtsqhUDyc9

**Comment by gorillaleon** [comment]
Which one would I need to use for the BCH to arrive on the ledger?

**Comment by JDonadio** [comment]
Please check the [address translator](https://github.com/bitpay/address-translator)

**Comment by JDonadio** [comment]
Oh ok, you should send to: `Legacy BitPay BCH Format: CNGGd2Pbn2Nqdjh14FF3kcrhx26FeFeREa`

**Comment by gorillaleon** [comment]
Many thanks it worked!!

Is there also a way to recover/get Bitcoin Gold + Bitcoin Diamond through Copay?

**Comment by JDonadio** [comment]
Bitcoin gold is also available in the recovery tool, diamond not.
