### ISSUE TITLE
Accidently tried to send BTC to BCH address

### ISSUE THREAD

**Issue by wblac** [bitpay/copay#7890]
Accidently tried to send BTC to BCH address - BTC have gone from wallet. Presumably transaction does not actually exist so can the BTC be recovered?

**Comment by tonyarmy** [comment]
Thank you sir


เมื่อ ศ. 19 ม.ค. 2561 เวลา 01:59 wblac <notifications@github.com> เขียนว่า:

**Comment by JDonadio** [comment]
https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-sent-bch-coins-into-a-btc-address-what-can-i-do-to-recover-my-bch-coins

The same process works in both ways, if you send BTC > BCH, you must scan your BCH wallet selecting the `btc/livenet` chain. If you send BCH > BTC, you must scan your BTC wallet selecting the `bch/livenet`chain.
