### ISSUE TITLE
Send btc from copay btc address to jaxx bch address.

### ISSUE THREAD

**Issue by ezybayz** [bitpay/copay#7891]
i have mistakenly send btc from copay btc wallet to jaxx bch wallet address.

any chance that i can recover the fund and how to so it?

thanks.

**Comment by JDonadio** [comment]
Sorry but if your recipient wallet doesn't belong to Copay or Bitpay you must contact to jaxx support team and ask they for your coins.

**Comment by ezybayz** [comment]
ok thanks

**Comment by Keensyst** [comment]
I have been working with github for two months and haven't received a
payment yet. Who do I need to speak with concerning this matter?
