### ISSUE TITLE
Transfer not conformed since more than 2 weeks

### ISSUE THREAD

**Issue by Lola8** [bitpay/copay#7895]
Hi,
I did my transfer since 12/28/2017 with low fee (1.31%) still not conformed.

https://insight.bitpay.com/tx/2cb4dac9e1bc5a2dc7fc19800c0da21af57a8025b70250fc14dedc6582a2f47f

Why? Can i cancel it?

Thank you!

**Comment by mr10008** [comment]
You have 323 Confirmations
