### ISSUE TITLE
Request: display the value of Bitcoin Cash in the fiat 

### ISSUE THREAD

**Issue by drwasho** [bitpay/copay#7897]
Currently Bitcoin wallets show the fiat value underneath the amount of Bitcoin, but this is not true for Bitcoin Cash.

**Comment by gabrielbazan7** [comment]
We are working on this right now.

**Comment by gabrielbazan7** [comment]
https://github.com/bitpay/copay/pull/7900

**Comment by drwasho** [comment]
Awesome, thanks!
