### ISSUE TITLE
Question about bitcoin-wallet-service

### ISSUE THREAD

**Issue by jackyxie** [bitpay/copay#7898]
Excuse me,
      I just setup a bitcoin-wallet-service myself, and I have a question about it.

I already have several  multisig wallet in copay, which using the default bws address. I change my own bws url to my own and reregister, but the tx history and balance shows abnormal. Does all the other partner also need to user the same bws url? Is there any method to fix this situation?

Best regards,
Jc

**Comment by BGalliotti** [comment]
Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will happy to help you.
Thanks
