### ISSUE TITLE
I can not send my Bitcoins from my Copay Wallet to the exchange

### ISSUE THREAD

**Issue by evzmanyan** [bitpay/copay#7905]
I've tried more than three times to send my BTC from my Copay wallet to the exchange Yobit.But each time my money is returned. I pointed a good miner fee (comission) (about 31%). Pls, help me to understand what is matter.

**Comment by Gamboster** [comment]
Hello @evzmanyan, sorry for the delay. What do you mean when you say "But each time my money is returned" ?
Are you sure that you are sending your funds correctly ?

**Comment by YKon2** [comment]
I have the same issue. 
The proposal has been stuck for over 24 hours and it says that "payment accepted, but not yet broadcasted". I've tried to send it again about 10 times. Every time it stops after an hour. I also updated the app. The fee is about 0.35%, is it too low? I don't know how to point it higher.
Please help.

**Comment by Gamboster** [comment]
Hi Guys, again, sorry for the delay. Could you tell me if you still have problems like the one described above? Or if it was resolved.
Regards!

**Comment by BGalliotti** [comment]
Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will happy to help you.
Thanks
