### ISSUE TITLE
Deleted Copay app and only got 11 words

### ISSUE THREAD

**Issue by Kcrng** [bitpay/copay#7906]
So basically i deleted the Copay app a few days ago to create some space on my phone, and now that i have downloaded the app again i can't log in because i only got 11 words. You need to have 12 words to log in as a security check but i lost 1 word somehow. Is there a method i can log in because i invested in Bitcoin and i got all my Bitcoins in my Copay wallet. Help me out please.

**Comment by Gamboster** [comment]
Unfortunately if you do not have the 12 words, or some other backup method that provides copay, you can not replicate your wallet.

These are the lists of words in different languages. Search for your language and, if you know in what position the missing word was, you could try one by one until you get it right. If you know how to programming, maybe you could run a script that will test the words for you.
I can not think of another solution.

https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md

**Comment by harrisondel** [comment]
@Kcrng 
if you didn't find your lost word of recovery phrase, I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
