### ISSUE TITLE
I can’t build wallet in Arch Linux

### ISSUE THREAD

**Issue by yoburtu** [bitpay/copay#7907]
Hi!,

I can’t build copay wallet in my Arch Linux box. I attach the error log.

Best regards.
[error-copaywallet.log](https://github.com/bitpay/copay/files/1649259/error-copaywallet.log)

**Comment by BGalliotti** [comment]
Hello,
**Are you still experiencing this issue?**
We look forward to hearing from you.
Regards

**Comment by BGalliotti** [comment]
Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will happy to help you.
Thanks
