### ISSUE TITLE
Still don’t quite get BTC TO Bitcoin Cash protocol??

### ISSUE THREAD

**Issue by hrw1008** [bitpay/copay#7908]
I want to send BitcoinCash from my Copay wallet to Binance exchange. I copied Binance address into Copay and it said I needed a different BCH address  say :
Copay only supports BitcoinCash using new version number addresses. 
How does one do this? I didn’t understand the support post link??? Any help here? Thanks.

**Comment by Gamboster** [comment]
Hello @hrw1008 
Copay accept new ABC's addresses format for BCH, something like this: BitcoinCash:qzrdwfunndxcumjx5c93hss6n3w4g2fwfzq3k5m4fcj1, which is a new convention to prevent errors (https://blog.bitpay.com/cashaddr-bch-format/)

If you need to send to "old" addresses, and you are SURE those are BCH addresses, you can "translate" them using the BCH Translator tool: https://bitpay.github.io/address-translator/
