### ISSUE TITLE
my anti virus won't let me install the new updated copay version

### ISSUE THREAD

**Issue by allthatmoney** [bitpay/copay#7909]
whenever i download the new version of copay and try to install it my antivirus blocks it. it says it's dangerous because it's coming from an unverified address.
is this new version been hacked? i have never had that problem in the past.

**Comment by mr10008** [comment]
I just installed the latest version without problems - avast antivirus.
But the the signature file Copay.exe.sig is corrupted so who knows, maybe the hackers did change the installer and corrupted the signature file so the users would not be able to verify it.
Last time the signature file was not even available for a longer time until I posted the request here.
I would not use the latest installer until proper signature file gets posted for downloads.

**Comment by allthatmoney** [comment]
i guess i'll stay away from this one. i already lot 40 dollars from installing bitpay about 4 months ago and i used the bitcoin address that i got when i clicked on receive bitcoins. that btc address sent my btc to someone else and bitpay said it was not even a bitcoin address that belongs to bitpay. but yet it was the btc address i received from inside my newly installed wallet. they need to fid out how these hackers are getting into gethub and put a stop to it.

**Comment by mr10008** [comment]
Switch to Mycelium

**Comment by BGalliotti** [comment]
Hello,
**Are you still experiencing this issue?**
We look forward to hearing from you.
Regards

**Comment by allthatmoney** [comment]
i have switched to the exodus wallet. it runs a lot smoother than
bitpay/copay plus it has a lot of coins you can store in it, probably about
50 coins.

**Comment by BGalliotti** [comment]
Thanks for commenting out @allthatmoney 
We are closing this thread.
Thanks.
