### ISSUE TITLE
Missing transactions in transaction history but wallet balance is correct

### ISSUE THREAD

**Issue by hpernu** [bitpay/copay#7910]
There are completed transactions missing in my list of transactions: both from the exported CSV and in the visual UI. Nonetheless, the balance is correct. I know that the the transactions have been completed because the money is seen in the other wallets and the received transaction is confirmed.

This issue affects at least a BCH wallet where there are 9 transactions in close succession. The first one being a deposit and followed by within only a few minutes by 8 withdraws. Invariably, one of the withdraws is missing.

Clearing the cache or rescanning the addresses does not help. However, this may cause the list to change so that a different withdraw is missing.  Is there a limit on how much per hour/minute/whatever Copay is able to show and export via the interface? 

The same problem affects at least Windows and Android version.

**Comment by gabrielbazan7** [comment]
Hi! if you still having this issue, please reopen the ticket. There were some refactors done regarding this in the latest versions.
