### ISSUE TITLE
Unconfirmed transaction doesn't show up at btc.com,  blockchain.info or insight.bitpay.com

### ISSUE THREAD

**Issue by superdare** [bitpay/copay#7911]
Hello,
It seems that Copay wallet didn't want to broadcast this unconfirmed transaction, I waited more than 6 hours.
In the Android wallet the transaction looks ok. I don't know what should I do, please help. 
tx: f32306dfaba849f6204a7b8869889365437f16665cd2bdd4ca83e06f8a7a90dd
destination add: 1BEd5FKZpEJMipMAkWgbWoAD7txtDEN24P
Thank you. 

![screenshot_2018-01-22-11-33-57-513_com bitpay copay 02](https://user-images.githubusercontent.com/35686030/35214784-fd26a57e-ff6a-11e7-84f5-f9333bc8aafa.png)

**Comment by BGalliotti** [comment]
Hello,
**Are you still experiencing this issue?**
We look forward to hearing from you.
Regards

**Comment by BGalliotti** [comment]
Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will happy to help you.
Thanks
