### ISSUE TITLE
Copay.exe.sig file is corrupted

### ISSUE THREAD

**Issue by mr10008** [bitpay/copay#7915]
Please upload the proper Copay.exe.sig file for the latest version again, this one is corrupted.
Thanks

**Comment by junderw** [comment]
No it's not. I downloaded it fine: Here's the SHA256 of the two files up currently, but be sure to verify the signature.

```
00faa5f3877808a11684a0348c4b545f66eca7a2ec911b3106fa88e12e326ec2  Copay.exe.sig
2f31b0f358c34462a095636fd841d2647d104c4c7def141dc52186a3e53a126a  Copay.exe
```

```
gpg: Signature made Sat Jan 20 01:02:19 2018 JST
gpg:                using DSA key 5CD600A61112CFA1
gpg: Good signature from "Copay (visit copay.io) <copay@bitpay.com>" [full]
```

Downloaded from:
https://github.com/bitpay/copay/releases/download/v3.13.1/Copay.exe.sig
https://github.com/bitpay/copay/releases/download/v3.13.1/Copay.exe

**Comment by vuduy67215** [comment]
Vào 07-02-2018 0:39, "Gabriel Masclef" <notifications@github.com> đã viết:
