### ISSUE TITLE
update problem

### ISSUE THREAD

**Issue by riyami3** [bitpay/copay#7917]
hi, i had 0.0625btc in my wallet, i updated it and now it tells me there is nothing.

**Comment by Gamboster** [comment]
Hello @riyami3 
What did you update? the Copay app?
If so, the wallets would not have to be erased. Now, if you uninstalled the previous one, you should have a backup of your wallet in order to recover your funds.
Could you explain your problem a little better?

**Comment by BGalliotti** [comment]
Hello,
**Are you still experiencing this issue?**
We look forward to hearing from you.
Regards

**Comment by BGalliotti** [comment]
Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will happy to help you.
Thanks
