### ISSUE TITLE
Missing FAQs about security

### ISSUE THREAD

**Issue by fmonts** [bitpay/copay#7927]
I think 2 very important FAQs are missing:

- Is the wallet safe against viruses on my computer/smartphone?
- Is it safe against the developers? Or they can publish an update that sends our bitcoins to themselves?

**Comment by dabura667** [comment]
1. No
2. If you aren’t compiling the app yourself, no.

**Comment by BGalliotti** [comment]
I'm closing this thread, please if you still need support, open a new one.
