### ISSUE TITLE
cannot sweep private keys from cashaddress

### ISSUE THREAD

**Issue by paOol** [bitpay/copay#7936]
https://cashaddress.org/

steps to reproduce:

- open page on desktop,
- send some bch to the bitcoin cash address
- wait 1 confirm
- Open copay on phone
- click Scan and scan the private Key beginning with 'L'
- get an error saying no funds found

Also tested with the paper wallet section. same issue.

I was able to sweep the funds using the bitcoin.com wallet however.

**Comment by imaginaryusername** [comment]
Can confirm, still have the problem. Bitcoin.com sweeps just fine. Problem also exists if you BIP39 encrypt the private key.

**Comment by cmgustavo** [comment]
It 's working for me. Could you try downloading latest version of the app (v4.6.1)? 

BTW, the private key in cashaddress.org starts with `K`.

Thanks
