### ISSUE TITLE
Purchased Amazon giftcard on bitpay but never received.  

### ISSUE THREAD

**Issue by lchaud46** [bitpay/copay#7943]
Hello, 

On 1/10/18 I purchased an Amazon gift card on my bitpay wallet but never received the gift card.  Here is the blockchain confirmations:

https://insight.bitpay.com/tx/8dd571625e57f0e0063aab60214262ee23d70a0d66334fb5dfd67c48b4665dd7

I have already sent 2 e-mails to support@bitpay and help@bitpay with no response.  See screenshots of my wallet:

![img_0367](https://user-images.githubusercontent.com/35856625/35467033-c6534eec-02d7-11e8-8b46-d2e5c9e9013b.PNG)
![img_0366](https://user-images.githubusercontent.com/35856625/35467034-c81c1f74-02d7-11e8-9156-dbc0205c0cea.PNG)

Please help

**Comment by Gamboster** [comment]
Hello @lchaud46 Sorry for the problems related to Amazon integration.
If for some reason your Amazon Gift Card is not getting the code to redeem it, please contact to the bitpay help center: https://help.bitpay.com/requestHelp, select the BitPay payment/transaction and describe your issue providing the invoice id or transaction id for your Amazon Gift Card purchase.

**Comment by lchaud46** [comment]
Gamboster, I made submission to the help center several weeks ago and have also followed up by e-mail on January 11th and January 26th.  I have received nothing but automated replies.  I have been incredibly patient and looking for some help please.  I am a widowed senior citizen and $1,000 is a lot of money for me.  This amazon giftcard was to buy birthday gifts for my grandchildren.

**Comment by bitjson** [comment]
Hi @lchaud46, thank you for your patience. We've seen a huge influx of new users in the past month, causing a backlog in support requests. I'm closing this issue here, and you should be hearing from our support team via email soon.

**Comment by lchaud46** [comment]
Hello, I have heard anything about resolving my issue.  Over a month has passed.  Why has no one addressed my issues.  I have posted all the information on this message board and have submitted the same information by email.
