### ISSUE TITLE
Can't transfer funds

### ISSUE THREAD

**Issue by stevenlopes** [bitpay/copay#7945]
Why can't I transfer my small amount of btc yo another wallet? It's being held hostage because "it's too little of an amount for fees" how about no.. if you don't want to support segwit, I don't want to support you.

**Comment by Gamboster** [comment]
This warning means that the incoming transaction is smaller than current recommended bitcoin network fee. If you try to redeem this bitcoin amount in the future, the fee required by the Bitcoin network may be higher than the amount itself.

**Comment by vuduy67215** [comment]
Vào 07-02-2018 0:40, "Gabriel Masclef" <notifications@github.com> đã viết:
