### ISSUE TITLE
Critical Security Advisory for BitPay and Copay Wallet Spending Password Users

### ISSUE THREAD

**Issue by tarcisiogripp** [bitpay/copay#7964]
I received an e-mail from hello@bitpay.com with this text:

We have discovered a private key encryption vulnerability affecting some users of the BitPay and Copay apps' spending password feature. We patched these issues in last week's updates to our wallet apps. However, if you use a spending password to encrypt your private keys, you may need to take additional action to protect your private keys.

At the end of the e-mail there is a button with this: "MAKE SURE YOUR WALLET IS SECURE". Is this e-mail trustable and is it really from copay/bitpay?

Thanks in advance

**Comment by bitjson** [comment]
Yes, and the link leads to this blog post: https://blog.bitpay.com/wallet-spending-password-vulnerability/
