### ISSUE TITLE
Bitcoin Gold/12 phrase from Bitpay

### ISSUE THREAD

**Issue by oj89** [bitpay/copay#7987]
Hi guys,

I'm trying to get my BTG from my Bitpay account. I only got one issue. I do have access to my Bitpay account. But I don't have the 12 word phrase thats used to get the BTG of it. Is it possible to reset the 12 word phrase or is there any other/new way to get the BTG of the Bitpay wallet?

Thanks in advance!

**Comment by Gamboster** [comment]
The 12 words can not be reset.
If you still have your wallet imported into Copay, you can go to Settings -> Wallets settings -> Backup -> Here you can see the 12 words of the selected wallet.

Please make a backup of your words before you lose your wallet for any reason. That way you'll keep your funds safe.
