### ISSUE TITLE
TOTAL HORSESHIT COPAY

### ISSUE THREAD

**Issue by jbarks** [bitpay/copay#7991]
Ive made transactions from copay to binance with no issues until today.. I now randomly have a spending password? So basically, my funds that I have just put in there are fucked because of you assholes.
and, no, I dont have kids that can come and fuck around, its not on my mobile phone and this is on a desktop pc in my home. 

How do I randomly have a god damned password now?

**Comment by Gamboster** [comment]
Please, read this link: https://support.bitpay.com/hc/en-us/articles/115003004403-I-forgot-my-wallet-spending-password-What-can-I-do-

**Comment by jbarks** [comment]
Doesnt help me one bit, because its requiring a fucking spending password to delete, restore from backup or to enter in my phrase pass.

**Comment by gabrielbazan7** [comment]
The spending password is not require to delete the wallet.

**Comment by jbarks** [comment]
You got me, I am just here for a good laugh.

**Comment by jbarks** [comment]
So this password is supposedly stored on my computer, If i go digging around the application files it should be in a log somewhere?

**Comment by gabrielbazan7** [comment]
no
