### ISSUE TITLE
authorization code forgotten personal wallet

### ISSUE THREAD

**Issue by Jenny87x** [bitpay/copay#8010]
Hello,

I have a big problem. I want to send money from Copay to my friend but I have forgotten my personal wallet authorization code. I have the 12 words, can somebody help me how to avoid or to change? There's a lot of money (at least for me) on it. Thank you for your help. Greetz

**Comment by bitjson** [comment]
What do you mean by `wallet authorization code`?

If you have your 12 word backup, you should be able to import it into any version of Copay.

(Closing, since this isn't a bug report or feature request.)
