### ISSUE TITLE
When I restore my wallet, it gives me a different BTC address

### ISSUE THREAD

**Issue by dse-2017** [bitpay/copay#8013]
I still have my Bitpay wallet installed on my old machine, version 3.9.1 Windows.  When I installed the latest version 3.14.0 of Bitpay on a new machine, and import the wallet using the 12 words and same spend password, it gives me completely different wallet address.   My impression was that it should give me access to the exact wallet address that I had entered, which I want to do because it is my mining wallet.

Thank you.

**Comment by gabrielbazan7** [comment]
https://github.com/bitpay/copay/wiki/COPAY---FAQ#why-my-address-keeps-changing

**Comment by Ronarkdel** [comment]
@dse-2017 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
