### ISSUE TITLE
About wallet 

### ISSUE THREAD

**Issue by burakcan34** [bitpay/copay#8019]
Hi,
 After i deleted my copay wallet from my phone, i took BTC. But now when i download copay wallet, i can not see it and my wallet has another btc adress. Can you help me please?
Burak Can

**Comment by gabrielbazan7** [comment]
Did you import your wallet using the 12 words ?

**Comment by burakcan34** [comment]
Thank you, i did. There is no problem.
Burak Can

13 Şub 2018 2:02 ÖS tarihinde "Gabriel Edgardo Bazán" <
notifications@github.com> yazdı:

Did you import your wallet using the 12 words ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bitpay/copay/issues/8019#issuecomment-365260377>, or mute
the thread

**Comment by Ronarkdel** [comment]
@burakcan34 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
