### ISSUE TITLE
Fee percentage is misleading because it includes the fee

### ISSUE THREAD

**Issue by timothyej** [bitpay/copay#8020]
On the *Confirm* screen, the fee percentage is based on the sending amount including the fee. However, the text says "X% of the sending amount". This is misleading since the fee is not included in the amount shown at the top of the view.

I'm happy to submit a pull request for this if you agree that it should be changed.

### How to reproduce

1. In Copay, press *Scan* or *Send*
2. Enter a bitcoin address or scan a QR code
3. Enter a small amount to send (it needs to be small enough to make the fee have a significant change on the percentage)
4. Press the next button
5. Verify that the entered amount is displayed under the *Sending* label
6. Note that the fee percentage is calculated from the sending amount with the fee included

### Expected behavior

I would expect the fee percentage to be calculated from only the sending amount. E.g. if I want to send `0.0001` BTC and the fees are `0.0002` BTC, I would expect the fee percentage to be `200%` of the sending amount. But now the app would display `67%`, which is misleading.

### Screenshot

![img_4200](https://user-images.githubusercontent.com/721091/36062416-8127a6c4-0e6c-11e8-99cd-66f127b58383.png)

*Note that although the fees are bigger than the sending amount, the text still says "61.83% of the sending amount".*

**Comment by Gamboster** [comment]
Hello @timothyej. Thanks for the observation.

I believe that both ways of seeing it are correct. The current one is based on the total value of the transaction that you will send, while the one you propose is based on the amount you want to send, without including the fee. If the calculations are correct, both will reflect the same information basically.
And I think that changing that now can confuse users, who for so long have been handled with the same percentage calculation.
But, no doubt, we will consider your advice and discuss.

Regards!

**Comment by timothyej** [comment]
Hi @Gamboster,

I totally understand. How about just changing the text to `X% of the total amount`, i.e. replacing `sending` with `total`? It would be less disruptive and make the sentence less ambiguous.

**Comment by timothyej** [comment]
Thanks! Love the app btw, keep up the good work 🍻

**Comment by Gamboster** [comment]
The change was merged, you can see it reflected when we release Copay version 4.
https://github.com/bitpay/copay/pull/8039

So I will close this issue. Regards
