### ISSUE TITLE
Mining. New Bitcoin address in the Copay.

### ISSUE THREAD

**Issue by silegonchet** [bitpay/copay#8021]
Hello.
I found that my bitcoin address had changed. I do mining (NiceHash pool) at the old address. Will the funds come to my Copay wallet if NiceHash makes a payment to the old address? If not, what should I do?

**Comment by gabrielbazan7** [comment]
https://support.bitpay.com/hc/en-us/articles/115003004423-Do-I-still-own-old-bitcoin-addresses-
