### ISSUE TITLE
Bitcoin transferred from copay to blockchain wallet yet to receive till now. 

### ISSUE THREAD

**Issue by QuestBit** [bitpay/copay#8023]
It has been almost 3 month now. And the issue is not resolve. The ticket was close without a solution. The last message mentioned by you guys saying that you will get back to us after your system glitch. And you didn’t get back to us. The recipient is making hell of a noise at us because of copay transfer we’re stuck. Our reputation is at stack. This is going out of hand now. We need a response from you guys.

**Comment by QuestBit** [comment]
Can we get back the Btc ? It’s been 5 months now. What’s wrong with the network ? We are running a business here. The recipient that we sent to has not received the Btc.

**Comment by BGalliotti** [comment]
Hello,
**Are you still experiencing this issue?**
We look forward to hearing from you.
Regards

**Comment by QuestBit** [comment]
Yes we are still yet to receive the bitcoin that was send out from copay wallet. It’s been more than 4 months now. The recipient was very angry at us. Please resolve this issue ASAP

**Comment by BGalliotti** [comment]
Hello @QuestBit  We are sorry you have had this bad experience.
So we can further help, please provide as many of the following details as you can:

- Current device used
- Current operating system for the device
- Current version of the wallet used
- Any log files containing error details
- Error screenshot
- Steps to replicate
- BitPay Wallet ID - To get your Wallet ID, open your BitPay application, then go to Settings > Wallets & Integrations > More Options > Wallet Information.

Regards

**Comment by QuestBit** [comment]
Current device used- iPhone 7
Current operating system for the device - iOS
Current version of the wallet used - v4.2.0
Any log files containing error details - It was written transaction was not found.
Error screenshot - (2 bitcoin missing) 

https://insight.bitpay.com/tx/4c37091528a48b64505bcc293b62005e32b414b57dd7c32e84aa57dd3e79e080

(0.39 bitcoin missing)
https://insight.bitpay.com/tx/03b018698f1f82ca933bba80790971c45470089d5151d19441570842da65fdfb

BitPay Wallet ID - f0c1d277-4f73-4f0f-8afc-0e5ed5d90496

**Comment by BGalliotti** [comment]
Hello @QuestBit

Thanks for reaching out to us.

**As you can see:**
- https://insight.bitpay.com/tx/4c37091528a48b64505bcc293b62005e32b414b57dd7c32e84aa57dd3e79e080

has 29342 confirmations and the funds are already spent (that is the "S" in parentheses).

- https://insight.bitpay.com/tx/03b018698f1f82ca933bba80790971c45470089d5151d19441570842da65fdfb

same as the first transaction, and has 21684 confirmations.

- You have sent those funds using a Copay/Bitpay wallet. 
- The funds have reached the destination address. 
- They have been successfully confirmed (typically a transaction is considered confirmed with 6+ confirmations, your transactions have 21600+ confirmations).

Whoever owns the destination/destinations addresses, **has already spent the funds, so they cannot tell you they did not receive the funds.**

**On our end, everything is OK, funds were in a Copay wallet, they were sent, and they were successfully received.**

If you have sent the funds to a wrong address, unfortunately, there is nothing we can do.

Here is the wallet report, as you can see, the first and 3rd transactions are the ones you mention:

```
* Wallet info
  ID: f0c1d277-4f73-4f0f-8afc-0e5ed5d90496 Coin: btc
  LIVENET 1-of-1 [BIP44 P2PKH] wallet (status: complete)
  Created on: Mon Aug 21 2017 02:15:52 GMT-0300

* Balance
  Total: 0.00000000 btc (0.00000000 btc locked)
  Confirmed: 0.00000000 btc (0.00000000 btc locked)
  Available: 0.00000000 btc (0.00000000 btc confirmed / 0.00000000 btc unconfirmed)

* No pending tx proposals.

* Main addresses (not including change addresses)
  [Mon Aug 21 2017 02:50:52 GMT-0300] 1Dg4XALCH4rKHuUoh6hbtjagzsRMtQ4MVj (m/0/0)
  [Thu Aug 24 2017 23:49:28 GMT-0300] 1GcmWUNNpMBY6zPRyJbATRAo2WjGa9Zsm2 (m/0/1)
  [Thu Aug 24 2017 23:55:26 GMT-0300] 1KcxqXVKYijC3JCHmAbnytTDcExzLvfTzz (m/0/2)
  [Thu Aug 31 2017 06:49:37 GMT-0300] 199YChdKpx8kddMWkqvMKQbZKpJwV8cgo7 (m/0/3)
  [Thu Aug 31 2017 06:53:10 GMT-0300] 1CfSfTtJK3NHPNBg2A6gEJtwscvC5QiJj (m/0/4)
  [Sat Sep 09 2017 13:04:33 GMT-0300] 19u9JELZswfBKjtqPUqfvwL4HnK3fWyfbh (m/0/5)

* Tx history
  [Tue Jan 16 2018 05:17:47 GMT-0300] 03b018698f1f82ca933bba80790971c45470089d5151d19441570842da65fdfb => sent 0.40098788 btc (fee/kb 0.00225445 btc) (21683 confirmations)
  [Mon Jan 15 2018 01:46:56 GMT-0300] b29015ccb6ae53edba917145b381469f47660ea7bda37c2251179e6852d514c1 => sent 0.10000000 btc (fee/kb 0.00424174 btc) (21862 confirmations)
  [Thu Nov 30 2017 00:45:32 GMT-0300] 4c37091528a48b64505bcc293b62005e32b414b57dd7c32e84aa57dd3e79e080 => sent 2.00000000 btc (fee/kb 0.00162322 btc) (29342 confirmations)
```

Please let us know if you have any additional questions.
Kind regards.

**Comment by QuestBit** [comment]
Hi there,
The wallet address is correct. The address of recipient would not go wrong because the earlier transaction went through and after few minutes another transaction took place to the same address but the bitcoin was not received. I can show you the recipient wallet account. This is the recipient’s wallet ID: 
650a6640-25d7-4023-b70c-51bdd793350a
In fact, I’ve contacted blockchain wallet as well. But there’s no reply from their end. How do we suppose to resolve this ?
Thank you. 

Regards,
QuestBit 


On Tuesday, June 5, 2018, 9:39 PM, BGalliotti <notifications@github.com> wrote:


Hello @QuestBit

Thanks for reaching out to us.

As you can see:
   
   - https://insight.bitpay.com/tx/4c37091528a48b64505bcc293b62005e32b414b57dd7c32e84aa57dd3e79e080

has 29342 confirmations and the funds are already spent (that is the "S" in parentheses).
   
   - https://insight.bitpay.com/tx/03b018698f1f82ca933bba80790971c45470089d5151d19441570842da65fdfb

same as the first transaction, and has 21684 confirmations.
   
   - You have sent those funds using a Copay/Bitpay wallet.
   - The funds have reached the destination address.
   - They have been successfully confirmed (typically a transaction is considered confirmed with 6+ confirmations, your transactions have 21600+ confirmations).

Whoever owns the destination/destinations addresses, has already spent the funds, so they cannot tell you they did not receive the funds.

On our end, everything is OK, funds were in a Copay wallet, they were sent, and they were successfully received.

If you have sent the funds to a wrong address, unfortunately, there is nothing we can do.

Here is the wallet report, as you can see, the first and 3rd transactions are the ones you mention:
* Wallet info
  ID: f0c1d277-4f73-4f0f-8afc-0e5ed5d90496 Coin: btc
  LIVENET 1-of-1 [BIP44 P2PKH] wallet (status: complete)
  Created on: Mon Aug 21 2017 02:15:52 GMT-0300

* Balance
  Total: 0.00000000 btc (0.00000000 btc locked)
  Confirmed: 0.00000000 btc (0.00000000 btc locked)
  Available: 0.00000000 btc (0.00000000 btc confirmed / 0.00000000 btc unconfirmed)

* No pending tx proposals.

* Main addresses (not including change addresses)
  [Mon Aug 21 2017 02:50:52 GMT-0300] 1Dg4XALCH4rKHuUoh6hbtjagzsRMtQ4MVj (m/0/0)
  [Thu Aug 24 2017 23:49:28 GMT-0300] 1GcmWUNNpMBY6zPRyJbATRAo2WjGa9Zsm2 (m/0/1)
  [Thu Aug 24 2017 23:55:26 GMT-0300] 1KcxqXVKYijC3JCHmAbnytTDcExzLvfTzz (m/0/2)
  [Thu Aug 31 2017 06:49:37 GMT-0300] 199YChdKpx8kddMWkqvMKQbZKpJwV8cgo7 (m/0/3)
  [Thu Aug 31 2017 06:53:10 GMT-0300] 1CfSfTtJK3NHPNBg2A6gEJtwscvC5QiJj (m/0/4)
  [Sat Sep 09 2017 13:04:33 GMT-0300] 19u9JELZswfBKjtqPUqfvwL4HnK3fWyfbh (m/0/5)

* Tx history
  [Tue Jan 16 2018 05:17:47 GMT-0300] 03b018698f1f82ca933bba80790971c45470089d5151d19441570842da65fdfb => sent 0.40098788 btc (fee/kb 0.00225445 btc) (21683 confirmations)
  [Mon Jan 15 2018 01:46:56 GMT-0300] b29015ccb6ae53edba917145b381469f47660ea7bda37c2251179e6852d514c1 => sent 0.10000000 btc (fee/kb 0.00424174 btc) (21862 confirmations)
  [Thu Nov 30 2017 00:45:32 GMT-0300] 4c37091528a48b64505bcc293b62005e32b414b57dd7c32e84aa57dd3e79e080 => sent 2.00000000 btc (fee/kb 0.00162322 btc) (29342 confirmations)

Please let us know if you have any additional questions.
Kind regards.

**Comment by BGalliotti** [comment]
Hello @QuestBit 

Thanks for reaching out to us.

We cannot check that wallet ID since it is not a Bitpay wallet.

The transaction has properly gone through, and if the destination address is right, they have received the funds, and there is nothing to argue about.

We have provided you with enough evidence, that should be more than sufficient.

If there is something else we can do for you, please let us know.
Kind regards.

**Comment by jamesscookk** [comment]
Hood funds please hacked emote os

**Comment by BGalliotti** [comment]
@jamesscookk  Please explain your inquiry

> Hood funds please hacked emote os

**Comment by Ronarkdel** [comment]
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
