### ISSUE TITLE
can't update wallet:403

### ISSUE THREAD

**Issue by blinov02** [bitpay/copay#8038]
I have 403 problem.I can't sent my bitcoins.and I can't backup my wallet.when I try to backup it tells me that my wallet is not registered in bitcore

**Comment by blinov02** [comment]
can someone help me!

**Comment by blinov02** [comment]
it looks like someone stole my money!

**Comment by mohammadrafigh** [comment]
I get 403 on Linux client too. I cannot create or import any wallet.
after checking console I found that Bitpay has restricted access for Iranian users :-1:

**Comment by gabrielbazan7** [comment]
Hi! if you still having issues, please re open this ticket. You could always import your wallet using this 12 words in another software wallet or you could use the recovery tool to move the funds to another wallet https://bitpay.github.io/copay-recovery/

**Comment by Retul15** [comment]
Use VPN
