### ISSUE TITLE
I m stupid please help me 

### ISSUE THREAD

**Issue by crudi1964** [bitpay/copay#8065]
I have no idea how happened but when I opened wallet I wrote only 11 security words: what I can do now that I changed phone ?

**Comment by asad523** [comment]
01675914423

**Comment by crudi1964** [comment]
Sorry what does this number mean ?

**Comment by gabrielbazan7** [comment]
Here you have a list of the possible words https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md. Maybe someone here could help you with an script to cover all the possibilities.

**Comment by crudi1964** [comment]
Thank you It s impossible for me to find The correct one and first of all in The right position
Maybe someone could suggest me a different system

**Comment by gabrielbazan7** [comment]
Hi ! if you still having issue, re open a new ticket asking for help explaining your problem or take a look to reedit maybe someone has a similar problem and could help you.

**Comment by Ronarkdel** [comment]
@crudi1964 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
