### ISSUE TITLE
Is there a reason why BCH card loads aren't activated?

### ISSUE THREAD

**Issue by GoHome93** [bitpay/copay#8067]
It's been a few months since the announcement of the BCH wallet in Bitpay..but still we don't have BCH card loads. Is there a reason we don't have it yet? I'm tired of paying the ridiculous fees..

**Comment by asad523** [comment]
https://bwscash.bitcoin.com/bws/ap

**Comment by gabrielbazan7** [comment]
We are working on this.

**Comment by GoHome93** [comment]
Thank you
