### ISSUE TITLE
BCH Stuck in Copay Multisig Wallet Using Ledger Nano S

### ISSUE THREAD

**Issue by ledgeruser** [bitpay/copay#8080]
@matiu @blueknight02

After many months this is still not solved and I still cannot access my BCH through Copay.  I have 2-of-2 multisignature setup.  Copayer 1 is on my computer using Ledger Nano S for signing.  When I hit "Duplicate for BCH" in this copay wallet nothing happens.  No old transactions populate, no current balance populates.  When I go to Settings-->Bitcoin Cash I can view my full balance.  Copayer 2 is on my phone and I can view balance and create a payment proposal to move the BCH to a new address (out of copay), but the payment proposal will not populate for Copayer 1 so I cannot approve the payment proposal and complete the transaction.  My BCH are stuck on Copay.  I'm starting to get concerned that these are lost forever.  Does anyone have any suggestions on how I can get my BCH out of copay multisig?  Thank you so much in advance for any help provided!

**Comment by ledgeruser** [comment]
Just figured it out.  

Closed.

**Comment by Mansarde** [comment]
How did you resolve the problem?
