### ISSUE TITLE
spending password copay

### ISSUE THREAD

**Issue by Carlos127** [bitpay/copay#8087]
I have a problem with my btc wallet copay.
I'm trying send btc from my wallet to a exchange, but the app request a spending password. I never set up a spending password.
Without the password my bitcoin is essentially frozen without a way to transfer.

**Comment by JohnJJJ** [comment]
If you still own your recovery phrase just delete and then reinstall the app. As long as you have your keys to your wallet backed up or the recovery phrase you are ok. Once you’ve reinstalled, by default there is no password so you’ll be able to spend your funds.

**Comment by gabrielbazan7** [comment]
@Carlos127 when you create the wallet the app gives the option to set the spending password. Do you remember this ?

**Comment by sadpandas** [comment]
I just lost $150.00 My Lastpass didn't save my generated password and apparently you need it to backup your wallet.

**Comment by challme28** [comment]
I have the same issue with the desktop app. I created a new wallet, transferred 0.042 BTC then left it without a back up. Days later I tried to back it up but the prompt for my "spending password" showed up, which I haven't set up.

**Comment by Ronarkdel** [comment]
@Carlos127 

I can recover your wallet , i have cracked spending pin before. if you want need help send me email : anywalletrecovery@gmail.com
