### ISSUE TITLE
Recovering Bch 

### ISSUE THREAD

**Issue by JohnJJJ** [bitpay/copay#8088]
I’m using the latest version of Copay on my phone. I don’t have the “bitcoin-cash support” tab in settings instead it just says “bitcoin cash”. I would like to recover Bch from the fork last year. I’m certain I had btc in there at the time

**Comment by gabrielbazan7** [comment]
Tap in "bitcoin cash", then in "Duplicate for BCH"

**Comment by pietjebelkees** [comment]
I've sent bch to my btc copay wallet, when I tap settings > bitcoin cash it says that my bch are there, the exact amount. When I tab on duplicate a bch wallet is created but no sign of the bch, I already tried the recovery tool. It says 0 bch. I already checked the transaction, it has been confirmed 2 days ago.

Could anyone please help me? It's a descent amount and I've worked hard for it :(

**Comment by pietjebelkees** [comment]
This is insane, copay isn't fixing this? I just sent another 0.1 to the address as a test, transaction was completed. But also the 0.1 is lost now. When I click on duplicate it shows 0.0 bch, scanning the wallet results in 0.0 bch to. But before I click on duplicate it says 8.23 bch?

**Comment by BGalliotti** [comment]
For further info follow #8460

Thanks, regards.

**Comment by Ronarkdel** [comment]
@JohnJJJ 

I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
