### ISSUE TITLE
Payment Accepted but not yet broadcasted: Error Querying the Blockchain

### ISSUE THREAD

**Issue by Ostseebengel** [bitpay/copay#8091]
Yesterday and today I tried to send my BTCZ to another wallet but it was not possible. The transaction was created but not broadcasted. I tried several times to resend the transaction proposal but without success. I also deleted the transaction proposal several times and created a new transaction with the same result.
![screenshot 6](https://user-images.githubusercontent.com/36732577/36551269-806b78e8-17f7-11e8-9d4f-b32dc9adad10.png)
![screenshot 7](https://user-images.githubusercontent.com/36732577/36551275-833ed060-17f7-11e8-9860-b7668a4e65db.png)
![screenshot 8](https://user-images.githubusercontent.com/36732577/36551280-85b414d6-17f7-11e8-90c4-a1e6b1f34cc7.png)
![screenshot 9](https://user-images.githubusercontent.com/36732577/36551284-884e8e56-17f7-11e8-913d-c123570ca9d8.png)
![screenshot 10](https://user-images.githubusercontent.com/36732577/36551287-8abbb9c0-17f7-11e8-8115-d33989f968de.png)

**Comment by gabrielbazan7** [comment]
Sorry, this is BitPay/Copay Wallet GitHub issues. We don't support BTCZ. Post your issues here instead: https://github.com/bitcoinz-pod/bitcoinz-wallet/issues
