### ISSUE TITLE
BCTZ Wallet Issue

### ISSUE THREAD

**Issue by robash982** [bitpay/copay#8115]
Need help with BTCZ wallet.

I have been mining on zpool for a couple days. Set up a new BTCZ wallet to receive funds. First couple deposits worked great, however, I didn't know the address automatically changed in the wallet. Now zpool has sent a few hundred coins to the old address and they are not showing up. Is there any way to fix this?

**Comment by stompingyaya** [comment]
กระเป๋าของผมยุที่ไหน
