### ISSUE TITLE
Duplicating BCH ends up in 0 BCH

### ISSUE THREAD

**Issue by pietjebelkees** [bitpay/copay#8118]
Hello,

I’ve sent about 12 BCH to my copay BTC wallet, when I navigate to -> settings -> Bitcoin Cash the exact amount of BCH is displayed and I can click on Duplicate. When I click on duplicate it a BCH wallet is created with 0 BCH.

I’ve used the recovery tool, ends up in 0 BCH
I’ve checked the transactions, transaction completed with confirmations
I already used the recovery seed to open the wallet on another device, But nothing helps

Could someone please help me? This is 50% of my savings.

Thanks

**Comment by pietjebelkees** [comment]
Hello?

**Comment by Gamboster** [comment]
Hello @pietjebelkees . Sorry for the delay. If what you describe is correct, here are the options to recover your BCH:
1) Check this out: https://github.com/bitpay/copay/wiki/COPAY---FAQ#i-sent-bch-coins-into-a-btc-address-what-can-i-do-to-recover-my-bch-coins

2) Or also you can create a new BCH wallet, using the backup (the 12 words) from the BTC wallet, and you will have access to the BCH.

3) Another option: Go to settings -> Bitcoin Cash -> Choose the BTC wallet -> Duplicate for BCH

If you think your balance may not be showing right, try rescanning your funds:
Settings -> Wallet Settings -> More Options -> Wallet Addresses -> Scan addresses for funds

**Comment by pietjebelkees** [comment]
Wallet id BTC wallet: 9aebeb6c-5234-45ca-af43-a27822bb591f

Wallet id BCH wallet that is created: 34632bd2-5fef-49ea-9944-a90b7a6ca364

Transaction ID of the 8.399 BCH: 552efda01c9efe3bf019ecc53ef57524da86ff28b34aafbaa944e09e81d2fb0c

Transaction ID of the 0.21 BCH: 964dbe6ab202b690b25936366a2df44e4255ae8b2479a9abc2bb8e2597c3640d

Can’t find the transaction ID of the other 0.1 BCH is acting weird it says 10 BCH but here is the link: https://bitinfocharts.com/bitcoin%20cash/address/1BCWeSohZRYgtWXg9kMFp9t3nT66vkkEtn

Thanks

**Comment by pietjebelkees** [comment]
Any word?

**Comment by pietjebelkees** [comment]
Hello??

**Comment by pietjebelkees** [comment]
Thanks for the great help and quick responses, NOT

What a shitty support, I lost $11.000 because these guys don’t know how to fix bugs in their bitpay and copay wallets.

**Comment by gabrielbazan7** [comment]
We review your issue, give us some time to come to a conclusion

**Comment by pietjebelkees** [comment]
Thank you

**Comment by pietjebelkees** [comment]
Hello?!!

**Comment by pietjebelkees** [comment]
Come on support this issue is created 10 days ago and I want my coins back

**Comment by pietjebelkees** [comment]
WHO EVER IS READING THIS DON’T USE COPAY OR BITPAY IF YOU HAVE EITHER ONE OF THESE WALLETS TRANSFER YOUR COINS INMEDIATELY TO ANOTHER WALLET. 

COPAY STOLE ALMOST 9 BCH OF ME AS YOU ARE READING THIS YOU CAN SEE THAT THE SUPPORT ISN’T RESPONDING NOR HELPING AT ALL. YOU HAVE BEEN WARNER

**Comment by pietjebelkees** [comment]
WARNED*

**Comment by pietjebelkees** [comment]
Man can anybody just help me this f**king sucks

**Comment by pietjebelkees** [comment]
Hello?!

**Comment by pietjebelkees** [comment]
Fuck you man fucking bitches I’ll spread the word that you guys are scammers you fucking idiots

**Comment by pietjebelkees** [comment]
Just keep ignoring me that’s good for your karma :)

**Comment by matiu** [comment]
Hello,  I will not respond this thread while there are insults on it, you may create a new ticket if you want and it will be reevaluated.

matías.

**Comment by Ronarkdel** [comment]
@pietjebelkees 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
