### ISSUE TITLE
Since update to version 3.14.2 on android copay hangs on splash screen

### ISSUE THREAD

**Issue by tokth** [bitpay/copay#8122]
On my Samsung S4 copay hangs on the splash screen since I updated to 3.14.2. I tried also NOX emulator with the newest version and it also hangs with the splash screen. I removed version 3.14.2 and installed version 3.14.1 the app started as normal. Then update to 3.14.2 and it hangs again in splash screen. 
I have not tested this on the Samsung S4 only on NOX emulator because I am afraid that my wallet is lost if I delete the newest version on my S4.

**Comment by Gamboster** [comment]
That error is known and we already managed to reproduce it. We are working on a fix that will solve it. We will post a new update as soon as we can. Thanks for the report.
By the way, as long as you have the correct backup of your wallet (The 12 words for example), you should not worry about uninstalling the app. Then you can import your wallet again. Regards

**Comment by tokth** [comment]
Thank you for the info, but my problem was that I have lost my backup seed from the wallet. 

For people with the same problem I have managed to get the app running again. 
What I did was downgrading to version 3.14.1 with the command  

   # pm install -r -d copay-3.14.1.apk 

from a root-terminal. After that the app started up and I could get my backup seed again. I have now written it down and will keep it in a safe place just for the next time.

Again thank you very much for your fast answer. Awesome support/feadback.

**Comment by Gamboster** [comment]
@tokth , a new version of Bitpay was released, in which the problem you reported should be fixed. Update it and try again. Regards!

**Comment by tokth** [comment]
New version 3.15.1 installed and all is okay.  Looks like this problem is solved. 
Again thanks for your worked and help. Great team.
