### ISSUE TITLE
BitCoin locked in my wallet

### ISSUE THREAD

**Issue by WernerObri** [bitpay/copay#8127]
Wallet-Id f4001d241-4416-450a-8c49-26c3e4f4d9a9

Why are 1,563201 BTC locked in my wallet?
I do not have any open transactions?

pls. investigate and send a feedback
kind regards
Werner Obritzberger

**Comment by pasinduchamod** [comment]
what happen , what app you use ??

**Comment by berkka** [comment]
I have the same issue using bitpay ios wallet.  Have you found a solution yet?

**Comment by gabrielbazan7** [comment]
Please read https://github.com/bitpay/copay/wiki/COPAY---FAQ#why-creating-a-transaction-proposal-lock-my-balance-and-is-significantly-higher-than-the-proposal-amount

**Comment by berkka** [comment]
Thank you for your response,  i am confused as it is a brand new wallet, no transactions other than the initial deposit of bitcoin.  Is there a way to unlock the balance.

Thanks

**Comment by gabrielbazan7** [comment]
What do you mean by lock ? could you share some screenshots with me ?

**Comment by berkka** [comment]
after depositing btc into wallet I attempted to make a btc payment which stated failure to get response from server, below is screenshot of the lock I mean.

![img_1729](https://user-images.githubusercontent.com/36989681/36899169-d42bb9ba-1e15-11e8-9197-58f05fa66423.jpeg)

**Comment by pasinduchamod** [comment]
do you make some back up ??

**Comment by berkka** [comment]
yes

**Comment by gabrielbazan7** [comment]
Could you check if you have a pending transaction proposal in your wallet ? Also, upgrade to the last version 3.15.1

**Comment by berkka** [comment]
I still have pending transaction which is now out of time, shall i delete it?  
 I am on version 3.15.1

**Comment by gabrielbazan7** [comment]
Yes ! your funds are locked for that transaction, try to re broadcast or deleted and do it again

**Comment by gabrielbazan7** [comment]
@WernerObri send me a screenshot from the same view that berkka sent, so I could help you

**Comment by berkka** [comment]
Ok, just deleted transaction and then attempted to send a new one, Server issue again??
![img_1730](https://user-images.githubusercontent.com/36989681/36899576-985ec1f0-1e17-11e8-921b-7c4d27a7725f.jpeg)

**Comment by gabrielbazan7** [comment]
Could you confirm you are in version 3.15.1 ?

**Comment by berkka** [comment]
yes

![img_1731](https://user-images.githubusercontent.com/36989681/36899942-3d4f5458-1e19-11e8-8b2d-12f7b7452703.jpeg)

**Comment by gabrielbazan7** [comment]
Thanks for the detail information. We will check your issue.

**Comment by berkka** [comment]
So there is no fix at this time?

**Comment by gabrielbazan7** [comment]
No. I'm sorry

**Comment by berkka** [comment]
Okay, so how/when do i get this resolved?

**Comment by SACBALLZ** [comment]
waiting for this too, hopefully value doesnt doesnt go down by the time this is fixed

**Comment by pasinduchamod** [comment]
try with backup

**Comment by WernerObri** [comment]
In my sotuation there was a pending transaction
Deleted this and everything ok
An additional option is to delete the cache
You can do this 
Settings - personal wallet - additional options - transaction history - delete cache

Hopefully this helps you too

**Comment by botcoin101** [comment]
Hi guys just wondering if you can advise me how to fix the following issue: I have 1 BTC in my wallet on my Galaxy S8 Bitpay app. I am trying to sell my BTC on my linked Coinbase account, as I have many times before, but this weekend it is saying, "connecting to coinbase", then, "error. Unknown error." I have asked both Bitpay and Coinbase for support but that might take a while! The only change I have made since the last time I sold BTC is I increased the security on my Coinbase due to having funds in there and releasing those funds to my Bank acc. Would this make a difference to selling BTC on the app? I also looked at what happens when I try to buy BTC. It says "Access token is invalid". Does anyone have any ideas whats gone wrong?

**Comment by pasinduchamod** [comment]
Can you send some screen shot of yoir error

**Comment by pasinduchamod** [comment]
Hello @berkka  . Could you provide us more information about your wallet?
Your wallet id (Of the wallet from which you are trying to send funds): Settings -> Your wallet -> More options -> Wallet information -> Wallet id
The device on . and your back up code,
And the Android/ iOS version of your device.

Thank you.

**Comment by Ronarkdel** [comment]
@botcoin101 
@berkka 
I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
