### ISSUE TITLE
Can't send to payment proposal "server response could not be verified"

### ISSUE THREAD

**Issue by JulianDF** [bitpay/copay#8140]
When I try to use bitpay to "purchase with bitcoin" on verious sites, a payment proposal is generated, but not executed. instead, I receive the following error message: 
"could not send transaction - 
server response could not be verified"

The same happens if I try to purchase an Amazaon giftcard through the app.
Normal send works.

Issues on iphone os 11.2.6
On MacOS High Sierra 10.13.3 it seems to work for now. 

What's going on?

**Comment by nechtmarrie** [comment]
i'm having the same issue on all my devices, even those i just restored on from a backup.

**Comment by JulianDF** [comment]
from my desktop it seems to work (MacOS High Sierra 10.13.3)

**Comment by nechtmarrie** [comment]
Hmm i havent tried on my desktop, tho i saw the bitpay app was just updated so i guess this is a bug in the latest release?

**Comment by JulianDF** [comment]
Could be,
I installed on mobile yesterday, and there seems to be no record of this issue, so maybe it has something to do with recent updates.

**Comment by JulianDF** [comment]
Anyways, unsettling.

**Comment by nechtmarrie** [comment]
Bitpay on windows 10 indeed works, i however did not upgrade to the lastest version yet.

**Comment by gabrielbazan7** [comment]
Update the app to the most recent version v3.15.1

**Comment by jojo2225** [comment]
I am on v3.15.1 and am still getting this issue. Any fixes?

**Comment by gabrielbazan7** [comment]
Working on this

**Comment by jojo2225** [comment]
Thanks :) 👍

**Comment by SACBALLZ** [comment]
I am having the issue as well. Just installed app yesterday so should be on latest version

**Comment by cmgustavo** [comment]
Please, upgrade to latest version 3.15.2 and try again.

Thanks for report.

**Comment by SACBALLZ** [comment]
It worked, impressive customer service thank you

**Comment by pietjebelkees** [comment]
@gabrielbazan7 respond to my issue man
