### ISSUE TITLE
When I try to buy things it says server response could not be verified

### ISSUE THREAD

**Issue by GoldenGamerBro** [bitpay/copay#8152]
I've tried deleting the payment proposal and sending it again but it just says  server response could not be verified. I have a 1/1 account.

**Comment by SACBALLZ** [comment]
Same problem, just trying to spend my little bit of bitcoin and its been a HUGE pita, makes me wonder if its worth my time mining

**Comment by cmgustavo** [comment]
Please, upgrade to latest version 3.15.2 and try again (if it doesn't work, remove payment proposal and try again).

**Comment by leighellishtx** [comment]
I'm getting the same thing. Version 3.15.2 isn't the current iOS version - 3.15.1 is. Does anyone have a fix?

**Comment by GoldenGamerBro** [comment]
The update just showed up a few days ago for me and it works now

**Comment by JoeDeMoeFoe** [comment]
Me too. Wht can I do? How do I roll it back?

**Comment by Gamboster** [comment]
Hello @JoeDeMoeFoe, What we recommend as developers is to keep the application as up-to-date as possible. We are constantly solving bugs and trying to improve, prioritizing the safety of the user first and foremost. 

I will close the ticket for now, please if someone remains having problems open a new one. Regards!
