### ISSUE TITLE
Issue topping up card - COULD NOT CREATE INVOICE - RATE LIMITED

### ISSUE THREAD

**Issue by opentoe** [bitpay/copay#8153]
When I try to top up card, which I've done hundreds of times, now I get an error saying "COULD NOT CREATE INVOICE, RATE LIMITED". So I now I cannot add funds to my card. Maybe some of the devs can take a look, since this is the entire reason why I use this program/card.
Thanks.

**Comment by Gamboster** [comment]
Hi @opentoe . 
I'm sorry for the delay, do you still have the problem you mentioned? If so, we will try to help you

**Comment by BGalliotti** [comment]
Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will happy to help you.
Thanks.

**Comment by opentoe** [comment]
Here we go again. Getting this rate limited error again. And the last time I created an invoice was 3 days ago. Everytime I try to top off a card I always get nervous because it now ends up a 50/50 chance it will work. I've lost quite a bit of money having to sit on Bitcoin and just wait until I can top off my card.

**Comment by BGalliotti** [comment]
Hello @opentoe 
Thanks for reaching out to us.

Please write to the Bitpay support: https://help.bitpay.com/requestHelp
Our representatives are going to address your inquiry there.

We would appreciate your patience.

Thanks in advance, Kind regards.
