### ISSUE TITLE
bugs newest version. 4.5 bitcoin.com wallet. contact list / open in wallet redirect

### ISSUE THREAD

**Issue by gimmethatfix** [bitpay/copay#8155]
contact list entry cant be deleted.
open in wallet redirect nit working with android.

opens two  dailpads on oin request.

https://www.reddit.com/r/btc/comments/81set9/how_to_set_up_a_bitcoin_cash_address_to/?utm_source=reddit-android

**Comment by Gamboster** [comment]
This is not the bitcoin.com repository, this is the Copat / BitPay app repository.
If you are talking about Copay or BitPay app, then a new version of the wallet was released. Please, update it to the latest version and try again. If any error persists, create a new ticket and we will try to solve it. Regards!
