### ISSUE TITLE
BitPay Amazon Gift Card lost

### ISSUE THREAD

**Issue by luiscb1** [bitpay/copay#8156]
I paid for the Amazon gift card, yet they just took my coin and provided no gift card at all. I went to "My Card," and there's nothing. I asked for help thx your asisten.

**Comment by EthanKRUnity** [comment]
Im having the exact same problem i sent about 38 dollars in bitcoin and got nothing.

**Comment by luiscb1** [comment]
in the service nothing respond ahhhh wait....

**Comment by Gamboster** [comment]
Hi guys, I'm so sorry for the delay in responding. Did you read the Copay FAQ?
https://github.com/bitpay/copay/wiki/COPAY---FAQ#amazon-gift-card

Please follow the steps described in that link to raise the corresponding claim to the team specialized in this topic.
