### ISSUE TITLE
Help re Money lost between copay and coinbase 

### ISSUE THREAD

**Issue by mjmess01** [bitpay/copay#8169]
I tried to sell bitcoin from my Personal Copay Wallet to be deposited in my Coinbase account. However, the transaction did not go through because "price falls over the selected percentage." There is a button entitled, "Remove transaction." However, nothing happens when I click it. 

At this point, the money did not make it to my Coinbase account and has not been returned to my CoPay Wallet. 

CoPay has no customer service email or phone number. Rather, they have this apparently unmonitored site. If any one can offer help, I would greatly appreciate it.

**Comment by cmgustavo** [comment]
Please, check that your funds are in your Coinbase Account and sell it manually through Coinbase if you still want to sell. The message "price falls over the selected percentage." means that the pricing of Bitcoin get over your selected percentage before selling. It 's a preventive action to avoid that price raising more than you expected (that could happen if the transaction takes long time to confirm).

**Comment by mjmess01** [comment]
The funds are not in my Coinbase account.

The funds are not in my Co-Pay Account.

 

On March 1, 2018, I tried to “Sell Bitcoin (Coinbase) -.006384 BTC.” (First Attachment).  When I click on that transaction, I see the Second Attachment.

 

When I click on “coinbase” (third attachment), it shows “-.00638409 – Error” (Fourth Attachment). When I click the fourth attachment, I get the screen shown on the fifth attachment which shows “Status Error.” There is a button to “remove transaction.” However, nothing happens when I click it.

 

So, I tried to send money from CoPay to Coinbase. The funds were removed from copay and appear to never have made it to Coinbase. However, the funds were not returned to my account. 

 

Where are the funds? 

 

Thank you,

Mike

 

 

          

Big Firm Experience. Small Firm Attention.

Michael Messinger

Law Offices of Michael Messinger, PLLC

6135 Park South Dr. – Suite 510 

Charlotte, NC 28210 

Office: 704-609-4277

 

CONFIDENTIALITY NOTICE: This electronic mail transmission has been sent by a lawyer. It may contain information that is confidential, privileged, proprietary, or otherwise legally exempt from disclosure. If you are not the intended recipient, you are hereby notified that you are not authorized to read, print, retain, copy or disseminate this message, any part of it, or any attachments. If you have received this message in error, please delete this message and any attachments from your system without reading the content and notify the sender immediately of the inadvertent transmission. There is no intent on the part of the sender to waive any privilege, including the attorney-client privilege, that may attach to this communication. Thank you for your cooperation.

**Comment by mjmess01** [comment]
Also, as you can see from Attachment 6, .00638409 BTC were supposedly deposited in my Coinbase account on March 1st. However, these funds are not and have never been in my account.  

 

Thank you,

Mike

 

___________________________

 

The funds are not in my Coinbase account.

The funds are not in my Co-Pay Account.

 

On March 1, 2018, I tried to “Sell Bitcoin (Coinbase) -.006384 BTC.” (First Attachment).  When I click on that transaction, I see the Second Attachment.

 

When I click on “coinbase” (third attachment), it shows “-.00638409 – Error” (Fourth Attachment). When I click the fourth attachment, I get the screen shown on the fifth attachment which shows “Status Error.” There is a button to “remove transaction.” However, nothing happens when I click it.

 

So, I tried to send money from CoPay to Coinbase. The funds were removed from copay and appear to never have made it to Coinbase. However, the funds were not returned to my account. 

 

Where are the funds? 

 

Thank you,

Mike

**Comment by mjmess01** [comment]
Issue resolved. I did not realize that I had a second coinbase account. That is where the funds went. Thank you for your help.
