### ISSUE TITLE
Error at confirm - server response could not be verified

### ISSUE THREAD

**Issue by calebro** [bitpay/copay#8172]
Been trying to send funds using copay from iPhone using latest app version downloaded 3/5 - keep getting "Error at confirm - server response could not be verified" - when i click ok it shows request is timing out but all details in request are correct. if i try to retry "slide to pay" it shows funds are locked by pending spend proposals. What can I do I need to send funds today?

**Comment by cmgustavo** [comment]
Try to remove the pending proposal in order to unlock the inputs.

**Comment by cmgustavo** [comment]
Also upgrade to Copay v3.15.2 before to try again

**Comment by Gamboster** [comment]
Due to the lack of response I will change it as solved. Please, if necessary, reopen it.
Regards.
