### ISSUE TITLE
502

### ISSUE THREAD

**Issue by grigorii163** [bitpay/copay#8180]
What is it error 502?

**Comment by Gamboster** [comment]
Hello @grigorii163 
Could you specify the problem a little more? Where do you got that error ? Maybe upload an image?

**Comment by grigorii163** [comment]
the error appeared because of problems with the Internet. already everything works well. tnk
--
Отправлено из Mail.Ru для Android пятница, 09 марта 2018г., 21:49 +03:00 от Gabriel Masclef  notifications@github.com :
