### ISSUE TITLE
https://github.com/bitpay/copay/releases/tag/v3.15.2

### ISSUE THREAD

**Issue by TraceyForsman** [bitpay/copay#8200]
![bitpay download 030718](https://user-images.githubusercontent.com/36748506/37126845-d7a19748-2240-11e8-8854-65b6e2138d87.JPG)

Update won't download when I click on the title.  Do I have to download each (all) files individually?

**Comment by cmgustavo** [comment]
Which platform are you using? If you have:

* Linux: download Copay/BitPay-linux.zip
* Windows: Copay/BitPay.exe
* MacOS: Copay/BitPay.dmg

The other files (`.sig`) are used to verify the downloaded file is correct. https://github.com/bitpay/copay#how-to-verify-copay-signatures

**Comment by TraceyForsman** [comment]
Thank you!
Sent from Mail for Windows 10
