### ISSUE TITLE
expired time reply on my bitpay wallet

### ISSUE THREAD

**Issue by juliuswoods** [bitpay/copay#8202]
please can anyone help me with a solution on how i can stop the "time expired" i get from bitpay app wallet each time i try to send fund to my skrill account

**Comment by Gamboster** [comment]
Hello @juliuswoods 
Could you specify the problem a little more? Maybe upload an image with the error?

**Comment by Gamboster** [comment]
Due to the lack of response I will close the ticket. Please, if necessary, reopen it.
Regards.
