### ISSUE TITLE
You can't sweep a paper wallet without an annoying prompt to buy bitcoins

### ISSUE THREAD

**Issue by Codingale** [bitpay/copay#8226]
![RETARD](https://user-images.githubusercontent.com/6324853/37243597-3e9973fc-244a-11e8-97cb-56d45cab9a13.png)

_I won't be monitoring this issue._

**Comment by dabura667** [comment]
Yes you can. Paper wallet sweep is in Settings, not Send.

**Comment by Gamboster** [comment]
As Dabura said, sweep a paper wallet is through the scan. But you must have a wallet to which you will send the funds

**Comment by Codingale** [comment]
You still can't access it, also my edit didn't go through. I checked all menu settings.
