### ISSUE TITLE
doesnt work with my computer?

### ISSUE THREAD

**Issue by aspentharealist** [bitpay/copay#8228]
i downloaded bitpay and bitcore.exe im on a new windows 10 pc but it says that it cant run on my pc??any ideas?

**Comment by gabrielbazan7** [comment]
Hi! sorry for the delay in the response, if you still having issues, could you copy the error you get here, please ?

**Comment by BGalliotti** [comment]
Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will happy to help you.
Thanks.
