### ISSUE TITLE
### WARNING: Chrome App will not longer be supported > move to firefox app

### ISSUE THREAD

**Issue by treakiandroid** [bitpay/copay#8245]
### WARNING: Chrome App will not longer be supported

is written when i want to install the chrome app. Why do i want to install it, to dont mess the 8GB card of my linux based arm-book (mobile computer with arm processor, the only way to get 10h of battery and still not as heavy as a box of stones) with another 100MB (much to big) application. So if there is already everything in need within the browser and google thinks to disable the grate feature to build up on this, why not switch to a firefox app. Its even more free and will work then also on firefox phones ;)

regards

**Comment by treakiandroid** [comment]
oh no, i take back everything just written, lookes like they are closing down to: https://wiki.mozilla.org/Marketplace/FutureofMarketplaceFAQ

what to do what do to ;(

**Comment by treakiandroid** [comment]
or maybe you could build it as an https://developer.mozilla.org/en-US/Apps/Progressive ??

**Comment by bitjson** [comment]
If you'd rather not use the desktop version, you can always clone this repo and run it in a web browser yourself. Just follow the instructions in the Readme 👍
