### ISSUE TITLE
scanning bitcoin cash private key doesn't work

### ISSUE THREAD

**Issue by bchtips** [bitpay/copay#8258]
wallet assumes BTC, says funds not found

**Comment by zynbi** [comment]
zyn

Vào 1:04 Th 7, 17 thg 3 2018 BCH Tips <notifications@github.com> đã viết:

**Comment by Khoroyar** [comment]
The QR code in the application is recognized by the QR scanners as a string containing the word "BITCOIN:" at the beginning of the address and letters only of the upper case.
If the purse address is case sensitive, it will be wrong in any case.

**Comment by Khoroyar** [comment]
Sorry, fixed in 3.15.2, just need to upgrade to the latest version
