### ISSUE TITLE
Insufficient funds for fee + rate limit

### ISSUE THREAD

**Issue by growtechknow** [bitpay/copay#8265]

**Comment by cmgustavo** [comment]
Sorry for delayed reply. What operation are you trying to do? Sending bitcoin, top up the card or another?

**Comment by growtechknow** [comment]
Well, it's still doing the inssuficient fund on my Desktop app on windows 10, I'm having to shift the funds to different wallets to get it to work which is paying you guys more money in fees. Very irritating and inconvenient, when we want to move our money to your wallet it is for a purpose more than likely to cash out, don't hold our funds or be a thing of the past.

**Comment by growtechknow** [comment]
Durring peak times, whatever times, there is no way I have inssuficent funds for withdrawl. Period, fix this issue please. This is not sustainable
