### ISSUE TITLE
I NEVER SET A COPAY WALLET SPENDING PASSWORD

### ISSUE THREAD

**Issue by Belkodon** [bitpay/copay#8267]
I NEVER SET A COPAY WALLET SPENDING PASSWORD.

I installed the COPAY WALET APP on my iPhone in december 2017.
Back then I didn´t have problems to send or receive BTC or any currency.

I activated the "touch ID security" ( for login & spending )

I never looked at the "12 word recovery phrases", 
since I could do that at anytime later, ...

NOW THERE IS A "SPENDING PASSWORD" OPTION
WHICH IS SUDDENLY ACTIVATED – NOT BY ME ! ! !

THE FACT THAT IT´S ACTIVATED PREVENTS ME FROM BEING ABLE :
> TO SEND MY BTC
> TO LOOK AT THE "12 WORDS BACKUP PHRASE"

WTF !
--------------
--------------
> IS THERE A WAY TO DOWNGRADE TO AN OLDER VERSION OF COPAY WALLET ?
( IN ORDER TO GET RID OF BEING ASKED FOR A PASSWORD THAT I NEVER SET ? )
> WHY CAN´T I JUST ACTIVATE GOOGLE AUTHENTICATOR FOR COPAY ?
TO GET AROUND ...

<img width="445" alt="bildschirmfoto 2018-03-19 um 16 51 33" src="https://user-images.githubusercontent.com/7950439/37606505-e6bad8bc-2b95-11e8-91fe-07c677ff8464.png">
<img width="462" alt="bildschirmfoto 2018-03-19 um 16 51 55" src="https://user-images.githubusercontent.com/7950439/37606506-e70a8efc-2b95-11e8-8b35-add5dc0e30d8.png">

**Comment by sadpandas** [comment]
I know your pain. The password protection is forced on yet it says I have to backup my phrase first before I can enable it. No password means I cant back it up.  

![36962082-55c76216-200b-11e8-95ab-76382833c928](https://user-images.githubusercontent.com/37060576/37734573-354df5c8-2d11-11e8-94b2-cf7f8b64e23b.png)

**Comment by cmgustavo** [comment]
The App now prevents to receive bitcoin until backup is completed. If you have an old wallet with funds (and also have the words to restore), try to remove it and restore again with your words and remember to set a spending password at import time.

**Comment by Belkodon** [comment]
A) I NEVER MADE A BACKUP       –––– >   SO I DONT HAVE MY 12 WORD PHRASE
B) I NEVER SET A SPENDING PASSWORD NEITHER  –––– >   CAUSE THAT STUPID "OLD
SCOOL LEGACY" FUNCTION HAS BEEN INTEGRATED " L A T E R "
C) I NEVER WAS ASKED TO SET A SPENDING PASSWORD


> SO WHY AM I ASKED TO ENTER SPENDING PASSWORD   " N O W - S U D D E N L Y
"  A F T E R  3   M O N T H ? ? ?
> I COULD USE THE COPAY APP WITHOUT ANY PROBLEM : B E F O R E  ? ? ?
  ( I could send and receive without any password popup. )

> WHY CAN A SOFTWARE CHANGE AND STEAL MY MONEY ? ? ?

- - - -
PROGRAMMING IS ABOUT LOGIC THINKING.
WHY CAN´T  PROGRAMMERS THINK LOGICAL BEFORE THEY   " T E S T "     THEIR
FUNCTIONS OR APPS IN REAL LIFE SITUATIONS ? ? ?
- - - -

> I HAVE EVIDENTLY BEEN TECNICALLY ENTRAPPED.
THE COPAY APP IS EVIDENTLY TRASH RIGHT NOW.
- - - -








2018-04-06 15:33 GMT+02:00 Gustavo Maximiliano Cortez <
notifications@github.com>:

**Comment by Belkodon** [comment]
I EXPECT THE " SPENDING PASSWORD FUNCTION " POPUP TO BE BE REMOVED
AND BE REPLACED WITH THE FAMOUS
" GOOGLE AUTHENTFICATOR "

AMEN

2018-04-06 18:35 GMT+02:00 J. St. <joachim.stevens@gmail.com>:

**Comment by johnsonrose** [comment]
I can recover your wallet if you want need help  send me email : anywalletrecovery@gmail.com

**Comment by Belkodon** [comment]
> I can recover your wallet if you want need help send me email : [anywalletrecovery@gmail.com](mailto:anywalletrecovery@gmail.com)

I guess it´s not worth your time since there is only a small amount of BTC (atm worth 25 EUR) left on the wallet.

**Comment by johnsonrose** [comment]
@Belkodon 
no problem, send me details, i can still do first stage of recovery on it

**Comment by Belkodon** [comment]
How would that wallet recovery work, since I don´t have the private key... ?

**Comment by Belkodon** [comment]
Obviously I have the Copay-Wallet installed. 
I can start the app and then I can try to access the BTC.
Then I get a fucking pop-up asking for a password.
