### ISSUE TITLE
Purchased BTC with address and now address is changed

### ISSUE THREAD

**Issue by Grambo112233** [bitpay/copay#8270]
I haven't got my BTC however the company stated they cleared the funds and the BTC should be on it's way. I see the address is different now for my wallet. I am wondering where the BTC is. As it's been several hours and I don't see the funds.
Can you check my wallet to see if any postings have been made today to send BTC to my wallet? 
I am at work and don't have time to look through all of the questions. 
Can you help with this?
grambo112233@gmail.com
Thank you

**Comment by BGalliotti** [comment]
Is this issue already solved?
The address you are talking about is just one of the infinite addresses a wallet can have.
Could you provide us your wallet ID so we can check it out.

Regards.

**Comment by Grambo112233** [comment]
Thank you for replying.
.the issue was resolved and few weeks ago.

thank you,
Graham

**Comment by BGalliotti** [comment]
You're welcome @Grambo112233 
We are closing this thread, please if you still need support, open a new one, we will happy to help you.
Thanks.
