### ISSUE TITLE
Lost Copay wallet but have the Co-payWallet Id and BTC transaction

### ISSUE THREAD

**Issue by rhcisme** [bitpay/copay#8272]
Hi.  I set up a Copay wallet.  Copay did not send me the 12 word recovery phrase and it automatically set up a security password which I didn't request.  One of the blogs recommended deleting the wallet and then reinstalling which I did.  I thought I had the 12 word phrase but don't.   I do have the wallet id and Extended Public Key (which I took a screen shot of) and a copy of the transaction from Coinbase showing which address it was sent to.  Is there  anyway to recover this.  I can't find a backup and Copay never requested I back up.  Pretty frustrated and would appreciate any help.

**Comment by BGalliotti** [comment]
Hello,

There is no way to recover the wallet without the 12 word recovery phrase.
The backup and encrypt password are set up by the user, the app does not do this automatically.

With the wallet ID we can just retrieve some wallet info, but not the wallet itself or the words.
Public keys let you generate addresses, not more than that.

**Comment by johnsonrose** [comment]
@rhcisme 
I can recover your wallet if you want need help  send me email : anywalletrecovery@gmail.com
