### ISSUE TITLE
Two same applications in market.

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [bitpay/copay#8273]
https://play.google.com/store/apps/details?id=com.bitpay.wallet
https://play.google.com/store/apps/details?id=com.bitpay.copay

Same description, same link to github, same version. What is the difference?

**Comment by cmgustavo** [comment]
BitPay includes the BitPay Debit Card (Visa) integration for top up dollars with bitcoin.

**Comment by c-e-p-x-u-o** [comment]
It MUST be explained in the app description!
