### ISSUE TITLE
Can't make backup password 

### ISSUE THREAD

**Issue by Nimitay** [bitpay/copay#8288]
Every time I try to make one I get sent in a loop. First it makes sure I know Noone is watching, then about screenshots. I enter my password first and then it just sends me back to make sure I have no one watching.

**Comment by gabrielbazan7** [comment]
The spending password is the password you set at creation time ( you could do it later also ) to encrypt your wallet. You need to enter it correctly to do the backup.

**Comment by Nimitay** [comment]
Thank you I thought I needed a new password
