### ISSUE TITLE
BCH money transfer

### ISSUE THREAD

**Issue by udai001** [bitpay/copay#8293]
I sent money on BCH
However, it is not listed in the transaction.
Please solve it.

**Comment by matiu** [comment]
Can you share a TX id or wallet address so we can check it?

**Comment by BGalliotti** [comment]
Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will happy to help you.
Thanks.
