### ISSUE TITLE
BCH transaction not showing up on blockchain and stuck on "sending funds".

### ISSUE THREAD

**Issue by MashaScream** [bitpay/copay#8299]
Alright, so I just sent about 0,02 BCH to an address.

Shortly after, I sent all the remaining funds of my other BCH wallet to the same address.

Both transactions show up as "Sending funds". However, when I inspect the address I sent them to on Blockchain and my own address, there aren't any new transactions shown up.

This is impossible because, as I said, it shows on my Copay wallet as being sent. And I did send it, I have proof of it on my Copay screen.

**Comment by MashaScream** [comment]
![screenshot_2018-03-24-01-28-48-568_com bitpay copay](https://user-images.githubusercontent.com/6126691/37858279-1d016d08-2f03-11e8-93c1-455b7f59e608.png)

**Comment by cashaddressio** [comment]
The same thing happened to me.  Its something with the change address.  I even went so far as to view the change address on the last successful transaction.  I took the wallet seed and browsed through the generated addresses from m'44/0/0 , but could not find the change address that the wallet sent it to.
I hope you and I are not at a loss.   This issue must be resolved ASAP.

**Comment by udai001** [comment]
The same thing happens to you as I am. I sent money from yesterday night copay, but it is Transaction Not Found even in the morning. This is a problem to be solved as soon as possible.

**Comment by MashaScream** [comment]
Now my transaction has disappeared from the Copay app as it had never happened.

It is a minimal amount, but I’m sure that if this has happened to multiple people, the final amount could potentially be huge.

If this isn’t a code issue, and even if it is, we are on legal ground to sue the developers of the app. Seeing how seldom they check their GitHub, it makes me think they wouldn’t care.

I am skeptical and think Copay is indeed stealing from its users. Money doesn’t get lost. Let’s see how far this goes and if there’s multiple people affected, we can file a legal complaint.

**Comment by johnkks** [comment]
Same issue, hope they can notice it. ((((

**Comment by bigboybiggs** [comment]
I also am experiencing the exact same problem where I sent approximately $750 bch and it’s been stuck in sending mode but never actually sending. My transaction also does not show up on blockchain

**Comment by udai001** [comment]
Support is too late We have right to sue

**Comment by bigboybiggs** [comment]
Why hasn’t copay suppost responded or assisted any of the issues yet?

**Comment by MashaScream** [comment]
I got my BCH back on my wallet again after more than a day.

My guess is Copay's code isn't working properly and all BCH transactions are being dropped out of the mempool and returned to you.

**Comment by udai001** [comment]
Does the remittance history also disappear?

**Comment by mungobedford** [comment]
I've got the same problem.  I tried sending 0.05 BCH yesterday to my HitBTC exchange address and it's just stuck at  "Sending funds"... and today I tried sending 0.110524 BCH and it is also stuck at "Sending funds".

My BCH has gone from my Copay BCH Wallet, but they do not appear on the block-chain at https://bch-insight.bitpay.com/ - it just comes back with "Transaction Not Found " - and the BCH has not arrived at my exchange address.

Can someone from Copay support please look into this ASAP.  I was happy with Copay until these issues.

**Comment by MashaScream** [comment]
Sounds like Copay just can’t code for shit when it comes to BCH.

Time to switch to a more reliable wallet. Wouldn’t be surprised if they fucked up this big on BTC as well.

**Comment by udai001** [comment]
Have you solved this problem already?

**Comment by csolinger** [comment]
No

**Comment by bigboybiggs** [comment]
I am also having the same problem with my bch. It's very disappointing for CoPay lack of response and way of handling such issues.

**Comment by BGalliotti** [comment]
Hello,
**Do you still need support with this issue?**
We look forward to hearing from you.
Regards

**Comment by BGalliotti** [comment]
Hello,

We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will happy to help you.

Regarding BCH recovery please refer to #8586

Thanks
