### ISSUE TITLE
BCH Transaction Not Found (Urgent!!)

### ISSUE THREAD

**Issue by johnkks** [bitpay/copay#8300]
Hello Copay,

I have sent two funds today shows attached below. And the status are both stuck in Sending and can not find in blocks even. Please fix it and I hope the funds won't be lost.

Regards.
![2018-03-24 8 16 37](https://user-images.githubusercontent.com/4078244/37863898-3a97ec9a-2fa1-11e8-8597-175fc4ddd474.png)
![2018-03-24 8 15 47](https://user-images.githubusercontent.com/4078244/37863899-3acad876-2fa1-11e8-8ac3-cabb73bd07a7.png)
![2018-03-24 8 15 34](https://user-images.githubusercontent.com/4078244/37863901-3b087b36-2fa1-11e8-89c0-e22269b874c7.png)

**Comment by johnkks** [comment]
The funds was returned back to the wallet. What should I do for now? Need some help.

**Comment by BGalliotti** [comment]
You can try sending the funds again.

Make sure you have the proper fee setting so the transaction does not take too long

**Comment by johnkks** [comment]
Had tried many many times. I had given up and used electron-cash instead. I won't lose anymore due to the copay transfer issue. (((
