### ISSUE TITLE
Tried sending bch yesterday and it’s still stuck on sending and does not show on blockchain. 

### ISSUE THREAD

**Issue by bigboybiggs** [bitpay/copay#8301]
One of the times I checked to see the bch had been processed, there was a small button that said “network error” next to the failed bch transaction

**Comment by bigboybiggs** [comment]
![9bf1c2fe-a7c8-41d1-9c2b-d0a62e050acb](https://user-images.githubusercontent.com/37738313/37865001-8ff476e0-2f33-11e8-823d-b16079b13717.png)
![79f6a29b-f481-454c-97a2-4091dfd8801c](https://user-images.githubusercontent.com/37738313/37865002-9020d6c2-2f33-11e8-8580-93b387504ee0.png)

**Comment by udai001** [comment]
Have you solved this problem already?

**Comment by bigboybiggs** [comment]
No, the issue is still the same. This is horrible. I have no access to my money and the matter isn’t even assigned to someone yet. It’s been several days and no action by copay or communication

**Comment by bigboybiggs** [comment]
NOPE been without my $$ for a week

**Comment by bigboybiggs** [comment]
Is there any tech support? Why hasn’t tech addressed this matter yet?

**Comment by matiu** [comment]
@bigboybiggs could you try the recovery tool to access your funds?  The tool is at https://bitpay.github.io/copay-recovery/
you need your backup phrase to access it.
