### ISSUE TITLE
Amazon gift card not received 

### ISSUE THREAD

**Issue by malcolm0056** [bitpay/copay#8302]
I pay 32$ for an amazon gift card money was taken and confirmed over 10 days  but no card yet

**Comment by matiu** [comment]
Hi, I am very sorry for the delay, can you share the address or transaction id so we can check it?

**Comment by malcolm0056** [comment]
https://bitpay.com/invoice?id=HeM41WWgnUwnp7rjAYNTMC&v=2&purchaserKey=PojZxfGQyWGvywgW8KRqgsgtoy2Chkj5mEy7vLWdTtXkJRMZtCwSXBRGwBM14exBwkS7UYJS5RRMr8xPT4SwvQ1BGxZ5XGWwLweX8kPMgGcosm5sRMv4sXd5PMLPxMvBi1C1UQAnLYx2gAPnnG2BEADcnDg4GhczikXqptqsNEcjo3j

**Comment by Gamboster** [comment]
Hello @malcolm0056.

Whenever you have problems like this with the Amazon Gift Card, you can follow this procedure found in our FAQs: https://github.com/bitpay/copay/wiki/COPAY---FAQ#amazon-gift-card

You can go doing it if you want. Anyways, with the transaction id that you passed, I will escalate your claim to the specialized team.

**Comment by malcolm0056** [comment]
https://insight.bitpay.com/tx/0da3c023f9cb38d7a144da639be2b292864a6d33484356c7088b09644a497d19

**Comment by BGalliotti** [comment]
Hello,
We are re-organizing all the support tickets.
Please if you still need support, do it directly through bitpay here: https://help.bitpay.com/requestHelp
Thanks.

**Comment by malcolm0056** [comment]
Help

**Comment by malcolm0056** [comment]
No what should i do??

**Comment by BGalliotti** [comment]
@malcolm0056 Request them help [here](https://help.bitpay.com/requestHelp). They will properly address your issue.
