### ISSUE TITLE
do not import wallet ( after reinstalling windows )

### ISSUE THREAD

**Issue by VahtangKyiv** [bitpay/copay#8304]
After reinstalling windows, the wallet is not imported, 

wallet - t1W1BjvJE6VwUS5UNXNBGk4WCxsSVmGBeoR

After entering 12 words nothing happens

![387](https://user-images.githubusercontent.com/37780011/37878727-0b077ace-3076-11e8-9ee1-affef454045a.png)
the password I enter also does not help

**Comment by VahtangKyiv** [comment]
please write me a link to the purse which is in the screenshot, maybe I downloaded the wrong one ...

**Comment by cmgustavo** [comment]
Sorry MyBitcoinZ is not an App supported by BitPay

**Comment by johnsonrose** [comment]
@VahtangKyiv 
I can recover your wallet if you want need help  send me email : anywalletrecovery@gmail.com
