### ISSUE TITLE
Transactions not found

### ISSUE THREAD

**Issue by CodersBrothers** [bitpay/copay#8323]
I'm checking something weird. Copay wallet, Bitpay Insight and Blockchain is showing different details. For Example: Copay is showing as not confirmed a transacction with more than 10 confirmations in Insight.

**Comment by CodersBrothers** [comment]
Electron Cash say that the refund address not is an own address. I used the method ismine("address"). Very weird!

**Comment by cmgustavo** [comment]
Sorry for delayed reply, the transaction has been confirmed? Maybe it was a networking issue or something that we need to verify if problem persist. 

Thanks.
