### ISSUE TITLE
BCH balance shows as 0 on copay after duplicating 

### ISSUE THREAD

**Issue by steevan01** [bitpay/copay#8341]
Like many others I have transferred a paper btc wallet from pre August 2017 to bitpay 

I clicked bitcoin cash  under preferences and selected duplicate for bch and the balance shows as 0

Any idea how to get the bch ?

Also if I transfer the btc out for now can I still get the bch or should I leave the btc in until this is sorted ?

**Comment by matiu** [comment]
Can you try to "scan addresses for funds" in options?

**Comment by matiu** [comment]
thanks for the update.
