### ISSUE TITLE
Error at confirm: We were unable to decode your transaction

### ISSUE THREAD

**Issue by StingNguyen** [bitpay/copay#8342]
I have get a Error: 

https://test.bitpay.com/invoice?id=YMXhsmRwtbLUNzGKQoheFd

![9f720971-57a8-4685-8417-708bd6c3d85c](https://user-images.githubusercontent.com/1131069/38128538-2c76a1a0-3425-11e8-8be3-4a8e2da83a6e.jpg)

**Comment by cmgustavo** [comment]
It has been fixed. Thanks for reporting.

**Comment by StingNguyen** [comment]
Yeah, it is fixed

**Comment by StingNguyen** [comment]
but, My APP Bitpay in IPhone still error after updated:

![de3ff35d-8851-4451-bb84-a3f640ea3114](https://user-images.githubusercontent.com/1131069/38295434-2e97debc-3818-11e8-8cfc-a019a0a526a1.jpg)
![fcfa7606-f567-432a-9d7c-b373e61bf143](https://user-images.githubusercontent.com/1131069/38295436-2eecbf5e-3818-11e8-9b2b-96219d8d9ce5.jpg)

allows in this Screen. 

Bitpay Version: 4.0.13

**Comment by StingNguyen** [comment]
i remove APP, and Reinstall, but it is fail Open

**Comment by cmgustavo** [comment]
Please, upgrader your phone to iOS 11.3
