### ISSUE TITLE
Money didn´t recieved

### ISSUE THREAD

**Issue by wintergarten** [bitpay/copay#8346]
I have a problem with my money account.
I sent 5000€ from my Backoffice4you account to copay on 06.12.2017 18:17:00, with the transaction ID: 267793 and the wallet ID: Bitcoin Wallett: 1FJ6CawsKgfGi1CrqEiznBNWF73tT6R9fs, please send the money back to the account or show me where it is.
It shown up, but then in a moment not anymore, if it´s a network problem then write me or please for a support.

If you want to contact me please write me on my email: georgswintergarten@gmail.com

Please for a quick respond! 
Kindly Sampl

**Comment by matiu** [comment]
Hi, that address did not received any transactions, please contact the sender.
https://blockdozer.com/insight/address/1FJ6CawsKgfGi1CrqEiznBNWF73tT6R9fs
