### ISSUE TITLE
Bug: disappearing information

### ISSUE THREAD

**Issue by caveman1973** [bitpay/copay#8357]
When I click to see my wallet, the content shows for a second and disappears.

If I wait a few seconds it appears but not the transactions history. 

If I return to home page and head back the same thing occurs. 

I don't know where to upload a video so I made a low quality gif to show the problem. 

https://i.imgur.com/Sq2tSYW.gif

**Comment by cmgustavo** [comment]
Thanks for reporting. We could reproduce the issue and will send a fix asap

**Comment by gabrielbazan7** [comment]
fixed #8359
