### ISSUE TITLE
BCH: "View on Blockchain" is Broken

### ISSUE THREAD

**Issue by JulianTosh** [bitpay/copay#8362]
v3.15.2

When trying to view a BCH transaction on the blockchain, a browser instance opens with the incorrect URL causing the browser to display "Cannot GET /tx/713...".

The URL is missing a # as in this example:

Expected:
https://bch-insight.bitpay.com/#/tx/713...

What I get:
https://bch-insight.bitpay.com/tx/713...

If I manually insert the #/ into the URL, it works fine.

**Comment by matiu** [comment]
thanks for the report, this should be fixed in the current V4.
