### ISSUE TITLE
APP Don't work - White screen -  Stuck in splash screen

### ISSUE THREAD

**Issue by mexico8686** [bitpay/copay#8366]
I access the app and it gos to a whote screen amd i cant access my account

**Comment by mexico8686** [comment]
White*

**Comment by viktorcr** [comment]
App don't work, iphone 5

**Comment by mexico8686** [comment]
It’s iPhone 7, and it has worked for many mo the and today only white screen

**Comment by cmgustavo** [comment]
@viktorcr : New version of Copay for iPhone/iPad requires iOS 11, that hasn't support for iPhone 5 and 5C.
@mexico8686 : Do you have your phone updated?

**Comment by viktorcr** [comment]
@cmgustavo I have only iphone 5 , how I can get my money?

**Comment by cmgustavo** [comment]
Restore your backup words in another device (PC or Mac). Or use our recovery tool (https://bitpay.github.io/copay-recovery/) to send to another wallet.

**Comment by viktorcr** [comment]
I try restore in my android - don't work. Recovery tool don't work, error

**Comment by matiu** [comment]
@viktorcr can you explain the problem?

**Comment by viktorcr** [comment]
App don't work after update

Отправлено с iPhone

**Comment by zekecucukwei** [comment]
If I updated my iPhone to ios11, I hope I can use the bch wallet soon

**Comment by alsid** [comment]
Getting white screen too
IPhone 6
IOS: 11.3
App version: 4.0.13

**Comment by alsid** [comment]
After updating to 4.0.14 issue remains.
After starting the app I'm getting splash screen and then just white nothing.
Should I provide additional details some how?

**Comment by cmgustavo** [comment]
If you have your backup phrase, could you uninstall and install the app again? We are investigating this issue and couldn't reproduce on our testing devices

Thanks.

**Comment by mexico8686** [comment]
If I don’t have backup?

**Comment by alsid** [comment]
I don't have a backup phrase either. So the only way is try to recover app.
Quick look shows that it's something with cordova since the app itself is base on it.
Could try to debug it but don't have another ios running device.

**Comment by JulianTosh** [comment]
Force stop the app, then clear the app cache in the app manager. DO NOT clear the app data - only the app cache. This works for me on Android. Mileage may vary on iOS. This has been happening to me more and more as well, but the steps resolve the issue for me.

**Comment by alsid** [comment]
@JulianTosh thank you for an advice.  iOS doesn't have such functionality out of the box unfortunately. I tried to unload and re-install the app without removing data. No luck still.

**Comment by gabrielbazan7** [comment]
@alsid we are sending a new release today that might solve this issue. Sorry, I will let you know when it gets approved in the store.

**Comment by gabrielbazan7** [comment]
Copay/BitPay v4.1.1 is out on app store. Could you try now @alsid ?

**Comment by mexico8686** [comment]
For me it did not work

**Comment by benito170617** [comment]
For me the update dont work too

**Comment by zynbi** [comment]
zyn

Vào 2:05 Th 5, 05 thg 4 2018 Gustavo Maximiliano Cortez <
notifications@github.com> đã viết:

**Comment by beresfordt** [comment]
Still have this issue:

Copay: 4.1.2
iOS: 11.3
iPhone: 7+

**Comment by alsid** [comment]
@gabrielbazan7 thanks for an update. As others noticed it didn't help though.

**Comment by alsid** [comment]
@gabrielbazan7 is it possible to debug the app using remotedebug-ios-webkit-adapter? After configuring everything I can see Safari tabs but no copay app. I was wondering if it's possible at all. Are there any other options available?

**Comment by alsid** [comment]
Last 3 messages before app crashes from the log:
``default    09:21:40.749364 +0200    Copay    [info] Platform ready (cordova): Copay - v4.1.2 #205edab
default    09:21:40.884050 +0200    Copay    THREAD WARNING: ['StatusBar'] took '131.760986' ms.  Plugin should use a background thread.
default    09:21:40.901342 +0200    Copay    [error] Could notinitialize the app
``

**Comment by LynetteKahue** [comment]
ugh I'm having same issue and I really need to access my BTC; don't have backup and was just sending BTC last night. Phone updated and now Copay splash screen comes up and goes to white screen....nothing. PLEASE HELP!

**Comment by LynetteKahue** [comment]
I have Copay 4.1.2
iOS: 11.3
iPhone 6

And still can't get Copay to open (white screen)

**Comment by cmgustavo** [comment]
Hello, we are working on a solution. Thanks for help @alsid

**Comment by LynetteKahue** [comment]
Thanks @cmgustavo and hello from your old HR Lynette :)

**Comment by gabrielbazan7** [comment]
@alsid Could you share me your email ? send me a message to gabriel@bitpay.com. We are going to add you to the test flight program, and send a new release with some new logs.

**Comment by irynchik93** [comment]
IreN

**Comment by cmgustavo** [comment]
Hello @LynetteKahue , we are working on this issue and going to send a fix as soon as possible. 
Thanks @alsid for your help. We are sending another version to our testflight testers.

**Comment by cmgustavo** [comment]
New version is available on the stores (v4.1.5). @LynetteKahue could you try to upgrade the app and let us know if issue has been fixed? Thanks.

**Comment by alsid** [comment]
Problem solved in my case. Thank you @cmgustavo @gabrielbazan7

**Comment by benito170617** [comment]
Issue fixed

**Comment by LynetteKahue** [comment]
@cmgustavo @gabrielbazan7 YAY! thanks so much, that fixed it. You ROCK! so happy I can get in my wallet now 👍

**Comment by Boris3333** [comment]
not working on iphone6 version 10.2

**Comment by BGalliotti** [comment]
Hello @Boris3333,

**What version of the app are you using?**
If you do not have the latest (**4.2.0**) please update it and try again.

For update instructions, please follow #8532 (just the beginning, the update related steps).

**In case you experience the issue after updating, so we can further help, please provide as many of the following details as you can:**

- Current device used
- Current operating system for the device
- Current version of the wallet used
- Any log files containing error details
- Error screenshot
- Steps to replicate
- BitPay Wallet ID - To get your Wallet ID, open your BitPay application, then go to Settings > Wallets & Integrations > More Options > Wallet Information.

Regards

**Comment by BGalliotti** [comment]
@Boris3333  Please see #8564 
Regards

**Comment by EstebanPacheco** [comment]
Hi everybody, here the sames issues, got an old device running iOS 9.3.5, and copay 4.0.12, ant he app wont start, it freezes and all i can see is a big copay logo with a dark blue bakcground, nothing happens. I s there a way to resolve this??


Thanks in advance.

**Comment by EstebanPacheco** [comment]
Hi everybody, here the sames issues, got an old device running iOS 9.3.5, and copay 4.0.12, ant he app wont start, it freezes and all i can see is a big copay logo with a dark blue bakcground, nothing happens. I s there a way to resolve this??


Thanks in advance.

**Comment by BGalliotti** [comment]
Hello @EstebanPacheco,

Thanks for reaching out to us.
Please refer to #8564

The latest version is working properly, your issue must be related to the app and OS versions.
You should update the app. In order to do that you have to upgrade your iOS to version 10.3 as mentioned in #8564.

Please let us know if you have any additional questions.
Kind regards.

**Comment by gskoul3** [comment]
Hi,
Hangs on splash screen after updating some months ago 
android 4.4.2
version  3.9.1 
Could not find class 'android.hardware.fingerprint.FingerprintManager$CryptoObject', referenced from method com.cordova.plugin.android.fingerprintauth.FingerprintAuth.onAuthenticated
.......................
E/FingerprintAuth(26262): minimum SDK version 23 required
no  backup or 12 word and a tiny amount of money in the wallet
cant update android to newer version

Thanks

**Comment by cmgustavo** [comment]
Minimum version of Android required by Copay/BitPay Wallet is 5.1. Try to upgrade your Android and download the app again.

Thanks!

**Comment by aswinmaze** [comment]
@cmgustavo , where should I find New version of(v4.1.5). Can u send the link. I m using groney version in play store 1.01

**Comment by aswinmaze** [comment]
I m facing the white background issue at the time of sign in

**Comment by BGalliotti** [comment]
Hello @aswinmaze 
Thanks for reaching out to us.

You can find the latest version of the Copay wallet here:

https://github.com/bitpay/copay/releases

You can also look for it on the [Google Playstore](https://play.google.com/store/apps/details?id=com.bitpay.copay&hl=en)

Please let us know if you have any additional questions.
Kind regards.

**Comment by startkiller** [comment]
I'm having this problem with my new smartphone ... (Zenfone zoom S)
I'm trying to migrate, but it seems very difficult!
since he asks for an encrypted password that I've never heard before, and the application does not open on the new smartphone.

Note: Everything is updated, cleaned and reinstalled. I also have the backup phrase

**Comment by felipelalli** [comment]
I have the same issue on the version 5.0.7 on Android. Clear cache didn't help.

**Comment by gabrielbazan7** [comment]
Hi! sorry, we send a new version of the app to the stores, should be available soon.
