### ISSUE TITLE
Importing unencrypted wallet.dat

### ISSUE THREAD

**Issue by jmarkinman** [bitpay/copay#8375]
When I try to import wallet.dat, which is not encrypted, I am prompted for a password to decrypt the file. I am forced to type in a password in order to import the file. There is no way to import the file unless I also include a password. Since however the file is unencrypted, any import fails with dummy passwords as it unsuccessfully tries to decrypt with the dummy password.

Therefore, I can not import an unencrypted wallet.dat file to my bitpay app.

There should be a way to import unencrypted wallet.dat files into bitpay without submitting a password.

**Comment by matiu** [comment]
it is not possible to export an unencrypted wallet file with Copay.

**Comment by matiu** [comment]
Where did you get your wallet.dat?

**Comment by jmarkinman** [comment]
Yes, I’m trying to import, not export. Wallet.dat comes from my bitcoin core full node. BTC is empty but it still has several BCH on this wallet. I was having trouble with downloading the full BCH node and don’t intend to run it either, and would just like to import my BCH onto my copay wallet. Bitcoin ABC can read the file no problem.

**Comment by matiu** [comment]
wallet.dat from bitcoind is a completely different format, I am afraid that is not possible at all.

**Comment by matiu** [comment]
I think that electron-cash support bitcoind's wallet.dat format, you can try that one.

**Comment by johnsonrose** [comment]
@jmarkinman 
I can recover your wallet if you want need help  send me email : anywalletrecovery@gmail.com
