### ISSUE TITLE
Copay app 4.0.12 not loading on iOS 10.3.3, Apple iPhone 5, ND097LL/A

### ISSUE THREAD

**Issue by IsraelTorres** [bitpay/copay#8382]
App: Copay Bitcoin Wallet Version 4.0.12 (Apr 2nd 2018), Updated April 4th via App Store
OS: iOS 10.3.3
Phone: Apple iPhone 5, ND097LL/A

Starting App stays on CoPay splash screen indefinitely. 
Closed App via iPhone (double tap home)
Restarted iPhone (via shutdown slider)
Tried tapping around screen after a while of it on the splash screen, no response.

I would imagine the app simply wouldn't install via update automatically from the App Store, if it was not compatible with the existing OS or Phone model, or without further warning. Why would it install otherwise?

![app-splash-screen](https://user-images.githubusercontent.com/216270/38450868-7a9d487e-39da-11e8-9831-f1eeb8e3287c.jpg)

**Comment by redsn0w0** [comment]
The same problem here.

iOS 10.3.3 (14G60)
iPhone 5 - MD297/B

**Comment by cryptowampum** [comment]
Some Problem iPhone 6s 10.3.1

**Comment by zekecucukwei** [comment]
My copay wallet is not opening too in my iPhone ;( what to do guys??

**Comment by IsraelTorres** [comment]
Updated to **4.0.14** tonight (April 10th 2018 via iPhone App Store), and we are back in business!
**Thank you so much for updating it so quickly!**

**This combination works as of April 10th:**
App: Copay Bitcoin Wallet Version 4.0.14 (Apr 10th 2018), Updated April 10th via App Store
OS: iOS 10.3.3
Phone: Apple iPhone 5, ND097LL/A

**Comment by cryptowampum** [comment]
Thanks guys!

**Comment by benito170617** [comment]
The same problem , you fixed ?

**Comment by benito170617** [comment]
The update does not work

**Comment by DDFF111** [comment]
Same problem here - IPhone 7, latest version of the app (4.1.2; Apr 15). 
Any ideas?

**Comment by gabrielbazan7** [comment]
Hi ! sorry about that, we still working on this. Please see https://github.com/bitpay/copay/issues/8366

**Comment by DDFF111** [comment]
Thanks for the update!
