### ISSUE TITLE
Wallet is busy error

### ISSUE THREAD

**Issue by caswastik** [bitpay/copay#8385]
Error is showing what to do please reply faster

**Comment by pasinduchamod** [comment]
Hello @caswastik  . Could you provide us more information about your wallet?
Your wallet id (Of the wallet from which you are trying to send funds): Settings -> Your wallet -> More options -> Wallet information -> Wallet id
The device on . and your back up code,
And the Android/ iOS version of your device.

Thank you.

**Comment by Gamboster** [comment]
Hello @caswastik. Are you still having the problem of "wallet is busy"? Please, if the error keeps appearing, reopen this ticket. Regards!
