### ISSUE TITLE
Stuck on creating transaction

### ISSUE THREAD

**Issue by ekim2388** [bitpay/copay#8386]
I've been trying to send bitcoin to another wallet but my screen stays stuck on creating transaction. Any suggestions? My money is stuck on the copay app. Thank you.

**Comment by Gamboster** [comment]
Hello @ekim2388. Could you provide us more information about your transaction?
Your wallet id (Of the wallet from which you are trying to send funds): Settings -> Your wallet -> More options -> Wallet information -> Wallet id
The device on which you have installed copay
And the Android/ iOS version of your device.

Thank you.

**Comment by ekim2388** [comment]
Wallet id = d95c5eb0-6ae6-4e4c-b57d-b772deaf1cbd
Device = Galaxy J3 Emerge
Android Version 6.0.1
I've sent paymernts on this phone already multiple times.

**Comment by adolforrt** [comment]
Hello,

If you are using the BitPay wallet on your mobile device, please update the wallet application in the [Google Play Store (Android)](https://play.google.com/store/apps/details?id=com.bitpay.wallet). If you are using the wallet on a desktop computer, you can download the most recent version of the BitPay wallet [here](https://bitpay.com/wallet).

**Please update your BitPay wallet app to the latest version, and let us know if you have any more issues.**

**Comment by ekim2388** [comment]
Hey, the update last week made it work. Thank you.
