### ISSUE TITLE
Havent recieved an Amazon giftcard!

### ISSUE THREAD

**Issue by jbblockchain** [bitpay/copay#8389]
Hi, I recently bought an amazon giftcard through the bitpay app with BTC. It has been more than a day since I bought it.  what is going on?

**Comment by cmgustavo** [comment]
Could you provide us more information? Transaction ID, amount of the gift card, and also if you got any error after confirm your purchase.

**Comment by BGalliotti** [comment]
Please check this out:
https://github.com/bitpay/copay/wiki/COPAY---FAQ#amazon-gift-card
