### ISSUE TITLE
I M STUPID , Please Help me 

### ISSUE THREAD

**Issue by crudi1964** [bitpay/copay#8399]
I have no idea how happened but when I opened wallet I wrote only 11 security words: what I can do now that I changed phone ? Not able to have my wallet back without the 12 words . Thank you

**Comment by gabrielbazan7** [comment]
Maybe you could ask for help here https://github.com/bitpay/copay/issues/4808

**Comment by KeyJockey** [comment]
Just got an email note that the other thread is closed, consolidating issue here.

Sorry I still don't have any more info to contribute to this, my niece swears she did *not* add a password to the wallet so *supposedly* all we SHOULD need is the seed word list, that she saved, but that did not work.

Really would like to see a brute-force seed-word sorting tool made for this, "just in case".

**Comment by BGalliotti** [comment]
@KeyJockey  we referenced this thread with https://github.com/bitpay/copay/issues/4808

Regards

**Comment by Richie202a** [comment]
@crudi1964 
If you still have problem finding missing words of your recovery phrase. I can find  the right word for you. you can contact me at : : anywalletrecovery@gmail.com
