### ISSUE TITLE
recovery COPAY

### ISSUE THREAD

**Issue by enzokv** [bitpay/copay#8400]
Hello
i have lost app COPAY on my smartphone.
than when i try to recover wallet on anothe smartphone with seed phrase, i get wallet with 0 bitcoins and no one transaction!

what have i do to recover my coins in your wallet?!!!

**Comment by gabrielbazan7** [comment]
Hi! I think that you might import another wallet in your phone, are you sure those are the words of the wallet you want to import ?

**Comment by enzokv** [comment]
Hello
I have only one seed phrase
I try Do it on another smartphone where ever was no one wallet
I deadly hope that you can help me to solve my problem

вт, 10 апр. 2018 г., 17:42 Gabriel Edgardo Bazán <notifications@github.com>:

**Comment by enzokv** [comment]
Hello once again.
Do you have decision for me? And can you send  me previous version of copay
wallet? Ill Try to Install it on smartphone where was wallet

вт, 10 апр. 2018 г., 17:42 Gabriel Edgardo Bazán <notifications@github.com>:

**Comment by gabrielbazan7** [comment]
That will not help you. You need to remember the 12 words.

**Comment by enzokv** [comment]
I have 12words. Why it not working? Can you find wallet ID by email? Please
help me to recover my coins=((( What should i Do for this? There was big
summ for me

чт, 12 апр. 2018 г., 0:33 Gabriel Edgardo Bazán <notifications@github.com>:

**Comment by gabrielbazan7** [comment]
Share me your wallet ID ( for example: 9f97de52-efbd-4d41-85cc-b608a6e54b45 )

**Comment by enzokv** [comment]
Can we talk in Skype?

And its main trouble. My friend dnt have original wallet ID. When she
create wallet in copay there was no any mail with info about wallet like ID
or smth else

пт, 13 апр. 2018 г., 17:56 Gabriel Edgardo Bazán <notifications@github.com>:

**Comment by enzokv** [comment]
Can we restore wallet info using email from whicn wallet was created?

пт, 13 апр. 2018 г., 17:56 Gabriel Edgardo Bazán <notifications@github.com>:

**Comment by gabrielbazan7** [comment]
No. The only way is to find the 12 words.

**Comment by enzokv** [comment]
Its not working! Because of your soft we lost 4000 dollars. And i ask and
demand to solve this problem. 12words dnt help. So please find any way to
return coins

Best regards, Vladimir

пт, 13 апр. 2018 г., 22:42 Gabriel Edgardo Bazán <notifications@github.com>:

**Comment by enzokv** [comment]
hello=) is anyone here?=)

**Comment by gabrielbazan7** [comment]
You need the 12 words of the wallet you have the funds. Unfortunately there is nothing we can do for you.
