### ISSUE TITLE
Top-up pending

### ISSUE THREAD

**Issue by nikvb** [bitpay/copay#8411]
I've made a top up that is still pending. The transaction has 8 confimations as of now.

https://insight.bitpay.com/tx/2c6698feb3864fa3ff1e9f46956b2979c010bf53530878a1bb7fc862f5ce14d0

Please check what could be an issue.

**Comment by Gamboster** [comment]
Hello @nikvb . I am very sorry that you are having problems with our wallet
If for some reason your Top up is never completed by some bug, please contact to the bitpay help center: https://help.bitpay.com/requestHelp, select the "BitPay card" option and describe your issue providing the transaction id. Also you can send an email to help@bitpay.com.

From our side, we will review the behavior of top ups. If we find a bug, we will try to solve it ASAP
