### ISSUE TITLE
UNKNOWN ERROR OCCURS WHEN TRYING TO CONNECT TO COINBASE

### ISSUE THREAD

**Issue by romerobd** [bitpay/copay#8416]
When selling bitcoin I get an ERROR message when trying to connect to coinbase.

![e50bf2d1-aafe-4cdb-a168-655f724ba268](https://user-images.githubusercontent.com/38312883/38664121-9410bb9e-3ded-11e8-9054-c8c94022da7c.png)

**Comment by romerobd** [comment]
Yes I am.

**Comment by romerobd** [comment]
Any news on this?  Downloaded the update and same issue.  Deleted the app and installed again and same issue.  Is anyone else having this problem?

**Comment by cmgustavo** [comment]
Hello @romerobd , sorry about that. We were working on a fix and will be available in the next release (v4.1.2), probably tomorrow. Thanks for you patience.

**Comment by romerobd** [comment]
Awesome thanks for the update.

**Comment by gabrielbazan7** [comment]
@romerobd the update is ready on the store, could you try again ?

**Comment by BGalliotti** [comment]
#8475
