### ISSUE TITLE
Stuck on fee calculation

### ISSUE THREAD

**Issue by rjevsky** [bitpay/copay#8417]
Hi!
Both clients (Bitpay and Copay) stuck on "Calculating fee..." and I can not make any transaction.

**Comment by shaun-ba** [comment]
Yes, same here, wallet completely unusable.

**Comment by shaun-ba** [comment]
@rjevsky I only use the Android version, but just installed the Desktop client and I'm being returned the error:

"Merchant fee too high, payment rejected".

**Comment by shaun-ba** [comment]
It's a bug, and their response times for urgent issues such as this are known to be very poor.

**Comment by shaun-ba** [comment]
It's "Merchant", not "Miner". I have no idea what this means and the error links to an unrelated article with nothing about the error.

**Comment by shaun-ba** [comment]
@cmgustavo I suggest you jump on this issue ASAP

**Comment by shaun-ba** [comment]
@rjevsky I've reverted to 0.14.2 where the issue/bug isn't, working fine there.

**Comment by rjevsky** [comment]
Perfect! I'll try to downgrade wallet on my iOS, but thinking this not possible...

**Comment by shaun-ba** [comment]
@rjevsky Yes I wouldn't advise untrusted sources, stick to the Desktop version until it's resolved.

Note: Make sure to adjust the fees, their fee calculations are totally off in 0.14.2 and I now have frozen funds and the change is also stuck.

I can't believe what BitPay have turned into over the last year, it's time for a competitor.

**Comment by rjevsky** [comment]
About desktop version =)
![screen shot 2018-04-12 at 14 51 45](https://user-images.githubusercontent.com/38314447/38673066-2e9cac22-3e61-11e8-9546-c17e94747fa3.png)

and we still not have any message from developers...

**Comment by shaun-ba** [comment]
I'm running the linux version, I simply extract to a new directory and run, not sure how it works on MAC.

To ensure you're running a clean (older) version, backup/move your data directory, and restore wallet from backup phrase.

**Comment by shaun-ba** [comment]
Now any version is showing "WALLET_BUSY: wallet is busy, try later"...... This is a joke

**Comment by shaun-ba** [comment]
@rjevsky What is not extremely worrying is my wallet has decreased by 40% in balance, with no record of why.

**Comment by BGalliotti** [comment]
Hello,
**Are you still experiencing this issue?**
We look forward to hearing from you.
Regards

**Comment by BGalliotti** [comment]
Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will be happy to help you.
Thanks

**Comment by ad-m** [comment]
I just receive this message and I can not make the payment from Copay to BitPay.

**Comment by BGalliotti** [comment]
Hello @ad-m 
Thank you for reaching out to us.

To know how to make a payment please watch the following video:
- [How to make a payment](https://bit.ly/2IdrZqL)

If you were having a problem please open a new issue detailing the inquiry.
Kind regards.

**Comment by ad-m** [comment]
@BGalliotti Thank you for your message. I have made many payments before, this is not the first time for me.

**Comment by BGalliotti** [comment]
Hello @ad-m 
Thank you for reaching out to us.

What is the issue you are experiencing exactly?

We look forward to hearing from you.
