### ISSUE TITLE
Multisign Wallet

### ISSUE THREAD

**Issue by nicoarg1103** [bitpay/copay#8418]
Hola, quisiera saber como es el proceso para recuperar una billetera multisign 2-4 tengo las 48 seed pero no estoy pudiendo recuperarlas.

**Comment by Gamboster** [comment]
Hola @nicoarg1103 . A qué te refieres con recuperarla? Quieres importar la wallet ?
Si es una wallet 2-4 entonces debes importar las 4 seeds por separado, es decir, primero con 12 palabras. Importas esa, luego con las siguientes 12 palabras, y así. Al final tendrás 4 wallets que conformaran tu multisig..

>pero no estoy pudiendo recuperarlas
Por algo en particular? Estas intentando poner las 48 palabras juntas? Porque se importa de a 12.

**Comment by nicoarg1103** [comment]
Hola muchas gracais por contestar, si efectivamente quiero importar la wallet. Genial entonces es de a 12 que importo, y se hace desde el boton Importar Wallet o Crear Nueva wallet?.

**Comment by Gamboster** [comment]
Desde el botón de importar. Saludos!

**Comment by nicoarg1103** [comment]
Gracias gamboster, por algun motivo quizas el orden o alguna palabra me esta dando frase incorrecta, tenes idea si se puede comprobar desde alguna pagina las palabras? por ejemplo acentos/mayúsculas, etc? o el orden?

**Comment by Gamboster** [comment]
Puedes ver las palabras aquí: https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md
El orden no, es totalmente aleatorio cuando se generan las 12 palabras y deberías haberlos anotado en el orden correcto.

**Comment by Richie202a** [comment]
@nicoarg1103 
did you restore your wallet. if you couldn't recover I can recover and I have many experience in this issue
you can dm me at : anywalletrecovery@gmail.com
