### ISSUE TITLE
Missing Money

### ISSUE THREAD

**Issue by cbirky** [bitpay/copay#8444]
I sent $200 to LQDFX and it is in neither account now. It doesn't show in my CoPay account or my LQDFX.
Transaction: 8e6fe06879a4f2f2dd91375c82cc41edddea87bb71f9233e9a65d59e6a0b2fc3

**Comment by reelen** [comment]
I sent .06 BTC to my copay wallet as well.  Has multiple confirmations.  Not showing up at all.  

Transaction: 1d13d7b6f58cab7e086e176be963583fd078e0c812eeeebd6717d3ed76e238a5

**Comment by adolforrt** [comment]
Hello,

You can try this two options:

1- Settings > wallet > more opts > transaction history > clear caché. If for some reason you cannot reach this option please provide some screenshots.
2- Settings > wallet > more opts > wallet addresses > scan addresses for funds.

Regards.-

**Comment by BGalliotti** [comment]
Hello,

Thank you for reaching out to to us.

So we can further help, please provide as many of the following details as you can:

- Current device used
- Current operating system for the device
- Current version of the wallet used
- Any log files containing error details
- Error screenshot
- Steps to replicate
- BitPay Wallet ID - To get your Wallet ID, open your BitPay application, then go to Settings > Wallets & Integrations > More Options > Wallet Information.

You can paste your screenshots in the comment.
Regards

**Comment by cbirky** [comment]
![image](https://user-images.githubusercontent.com/38436785/39275641-e014e4a4-489a-11e8-8611-69abf4460833.png)

![image](https://user-images.githubusercontent.com/38436785/39275653-eb88e75e-489a-11e8-98ff-f4d42db93f3a.png)

Samsung Note 8
       Android Version 8

CoPay Version v4.1.2

**Comment by cbirky** [comment]
This process is taking a very long time. I would like an answer within 24 hours as this has been an ongoing situation for the last 2 weeks.

**Comment by BGalliotti** [comment]
Hello, can you send us your wallet ID please?

Thanks.

**Comment by cbirky** [comment]
![screenshot_20180428-104407_copay](https://user-images.githubusercontent.com/38436785/39399372-40b1ee14-4ad1-11e8-995e-6a8ed6fc1638.jpg)

**Comment by BGalliotti** [comment]
Hello @cbirky  as we  can confirm, the transaction was done:

`[Fri Apr 13 2018 22:13:28 GMT-0300] 8e6fe06879a4f2f2dd91375c82cc41edddea87bb71f9233e9a65d59e6a0b2fc3 => sent 0.02546616 btc (fee/kb 0.00042879 btc) (2486 confirmations)
`

Same for you @reelen 
`[Mon Apr 16 2018 16:32:59 GMT-0300] 1d13d7b6f58cab7e086e176be963583fd078e0c812eeeebd6717d3ed76e238a5 <= received 0.06283318 btc (fee/kb 0.00006801 btc) (2078 confirmations)
`
