### ISSUE TITLE
Recovery with BIP39 additional passphrase is broken across versions

### ISSUE THREAD

**Issue by JulianTosh** [bitpay/copay#8447]
My brother in law created a wallet at some point prior to #7795, recently needed to recover the wallet, and was presented with "Could not access wallet" error when he attempted the recovery. The wallet was created with 12 words AND a BIP39 passphrase.

I recalled that there were some code changes relating to #7795 and the BIP39 extra passphrase and suggested that he download a release prior to that incident. He did and his import worked flawlessly.

I will try to narrow down where the break happened, but this will take considerable troubleshooting time to download each release, create a wallet, and restore to a 3.15.2 release instance.

**Comment by gabrielbazan7** [comment]
Hi Julian ! Which version did he try ? It was broken in version v4 but we sent a fix, v4.1.2 should work.

**Comment by enzokv** [comment]
Julian!! Hello!!!

may be a have similar problem with BIP39!
Where you get version 3.9.0 for android.

**Comment by BGalliotti** [comment]
@enzokv  you can find the releases here: https://github.com/bitpay/copay/releases

Anyways you will need some knowledge to perform this action.

Any useful links @JulianTosh ?

**Comment by enzokv** [comment]
Hello. I know this link. But i can t find apk files for Android its seems
to me that there apps for desktop.

чт, 26 апр. 2018 г., 20:43 BGalliotti <notifications@github.com>:

**Comment by BGalliotti** [comment]
#8440
