### ISSUE TITLE
 35000 btcz did not come to the local wallet

### ISSUE THREAD

**Issue by Edwardroshka** [bitpay/copay#8452]
I went to a local wallet phone for Android 35000 btcz, a program called a bitcoin wallet. there's still an address, but no coins. Unable to attach the screenshots.
the address where the coins t1JsygbrRVsrjijEb32HDUgYa3ydpsV51XG   were sent is still in the phone. And has not changed. What to do?

**Comment by Edwardroshka** [comment]
why are you blocking me?

**Comment by gabrielbazan7** [comment]
BTCZ is not supported by Copay or BitPay. You have to use BTCZ software: https://github.com/bitcoinz-pod/bitcoinz-wallet/releases or https://play.google.com/store/apps/details?id=com.btczcom.btcz
Post your issues here instead: https://github.com/bitcoinz-pod/bitcoinz-wallet/issues
