### ISSUE TITLE
Still getting no where

### ISSUE THREAD

**Issue by InigoMontpiya** [bitpay/copay#8458]
Hi there,

Still getting no where at all. 

My old phone died but it did not concern me as I have my recovery phrase. Sadly it turns out this system does not work at the moment and I have lost all of my funds!!!!

When I enter my recovery phrase into my new phone I get a completely empty wallet with no traces of any of my old transactions or addresses. 

PLEASE HELP

**Comment by InigoMontpiya** [comment]
Hi @adolforrt 

Details requested are below, thanks for your help!

Xiaomi Mi Mix 2
Android - 8.0.0 OPR1.170623.027
There is no error file as the issue is simply my funds do not display

Steps to replicate: Download copay -> select "recover wallet" -> enter 12 word pass phrase -> get empty wallet with no funds. 

Wallet ID: bcd73ee5-7530-415c-854f-ec18e08cbfe2

Address missing from wallet: Delivery Address: 1MsJm3Yi7LG2wqojXSwDcynYNNRiBz4vF8
I was getting small amounts of BTC delivered on a 2 weekly basis to the above address. 

Thanks for you time.

**Comment by InigoMontpiya** [comment]
@adolforrt,

Any update on this?

**Comment by InigoMontpiya** [comment]
Heyo! This is getting quite frustrating and no one seems to know why the import function does not work?

**Comment by BGalliotti** [comment]
Hello @InigoMontpiya  we have been checking your info. This is what we retrieved:

```
Found wallet associated to bcd73ee5-7530-415c-854f-ec18e08cbfe2. Querying wallet info...

* Wallet info
  ID: bcd73ee5-7530-415c-854f-ec18e08cbfe2 Coin: btc
  LIVENET 1-of-1 [BIP44 P2PKH] wallet (status: complete)
  Created on: Mon Apr 16 2018 07:48:43 GMT-0300

* Balance
  Total: 0.00000000 btc (0.00000000 btc locked)
  Confirmed: 0.00000000 btc (0.00000000 btc locked)
  Available: 0.00000000 btc (0.00000000 btc confirmed / 0.00000000 btc unconfirmed)

* No pending tx proposals.

* Main addresses (not including change addresses)
  [Mon Apr 16 2018 07:50:24 GMT-0300] 15gXEpNHN9Ug9eTqGfJ3iw5e1SkswCybHg (m/0/0)
  [Mon Apr 16 2018 07:50:39 GMT-0300] 1Aj2mWEQ1xyzySdHk3dWjC49rDreufNBZP (m/0/1)
  [Mon Apr 16 2018 07:52:59 GMT-0300] 1gzxxdDSReNctXSashzJdQSx6nUr6BDpm (m/0/2)
  [Mon Apr 16 2018 08:11:11 GMT-0300] 1BJQhvi4Kj37ibQUXmLubzFbX7LaHfpJ3n (m/0/3)

* No tx history.
```
The address  you mention, is related to another wallet which has funds.

Basically you are importing a different wallet.

If there is any other question or concern please let us know.

Kind Regards

**Comment by InigoMontpiya** [comment]
@BGalliotti 

I have the pass phrase I wrote it down in two separate places to make sure I would not lose it. The issue is that when I enter said pass phrase I import a wallet with zero funds rather than my own wallet.

**Comment by enzokv** [comment]
ATTENTION!!!

this trouble repeats for several people!!! i have absolutely same trouble!!!
after reinstall 12words recovery blank wallet without transactions and coins!!

COPAY TEAM!!! you should to dig this issues harder!!!

**Comment by BGalliotti** [comment]
@InigoMontpiya  We already provided all the information we have access to. 
Anyways we will be following this closely.
@enzokv  try these steps, they might work
**Open up your BitPay app and try the following steps:**

- ("Settings" > "Wallet" > "More Options" > "Transaction History" > "Clear cache")
- ("Settings" > "Wallet" > "More Options" > "Wallet Addresses" > "Scan addresses for funds")

**Comment by BGalliotti** [comment]
#8440
