### ISSUE TITLE
I cannot send BCH from copay, receiving address cannot be put

### ISSUE THREAD

**Issue by yuishida311** [bitpay/copay#8460]
I am trying to put receiving address for BCH but only BTC is available. 
I was able to send BCH last month though.
Please check the attachments and let me know what I should do.
![img_3262](https://user-images.githubusercontent.com/38498479/38934443-b871bdd0-4356-11e8-9f37-0fd6feb2fb1e.PNG)

![img_3261](https://user-images.githubusercontent.com/38498479/38934364-89e91a9e-4356-11e8-9e86-53a42374559e.PNG)

**Comment by gabrielbazan7** [comment]
The first screenshot is from the view for duplicate a bitcoin cash wallet from a bitcoin wallet. I don't completely understand your issue. To transfer to a BCH address past it in the send input.

**Comment by yuishida311** [comment]
Thank you for your quick reply.
When I  copy and past BCH address to the recipient, it takes me to BTC page to put the amount.
When I  scan BCH QR code, it still leads me to the BTC payment and cannot choose BCH though I was able to send last month.
Then when I  go to setting and click "Bitcoin Cash" right below of "Preference" , it says No wallets eligible for Bitcoin Cash support. So I was wondering if that is relating to the issue that I cannot send bitcoin cash.

**Comment by gabrielbazan7** [comment]
Do you mind share the address to me ? . No it's not related. That's is a feature for users that claims their BCH after the hard fork.

**Comment by yuishida311** [comment]
Sure, here is the address for BCH.
3LEBdKoRnyBdbde5zYQ6mHt2amfuHkmWgU

**Comment by yuishida311** [comment]
Oh really!?
I got it from BitFlyer Japan.

**Comment by BGalliotti** [comment]
Hello,

thanks @JulianTosh  for the info.

@yuishida311  if you need to duplicate your wallet (to have a BCH wallet as well) follow this [article](https://support.bitpay.com/hc/en-us/articles/115005019583-How-Can-I-Recover-Bitcoin-Cash-BCH-from-My-Wallet-)

Please let us know if you need anything else.

Regards
