### ISSUE TITLE
BitPay Amazon Gift Card

### ISSUE THREAD

**Issue by Jaguar230** [bitpay/copay#8466]
i paid for the amazon gift card but nothing have been provided. i already sent request to bitpay support but nothing have been replied back to me.i want my refund back.i hope bitpay will resolve this matter asap

**Comment by BGalliotti** [comment]
Hello, the bitpay team is taking care of your issue.

**Comment by BGalliotti** [comment]
We will be closing this thread, If you need further support on this issue please do it directly through bitpay.

Thanks.
