### ISSUE TITLE
Unknown Error Coinbase

### ISSUE THREAD

**Issue by F111DXK** [bitpay/copay#8475]
Hello, I’m having issues selling BTC. I linked my copay wallet through coinbase but i’m getting an unknown error when I try to sell.  I logged off and on but same issue.  Please advise.  Thanks.

**Comment by BGalliotti** [comment]
Hello,

Thank you for reaching out to to us.

So we can further help, please provide as many of the following details as you can:

- Current device used
- Current operating system for the device
- Current version of the wallet used
- Any log files containing error details
- Error screenshot
- Steps to replicate
- BitPay Wallet ID - To get your Wallet ID, open your BitPay application, then go to Settings > Wallets & Integrations > More Options > Wallet Information.

**Comment by F111DXK** [comment]
Apple iPhone 7
iOS 11.3.1
Copay v4.1.2

**Comment by BGalliotti** [comment]
Thanks for the info provided, please attach some screenshots of the error and the steps needed for the error to occur so we can properly address your issue

**Comment by F111DXK** [comment]
![2aac05cb-4a08-407f-abfe-5435709a16ac](https://user-images.githubusercontent.com/38562891/39264355-affe056e-4892-11e8-9537-2376c942bf32.png)
![c4349396-bada-4400-b12c-3bb6fb33e2dd](https://user-images.githubusercontent.com/38562891/39264356-b0159472-4892-11e8-8dd3-f693453858a6.png)
![7e4ba9c8-88bc-4562-b6e9-98da43e01077](https://user-images.githubusercontent.com/38562891/39264357-b025d68e-4892-11e8-9179-08a2e72c658a.png)

**Comment by BGalliotti** [comment]
Please do the following:

Try to sell bitcoin on Coinbase until you get the error you previously posted.
Then go back to Home screen and next,
Settings > About BitPay > Session Log > Tap on the three dots line on the upper right corner > Send by email
and use these address: arodriguez@bitpay.com

Or in the desktop version, click on "Copy to clipboard" and paste it in the email.
Thanks.

**Comment by F111DXK** [comment]
sent to arodriguez@bitpay.com

**Comment by BGalliotti** [comment]
Thanks @F111DXK  we will be posting soon.
R

**Comment by BGalliotti** [comment]
Hello,

You are getting this error:

`[error]Coinbase: Sell Request ERROR 400. Can't sell with this payment method.`

Please try adding another payment method within your account on [coinbase.com](https://www.coinbase.com/)

and let us know what happens.

Regards.

**Comment by F111DXK** [comment]
I’m getting the same error message after I changed payment method.

**Comment by BGalliotti** [comment]
@F111DXK  please send us the error log again so we can further research.

Try to sell bitcoin on Coinbase until you get the error you previously posted.
Then go back to Home screen and next,
Settings > About BitPay > Session Log > Tap on the three dots line on the upper right corner > Send by email
and use these address: arodriguez@bitpay.com

Or in the desktop version, click on "Copy to clipboard" and paste it in the email.
Thanks.

**Comment by BGalliotti** [comment]
Hello @F111DXK  sorry for the delay, please try changing the payment method, logout from coinbase, from the bitpay app, then log in and try again.

To log out from Coinbase: Bitpay App > Settings > Coinbase > log out

This issue does not depend on us, we will suggest you to contact [Coinbase support](https://support.coinbase.com/)

As a last resort, if you find no solutions, you can try with the desktop app or updating the mobile app.

Check out the following steps meticulously:
**Do not uninstall the app if you do not have backed up the wallet, you will lose your wallet and funds if you do so.**

If you haven't backed up your wallet, please first go to Settings > Your Wallet Name > Backup. [Write down the 12 word backup phrase and secure it](https://blog.bitpay.com/private-key-security/). We do not recommend emailing it to yourself.

To import the wallet on another device, you can click the **+** next to Wallets and then choose **Import wallet**. Enter the 12 word backup phrase and you will now have access to the wallet from both devices.

Please see the [following article](https://support.bitpay.com/hc/en-us/articles/115003028346-How-do-I-move-my-wallet-from-Copay-to-BitPay-) for steps on how to restore the wallet from a backup.

**You can also try using another device in case you can not upgrade you phone's OS.**

If you are using the BitPay wallet on your mobile device, please update the wallet application in the [App Store (iOS)](https://itunes.apple.com/us/app/bitpay-secure-bitcoin-wallet/id1149581638) or [Google Play Store (Android)](https://play.google.com/store/apps/details?id=com.bitpay.wallet). If you are using the wallet on a desktop computer, you can download the most recent version of the BitPay wallet [here](https://bitpay.com/wallet).

After updating, import your wallet:

Please see the following article for steps on restoring your wallet using the recovery phrase: https://support.bitpay.com/hc/en-us/articles/115003004363-I-lost-my-wallet-or-changed-my-phone-What-can-I-do-to-restore-my-wallet-

If you are experiencing an issue, here are some things that you can check:
- Are you sure that the recovery phrase was written in the correct order?
- Did you use all lowercase letters and no punctuation?
- Did you add a password to your recovery phrase?
- [Do you have the QR code or text/file backup?](https://support.bitpay.com/hc/en-us/articles/115003004363-I-lost-my-wallet-or-changed-my-phone-What-can-I-do-to-restore-my-wallet-)
- Did you separate each word with a single space (no commas or any other punctuation)?

Please also ensure that your words are all contained in the following list of possible words:
https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt

Please also make sure:
**Your phone is not using capitals for the first letter of the words**
**You are not typing spaces:**

- before the first word
- more than one space between words
- After the last word

**If you are still experiencing this issue after checking all of the above, please let us know.**

**Comment by BGalliotti** [comment]
@F111DXK  we noticed you closed the thread, did something work for you?

**Comment by F111DXK** [comment]
have to find another payment method

**Comment by BGalliotti** [comment]
@F111DXK  thanks for commenting. Please if you solve your issue after doing so, share your solution, the community will be grateful.

Best regards.
