### ISSUE TITLE
Copay V4 doesn't work with android software renderer

### ISSUE THREAD

**Issue by 94b42c29dd** [bitpay/copay#8482]
I always used copay without many issues on Replicant (android distribution). Unfortunately since version 4 it hangs on boot, showing only the copay logo.

Replicant is the only android distribution that comes with only free and open-source software. This does mean however it can't do GPU acceleration and relies on the android software renderer. I really hope copay can stay compatible with this distribution for people who do not want to run non-free (closed-source) software. As I said, the app worked fine before (version 3.x).

**Comment by gabrielbazan7** [comment]
close this one in other to #8366
