### ISSUE TITLE
Password olvidado

### ISSUE THREAD

**Issue by aavfx** [bitpay/copay#8487]
Se me olvidó el password de mi billetera de copay, no la tenia respaldada, la billetera me aparece con el saldo pero no puedo sacar mis btc, hay alguna forma de resetear o recuperar la clave?

**Comment by BGalliotti** [comment]
Hola,

**Lamentablemente no hay forma de recuperar sin las opciones de respaldo (frase de recuperación, archivo, etc).**

Lo único que podemos sugerirle es tratar de recordar su contraseña.
**Por las dudas, le recordamos que no hay ningún requisito especial para la contraseña como símbolos, mayúsculas o números.**

Si tiene alguna otra duda o consulta por favor, dejenoslo saber.

**Comment by Richie202a** [comment]
@aavfx 
I can crack your wallet password if you want send me email : anywalletrecovery@gmail.com

**Comment by richardsuns** [comment]
@aavfx 
if you still have access to your wallet, the password can be cracked
