### ISSUE TITLE
Can't send money

### ISSUE THREAD

**Issue by Spursup** [bitpay/copay#8495]
I have over $21 in my wallet and I can't even send $2. I am highly upset and I need someone to resolve this issue.

**Comment by BGalliotti** [comment]
Hello,

Thank you for reaching out to us.

So we can further help, please provide as many of the following details as you can:

- Current device used
- Current operating system for the device
- Current version of the wallet used
- Any log files containing error details
- Error screenshot
- Steps to replicate
- BitPay Wallet ID - To get your Wallet ID, open your BitPay application, then go to Settings > Wallets & Integrations > More Options > Wallet Information.

Regards

**Comment by 1texan** [comment]
Hello,

I'm trying to send money from Copay to Bitpay, but when it asks for my password I get and error message stating incorrect password.  No, it's the correct password.  Copay has my money and it's stuck there.

**Comment by BGalliotti** [comment]
Hello,

Please try to remember your password.
If you do not remember it, you can delete and recover your wallet with the 12-word recovery phrase.

Do not proceed with the wallet deletion/app uninstall if you have not backed up your wallet.

For further help on how to backup and recover your wallet, please follow this post: #8532

Please let us know if that worked.

regards

**Comment by zynbi** [comment]
zyn
