### ISSUE TITLE
Transaction missing

### ISSUE THREAD

**Issue by pranay1245** [bitpay/copay#8498]
I sent 0.0195 bitcoin from copay to neteller...the invoice was paid at the time and was pending...but now the transaction is missing from copay and i haven’t received the money on neteller...and also the transaction is not shown on insight...plz help

**Comment by BGalliotti** [comment]
Hello,

Thank you for reaching out to to us.

So we can further help, please provide as many of the following details as you can:

- Current device used
- Current operating system for the device
- Current version of the wallet used
- Any log files containing error details
- Error screenshot
- Steps to replicate
- BitPay Wallet ID - To get your Wallet ID, open your BitPay application, then go to Settings > Wallets & Integrations > More Options > Wallet Information.

Regards

**Comment by pranay1245** [comment]
Thank you...its done...it took 12 hrs to credit in my account...and midway through that time...transaction status was missing...so i got worried...

**Comment by BGalliotti** [comment]
Excellent @pranay1245  

I'll be closing this thread.
Please if you still need support, open a new one, we will happy to help you.
Thanks.
