### ISSUE TITLE
Typescript error on npm run start

### ISSUE THREAD

**Issue by GarrettFleischer** [bitpay/copay#8512]
I followed the install instructions on a Linux Mint box and it successfully built and is running on port 8100.
However I get the following typescript errors in both the terminal and the web page:

> [13:10:36]  typescript: node_modules/@types/node/index.d.ts, line: 2381 
>             Duplicate identifier 'URL'. 
> 
>     L2380:      values(): IterableIterator<string>;
>     L2381:      [Symbol.iterator](): IterableIterator<[string, string]>;
> 
> [13:10:36]  typescript: node_modules/@types/node/index.d.ts, line: 2399 
>             Duplicate identifier 'URLSearchParams'. 
> 
>     L2399:      export interface LookupOneOptions extends LookupOptions {
>     L2400:          all?: false;
> 
> [13:10:36]  typescript: node_modules/@types/node/index.d.ts, line: 2417 
>             Cannot export 'URL'. Only local declarations can be exported from a module. 
> 
>     L2416:      export function lookup(hostname: string, callback: (err: NodeJS.ErrnoException, address: string, family: number) => void): void;
>     L2418:      // NOTE: This namespace provides design-time support for util.promisify. Exported members do not exist at runtime.
> 
> [13:10:36]  typescript: node_modules/@types/node/index.d.ts, line: 2417 
>             Cannot export 'URLSearchParams'. Only local declarations can be exported from a module. 
> 
>     L2416:      export function lookup(hostname: string, callback: (err: NodeJS.ErrnoException, address: string, family: number) => void): void;
>     L2418:      // NOTE: This namespace provides design-time support for util.promisify. Exported members do not exist at runtime.
> 
> [13:10:36]  typescript: node_modules/typescript/lib/lib.dom.d.ts, line: 12210 
>             Duplicate identifier 'URL'. 
> 
>    L12209:  readonly badInput: boolean;
>    L12210:  readonly customError: boolean;
>    L12211:  readonly patternMismatch: boolean;
> 
> [13:10:36]  typescript: node_modules/typescript/lib/lib.dom.d.ts, line: 12226 
>             Duplicate identifier 'URL'. 
> 
>    L12225:  };
>    L12227:  interface VideoPlaybackQuality {
> 
> [13:10:36]  typescript: node_modules/typescript/lib/lib.dom.d.ts, line: 14282 
>             Duplicate identifier 'URLSearchParams'. 
> 
>    L14281:      set(name: string, value: string): void;
> 
> [13:10:36]  typescript: node_modules/typescript/lib/lib.dom.d.ts, line: 14309 
>             Duplicate identifier 'URLSearchParams'. 
> 
>    L14309:  interface FilePropertyBag extends BlobPropertyBag {
>    L14310:      lastModified?: number;
> 
> [13:10:36]  typescript: src/providers/app-identity/app-identity.ts, line: 7 
>             Cannot find module 'bitauth'. 
> 
>        L7:  import * as bitauthService from 'bitauth';
>        L8:  import * as _ from 'lodash';
> 
> [13:10:36]  typescript: src/providers/bitpay/bitpay.ts, line: 8 
>             Cannot find module 'bitauth'. 
> 
>        L8:  import * as bitauthService from 'bitauth';

**Comment by Yoyae** [comment]
I'm having similar issue. Using node v9.11.1 and npm v6.0.0. Here bugs I have :
    
    typescript: node_modules/@types/node/index.d.ts, line: 2381
            Duplicate identifier 'URL'.

    L2380:      values(): IterableIterator<string>;
    L2381:      [Symbol.iterator](): IterableIterator<[string, string]>;

    typescript: node_modules/@types/node/index.d.ts, line: 2399
            Duplicate identifier 'URLSearchParams'.

    L2399:      export interface LookupOneOptions extends LookupOptions {
    L2400:          all?: false;

    typescript: node_modules/@types/node/index.d.ts, line: 2417
            Cannot export 'URL'. Only local declarations can be exported from a module.

    L2416:      export function lookup(hostname: string, callback: (err: NodeJS.ErrnoException, address: string, family: number) => void): void;
    L2418:      // NOTE: This namespace provides design-time support for util.promisify. Exported members do not exist at runtime.

    typescript: node_modules/@types/node/index.d.ts, line: 2417
            Cannot export 'URLSearchParams'. Only local declarations can be exported from a module.

    L2416:      export function lookup(hostname: string, callback: (err: NodeJS.ErrnoException, address: string, family: number) => void): void;
    L2418:      // NOTE: This namespace provides design-time support for util.promisify. Exported members do not exist at runtime.

    typescript: node_modules/typescript/lib/lib.dom.d.ts, line: 12210
            Duplicate identifier 'URL'.

    L12209:  readonly badInput: boolean;
    L12210:  readonly customError: boolean;
    L12211:  readonly patternMismatch: boolean;
    
    typescript: node_modules/typescript/lib/lib.dom.d.ts, line: 12226
            Duplicate identifier 'URL'.

    L12225:  };
    L12227:  interface VideoPlaybackQuality {
    
    typescript: node_modules/typescript/lib/lib.dom.d.ts, line: 14282
            Duplicate identifier 'URLSearchParams'.

    L14281:      set(name: string, value: string): void;
    
    typescript: node_modules/typescript/lib/lib.dom.d.ts, line: 14309
            Duplicate identifier 'URLSearchParams'.

    L14309:  interface FilePropertyBag extends BlobPropertyBag {
    L14310:      lastModified?: number;

**Comment by ayush-techracers** [comment]
I also received the same error. I'm using the following:
1. node: v8.9.3
2. npm: 5.6.0
3. tsc: 2.7.2

Error:
```
[19:36:39]  typescript: node_modules/@types/node/index.d.ts, line: 2381 
            Duplicate identifier 'URL'. 

    L2380:      values(): IterableIterator<string>;
    L2381:      [Symbol.iterator](): IterableIterator<[string, string]>;

[19:36:39]  typescript: node_modules/@types/node/index.d.ts, line: 2399 
            Duplicate identifier 'URLSearchParams'. 

    L2399:      export interface LookupOneOptions extends LookupOptions {
    L2400:          all?: false;

[19:36:39]  typescript: node_modules/@types/node/index.d.ts, line: 2417 
            Cannot export 'URL'. Only local declarations can be exported from a module. 

    L2416:      export function lookup(hostname: string, callback: (err: NodeJS.ErrnoException, address: string, family: number) => void): void;
    L2418:      // NOTE: This namespace provides design-time support for util.promisify. Exported members do not exist at runtime.

[19:36:39]  typescript: node_modules/@types/node/index.d.ts, line: 2417 
            Cannot export 'URLSearchParams'. Only local declarations can be exported from a module. 

    L2416:      export function lookup(hostname: string, callback: (err: NodeJS.ErrnoException, address: string, family: number) => void): void;
    L2418:      // NOTE: This namespace provides design-time support for util.promisify. Exported members do not exist at runtime.

[19:36:39]  typescript: node_modules/typescript/lib/lib.dom.d.ts, line: 12210 
            Duplicate identifier 'URL'. 

   L12209:  readonly badInput: boolean;
   L12210:  readonly customError: boolean;
   L12211:  readonly patternMismatch: boolean;

[19:36:39]  typescript: node_modules/typescript/lib/lib.dom.d.ts, line: 12226 
            Duplicate identifier 'URL'. 

   L12225:  };
   L12227:  interface VideoPlaybackQuality {

[19:36:39]  typescript: node_modules/typescript/lib/lib.dom.d.ts, line: 14282 
            Duplicate identifier 'URLSearchParams'. 

   L14281:      set(name: string, value: string): void;

[19:36:39]  typescript: node_modules/typescript/lib/lib.dom.d.ts, line: 14309 
            Duplicate identifier 'URLSearchParams'. 

   L14309:  interface FilePropertyBag extends BlobPropertyBag {
   L14310:      lastModified?: number;
```

**Comment by gabrielbazan7** [comment]
Fixed here https://github.com/bitpay/copay/pull/8514

**Comment by ayush-techracers** [comment]
Thanks @gabrielbazan7 .
