### ISSUE TITLE
BitPay and CoPay wallets require Android 6.0?

### ISSUE THREAD

**Issue by PrzemekFPL** [bitpay/copay#8513]
I didn't find this information on the website or in the Play Store description, so I want to ask if there are no plans to support Android versions below version 6.0?

**Comment by BGalliotti** [comment]
Hello @PrzemekFPL  Android 6.0 is the minimum versiion  supported by our app.

Due to our development definitions we are not going to support older versions and there are no plans for that so far.
Thank you for your interest and support.
Regards

**Comment by BGalliotti** [comment]
Hello, thanks for the heads up @PrzemekFPL  we will fix this ASAP.
