### ISSUE TITLE
Unconfirmed transaction did not send to wallet

### ISSUE THREAD

**Issue by aethernevernether** [bitpay/copay#8525]
https://blockchain.info/address/1BRYUhRWRMFaf9M8aLzv6drM1XgotwnHuz

**Comment by aethernevernether** [comment]
This is the transaction
https://blockchain.info/tx/e4ad007604c7f07230d9ae16618e3167ac491a60c53403c9d9a29c267a312015

**Comment by BGalliotti** [comment]
Hello @aethernevernether as we can see the transaction is confirmed.
Are you expecting funds to be in your wallet? Please explain your case in a more detailed way.
thanks
