### ISSUE TITLE
PLEASE HELP ME!!   Copay Wallet won't let me send my bitcoin

### ISSUE THREAD

**Issue by sharon-btcwallet** [bitpay/copay#8531]
It's asking for a "send passcode" and I never was asked to set one!  Saw other people having trouble with this as well.

Here's what it LOOKS like I need to do:
1. Back up my wallet (don't know how to do that or if it will let me)
2. Delete the wallet (don't know how to do this either!)
3. Recover it with the 12 words I was given when I signed up.

I hope someone out there has a nice, simple answer.  Have a fairly large amount of btc locked in it!

**Comment by BGalliotti** [comment]
Hello @sharon-btcwallet  please refer to #8532
