### ISSUE TITLE
How to back up + Import my Bitpay / MIGRATE Copay Wallet

### ISSUE THREAD

**Issue by BGalliotti** [bitpay/copay#8532]
How to backup/Migrate my Bitpay/Copay Wallet

**Backup/Migration Checklist:**
1. Back the wallet/s up
2. Install/Update the wallet App
3. Import/Restore the wallet/s

**IMPORTANT NOTE:**
**Do not uninstall the app if you do not have backed up the wallet, you will lose your wallet and funds if you do so.**

**BACK UP**

If you haven't backed up your wallet, please first go to Settings > Your Wallet Name > Backup. [Write down the 12-word backup phrase and secure it](https://blog.bitpay.com/private-key-security/). We do not recommend emailing it to yourself.

Watch this [video](https://www.youtube.com/watch?v=U23E-dZEuYs&t=26s) to see how to backup your wallet.

**The 12-word recovery phrase is the only way to recover your wallet.**

**UPDATE** (if necessary)

**You can try using another device in case you cannot upgrade your phone's OS.**

If you are using the BitPay wallet on your mobile device, please update the wallet application in the [App Store (iOS)](https://itunes.apple.com/us/app/bitpay-secure-bitcoin-wallet/id1149581638) or [Google Play Store (Android)](https://play.google.com/store/apps/details?id=com.bitpay.wallet). If you are using the wallet on a desktop computer, you can download the most recent version of the BitPay wallet:

- [Windows](https://www.microsoft.com/store/apps/9MZGT30HL9DF)
- [Mac](https://itunes.apple.com/us/app/bitpay/id1440200291?ls=1&mt=12) (BitPay App. Copay is not available yet)
- [Linux](https://snapcraft.io/copay)

**IMPORT/RESTORE**

**After updating, import your wallet.**

- NOTE: Unless you have created the wallet with a very old version of the app, **YOU DO NOT NEED THE PASSWORD, so do not enter it. This troubleshooting guide is only for the 12-word passphrase recovery.**

To import the wallet on another device, you can click the **+** next to Wallets and then choose **Import wallet**. Enter the 12-word backup phrase and you will now have access to the wallet from both devices.

Please see the [following article](https://support.bitpay.com/hc/en-us/articles/115003028346-How-do-I-move-my-wallet-from-Copay-to-BitPay-) for steps on how to restore the wallet from a backup.

Please see the following article for steps on restoring your wallet using the recovery phrase: https://support.bitpay.com/hc/en-us/articles/115003004363-I-lost-my-wallet-or-changed-my-phone-What-can-I-do-to-restore-my-wallet-

**If you are experiencing an issue with the recovery phrase, here are some things that you can check:**
- Are you sure that the recovery phrase was written in the correct order?
- Did you use all lowercase letters and no punctuation?
- Did you add a password to your recovery phrase?
- [Do you have the QR code or text/file backup?](https://support.bitpay.com/hc/en-us/articles/115003004363-I-lost-my-wallet-or-changed-my-phone-What-can-I-do-to-restore-my-wallet-)
- Did you separate each word with a single space (no commas or any other punctuation)?

Please also ensure that your words are all contained in the following list of possible words:
https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt
For other languages click [here](https://github.com/bitcoin/bips/blob/master/bip-0039).

Please also make sure:
**- Your phone is not using capitals for the first letter of the words**
**- You are not typing spaces:** (if you are getting a **13 WORDS ERROR**, pay special attention to this point)

   - before the first word
   - more than one space between words
   - After the last word

**Check out the following videos if you need more explanations**

- [How to backup and restore my wallet](https://www.youtube.com/watch?v=U23E-dZEuYs&index=3&list=PLM4HPl72LIecMZ821jZC9OB55F9ALiLqL)
- [Bitpay wallet Youtube FAQ](https://www.youtube.com/playlist?list=PLM4HPl72LIecMZ821jZC9OB55F9ALiLqL)

**Comment by sharon-btcwallet** [comment]
Thank you so much for helping me. 

I have another question as I got stuck at the point after I backed up my wallet and updated the app for copay.

Notes weren't clear about what to do next.   Am I supposed to delete my copay app on my phone now and download a new one?   

Please advise.  Have read the instructions several times and still confused.

Thank you!

**Comment by BGalliotti** [comment]
Hello @sharon-btcwallet   you are welcome
After updating the app, please proceed to import your wallet with the 12-word phrase
regards

**Comment by joehayes13** [comment]
#8668 continued 
I had a copay wallet on my phone when it crashed. It had no funds on it at the time so I dident care about it. I also lost the 12 word seed. Again no funds dident care about it. 
But when i changed wallets from my pool I dident realise it dident take. So yesterday 1 btc got sent to this wallet that I dont have access to any longer.
I have proof of ownership. How do I recover that btc?

**Comment by BGalliotti** [comment]
Hello  @joehayes13 

Thanks for reaching out to us.
If you have your 12-word phrase, you will be able to recover your wallet (I assume we are talking about a Bitpay/Copay wallet). In this case, follow the procedure described above in an earlier post.

If not, unfortunately, there is no way to recover that wallet, and as we do not store any information and there is no account for a bitpay wallet, we can not help with this.

If there is any other question or concern we can help you with please let us know.
Kind regards.

**Comment by VahtangKyiv** [comment]
Hello! Can 12 words coincide with the other participants? I could not restore my old wallet (MyBitcoinZ), I tried to create a new purse and used words and order from the old wallet, and everything went well, the question - where did my old balance in the amount of 12,800 BTCZ ??

**Comment by VahtangKyiv** [comment]
t1W1BjvJE6VwUS5UNXNBGk4WCxsSVmGBeoR

**Comment by corn91791** [comment]
Somebody stole all my money out of my bank going because when they stole my wallet I mean my phone

**Comment by BGalliotti** [comment]
Hello @VahtangKyiv ,

 > Can 12 words coincide with the other participants?
 No, every wallet is unique as its ID, addresses, and backup data.

**What you have pasted is not a a valid bitcoin/ bitcoin cash transaction. I do not understand correctly, but if you are using Copay/Bitpay wallets they have no support for other currencies than BTC and BCH.

@corn91791  Please try to be clearer when explaining your issue so we can properly address it.

Thanks for reaching out to us.



If there is any other question or concern we can help you with please let us know.
Kind regards.

**Comment by nguyenanh462117** [comment]
Vào 18:24, T.7, 13 Th10, 2018 vnbtc <notifications@github.com> đã viết:

**Comment by munternet** [comment]
Do I have to download the new version from microsoft or is there another way? Cheers

**Comment by BGalliotti** [comment]
Hello @munternet,
Thanks for reaching out to us.

From version 5.1.0 onwards, it will be no longer available here on GitHub.

It is not mandatory to download it now, you can still use the legacy version in case you need it. However, the legacy version has no longer support. We recommend you backup all your wallets, make sure to have written down all your recovery phrase on a physical mean (a piece of paper for example) to make the migration process to the new app more straightforward.

Please let us know if you have any additional questions.
Kind regards.

**Comment by munternet** [comment]
> Hello @munternet,
> Thanks for reaching out to us.
> 
> From version 5.1.0 onwards, it will be no longer available here on GitHub.
> 
> It is not mandatory to download it now, you can still use the legacy version in case you need it. However, the legacy version has no longer support. We recommend you backup all your wallets, make sure to have written down all your recovery phrase on a physical mean (a piece of paper for example) to make the migration process to the new app more straightforward.
> 
> Please let us know if you have any additional questions.
> Kind regards.

Thanks for the replay :)
I was wondering if there was a way to download the file other than the microsoft store as don't really want a microsoft account?
Or is it possible to download on another machine and transfer it?
Cheers

**Comment by pablo48** [comment]
The new Version 5, don't work with Win7, only with Win10. Which solution do you have for older Windows Systems?

**Comment by munternet** [comment]
I'm running a cut down version of windows 10 from teamos with no ms telemetry so no updates or anything else that contacts ms. I have a ligit version but this version is so much better for me. I just wanted a file I could install manually :)

**Comment by sergioch100** [comment]
Buenas noches, no se si me pudieran ayudar tengo un problema con mi billetera Bitpay en ios 
yo tengo las 12 frases pero no me dejecuperarla que podria hacer ???

**Comment by johnjames333** [comment]
@joehayes13 @VahtangKyiv 
we have developed our own hardware for cracking BITCOIN wallet PASSWORDS with superfast speed
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333
