### ISSUE TITLE
Installing Bitpay app in Linux + Creating desktop shortcut // Copay legacy versions

### ISSUE THREAD

**Issue by sgehrman** [bitpay/copay#8533]
I downloaded the linux copay and extracted it, now I have a folder full of junk.  doesn't even extract in a folder, just blasts files all over.  Worthless. no idea what to do with this mess.

**Comment by BGalliotti** [comment]
Hello @sgehrman let us help you.
Here is how you download and run the linux app: https://www.youtube.com/watch?v=ISQl-ZdSbDM

What you get after extracting the file, is the folder with the wallet. Right.

We recommnend you:
- Create a folder manually with the linux "explorer" and extract the files there to keep it tidy.
(remember where you created the folder, you will need this later)

**You have two options:**
1. Run the wallet by the console. (as shown on the video.  It might slightly change according to your linux distribution).
2. Create a launcher on your desktop so you can doble click on it and open the wallet. (as the typical windows way).

For option two, do this:
1. Right Click on your desktop (the wallpaper) and click on "Create a new launcher here.." 
2. Enter a name for the launcher (the shortcut)
3. Click on "Browse"
4. Look for the folder containing the files, click on the file named "bitpay" (its size is 7.2MB approximately just in case)
5. Click ok.

You will have your launcher on the desktop. Now you can double click on it and open the wallet.



 
The thing is, as usually in linux
