### ISSUE TITLE
Transaction on my Copay personal wallet 

### ISSUE THREAD

**Issue by bigheartcrx** [bitpay/copay#8534]
Transaction on my Copay personal wallet Wont let me make any transaction and each time I try to check my Recent Transactions it keeps saying Transaction not available at this moment what’s going on ??

**Comment by BGalliotti** [comment]
Hello @bigheartcrx  
Thank you for reaching out to us.

So we can further help, please provide as many of the following details as you can:

- Current device used
- Current operating system for the device
- Current version of the wallet used
- Any log files containing error details
- Error screenshot
- Steps to replicate
- BitPay Wallet ID - To get your Wallet ID, open your BitPay application, then go to Settings > Wallets & Integrations > More Options > Wallet Information.

Please include any other information or screenshot you consider necessary or more explanatory.
Regards

**Comment by BGalliotti** [comment]
Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will be happy to help you.
Thanks
