### ISSUE TITLE
I am getting WALLET_BUSY

### ISSUE THREAD

**Issue by Akhilesh05** [bitpay/copay#8546]
It says wallet is busy, try later.

What is happening?

**Comment by bossx211** [comment]
Me same

**Comment by HB-Dimple** [comment]
I am facing the same issue in the application. Could not update wallet: Wallet_Busy: Wallet is busy, try later.

**Comment by funforkq** [comment]
Me too both coin and cash wallet

**Comment by FaSSt3r** [comment]
Same problem "Could not update wallet: WALLET_BUSY: Wallet is busy, try, later." 10 hours ago

**Comment by sunduk886** [comment]
The same problem.

**Comment by Xorba001** [comment]
same, should not happen, ever, fix this. im new and deposited some coin waiting to setup IT stuff. disappointed that my funds are rendered unavailable. could be grave if someone waits for medical attention.

**Comment by olalawal** [comment]
8 hours here an counting this is anoying

**Comment by rolf1991** [comment]
Same issue. Please fix it. I got some bitcoins this night  but can’t use it !! Horrible

**Comment by Gines88** [comment]
I have this problem

**Comment by boyasia1989** [comment]
Me too. Bitpay in Germany

**Comment by scottcarat** [comment]
me too. WALLET_BUSY: Wallet is busy, try later

**Comment by korneff** [comment]
![4](https://user-images.githubusercontent.com/38942120/39571941-eef8aa46-4ed5-11e8-8d4b-ebca9570b6a2.jpg)

**Comment by thor12341** [comment]
me too. WALLET_BUSY: Wallet is busy, try later
WTFFF FIX THIS!!! any info about this?????????

**Comment by korneff** [comment]
I hope this is not mass theft of money

**Comment by boyasia1989** [comment]
Whathappen if 15 BTC mine ...... go to paradise?

**Comment by boyasia1989** [comment]
We need BITPAY team service !

**Comment by scottcarat** [comment]
Not a good user experience! Hope they can fix this quickly.

**Comment by thor12341** [comment]
im scared FIX THIS haha

**Comment by boyasia1989** [comment]
HOPE Light back. 
I am standing on the top of TRUMP Tower with last paper. 
`http://www.mediafire.com/file/vpcd5a59xpp6hyn/Hue%20Beauty%20Nails%20%26%20Spa.png`

**Comment by boyasia1989** [comment]
[http://www.mediafire.com/file/vpcd5a59xpp6hyn/Hue%20Beauty%20Nails%20%26%20Spa.png](url)

**Comment by korneff** [comment]
7  hours ago (((

**Comment by FaSSt3r** [comment]
already it's working for me

**Comment by SasaWebUp** [comment]
Is this a theft of btc?

**Comment by korneff** [comment]
Ура Ура working  ))

**Comment by scottcarat** [comment]
seems to be working for me now. sent funds out of wallet

**Comment by BGalliotti** [comment]
#8549
