### ISSUE TITLE
Digital Bitbox issue

### ISSUE THREAD

**Issue by mrshodl** [bitpay/copay#8552]
My digital bitbox would not show an available balance today with its bitcoin wallet app. It was working yesterday and this the first time the issue has happened.

the device is working in conjunction with the electrum wallet.

I reset the device back to factory settings and now it wont generate any bitcoin address.

When click on the generate address button it brings up an error 'copayer not found.

The wallet service URL it pulls from is  https://bws.bitpay.com/bws/api

I have informed bitbox support but thought I would also bring it to your attention.

![digi](https://user-images.githubusercontent.com/38954279/39584252-ddb1ca56-4ee9-11e8-81f0-a687833e7632.png)

![url](https://user-images.githubusercontent.com/38954279/39584248-d89faee8-4ee9-11e8-8106-6e5f1308025d.png)

**Comment by matiu** [comment]
You need to contact digital bitbox  regarding this issue.

**Comment by mrshodl** [comment]
i did contact digital bitbox support and they did not help at all.
