### ISSUE TITLE
Btc no in my wallet

### ISSUE THREAD

**Issue by GateP** [bitpay/copay#8559]
Hello
I ve done wire from kraken this morning 
Nothing in my wallet?
Thanks

**Comment by BGalliotti** [comment]
Hello @GateP ,

Thank you for reaching out to us.
Please explain your issue as clearly as possible so we can accurately address a solution for you.

Also please provide as many of the following details as you can:

- Current device used
- Current operating system for the device
- Current version of the wallet used
- Any log files containing error details
- Error screenshot
- Steps to replicate
- BitPay Wallet ID - To get your Wallet ID, open your BitPay application, then go to Settings > Wallets & Integrations > More Options > Wallet Information.

Regards

**Comment by BGalliotti** [comment]
Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will be happy to help you.
Thanks
