### ISSUE TITLE
Not confirmed

### ISSUE THREAD

**Issue by patriots1121** [bitpay/copay#8563]
Sent bitcoins over 2 hrs ago and it is still not confirmed? It has never taken this long.

**Comment by BGalliotti** [comment]
Hello @patriots1121  yesterday we have experienced an outage, that might have been the cause.

Are you still waiting for this transaction to be confirmed?

If so, please provide as many of the following details as you can:
- Transaction
- Current device used
- Current operating system for the device
- Current version of the wallet used
- Any log files containing error details
- Error screenshot
- Steps to replicate
- BitPay Wallet ID - To get your Wallet ID, open your BitPay application, then go to Settings > Wallets & Integrations > More Options > Wallet Information.

Regards

**Comment by patriots1121** [comment]
Why hasn’t my transaction been confirmed?
