### ISSUE TITLE
New version problem

### ISSUE THREAD

**Issue by Boris3333** [bitpay/copay#8564]
Hey, I forgot my 12 words and I have iPhone 6. Still on ios 10.2 if i download newest version of ios can i still have my wallet. BCS don't have 12 words now. I was able to see my wallet 2 months ago.

**Comment by BGalliotti** [comment]
Hello @Boris3333,

**Unfortunately, without the 12-word recovery phrase, you will not be able to recover the wallet and there is no way for us to help with that.**

**As a recommendation for the future, backup your wallet right after creating it and write down the 12-word phrase, store it in a safe place and do not share it with anybody.**

Uninstalling the app without backing your wallet up, will lead to losing your wallet and money.

If there is any other question or concern please let us know.

Regards

**Comment by Boris3333** [comment]
@BGalliotti  i didn't lose my phone. I just cant log in to my wallet because of latest update. Im saying if i update my phone without deleting apps can i see my wallet

**Comment by BGalliotti** [comment]
Hello @Boris3333  

1. 

> Im saying if i update my phone without deleting apps can i see my wallet

Theoretically, yes. Anyways we recommend to backup the wallets before proceeding to update the phone (by updating the phone we understand updating the phone's operative system, iOS in your case).

2.

Without the 12-word recovery phrase, you will not be able to recover the wallet.

**Comment by BGalliotti** [comment]
Hello @Boris3333  the minimum supported version is iOS 10.3, you should update the OS.

If there is any other question or concern please let us know.

Kind Regards

**Comment by Boris3333** [comment]
@BGalliotti  okay but i was able to see my wallet for like 2 years no prob. cant see because of the update. so if i update my phone i can see my wallet again and i can have my 12 words back right ?

**Comment by BGalliotti** [comment]
@Boris3333  we understand, unfortunately, due to development implementations, the minimum required versions of the OS changes along the way.

Regarding the 12-word phrase:

- If you do not have a password set for that wallet, you will be able to see your 12-words:

Open the Copay/Bitpay App > Settings > [your wallet] > backup

- If you have set a password you will need it to do the previous steps.
