### ISSUE TITLE
Wallet sorting in 4.2.0 has a small bug

### ISSUE THREAD

**Issue by JulianTosh** [bitpay/copay#8566]
When I sort my wallets and hit done button, the wallet at the top always shows up at the bottom after I close/reopen. Maybe an index issue.

**Comment by BGalliotti** [comment]
Hello @JulianTosh 

This issue has been added to our Support Request List and we will be reviewing it.
Thanks for your contribution.

**Comment by gabrielbazan7** [comment]
Working well in the current version
