### ISSUE TITLE
BTC Not credited to my wallet

### ISSUE THREAD

**Issue by kayawu** [bitpay/copay#8569]
Hi
Huawei Phone and Android v4.2 Version of copay Used. Before 10hours send BTC to copay Wallet but still Not received
Wallet id:
ab479db1-cde2-4ffe-a95a-a1ba35c0210d

**Comment by BGalliotti** [comment]
Hello @kayawu  
Your wallet is ok, it has received no transactions so far.
Do you any confirmation email, transaction link, or the transaction hash so we can further help?

We look forward hearing from you.
Regards

**Comment by kayawu** [comment]
i sent 0,00408696 BTC from my Binance wallet (withdraw) to my copay wallet:
18Q338JSj8kBL6r2du2wPZmbyeVHRaqirf

Binance does not show any Txid at Transaction details, but it is out

**Comment by BGalliotti** [comment]
@kayawu  

18Q338JSj8kBL6r2du2wPZmbyeVHRaqirf this is the bitpay wallet address you have sent funds to (according to you)

Anyways, you are not going to receive the funds until the transaction is confirmed. 
You must have a transaction link or number, please check it and post it here so we can further help you.

Regards

**Comment by kayawu** [comment]
thanks for the fast replies. it seems Binance did not send me yet a transaction confirmation request via email. i will contact to Binance. 
kind regards

**Comment by BGalliotti** [comment]
@kayawu  Not a problem. 

**We look forward to hearing from you.**

If there is any other question or concern please let us know.

Kind Regards
