### ISSUE TITLE
12phrases

### ISSUE THREAD

**Issue by Supera06** [bitpay/copay#8570]
I forgot 12 phrases. Please tell me how to withdraw Wallet coins.

**Comment by BGalliotti** [comment]
Hello @Supera06 ,

We are sorry you have had this bad experience.

Unfortunately there is nothing we can do on our side.



There is no account or password for the BitPay wallet. Please see https://support.bitpay.com/hc/en-us/articles/115002989283-Why-don-t-I-have-an-online-account-for-my-BitPay-wallet-.

BitPay does not store your private keys or have access to your funds. The BitPay wallet secures your Bitcoin and Bitcoin Cash **only** on your device. To restore your wallet if your device is lost or stolen, you must save the 12-word backup phrase that you receive when you create a wallet. BitPay will not be able to recover your funds.


Learn how to backup and restore a wallet from the backup phrase [here](https://www.youtube.com/watch?v=U23E-dZEuYs).


Thank you for choosing BitPay. If we can answer any further questions, please let us know.
