### ISSUE TITLE
Bitpay app Mac / BCH wallet

### ISSUE THREAD

**Issue by EnacheLucian** [bitpay/copay#8571]
it keep appear on my wallet Bitcoin.com > download available . and send me to GitHub , but here I don t find a release for Mac . And how can I update my wallet to have bitcoincash address , pls help

**Comment by BGalliotti** [comment]
Hello @EnacheLucian  we would like you to better explain your inquiry.

If you want to download the Bitpay wallet for Mac, do it [here](https://github.com/bitpay/copay/releases/download/v4.3.1/BitPay.dmg).

For how to duplicating your wallet to have a BCH wallet check this [article](https://support.bitpay.com/hc/en-us/articles/115005019583-How-Can-I-Recover-Bitcoin-Cash-BCH-from-My-Wallet-)

Don't forget to watch the video within it.

If there is any other question or concern please let us know.
