### ISSUE TITLE
BCH Wallet History Goes Back Before Aug. 1st Fork

### ISSUE THREAD

**Issue by jameswalpole** [bitpay/copay#8572]
BCH wallet duplicated from a BTC wallet is showing a BCH transaction history dating back before the creation of BCH itself. 

I'm using 4.2.0 on mobile (Android) and 4.3.0 on desktop (MacOS) 

![screen shot 2018-05-05 at 1 27 46 pm](https://user-images.githubusercontent.com/9257396/39665848-3ad1b23a-5068-11e8-97c5-e7ecd1b6140d.png)

**Comment by jameswalpole** [comment]
From a UX standpoint, I recommend not showing BCH transactions going back before wallet split – that transaction history is available in the origin BTC wallet

Maybe it could be an advanced feature to view pre-fork history, but for average user I could see this really throwing them off.

This must be a newer thing, because I don’t recall seeing the history shown this way before.

(Or, if you show the pre-fork history, label the pre-fork transactions with BTC and not BCH denomination) + carry over the transaction memo information from the origin wallet (if possible).

**Comment by matiu** [comment]
BCH chain goes back to the origin of bitcoin, I think it is the right desition for any fork
