### ISSUE TITLE
Wallet error 403 Forbidden 

### ISSUE THREAD

**Issue by Shubak** [bitpay/copay#8578]
I have sent BTC to my wallet. But it shows that there is an error 403.  I have downloaded the latest version of the copay wallet, still no change.

**Comment by BGalliotti** [comment]
Hello @Shubak 
Please try changing the way how you get connected to the internet

If you are in any of these countries, you wil not be able to use bitcoin services:
- Cuba, Iran, Syria, Sudan and N. Korea

If there is any other question or concern please let us know.

**Comment by Shubak** [comment]
Solved the issue by downloading copay wallet to my phone
