### ISSUE TITLE
HELP! could not update wallet, wallet needs address scan

### ISSUE THREAD

**Issue by Wokeface** [bitpay/copay#8594]
I'm in my copay bitcoin wallet in both iOS and android logged in. But it says "could not update wallet : WALLET_NEED_SCAN: wallet needs addresses scan. Tap to retry "
Please help me access my coins!!!

**Comment by BGalliotti** [comment]
Hello @Wokeface  

Thank you for reaching out to us.
We are sorry you have had this bad experience.

**Please make sure You are properly connected to the internet.**

**Then open up your BitPay app and try the following steps:**

- ("Settings" > "Wallet" > "More Options" > "Transaction History" > "Clear cache")
- ("Settings" > "Wallet" > "More Options" > "Wallet Addresses" > "Scan addresses for funds")

**Please do not uninstall the app or delete the wallet if you did not back it up properly, in such case, please do so. This is the only way to recover your wallet.**

If you need any further assistance please provide as many of the following details as you can:**

- Current device used: Phone model 
- Current operating system version for the device: iOS, Android..
- Current version of the wallet used: Bitpay App > Settings > About bitpay 
- Any log files containing error details: Bitpay App > Settings > About bitpay > Session Log > Tap on the Upper right corner (three dots) > Send by email (you can screenshot the content as well and attach the images to your e-mail. In such case, please make sure you move the slider to "Debug").
- Error screenshot: On [iPhone](https://apple.co/1DAB204) on [Android](https://www.wikihow.tech/Take-Screenshots-on-an-Android)
- Steps to replicate: Steps needed for the error to appear.
- BitPay Wallet ID - To get your Wallet ID, open your BitPay application, then go to Settings > Wallets & Integrations > More Options > Wallet Information.

**We look forward to hearing from you.**

Kind Regards.

**Comment by Wokeface** [comment]
It worked like a charm!!
Thank you for your quick reply!!
