### ISSUE TITLE
Custom fee setting removed?

### ISSUE THREAD

**Issue by Mirobit** [bitpay/copay#8597]
Why was the custom fee setting removed?
Currently 1 sat/byte transactions get confirmed within one block but "Super Economy" suggestes 4 sats/byte.

**Comment by BGalliotti** [comment]
Hello @Mirobit,

The option is still available.

Please do the following:

Bitpay wallet > Send > Enter recipient > Enter amount >Tap on "Bitcoin Miner Fee" > Tap on the Fee level dropdown.

There you have the **Custom** option.

If there is any other question or concern please let us know.
Regards.

**Comment by Mirobit** [comment]
@BGalliotti Thanks for your reply. But I don't have this option if I scan a BitPay QR Code. Than it says "Recommended Fee" which can't be changed. This is really anoying, since the recommendation is even with an empty mempool way too high.

**Comment by BGalliotti** [comment]
Hello @Mirobit ,

Thanks for reaching out to us.
That is true, in that case the merchant suggests a fee which will let the transaction go through the network and get confirmed as fast as possible, and it cannot be changed.

Please let us know if you have any additional questions.
Kind regards.
