### ISSUE TITLE
I can't send out funds from my wallet

### ISSUE THREAD

**Issue by dguzman7** [bitpay/copay#8612]
Hi,

I'm having this problem with my wallet. I'm trying to send out some funds, I already add the destiny account but when i'm going to do the transfer the app says that i don't have enough funds, but i recieved the money i suposse send out with, and got 6+ confirmations so far. I don't know what to do.

**Comment by BGalliotti** [comment]
Hello @dguzman7 

Thank you for reaching out to us.

**So we can further help, please provide as many of the following details as you can:**

- Current device used: Phone model 
- Current operating system version for the device: iOS, Android..
- Current version of the wallet used: Bitpay App > Settings > About bitpay 
- Any log files containing error details: Bitpay App > Settings > About bitpay > Session Log > Tap on the Upper right corner (three dots) > Send by email (you can screenshot the content as well and attach the images to your e-mail. In such case, please make sure you move the slider to "Debug").
- Error screenshot: On [iPhone](https://apple.co/1DAB204) on [Android](https://www.wikihow.tech/Take-Screenshots-on-an-Android)
- Steps to replicate: Steps needed for the error to appear.
- BitPay Wallet ID - To get your Wallet ID, open your BitPay application, then go to Settings > Wallets & Integrations > More Options > Wallet Information.

**We look forward to hearing from you.**
