### ISSUE TITLE
COPAY wallet history does not open

### ISSUE THREAD

**Issue by usagitan666** [bitpay/copay#8613]
COPAY wallet history does not open

**Comment by BGalliotti** [comment]
Hello @usagitan666 could you please better explain your problem?

**So we can further help, please provide as many of the following details as you can:**

- Current device used: Phone model 
- Current operating system version for the device: iOS, Android..
- Current version of the wallet used: Bitpay App > Settings > About bitpay 
- Any log files containing error details: Bitpay App > Settings > About bitpay > Session Log > Tap on the Upper right corner (three dots) > Send by email (you can screenshot the content as well and attach the images to your e-mail. In such case, please make sure you move the slider to "Debug").
- Error screenshot: On [iPhone](https://apple.co/1DAB204) on [Android](https://www.wikihow.tech/Take-Screenshots-on-an-Android)
- Steps to replicate: Steps needed for the error to appear.
- BitPay Wallet ID - To get your Wallet ID, open your BitPay application, then go to Settings > Wallets & Integrations > More Options > Wallet Information.

In the meantime please try the following:

**Please open up your BitPay app and try the following steps:**

- ("Settings" > "Wallet" > "More Options" > "Transaction History" > "Clear cache")
- ("Settings" > "Wallet" > "More Options" > "Wallet Addresses" > "Scan addresses for funds")

**Please do not uninstall the app or delete the wallet if you did not back it up properly, in such case, please do so. This is the only way to recover your wallet.**

If you need any further assistance, please let us know.

**We look forward to hearing from you.**
