### ISSUE TITLE
Problem with recovery

### ISSUE THREAD

**Issue by j4nos** [bitpay/copay#8620]
I have some Bitcoin saving in Copay. Bought a new phone and try to restore the wallet, but after put in 12 words, balance is 0.00 and no transaction found. Do you have any idea? Do I lost all my money?

**Comment by BGalliotti** [comment]
Hello @j4nos 

Please make sure the wallet you are recovering is the wallet that has the funds.

**Please open up your BitPay app and try the following steps:**

- ("Settings" > "Wallet" > "More Options" > "Transaction History" > "Clear cache")
- ("Settings" > "Wallet" > "More Options" > "Wallet Addresses" > "Scan addresses for funds")

**Please do not uninstall the app or delete the wallet if you did not back it up properly, in such case, please do so. This is the only way to recover your wallet.**

If you need any further assistance, please let us know.

**Comment by j4nos** [comment]
It appeared 3 address after scan. One of the is the proper one. Copied. What to do next?

**Comment by BGalliotti** [comment]
Hello @j4nos ,

After finding addresses with funds your funds should be refreshed automatically.
Please try restarting your phone, and repeating the steps we sent you previously.

If there is any other question or concern we can help you with please let us know.
Kind regards.

**Comment by j4nos** [comment]
I repeated many times, I know the 12 words, but I can not get my balance. Please help.

**Comment by BGalliotti** [comment]
Hello @j4nos 

Thank you for reaching out to us.

**So we can further help, please provide as many of the following details as you can:**

- Current device used: Phone model 
- Current operating system version for the device: iOS, Android..
- Current version of the wallet used: Bitpay App > Settings > About bitpay 
- Any log files containing error details: Bitpay App > Settings > About bitpay > Session Log > Tap on the Upper right corner (three dots) > Send by email (you can screenshot the content as well and attach the images to your e-mail. In such case, please make sure you move the slider to "Debug").
- Error screenshot: On [iPhone](https://apple.co/1DAB204) on [Android](https://www.wikihow.tech/Take-Screenshots-on-an-Android)
- Steps to replicate: Steps needed for the error to appear.
- BitPay Wallet ID - To get your Wallet ID, open your BitPay application, then go to Settings > Wallets & Integrations > More Options > Wallet Information.

**We look forward to hearing from you.**

**Comment by j4nos** [comment]
Phone: iPhone 5s
OS: 11.3.1 (15E302)
Copay version: v4.3.5

I see only one warning, no error: `[warn] GetLowUtxos null`

**Comment by BGalliotti** [comment]
Hello @j4nos ,

Thanks for all the information provided.

Please send us your wallet ID so we can check what is wrong with it.

BitPay Wallet ID - To get your Wallet ID, open your BitPay application, then go to Settings > Wallets & Integrations > More Options > Wallet Information.

**We look forward to hearing from you.**

**Comment by j4nos** [comment]
Wallet ID: `1BokrdmYceffmuNujKDSAz9YtDMZMpv71R`

**Comment by BGalliotti** [comment]
Hello @j4nos ,
´1BokrdmYceffmuNujKDSAz9YtDMZMpv71R 

is not your wallet ID, it is an address.

**There are no transactions related to that [address](https://live.blockcypher.com/btc/address/1BokrdmYceffmuNujKDSAz9YtDMZMpv71R/)**

Also the bitpay wallet related to that address has no funds neither transactions.

**Find your wallet address here:**

BitPay Wallet ID - To get your Wallet ID, open your BitPay application, then go to Settings > Wallets & Integrations > More Options > Wallet Information.

Thanks, regards.

**Comment by j4nos** [comment]
`11148fc8-974b-4c7f-b4cd-5f7feeaa4cf7`

**Comment by BGalliotti** [comment]
Hello @j4nos ,

Yes that is your wallet iD and the address you have provided us belongs to that wallet.

Here is your wallet report:

`* Wallet info
  ID: 11148fc8-974b-4c7f-b4cd-5f7feeaa4cf7 Coin: btc
  LIVENET 1-of-1 [BIP44 P2PKH] wallet (status: complete)
  Created on: Wed Sep 14 2016 18:54:01 GMT-0300

* Balance
  Total: 0.00000000 btc (0.00000000 btc locked)
  Confirmed: 0.00000000 btc (0.00000000 btc locked)
  Available: 0.00000000 btc (0.00000000 btc confirmed / 0.00000000 btc unconfirmed)

* No pending tx proposals.

* Main addresses (not including change addresses)
  [Wed Sep 14 2016 18:54:29 GMT-0300] 1BokrdmYceffmuNujKDSAz9YtDMZMpv71R (m/0/0)
  [Fri May 11 2018 11:44:30 GMT-0300] 1CuUrXLRs9DYVBLVskHcK4se68ABvHDgyz (m/0/1)
  [Fri May 11 2018 19:18:47 GMT-0300] 1NZuPRKQvztrZXp2rZc5BkX8JB4brMHjcS (m/0/2)
  [Tue May 15 2018 06:57:48 GMT-0300] 1M2M5FLuPRrYwEwB8zhPcC3azcwB2bTcis (m/0/3)

* No tx history.
`
These wallet has no transactions. 

Please check if you have other wallets.

Regards.

**Comment by djjames** [comment]
dude

**Comment by j4nos** [comment]
Downloaded sourcecode of Copay. How can I build and run it on my iPhone? I do not find the Xcode project file.

**Comment by BGalliotti** [comment]
Hello @j4nos ,

The wallet you mention does exist but it is a different one.

You should for the 12-word passphrase and restore it, everything should go well
If there is any other question or concern we can help you with please let us know.
Regards.
