### ISSUE TITLE
I bought btc. Didnt come to wallet.

### ISSUE THREAD

**Issue by kaijin007** [bitpay/copay#8621]
I bought a btc from btc atm. But btc didnt come to my wallet

**Comment by BGalliotti** [comment]
Hello @kaijin007  transactions usually take some time. 

Your funds might be arriving to your wallet.

You can check the transaction status here: https://insight.bitpay.com/ entering the transaction hash (the numbers and letters string)

Please let us know if there is any issue.

Regards
