### ISSUE TITLE
Which download for me?

### ISSUE THREAD

**Issue by swdb2018** [bitpay/copay#8624]
I want a wallet for Windows 7 32-bit PC operating system. Please give me a link.

**Comment by BGalliotti** [comment]
Hello @swdb2018 ,

**The desktop version of the wallet is only available in 64-bit.**

You can download the mobile version on the [App Store (iOS)](https://itunes.apple.com/us/app/bitpay-secure-bitcoin-wallet/id1149581638) or [Google Play Store (Android)](https://play.google.com/store/apps/details?id=com.bitpay.wallet) depending on what version do you have.

If you need any further assistance please open a new ticket.

Thank you for your interest and support.
