### ISSUE TITLE
Transfer not received into my wallet

### ISSUE THREAD

**Issue by KadarMarine** [bitpay/copay#8625]
While it is not unusual for a transaction like this to be delayed for a few hours, it has been nearly 12 hours since NiceHash transferred 0.03018520 BTC into my wallet. Why is this transfer (payment) not showing up in my copay account after almost half a day?

**Comment by BGalliotti** [comment]
Hello @KadarMarine , 

Depending on the fees some transactions can take more time to be confirmed.

Please post your wallet ID and transaction, so we can give you assistance with this question.

- BitPay Wallet ID - To get your Wallet ID, open your BitPay application, then go to Settings > Wallets & Integrations > More Options > Wallet Information.

Typically a transaction is a number like this:  8a5aa879ef0db0cc82c02a5a54986d077babd976b4c183ae5322d6685e445043.

you might have a link to it, both are useful for us.

**We look forward to hearing from you.**

**Comment by KadarMarine** [comment]
Thank you for your response.

My Wallet ID is:
1LWUJd8yhuLhQkig522FG1RQJDTxK2TbHu

The Transaction Number is:
aece696404169239d20d09108aa026e985565fe13500aa03effb895c673bf761

Regards,
Keith Davis

**Comment by BGalliotti** [comment]
Hello @KadarMarine ,

We are reviewing your transaction. In the meantime, note your transaction has 201 outputs (a typical P2P transaction has 1 output) so this transaction is going to be very costly in terms of fees and also if it has low fees is going to take a long while to be confirmed, so a delay would be very expectable.

**Comment by KadarMarine** [comment]
Thank you for the explanation.

Regards,
Keith Davis

**Comment by BGalliotti** [comment]
Not a problem @KadarMarine .

Regards.
