### ISSUE TITLE
I sent btc. After 12 hours doesn't confirmed and transaction lost.

### ISSUE THREAD

**Issue by Geirge** [bitpay/copay#8627]
I sent 0.55 btc to 3JaDkW8mga1Mhth6V4QgRuMPyxkmg7wVvd with txid 8de570f15f1ebd20f7c83e54dc2c856260fa28dc4179daefb49003b237402c33

Help please!

**Comment by BGalliotti** [comment]
Hello @Geirge,

Thanks for reaching out to us.

We have checked your transaction, it has no confirmations yet but it was already broadcasted (sent to the bitcoin network).

It will take a while until the transaction is confirmed.

If there is any other question or concern we can help you with please let us know.

Kind regards.
