### ISSUE TITLE
  transaction not confirmed

### ISSUE THREAD

**Issue by Blancaguado** [bitpay/copay#8629]
Goodnight,

I have made two withdrawals from my copay wallet, one at 9:20 in the morning and another at 13:00 p.m. today, May 11 and it has not yet reached the shipping wallet, what worries me is that when I look to see how the transaction goes in the blockchein tells me that it is not found, that there are no transactions with that address, I send both directions.

35ZBG12eYUDrYDe4iQzijiCjXhzd6GHT3e

36Jb6NsR48i2x5biZ2NkHmP1JFVUk4udYh

ID WALLET     424a7e38-3bd9-4ef6-b3d3-c50bcfdc87bf

Could you help me solve the problem?

Thank you

**Comment by BGalliotti** [comment]
Hello @Blancaguado
Thanks for reaching out to us.  We are sorry you have had this bad experience.

It must have been a matter of time. As you can see below, both transactions are confirmed (6+ confirmations)

https://live.blockcypher.com/btc/address/35ZBG12eYUDrYDe4iQzijiCjXhzd6GHT3e/

https://live.blockcypher.com/btc/address/36Jb6NsR48i2x5biZ2NkHmP1JFVUk4udYh/

Both transaction are showing up in your wallet as well.

Feel free to get back to us in case you have any questions or concerns.
