### ISSUE TITLE
12-word backup phrase file location on android ?

### ISSUE THREAD

**Issue by Synless** [bitpay/copay#8632]
Hi,
I had an unexpected factory reset of my android phone. I manage to recover most of the files as text files with shuffled numbers as name. I now digging into thousands of files with homemade C# program to try to find keywords within those files.
I remember my spending password but I wish to find either the 12 words or the private key, being hashed or not.

Thanks for any help provided.

**Comment by BGalliotti** [comment]
Hello @Synless, 

The 12-word recovery phrase is not stored in your device, and is not a kind of "password".

It is a set of words which is translated to a number that corresponds to a wallet. 
Thank you for your interest and support.
If there is any other question or concern we can help you with please let us know.

**Comment by Synless** [comment]
I know that the 12 words are supposed to recreate the private key, I am not new to crypto.

If it is not stored on the device then where ?
