### ISSUE TITLE
Can not recover Copay balance with 12 recovery passphrase

### ISSUE THREAD

**Issue by j4nos** [bitpay/copay#8637]
I backed up my Copay wallet with 12 recovery passphrase. My phone went wrong so tried to recover it on an other phone, but balance is 0.00. After back up, I sent some amount from that balance. Tried also this approach to import wallet:

"Settings" > "Wallet" > "More Options" > "Transaction History" > "Clear cache"
"Settings" > "Wallet" > "More Options" > "Wallet Addresses" > "Scan addresses for funds"

I get money in 2015 to this address: 1DpmSrg9Bur2VhiMqEu4gYnA28gaM7ZVjp

Did I need to back up and save 12 recovery passphrase after each initiated transaction to keep my money safe?

**Comment by BGalliotti** [comment]
Hello @j4nos ,You do not need to backup your recovery phrase after each transaction.

The 12-word recovery phrase, is needed to recover the wallet and does not change over time.
If there is any other question or concern we can help you with please let us know.
