### ISSUE TITLE
Copay Chrome extension no longer supported

### ISSUE THREAD

**Issue by ANTOCORT** [bitpay/copay#8645]
I have tried to send BTC from the Cpoay extension of my browser and I have not succeeded. Skrill gives me an encrypted address. When I copy the payment URL and try to paste it into the recipient's box, the following message appears: the payment protocol is not supported in Chrome. What should I do since it is the only APP that supports my PC? Thanks.

**Comment by BGalliotti** [comment]
Hello @ANTOCORT ,

The Copay Chrome extension is no longer supported and has no support. Anyways it is somehow working.
Please install the Copay Desktop version.

Follow #8532  for instructions on the installation process.

If you have any other questions please let us know.

kind regards.
