### ISSUE TITLE
Bch lost

### ISSUE THREAD

**Issue by GateP** [bitpay/copay#8647]
Hello
I ve sent bcc (2440€) 2 days ago
I ve nothing in my wallet
https://blockchair.com/bitcoin-cash/address/qz54u7mga9vm647dnvx9ncnufv3w9cl7xqlsw3c67s
What can i do?
Thanks
￼

**Comment by BGalliotti** [comment]
Hello @GateP ,

Thanks for reaching out to us.

You have sent BCH to a BTC wallet. To try to recover your funds please follow the guide on #8586 (BGalliotti's post).

Feel free to get back to us in case you have any questions or concerns.

Kind Regards

**Comment by GateP** [comment]
Hello

Sorry non BCH founded

Thks for your advise



2018-05-16 15:28 GMT+02:00 BGalliotti <notifications@github.com>:

**Comment by BGalliotti** [comment]
Hello @GateP 
We appreciate your feedback.
If there is any other question or concern we can help you with please let us know.

Kind regards.

**Comment by Richie202a** [comment]
@GateP 
did you restore your lost bch? if you couldn't, reach me at : anywalletrecovery@gmail.com I can restore it
