### ISSUE TITLE
How to build Copay source code?

### ISSUE THREAD

**Issue by j4nos** [bitpay/copay#8648]
Hi! Cloned source code of Copay. How can I build and run it on my iPhone? I do not find the Xcode project file.

**Comment by BGalliotti** [comment]
Hello @j4nos  ,

Thanks for reaching out to us.

One of our developers is going to take care of your inquiry.

We would appreciate your patience, thanks in advance.
Kind regards.

**Comment by j4nos** [comment]
Looking forward to get some help.

**Comment by gabrielbazan7** [comment]
The steps are in the readme file.  For IOS: 

```
npm run clean-all
npm run apply:copay
npm run prepare:copay
npm run start:ios 
```

The Xcode will open automatically with the project.
