### ISSUE TITLE
missing btc

### ISSUE THREAD

**Issue by jaylingo** [bitpay/copay#8650]
went to make a transaction and now by btc is gone doesnt show up on transaction
deposited 0.02 used 0.01 now 0.01 missing....

fc1c7585-033c-4b7c-b9ba-3a8a27647c49 wallet id

**Comment by BGalliotti** [comment]
Hello  @jaylingo ,

Thanks for reaching out to us.

Please send us the transaction hash (something like this "d0a23876de7cf87574b5cda7557bcc8af5d84f3fd1e6f4c6063fd6b72b0e69ae") or a link (if you have that) so we can further investigate.

If there is any other question or concern we can help you with please let us know.
Kind regards.
