### ISSUE TITLE
Wrong transactiom 

### ISSUE THREAD

**Issue by Ivanryz** [bitpay/copay#8654]
Invalid transaction. I made a transaction on the wallet after 15 minutes. At this time, the transaction history is also unavailable. what should I do? Can I cancel a transaction?

**Comment by Ivanryz** [comment]
https://insight.bitpay.com/tx/dd161a98b28adc4cb8005a2d574cc3ce74cca393cb736f9a342d246cf14996a9

**Comment by BGalliotti** [comment]
Hello  @Ivanryz ,

Thanks for reaching out to us.
As we could check, the transaction is properly confirmed, the funds reached the destination address and the funds are unspent.

The transaction is properly shown in the wallet transaction history.

If there is any other question or concern we can help you with please let us know.
Kind regards.
