### ISSUE TITLE
Are you blocking me?

### ISSUE THREAD

**Issue by greggluhring** [bitpay/copay#8655]
BGalliotti I don't know what's happening here but I came here for help because I've lost a total of $500 so far using CoPay. I came back just now to check if you'd answered my request for help after I clarified and both of my requests have been removed from your issues forum.

I had a feeling there was something not right here but I gave you the benefit of the doubt. You could probably see that I'd even changed the inflammatory title of my last post to something more appropriate.

I need some help here to recover my coins. If I can't get it from you, I'll take the issue to GitHub and to BitPay and whoever else might listen.

I hope I'm over reacting but in looking at your solutions for other users here, the inconsistency of the help you are providing and the articles I've read about CoPay elsewhere, You might be looking at some heat coming your way.

I don't see any place else to post this but in Issues so here is is for all to see.

GL

**Comment by BGalliotti** [comment]
Hello  @greggluhring ,

Thanks for reaching out to us.

We are sorry you have had this bad experience.

We want to tell you we are not blocking you. We just try to keep things tidy, same questions/concerns/problems in the same thread and also try to clear the clutter. 

We did not remove your posts, we just closed them and for the aforementioned reason is why we encouraged you to refer to one of the related existing threads.

Github only shows the open issues. If you search by keywords or google your post, you will find it, it is still there.

We apologize if there was any inconsistency in our answers. 

Please if you could not solve your issue yet, post your concerns on the thread # 8586, we will follow up with you there.

Hope our explanations help.

We are going to close this thread. Please if you a have a different issue, open a new thread and we will be happy to help you.

Kind regards.
