### ISSUE TITLE
Bitcoin not received

### ISSUE THREAD

**Issue by onyebuchi123** [bitpay/copay#8657]
BTC was transfered to my address but I'm yet to receive it.  This is the batch f8c6c836ad458c9c6d780318d6e025331c2cc35bb07a89aa3b188029f0ddb83d
 and my wallet address is 1NzzmDPcNJ6N7vfav8UbXNj6AiQ5DDyXxv

**Comment by BGalliotti** [comment]
Hello  @onyebuchi123 ,

Thanks for reaching out to us.
As we could check, the transaction is properly confirmed, the funds reached the destination address and the funds are unspent.

The transaction is properly shown in the wallet transaction history.
**Please open up your BitPay app and try the following steps:**

- ("Settings" > "Wallet" > "More Options" > "Transaction History" > "Clear cache")
- ("Settings" > "Wallet" > "More Options" > "Wallet Addresses" > "Scan addresses for funds")

**Please do not uninstall the app or delete the wallet if you did not back it up properly, in such case, please do so. This is the only way to recover your wallet.**

If there is any other question or concern we can help you with please let us know.
Kind regards.

**Comment by onyebuchi123** [comment]
It has appeared on my wallet thanks.

**Comment by BGalliotti** [comment]
@onyebuchi123  Excellent!

Thanks for the update, we are happy to know it worked!

best regards.
