### ISSUE TITLE
Send funds to Skrill. Windows 32 bit

### ISSUE THREAD

**Issue by ANTOCORT** [bitpay/copay#8658]
Hello. 
Mi problem is the following:

I want to send funds to Skrill through Bitpay / Copay but the applications that offer for PC do not support my system that is 32 and not 64Bits. On the other hand ,
Edward (BitPay Support Team), told me to install a Google Play Store application. Well, I downloaded it and added funds to the purse, but now it does not work.
Now I wonder what I should do.
Thanks

**Comment by BGalliotti** [comment]
Hello  @ANTOCORT ,

Thanks for reaching out to us.
We will need more information to address your inquiry.

What do you mean exactly by this:

> Well, I downloaded it and added funds to the purse, but now it does not work.

If there is any other question or concern we can help you with please let us know.
Kind regards.

**Comment by ANTOCORT** [comment]
Well, here you are my problem: I want to send funds to Skrill through Bitpay / Copay but the applications that offer for PC do not support my system that is 32 and not 64Bits. On the other hand ,
Edward (BitPay Support Team), told me to install a Google Play Store application. Well, I downloaded it and added funds to the purse, but now it does not work.
Now I wonder what I should do.
Thanks

**Comment by BGalliotti** [comment]
Hello  @ANTOCORT ,

Thanks for reaching out to us.

We understand what you mentioned about your 32bit system.

What we do not completely understand is what is not working, punctually this phrase:
> Well, I downloaded it and added funds to the purse, but now it does not work.

For us to help you solve the issue, please provide more information and detailed explanation of what "does not work"

This could be useful as a guidance;

- Current device used: Phone model 
- Current operating system version for the device: iOS, Android..
- Current version of the wallet used: Bitpay App > Settings > About bitpay 
- Any log files containing error details: Bitpay App > Settings > About bitpay > Session Log > Tap on the Upper right corner (three dots) > Send by email (you can screenshot the content as well and attach the images to your e-mail. In such case, please make sure you move the slider to "Debug").
- Error screenshot: On [iPhone](https://apple.co/1DAB204) on [Android](https://www.wikihow.tech/Take-Screenshots-on-an-Android)
- Steps to replicate: Steps needed for the error to appear.
- BitPay Wallet ID - To get your Wallet ID, open your BitPay application, then go to Settings > Wallets & Integrations > More Options > Wallet Information.

**We look forward to hearing from you.**
If there is any other question or concern we can help you with please let us know.
Kind regards.
