### ISSUE TITLE
Why you don't create components?

### ISSUE THREAD

**Issue by SexyAtlas** [bitpay/copay#8670]
Hi, I've been working with angular 4 for the past couple month in my work, and I'd like to contribute with you in my spare time, but reading your code It seems that you don't use components (well you have one but you could use more), and I was wondering if that was a design mode of work, or just you haven't need them.

**Comment by bitjson** [comment]
@SexyAtlas fantastic! We'd love to take contributions.

It's not a design choice, we're just still refactoring much of the older AngularJS code. We'd love to get everything refactored into cleaner, reusable components. If you're willing to take a swing at it, we'd love to pull in your work!

**Comment by bitjson** [comment]
You can see @msalcala11 contributed the first proper component here: https://github.com/bitpay/copay/tree/master/src/components

It's also a great example of how to test components: https://github.com/bitpay/copay/blob/master/src/components/expandable-header/expandable-header.spec.ts

PRs welcome!
