### ISSUE TITLE
 update to v4.3.5 from v3.15.2-fails ACCESS DENIED-WINDOWS

### ISSUE THREAD

**Issue by kirksu** [bitpay/copay#8671]
During Install, I received an error message.  "Access Denied"  when the new install tried to delete and replace a file.
Should I ignore the error and continue with the install?  Please advise.
Please see  attached screen shot of error message. 

![copay update to v4 3 5 from v3 15 2-fails]
(https://user-images.githubusercontent.com/33265263/40285840-0bca24de-5c5e-11e8-8b8b-bf9861ea8cff.JPG)

**Comment by BGalliotti** [comment]
Hello @kirksu  ,

Thanks for reaching out to us.

That seems to be a Windows issue. 

You might need to install the app signing into an Administrator account or you can try running the installation as an administrator. Please check this [article](https://www.tenforums.com/tutorials/3436-run-administrator-windows-10-a.html).

Also, make sure you do not have the wallet app open when trying to uninstall/update. The OS is using the files so it probably would not let any application, modify those files in execution


If there is any other question or concern we can help you with please let us know.
Kind regards.

**Comment by kirksu** [comment]
HI thanks so much for the quick reply.  I had the old version open on my
computer while trying to install the new one.  Duh.  The install went
without a hitch when I tried it with the old version closed.
Thanks again.
Kirk
www.casabambu.com
US phone: 512-646-2658
CR phone: +506-4000-2148

Like us on Facebook <http://www.facebook.com/casabambu>
Follow us on Twitter <https://twitter.com/Casa_Bambu>

**Comment by BGalliotti** [comment]
@kirksu  Not a problem! 

We are glad you overcame the issue.

Kind regards
