### ISSUE TITLE
Address URI using bchtest with amount is not recognized

### ISSUE THREAD

**Issue by stepierc** [bitpay/copay#8672]
URIs that scan and work as expected:
bitcoincash:qzk5zzcvzd209xskquns5eq4cqpf0py59cpzwz3rut?amount=0.05 
bchtest:qzk5zzcvzd209xskquns5eq4cqpf0py59cpzwz3rut

URI that is not recognized as a valid URI (no option to send) when scanned:
bchtest:qzk5zzcvzd209xskquns5eq4cqpf0py59cpzwz3rut?amount=0.05 

Adding amount query parameter to the working bchtest URI seems to make it fail.

**Comment by gabrielbazan7** [comment]
Thanks for the report. We will check

**Comment by gabrielbazan7** [comment]
This works fine.
