### ISSUE TITLE
bch-insight.bitpay.com is showing incorrect balances

### ISSUE THREAD

**Issue by BGalliotti** [bitpay/copay#8677]
Hello,

bch-insight.bitpay.com is showing **incorrect balances** for some addresses.

Example:

**qqnlkglzevnvrgefype52hdc7mapnlqwmuptutgf8c** has a balance of **37,713.10941936 BCH** 
on *blockchair.com* and *bch.btc.com*, but **14,942.12998416 BCH on bch-insight.bitpay.com**.

**Links here:**

- [Insight](https://bch-insight.bitpay.com/#/address/qqnlkglzevnvrgefype52hdc7mapnlqwmuptutgf8c)
- [BlockChair.com](https://blockchair.com/bitcoin-cash/address/qqnlkglzevnvrgefype52hdc7mapnlqwmuptutgf8c)
- [bch.btc.com](https://bch.btc.com/14eQD1QQb8QFVG8YFwGz7skyzsvBLWLwJS)

Kind Regards.

**Comment by matiu** [comment]
Please open this on insight-api repo, it is not related to Copay.

**Comment by BGalliotti** [comment]
thanks @matiu .
