### ISSUE TITLE
Added network fee on BitPay invoices is incorrect

### ISSUE THREAD

**Issue by MarkWalken** [bitpay/copay#8680]
Hi Team,

I recently ran into an excessively high added "network fee" on your invoice when I went to checkout. 

During the time of the Bitcoin invoice, 10 sat/byte was more than enough for a very quick transaction. (Only 800~ transactions were in the mempool with that fee or higher). This works out to about 10 cents USD for a 226 byte transaction. The added network fee on your Bitpay invoice was $1.32. How is that necessary or realistic?

Can you please advise how we can work together on improving the added network fee on your invoices, and how they are calculated? They are not matching what current market demands are - we shouldn't have to pay for what the transaction costs MIGHT be in the future, we should only have to pay what they are at that point in time.

Thank you for your help. Please note I was using Earn's API at the time of transacting. The $1.32 added fee on your invoice was not representative of current network conditions. 

Also, please note that I recognize the difference between the transaction fee on my transaction (the fee I'm paying to send the transaction to Bitpay), and the added network fee that you automatically add into the invoice.

Thank you!

**Comment by matiu** [comment]
This is unrelated to Copay, but to Bitpay.com payment processing software.

**Comment by MarkWalken** [comment]
@matiu BitPay support directed me directly to this Github repository. Can you share it with the appropriate team? If not, where should I share it?

**Comment by matiu** [comment]
@MarkWalken sorry for the confusion, I will direct the ticket to the right person and updat you on the progress.

**Comment by MarkWalken** [comment]
Hi Matias,

Hope you're well! I wanted to follow up on the below to see if you had an
update?

I also wanted to ask about a separate issue - I recently paid a BitPay
invoice, and immediately I received the standard email of "Your included
network fee was too low", and proceeded to explain how network fees work.

Then, however, the transaction confirmed less than 10 minutes later (I
confirmed how busy the mempool was before sending). So, I think that
possibly for those automated emails, the team might need to rethink which
fees are actually "low".

Thank you your help!

**Comment by matiu** [comment]
Hi @MarkWalken .

Please see https://support.bitpay.com/hc/en-us/articles/115002990803-What-is-the-Network-Cost-fee-on-BitPay-invoices-and-why-is-BitPay-charging-it-

network fees are the needed fee to move the coins in the required time in and out of Bitpay. The fee estimation itself, is provided by the bitcoin client (bitcoin core) thru the RPC call estimatefee. It  is an estimation, and therefore it can happen it is higher or lower than the actual value.

**Comment by MarkWalken** [comment]
Hi Matias,

I work for BRD (cryptocurrency wallet), and I think you accidentally
misread my email. The automated email your team sends out when you pay for
an invoice (network fee too low) is too strict in regards to fees in my
opinion. Users shouldn't have to include a fee on the transaction that
guarantees the next block confirmation to avoid that automated email.

There should be more leeway to avoid that automated email, for example if
you see that it should confirm within the next 4-6 blocks, then the email
shouldn't be sent.

Thank You,

**Comment by matiu** [comment]
Hi Mark,

I understand you point but I dont think that is the case.

Bitpay only assures the exchange rate for 15 min. That is a risk way beyond
most exchanges. Supporting transactions that confirm in 4/6 blocks would
mean Bitpay will only be able to exchange the coins for the merchant in
40-60 minutes after issuing the exchange rate, which is unacceptable.

I am.only telling you my version of it. I dont work for payment processing
and you should ask this questions to support@bitpay.com. this repo is for
the wallet issues

Thanks!
Matias

**Comment by MarkWalken** [comment]
Hi Matias,

I see where the confusion lies.

I thought I was talking to BitPay. Whoever did the CC for me in May (I’ve
been waiting since May for a response) accidentally sent me to Copay. (I
originally emailed BitPay, so I don’t know how this occurred)

Thanks for your help. BitPay doesn’t require a confirmation within 15
minutes however, they only require that the transaction is broadcast within
15 minutes to honor the exchange rate of the invoice.
