### ISSUE TITLE
BCH generated address not valid

### ISSUE THREAD

**Issue by jandrop** [bitpay/copay#8681]
The BCH address generated to receive is not valid:

### Steps to reproduce:
1. Add a BCH Wallet
2. Go received menu
3. Generate new address
4. Go to kraken or another site to check the address like [here](https://www.blocktrail.com/BCC)

### Actual result:
The address is not valid
### Expected result:
The address should be valid.

**Comment by maektwain** [comment]
I think you need to add bitcoincash: prefix after generating address.

**Comment by cmgustavo** [comment]
These websites are still using legacy address format (they don't know about new format). It 's not a bug from Copay. Please, check this tool to convert the new cash address format generated by Copay to legacy format: https://cashaddr.bitcoincash.org/

Learn more about new cash address here: https://www.bitcoinabc.org/2018-01-14-CashAddr/

Thanks!
