### ISSUE TITLE
could not fetch payment: check if it is still valid

### ISSUE THREAD

**Issue by haiyizxx** [bitpay/copay#8689]
I am building a payment server that sends payment request but I keep getting this error when I scan. I checked my log, there is no incoming request. How does copay wallet reject the payment request without actually fetch my payment request? My payment request works on other wallets. 

Could you explain why I get the error message?

Thanks in advance.

**Comment by haiyizxx** [comment]
hi @matiu, any luck?

**Comment by matiu** [comment]
this means the payment is expired or the server responded 404 (so the payment is no longer available).
