### ISSUE TITLE
How a transaction initiated without the user intention?

### ISSUE THREAD

**Issue by j4nos** [bitpay/copay#8690]
I get as salary 5.2 BTC to this address: `1DpmSrg9Bur2VhiMqEu4gYnA28gaM7ZVjp`
I transfered 2.4 BTC, 0.2 BTC to an other address, but rest stayed in the wallet.
When I check wallet with https://blockchain.info, I see many transactions I did not initiated. How is it possible? Does `Copay` has any extra logs about it? I would be curious who started transactions? Here is the BTC movements. From 11 transactions only 2 was initiated by me.

<img width="929" alt="40075852-b0a5f10c-587d-11e8-853e-99986ea83b97-3" src="https://user-images.githubusercontent.com/11924475/40442611-72054e96-5ec4-11e8-81c1-1400d1aa0556.png">

**Comment by BGalliotti** [comment]
Hello @j4nos 

Thanks for reaching out to us.

**As you can see on the blockchain:**

- No. Transactions | 4
1. received 2.45 BTC
2. received 2.76168923 BTC
3. Sent 0.013772 BTC 
4. Sent 2.74890944 BTC

Maybe [here](https://live.blockcypher.com/btc/address/1DpmSrg9Bur2VhiMqEu4gYnA28gaM7ZVjp/) its easier to read.

**For every transaction at least you have 3 movements: (unless the change is zero, in which case you have 2)**

- Money sent (origin)
- Money received (destination)
- Change (going back to origin)

**For example, In this [transaction](https://live.blockcypher.com/btc/tx/0ce06730094fb9cb8233515cac3d6aa96e99b27b394851ad7f626cb105238b57/)Where you receive 2.45 BTC:**

- What you see on the left side, **is the sender** (origin, where funds come from)
- **You** (1DpmSrg9Bur2VhiMqEu4gYnA28gaM7ZVjp) **are just one of the recipients.**
- One of the 10 outputs you see on the right side, **might be the change which goes back to the sender**.

**Does this clarify your question?**

Please let us know if you have any additional questions.
Kind regards.
