### ISSUE TITLE
I need to find my wallet file

### ISSUE THREAD

**Issue by kalif4** [bitpay/copay#8692]
I need to reach out to Copay customer support to see if they can send me my wallet file. The contents are something like this - 

"iv":"v79..g==","v":1,"iter":10000,"ks":128,"ts":64,"mode":"ccm","adata":"","cipher":"aes","salt":"gAmmJAUU6r0=","ct":"4FWMmL...RIGnOUri1e"}

help

**Comment by gabrielbazan7** [comment]
Hi ! read this article: 

https://support.bitpay.com/hc/en-us/articles/115003004363-I-lost-my-wallet-or-changed-my-phone-What-can-I-do-to-restore-my-wallet-

The backup is not stored on BitPay servers, so BitPay cannot recover funds for you.
