### ISSUE TITLE
Unable to send BCH

### ISSUE THREAD

**Issue by nilsbringsjord** [bitpay/copay#8695]
I am attempting to make a BITCOIN CASH transaction, however, it always deafualts to only allow me to send BTC. How can I fix this issue?

**Comment by BGalliotti** [comment]
Hello @nilsbringsjord ,

Thanks for reaching out to us.
To make a BCH transaction, you need to have BCH.
To have BCH you need a BCH wallet and then put BCH in it. By default when you create a wallet, it is a BTC wallet.

**To duplicate your wallet to a BCH wallet please refer to the duplicate steps on #8586  (only the duplicate steps).**

**To create a wallet:**

- Open your Bitpay/Copay app > Tap on the **+** sign on Bitcoin Wallets > Create Personal Wallet >  Enter a wallet name, select the desired coin (BCH or BTC) > Tap Create Wallet.
- When you are asked to protect your wallet with a password, tap "yes" enter your password, and write it down on a piece of paper.
- Now your wallet says "Needs backup". Follow this video to back up your wallet: https://bit.ly/2Jz1cFZ
- **Remember to write down your password and 12-word passphrase on a piece of paper and store it in a safe place. The 12-word phrase is the *only* way to recover your wallet, *this step is extremely important*.**

**To send funds, follow these steps:**
- Open your Bitpay/Copay app > Tap Send (on the lower bar) > Tap on the wallet you want to send money to > Enter the amount and then tap on the arrow > If you get a "bitcoin Miner fees unusually high" message,
tap "I understand" > tap on "click to accept" and enter your password

Please let us know if you have any additional questions.
Kind regards.

**Comment by peregajendra13** [comment]
I have the same issue and a BCH account with BCH on it in my Copay and every time I try to send BCH it goes by default to my BTC account, it does not mater if the address I paste there is a BCH address, it goes by default to BTC account.

The only time it works is when you can scan a QR code with a defined amount of BCH, if it ia a general QR code where you can send any amount of BCH it goes by default to the BTC.

**Comment by gabrielbazan7** [comment]
Could you share the address you are using?

**Comment by gabrielbazan7** [comment]
Please reopen the issue if you still having problems

**Comment by BGalliotti** [comment]
Hello @NadiiaS 

Thanks for reaching out to us.

Please refer to #8843 

Please let us know if you have any additional questions.
Kind regards.

**Comment by gitchand** [comment]
Can anyone help me to solve this issue:
An error occured:
16: mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation). Code:-26
While pushing a BCH tx
