### ISSUE TITLE
Spending/Encrypt password - Types of password

### ISSUE THREAD

**Issue by mintminty59** [bitpay/copay#8696]
I have fallen victim to this bug on windows wallet. I never said a spending key or a 12 memorable word now suddenly it is asking me for a spending password I never set no matter what I do, I am not able to perform backups , I am not able to transfer funds, etc etc and I am pretty pissed off to say the least.

Nobody else has accsess to my laptop as I live by myself and there are no babies etc that set a password for me. There has to be a way to fix this issue as I am not alone

**Comment by BGalliotti** [comment]
Hello @mintminty59 

Thanks for reaching out to us.

The first time you create a wallet you are asked for a password and to backup the wallet. You might have forgotten this "detail".

We have put several screens letting know the user how the wallet works, the importance of backing up, writing down the 12-word phrase, and using a password.

To restore your wallet, you must save the 12-word backup phrase that you receive when you create a wallet.

So basically if you don't have the passphrase, the only way to recover the wallet is trying to remember the password. Just in case, it could be useful for you to know that there are no specific requirements for the password (like caps, numbers, etc).

**As a recommendation for the future, backup your wallet right after creating it and write down the 12-word phrase, store it in a safe place and do not share it with anybody.**

Unfortunately, there is nothing we can do for you regarding the wallet recover/funds.

**There is no account or password for the BitPay wallet. Please see https://support.bitpay.com/hc/en-us/articles/115002989283-Why-don-t-I-have-an-online-account-for-my-BitPay-wallet-.**

**BitPay does not store your private keys or have access to your funds. The BitPay wallet secures your Bitcoin and Bitcoin Cash **only** on your device.**


Please let us know if you have any additional questions.
Kind regards.

**Comment by jameec** [comment]
Hi, glad I found this thread. Regarding the Bitpay spend password. I do have the 12 words phrase but I don't recall ever setting up an encrypt password. This is where I am stuck sending my BTC from my bitpay wallet. I am asked to Enter encrypt password in order to send funds. Any thoughts on how to deal with this? thanks,

**Comment by BGalliotti** [comment]
Hello @jameec ,
Thanks for reaching out to us.

In the Bitpay/Copay wallet you have:

- A 12 -word passphrase/ text file/QR code which are **different forms of backup for the same wallet** (you do not need all of them, one of them is enough).
- You can protect the **wallet** with an Encrypt/Spending password. If you have entered a PIN number as your Encrypt password, that is another story. There are no specific requirements for this password.
- You can protect the **app** with a PIN, **that is an extra protection but it's not related to the wallet itself**.

**If you have the 12-word passphrase but you do not remember the encrypt password, recover the wallet again with the 12 word passphrase.**

**If you do not know what you are you exactly doing, please let us know, we will give you further guidance.**

**Please refer to #8532 to know more about the recovery process.**
Make sure you check ALL the information (read the whole thread, read all the articles and watched the videos) before deleting your wallet.

Please let us know if you have any additional questions.
Kind regards.
