### ISSUE TITLE
Wrong address

### ISSUE THREAD

**Issue by Raemstel** [bitpay/copay#8700]
On May 25 I tried to transfer from Bitstamp 1 BCH to my Copay wallet.
I have at Copay a BTC and a BCH wallet.
As receiving address I at Copay I made an error: I used the BTC address in stead of BCH address.
Result: transaction at Bitstamp approved but no BCH received at Copay BCH wallet.
How to solve?
![bitstamp 260518](https://user-images.githubusercontent.com/32367560/40575145-7f0cf39c-60df-11e8-9e92-2b2557d3aa3f.png)

**Comment by BGalliotti** [comment]
Hello @Raemstel 

Thanks for reaching out to us.

Please refer to #8586  

Please let us know if you have any additional questions.
Kind regards.
