### ISSUE TITLE
Enable External Services

### ISSUE THREAD

**Issue by duongnvt2110** [bitpay/copay#8702]
### I set the COPAY_EXTERNAL_SERVICES_CONFIG_LOCATION="~/.copay/externalServices.json" but it's wrong.And how to fix it?
C:\xampp\htdocs\copay>npm run apply:copay
copay@4.3.6 apply:copay C:\xampp\htdocs\copay
cd app-template && node apply.js copay
~/.copay/externalServices.json
Applying templates for: Copay
 index-template.html => src/
config-template.xml => /
ionic.config-template.json => /
manifest.ionic-template.json => src/
 build-desktop.js => desktop/
 .desktop => desktop/
setup-win.iss => desktop/
 build-macos.sh => desktop/
 build-linux.js => desktop/
Copying copay/appConfig.json to assets
Looking for COPAY_EXTERNAL_SERVICES_CONFIG_LOCATION...
Found at: ~/.copay/externalServices.json
Copying ~/.copay/externalServices.json to assets.
{ Error: ENOENT: no such file or directory, open 'C:\xampp\htdocs\copay\app-template\~\.copay\externalServices.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (C:\xampp\htdocs\copay\app-template\apply.js:107:27)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\xampp\\htdocs\\copay\\app-template\\~\\.copay\\externalServices.json' }
External services not configured.
Copying dir 'copay/img' to '../src/assets/img/app'...
Copying dir 'copay/sass' to '../src/theme'...
Applying distribution-specific configuration to package.json...**

**Comment by cmgustavo** [comment]
Just ignore the variable `COPAY_EXTERNAL_SERVICES_CONFIG_LOCATION` or set your own externalService.json file.
