### ISSUE TITLE
OLD IPAD 2 OLD COPAY VERSION

### ISSUE THREAD

**Issue by EstebanPacheco** [bitpay/copay#8708]
Hello! is there any way to install the last version of COPAY on an iPad 2 running iOS 9.3.5

thanks in advance

**Comment by BGalliotti** [comment]
Hello @EstebanPacheco ,

Thanks for reaching out to us.

We are afraid for now that is not possible. 

However, we think you should be able to upgrade your iOS, and use Copay/Bitpay.

Please let us know if you have any additional questions.
Kind regards.
