### ISSUE TITLE
iOS Breaks the QR

### ISSUE THREAD

**Issue by maektwain** [bitpay/copay#8709]
We have been facing this issue after a while say couple of hours we use the app again, it breaks the QR , we are using our own BWS and modified version of app.

So we drilled down on BWS and App, 

1. BWS stores addresses looks ok to us
2. Client side we noticed it appends two addresses (address_One + address_two) (when this error occurs)

Now naturally it should not append two address together , so we looked at those entries in BWS it has same time createdAT inside BWS.

Now our workaround is to clear the existing lastAddress based on walletId.

**Comment by matiu** [comment]
we can't help you with a mofied version of the app, we need . case we can reproduce. If you can provide a QR that doesn't work with the vanilla version of the app, we can help.
