### ISSUE TITLE
24 word seed - copay backup issue

### ISSUE THREAD

**Issue by ShriScoopy** [bitpay/copay#8710]
I have a Copay wallet with a 24 word backup seed, not 12. Recently when trying to restore my Copay wallet using seed I get the error:

> Could not access the wallet at the server. Please check:
> The password of the recovery phrase (if set)
> The derivation path
> The wallet service URL

Can anybody please advise what the derivation path or wallet service URL should be? I only wrote down the 24 words when I set it up on the Copay app in Jan 2018. I originally set up the wallet with the Android mobile app and have tried restoring on Android, IOS, and Chrome with no success.

Any help or advice would be appreciated.

**Comment by maektwain** [comment]
I don't think it has 24 word backup, are you talking about total word count like individual characters?

1. Correct BWS url is "https://bws.bitpay.com/bws/api/"

Derivation path deepening on which coin you are using for BTC  `"m/44'/0'/0'";`

**Comment by ShriScoopy** [comment]
Yeah Copay usually have 12 words but somehow I got a 24 word, perhaps because I was on an old version of Copay when I set this wallet up. Not sure. 

I guess I need to hear from someone who has used 24 word seed on Copay Android mobile wallet

**Comment by gabrielbazan7** [comment]
By default, Copay generates a 12 words backup. You could try in the create view setting the "Specify Recovery Phrase" option and enter there the 24 words. For sure, that backup was generated by another software and not Copay.

<img width="398" alt="bitpay_-_secure_bitcoin_wallet" src="https://user-images.githubusercontent.com/10999037/40662135-e6027e8e-632b-11e8-9bbe-582f81ed4f79.png">

**Comment by Richie202a** [comment]
@ShriScoopy 
did you restore your 24 recovery phrase, if you couldn't send me email I can recover it : anywalletrecovery@gmail.com

**Comment by maektwain** [comment]
@

> @ShriScoopy
> did you restore your 24 recovery phrase, if you couldn't send me email I can recover it : [anywalletrecovery@gmail.com](mailto:anywalletrecovery@gmail.com)

Please delete this reply @gabrielbazan7 spam
