### ISSUE TITLE
Change my copayer's name in shared wallet

### ISSUE THREAD

**Issue by kadufrusso** [bitpay/copay#8713]
Hi, I mistakenly gave an unintended name to me in a shared wallet. Is it possible to change?

**Comment by BGalliotti** [comment]
Hello @kadufrusso 

Thanks for reaching out to us.

You can change your wallet's name by doing this:

Open up your Bitpay/Copay app 
- Go to Settings > [your wallet] > Name (tap there) > Enter the desired name > Save

Please let us know if you have any additional questions.
Kind regards.
