### ISSUE TITLE
Possible testnet scam

### ISSUE THREAD

**Issue by KayleyWong** [bitpay/copay#8722]
Hi guys, I really need your help on this. My transaction ID is b2898b8c5f5f01f573e768ec21fc4f15c1e433e7255960fb71551f06cec36651. It seems that my transaction confirmed. What should I do next? I’m stuck.

**Comment by BGalliotti** [comment]
Hello @KayleyWong 

Thanks for reaching out to us.

Your wallet is a **testnet wallet**, please refer to this [article](https://support.bitpay.com/hc/en-us/articles/360004102011-What-is-testnet-How-do-I-avoid-testnet-Bitcoin-scams-) to know what this is about and why you are experiencing this situation.

Please let us know if you have any additional questions.
Kind regards.
