### ISSUE TITLE
Taking forever

### ISSUE THREAD

**Issue by patriots1121** [bitpay/copay#8723]
To receive my bitcoins. Over an hr.

**Comment by BGalliotti** [comment]
Hello @patriots1121 ,

Thanks for reaching out to us.

We are trying to keep this support channel tidy and clean. This helps not only you but other users.

We have answered you #8722 and #8563 and never received a reply, please do not open a new thread if your concern is related/the same/similar to the earlier ones. Opening a new thread, that does not help the community.

- Have you read #8722  ?

**If not, please go ahead and read it.**

Also please check our articles [here](https://support.bitpay.com/hc/en-us/search?utf8=%E2%9C%93&query=transaction), they could be useful.

**If you have any other concerns, please open a new one, follow it along, and bear in mind the following:**

- Use an explanatory title for the thread.
- Provide a clear explanatory description of the issue.
- As you expect answers to your questions from us, we expect your reply to our answers/questions.
- Keeping the forum tidy is in benefit of all the community.

Thanks for understanding.
Kind regards.
