### ISSUE TITLE
Bitpay invoice not confirmed

### ISSUE THREAD

**Issue by ajijos** [bitpay/copay#8728]
Sent Bitcoins over 10 hours ago to Bitpay Invoice : https://bitpay.com/invoice?id=cSy7cwx2F5hHafNVPYRaM

The transaction id is : ad4618cede44de6a8898f7320d26ee38bf852d5a46c96f3c809b6e92591634ae

There are more than 50 confirmations, but Bitpay invoice is still showing as unconfirmed.

Please Help !!!!

**Comment by BGalliotti** [comment]
Hello @ajijos, 
Thanks for reaching out to us.

Please send your here: https://help.bitpay.com/requestHelp

Our agents will take care of you there.

Kind regards.
