### ISSUE TITLE
WALLET CONFIGURATION

### ISSUE THREAD

**Issue by bazz7878** [bitpay/copay#8735]
I accidentally transferred BCH to the BTC address on copay

I would like to add coins to the BCH address using WALLET CONFIGURATION, but what should I do?

After entering Recovery phrase (mnemonic) or File / Text backup and searching, I found BCH coin (0.40216757 BCH) at BTC address!

I enter the BCH address and move funds but I can not do it!
How can I correctly return the BCH coin to the BCH address?
Thank you! ><;

Even after 24 hours "Please wait
You can not transfer funds to BCH Wallet with the display of "This process could take several several minutes"!><;
![bandicam 2018-06-04 09-04-09-301](https://user-images.githubusercontent.com/39890739/40894063-d5928458-67e1-11e8-8b9c-5fab31b81706.jpg)
![bandicam 2018-06-04 09-21-12-179](https://user-images.githubusercontent.com/39890739/40894072-ea123f36-67e1-11e8-84cf-3ed8cbf2a0f5.jpg)
![bandicam 2018-06-03 07-10-56-486](https://user-images.githubusercontent.com/39890739/40894077-f67b6d6a-67e1-11e8-9bfc-7d2eea38f7b6.jpg)
![bandicam 2018-06-03 07-06-18-964](https://user-images.githubusercontent.com/39890739/40894081-fba88e8a-67e1-11e8-9825-2af2d68c8fe2.jpg)

**Comment by BGalliotti** [comment]
Hello @bazz7878 , 

Please refer to #8586 to know how to recover your funds.

We will be closing this thread, if you need further guidance, please open a new one.

Kind regards.
