### ISSUE TITLE
Funds stuck in 2/2 multisig copay wallet

### ISSUE THREAD

**Issue by gocheto** [bitpay/copay#8738]
I've created a multisig wallet with another person and we need two confirmations to send money out but he doesn't have the device he accepted the invitation and it's not backed up. I can created a proposal to transfer the funds to a new wallet but need second confirmation to complete it. We have the original invitation code but it's not allowing us to accept it again because it's already been accepted. 
Is it possible to recover the funds?

**Comment by BGalliotti** [comment]
Hello @gocheto ,

Thanks for reaching out to us.

The only way to recover the funds is by recovering the other wallet. For that, you will need that wallet backup phrase/file/text.
Without the backup, unfortunately, the wallet and funds are lost.
#8736
Kind regards.
