### ISSUE TITLE
I got my bitcoins but it’s not in my wallet 

### ISSUE THREAD

**Issue by kattgarcia1** [bitpay/copay#8747]
Please help I got my bitcoins but they have not went into my wallet !

**Comment by BGalliotti** [comment]
Hello @kattgarcia1 

Thanks for reaching out to us.
Please refer to #8712 to know more about why it takes a while for the funds to reach a wallet.

If you have any other question related to this topic, please post it there (#8712)

Please let us know if you have any additional questions.
Kind regards.
