### ISSUE TITLE
Can’t Access Copay

### ISSUE THREAD

**Issue by juliebendle** [bitpay/copay#8750]
Hi there all I do hope you can help me please? I have bitcoin in Copay but for some reason it will not load up the app on my ipad2. I now have to sign in on my iPhone but it needs the encryption code. Where do I go to find the translation for my twelve words to get my code please? I think it’s asking for it as I’m trying to back up my wallet

**Comment by Umarancopay** [comment]
I'm trying to open an account with Copay but I couldn't

**Comment by Umarancopay** [comment]
May I have step by step like an explanation for a kinder garden student. I'm to old for this new technology

**Comment by BGalliotti** [comment]
Hello 

Thanks for reaching out to us.
@juliebendle  
- The Bitpay/Copay app requires iOS 10 as a minimum
- If you have the 12-word passphrase, you do not need the password. If you are trying to restore the wallet using the passphrase, do not enter any password in the recovery process.
To know how to recover the wallet please refer to #8532 and focus on the import procedure.

If you have any related issues, please post your inquiry there.

@Umarancopay 
Are you trying to create a wallet? 
Please explain clearly what do want to do.

Please let us know if you have any additional questions.
Kind regards.
