### ISSUE TITLE
I want my old address back!

### ISSUE THREAD

**Issue by drago23456** [bitpay/copay#8757]
I mine btc and copay changed my btc address and i can't receive my mined btc!!

**Comment by gabrielbazan7** [comment]
Hi take a look at this articles
https://support.bitpay.com/hc/en-us/articles/115002989643-Why-does-my-BitPay-wallet-s-bitcoin-address-keep-changing-
https://support.bitpay.com/hc/en-us/articles/115003004423-Do-I-still-own-old-bitcoin-addresses-
