### ISSUE TITLE
Wallet does not show history of transactions

### ISSUE THREAD

**Issue by NadiiaS** [bitpay/copay#8759]
My Bitcoin wallet shows the total amount but it doesn't show each transaction when I open it.

**Comment by o-STOP-o** [comment]
Koma

**Comment by BGalliotti** [comment]
Hello @NadiiaS 

Thanks for reaching out to us.
Please try refreshing your wallet addresses.

Refer to #8657

Please let us know if you have any additional questions.
Kind regards.

**Comment by Wongkako** [comment]
#8657



從我的 Samsung Galaxy 智慧型手機傳送。

-------- 原始訊息 --------
自： BGalliotti <notifications@github.com>
日期： 2018/6/11 下午10:55 (GMT+08:00)
至： bitpay/copay <copay@noreply.github.com>
副本： Subscribed <subscribed@noreply.github.com>
主旨： Re: [bitpay/copay] Wallet does not show history of transactions (#8759)


Hello @NadiiaS<https://github.com/NadiiaS>

Thanks for reaching out to us.
Please try refreshing your wallet addresses.

Refer to #8657<https://github.com/bitpay/copay/issues/8657>

Please let us know if you have any additional questions.
Kind regards.
