### ISSUE TITLE
how can I import bitcoin.com wallet to bitpay wallet use 12 recover phrase?

### ISSUE THREAD

**Issue by daffy6537** [bitpay/copay#8766]
when I try to import it, the app noticed me that 
【Could not access the wallet at the server, Please check
 the password of the recovery phrase ; the derivaton path; the wallet service url
NOTE: to import a wallet form third-party software please go to add wallet and specify the recover phrase here】

**Comment by junderw** [comment]
use "create wallet" and open advance settings to select your own phrase instead of "random"

**Comment by daffy6537** [comment]
@junderw great! Thank you very much!!  but my balance is 0 after recovery.

**Comment by daffy6537** [comment]
@junderw great! Thank you very much!!  but my balance is 0 after recovery.

**Comment by daffy6537** [comment]
@junderw   done!
"Settings" > "Wallet" > "More Options" > "Transaction History" > "Clear cache"
"Settings" > "Wallet" > "More Options" > "Wallet Addresses" > "Scan addresses for funds"
thanks
