### ISSUE TITLE
Don't see my btc after wallet import

### ISSUE THREAD

**Issue by VMorozenko** [bitpay/copay#8775]
Im using Copay on my iPhone but forgot password required to transfer BTC. As clear understood this password impossible recover. Thats why I installed Copay on other device and imported successfully my wallet using recovery phrase. But on imported wallet there is 0 amount of my BTC. At the same time on my main device I see all my bitcoins but can't transfer without password.

Please advise

**Comment by BGalliotti** [comment]
Hello @VMorozenko 

Thanks for reaching out to us.
Please refer to #8657  to know how to refresh your wallet.

Please let us know if you have any additional questions.
Kind regards.

**Comment by VMorozenko** [comment]
Thanks for quick response.
I tried to do according your recommendation but without success
("Settings" > "Wallet" > "More Options" > "Wallet Addresses" > "Scan addresses for funds")
There is still 0 btc on second device as it was before

My wallet address on first device with available funds 1C3ZC7o3geSQoyBJLncP1ghecYfWiDLBRh 
My wallet address on second device with 0 funds 1HMKuLwLhRLAMgjMCj6DxJN2tAVCHbpHcx

**Comment by BGalliotti** [comment]
Hello @VMorozenko 

You are welcome. 

You are looking at different wallets, that is why you have different funds.

What you should do is import the same wallet you have in the iPhone, on the other device. 

For that, you need that wallet 12-word passphrase. 

To know how to import that wallet please refer to #8532

Please let us know if you have any additional questions.
Kind regards.

**Comment by VMorozenko** [comment]
How can I transfer funds from wallet without password to transfer?
Is it possible to move it back to previous senders who sent it before to my wallet?

**Comment by BGalliotti** [comment]
Hello @VMorozenko ,

Thanks for reaching out to us.
- To know how to transfer funds watch this video: https://www.youtube.com/watch?v=jctgoHSwPM0
- To send funds back to your senders, you have to know the addresses where the funds were sent from.

What you can do is:

Open the Bitpay app > tap on your wallet > Tap on the transaction you want to send back > Tap **View on blockchain** 

**Usually**, not always, you will get one address on the left side of the transaction. That should be the sender's address. 

We recommend you to check the address with the sender.

Please let us know if you have any additional questions.
Kind regards.
