### ISSUE TITLE
i cant spend my bitcoin in my co-pay wallet, it keeps telling me insufficient fund, whereas i have enough to spend

### ISSUE THREAD

**Issue by CUTEYGEM** [bitpay/copay#8776]

**Comment by BGalliotti** [comment]
Hello @CUTEYGEM  please send us your wallet ID.

To get your Wallet ID, open your BitPay/Copay application, then go to `Settings` > [Your wallet] > `More Options` > `Wallet Information`. On your phone, if you tap on the wallet ID it will copy it to the clipboard.

Please check this [article](https://support.bitpay.com/hc/en-us/articles/360004102011-What-is-testnet-How-do-I-avoid-testnet-Bitcoin-scams-) in the meantime.
