### ISSUE TITLE
Error Wallet

### ISSUE THREAD

**Issue by thyagoromeiro** [bitpay/copay#8785]
Good night 

When I try to access the wallet, the error below occurs

A general unexpected critical error has ocurred
error: couldn't connect to server: EOF reached (code 1)
(make sure server is running and you are connecting to the RPC port)
See the console/logfile output for more detailed error information

**Comment by BGalliotti** [comment]
Hello @thyagoromeiro 

Thank you for reaching out to us.

**So we can further help, please provide as many of the following details as you can:**

- Current device used: Phone model 
- Current operating system version for the device: iOS, Android..
- Current version of the wallet used: Bitpay App > Settings > About bitpay 
- Any log files containing error details: Bitpay App > Settings > About bitpay > Session Log > Tap on the Upper right corner (three dots) > Send by email (you can screenshot the content as well and attach the images to your e-mail. In such case, please make sure you move the slider to the **"Debug"** position).
- Error screenshot: On [iPhone](https://apple.co/1DAB204) on [Android](https://www.wikihow.tech/Take-Screenshots-on-an-Android)
- Steps to replicate: Steps needed for the error to appear.
- BitPay Wallet ID - To get your Wallet ID, open your BitPay application, then go to Settings > Wallets & Integrations > More Options > Wallet Information.

**We look forward to hearing from you.**
