### ISSUE TITLE
Wallet

### ISSUE THREAD

**Issue by grigorii163** [bitpay/copay#8786]
Hello! I use a purse for Android. If I generate a new purse address in it, will I receive an automatic payment to the old one?

**Comment by BGalliotti** [comment]
Hello @grigorii163 

Thanks for reaching out to us.

You receive payments in the addresses you share with the sender.
If you share the new address and tell them to send you the funds to that address, you will receive the funds there.

Please let us know if you have any additional questions.
Kind regards.

**Comment by grigorii163** [comment]
and if automatic payment was sent to the old address, when I have already generated a new one?
--
Отправлено из Mail.Ru для Android пятница, 15 июня 2018г., 23:00 +03:00 от BGalliotti  notifications@github.com :

**Comment by BGalliotti** [comment]
Hello @grigorii163 

Thanks for reaching out to us.

Nothing bad happens, you are just going to receive the funds in the address they sent the funds to regardless if you generated new addresses or not. 

You can generate infinite addresses, that has nothing to do with the funds you are going to receive.
If you want to receive funds into a different address, generate the address and then share it with the sender.

You can see addresses in a wallet, as different pockets in an actual wallet. 

Please let us know if you have any additional questions.
Kind regards.
