### ISSUE TITLE
Unable to spend testnet coins

### ISSUE THREAD

**Issue by ishij** [bitpay/copay#8788]
Bitpay __ unable to spend btc? Which is stored in testnet wallet

**Comment by BGalliotti** [comment]
Hello @ishij 

Thanks for reaching out to us.

Testnet wallets are meant for testing purposes, and testnet coins have no real value.

Please read the following article: https://support.bitpay.com/hc/en-us/articles/360004102011-What-is-testnet-How-do-I-avoid-testnet-Bitcoin-scams-

to know:

- What is testnet
- Why is important to know what is testnet
- How to avoid testnet scams

Please let us know if you have any additional questions.
Kind regards.

**Comment by BGalliotti** [comment]
#8722
