### ISSUE TITLE
Do I lose funds if I update the app?

### ISSUE THREAD

**Issue by ishij** [bitpay/copay#8789]
Installed Bit pay version in my mobile is v 4.3.6, had btc in it.
If I update to latest version, is there any possibility loss of btc, should I transfer it to other wallet before update?
 latest version 4.4 not available in play store

How do I update??

**Comment by BGalliotti** [comment]
Hello @ishij 

Thanks for reaching out to us.
If you update the app and everything goes normally, theoretically there is no possibility of losing your wallet/funds.

Anyways, we strongly recommend you to back up your wallet, and store your backup phrase in a safe place.

Please refer to #8532  to know how to proceed.

Please let us know if you have any additional questions.
Kind regards.
