### ISSUE TITLE
Please tell me how I will send BCH to external address. Translate BTC addresses

### ISSUE THREAD

**Issue by siva8888** [bitpay/copay#8790]
I have BCH on copay wallet. I want to send BCH to external address but can not. why? Please tell me how I will send BCH to external address.

**Comment by BGalliotti** [comment]
Hello @siva8888 

Thank you for reaching out to us.

Make sure your wallet is not a testnet wallet, please refer to #8788 
**If that is not your problem, So we can further help, please provide as many of the following details as you can:**

- Current device used: Phone model 
- Current operating system version for the device: iOS, Android..
- Current version of the wallet used: Bitpay App > Settings > About bitpay 
- Any log files containing error details: Bitpay App > Settings > About bitpay > Session Log > Tap on the Upper right corner (three dots) > Send by email (you can screenshot the content as well and attach the images to your e-mail. In such case, please make sure you move the slider to the **"Debug"** position).
- Error screenshot: On [iPhone](https://apple.co/1DAB204) on [Android](https://www.wikihow.tech/Take-Screenshots-on-an-Android)
- Steps to replicate: Steps needed for the error to appear.
- BitPay Wallet ID - To get your Wallet ID, open your BitPay application, then go to Settings > Wallets & Integrations > More Options > Wallet Information.

**We look forward to hearing from you.**

**Comment by BigslimVdub** [comment]
I have this identical issue with Bitpay wallet. I updated to latest yesterday and now I can not send or receive from my wallet. I also can not receive to JAXX wallet on BCH address. I can also not receive on Bittrex BCH wallet. All wallets say address are BTC and not BCH one I try to transfer. 

Using V4.4.0

These wallet address, I was able to send and receive to less than one month ago. Even Bittrex says my BCH wallet on Bitpay is now BTC even though I have multiple tx to the same address within the past month bch to bch. 

I can not create a new address either. When I click the "generate new address" it blinks and does not produce a new address. 

Same issue on iPhone and OSX applications both up to date.

**Comment by BGalliotti** [comment]
Hello @BigslimVdub ,

Thanks for reaching out to us.

Please, open up the Bitpay wallet and try to perform the following actions:
- Generate new BCH addresses
- Send funds

Take screenshots of any errors you get in the process.
Without closing the app, send us the logs (paste the logs here in your Github response).

Bitpay App > Settings > About bitpay > Session Log > Tap on the Upper right corner (three dots) > Send by email (you can screenshot the content as well and attach the images to your e-mail. In such case, please make sure you move the slider to the "Debug" position).

Please let us know if you have any additional questions.
Kind regards.

**Comment by BigslimVdub** [comment]
I did generate a new wallet last night (that also allowed me to generate new address’) but using the app to send funds to bittrex or JAXX both show their address as a BTC address. I was able to transfer funds from my old wallet that had been in use up to 0.4.3 to the newly generated wallet on 0.4.4 but still can not transfer out from bch wallet on 0.4.4

**Comment by BGalliotti** [comment]
Hello @BigslimVdub ,

Thanks for reaching out to us.

We understand the situation. However, we need more information to research this issue.

We assume you have BCH wallets, you are generating addresses with a BCH wallet.

Please send us:

- Wallet ID
- Some addresses generated 

**We look forward to hearing from you.**

**Comment by BigslimVdub** [comment]
Old wallet that worked fine -  qqvzpa3e5702hwu69g7s5h28qahnm053k5h9fwszr6
New wallet generated yesterday - qzvc7ysf9qd6ytzymputhkjxu5gq0t3fugc0t6cmdm , qzjytzxj4cx2m5g7puf0lh3mvprayszj3u5manhd22 , wallet that was used to tx from old wallet to new wallet - qr09ghdlznj8ltnmeghdssfh3kprdmpneu6gpdtp4f

You can see tx that have been made for them.

**Comment by BGalliotti** [comment]
Hello @BigslimVdub,

Thanks for reaching out to us.
We have been testing many wallets.
The Bitpay/Copay wallet is generating the addresses successfully.
If needed, you can enable the **Copay Style Addresses** (usually beginning with C):

- Open the Bitpay/Copay app > go to **Settings** > **Advanced** > enable **Use Bitcoin Cash Copay Style Addresses**

The matter with Jaxx wallet and other wallets is that they generate BCH addresses using the BTC format.
The Bitpay/Copay app to avoid users sending BCH to BTC addresses by mistake, when it reads/detects a BTC format only lets the user select BTC wallets.

Due to this behavior of the Bitpay/Copay wallet, you need to translate the addresses generated by the other wallets and paste them in the Bitpay/Copay wallet.

To translate the address use this tool: https://bitpay.github.io/address-translator/
Paste the address where you want to receive the BCH on the translator. 

- Option 1: Copy the Legacy BitPay BCH Format address. In the Bitpay/Copay app go to **Send**
and paste the address. Then continue with the sending process.
- Option 2: In the Bitpay/Copay app go to **Scan** and scan the Legacy BitPay BCH Format QR code.

Please let us know if you have any additional questions.
Kind regards.

**Comment by BigslimVdub** [comment]
Why would you stop supporting scanning of old address?

All the address of exchanges are 1***** address for bch. End users need the function to scan any qr code or use any new or old style bch address format.

**Comment by BigslimVdub** [comment]
I enter the address in the translator page and used the "Legacy copay" address as my output on Bitpay app and the funds were transferred the first try.

**Comment by BGalliotti** [comment]
Hello @BigslimVdub 

Thanks for reaching out to us.

> I enter the address in the translator page and used the "Legacy copay" address as my output on Bitpay app and the funds were transferred the first try.

We are glad to know you could transfer the funds!

> Why would you stop supporting scanning of old address?

That is a reasonable question. Personally, I do not make this kind of decisions and also I do not use BCH so I have not dealt with this matter ever.
We (Bitpay) have a lot of confusions from people sending BCH to BTC addresses, after what they have to go over a procedure to recover the funds, this happens very often, so a way to limit this, is by forcing BTC transactions whenever a BTC address format is detected.

Thanks for your feedback.


Please let us know if you have any additional questions.
Kind regards.

**Comment by borisjavier** [comment]
Why in the hell I cannot send BCH from copay BCH wallet? In windows version I click on send it gives only option to enter or scan bitcoin core address....

**Comment by BGalliotti** [comment]
Hello @borisjavier,
Thanks for reaching out to us.

> Why in the hell I cannot send BCH from copay BCH wallet? In windows version I click on send it gives only option to enter or scan bitcoin core address....

Please refer to #8843 

Please let us know if you have any additional questions.
Kind regards.

**Comment by borisjavier** [comment]
Thxs,
