### ISSUE TITLE
Compra de gift cards

### ISSUE THREAD

**Issue by rodrigedug** [bitpay/copay#8794]
Compre una Gift cards de Amazon en descontaron los btc y aun no me envian mi codigo por favor ayuda

**Comment by BGalliotti** [comment]
Hola @rodrigedug,

**Para que podamos ayudarlo más, proporcione tantos de los siguientes detalles como pueda:**

- Dispositivo actual utilizado
- Versión actual del sistema operativo para el dispositivo: iOS, Android ...
- Versión actual de la billetera utilizada: Aplicación Bitpay> Configuración> Acerca de Bitpay
- Captura de pantalla de error: en [iPhone] (https://apple.co/1DAB204) en [Android] (https://www.wikihow.tech/Take-Screenshots-on-an-Android)
- Pasos para replicar: pasos necesarios para que aparezca el error.
- ID de Wallet de BitPay: para obtener su ID de Wallet, abra su aplicación BitPay, luego vaya a Configuración> Billeteras e integraciones> Más opciones> Información de billetera.

**Comment by rodrigedug** [comment]
Usos sistema android y alli envío los captures de mi billetera necesito
ayuda para recupera mi fondos o Gift card

**Comment by rodrigedug** [comment]
Aquí el id de mi billetera por favor ayuda

**Comment by rodrigedug** [comment]
Aqui el id de mi billetera

**Comment by BGalliotti** [comment]
Hola @rodrigedug ,

Gracias por la respuesta. 

No incluyó o nos hemos recibido su ID de billetera ni capturas de pantalla.

Por favor, no responda al email que recibe. Una vez recibido el email, haga click en "Open it on Github" (o "abrir en Github") y pegue directamente en su respuesta en Github, el texto o imágenes que desee incluir.

Dado su caso, por favor escíbanos aquí: https://help.bitpay.com/requestHelp

Nuestros asesores de Bitpay atenderán su consulta.

Gracias.

**Comment by rodrigedug** [comment]
Realice compra de Gift cards y aun no me llega el codigo por favor ayuda
envío capture de de id de billetera y transacción

**Comment by BGalliotti** [comment]
Hola @rodrigedug , 

Entendemos su consulta, necesitamos que la dirija al centro de atención y soporte de Bitpay.

Para ésto, diríjase a https://help.bitpay.com/requestHelp y complete el formulario paso a paso para recibir asistencia.

Vamos a cerrar este hilo. 

Gracias, saludos cordiales.

**Comment by rodrigedug** [comment]
- Dispositivo actual utilizado

Un teléfono LG-K371

   - Versión actual del sistema operativo para el dispositivo: Android .

ANDROID 6.0

   - Versión actual de la billetera utilizada: Aplicación Bitpay>
   Configuración> Acerca de Bitpay

COPAY v4.3.6


   - ID de Wallet de BitPay: para obtener su ID de Wallet, abra su
   aplicación BitPay, luego vaya a Configuración> Billeteras e integraciones>
   Más opciones> Información de billetera.

98d08aed-adc2-4f0a-a507-9baed33095a3

Transacion realizada

**Comment by rodrigedug** [comment]
- *Dispositivo actual utilizado*

Un teléfono LG-K371

   - *Versión actual del sistema operativo para el dispositivo: Android .*

ANDROID 6.0

   - *Versión actual de la billetera utilizada: Aplicación Bitpay>
   Configuración> Acerca de Bitpay*

COPAY v4.3.6


   - *ID de Wallet de BitPay: para obtener su ID de Wallet, abra su
   aplicación BitPay, luego vaya a Configuración> Billeteras e integraciones>
   Más opciones> Información de billetera.*

98d08aed-adc2-4f0a-  a507-9baed33095a3

*Transacion realizada*

279b04d1756f9ce2e8e4b030f77b35  d846238d78806042dec1c1b38f85f9  7f09


 *DIRECCIÓN DE ENVIÓ *

166xVzSJTQ87KsjejePRoweZyJG7Kr  ra2G

*FECHA Y HORA*
18/06/2018 07:37 p.m.

*CANTIDAD ENVIADA   *
0.087458 BTC

Espero me ayuden a resolver este inconveniente y poder recuperar mi tajeta
de regalo de amazon
GRAcias
