### ISSUE TITLE
Missing Amazon Gift Card - Money Taken No Giftcard

### ISSUE THREAD

**Issue by Dredawgrasta** [bitpay/copay#8801]
Hello I tried pruchasing an amazon gift card using the copay and it took my money but did not generate a gift card. The error said unable to apply to invoice.

The gift card amount is $1250 and the transaction details are below

https://insight.bitpay.com/tx/c03ca4387dc2ab54e9ba7203d2deb934254aeca64c7e0c3d1e5bec7424753424

![image](https://user-images.githubusercontent.com/40430083/41658557-5b449768-745c-11e8-819f-3ea75de7be5a.png)

![image](https://user-images.githubusercontent.com/40430083/41658574-69d60924-745c-11e8-97a0-08a15ca273fb.png)

**Comment by BGalliotti** [comment]
Hello @Dredawgrasta 

Thanks for reaching out to us.

Please address your inquiry to the Bitpay Support Center, our reps will take care of your issue:

https://help.bitpay.com/requestHelp
Kind regards.
