### ISSUE TITLE
Lost funds 

### ISSUE THREAD

**Issue by murdahbkib** [bitpay/copay#8802]
Sent a payment it was never received by the recipient nor was i notified that it had been received in my wallet it says moved but also says I have the funds but when I try to send another payment it says insufficient funds but it shows I have Enough funds  id#671aabac-2dec-4d47-a114-bb8b6b2f04ab

**Comment by BGalliotti** [comment]
Hello @murdahbkib 

Thanks for reaching out to us.

You have sent funds from your wallet to your wallet, that is why it says "moved".
According to our DB this is your balance:

`* Balance
  Total: 0.01156837 btc (0.00000000 btc locked)
  Confirmed: 0.01156837 btc (0.00000000 btc locked)
  Available: 0.01156837 btc (0.01156837 btc confirmed / 0.00000000 btc unconfirmed)
  By address:
    15ZdUkC5TCYHZrVJMCFxq4TXyUd9JctcmV (m/0/2): 0.01136600 btc
    15nvmEvi1nKh7nBEzEosNat9EvN8kpVkqN (m/1/4): 0.00020237 btc
`

Are you trying to send an amount greater than your funds?

Please let us know if you have any additional questions.
Kind regards.

**Comment by Travis2022** [comment]
@murdahbkib 
I can help you find your lost fund contact me here : anywalletrecovery@gmail.com
