### ISSUE TITLE
Confirmed transaction not received / Refresh history cache

### ISSUE THREAD

**Issue by rospeed7998** [bitpay/copay#8806]
About 3 hours ago i sent bitcoins to another copay wallet of mine its says confirmed but i have no bitcoins yet

**Comment by BGalliotti** [comment]
Hello @rospeed7998 

Thanks for reaching out to us.
Please check the transaction on the blockchain to see if its properly confirmed ( consider it confirmed if it has 6+ confirmations).
If it was confirmed **Please open up your BitPay app and try the following steps:**

- ("Settings" > "Wallet" > "More Options" > "Transaction History" > "Clear cache")
- ("Settings" > "Wallet" > "More Options" > "Wallet Addresses" > "Scan addresses for funds")

**Please do not uninstall the app or delete the wallet if you did not back it up properly, in such case, please do so. This is the only way to recover your wallet.**

If you need any further assistance, please let us know.
Kind regards.
