### ISSUE TITLE
btc not authorized

### ISSUE THREAD

**Issue by Agnaldo1975** [bitpay/copay#8807]
I have a shared wallet where I kept my btc with another person and she without my key managed to withdraw? how can this be?
I did not authorize this, and if it was shared I should have given my key.

15qC53FgDLHXADhEEw7xgmjyt4g2ibu6qy

**Comment by BGalliotti** [comment]
Hello @Agnaldo1975 

Thanks for reaching out to us.

If **0f354194-213e-4f79-aef7-fd83ac817ad5** is your wallet, it is not a shared wallet it is just a regular wallet, so if the other person has this wallet set up on their device, they can do whatever they want.

To get your Wallet ID, open your BitPay application, then go to Settings > Wallets & Integrations > More Options > Wallet Information.

Check if this is the wallet we are talking about. If we are correct, please take the measures you consider necessary to manage your wallet.

If you need assistance for creating a shared wallet please let us know.

Please let us know if you have any additional questions.
Kind regards.

**Comment by Agnaldo1975** [comment]
00d77e91-40b1-438a-9f16-1e98e77deadf
This above the ID of the portfolio that the person created made me the convinte I accepted saying to be shared, he put the btc, in it I made the payment and he got to take without my authorization is possible? I lost this btc? even without typing my key or accepting the proposal?

**Comment by BGalliotti** [comment]
Hello @Agnaldo1975 

Thanks for reaching out to us.
The wallet **00d77e91-40b1-438a-9f16-1e98e77deadf** 
 is a 2-3 wallet, which means the wallet has 3 copayers (3 people who share the wallet) and needs 2 signatures to authorize a transaction.

They do not need your signature, as long as the other 2 copayers sign (one of them creates the proposal and the other one approves it, they can transfer funds out of the wallet.

Certainly there is no way to recover those funds and there is nothing we can do in this case.

Please let us know if you have any additional questions.
Kind regards.
