### ISSUE TITLE
BCH recovery tool stuck at Please wait "This process could take several minutes" after succesfully finding balance

### ISSUE THREAD

**Issue by bchwallet** [bitpay/copay#8809]
When using the "https://bitpay.github.io/copay-recovery/" recovery tool and tweaking it a bit(had to set address gap to 130. It finds my total balance that got stuck by sending BCH to my copay legacy BTC address.

 After the process of searching for the balance(which takes quite a long time with this address gap) I get to choose the address to sent it to(tried varies ones all in the new format and/or translated with the translation tool). The page get's stuck at the "This process could take several minutes" sending stage/page. 

Tried the process multiple times, multiple addresses and with/without spending password.

**When pulling up the console with inspect element on this page I see the following error:**
"ERROR Object { headers: Object, status: 0, statusText: "Unknown Error", url: null, ok: false, name: "HttpErrorResponse", message: "Http failure response for (unknown …", error: error }"

Could someone please assist me in recovering my BCH, tell me what I'm doing wrong or is this an error on the tools end?

**Comment by bchwallet** [comment]
In addition it gives this error in the console:

"Failed to load https://blockdozer.com/insight-api/tx/send: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin https://bitpay.github.io' is therefore not allowed access." 

So it looks like the tools hasn't permission to use the blockdozer API to make the transaction, probably means that it's because of the tool right?

**Comment by BGalliotti** [comment]
Hello @bchwallet 
We apologize for our delay.

**Are you still experiencing an issue?**
Were you able to recover the funds?

Our recovery tool has gone through several fixes and the issues you mention might have been solved.

We look forward to hearing from you.

**Comment by jesskie** [comment]
Ok'thank you

jess
