### ISSUE TITLE
12 words phrase invalid ___ bitcoin.com wallet

### ISSUE THREAD

**Issue by ishij** [bitpay/copay#8813]
Forgot spending pwd, treing to recover it using 12 words phrase, entered the correct words,

**Comment by BGalliotti** [comment]
Hello @ishij 

Thanks for reaching out to us.

Please refer to #8532  and let us know if you have any additional questions.
Kind regards.

**Comment by Ivan777111** [comment]
Hello!
The application asks for a password that I did not install! I tried to import a wallet, but the application requires 13 words, not 12! version of the purse v4.5.0
how can I get my money back?
I only have 12 words!

**Comment by BGalliotti** [comment]
Hello @Ivan777111 

Thanks for reaching out to us.
The application requires 12-word recovery phrase. It might be telling you have entered 13.

Very likely you have typed an additional space at the end or after some word. 

Please refer to #8532  and check all the details.

Please let us know if you have any additional questions.
Kind regards.

**Comment by Travis2022** [comment]
@ishij 
@Ivan777111 
could you recover your wallet, if not I can help you restore it : anywalletrecovery@gmail.com
