### ISSUE TITLE
Amazon card (and other wallet options) has disappeared from phone app. Windows Phone no longer supported.

### ISSUE THREAD

**Issue by revcozmo** [bitpay/copay#8819]
the title says. I have had the option to purchase Amazon cards directly from my wallet for quite a while.
That option is no longer available on my Windows Phone wallet app.
Is there an update or something I can do to get that back?

**Comment by BGalliotti** [comment]
Hello @revcozmo 

Thanks for reaching out to us.

**The Windows Phone app is no longer supported and has no updates.**

You can download the latest version of the app for Android or iOS (iPhone/iPad).
If you want to use it on a computer, you can download it here:

- https://github.com/bitpay/copay/releases

Scroll down to the see the blue squares with the icons for each operative system.

Please let us know if you have any additional questions.
Kind regards.
