### ISSUE TITLE
Accessing Coinbase wallet

### ISSUE THREAD

**Issue by sdholste** [bitpay/copay#8820]
Hi. I have linked my Coinbase account to my Copay account. I bought bitcoin through Coinbase on the Copay app and it had gone into my wallet on the Coinbase app... how do I access those funds to make a payment through Copay app? Thanks.

**Comment by BGalliotti** [comment]
Hello @sdholste ,

Thanks for reaching out to us.

According to you, the funds have reached your wallet. In that case, your balance should be reflecting those funds.

If you do not see the funds, **Please open up your BitPay app and try the following steps:**

- ("Settings" > "Wallet" > "More Options" > "Transaction History" > "Clear cache")
- ("Settings" > "Wallet" > "More Options" > "Wallet Addresses" > "Scan addresses for funds")

To know how to make a payment, watch this [video](https://www.youtube.com/watch?v=jctgoHSwPM0&t=37s).

Please let us know if you have any additional questions.
Kind regards.

**Comment by sdholste** [comment]
Hi


The problem is that the BTC funds are in my COINBASE wallet, which I have linked to my COPAY app, but they do not show in my COPAY app so I cannot pay for anything. My personal wallet in COPAY shows as empty. When I click on the coinbase icon under services, I just get the option to buy or sell some more bitcoin.... how can I get the app to access the BTC funds in COINBASE to pay for something?


Thanks,

Stephen

________________________________

**Comment by BGalliotti** [comment]
Hello @sdholste ,

Thanks for reaching out to us.

Please send us a screenshot of the screen showing the Coinbase transaction within the Bitpay/Copay app.
We need to know if the operation is **Complete, Pending or if there was an error.**

Bear in mind the operation might take a while.

Try opening and closing the app, it syncs with the Coinbase server to retrieve the funds.

Please let us know if you have any additional questions.
Kind regards.

**Comment by smiles420** [comment]
I’m having the exact same issue. Once purchasing through copay my finds stay on coinbase and I have to resend them and pay more fees to have my btc in my copay wallet. I’ve tried what you suggested above and I’ve deleted and reinstalled the app.

**Comment by BGalliotti** [comment]
Hello @smiles420 

Thanks for reaching out to us.

**What version of the wallet are you using?**

**Please try the following workaround:**

- Tap **Receive** on the bottom menu of the app
-  Tap the QR code to copy the address
- Log into **Coinbase** on my mobile browser
- Go through their send flow and add the bitpay wallet address

Check out this [video](https://www.youtube.com/watch?v=UE1OLYW50XM&t=23s) on how to buy and sell bitcoin with Coinbase, it might be helpful.

It can take up to **6 hours** approximately for the funds to arrive your bitpay wallet.

If after this time you do not see your funds in the wallet (and the payment is properly confirmed):

**Please open up your BitPay app and try the following steps:**

- Settings > Wallet > More Options > Transaction History > Clear cache

- Settings > Wallet > More Options > Wallet Addresses > Scan addresses for funds

**Please do not uninstall the app or delete the wallet if you did not back it up properly, in such case, please do so. This is the only way to recover your wallet.**

Please let us know if you have any additional questions.
Kind regards.

**Comment by sdholste** [comment]
Thanks. Thanks worked ok.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by BGalliotti** [comment]
Hello @sdholste 

Thanks for your update. 
Kind regards.
