### ISSUE TITLE
BitPay 4.4.0 Doesn't Run on Windows 7 32-bit. No 32-bit support.

### ISSUE THREAD

**Issue by Aureuum** [bitpay/copay#8826]
BitPay 4.4.0 Doesn't Run on Windows 7 32-bit.
Could you make a version that runs on Windows 7 32-bit as well?
Thank you!

**Comment by BGalliotti** [comment]
Hello @Aureuum ,

Thanks for reaching out to us.

**The desktop version of the wallet is only available in 64-bit.**
As the development team has decided time ago, to stop supporting the 32-bit application, they are not developing for the 32-bit architecture any longer.

If your computer architecture is 64-bit, you can install a 64-bit OS (you can have a 64-bit architecture computer and a 32-bit OS installed).

To check what is your case, please follow this link: https://www.computerhope.com/issues/ch001121.htm

As a workaround, you can download the mobile version on the [App Store (iOS)](https://itunes.apple.com/us/app/bitpay-secure-bitcoin-wallet/id1149581638) or [Google Play Store (Android)](https://play.google.com/store/apps/details?id=com.bitpay.wallet) depending on which phone/tablet you have.

Please let us know if you have any additional questions.
Kind regards.
