### ISSUE TITLE
Amazon gift card

### ISSUE THREAD

**Issue by jaroliverpool** [bitpay/copay#8830]
I made a request for 2.80 amazon gift card copay took my btc but never got the code to redeem the gift card please help

**Comment by jaroliverpool** [comment]
https://imageshack.us/i/pnesGXDZp

**Comment by BGalliotti** [comment]
Hello @jaroliverpool 

Thanks for reaching out to us.

Please write to the Bitpay support: https://help.bitpay.com/requestHelp
Our representatives are going to address your inquiry there.

We would appreciate your patience.

Thanks in advance, Kind regards.
