### ISSUE TITLE
Amazon invoice 

### ISSUE THREAD

**Issue by sudotcpdump** [bitpay/copay#8831]
Whenever I try to create an Amazon gift card it tells me "could not create invoice" 

I have enough confirmations 
I've tried reinstalling app
Ive tried android and windows 10
I've tried creating a new wallet twice 

Dont know what else to do never had an issue buying Amazon gift cards until now.

**Comment by hacuong1990** [comment]
Hay thuan tien

**Comment by BGalliotti** [comment]
Hello @sudotcpdump  @SpyShadow117  @hacuong1990 

Thanks for reaching out to us.

Please write to the Bitpay support: https://help.bitpay.com/requestHelp
Our representatives are going to address your inquiry there.

We would appreciate your patience.

Thanks in advance, Kind regards.

**Comment by sudotcpdump** [comment]
Thanks they emailed me

**Comment by BGalliotti** [comment]
Hello @sudotcpdump 
Awesome! thanks for your update
Kind regards.
