### ISSUE TITLE
Wallet not backed up - opened from fresh windows install

### ISSUE THREAD

**Issue by smokenmirrors2** [bitpay/copay#8836]
I don't recall backing up my wallet, and I had the bitcoin.com wallet files on an external hdd, whenever I opened it, my wallet was available. After doing a fresh windows install, I now am asked to create bitcoin wallet or restore from backup ... I guess I should have done a backup ....

**Comment by BGalliotti** [comment]
Hello @smokenmirrors2 

Thanks for reaching out to us.

**Is your inquiry related to the Copay/BitPay wallet ?**

Please let us know if you have any additional questions.
Kind regards.

**Comment by smokenmirrors2** [comment]
https://wallet.bitcoin.com/

This one, I was wondering if it would be possible for me to copy any old files from the previous OS over to the new one? I was able to open the wallet before so there must have been some files it deleted.

**Comment by BGalliotti** [comment]
Hello @smokenmirrors2 

Thanks for reaching out to us.

**We are not related to the Bitcoin.com wallet.**

Please reach out to the [Bitcoin.com forum](https://forum.bitcoin.com/) and post your inquiry there.

Please let us know if you have any additional questions regarding Copay/Bitpay wallets.
Kind regards.

**Comment by Travis2022** [comment]
@smokenmirrors2 
I can recover your backup if need help pm me : anywalletrecovery@gmail.com
