### ISSUE TITLE
Missing funds

### ISSUE THREAD

**Issue by shp42069** [bitpay/copay#8837]
Sent a payment it was never received by the recipient nor was i notified that it had been received in my wallet it says moved Says it was paid and confirmed the recipient says they never received the funds. 

96997e1991e05eb0ab05a666014ffe1551f25af941938bf77a41f97c5c777949

**Comment by BGalliotti** [comment]
Hello @shp42069 

Thanks for reaching out to us.

> Sent a payment it was never received by the recipient nor was i notified that it had been received in my wallet it says moved Says it was paid and confirmed the recipient says they never received the funds.

**Please try to be clear on your explanations using well-formed phrases and punctuation signs, we do not exactly understand what are you expecting from the transaction.**

The transaction has properly gone through: 

https://live.blockcypher.com/btc/tx/96997e1991e05eb0ab05a666014ffe1551f25af941938bf77a41f97c5c777949/

Please let us know if you have any additional questions.
Kind regards.

**Comment by shp42069** [comment]
It’s very simple. I sent the funds. It said on my end that it went thru, the funds are no longer in my account, but the recipient never received the funds in their account. I’m not sure how that’s unclear.

**Comment by BGalliotti** [comment]
Hello @shp42069 

Thanks for clearing this up.

The funds were properly sent, so everything is fine on our end.

Please tell the recipient to check with their end.

Kind regards.

**Comment by shp42069** [comment]
This is not answered. The money is still missing please reverse the transaction!

**Comment by BGalliotti** [comment]
Hello @shp42069 

Thanks for reaching out to us.

The transaction has gone through, and it has **2379 confirmations.**
- A transaction is considered **complete and not reversible, after six (6) confirmations**. We cannot reverse the transaction (nobody can do that).
- The funds were received, furthermore, they were already spent, so nobody can tell you they did not receive the funds.

There are two possibilities:

- They are lying/trying to scam you.
- You sent the funds to a different address than the expected

However, there is no fault on our side, and unfortunately, there is nothing we can do for you.

Kind regards.

**Comment by Travis2022** [comment]
@shp42069 
did you get back your lost fund, I might help you just send me gmail : anywalletrecovery@gmail.com
