### ISSUE TITLE
Increase privacy

### ISSUE THREAD

**Issue by fabianfabian** [bitpay/copay#8839]
When I start Copay, connections are made to Bitpay, Github, Google and Kraken.

It would be nice if we could have the option to minimise third party snooping, I assume the connections to Bitpay are required for basic functionality, but Github (checking for updates?), Google (analytics?) and Kraken (exchange rates?) should be optional.

If my guesses are wrong it is because your privacy policy is too generic and not clear on this.

<img width="381" alt="screen shot 2018-07-03 at 22 56 57" src="https://user-images.githubusercontent.com/343640/42244284-b5ef6a68-7f14-11e8-9a83-948e81d42f86.png">

**Comment by dan-da** [comment]
3rd party snooping by default is really unacceptable in a bitcoin wallet.  Any such should be explicitly opt-in, not opt-out.

**Comment by cmgustavo** [comment]
Fixed: https://github.com/bitpay/copay/blob/master/CSP.md
