### ISSUE TITLE
Reference Number 

### ISSUE THREAD

**Issue by BluBenji** [bitpay/copay#8849]
I sent a payment that got refunded and they said that co pay has a place I put the reference number to redeem my Money , and I don’t see where it’s at and be more the 4 hours

**Comment by BGalliotti** [comment]
Hello @BluBenji 

Thanks for reaching out to us.

Please contact the Bitpay support here: https://help.bitpay.com/requestHelp

They will take care of your inquiry.
Please let us know if you have any additional questions.
Kind regards.
