### ISSUE TITLE
Disassociate email address from wallets

### ISSUE THREAD

**Issue by CR0CKER** [bitpay/copay#8852]
I receive email notifications for every transfer and don’t remember ever giving my email address to Copay. There should be a way to prevent Copay from registering my wallets with Bitpay and sending me email notifications. I have turned off the email notifications in my copay settings, but don’t see any way to remove my email records and wallet records from Bitpay servers.  

It’s also not clearly communicated what information is being sent to Bitpay when generating wallets or making transactions. This should be made very clear.

**Comment by BGalliotti** [comment]
Hello @CR0CKER 

Thanks for reaching out to us.

Please update the wallet. Then go to Settings > Notifications
If your email is set, delete and disable the email notifications.

If your email is not set, please enter it on the email field in the bottom (the email address where all the notifications are being sent), enable the notifications, and close the app.

Reopen the app then go to Settings > Notifications , remove your email address and disable the email notifications.

> It’s also not clearly communicated what information is being sent to Bitpay when generating wallets or making transactions. This should be made very clear.

I will research this point and answer to you. If you want to, you can open a ticket so we can take it as a feature request.

Please let us know if you have any additional questions.
Kind regards.
