### ISSUE TITLE
BITPAY WALLET RECOVERY

### ISSUE THREAD

**Issue by travelkapil** [bitpay/copay#8853]
HI I AHVE BIT WALLET WHICH HAVE BTC, MY PHN LOST, I HAVE ONLY EMAIL WALLET PASSWORD AND LAST LATEST BTC ADDRESS OF MY SAME WALLET, PLS DO NEEDFULL, HELP ME OUT

**Comment by BGalliotti** [comment]
Hello @travelkapil 

Thanks for reaching out to us.

The only way to recover the wallet is by the 12-word phrase.
Please refer to  #8532

Please let us know if you have any additional questions.
Kind regards.

**Comment by travelkapil** [comment]
I have only registered email, password and latest address of btc

**Comment by BGalliotti** [comment]
Hello @travelkapil 

Then, unfortunately, there is no way to recover the wallet.

Please read the recommendations on #8532 in regards to the wallet backup.

Kind regards.
