### ISSUE TITLE
Password on wallet creation process / import 3rd party wallet

### ISSUE THREAD

**Issue by Hansizhan** [bitpay/copay#8859]
I noticed that there is no password option when I create a new wallet. Would you like explain why you cancel the password option? Thank you.

**Comment by BGalliotti** [comment]
Hello @Hansizhan 

Thanks for reaching out to us.
Which version of the wallet are you talking about?
When you create  a new wallet, on the onboarding you are prompted to protect the wallet with a password as if you want to.

In the app you can always protect the wallet witha password:

Open the app > Go to **Settings** > Wallet (the wallet you want to protect) > enable **R

Please let us know if you have any additional questions.
Kind regards.

**Comment by Hansizhan** [comment]
Hello, it is the latest version. I am not referring to the password of copay or bitpay wallet, I am referring to the phrase password option of bip39.

**Comment by BGalliotti** [comment]
Hello @Hansizhan 

Thanks for reaching out to us.

**Are you talking about the wallet backup?**
Every wallet has its own phrase, that is what makes the wallet unique, that feature is of course still available.

If you haven't backed up your wallet, please first go to Settings > Your Wallet Name > Backup. [Write down the 12 word backup phrase and secure it](https://blog.bitpay.com/private-key-security/). We do not recommend emailing it to yourself.

To import the wallet on another device, you can click the **+** next to Wallets and then choose **Import wallet**. Enter the 12 word backup phrase and you will now have access to the wallet from both devices.

Please see the [following article](https://support.bitpay.com/hc/en-us/articles/115003028346
wallet-from-Copay-to-BitPay-) for steps on how to restore the wallet from a backup.

**If you have created your wallet with a 3rd party software and you want to specify the passphrase:**
(for example, you created the wallet with Samourai Wallet and now you want to use that wallet in Bitpay/Copay) app:

- Tap on **Create a new wallet** on the top of the app
- Tap **Create personal wallet**
- Enter a wallet name, select **BTC** as coin
- Tap on the **Show advanced options** dropdown  
- Tap on the **Wallet key** dropdown (it is set to **Random** by default) and select **Specify Recovery Phrase**
- Tap on **Wallet recovery phrase** and then **OK** > enter your passphrase. After entering your passphrase and checking all the recommendations on (**5**)  you will be prompted to secure the wallet with a password, tap **NO** then tap **I'M SURE**.

Please let us know if you have any additional questions.
Kind regards.

**Comment by tabathap** [comment]
👌
