### ISSUE TITLE
Referring to issue #8023 that you have closed

### ISSUE THREAD

**Issue by QuestBit** [bitpay/copay#8860]
Hi there,

The wallet address is correct. The address of recipient would not go wrong because the earlier transaction went through and after few minutes another transaction took place to the same address but the bitcoin was not received that you can view in the transaction ID’s that I gave. I can show you the recipient wallet account. This is the recipient’s wallet ID: 

650a6640-25d7-4023-b70c-51bdd793350a

In fact, I’ve contacted blockchain wallet as well. But there’s no reply from their end. How do we suppose to resolve this ?

Thank you. 

Regards,

QuestBit

**Comment by BGalliotti** [comment]
Hello,
We are re-organizing all the support tickets.
Since there is already an open issue for this same question, we will close it.

Thanks
