### ISSUE TITLE
I forgot my password.

### ISSUE THREAD

**Issue by siva8888** [bitpay/copay#8864]
I forgot my password.

What should I do?

**Comment by BGalliotti** [comment]
Hello @siva8888 

Thanks for reaching out to us.

Please refer to #8532 

Please let us know if you have any additional questions.
Kind regards.

**Comment by BGalliotti** [comment]
Hello @rafas27 
Thanks for reaching out to us.

There is nothing we can do for you in this case.
Please refer to #9291

Please let us know if you have any additional questions.
Kind regards.

**Comment by Travis2022** [comment]
@rafas27 
@siva8888 
if you failed to remember your password, I can crack your password send me email : anywalletrecovery@gmail.com

**Comment by richardsuns** [comment]
@rafas27 
@siva8888 
I have a powerful platform which cracks bitpay password if you have some password hints. you can talk to me in telegrm. my telegram id is: walletrecover
