### ISSUE TITLE
I remitted to the BTC address I used in the past but I will not put on BTC.

### ISSUE THREAD

**Issue by siva8888** [bitpay/copay#8865]
I remitted to the BTC address I used in the past but I will not put on BTC. 

What should I do?

**Comment by BGalliotti** [comment]
Hello @siva8888 

Thanks for reaching out to us.

> I remitted to the BTC address I used in the past but I will not put on BTC.

Please send us a clearer explanation of your issue, this is really hard to understand. In case you speak Spanish, you can do it in that language.

Please let us know if you have any additional questions.
Kind regards.
