### ISSUE TITLE
App issues on iphone 

### ISSUE THREAD

**Issue by chamcfc** [bitpay/copay#8869]
I’m not sure if it was the latest update but everytime I click a transaction it says “transaction not found” and nothing shows up in history if I click the wallet

**Comment by chamcfc** [comment]
Now it says transaction not available at this time

**Comment by cmgustavo** [comment]
Try to clear cache history: ```Settings > Wallet Settings > More Options > Transaction History > Clear cache```
Please, let us know if it solves your issue.

Thanks

**Comment by chamcfc** [comment]
Yep that worked! Thank you so much
