### ISSUE TITLE
Nexus 5 6.0.1 Hangs at Splash Screen / White Screen

### ISSUE THREAD

**Issue by VRRollerCoaster** [bitpay/copay#8870]
Nexus 5 on Marshmallow 6 6.0.1, after I updated the CoPay app it now hangs at the splash screen, then goes to a white screen after. I don't have any coins, but still can't use this app.

Screenshots:
![1](http://pasteupload.com/images/2018/07/12/Screenshot_20180712-1418232.jpg)
![2](http://pasteupload.com/images/2018/07/12/Screenshot_20180712-1419232.jpg)

**Comment by BGalliotti** [comment]
Hello @VRRollerCoaster 

Thanks for reaching out to us.

We are sorry you have had this bad experience.

We have tested the app with the exact same phone, and it is working properly.

Our phone:

LG Nexus 5
Android 6.01
Android security patch level: October 5, 2016
Copay wallet 4.5.0

Try uninstalling and re-installing the app. Then restart the phone (turn off and on) and open the app.

Please let us know if you have any additional questions.
Kind regards.

**Comment by VRRollerCoaster** [comment]
Not worth my time... I just uninstalled. Thanks for trying to help.
