### ISSUE TITLE
How to import P2SH wallet to copay

### ISSUE THREAD

**Issue by Hansizhan** [bitpay/copay#8877]
I created a P2SH address wallet in electrum balance 1BTC, but I can't import P2SH wallet via seed.
When I enter the seed, the result is a P2PKH address wallet, balance 0

**Comment by BGalliotti** [comment]
Hello @Hansizhan 

Thanks for reaching out to us.

To import the PS2H wallet, you have to manually set the derivation path.
**To create a wallet:**

- Open your Bitpay/Copay app > Tap on the **+** sign on Bitcoin Wallets > Create Personal Wallet >  Enter a wallet name, select BTC as coin
- Tap **Show advanced options** and within **wallet key** select **Specify Recovery Phrase**
- Change the derivation path (probably changing the purpose constant from **44** to **45** it could work, you should check the Electrum documentation).
- Enter the recovery phrase
- Tap **Create wallet**
- When you are asked to protect your wallet with a password, tap "yes" enter your password, and write it down on a piece of paper.
- Now your wallet says "Needs backup". Follow this video to back up your wallet: https://bit.ly/2Jz1cFZ
- **Remember to write down your password and 12-word passphrase on a piece of paper and store it in a safe place. The 12-word phrase is the *only* way to recover your wallet, *this step is extremely important*.**

Please let us know if you have any additional questions.
Kind regards.

**Comment by Hansizhan** [comment]
According to your method, you can't restore assets. My wallet is derived from 44. It is a 2-2 wallet P2SH. I can't recover it by creating a new wallet. I want to know if I can import the wallet by changing BWS?

**Comment by BGalliotti** [comment]
Hello @Hansizhan 

Thanks for reaching out to us.

We assumed your wallet was a 1-1. 

In your case, follow these instructions:

- Open your Bitpay/Copay app > Tap on the **+** sign on Bitcoin Wallets 
- Tap Create Shared Wallet 
- Enter a wallet name
- Select BTC as coin
- Set the number of copayers and required signatures to **2**
- Tap **Show advanced options** and within **wallet key** select **Specify Recovery Phrase**
- Change the **derivation path** and **BWS** manually. Make sure about the configuration you have to use, if this is wrong, you will not see your wallet funds.
- Enter the recovery phrase
- Tap **Create wallet**
- When you are asked to protect your wallet with a password, tap "yes" enter your password, and write it down on a piece of paper.
- Now your wallet says "Needs backup". Follow this video to back up your wallet: https://bit.ly/2Jz1cFZ
- **Remember to write down your password and 12-word passphrase on a piece of paper and store it in a safe place. The 12-word phrase is the *only* way to recover your wallet, *this step is extremely important*.**

Please let us know if you have any additional questions.
Kind regards.

**Comment by Hansizhan** [comment]
My shared wallet phrase is covered by P2PHK wallet and can't be recovered. Besides https://bws.bitpay.com/bws/api, is there any other BWS to choose?

**Comment by BGalliotti** [comment]
Hello @Hansizhan 

Thanks for reaching out to us.

> My shared wallet phrase is covered by P2PHK wallet and can't be recovered.

This is not what you told us in the beginning, that is why we looked for a solution regarding P2SH.

> I created a P2SH address wallet in electrum balance 1BTC, but I can't import P2SH wallet via seed.
When I enter the seed, the result is a P2PKH address wallet, balance 0

This is what you told us.

Again, you should change the purpose constant, as we described in the previous answer, in order to change the derivation path, ask Electrum support/documentation to know how to do it.

Some wallets use a BWS (Bitcoin Wallet Service) some others not.
As far as I know, there are no "public" BWSs to use. You can set up your own if that was your idea.
Please check this [article](https://bitcore.io/guides/wallet-service/) out.

Please let us know if you have any additional questions.
Kind regards.
