### ISSUE TITLE
BitcoinZ mined not showing up in wallet

### ISSUE THREAD

**Issue by kryptob** [bitpay/copay#8878]
Good day, i have successfully mined over 5k bitcoinz to my wallet address t1MVMeQoxoN3Yf1PU3DngpvAxsZC8wpgF5w  from this pool https://bitcoinz.axepool.com/ , and till now it's not showing up in my wallet.  Please what do i do ?

**Comment by BGalliotti** [comment]
Hello @kryptob ,

Thanks for reaching out to us.

Are you using the Bitpay/Copay wallet? If not, please reach your wallet support. 
The address is not a Bitpay/Copay wallet neither a transaction, address, block.

If the transaction has gone through, you should see it in your wallet. 


Please let us know if you have any additional questions.
Kind regards.

**Comment by kryptob** [comment]
Hi Yes, I’m using a copay wallet.  That is my address I have on the wallet and I’ve received funds to it before.

**Comment by BGalliotti** [comment]
Hello @kryptob 

Thanks for reaching out to us.

**Our wallet only works with bitcoin and bitcoin cash**. You would have to look for a wallet which lets you manage **bitcoin Z**.

Please let us know if you have any additional questions.
Kind regards.
