### ISSUE TITLE
Transfer on July 10, 2018 started but not completed.

### ISSUE THREAD

**Issue by LLCruising** [bitpay/copay#8879]
I made a transfer request on July 10 but it never reached my account on the other end. Is there any way the funds can be returned to my bitcoin walletfa61a9ef706e1f0a8bb24df07b86f21ee01b6895204031b36dc21a7a83729dbd

**Comment by BGalliotti** [comment]
Hello @LLCruising 

Thanks for reaching out to us.

The transaction you mention has properly gone through: 
https://live.blockcypher.com/btc/tx/fa61a9ef706e1f0a8bb24df07b86f21ee01b6895204031b36dc21a7a83729dbd/

There is nothing wrong with the Bitpay side, the transaction has reached the destination address.

If it did not reach the **expected** address, you might have sent the funds to a different address.

Please let us know if you have any additional questions.
Kind regards.
