### ISSUE TITLE
transaction

### ISSUE THREAD

**Issue by kindralea** [bitpay/copay#8884]
hello i have a transaction that did not go through  it timed  out and the money never came  back onto my account i need you look at rhis transaction and tell me why or how this is going on  19c56aec5f83fd43a20330ab1c83f566c70a89f859f7a8246d4777f4dc6fe606 is the transaction and they are saying they never received it you timed it out and they were never given the bitcoin.  please explain this to me and what excactly  happened to the bitcoun

**Comment by BGalliotti** [comment]
Hello @kindralea 

Thanks for reaching out to us.

The transaction you mention has properly gone through, you can check it out here:

https://live.blockcypher.com/btc/tx/19c56aec5f83fd43a20330ab1c83f566c70a89f859f7a8246d4777f4dc6fe606/

The Bitcoin has reached the destination address, there are two chances:

- The address where you sent the funds to, is not the desired address
- They are trying to scam you

Please let us know if you have any additional questions.
Kind regards.

**Comment by BGalliotti** [comment]
Hello @kindralea 

Thanks for reaching out to us.

A transaction has an origin and a destination address. If they have given you the destination address -and there is some proof of that- (like an email), then you have the transaction that has gone through and shows the destination address, basically it proves the funds have reached the destination address.

Please let us know if you have any additional questions.
Kind regards.

**Comment by kindralea** [comment]
yes they are saying there system times out after 15 minutes and what happeneds if that is true were does the money go at that point because they have no reason to lie they are loosing money if they were lying. and i have gone over this with them pretty throughly  and on there end the transaction did not go through and i need to know were the money went if thats the case as the company holding my bitcoin shouldnt you be finding out what happened or try and contact and track down what happened cause im going to have to get a attorney and i feel you are reliable. it showes the it was in the block chain but i dont see it was received that it was just sent.

**Comment by BGalliotti** [comment]
Hello @kindralea 
Thanks for reaching out to us.

Please write to the Bitpay support: https://help.bitpay.com/requestHelp
Our representatives are going to address your inquiry there.

We would appreciate your patience.

Thanks in advance, Kind regards.
