### ISSUE TITLE
Consulta de deposito

### ISSUE THREAD

**Issue by WalterPY** [bitpay/copay#8885]
Hola, he depositado en mi billetera el día jueves 12/07/2018 una cantidad que hasta ahora no fue confirmada en mi billetera, pero ya se realizo la transacción ese mismo día, eso lo verifique en el blockchain el monto fue de 0.00404600 BTC. si por favor me pudieran ayudar con este deposito que realice gracias

**Comment by tutul523** [comment]
#8885

**Comment by WalterPY** [comment]
Hola, él depositó en mi billetera el día jueves 12/07/2018 una cantidad que hasta ahora no fue confirmada en mi billetera, pero ya realizaste la transacción ese mismo día, eso lo verifica en el blockchain el monto fue de 0.00404600 BTC. si por favor me ayuda con este deposito que gracias

**Comment by BGalliotti** [comment]
Hola @WalterPY ,
Por favor envíenos el ID de la transacción y de su wallet para que podamos chequear la transacción y determinar el problema.

Esperamos su respuesta, saludos cordiales.

**Comment by WalterPY** [comment]
https://www.blockchain.com/en/btc/tx/f9ac74628c7e2bb3f80af1d93a0c0e060259789e79940e692ab945821a514abd
<http://tracking.freebitco.in/tracking/click?d=iAjB32zagnLkTkRfx6apsJwHrHzCqZe3HhYQt-8eAlXsS9euLqV8z5Mj-YF_JOe035-2EFO-JjANpNb4DTuokErU2vDnqE0LDljZWwSojKgbl4JCulE3ZWk3ZHgcGMy7aJ8RTFHZGj3GEsE0o2y7pze3iT0iN5AY89iCfC1yrQegZaKgp7sq--zt56Or4Uk1JwoxRiGuOIripedtkLhGO4M1>
.

19UYscFVLNJuu5txwBZchiVhEMShfdw1Q1

**Comment by BGalliotti** [comment]
Hola @WalterPY,

Está usando la billetera de Bitpay / Copay?

La transacción que nos envía, está confirmada y correcta.

La dirección  19UYscFVLNJuu5txwBZchiVhEMShfdw1Q1 no está relacionada con esta transacción.

Si está usando una billetera diferente a Copay / Bitpay, diríjase al soporte de su billetera.
Verifique la transacción y el ID de billetera (lo que nos pasó no es un ID de billetera de Bitpay/Copay).

Si no entiende algo de lo que le pedimos, dejenoslo saber, esto facilitará la resolución del problema.

Saludos cordiales.

**Comment by WalterPY** [comment]
Estoy usando la billetera copay y es transacción en el blockchain esta relacionada con esa dirección de billetera. Adjunto imagen del correo de confirmación a esa dirección de correo

![sin titulo](https://user-images.githubusercontent.com/38765983/42878952-417b5064-8a65-11e8-809e-eca894df8876.png)

**Comment by WalterPY** [comment]
envió imagen de la billetera 

![sin titulo](https://user-images.githubusercontent.com/38765983/42879484-3272adea-8a67-11e8-9407-6b131557a67b.png)

**Comment by WalterPY** [comment]
f9ac74628c7e2bb3f80af1d93a0c0e060259789e79940e692ab945821a514abd

este es el ID de la confirmación en el blockchain, de esa transacción

**Comment by WalterPY** [comment]
La billetera que utilizo es de COPAY y la direccion de billetera que le envie es de copay
este es el ID de la transacción f9ac74628c7e2bb3f80af1d93a0c0e060259789e79940e692ab945821a514abd

le envió imágenes 
![sin titulo](https://user-images.githubusercontent.com/38765983/42881099-fecf1b94-8a6c-11e8-8610-cdfe6ff2aa68.png)

**Comment by BGalliotti** [comment]
Hola @WalterPY ,

La billetera que usted adjunta en la imagen, es de Copay y es la que se usó para enviar los fondos a **19UYscFVLNJuu5txwBZchiVhEMShfdw1Q1**.

**19UYscFVLNJuu5txwBZchiVhEMShfdw1Q1** está asociado a la transacción que usted mencionó previamente, no la vimos por que eran demasiados outputs.

El caso es el siguiente:

- Usted (o alguien) envió fondos desde una billetera de Copay a **19UYscFVLNJuu5txwBZchiVhEMShfdw1Q1**
- La dirección **19UYscFVLNJuu5txwBZchiVhEMShfdw1Q1** no pertenece a Copay / Bitpay por lo tanto no espere encontrar fondos en billeteras de Copay/Bitpay.
- Si la persona/entidad que debía recibir los fondos, dice no haberlos recibido, pidales que vuelvan a chequearlo. Los fondos fueron recibidos y ya fueron gastados.

Puede ver esto aquí: https://live.blockcypher.com/btc/address/19UYscFVLNJuu5txwBZchiVhEMShfdw1Q1/

Si tiene alguna otra consulta, no dude en escribirnos.

**Comment by WalterPY** [comment]
Muchas gracias, voy a crear otra billetera

**Comment by BGalliotti** [comment]
Hola @WalterPY ,

Por nada, espero que haya entendido la explicación que dimos.

Si crea una nueva billetera, ésta es totalmente distinta, tendrá saldo cero y no tiene nada que ver con las direcciones y transacciones mencionadas previamente. 

Saludos cordiales.

**Comment by BGalliotti** [comment]
Hola @WalterPY ,

Cuando usted envía fondos, usted elige una dirección de destino, la cual puede pertenecer a Copay/Bitpay o no, la dirección de destino no es "generada" por la misma billetera que envía los fondos.

La dirección **19UYscFVLNJuu5txwBZchiVhEMShfdw1Q1** no se encuentra en nuestra base de datos.

**Comment by BGalliotti** [comment]
Hola @WalterPY ,

No hemos tenido problemas con nuestra base de datos, por lo cual descartamos esa opción.

Si esa fuese una dirección de Bitpay/Copay, deberíamos encontrarla.

Podría haber ocurrido lo siguiente:
- Usted recibe fondos de 19UYscFVLNJuu5txwBZchiVhEMShfdw1Q1
- Usted ve 19UYscFVLNJuu5txwBZchiVhEMShfdw1Q1 en alguna transacción (lo cual no implica que tenga algo que ver con Bitpay/Copay)
- Usted envía fondos a esa dirección que cree que pertenece a Bitpay/Copay

**Comment by WalterPY** [comment]
yo creo que se están confundiendo al decir que la
dirección 19UYscFVLNJuu5txwBZchiVhEMShfdw1Q1 no es de COPAY si ya realice 6
transacciones con esa misma dirección y me llego todas menos esta ultima es
imposible que no sea de la billetera de COPAY mirando en blockchain te das
cuenta que todas las transacciones anteriores se realizaron a esa dirección
y en la captura que te envié también vez que es del software de copay.

**Comment by WalterPY** [comment]
yo deposite en esta billetera, y si es de ustedes esta en su software
aqui le envio la prueba con el QR para que vean que si es de ustedes
que no se haya depositado es el inconveniente por que la transacción fue
confirmada

**Comment by WalterPY** [comment]
Ya encontré donde está el problema, gracias por la paciencia

**Comment by BGalliotti** [comment]
Hola @WalterPY ,

Nos alegramos de que haya encontrado el problema, gracias por avisarnos.

Saludos cordiales.

**Comment by jairogutierrez1** [comment]
Hola buenas tardes 
Es que tengo un problema con una transacción que realice por medio de mi wallet en bitpay, la realicé el día 20 de junio y hoy es 22 y aún no ha sido confirmada y debido a eso no puedo darle uso a mi wallet, alguien sabe como hacer para confirmar esa transacción o que puedo hacer para solucionar esto, cada que intento hacer un envío de btc me sale error 500

**Comment by BGalliotti** [comment]
Hola @jairogutierrez1 
Gracias por ponerse en contacto con nosotros.

Por favor, si el hilo está cerrado o su consulta no está directamente relacionada con la conversación, abra un nuevo hilo/issue.

La confirmación de la transacción no puede acelerarse en su caso. Para saber más sobre por qué las transacciones demoran en confirmar, lea [éste](https://github.com/bitpay/copay/issues/8803#issuecomment-398775441) post (en Inglés).

En cuanto al error 500, puede deberse a cuestiones de conectividad, por favor intente nuevamente.
En qué país se encuentra?

Por favor, háganos saber si tiene alguna pregunta adicional.
Saludos cordiales.
