### ISSUE TITLE
System Attack bitpay.exe

### ISSUE THREAD

**Issue by SpazRex** [bitpay/copay#8889]
I updated my bitpay wallet and now im getting an alert for a system attack. Its popping up every 10 seconds.
Im not sure whats going on cause even in my bitpay wallet i cannot see my btc value says network error.
Any help would be great!

![issue_li](https://user-images.githubusercontent.com/41357340/42862613-177387a0-8a15-11e8-94d5-b8917f227870.jpg)

![issue2](https://user-images.githubusercontent.com/41357340/42862517-ae128c48-8a14-11e8-8d6b-f6a6df27490f.PNG)

**Comment by BGalliotti** [comment]
Hello @SpazRex 

Thanks for reaching out to us.

For some reason DNS8 has classified bws.bitpay.com as malicious service.

DNS8 is reclassifying to clean. Should be resolved on your side as fast as they solve that.

As DNS8 is blocking bws.bitpay.com you are getting the network error.

Please let us know if you have any additional questions.
Kind regards.

**Comment by SpazRex** [comment]
Great, thank you for the response. Ill wait and see what happens. If anything changes Ill post here.

**Comment by BGalliotti** [comment]
Hello @SpazRex 

Thanks for your update.

We will appreciate you posting the news here.

Kind regards.

**Comment by 22split** [comment]
Hello, I have the exact same problem, its still on.

**Comment by BGalliotti** [comment]
Hello @22split 

Thanks for reaching out to us.

We think the problem is the same, we are going to report it.

Regarding the wallet, please refer to #8532 

Please let us know if you have any additional questions.
Kind regards.

**Comment by SpazRex** [comment]
Its still responding the same with no change. Ill keep watching for any progress on my end.

**Comment by jamesscookk** [comment]
Ignore these emails please he is the hacker I will send all pics and info
to ela ela orate has running iOS remote view on my android s8 and somehow
messed with my wifi and switched it has taken my hit hub well he/she and is
doing it to 196 others I saw in his folder left on my phone

**Comment by 22split** [comment]
Want to add that my wallet is a desktop wallet in Win10. I have no other issues than process is blocked by Norton as described above. No notifications without use of Bitpay wallet. Have checked with 3 other programs and no trojans nor viruses on my PC.

**Comment by SpazRex** [comment]
Same here with the notification.

**Comment by 22split** [comment]
Today it was possible to make a new wallet, did not succeed yesterday. Did not try to recover via pass phrase, because no Bitcoins in wallet.

**Comment by SpazRex** [comment]
It seams to be fixed now, not getting the notification anymore. If that changes ill leave a comment.
