### ISSUE TITLE
BTC to Bitpay Visa transaction evaporated

### ISSUE THREAD

**Issue by SFisherlmp** [bitpay/copay#8891]
Hi,
We have Bitpay Visa on our iPhone X. 
At the bottom of the screen is: Home - Receive - Send - Scan - Settings.
We clicked the Receive and got an address 1Q9vekDkF7TBH42mP1LWZk7PCqDpAaCEgy
We went into BTC Wallet and put this address in presuming the .261027 BTC would be withdrawn from out BTC Wallet and later appear in our Bitpay Visa.
We see that the funds did get withdrawn from our BTC Wallet and went into the address.
But then someone sent it to 39hV2nSfQZ1baz3FpgHVp8mT3cofXF59m4. 

Why isn't our BTC in our Bitpay Visa???

Please advise.

**Comment by BGalliotti** [comment]
Hello 
Thanks for reaching out to us.

Please write to the Bitpay support: https://help.bitpay.com/requestHelp
Our representatives are going to address your inquiry there.

We would appreciate your patience.

We will close the ticket.
Thanks in advance, Kind regards.
