### ISSUE TITLE
Exchange fees are terribly high, no middle man please

### ISSUE THREAD

**Issue by ghost** [bitpay/copay#8894]
They charge fees for everything in crypto, we donot need exchange websites for doing trading, is stupid, just have the trading in the apps, just have twtwo smart addresses for litecoin, ethereum and the Chinese Baxter coin, so we can deposit the coins in the smart address and receive directly the btcz, that wsy there is no middle man and no withdraw fees, is freaking stupid, over 100btc for trading, and plus the withdraw fee that is over 160 coins lost there for the middle man, not to mention the fee the network of the coin charges.

**Comment by BGalliotti** [comment]
Hello @fernysalaz 

Thanks for reaching out to us.

**Could you specify what your issue is, and how can we help you?**
**Is your issue related to Copay/Bitpay app?**

Please let us know if you have any additional questions.
Kind regards.

**Comment by fernysalaz** [comment]
The app should have smart address to exchange directly to them, that way
there is no middle man getting the exchange fee and the withdraw fee, is
unnecessary to have exchange websites sense wallets can directly do this.

**Comment by BGalliotti** [comment]
Hello @fernysalaz 
Thanks for reaching out to us.

We will revise this thread and if it applies, we will put it in our feature request list.

Please let us know if you have any additional questions.
Kind regards.
