### ISSUE TITLE
Order

### ISSUE THREAD

**Issue by MadDadik2** [bitpay/copay#8898]
Sent long, do you can cansel it?
 6f302a01e6e1c6e7ef579eb125b943bade2eadc7c9a8d70cb6e8e40ae2e24a3e

**Comment by BGalliotti** [comment]
Hello @MadDadik2 

Thanks for reaching out to us.

The transaction has no confirmations, however, it can not be reversed, there is nothing to be done.

Please let us know if you have any additional questions.
Kind regards.

**Comment by MadDadik2** [comment]
In wallet write "waiting confirm 0.04295". I no have open transaction on this higher 0.0005

**Comment by BGalliotti** [comment]
Hello @MadDadik2 

Thanks for reaching out to us.

> I no have open transaction on this higher 0.0005
**We do not quite understand this, please to be clear on the explanation.**

No matter the amount of the transaction, it cannot be reversed.

Please let us know if you have any additional questions.
Kind regards.

**Comment by BGalliotti** [comment]
Hello @MadDadik2 

**We have not heard of you in while!**

**Are you still experiencing an issue?**

We are going to close this thread, please if you need further help, open a new one explaining the issue in detail, providing all the relevant information possible, we will be happy to help you :)

Kind regards.
