### ISSUE TITLE
Is there Android apk file for download？

### ISSUE THREAD

**Issue by daffy6537** [bitpay/copay#8924]
same as the title

**Comment by BGalliotti** [comment]
Hello @daffy6537 

Thanks for reaching out to us.

No, you can download the Bitpay/Copay app from the Google Play store.

Please let us know if you have any additional questions.
Kind regards.

**Comment by daffy6537** [comment]
@BGalliotti Thanks a lot

**Comment by daffy6537** [comment]
Thank you very much @BGalliotti

**Comment by BGalliotti** [comment]
You're welcome @daffy6537 

if you have any other concern, please open a new thread.

Kind regards.
