### ISSUE TITLE
Copay transaction lost

### ISSUE THREAD

**Issue by wintergarten** [bitpay/copay#8925]
Is it possible to get a lost transaction back?
When it is, how could I get it back and how long will it take?

It was a transaction from december 6th at 18am, and it won´t show on my wallet. I didn´t recived any kind of transaction that day.
I pulled a request before, but none of them could help me yet, so if someone know how to pull the money back, could you please contact me.

My e-mail: georgswintergarten@gmail.com
Wallet ID: 6580d186-ea0b-4dfc-8f06-cb3cd1c7f2e9
Kindley regards

**Comment by BGalliotti** [comment]
Hello @wintergarten 

Thanks for reaching out to us.

That is not actually possible. Generally speaking, a transaction cannot be reversed, and after the 6th confirmation, that is practically impossible.


Please let us know if you have any additional questions.
Kind regards.
