### ISSUE TITLE
Backoffice4you

### ISSUE THREAD

**Issue by wintergarten** [bitpay/copay#8926]
#267793 06.12.2017 18:17:00

Details

Status Bestätigt
Zweckmanuelle Auszahlung
Methode Bitcoin
Summe -5000,00 €
Wallet W5649
Richtung Ausgehend
Transaktions ID267793
SystemnachrichtenBitcoin Wallett: 1FJ6CawsKgfGi1CrqEiznBNWF73tT6R9fs

Do someone know how to pull back the money or how to confirm the status of my wallet?
I had a confirmed status but I didn´t recived anything on my wallet.

You can contact me on my e-mail: georgswintergarten@gmail.com

Kindly regards

**Comment by BGalliotti** [comment]
Hello @wintergarten 

Thanks for reaching out to us.

We have found a wallet which holds the address **1FJ6CawsKgfGi1CrqEiznBNWF73tT6R9fs**
 That might be your wallet. 

To access the wallet you need to install the Copay app and import the wallet using the 12*word passphrase.

To know how to do that, please refer to #8532 

Please let us know if you have any additional questions.
Kind regards.

**Comment by aoichai** [comment]
#8532
