### ISSUE TITLE
Never got money that was sent.

### ISSUE THREAD

**Issue by vin2163385** [bitpay/copay#8929]
I had $514 coming from an account that was sent, and the account says it was sent successfully. The company told me to reach out to my wallet provider to find out why I never got my money and it’s been a week.

**Comment by BGalliotti** [comment]
Hello @vin2163385 

Thanks for reaching out to us.
Are you using the Copay/Bitpay wallet?

Please send us your wallet ID and transaction ID so we can check what is going on.
