### ISSUE TITLE
BTC from bitnovo Dash not received

### ISSUE THREAD

**Issue by rainyday69** [bitpay/copay#8935]
Hi,
My wallet ID is 98e7dc62-7e1b-4490-8669-d4e0a73cffca and wallet address is 17uxnE69ucaRkD5sL8kVw3VstgYTUc3Wm2
as stated in the title the BTC originate from bitnovo dash
Thanks in advance for your assistance

**Comment by BGalliotti** [comment]
Hello @rainyday69 

Thanks for reaching out to us.
We have checked your information. 
This is not a Bitpay problem, either the transaction is taking long or you have sent the funds to another wallet/address.

For now, there is nothing we can do for you.

If you want to, send us the transaction ID, we can check it out and tell you what might be going on.

Please let us know if you have any additional questions.
Kind regards.

**Comment by rainyday69** [comment]
Attached to this message is the screenshot of the summary of the
transaction I will check if I can get any further information such as the
transaction ID you requested. Many thanks for your assistance
[image: Screen Shot 2018-08-01 at 3.52.10 AM.png]

**Comment by rainyday69** [comment]
Attached to this message is the screenshot of the summary of the transaction I will check if I can get any further information such as the transaction ID you requested. Many thanks for your assistance 

<img width="1219" alt="screen shot 2018-08-01 at 3 52 10 am" src="https://user-images.githubusercontent.com/41979202/43593229-8d7fab72-9677-11e8-8d03-027a040615c3.png">

**Comment by BGalliotti** [comment]
Hello 
Thanks for the screenshot, it shows the same information you have previously sent.
The address belongs to your wallet, we need the transaction to check what has happened.

Kind regards.
