### ISSUE TITLE
Restored wallet can't send "no wallets available"

### ISSUE THREAD

**Issue by metalgeekstl** [bitpay/copay#8944]
I restored a wallet from a 12-word backup, but when I try to select the wallet to send, I get the above error.

Wallet ID:

456e2404-dd15-4200-83e7-be8fc3ac1d40

**Comment by BGalliotti** [comment]
Hello @metalgeekstl 
Thanks for reaching out to us.

Your wallet is a BCH wallet. 
Are you trying to send funds to a BTC wallet?
Could you send us the destination address?

Please let us know if you have any additional questions.
Kind regards.

**Comment by metalgeekstl** [comment]
Turns out the site I was trying to send to is giving me a BTC address even though I selected BCH. Tested on my Coinbase BCH wallet and it worked.

Please close ticket. Thanks.

**Comment by tatyana197677** [comment]
6580d186-ea0b-4dfc-8f06-cb3cd1c7f2e9

**Comment by BGalliotti** [comment]
Hello  @metalgeekstl 

**We are glad you were able to solve the issue!**

@tatyana197677 please open a ticket explaining your issue so we can assist you.

We are going to close the ticket.
Feel free to open a new one in case you have any questions or concerns.

**Thank you for your interest and support.**
