### ISSUE TITLE
Is it possible that addresses used in the past are displayed again?

### ISSUE THREAD

**Issue by hide7442** [bitpay/copay#8949]
On July 7, 2018 I transferred money from kraken to the address copied from the screen of Copay.
But I did not put on the money.
After checking the transaction history of the block chain,
There was a lot of usage history in the past though it was the address generated from the receipt button.
The address used in the past is displayed again.
The balance is consistent with 0.09216 of BITCOIN I sent money from kraken.

Received address: 19EZfGiZw69rM8tmUFjhkt2gipUWjU7LXe

Is it possible that addresses used in the past are displayed again?

**Comment by BGalliotti** [comment]
Hello @hide7442 
Thanks for reaching out to us.

Sure, you might be moving funds from that address. If that address has funds and you move funds or make payments, it is likely that the funds in that address are going to be used. 

Does that make sense to you?


Please let us know if you have any additional questions.
Kind regards.
