### ISSUE TITLE
error in detail of the transaction

### ISSUE THREAD

**Issue by jacobobek** [bitpay/copay#8953]
It is the first time I buy bitcoin and I pass it to copay's birtual wallet, and I get a message that the transaction is not available at this time because it will be

**Comment by BGalliotti** [comment]
Hello @jacobobek 

Thanks for reaching out to us.

We are sorry you have had this bad experience.

- **Please send us the BitPay/Copay Wallet ID and the transaction hash / ID or the link so we can further investigate and address your inquiry.**

- To get your Wallet ID, open your Copay/BitPay application, then go to `Settings` > [Your wallet] > `More Options` > `Wallet Information`. 
On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste it in your e-mail. 
You can do the same on your computer by clicking on the wallet ID.

- The transaction hash / ID is a alphanumeric chain like this: **d0a23876de7cf87574b5cda7557bcc8af5d84f3fd1e6f4c6063fd6b72b0e69ae**

**We look forward to hearing from you.**
Kind regards.
