### ISSUE TITLE
i received a payment then it say payment not available at this time

### ISSUE THREAD

**Issue by EPTJ0e** [bitpay/copay#8970]
i received a payment then it say payment not available at this time
i need help fast please

**Comment by corn91791** [comment]
Who sent this letter and send us what’s going on with this

On Aug 9, 2018, at 9:21 AM, EPTJ0e <notifications@github.com> wrote:

i received a payment then it say payment not available at this time
i need help fast please

**Comment by EPTJ0e** [comment]
i go to Transaction history then i clear the cache then it work good
