### ISSUE TITLE
Mining with copay address

### ISSUE THREAD

**Issue by bufelo** [bitpay/copay#8981]
Hi there, can anyone advise, can I put in btc wallet address generated some times ago as my mining payment wallet? Will it be lost in transaction which the address generated 3 to 4 weeks ago. Cause copay might generate new address each time it request for btc, as I can see from the addresses on the wallet, it shows unused address. Can someone advise. Thank you in advance.

**Comment by corn91791** [comment]
OK will put my bag in my address

On Aug 12, 2018, at 9:58 AM, bufelo <notifications@github.com> wrote:

Hi there, can anyone advise, can I put in btc wallet address generated some times ago as my mining payment wallet? Will it be lost in transaction which the address generated 3 to 4 weeks ago. Cause copay might generate new address each time it request for btc

**Comment by BGalliotti** [comment]
Hello @bufelo 
Thanks for reaching out to us.

> can I put in btc wallet address generated some times ago as my mining payment wallet?

Yes, but we do not quite recommend it as usually those are a lot of "micro" payments and it ends up being expensive to move those funds. They are most times comparable to the fees itself.
We recommend you to use a wallet like Coinbase's or other exchange.

> Will it be lost in transaction which the address generated 3 to 4 weeks ago.

**No**. All the wallet addresses are valid and if you send the funds to your wallet, they will remain there, no matter in what address.

Please let us know if you have any additional questions.
Kind regards.

**Comment by bufelo** [comment]
Thank you @bgalliotti, appreciated your reply. :)

**Comment by BGalliotti** [comment]
Hello @bufelo 

You are welcome!
Kind regards.
