### ISSUE TITLE
Amazon gift card missing

### ISSUE THREAD

**Issue by BlackTiger1500** [bitpay/copay#9006]
I bought an Amazon gift card a while back and it doesn't appear in the app anymore. I tried reinstalling the app and importing my wallet again but that did not do anything.
![screenshot_20180816-041711](https://user-images.githubusercontent.com/26808641/44197800-b057f000-a10d-11e8-9b0b-a028dd254ab2.jpg)

**Comment by BGalliotti** [comment]
Hello @BlackTiger1500 
Thanks for reaching out to us.

The Giftcards are not associated with a wallet, when you uninstall the wallet, that information is lost.

Could you use the gift card?


Please let us know if you have any additional questions.
Kind regards.

**Comment by BlackTiger1500** [comment]
I was able to see the code for redeeming it but I kept it for later use and I was not warned that gift card information is not stored with the wallet and has to be backed up by the user.

**Comment by BGalliotti** [comment]
Hello @BlackTiger1500 
Thanks for reaching out to us.

Please write to the Bitpay support: https://help.bitpay.com/requestHelp
Our representatives are going to address your inquiry there.
Describe your situation and include the redeeming code, they will very likely solve your issue.

We would appreciate your patience.

Thanks in advance, Kind regards.

**Comment by BlackTiger1500** [comment]
Thats the issue, I dont have the code. It was in the app under the Amazon section and somehow disappeared. And I requested help from Bitpay support.

**Comment by BGalliotti** [comment]
Hello @BlackTiger1500 
Thanks for reaching out to us.

Let me see what I can do for you, we will try to find the transaction.

We would appreciate your patience.

Thanks in advance, Kind regards.

**Comment by BGalliotti** [comment]
Hello @BlackTiger1500 
Thanks for reaching out to us.

You are welcome, we will be requesting you more information in case of need.
For now, we're ok, it is just going to take some time since the transaction/address are not complete.

Please let us know if you have any additional questions.
Kind regards.

**Comment by BlackTiger1500** [comment]
Hey, thanks for your time and help. The representatives from Bitpay support were able to help and I got my gift card code recovered.
