### ISSUE TITLE
Displaying transactions history takes infinite time

### ISSUE THREAD

**Issue by telelvis** [bitpay/copay#9012]
Hello Copay

I have a wallet with some weird transactions in history, e.g. zero fee, very long size, sender and receivers are the same, etc

When I click on a wallet to open it's details, UI says  
"Updating transaction history, Please stand by"
It downloads N transactions and then stucks.

I am running latest Copay 4.5.0 on Mac

Pls let me know how can I troubleshoot this further

Thanks

**Comment by BGalliotti** [comment]
Hello @telelvis 
Thanks for reaching out to us.

Please send us your wallet ID so we can verify the transactions you mention.

**Please open up your BitPay app and try the following steps:**

- Settings > Wallet > More Options > Transaction History > Clear cache
- Settings > Wallet > More Options > Wallet Addresses > Scan addresses for funds


Please let us know if you have any additional questions.
Kind regards.
