### ISSUE TITLE
Sent funds inquiry

### ISSUE THREAD

**Issue by squareoff1212** [bitpay/copay#9024]
Hello copay I send money using app QR code and my money never showed in my acct so I delete the app and redownloaded it I have a 19 word recovery phrase and it doesn’t work on the app so I had to start a new copay I just used the QR code address again and it did the same thing to me twice that $380 down the drain I would like for this problem to be fix either I would like my bitcoins or Money

**Comment by BGalliotti** [comment]
Hello @squareoff1212 
Thanks for reaching out to us.

Please send us your wallet id and transactions ID.

**Where did you send funds to?**

We look forward to hearing from you.
Kind regards.

**Comment by squareoff1212** [comment]
I sent coins to my copay. 

Transaction ID: 063a3d4d9d
Wallet address: 13Hd1ZSzUieDkuAKc9HE12qc4MhoPpdM
Date: 08/14/2018

**Comment by BGalliotti** [comment]
Hello @squareoff1212 
Thanks for reaching out to us.

The address you have sent us is not a valid address and the transaction ID is not complete.

your  wallet address should be something like:
1ErBZaqzzW1ScN34RxYLybwpw3ATSGE3vu

the transaction ID is something like this:

d0a23876de7cf87574b5cda7557bcc8af5d84f3fd1e6f4c6063fd6b72b0e69ae


Please send us the correct information so we can provide you further support.
Kind regards.

**Comment by BGalliotti** [comment]
Hello @squareoff1212 
Thanks for reaching out to us.

You must have the transaction ID, that is independent of the wallet and that lets you check the transaction on the blockchain.

>  the one giving to me has 19 words so it’s not working

the possible number of words are: from 3 to 24 by 3 numbers. (3,6, ..) so something has to be wrong with the number of words.

After you have figured that out,

As your wallet was not created using the Copay wallet you have to import it:

- Tap on **Create a new wallet** on the top of the app
- Tap **Create personal wallet**
- Enter a wallet name, select **BTC** as coin
- Tap on the **Show advanced options** dropdown  
- Tap on the **Wallet key** dropdown (it is set to **Random** by default) and select **Specify Recovery Phrase**
- Tap on **Wallet recovery phrase** and then **OK** > enter your passphrase. After entering your passphrase and checking all the recommendations on (**5**)  you will be prompted to secure the wallet with a password, tap **NO** then tap **I'M SURE**.

**Now you have the wallet created.**




Please let us know if you have any additional questions.
Kind regards.

**Comment by squareoff1212** [comment]
Ok I’ve done everything and a wallet was created but my money still didn’t appear

**Comment by BGalliotti** [comment]
Hello @squareoff1212 
Thanks for reaching out to us.

If you have created a brand new wallet, that wallet has nothing to do with the previous one and you will see the funds there.

Also, the address 13Hd1ZSzUieDkuAKc9HE12qc4MhoPpdM does not belong to a Copay/Bitpay wallet.

Basically, funds are sent to an address which may belong to a wallet.
If you own that wallet you will see the funds in it, if not there is no way to recover the funds.

In addition, a transaction cannot be reversed so in case the funds were sent to a wrong address, nothing can be done.

Please let us know if you have any additional questions.
Kind regards.

**Comment by squareoff1212** [comment]
Yes that address does belong to a copay wallet that’s the address my copay gave me when I scanned the QR Code I have receipt right here still I called cottonwood vending and they said it’s not their end all the confirmations was there to call the receiving wallet which is copay

**Comment by squareoff1212** [comment]
Is there a way I can upload pictures to actually show you what I’m talking about because I just sent 400$ a hour ago and when I checked the un used addresses the address I just used to send $400 to with QR code comes up as un used addresses on my copay app how is that possible

**Comment by BGalliotti** [comment]
Hello @squareoff1212 
Thanks for reaching out to us.

> Yes that address does belong to a copay wallet that’s the address my copay gave me when I scanned the QR Code I have receipt right here still I called cottonwood vending and they said it’s not their end all the confirmations was there to call the receiving wallet which is copay

As previously stated, the address 13Hd1ZSzUieDkuAKc9HE12qc4MhoPpdM does not belong to any Copay/Bitpay wallet.

> Is there a way I can upload pictures to actually show you what I’m talking about because I just sent 400$ a hour ago and when I checked the un used addresses the address I just used to send $400 to with QR code comes up as un used addresses on my copay app how is that possible

Yes. Please answer to this response from the Github website. There you can paste images on the text field or by dragging and dropping them. This is explained on the bottom of the text field where you write your answer.

Please let us know if you have any additional questions.
Kind regards.
