### ISSUE TITLE
Can't override 2 sat/B "suggested" fees

### ISSUE THREAD

**Issue by ernestasromeika** [bitpay/copay#9025]
Tried to do a payment via bitpay (from copay wallet), needed this tx done pretty quickly, the in app fees calculated to a 2.8 sat/B where as I've set my fee settings to be at 30 sat/B. There's no apparent way to change the "suggested" fee, so did the transaction anyway, now waiting for several hours. Not sure if this is a bug, but if it's not there should definitely be a way to reject the "suggested by merchant" fee and default back to your own.

**Comment by arensirb** [comment]
This here annoys me too.. The merchant has suggested an INCREDIBLY low fee.. Why can't we override it? 

I  don't want to wait 10-15-20 hours for payment to go through.
I transferred btc from Kraken to you, and that was 12.105 sat/B
I did a purchase on another website and it used  4.664 sat/B

It's gonna take forever! Please allow us to override. It even says SUGGESTED.. Suggested means CAN CHANGE.
Why does it not say "Merchant has set a fixed fee" ... ?

**Comment by arensirb** [comment]
Hi again @BGalliotti..

Actually it will, because the other transaction was done LONG before the one I paid with your app.. 
It took so long my order was actually cancelled and I had to contact them to fix it.. 

Why do you claim that increasing the fee will not accelerate? That's not true and you know it. 

With a higher fee it would have been completed A LOT sooner.

**Comment by BGalliotti** [comment]
Hello 
Thanks for reaching out to us.

I Will remove your last comment and answer your last question on my previous comment.

Please let us know if you have any additional questions.
Kind regards.

**Comment by ernestasromeika** [comment]
I don't see why @BGalliotti 's comments were removed, his concerns were on point. Copay's wallet enforces unreasonable suggested fees when paying for bitpay powered merchants. There's no such thing as a suggested fee in bitcoin protocol, it's just a classic case of stuffing down proprietary garbage that no one needs or asks for. I've moved to a different wallet since I've opened this ticket and couldn't be happier.

**Comment by arensirb** [comment]
@ernestasromeika It was my comment that was removed, not @BGalliotti 's.. He/She is the moderator that did not like my replies. Fact is that transaction fee DOES have something to do with how fast a transaction goes through.

Unreasonably low? yes.. I want them higher.
Which wallet did you move to?

**Comment by ernestasromeika** [comment]
Yes sorry, selected the wrong name handle, I meant it about your comments. I've moved to Samourai wallet which gives me full control over fees and even allows me to append some fees if the transaction is going slow (by using flag RBF flags and CPFP transactions).

**Comment by arensirb** [comment]
@ernestasromeika That doesn't even support bitpay invoices.. So, can't use it .-/
