### ISSUE TITLE
Transaction has the status “Sending” for a long time

### ISSUE THREAD

**Issue by owaewa** [bitpay/copay#9026]
Transaction ID 
13210fae559f8cbceda31c37a2490814a19d22176a9a5d675b2a97d4948eca58

**Comment by BGalliotti** [comment]
Hello @owaewa 
Thanks for reaching out to us.
 We could not find any transaction with that ID, please send us the link.
Is it a BCH or BTC transaction?
If not, you will not see it on your wallet.

In the meantime

**Please open up your BitPay app and try the following steps:**

- Settings > Wallet > More Options > Transaction History > Clear cache
- Settings > Wallet > More Options > Wallet Addresses > Scan addresses for funds


Please let us know if you have any additional questions.
Kind regards.

**Comment by BGalliotti** [comment]
Hello @owaewa 

**We have not heard of you in while!**

**Are you still experiencing an issue?**

We are going to close this thread, please if you need further help, open a new one explaining the issue in detail, providing all the relevant information possible, we will be happy to help you :)

Kind regards.
