### ISSUE TITLE
Never got my money

### ISSUE THREAD

**Issue by aubreyg09** [bitpay/copay#9027]
I sent myself $120 from coinbase to my copay to transfer to my lqdfx account. Transaction ID f22279bf3e0709a10f5d1abed0dfc94cf3f08de96e39f8039a40749c79d6ba02. Wallet id  1CuoCNiajiZreH1TC8VGKBjGSGuMpK13Y7  but the money is not there even though it says confirmed. When will it be there?

**Comment by BGalliotti** [comment]
Hello @aubreyg09 
Thanks for reaching out to us.

We found the transaction in a bitpay wallet. 
You have to be looking in the wrong wallet.

Please send us your wallet ID to check it out.
we look forward to hearing from you.
Kind regards.

**Comment by BGalliotti** [comment]
Hello @aubreyg09 

**We have not heard of you in while!**

**Are you still experiencing an issue?**

We are going to close this thread, please if you need further help, open a new one explaining the issue in detail, providing all the relevant information possible, we will be happy to help you :)

Kind regards.
