### ISSUE TITLE
Insufficient funds / Consolidate funds / Sendmax / send max

### ISSUE THREAD

**Issue by osquare96** [bitpay/copay#9035]
I’ve been trying to deposit money into my trading account for ever. Since many brokers took away the easier method for depositing which is debit credit. Finally got to learn the bitcoin method and now when I send my receiving address from LQDFX to COPAY, and put the amount on copay, it keeps saying “insufficient funds” ... why! Help.

**Comment by BGalliotti** [comment]
Hello @osquare96 

Thank you for reaching out to us.

**So we can further help, please provide as many of the following details as you can:**

- Current device used: Phone model 
- Current operating system version for the device: iOS, Android..
- Current version of the wallet used: Bitpay App > Settings > About bitpay 
- Any log files containing error details: Bitpay App > Settings > About bitpay > Session Log > Tap on the Upper right corner (three dots) > Send by email (you can screenshot the content as well and attach the images to your e-mail. In such case, please make sure you move the slider to the **"Debug"** position).
- Error screenshot: On [iPhone](https://apple.co/1DAB204) on [Android](https://www.wikihow.tech/Take-Screenshots-on-an-Android)
- Steps to replicate: Steps needed for the error to appear.
- **BitPay Wallet ID** - To get your Wallet ID, open your BitPay application, then go to `Settings` > [Your wallet] > `More Options` > `Wallet Information`. On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste in your e-mail.

**We look forward to hearing from you.**



Please let us know if you have any additional questions.
Kind regards.

**Comment by osquare96** [comment]
I use Copay not bitpay. I use iPhone 7 Plus iOS.. and this keeps happening

**Comment by BGalliotti** [comment]
Hello @osquare96 
Thanks for reaching out to us.

Do you have enough funds for the transaction?

Please send us the wallet ID so we can verify that.
Kind regards.

**Comment by osquare96** [comment]
I want to know what the fee is for copay?
Where can I find my wallet ID

**Comment by BGalliotti** [comment]
Hello @osquare96 
Thanks for reaching out to us.

> Where can I find my wallet ID

This was explained previously. 
- CoPay Wallet ID - To get your Wallet ID, open your CoPay application, then go to `Settings` > [Your wallet] > `More Options` > `Wallet Information`. On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste in your e-mail.

> I want to know what the fee is for copay?

Check this posts:
#5164 (comment)
#4803 (comment)


Thank you for reaching out to us.
Please let us know if you have any additional questions.
Kind regards.

**Comment by osquare96** [comment]
I think you guys actually explained this with bitpay not copay, so I didn’t
know the instructions were the same. And again, what’s the fee for copay?

My wallet ID: 3cc2bb32-ffbf-4e35-9cb2-2371f780d7d3

**Comment by BGalliotti** [comment]
Hello @osquare96 
Thanks for reaching out to us.

> I think you guys actually explained this with bitpay not copay, so I didn’t know the instructions were the same.

**We apologize for that. Yes the instructions are the same.**

This is your balance:

`
* Balance
  Total: 0.00481047 btc (0.00000000 btc locked)
  Confirmed: 0.00481047 btc (0.00000000 btc locked)
  Available: 0.00481047 btc (0.00481047 btc confirmed / 0.00000000 btc unconfirmed)
` 
The amount you want to send plus the fees, cannot exceed your balance.

> And again, what’s the fee for copay?

Check this posts:
#5164 (comment)
#4803 (comment)

It is explained in a detailed way on the comments.
**This was also answered in the previous post.**

Please let us know if you have any additional questions.
Kind regards.

**Comment by osquare96** [comment]
Okay.. I’m trying to understand, my final question is, how come when I try
to send money to my broker with copay it says insufficient funds?

**Comment by osquare96** [comment]
Ill try this and let you know if it works. Thanks

**Comment by BGalliotti** [comment]
Hello @osquare96 

**We have not heard of you in while!**

**Are you still experiencing an issue?**

We are going to close this thread, please if you need further help, open a new one explaining the issue in detail, providing all the relevant information possible, we will be happy to help you :)

Kind regards.
