### ISSUE TITLE
npm ERR! secp256k1@1.1.5 install: `node-gyp rebuild` npm ERR! Exit status 1

### ISSUE THREAD

**Issue by JerryBaojin** [bitpay/copay#9037]
when i run _npm install_，it appears to show **npm ERR! secp256k1@1.1.5 install: `node-gyp rebuild` npm ERR! Exit status 1**

**Comment by ycarogabriel** [comment]
did you solved?

**Comment by JerryBaojin** [comment]
nope

**Comment by Bassist067** [comment]
I'm trying to run this on windows at VS Code. The problem disappeared when I ran this as admin.

**Comment by ReeseWang** [comment]
Still no fix? I ran into this too. Perhaps secp256k1@1.1.5 released in 2015 is too old?

**Comment by JDJBSPL** [comment]
@JerryBaojin I am getting same error, How you able to npm install successfully?
