### ISSUE TITLE
Funds not showing up

### ISSUE THREAD

**Issue by tedzz11** [bitpay/copay#9039]
I had received some amount in my Copay Wallet, i firstly used PC version for the same, at that time it appeared towards the same. Later after 1 hour, i open the same it does not show up, in any forms of devices, pc/mobile versions. Please help me with the stated issue, as soon as possible.

Regards,

**Comment by BGalliotti** [comment]
Hello @tedzz11 

Thank you for reaching out to us.

**Please open up your BitPay app and try the following steps:**

- Settings > Wallet > More Options > Transaction History > Clear cache
- Settings > Wallet > More Options > Wallet Addresses > Scan addresses for funds

**In the meantime, So we can further help, please provide as many of the following details as you can:**

- Current device used: Phone model 
- Current operating system version for the device: iOS, Android..
- Current version of the wallet used: Bitpay App > Settings > About bitpay 
- Any log files containing error details: Bitpay App > Settings > About bitpay > Session Log > Tap on the Upper right corner (three dots) > Send by email (you can screenshot the content as well and attach the images to your e-mail. In such case, please make sure you move the slider to the **"Debug"** position).
- Error screenshot: On [iPhone](https://apple.co/1DAB204) on [Android](https://www.wikihow.tech/Take-Screenshots-on-an-Android)
- Steps to replicate: Steps needed for the error to appear.
- BitPay Wallet ID - To get your Wallet ID, open your BitPay application, then go to `Settings` > [Your wallet] > `More Options` > `Wallet Information`. On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste in your e-mail.

**We look forward to hearing from you.**

**Comment by corn91791** [comment]
I don’t have an android phone

**Comment by sirnicolas21** [comment]
hi,
i do have same problem but on testnet
i tried clear cache and scan but nothing happen

Device = oneplus 3t
android 8.0.0
copay 4.6.3 #391d02
wallet id = 0506a12e-c54d-4ab1-b98e-d0b42cf6cbeb

**Comment by BGalliotti** [comment]
Hello @sirnicolas21 
Thanks for reaching out to us.

According to us, your last transaction dates from September 27. 

Here are your transactions:

``
[Thu Sep 27 2018 19:03:43 GMT-0300] c718f90010d1464ca2dd2bab2bc3c225dce3286193505462ab1378a79bc695f7 <= received 0.05990972 btc (fee/kb 0.00001102 btc) (582 confirmations)
  [Thu Sep 27 2018 19:03:43 GMT-0300] b740d5f0ffce44b978544c4ffd43115d17edbd7f6e53626f6108456fd38fd6c0 <= received 0.02799450 btc (fee/kb 0.00001102 btc) (582 confirmations)
  [Thu Sep 27 2018 18:43:42 GMT-0300] c57b0c9c912dce0983435a12750df4fd118eb47147f186ccbcb1a8f239cf13ab <= received 0.12069817 btc (fee/kb 0.00001108 btc) (583 confirmations)
  [Thu Sep 27 2018 17:03:05 GMT-0300] af6396538dabd174e7015599dd36e93a9ad0f29aa747a6d11e69d4da7c282c17 <= received 6.05099449 btc (fee/kb 0.00001107 btc) (588 confirmations)
  [Thu Sep 27 2018 16:42:58 GMT-0300] 4004630fe10a4b5a67e7f0feda887e9af3d174a51d0b7af5ff5a604c82789562 <= received 0.02799450 btc (fee/kb 0.00001107 btc) (589 confirmations)
``

Please let us know if you have any additional questions.
Kind regards.

**Comment by sirnicolas21** [comment]
well yes... the balance is updated... i see that now after 8 days, but it wasn't updated on 29th of September... maybe there is a delay on your service that's why the initial user that created the ticket here didn't reply further.

**Comment by BGalliotti** [comment]
Hello @sirnicolas21 ,

Sometimes the transactions take longer than expected to be confirmed, you can read about this [here](https://github.com/bitpay/copay/issues/8803#issuecomment-398775441).

Also in some cases, it could take a while for the transaction to show up on the wallet.

If you can see a transaction on the blockchain and the same is not showing up on the wallet, you can refresh the wallet cache:

**Please open up your BitPay app and try the following steps:**

- Wallet > Preferences (top right corner icon) > Transaction History > Clear cache
- Wallet > Preferences (top right corner icon) > Wallet Addresses > Scan addresses for funds

Please let us know if you have any additional questions.
Kind regards.

**Comment by sirnicolas21** [comment]
that's not the case, maybe your transaction parser is slow.... i do happen to be a blockchain developer and i had more than 10 confirmations when i  wrote here.

**Comment by BGalliotti** [comment]
Hello @sirnicolas21 
Thanks for the heads up.

Our development team is going to investigate.

Kind regards.

**Comment by sirnicolas21** [comment]
i shall remark that the task is in "closed" state.
