### ISSUE TITLE
Je n'ai pas reçu mes BTC

### ISSUE THREAD

**Issue by CtroisPO** [bitpay/copay#9052]
Bonjour j'ai envoyé des BTC a mon adresse de portefeuille le 22 aout et je lai toujours rien dessus alors que le transfert a été effectué

**Comment by BGalliotti** [comment]
Hello @CtroisPO 
Thanks for reaching out to us.

Please send us the transaction ID and your wallet ID so we can verify what happened.

- CoPay Wallet ID - To get your Wallet ID, open your CoPay application, then go to `Settings` > [Your wallet] > `More Options` > `Wallet Information`. On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste in your e-mail.

**We look forward to hearing from you.**
Kind regards.

**Comment by CtroisPO** [comment]
a967e7d1-7a1e-48f7-9884-8414af2a57b6


________________________________

**Comment by CtroisPO** [comment]
a967e7d1-7a1e-48f7-9884-8414af2a57b6

**Comment by BGalliotti** [comment]
Hello @CtroisPO 
Thanks for reaching out to us.

There are no transactions in this wallet please send us the transaction ID/Link

Kind regards.

**Comment by CtroisPO** [comment]
No i dont have anoter wallet

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by BGalliotti** [comment]
Hello @CtroisPO 
Thanks for reaching out to us.

Well, the transaction is not yet confirmed. 
Anyways, if some funds have gone into your wallet, it should the transaction with 0 confirmations, and that is not happening.
You should check to what address have they sent you the funds, and send us the address so we can check if it belongs to your wallet. 

Think how did you get the address where you wanted to receive the funds.

Please let us know if you have any additional questions.
Kind regards.

**Comment by CtroisPO** [comment]
I have recive thanks

**Comment by BGalliotti** [comment]
Hello @CtroisPO 
Thanks for your update
Kind regards.
