### ISSUE TITLE
Never received funds sent to lqdfx

### ISSUE THREAD

**Issue by usmartfx** [bitpay/copay#9055]
I sent $250 to my lqdfx account and and have not received anything yet it's been over 2 days

**Comment by BGalliotti** [comment]
Hello @usmartfx 
Thanks for reaching out to us.

You have sent those funds with the Copay/Bitpay wallet, right?

In such case, is the transaction confirmed? If it was confirmed, everything is fine on our end.
If not, please send us the wallet ID and transaction ID.

Please let us know if you have any additional questions.
Kind regards.

**Comment by usmartfx** [comment]
yes this was from copay to lqdfx
Wallet ID is b12d90e8-4817-4ac0-8b2f-914ba

**Comment by usmartfx** [comment]
Transaction ID is 
380d480c1b204d4d7b92da728869538066316688e332f9cd302d6370657a2b2a

**Comment by BGalliotti** [comment]
Hello @usmartfx 
Thanks for reaching out to us.

The transaction is confirmed: https://live.blockcypher.com/btc/tx/380d480c1b204d4d7b92da728869538066316688e332f9cd302d6370657a2b2a/

And it is shown in the wallet.

There is nothing wrong on Bitpay's side. 

Please reach the technical support of the destination wallet/entity and ask them about your problem.
Kind regards.

**Comment by Jarvisscar** [comment]
Hello I’m having the same issue as well
