### ISSUE TITLE
Sent funds from copay to lqdfx but never went through

### ISSUE THREAD

**Issue by gusinvegas** [bitpay/copay#9060]
Good afternoon, I've sent funds from Copay to LQDfx and on 8/22 and it still has not deposited into LQDfx.

Transaction ID:
dd107b89bd2b8bd348224d32bdb354f06655768ea7861394d5747657f4a410f2

Please help?

**Comment by BGalliotti** [comment]
Hello @gusinvegas 
Thanks for reaching out to us.

The transaction has properly gone through, you can check it here:
https://live.blockcypher.com/btc/tx/dd107b89bd2b8bd348224d32bdb354f06655768ea7861394d5747657f4a410f2/
Are you sure you sent the funds to the correct address?


Please let us know if you have any additional questions.
Kind regards.

**Comment by daviduzoma** [comment]
The same has happened to my deposit on 10/08. Wallet i:7dcebe52-1426-416f-8ee0-f01e963b6239 I believe the address was 1DVZogaMrWhopVhZy9MqwYHrjjKYnxMUzC.  This was a transaction for 35$

**Comment by daviduzoma** [comment]
So what do u red from me in order to find it. It has been 3 days and I
strongly feel i a being cheated out of my hard earned money

**Comment by BGalliotti** [comment]
Hello @daviduzoma 
Thanks for reaching out to us.

>So what do u red from me in order to find it.
Unfortunately, nothing. 

As already stated, the operation is not traceable neither reversible.

Best regards.
