### ISSUE TITLE
Import BIP44 seed / Import 3rd party wallet

### ISSUE THREAD

**Issue by alexgerdov** [bitpay/copay#9063]
Hello,

Is there a way to import the seed of BIP44 wallet that was generated in another wallet software? 

Example seed (in hex string):
4f2129d6389d2e31a45e3956b15a9e23ce544129798faae0639a4636429cb9fc

the derivation scheme is a standard BIP44:
m/44'/1'/0'

I tried to use https://iancoleman.io/bip39/ to generate the recovery phrase and it did not work.

Thanks.

**Comment by BGalliotti** [comment]
Hello @alexgerdov 
Thanks for reaching out to us.

Yes, it is possible to import the wallet. 
The easiest way is by entering the words. 

**If you do not have any wallet or your wallet was not created with the Bitpay/Copay** (for example, you created the wallet with Samourai Wallet and now you want to use that wallet in Bitpay/Copay. )

- Tap on **Create a new wallet** on the top of the app
- Tap **Create personal wallet**
- Enter a wallet name, select **BTC** as coin (the coin of your choice)
- Tap on the **Show advanced options** dropdown  
- Tap on the **Wallet key** dropdown (it is set to **Random** by default) and select **Specify Recovery Phrase**
- Tap on **Wallet recovery phrase** and then **OK** > enter your passphrase. After entering your passphrase and checking all the recommendations on (**5**)  you will be prompted to secure the wallet with a password, tap **NO** then tap **I'M SURE**.

**Now you have the wallet created.**

Then:

- Settings > Wallet > More Options > Transaction History > Clear cache
- Settings > Wallet > More Options > Wallet Addresses > Scan addresses for funds

**If you want to use the string**, the way to do this is by using the string, open a wallet, go to send and paste the string in the send field.

If you do not have a wallet in Copay, you can create one:**To create a wallet:**

- Open your Bitpay/Copay app > Tap on the **+** sign on Bitcoin Wallets > Create Personal Wallet >  Enter a wallet name, select BTC as coin > Tap Create Wallet.
- When you are asked to protect your wallet with a password, tap "yes" enter your password, and write it down on a piece of paper.
- Now your wallet says "Needs backup". Follow this video to back up your wallet: https://bit.ly/2Jz1cFZ
- **Remember to write down your password and 12-word passphrase on a piece of paper and store it in a safe place. The 12-word phrase is the *only* way to recover your wallet, *this step is extremely important*.**




Please let us know if you have any additional questions.
Kind regards.
