### ISSUE TITLE
erro 403 ,nao recebi meus btc na carteira copay

### ISSUE THREAD

**Issue by Josianefga** [bitpay/copay#9064]
esta dando este erro na carteira e nao consigo atualiza ,
meus btc nao chegaram e ja foram altenticados 
link .Veja por outro site: https://live.blockcypher.com/btc/tx/06a7f58df60f048cdaf20f426fc966e96cb595a8fa62599ecf7d244d7160d30c/
endereço..   13oCQ8Sdz4R6DNBwKkdaqR3adpeQNyMsEX ( carteira copay ,app ,android)
Payment Received New payment received
A payment of 0.264559 BTC has been received into your wallet.

See it on the Blockchain

**Comment by BGalliotti** [comment]
Hello @Josianefga 
Thanks for reaching out to us.

**Please open up your BitPay app and try the following steps:**

- Settings > Wallet > More Options > Transaction History > Clear cache
- Settings > Wallet > More Options > Wallet Addresses > Scan addresses for funds

Also please make sure, the wallet you are using is the wallet where you expecting the funds to be.


Please let us know if you have any additional questions.
Kind regards.
