### ISSUE TITLE
Need padding

### ISSUE THREAD

**Issue by Kirvx** [bitpay/copay#9066]
**The new design is great** :+1: 

![screenshot_2018-08-28-11-46-38-325_com bitpay wallet](https://user-images.githubusercontent.com/6627786/44716690-5a932880-aabb-11e8-925e-bc741dd5dc07.png)

**Comment by BGalliotti** [comment]
Hello @Kirvx 

Thanks for your feedback, our developers are being noticed about your contribution.


Please let us know if you have any additional questions.
Kind regards.

**Comment by Gamboster** [comment]
Thanks @Kirvx for report it. I just sent a PR fixing this and other things related long strings and different languages.

https://github.com/bitpay/copay/pull/9072

**Comment by Gamboster** [comment]
The PR was merged, I'm going to close this issue. You will see the changes in the next release.
Regards
