### ISSUE TITLE
Amazon gift card purchase issue

### ISSUE THREAD

**Issue by CellarDoor00** [bitpay/copay#9087]
Hi,

I tried to buy an amazon gift card today from my Copay wallet with BCH and the process timed out while broadcasting the transaction. I got a message to try later.

However, I later saw that the funds were sent to your address during that time. But, I never received the gift card.

Transaction id: 
8280a2feeb428a438d864df11d8e1539c04210f7b2f488da8ccc9b75b5173ccd

Address funds were sent to:
qpjhm2328su83hr6p7gzut0ka7e40qqaks6ll9pgpv

Amount: 0.845418 BCH ($525 amazon gift card).

Time: 1:09 PM EST 9/1/2018

Please send the gift card or refund the BCH to qz6gez8z5zfsmh3grfdyv9aujcss4qj99s9dpwyfyg

Thanks!

Mike

**Comment by corn91791** [comment]
No do not send it to that address cause this person who’s ever trying to
collect my money is not the person so stop letting these people check you

**Comment by BGalliotti** [comment]
Hello @CellarDoor00 
Thanks for reaching out to us.

Please write to the Bitpay support: https://help.bitpay.com/requestHelp
Our representatives are going to address your inquiry there.

We would appreciate your patience.

Thanks in advance, Kind regards.
