### ISSUE TITLE
The testnet Bitcore Wallet Service of Copay are not working

### ISSUE THREAD

**Issue by the9ull** [bitpay/copay#9088]
Hello,
the service are not working for some time.
Where I should report this type of problems?

Thank you

**Comment by BGalliotti** [comment]
Hello @the9ull 
Thanks for reaching out to us.

We are sorry you have had this bad experience and apologize for the inconveniences it might have caused you.

This is the right place, thanks for reporting this issue.

We are aware of this problem and we are looking for a solution.
We will let you know as soon as we figure this out.

We would appreciate your patience.

Please let us know if you have any additional questions.
Kind regards.
