### ISSUE TITLE
Copay Missing Budget

### ISSUE THREAD

**Issue by kumsal2** [bitpay/copay#9091]
Hello I opened my copay account on august 12. After that from nicehash I sent my money to my copay account. When I restore my account on Mobile phone or Windows I cant see my budget.It seems no any money. Can you help for this issues?

**Comment by BGalliotti** [comment]
Hello @kumsal2 

Thank you for reaching out to us.

**So we can further help, please provide as many of the following details as you can:**

- Current device used: Phone model 
- Current operating system version for the device: iOS, Android..
- Current version of the wallet used: CoPay App > Settings > About CoPay 
- Any log files containing error details: CoPay App > Settings > About CoPay > Session Log > Tap on the Upper right corner (three dots) > Send by email (you can screenshot the content as well and attach the images to your e-mail. In such case, please make sure you move the slider to the **"Debug"** position).
- Error screenshot: On [iPhone](https://apple.co/1DAB204) on [Android](https://www.wikihow.tech/Take-Screenshots-on-an-Android)
- Steps to replicate: Steps needed for the error to appear.
- CoPay Wallet ID - To get your Wallet ID, open your CoPay application, then go to `Settings` > [Your wallet] > `More Options` > `Wallet Information`. On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste in your e-mail.

**We look forward to hearing from you.**
