### ISSUE TITLE
I didnt get the money I Sent to Copay

### ISSUE THREAD

**Issue by facundofacundo777** [bitpay/copay#9093]
Hi there,
I bought some bitcoins and sent the money to Copay but i didn't received it!

Thanks for your help!

**Comment by BGalliotti** [comment]
Hello @facundofacundo777 
Thanks for reaching out to us.



Please let us know if you have any additional questions.
Kind regards.

**Comment by facundofacundo777** [comment]
Hi there,

I just got the money on my wallet!

Thanks for your reply

**Comment by BGalliotti** [comment]
Hello 

**We are glad you were able to solve the issue!**

Please bear in mind some transactions can take a while to be confirmed.
In case you experience the same in the future, please check the transaction on the blockchain.

If it was confirmed (6+ confirmations) and not showing up in your wallet, 
**Please open up your BitPay app and try the following steps:**

- Settings > Wallet > More Options > Transaction History > Clear cache
- Settings > Wallet > More Options > Wallet Addresses > Scan addresses for funds

Feel free to get back to us in case you have any questions or concerns.

**Thank you for your interest and support.**
