### ISSUE TITLE
unconfirmed transaction

### ISSUE THREAD

**Issue by vladdyaj** [bitpay/copay#9099]
sent bitcoin from copay to huobi through the mobile app.  showing as 'unconfirmed' checked a block explorer and it is there - how long does it typically take to confirm ? or is there a way to expedite the confirmation?  cancel? resend?  thx in advance

**Comment by BGalliotti** [comment]
Hello @vladdyaj 
Thanks for reaching out to us.

Please refer to #8712, there is detailed explanation on transaction, fees, approval time and related topics.

Once a transaction has been broadcast, there is no way to cancel it.

Please let us know if you have any additional questions.
Kind regards.
