### ISSUE TITLE
address change

### ISSUE THREAD

**Issue by horicoh** [bitpay/copay#9101]
I tried to transfer fund to my personal wallet but the address has changed.... Will I still receive my funds ??

**Comment by BGalliotti** [comment]
Hello @horicoh 
Thanks for reaching out to us.

Your bitcoin wallet has the ability to generate infinite addresses.

As soon as the address belongs to your wallet, You should not have any problems. Here is an explanation about the addresses changing.

To protect your privacy, the BitPay wallet generates new addresses automatically once you use a bitcoin address once.

All bitcoin transactions are public, traceable, and permanently stored in the Bitcoin network. For these reasons, bitcoin addresses should only be used once and users must be careful not to disclose their addresses. When addresses are re-used, they allow others to much more easily and reliably determine that the address being reused is yours. 

Please let us know if you have any additional questions.
Kind regards.

**Comment by horicoh** [comment]
Yeah after the first transaction ,it changed but till now the other funds didn't arrive in my wallet after the address changed..... I sent the coin but it never arrived in my wallet....i

**Comment by BGalliotti** [comment]
Hello @horicoh 

Thanks for reaching out to us.

We are sorry you have had this bad experience.

- **Please send us the BitPay/Copay Wallet ID and the transaction hash / ID or the link so we can further investigate and address your inquiry.**

- To get your Wallet ID, open your Copay/BitPay application, then go to `Settings` > [Your wallet] > `More Options` > `Wallet Information`. 
On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste it in your e-mail. 
You can do the same on your computer by clicking on the wallet ID.

- The transaction hash / ID is a alphanumeric chain like this: **d0a23876de7cf87574b5cda7557bcc8af5d84f3fd1e6f4c6063fd6b72b0e69ae**

**We look forward to hearing from you.**

**Comment by horicoh** [comment]
4a440417-6ee5-471f-bcf6-cb7a473a7c1f that is the wallet ID.....I bought the coin from a third party I can't get the trasanction hash*sobs

**Comment by BGalliotti** [comment]
Hello @horicoh 
Thanks for reaching out to us.

These are the transactions related to your wallet:

`* Tx history
  [Wed Sep 05 2018 20:14:12 GMT-0300] 34f1e9f153c430aff1cb1872947d31409a04299567b4812513fc8b580a1fc3e1 => sent 0.56605278 btc (fee/kb 0.00028897 btc) (703 confirmations)
  [Wed Sep 05 2018 19:36:44 GMT-0300] 54f60631fdbfed71ed8255b3c6a8425c51aae07cc5871a4e64b617f21faf8226 <= received 0.56659891 btc (fee/kb 0.00039000 btc) (706 confirmations)
  [Sun Aug 26 2018 12:40:38 GMT-0300] 6212f8b5cb6671ab86e7434dfe894733918667ad2a8b836f5e8845fd3cf68149 => sent 0.31889611 btc (fee/kb 0.00064157 btc) (2233 confirmations)
  [Thu Aug 16 2018 04:27:48 GMT-0300] 0d308079d76ad2c82857a5a5fd13e5a824b0831294e8ad0af04747b2a14463a2 <= received 0.08040499 btc (fee/kb 0.00003504 btc) (3802 confirmations)
  [Wed Aug 08 2018 12:48:33 GMT-0300] 487df08f20df53f05847b374aabb516fa8fb592d05192ee876287413ad4714fe <= received 0.08912670 btc (fee/kb 0.00012680 btc) (5007 confirmations)
  [Sat Aug 04 2018 22:21:05 GMT-0300] bb51980d53934053ff4ec61bdd33a23f22e17e301ebceb34e4c9b3e520d79d36 <= received 0.08798229 btc (fee/kb 0.00003801 btc) (5542 confirmations)
  [Wed Aug 01 2018 22:51:32 GMT-0300] 70c4805f59784b08390aba125d073bca35736939403aaddc46bc1ca0dd45a4b7 => sent 0.01305000 btc (fee/kb 0.00065022 btc) (6034 confirmations)
  [Sun Jul 29 2018 01:25:56 GMT-0300] aec4c15d4f82758ce7350eb3b1edc90325fc13b43c7e0826b1ef5e2675577321 <= received 0.01216890 btc (fee/kb 0.00002843 btc) (6605 confirmations)
  [Thu Jul 26 2018 22:50:57 GMT-0300] 0f8e068b3a53cecf087bc916c563320518274c10d9f4510cd26a4c3199aa648b <= received 0.02535912 btc (fee/kb 0.00005424 btc) (6950 confirmations)
  [Wed Jul 25 2018 15:14:01 GMT-0300] 325205babccca22d45d389a753e8d11746bc1121edf7e186dbd51eac3655c50a <= received 0.03704911 btc (fee/kb 0.00016666 btc) (7166 confirmations)
`
In case you do not see the same transactions in your wallet, 
**Please open up your Copay/BitPay app and try the following steps:**

- Settings > Wallet > More Options > Transaction History > Clear cache
- Settings > Wallet > More Options > Wallet Addresses > Scan addresses for funds

If none of those transactions is the one you are talking about, please:

- Verify the transaction, if it is confirmed, the funds should have reached the other end.
- Make sure the "other end" is your Copay/Bitpay wallet.

Please let us know if you have any additional questions.
Kind regards.
