### ISSUE TITLE
bitcoins send but never received in wallet

### ISSUE THREAD

**Issue by carlosrinc** [bitpay/copay#9109]
Hi,

I have a problem. I send btc to a Wallet copay, but the money was never received.

Here is the information:

Copay Wallet ID
e005cf04-bb5c-40a6-b373-47d7fae394eb
the transaction hash / ID
bf8e2312eb54e634c8ee50f68af146463f81e4735a29e1a18c4531d96d89deae

Thanks for help.

**Comment by carlosrinc** [comment]
Thanks alot!!!

The transaction was received about 2 hours ago.  Regards.

**Comment by BGalliotti** [comment]
Hello @carlosrinc 
Thanks for reaching out to us.

We are glad you were able to solve the issue!

Kind regards.
