### ISSUE TITLE
Send btc but not received after 5 hours

### ISSUE THREAD

**Issue by mtlam1** [bitpay/copay#9110]
I used copay to send btc, but coin never received after 5 hours.  Please help.

The transaction id is:  7cec0932e664a2552889cfc38696b4c68cf68a0a968f090dfb68062d9f90cee6

I looked up on insight, this id doesnt exist.

My copay wallet id is: f4a9165b-1c03-4adc-a050-3bbe325b3edb

**Comment by BGalliotti** [comment]
Hello @mtlam1 
Thanks for reaching out to us.

The transaction **7cec0932e664a2552889cfc38696b4c68cf68a0a968f090dfb68062d9f90cee6**
https://live.blockcypher.com/btc/tx/7cec0932e664a2552889cfc38696b4c68cf68a0a968f090dfb68062d9f90cee6/

has not been confirmed yet, please wait until it is confirmed by the network.

To know why some transactions take a while to be confirmed,  please refer to #8712

**Please open up your BitPay app and try the following steps:**

- Settings > Wallet > More Options > Transaction History > Clear cache
- Settings > Wallet > More Options > Wallet Addresses > Scan addresses for funds

Please let us know if you have any additional questions.
Kind regards.
