### ISSUE TITLE
CoPay missing from Google Play

### ISSUE THREAD

**Issue by hsjoberg** [bitpay/copay#9111]
CoPay and BitPay Wallet are missing from Google Play.

https://play.google.com/store/apps/details?id=com.bitpay.copay

https://play.google.com/store/apps/details?id=com.bitpay.wallet

**Comment by robvdbrand** [comment]
Yep, noticed the same and wondering what's going on.

**Comment by ad-m** [comment]
It's available for me right now. 

@hsjoberg , @robvdbrand , do you can verify again?

**Comment by robvdbrand** [comment]
yep, it's working

**Comment by hsjoberg** [comment]
Yes, it's available now again, thanks!

**Comment by akshaynexus** [comment]
same issues again, not available atm

**Comment by BGalliotti** [comment]
Hello @akshaynexus ,

Thank you for reaching out to us.

Please write to the BitPay Customer Success team: https://help.bitpay.com/requestHelp
Our representatives can address your inquiry there.

We would appreciate your patience.
Kind regards.
