### ISSUE TITLE
CONTRASEÑA INCORRECTA

### ISSUE THREAD

**Issue by kamiloarcila** [bitpay/copay#9115]
Buenas noches.  Estoy haciendo un envío y cuando voy a confirmarlo con mi contraseña. La que siempre he utilizado y me dice que es incorrecta. Cuál es el paso  a seguir. Ya que no me está dejando retirar los fondos. Es la contraseña de cifrado

**Comment by BGalliotti** [comment]
Hola @kamiloarcila,

Gracias por contactarnos.

Lo que esta planteando en principio no es posible. 

Hay dos opciones:
- Esta ingresando mal la contraseña
- Ha cambiado la contraseña

Si posee la frase de recuperación, puede eliminar la billetera y a continuación importarla.
Si no posee la frase de recuperación, no elimine la billetera y trate de recordar la contraseña, caso contrario perderá sus fondos.

Para saber como recuperar la billetera diríjase al post #8532 (en inglés) 

Si tiene alguna otra consulta no dude en escribirnos.

Saludos cordiales.

**Comment by jojesua** [comment]
No recuerdo la contraeña de cifrado apra entrar en bitpay. Pero antes de seguir con el proceso como puedo confirmar las semillas sean correctas?

**Comment by jojesua** [comment]
Lo que perdi fue la contraseña de entrada a bitpay wallet

**Comment by gabrielbazan7** [comment]
@jojesua Podes intentar importar la billetera en otro dispositivo para comprobar que tus palabras sean correctas. Si tenes más dudas por favor abri otro ticket
