### ISSUE TITLE
Amazon GiftCard payment failure

### ISSUE THREAD

**Issue by nexiapps** [bitpay/copay#9122]
I purchased an amazon card with my copay wallet and it says failure but it’s sending in my transaction I don’t understand why. Please respond to me fast

**Comment by BGalliotti** [comment]
Hello 
Thanks for reaching out to us.

Please write to the Bitpay support: https://help.bitpay.com/requestHelp
Our representatives are going to address your inquiry there.

We would appreciate your patience.

Thanks in advance, Kind regards.
