### ISSUE TITLE
Accidently sent USDT to copay

### ISSUE THREAD

**Issue by hemantizbest** [bitpay/copay#9132]
Dear team
I have accidentally sent 159 USDT to copay wallet on 17th September at 02:45 AM.
Please help to recover them. I will be highly thankful to you.

My copay wallet registered email I'd is hemantgandhi0128@gmail.com.

**Comment by BGalliotti** [comment]
Hello @hemantizbest 
Thanks for reaching out to us.

Unfortunately, we have no way to recover USDT, our wallet only supports BTC and BCH.


Please let us know if you have any additional questions.
Kind regards.

**Comment by hemantizbest** [comment]
I understand that copay only supports BTC & BCH. But I require your help.
All my USDT is stored in copay address which is
"1KtN6Dh7isQ1xjXtJtpcBnj7si6z9h6B78"

I have done that transaction by mistake. Please ask your technical team to
help me. I am regular user of copay.

I can provide you all the necessary details. Please help me sir. Just send
back those tokens back to the sender account. I will then coordinate with
them.

**Comment by hemantizbest** [comment]
Thanx for your reply team

Please let me know where to find 12-word recovery phrase.

Regards
Hemant Gandhi
On 19 Sep 2018 6:51 pm, "BGalliotti" <notifications@github.com> wrote:

Hello @hemantizbest <https://github.com/hemantizbest>
Thanks for reaching out to us.

If you have sent the funds to your Copay wallet, try the following:

   - Look for a wallet that supports USDT (google away, here
   <https://freewallet.org/currency/usdt> is one but we have no special
   recommendations and do not know if it's going to work).
   - Install the wallet app and import the Copay wallet using the 12-word
   recovery phrase
   - If the importing is successful, the wallet should scan for funds. If
   the wallet supports many coins, make sure to select USDT as one the wallets
   you want to use (typically this is done on the onboarding/initial setup
   wizard, if not, look on the settings).

*NOTE: this is a generic procedure, not specific instructions for a certain
wallet, this is pretty much how the process should be.*

We hope this is going to work. If you were successful, the community and
us, we will greatly appreciate if you share your experience.

Best regards.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bitpay/copay/issues/9132#issuecomment-422800766>, or mute
the thread

**Comment by BGalliotti** [comment]
Hello @hemantizbest 
Thanks for reaching out to us.

You are welcome.

You can find the 12-words backup phrase, here:
- Open the Copay/BitPay app
- Select the wallet 
- Tap the upper right corner icon
- Scroll down and tap **Backup**
- Continue that menu flow

Please let us know if you have any additional questions.
Kind regards.
