### ISSUE TITLE
I can't send money to LQDFX broker account or coinbase.

### ISSUE THREAD

**Issue by Joeafri** [bitpay/copay#9133]
No matter how much amount i try to send, it keep saying amount is insufficient. I really don't understand what's going on.. I even try to send the half of my amount and still says the same.. HELP!!

**Comment by BGalliotti** [comment]
Hello @Joeafri 
Thanks for reaching out to us.

Please refer to #9035 there is a comment explaining this question. 

Please let us know if you have any additional questions.
Kind regards.

**Comment by van2009181435** [comment]
gj

**Comment by van2009181435** [comment]
asdd
