### ISSUE TITLE
Carteira compartilhada

### ISSUE THREAD

**Issue by JOSEPINHEIROs** [bitpay/copay#9143]
Gostaria de saber se eu tenho uma carteira compartilhada 3/3 e 1 das pessoas pode retirar sozinho o BTC de lá?

**Comment by BGalliotti** [comment]
Hello @JOSEPINHEIROs 
Thanks for reaching out to us.

> 1 das pessoas pode retirar sozinho o BTC de lá?
**No.** 
A 3-3 wallet means it has 3 copayers and needs 3 signatures tu approve a transaction, then for every transaction 3 signatures will be needed.

For what you want to do ( a wallet shared by 3 people and only one signature needed), what you need is a 1-3 wallet, in that case you will need only one signature to approve a transaction.

Please let us know if you have any additional questions.
Kind regards.

**Comment by van2009181435** [comment]
vj

**Comment by vnbtc** [comment]
[bitcoincash:?r=https://bitpay.com/i/XvSty91xatikvrLBWFdxH8](url)
