### ISSUE TITLE
Netzwerkfehler (Network Error)

### ISSUE THREAD

**Issue by scout02** [bitpay/copay#9147]
Dear Support Team!

I can open my copay App and watching my old transactions, but my remainig Bitcoins are Not shown.

What can I do to have access to my Bitcoins?

Thank you for helping me,

Scout02

**Comment by BGalliotti** [comment]
Hello @scout02 
Thanks for reaching out to us.

**Please open up your BitPay app and try the following steps:**

- Wallet > Preferences (top right corner icon) > Transaction History > Clear cache
- Wallet > Preferences (top right corner icon) > Wallet Addresses > Scan addresses for funds

Please let us know if you have any additional questions.
Kind regards.

**Comment by BGalliotti** [comment]
To have a more in-depth explanation of what fees are and how they work, please check the following threads:

- #[5164](https://github.com/bitpay/copay/issues/5164#issuecomment-265569494)

- #4803
