### ISSUE TITLE
Problem Solved!

### ISSUE THREAD

**Issue by Method9312211** [bitpay/copay#9168]
I had missing money for like 20 minutes, but they got back. Sorry for posting its fixed now.

**Comment by BGalliotti** [comment]
Hello @Method9312211 

**We are glad you were able to solve the issue!**

We are going to close the ticket.

Regarding delays on payments/transactions, please refer to [8712](https://github.com/bitpay/copay/issues/8712#issuecomment-392816250)

Feel free to open a new one in case you have any questions or concerns.

**Thank you for your interest and support!**
