### ISSUE TITLE
testnet not found in advanced option

### ISSUE THREAD

**Issue by huahuayu** [bitpay/copay#9171]
as per the [official document said](https://test.bitpay.com/docs/testing) : 

> 3. Select "Advanced Options" and activate the "Testnet" option provided.

but I don't find the option in bitpay / copay

copay version: macOS v4.6.2   commit hash:3917d02
bitpay version: macOS v4.6.2   commit hash:3917d02

**Comment by BGalliotti** [comment]
Hello @huahuayu 
Thanks for reaching out to us.

If you want to create a testnet wallet:

- Open the Copay app
- Tap **+** on Bitcoin wallets
- Tap **Create Personal Wallet**
- Enter a name, select the desired coin
- Expand **Show advanced options**
- Enable **Testnet**

Please read this [article](https://support.bitpay.com/hc/en-us/articles/360004102011-What-is-testnet-How-do-I-avoid-testnet-Bitcoin-scams-) on testnet wallets related to scams.

If this was not your inquiry, please let us know.

Please let us know if you have any additional questions.
Kind regards.

**Comment by huahuayu** [comment]
thx @BGalliotti got it, I can enable testnet now, but another question, how can I import testnet account, I don't have recover phrase, I only have private which I generated by a golang program.
![image](https://user-images.githubusercontent.com/1725060/46186798-00cc8b00-c313-11e8-9b8f-8fe8817b78ff.png)

**Comment by BGalliotti** [comment]
Hello @huahuayu 
Thanks for reaching out to us.

Let us clarify all the things around the import feature:

- On previous versions of the wallet it was possible to import a wallet using a file or pasting a text. Now that is not possible any longer and it is also different on mobile and desktop. 

- On desktop the wallet is exported as a file and as the file is encrypted, a password is used to encrypt the text (that password has nothing to do with all the other wallets password, generally speaking, to encrypt something, you need a password).
You can either open a file or drag and drop it on the **FILE/TEXT** field.

- On mobile, the wallet is exported as a text (which is also encrypted) and that text can be sent by email or just copied to the clipboard. As the text is encrypted, those actions are safe.
To import a wallet you have to paste the text on the **FILE/TEXT** field.

- On both cases, when importing you will have to provide the password for the wallet to be decrypted.
Again, that password has nothing to do with the rest of the wallet passwords.

When importing a wallet, you need:
- Recovery phrase 
or 
- file or text (these latter two deppending on the platform) **Password required in this case**

So, when it comes to the **recovery phrase** ignore the password field that appears for the **phrase** recovery option:

![image](https://user-images.githubusercontent.com/38531900/46213119-22774380-c30e-11e8-9787-e09288e33e9a.png)

> so the question is as same as if I have a paper wallet, which is no encryed text private key(with no recover phrase), how can I import it to bitpay?

- Just paste/write down the recovery phrase, select the proper coin and import the wallet

Please let us know if you have any additional questions.
Kind regards.

**Comment by huahuayu** [comment]
@BGalliotti I can understand your concern, but think about this: I am a developer, and I generated the private keys by a program, it's unencrypted, so in this case, how can I import it into bitpay? or How can I add a password to the private key so I can meet your rules

**Comment by huahuayu** [comment]
@BGalliotti for better track, I open a [new issue ](https://github.com/bitpay/copay/issues/9178)for import unencrypted key, and this issue can be close,thank you.

**Comment by BGalliotti** [comment]
Hello @huahuayu 
Thanks for your updates.

We have answered your question [here](https://github.com/bitpay/copay/issues/9178#issuecomment-425925680).

For people interested in creating a wallet using a custom recovery phrase, please check this [thread](https://github.com/bitpay/copay/issues/9178#issuecomment-425925680).





Please let us know if you have any additional questions.
Kind regards.
