### ISSUE TITLE
How I sign-out from my Copay app on Windows?

### ISSUE THREAD

**Issue by jdipro** [bitpay/copay#9177]
Hi, I opened a Copey Bitcoin Wallet and I downloaded the Windows app.  I close it and open again and the app is ´open´. Is it anyway to logout and start again with a new log in (with password verification)?
Thanks!
Juan.

**Comment by BGalliotti** [comment]
Hello @jdipro 
Thanks for reaching out to us.

We are afraid that is not possible, there is no account where you log in if what you need is a **multiuser** wallet, Copay does not work like that.

You can secure the **app** with a PIN and the **wallets** with a password (two different things).

To secure the app:

- Open the Copay app
- Tap the top corner icon
- Go to **Lock**
- Enable **PIN**
- Enter and confirm.

NOTE: to secure the app, all the wallets must be backed up, this means, please make sure you have a backup of your wallet on a piece of paper safely stored.

To secure a wallet:

- Open the Copay app
- Select the wallet to secure
- Tap the top corner icon
- Enable **Request Encrypt Password**
- Enter and confirm.

NOTE: Bear in mind you need to have the wallets carefully backed up. In case forget this password, the only way to recover a wallet is by the recovery phrase.

Please let us know if you have any additional questions.
Kind regards.

**Comment by jdipro** [comment]
Thank you for your answer!

**Comment by BGalliotti** [comment]
Hello @jdipro 

You are welcome!

We are going to close the ticket.
Feel free to open a new one in case you have any questions or concerns.

**Thank you for your interest and support!**
