### ISSUE TITLE
Sent funds inquiry

### ISSUE THREAD

**Issue by plometeus** [bitpay/copay#9182]
To Whom it may concern,

I sent btcz from the stock exchange to my wallet . blockchain appears too, but it didn't come to the wallet. What am I supposed to do? I am using mac osx and wallet version last 1.0.9
My Wallet Address : t1dDJL1XuWfENgvLj3QKKnqwUzHMrCqo7Mn
BTCZ txid: 61dc362f2e83a5fcbee977cba2cf0b7fef61d1f2caf63ae01f54c3537c8a9f1f

Thanks a lot.
Best regards
<img width="415" alt="ekran resmi 2018-10-03 21 45 38" src="https://user-images.githubusercontent.com/35933288/46432013-df75ff80-c755-11e8-9399-fc122811b6c0.png">
<img width="420" alt="ekran resmi 2018-10-03 21 45 46" src="https://user-images.githubusercontent.com/35933288/46432015-e00e9600-c755-11e8-895d-2f546a67b381.png">
<img width="1731" alt="ekran resmi 2018-10-03 21 46 23" src="https://user-images.githubusercontent.com/35933288/46432016-e00e9600-c755-11e8-94ca-258e6d28a037.png">

**Comment by BGalliotti** [comment]
Hello @plometeus 
Thanks for reaching out to us.

You may want to reach [BTCZ support](https://github.com/bitcoinz-wallets/bitcoinz-copay-wallet/issues). We are not related to the BTCZ wallet.

Please let us know if you have any additional questions.
Kind regards.

**Comment by plometeus** [comment]
Hello, Mr. official,

wallet support section when we write to the copay page, so I wrote My problem there. a program written using the copay source code or wallet. I looked at the site there is no other place to write. could you give me an address I can write to regarding the problem.

thank you.
Best regards

BGalliotti <notifications@github.com<mailto:notifications@github.com>> şunları yazdı (4 Eki 2018 18:05):


Hello @plometeus<https://github.com/plometeus>
Thanks for reaching out to us.

You may want to reach BTCZ support<https://github.com/bitcoinz-wallets/bitcoinz-copay-wallet/issues>. We are not related to the BTCZ wallet.

Please let us know if you have any additional questions.
Kind regards.

**Comment by BGalliotti** [comment]
Hello @plometeus 
Thanks for reaching out to us.

The link we have shared with you is the only one that we found.

If you need further support go to their repository: https://github.com/bitcoinz-wallets/bitcoinz-copay-wallet/issues

and create an issue stating what your problem is, same as you did here.

Kind regards.

**Comment by plometeus** [comment]
Excuse me thanks a lot for your attention and information. Best regards

BGalliotti <notifications@github.com<mailto:notifications@github.com>> şunları yazdı (5 Eki 2018 21:17):


Hello @plometeus<https://github.com/plometeus>
Thanks for reaching out to us.

The link we have shared with you is the only one that we found.

If you need further support go to their repository: https://github.com/bitcoinz-wallets/bitcoinz-copay-wallet/issues

and create an issue stating what your problem is, same as you did here.

Kind regards.
