### ISSUE TITLE
Fees amount / Amount comparable to fees

### ISSUE THREAD

**Issue by mshanx** [bitpay/copay#9183]
Hello guys,
I sent 0.0001 BTC which was 0.65 USD atm and it's shown the commission of 0.000078 BTC and it was 0.51 USD. Your wallet indicated that this commission amount is 43.85% of the total amount. I'm not sure if my maths skills are on so bad level or you are showing wrong commission?
Please have a look at the screen shot: [Image](https://i.imgur.com/ANNNaXo.png)
Thanks for the help!

**Comment by BGalliotti** [comment]
Hello @mshanx 
Thanks for reaching out to us.

Your maths are fine, some amounts are just not worth it to send in relation to the fees.

You can read something about the fees here:

- [5164](https://github.com/bitpay/copay/issues/5164#issuecomment-265569494)
- [4803](https://github.com/bitpay/copay/issues/4803)

We hope this is going to be useful for you.

Something that you can do is change the fees. On the last screen before sending, tap below **Bitcoin miner fee** and change the fees to a different value.

Please let us know if you have any additional questions.
Kind regards.
