### ISSUE TITLE
HELP PLEASE

### ISSUE THREAD

**Issue by mhac25ph** [bitpay/copay#9185]
WHY MY PASSWORD HAD A PROBLEM..HELP ME ME OUT

**Comment by BGalliotti** [comment]
Hello @mhac25ph 
Thanks for reaching out to us.

What problem are you having with the password (which we assume is the wallet Encrypt Password)?

In case that was the problem, please refer to [8532](https://github.com/bitpay/copay/issues/8532#issue-319277251).

Please let us know if you have any additional questions.
Kind regards.

**Comment by mhac25ph** [comment]
thanks sir i just carried away because of the caps lock... i  thank you very much

**Comment by BGalliotti** [comment]
Hello @mhac25ph 

**We are glad you were able to solve the issue!**

We are going to close the ticket.
Feel free to open a new one in case you have any questions or concerns.

**Thank you for your interest and support!**
