### ISSUE TITLE
Unauthorized access? 

### ISSUE THREAD

**Issue by Oceanstar2050** [bitpay/copay#9190]
Did anyone else experience this issue before? 

I have set up a 2-sig wallet, and deposited money in it. This morning, without my access, a proposal was set to create by me, and the vendor accepted it the very next minutes, and my BTC was sent and accepted by him. 

Transaction ID :
8b3321ad110a7332f13a2fa63ced3190d5cb601d85ff417f413a0aba142d24a7

Did my account got hacked?

**Comment by BGalliotti** [comment]
Hello @Oceanstar2050 
Thanks for reaching out to us.

What you are posing makes no sense.

A multi sig wallet needs two signatures.

To understand how a multisig wallet works, please check our [video library](https://www.youtube.com/user/BitPayVideos/search?query=multisig)

Please make sure what is exactly what you have done, and send your inquiry.

**So we can further help, please provide as many of the following details as you can:**

- Current device used: Phone model 
- Current operating system version for the device: iOS, Android..
- Current version of the wallet used: CoPay App > Settings > About CoPay 
- Any log files containing error details: CoPay App > Settings > About CoPay > Session Log > Tap on the Upper right corner (three dots) > Send by email (you can screenshot the content as well and attach the images to your e-mail. In such case, please make sure you move the slider to the **"Debug"** position).
- Error screenshot: On [iPhone](https://apple.co/1DAB204) on [Android](https://www.wikihow.tech/Take-Screenshots-on-an-Android)
- Steps to replicate: Steps needed for the error to appear.
- CoPay Wallet ID - To get your Wallet ID, open your CoPay application, then go to `Settings` > [Your wallet] > `More Options` > `Wallet Information`. On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste in your e-mail.

**We look forward to hearing from you.**

**Comment by Oceanstar2050** [comment]
I am using a Samsung S9, and the Copay version V4.7.0.

I was in a 2-sig wallet, where my permission is needed to send money out, and I have about $7000 USD worth of bitcoin in it.

Two days ago, without me knowing it, the other (vendor) party created a proposal (Copay says Client, which is me, created it) to send money to himself, and he then accepts the proposal and have the BTC taken out of my account!

Attached are screenshots for the transaction. I have not received the goods yet, and therefore I would not have released the funds, but apparantly the other party got a hold of my acocunt and released the fund to themselves?

Can you trace the IP where the proposal creation was generated?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by BGalliotti** [comment]
Hello @Oceanstar2050 
Thanks for reaching out to us.

> Attached are screenshots for the transaction. I have not received the goods yet, and therefore I would not have released the funds, but apparently, the other party got a hold of my account and released the fund to themselves?

- There are no attachments on your response, if you consider they will help in understanding the issue, please reply again attaching the pictures.

> Two days ago, without me knowing it, the other (vendor) party created a proposal (Copay says Client, which is me, created it) to send money to himself, and he then accepts the proposal and have the BTC taken out of my account! 

We have suggested you watch the videos explaining how multisig wallets work.

Let's try an explanation:

We have a wallet (for instance) 2-2 which means 2 Copayers (copayer A, copayer B), 2 signatures.
To send funds out of this wallet, copayer A, attempts to make the payment or pay the invoice.
That generates a **payment proposal** that is sent to copayer B.

Until now, the transaction does not exist on the bitcoin network, it has copayer A signature and it is waiting for copayer B signature.

Copayer B realizes there is a payment proposal.
- If he approves the proposal, the transaction is created and broadcast.
- If not, the proposal is declined, everything ends there, the funds do not leave the wallet, no transaction is broadcast.

In the specific case of a 2-1 wallet (2 copayers, one signature) the proposal needs one signature to be approved. In this case, the second copayer approval is not needed.
This is not your case as your wallet is a 2-2.

In your case, you (or someone who uses your device) must have approved the proposal. 

Please let us know if you have any additional questions.
Kind regards.
