### ISSUE TITLE
After removing SIM card Copay refuses to start

### ISSUE THREAD

**Issue by ihqtzup** [bitpay/copay#9192]
https://github.com/bitpay/copay/issues/2665

**Comment by BGalliotti** [comment]
Hello @ihqtzup 

Thank you for reaching out to us.

**So we can further help, please provide as many of the following details as you can:**

- Current device used: Phone model 
- Current operating system version for the device: iOS, Android..
- Current version of the wallet used: CoPay App > Settings > About CoPay 
- Any log files containing error details: CoPay App > Settings > About CoPay > Session Log > Tap on the Upper right corner (three dots) > Send by email (you can screenshot the content as well and attach the images to your e-mail. In such case, please make sure you move the slider to the **"Debug"** position).
- Error screenshot: On [iPhone](https://apple.co/1DAB204) on [Android](https://www.wikihow.tech/Take-Screenshots-on-an-Android)
- Steps to replicate: Steps needed for the error to appear.
- CoPay Wallet ID - To get your Wallet ID, open your CoPay application, then go to `Settings` > [Your wallet] > `More Options` > `Wallet Information`. On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste in your e-mail.

**We look forward to hearing from you.**

**Comment by ihqtzup** [comment]
CAT S60
Android 6
4.7.1
- Cant start Copay
- 
![screenshot_20181008-130319](https://user-images.githubusercontent.com/1743396/46748973-83fbc280-ccbd-11e8-9fbc-e31a3e61f218.png)
- Remove SIM and start Copay.
- Cant get wallet id. Copay does not start

**Comment by ihqtzup** [comment]
CAT S60
Android 6
4.7.1
- Cant start Copay
- 
![screenshot_20181008-130319](https://user-images.githubusercontent.com/1743396/46748973-83fbc280-ccbd-11e8-9fbc-e31a3e61f218.png)
- Remove SIM and start Copay.
- Cant get wallet id. Copay does not start

**Comment by BGalliotti** [comment]
Hello @ihqtzup 
Thanks for reaching out to us.

We have been researching this issue and testing the app on Android 6.0 and could not reproduce it.

We are still investigating and would appreciate your patience.

Kind regards.

**Comment by BGalliotti** [comment]
Hello @ihqtzup 

We have released a new update for the app, please update your app and try again.

Please let us know if you have any additional questions.
Kind regards.
