### ISSUE TITLE
Feature Request: OpenCAP Aliases

### ISSUE THREAD

**Issue by lane-c-wagner** [bitpay/copay#9193]
OpenCAP is an open-source protocol for relating aliases (human readable and customizable identifiers) to addresses. Integrating at least the spending side would be really easy (although receiving is also pretty easy) its just a REST protocol.

Protocol: https://github.com/opencap/protocol

Server Implementation: https://ogdolo.com

**Comment by matiu** [comment]
thanks, for the moment we are not planning on integrating with openCAP. While the approach we interesting we would prefer something based on the blockchain, so users dont need to trust a server to serve the real addresses.
