### ISSUE TITLE
Sent money from copay to lqdfx and it declined. But my money never returned to copay.

### ISSUE THREAD

**Issue by daviduzoma** [bitpay/copay#9195]
This has happened to my deposit on 10/08. Wallet i:7dcebe52-1426-416f-8ee0-f01e963b6239 I believe the address was 1DVZogaMrWhopVhZy9MqwYHrjjKYnxMUzC.  This was a transaction for 35$

**Comment by BGalliotti** [comment]
Hello @daviduzoma 
Thanks for reaching out to us.

We apologize for the delay.

This transaction might be the one you are talking about:

https://insight.bitpay.com/tx/9115975e670d37184d114ef64710eca1e1f059223bf7db1c3978bee6224c7315

It has properly gone through.

If you were talking about a different transaction please let us know.
Kind regards.
