### ISSUE TITLE
Error: We were unable to decode your transaction

### ISSUE THREAD

**Issue by amz-amz** [bitpay/copay#9196]
I am using Copay for Windows, and trying to do a test transaction, but get this error
![image](https://user-images.githubusercontent.com/44053058/46790699-d5e52c80-cd3f-11e8-8a5e-441cb718a6c7.png)

**Comment by BGalliotti** [comment]
Hello @amz-amz 
Thanks for reaching out to us.

We are researching your issue. 

Please try again, we will be posting an answer soon.

We would appreciate your patience.

Kind regards.

**Comment by amz-amz** [comment]
I guess it is fixed now :)

**Comment by BGalliotti** [comment]
Hello @amz-amz 

**We are glad you were able to solve the issue!**

We are going to close the ticket.
Feel free to open a new one in case you have any questions or concerns.

**Thank you for your interest and support!**
