### ISSUE TITLE
How to recover BCH sent to a BTC wallet

### ISSUE THREAD

**Issue by bucko7** [bitpay/copay#9197]
I did not receive a payment to my BCH account.

**Comment by BGalliotti** [comment]
Hello,

To recover Bitcoin Cash (BCH) from a BitPay/Copay BTC wallet, please follow the steps below:
1. Within the Bitpay/Copay app, click the BTC wallet that BCH funds were sent to
2. Click the settings button at the top right
3. Tap on the `Duplicate ( Bitcoin Cash )` option

Duplicating the BTC wallet will create a BCH wallet in the app with your BCH balance.

The option above to `duplicate` is not available for multi-sig BTC wallets. You will need to use the [recovery tool](https://bitpay.github.io/copay-recovery/) to recover BCH funds sent to a multi-sig BTC wallet.

For help with this process check out our [video guide](https://youtu.be/BW4hzvIk79g) or our [help article](https://support.bitpay.com/hc/en-us/articles/115005019583-How-Can-I-Recover-Bitcoin-Cash-BCH-from-My-Wallet-).

Finally, please clear your history cache. To do so, open up the BitPay app and do the following steps:

- `Wallet` > `Preferences` (icon in the top right corner) > `Transaction History` > `Clear cache`

- `Wallet` > `Preferences` (icon in the top right corner) > `Wallet Addresses` > `Scan addresses for funds`

If you have any other questions or concerns, please let us know.

**Comment by marcosbkpty** [comment]
Hi, I did the Duplicate procedure (I had sent BCH from one wallet into BTC address at Bitpay), and balance now shows, but is not available as it does not get confirm in the blockchain. It has been a day already. After clearing the cache, it shows the balance again, but without confirming .... any idea what is wrong? Thanks!

**Comment by BGalliotti** [comment]
Hello @marcosbkpty 
Thanks for your update, we are glad the transaction went through properly.

Please open a new thread if you have any additional questions.
Kind regards.
