### ISSUE TITLE
Funds not available

### ISSUE THREAD

**Issue by m16paw** [bitpay/copay#9200]
Hello, I have only started using bitpay for one reason, to purchase cards from egifter.com

I transferred 31$ from my blockchain account, the total from egifter was 28.95 and when I went to pay it said insufficient funds. After restarting my bitpayapp on my PC i had 0 btc. I tried clicking my transaction but it said transaction is not available at this time.
![image](https://user-images.githubusercontent.com/44129240/46912480-e3661500-cfd2-11e8-8bb7-82b117d2dd16.png)

I really need help asap as I am very worried

My twitter is @promises and my kik is camo if anyone can message me on there as i am unsure of how notifications work on here

Thanks
Alan

**Comment by m16paw** [comment]
![image](https://user-images.githubusercontent.com/44129240/46912489-0264a700-cfd3-11e8-97ae-1e5c3f867f4a.png)
![image](https://user-images.githubusercontent.com/44129240/46912493-07295b00-cfd3-11e8-99b1-6d40a6de201e.png)

**Comment by Promises** [comment]
I dont have anything with bitpay to do, you seem to have tagged me by accident.

But are you certain both the bitpay wallet on the pc and phone are connected to the correct account or wallet?
