### ISSUE TITLE
 Se puede recibir varias veces en la misma dirección de bitcoin

### ISSUE THREAD

**Issue by Blancaguado** [bitpay/copay#9201]
Buenas tardes, ¿se puede hacer desde la billetera de copay recibir 2 o mas veces en el mismo nº de cuenta o dirección? ¿ o hay que generar una nueva cada vez que se quiera recibir bitcoin? 

Muchas gracias

**Comment by BGalliotti** [comment]
Hola @Blancaguado 
Gracias por ponerte en contacto con nosotros.

> ¿se puede hacer desde la billetera de copay recibir 2 o mas veces en el mismo nº de cuenta o dirección?

- Si, es posible, no hay un limite de veces en las que una direccion puede ser usada. Asimismo, todas las direcciones son validas, nunca caducan

> ¿ o hay que generar una nueva cada vez que se quiera recibir bitcoin?

- No hace falta, esto lo hace la aplicacion por defecto. De todas maneras si usted quisiera hacerlo, lo que debe hacer es compartir la direccion que usted desee, con la persona/entidad que va a enviarle fondos.

Por favor, háganos saber si tiene alguna pregunta adicional.
Saludos cordiales.
