### ISSUE TITLE
Finding a xpub from a copay from a specific address

### ISSUE THREAD

**Issue by boichez** [bitpay/copay#9203]
Well guys...Maybe you are thinking... what?

Let me try explain...

I am using this tool to try to take a specific pkey from a BIP32 Extended Key (DERIVED ADDRESS).

https://www.coinomi.com/recovery-phrase-tool.html
I have my seed and its generate everything,,,

But there is a problem...

I don't know why, there is an addrress in my wallet that when I deposit a altcoin there, I receive funds... but when I withdraw, It disapears and do not show the XPUB and It do not show it forr me in BIP32 Extended Key list... 

Any Idea why?

**Comment by matiu** [comment]
sorry, we can't help with that.
