### ISSUE TITLE
Missing 1 word from recovery seed (24 words)

### ISSUE THREAD

**Issue by tmdrns** [bitpay/copay#9204]
Hello all,

I f*cked up. I have al my currencies stored on a Trezor One, and (thought) i had the recovery seed with 24 words. When i updated the firmware of the Trezor, the device got wiped. When i wanted to restore using my recovery seed, i found out it contains only 23 words. I tried different tools, but nothing works. My situation:

- Wiped Trezor One
- I don't know my BTC adress of the wallet (for sure, i think i have the correct one)
- I don't know the public key
- I have 23 words written down

Do you guys have any suggestions?

**Comment by junderw** [comment]
Nope... unfortunately, there are soooo many ways you could have mis-written the phrase...

So 24 possible slots for the missing word.

Multiply by 2048 words.

49152 possibilities. Then there's a 8 bit checksum, so 1 in 256 is a valid phrase.

So 192 possible valid phrases you could have.

But this assumes you have all the other words correct and in the right order.

**Comment by Silvanobonafe** [comment]
Hi i have software to find the word back.
please go to my website bonafe.nl

**Comment by Silvanobonafe** [comment]
I like to try to help you. 
Contact me if you want?
www.bonafe.nl

**Comment by Silvanobonafe** [comment]
Bitpay why you delted my comment? 
I just try to help this person...
 info@bonafe.nl

**Comment by BGalliotti** [comment]
Hello @Silvanobonafe 

Many people has been scammed by this mean, so have taken that policy to moderate this kind of comment.

So, unless a user asks you for your email address, do not post it, otherwise, the comment will be deleted/moderated.

Kind regards.

**Comment by Travis2022** [comment]
@tmdrns 

I read your issue if you haven't recovered your lost wallet, i can recover it send me message here  : anywalletrecovery@gmail.com
