### ISSUE TITLE
copay

### ISSUE THREAD

**Issue by ayojust** [bitpay/copay#9207]
I am having the same issues as others as I see which is depositing money into my lqdfx broker account and the transaction being declined but no funds went back to my copay wallet. I have looked at the other methods that were suggested and still nothing.

**Comment by BGalliotti** [comment]
Hello @ayojust 
Thanks for reaching out to us.

- What is exactly the issue you are having?
Before moving forward please check #9035 and #9133 and post your question/answer on the related thread.

If your inquiry was a different one, not related to those posts, answer on this thread.

Please let us know if you have any additional questions.
Kind regards.

**Comment by BGalliotti** [comment]
Hello @ayojust 
Thanks for reaching out to us.

> the issue is deposited bitcoin into an account 
- What account? If you were talking about bitpay, remember there are no accounts but wallets.
- From what account?
- To what account/address?
- **Please send us the BitPay/Copay Wallet ID and the transaction hash / ID or the link so we can further investigate and address your inquiry.**

- The transaction hash / ID is a alphanumeric chain like this: **d0a23876de7cf87574b5cda7557bcc8af5d84f3fd1e6f4c6063fd6b72b0e69ae**

> nothing went through and the transaction was declined
- Then the funds have not been moved from where they were.

> I am here requesting a refund back to my copay account because supposedly there was insufficient funds trying to deposit.

- Where? Copay? LQDFX?

**We look forward to hearing from you.**
Kind regards.

**Comment by ayojust** [comment]
From my wallet to my lqdfx account. No funds was deposited into my LQDFX account because it states there were insufficient funds. Now, I would assume that since no funds were deposited into my LQDFX account that the funds will reappear back into my copay wallet. But that’s not the case because it shows in my wallet that the funds were sent.

**Comment by BGalliotti** [comment]
Hello @ayojust 
Thanks for reaching out to us.

There are two possibilities:

1. The funds were sent.
In this case, everything is fine on our end. The time of confirmation of the transaction depends on the bitcoin network and the fees you have used.
There is nothing to do here.
Check on the other extreme and ask them what is going on.

If the transaction is properly broadcast and has no confirmations yet, you will have to wait. 
Typically it gets confirmed in a few hours. If not, it could take up to a month. If it never got confirmed, the funds will go back to your wallet after that.

2. The funds were NOT sent
They will be in your wallet. 
The other extreme will not receive anything.
The transaction has never existed.

If you need more support on our end:

- **Please send us the BitPay/Copay Wallet ID and the transaction hash / ID or the link so we can further investigate and address your inquiry.**

- To get your Wallet ID, open your Copay/BitPay application, then go to `Settings` > [Your wallet] > `More Options` > `Wallet Information`. 
On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste it in your e-mail. 
You can do the same on your computer by clicking on the wallet ID.

- The transaction hash / ID is a alphanumeric chain like this: **d0a23876de7cf87574b5cda7557bcc8af5d84f3fd1e6f4c6063fd6b72b0e69ae**

**We look forward to hearing from you.**




Please let us know if you have any additional questions.
Kind regards.

**Comment by ayojust** [comment]
Why is that no matter how much I send the receiver states that I am still short some money no matter how much I send. This is getting ridiculous. This is terrible and I need answers. And yes to answer the question I have enough funds to send what I am sending over and even some left over in the account.

**Comment by BGalliotti** [comment]
Hello @ayojust 
Thanks for reaching out to us.

We will put it simply:

- Find your wallet balance below. Those are the funds you have. If you want to send the whole amount,
go to the wallet, tap **Send** on the bottom, enter the receiving address and when you are prompted for the amount, tap **Send max**.
- You have not provided the information we requested previously. Without clear, detailed, enough and accurate information, we cannot provide answers.

`* Balance
  Total: 0.00367749 btc (0.00000000 btc locked)
  Confirmed: 0.00367749 btc (0.00000000 btc locked)
  Available: 0.00367749 btc (0.00367749 btc confirmed / 0.00000000 btc unconfirmed)
  By address:
    1CX8KmZVwVg9PsP1uNMA6Vdsp1KXQ76RjM (m/1/5): 0.00237315 btc
    1KXWv3o6qgBs2zG4YhyFvQgMQQFpoc4GcS (m/1/4): 0.00130434 btc
`

Kind regards.

**Comment by Hneng** [comment]
Hneng.thang
