### ISSUE TITLE
Billetera compartida desaparecio

### ISSUE THREAD

**Issue by kamiski** [bitpay/copay#9209]
Mi socio y yo tenemos una billetera compartida...mi celular se me daño y yotengo laa 12 palabras de mi wallet principal pero las de la compartida no recuerdo que me las diera la aplicacion....como puedo hacer para recuperar mi dinero si mi socio si tiene las 12 palabras pero yo no? 

[ENGLISH]
My partner and I have a shared wallet ... my cell phone is hurting me and I have the 12 words of my main wallet but the shared words I do not remember that I gave them the application ... how can I get my money back if my partner does have the 12 words but I do not? help me please urgently need to use the funds

**Comment by kamiski** [comment]
My partner and I have a shared wallet ... my cell phone is hurting me and I have the 12 words of my main wallet but the shared words I do not remember that I gave them the application ... how can I get my money back if my partner does have the 12 words but I do not? help me please urgently need to use the funds

**Comment by kamiski** [comment]
Por favor agradezco su ayuda no se q hacer

**Comment by BGalliotti** [comment]
Hola @kamiski,

Gracias por contactarnos.

> Mi socio y yo tenemos una billetera compartida...mi celular se me daño y yotengo laa 12 palabras de mi wallet principal pero las de la compartida no recuerdo que me las diera la aplicacion....como puedo hacer para recuperar mi dinero si mi socio si tiene las 12 palabras pero yo no?

SI su billetera compartida es 2-1 (2 copayers y 1 firma), su socio puede enviar los fondos a otra billetera. Pueden crear una nueva billetera compartida y enviar los fondos ahi.

Si la billetera es 2-2 (2 copayers, 2 firmas) lamentablemente no pueden recuperar los fondos dado que requieren dos firmas para mover los fondos.

Saludos cordiales.
