### ISSUE TITLE
BCH wallet duplication should copy addresses instead of scanning

### ISSUE THREAD

**Issue by BGalliotti** [bitpay/copay#9212]
When duplicating a BCH wallet (usually for funds recovery purposes) the app scans 20 addresses.

If the totality of the funds is covered there, everything is fine, but, if part or all the funds are stored in addresses greater than 20, (i.e the address with funds is the number 45) the funds will not be found.

The addresses copy will provide:

- Faster duplication
- Better and simpler recovery

We are open to contributions.
Best regards.

**Comment by matiu** [comment]
fixed.
