### ISSUE TITLE
Pin Freezing

### ISSUE THREAD

**Issue by andrewhramadan** [bitpay/copay#9216]
I can’t type in my PIN to access my wallet. It says I have the most updated version of the app. Any suggestions? Every time it just times me out for 2 minutes

**Comment by gabrielbazan7** [comment]
Hi @andrewhramadan, what do you mean by "can't type", you mean the pin pad is not working ? Do you wait the 2 minutes? Are you sure you are entering the correct pin? If not the only way to get access to your wallets will be deleting the app and importing them again ( first be sure you have your 12 words recovery phrase ). Also, could you share more info about the phone you are using? thanks!

**Comment by andrewhramadan** [comment]
Please delete this, was just human error
