### ISSUE TITLE
Unrecognized sent transaction in my account.

### ISSUE THREAD

**Issue by Opcommshq** [bitpay/copay#9234]
Hi Team

Please be advised that there is a sent transaction in my Copay wallet that I am not aware of.
That is a very urgent matter, please could you advise if there is anyway to track this transaction to the receiving wallet owner. please could you also confirm what time zone is displayed in my Copay wallet, is it EST, UTC or GMT. your quick response will be appreciated.

**Comment by BGalliotti** [comment]
Hello @Opcommshq,
Thanks for reaching out to us.

We are sorry you have had this bad experience.

> please could you also confirm what time zone is displayed in my Copay wallet, is it EST, UTC or GMT. your quick response will be appreciated.

The time used is your device local time.

> Please be advised that there is a sent transaction in my Copay wallet that I am not aware of.
That is a very urgent matter, please could you advise if there is anyway to track this transaction to the receiving wallet owner. 

Every outgoing transaction on your wallet has to be signed by the wallet private keys.
This means, to be valid, a transaction has to be sent from your wallet using your device/devices.

Here are two chances:

  -  You have sent the funds, maybe accidentally.
  -  Somebody stole your wallet (recovery phrase, private key) or your device/devices where the wallet is installed and has sent the funds.

Unfortunately, there is nothing we can do in this case. Also, a Bitcoin transaction cannot be reversed, so there is no way to recover those funds.

Please make sure your devices are safe and your wallets are secured with password/fingerprint if necessary.

**To secure your wallet, follow these instructions:**

- Open the BitPay app
- Select the wallet you want to secure with a password
- Tap the upper right corner icon
- Enable **Request Encrypt Password**
- Enter the password and confirm

**To secure your device (the wallet app)**

- Open the BitPay app
- Tap the gear icon on the upper right corner
- Tap Lock and select the method you want to use (PIN or Fingerprint)

**Note:** to use the fingerprint lock, your device has to support it and it has to be set up, this is done on the system settings and will vary depending on your phone.

- **If you think somebody could have used your wallet, do not use it anymore to receive funds.**

- **If it still has funds, move all the funds to another bitcoin wallet.**

Please let us know if you have any additional questions.
Kind regards.

**Comment by Opcommshq** [comment]
Thanks for the information.  Unfortunately the security of our account was compromised and funds was sent illegally.  Does Copay store any IP (or any other information) regarding logins to the app or transactions being sent/received.  Could we check the information for the specific transaction that was sent?  Any assistance will be appreciated.

**Comment by BGalliotti** [comment]
Hello @Opcommshq 
Thanks for reaching out to us.

> Does Copay store any IP (or any other information) regarding logins to the app or transactions being sent/received, or maybe type of device (mobile/pc)?.

Copay only keeps track of the transactions where the wallet is involved in, meaning the funds sent and received. To see the transactions, open the Copay app and open the desired wallet.
No data of the receiver is stored in the wallet (there is no way to know about the receiver of the funds).

> Could we check the information for the specific transaction that was sent? 

A transaction consists of an amount sent or received, the origin address/es and destination address/es.
You can check all the transactions on the wallet. Then you can check the transactions on the blockchain to have more details.
A good tool is [Blockchair](https://blockchair.com/).

Please let us know if you have any additional questions.
Kind regards.

**Comment by BGalliotti** [comment]
Hello @Opcommshq 
Thanks for reaching out to us.

We cannot do that, the wallet does not retrieve that information, and does not use it.

We understand your questions and concerns, unfortunately, there is nothing we can do to help.

Please let us know if you have any additional questions.
Best regards.
