### ISSUE TITLE
Bitcoin Cash

### ISSUE THREAD

**Issue by Blancaguado** [bitpay/copay#9239]
Buenas tardes, quisiera enviar bitcoin cash a la billetera de copay y he visto en avanzado que hay un apartado que pone: si se habilita, las direcciones de Bitcoin Cash se mantendran usando el formato Copay y no el nuevo formato CashAddr.
¿Que significa esto? ¿Debo activarlo?
Yo la billetera de Copay la tengo descargada desde finales del 2017, principios del 2018, no se exactamente la fecha. Si es algo que salio a posterior, ese nuevo formato, quizá no la tenga configurada como toca y me salga una direccion de bitcoin cash a la que no lleguen los bitcoin Cash.
¿podrían ayudarme? 

Muchas gracias

**Comment by Blancaguado** [comment]
Good afternoon, I would like to send cash bitcoin to the copay wallet and I have seen in advance that there is a section that is set: if enabled, the Bitcoin Cash addresses will remain using the Copay format and not the new CashAddr format.
What does this mean? Should I activate it?
The legend of Copay and the version downloaded from the end of 2017, beginning of 2018, did not exactly date. If it's something that comes out later, this new format will probably not be configured as it touches and I get an effective bitcoin address that did not reach Bitcoin Cash.
Could you help me?

thank you

**Comment by BGalliotti** [comment]
Hola @Blancaguado,
Gracias por consultarnos.

La opcion que usted menciona, sirve para mostrar las direcciones de Bitcoin Cash en formatos diferentes. En general es poco usado, de todas formas si usted necesitara compartir las direcciones BCH  en este formato, le sera util activar la opcion.

El hecho de que active o desactive esta opcion, no influye en el hecho de que usted reciba o no fondos, siempre y cuando usted comparta correctamente la direccion a donde quiere recibir los fondos.

Saludos cordiales.
