### ISSUE TITLE
Error: We were unable to decode your transaction / Testnet issue

### ISSUE THREAD

**Issue by davidlev** [bitpay/copay#9240]
i am trying to perform a payment to a bitpay invoice on testnet and getting this error. Tried to send via windows and android wallet

**Comment by markokoleznik** [comment]
The same thing happens to me. @matiu if you any need additional info (steps to reproduce, screenshots), just say.

**Comment by matiu** [comment]
Hi! This is not really a Copay error, but a message returned by the payment server.

Could you please contact support@bitpay.com regarding this issue?

There was a Testnet outage yesterday, so please try again before contacting support, just in case.
thanks a lot!
