### ISSUE TITLE
BTC gone

### ISSUE THREAD

**Issue by xxx67024** [bitpay/copay#9241]
Welcome everyone. I have a problem. The fact is that after I sent from my Copay bitcoin wallet a small BTC amount, all other BTC that remained in the account disappeared, the transaction history also disappeared. In what could be the problem? I use iPhone 8 Plus (iOS 12.0)

**Comment by BGalliotti** [comment]
Hello @xxx67024 
Thanks for reaching out to us.

**Please open up your BitPay app and try the following steps:**

- Wallet > Preferences (top right corner icon) > Transaction History > Clear cache
- Wallet > Preferences (top right corner icon) > Wallet Addresses > Scan addresses for funds

Please let us know if you have any additional questions.
Kind regards.

**Comment by Travis2022** [comment]
@xxx67024 

if you haven't recovered your wallet, i can restore it contact me : anywalletrecovery@gmail.com
