### ISSUE TITLE
BitNational ATM / Copay HELP

### ISSUE THREAD

**Issue by stranglehold1984** [bitpay/copay#9242]
Today I went to a BitNational ATM and scanned the code for my Copay wallet, inserted $200CAD intk the machine and hit send, i recieved a receipt for my transaction. It has now been 2+ hours and the bitcoins have not shown up in my Copay wallet. The wallet information is correct and corresponding to both the receipt and my wallet. But there was no transfer. I have photos of my receipt, as well as my wallet QR code. 
Can anyone please help me find my bitcoins!!!!

**Comment by BGalliotti** [comment]
Hello @stranglehold1984 
Thanks for reaching out to us.

You should check two things:

- The transaction hash / ID is a alphanumeric chain like this: **d0a23876de7cf87574b5cda7557bcc8af5d84f3fd1e6f4c6063fd6b72b0e69ae** you can enter this string on [Insight](https://insight.bitpay.com/) (paste it) and check what is the transaction status. (it is confirmed, not, it went to your wallet address, not..)

**Please open up your BitPay app and try the following steps:**

- Wallet > Preferences (top right corner icon) > Transaction History > Clear cache
- Wallet > Preferences (top right corner icon) > Wallet Addresses > Scan addresses for funds

**We look forward to hearing from you.**
Kind regards.

**Comment by jesskie** [comment]
How
