### ISSUE TITLE
BitPay Phantom Spending Password

### ISSUE THREAD

**Issue by darakaye** [bitpay/copay#9252]
Hello,

Hopefully, you guys can help me.  I downloaded the bitpay wallet bc a vendor wanted me to pay using bitpay invoice.  I sent btc to this new wallet.  I went to export btc to invoice in bitpay and my app required a spending or encrypted password.  I never set one up.  Dont have the 12 word back up either as I dont use this wallet.  Just needed for this one send.  What can I do now??  yikes!

**Comment by BGalliotti** [comment]
Hello @darakaye 
Thanks for reaching out to us.

Please refer to [#5497](https://github.com/bitpay/copay/issues/5497#issuecomment-435405463)

Please let us know if you have any additional questions.
Kind regards.
