### ISSUE TITLE
Transaction not available at this time

### ISSUE THREAD

**Issue by HsounaZinoubi** [bitpay/copay#9253]
I just transferred money in and it says Transaction not available at this time
what is the problem ? it has been more then 2 hours!!!

**Comment by BGalliotti** [comment]
Hello @HsounaZinoubi 
Thanks for reaching out to us.

Please refer to [8803](https://github.com/bitpay/copay/issues/8803#issuecomment-3987754410)

Please let us know if you have any additional questions.
Kind regards.
