### ISSUE TITLE
Wrong transaction / BCH recovery?

### ISSUE THREAD

**Issue by svorovsky007** [bitpay/copay#9257]
Hello, I have a trouble, please help me, I transferred to the wallet with Binance Copay BTC, not the cryptocurrency BCH(BCC), indicated the wallet turns out, the transaction has already passed. What can be done? How to get the money back? I have already opened a new wallet for BCH in the app. Help please.

**Comment by BGalliotti** [comment]
Hello @svorovsky007 

Thanks for reaching out to us.

It seems you have sent BCH to a BTC wallet.
Please refer to [9197](https://github.com/bitpay/copay/issues/9197#issuecomment-429366981)

If that was not your problem, please send us a clearer explanation so we can properly address it.

Please let us know if you have any additional questions.
Kind regards.
