### ISSUE TITLE
Network Match Error

### ISSUE THREAD

**Issue by reevers06** [bitpay/copay#9265]
Hi There

When I try to send funds from my Copay account it says  The wallet you are using  does not match the network of the address . Not sure what to do to fix it.

Thank you

**Comment by BGalliotti** [comment]
Hello @reevers06 

Thanks for reaching out to us.
We are sorry you have had this bad experience.

This error appears when:

- You are trying to send Bitcoin (BTC) to a Bitcoin Cash (BCH) address or vice-versa
- You are trying to send BTC/BCH **testnet** to **livenet** or vice-versa

Please make sure the wallet you are using, matches the network (livenet/testnet) and currency (BTC/BCH) of the destination address.

- Also please try scanning or pasting the destination address, not typing it in.

What is testnet? click [here](https://support.bitpay.com/hc/en-us/articles/360004102011-What-is-testnet-How-do-I-avoid-testnet-Bitcoin-scams-) to know more about it.

Please let us know if you have any additional questions.
Kind regards.

**Comment by reevers06** [comment]
Hi There 

I do have Bitcoin and Bitcoin cash in my wallet but have never tried to send Bitcoin Cash. 

The send function quit working after the last update I received for Copay. It always worked fine previously. 

Is there a way to update it again? I am at a loss on what to do but I need to be able to use it. 

Thanking you in advance. 

Bryan Reeves

**Comment by BGalliotti** [comment]
Hello @reevers06 
Thanks for reaching out to us.

> Hi There I do have Bitcoin and Bitcoin cash in my wallet but have never tried to send Bitcoin Cash.

**Everything is fine with having Bitcoin and Bitcoin Cash.**

> The send function quit working after the last update I received for Copay. It always worked fine previously.  

**The function works properly. What does not work properly is when you manually type in the address.** Please scan or copy and paste the address.

> Is there a way to update it again? I am at a loss on what to do but I need to be able to use it.

**We will be releasing an update soon.**

Please let us know if you have any additional questions.
Kind regards.
