### ISSUE TITLE
Import Bitpay/Copay wallet into Bitcoin core wallet

### ISSUE THREAD

**Issue by manjunath2334** [bitpay/copay#9280]
Hi guys, 
  I am new to this Bitcoin full node. Please let me know how to import Bitpay/Copay wallet into my Bitcoin core wallet

**Comment by BGalliotti** [comment]
Hello @manjunath2334 
Thanks for reaching out to us.

In general, you import a wallet by using its recovery phrase or by its private key.

We do not specifically know if the bitcoin core desktop wallet has the importing feature.
Please reach the bitcoin core support out and let them know about your inquiry.

Please let us know if you have any additional questions.
Kind regards.

**Comment by manjunath2334** [comment]
@BGalliotti Thanks for the response, definitely will reach out Bitcoin core team, and will check with them as well.
