### ISSUE TITLE
no puedo enviar BCH desde mi billetera

### ISSUE THREAD

**Issue by Blancaguado** [bitpay/copay#9284]
Buenas tardes, 
quiero enviar desde mi billetera BCH en Copago y no se abre, cuando copio la dirección de envío, solo se abre la billetera BTC, y lo que quiero es enviar BCH. 
¿Me puedes ayudar? 
Gracias !!

**Comment by BGalliotti** [comment]
Hola @Blancaguado,
Gracias por escribirnos,

Vemos que abrio otro ticket por la misma cuestion: #9283
Todavia necesita ayuda con esto?

Esperamos su respuesta, saludos cordiales.

**Comment by Blancaguado** [comment]
Hola, no es el mismo problema que ya comente en otra ocasión pues ya he hecho transacciones con la billetera BCH.
Ahora cuando quiero enviar el BCH que tengo en la billetera a otra persona.. se me abre directamente para enviar BTC y no puedo mandar el BCH.  No sé que es lo que hago mal o que pasa.

Gracias

**Comment by BGalliotti** [comment]
Hola @Blancaguado,
Gracias por escribirnos,

Esto se debe a que la billetera interpreta ese formato de direcciones, como direcciones BTC.

Por favor refierase al post #8843
Debe transformar la direccion con la herramienta provista.

Esperamos su respuesta, saludos cordiales.
