### ISSUE TITLE
Problem in payment 

### ISSUE THREAD

**Issue by hanna-bitcoins** [bitpay/copay#9285]
I made a payment 1 hour ago, it’s showing sending and payment unconfirmed !!! I confirm my payment! 
Money gone from my wallet ! But user didn’t receive the money !!!

**Comment by BGalliotti** [comment]
Hello @hanna-bitcoins 
Thanks for reaching out to us.

- Has your payment succeded?

Please let us know if you have any additional questions.
Kind regards.

**Comment by BGalliotti** [comment]
Hello @hanna-bitcoins 

**We have not heard from you in while!**

**Are you still experiencing an issue?**

We are going to close this thread, please if you need further help, open a new one explaining the issue in detail, providing all the relevant information possible, we will be happy to help you :)

Kind regards.
