### ISSUE TITLE
Amazon 

### ISSUE THREAD

**Issue by christiangirl41** [bitpay/copay#9287]
Would like to purchase 1000 gift card with my bitcoin wallet 
Christine Massey christiangirl41@gmail.com
7724539446

**Comment by BGalliotti** [comment]
Hello @christiangirl41 
Thanks for reaching out to us.

To purchase Amazon gift cards, do the following:

- Open the BitPay app
- Scroll down and go to Amazon Gift Cards
- Tap **Enter amount** and enter the desired amount
- Select the wallet you will use to purchase the card
- Confirm the purchase

Please let us know if you have any additional questions.
Kind regards.

**Comment by vnbtc** [comment]
@bitpayalan

**Comment by christiangirl41** [comment]
Thank you 😊

**Comment by christiangirl41** [comment]
Thank you 😊
