### ISSUE TITLE
I lost, forgotten my password, what can I do?

### ISSUE THREAD

**Issue by BGalliotti** [bitpay/copay#9292]
Many people lose or forget their passwords. This is critical for people having funds in their wallets or expecting to receive decent amounts of cryptocurrency.

Since the password is stored locally on your device, there is nothing we can do to restore it.

There are two ways to solve this situation:

1. Remember the password. Keep in mind there are no special requirements for the password such as numbers, symbols, uppercase letters, etc.

2. Restore the wallet with the 12-word recovery phrase.

For option 2:

**What you can do is restore the wallet.**

**A)** First, make sure the recovery phrase you have, corresponds to the wallet you want to restore.

i) **IF YOU HAVE ONLY ONE WALLET IN THE APP**

- If you have only one wallet, import the wallet with the instructions below (**C**).
You should get an error saying the wallet is already in the app. 

- In such case, you can safely proceed to delete the wallet and restore it (remember, only in case you have only one wallet). Proceed to (**B**)
- If you do not get an error (and you have only one wallet), then the recovery phrase that you have does not belong to the wallet you want to restore. Proceed to (**D**)

ii) **IF YOU HAVE MORE THAN ONE WALLET IN THE APP**

- Install BitPay app (If you use Copay, install BitPay. If you use BitPay, install Copay)

Install the Copay app from the [App Store (iOS)](https://itunes.apple.com/us/app/bitpay-secure-bitcoin-wallet/id1149581638) or [Google Play Store (Android)](https://play.google.com/store/apps/details?id=com.bitpay.wallet). If you are using the wallet on a desktop computer, you can download the most recent version of the Copay wallet [here](https://bitpay.com/wallet).

- Import the wallet ( follow steps on **C**)
- Check the wallet imported is the one you want to restore. In case it is, you can safely proceed to (**B**), if not, proceed to (**D**).

**B)** Delete the wallet

- Open the BitPay wallet
- Select the wallet 
- Tap the upper right corner icon (Preferences)
- Scroll down and tap **Delete Wallet** > **Delete**

Then proceed to **C**

**C) Import/Restore**

Please see the following [article](https://support.bitpay.com/hc/en-us/articles/115003028346
wallet-from-Copay-to-BitPay-) for steps on how to restore the wallet from a backup.

Here is a [video](https://www.youtube.com/watch?v=U23E-dZEuYs&t=1s) from our support channel for a clearer explanation.

To import the wallet on another device, you can click the **+** next to Wallets and then choose **Import wallet**. Enter the 12-word recovery phrase and you will now have access to the wallet from both devices.

Please see the following [article](https://support.bitpay.com/hc/en-us/articles/115003004363-I-lost-my-wallet-or-changed-my-phone-What-can-I-do-to-restore-my-wallet-) for steps on restoring your wallet using the recovery phrase.

**If you are experiencing an issue, here are some things that you can check:**

- Are you sure that the recovery phrase was written in the correct order?
- Did you use all lowercase letters and no punctuation?
- Did you add a password to your recovery phrase?
- [Do you have the QR code or text/file backup?](https://support.bitpay.com/hc/en-us/articles/115003004363-I-lost-my-wallet-or-changed-my-phone-What-can-I-do-to-restore-my-wallet-)
- Did you separate each word with a single space (no commas or any other punctuation)?

Also make sure:
**- Your phone is not using capitals for the first letter of the words**

**- You are not typing spaces:**

- before the first word
- more than one space between words
- After the last word

Please also ensure that your words are all contained in the following [list of possible words](https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt) (in English).

For other languages click [here](https://github.com/bitcoin/bips/blob/master/bip-0039)

**D)** We recommend you look for other recovery phrases (12-word recovery phrases) that you might have and try to restore the wallet.
If you do not have the recovery phrase for that wallet, unfortunately, there is no way to recover it, however, we recommend not to uninstall the wallet nor to delete the wallet, so in case you find the recovery phrase, you can restore it.

**Bear in mind**

**There is no account or password for the BitPay wallet. Please see the following [article](https://support.bitpay.com/hc/en-us/articles/115002989283-Why-don-t-I-have-an-online-account-for-my-BitPay-wallet-).**

**BitPay does not store your private keys or have access to your funds. The BitPay wallet secures your Bitcoin and Bitcoin Cash **only** on your device. To restore your wallet if your device is lost or stolen, you must save the 12-word backup phrase that you receive when you create a wallet. BitPay will not be able to recover your funds.**

**Comment by Hillsongnit** [comment]
If you lost your wallet pass and you need help to get it back with all of your crypto intact hire B I T C O I N R E C O V E R Y  at  Consultant Com, a recovery expert also provides services that involves crypto trading and investment management guides with 100% professionalism is their virtue.
