### ISSUE TITLE
Amazon giftcard blocked

### ISSUE THREAD

**Issue by nevuillu** [bitpay/copay#9294]
Hi. I'm use a Google translate.

Good afternoon. A warm greeting from Venezuela. I write to you because about 8 months ago, I created an Amazon giftcard but Amazon blocked my account and asked me for a verification of funds by fax, something they never answered me. Is there a possibility of reversing that? I am writing to you at this point because I was just informed of this. even in copay tells me to redeem or that I have already used the card. Those options go there. Is there a possibility to do something? Many thanks!

**Comment by BGalliotti** [comment]
Hello @nevuillu 
Thanks for reaching out to us.

We understand your inquiry.

Please write to the Bitpay support: https://help.bitpay.com/requestHelp
Our representatives are going to address your inquiry there.

We would appreciate your patience.

Thanks in advance, Kind regards.
