### ISSUE TITLE
Senha criptografada

### ISSUE THREAD

**Issue by startkiller** [bitpay/copay#9301]
I was tring to send my BTCs from the wallet copay to another wallet, but it asks for an encrypted password, which I do not remember having created.
Now I need to move my BTCs and I'm stuck.

Note: I have the backup password

**Comment by startkiller** [comment]
solved by trying on the bitpay app.

copay still not working, but now it's fine for me.

**Comment by BGalliotti** [comment]
Hello @startkiller 
Thanks for reaching out to us.

We are glad you could solve the issue.
The workaround for the password is to delete the wallet and re-import it by using the 12-word recovery phrase, which is probably what you have done with BitPay.

For this issue please refer to #9292

We appreciate your feedback.
Kind regards.
