### ISSUE TITLE
Android version just hangout after the last update 

### ISSUE THREAD

**Issue by pinhopro** [bitpay/copay#9302]
Hi, 

My android auto updated the copay to the latest version 5.0.7 automatically, and now my copay just hangs on the opening splash screen. 

Previous version worked fine. 

I also found a lot of people with the same problems commenting on google play store. 

Not sure what caused this, but I would love to understand what happened and if you guys could fix this. 

Thanks
Rodrigo

**Comment by gabrielbazan7** [comment]
Hi! yes, there is a new version on the way should be available in the stores soon.

**Comment by pinhopro** [comment]
Thanks for the prompt response. 

Do you think the update will be available tomorrow?

**Comment by gabrielbazan7** [comment]
Yes

**Comment by BGalliotti** [comment]
Hello @pinhopro 
Thanks for reaching out to us.

The app is already available on [Google PlayStore](https://play.google.com/store/apps/details?id=com.bitpay.copay)

Please let us know if you have any additional questions.
Kind regards.
