### ISSUE TITLE
Confirming...

### ISSUE THREAD

**Issue by oldspace44** [bitpay/copay#9319]
I sent 0.022 BTс to the exchange, and after that I wanted to send the rest of the money for exchange, but they turned out to be blocked. But I did not do anything with them. What reason ?
![1](https://user-images.githubusercontent.com/45183412/48736181-94864d80-ec18-11e8-8059-716b303362bb.png)
![2](https://user-images.githubusercontent.com/45183412/48736205-a36d0000-ec18-11e8-83ec-cf8fbe4f1747.png)

**Comment by oldspace44** [comment]
and my transaction of 0.022 - unconfirmed

**Comment by BGalliotti** [comment]
Hello @oldspace44 
Thanks for reaching out to us.

As you can see it says **Locked 0.00 BTC** then there are no locked funds.
Also, there is a clock on the left side of your funds, that means the funds are still pending confirmation.

Even if you had the **Use unconfirmed funds** option enabled, you will not be able to pay invoices with unconfirmed funds, in case you had experienced an issue in relation to that.

So, if you want to pay an invoice (moving funds to an exchange many times work like that) you will have to wait until the funds are confirmed.

Please let us know if you have any additional questions.
Kind regards.
