### ISSUE TITLE
Stuck at splash screen v5.1.1 on Android 5.1.1

### ISSUE THREAD

**Issue by JulianTosh** [bitpay/copay#9320]
Wallet hardware is Samsung SM-T330NU with Android 5.1.1.

Copay Version 5.1.1(updated on 2018-11-16).

Opening app results in an eternal splash screen.

**Comment by gabrielbazan7** [comment]
Hi Julian, sorry about that. Did you try installing BitPay app or reinstalling Copay? Did you see any popup with an error?

**Comment by JulianTosh** [comment]
I upgraded to the latest in the android app store. After it finished upgrading, I opened the app and it stuck on the splash screen.

I tried force quitting the app, then deleting the apps' cache (not data). Same result: freezes at the splash screen.

**Comment by JulianTosh** [comment]
To clarify, this device was running an older version of Copay (don't remember the version). I don't use it very often so it was out of date. I let the play store update the app to the latest version of Copay available.

I have not ever used the BitPay app.
