### ISSUE TITLE
Sending...

### ISSUE THREAD

**Issue by owaewa** [bitpay/copay#9321]
f105c6d7344f1fad129fd7ae588b04c83dc34445b124ff3a6e89a40249cd3d82

Not going for two days

**Comment by BGalliotti** [comment]
Hello @owaewa  
Thanks for reaching out to us.

The transaction is still unconfirmed: https://blockchair.com/bitcoin/transaction/f105c6d7344f1fad129fd7ae588b04c83dc34445b124ff3a6e89a40249cd3d82

That is not something we can change.
Please refer to [this](https://github.com/bitpay/copay/issues/8712#issuecomment-392816250) post for more in-depth information.

Please let us know if you have any additional questions.
Kind regards.
