### ISSUE TITLE
Bitcoins purchase problem

### ISSUE THREAD

**Issue by Alexandregr13** [bitpay/copay#9322]
First of all, I apologize for the mistakes. I am French.
I recently purchased 100 euros worth of Bitcoins from your  partner site: ZeBitcoin.
So I created a wallet and filled in the address you gave me when I paid. The payment has been made see blockchain: https://bitcoin.zeblockchain.com/address/179i23otgBHKGaAGFenUHWpSWKuBbCgCJ6
 However, it has now been more than 20 hours and the Bitcoins still do not appear on my account.

![img_2977](https://user-images.githubusercontent.com/45198186/48766805-b0e4c180-ecce-11e8-99bf-a2ae1f4188e8.PNG)
![img_2978](https://user-images.githubusercontent.com/45198186/48766820-b80bcf80-ecce-11e8-8b6a-919e6b7d20d1.PNG)

I let you my email adresse : alexandregrondin7@gmail.com

**Comment by Alexandregr13** [comment]
Hello, I managed to solve the sorry problem of the inconvenience.

**Comment by BGalliotti** [comment]
Hello @Alexandregr13 

**We are glad you were able to solve the issue!**

Sometimes the confirmation takes a while depending on the network and fees used on the transaction.
As a suggestion, you can refresh the wallet cache whenever that happens. To know how to do so, click [here](https://github.com/bitpay/copay/issues/8806#issuecomment-399074701).

We are going to close the ticket.
Feel free to open a new one in case you have any questions or concerns.

**Thank you for your interest and support!**
