### ISSUE TITLE
I bought an Amazon gift card and the code did not arrive

### ISSUE THREAD

**Issue by jadfj09** [bitpay/copay#9324]
I bought an 75$ Amazon gift card and the code did not arrive. Copay deducted the BTC from my account. showed a message that said "waiting for payment confirmation" 
but the code does not appear in the list next to the others

**Comment by BGalliotti** [comment]
Hello @jadfj09 
Thanks for reaching out to us.

Please write to the Bitpay support: https://help.bitpay.com/requestHelp
Our representatives are going to address your inquiry there.

We would appreciate your patience.

Thanks in advance, Kind regards.
