### ISSUE TITLE
Cannot access my coins

### ISSUE THREAD

**Issue by abhi0497** [bitpay/copay#9326]
I'm getting error in my copay bitcoin wallet in both Windows and android, it says "could not update wallet : WALLET_NEED_SCAN: wallet needs addresses scan. Tap to retry "
When i even trying to recover my wallet it is showing same error

**Comment by PsychoSterope** [comment]
I have this same exact error on all of my devices now. I have tried the recovery instructions, but nothing is helping. 

Any other suggestions Devs?

**Comment by abhi0497** [comment]
Fixed
