### ISSUE TITLE
Cannot install the bitpay new desktop platform

### ISSUE THREAD

**Issue by hassen007** [bitpay/copay#9329]
I tried to install the new desktop platform but i failed, i use windows 7

**Comment by BGalliotti** [comment]
Hello @hassen007 
Thanks for reaching out to us.

The new Copay version requires Windows 10 version 14316.0 or higher, that is why it is not working for you.

Remember you can still use the app on mobile platforms.

Please let us know if you have any additional questions.
Kind regards.
