### ISSUE TITLE
New desktop platform announcement. Windows 10 required

### ISSUE THREAD

**Issue by yunesj** [bitpay/copay#9331]
Is there a place where I can read about the new desktop platform?

If the GitHub source code and released binaries are for the legacy version, does that mean the new desktop platform is closed source?

If that's not the case, how can I verify that the release in the App Store matches the GitHub source?

**Comment by MrsMasternode** [comment]
I have windows 8.1 pro, cannot get update req windows 10 ... stupid
<img width="869" alt="bitpay10req" src="https://user-images.githubusercontent.com/39469558/48979814-1c8fab80-f08e-11e8-94cd-5a8c55e9047c.PNG">

**Comment by BGalliotti** [comment]
Hello @MrsMasternode 
Thanks for reaching out to us.

The new Windows app requires Windows 10 as you can see it [here](https://www.microsoft.com/en-us/p/bitpay-for-windows/9nbr15sk4zjv?activetab=pivot:regionofsystemrequirementstab).

Please let us know if you have any additional questions.
Kind regards.

**Comment by yunesj** [comment]
Hi @BGalliotti, it seems that @MrsMasternode hijacked this ticket to make an unrelated complaint.

Your answer does not address my original question, which was not about Windows 10. Would you please remove "Windows 10" from the title and remove the "Answered" flair?

Thanks!

**Comment by cmgustavo** [comment]
> If that's not the case, how can I verify that the release in the App Store matches the GitHub source?

Go to "Settings" -> "About" and check that the version and commit match with this https://github.com/bitpay/copay/releases

**Comment by yunesj** [comment]
> check that the version and commit match

Hi @cmgustavo, I meant to ask how we can verify that the released code matches the open source. Obviously, any bad actor could release some compromised software that puts anything in the "About" screen. And, it seems important that verification should not depend on running the app!

The attack that I am concerned about is a bad copay employee, someone with copay's Apple's login credentials, Apple, or anyone else down the distribution chain makes a small modification to the code that sends private keys to the bad actor, thereby giving the bad actor control over all funds held in all Copay wallets.

**Comment by yunesj** [comment]
Given the recent security oversights related to the build process, is there any update about this?

**Comment by BGalliotti** [comment]
Hello @yunesj 
Thank you for reaching out to us.

The building process is always supervised and signed by trusted people and the code is reviewed by this people and the community.
Other than that, the apps are reviewed by the corresponding app stores before reaching the end user, so the overall process is safe and secure.

Kind regards.

**Comment by yunesj** [comment]
> The building process is always supervised ... by trusted people

Hi @BGalliotti ,

It doesn't seem that there's any way to verify that the app run on the iPhone is the same as the code in GitHub.

It seems like our only option is to trust these "trusted people" not to

1. run away with all of the money that passes through the BitPay wallets, and
2. never make a mistake in the build process (again)

Don't you think you're asking people to put a lot of faith in an unknown number of unknown people?

Don't you agree that this is an area for improvement?

The BitPay wallet is still my favorite, because of it's 2FA/multisig implementation, but it seems like BitPay is rolling back security for no good reason (due to this example and the deprecation of wallet passcodes).

Thanks.

**Comment by matiu** [comment]
Hi @yunesj


You can download the code and compiled yourself. Or download the signed binaries (from the app store)  In the later case you sre trusting the signed and the app store. Unfortunately thise are the only options. If you have any alternative delivery method to suggest we will be happy to consider it. Thanks.
