### ISSUE TITLE
Cannot launch BitPay (Snap) on Fedora 29

### ISSUE THREAD

**Issue by xenog** [bitpay/copay#9333]
On Fedora 29, the BitPay wallet app installed via Snap doesn't launch. When running on command-line with the `bitpay` command, it exists immediately with status 1 without error messages.

**Comment by brainscar** [comment]
I think it's because Wayland is default on Fedora 29:


https://github.com/bitpay/copay/issues/9439

**Comment by xenog** [comment]
I'm no longer using Fedora 29.
