### ISSUE TITLE
Amazon Gift Card Problem

### ISSUE THREAD

**Issue by sezbladex** [bitpay/copay#9334]
I am using coinbase i sent btc to my bitpay wallet for buy amazon gift card. I bought 98 USD Amazon gift card but I cant get any code and bitpay app stop working. I reset my phone i try everything i cant use your app. I looked my mail i got invoice but where is my amazon gift card code ? I delete app and reinstall it works i can use app but i forget my restore code. Its really bullshit I sent support mail I tell this and I sent my bitpay btc adress. I just want to my amazon gift card.

**Comment by BGalliotti** [comment]
Hello @sezbladex 

Have you received the redeem code?

Please let us know if you have any additional questions.
Kind regards.
