### ISSUE TITLE
npm package 'event-stream' pulls in malware

### ISSUE THREAD

**Issue by PrecociouslyDigital** [bitpay/copay#9347]
Recently, control of the package event-stream was given to @right9ctrl, who injected malware into the package (see https://github.com/dominictarr/event-stream/issues/116 for details). Just now, contributors analyzing the injected code have found that it specifically targets copay, based on its package description.

**Comment by scottrobertson** [comment]
https://github.com/bitpay/copay/issues/9346

**Comment by PrecociouslyDigital** [comment]
Dupe of #9346
