### ISSUE TITLE
did any other libs hacked like "event-stream"? should we check all the libs now?

### ISSUE THREAD

**Issue by daffy6537** [bitpay/copay#9349]
did any other libs hacked like "event-stream"? should we check all the libs now?

**Comment by sartaj** [comment]
OSS should be treated with a no trust mentality when dealing with sensitive data. Strict Content Security Policies can prevent hacks that steal data and thorough E2E/unit tests can prevent hacks that mess with UX.

**Comment by lmcarreiro** [comment]
Maybe just add a white list of servers instead of allow any server: https://github.com/bitpay/copay/blob/72a9e176c12c77b5dfc4590c88de73f28fa301b7/app-template/config-template.xml#L121

**Comment by matiu** [comment]
We are checking them now, and also restricting network access from the app. thanks.
