### ISSUE TITLE
No 5.2.0 Copay version in App Store

### ISSUE THREAD

**Issue by mshanx** [bitpay/copay#9350]
Hello. In your official release you mentioned that it's important to upgrade the software however there is only 5.1.0 version available in App Store and even after refreshing and waiting for several hours didn't help. The new version is not available. Can you tell us when approximately it's going to be available in App Store?

**Comment by stevenodb** [comment]
Furthermore, should I be worried if I only use Copay on iOS? The sandboxed environment should protect Copay’s files, right?

**Comment by kanamachi** [comment]
Hello ,I use android.
Please tell me how can get upload no5.2.0 bitpay/copay.


2018年11月28日(水) 7:26、SweetPPro さん（notifications@github.com）のメッセージ:

**Comment by BGalliotti** [comment]
Hello @kanamachi 
Thanks for reaching out to us.

- For Windows click [here](https://www.microsoft.com/en-us/p/bitpay-for-windows/9nbr15sk4zjv?activetab=pivot%3Aoverviewtab).
- For Android click [here](https://play.google.com/store/apps/details?id=com.bitpay.wallet).
   For Coppay on Android clikck [here](https://itunes.apple.com/ar/app/copay-bitcoin-wallet/id951330296?mt=8)
- For Linux click [here](https://snapcraft.io/bitpay)
- [Mac OS](https://itunes.apple.com/us/app/bitpay/id1440200291?ls=1&mt=12)
- [iOS](https://itunes.apple.com/us/app/bitpay-secure-bitcoin-wallet/id1149581638?mt=8)

@mshanx The relevant update is **5.2.2** and is already released.
Some platforms as iOS are taking more than expected to be approved by the respective market and should be available shortly. (Bitpay App)

Please let us know if you have any additional questions.
Kind regards.

**Comment by BGalliotti** [comment]
@mercurytoxic Thanks!

Fixed 👍 

Kind regards.

**Comment by mercurytoxic** [comment]
There's still no mention of Android or a link to an apk or Google play store in the new "Copay on Android" link.

**Comment by a198d22** [comment]
ต้องทำอย่างไรบ้างครับ ทำไม่เป็นครับ

เมื่อ 28 ม.ค. 2019 1:23 หลังเที่ยง "Luis Aranguren" <
notifications@github.com> เขียนว่า
