### ISSUE TITLE
Didn't Receive Amazon Gift Card Code!

### ISSUE THREAD

**Issue by komswtw** [bitpay/copay#9354]
Hey there, i bought amazon gift card from you which is $88.65 but i didnt receive any amazon code 
and the gift card not showing up over my bitpay wallet!!!

Wallet ID is : d957dbf8-9a7d-4114-b114-201365733e3d
Version is : v5.1.0
Transaction ID: cea4661e5df495372a630bdba7ef20ba1f1153e162c51a0875b26958be5567b3
Link on BitPay insight: https://insight.bitpay.com/tx/cea4661e5df495372a630bdba7ef20ba1f1153e162c51a0875b26958be5567b3

**Comment by BGalliotti** [comment]
Hello @komswtw 
Thanks for reaching out to us.

Please write to the Bitpay support: https://help.bitpay.com/requestHelp
Our representatives are going to address your inquiry there.

We would appreciate your patience.

Thanks in advance, Kind regards.
