### ISSUE TITLE
How to convert Bitpay xPrivKey to private key

### ISSUE THREAD

**Issue by namjungsoo** [bitpay/copay#9355]
Network: BCH testnet
Client: bitcoin-abc-0.18/bin/bitcoind and bitcoin-cli

I want to convert xPrivKey which is from exported Bitpay wallet file to private key for using `bitcoin-cli importprivkey`

Thank you.

**Comment by matiu** [comment]
I don't think that is possible.

I sugest you move you coins to a new bitcoin-cli wallet.
