### ISSUE TITLE
Incorrect balance calculation

### ISSUE THREAD

**Issue by monsterbitar** [bitpay/copay#9356]
As of the BCH/BSV split I tried to separate my coins by making a new 1-of-1 wallet, to which I sent a dust-tx that is only valid on the ABC side. I then moved all my funds to it, and moves some funds back to savings, after which I realized that I should've moved *all* instead.

Simple misstake, I just sent it back to the splitter address, then sent all to a spendings wallet, then the savings value back to the savings wallet. The split worked out fine, so I removed the splitter wallet, but now copay now shows an incorrect balance for my savings and spendings wallets.

Example:

I had X on my savings wallet, I sent all X out twice, and received the full X back twice, so should still have X. Instead it says I have 2X.

The spending wallet had Y, sent Y to the splitter wallet, then got X+Y sent to back to it. It then sent X to the savings wallet and expected result is that it shows Y left in the wallet, but instead it shows Y+(X+Y).

**Comment by matiu** [comment]
Hi,
In order to help you with this issue, we will need to check the affected addresses in particular.
 Could you please contact us directly:  support@bitpay.com?

thanks!
matías
