### ISSUE TITLE
no puedo enviar btc

### ISSUE THREAD

**Issue by nahuel1981** [bitpay/copay#9391]

**Comment by nahuel1981** [comment]
quiero enviar btc a una wallet electrum pero no logro hacerlo. pongo enviar, luego la direccion de destino, pero no tengo opcion de seguir avanzando con la operacion, no tengo donde poner el monto ni nada. tengo la app de la tienda de windows 10

**Comment by BGalliotti** [comment]
Hola @nahuel1981 ,

Lamentamos el inconveniente que esta experimentando.

Podria por favor enviarnos capturas de pantalla de la pantalla de pago?

Esperamos su respuesta.
Saludos cordiales.

**Comment by orangecstsne04** [comment]
? Como"¿

Sent from Yahoo Mail on Android 
 
  On Sun, Dec 9, 2018 at 9:12 AM, nahuel1981<notifications@github.com> wrote:   
quiero enviar btc a una wallet electrum pero no logro hacerlo. pongo enviar, luego la direccion de destino, pero no tengo opcion de seguir avanzando con la operacion, no tengo donde poner el monto ni nada. tengo la app de la tienda de windows 10

**Comment by BGalliotti** [comment]
Hola @ nahuel1981

**¡No hemos tenido noticias tuyas desde hace tiempo!**

**¿Sigues experimentando un problema?**
Vamos a cerrar esta conversación, por favor, si necesita más ayuda, abra un nuevo issue que explique el problema en detalle, brindando toda la información relevante posible, estaremos encantados de ayudarle :)

Saludos cordiales.

**Comment by toxicayon** [comment]
Tampoco puedo enviar BTC, quiero enviar para recargar skrill o neteller que son monederos electrónicos y no me deja, dice que que no tengo los fondos suficiente, probe enviando montos menores pero todavia no me deja
