### ISSUE TITLE
Particl Support

### ISSUE THREAD

**Issue by spazzymoto** [bitpay/copay#9397]
Hey guys,

I am part of the [Particl Project](https://particl.io/) and have been tasked with updating our fork of the copay wallet to the latest version.

I though i would reach out to you guys and ask if you would accept a pull request to add Particl to the actual Copay wallet as an additional coin, much like Bitcoin Cash was added. I thought we could use the _enabledExtensions to only show Particl in the Copay version of the app.

This would mean adding bitcore-lib-particl to the various support libraries BWC, BWS as well. 

If this is not something you guys would be interested in feel free to close this issue.

Thank you for your time.
Regards
Rob

**Comment by matiu** [comment]
Hi, 

thanks for reaching out. We are not interested at this moment in adding Particl support. thanks.
matías
