### ISSUE TITLE
HELP! Blockchain says transaction doesn’t exist

### ISSUE THREAD

**Issue by jesuswalks2011** [bitpay/copay#9405]
Just sent bitcoin received in trade on localbitcoins to wallet and it’s been over an hour with no pending deposit notification. When I searched the transaction ID on blockchain it said no such transaction exists. HELP!

**Comment by orangecstsne04** [comment]
What does that mean?
Sent from Yahoo Mail on Android 
 
  On Thu, Dec 13, 2018 at 9:21 AM, jesuswalks2011<notifications@github.com> wrote:   
Just sent bitcoin received in trade on localbitcoins to wallet and it’s been over an hour with no pending deposit notification. When I searched the transaction ID on blockchain it said no such transaction exists. HELP!

**Comment by BGalliotti** [comment]
Hello @jesuswalks2011 
Thanks for reaching out to us.

- **Please send us the transaction hash / ID is a alphanumeric chain like this: **d0a23876de7cf87574b5cda7557bcc8af5d84f3fd1e6f4c6063fd6b72b0e69ae**

**We look forward to hearing from you.**

**Comment by BGalliotti** [comment]
Hello @jesuswalks2011 

**We have not heard from you in while!**

**Are you still experiencing an issue?**

We are going to close this thread, please if you need further help, open a new one explaining the issue in detail, providing all the relevant information possible, we will be happy to help you :)

Kind regards.
