### ISSUE TITLE
Wallet_Locked: ***Solved***

### ISSUE THREAD

**Issue by alirezaaf** [bitpay/copay#9415]
hi,i wanted to send btc to a wallet address but it give me this error --> wallet is locked
any help?

**Comment by BGalliotti** [comment]
Hello @alirezaaf 
Thanks for reaching out to us.

Are you still experiencing the issue?



Please let us know if you have any additional questions.
Kind regards.

**Comment by Markusdr21** [comment]
I have the same problem can not do anything with my money it is I should enter the encrypted code in the transaction even though I have none

**Comment by BGalliotti** [comment]
Hello @alirezaaf

Thank you for reaching out to us.

**So we can further help, please provide as many of the following details as you can:**

- Current device used: Phone model 
- Current operating system version for the device: iOS, Android..
- Current version of the wallet used: CoPay App > Settings > About CoPay 
- Any log files containing error details: CoPay App > Settings > About CoPay > Session Log > Tap on the Upper right corner (three dots) > Send by email 

- Error screenshot: On [iPhone](https://apple.co/1DAB204) on [Android](https://www.wikihow.tech/Take-Screenshots-on-an-Android)
- Steps to replicate: Steps needed for the error to appear.
- CoPay Wallet ID - To get your Wallet ID, open your CoPay application, then go to `Settings` > [Your wallet] > `More Options` > `Wallet Information`. On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste in your e-mail.

**We look forward to hearing from you.**

**Comment by Amin2110** [comment]
How can i get my wallet

**Comment by BGalliotti** [comment]
Hello @Amin2110 
Thanks for reaching out to us.

> How can i get my wallet

Please open a new issue [here](https://github.com/bitpay/copay/issues) describing clearly what your problem is.

We look forward to hearing from you
