### ISSUE TITLE
Help encryptet code

### ISSUE THREAD

**Issue by Markusdr21** [bitpay/copay#9418]
I can no longer make a transfer it is I have to enter the encrypted code although I have none

**Comment by MrTschi** [comment]
Did you protected your wallet during creation with a password? Did you loose this password?
Do you have a backup (the 12 words) of your wallet?

**Comment by Markusdr21** [comment]
The problem is the is not longer available on google play...

**Comment by MrTschi** [comment]
So please, can you close this issue if you have solved it by your own?

**Comment by BGalliotti** [comment]
Hello @Markusdr21 
Thanks for reaching out to us.

> I can no longer make a transfer it is I have to enter the encrypted code although I have none

Are you talking about the encrypt password?
In such case, please refer to [8532](https://github.com/bitpay/copay/issues/8532#issue-319277251).

> The problem is the is not longer available on google play...

The app is being distributed on [GitHub](https://github.com/bitpay/copay/releases).
