### ISSUE TITLE
Amazon Asking for Gift Card receipt

### ISSUE THREAD

**Issue by AymanBelom** [bitpay/copay#9432]
Hey there, 
I've bought Amazon Gift Card of the app and added it to the account after i placed an order i got an email that they want the receipt of the AGC and i have sent it 
but they are rejecting to open my account again because the Gift Card i got seems violated their terms and i was recommended to contact the point of purchase !!!
![screenshot_3](https://user-images.githubusercontent.com/46269608/50551676-6d964f00-0c8d-11e9-8ff4-f66aa4235939.png)

**Comment by jesskie** [comment]
Hello gud day,I remember that'i try
 to avail but they didn't accept my card

**Comment by jesskie** [comment]
My   card did not reach d price so I did not recieved O.R

**Comment by jesskie** [comment]
I have not recieved any card sir

**Comment by matiu** [comment]
Hi. Please contact support@bitpay.com for question regarding the Gift cards. They will happy to assist you.
