### ISSUE TITLE
i can't see the transaction history in copay wallet 

### ISSUE THREAD

**Issue by ramiali1994** [bitpay/copay#9435]
hello 
i have wallet of BCH i can't see the transaction history in copay wallet !

**Comment by matiu** [comment]
Can you provide more details?  What is the address that belong to the wallet that should have a tx?

**Comment by ramiali1994** [comment]
share wallet with 3 privet key 
HMQaQhJ2fzaTj2MXNHFTHAuc4mPcFbmgvW

**Comment by matiu** [comment]
Hi, that address is not associated to any Copay or Bitpay Wallet on the default backend. Can you share a screenshot of the walletId

**Comment by ramiali1994** [comment]
this is the wallet ID : 6ed14e1d-2c81-4c6e-88e4-3016104ffcff

**Comment by BGalliotti** [comment]
Hello @ramiali1994 
Thanks for reaching out to us.

**Refresh the transaction cache**

    Select your wallet > Tap on the icon in the upper right corner of the screen > Choose "Transaction History" > Choose "Clear Cache" to reset your transaction list.

**Note:** Your wallet will say 'Updating Wallet' until the list has been retrieved.

**Refresh the server's cache.**

    Select your wallet > Tap on the icon in the upper right corner of the screen > Go to "Wallet Addresses" > Choose Scan addresses for funds

**Note:** Your wallet will say 'Scanning Funds' until the addresses have been scanned.

**Please do not uninstall the app or delete the wallet if you did not back it up properly, in such case, please do so. The wallet backup is the only way to recover your wallet.**

**Comment by Nucnay3428** [comment]
Still struggling

**Comment by matiu** [comment]
Can you provide any information about your proble, @Nucnay3428 ?

**Comment by jesskie** [comment]
Yes sir

jesus urbe

**Comment by jesskie** [comment]
Luke a about what sir?

jesus urbe

**Comment by Nucnay3428** [comment]
I'm sorry to bother I'm not sure how to get anywhere with the site I'm struggling to find out what to do

**Comment by BGalliotti** [comment]
Hello @Nucnay3428 
Thanks for reaching out to us.

> I'm sorry to bother I'm not sure how to get anywhere with the site I'm struggling to find out what to do

Please try to explain your issue the most clearly as possible so we can address your inquiry.

 **We look forward to hearing from you.**

**Comment by jesskie** [comment]
BitBounce Notification
[image: BitBounce]



Hello!

I’ve signed up for a cryptocurrency spam solution called BitBounce and I
added you to my “whitelist”. That means you can email me and your emails
will come through.

For people who aren’t on my whilelist, I’m charging $0.05 in Credo for
their email to get to my inbox. A cleaner inbox and more money? Win! You
should check it out!

*Sign up for BitBounce and earn 1 complimentary Credo.*
<https://bitbounce.com?ref=bitbounce>

Unsubscribe
<https://bitbounce.com/unsubscribe_from_whitelist_email_notifications/4283826233>
from Jess Urbe's whitelist notification emails.



*BitBounce* <https://bitbounce.com?ref=bitbounce> is powered by the *Credo*
<https://bitbounce.com/credo> cryptocurrency

*I’m from a business* —  what are my *delivery options*
<https://bitbounce.com/business>

BitBounce and Credo are transacted through *CredoEx*
<https://credoex.com?ref=bitbounce>
Made by Turing Technology Inc. in San Mateo, California *Sign Up for
BitBounce* <https://bitbounce.com?ref=bitbounce>
