### ISSUE TITLE
Please add a dmg installer for mac user, couldn't update using app store in certain countries.

### ISSUE THREAD

**Issue by waveiron** [bitpay/copay#9458]
![image](https://user-images.githubusercontent.com/4930447/50930667-84158500-149b-11e9-937e-a1e32ce6759c.png)

**Comment by waveiron** [comment]
I could only use outdated chrome copay app on macos right now.

**Comment by waveiron** [comment]
I found an outdated dmg release (v4.8.1) and its update link leads to 404.

![image](https://user-images.githubusercontent.com/4930447/50930844-ff773680-149b-11e9-81d6-23f5fb1d9eef.png)

![image](https://user-images.githubusercontent.com/4930447/50931036-7f9d9c00-149c-11e9-9a0d-923d41ec4055.png)

**Comment by waveiron** [comment]
It's going to be a BIG help to add a standalone dmg in each release.

**Comment by FranklinYu** [comment]
Which country was it?

**Comment by BGalliotti** [comment]
Hello @waveiron 

Unfortunately, if the country is banned, it is not going to work.

Kind regards.
