### ISSUE TITLE
Não recebi meus btcs

### ISSUE THREAD

**Issue by rodox19** [bitpay/copay#9463]
olá, foi me enviado um valor de 1 btc para a carteira 19Sp4BjW3p6Dsmgg6wZzcpjPf74UDGymm que era minha na copay, mas não chegou, e quando clico para ver minha carteira ela mudou no aplicativo. Por favor me auxiliar. No aguardo de uma resposta.

Att.

**Comment by matiu** [comment]
Hi, the address 19Sp4BjW3p6Dsmgg6wZzcpjPf74UDGymm is not associated with any address hosted by Bitpay Wallets/  Copay. Can you share your wallet id?
