### ISSUE TITLE
Access denied for IP addresses from Vietnam?

### ISSUE THREAD

**Issue by thaolx** [bitpay/copay#9475]
I've tried to use copay from all major ISP in Vietnam. Looks like all IP from Vietnam are filtered. Must be a mistake.
screenshot of https://bws.bitpay.com/bws/api attached.

![bws](https://user-images.githubusercontent.com/25919799/51376516-1c1a0b00-1b3b-11e9-9141-44a9b6882ee3.png)

**Comment by thaolx** [comment]
I've been following bitcoin scene in Vietnam since 2013. Some high ranking officials from State Bank of Vietnam had asked me to consult them privately about bitcoin and cryptocurrency in general. To the best of my knowledge bitcoin is still unregulated in Vietnam. Yes, VND is the only legal tender in Vietnam and it is illegal to list price of commodity publicly in Bitcoin but so is USD and any other foreign currency. Other than that no one has been put on trial for using, trading and mining Bitcoin in Vietnam while some have been put in prison for bitcoin related activities in the US.

I've been using  copay as the main btc/bch wallet for years and helped many install it. IMO it is the best wallet out there. Prevent the whole country from using copay based on essentially nothing is the huge mistake. Please reconsider.

**Comment by BGalliotti** [comment]
Hello @thaolx 
Thanks for reaching out to us.

We appreciate your support. To operate as a bitcoin company we have to comply with rules and regulations, it is not up to us which countries are banned.
If the ban was removed in the future, we will follow it.

You can check that out [here](https://en.wikipedia.org/wiki/Legality_of_bitcoin_by_country_or_territory#Vietnam).

Thanks for your appreciation 
Kind regards.

**Comment by minhng99** [comment]
So can we use VPN to make payment using BitPay?

**Comment by looeee** [comment]
I'm Irish but in Vietnam for some months on business. Does this mean I'm banned from using Bitpay while I'm here, even though my business is Irish and all payments are handled and taxed through Ireland?
