### ISSUE TITLE
Suggestion to add example externalServices.json

### ISSUE THREAD

**Issue by jfbloom22** [bitpay/copay#9479]
Very excited to start building copay from source!  This is awesome!  
One of the first I need to configure is externalServices.json.  However, I can't find an example of this file.  It will take me some time to review the source code and figure out what exactly needs to be setup in this file.  Anyone have an example?  And what do you all think about adding a "example-externalServices.json" file to the repo?

**Comment by matiu** [comment]
externalServices is only for  Bitpay's integrations. You should not need it for building copay. Let us know any problem.
