### ISSUE TITLE
wallet

### ISSUE THREAD

**Issue by kensin18** [bitpay/copay#9480]
my wallet network error ?

**Comment by kensin18** [comment]
https://sv1.uphinhnhanh.com/images/2019/01/19/IMG_1315.png

**Comment by brainscar** [comment]
Are you in Vietnam? (your phone shows Viettel as network)


See: https://github.com/bitpay/copay/issues/9475

**Comment by BGalliotti** [comment]
Hello @kensin18 
Thanks for reaching out to us.

Your error is due to the country you are in. 

You will not be able to operate with bitcoin there.

Please let us know if you have any additional questions.
Kind regards.
