### ISSUE TITLE
Bitpay restricted from Algerian IPs

### ISSUE THREAD

**Issue by 1mish** [bitpay/copay#9481]
Hello,

Access to all bitpay services is restricted for all my devices until i use a VPN.

This includes Bitpay/Copay apps on Windows / iOS bitpay's main website, insight.bitpay.com, and payment invoices urls.

Did you bann Algerian IPs ?

Thank you.

**Comment by 1mish** [comment]
Issue still persists.

**Comment by BGalliotti** [comment]
Hello @1mish 
Thanks for reaching out to us.

Bitcoin is not legal in your country, that is why you are experiencing this issue.

You can check it out [here](https://en.wikipedia.org/wiki/Legality_of_bitcoin_by_country_or_territory#Africa).

Kind regards.
