### ISSUE TITLE
Money sent from coinbase not showing in wallet

### ISSUE THREAD

**Issue by pmh856** [bitpay/copay#9483]
Sent money from coinbase to my copay address and it’s not showing in copay. I’m new to all this and don’t know what I am doing. Please help

**Comment by BGalliotti** [comment]
Hello @pmh856 
Thanks for reaching out to us.

Apologies for the long delay, if you are still experiencing the issue,

- **Please send us the BitPay/Copay Wallet ID and the transaction hash / ID or the link so we can further investigate and address your inquiry.**

- To get your Wallet ID, open your Copay/BitPay application, then go to `Settings` > [Your wallet] > `More Options` > `Wallet Information`. 
On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste it in your e-mail. 
You can do the same on your computer by clicking on the wallet ID.

- The transaction hash / ID is a alphanumeric chain like this: **d0a23876de7cf87574b5cda7557bcc8af5d84f3fd1e6f4c6063fd6b72b0e69ae**

**We look forward to hearing from you.**
