### ISSUE TITLE
system error

### ISSUE THREAD

**Issue by Doublef1000** [bitpay/copay#9492]
hi
December 14th of last year i sent 1776 thethers from my tether wallet to my bitcoin copay address. At the time the 1776 thethers were worth 1800 usd however when mined and received in my wallet I only received 0.5usd. I have tried for a year to retrieve the funds is there anyway I can get my money back please thank you

**Comment by BGalliotti** [comment]
Hello, 
The BitPay/Copay wallets only support Bitcoin and Bitcoin Cash. BitPay cannot directly assist with recovering non-supported funds.

If you sent USDT (Tether) to your Bitcoin wallet, you might be able to recover these funds by importing your wallet's private key into another wallet which supports USDT (such as Omniwallet). 
To import your private key:

1. Export and decrypt your BitPay/Copay private key:

* Open the BitPay App > Select your BTC wallet > Go to Preferences (Top right corner) > Scroll down to the Advanced section > Export 

* Enter a password of your choice (this password will be used to decrypt the private key) then copy the private key to your clipboard or send it to your personal email. 

* 

Go to https://bitwiseshiftleft.github.io/sjcl/demo/. 
Paste the private key into the Ciphertext area, then enter the password you have set in your wallet in the Password field.

* Click on the Decrypt arrow.

* The Plaintext area should now display your extended private key (xPrivKey). 

WARNING: Your extended private keys are all that anyone needs to access your bitcoin funds. Be sure to protect your private keys and store them only on secure devices. BitPay does not have access to your keys, so you alone are responsible for them. **If you share private key access with external services, including your email or internet service provider, you take responsibility for the risk of theft or breach.** Only advanced users should handle extended private keys.

2. Import your private key into Omniwallet by following the steps outlined in [Omniwallet’s help article](https://github.com/OmniLayer/omniwallet/wiki/Importing-a-Private-Key-into-Omniwallet.org)

**Please contact Omniwallet's support team if you are having trouble importing your private key or recovering the funds.**
