### ISSUE TITLE
No record/activity of sent bitcoin. No receive bitcoin

### ISSUE THREAD

**Issue by ghost** [bitpay/copay#9497]

**Comment by BGalliotti** [comment]
Hello 

Thanks for reaching out to us.

We are sorry you have had this bad experience.

- **Please send us the following information so we can further investigate and address your inquiry.**

- Wallet ID

To get your Wallet ID:
- Open the BitPay application
- Select the wallet
- Tap **Preferences** (top right icon)
- Scroll down and tap **Wallet Information**

On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste it in your post.
You can do the same on your computer by clicking on the wallet ID.

- **Transaction hash / ID or the transaction link**

The transaction hash / ID is a alphanumeric chain like this: **d0a23876de7cf87574b5cda7557bcc8af5d84f3fd1e6f4c6063fd6b72b0e69ae**
