### ISSUE TITLE
No record/activity of sent bitcoin. No receive bitcoin

### ISSUE THREAD

**Issue by jambow** [bitpay/copay#9498]
Greetings

0.048 Bitcoin was sent to a wallet that never received the bitcoin + there is no transaction history recorded in the copay wallet activity and the bitcoin has gone from the copay wallet. I sent and received two smaller transactions afterward one to the same address as it was not used by the 0.048 transaction and they worked fine.

If U could help
Thanx

![screenshot 77](https://user-images.githubusercontent.com/47216543/52061261-a477c180-25b9-11e9-9184-3164e84b5c64.png)

**Comment by BGalliotti** [comment]
Hello @jambow 
Thanks for reaching out to us.

Please write to the Bitpay support: https://help.bitpay.com/requestHelp
Our representatives are going to address your inquiry there.

We would appreciate your patience.

Thanks in advance, Kind regards.
