### ISSUE TITLE
Lost funds in Wallet 

### ISSUE THREAD

**Issue by mhog91** [bitpay/copay#9515]
I tried to send some bitcoin to Coinbase but had forgot my encrypt password.  I recovered my wallet using my 12 word phrase to set a new one but my coins are now gone.  How do I recover them?

**Comment by mhog91** [comment]
I have the address the funds were sent to in my wallet but it is not showing when I try to “recover funds” in the app

**Comment by BGalliotti** [comment]
Hello @mhog91 

**We have not heard from you in while!**

**Are you still experiencing an issue?**

Kind regards.
