### ISSUE TITLE
No me aparece un pago

### ISSUE THREAD

**Issue by jordimen03** [bitpay/copay#9517]
E recibido email de confirmacion de un pago a la billetera de 0’003371 con id trasaccion 

7ce4f1645ac6ff714773a730e7021130cedb7236ba119d6cdc72595e298e4778

Y no me aparece reflejado

**Comment by BGalliotti** [comment]
Hola
Gracias por ponerse en contacto con nosotros.

La transacción está confirmada, por favor haga un refresco de su billetera.

Siga las instrucciones del post #8657 

Por favor, háganos saber si tiene alguna pregunta adicional.
Saludos cordiales.

**Comment by jordimen03** [comment]
Hola ya lo e hecho y sigue sin aparecer

**Comment by BGalliotti** [comment]
Hola @jordimen03 

Es posible que la transacción haya ido a otra billetera. 
Por favor chequee la dirección de destino para ver si recibió los fondos.

Para hacerlo ingrese la dirección en la que debería haber recibido los fondos aquí:

https://insight.bitcore.io 

Si necesita que investiguemos en profundidad, vamos a necesitar la dirección de destino.
Saludos cordiales.

**Comment by jordimen03** [comment]
Lo acabo de comprobar y es correcta la direccion os paso la direccion

13Sqw8TuXxncMJskaVcAJ4L2NZLyttMW57

**Comment by BGalliotti** [comment]
Hola @jordimen03 
Gracias por ponerse en contacto con nosotros.

Hemos verificado los datos y los fondos llegaron a una billetera de BitPay/Copay.

Por favor refresque la billetera nuevamente, si no logra ver la transaccion, contacte al soporte de bitpay (https://help.bitpay.com/requestHelp) enviando sus datos:

- ID de transaccion 
- ID de billetera.

Saludos cordiales.
