### ISSUE TITLE
Transaction not Found

### ISSUE THREAD

**Issue by Pescad0res** [bitpay/copay#9518]
I ve received a few dollars in my copay wallet 18 hours ago. It is not confirmed untill now and when i check it on insight thiss message appears " Transaction not Found"  i need some help here

**Comment by BGalliotti** [comment]
- **Please send us the transaction hash / ID or the link so we can further investigate and address your inquiry.**

- The transaction hash / ID is a alphanumeric chain like this: **d0a23876de7cf87574b5cda7557bcc8af5d84f3fd1e6f4c6063fd6b72b0e69ae**

**We look forward to hearing from you.**

**Comment by Pescad0res** [comment]
this is it : 48df8314e7a31b9e2dfa067551a82a98318a40aeebfc508dfec52eb11b67f70e

**Comment by BGalliotti** [comment]
Hello @Pescad0res 
Thanks for reaching out to us.

We have checked the transaction, it is properly confirmed and has reached a Copay/bitpay wallet.
If you were not seeing the transaction in the wallet, please refresh it as described in #8657 

If that does not work, please write to the Bitpay support: https://help.bitpay.com/requestHelp
Our representatives are going to address your inquiry there.

Kind regards.
