### ISSUE TITLE
Please tell me the way to restore my copay wallet

### ISSUE THREAD

**Issue by yhayasaka001** [bitpay/copay#9519]
Dear,copay support stuff

My name is HAYASAKA from JAPAN.
I could not open my wallet since 1 month ago.
Then I tried to restore my copay wallet by making new copay wallet and restore my wallet.
But firstly could not make new copay wallet and rstore my wallet.
Please tell me the way to restore my copay wallet.
Thank you

**Comment by BGalliotti** [comment]
Hello @yhayasaka001 
Thanks for reaching out to us.

Please refer to #8532 

Please let us know if you have any additional questions.
Kind regards.

**Comment by yhayasaka001** [comment]
Dear support team

My name HAYASAKA from JAPAN.
Please tell me the mean of error 403(cannot creat new wallet).
And please tell me the way to deal with this problem.
Thank you]
Hayasaka

**Comment by BGalliotti** [comment]
Hello @yhayasaka001 
Thanks for reaching out to us.

The 403 error is mostly due to the country you are connecting from.

Please refer to #9070 to know what is it about and how to solve it. 

Please let us know if you have any additional questions.
Kind regards.
