### ISSUE TITLE
can not load my bitpay card

### ISSUE THREAD

**Issue by profitboss** [bitpay/copay#9520]
I try to load bitcoin on my card and it just says could not create the invoice.  I called fraud dept. said my card is fine and then I called bitpay and some lady say my act. closed.  I dont know how to fix this, bitpay customer service sucks!

**Comment by BGalliotti** [comment]
Hello @profitboss 
Thanks for reaching out to us.

We do not attend bitpay card related issues.
Please write to the Bitpay support: https://help.bitpay.com/requestHelp
Bitpay representatives are going to address your inquiry there.

We would appreciate your patience.

Thanks in advance, Kind regards.
