### ISSUE TITLE
Online earnings 

### ISSUE THREAD

**Issue by Darla74** [bitpay/copay#9525]
How do I get my online earnings to deposit into my account here?

**Comment by BGalliotti** [comment]
Hello @Darla74 
Thanks for reaching out to us.

Your online earnings have to be either in an exchange or in a wallet.
To know how to move funds **from** our wallet watch this video:
https://www.youtube.com/watch?v=jctgoHSwPM0&t=37s

To know how to move your funds from another wallet app or an exchange, please reach their support.

Please let us know if you have any additional questions.
Kind regards.
