### ISSUE TITLE
Copay/Bitpay wallet fees seem exceedingly high

### ISSUE THREAD

**Issue by crwatkins** [bitpay/copay#9526]
Current **Normal** fee is 80 sat/byte.   No one else's **Priority** fee is even half that on [p2sh.info](https://p2sh.info/dashboard/db/fee-estimation).  Is this intentional or a bug?  

Also in both Copay and Bitpay wallets on iOS and on desktop Mac, **Average confirmation time** is listed as "..." on the Bitcoin Network Fee Policy page.

**Comment by crwatkins** [comment]
A transaction sent using the Bitpay wallet with a custom fee of 2 sat/B was confirmed within an hour.  I realize this is highly anecdotal, but I didn't want to just compare to all the other estimates.

**Comment by crwatkins** [comment]
This may or may not be related to the same issue, but it is related to setting fees:  Since these fees are way too high, I use the "Custom" setting and use 2 sat/B.  Sometimes it works and sometimes it ignores me and continues to send the "Super Economy" rate of 20 sat/B.

In another slightly relate fee bug, the wallet when displaying transaction details listed:
![image](https://user-images.githubusercontent.com/11914193/53042301-f6429780-3453-11e9-9786-3ea036eace85.png)
which is clearly the wrong units.

**Comment by cmgustavo** [comment]
Thanks for reporting. It 's been fixed on this #9535
