### ISSUE TITLE
Recovering wallet after upgrading my iphone

### ISSUE THREAD

**Issue by shrkl** [bitpay/copay#9527]
I have upgraded my phone to iPhone10 and made fitfully backup and restored from the cloud but I don’t see my wallet when I open the Copay

**Comment by BGalliotti** [comment]
Hello @shrkl 
Thanks for reaching out to us.

Please refer to #8532 and pay attention to point **3**.

Please let us know if you have any additional questions.
Kind regards.

**Comment by shrkl** [comment]
Hi

Thank you kindly.

I do have a problem, as I simply upgraded my iphone WITHOUT making special back up phrase.
Since I should have a full back up of my phone in the cloud – can I do that from the back up?

IL

Israel Liberzon MD |
Professor and Department Head
Department of Psychiatry, Texas A&M University Health Science Center
8441 Riverside Pkwy, Clinical Building 1, 1st Floor Suite 1100 | Bryan, TX 77807

ph: 979.436.9151 | liberzon@tamhsc.edu<applewebdata://44CCD050-6B44-4002-83CB-8D5A849C6807/hbriggs@tamhsc.edu>
MAKING WHAT IF POSSIBLE | whatif.tamhsc.edu<http://whatif.tamhsc.edu>

**Comment by BGalliotti** [comment]
Hello @shrkl 
Thanks for reaching out to us.

You can try, we do not exactly if it's going to work.

Please let us know if you have any additional questions.
Kind regards.
