### ISSUE TITLE
Funds havent arrived

### ISSUE THREAD

**Issue by rosso7** [bitpay/copay#9529]
Hi
I havent recieved my bitcoins after 24 hours. Nomally it takes minuts. I Know they have been send but they are not in my copay wallet. What to do?

**Comment by BGalliotti** [comment]
Hello @rosso7 
Thanks for reaching out to us.

- **Please send us the BitPay/Copay Wallet ID and the transaction hash / ID or the link so we can further investigate and address your inquiry.**

- To get your Wallet ID, open your Copay/BitPay application, then go to `Settings` > [Your wallet] > `More Options` > `Wallet Information`. 
On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste it in your e-mail. 
You can do the same on your computer by clicking on the wallet ID.

- The transaction hash / ID is a alphanumeric chain like this: **d0a23876de7cf87574b5cda7557bcc8af5d84f3fd1e6f4c6063fd6b72b0e69ae**

**We look forward to hearing from you.**
Kind regards.

**Comment by sofiarick** [comment]
I was also sent bitcoin it’s going to 24hours now I still haven’t received it

**Comment by sofiarick** [comment]
Please I need response...please..I don’t understand this site

**Comment by BGalliotti** [comment]
Hello @sofiarick  @rosso7 
Thanks for reaching out to us.

To proceed with your issues, we need the information requested previously **[here](https://github.com/bitpay/copay/issues/9529#issuecomment-465618019)**, please answer posting that information so we can move forward.

We look forward to hearing from you.
Kind regards.

**Comment by sofiarick** [comment]
13NbzZPooPHjsvnqgsFCKuAVTDUYDkuzAt

**Comment by BGalliotti** [comment]
Hello @sofiarick 
There are no transactions related to the address [13NbzZPooPHjsvnqgsFCKuAVTDUYDkuzAt](https://insight.bitpay.com/address/13NbzZPooPHjsvnqgsFCKuAVTDUYDkuzAt)

Please let us know if you have any additional questions.

**Comment by mohreza2019** [comment]
1FeEnBfYBmamD9F5kqU3RnoZ1QbRpUBr8H

**Comment by mohreza2019** [comment]
Please payment sent to me more than 12hours now and still not arrived 
1FeEnBfYBmamD9F5kqU3RnoZ1QbRpUBr8H

Please help

**Comment by BGalliotti** [comment]
Hello @mohreza2019 
Thanks for reaching out to us.

All the transactions related to the address 1FeEnBfYBmamD9F5kqU3RnoZ1QbRpUBr8H are confirmed.

If a transaction is taking a while to be confirmed, please refer to #8712 

Kind regards.
