### ISSUE TITLE
Wallet not registered in BWS issue

### ISSUE THREAD

**Issue by wormdz** [bitpay/copay#9531]
hi , in my phone, i can not access my wallet in copay, he shows me this wallet is not registered in bitcore wallet service (bws) donated, please help me got my wallet back

**Comment by BGalliotti** [comment]
Hello @wormdz 
Thanks for reaching out to us.

- Is the wallet showing up in the app?
- When and where (what screen) do you get that message ("wallet is not registered in bitcore wallet service (bws)") ?

We look forward to hearing from you.
Kind regards.

**Comment by wormdz** [comment]
Hello @BGalliotti
thank you to answer me,
    * Is the wallet showing up in the app?
in the app it shows up on this wallet is not saved in bitcore wallet service (bws) 
    * When and where (what screen) do you get that message ("wallet is not registered in bitcore wallet service (bws)") ?
the message ("the wallet is not registered in the Bitmap Wallet Service (BWS)") appeared when I opened my wallet in the application

I would like to recover my satoshi and transfer them to another wallet, I have the code of the 12 word for recovered but I do not find you how, I can get it https://bitpay.github.io/copay-recovery/, but rest blocked

**Comment by BGalliotti** [comment]
Hello @wormdz 
Thanks for reaching out to us.

>  in the app it shows up on this wallet is not saved in bitcore wallet service (bws)

If the wallet shows up in the wallet app, it has to be in BWS.

**Make sure to have your 12-word recovery phrase backed up on a piece of paper.

Please try deleting the wallet and re-importing it, if that does not work, try uninstalling and re-installing the app.

> I would like to recover my satoshi and transfer them to another wallet, I have the code of the 12 word for recovered but I do not find you how, I can get it https://bitpay.github.io/copay-recovery/, but rest blocked

The recovery tool should work for everyone as it is not "affected" by local or international cryptocurrency regulations.

You can use our recovery tool to move your funds. To know how to do it, please refer to #9540 

Please let us know if you have any additional questions.
Kind regards.

**Comment by wormdz** [comment]
Hello @BGalliotti
thank you to answer me,
The recovery tool don't work 
![btc](https://user-images.githubusercontent.com/47779632/53257956-ad951380-36cb-11e9-86ea-c4eb805b07e9.jpg)

she takes too much time, like her, , 
how much time it takes ?
thank you

**Comment by BGalliotti** [comment]
Hello @wormdz 
Thanks for reaching out to us.

The process takes several minutes as it says, depending on the number of addresses your wallet has and the **Gap** value.

Kind regards.

**Comment by wormdz** [comment]
Hello @BGalliotti
thank you to answer me,
does the procedure take more than 48 hour? It's normal ?
![btc](https://user-images.githubusercontent.com/47779632/53285871-80e20a00-3766-11e9-80fa-14677aa1cd92.jpg)
is there another way to recover my wallet? please

**Comment by BGalliotti** [comment]
Hello @wormdz 
Thanks for reaching out to us.

- Was your wallet created with a 3rd party wallet app?

We look forward to hearing from you.
Kind regards.
