### ISSUE TITLE
Bitpay banned my country, how do i move my balance? 

### ISSUE THREAD

**Issue by bangh85** [bitpay/copay#9532]
Hi everyone
I use bitpay before, today i login to my bitpay wallet. But have report that bitpay banned my country . So can help with my old balance in bitpay? Have any same issue? Im from vietnam. 
Bitpay have any inform before banned? 

Thanks

**Comment by BGalliotti** [comment]
Hello 
Thanks for reaching out to us.

Please write to the Bitpay support: https://help.bitpay.com/requestHelp
Our representatives are going to address your inquiry there.

We would appreciate your patience.

Thanks in advance, Kind regards.

**Comment by bangh85** [comment]
But they banned we access website too.

**Comment by BGalliotti** [comment]
Hello @bangh85 
Thanks for reaching out to us.

Please refer to #9540

Kind regards.
