### ISSUE TITLE
Transaction failed

### ISSUE THREAD

**Issue by wintergarten** [bitpay/copay#9538]
I had a transaction with a low priority so i guess i have to wait but the transaction took like 6 months now.
I just want to ask if you could check the wallet 1FJ6CawsKgfGi1CrqEiznBNWF73tT6R9fs.
Kind regards

**Comment by wintergarten** [comment]
I had a transaction with a low priority so i guess i have to wait but the transaction took like 6 months now.
I just want to ask if you could check the wallet 1FJ6CawsKgfGi1CrqEiznBNWF73tT6R9fs.
Kind regards

**Comment by BGalliotti** [comment]
Hello @wintergarten 
Thanks for reaching out to us.

We have checked your wallet and it has no unconfirmed transactions. All the funds are currently available.

If you have any issues with a particular transaction, please send us the transaction ID so we can check it out.


Please let us know if you have any additional questions.
Kind regards.

**Comment by wintergarten** [comment]
I had already send you 3 messages from transactions and I didn´t received
it yet.

Please check it.

Am Mo., 15. Apr. 2019 um 21:22 Uhr schrieb BGalliotti <
notifications@github.com>:

**Comment by BGalliotti** [comment]
Hello @wintergarten 

We have no other tickets from you.
If you have sent them to the BitPay support, they are going to answer your inquiries.

Please let us know if you have any additional questions.
Kind regards.
