### ISSUE TITLE
funds transfer 

### ISSUE THREAD

**Issue by Amandinepraline** [bitpay/copay#9544]
Hello 
why i can't transfer my bitcoin cash amount to another wallet?

**Comment by joplee1209** [comment]
im using bitpay to deposit funds ti skrill  i waitied for the next page bitpay address not showing to deposit funds please help or is there a system down to transfer funds from bitpay to skrill?

**Comment by joplee1209** [comment]
when can i use bitpay to transfer my funds to skrill?

**Comment by BGalliotti** [comment]
Hello 
Thanks for reaching out to us.

@Amandinepraline 
>  why i can't transfer my bitcoin cash amount to another wallet?

What issues are you having, are you getting any error messages?

@joplee1209 
> when can i use bitpay to transfer my funds to skrill?

If Skrill provides you a Bitcoin / Bitcoin Cash address, then you can send funds to that address.
If you need something else, please open a new issue.

We look forward to hearing from you.
Kind regards.

**Comment by haus1985** [comment]
https://github.com/bitpay/copay/issues/9544#issuecomment-467161141
