### ISSUE TITLE
Transfer funds from Bitpay to Skrill 

### ISSUE THREAD

**Issue by joplee1209** [bitpay/copay#9545]
im using bitpay to deposit funds ti skrill  i waitied for the next page bitpay address not showing to deposit funds please help or is there a system down to transfer funds from bitpay to skrill? 

i use different browser still bitpay fund transfer not working please help i need to transfer funds please

whats going on your site cannot transfer funds still to other wallet.

**Comment by joplee1209** [comment]
i use different browser still bitpay fund transfer not working please help i need to transfer funds please

**Comment by joplee1209** [comment]
whats going on your site cannot transfer funds still to other wallet.

**Comment by BGalliotti** [comment]
Hello @joplee1209 
Thanks for reaching out to us.

If Skrill provides you a Bitcoin / Bitcoin Cash address, then you can send funds to that address.

- What are exactly the issues you are experiencing?

Kind regards.
