### ISSUE TITLE
I don't see my wallet when I tried Importing from backup

### ISSUE THREAD

**Issue by kewlwz** [bitpay/copay#9548]
Hello,
       I don't see my wallet when I try Importing from backup, I only see the default wallet which has no BTC in it. I forgot my wallet encrypt password, so trying to restore the wallet in another phone. Please help, 
       Is the way to send the money back to the Sender, without the encrypt password? I know the sender's address.

**Comment by BGalliotti** [comment]
Hello @kewlwz 
Thanks for reaching out to us.

> Please help,
Is the way to send the money back to the Sender, without the encrypt password?

No, you will not be able to do it as the password will be required.

> I don't see my wallet when I try Importing from backup

- Can you finish the import process? if not, What happens?
- You might be trying to import the wallet that is already in the app.
Check if the 12-word recovery phrase you want to import are the same as the wallet that is already in your app.

Kind regards.

**Comment by kewlwz** [comment]
Thanks for your response. 

* Can you finish the import process? if not, What happens?
         - 

> Yes, I am able to import using the 12-word recovery phase but I get just an empty wallet and not my wallet. My wallet name is different.

* You might be trying to import the wallet that is already in the app.
  Check if the 12-word recovery phrase you want to import are the same as the wallet that is already in your app.
         - 

> I verified, there are no other wallet in my Original other than my Personal Named Wallet. Still it just imports a generic empty wallet.

Once I create a Wallet and back it up with 12-word phrase, Every time I add some money into the wallet, should I need to backup again, as often a change is made?

**Comment by BGalliotti** [comment]
Hello @kewlwz 
Thanks for reaching out to us.

> Yes, I am able to import using the 12-word recovery phase but I get just an empty wallet and not my wallet. My wallet name is different.

The wallet name does not care and depending on the wallet version you are using, the app will retrieve the original name or not.
If you restore the wallet **A** (for instance) with the 12-word phrase, then that is fine, you cannot recover "another", say wallet **B** using your recovery phrase.

> I verified, there are no other wallet in my Original other than my Personal Named Wallet. Still it just imports a generic empty wallet. 

You cannot import a generic wallet, you either import a unique wallet or create a unique one (each wallet has a unique recovery phrase).

> Once I create a Wallet and back it up with 12-word phrase, Every time I add some money into the wallet, should I need to backup again, as often a change is made?

No, the recovery phrase does not change, it is unique and permanent.

Please let us know if you have any additional questions.
Kind regards.
