### ISSUE TITLE
 I use this app and I made a btc purchase, and now it says uncomfirmed. It’s been 6 hours, so I did a google search and figured out I needed to add a fee charge too? I didn’t know I had to add fees or does it add its own fees? How do I fix this please.

### ISSUE THREAD

**Issue by fuco2k3** [bitpay/copay#9553]

**Comment by BGalliotti** [comment]
Hello @fuco2k3 
Thanks for reaching out to us.

For a deeper understanding of the fees, please refer to:

[Copay FAQ - Fees](https://github.com/bitpay/copay/wiki/COPAY---FAQ#copay-requires-high-fees-for-low-amounts-transactions)

Also, check the posts mentioned there:

- https://github.com/bitpay/copay/issues/5164#issuecomment-265569494
- https://github.com/bitpay/copay/issues/4803#issuecomment-254496226

Kind regards.
