### ISSUE TITLE
illegal block size exception

### ISSUE THREAD

**Issue by tig4** [bitpay/copay#9568]
Cannot send funds anywhere. Just says error illegal block size exception. Was relying on this service for important payment. Need to get it out. I guess I used the old copay instead of bitpay. Could someone help please.

Hey didn't know how to reply the best way. I replied and it still said pending my response. Hope this is cool.

**Comment by BGalliotti** [comment]
Hello @tig4 

Thanks for reaching out to us.
 You are probably using an old version of the wallet, please update, try again and let us know what happens.

We look forward to hearing from you.
Kind regards.

**Comment by tig4** [comment]
Hey thanks for the reply. I can't seem to find an updated version of copay. I have installed  bitpay but can't figure out how to move funds from copay to bitpay. Is there a way to recover my wallet from copay in bitpay?

**Comment by tig4** [comment]
Hey thanks for the reply. I can't seem to find an updated version of copay. I have installed bitpay but can't figure out how to move funds from copay to bitpay. Is there a way to recover my wallet from copay in bitpay?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by BGalliotti** [comment]
Hello @tig4 
You are welcome,

You can import your wallet in Copay/Bitpay following [this](https://github.com/bitpay/copay/issues/8532#issue-319277251) instructions.

Keep in mind you can simply have all the wallets in the same app and send the funds from one wallet to another.

Kind regards.
