### ISSUE TITLE
MIS BTC NO SE VEN REFLEJADOS EN MI BITPAY

### ISSUE THREAD

**Issue by Davijo90** [bitpay/copay#9570]
Buenos días, ya he hecho todos los pasos que me han dicho y aún no veo los btc en mi Wallet. Mi caso es que recibí btc a mi Wallet de BitPay y efectivamente el pago fue confirmado, pero no se vé reflejado en mi Wallet. En el historial de transacciones se puede apreciar el btc cuando entra a mi Wallet pero no se ve la salida de ellos y tampoco se ven en mi Wallet los btc. Ya actualice cache, ya busque direcciones con fondos y aun no se donde están mis btc. Ayuda porfavor. En la siguiente imagen puedo mostrar por medio de un screenshot que se ven que los btc si llegaron a mi Wallet pero no se ven reflejados. #

**Comment by BGalliotti** [comment]
Hola @Davijo90 
Gracias por ponerse en contacto con nosotros.

Por favor, proporcione tantos de los siguientes detalles como pueda. Esto nos ayudará a ayudarte.

- Dispositivo actual utilizado.
     Ordenador o teléfono, incluido el modelo.
- Versión actual del sistema operativo para el dispositivo.
     Windows, iOS, Android, etc.
- Versión actual de la cartera utilizada.
     Aplicación BitPay> Configuración> Acerca de BitPay
- Cualquier archivo de registro que contenga detalles de error.
     Para obtener sus archivos de registro, abra su aplicación BitPay, luego vaya a Configuración> Acerca de BitPay> Registro de sesión> Toque en la esquina superior derecha (tres puntos)> Enviar por correo electrónico (también puede capturar el contenido y adjuntar las imágenes a su En tal caso, asegúrese de mover el control deslizante a la posición ** "Depurar" **).
- Error de captura de pantalla (s)
     En [iPhone] (https://apple.co/1DAB204)
     En [Android] (https://www.wikihow.tech/Take-Screenshots-on-an-Android)
- Pasos para replicar
     Pasos necesarios para que se produzca el error.
- Identificación de BitPay Wallet
     Para obtener su ID de billetera, abra su aplicación BitPay, luego vaya a la billetera con la que pagó> Preferencias> Información de billetera. El ID de la cartera debe ser el tercer elemento de la lista. En su teléfono, si toca la identificación de la cartera, la copiará en el portapapeles para que pueda pegar su correo electrónico.

¡Esperamos con interés escuchar de usted!
