### ISSUE TITLE
illegal block size exception 

### ISSUE THREAD

**Issue by tig4** [bitpay/copay#9572]
Hey. Left a comment on the last thread but it still said waiting for user response. I am kinda running out of time. Sure you've heard that before. Just trying to get funds into bitpay from copay somehow. I will be checking all day and would love to take care of this soon. If someone could help I'd really appreciate it. Maybe include how I could take off the response pending tidal too. Thank you guys and girls.

**Comment by BGalliotti** [comment]
Hello @tig4 
Thanks for reaching out to us.

We apologize for the delay.
We have answered [here](https://github.com/bitpay/copay/issues/9568).

Kind regards.
