### ISSUE TITLE
i cant find any record of my transaction in my copay acct

### ISSUE THREAD

**Issue by latashao** [bitpay/copay#9577]
i need my blockchain receipt but i cant even find the $20 transaction i sent out earlier

**Comment by BGalliotti** [comment]
- **Please send us the BitPay/Copay Wallet ID and the transaction hash / ID or the link so we can further investigate and address your inquiry.**

- To get your Wallet ID, open your Copay/BitPay application, then go to `Settings` > [Your wallet] > `More Options` > `Wallet Information`. 
On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste it in your e-mail. 
You can do the same on your computer by clicking on the wallet ID.

- The transaction hash / ID is a alphanumeric chain like this: **d0a23876de7cf87574b5cda7557bcc8af5d84f3fd1e6f4c6063fd6b72b0e69ae**

To see the transactions:
- Open the Copay/Bitpay app
- Select the desired wallet
- Tap the transaction
- Scroll down and tap the transaction ID to copy it

**We look forward to hearing from you.**
