### ISSUE TITLE
can't start Copay anymore?

### ISSUE THREAD

**Issue by max-hart** [bitpay/copay#9581]
Hi!
Since today I've trouble accessing the Copay app. 

After showing the Copay-logo for a second a failure pop-up appears: 
"_Could not initialize the app. TypeError: Attempted to assign to readonly property_".
After tapping OK the screen stays white.

What can I do to access the app again?
Your help is highly appreaciated. Thank you in advance!
Best regards
Max

**Comment by BGalliotti** [comment]
Hello @max-hart 

Thank you for reaching out to us.

**So we can further help, please provide as many of the following details as you can:**

- Current device used: Phone model 
- Current operating system version for the device: iOS, Android..
- Current version of the wallet used: CoPay App > Settings > About CoPay 
- Error screenshot: On [iPhone](https://apple.co/1DAB204) on [Android](https://www.wikihow.tech/Take-Screenshots-on-an-Android)
- CoPay Wallet ID - To get your Wallet ID, open your CoPay application, then go to `Settings` > [Your wallet] > `More Options` > `Wallet Information`. On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste in your e-mail.

**We look forward to hearing from you.**

**Comment by max-hart** [comment]
Hey, 
I am using an iPhone 8 running on iOS 12.1.4
Copay Version 5.6.4 - updates today via AppStore 
I can’t get the app started, so I can’t tell you my wallet ID.
Thank you so much!

**Comment by BGalliotti** [comment]
Hello @max-hart 
Thanks for reaching out to us.

We have tested the app on the platform you are using and it is working properly.
Please try uninstalling and reinstalling the app.

Kind regards.
