### ISSUE TITLE
Merchant fee to high. Payment rejected and after stuck on fee calculation

### ISSUE THREAD

**Issue by mustafaarslantas** [bitpay/copay#9592]
Hello, i trying to pay but have error 'Merchant fee to high. Payment rejected' and after stuck on fee calculation.

**Comment by BGalliotti** [comment]
Hello @mustafaarslantas 
Thanks for reaching out to us.

We are working on this issue and will post as soon as possible.

Please let us know if you have any additional questions.
Kind regards.

**Comment by laksh1010** [comment]
me also having same issue. how to fix ?

**Comment by ad-m** [comment]
me also having same issue. how to fix ?

**Comment by Giftcarder** [comment]
I seem to be having the same issue with bitpay, any new updates on this?

**Comment by 0xBenjamin** [comment]
They do it on purpose

**Comment by matiu** [comment]
Hi, what version of the app are you using?
