### ISSUE TITLE
Forgot password PF wallet

### ISSUE THREAD

**Issue by bksbruno** [bitpay/copay#9598]
O forgot the password to do transfer. Os the same oficial 12 words?

**Comment by BGalliotti** [comment]
Hello @bksbruno 
Thanks for reaching out to us.

The 12-word recovery phrase is not the encrypt password but it lets you recover the wallet. 
To know how to recover the wallet please refer to #9292 .

To know more about the passwords please read this article: https://support.bitpay.com/hc/en-us/articles/360018366012-BitPay-Products-and-Their-Passwords

Please let us know if you have any additional questions.
Kind regards.

**Comment by Travis2022** [comment]
@bksbruno 

if you haven't recovered your wallet, i can do it dm me : anywalletrecovery@gmail.com
