### ISSUE TITLE
i cant find any record of my transaction in my copay acct

### ISSUE THREAD

**Issue by udginvr-crypterium** [bitpay/copay#9604]
Wallet Id: 18d3c1ce-08ef-474c-b825-34ac40509fd6
I have sent 0.0011 BTC onto address 3939gxLpFtjioKgFGQiC7ZBQadKwuBywnV
Transaction time was between 2019-03-25 15:04 and 2019-03-25 15:12 UTC
Now I see that my wallet balance has dropped nearly 0.002 BTC and there are no signs of transaction neither in the blockchain, nor in the Copay wallet itself.
Don't even know where to dig to find my crypto... Some advice please?
BTW: This is a distributed wallet (it is used by several people on the different computers). Could it be an issue? If it is - please provide me with some info to make a situation clearer for me.

**Comment by udginvr-crypterium** [comment]
After receiving an external transaction, the balance has returned to normal. Still no trace of a transaction in question.
The issue is resolved, but I would appreciate any additional info (this is not the first case when crypto is mysteriously missing for some days).

**Comment by BGalliotti** [comment]
Hello @udginvr-crypterium 
Thanks for reaching out to us.

We have checked your wallet and you have no transactions on 03/25.

The address 3939gxLpFtjioKgFGQiC7ZBQadKwuBywnV has no transactions until today as you can see [here](https://insight.bitcore.io/#/BTC/mainnet/address/3939gxLpFtjioKgFGQiC7ZBQadKwuBywnV).

Please let us know if you have any additional questions.
Kind regards.

**Comment by udginvr-crypterium** [comment]
Hello @BGalliotti 
I'm mostly interested in an issue itself. Why did Copay show my balance decreased (though no outgoing transaction was/is present). And more importantly - how do I recover from the situation? For now it happened twice and resolves authomatically after a couple of days (or maybe after I receive an incoming transaction?), but it is quite uncomfortable to not be able to understand what is happening with my balance.
