### ISSUE TITLE
Retrieving a Private Key

### ISSUE THREAD

**Issue by dicijr** [bitpay/copay#9623]
Hello,

I've spent the last 3-4 hours trying to figure out how to retrieve a specific private key.

I wouldn't say im a super expert, but I certainly have an understanding of some of this.

I've followed mostly every guide I can and have come to grips that:

- I am using the iancoleman tool to get addresses/priv keys.
- I can't locate my address.
- I have the wallet and Its backed up.
- Heres wallet info:
http://prntscr.com/n6mtq6

- I have access to 2/3 devices but from what I can [iece together in my head. I'm taking the xprivkey to find addresses and I shouldnt need any others?

My head hurts.
----------------------------------------
Heres what I think I can understand..

This wallet was created in April 2017 and I am not sure the derivation path that was used to find the series of addresses.

I've tried using my xprivkey to derrive several different paths and I have not found any addresses in my recent addresses.
(m/45'/2147483647/0 , etc)
Something makes me feel like the derivation path was different when my wallet was created.

**Comment by dicijr** [comment]
Backstory:

Sent Tether to this btc address by mistake, trying to get it back.

**Comment by dicijr** [comment]
My wallet was created in April 2017 if that helps with deri. paths..

**Comment by dicijr** [comment]
If my understanding is correct, one of my xpub keys should be able to put into blockchain explorer and be able to show my transaction (or any on my bitpay wallet) as a whole.

This is not the case.

**Comment by dicijr** [comment]
Following: https://github.com/thephez/copay-hd-multisig-recovery/blob/master/Copay%20HD%20Multisig%20Address%20Derivation%20and%20Manual%20Transaction%20Creation.md

in attempts to re-create my addresses I have discovered both my phone and my computer are identifying as the same copayer.

**Comment by dicijr** [comment]
I believe the final question is:

If I have the xpub keys of the copayers and the xprivkey of one copayer (1-3) am I able to retrieve a private key. (Sent tether to copay address)

**Comment by BGalliotti** [comment]
Hello @dicijr,

Thank you for reaching out to us.

> If I have the xpub keys of the copayers and the xprivkey of one copayer (1-3) am I able to retrieve a private key. (Sent tether to copay address)

No. With all the xpub keys you can generate addresses.
With all the xpub and xpriv keys needed you can recover the wallet, however to retrieve addresses from a specific copayer you need all the public keys and its private key, for example:

You have this 1-3 wallet:

- Hugo: xpub + xpriv
- Paco: xpub
- Luis: xpub

You cannot generate Paco's or Luis's addresses with that information.

Please let us know if you have any additional questions.
Kind regards.
