### ISSUE TITLE
rejoining a multisig wallet, having only the seed phrase

### ISSUE THREAD

**Issue by DE4DCATBOUNCE** [bitpay/copay#9624]
moving to a new device and want to restore my part of 2of3 multisig wallet. besides having to specify my name, derivation path, select a coin and type in my recovery seed, i supposedly still need to have a wallet invitation.

where can I retrieve it?

**Comment by BGalliotti** [comment]
Hello @DE4DCATBOUNCE 
Thank you for reaching out to us.

You have to import the wallet:

- Open the Copay/Bitpay app
- Tap the **+** on the top left corner of the app
- Tap **Import wallet**
- Select the coin
- Enter the recovery phrase
- Tap **IMPORT** (top left corner)

Please let us know if you have any additional questions.
Kind regards.

**Comment by insiderq** [comment]
The question isn't properly answered. So sad truth here for @DE4DCATBOUNCE is that at least you need a 3 public keys to retrieve that wallet.

**Comment by DE4DCATBOUNCE** [comment]
Exactly, this isn't properly answered. To explain myself more clear - there a 3 participants in a 2of3 shared wallet. All of us have our seeds. One of has changed his phone, so new fresh app was installed. Now the issue is, how to restore the wallet for that one participant with a new phone, without creating a new shared wallet, and all 3 participants having to set up new wallets as well.

**Comment by insiderq** [comment]
Oh, you have all of 3 seeds. I thought you have only 2 seeds.

Then just simple "import wallet" without any advanced options should work for you.
I have already done this.

**Comment by Amin2110** [comment]
Tq

**Comment by matiu** [comment]
@insiderq that is incorrect.

if the wallet was hosted on the default wallet server (BWS), BWS has the public keys of the wallet. You can restore the wallet with a single seed.

**Comment by matiu** [comment]
So, just import the seed. and the previously shared wallet should appear. let us know any problem.
