### ISSUE TITLE
Transaction broadcasted but doesn't exist on explorer

### ISSUE THREAD

**Issue by eccentricbiped** [bitpay/copay#9625]

**Comment by BGalliotti** [comment]
Hello @eccentricbiped 
Thank you for reaching out to us.

Please post the transaction ID so we can verify it.

Kind regards.

**Comment by eccentricbiped** [comment]
Seems the transaction was eventually confirmed, it was temporarily in a
weird state where it didn't exist on block explorer.

**Comment by BGalliotti** [comment]
Hello @eccentricbiped 

**We are glad to know you were able to solve the issue!**
Feel free to open a new one in case you have any questions or concerns.

**Thank you for your interest and support!**
