### ISSUE TITLE
My BTC Balance is Stuck - Creating transaction...  Times Out/Never Gets Created

### ISSUE THREAD

**Issue by jl22253** [bitpay/copay#9630]
I have the Copay App for IOS, v.5.7.1, #f75b016

I have a particular wallet that I can't send BTC out of.  I've tried sending it to other wallets on my Copay App as well as my cold storage, and all I get is the Creating transaction... message for several seconds and then nothing happens.

I have other wallets on my Copay App that are working fine.

This is the wallet id: a20290f5-2db4-4e00-9978-0f697f0bf08a

Thanks for your help!!

**Comment by jl22253** [comment]
I deleted the wallet and then restored it with the 12 word phrase, and the wallet is still messed up, cannot send any funds out of it.  Same problem - Creating Transaction... and then the message goes away and nothing else ever happens.  Can someone please help?

**Comment by BGalliotti** [comment]
Hello @jl22253 

Thank you for reaching out to us.

We have checked your wallet and it seems to be fine. You have made many transactions.
Are you still experiencing the issue?

**In such case, so we can further help, please provide as many of the following details as you can:**

- Current device used including model
- Current operating system version for the device- Current version of the wallet used: Copay App > Settings > About Copay
- Any log files containing error details: Copay App > Settings > About CoPay > Session Log > Tap on the Upper right corner (three dots) > Send by email
- Error screenshot: On [iPhone](https://apple.co/1DAB204) on [Android](https://www.wikihow.tech/Take-Screenshots-on-an-Android)
- Steps to replicate: Steps needed for the error to appear.
- Copay Wallet ID - To get your Wallet ID, open your Copay application, then go to `Settings` > [Your wallet] > `More Options` > `Wallet Information`. On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste in your reply.

Please let us know if you have any additional questions.
Kind regards.

**Comment by jl22253** [comment]
Thanks for the response.  I fixed the issue by restoring my private keys onto the Blockchain Wallet and could then transfer the funds out.  Thanks anyways!
