### ISSUE TITLE
Transaction not showing

### ISSUE THREAD

**Issue by vegamo1** [bitpay/copay#9631]
I transfer 36 dollars to this address 14Hyo1inan5xHHQT8LV6yqtDWc3nKCr9Lu and has not been confirm yet since yesterday. Transaction I'd 5fa4b84625639666e6430b774a6ede3a471ebb7466de836d1745622c5aef753c.

**Comment by BGalliotti** [comment]
Hello @kleetus 
Thank you for reaching out to us.

The transaction has properly gone through:
https://insight.bitcore.io/#/BTC/mainnet/tx/5fa4b84625639666e6430b774a6ede3a471ebb7466de836d1745622c5aef753c

If you were not seeing it on your transaction history or your balance is wrong, please [refresh](https://github.com/bitpay/copay/issues/8806#issuecomment-399074701) your wallet.

Please let us know if you have any additional questions.
Kind regards.
