### ISSUE TITLE
Transaction

### ISSUE THREAD

**Issue by vegamo1** [bitpay/copay#9632]
I did a transaction of 25 to this address 14Hyo1inan5xHHQT8LV6yqtDWc3nKCr9Lu with 6+ confirmation, the costumer said have not recieved yet. Transaction I'd 635fdc36e9b51b62242b1fcebee11f83314fc227133efc220c6a1a63d22af850.

**Comment by BGalliotti** [comment]
Hello @vegamo1 
Thank you for reaching out to us.

The transaction [635fdc36e9b51b62242b1fcebee11f83314fc227133efc220c6a1a63d22af850](https://insight.bitcore.io/#/BTC/mainnet/tx/635fdc36e9b51b62242b1fcebee11f83314fc227133efc220c6a1a63d22af850) is properly confirmed .

If the transaction was not showing up please refer to #9631 

Please let us know if you have any additional questions.
Kind regards.
