### ISSUE TITLE
Bitcoin missing after recovering wallet

### ISSUE THREAD

**Issue by williams12350** [bitpay/copay#9641]
I recently had to reset my phone so before I did I wrote down the recovery phrase very carefully. After re downloading the bit pay wallet I tried my pass phrase to restore I was greeted with this message -
could not access the wallet server please check -
the password of the recovery phrase
the derivation path 
the wallet surface url

so I contacted bit pay and they advise me to -  open a new wallet, then create new wallet, then use my passphrase instead of a random key. I have done this and the wallet was recovered but it is empty. any ideas?? it was over 1.2 btc in there money I just cant afford to lose
Please help!

**Comment by BGalliotti** [comment]
Hello @williams12350,
Thank you for reaching out to us.

- **Please send us the Copay Wallet ID and the transaction hash / ID or the link so we can further investigate and address your inquiry.**

- To get your Wallet ID, open your Copay application, then go to `Settings` > [Your wallet] > `More Options` > `Wallet Information`. 
On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste it in your e-mail. 
You can do the same on your computer by clicking on the wallet ID.

**We look forward to hearing from you.**

**Comment by Travis2022** [comment]
@williams12350 
if you didn't import your wallet, i can help you recover it 
 : anywalletrecovery@gmail.com

**Comment by richardsuns** [comment]
@williams12350 
did you restore your wallet? i think i can solve it if you still see zero balance
