### ISSUE TITLE
Slushpool payment issue

### ISSUE THREAD

**Issue by dombouchard** [bitpay/copay#9643]
Hi, i requested a payout from slushpool yesterday to a wrong wallet address, to a Copay wallet i dont have access anymore. Is there any way to see where those btc ended up?

**Comment by BGalliotti** [comment]
Hello @dombouchard 
Thank you for reaching out to us.

By checking the transaction you can deduce where the funds have gone, however, that does not mean you will have access to the funds.

You can search for a transaction on [insight](https://insight.bitcore.io/) by entering the transaction 

Please let us know if you have any additional questions.
Kind regards.
