### ISSUE TITLE
Errors "Could not update wallet : Network error"

### ISSUE THREAD

**Issue by phamvietphi** [bitpay/copay#9658]
I have problem with Copay app. 

It write : " Could not update wallet : Network error"

I have 0.10077 BTC in my wallet, but I cant transfer my money, cant use. Please help me fix this Error. Thank you.

![WhatsApp Image 2019-04-12 at 15 04 06](https://user-images.githubusercontent.com/49551421/56021896-c2d60800-5d34-11e9-9d94-a55f67e875b4.jpeg)
![WhatsApp Image 2019-04-12 at 15 04 09](https://user-images.githubusercontent.com/49551421/56021897-c36e9e80-5d34-11e9-906a-fda9e4cd27f8.jpeg)

**Comment by BGalliotti** [comment]
Hello @phamvietphi 
Thank you for reaching out to us.

Please refer to #9070 

Please let us know if you have any additional questions.
