### ISSUE TITLE
Copay Android builds

### ISSUE THREAD

**Issue by Forage** [bitpay/copay#9665]
Since some time now Copay is no longer available in the Google app store, nor are apk files being provided.

The last apk is available with a cryptic name for version 5.4.0, with missing out on releases before and after that.
The website has been taken down at the same time.

What is going on? Have you lost interest?
Would it be possible to provide builds again?

**Comment by BGalliotti** [comment]
Hello @Forage  
Thank you for reaching out to us.

The latest uploaded apk file is version 5.7.1 that can be found here](https://github.com/bitpay/copay/releases).

We are going to be uploading not all releases but the major ones.

Please let us know if you have any additional questions.
Kind regards.

**Comment by Forage** [comment]
Thank you for your reply.
Unfortunately it is not a Copay build that is available of version 5.7.1 but a Bitpay build.

**Comment by BGalliotti** [comment]
Hello @Forage 
Thank you for reaching out to us.

>  Unfortunately it is not a Copay build that is available of version 5.7.1 but a Bitpay build.

You are right, we apologize for the mistake. We should be uploading a Copay build on next releases.
Please try with the BitPay app in the meantime.

Please let us know if you have any additional questions.
Kind regards.

**Comment by Forage** [comment]
The latest two releases provide Android builds again, but with the ambiguous name android-release-signed-aligned.apk. These turn out to be Bitpay builds however.

Will there be Copay builds made available again in the near future?

**Comment by BGalliotti** [comment]
Hello @Forage 
Thank you for reaching out to us.

Yes, there will be Copay builds, we are uploading build only when major updates happen. Please stay tuned for the next release.

Please let us know if you have any additional questions.
Kind regards.

**Comment by matiu** [comment]
@Forage 

thanks for you input on the APK name. we will name them Copay or Bitpay depending the app.  we just build Copay-5.9.4.apk for the next release. it will be delivered today.

**Comment by Forage** [comment]
Should this bug be reopened again or should I create a new one for the same subject?

**Comment by BGalliotti** [comment]
Hello @Forage 

No, we understand the inquiry has been answered. 
If it was not clear:

- In regards to the app name, that was answered [here](https://github.com/bitpay/copay/issues/9665#issuecomment-507645973).
- About the availability of Copay versions, it will simply not be released as frequently as BitPay app, only when major changes are done, that will stay the same, the latest releases can be found [here](https://github.com/bitpay/copay/latest)

Kind regards.

**Comment by KreAch3R** [comment]
> Hello @Forage
> 
> No, we understand the inquiry has been answered.
> If it was not clear:
> 
> * In regards to the app name, that was answered [here](https://github.com/bitpay/copay/issues/9665#issuecomment-507645973).
> * About the availability of Copay versions, it will simply not be released as frequently as BitPay app, only when major changes are done, that will stay the same, the latest releases can be found [here](https://github.com/bitpay/copay/latest)
> 
> Kind regards.

Hello @BGalliotti 

The last link you provide about Copay builds does not work. Where can we find the Android builds?

**Comment by Forage** [comment]
> > Hello @Forage
> > No, we understand the inquiry has been answered.
> > If it was not clear:
> > 
> > * In regards to the app name, that was answered [here](https://github.com/bitpay/copay/issues/9665#issuecomment-507645973).
> > * About the availability of Copay versions, it will simply not be released as frequently as BitPay app, only when major changes are done, that will stay the same, the latest releases can be found [here](https://github.com/bitpay/copay/latest)
> > 
> > Kind regards.
> 
> Hello @BGalliotti
> 
> The last link you provide about Copay builds does not work. Where can we find the Android builds?

You'd need to go back to version 8.0.5 in the releases list. For some reason an update to major versions 9, 10 and 11 don't qualify as "major changes ... done".

**Comment by KreAch3R** [comment]
> You'd need to go back to version 8.0.5 in the releases list. For some reason an update to major versions 9, 10 and 11 don't qualify as "major changes ... done".

But I can't access the releases pages at all, that link is dead. 

Who are the maintainers of these builds? Can't they produce a recent one?

**Comment by Forage** [comment]
> > You'd need to go back to version 8.0.5 in the releases list. For some reason an update to major versions 9, 10 and 11 don't qualify as "major changes ... done".
> 
> But I can't access the releases pages at all, that link is dead.
> 
> Who are the maintainers of these builds? Can't they produce a recent one?

Works fine here: https://github.com/bitpay/copay/releases/tag/v8.0.5

**Comment by KreAch3R** [comment]
Thanks @Forage . I found the builds but are indeed too far back, as you said. 

I pulled the plug and compiled it from sources on my own. The source is currently in an unbuildable state so I created two commits https://github.com/bitpay/copay/pull/11307 to address that: https://github.com/bitpay/copay/pull/11306


<img src="https://i.imgur.com/PhJ0Lra.png" width="400">
