### ISSUE TITLE
Unconfirmed Transaction and not found 

### ISSUE THREAD

**Issue by kasas101** [bitpay/copay#9668]
I used my Copay wallet to send all my funds and I didn´t notice that the fee was very low, now my transaction is in sending status. A week has passed, when I search the transaction ID on blockchain it say "transaction not found". Help me please.

**Comment by BGalliotti** [comment]
Hello @kasas101 
Thank you for reaching out to us.

- **Please send us the BitPay/Copay Wallet ID and the transaction hash / ID or the link so we can further investigate and address your inquiry.**

- The transaction hash / ID is a alphanumeric chain like this: **d0a23876de7cf87574b5cda7557bcc8af5d84f3fd1e6f4c6063fd6b72b0e69ae**

**We look forward to hearing from you.**

Kind regards.

**Comment by kasas101** [comment]
Thank you, this is the transaction ID  3e9db9beb11be09e1a4c541128465a4e0608d5ebd48a2f2c421ec70ec57857cf

**Comment by BGalliotti** [comment]
Hello @kasas101 

We have successfully broadcast your transaction, you can check its status [here](https://insight.bitcore.io/#/BTC/mainnet/address/3e9db9beb11be09e1a4c541128465a4e0608d5ebd48a2f2c421ec70ec57857cf).

Feel free to get back to us in case you have any questions or concerns.

**Comment by kasas101** [comment]
Thank you very much !
