### ISSUE TITLE
Bitcoin not able to send

### ISSUE THREAD

**Issue by pranay1245** [bitpay/copay#9669]
I am unable to send .039 BTC present in my account...plz help

**Comment by BGalliotti** [comment]
Hello @pranay1245 
Thank you for reaching out to us.

What is exactly the inconvenience you are having?

**So we can further help, please provide as many of the following details as you can:**

- Current device used including model
- Current operating system version for the device- Current version of the wallet used: Copay App > Settings > About Copay
- Any log files containing error details: Copay App > Settings > About CoPay > Session Log > Tap on the Upper right corner (three dots) > Send by email
- Error screenshot: On [iPhone](https://apple.co/1DAB204) on [Android](https://www.wikihow.tech/Take-Screenshots-on-an-Android)
- Steps to replicate: Steps needed for the error to appear.
- Copay Wallet ID - To get your Wallet ID, open your Copay application, then go to `Settings` > [Your wallet] > `More Options` > `Wallet Information`. On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste in your reply.

We look forward to hearing from you.

**Comment by jordimen03** [comment]
Hola tengo operaciones sin confirmar desfe el martes cuando se van a confirmar

Un saludo

**Comment by BGalliotti** [comment]
Hola @jordimen03 
Gracias por ponerse en contacto con nosotros.

Compártanos el ID de las transacciones para que podamos verificar la situación.
Es posible que simplemente haya usado fees bajos y dada la congestión de la red, tarda mucho en confirmar

Esperamos su respuesta.
Saludos cordiales.
