### ISSUE TITLE
Private key exported in Chinese can't be imported,  Lost my BTC

### ISSUE THREAD

**Issue by fixallbug** [bitpay/copay#9672]
Hi,

The private key  I used Bitpay wallet in Simplified Chinese exported, can't be imported into any BTC wallet,  always said that private key was wrong, including Bitpay wallet, Copay wallet, and Blockchain, private key in English has no this problem in the same wallet, now I have lost my BTC, is there any way to fix it ?

**Comment by BGalliotti** [comment]
Hello @fixallbug 
Thank you for reaching out to us.

The funds are not lost. What you can do is create a new wallet using a recovery phrase in English (compatible with any wallet app) and move the funds to that wallet. 
All that can be done from Copay:

- Import the simplified Chinese wallet 
- Set the app language to English)
- Create a wallet 
- Move the funds from the "Chinese" wallet to the new "English" wallet.

Please let us know if you have any additional questions.
Kind regards.

**Comment by Amin2110** [comment]
Pay

**Comment by Amin2110** [comment]
Pay

**Comment by fixallbug** [comment]
@BGalliotti 
Hi,

I can't import my Simplified Chinese wallet into any BTC wallet with the 12 Chinese characters which was created by Bitpay wallet in Simplified Chinese, it always happened like the screenshot：
![bit](https://user-images.githubusercontent.com/49889808/56625841-ef6f0700-65f3-11e9-9b79-f1a860e4cb1e.JPG)

**Comment by Amin2110** [comment]
Pay

**Comment by nihao10086nihao** [comment]
I also met this question. Copay wallet
My mobile phone is lost and cannot be retrieved in Chinese.

**Comment by Amin2110** [comment]
UPDATE

**Comment by Amin2110** [comment]
https://github.com/bitpay/copay/issues/9672#issuecomment-486245095

**Comment by matiu** [comment]
Can you please check all the characters on the backup are on the allowed Chinese simplied wordlist:

https://github.com/bitcoin/bips/blob/master/bip-0039/chinese_simplified.txt
?

You may have some typo.
