### ISSUE TITLE
 Display style error 

### ISSUE THREAD

**Issue by langubtc** [bitpay/copay#9680]
Language  chinese
![image](https://user-images.githubusercontent.com/43126361/56782253-e6ab4a80-6818-11e9-8be6-12355420310e.png)

**Comment by BGalliotti** [comment]
Hello @langubtc 
Thank you for your feedback.

We will really appreciate if you could correct translation [here](https://crowdin.com/project/copay/zh-CN#). You can log in with your GitHub account.

Please let us know if you have any additional questions.
Kind regards.
