### ISSUE TITLE
Could not update wallet, wallet needs address scan

### ISSUE THREAD

**Issue by tiennm54** [bitpay/copay#9684]
Hi

I am from Vietnam. I installed copay on the computer with the operating system is win 10. My wallet always says "Could not update wallet: 403" error. I have moved BTC into my wallet but I don't get it. Please help me. Sorry for my English not good

Thank you so much!

**Comment by BGalliotti** [comment]
Hello @tiennm54 
Thank you for reaching out to us.

- In regards to the error 403 please refer to #9070 
- To recover your funds, please refer to #9540 

Please let us know if you have any additional questions.
Kind regards.

**Comment by lbsparks** [comment]
Hi, I am getting an error on my bitpay. Could not update wallet 500. HOW DO I FIX IT

**Comment by BGalliotti** [comment]
Hello @lbsparks 
Thank you for reaching out to us.

Please check your internet connection and try again.

Kind regards.
