### ISSUE TITLE
Backup issue

### ISSUE THREAD

**Issue by vanbreukelingen** [bitpay/copay#9699]
Well I have a backup from an older copay wallet in Arch 5.0.10-zen; I have ten of the 12 required remembering phrases written down and the password; is there a possibility to recover?

**Comment by matiu** [comment]
You need the 12 words to recover the backup. the words are from a predetermined list:  https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt of 2048 words

Depending on the funds held by the wallet you may evaluate if it worth to try to recover them by trying different words

**Comment by richardsuns** [comment]
@vanbreukelingen 
i have powerful machine to find the lost 2 words of the phrase
contact me in telgram   telegram id: @walletrecover
