### ISSUE TITLE
Is Windows 7 supported? 

### ISSUE THREAD

**Issue by ZhenyaKa** [bitpay/copay#9700]
How to download and install Windows 7 x64 version?

**Comment by BGalliotti** [comment]
Hello @ZhenyaKa 
Thank you for reaching out to us.

The latest version of the app requires Windows 10. You can install the Copay/Bitpay legacy versions of the app (until 4.8.1).

However, the legacy app is becoming obsolete and some functions are not working any longer (like the gift cards and BitPay card so far)

Please let us know if you have any additional questions.
Kind regards.
