### ISSUE TITLE
Never received funds to my LQDFX account

### ISSUE THREAD

**Issue by Jarvisscar** [bitpay/copay#9704]
I sent funds to my LQDFX account via Copay but LQDFX never received the funds! Usually it takes about 30 minutes but it’s been almost a full day since I submitted the transaction.

**Comment by matiu** [comment]
Hi,

Do you see the TX on the blockchain?

**Comment by Jarvisscar** [comment]
TX? Are talking about when I select view on blockchain and it takes me to insight? If so, no! But I’m not sure where to look honestly!

**Comment by matiu** [comment]
Yes. That tx. If it is confirmed, you need to sned them the tx id (send
them the link) as a proof of payment.

**Comment by Jarvisscar** [comment]
Are you referring to the transaction ID? But yes the it has been confirmed

**Comment by matiu** [comment]
Then, it is not related to the wallet, if the tx is confirmed already on
the blockchain. Talk to LQDFX.
