### ISSUE TITLE
copay 

### ISSUE THREAD

**Issue by dcitrano** [bitpay/copay#9707]
LQDFX said they sent a refund and sent me the address but i have not seen my refund in my wallet on copay. how do i know what to look for on the block chain in in site?

**Comment by matiu** [comment]
You need to contact them and ask them for the transaction ID and the address the used to send you back the funds.

**Comment by dcitrano** [comment]
I did I have the I'd number

**Comment by dcitrano** [comment]
I have the transaction I'd but I don't know what in looking with itSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Matias Alejo Garcia <notifications@github.com> Date: 5/8/19  1:09 PM  (GMT-06:00) To: bitpay/copay <copay@noreply.github.com> Cc: dcitrano <Citranoderek6@gmail.com>, Author <author@noreply.github.com> Subject: Re: [bitpay/copay] copay  (#9707) You need to contact them and ask them for the transaction ID and the address the used to send you back the funds.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/bitpay/copay/issues/9707#issuecomment-490591644",
"url": "https://github.com/bitpay/copay/issues/9707#issuecomment-490591644",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by dcitrano** [comment]
Can any one help me to find my money that was refunded to me? Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Matias Alejo Garcia <notifications@github.com> Date: 5/8/19  1:09 PM  (GMT-06:00) To: bitpay/copay <copay@noreply.github.com> Cc: dcitrano <Citranoderek6@gmail.com>, Author <author@noreply.github.com> Subject: Re: [bitpay/copay] copay  (#9707) Closed #9707.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/bitpay/copay/issues/9707#event-2328044883",
"url": "https://github.com/bitpay/copay/issues/9707#event-2328044883",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
