### ISSUE TITLE
Wallet Hacked or unknown transaction

### ISSUE THREAD

**Issue by ashwinpijdurkar** [bitpay/copay#9708]
is there any way to trace the transaction happned on my wallet as all of my funds were removed unknowingly 
( my private key backup is secured in my cupboard + no one touched my phone or pc)
but i have the transaction address and also the other guys wallet still has all the funds ( it is reflected on blockchain)

transaction link- https://insight.bitpay.com/tx/cc8361ba7c39ff1b8677fbf4a8fe059ee1567713266d464713912e47ee426db6
transaction id- 
cc8361ba7c39ff1b8677fbf4a8fe059ee1567713266d464713912e47ee426db6

+ im the owner of the sending wallet ( but i did not sent the funds)

is it possible to trace?
or  is it possible to guess the private key for the one who got all my funds? i dont think so and i dont even know where to ask help fr4om

**Comment by BGalliotti** [comment]
Hello @ashwinpijdurkar 
Thank you for reaching out to us.

We are sorry you have had this bad experience.

> is there any way to trace the transaction happned on my wallet as all of my funds were removed unknowingly
( my private key backup is secured in my cupboard + no one touched my phone or pc)
but i have the transaction address and also the other guys wallet still has all the funds ( it is reflected on blockchain)

What you pose is strange taking into account nobody has used your devices. Please make sure your devices are properly secured. In addition to that you might want to analyze your devices for viruses/malware.
If you think your wallet may be compromised, consider moving your funds to another wallet and changing your receiving address on future payments.

It is not possible to track down the transaction, you can trace what happened with the funds after leaving your wallet but will have no information about the owners of the "addresses".

>  or is it possible to guess the private key for the one who got all my funds? i dont think so and i dont even know where to ask help fr4om

This is impossible.

Please let us know if you have any additional questions.
Kind regards.
