### ISSUE TITLE
Bitcoin transaction issue / problem

### ISSUE THREAD

**Issue by uandarful** [bitpay/copay#9713]
Hello,
I have sent from a wallet of mine to my copay wallet some bitcoins and even if I have 6/6 confirmations I did not received the amount in my copay wallet.  What is happening ?

Copay generated for receiving wallet: 1MB4xCajUWvr9YBUrhxb8jHvHgbFHZy3TQ
txid : 904eea4cc8f75341a7a0c105a7bf5d29177c124ecbc2a393ef38ab8ca6e4a5e6
Amount: 0.01607773

I am waiting your answer asap ! 
Thank you

**Comment by BGalliotti** [comment]
Hello @uandarful 
Thank you for reaching out to us.

- **Please send us the BitPay/Copay Wallet ID so we can further investigate and address your inquiry.**

- To get your Wallet ID, open your Copay/BitPay application, then go to `Settings` > [Your wallet] > `More Options` > `Wallet Information`. 
On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste it in your e-mail. 
You can do the same on your computer by clicking on the wallet ID.

**We look forward to hearing from you.**

**Comment by uandarful** [comment]
Hello,
Wallet ID:
bfd90afe-1b78-403b-a824-dfdb4a4f930e

The generated wallet to receive the amount in Bitpay was
:1MB4xCajUWvr9YBUrhxb8jHvHgbFHZy3TQ
The transaction id was:
904eea4cc8f75341a7a0c105a7bf5d29177c124ecbc2a393ef38ab8ca6e4a5e6

**Comment by BGalliotti** [comment]
Hello @uandarful 
Thank you for reaching out to us.

We have checked your wallet and the address does not belong to it either to any Copay/BitPay wallet, that is why you are not receiving the funds.

Unfortunately, there is nothing to do about it as Bitcoin transactions are not reversible.

To get addresses to receive funds:

- Open the app
- Select the wallet where you want to receive the funds
- Tap **Receive**
- Tap the QR code/address to copy it or let the sender scan the code

Please let us know if you have any additional questions.
Kind regards.
