### ISSUE TITLE
24 hours unconfirmed 

### ISSUE THREAD

**Issue by Fuschler** [bitpay/copay#9721]
the following  transactions did not have a confirmation since 24 hours

i have a copay wallet

what should i do?

a51553f95ea8c46874e5f42c2bbe81c549329d604dce0897b1c94961343c8138

thanks

**Comment by kalif4** [comment]
Tengo el mismo problema se quedo sin confirmar y ya va a completar 3 horas y mi billetera es de copay, puede retornar a mi billetera o que se debe hacer.

59b7a63ab00182c43e0d559ea8cc28631aa8e0189138feb7670ccff30424d3fb
![WhatsApp Image 2019-05-15 at 09 19 04](https://user-images.githubusercontent.com/39574708/57796055-114c3d00-770d-11e9-84ae-0ff3c63e6b3e.jpeg)
![WhatsApp Image 2019-05-15 at 09 21 54](https://user-images.githubusercontent.com/39574708/57796057-114c3d00-770d-11e9-95e5-ec511c1c5b2e.jpeg)

**Comment by gabrielbazan7** [comment]
Take a look at this article 

https://support.bitpay.com/hc/en-us/articles/360025484512-Missing-transactions-Why-is-my-transaction-unconfirmed-

**Comment by gabrielbazan7** [comment]
https://www.blockchain.com/btc/unconfirmed-transactions
