### ISSUE TITLE
Bitcoin Balance Locked

### ISSUE THREAD

**Issue by buddilla** [bitpay/copay#9724]
How do I fix a locked bitcoin wallet and for some reason I have 3 payment proposals? These issues started with the new update on iOS. 

ID: c5f9f602-8188-4154-8a15-a8291f3dc887
![Screen Shot 2019-05-15 at 12 33 16 PM](https://user-images.githubusercontent.com/13294167/57803595-a5b69f80-770d-11e9-9fb2-9055e1442131.png)

**Comment by gabrielbazan7** [comment]
You need to remove those unsent transactions to unlock that balance. To do that, click on the transaction and you will see an option to delete it. It seems that you are getting an error when trying to top up your card and the transactions ( already created ) were never broadcasted.

**Comment by buddilla** [comment]
Thank you very much that fixed the issue...
