### ISSUE TITLE
Never received my bitcoin payment 

### ISSUE THREAD

**Issue by cjac1027** [bitpay/copay#9726]
I sent Bitcoin from copay into a forex account 9-10 hours ago but never received the payment

**Comment by cjac1027** [comment]
I the payment to here 31kuy1NSmronk6MvSQmp2FNym53rHnAbPF

This is the transaction ID
fe035e75f80d51e7e9c06b948b661458ffec60d7e8f667b1e2cf63a6c6f981fb

It says 6+ confirmations

**Comment by BGalliotti** [comment]
Hello @cjac1027
Thank you for reaching out to us.

As you can see the payment has been sent to the desired address and it is properly confirmed. 
If the destination address was wrong, unfortunately, there is nothing to do about it as bitcoin transactions are not reversible.
If the address was the right one, please reach Forex, let them know about your case and provide them the transaction ID/Link.

Kind regards.
