### ISSUE TITLE
Passphrase only recovers BTC wallet after device change

### ISSUE THREAD

**Issue by SimonJ802** [bitpay/copay#9727]
Hi, it looks like I've lost access to my BCH wallet (created from the fork) as I upgraded to a new phone. Stupidly I overlooked ensuring I had a passphrase for the BCH wallet because it was automatically created by CoPay. Access to my original BTC wallet was no problem using the pass phrase but I suppose the BCH is unrecoverable now. Looks like it might be a case of easy come easy go ..... unless there is a way to recover it with CoPay somehow?

**Comment by gabrielbazan7** [comment]
Hi Simon. Should work. You choose the correct coin when importing the wallet ( BCH )?  Which error did you get?

**Comment by SimonJ802** [comment]
Hi Gabriel, I went back and yes, there was a BCH option - not sure it was there the first time I did it - maybe going crazy!

Thanks very much for your reply - prompted me to go back a look properly. Much appreciated.
