### ISSUE TITLE
Missing payment 

### ISSUE THREAD

**Issue by rosso7** [bitpay/copay#9728]
I have waited 48 hours in a small transfer. My copay wallet still says "sending" to the transaktion.
Id is 2d2a00ad5907b5f9e188f0efd5f826419c208a698193483d3e10a3b840b67574
What to do?

**Comment by rosso7** [comment]
Now a new one doesent go through 
Id is cae9920e47073dee636c5f86d6dde325f9e82f8a646a10f2f14caa0fe31ff85d

The one above toke 3 days. Whats going on at the moment?

**Comment by micahriggan** [comment]
https://jochen-hoenicke.de/queue/#0,24h

Your tx has a $1.43 fee on it, which seems reasonable, unfortunately the mempool has been spiking

**Comment by rosso7** [comment]
Thanks for your reply
What do you mean by spiking? What is the timeframe do you think?
Regards René Lindgren

lør. 25. maj 2019 20.43 skrev micahriggan <notifications@github.com>:

**Comment by micahriggan** [comment]
As in the number of pending transactions waiting to get into a block increased dramatically very quickly. If you check out the graphs, the fees have risen to 200 sat/byte and your transaction has a fee of 33.7 sat/byte. There's really no way to know how long it will take, but those graphs are a good visualization of where your transaction will be as far as priority for the miners
