### ISSUE TITLE
Still stuck in sending

### ISSUE THREAD

**Issue by brandnews** [bitpay/copay#9737]
I'm transferring funds out of my copay wallet and it's been 11 hours,so far,stuck in sending. Please advise.

**Comment by BGalliotti** [comment]
Hello @brandnews 
Thank you for reaching out to us.

Please check [this](https://github.com/bitpay/copay/issues/8803#issuecomment-398775441) post.

If your issue persists, please send us the transaction ID.


Please let us know if you have any additional questions.
Kind regards.
