### ISSUE TITLE
Question??

### ISSUE THREAD

**Issue by dombouchard** [bitpay/copay#9742]
Hi, I sent BTC from Slushpool to a Copay address i don't have access to anymore (was never properly setup) by mistake. Where are those BTC now? Lost forever or Copay will one day recover these "unclaimed" BTC after a couple of years? If you have a way i can recover these BTC (that i mined myself), please let me know.
Dom

**Comment by BGalliotti** [comment]
Hello @dombouchard 
Thank you for reaching out to us.

> Where are those BTC now?

They should be on the same address as we assume they have remain untouched.

> Lost forever or Copay will one day recover these "unclaimed" BTC after a couple of years? If you have a way i can recover these BTC (that i mined myself), please let me know.

The funds are lost forever (unless you find the recovery phrase of the wallet and recover them).
We do not have access to the funds either to the recovery phrase/private keys of the wallet, we cannot recover them.

Please let us know if you have any additional questions.
Kind regards.
