### ISSUE TITLE
Application doesn’t work 

### ISSUE THREAD

**Issue by Between1stand2nd** [bitpay/copay#9753]
I can see the balance of my accounts for BTC and BCH. However when I tap one of those accounts, nothing happens. I can’t see any transaction details and can’t proceed with “send”, “receive” coins. I have 4 wallets for BTC and 2wallets for BCH. And all of the have the same problem.

**Comment by BGalliotti** [comment]
Hello @Between1stand2nd 
Thank you for reaching out to us.

- **Please send us the BitPay/Copay Wallet ID so we can further investigate and address your inquiry.**

- To get your Wallet ID, open your Copay/BitPay application, then go to `Settings` > [Your wallet] > `More Options` > `Wallet Information`. 
On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste it in your e-mail. 
You can do the same on your computer by clicking on the wallet ID.

**We look forward to hearing from you.**

Kind regards.

**Comment by Between1stand2nd** [comment]
Hi
When I opened Copay a few minutes ago it worked. I don’t know what happened
but I’m glad that the problem was solved.

Thanks

2019年6月14日(金) 3:16 BGalliotti <notifications@github.com>:
