### ISSUE TITLE
Website down, where to download binaries? Copay available on stores

### ISSUE THREAD

**Issue by septagram** [bitpay/copay#9759]
The copay.io URL redirects to this GitHub now. I'd like to download Windows binaries for the latest version. Where can I get them?

**Comment by septagram** [comment]
Okay, so they can be installed from Windows Store (as well as from Mac App Store for Mac and from Snapcraft for Linux). Can you please add a note in README that they are available from those stores?

**Comment by rastajpa** [comment]
Hello! you can check this link to see the latest releases -> https://github.com/bitpay/copay/releases

You can also find the different installers and the source code.
I hope I've helped.

**Comment by septagram** [comment]
Thanks ) Yeah, that's how I figured it out. The thing is IMHO it should be pointed out in the most obvious location -- README, while the website is down.

Speaking of which, what happened?

**Comment by rastajpa** [comment]
We will update the README file soon and consider your suggestion. Thank you!
The website is down at this time because nobody kept the information updated.

**Comment by septagram** [comment]
Alright )
