### ISSUE TITLE
Stuck in sending (again)

### ISSUE THREAD

**Issue by rosso7** [bitpay/copay#9762]
Still waiting on this One
cae9920e47073dee636c5f86d6dde325f9e82f8a646a10f2f14caa0fe31ff85d
What is going on ?

**Comment by BGalliotti** [comment]
Hello @rosso7 
Thank you for reaching out to us.

The transaction is properly confirmed, you can see it [here](https://insight.bitcore.io/#/BTC/mainnet/tx/cae9920e47073dee636c5f86d6dde325f9e82f8a646a10f2f14caa0fe31ff85d).

To learn more about transactions confirmation please refer to #8803 

Kind regards.

**Comment by dehichan** [comment]
ありがとうございます
感謝します

2019年6月14日(金) 3:52 BGalliotti <notifications@github.com>:

**Comment by dehichan** [comment]
申し訳ありません。

copayに送金したのに、
14日くらい受け取れません

確認お願いします

1G3yQLBLtDPbQW8agj4sMRvNnTQMiZ934D

2019年6月14日(金) 3:52 BGalliotti <notifications@github.com>:

**Comment by dehichan** [comment]
申し訳ございません。
copayに送金したのですが、まだ届きません。
確認お願いします。

1G3yQLBLtDPbQW8agj4sMRvNnTQMiZ934D

**Comment by BGalliotti** [comment]
Hello @dehichan 
Thank you for reaching out to us.

We do not speak Japanese, if possible please translate your inquiry to English or Spanish, this will increase your probability of getting answered by the community.

This thread is closed, please open yourself a new one and provide the transaction ID and wallet ID.

- To get your Wallet ID, open your Copay/BitPay application, then go to `Settings` > [Your wallet] > `More Options` > `Wallet Information`. 
On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste it in your e-mail. 
You can do the same on your computer by clicking on the wallet ID.

- The transaction hash / ID is a alphanumeric chain like this: **d0a23876de7cf87574b5cda7557bcc8af5d84f3fd1e6f4c6063fd6b72b0e69ae**

Kind regards.

**Comment by dehichan** [comment]
Hello.
I have sent to copay but I have not received it for more than two weeks.
Verification please.

51ca5d5d-8aa6-41df-b14a-8db5c04b053e


xpub6CadGJiT4rjLyBNB2GpdS6SFUxKVvwsLvUKLmsUgRXmdD6cruZawkpRgmAGHY6peLLaJmVmeSkaNckPfiWrPvoJ7GARWVjSKzxpot33yR1w


2019年7月12日(金) 3:47 BGalliotti <notifications@github.com>:

**Comment by BGalliotti** [comment]
Hello @dehichan 
Thank you for reaching out to us.

Please send us the transaction ID, you should be able to obtain it from the platform you have sent the funds to Copay.

If you do not know how to do that, please reach out to their support service.

We look forward to hearing from you.
Kind regards.
