### ISSUE TITLE
Make the coins available after writing wrong password 

### ISSUE THREAD

**Issue by Akvarella** [bitpay/copay#9770]
I wrote wrong password couple of times by accident and now it’s written that all amount of my wallet’s bitcoins is in “waiting for confirmation condition”. Is it okey? What should I do to make it available again?

**Comment by BGalliotti** [comment]
Hello @Akvarella 
Thank you for reaching out to us.

> I wrote wrong password couple of times by accident and now it’s written that all amount of my wallet’s bitcoins is in “waiting for confirmation condition”. Is it okey? What should I do to make it available again?

We do not quite understand your issue.
Transactions confirmation are totally independent of any password.

If you are still experiencing this issue, please let us know.
Learn more about recovering your wallet here: #9292 

Kind regards.
