### ISSUE TITLE
How can i get my public key address from copay 5.3.1???? 

### ISSUE THREAD

**Issue by Grambo112233** [bitpay/copay#9775]
It seems like this should be very easy to get a public key for multisig  return of funds.  I liked every where and found a extended public key but the multisig box won't take the key?  

Anyone know where or how I can get this public key for my wallet? It is Copay 5.3.1
Thank you

**Comment by matiu** [comment]
Enter the wallet, then Settings (top right), then wallet Information. At the end, there are the extended public key(s) (xpubs).
