### ISSUE TITLE
Los Fondos reflejados son incorrectos y una transaccion no fue confirmada

### ISSUE THREAD

**Issue by Gmlozano** [bitpay/copay#9789]
Buen día, el día de hoy al hacer un envío por error seleccioné la opción  "Envío Máximo" sin embargo no deslicé la opción que da para "enviar pago" ni tampoco confirmé sino que simplemente me devolví en la pantalla (no me llegó ningún mensaje al correo confirmando envio o algo asó)....y volví a hacer el proceso de envio normalmente a la billetera de otra persona (en esta oportunidad deslicé, confirmé el pago y me llegó mensaje a mi correo que habia enviado esa transacción )....Cuando revisé el saldo de BTC no correspondía al valor que debía tener (ejemplo: en un principio tenía 0.05 y el envio que si confirme era por 0.025 por lo cual tendría que tener en el saldo  0.025 pero me aparece 0.005)...

Al revisar las transacciones por Insigght..observo que hay una transacción que no tiene dirección de billetera destino, esta el espacio en blanco pero si tiene un valor y a su lado tiene una "U" verde. Después de esta transacción si aparece la transacción que yo confirme a la dirección de biletera correcta y por el valor correcto., pero tambien tiene una U verde al lado

Finalmente me aparece un letrero rojo que dice "Unconfirmed Transaction" y un señala el valor de las dos transacciones antes mencionadas.

Actualmente en la aplicación de Copay ya no me aparece el registro  de que envié la transacción que aprobé y el saldo sigue estando mal...q debo hacer??....adicional a ello no encuentro copay en la aplicación de google play

**Comment by BGalliotti** [comment]
Hola @Gmlozano 
Gracias por ponerse en contacto con nosotros.

Continúa teniendo este problema?


Esperamos su respuesta.
Saludos cordiales.
