### ISSUE TITLE
Where can I download wallet?

### ISSUE THREAD

**Issue by familiasarta** [bitpay/copay#9794]
I want to download the wallet to PC but I am not finding the link. when I go to copay.io I'm redirected to https://github.com/bitpay/copay and I can not find where to download the software

**Comment by BGalliotti** [comment]
Hello @familiasarta 
Thank you for reaching out to us.

You can download Copay here: https://github.com/bitpay/copay/releases

The mobile version (.apk file) is being released only when there are major changes on the app so you might not always find the latest version for the Android platform.

Kind regards.
