### ISSUE TITLE
Money Gone

### ISSUE THREAD

**Issue by ElectrumDevelopment** [bitpay/copay#9795]
I sent a $10 transaction and I refresh my wallet balance and like there's only $4 left (should have like $90 left). I check the transaction and this is what it shows.

https://insight.bitcore.io/#/BTC/mainnet/tx/d81473c2624e2c56633f280632e4db60c01415e5ac3b4de179f6b3d89e8979ca

**Comment by BGalliotti** [comment]
Hello @ElectrumDevelopment 
Thank you for reaching out to us.

Are you still experiencing the issue?

We look forward to hearing from you.
Kind regards.
