### ISSUE TITLE
Los fondos de la Wallet son inconsistentes

### ISSUE THREAD

**Issue by osmarg** [bitpay/copay#9796]
![Saldo Inconsistente Wallet](https://user-images.githubusercontent.com/51306382/58772177-57165b80-857d-11e9-9e9c-54793db95927.JPG)

El saldo de la wallet es inconsistente. Realice un deposito por 0.511492 BTC y luego realice un retiro por 0.01389 BTC y luego otro retiro por 0,055361 (este ya no se ve reflejado en la wallet), luego de ejecuta la segunda transacción, el saldo de la Wallet volvió a ser el inicial antes de las transacciones realizadas hoy (2 de mayo de 2019), es decir, muestra 0.002061.
Ver la imagen adjunta en la cual se refleja la inconsistencia del saldo.

**Comment by osmarg** [comment]
Ya muestra el saldo correcto y se puede cerrar elcaso. Gracias

**Comment by matiu** [comment]
Gracias. Tuvimos algunos inconsistencias con transactions sin confirmar. Estamos arreglamos esos errores ahora. saludos.
