### ISSUE TITLE
Restore Wallet from iphone 

### ISSUE THREAD

**Issue by mac12345678** [bitpay/copay#9798]
Hi,

Before you answer yes I know I should have written down the 12-word phrase and i may have its finding it thats the issue. 

i have an iPhone with water damage I may be able to recover data but not open the app as the phone as dead.

I do have a local itunes backup that was encrypted so i assumed it would restore my copay data and it would be fine. I have restored the data but it hasn't restored my wallet but has restored user names and passwords for other apps.

Any thoughts on ether extracting the info off a failed iPhone or restoring the data from a locally encrypted itunes backup or am I stuffed are my cypto investments gone.

**Comment by BGalliotti** [comment]
Hello @mac12345678 
Thank you for reaching out to us.

Our wallet does not back up on the iTunes backup, so it should not work.

Please let us know if you have any additional questions.
Kind regards.

**Comment by johnjames333** [comment]
we have developed our own hardware for cracking bitpay/copay wallet password with superfast speed
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333

**Comment by Travis2022** [comment]
@mac12345678 
I have recover similar issue for a copay wallet before
