### ISSUE TITLE
Error 500 Missing Inputs

### ISSUE THREAD

**Issue by osmarg** [bitpay/copay#9799]
![Error 500](https://user-images.githubusercontent.com/51306382/58893121-1883bc80-86b5-11e9-91dd-104aa48ccd26.JPG)
Buen día
Desde ayer 3-Junio-2019 estoy intentando realizar un envío y la aplicación no lo permite muestra "error 500 Missing Inputs". Ver imagen adjunta
Por favor su colaboración con la solución. 
Gracias

**Comment by osmarg** [comment]
![Error Bitcore](https://user-images.githubusercontent.com/51306382/58922283-d764ca00-86ff-11e9-8026-18ff22ca7952.JPG)
La billetera muestra un nuevo error (ver imagen) y muestra una transacción en estado "movido", es decir, en ves de enviado dice movido.

**Comment by matiu** [comment]
Hola, tuvimos un problema con el backend ayer, ya está solucionado, por favor intenta nuevamente.
