### ISSUE TITLE
input derivation path not available (signing transaction)

### ISSUE THREAD

**Issue by rxrob** [bitpay/copay#9803]
I have been getting that error for 4 hours now. my transaction says confirmed but the coin says unspent. what does that even mean...

**Comment by rxrob** [comment]
i just realized that the output address and the input address are both associated with my private key. i some how have accesss to 55 bitcoin that i didnt have orginally. i am very confused. i have been in bitcoin since 2011 and i some how never have run into this issue before. i will see if i can import my private key into another wallet to see if i have accesss to the 55 bitcoin funds.

**Comment by matiu** [comment]
Hi, sorry we had some issues with the backend yesterday, it is fixed already. In case you balance is still incorrect, please "scan address from funds" from the wallet to refresh it.
