### ISSUE TITLE
método de error de bitcore invocado: método abstracto entrada clara firma

### ISSUE THREAD

**Issue by criptotab21** [bitpay/copay#9804]
Tengo un grave error acabo de crear un copay y coloque btc en mi cuenta y no permite sacar dinero de mi copay alguien que me ayude por favor

**Comment by miguel11y** [comment]
Me pasa igual hace 3 horas no he podido enviar un pago

**Comment by criptotab21** [comment]
¿No haz podido solucionar?

**Comment by miguel11y** [comment]
nada amigo y tu ?sabes como resolver ?

**Comment by criptotab21** [comment]
Tampoco primera vez que lo uso y me siento estafado no entiendo tienes tiempo con este tipo de problema?

**Comment by matiu** [comment]
Hola, estoy fue un error en el backend ayer y ya esta arreglado, disculpá los inconvenientes.

**Comment by criptotab21** [comment]
Amigo pero yo tenia 740$ en btc ahora resulta que tengo 7$ porque tengo este tipo de error: Id transacción: c9dcb998d263c7da512a26abdb4ba5fafc2911262e6324e15092bba492a708b5

**Comment by criptotab21** [comment]
Hice una transacción de 240$ y ahora resulta que tengo 7$ y en total deberían quedarme 490$ en btc necesito ayuda

**Comment by matiu** [comment]
@criptotab21 podrías mandarle el address de tu wallet asi lo verifique?

**Comment by criptotab21** [comment]
1bb916e6-7b0c-45f0-a500-eb6fe91e936f

Allí está el Id wallet amigo

**Comment by criptotab21** [comment]
@matiu @matiu

**Comment by matiu** [comment]
@criptotab21  Tenés tres transacciones en tu wallet
una entrante y 2 salientes. el resultante es:
0.00100536 BTC

Sobre cual transcción tenés dudas?

**Comment by criptotab21** [comment]
Quiero saber dónde está el resto de mi dinero tenía 0.09492
 Hice dos transacciones 

Una de: 0.026038

Otra de: 0.00532

Y mi btc entrante fue de 0.94921

Mi pregunta es donde está el resto de mis btc amigo

**Comment by criptotab21** [comment]
@matiu

**Comment by matiu** [comment]
Hola. La entrante fue de:0.03249028 BTC a tu wallet.
c9dcb998d263c7da512a26abdb4ba5fafc2911262e6324e15092bba492a708b5

Si ves la transacción aquí:
https://www.blockchain.com/btc/tx/c9dcb998d263c7da512a26abdb4ba5fafc2911262e6324e15092bba492a708b5

sólo el address 1KeCER9EyoTKLZwW6mziADK8d4ewwmyj6d es el de tu wallet, y ese output es de 
0.03249028 btc.

Puede haberse informado mal el amount de la TX ayer durante el tiempo que estuvo caido nuestor server, pero en la blockchain estan registradas todas las trasacciones.
