### ISSUE TITLE
bitpay issuess unsolved

### ISSUE THREAD

**Issue by humbleking** [bitpay/copay#9807]
please i have funds in my bitpay wallet but  when i tried transferring funds to another wallet it says  input derivation path not available(signing transaction).please can somebody help me

**Comment by rleonardo815** [comment]
Says the same for me last 24 hrs. Help!!!!

**Comment by matiu** [comment]
Hi,

sorry for the inconvenience. This was fixed yesterday. Please see https://status.bitpay.com/
