### ISSUE TITLE
Could not update wallet: 525

### ISSUE THREAD

**Issue by EnchantedSin** [bitpay/copay#9808]
My wallet says scanning funds,  then when I hit the wallet  it just says Tap to Retry and Could Not update wallet: 525.........  what happened to all my bitcoins????

**Comment by EnchantedSin** [comment]
And then when I try to do anything, it says could not save preferences on server: 525

**Comment by timpiee** [comment]
Same, since using this wallet I've only had issues. Not to mention the shit ton of fees

**Comment by gaynell211** [comment]
I have some problem, What I need to do ?

**Comment by Coolspotcreative** [comment]
They currently have a twitter thread open regarding an issue they are working on, but they haven't confirmed what issue it is that they are working on, the tweet says the only thing we can do at this time is to wait for the fix to be issued. 

https://twitter.com/BitPaySupport/status/1136280009742663680

**Comment by matiu** [comment]
Hi,

sorry for the inconvenience. This was fixed yesterday. Please see https://status.bitpay.com/
