### ISSUE TITLE
Problem with account 

### ISSUE THREAD

**Issue by devkode112131** [bitpay/copay#9809]
I added today some money (44$), I sent to another account 20$.... and I’m my account I have 0$ . The money has not sent. So where are my money?
![824EB6A3-99EC-4176-8C55-CA961B50CF50](https://user-images.githubusercontent.com/51412636/58967183-8ccb6800-8768-11e9-9f6b-9241542bf919.png)

**Comment by rleonardo815** [comment]
I’ve had same issue. Something is wrong with the app or server

**Comment by tomasito1** [comment]
i too, help me please ((((

**Comment by MKBTC** [comment]
Same issues here!

**Comment by tomasito1** [comment]
what need doing?

**Comment by devkode112131** [comment]
Copay!!!! Update please because I need the money

**Comment by matiu** [comment]
Hi,

sorry for the inconvenience. This was fixed yesterday. Please see https://status.bitpay.com/
