### ISSUE TITLE
implement "advanced send"

### ISSUE THREAD

**Issue by maraoz** [bitpay/copay#981]
Add "advanced" toggle for Send form.

This should allow the user to:
- choose the unspent outputs (or funding addresses) to use for the transaction.
- set tx fee
- choose change address (?)

**Comment by matiu** [comment]
* Multiple outputs.

**Comment by 21xhipster** [comment]
:+1: We need organize transparent spending, so this feature is essential for us. Especially change address.

**Comment by vitalylvov** [comment]
Agree with @21xhipster. Can you tell when you plan to include this Issue in some Milestone?

**Comment by matiu** [comment]
This is not an high priority now, but we think is important and need to be eventually implemented. If you want to submit a PR, we will be happy to review it.

**Comment by matiu** [comment]
implemented in v1.1.3 (fee level).
multiple outputs: copay can handle now tx with multiple outputs created from somewhere else in BWS.
change address will not be implemented, Copay always generate a new address on outgoing txs.

**Comment by jooray** [comment]
Especially with current fees, setting a custom fee in sat/B would be very useful.

**Comment by junderw** [comment]
@jooray you already can. lol

**Comment by jooray** [comment]
I cannot see this option in the Chrome version of copay. Maybe it is only in some other versions.

**Comment by gabrielbazan7** [comment]
You could see the option in the confirm view.

<img width="398" alt="bitpay_-_secure_bitcoin_wallet" src="https://user-images.githubusercontent.com/10999037/32170476-6fbb36cc-bd53-11e7-89c6-25dbf641173a.png">

<img width="398" alt="bitpay_-_secure_bitcoin_wallet" src="https://user-images.githubusercontent.com/10999037/32170491-7c540bb6-bd53-11e7-9abe-863ae85f8ef7.png">
