### ISSUE TITLE
wallet Copay problems

### ISSUE THREAD

**Issue by salasruizbetiana** [bitpay/copay#9811]
Hello, Today I tried to sent btc and the transacction said Transaction error. After 3 hours my wallet es in cero and said Sacning Founds...525, when I Try to enter say could not aupdate wallet : 525. Please help me

**Comment by tomasito1** [comment]
i too have problems

**Comment by bitalias1** [comment]
me three

**Comment by matiu** [comment]
Hi,

sorry for the inconvenience. This was fixed yesterday. Please see https://status.bitpay.com/
