### ISSUE TITLE
Could not update transaction history

### ISSUE THREAD

**Issue by rubanvi** [bitpay/copay#9815]
Could not update transaction history and send BTC, wallet has problems with network

**Comment by rcastag** [comment]
https://bws.bitpay.com/bws/api/v2/feelevels is down

**Comment by rubanvi** [comment]
Hope it’s a temporary problem.

**Comment by matiu** [comment]
Hi,

sorry for the inconvenience. This was fixed yesterday. Please see https://status.bitpay.com/
