### ISSUE TITLE
Bitpay offline

### ISSUE THREAD

**Issue by jchukwum** [bitpay/copay#9819]
Bitpay server is offline. I'm unable to retrieve my wallet or create a new one (I initially thought it was my old app)

However I'm now certain that https://bws.bitpay.com is down. I'm receiving network error on these requests.

Please bring up the server.  

Thanks

**Comment by matiu** [comment]
Hi,

sorry for the inconvenience. This was fixed yesterday. Please see https://status.bitpay.com/
