### ISSUE TITLE
Wallet Balance

### ISSUE THREAD

**Issue by demarcoa** [bitpay/copay#9821]
I used to have 190$ worth of bitcoin in my copay wallet however when I check now I only have 80 even though I made no transactions. Where is all my money

**Comment by matiu** [comment]
Hello. Can you please let us know the address you had the funds or a
transaccion id?

**Comment by demarcoa** [comment]
This is my wallet id to receive 
16aQTw5dX3vhJaBzmwPAccMUaUxmnFcYwQ

**Comment by demarcoa** [comment]
These are all my transaction ID’s

fe8459645fa7a19b177176449573f915b19803ea596e598682257a030dfa7851

dc02e485d32fa9756767644d8cd207b29d3702b17ce09410693f9bb595215e94

aa18a8ca5ddd3aa2eadf1d283164e4c77d47c0eeaebcac311635b7f8020bd0ee

**Comment by matiu** [comment]
Hi, according to those transactions you moved:
aa18a8ca5ddd3aa2eadf1d283164e4c77d47c0eeaebcac311635b7f8020bd0ee => sent 0.01350463 dc02e485d32fa9756767644d8cd207b29d3702b17ce09410693f9bb595215e94 <= received 0.00440098 btc 
fe8459645fa7a19b177176449573f915b19803ea596e598682257a030dfa7851 <= received 0.01976397 btc 

So, your balance is 0.01061607, which seems to be correct.

**Comment by demarcoa** [comment]
Why does it say this then

**Comment by matiu** [comment]
Hi. Your message is incomplete. Can you send it again?

**Comment by demarcoa** [comment]
This is what my wallet says.

**Comment by matiu** [comment]
ok, thanks.

**Comment by demarcoa** [comment]
So where is my money

**Comment by demarcoa** [comment]
Why did you close it if the problem is still persisting

**Comment by demarcoa** [comment]
I’ll resend the picture again if you look at the email it actually sends

**Comment by matiu** [comment]
Sorry, I am having problems understanding your issue.

Your wallet balance is: 0.01061607 BTC

Do you see that on the app or no?

**Comment by demarcoa** [comment]
yes that is what it says on the app; however, the transaction ID for the bitcoin received on the second deposit is way off. This is what my wallet shows

![IMG_2923](https://user-images.githubusercontent.com/51425834/59043438-39c9e180-884a-11e9-9a2d-42d44a684d18.PNG)

**Comment by matiu** [comment]
thanks. can you try this:

from that page-> go to Wallet PReferences (top right) -> Transaction history -> Clear cache.

**Comment by demarcoa** [comment]
You’re right
