### ISSUE TITLE
Still 0,05 btc missing

### ISSUE THREAD

**Issue by RV9147** [bitpay/copay#9822]
1DkBxzrNgej6YAdj7Ehmy2HuzpkRCKaKYN is the address i received the btc to. For some reason yesterday morning while i could still check my wallet, i noticed the address was changed. Now it's this: 15TAEtKZ3HyvzocB5WTeMPuS5EHQC2qvjc
[Screenshot_20190606-071354](https://user-images.githubusercontent.com/51421877/59006485-e4320c80-882a-11e9-967e-6fac956c46b3.jpg)

**Comment by matiu** [comment]
Hi, the addr https://insight.bitcore.io/#/BTC/mainnet/address/1DkBxzrNgej6YAdj7Ehmy2HuzpkRCKaKYN

have 0 balance, It received a '11826600 SAT' transaction and then your wallet sent a 
'11813563 SAT' transaction to 37C7QXnSFTBKajEn5x4Nfg4HwNQRKazunD. 

As a result, the balance is 0.

**Comment by RV9147** [comment]
But initially i received 0,168266

**Comment by matiu** [comment]
Please check the incoming tx:
https://insight.bitcore.io/#/BTC/mainnet/tx/2530a2de2617add2a2514b1998e075908dfb5c9208c746afec3c266a2242db1e

The amount that was 11813563 SAT

It could have been reported incorrectly previously.

**Comment by RV9147** [comment]
Aight. Thx
