### ISSUE TITLE
522 code issue in co pay wallet

### ISSUE THREAD

**Issue by actadt** [bitpay/copay#9828]
I have a 522 error everytime I go to open co pay waller

**Comment by BGalliotti** [comment]
Hello @actadt 
Thank you for reaching out to us.

Sounds like you are experiencing a server-side issue. 
Are you still experiencing it?

We look forward to hearing from you.
Kind regards.

**Comment by actadt** [comment]
I know have an error 520 missing inputs when I send

**Comment by BGalliotti** [comment]
Hello @actadt 
Thank you for reaching out to us.

- **Please send us the BitPay/Copay Wallet ID and the transaction hash / ID or the link so we can further investigate and address your inquiry.**

- To get your Wallet ID, open your Copay/BitPay application, then go to `Settings` > [Your wallet] > `More Options` > `Wallet Information`. 
On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste it in your e-mail. 
You can do the same on your computer by clicking on the wallet ID.

- The transaction hash / ID is a alphanumeric chain like this: **d0a23876de7cf87574b5cda7557bcc8af5d84f3fd1e6f4c6063fd6b72b0e69ae**

**We look forward to hearing from you.**
