### ISSUE TITLE
Cannot restore wallet from 12 word phrase

### ISSUE THREAD

**Issue by TheSpartanK** [bitpay/copay#9835]
I had a couple of wallets created in a version of copay from sometime in 2017. I saved the 12 word recovery phrases. Today I went into the copay wallet and it's not working, showing 403 errors. Seems like it needs to be updated to work.

I then get my backup phrases from the copay app which match what I had saved 2 years previous, reenter them and everything is OK.

I have installed the latest version of bitpay and particl copay and used the copay recovery tool. Everytime I try to recover any of the wallets in any of those places, it just throws me an error.

1 wallet was normal and the other was a joint one with 2 members. Neither can be recovered

**Comment by BGalliotti** [comment]
Hello @TheSpartanK 
Thank you for reaching out to us.

> I had a couple of wallets created in a version of copay from sometime in 2017. I saved the 12 word recovery phrases. Today I went into the copay wallet and it's not working, showing 403 errors. Seems like it needs to be updated to work.

- What version of Copay is this one?
- What platform?

> I then get my backup phrases from the copay app which match what I had saved 2 years previous, reenter them and everything is OK.

- What version of Copay is this one?
- What platform?

> I have installed the latest version of bitpay and particl copay and used the copay recovery tool. Everytime I try to recover any of the wallets in any of those places, it just throws me an error.

- We have tested Particl Copay and did not work for us on some cases. Please keep in mind Particl Copay is a different software, not necessarily compatible and it's not related to us.
- What error do you get on the recovery tool?

**We also need to know the following:**

- Does your recovery phrase have a password?
- Are you entering a password on the recovery phrase? (*regardless of the previous question answer*)

We look forward to hearing from you.
Kind regards.

**Comment by TheSpartanK** [comment]
What version of Copay is this one? Actually I uninstalled it to reinstall the latest version so I can't find this out
What platform? It's on android.

I do however still have my windows desktop version installed, still holding the shared account. v3.0.6
This version is also showing the same problem - 403 error
I do see a message at the top saying I can download a new version but don't want to lose access to the original if it doesn't work.

We have tested Particl Copay and did not work for us on some cases. Please keep in mind Particl Copay is a different software, not necessarily compatible and it's not related to us. - Can you refer me to the correct app on google play store for android?

Does your recovery phrase have a password? I don't believe so and when I backed up both accounts, I didn't need a passphrase and it completed successfully.
Are you entering a password on the recovery tool? (regardless of the previous question answer) - No I didn't

**Comment by BGalliotti** [comment]
Hello @TheSpartanK 
Thank you for reaching out to us.

Before uninstalling or updating the app please back all the wallets up.

The app is no longer on the PlayStore.
You can find the latest Copay release [here](https://github.com/bitpay/copay/releases/download/v5.4.0/android-release-signed-aligned.apk), please download it, let your device install products for unknown sources (only for this install) and finish the installation.

Find relevant information regarding the error 403 please refer to #9070 
Also, please update your app, it is quite outdated, that might be the cause of the issue.

In regards to the backup phrase password, do not use a phrase password on the recovery tool

Please let us know if you have any additional questions.
Kind regards.

**Comment by nihao10086nihao** [comment]
Hello, I met this problem, too.

But I've solved it.

I can help you.

You can leave your contact information.
你好，我也遇见这个问题。
但是我已经解决了。
我可以帮组你。
你可以留下你的联系方式。

**Comment by nihao10086nihao** [comment]
你好，我遇见过这种问题。我可以帮助你

**Comment by johnjames333** [comment]
@TheSpartanK 
we have developed our own hardware for fixing BITCOIN recovery phrase with superfast speed
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333

**Comment by Travis2022** [comment]
@TheSpartanK 
if you haven't recovered your wallet contact me I can recover it : anywalletrecovery@gmail.com
