### ISSUE TITLE
my wallet has b

### ISSUE THREAD

**Issue by aligbedinero** [bitpay/copay#9844]
my wallet has been hacked and all my btc sent to d below address
 1LxJe3LGiVVoQd4TB7HjyPCzvqVWjXHybP

**Comment by aligbedinero** [comment]
please help
 d btc was sent to the below address with the hashtag 

1LxJe3LGiVVoQd4TB7HjyPCzvqVWjXHybP

6aa72104bf9c14be57788797a4a4cd649c09d4e98c0a310b7eacf65c0f7c4792

**Comment by aligbedinero** [comment]
dadffde4c9d340f5d00af1b8c5df7e559431f0e2

**Comment by aligbedinero** [comment]
Pls I want to take my life get back to me

**Comment by BGalliotti** [comment]
Hello @aligbedinero 
Thank you for reaching out to us.

We are sorry you have had this bad experience.

Here are two chances:

  -  You have sent the funds, maybe accidentally.
  -  Somebody stole your wallet (recovery phrase, private key) or your device/devices where the wallet is installed and has sent the funds.

Unfortunately, there is nothing we can do in this case. Also, a Bitcoin transaction cannot be reversed, so there is no way to recover those funds.

Please make sure your devices are safe and your wallets are secured with password/fingerprint if necessary.

**To secure your wallet, follow these instructions:**

- Open the Copay/BitPay app
- Select the wallet you want to secure with a password
- Tap the upper right corner icon
- Enable **Request Encrypt Password**
- Enter the password and confirm

**To secure your device (the wallet app)**

- Open the Copay/BitPay app
- Tap the gear icon on the upper right corner
- Tap Lock and select the method you want to use (PIN or Fingerprint)

**Note:** to use the fingerprint lock, your device has to support it and it has to be set up, this is done on the system settings and will vary depending on your phone.

- **If you think somebody could have used your wallet, do not use it anymore to receive funds.**

- **If it still has funds, move all the funds to another bitcoin wallet.**


Please let us know if you have any additional questions.
Kind regards.

**Comment by aligbedinero** [comment]
I have all security on my wallet no one gained access to my wallet it was hacked

**Comment by aligbedinero** [comment]
So you guys mean am doomed? There is no way I can retrieve this money or get who is involve in this ?

**Comment by BGalliotti** [comment]
Hello @aligbedinero 
Thank you for reaching out to us.

> So you guys mean am doomed? There is no way I can retrieve this money or get who is involve in this ?

Unfortunately there is no way to do any of those things

Please let us know if you have any additional questions.
Kind regards.

**Comment by Imran144** [comment]
I never believed in bitcoin retrieval cos people around me told me it’s not possible. Sometimes last year I fell for a binary option scam which promised a higher return and I lost close to $90,000 worth of bitcoin, I felt so sad and devastated at the same time and lost all hope. Few months ago I read a lot reviewed on bitcoin site how digital currency had helped them recover there stolen bitcoin, as regards a recovery expert and genius so I contact his via his email digitalcurrency14 @gmail Com, explained my ordeal how I was scammed and he promised to help me get all my bitcoin back to my greatest surprise I got all bitcoins recovered within 48 hours. I don’t know how he got it done, If you've been rubbed of bitcoin reach out to this guy digitalcurrency14 @gmail com he's a life changer!!!

**Comment by Beckyni** [comment]
I had lost some funds due to an airdrop scam too and it fucked me up luckily I got introduced to this hacker who helped me recover what was stolen from me hit him up on telegram::https://t.me/badestha
