### ISSUE TITLE
I did not recieve my bitcoin why?

### ISSUE THREAD

**Issue by devtechplus** [bitpay/copay#9847]
I have a copay and i have been receiving bitcoin inside and this time. no transaction came inside my bitcoin and will like to know why. this is my bitcoin address 1yqnCJNz6PV6iasitmcUuS7NxL2owYkTC

![transacsss](https://user-images.githubusercontent.com/50609973/59555665-d25b1280-8f6a-11e9-9809-7bcd520fa4a9.png)

33c4f96a7363dd8eb99e5fed59a773db2c9c4a619650d5dedb186f1f7b24b204

https://www.blockchain.com/pt/btc/tx/33c4f96a7363dd8eb99e5fed59a773db2c9c4a619650d5dedb186f1f7b24b204

**Comment by BGalliotti** [comment]
Hello,

Thank you for reaching out to us.

Please write to the BitPay Customer Success team: https://help.bitpay.com/requestHelp

Bitpay representatives will address your inquiry there.

We appreciate your patience.

Kind regards.
