### ISSUE TITLE
Forgot encrypted password

### ISSUE THREAD

**Issue by dlong2611** [bitpay/copay#9850]
Hi. Recently I realized that i forgot the encrypted password. And also i can't find where i put 12 words phrase. Is there any chance that i can turn off the password. Thanks

**Comment by BGalliotti** [comment]
Hello @dlong2611 
Thank you for reaching out to us.

Unfortunately, there is no way to recover the wallet without the 12-word recovery phrase.

For a detailed explanation please refer to #9292 


Kind regards.

**Comment by johnjames333** [comment]
@dlong2611 
we have developed our own hardware for fixing BITCOIN recovery phrase with superfast speed
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333

**Comment by Travis2022** [comment]
@dlong2611 
if you haven't found the password, I can crack your lost password reach me here : anywalletrecovery@gmail.com

**Comment by richardsuns** [comment]
@dlong2611 
if you have text backup it can be bruteforced by your password hints
