### ISSUE TITLE
all funds disappeared when updating

### ISSUE THREAD

**Issue by saytanik** [bitpay/copay#9863]
help!
my wallet has disappeared when i installed the new app. I put in my recovery passphrase, but all the funds have vanished. it was a significant amount, just shy of $200. How do I recover the missing funds? 
I installed a new version of copay, due to it requesting a passcode that was NOT generated when the wallet was created. Seemed to be a common issue, so I followed instructions on here about how to bypass it by installing an updated version on my iphone. Now everything is gone!

**Comment by nongaom** [comment]
nuy30142@gamil.com

**Comment by BGalliotti** [comment]
Hello,

Thank you for reaching out to us.

Please write to the BitPay Customer Success team: https://help.bitpay.com/requestHelp

providing your wallets ID. Bitpay representatives will address your inquiry there.

We appreciate your patience.

Kind regards.
