### ISSUE TITLE
Can not restore wallet using 12 word phrase 

### ISSUE THREAD

**Issue by Lillechris83** [bitpay/copay#9868]
I can not restore my wallet using 12 word phrase... Should not be passord protected.

**Comment by BGalliotti** [comment]
Hello @Lillechris83 
Thank you for reaching out to us.

Please refer to #9292 proceed step by step and let us know if you get any errors.

Kind regards.

**Comment by nihao10086nihao** [comment]
Hello, I met this problem, too.

But I've solved it.

I can help you.

You can leave your contact information.
你好，我也遇见这个问题。
但是我已经解决了。
我可以帮组你。
你可以留下你的联系方式。

**Comment by BGalliotti** [comment]
Hello @Lillechris83 

@nihao10086nihao is not part of the Copay development team.

Please **do not share your 12-word recovery phrase with any person you do not closely know and trust** as that is the only thing needed to access to and manage your funds.

Kind regards.

**Comment by nihao10086nihao** [comment]
我也遇见这种问题，我可以帮助你

**Comment by johnjames333** [comment]
@Lillechris83 
we have developed our own hardware for fixing BITCOIN recovery phrase with superfast speed
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333
