### ISSUE TITLE
Unable to recover wallet with 12 word phrase

### ISSUE THREAD

**Issue by helpmerecoverplease** [bitpay/copay#9869]
Hi,

I have a new phone and have been able to recover my BCH wallet but not my BTC wallet despite having the 12 word phrase. I still have the old phone so can hopefully create a new wallet and send to that if necessary, but hoping there’s a better way?

The error message I’m getting says to check the password of the recovery phrase, the derivation path or the wallet service URL. Any help appreciated

**Comment by helpmerecoverplease** [comment]
Closing this as the same 12 words for BCH account worked for BTC...not sure what the other 12 words I had were for!

**Comment by johnjames333** [comment]
@helpmerecoverplease 
we have developed our own hardware for fixing BITCOIN recovery phrase with superfast speed
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333
