### ISSUE TITLE
error: snap "bitpay" not found / Linux installation issue

### ISSUE THREAD

**Issue by clayt0nk** [bitpay/copay#9873]
On Linux / Debian / Buster:

# snap search bitpay
Name    Version  Publisher      Notes  Summary
bitpay  5.9.3    gabrielbitpay  -      A Secure Bitcoin Wallet
copay   5.9.3    gabrielbitpay  -      A Secure Bitcoin Wallet

# snap install bitpay
error: snap "bitpay" not found

**Comment by clayt0nk** [comment]
Same behavior on Ubuntu Xenial

**Comment by gabrielbazan7** [comment]
I tried in my Linux Mint with:
```
snap find bitpay
snap download bitpay
snap ack bitpay_23.assert
snap install bitpay_23.snap
```
And it installs properly

**Comment by clayt0nk** [comment]
$ snap download bitpay
Fetching snap "bitpay"
error: cannot download snap "bitpay": snap not found

I am able to install other snaps, including Brave, cointop, and multiple games. bitpay snap is the only one that exhibits this behavior.

I am in PRC. I just tried to install through a VPN and it worked. It would appear that whoever is running the snap store has bent over for the PRC and is doing geographic blocking. How -- submissive of them.
