### ISSUE TITLE
Im still using copay, need help to next step 

### ISSUE THREAD

**Issue by copuser115** [bitpay/copay#9874]
Hello, im not quite following up on copay, is the copay walle

**Comment by BGalliotti** [comment]
Hello @copuser115 
Thank you for reaching out to us.

We do not understand your inquiry, do you need to download Copay?
If so, Copay is no longer available on Google PlayStore, we will be uploading only major releases of the app to GitHub. You can download it [here](https://github.com/bitpay/copay/releases) (download the .apk file)

If that was not your inquiry, please try to clarify the same.

Kind regards.

**Comment by copuser115** [comment]
Thanks for replying back to me, is everything good now, i qas able to move
my money out,thanks
