### ISSUE TITLE
I have problema with my copay

### ISSUE THREAD

**Issue by blz112231** [bitpay/copay#9883]
I charged today with 50 USD.I sent Money 43 USD. The money was not sent. I have 0 USD . Why? 
![96A63F31-C222-4984-8BC4-BC36FA8D0386](https://user-images.githubusercontent.com/52286941/60271763-9b3a1900-98fb-11e9-9e7a-07cc1c9234a9.png)
![EC8C8AC1-FC1B-46D1-80F3-0C632BDC3ED1](https://user-images.githubusercontent.com/52286941/60271764-9bd2af80-98fb-11e9-9c5f-b8e09e2e4570.png)

**Comment by BGalliotti** [comment]
Hello @blz112231 

Thank you for reaching out to us.
Please write to BitPay Customer Success: https://help.bitpay.com/requestHelp.

We appreciate your patience.
Kind regards.
