### ISSUE TITLE
Cannot type pin. Nothing appears on the screen while typing.

### ISSUE THREAD

**Issue by bitcoinmeetups** [bitpay/copay#9893]
Cannot type pin. Nothing appears on the screen while typing.

Hi,

I am helping a friend. When he types his pin nothing appears on the screen and then he gets the error message to try again in a few minutes. He is sure his pin is correct.

a) Can he keep on trying or is there a limited number of attempts before the app blocks you permanently?

b) Why isn't there any response from the UI when he types in the digits?

c) What is the best course of action?

BM

**Comment by bitcoinmeetups** [comment]
![1561782012288](https://user-images.githubusercontent.com/2834754/60379594-e705d300-9a5f-11e9-86e4-8eb417c25b8c.jpg)

**Comment by gabrielbazan7** [comment]
Hi! there was an issue with the PIN feature that was solved in the current version. Which version of the app are you using?
