### ISSUE TITLE
Problem with address not found

### ISSUE THREAD

**Issue by EstefAlarcon** [bitpay/copay#9911]
My broker sent some funds to my wallet but I don't have any funds transferred to my wallet when I checked the address doesn't match with the current one I just have one wallet, they say they cannot undo the transaction because it was authorized already, they gave me the address, but I don't have a recovery phrase. What should I do in order to get access to this bitcoin address because I want get my money 😔

**Comment by BGalliotti** [comment]
Hello @EstefAlarcon 

Thank you for reaching out to us.

Please write to the BitPay Customer Success team: https://help.bitpay.com/requestHelp

BitPay representatives can address your inquiry there.

We appreciate your patience.

Kind regards.
