### ISSUE TITLE
Can't see incoming btc in wallet.

### ISSUE THREAD

**Issue by spymlk** [bitpay/copay#9933]
Hello. I downloaded copay from apkmonk.com 
And sent some btc into the wallet. 
I can't seem to see the pending transaction in the wallet. 
Do you think i got scammed?

**Comment by BGalliotti** [comment]
Hello @spymlk 

Thank you for reaching out to us.

Please write to the BitPay Customer Success team: https://help.bitpay.com/requestHelp

BitPay representatives can address your inquiry there.

We appreciate your patience.
Kind regards.
