### ISSUE TITLE
Cannot send BTC from Copay wallet.

### ISSUE THREAD

**Issue by JamesNguyenVN** [bitpay/copay#9938]
Dear Sirs,

Today I need to send my BTC to my friend but I cannot send. I use Copay wallet version V5.9.4. I tried to recover by 12 phases ( to both Copay and Bitpay in another phone) but still can not recover. A attached here the screens for that. 
Please help to solve for me and tell me how to send. Thank you so much.
![copay1](https://user-images.githubusercontent.com/17883448/61107655-a6b84300-a4aa-11e9-8832-7a25e8744db6.jpg)
![copay2](https://user-images.githubusercontent.com/17883448/61107668-addf5100-a4aa-11e9-82d5-9015710ba8e1.jpg)

**Comment by flean** [comment]
I'm having the same issue tried with version 6.0.0-beta-1 anvil's version 5.6.6
```
[Log] [debug] Dynamic fee: normal/livenet 56 SAT/B (main.js, line 23241)
[Error] Failed to load resource: the server responded with a status of 400 () (txproposals, line 0)     http://bws.bitpay.com/bws.api/v3/txproposals/
```
TestNet is not creating this issue

**Comment by BGalliotti** [comment]
Hello @JamesNguyenVN 
Thank you for reaching out to us.

Please try again creating the wallet specifying the recovery phrase. Follow the instructions give [here](https://github.com/bitpay/copay/issues/9916#issue-464712495).

Please let us know if you have any additional questions.
Kind regards.

**Comment by walletrescue** [comment]
@flean 
@JamesNguyenVN 
did you recover your wallet? I may help if you need send me gamil  : anywalletrecovery@gmail.com
