### ISSUE TITLE
Import multisig electrum wallet to copay

### ISSUE THREAD

**Issue by brainwashed20** [bitpay/copay#9939]
Hello,

Is possible to import an already created multisig wallet from Electrum wallet to copay ?

Regards,
Alexandru

**Comment by brainwashed20** [comment]
Can you provide an answer to the question above ?

I’m sure that is a feature that many users would benefit from it.

Or let’s put it like this:

Given X xpriv keys and the derivation path, is it possible to import this multisig wallet to copay?

I’m waiting for your answer.

Thanks in advance !

**Comment by BGalliotti** [comment]
Hello @brainwashed20 
Thank you for reaching out to us.

No, as Electrum does not work as BIP 39 to calculate the seed (regardless it uses the same set of words), Electrum seeds are not compatible with other wallets and Copay takes Electrum seeds as no valid.

Please let us know if you have any additional questions.
Kind regards.
