### ISSUE TITLE
Btc Sending Issue

### ISSUE THREAD

**Issue by korhankemik** [bitpay/copay#9963]
Hello,

I just sent 0.25 btc to below address. I saw sent alert but i couldn't see any transaction on my activity list. Please help!!

My Address : 1PiejMqTMYAARUyiZWF1XF4gjGnYrFFv6A
Sent Address : 3QQVTvP69aGFmjd3dFzZsvwGBwM1bW7kEC

**Comment by korhankemik** [comment]
Please help immidiately. My money has gone!

**Comment by korhankemik** [comment]
PLease Help!!!

**Comment by matiu** [comment]
I see there is no transaction on any wallet involving the address 3QQVTvP69aGFmjd3dFzZsvwGBwM1bW7kEC

please contact support@bitpay.com so we can give you more details about your wallet via a private channel.
