### ISSUE TITLE
Transaction Sign Method

### ISSUE THREAD

**Issue by raghwendra21** [bitpay/copay#9964]
How bitpay sign transaction in copay wallet using private key of 2 of users at the time of accept praposal

**Comment by BGalliotti** [comment]
Hello @raghwendra21 
Thank you for reaching out to us.

This is not done simultaneously.

1.  The Copayer 1 generates the payment proposal.
2. The Copayer 2 receives the payment proposal
3. The Copayer 2 approves (or not) the payment proposal.
4. The transaction is created and broadcast.

Please let us know if you have any additional questions.
Kind regards.
