### ISSUE TITLE
problem with transaction

### ISSUE THREAD

**Issue by Albert020287** [bitpay/copay#9981]
5 june 2019 amount  0.572887 btc had come on my copay wallet
when i tried to withdraw it , the amount was blocked. then it faded away 
![Untitled](https://user-images.githubusercontent.com/53168530/61614216-d2d28180-ac6b-11e9-8354-4b5779bb67e9.png)

please give me an answer on my email adress 13hhh@inbox.ru

**Comment by matiu** [comment]
please check the transaction on the blockchain. It could happen the transaction was not confirmed or has a problem indexing.

**Comment by walletrescue** [comment]
@Albert020287 
did you recover your bitcoin if you couldn't i may be able to help just reach me here  : anywalletrecovery@gmail.com
