### ISSUE TITLE
Funds not received

### ISSUE THREAD

**Issue by ljmejia** [bitpay/copay#9996]
I sent to copay 3.5 hours ago. It’s still not received. I sent .0235967
I have transaction ID. I sent at 2:40:35
It’s 5:45. Why don’t you have a support email for Copay?

**Comment by ljmejia** [comment]
Also the Copay wallet is saying Network Error and taking forever to load info.

**Comment by bknght0911** [comment]
I do not want this copay

**Comment by marcelott** [comment]
I have the same issue!

**Comment by BGalliotti** [comment]
Hello 
Thank you for reaching out to us.

@ljmejia 
@bknght0911 
@marcelott 

Please [refresh](https://github.com/bitpay/copay/issues/9886) your wallets and try again.
We have experienced an outage a few hours ago that might have caused this issue.

Please let us know if you have any additional questions.
Kind regards.

**Comment by calimade559** [comment]
I have been waiting two days for my money to get on to my wallet.  I still haven't received nothing or a answer back.. I tried putting $650 on my wallet through the Bitcoin ATM I have the receipt the redemption code and pin. So  what should o do. Please help me.

**Comment by BGalliotti** [comment]
Hello @calimade559 

If you are still experiencing this issue please write to the BitPay Customer Success team: https://help.bitpay.com/requestHelp

Their representatives can address your inquiry there.
Kind regards.

**Comment by walletrescue** [comment]
@ljmejia 
@marcelott 
@bknght0911 
did you receive your coins finally. if you didn't I can help you recover your coins you can find me here : : anywalletrecovery@gmail.com
