### ISSUE TITLE
Getting CORS error

### ISSUE THREAD

**Issue by MonarthS** [bitpay/copay#9997]
It was working properly yesterday, but today I'm getting error that it is blocked by CORS policy.

![Screen Shot 2019-07-23 at 3 59 36 PM](https://user-images.githubusercontent.com/40236229/61705525-88ccc700-ad63-11e9-8479-a99e3de0a53a.png)

**Comment by matiu** [comment]
We experienced a temporary outage that affected our wallet users this morning. We’re sorry for the inconvenience. Our servers are now up and running.
