### ISSUE TITLE
network issue

### ISSUE THREAD

**Issue by marcelott** [bitpay/copay#9998]
Hello Team there is a network Issue. Please help us out!

**Comment by marcelott** [comment]
Hello, I opened the Copay app on my Iphone. But it saying: network issue. Cannot update tx history.

Can some one help?

**Comment by marcelott** [comment]
I have version 5.9.5

**Comment by marcelott** [comment]
What can I do?

**Comment by kashif04444** [comment]
Hi Team i am also facing the same issue network error unable to send or receive BTC

**Comment by Vagab0n** [comment]
I have this problem too.
And now bitpay said my wallet dont exist :o ..

**Comment by matiu** [comment]
We experienced a temporary outage that affected our wallet users this morning. We’re sorry for the inconvenience. Our servers are now up and running.
